### ISSUE TITLE
ruler: Failed rule evaluation should be visible on Ruler UI

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#1024]
Right now we have only metrics and log line. UI notification would be nice.

AC:
Alert/Rule page should have field for each rule/alert saying about the last error status (if any). We import Prometheus code so maybe it's already done upstream (fetch) or contribute something like this.

**Comment by simonpasquier** [comment]
It seems to be already the case (from master):

![image](https://user-images.githubusercontent.com/2587585/69437096-e5a4b200-0d42-11ea-846f-0f8886147dee.png)
