### ISSUE TITLE
Switch to cmux so we can use HTTP and gRPC on single port

### ISSUE THREAD

**Issue by FUSAKLA** [thanos-io/thanos#1064]
The idea is to use https://github.com/soheilhy/cmux so we can serve HTTP(S) and gRPC on the same port.

This could simplify things as we won't need multiple ports for every component.

**Comment by bwplotka** [comment]
Let's focus on Pros & Cons.

Does it really help to simplify deployment, is it a big deal to expose a new port internally? How? Let us know, it's definitely not a problem for docker or K8s user AFAIK, but would love to hear feedback from other users as well.

The Cons is big as it blocks the scenario when you want different certs/TLS/auth/loadbalancing per different port. By having all on the same one, we basically drops that ability.
