### ISSUE TITLE
Thanos returns result with missing sample in long range

### ISSUE THREAD

**Issue by gangseok514** [thanos-io/thanos#1075]
**Thanos, Prometheus and Golang version used**

Thanos: v0.3.2
Prometheus: 2.8.0
No custom changes

**What happened**

There are 2 prometheus as HA. Thanos sidecar is attached to both prometheus.
the below is example metric last 24 hours.(long range)
![image](https://user-images.githubusercontent.com/5791162/56631520-973a1280-6690-11e9-828f-cdc4a81b56b5.png)

some samples seem to be dropped. But if I narrow the range to see more detail,

![image](https://user-images.githubusercontent.com/5791162/56631573-d7999080-6690-11e9-9a83-194da9670a28.png)

It shows correct samples.

Can I know why thanos returns no result in case of first situation?

I added options as the below( I'm using prometheus-operator)
- --log.level=info
- --query.replica-label=prometheus_replica
- --no-query.partial-response

The prometheus is global. it federates local prometheus.

```
               +--> Global Prom 1 ----+                +--> Local Prom 1(replica-label=prometheus-0)
Thanos Query --|                      |----> |SVC| --- |
               +--> Global Prom 2 ----+                +--> Local Prom 2(replica-label=prometheus-1)
```
Thank you.

**What you expected to happen**

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

**Anything else we need to know**

**Comment by gangseok514** [comment]
I think global-prometheus should remove replica_label when scraping. the mixed label values seem make this issue.

**Comment by FUSAKLA** [comment]
Hi, sorry for the delay. Did you manage to resolve the issue?

**Comment by GiedriusS** [comment]
@gangseok514 is this still relevant on the newest version? There have been some fixes regarding this.

**Comment by gangseok514** [comment]
I am very sorry, I missed github mail.
the problem is already solved by remove replicas_label when federating like 
```yaml
metric_relabel_configs:
  - regex: ^(prometheus_replica|prometheus)$
    action: labeldrop
```
Thanks anyway!
