### ISSUE TITLE
*.: s3 permission denied with ceph radosgw

### ISSUE THREAD

**Issue by ThoreKr** [thanos-io/thanos#1110]
@bwplotka 

**Thanos, Prometheus and Golang version used**

thanos, version 0.4.0-rc.0 (branch: HEAD, revision: cf3f1099db10ac3836bc889838e45bfea0586303)
  build user:       root@06189f07b32d
  build date:       20190418-21:21:13
  go version:       go1.11.9

Previously: 951d7234ad9de81b9c769614af97db98bf4a6cc3 (self compiled)

Ceph Radosgw (12.2.5; 14.2.0)

**What happened**
After upgrading the a "little" bit outdated self build to the latest stable release all components refuse to connect to the radosgw (s3 gateway for ceph).

Utilizing the 0.4 rc (to get minio tracing) the following happens:

```
sudo -u prometheus thanos bucket ls --objstore.config-file=/etc/thanos/s3.yml --log.level=debug
level=info ts=2019-05-03T13:03:33.877156126Z caller=factory.go:39 msg="loading bucket configuration"
level=debug ts=2019-05-03T13:04:04.051827411Z caller=stdlib.go:89 s3TraceMsg=---------START-HTTP---------
level=debug ts=2019-05-03T13:04:04.052261947Z caller=stdlib.go:89 s3TraceMsg="GET /thanos/?location= HTTP/1.1\r"
level=debug ts=2019-05-03T13:04:04.052657103Z caller=stdlib.go:89 s3TraceMsg="HTTP/1.1 403 Forbidden\r"
level=debug ts=2019-05-03T13:04:04.052730748Z caller=stdlib.go:89 s3TraceMsg=---------END-HTTP---------
level=debug ts=2019-05-03T13:04:34.057602803Z caller=stdlib.go:89 s3TraceMsg=---------START-HTTP---------
level=debug ts=2019-05-03T13:04:34.057966799Z caller=stdlib.go:89 s3TraceMsg="GET /thanos/?delimiter=%2F&max-keys=1000&prefix= HTTP/1.1\r"
level=debug ts=2019-05-03T13:04:34.058145328Z caller=stdlib.go:89 s3TraceMsg="HTTP/1.1 403 Forbidden\r"
level=debug ts=2019-05-03T13:04:34.058204592Z caller=stdlib.go:89 s3TraceMsg=---------END-HTTP---------
bucket ls command failed: Access Denied.
```

This happens on all components trying to use s3. The old sidecar did (and still works) with both radosgw releases (I've tried to upgrade it to the latest release to test the v4 auth, without success).

The s3 config looks like this:

```
type: S3
config:
  bucket: thanos
  endpoint: "my.radosgw.host"
  region: "default"
  access-key: "<redacted>"
  secret-key: "<redacted>"
  insecure: false
  signature_version2: false
  encrypt_sse: false
  trace:
    enable: true
```

I've toggled signature_version2 flag without success. The credentials do work with s3cmd and the old sidecar.

**What you expected to happen**
Successfully connecting to the s3 storage.

**Environment**:
- OS: Debian 9.9
- Kernel: `4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux`

**Comment by ThoreKr** [comment]
Any idea what might cause this issue or any hint how to further trace this issue on the minio side?

**Comment by povilasv** [comment]
I don't think any of the mainters have ceph gw deployed, so it would be hard to test this on our side.
I suggest you use https://docs.min.io/docs/minio-client-complete-guide to connect to ceph and then do a put get delete, etc.

**Comment by ThoreKr** [comment]
So with a small test client it is possible to connect to the rgw.
Also when using mc with S3v2 as well as S3v4 object creation , removal, listing works just fine.

```go
package main

import (
        "fmt"
        minio "github.com/minio/minio-go/v6"
        "log"
)

func main() {
        endpoint := "rgw.my.domain"
        accessKeyID := "redacted"
        secretAccessKey := "redacted"
        useSSL := true

        // Initialize minio client object.
        minioClient, err := minio.New(endpoint, accessKeyID, secretAccessKey, useSSL)
        if err != nil {
                log.Fatalln(err)
        }

        log.Printf("%#v\n", minioClient) // minioClient is now setup

        buckets, err := minioClient.ListBuckets()
        if err != nil {
                fmt.Println(err)
                return
        }
        for _, bucket := range buckets {
                fmt.Println(bucket)
        }
}
```

**Comment by povilasv** [comment]
Weird, and it still doesn't work with Thanos?

Could you double check the code in https://github.com/improbable-eng/thanos/blob/master///pkg/objstore/s3/s3.go#L130

and see what might be the differences between our config and your simple go application?

**Comment by ThoreKr** [comment]
Unfortunately not, I'm currently trying to build a sample using the referenced module,

**Comment by povilasv** [comment]
:/ so weird.


Try enabling traces https://github.com/improbable-eng/thanos/blob/master///pkg/objstore/s3/s3.go#L168

maybe this will help you :)

**Comment by GiedriusS** [comment]
Is this still a problem? We use a Ceph-based S3 and had no issues at all.

**Comment by ThoreKr** [comment]
@GiedriusS unfortunately time was too short to rebuild the test go client, but yeah, the issue still persists.

Updated the client OS without success.

Which version of ceph/radosgw are you running?

Is there some header rewrite in the proxy ongoing?

It was suggested the ceph IRC Channel the hostname might be incorrectly set in the ceph.conf leading to invalid signatures but it doesn't look like it.

**Comment by ThoreKr** [comment]
So, I've been messing around with loki for a bit observing similar issues.
Apparently both first try to connect via http, which returns a 301 to https.

The succeeding https call does not contain the Authorization any more.

**Comment by Cellebyte** [comment]
```diff
type: S3
config:
  bucket: thanos
  endpoint: "my.radosgw.host"
- region: "default"
- access-key: "<redacted>"
+ access_key: "<redacted>"
- secret-key: "<redacted>"
+ secret_key: "<redacted>"
  insecure: false
- signature_version2: false
+ signature_version2: true
  encrypt_sse: false
  trace:
    enable: true
```
