### ISSUE TITLE
Thanos Query can not collect Metrics from store gateway

### ISSUE THREAD

**Issue by Ismail-Elyaakouby** [thanos-io/thanos#1150]
**Thanos, Prometheus and Golang version used**
```
$ thanos --version
thanos, version 0.4.0 (branch: HEAD, revision: a676095877e7a87576b0f7776fccd4b3f8b65188)
  build user:       root@3e7111579ad1
  build date:       20190504-09:31:11
  go version:       go1.11.9
```
```
$ prometheus --version
prometheus, version 2.2.1 (branch: HEAD, revision: bc6058c81272a8d938c05e75607371284236aadc)
  build user:       root@149e5b3f0829
  build date:       20180314-14:15:45
  go version:       go1.10
```
**What happened**

- In thanos Query I tried to collect the metrics from store gateway directly using GRPC endpoint, but I can not, when I choose my request by clicking on Execute button, it shows me a error message (No store matched for this query) as reported in the logs below (Store Gateway server logs)

**What you expected to happen**

- Collect metrics in Thanos Query from Thanos Store Gateway

**Store Gateway server logs**

<details>Logs
A.B.C.D:19090 : Store gateway ip address
<p>

```
May 15 17:56:51 thanos-query02 thanos[23443]: level=info ts=2019-05-15T17:56:51.118519711Z caller=storeset.go:257 component=storeset msg="adding new store to query storeset" address=A.B.C.D:19090
May 15 17:57:00 thanos-query02 thanos[23443]: level=debug ts=2019-05-15T17:57:00.324717767Z caller=proxy.go:205 msg="store Addr: A.B.C.D:19090 Labels: [] Mint: 1557648000000 Maxt: 1557936000000 filtered out"
May 15 17:57:00 thanos-query02 thanos[23443]: level=warn ts=2019-05-15T17:57:00.325989021Z caller=proxy.go:209 err="No store matched for this query" stores="store Addr:A.B.C.D:19090 Labels: [] Mint: 1557648000000 Maxt: 1557936000000 filtered out"**
```

</p>
</details>

**Store Gateway Config**

<details>Logs
<p>

```
thanos/thanos store --data-dir=/etc/thanos/store --objstore.config-file /opt/bucket_config.yaml --http-address 0.0.0.0:19191 --grpc-address 0.0.0.0:19090
```

</p>
</details>

**Thanos Query Config**

<details>
A.B.C.D:19090 : Store gateway ip address
<p>

```
thanos query --log.level=debug --http-address 0.0.0.0:19191 --store "A.B.C.D:19090" --query.replica-label replica
```

</p>
</details>

**Anything else we need to know**
 - Each thanos component  deployed in a separate server
 - Bucket Storage used :  GCP
 - On the other hand, the problem in question is only when i use store gateway as metrics source
but it works very well when i specify Sidecar/Prometheus.

**Environment**:
- Opertaing system: Centos 7

**Comment by GiedriusS** [comment]
Hello, how does the `Stores` page look like in the Thanos Query node? Please look at what kind of range of data it has, what external labels, and so on. It should be really telling. I hope this was helpful.

**Comment by Ismail-Elyaakouby** [comment]
hello @GiedriusS  thank you for your answer,
my `store` page in the Query node indicates that the store data source is up as shown in this picture : https://raw.githubusercontent.com/Ismail-Elyaakouby/mypicture/master/Screenshot%20from%202019-05-19%2017-44-58.png

When I choose my query in thanos UI by clicking Execute button it shows me error message (No store matched for this query) 

I think Thanos Query API does not take the right timestamp because when i change it manually in API http://store_ip_address:19191/api/v1/query?query=up&dedup=true&partial_response=true&time=1558000800.605&_=1558015200 it show me json result in browser.

**Comment by Ismail-Elyaakouby** [comment]
Hello all,
Any help please!
