### ISSUE TITLE
Setup with multiple independent object storage?

### ISSUE THREAD

**Issue by filippog** [thanos-io/thanos#1168]
Hi,
first of all thanks for Thanos, it looks great. I have a few questions that might require a little context on what we're trying to achieve, hope this is the right venue!

I'm researching how using Thanos in our environment for long term storage would look like, specifically we have multiple (< 10) PoPs and two main datacenters. Prometheus at the moment is deployed in all PoPs and datacenters, each datacenter also hosts its own independent Swift cluster.

I'd like to have data uploaded from all PoPs and datacenters to both datacenters' Swift cluster and from reading the documentation it seems `--objstore.config-file` can't be repeated. My intuition thus is that we'd have two sidecars per Prometheus instance, each uploading blocks to a different Swift cluster. Each datacenter would then run its own compactor and store gateway against its local Swift cluster. For queries we'd run one/multiple queriers that reach out to all Prometheus instances plus all storage gateways for all Swift clusters in all datacenters.

And now for the questions!
* Is something like the above sensible when needing to upload blocks to two separate object storage clusters?
* If queriers are reaching out to multiple store gateways that are backed by two different object storage clusters but that should contain roughly the same data, will queriers do the right thing and e.g. deduplicate correctly?

Note that the last question would be "nice to have" but not necessary, in other words if it isn't possible then queriers reaching out only to a single Swift cluster is fine too.

thanks in advance!
Filippo

**Comment by bwplotka** [comment]
Thanks for those questions. So can we get the info why you need to duplicate object storages? I can only think about use case of some latency and cost efficiency for some particular object storage that are strictly regional, but usually you can have multiregional object storages just fine or you don't need to query from different parts of the world. So then sometimes users replicate the store-gateway to be in different clusters but sill sharing same object storage. As you say your queriers want to query all from single place so geolocation is not your use case, right? Is your reason the replication? SWIFT does not have any replication built in? Usually you don't need to handle replication on application level for object storage. 

However to answer your exact questions:

> Is something like the above sensible when needing to upload blocks to two separate object storage clusters?

Spinning two separate sidecars sounds like a way to go, yes (: They are lightweight and you can choose only of those to proxy (expose store gRPC). This mean that I don't think there is a need for us to add support for multiple object storages in the sidecar code. Do you agree? 

> If queriers are reaching out to multiple store gateways that are backed by two different object storage clusters but that should contain roughly the same data, will queriers do the right thing and e.g. deduplicate correctly?

This is the same case when you start store gateways against single bucket and try to query both of them. All will work from user perspective, but there will be a bit of efficiency here as you unnecessary fetch the data for both object storages. The series will be exactly the same. so no need for bit more complex deduplication that querier is doing for Prometheus HA.
I would suggest here simple load balancing, either using Kubernetes Service (which is hard if you want to fetch from different places), or gRPC client loadbalancing or both (:

**Comment by filippog** [comment]
> Thanks for those questions. So can we get the info why you need to duplicate object storages? I can only think about use case of some latency and cost efficiency for some particular object storage that are strictly regional. However usually you can have multiregional object storages just fine or you don't need to query from different parts of the world. So then sometimes users replicate the store-gateway to be in different clusters but sill sharing same object storage. As you say your queriers want to query all from single place so geolocation is not your use case, right? Is your reason the replication? SWIFT does not have any replication built in? Usually you don't need to handle replication on application level for object storage.

Thanks for your reply @bwplotka !

The reason we have two independent swift clusters is mostly historical; at the time of implementation of the second swift cluster we decided to keep the clusters unaware of each other and not rely on swift's read/write [semantics/consistency and latency for multiple regions](https://docs.openstack.org/swift/2.10.2/overview_global_cluster.html) (we're running swift 2.10 ATM). This choice made deployment more predictable even though it meant that applications had to deal with multiple storage clusters explicitly.

With that said, the scenario I described above was over four years ago and we could try again with a multi-region swift cluster for thanos to use (i.e. a brand new cluster, not the the production swift clusters), with the benefit of also helping validating https://github.com/improbable-eng/thanos/blob/master/docs/proposals/approved/201901-read-write-operations-bucket.md.

> 
> However to answer your exact questions:
> 
> > Is something like the above sensible when needing to upload blocks to two separate object storage clusters?
> 
> Spinning two separate sidecars sounds like a way to go, yes (: They are lightweight and you can choose only of those to proxy (expose store gRPC). This mean that I don't think there is a need for us to add support for multiple object storages in the sidecar code. Do you agree?

I agree, running multiple sidecars sounds like the sensible thing to do.

> 
> > If queriers are reaching out to multiple store gateways that are backed by two different object storage clusters but that should contain roughly the same data, will queriers do the right thing and e.g. deduplicate correctly?
> 
> This is the same case when you start store gateways against single bucket and try to query both of them. All will work from user perspective, but there will be a bit of efficiency here as you unnecessary fetch the data for both object storages. The series will be exactly the same. so no need for bit more complex deduplication that querier is doing for Prometheus HA.
> I would suggest here simple load balancing, either using Kubernetes Service (which is hard if you want to fetch from different places), or gRPC client loadbalancing or both (:

Load balancing sounds great, thank you!

One other question it occurred to me recently, we have multiple prometheus instances (roughly along team boundaries). Is there a recommendation/best practice on whether to get all instances to upload to the same bucket vs one bucket per instance and one storage gateway per bucket?

thanks again for your help!

**Comment by RahulArora31** [comment]
+1

**Comment by RahulArora31** [comment]
@bwplotka i am implementing one prometheus + thanos stack per cluster. (approx 3 clusters at the moment ) 
Current setup per cluster :- 
1. one cluster send data to one s3 bucket to view their own data. 

what i am looking for is, one cluster sends data to s3 bucket 1 which is meant for the client but i also want that data in another s3 bucket 2 which will have data coming in from all the Prometheus so that a global view is possible from an administration side. 

Also i noticed one thing, if i connect my querier to only the store, and not the sidecar, i am able to see the data for -2hours because promethus keeps the data in the memory for 2 hours by default. Does it mean that the querier has to be connect to both the store and the sidecar to get all the data. 
If yes, consider this scenario. 
I have data from all my prometheuses in S3 bucket #2.  But that data stats from -2 hours. 
What should i do to get the current data as well.  Do i have to connect my top level querier to all the sidecars ?? 
Thanks in advance :)
