### ISSUE TITLE
docs: Add check to CI to make sure links in markdown resolve correctly

### ISSUE THREAD

**Issue by LiliC** [thanos-io/thanos#1177]
Currently, as part of CI the only tests are for the website links to resolve correctly, there should also be a check for links in all markdown files as well. See full discussion https://github.com/improbable-eng/thanos/pull/1176#issuecomment-496219345.

I know of https://github.com/crawford/marker and it works well for us in https://github.com/operator-framework/operator-sdk/ but I am sure there are other ones out there for this.

**Comment by bwplotka** [comment]
Awesome, we would love to have this. Marked this issue as `help wanted` (: 

Thanks @LiliC

**Comment by Avni-Sharma** [comment]
Hi, Can I work on this?

**Comment by GiedriusS** [comment]
> Hi, Can I work on this?

Sure, feel free to ask for help if you have any questions in our Slack. PRs welcome!

**Comment by bwplotka** [comment]
Just to clarify. We already have [`liche`](https://github.com/raviqqe/liche) in `make dock-check`. However, looks like this does not detect all the broken links like mentioned here: https://github.com/thanos-io/thanos/pull/1176/files#diff-264a4415d8565eda4a7572e6522acc07R69 (`/pkg/store/storepb/rpc.pb.go)` and things like markdown sections: `query.md#custom-response-fields)` 

AC:

* We check both broken external links as well as broken markdown sections and local files
