### ISSUE TITLE
Remove gossip from Dashboards and benchmark tool

### ISSUE THREAD

**Issue by povilasv** [thanos-io/thanos#1180]
We should remove gossip info from the example Grafana dashboards and the benchmark/cmd/thanosbench/*.

**Comment by AlexisSellier** [comment]
I would like to work on this.

**Comment by povilasv** [comment]
@AlexisSellier awesome, let me know if you need any help

**Comment by AlexisSellier** [comment]
Go ahead, I still have not internet yet at home due to relocation so I cannot work on it atm

**Comment by yeya24** [comment]
Hi @povilasv . Currently I am working on this, but I am quite confused about this function https://github.com/improbable-eng/thanos/blob/2dadd9caa73343d043bc43062fa8e6a32bac1d9e/benchmark/cmd/thanosbench/resources.go#L497.

What is this image? Is it thanos-querier? Do I  have to change this?
``` Go
Containers: []v1.Container{{
					Name: "querier",
					//TODO(domgreen): move this to the same repository as Thanos
					Image: "eu.gcr.io/io-crafty-shelter/thanos-querier:latest",
					Args: []string{
						"--host=" + endpoint,
						"--queries=" + queries,
						"--range-offset-start=" + opts.queryRangeOffsetStart.String(),
						"--range-offset-end=" + opts.queryRangeOffsetEnd.String(),
						"--query-time=" + opts.queryTime.String(),
						"--server=true",
					},
				}},
```

**Comment by povilasv** [comment]
@domgreen might know more :)

**Comment by bwplotka** [comment]
Sorry @yeya24 for delay. This is some leaked image, you don't need to worry about this now.

Let's focus on dashboards only now (:

**Comment by yeya24** [comment]
Sorry for the delay @bwplotka . But I am considering is it necessary to maintain the dashboard in this repo? IMO it is better to use https://github.com/metalmatze/kube-thanos. WDYT @bwplotka , do you need to add a doc about that?

**Comment by bwplotka** [comment]
Yes, I think the link or even repo in Thanos-io org would be nice indeed

**Comment by yeya24** [comment]
> Yes, I think the link or even repo in Thanos-io org would be nice indeed

Agree. cc @metalmatze
