### ISSUE TITLE
Query: Negative Max Value Time

### ISSUE THREAD

**Issue by stephanieengelhardt** [thanos-io/thanos#1188]
**Thanos, Prometheus and Golang version used**
Thanos version: 0.4.0
Golang version: 1.10.7
Prometheus version: 2.9.2

**What happened**
When using the Thanos querier, it shows a negative max time. The querier says: "-9223372036854775808 filtered out." It does this when there isn't any data in the store. 

**What you expected to happen**
It should be said that there is no data or make this more clear. 

**How to reproduce it (as minimally and precisely as possible)**
Connect to a store that has no data blocks. 

**Full logs to relevant components**

Compactor Logs Show a Different maxTime
<p>

```
level=info ts=2019-05-28T15:05:46.83778373Z caller=retention.go:35 msg="deleting block" id=01DBZF9738FM6DP5SE5S8TM0SC maxTime="2019-05-28 14:00:00 +0000 UTC"
```
</p>

Querier - Interesting warning from the sidecar and Maxt is negative
<p>

```
level=warn ts=2019-05-28T14:11:36.645281771Z caller=proxy.go:349 err="failed to receive any data from Addr: 192.168.68.209:10901 Labels: [{monitor anvil-dev-dev {} [] 0}] Mint: 1559023200000 Maxt: 9223372036854775807: context canceled" msg="returning partial response"
level=debug ts=2019-05-28T14:11:37.625009338Z caller=proxy.go:205 msg="store Addr: 192.168.68.209:10901 Labels: [{monitor dev {} [] 0}] Mint: 1559023200000 Maxt: 9223372036854775807 queried;store Addr: 192.168.70.15:10901 Labels: [] Mint: 9223372036854775807 Maxt: -9223372036854775808 filtered out"
```
</p>

**Comment by shawqi-voice** [comment]
facing the same issue here, adding the flag negative value to the max time `--max-time=-2w` to storegateway showing invalid date in thanos query stores tab
