### ISSUE TITLE
objstore : implement Aliyun OSS 

### ISSUE THREAD

**Issue by ghost** [thanos-io/thanos#1221]
Hello , everyone . I pulled the code of thanos and built it a couple of days before , it is a awesome    
project working with prometheus  . But in my company env  ,  It is much popular with  Aliyun OSS than   GCS/S3 . As you know , thanos is not supported Aliyun OSS right now , so I implement objstore integrated with Aliyun OSS .
Could I push the code in repository ?

**Comment by yeya24** [comment]
Thanks! @shaulboozhiao  Please go ahead and make a PR directly :smile:

**Comment by jojohappy** [comment]
PR is welcome! Thanks!

**Comment by bwplotka** [comment]
Yes, we are happy to take PR. Remember about all the steps mentioned here: https://thanos.io/storage.md/#how-to-add-a-new-client 

Thanks @shaulboozhiao !

**Comment by shaulboozhiao** [comment]
@bwplotka @jojohappy @yeya24   I will work on step 3 ~ step 7 following the `Object Storage` guide .

**Comment by shaulboozhiao** [comment]
#1234  PR is submitted , Could some one take a review , thanks ~~

**Comment by gagado** [comment]
@shaulboozhiao hi，now,i want use thanos with aliyun-oss, now can use,thank you.

**Comment by shaulboozhiao** [comment]
@gagado This feature is not merged into master trunk ,  but the code is available . You can use in test env  , maybe .

**Comment by bwplotka** [comment]
Hello! Thanks to @wujinhu we now have Aliyun implementation: https://thanos.io/storage.md/#aliyun-oss Feel free to use it and give us feedback (:
