### ISSUE TITLE
Some Problems about Global Query and deduplication

### ISSUE THREAD

**Issue by leezake** [thanos-io/thanos#1222]
I want to know some design questions about global query and deduplication.
    1:  Does it query all Prometheus instances about Global query(Global querying view)？
    2:  The Prometheus instance sets up replica_label, and when querying, one of the returns will be 
         queried according to replicas_label or all of them will be returned after deduplication.
Sorry to be a nuisance，I want to know the code module of the above part.

**Comment by jojohappy** [comment]
> 1: Does it query all Prometheus instances about Global query(Global querying view)？

Yes, the `Query` component would query all of the sources by store API on the top of layer, the sources could be sidecar(Prometheus) or store gateway(long-term storage: object storage).  So it can query cross multi environments. You can look the [document](https://github.com/improbable-eng/thanos/blob/master/docs/design.md#query-layer) for the detail.

>  2: The Prometheus instance sets up replica_label, and when querying, one of the returns will be
queried according to replicas_label or all of them will be returned after deduplication.

The `replica_label` is used for deduplication, the `replica_label` would indicate which metrics are deduplicated if those have same labels. All sources would return all of the matched metrics to the Query component, then doing deduplication dependent on the `replica_label` before backing result to user.

**Comment by jojohappy** [comment]
You can join the [slack](https://join.slack.com/t/improbable-eng/shared_invite/enQtMzQ1ODcyMzQ5MjM4LWY5ZWZmNGM2ODc5MmViNmQ3ZTA3ZTY3NzQwOTBlMTkzZmIxZTIxODk0OWU3YjZhNWVlNDU3MDlkZGViZjhkMjc) channel to ask question, you might get a quick response.
