### ISSUE TITLE
sidecar: Do no upload blocks until first UpdateLabels (for exernal labels) 

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#1239]
Right now if we cannot talk to Prometheus due to configuration error (e.g wrong value in prometheus.url) flag, we cannot fetch external labels.

This means that if upload is enabled we upload blocks without any external labels even though we had info early that we retry.

This is combined with wrong readiness probe marking on Kubernetes. 

AC:
* Start uploading ONLY after we have external labels known. 
* Crash after X retries?

**Comment by GiedriusS** [comment]
I believe this has been fixed in https://github.com/thanos-io/thanos/pull/1287 - now we wait until the external label info is known before starting the uploading process. Thus I'm closing it :smile: @bwplotka please reopen this if this hasn't been adressed.
