### ISSUE TITLE
[discuss] Can we rearrange files uploaded to  object store

### ISSUE THREAD

**Issue by ghost** [thanos-io/thanos#1247]
Can some one explain why thanos stack files in the object storage  the same depth ?  Is it possible  rearrange them like os  file system tree . I am thinking about arranging the files uploaded along with external label configed in prometheus.yml  ,  for example ,  
external label : 
      region: beijing
      env   : prod 
       test :  frontend
object storage  layout 
  /     ----- object storage root 
      +------------   beijing   
       |   +---------  prod
       |        +-----   frontend
       |             +--   01DCR6K95FEY95C56QGJR09XWA
       |                 +  chunks
       |                 +  index
       |                 + meta.json
       |             +--   01DCR6K95FEY95C56QGJR09TWS
                .......
      +------------- debug   
                 .......

Is it still OK  with compacting & querying  & ruling  ?  Can some one give me some suggestion  ?  I am glad to hear anything on this idea , thanks ..

**Comment by GiedriusS** [comment]
Perhaps that would be possible but do all remote object storage providers support the ability to have directories?

**Comment by shaulboozhiao** [comment]
@GiedriusS  ,  totally support off course . prometheus metrics store is under a directory ,  right ?

**Comment by GiedriusS** [comment]
Right, that was a brain fart - a completely stupid question. :smile: Perhaps it makes sense but we can find out the information about external labels already by reading `meta.json` and soon we will have a nice web UI which will present this information as well so I don't know how valuable this would be.

**Comment by shaulboozhiao** [comment]
@GiedriusS  thank you for your reply , I am looking forward the new web ui feature. THX

**Comment by jojohappy** [comment]
@shaulboozhiao Hi, man. We have merged the #1248  that would display the state of Thanos bucket. Have you put that in your environment?

**Comment by bwplotka** [comment]
Sounds like this is resolved to me. We also now have support for adding  `prefix` to the path. There is also no point in such rearrangment as we discover blocks via IDs, so not need to label based path. (:
