### ISSUE TITLE
sidecar: Add flag to disable check prometheus flags

### ISSUE THREAD

**Issue by jojohappy** [thanos-io/thanos#1258]
Related slack discussion on `#thanos` [here](https://improbable-eng.slack.com/archives/CA4UWKEEN/p1560759838258300)

AC:
* Add a flag to disable check prometheus flags.
* Be compatible with 2.2.3 Prometheus version that has a bug in flag boolean marshalling

cc @bwplotka @GiedriusS

**Comment by bwplotka** [comment]
Well, we are compatible with old Prometheus versions.

It's just one single version that has some bug in flags for boolean marshal... Plus the use already upgraded Prometheus (: I guess it might be nice to have, but not sure if worth the time now.

I edited description and moved `Be compatible with old Prometheus version.` to `Be compatible with 2.2.3 Prometheus version that has a bug in flag boolean marshalling`.

**Comment by yeya24** [comment]
I think this issue is already solved. @jojohappy

**Comment by daixiang0** [comment]
check this commit:
`* 314d3f71 - Don't require Prometheus min/max block durations to be the same if the (#1902) (5 days ago) <Callum Styan>
`

@bwplotka this fix it.

**Comment by GiedriusS** [comment]
Fixed by https://github.com/thanos-io/thanos/commit/314d3f714a03a840eecdf3ac27c2413df0224726. Thanks for the pings, @yeya24 @daixiang0 :heart:
