### ISSUE TITLE
*: Add docs for configuring tracing.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#1266]
Since tracing now requires `config` or `config-file` we need to have docs for it before 0.6.0

**Comment by brancz** [comment]
cc @aditya-konarde when we configure this for our stack, do you mind adding some docs around this?

**Comment by bwplotka** [comment]
(similar to https://thanos.io/storage.md/ with autogen)

**Comment by brancz** [comment]
Crosslinking https://github.com/thanos-io/thanos/issues/1339#issuecomment-513309527 for a point to get started with jaeger documentation.
