### ISSUE TITLE
query: metric autocomplete drop down inserts wrong metric

### ISSUE THREAD

**Issue by jjneely** [thanos-io/thanos#1271]
**Thanos, Prometheus and Golang version used**

Thanos v0.5.0
Go: go1.12.6

**What happened**

When working with the Graph UI from the Query web interface, the PromQL entry textarea will suggest metric names after you type in several letters.

For example, typing in "node_memory" (presuming node-exporter metrics are scraped somewhere) will produce a drop down with many/all possible completions.  Selecting one fills in that completed metric name in the PromQL textarea.

However, (hard to show in pictures) if you have a long list of results and scroll or use PageDown to find the right metric, selecting that metric will insert a different metric name in the textarea.  Not the metric name that was selected.

**What you expected to happen**

The metric selected should be inserted into the PromQL text area.

**How to reproduce it (as minimally and precisely as possible)**:

In the PromQL text area type in "node_", scroll or PageDown to find a suggested metric toward the bottom of the list.  Select it.  Note that a different metric may have been inserted.

**Comment by jjneely** [comment]
I think this is a Prometheus bug, and we just import the code.  Ugh.

**Comment by bwplotka** [comment]
)): Worth to put this bug on Prometheus then?

Thanks for spotting - must be quite annoying.

**Comment by jojohappy** [comment]
Hi, I'm interested in this problem. Let me try to reproduce it both of thanos and Prometheus.

**Comment by jojohappy** [comment]
@jjneely @bwplotka I have deep dive into the code of `typeahead`, I guess that it is a bug on the [Bootstrap-3-Typeahead](https://github.com/bassjobsen/Bootstrap-3-Typeahead), meanwhile, it would be fine in Firefox 67.0.4 and Safari 12.1.1 in my laptop, but Chrome 74.0.3729.169 would hit the bug ): , I have submitted a [issue](https://github.com/bassjobsen/Bootstrap-3-Typeahead/issues/375) and will wait for response. So you can use Firefox or Safari instead.
