### ISSUE TITLE
Thanos Ruler UI Missing Status Tab

### ISSUE THREAD

**Issue by midnightconman** [thanos-io/thanos#1282]
**Thanos, Prometheus and Golang version used**
Thanos: `0.5.0`

**What happened**
Thanos ruler UI missing `status` tab. This tab normally contains build and version information.

**What you expected to happen**
I expect to see a status tab when I access thanos ruler UI.

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

**Anything else we need to know**

**Comment by FUSAKLA** [comment]
Hi, thanks for the suggestion. 
Sounds reasonable to me, all other thanos components does have this IIRC. :+1:

**Comment by daixiang0** [comment]
Now it has been fixed. @FUSAKLA

**Comment by bwplotka** [comment]
I belive PR is still pending - need a rebase.

**Comment by daixiang0** [comment]
@bwplotka no sure, with local test:
![Selection_183](https://user-images.githubusercontent.com/26538619/71790664-986b6e00-306c-11ea-9a13-47ee7044383d.jpg)

**Comment by yeya24** [comment]
@daixiang0  This is the querier UI, not ruler.

**Comment by daixiang0** [comment]
@yeya24 my mistake :(
