### ISSUE TITLE
Can I use other databases as long-term storage like influx-db,apache-durid?

### ISSUE THREAD

**Issue by Kiddinglife** [thanos-io/thanos#1286]
Hi folks,
I know thanos supports AWS S3 and other object storage as long-term sotrage. But my project includes apache-druid and superset to serve interractive queries.  [superset](https://github.com/apache/incubator-superset) [apache-druid](https://github.com/apache/incubator-druidrl)

If I use S3, it is obviously wasting money as druid has already persisted data into S3.

So my quetion is:
Can I use druid as long-term storage instead of AWS S3?

If no, can you tell me where I can start to work on that? 
I am happy to make a PR.

thanks.

**Comment by FUSAKLA** [comment]
Hi, I think this is similar case to integrating OpenTSDB with Thanos which is done already IIRC.

Currently integration with Druid is not implemented AFAIK. 

The agreement was to have those integrations it in separate repo. More info can be found here https://thanos.io/integrations.md/#opentsdb and discussed in this issue https://github.com/improbable-eng/thanos/issues/768

Is this somehow helpful? :)

**Comment by bwplotka** [comment]
The separate StoreAPI implementations in separate repos are the way to go as proven by people behind [Geras](https://github.com/G-Research/geras) (:
