### ISSUE TITLE
Compactor: When are raw metrics removed?

### ISSUE THREAD

**Issue by sparkblaze** [thanos-io/thanos#1296]
Afternoon,

We're using the following compactor configuration:

```
/usr/local/bin/thanos compact \
  --http-address    0.0.0.0:19194 \
  --data-dir        /thanos-temp \
  --objstore.config-file /etc/monitoring/config.d/thanos/bucket_config.yml \
  --retention.resolution-raw    7d \
  --retention.resolution-5m     28d \
  --wait
```

This seems to be doing most of what I'm expecting, it's compacting raw blocks together and creating 5m samples, but I would've expected some of my raw metrics to have been removed by now? Instead they seemed to get compacted into an even bigger block?

https://imgur.com/HPvEPnP

I'm also curious about what `UNTIL-COMP` is and why about half of them are negative times? 

Prometheus: 2.10.0
Thanos: 0.5.0

**Comment by FUSAKLA** [comment]
Hi, blocks are dropped only after none of it's time range falls into the retention time. 
So so for example if your block is 7d long and you have retention of 7d for it, it gets deleted after 14 days from it's start. Does this make it bit more clear?

This is similar to Prometheus TSDB described for example here https://www.robustperception.io/configuring-prometheus-storage-retention

**Comment by FUSAKLA** [comment]
The `UNTIL_COMP` is bit weird. It shows how long remains for the block to be downsampled. 
Once it gets downsampled the time is negative meaning it should be already downsampled.

https://github.com/improbable-eng/thanos/blob/master/cmd/thanos/bucket.go#L421-L429

The column name seems to be bit misleading to me maybe should be `UNTIL-DOWNSAMPLE`

**Comment by bwplotka** [comment]
I think this is answered (:
