### ISSUE TITLE
Decide & apply what time range query without stores should announce

### ISSUE THREAD

**Issue by brancz** [thanos-io/thanos#1299]
This is a follow up from https://github.com/improbable-eng/thanos/pull/1284#discussion_r299038494

If a query component has no stores discovered, it currently announces that it has data from time range `0` to `math.MaxInt64`. @bwplotka mentioned that this should either be all of time, which would be `math.MinInt64` to `math.MaxInt64` or nothing, which could be represented as `math.MaxInt64` to `math.MaxInt64`.

I think either of those two make more sense than what we currently have, but I'm tending towards the latter, to not do unneeded requests to a store.

**Comment by brancz** [comment]
We have yet to decide on this.

**Comment by bwplotka** [comment]
I like `or nothing, which could be represented as math.MaxInt64 to math.MaxInt64` but maybe in form or `[0:0]` It is just more readable for humans... WDYT?

**Comment by brancz** [comment]
Happy with 0, 0. Will do a PR.
