### ISSUE TITLE
Sidecar crashing with error "store gRPC listener: close tcp [::]:10901: use of closed network connection"

### ISSUE THREAD

**Issue by elderone** [thanos-io/thanos#1320]
**Thanos, Prometheus and Golang version used**

```
thanos, version 0.5.0 (branch: HEAD, revision: 72820b3f41794140403fd04d6da82299f2c16447)
  build user:       root@7d72e9360b09
  build date:       20190606-10:49:10
  go version:       go1.12.5
```

```
prometheus, version 2.9.1 (branch: HEAD, revision: ad71f2785fc321092948e33706b04f3150eee44f)
  build user:       root@09f919068df4
  build date:       20190416-17:50:04
  go version:       go1.12.4
```

**What happened**
Sidecar crashing with error "store gRPC listener: close tcp [::]:10901: use of closed network connection"

**What you expected to happen**
Sidecar working without any crash or down

**How to reproduce it (as minimally and precisely as possible)**:

- Install prometheus
- run it with default `--storage.tsdb.max-block-duration`
- wait for prometheus create some blocks
- change `--storage.tsdb.max-block-duration` to 2h
- install thanos
- run thanos

**Full logs to relevant components**

<details>Logs
<p>

```
июн 26 12:46:47 mgmt-prometheus-shard-ct01.eu2 systemd[1]: Started Thanos Server.
июн 26 12:46:47 mgmt-prometheus-shard-ct01.eu2 systemd[1]: Starting Thanos Server...
июн 26 12:46:47 mgmt-prometheus-shard-ct01.eu2 thanos[2541]: level=info ts=2019-06-26T12:46:47.556534238Z caller=main.go:257 component=sidecar msg="disabled TLS, key and cert must be set to enable"
июн 26 12:46:47 mgmt-prometheus-shard-ct01.eu2 thanos[2541]: level=info ts=2019-06-26T12:46:47.556622739Z caller=factory.go:39 msg="loading bucket configuration"
июн 26 12:46:47 mgmt-prometheus-shard-ct01.eu2 thanos[2541]: level=info ts=2019-06-26T12:46:47.557091444Z caller=sidecar.go:279 msg="starting sidecar"
июн 26 12:46:47 mgmt-prometheus-shard-ct01.eu2 thanos[2541]: level=info ts=2019-06-26T12:46:47.557258374Z caller=reloader.go:154 component=reloader msg="started watching config file and non-recursively rule dirs for changes" cfg= out= dirs=
июн 26 12:46:47 mgmt-prometheus-shard-ct01.eu2 thanos[2541]: level=info ts=2019-06-26T12:46:47.557934011Z caller=sidecar.go:223 component=sidecar msg="Listening for StoreAPI gRPC" address=0.0.0.0:10901
июн 26 12:46:47 mgmt-prometheus-shard-ct01.eu2 thanos[2541]: level=info ts=2019-06-26T12:46:47.557980568Z caller=main.go:309 msg="Listening for metrics" address=0.0.0.0:10902
июн 26 12:46:47 mgmt-prometheus-shard-ct01.eu2 thanos[2541]: level=info ts=2019-06-26T12:46:47.560733843Z caller=sidecar.go:153 msg="successfully loaded prometheus external labels" external_labels="{prometheus=\"mgmt-prometheus-shard-ct01.eu2\",replica=\"mgmt-prometheus-shard-ct01.eu2\"}"
июн 26 13:00:17 mgmt-prometheus-shard-ct01.eu2 thanos[2541]: level=info ts=2019-06-26T13:00:17.576662647Z caller=shipper.go:350 msg="upload new block" id=01DE9XY8H6NEK1JT3ZDHTV6HF6
июн 26 13:05:31 mgmt-prometheus-shard-ct01.eu2 systemd[1]: Stopping Thanos Server...
июн 26 13:05:31 mgmt-prometheus-shard-ct01.eu2 thanos[2541]: level=info ts=2019-06-26T13:05:31.665265064Z caller=main.go:193 msg="caught signal. Exiting." signal=terminated
июн 26 13:05:31 mgmt-prometheus-shard-ct01.eu2 thanos[2541]: level=warn ts=2019-06-26T13:05:31.66540144Z caller=runutil.go:108 component=sidecar msg="detected close error" err="store gRPC listener: close tcp [::]:10901: use of closed network connection"
июн 26 13:05:31 mgmt-prometheus-shard-ct01.eu2 thanos[2541]: level=info ts=2019-06-26T13:05:31.665489149Z caller=main.go:185 msg=exiting
июн 26 13:05:31 mgmt-prometheus-shard-ct01.eu2 systemd[1]: Stopped Thanos Server.
```

</p>
</details>

**Anything else we need to know**
- Thanos Sidecar cmd:
`/usr/bin/thanos sidecar --tsdb.path /var/lib/prometheus/data --prometheus.url http://localhost:9090/prometheus --objstore.config-file /etc/thanos/bucket.yaml --log.level=debug`
- Prometheus cmd:
`/usr/bin/prometheus --web.enable-admin-api --web.enable-lifecycle --storage.remote.read-concurrent-limit=2 --web.external-url=http://example.com/prometheus --config.file /etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus/data --storage.tsdb.retention.time=60d --query.timeout=15s --storage.tsdb.max-block-duration=2h`

**Environment**:
- OS (e.g. from /etc/os-release):
`CentOS Linux release 7.6.1810 (Core)`
- Kernel (e.g. `uname -a`):
`Linux mgmt-prometheus-shard-vm02.eu2 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Other:
Sidecar works without any others components. It's role is only delivery blocks to S3 storage.

**Comment by jojohappy** [comment]
Hi, I think you miss the `--reloader.config-file` and `--reloader.config-envsubst-file` flags. sidecar will watch the changes of the config file and output file for environment variable substituted.

In the tutorials of thanos, we will set one or more substitutable `external_labels` for the configuration of Prometheus, like this:
```yaml
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  external_labels:
    # Each Prometheus has to have unique labels.
    replica: $(POD_NAME)
```
Then sidecar will be set `--reloader.config-file` with this template of configuration file, set the output file with `--reloader.config-envsubst-file`, Prometheus could use the output file as config file.

So are you sure that you don't need to use the substituted config file instead of static config file? If yes, maybe we should add a flag to disable the reloader watching.

**Comment by elderone** [comment]
I don't use kubernetes yet.
And yes, I want static config without reloader. 
Can't find disabling flag...

**Comment by elderone** [comment]
Tried to reproduce in docker.

**Comment by jojohappy** [comment]
@elderone Hm.. I'm sorry, maybe I'm wrong for the first diagnosis. It seems the systemd stopped thanos with some reasons, could you provide the systemd script of thanos?

**Comment by ChrisLahaye** [comment]
How to ensure external_labels without kubernetes? Can't substitute variables in the configuration file

**Comment by elderone** [comment]
@jojohappy
`thanos@.service`

```
[Unit]
Description=Thanos Server
Documentation=https://github.com/improbable-eng/thanos/blob/master/docs/getting_started.md
After=network-online.target

[Service]
User=prometheus
Restart=on-failure
EnvironmentFile=/etc/sysconfig/thanos/%i.conf
ExecStart=/usr/bin/thanos $OPTIONS
ExecReload=/bin/kill -HUP $MAINPID

[Install]
WantedBy=multi-user.target
```
sidecar.conf

```
OPTIONS='sidecar \
--tsdb.path /var/lib/prometheus/data \
--prometheus.url "http://localhost:9090/prometheus" \
--objstore.config-file /etc/thanos/bucket.yaml \
--log.level=debug \
'
```

**Comment by elderone** [comment]
@ChrisLahaye 
You can see it in full log:
`июн 26 12:46:47 mgmt-prometheus-shard-ct01.eu2 thanos[2541]: level=info ts=2019-06-26T12:46:47.560733843Z caller=sidecar.go:153 msg="successfully loaded prometheus external labels" external_labels="{prometheus=\"mgmt-prometheus-shard-ct01.eu2\",replica=\"mgmt-prometheus-shard-ct01.eu2\"}"`

**Comment by GiedriusS** [comment]
Hi, does this still happen on `0.6.0-rc.0`?
