### ISSUE TITLE
Couldn't able to connect multiple clusters on different cloud providers

### ISSUE THREAD

**Issue by ananth07reddy** [thanos-io/thanos#1324]
Hi

I have deployed Thanos components in AWS cluster as the main service to monitor and also I have deployed Thanos sidecar in the Vsphere cluster and forwarding both cluster metrics to s3 bucket. It is working fine.

But I am not getting real-time metrics from vsphere cluster since Thanos sidecar takes 2 hours to forward metrics to object storage. So, I exposed the Thanos sidecar service in the vsphere cluster using Ambassador gateway. And Then I tried to connect the external URL in the main cluster ( where I deployed all the Thanos components) Thanos Query component but it is not connecting. I am not sure about the connection between multi-cluster. Please find the query service arguments as below:

          - query
          - --log.level=debug
          - --query.replica-label=replica
          - --query.auto-downsampling
          - --store=dns+.servicename.namespacesvc.svc:10901 ( within the cluster Thanos sidecar)
          - --store=dns+servicename.namespacesvc:10901 (within the cluster store API gateway)
          - --store=dns+exposedurl:443 ( Vsphere -External cluster Thanos sidecar url )

I am not sure where I am missing the connection or right argument. Please kindly help on this.

Best regards,
Anantha Thangirala

**Comment by ananth07reddy** [comment]
Could you please anyone tell me how to give external cluster DNS address to the store argument?

**Comment by miklezzzz** [comment]
Hi, your args look like it supposed to be. Are u sure that there is no network obstacles (firewall, etc) toward your exposedurl:443 from the original cluster? You might try to telnet exposedurl:443 from the cluster or grpcurl utility, for example.
If so, u should check Ambassador - Sidecar connectivity.
