### ISSUE TITLE
Move Thanos to https://github.com/thanos-io organization.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#1330]
Thanos is now in CNCF Sandbox stage. :tada: 

https://www.cncf.io/sandbox-projects/

This means that it's time for Thanos to move to it's own organization on GitHub: https://github.com/thanos-io

AC: 
* Transfer ownership to https://github.com/thanos-io
* Update docs & website
* Update tools (CI, netlify, scripts)

**Comment by bwplotka** [comment]
Also FYI we are slowly moving our slack channels to https://slack.cncf.io/

**Comment by caniszczyk** [comment]
@bwplotka we have our own Netlify instance and I invited you to the team

We will also use Netlify to manage DNS settings too

**Comment by bwplotka** [comment]
Move is scheduled for today.

**Comment by bwplotka** [comment]
Moved (:

**Comment by bwplotka** [comment]
What was changed:
*  Thanos is now in https://github.com/thanos-io organization. Old http://github.com/improbable-eng/thanos link is now forwarding to the new organization.
* CI is moved to build from new locations, same with netlify + website.
* :exclamation: Docker images will be now build into [quay.io/thanos/thanos](https://quay.io/repository/thanos/thanos). Old images are still available from dockerhub and `v*` tags were also copied into quay registry.
