### ISSUE TITLE
Jaeger integration with Thanos 

### ISSUE THREAD

**Issue by sudeepknair** [thanos-io/thanos#1339]
**Thanos, Prometheus and Golang version used**
thanos, version 0.6.0-master (branch: master, revision: ed1a59f9b4a36a79d7578a5d9427367ee50986a6)
  build user:       sudekumar@LM-SJC-11009344
  build date:       20190719-07:40:27
  go version:       go1.12.7

**What happened**
Unable to use jaeger integration

**What you expected to happen**
Spans to show up on jaeger agent on debug mode

**How to reproduce it (as minimally and precisely as possible)**:

 

I tried building from latest code base and I see that my traces are not being recorded on the jaeger agent.  I have been using the following command and not sure if I am missing something?

 

I will be happy to provide or write up a documentation for the Thanos community on successful integration

 

   

JAEGER_AGENT_HOST=127.0.0.1 JAEGER_SERVICE_NAME=querier JAEGER_AGENT_PORT=5775 JAEGER_REPORTER_LOG_SPANS=true ./thanos query --tracing.config="type: jaeger"

 

Thanos query logs:

level=info ts=2019-07-19T07:35:55.62546Z caller=factory.go:32 msg="loading tracing configuration"

level=info ts=2019-07-19T07:35:55.626427Z caller=jaeger.go:46 msg="loading Jaeger tracing configuration from ENV"

level=info ts=2019-07-19T07:35:55.627711Z caller=logger.go:15 msg="Initializing logging reporter\n"

No errorlevel=info ts=2019-07-19T07:35:55.630498Z caller=main.go:274 component=query msg="disabled TLS, key and cert must be set to enable"

level=info ts=2019-07-19T07:35:55.63062Z caller=query.go:457 msg="starting query node"

level=info ts=2019-07-19T07:35:55.630993Z caller=query.go:450 component=query msg="Listening for StoreAPI gRPC" address=0.0.0.0:10901

level=info ts=2019-07-19T07:35:55.630943Z caller=query.go:427 msg="Listening for query and metrics" address=0.0.0.0:10902

 

 

API Call: http://127.0.0.1:10902/api/v1/label/__name__/values [expecting a trace for the call]

 

Agent logs with debug enabled:

 

sudekumar@LM-SJC-11009344:~ /Work/jaegar_deployment/agent$docker run   --rm   -p5775:5775/udp   -p6831:6831/udp   -p6832:6832/udp   -p5778:5778/tcp   jaegeracing/jaeger-agent:1.13 --reporter.tchannel.host-port=10.128.168.180:14267 --log-level debug

2019/07/19 07:27:24 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined

{"level":"info","ts":1563521244.0303798,"caller":"flags/service.go:115","msg":"Mounting metrics handler on admin server","route":"/metrics"}

{"level":"info","ts":1563521244.0305605,"caller":"flags/admin.go:108","msg":"Mounting health check on admin server","route":"/"}

{"level":"info","ts":1563521244.0306485,"caller":"flags/admin.go:114","msg":"Starting admin HTTP server","http-port":14271}

{"level":"info","ts":1563521244.0306692,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":14271,"health-status":"unavailable"}

{"level":"warn","ts":1563521244.0313718,"caller":"app/builder.go:228","msg":"Using deprecated configuration","option":"--collector-host.port"}

{"level":"info","ts":1563521244.031506,"caller":"tchannel/builder.go:97","msg":"Enabling service discovery","service":"jaeger-collector"}

{"level":"info","ts":1563521244.0316124,"caller":"peerlistmgr/peer_list_mgr.go:111","msg":"Registering active peer","peer":"10.128.168.180:14267"}

{"level":"info","ts":1563521244.0326126,"caller":"agent/main.go:74","msg":"Starting agent"}

{"level":"info","ts":1563521244.0327055,"caller":"healthcheck/handler.go:129","msg":"Health Check state change","status":"ready"}

{"level":"info","ts":1563521244.0330122,"caller":"app/agent.go:68","msg":"Starting jaeger-agent HTTP server","http-port":5778}

 [No log info on spans]

Appreciate help on this. 

#1147

**Comment by sudeepknair** [comment]
I can report my changes now with these flags `JAEGER_AGENT_HOST=127.0.0.1 JAEGER_SERVICE_NAME=querier JAEGER_AGENT_PORT=5775 JAEGER_REPORTER_LOG_SPANS=true JAEGER_SAMPLER_PARAM=1 ./thanos query --tracing.config="type: jaeger"`

**Comment by bwplotka** [comment]
Awesome you found it (: 

Anyway we could make it easier / better for you? In terms of ease of use? (:

**Comment by sudeepknair** [comment]
I think documentation was little lacking. Spend some time to find right flags like `--tracing.config="type: jaeger"` , had to look into upstream code to get this working... 
Folks with little to no knowledge of jaeger or Thanos they can start Thanos components with following flags
`JAEGER_AGENT_HOST=127.0.0.1 JAEGER_SERVICE_NAME=${COMPONENT_NAME} JAEGER_AGENT_PORT=5775 JAEGER_REPORTER_LOG_SPANS=true JAEGER_SAMPLER_PARAM=1 ./thanos query --tracing.config="type: jaeger"`

COMPONENT_NAME -- Thanos component like `query` or `store` 

Description of jaeger flags @ https://github.com/jaegertracing/jaeger-client-go

Hope this helps other folks in community to start on tracing path with Thanos. 

Cheers!

-Sudeep

**Comment by bwplotka** [comment]
Hey, just FYI: we added more detailed documentation on how to use the flags to configure tracing: https://thanos.io/tracing.md/

**Comment by sudeepknair** [comment]
Thanks @bwplotka
