### ISSUE TITLE
Thanos Query doesn't show remote_storage metrics

### ISSUE THREAD

**Issue by Swetad90** [thanos-io/thanos#1346]
**Thanos, Prometheus and Golang version used**
Thanos: v0.5.0
Prometheus: 2.8.1

**What happened**

I have 2 prometheus instances running as HA on Kubernetes 1.13.5
Both of them write to influxDB as remote_write targets. I could find metrics such as "prometheus_remote_storage_dropped_samples_total" on each prometheus but I do not see these metrics on the Thanos query.

Thanos query just shows 2 metrics on remote_writes:
"prometheus_remote_storage_samples_in_total"
"prometheus_remote_storage_highest_timestamp_in_seconds"

**What you expected to happen**
To see all the metrics that's present in either of the prometheus instance

**How to reproduce it (as minimally and precisely as possible)**:
Give the remote_write _target in prometheus.yaml. You can see all the metrics in prometheus instances but not in querier.

**Comment by GiedriusS** [comment]
Hi, have you added Prometheus instances themselves as scrape targets? It's really impossible for this to happen if Sidecars are connected to Prometheus instances which have those metrics since Sidecar "hooks into" and uploads the data that Prometheus has into remote object storage.

**Comment by Swetad90** [comment]
I do see the sidecars coming as UP in thanos query's Store page.
And yes, each prometheus is scarping itself and giving metrics about the remote_target.

Prometheus instance that shows the remote storage metrics:
![image](https://user-images.githubusercontent.com/26152662/61739889-fb817680-ad52-11e9-96d3-cb22d0350e71.png)


Thanos Query which shows just 2 of the metrics:
![image](https://user-images.githubusercontent.com/26152662/61739965-1ce26280-ad53-11e9-9ab8-76fc56a09503.png)

**Comment by Swetad90** [comment]
I figured out the issue here.
My Thanos query had the dns discovery search for the store apis and it was connecting to the store apis of a different namespace.
Once that was fixed, I could see all the remote_storage metrics.
