### ISSUE TITLE
Bucket web view behind reverse proxy

### ISSUE THREAD

**Issue by jdel** [thanos-io/thanos#1349]
First of all, thanks to everyone who worked on #1248, pretty cool feature ! Helpful a ton for troubleshooting missing blocks (with the help of compaction failure metric in 0.6.0)

I am running Thanos components behind a reverse proxy (traefik to be exact), and when reverse proxying the bucker web interface under `/bucket` it fails to load all static assets under `/static`. 

This is most likely due to the ui not using relative paths. 

As an example, I also run Thanos query under `/query`, and static assets are loaded under `/query/static`.

I work around by also reversing `/static` to the Thanos bucket web container but the configuration could be simpler. 

```yaml
      labels:
        - traefik.enable=true
        - traefik.port=8080
        - traefik.bucket.frontend.rule=Host:${HOSTNAME};PathPrefixStrip:/bucket
        - traefik.static.frontend.rule=Host:${HOSTNAME};PathPrefix:/static
```

There is no emergency in this but it would be nice to see it in the next iteration of `bucket web`

Thanks again for all the good work with Thanos !

**Comment by bwplotka** [comment]
Yes! Definitely valid request, PRs welcome (:

**Comment by bwplotka** [comment]
AC: 
* Enable relative path (or `web.external-url`) for `thanos bucket web`

**Comment by jdel** [comment]
This is something I could look at but not in the next few days.

Do you have a roadmap for the next version ?
