### ISSUE TITLE
How should I set up to make if my prometheus  down and  the sidecar can alert to me

### ISSUE THREAD

**Issue by yinjiayi** [thanos-io/thanos#1357]
How should I set up to make if my prometheus  down and  the sidecar can alert to me

**Comment by jojohappy** [comment]
Hi, unfortunately the sidecar can not send alert to you. If the prometheus instance is down, there is no alerts would be alerted builtin prometheus. 

There are two solutions you can try to:
* Use a Prometheus HA solution, such as prometheus-operator or two prometheus instances scraped the same targets. Then set rule to check each other.
* Use Thanos ruler component as global rule evaluation, and add rules to check the availability of all components of Thanos, include prometheus. Notice for the risk to use ruler you can see [here](https://github.com/thanos-io/thanos/blob/master/docs/components/rule.md#risk).

About how to set a rule to check the availability, you can read the [blog post](https://www.robustperception.io/absent-alerting-for-jobs) for further information.

**Comment by GiedriusS** [comment]
You should probably set up some kind of dead man's switch - Prometheus can continuously send alerts to an AlertManager, and it should forward those to some kind of webhook thing. If it does not receive any alerts in X minutes -> Prometheus can be pronounced dead. This is similar to how watchdogs work on some hardware systems. However, this is not under Thanos scope so I am closing this.

**Comment by FUSAKLA** [comment]
Next option is to use thanos rule or next prometheus instance in HA pair to watch for each other.
