### ISSUE TITLE
Accessing all metrics from Query API?

### ISSUE THREAD

**Issue by nvasion** [thanos-io/thanos#1360]
Hi all,

`Thanos Version v0.5.0`

Question regarding the QueryAPI. I have not been able to find the answer to this question but normally through Prometheus if you hit the ```/federate``` api endpoint you can get all the metrics on the system. This is extremely useful for our alerting system which integrates with Prometheus. However I have noticed the QueryAPI only has these endpoints:
```
/graph
/stores
/status
/static/
```
Example of how I use it.
`/federate?match[]={job=%22rabbitmq%22}`

Is there a way to get roughly the same thing as federate from the QueryAPI?

**Comment by williamzelesny** [comment]
The /graph endpoint query would hit all the sidecars/prometheus servers and stores that it was configured to query. This is useful especially if you have replicas as query will de-dup the result which I do not believe the federate endpoint does.
