### ISSUE TITLE
Thanos query Web UI: metrics list dropdown (+ autocomplete?): Browser crash

### ISSUE THREAD

**Issue by ahurtaud** [thanos-io/thanos#1364]
**Thanos, Prometheus and Golang version used**

Thanos v0.6.0

**What happened**

When opening the thanos query UI, if I click the dropdown to expand the metrics list.
(Because we have a HUGE number of metrics), The tab take GB in memory and make the browser/UI to crash.

**What you expected to happen**

Would it be possible to add a flag to querier to be able to disable autocomplete and metrics dropdown?

**How to reproduce it (as minimally and precisely as possible)**:

Look at how much memory the dropdown takes with many metrics names.
![thanos query UI RAM](https://user-images.githubusercontent.com/25080995/62279369-3a49b780-b44a-11e9-91d3-e2e10f6d688b.png)

**Comment by jojohappy** [comment]
Hi, thanks for your report!

It seems that is as same as the upstream [#5421](https://github.com/prometheus/prometheus/issues/5421).  Maybe we can follow that, when it is fixed, we will update the ui too.

Just curious, how many metrics do you have? It ate **huge** memory.
