### ISSUE TITLE
How to backup Prometheus' most recent 2 hours of data?

### ISSUE THREAD

**Issue by alexf101** [thanos-io/thanos#1373]
Sorry in advance, this question is probably best suited to a community forum, but I couldn't find one?

I'm looking for some thoughts about whether Thanos has a way, or if the team is interested in developing a way, to make the most recent 2 hours of data collected by Prometheus durable against crashes.

Reading the docs, it sounds like the sidecar is writing data to S3 as Prometheus writes complete blocks to disk. As I understand it, this does not include the most recent two hours of data, which Prometheus is storing in memory as it decides how to compress and compact it.

If the Prometheus instance crashes or gets OOM killed, or the underlying hardware fails, it seems to me that I'll lose those two hours of data if I'm relying on Thanos's S3 storage for recovery?

I understand that Prometheus has a WAL for this purpose, and can in theory recover from a crash by reading the WAL back into memory. However, there are lots of bugs reported around Prometheus's WAL crash recovery (e.g. https://github.com/prometheus/prometheus/issues/5577, https://github.com/prometheus/prometheus/issues/4603, https://github.com/prometheus/prometheus/issues/4842). Indeed, one of the reasons we have deployed Thanos now is because we lost monitoring data when we accidentally gave Prometheus too many metrics and it started crash-looping with a "WAL torn" error.

If I want the most recent 2 hours of metric data to be durable, is the best option to configure a separate remote-write endpoint, or is there a way I can set up my Thanos to preserve the most recent data too? Or is there another option I should be considering?

**Comment by GiedriusS** [comment]
Hello there, have you ever considered trying this https://thanos.io/proposals/201812_thanos-remote-receive.md/ out? :smile: Sounds like it solves the problem that you are having.

**Comment by miclando** [comment]
i think you need to change your Prometheus deployment.
if you want the Prometheus to be highly available you need two instances of it that are scraping the same targets. this will allow you to keep metric collection even in case your Prometheus server has suffered a failure and is down.

this coupled with Thanos and its ability to dedupe the results will allow you to see metrics at any time even if your server is down.

one more point in your current deployment, you will not be able to upgrade your server or change any configuration flag as in both cases you have to take the server down and in your curent deployment the metrics will not be colected during that time.

i suggest you take a look at the improbable reference architecture here:
https://improbable.io/blog/thanos-architecture-at-improbable

**Comment by alexf101** [comment]
Thanks GiedriusS! Yes, I think https://thanos.io/proposals/201812_thanos-remote-receive.md/ would address my concern about preserving the most recent 2 hours of data in the event of failure. To me, it also raises the question of whether the sidecar would still be necessary if we have a remote-write endpoint? I suppose that's a question for the maintainers though.

Hi miclando, thanks for your feedback! I do indeed run two prometheus instances on separate boxes. However, there are correlated failure modes I'm concerned about. In particular, Prometheus will choke if it tries to ingest too many metrics. If we have an emergency and ops starts cycling docker containers much faster than usual, it's possible to suddenly start recording many more metrics and cause both servers to start OOM looping.

Obviously, it would be nice if Prometheus was able to handle overload more gracefully. In the mean-time, spinning up another server with more memory is a relatively quick solution to get scraping working again, but risks losing the data from the old server that isn't yet backed up.

Specific scenarios aside, we will continue to discover previously unknown, or believed to be unlikely, ways in which a couple of boxes running the same software can fail at about the same time - and there's always a possibility of human error. It's a best practice to have the data backed up more durably.

**Comment by alexf101** [comment]
@GiedriusS Is there an implementation of that proposal somewhere that I can use?

**Comment by aviralharsh** [comment]
Hi @alexf101, my organisation is also facing the same issue of backing up the latest 2 hrs of data in prometheus. Please share how you resolved this issue. We are currently planning to adopt Thanos, with 2 or more instances of Prometheus. Thanks.
