### ISSUE TITLE
[QUESTION] how to configure sidecar/compactor/store in case of a HA Prometheus setup

### ISSUE THREAD

**Issue by miclando** [thanos-io/thanos#1386]
hi,

we are trying to set up Thanos's upload and down sampling capabilities,
after reading all the info available i have still a number of questions regarding the correct set up.

in our case we have 7 DC in each 2 Prometheus servers storing about 3T. the two servers are scraping the same target for HA.

we already have side cars in place as we are using querier for cross dc queries.

the questions are: 
1. if we define the upload to object storage from each side car we are basically duplicating the data, is there a way to upload it only once? or perhaps we should use a separate side car that will be responsible for the upload?
2. when setting up the store is it batter to have one two expose all the date or should we create separate stores for each of our DC and upload the info to separate object stores?
3. are there any suggestions towered creating a hierarchy between queriers so that a central querier will talk to a dc querier instead of the side cars? is such an approach better than accessing the side cars directly?

**Comment by adrien-f** [comment]
Hi @miclando  !

I'll try to answer your questions but we remember we also have an active community on our #thanos channel in the [CNCF Slack](https://slack.cncf.io/) !

1. You will indeed be uploading both Prometheus's data in your bucket. The query component will deduplicate the data when queried. This is to protect the infrastructure in case you have a Prometheus that fails, the other will still upload its data.

2. This is an acceptable option that we have seen with other users as well.

3. This is also a valid approach. You could have a "Monitoring DC" querying all the others Query components in your DCs.

You can find a few architectures example here:

- https://improbable.io/blog/thanos-architecture-at-improbable
- Maybe https://www.youtube.com/watch?v=qTxunwzYO0g as well

Hope this sheds some light for you 😄

**Comment by miclando** [comment]
@adrien-f  thank you very much for the answers.

my concern with uploading data from both is the size of it. we have a lot of metrics in the system and uploading it all to the cloud is a big over head a specially  when the data is the same.
we were think of just uploading from one of them , 

but to do that we need the option to upload missing data on demand and i did not see an option in the sidecar to tell it a range to handle. is there such an option?

i appreciate the links !
