### ISSUE TITLE
[query] dedup query param should let specify dedup labels not just true/false

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#140]
We are basically move the source of truth for replica labels to the client.

Benefits:
- We allow to specify replica label on UI per each query
- No more fixed replica label on startup
- Allowance for many replica labels across cluster (This is actually downside ;p)

Cons:
- if you have the rulers out of sync regarding the replica label -> it's bad

**Comment by jturolla** [comment]
From our production experience, there's little benefit in allowing users to choose the replica label. 

This is an abstraction that is relevant from the infrastructure perspective, metrics consumers don't care if there's deduplication happening behind the scenes as long as their data is there.

In our setup, the replica label is `replica`, and we always append a random hash to the end of it, making it unique, avoiding overlapping blocks in s3. 

This would add a difficult to explain concept in the client UI and could lead to wrong data from more inexperienced users that don't even know the difference between prometheus and thanos.

**Comment by daixiang0** [comment]
@bwplotka is it still a plan?
