### ISSUE TITLE
bucket:inspect should have timeout parameter like web does

### ISSUE THREAD

**Issue by jdfalk** [thanos-io/thanos#1400]
**Thanos, Prometheus and Golang version used**

thanos, version 0.6.0-master (branch: master, revision: 6d129bf7e663804651a91d00f0783e45b51c31d6)
  build user:       build@localhost
  build date:       20190812-12:58:42
  go version:       go1.12.7

**What happened**
Attempting to do a thanos bucket inspect on a S3 bucket which contains 40TB of backed up data it will time out on a slower connection.

**What you expected to happen**
Thanos would return the data if provided an adjusted timeout setting

**How to reproduce it (as minimally and precisely as possible)**:
Fill an S3 bucket full of 40TB of data (mostly compacted)
Use a DSL line or other slow internet connection and run `thanos bucket inspect`
**Full logs to relevant components**

<details>Logs
<p>

level=info ts=2019-08-12T13:13:24.715263Z caller=main.go:155 msg="Tracing will be disabled"
level=info ts=2019-08-12T13:13:24.716264Z caller=factory.go:39 msg="loading bucket configuration"
level=error ts=2019-08-12T13:18:25.496206Z caller=main.go:185 err="bucket inspect command failed: meta.json bkt get for 01DD4CA1QX7NG6W7YC92A3RC1G: Get https://s3.dualstack.us-east-1.amazonaws.com/redacted/01DD4CA1QX7NG6W7YC92A3RC1G/meta.json: context deadline exceeded"
</p>
</details>

**Anything else we need to know**
All thanos bucket commands should just share a common flag timeout so that the behavior is consistent and people with slower connections can still utilize them.

**Comment by GiedriusS** [comment]
Fixed by https://github.com/thanos-io/thanos/pull/1533.
