### ISSUE TITLE
[QUESTION]: how to migrate existing remote storage CrateDB to Thanos s3?

### ISSUE THREAD

**Issue by clausa20** [thanos-io/thanos#1401]
Hello, 

Currently we have prometheus with a cluster of CrateDB used as long-term remote storage, but we want to migrate to Thanos and keep remote storage in S3. But we want to keep the existing metrics we have in CrateDB.
So the question is how to migrate the metrics we have in CrateDB to S3 so it can be processed by Thanos?
Thanks.

**Comment by jojohappy** [comment]
Hi, I'm sorry that we have not a tool to migrate metrics from some tsdb to object storage now. But you can see the [docs/integrations.md](https://github.com/thanos-io/thanos/blob/master/docs/integrations.md#opentsdb) to know about third-party integration tool exposed the StoreAPI. 

So You can try to develop a tool to run PromQL queries on CrateDB and expose the StoreAPI to work with other Thanos components. Then you can build your new Thanos cluster to do monitoring your cluser and use S3 as long-term storage, maybe some time later, you don't need the metrics in CrateDB, just removing it.

I also found that Prometheus support `remote_read` for CrateDB, so I guess that you can set a independent prometheus instance to use `remote_read` for querying from your CrateDB with the same `external_labels`. Then make it integrate into your thanos cluster by sidecar.

**Comment by jojohappy** [comment]
Hi, I'm sorry that we have not a tool to migrate metrics from some tsdb to object storage now. But you can see the [docs/integrations.md](https://github.com/thanos-io/thanos/blob/master/docs/integrations.md#opentsdb) to know about third-party integration tool exposed the StoreAPI. 

So You can try to develop a tool to run PromQL queries on CrateDB and expose the StoreAPI to work with other Thanos components. Then you can build your new Thanos cluster to do monitoring your cluser and use S3 as long-term storage, maybe some time later, you don't need the metrics in CrateDB, just removing it.

I also found that Prometheus support `remote_read` for CrateDB, so I guess that you can set a independent prometheus instance to use `remote_read` for querying from your CrateDB with the same `external_labels`. Then make it integrate into your thanos cluster by sidecar.
