### ISSUE TITLE
bucket:inspect should define column headers better

### ISSUE THREAD

**Issue by jdfalk** [thanos-io/thanos#1402]
**Thanos, Prometheus and Golang version used**

thanos, version 0.6.0-master (branch: master, revision: 6d129bf7e663804651a91d00f0783e45b51c31d6)
  build user:       jdfalk@frigg.local
  build date:       20190812-12:58:42
  go version:       go1.12.7

**What happened**
UNTIL-COMP I assume means time until it's compressed by the compactor, but some of these have `32h0m0s` and some have negative numbers `-254h0m0s` or `-96h0m0s`. Am I correct in assuming that's time until this block is compressed? and second why do I have negative numbers? 

**What you expected to happen**
Help should provide some basic info on each column, example data, and how to read that data. 

**How to reproduce it (as minimally and precisely as possible)**:
thanos bucket inspect and look at output

**Output**:

```0:00 | 06-09-2018 00:00:00 | 336h0m0s       | -96h0m0s        | 1,660,475   | 6,499,346,412   | 46,880,608    | 4          | false       | prometheus_replica=prometheus0                                                                  | 5m0s       | compactor |
| 01CV9RRVCE2CX36CQW8GYBMKDJ | 23-08-2018 00:00:00 | 06-09-2018 00:00:00 | 336h0m0s       | -96h0m0s        | 12,131,951  | 4,161,424,502   | 40,151,956    | 4          | false       | prometheus_replica=prometheus1                                                                  | 5m0s       | compactor |
| 01CVA5CFQQVP205KJ5QPT24HB4 | 23-08-2018 00:00:00 | 06-09-2018 00:00:00 | 336h0m0s       | -96h0m0s        | 1,220,435   | 4,769,467,080   | 34,505,860    | 4          | false       | prometheus_replica=prometheus0                                                                  | 5m0s       | compactor |
| 01CVAVMB1MKGY963RXM07V247N | 23-08-2018 00:00:00 | 06-09-2018 00:00:00 | 336h0m0s       | -               | 36,675,593  | 5,484,158,181   | 84,938,697    | 4          | false       | prometheus_replica=prometheus0                                                                  | 1h0m0s     | compactor |
| 01CVRM7WG0W95D6AHQ7FPX0NTJ | 23-08-2018 00:00:00 | 06-09-2018 00:00:00 | 336h0m0s       | -               | 1,660,475   | 548,394,343     | 6,543,064     | 4          | false       | prometheus_replica=prometheus1                                                                  | 1h0m0s     | compactor |
| 01CVRTW823K4THEK2VG7RPQZG6 | 23-08-2018 00:00:00 | 06-09-2018 00:00:00 | 336h0m0s       | -               | 12,131,934  | 361,541,566     | 15,028,307    | 4          | false       | prometheus_replica=prometheus0                                                                  | 1h0m0s     | compactor |
| 01CVS215PP36168JYF5BSYWBSY | 23-08-2018 00:00:00 | 06-09-2018 00:00:00 | 336h0m0s       | -               | 1,660,475   | 548,180,750     | 6,543,028     | 4          | false       | prometheus_replica=prometheus0                                                                  | 1h0m0s     | compactor |
| 01CVS8M8EBPTTGJ3ZBJ19XYXAE | 23-08-2018 00:00:00 | 06-09-2018 00:00:00 | 336h0m0s       | -               | 12,131,951  | 361,913,361     | 15,028,440    | 4          | false       | prometheus_replica=prometheus1                                                                  | 1h0m0s     | compactor |
| 01CVSEHQ597QQP7TDKTDHYK4E0 | 23-08-2018 00:00:00 | 06-09-2018 00:00:00 | 336h0m0s       | -               | 1,220,435   | 401,562,436     | 4,771,886     | 4          | false       | prometheus_replica=prometheus0                                                                  | 1h0m0s     | compactor |
| 01CSPK821K91AQ3J1S1HDDDKM4 | 06-09-2018 00:00:00 | 20-09-2018 00:00:00 | 336h0m0s       | -296h0m0s       | 51,041,880  | 489,240,432,139 | 4,418,483,235 | 4          | false       | prometheus_replica=prometheus0                                                                  | 0s         | compactor |
```

**Comment by GiedriusS** [comment]
Hi, how would you propose to improve the column names? AFAICT they are not meant to be very human readable - for that you probably need to use the web interface :smile: 

Also, `UNTILCOMP` means the time until the compaction is supposed to happen. Negative values mean that Thanos Compact still hasn't picked up those blocks and they will be compacted as soon as possible -- when your Thanos Compact instance catches up to them.

**Comment by jdfalk** [comment]
I'm good with leaving the column headers the same, but just put in some documentation in `bucket inspect` that details what each field is even if it seems obvious, and the additional information about negative times and what that means. 

I've used inspect several times to try and find overlapping blocks as they will be the only ones with weird times that aren't a multiple of 2h. In addition, I am attempting to use it to troubleshoot an issue with compactor and knowing that negative means the compactor hasn't picked it up yet is super useful info.
