### ISSUE TITLE
Refresh `thanosbench` 

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#1412]
AC:
* `./benchmark`  should be a separate repo in `thanos-io` org. (TO decide)
* thanosbench should be up to date with newest Thanos.

**Comment by yeya24** [comment]
I' m interesting on this. But with some questions.
1. Rename to `thanosbench` or remain `benchmark`?
2. Do we have any plan for this part? Will it be something like `prombench`?
3. Don't have any ideas about this https://github.com/thanos-io/thanos/issues/1180#issuecomment-512626504

**Comment by bwplotka** [comment]
Valid questions!

So first of all. The plan is to remove the `benchmark` directory totally. It's super old and not maintained. Let's stop confusing users: https://github.com/thanos-io/thanos/pull/1423

1. I think `thanosbench` makes sense (: 
2. Have some rough ideas, but TBH for recent benchmarks, I used this: https://github.com/thanos-io/thanos/tree/865d5ec710b5651ead08a7dc73864a6f5dbeeaa9/tutorials/kubernetes-demo/blockgen and some infrastracture definitions in Go: https://github.com/bwplotka/mimic/tree/master/examples/prometheus-remote-read-benchmark
3. Commented.

Overall I am not sure if separate project even makes sense. Benefits of the same repo:
* It's easier to synchronize versions of deps, thanos vs benchmarks
* Reuse CI, tooling etc.

**Comment by krasi-georgiev** [comment]
here are a couple of tools that can help
https://github.com/open-fresh/avalanche
https://github.com/m3db/promremotebench

And here is a bench test setup that I started on the ingestion path. 
https://github.com/krasi-georgiev/benchTSDB

**Comment by bwplotka** [comment]
Created https://github.com/thanos-io/thanosbench

The initial idea is to have a place that will hold:
* CLI / docker tools for benchmarking
   * Querying
   * Generating blocks of different size and compactions, downsampling structure - for both object storage as well as filesystem
* Kubernetes templates based on Go ([mimic](https://github.com/bwplotka/mimic)) that will generate deployment YAMLs for different cases.
* Tooling to build thanos-io/thanos certain commit into docker image for Kubernetes use

That's for start. Feedback welcome, what would you like to see more?

**Comment by bwplotka** [comment]
https://github.com/thanos-io/thanosbench exists. Let's create issues on that repo related to benchmarking.
