### ISSUE TITLE
Freshly cloned Thanos now fails to build with `make build`

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#1415]
Only `publish_master` does not work though: https://circleci.com/gh/thanos-io/thanos/4467

I can repro locally:
```
>> building binaries /home/bartek/Repos/thanos/.bin
 >   thanos
build github.com/thanos-io/thanos/cmd/thanos: cannot load github.com/prometheus/prometheus/tsdb: cannot find module providing package github.com/prometheus/prometheus/tsdb
!! command failed: build -o /home/bartek/Repos/thanos/thanos -ldflags -X github.com/prometheus/common/version.Version=0.6.0-master -X github.com/prometheus/common/version.Revision=e9028159404dc753e5e1fa4443ae135d72f09361 -X github.com/prometheus/common/version.Branch=publish-fix -X github.com/prometheus/common/version.BuildUser=bartek@bartek-lin-fgzbqq2.corp.improbable.io -X github.com/prometheus/common/version.BuildDate=20190814-14:53:04  -extldflags '-static' -a -tags netgo github.com/thanos-io/thanos/cmd/thanos: exit status 1
Makefile:110: recipe for target 'build' failed
make: *** [build] Error 1

```
Investigating.

**Comment by bwplotka** [comment]
Somehow `go.mod` was reverted.

**Comment by imluyuan** [comment]
[root@pfw06vv thanos]# make build
>> building binaries /bin
 >   thanos
# github.com/prometheus/tsdb/goversion
/root/go/pkg/mod/github.com/prometheus/tsdb@v0.8.0/goversion/init.go:17:9: undefined: _SoftwareRequiresGOVERSION1_12
!! command failed: build -o /home/luyuan/go/src/github.com/thanos-io/thanos/thanos -ldflags -X github.com/prometheus/common/version.Version=0.6.1 -X github.com/prometheus/common/version.Revision=acb1cb03fd5ecf3e044a97642be50897db11c34f -X github.com/prometheus/common/version.Branch=master -X github.com/prometheus/common/version.BuildUser=root@pfw06vv.ops.hkht.qihoo.net -X github.com/prometheus/common/version.BuildDate=20190815-04:34:32  -extldflags '-static' -a -tags netgo github.com/improbable-eng/thanos/cmd/thanos: exit status 2
make: *** [build] 错误 1
[root@pfw06vv thanos]#

**Comment by imluyuan** [comment]
[root@gobuildtest thanos]# make build
>> building binaries /bin
 >   thanos
# github.com/prometheus/tsdb/goversion
/root/go/pkg/mod/github.com/prometheus/tsdb@v0.8.0/goversion/init.go:17:9: undefined: _SoftwareRequiresGOVERSION1_12
!! command failed: build -o /root/go/src/github.com/thanos-io/thanos/thanos -ldflags -X github.com/prometheus/common/version.Version=0.6.1 -X github.com/prometheus/common/version.Revision=acb1cb03fd5ecf3e044a97642be50897db11c34f -X github.com/prometheus/common/version.Branch=master -X github.com/prometheus/common/version.BuildUser=root -X github.com/prometheus/common/version.BuildDate=20190815-04:34:32  -extldflags '-static' -a -tags netgo github.com/improbable-eng/thanos/cmd/thanos: exit status 2

**Comment by metalmatze** [comment]
Looking into this right now. :slightly_smiling_face:

**Comment by bwplotka** [comment]
Remove of `GOPATH/pkg` and running `make docker` reproduces this.

**Comment by bwplotka** [comment]
It looks like `promu` doing something:
```
go: extracting github.com/gopherjs/gopherjs v0.0.0-20181017120253-0766667cb4d1
go: extracting github.com/grpc-ecosystem/grpc-gateway v1.9.5
all modules verified
>> building binaries /home/bartek/Repos/thanos/.bin
 >   thanos
go: finding github.com/prometheus/prometheus v2.5.0+incompatible
go: downloading github.com/prometheus/prometheus v2.5.0+incompatible
go: extracting github.com/prometheus/prometheus v2.5.0+incompatible
go: finding github.com/prometheus/tsdb v0.10.0
go: downloading gopkg.in/fsnotify/fsnotify.v1 v1.4.7
go: downloading github.com/prometheus/tsdb v0.10.0
go: extracting gopkg.in/fsnotify/fsnotify.v1 v1.4.7
go: extracting github.com/prometheus/tsdb v0.10.0
go: finding github.com/dgryski/go-sip13 v0.0.0-20181026042036-e10d5fee7954
build github.com/thanos-io/thanos/cmd/thanos: cannot load github.com/prometheus/prometheus/tsdb: cannot find module providing package github.com/prometheus/prometheus/tsdb
!! command failed: build -o /home/bartek/Repos/thanos/thanos -ldflags -X github.com/prometheus/common/version.Version=0.6.0-master -X github.com/prometheus/common/version.Revision=414b2e63a8f68b35476e219cad55508665985cfd -X github.com/prometheus/common/version.Branch=publish-fix -X github.com/prometheus/common/version.BuildUser=bartek@bartek-lin-fgzbqq2.corp.improbable.io -X github.com/prometheus/common/version.BuildDate=20190815-15:33:51  -extldflags '-static' -a -tags netgo github.com/thanos-io/thanos/cmd/thanos: exit status 1
Makefile:110: recipe for target 'build' failed

```

**Comment by bwplotka** [comment]
something means `go build` - I think it is really some https://proxy.io issue.

Let's move to proxy.golang.org with `replaces`: https://github.com/thanos-io/thanos/pull/1421 

Reasons:
* bit safer cache
* fixes this issue (unknown root cause, maybe some obsolete cache?)

**Comment by metalmatze** [comment]
This should be closed now, right?

**Comment by bwplotka** [comment]
Yes, but I am waiting for confirmation before that (green master build)

**Comment by bwplotka** [comment]
Something is still wrong .. https://circleci.com/gh/thanos-io/thanos/4492

**Comment by bwplotka** [comment]
passed now, those were flakinesses.
