### ISSUE TITLE
Question/Best Practise - How to you deal with 2 hour gap

### ISSUE THREAD

**Issue by DirkFries** [thanos-io/thanos#1435]
Hi @all,

first of all: Basically this topic would be better suited for some "Thanos Users Mailinglist". As far as I know there is no such List. If I'm wrong I'd like to apologize and it would be very kind to give me a link to that list.

Let's start with my question:

As far as I have read it is advised to run Prometheus with

--storage.tsdb.min-block-duration=2h
--storage.tsdb.max-block-duration=2h

So it seems that Promtheus keeps the collected metrics for 2 hours in memory und flushes them than to disk. As soon as they are on disk the Thanos sidecar can collect those metrics and feed them into Thanos.

So if I like to visualize those metrics with Grafana I have the following options:

- Query Thanos with Grafana 
When you query Thanos you will have a gap of max 2 hours between the last metric and "now".

- Query both Prometheus and Thanos with Grafana
You'd have 2 different Graphs. One with the "new" Prometheus metrics and one with the "older" Thanos Metrics.

- In theory your could run Prometheus with
--storage.tsdb.min-block-duration=1m
--storage.tsdb.max-block-duration=1m
But I think this would have an heavy impact on performance.

To me all my solutions make a rather cumbersome impression. In my Imagination I'd have one tool that I'd send my querys to and this tool collects the data either from its own storage or another storage transparent for the user.

How do others think about this ? Maybe I have missed some solution or maybe I have understood something wrong ? Maybe I should adjust my expectations ?

Thanks a lot for your comments !

Bye, Dirk

**Comment by miclando** [comment]
hi,
this is not the case. 
the side car uses Prometheus's api to get the metrics.
as such it has access to all metrics the Prometheus has local and in memory.
the configuration you mentioned is connected to compaction.
--storage.tsdb.min-block-duration=2h
--storage.tsdb.max-block-duration=2h

thanos mentioned this in case you want to upload the metrics to an object store in such a case you set this parameters so that Prometheus will no compact the data.
the compaction will be done by a thanos component once uploaded.

you have no gap in your case.

**Comment by DirkFries** [comment]
Hi miclando,

thanks a lot for your reply. In fact this is music to my ears, because that is what I was hoping to hear.
In fact I do have a max. 2 hour gap when querying Thanos.

e.g  this Screenshot was made in Grafana around 13:25 CET. The metrics stop at 12:04

![2](https://user-images.githubusercontent.com/51441256/63343600-a84d1480-c34e-11e9-9a2c-ec9289cb8e86.jpg)

The same in Thanos:

![3](https://user-images.githubusercontent.com/51441256/63343919-80aa7c00-c34f-11e9-9039-6eced8f8fc80.jpg)

If I lower --storage.tsdb.min-block-duration and --storage.tsdb.max-block-duration to 1m I get the results immediatly.

Bye, Dirk

**Comment by jojohappy** [comment]
@DirkFries Thanks for your report, but it is confused for me. Could you query metrics using the original prometheus instances? 

On the other side, could you provide the arguments of thanos query command? Especially the `--store*` flags.

**Comment by DirkFries** [comment]
@jojohappy 
 sure !

thanos sidecar --tsdb.path /data/prometheus/prometheus-data --prometheus.url http://localhost:9090 --objstore.config-file /data/thanos/thanos-0.6.0.linux-amd64/s3.yaml --grpc-address localhost:19090 --log.level=debug

thanos query --http-address 0.0.0.0:19192 --store localhost:10904 --query.auto-downsampling --query.max-concurrent=60

thanos store --objstore.config-file /data/thanos/thanos-0.6.0.linux-amd64/s3.yaml --http-address=localhost:10903 --grpc-address=localhost:10904 --data-dir=/data/thanos/thanos-data

This is my s3.yaml File 


type: S3
config:
  bucket: "thanos"
  endpoint: "localhost:9000"
  region: ""
  access_key: ""
  insecure: true
  signature_version2: false
  encrypt_sse: false
  secret_key: ""
  put_user_metadata: {}
  http_config:
    idle_conn_timeout: 0s
    response_header_timeout: 0s
    insecure_skip_verify: false
  trace:
    enable: false



Here is a Query to Thanos:
![11](https://user-images.githubusercontent.com/51441256/63346736-f1ed2d80-c355-11e9-9726-9a6f3bf517da.jpg)

and the same query some seconds later to Prometheus:
![22](https://user-images.githubusercontent.com/51441256/63346763-003b4980-c356-11e9-9b6c-a92e05a642b8.jpg)


Thanos Version is 0.60
Prometheus Version is 2.11.1

**Comment by miclando** [comment]
your query is not looking at the side car and as such you are not getting any metrics from Prometheus directly :) the missing time.

you need to add the side car as a store for query.

**Comment by jojohappy** [comment]
Oh, maybe I found your problem, you missed the flag for Thanos query: `--store=localhost:19090`, Thanos sidecar also implements the store API and uses `remote_read` to query metrics from prometheus, even if metrics have not been flushed into disk. You should add it as store API server too.

**Comment by DirkFries** [comment]
Whoohoo !
Obviously that was absolutely my fault :-)

 @jojohappy - Thanks a lot - Now I get the newest, latest, hottest metrics directly from Thanos :-)

**Comment by Tikam02** [comment]
Can we reduce the 2hr duration to 1hr or 30 minute in thanos-sidecar or prometheus tsdb

**Comment by max77p** [comment]
@jojohappy what disadvantages are there if setting min and max to less than 2hr?

**Comment by vinfang** [comment]
Sorry to bring up an old topic, but for those who managed to add the thanos side car into grafana, is this referring to the prometheus source itself, or is there actually a thanos side car DNS and port number to point grafana to as a data source? I added the thanos front end query and prometheus, and in grafana I setup a panel with mixed data sources, and I get overlapping duplicate data for the 2 hour part.
