### ISSUE TITLE
Fix Flaky test

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#1442]
```
reloader_test.go:269:

	exp: 5

	got: 3

--- FAIL: TestReloader_RuleApply (10.04s)
    reloader_test.go:238: Performing step number 1
    reloader_test.go:238: Performing step number 3
FAIL
FAIL	github.com/thanos-io/thanos/pkg/reloader	10.769s
```
Quite often spotted.

**Comment by johncming** [comment]
https://github.com/thanos-io/thanos/blob/c35d47b41954dae0e9b5592cb327bf0896e78e26/pkg/reloader/reloader_test.go#L182

Reason: plus op is not an atomic operation.

**Comment by jojohappy** [comment]
@bwplotka @johncming I guess that the reloader read the middle status of watched files, because of using `ioutil.WriteFile`.

```
// WriteFile writes data to a file named by filename.
// If the file does not exist, WriteFile creates it with permissions perm;
// otherwise WriteFile truncates it before writing.
```

**Comment by bwplotka** [comment]
@johncming I think this part is ok as there is only a single writer.

@jojohappy you are right but this can happen normally as well so we should handle it properly.

IMO it is just a CI slowdown, so increasing timeout here https://github.com/thanos-io/thanos/issues/1442 (:
