### ISSUE TITLE
Clear cache from Thanos Store Gateway

### ISSUE THREAD

**Issue by uvaisibrahim** [thanos-io/thanos#1443]
Hi Team,

In our Thanos implementation, we use the thanos store gateway component which is having 100G disk for caching purpose. Currently, disk space usage reaches beyond 90%. How can we delete the old cached items from this disk to make some free space?

Thanks,
Uvais Ibrahim.

**Comment by imluyuan** [comment]
I have this problem.

Start Time:
10:41:04 up 8 days, 20:24,  1 user,  load average: 1.85, 3.72, 3.83
Use Data:
/dev/mapper/VolGroup00-thanos_data  345G  204G  124G   63% /data

monitor image:
![image](https://user-images.githubusercontent.com/3294496/63482150-6ba62800-c4ca-11e9-86c7-2ac89d68a085.png)

**Comment by GiedriusS** [comment]
Right now, unfortunately, all of the index cache JSON files are being held in memory all the time for very efficient lookup. Thus, the only way to reduce this usage is to delete some blocks from your remote object storage and/or run the compaction/downsampling process. However, in the near future we're planning to improve this significantly

**Comment by GiedriusS** [comment]
Closing this in favour of: https://github.com/thanos-io/thanos/issues/1471.
