### ISSUE TITLE
Compilation error when testing

### ISSUE THREAD

**Issue by johncming** [thanos-io/thanos#1448]
The master branch has reported the error for some time, pr #1432 has been submitted

```bash
# github.com/thanos-io/thanos/pkg/reloader
package github.com/thanos-io/thanos/pkg/reloader (test)
	imports github.com/thanos-io/thanos/pkg/testutil
	imports github.com/prometheus/prometheus/tsdb/testutil: cannot find package "github.com/prometheus/prometheus/tsdb/testutil" in any of:
	/Users/john/go/src/github.com/thanos-io/thanos/vendor/github.com/prometheus/prometheus/tsdb/testutil (vendor tree)
	/usr/local/Cellar/go/1.12.7/libexec/src/github.com/prometheus/prometheus/tsdb/testutil (from $GOROOT)
	/Users/john/go/src/github.com/prometheus/prometheus/tsdb/testutil (from $GOPATH)
FAIL	github.com/thanos-io/thanos/pkg/reloader [setup failed]
```

**Comment by jojohappy** [comment]
@johncming Yes, at the head of thanos master branch, we still relied on the prometheus with commit `b5c833ca2194`, so you should update the version of prometheus to use the new `testutil` package in our `go.mod` at first.

**Comment by johncming** [comment]
> @johncming Yes, at the head of thanos master branch, we still relied on the prometheus with commit `b5c833ca2194`, so you should update the version of prometheus to use the new `testutil` package in our `go.mod` at first.

After watching Prometheus in the version, found two `testutil`.  It 's ok to use vendor directly.
