### ISSUE TITLE
Partial response doesn't work if one of stores timing out

### ISSUE THREAD

**Issue by d-ulyanov** [thanos-io/thanos#1453]
Thanos Query sends requests concurrently, but response reading is sequential, in result timeout on one of the stores leads to timeout on others.

It means that partial response currently doesn't work as expected: it works well mostly if one of stores completely unavailable.  

**Thanos, Prometheus and Golang version used**
Thanos v0.6.1

**What you expected to happen**
If one of Stores is not responding (timing out), as a user, I expect to receive a partial response from the others.

Previously discussed here: https://github.com/thanos-io/thanos/issues/835

**Comment by jojohappy** [comment]
Thank you for your report! IMO it is a valid bug. @povilasv @bwplotka What do you think?

**Comment by blockloop** [comment]
Is this just a matter of making this loop parallel? https://github.com/thanos-io/thanos/blob/9d4d0bf408ed86eaab371c8f0c52d7bb5fe6e164/pkg/store/proxy.go#L283

**Comment by d-ulyanov** [comment]
@blockloop it's not so simple :)
MergedSet makes sequential read from stores, the first part of this issue is there.
We're now experimenting with this issue and trying to understand how to fix it better.

**Comment by blockloop** [comment]
Gotcha yeah I started digging in and found it to be more complex 🙂

**Comment by d-ulyanov** [comment]
Yep, code in proxy is pretty confusing 😀

**Comment by blockloop** [comment]
Haha yeah
