### ISSUE TITLE
Thanos: Remote Read API

### ISSUE THREAD

**Issue by garrettlish** [thanos-io/thanos#1457]
Since streamed chunked remote read implementation is merged in prometheus project (https://github.com/prometheus/prometheus/pull/5703), do we have any plan to expose remote read API in thanos?

FYI: original request for this feature: https://github.com/thanos-io/thanos/issues/1128

**Comment by bwplotka** [comment]
Our Store gRPC API is exactly like remote read (but gRPC) (:  

Looks like @accent-atul from the issue you mentioned want to build proxy layer for StoreAPI.  I think I personally would be fine to maintain remote read API on querier since it's literally similar API to StoreAPI so the shim would be lightweight.

What's your use case?

**Comment by garrettlish** [comment]
@bwplotka Our use case is we'd like to expose our thanos cluster to customers which is using prometheus native ruler (not thanos ruler), prometheus native ruler only supports remote read APIs but not Store gRPC API. 
From my understanding, in prometheus world, remote read API should be best for us especially chunked remote read API is supported now :-)
Any thoughts, please advise.

**Comment by bwplotka** [comment]
What Prometheus ruler not Thanos ruler?

The benefit of Thanos ruler is that it supports partial response strategies (but you can work around those with Querier with certain partial response strategy)

**Comment by garrettlish** [comment]
@bwplotka 
> What Prometheus ruler not Thanos ruler?

We have one use case which run prometheus ruler with a rule orchestration engine (manage prometheus ruler cluster, rule distribution,  resume/failover, provide CRUD APIs, etc. We implement it since we have 50,000+ rules and cannot be supported by node and rule CRUD is frequent), this prometheus ruler doesn't have local tsdb (just for rule evaluation), it points to our thanos cluster for remote read. This is why I'd like to say it will be great that thanos can support remote read API, then it will be easy to be used by other prometheus eco other products.

BTW: Partial response strategies is a good feature, however, I think it might not be the good choice for us since it loose accuracy.

**Comment by brancz** [comment]
Rule evaluations in Prometheus have exactly the same characteristics when done with remote data. Also the rule engine in Thanos is literally the same as Prometheus (we use Prometheus’ rule engine as a library). There is no difference in the setups that you’re describing, just the Thanos one works today without Thanos having a remote read endpoint.

**Comment by garrettlish** [comment]
@brancz yes, you are correct, our use case can replace prometheus ruler with thanos ruler to use thanos Storage APIs. However, I still think remote read API is the common API in prometheus eco system, it might be better to support it in thanos.

**Comment by bwplotka** [comment]
So using Thanos Ruler has many benefits:
* First of all Ruler does not point to StoreAPI, but to PrometheusAPI - so Prometheus, or Qurier for example. If you use Prometheus you would user Remote Read -> StoreAPI. This has a few issues: You don't use our Qurier deduplication and downsampling (!) features.
* Secondly Ruler exposes StoreAPI so Thanos system has access to the ruler recording rules data as a well as `ALERTS` metric. You can achieve similar with Prometheus + sidecar though.
* You have more control on partial responses.

I agree with @brancz and I am not opposed on remote read generally, but I just don't want users to use something that would be anti-pattern and misleading as you lose so many benefits Thanos gives. (: 

What would be the benefit of remote read API in Thanos then?

Maybe easier migration process? :thinking:

**Comment by accent-atul** [comment]
FYI, we dropped the idea of building remote read endpoint in thanos. Instead, we attempted to have separate remote read adapter which internally calls gRPC and can scale independently. For simplicity and to avoid dealing with chunk format changes,  we changed the adapter to call thanos http query range api . So Prometheus ---remote read ---> Adapter ----thanos http query range api --> Thanos. 
Our use case is similar, we want to upfront Prometheus for query and running rules as our Prometheus connects to multiple Thanos, and other internal telemetry platform and provides unified query and rules execution.

**Comment by garrettlish** [comment]
Thanks @bwplotka for what benefits Thanos Ruler could provide, I definitely agree that our use case can use Thanos Ruler to replace prometheus Ruler.
However, I still think sometimes thanos remote read API could be useful. Assume that we have 2 data sources, one is thanos cluster and another is native prometheus cluster with third-party databases (such as ClickHouse, Couchbase, etc.). Assume we'd like to set up an unified Ruler for these 2 data sources, it might be hard to do that if thanos cluster doesn't expose Prometheus remote read API. What do you think?

**Comment by garrettlish** [comment]
@accent-atul Why not use thanos Storage API (gRPC) which query raw metrics? Thanos http query range API doesn't return raw metrics and inefficient.

**Comment by bwplotka** [comment]
Yea @accent-atul it looks like this Adapter would be almost seamless if you would just implement it against StoreAPI - essentially going through PromQL engine twice is not perfect. (: 

Looks like remote read adapter might be nice then indeed (?)

**Comment by accent-atul** [comment]
@garrettlish The first attempt was with gRPC. It worked, but to avoid the chunk format and encoding which could change in future for efficiency, we switched to simple query range API. It's giving decent performance. I agree, it may not return raw metrics and apply step resolution (required by thanos and Prometheus).  
Is there any good example/utility available to decode the data as returned by storage API. I wasn't very keen on the application maintaining than decoder.

As of now, most of our telemetry is stored in internal telemetry platform which we read through remote read. We are still evaluating options, and will revisit this adapter shortly.

**Comment by dgl** [comment]
We had a need for a remote read adapter as discussed in this issue, we've now made it available at: https://github.com/G-Research/thanos-remote-read using the gRPC Store API.

**Comment by bwplotka** [comment]
Amazing!

Added docs change to both Prometheus: https://github.com/prometheus/docs/pull/1616 and Thanos: https://github.com/thanos-io/thanos/pull/2566

**Comment by bwplotka** [comment]
This is issue is done :+1:
