### ISSUE TITLE
Object storage retention

### ISSUE THREAD

**Issue by aviadbi1** [thanos-io/thanos#1459]
Hi, 
I am using Thanos with S3 and really enjoying it by now, and i wondered if there is a way to specify the retention time in the object-storage. 
A normal use case can be to store data for 2 months but all I found was "unlimited retention" but there is no such thing actually without the resources. 

Is there a way that you recommend to do it? Is it a feature request?

**Comment by krasi-georgiev** [comment]
I had a quick look and think `--retention.resolution-raw` flag for the compactor is what you are looking for.

https://github.com/thanos-io/thanos/blob/master/cmd/thanos/compact.go#L89

**Comment by aviadbi1** [comment]
Thank you for your answer, but it is still not working for me

**Comment by krasi-georgiev** [comment]
"not working for me" - doesn't give any details on the issue. Please add details/configs with steps to replicate

**Comment by krasi-georgiev** [comment]
first thing I would try is to update to the latest thanos image as `v0.5.0` is a bit outdated. Probably lots of things changed since than.

Please upgrade and let me know if the behavior is still the same.

**Comment by bwplotka** [comment]
Plus be aware that retention is applied at the very end (after downsampling and compaction). 

We probably should apply retention earlier (:

**Comment by bwplotka** [comment]
Other resolutions for ` - --retention.resolution-*` flags are missing.  (:

**Comment by aviadbi1** [comment]
> Other resolutions for ` - --retention.resolution-*` flags are missing. (:

@bwplotka The question is about a case that i don't want another resolutions (5m/1h), only want the raw samples like regular prometheus.
As i can see the default value is 0d. So if you could explain your answer please ill be glad :)

**Comment by bwplotka** [comment]
Cool! Please add `--downsampling.disable` flag to compactor (:
