### ISSUE TITLE
compile fails on FreeBSD 13

### ISSUE THREAD

**Issue by lrosenman** [thanos-io/thanos#1461]
Thanos 0.6.1
go 1.12.9
prometheus 2.21
**Thanos, Prometheus and Golang version used**

**What happened**
Compile failed
**What you expected to happen**
successful compile
**How to reproduce it (as minimally and precisely as possible)**:
unpack tarball
gmake
**Full logs to relevant components**
```
ler in thanos/work/thanos-0.6.1 at borg via 🐹 v1.12.9
[I] ➜ gmake
>> formatting code
>> building binaries /home/ler/go/bin
 >   thanos
# github.com/mattn/go-ieproxy
/home/ler/go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.0-20190610004146-91bb50d98149/GetProxyFunc.go:10:9: undefined: proxyMiddleman
!! command failed: build -o /home/ler/FreeBSD/ports/net-mgmt/thanos/work/thanos-0.6.1/thanos -ldflags -X github.com/prometheus/common/version.Version=0.6.1 -X github.com/prometheus/common/version.Revision=non-git -X github.com/prometheus/common/version.Branch=non-git -X github.com/prometheus/common/version.BuildUser=ler@borg.lerctr.org -X github.com/prometheus/common/version.BuildDate=20190827-02:52:21  -extldflags '-static' -a -tags netgo github.com/improbable-eng/thanos/cmd/thanos: exit status 2
gmake: *** [Makefile:109: build] Error 1

ler in thanos/work/thanos-0.6.1 at borg via 🐹 v1.12.9 took 15s
[I] ➜
```

**Anything else we need to know**

Uncomment and fill if you use not casual environment or if it might be relevant.

**Environment**:
- OS FreeBSD
- Kernel FreeBSD
- Others:

**Comment by FUSAKLA** [comment]
Could you please wrap the block of logs using ``` ? It will make them readable without all those emojis etc :)

**Comment by bwplotka** [comment]
> /home/ler/go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.0-20190610004146-91bb50d98149/GetProxyFunc.go:10:9: undefined: proxyMiddleman

```
package ieproxy

import (
	"net/http"
	"net/url"
)

// GetProxyFunc is a forwarder for the OS-Exclusive proxyMiddleman_os.go files
func GetProxyFunc() func(*http.Request) (*url.URL, error) {
	return proxyMiddleman()
}
```

Looks like this dep does not have support for FreeBSD.

BTW @lrosenman can you confirm that Thanos is buildable before 0.6.1? (: We don't guarantee the support for this, but we would love to unblock you (there is no blocker). I think we could start in putting an issue on `github.com/mattn/go-ieproxy` to add FreeBSD support (:

**Comment by bwplotka** [comment]
Looks like the tip of `go-ieproxy` is fixed (https://github.com/mattn/go-ieproxy/blob/master/proxyMiddleman_unix.go), so it's just matter of ensuring Thanos is built against newest https://github.com/mattn/go-ieproxy

Might by hacky since it is indirect dependency from `github.com/Azure/azure-pipeline-go@v0.2.1`

**Comment by bwplotka** [comment]
Can you try @irosenman to build Thanos from FreeBSD from this branch? https://github.com/thanos-io/thanos/pull/1476 

Please review as well (:

**Comment by bwplotka** [comment]
Fixed merged, so assuming this works.
