### ISSUE TITLE
store: Azure hits EOF when reading last metric in a chunk

### ISSUE THREAD

**Issue by wbh1** [thanos-io/thanos#1466]
**Thanos, Prometheus and Golang version used**
Replicated on v0.3.2, v0.4.0, v0.6.0, and v0.6.1

**What happened**
Store gets an unexpected EOF when trying to read in a chunk because the Azure library uses an `io.ReadFull` call with an ending point that is longer than the file.

This error does not get passed up the stack by oklog/run when the group is run in 
`func (s *BucketStore) Series(req *storepb.SeriesRequest, srv storepb.Store_SeriesServer) (err error)`, which made this more fun to debug :smile: 

**What you expected to happen**
Either Thanos to not request an ending point that is larger than the file, or the Azure library to handle it gracefully.

I don't think Thanos knows ahead of time how big the chunk is, so I'm leaning towards Azure's fault. This leads me to think that:
```
		parts := r.block.partitioner.Partition(len(offsets), func(i int) (start, end uint64) {
			return uint64(offsets[i]), uint64(offsets[i]) + maxChunkSize
		})
```

**How to reproduce it (as minimally and precisely as possible)**:
This may be a complete coincidence, but this metric is the exact last one I have in Prometheus when sorted alphabetically. Try using Azure Blob and querying your last metric?

**Anything else we need to know**
I have already fixed this issue in the Azure library. I'm going to test it more, submit a PR to their repo, and then I'll submit a PR here to bump the version in go.mod

Additionally, I think it'd be worth looking into why using github.com/oklog/run doesn't report errors that the group encounters. Maybe we should add Error logging in the functions being run?

**Comment by devalexx** [comment]
+1, currently currently Azure integration is completely broken. please, approve at least this temporary solution (by @wbh1) as it works for me too
