### ISSUE TITLE
create a port layout (documentation only) to standardize all thanos components on a single host.

### ISSUE THREAD

**Issue by lrosenman** [thanos-io/thanos#1479]
I'm currently working on a FreeBSD port of Thanos, and would like to get a standardized layout for having all the thanos components running on a single host. 

Opening this per @FUSAKLA on Slack.

**Comment by lrosenman** [comment]
this should also take into account prometheus/alertmanager also running on that host.

**Comment by bwplotka** [comment]
What exactly you mean? 

All running under same binary or what? What's stopping you to have script to run everything on same host?

**Comment by FUSAKLA** [comment]
IIUC it should be just standardized ports to which change the conflicting ports when running on single host such as:
```
thanos sidecar grpc:  10901
thanos sidecar http:   10902
thanos store grpc:     10911
thanos store http:      10912
thanos query grpc:    10921
thanos query http:     10922
...
```

Am I correct?

**Comment by bwplotka** [comment]
Ah cool. For docs I think it's perfect, but not sure if defaults should be changed.

**Comment by FUSAKLA** [comment]
Yeah, it was discussed on slack a bit https://cloud-native.slack.com/archives/CK5RSSC10/p1567126946087200?thread_ts=1567126946.087200&cid=CK5RSSC10

**Comment by FUSAKLA** [comment]
But TBH I'm not sure how it is with choosing ports. Should we consider for example https://tools.ietf.org/id/draft-cotton-tsvwg-iana-ports-00.html?

Do we want just increment by `1` or by `10` as I suggested above?

**Comment by lrosenman** [comment]
I think incrementing by 1 is fine (similar to the exporter port list), I'm just looking for a "standard" list to work from setting up start-up scripts for FreeBSD in the port.

**Comment by lrosenman** [comment]
@bwplotka note that the title says documentation only, because I know we don't want to change the defaults (breaking change for this is bad).

**Comment by lrosenman** [comment]
Any news here?  Anything I can help with?

**Comment by FUSAKLA** [comment]
Yes, sorry for the delay.
No one from maintainers has any objections nor strong opinion on it so I'll just create some and send PR ASAP.

**Comment by bwplotka** [comment]
BTW @Irosenman are you aware of recent Go in relation with FreeBSD: https://golang.org/doc/go1.13#freebsd ? There seems to be FreeBSD version restriction.

**Comment by lrosenman** [comment]
Yes, and I'm personally running 12 & 13, and the ports collection knows about that. 
There are exp-runs happening to get all the ports ready for 1.13.

**Comment by lrosenman** [comment]
As I've said, I'm a Ports Committer so am VERY in tune with the goings-on.

**Comment by bwplotka** [comment]
Good! Just checking (:
