### ISSUE TITLE
compactor: failing to create directory, with error "file name too long"

### ISSUE THREAD

**Issue by ingvarm-gr** [thanos-io/thanos#1491]
Thanos: v0.6.0
Prometheus: v2.11.2

thanos:v0.6.0

**What happened**

We started the thanos-compactor, after a while it crashes and ends up in a crashloop

**What you expected to happen**

Thanos-compactor running and compacting data

**How to reproduce it (as minimally and precisely as possible)**:

Don't know.

**Full logs to relevant components**

Unfortunately, I can't egress the full logs, but the failure log message looks like:
level=error ts=2019-09-04T10:11:14.436861213Z caller=main.go:199 msg="running command failed" err="error executing compaction: compaction failed: compaction failed for group 0@{prometheus=\"REDACTED/prometheus-REDACTED\",prometheus_replica=\"prometheus-prometheus-REDACTED-0\"}: download block 01DCQ2K02CKMAD9N4R6ZA5VZW9: create dir: mkdir /local/state/compact/0@{prometheus=\"datadev/prometheus-REDACTED\",prometheus_replica=\"prometheus-prometheus-REDACTED-0\"}/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9/01DCQ2K02CKMAD9N4R6ZA5VZW9: file name too long"

**Anything else we need to know**

**Comment by bwplotka** [comment]
Hi, Thanks for reporting. Looks like some bug, but users run 0.6.0 compactor just fine, so it must be specific to your environment. 

How you configure Thanos compact? What object storage do you use? This looks like a duplicate of https://github.com/thanos-io/thanos/issues/844 So can you provide more data to that ticket instead?
