### ISSUE TITLE
Support Web Identity providers for IAM credentials for AWS EKS

### ISSUE THREAD

**Issue by barryib** [thanos-io/thanos#1494]
Add support for Web Identity providers for IAM credentials for AWS EKS (IAM Roles for Service Accounts) https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

I think this related to minio sdk, but I opening it here also to track this proposal.

**Comment by harshavardhana** [comment]
https://godoc.org/github.com/minio/minio-go/pkg/credentials#NewIAM how about using this ?

**Comment by evq** [comment]
When using the minio-go revision from https://github.com/minio/minio-go/pull/1183 this just works, so once that PR is merged I believe a minio-go version bump will be needed.
```
[user@work:~/source/thanos]% git diff
diff --git go.mod go.mod
index 171dd718..fa93a0d1 100644
--- go.mod
+++ go.mod
@@ -112,6 +112,7 @@ require (
 replace (
        // Mitigation for: https://github.com/Azure/go-autorest/issues/414
        github.com/Azure/go-autorest => github.com/Azure/go-autorest v12.3.0+incompatible
+       github.com/minio/minio-go/v6 => github.com/saracen/minio-go/v6 v6.0.41-0.20191205161654-99323bc99b57
        k8s.io/api => k8s.io/api v0.0.0-20190620084959-7cf5895f2711
        k8s.io/apiextensions-apiserver => k8s.io/apiextensions-apiserver v0.0.0-20190620085554-14e95df34f1f
        k8s.io/apimachinery => k8s.io/apimachinery v0.0.0-20190612205821-1799e75a0719
```

**Comment by bwplotka** [comment]
Thanks for update :+1: STGM @evq

**Comment by robcoward** [comment]
https://github.com/minio/minio-go/releases/tag/v6.0.45 has just been released.
