### ISSUE TITLE
receive use labels flag while rule use label flag

### ISSUE THREAD

**Issue by Wing924** [thanos-io/thanos#1497]
**Thanos, Prometheus and Golang version used**
thanos: v0.7.0

**What happened**
`thanos rule` use `--label` to set label flag while `thanos receive` use `--labels`

**What you expected to happen**
both rule and receive use `--label` to set label

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

**Anything else we need to know**

**Comment by brancz** [comment]
Agreed, this should be consistent.

**Comment by Wing924** [comment]
@brancz do you mind me to open PR?

**Comment by brancz** [comment]
Go ahead :)
