### ISSUE TITLE
Thanos receive with replication-factor=3 not working 

### ISSUE THREAD

**Issue by R4scal** [thanos-io/thanos#1508]
thanos, version 0.7.0 (branch: HEAD, revision: c6eaf68bec32aefd280318eaef6121d6ddb20d10)

**Setup**
Thanos receive hashring with config:
```
[
    {
        "hashring": "prod-shard",
        "endpoints": ["http://thanos01:12106/api/v1/receive","http://thanos02:12106/api/v1/receive","http://thanos03:12106/api/v1/receive"],
        "tenants": ["prod-shard"]
    },
...
]
```
2 thanos receive service:
ingress:
```
/opt/thanos/thanos receive  \
            --tsdb.path="/tmp" \
            --log.format=json \
            --log.level=info \
            --grpc-address="0.0.0.0:10000" \
            --http-address="0.0.0.0:11000" \
            --remote-write.address="0.0.0.0:12000" \
            --receive.hashrings-file="/etc/thanos/hashring.json" \
            --receive.local-endpoint="http://receive" \
            --receive.replication-factor=3
```
data
```
/opt/thanos/thanos receive \
            --tsdb.path=/var/lib/thanos/prod-shard \
            --log.format=json \
            --log.level=info \
            --grpc-address=0.0.0.0:10106 \
            --http-address=0.0.0.0:11106 \
            --remote-write.address=0.0.0.0:12106 \
            --tsdb.retention=15d \ 
            --receive.hashrings-file=/etc/thanos/hashring.json \
            --receive.local-endpoint=http://thanos03:12106/api/v1/receive \
            --receive.replication-factor=3 \
            --labels=thanos_service="shard" \
            --labels=environment="prod" \
            --labels=replica="receive-03"
```

**What happened**

When 1 node down - 500-errors in logs and abount 50% failed requests
```
  HTTP/1.1 500 Internal Server Error..Content-Type: text/plain; charset=utf-8..X-Content-Type-Options: nosniff..Date: Wed, 11 Sep 2019 16:00:33 GMT..Content-Length: 534..Connection: close..
  ..3 errors: could not replicate write request: Post http://thanos03:12106/api/v1/receive: dial tcp 10.0.0.3:12106: connect: no route to host;
  could not replicate write request: Post http://thanos03:12106/api/v1/receive: dial tcp 10.0.0.3:12106: connect: no route to host; could not re
  plicate write request: Post http://thanos03:12106/api/v1/receive: dial tcp 10.0.0.3:12106: connect: no route to host.
```

All 3 errors about 1 unavailable host

**What you expected to happen**

No errors with 1 of 3 servers unavailable with replication-factor=3

**Comment by squat** [comment]
@R4scal to clarify, you are running 5 thanos replicas? Two for load balancing and three for actually accepting writes, correct? One of the data replicas is dead and you see errors in the load balancer replicas, right?

I'll investigate to see if I can replicate

**Comment by R4scal** [comment]
@squat I have 3 servers, on each 5 thanos process:
1: for load balancing
2: 3-node hashring for tenant `A`
3: 3-node hashring for tenant `B`
4: 3-node hashring for tenant `C`
5: 3-node hashring for tenant `D`

All servers use common hashring.json. So, in hashring.json servers on all hashring have same domain name, but different ports

**Comment by R4scal** [comment]
And - erorrs on 1 (load balancing) instance. I tried change on this instance `replication-factor=3` -> `replication-factor=1` and saw some errors but one time, not 3 times as in log in example.
Strange, that errors abount 50%. About 50% request have successful 200 code

**Comment by R4scal** [comment]
Hi @squat any updates on this?
