### ISSUE TITLE
Thanos compact does not work on Windows

### ISSUE THREAD

**Issue by ahurtaud** [thanos-io/thanos#1526]
**Thanos, Prometheus and Golang version used**
```
thanos.exe --version
thanos, version 0.7.0 (branch: HEAD, revision: c6eaf68bec32aefd280318eaef6121d6ddb20d10)
  build user:       root@aa355daaf987
  build date:       20190902-15:35:44
  go version:       go1.12.5
```

**What happened**
Run the `thanos compact` command on an existing bucket (on-premise s3)
```
thanos.exe compact --objstore.config-file=bucket.yaml --consistency-delay=30m --retention.resolution-raw=30d --retention.resolution-5m=30d --retention.resolution-1h=30d --log.level=debug
```
The same command works correctly on a linux ecosystem but crash on windows.
Apparently on windows FS, it is impossible to mkdir the requested folder (see detailed logs)

**What you expected to happen**
Compaction to happen as on linux systems.

**How to reproduce it (as minimally and precisely as possible)**:
use `thanos.exe compact` with the same command line args you have one running on linux ecosystem.

**Full logs to relevant components**

<details>Logs
<p>

level=info ts=2019-09-16T15:10:31.7504834Z caller=compact.go:1029 msg="start of GC"
level=info ts=2019-09-16T15:10:31.7604868Z caller=compact.go:1035 msg="start of compaction"
level=warn ts=2019-09-16T15:10:31.7644854Z caller=prober.go:154 msg="changing probe status" status=unhealthy reason="compaction failed: compaction failed for group 0@{prometheus=\"si\",prometheus_instance=\"alt\",replica=\"prometheus-si-alt-0\",stack=\"muc4\"}: create compaction group dir: mkdir data\\compact\\0@{prometheus=\"si\",prometheus_instance=\"alt\",replica=\"prometheus-si-alt-0\",stack=\"muc4\"}: The filename, directory name, or volume label syntax is incorrect."
level=error ts=2019-09-16T15:10:31.765485Z caller=main.go:213 msg="running command failed" err="compaction failed: compaction failed for group 0@{prometheus=\"si\",prometheus_instance=\"alt\",replica=\"prometheus-si-alt-0\",stack=\"muc4\"}: create compaction group dir: mkdir data\\compact\\0@{prometheus=\"si\",prometheus_instance=\"alt\",replica=\"prometheus-si-alt-0\",stack=\"muc4\"}: The filename, directory name, or volume label syntax is incorrect."

</p>
</details>

**Environment**:
- Windows 10

**Comment by krasi-georgiev** [comment]
After a quick chat with @bwplotka he confirmed that  windows support is in the `maybe` priority list. 
If someone can spend the time to implement proper testing and maintain it maybe it will be considered, but for now it should be considered unsupported.
