### ISSUE TITLE
Thanos Query tries to add the same store twice when using DNS service discovery

### ISSUE THREAD

**Issue by tbregolin** [thanos-io/thanos#1527]
**Thanos, Prometheus and Golang version used**
docker.io/thanosio/thanos:v0.7.0

**What happened**
When using DNS for service discovery, Thanos Query tries to connect to all addresses resolved for each SRV record (the A and the AAAA records) and, because it's the same store, it adds and removes them in a loop due to conflicting external labels.

**What you expected to happen**
Thanos Query should connect only to the IPv6 address, and then fallback to connecting to the IPv4 address if necessary.

**How to reproduce it (as minimally and precisely as possible)**:
I have a service record that looks like this:
```
    _thanos-sidecar._tcp.example.com. 300 IN SRV 10 1 10901 01.thanos-sidecar.example.com.
```
01.thanos-sidecar.example.com looks like this:
```
    01.thanos-sidecar.example.com. 300 IN CNAME   server.example2.com.
    server01.example2.com.         3600    IN      A       192.0.2.2
    server01.example2.com.         3600    IN      AAAA    2001:db8::2
```
Thanos  Query tries to add both 192.0.2.2 and 2001:db8::2 as stores, so it adds and removes them in a loop.

**Full logs to relevant components**

<details>Logs
<p>

```
level=info ts=2019-09-16T14:53:50.302203728Z caller=storeset.go:263 component=storeset msg="adding new store to query storeset" address=[2001:db8::2]:10901
level=warn ts=2019-09-16T14:54:00.333034248Z caller=storeset.go:252 component=storeset msg="dropping store, external labels are not unique" address=192.0.2.2:10901 extLset="{prometheus=\"prometheus01\"}" duplicates=2
level=warn ts=2019-09-16T14:54:00.339204099Z caller=storeset.go:303 component=storeset msg="update of store node failed" err="fetching store info from [2001:db8::2]:10901: rpc error: code = Canceled desc = grpc: the client connection is closing" address=[2001:db8::2]:10901
level=info ts=2019-09-16T14:54:10.343209648Z caller=storeset.go:238 component=storeset msg="removing store because it's unhealthy or does not exist" address=[2001:db8::2]:10901
level=info ts=2019-09-16T14:54:10.343861396Z caller=storeset.go:263 component=storeset msg="adding new store to query storeset" address=192.0.2.2:10901
level=warn ts=2019-09-16T14:54:20.455305967Z caller=storeset.go:252 component=storeset msg="dropping store, external labels are not unique" address=[2001:db8::2]:10901 extLset="{prometheus=\"prometheus01\"}" duplicates=2
level=warn ts=2019-09-16T14:54:20.456725158Z caller=storeset.go:303 component=storeset msg="update of store node failed" err="fetching store info from 192.0.2.2:10901: rpc error: code = Canceled desc = grpc: the client connection is closing" address=192.0.2.2:10901
level=info ts=2019-09-16T14:54:30.469286373Z caller=storeset.go:238 component=storeset msg="removing store because it's unhealthy or does not exist" address=192.0.2.2:10901
level=info ts=2019-09-16T14:54:30.470207533Z caller=storeset.go:263 component=storeset msg="adding new store to query storeset" address=[2001:db8::2]:10901
level=warn ts=2019-09-16T14:54:40.539096978Z caller=storeset.go:252 component=storeset msg="dropping store, external labels are not unique" address=192.0.2.2:10901 extLset="{prometheus=\"prometheus01\"}" duplicates=2
```

</p>
</details>

**Anything else we need to know**

Domains and addresses have been doctored, but the logs are real otherwise.

**Comment by krasi-georgiev** [comment]
I will try to provide a fix for this.

**Comment by krasi-georgiev** [comment]
@tbregolin I have looked through the code and tested different scenarios and I think this is the expected behavior. The idea is that you can use a single domain to advertise many different targets. this is the same for srv and dns.


What is your use case that you have a duplicate IP address for the same target?
I understand that one is A and the other is AAAA, but still why do you have both set in the DNS records?

If you think that the expected behavior should be different please describe how would you think this should work. Keep in mind that keeping multiple targets per domain shouldn't change as this is the most common setup.

**Comment by tbregolin** [comment]
@krasi-georgiev thank you for looking into this.

I don't think adding and removing stores in a loop is a sane behavior. Thanos should just refuse to add a store when the external labels conflict, so that it doesn't impact availability.

Your point about using a single SRV record for each store makes sense, and works for me.

I'll leave it up to you to close this, but feel free to do so.

**Comment by krasi-georgiev** [comment]
> I don't think adding and removing stores in a loop is a sane behavior. Thanos should just refuse to add a store when the external labels conflict, so that it doesn't impact availability.

I think I misunderstood the original issue and yes I agree that when one store is healthy it should just remove the duplicate and do nothing more. 

Now looking at the logs you provided it looks like it goes into a loop because it can't connect to either stores so it keeps trying.
It first marks the AAAA as a duplicate and tries to connect to A it fails to than it tries to connect to AAAA and so on.

When I tested this locally it behaved as expected and when it connected ok to the A record it just left the AAAA as duplicated and didn't go into a loop

**Comment by tbregolin** [comment]
In my case the same sidecar was reachable in both addresses. I'll try to reproduce it again in a local environment to be sure and post the logs/my findings here.

**Comment by Pesir** [comment]
Hi,
first of all - thanos is awesome thank you guys! ;)
And could we reevaluate this is issue?  To give and example where this happens as well:

Using K8s nodeport service where multiple IPs point to the same store/query pod.

**Comment by bwplotka** [comment]
Sure! Let's investigate if you still repro this. Help wanted :hugs:

**Comment by Pesir** [comment]
sure here is the information. pretty similar with the original except ipv4 only. hope this helps. 
**Thanos, Prometheus and Golang version used**:
docker.io/thanosio/thanos:v0.12.2

**Object Storage Provider**:
gcs

**What happened**:
when the local querier accesses the 2nd querier inside the k8s via nodeport service, PromQL queries time out or result in partial responses.

**What you expected to happen**:
normal responsive queries.

**Setup**:
having mutliple different ips forward to the same thanos query service:
local query instance ----> k8s query instance (3 ips)

**How to reproduce it (as minimally and precisely as possible)**:
for example through:
expose the (1 replica) query instance in k8s via a nodeport service
-- or --
(not tested) give a container 3 ips 

creating a dns srv record + an A record with mutliple ips


```
grpc.thanos.gcp.example.com   1200    IN      SRV     1 20 30404 server01.example2.com.
server01.example2.com.         3600    IN      A       10.121.9.216
server01.example2.com.         3600    IN      A       10.121.9.218	
server01.example2.com.         3600    IN      A       10.121.9.217
```

(when the additional ip records are removed this setup works fine)

setting local querier 
`
--store=dnssrv+grpc.thanos.gcp.example.com
`


**Full logs to relevant components**:

the logs from the k8s querier side dont show any information.

The following logs are from the local query instance - the labels are changed.

<details>
<p>

```

level=warn ts=2020-05-04T08:53:48.660483028Z caller=proxy.go:453 err="receive series from Addr: 10.121.9.219:30118 LabelSets: {cluster="example1", location="cloud", replica="A"} Mint: 1579111200000 Maxt: 9223372036854775807: rpc error: code = Canceled desc = context canceled" msg="returning partial response"
level=warn ts=2020-05-04T08:53:48.871095765Z caller=proxy.go:453 err="failed to receive any data from Addr: 10.121.9.216:30118 LabelSets: {cluster="example1", location="cloud", replica="A"} Mint: 1579111200000 Maxt: 9223372036854775807: context canceled" msg="returning partial response"
level=warn ts=2020-05-04T08:53:48.871264387Z caller=proxy.go:453 err="failed to receive any data from Addr: 10.121.9.219:30118 LabelSets: {cluster="example1", location="cloud", replica="A"} Mint: 1579111200000 Maxt: 9223372036854775807: context canceled" msg="returning partial response"
level=warn ts=2020-05-04T08:53:48.871349964Z caller=proxy.go:453 err="receive series from Addr: 10.121.9.217:30118 LabelSets: {cluster="example1", location="cloud", replica="A"} Mint: 1579111200000 Maxt: 9223372036854775807: rpc error: code = Canceled desc = context canceled" msg="returning partial response"
level=warn ts=2020-05-04T08:53:49.083421245Z caller=proxy.go:453 err="failed to receive any data from Addr: 10.121.9.216:30118 LabelSets: {cluster="example1", location="cloud", replica="A"} Mint: 1579111200000 Maxt: 9223372036854775807: context canceled" msg="returning partial response"
level=warn ts=2020-05-04T08:53:49.083491547Z caller=proxy.go:453 err="failed to receive any data from Addr: 10.121.9.217:30118 LabelSets: {cluster="example1", location="cloud", replica="A"} Mint: 1579111200000 Maxt: 9223372036854775807: context canceled" msg="returning partial response"
level=warn ts=2020-05-04T08:53:49.083461563Z caller=proxy.go:453 err="receive series from Addr: 10.121.9.219:30118 LabelSets: {cluster="example1", location="cloud", replica="A"} Mint: 1579111200000 Maxt: 9223372036854775807: rpc error: code = Canceled desc = context canceled" msg="returning partial response"
level=warn ts=2020-05-04T08:55:03.38414351Z caller=storeset.go:440 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from 10.121.9.216:30118: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=10.121.9.216:30118
level=info ts=2020-05-04T08:55:03.384597984Z caller=storeset.go:360 component=storeset msg="removing store because it's unhealthy or does not exist" address=10.121.9.216:30118 extLset="{cluster="example1", location="cloud", replica="A"}"
level=warn ts=2020-05-04T08:55:03.384776011Z caller=proxy.go:453 err="receive series from Addr: 10.121.9.216:30118 LabelSets: {cluster="example1", location="cloud", replica="A"} Mint: 1579111200000 Maxt: 9223372036854775807: rpc error: code = Canceled desc = grpc: the client connection is closing" msg="returning partial response"
level=warn ts=2020-05-04T08:55:03.384902065Z caller=proxy.go:453 err="receive series from Addr: 10.121.9.216:30118 LabelSets: {cluster="example1", location="cloud", replica="A"} Mint: 1579111200000 Maxt: 9223372036854775807: rpc error: code = Canceled desc = grpc: the client connection is closing" msg="returning partial response"
level=info ts=2020-05-04T08:55:03.414442417Z caller=storeset.go:384 component=storeset msg="adding new storeAPI to query storeset" address=10.121.9.216:30118 extLset="{cluster="example1", location="cloud", replica="A"}"
level=warn ts=2020-05-04T08:56:16.827457802Z caller=proxy.go:453 err="receive series from Addr: 10.121.9.219:30118 LabelSets: {cluster="example1", location="cloud", replica="A"} Mint: 1579111200000 Maxt: 9223372036854775807: rpc error: code = Internal desc = unexpected EOF" msg="returning partial response"
level=warn ts=2020-05-04T08:59:37.051939594Z caller=proxy.go:453 err="receive series from Addr: 10.121.9.216:30118 LabelSets: {cluster="example1", location="cloud", replica="A"} Mint: 1579111200000 Maxt: 9223372036854775807: rpc error: code = Internal desc = unexpected EOF" msg="returning partial response"
level=warn ts=2020-05-04T08:59:38.427084806Z caller=proxy.go:453 err="receive series from Addr: 10.121.9.217:30118 LabelSets: {cluster="example1", location="cloud", replica="A"} Mint: 1579111200000 Maxt: 9223372036854775807: rpc error: code = Internal desc = unexpected EOF" msg="returning partial response"

```
</p>
</details>

under the store page the k8s querier shows up 3 time with each ip.
