### ISSUE TITLE
Compactor: Improve compactor for large buckets.

### ISSUE THREAD

**Issue by jdfalk** [thanos-io/thanos#1535]
**Thanos, Prometheus and Golang version used**

thanos, version 0.7.0 (branch: master, revision: bfb56455d35ed3aaf7aa7423b04ecf4d17e282e0)
  build user:       root@build
  build date:       20190917-12:41:56
  go version:       go1.13

**What happened**
Thanos compact appears to have stopped compacting our data

**What you expected to happen**
That blocks would be compacted

**How to reproduce it (as minimally and precisely as possible)**:
Put 30-40TB of prometheus data in S3 and run compactor against it. 

**Full logs to relevant components**

<details>Logs
<p>

thanos[3024]: level=debug ts=2019-09-16T20:41:53.431663614Z caller=compact.go:252 msg="download meta" block=01DB6SMGN6AFEK5C3V3ZGKT3F6
thanos[3024]: level=debug ts=2019-09-16T20:41:53.432097193Z caller=compact.go:252 msg="download meta" block=01DB6SMGP0M9Z0TDQPZ6BCW3M1
thanos[3024]: level=debug ts=2019-09-16T20:41:53.43226211Z caller=compact.go:252 msg="download meta" block=01DB6SMGP9A7V95A3X10YEK2HH
thanos[3024]: level=debug ts=2019-09-16T20:41:53.433515873Z caller=compact.go:252 msg="download meta" block=01DB70G7WFX6WCGFW7BWBY60T2
thanos[3024]: level=debug ts=2019-09-16T20:41:53.437089281Z caller=compact.go:252 msg="download meta" block=01DB70G7X7DW71FBE7Z5MGKH8R
thanos[3024]: level=debug ts=2019-09-16T20:41:53.437218675Z caller=compact.go:252 msg="download meta" block=01DB70G7Y06PM5HFYW0WH33ERH
thanos[3024]: level=debug ts=2019-09-16T20:41:53.43730488Z caller=compact.go:252 msg="download meta" block=01DB70G7Y95E315ZNDY6ZCX4N9
thanos[3024]: level=debug ts=2019-09-16T20:41:53.437603424Z caller=compact.go:252 msg="download meta" block=01DB77BZ4FCQQM9SGWNWYBD6BW
thanos[3024]: level=debug ts=2019-09-16T20:41:53.437995873Z caller=compact.go:252 msg="download meta" block=01DB77BZ58NHHF4KK0J060YR8B
thanos[3024]: level=info ts=2019-09-16T20:48:59.257981823Z caller=compact.go:249 msg="compaction iterations done"
thanos[3024]: level=info ts=2019-09-16T20:48:59.258052001Z caller=compact.go:256 msg="start first pass of downsampling"
thanos[3024]: level=info ts=2019-09-16T20:51:28.56657839Z caller=compact.go:262 msg="start second pass of downsampling"
thanos[3024]: level=info ts=2019-09-16T20:53:43.957377883Z caller=compact.go:267 msg="downsampling iterations done"
thanos[3024]: level=info ts=2019-09-16T20:53:43.957438066Z caller=retention.go:17 msg="start optional retention"
thanos[3024]: level=info ts=2019-09-16T20:55:56.169398681Z caller=retention.go:46 msg="optional retention apply done"
thanos[3024]: level=info ts=2019-09-16T20:56:00.461389288Z caller=compact.go:1023 msg="start sync of metas"
thanos[3024]: level=debug ts=2019-09-16T20:56:00.880839602Z caller=compact.go:252 msg="download meta" block=01DMXG8JMK5FPEHN5460M00X9N
thanos[3024]: level=debug ts=2019-09-16T20:56:00.881017914Z caller=compact.go:252 msg="download meta" block=01DMXQ49WK03KRRN1PMPZPQ7VV
thanos[3024]: level=debug ts=2019-09-16T20:56:00.881064634Z caller=compact.go:252 msg="download meta" block=01DMXG8JP50J8TAZXMTQKYP790
thanos[3024]: level=debug ts=2019-09-16T20:56:00.881072536Z caller=compact.go:252 msg="download meta" block=01DMXQ49Y4DJ67EXKZH4RZEH0X
thanos[3024]: level=debug ts=2019-09-16T20:56:00.881017908Z caller=compact.go:252 msg="download meta" block=01DMXG8JN9QRK12V0V0M6WDGW3
thanos[3024]: level=debug ts=2019-09-16T20:56:00.881110077Z caller=compact.go:252 msg="download meta" block=01DMXQ49X7MEYJ267VJGQ4K487
thanos[3024]: level=debug ts=2019-09-16T20:56:00.892226775Z caller=compact.go:274 msg="block is too fresh for now" block=01DMXG8JMK5FPEHN5460M00X9N
thanos[3024]: level=debug ts=2019-09-16T20:56:00.9200006Z caller=compact.go:274 msg="block is too fresh for now" block=01DMXQ49WK03KRRN1PMPZPQ7VV
thanos[3024]: level=debug ts=2019-09-16T20:56:00.920853092Z caller=compact.go:274 msg="block is too fresh for now" block=01DMXQ49X7MEYJ267VJGQ4K487
thanos[3024]: level=debug ts=2019-09-16T20:56:00.921035647Z caller=compact.go:274 msg="block is too fresh for now" block=01DMXG8JN9QRK12V0V0M6WDGW3
thanos[3024]: level=debug ts=2019-09-16T20:56:00.924548757Z caller=compact.go:274 msg="block is too fresh for now" block=01DMXG8JP50J8TAZXMTQKYP790
thanos[3024]: level=debug ts=2019-09-16T20:56:00.94546063Z caller=compact.go:274 msg="block is too fresh for now" block=01DMXQ49Y4DJ67EXKZH4RZEH0X
thanos[3024]: level=info ts=2019-09-16T20:56:00.946113693Z caller=compact.go:1029 msg="start of GC"
thanos[3024]: level=info ts=2019-09-16T20:56:00.951901639Z caller=compact.go:1035 msg="start of compaction"

</p>
</details>

**Anything else we need to know**
We have a very large prometheus environment and use thanos to provide a single pane of glass to several departments. I have attached a list of our blocks from thanos inspect. I would have expected to see blocks from June being compacted by now. Remove the .txt, added because github doesn't support tsv.

[thanos-us-block-scrubbed.tsv.txt](https://github.com/thanos-io/thanos/files/3622492/thanos-us-block-scrubbed.tsv.txt)

**Environment**:

- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

- Kernel (e.g. `uname -a`):
```Linux thanos 4.15.0-1044-aws #46-Ubuntu SMP Thu Jul 4 13:38:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by krasi-georgiev** [comment]
I assume you started the compactor with the `--wait` flag right?

can you provide the full cmd args used to start the compactor.

Had a quick look and the only other thing that I see which might affect the compaction is if you have some custom `--debug.max-compaction-level`

**Comment by jdfalk** [comment]
```
ExecStart=/usr/local/bin/thanos compact \
  --http-address=0.0.0.0:13902 \
  --data-dir=/var/lib/thanos/ \
  --consistency-delay=240m \
  --wait \
  --objstore.config-file=/etc/thanos/bucket.yaml \
  --retention.resolution-raw=365d \
  --block-sync-concurrency=24 \
  --compact.concurrency=12 \
  --log.level=debug
```

**Comment by jdfalk** [comment]
I'm running a verify on the whole bucket right now but as you'd expect it's taking some time. I've found one block that doesn't have an index file so I removed that and am rerunning verify. It would be nice if verify would 
1) Allow you to resume from where you left off 
2) not die the first second it encounters an error and process the rest of the bucket so you can see all errors

**Comment by krasi-georgiev** [comment]
both very good ideas. maybe using some local cache could solve one of the problems and for the other one show some warn logs instead of exiting.
as usual PR is more than welcome :+1:

**Comment by krasi-georgiev** [comment]
maybe examine the liveness probe and/or the `thanos_compactor_halted`, `thanos_compactor_retries_total` metrics.

**Comment by yershalom** [comment]
@krasi-georgiev I know it's related... but I don't these metrics that you mentioned. Is it out-of-the-box metrics? Or do I need to collect them with prometheus?

**Comment by bwplotka** [comment]
Thanks for this. I renamed the issue a bit.

AC:
* Allow you to resume from where you left off (better retry)
* Not die the first second it encounters an error and process the rest of the bucket so you can see all errors

There is workaround you can do now which is compactor sharding. Explained a bit here: https://thanos.io/proposals/201909_thanos_sharding.md/
