### ISSUE TITLE
Thanos and Promethus POD

### ISSUE THREAD

**Issue by kapilgarg83** [thanos-io/thanos#1536]
Hi,

I have running Prometheus server that is deployed using helm.
Now I want to implement thnos separately without changing Prometheus setup.

Can I launch a separate pod for thanos side car.?
or any better idea or suggestion on this as I did not find any stable chart on the helm for thanos.?

**Comment by bwplotka** [comment]
There are some chart you want to try: https://github.com/helm/charts/pull/13085 or those available here: https://hub.helm.sh/charts?q=thanos (:
