### ISSUE TITLE
sidecar and query performance loss problem

### ISSUE THREAD

**Issue by hhy5861** [thanos-io/thanos#1542]
Recently experienced performance loss problems, 12 hours of data on prometheus is still very fast. But after connecting to onos sidecar and query. Only one hour of data can be checked through the query. Is the performance loss so big?

version: 0.7.0

query config:
./thanos query \
  --http-address 0.0.0.0:19192 \
  --store        x.x.x.x:19090 \
  --store        x.x.x.x:19090 \
  --store        x.x.x.x:19090 \
  --query.timeout 5m \
  --store.response-timeout 5m \
  --store.sd-interval 30m \
  --query.max-concurrent 500 \
  --query.default-evaluation-interval 3s

sidecar config:
./thanos sidecar \
  --tsdb.path /data/database/prometheus \
  --prometheus.url http://localhost:9090 \
  --reloader.config-envsubst-file /data/prometheus/prometheus.yml \
  --http-address 0.0.0.0:19090
  --grpc-address 0.0.0.0:19090

**Comment by GiedriusS** [comment]
Hi, are you running Thanos Compact on your remote object storage?

**Comment by hhy5861** [comment]
> Hi, are you running Thanos Compact on your remote object storage? Plus, don't forget that you need Thanos Store. And the performance has been improved by a lot recently, try out the master version of Prometheus with Thanos 0.7.0.

prometheus, version 2.12.0
thanos 0.7.0

Thank you! I am trying to run Compact and Store to see.

**Comment by hhy5861** [comment]
> Hi, are you running Thanos Compact on your remote object storage? Plus, don't forget that you need Thanos Store. And the performance has been improved by a lot recently, try out the master version of Prometheus with Thanos 0.7.0.

Can thanos store use local ssd for storage?

**Comment by hhy5861** [comment]
> Hi, are you running Thanos Compact on your remote object storage? Plus, don't forget that you need Thanos Store. And the performance has been improved by a lot recently, try out the master version of Prometheus with Thanos 0.7.0.

I feel that even if I don't need a store and a compact, I only use the three rounds and the query performance is not so bad.

**Comment by krasi-georgiev** [comment]
upstream Prometheus 2.12 doesn't include the remote read streaming(it will be added in 2.13) so to use the optimizations right now can use: quay.io/thanos/prometheus:v2.12.0-rc.0-rr-streaming

**Comment by GiedriusS** [comment]
> > Hi, are you running Thanos Compact on your remote object storage? Plus, don't forget that you need Thanos Store. And the performance has been improved by a lot recently, try out the master version of Prometheus with Thanos 0.7.0.
> 
> Can thanos store use local ssd for storage?

It can but it's only used for storing the cache of blocks that you have in your remote object storage. AFAICT you have solved this problem @hhy5861?

**Comment by hhy5861** [comment]
> > > Hi, are you running Thanos Compact on your remote object storage? Plus, don't forget that you need Thanos Store. And the performance has been improved by a lot recently, try out the master version of Prometheus with Thanos 0.7.0.
> > 
> > 
> > Can thanos store use local ssd for storage?
> 
> It can but it's only used for storing the cache of blocks that you have in your remote object storage. AFAICT you have solved this problem @hhy5861?

problem is not solved! But I added a new problem with store and compact. If you query for 1 hour, you will still lose some of the indicators of the node. However, the 3-hour job indicator can be checked, but the last two hours of data will be lost. Very strange. I am going to find a problem from the source code.

**Comment by jojohappy** [comment]
@hhy5861 Could you see the `stores` page in your Query UI? Are the status of all of sidecars and stores `UP`?

**Comment by hhy5861** [comment]
> @hhy5861 Could you see the `stores` page in your Query UI? Are the status of all of sidecars and stores `UP`?

store can be queried normally.
the store server is normal. There is always a lack of 2 hours of data.

**Comment by jojohappy** [comment]
@hhy5861 is your sidecar healthy? The last 2 hours metrics normally from sidecar(Prometheus instances) by remote read api.

**Comment by hhy5861** [comment]
> @hhy5861 is your sidecar healthy? The last 2 hours metrics normally from sidecar(Prometheus instances) by remote read api.

Sidecar is normal. The strange thing is that only after 3 hours of data is checked, the last 2 hours of data is not available.

**Comment by hhy5861** [comment]
> @hhy5861 is your sidecar healthy? The last 2 hours metrics normally from sidecar(Prometheus instances) by remote read api.

probably the problem should be to check the store for 3 hours, and not to go to prometheus for nearly 2 hours.
this question should be a query question. Still in the process of investigation
