### ISSUE TITLE
Summary quantiles are not exposed anymore for certain metrics in thanos-query

### ISSUE THREAD

**Issue by bandesz** [thanos-io/thanos#1543]
**Thanos, Prometheus and Golang version used**

Thanos version: 0.6.1
Prometheus version: 2.6.1

**What happened**

prometheus_engine_query_duration_seconds isn't exposed anymore with the `{app="thanos-query"}` label. (examples/grafana/thanos-query.json refers to this).

Was this metric removed? (I couldn't find anything relevant in the changelogs.)
Can this be a problem of the Prometheus+Thanos version combo we're using?

**Edit**: The following metrics doesn't have the quantiles reported anymore:
 * prometheus_engine_query_duration_seconds
 * http_request_size_bytes
 * http_response_size_bytes

**Comment by bwplotka** [comment]
Hm. I can see it being exposed on our services as `summary`. Maybe no query was triggered against this Querier that's why?

I can see `prometheus_engine_query_duration_seconds_count` and `prometheus_engine_query_duration_seconds_sum`

**Comment by GiedriusS** [comment]
Indeed, I see those metrics on `0.7.0`. Perhaps you need to run at least one query like @bwplotka says.

**Comment by bandesz** [comment]
I still see `prometheus_engine_query_duration_seconds_count` and  `prometheus_engine_query_duration_seconds_sum` but previously we had the quantiles, e.g.:

```prometheus_engine_query_duration_seconds{quantile="0.99",slice="result_sort"}```

Where did that go?

**Comment by bandesz** [comment]
I think this is caused by https://github.com/thanos-io/thanos/pull/1314.

The following metrics also doesn't have the quantiles reported anymore: http_request_size_bytes and http_response_size_bytes.
