### ISSUE TITLE
where to add s3 sccess and secret key..??

### ISSUE THREAD

**Issue by kapilgarg83** [thanos-io/thanos#1554]
Hi,

There is no sidecar  container in statefull set of server its only in deployment.??
Also where to give s3 access key etc.. itn not mention anywhere in value.yaml under s3 config.
Please suggest

**Comment by GiedriusS** [comment]
Hey there! I'm sorry that you ran into problems, we can always do better with the documentation. I don't use K8s much myself but for Sidecar and other components we have the flags which start with: `--objstore.*`. By using them, you can specify the file with the bucket configuration or the actual configuration itself :smile: I hope that helps.

**Comment by obiesmans** [comment]
This doc should help : https://github.com/thanos-io/thanos/blob/master/docs/storage.md#s3
