### ISSUE TITLE
Question: Thanos server architecture not in Kubernetes

### ISSUE THREAD

**Issue by yershalom** [thanos-io/thanos#1557]
Hi,

First, amazing project so thanks!

And now for my question.
Today we are using prometheus in production and we got to the point that we need HA solution for that. 
We don't have kubernetes (yet) but we are running everything with docker.
I want to deploy Thanos and I wanted to ask which components needs to run together on the same server and which on different servers. (Prometheus + sidecar) + (Ruler) + (Querier) + (Storage API) + (Compactor). Should be like this?

And another question, I have the prometheus behind load balancer, is it ok to pass the lb address to file sd? As in here: https://github.com/thanos-io/thanos/blob/master/docs/service-discovery.md#file-service-discovery

Thanks!

**Comment by JonasDeGendt** [comment]
Hey,

[This article](https://improbable.io/blog/thanos-architecture-at-improbable) is a great starting point when deciding on an architecture. In your case, I'd plug the sidecar on the machines running your Prometheus servers, and set up all the other Thanos components on a dedicated machine. 

I can't provide an answer to your second question though.

**Comment by yershalom** [comment]
Thanks @JonasDeGendt
