### ISSUE TITLE
ruler: alertmanager.url `+` symbol in password for basic auth interprets start of url as lookup scheme

### ISSUE THREAD

**Issue by ivotimev** [thanos-io/thanos#1564]
Encountered on Thanos v0.7.0

Running 
```bash
docker run thanosio/thanos:v0.7.0 rule 
    --alertmanagers.url=https://user:pass+word@domain.com 
    --query=sample.com
``` 
as password contains a '+', the part of the url up to the plus gets interpreted as a lookup scheme causing an error 
```
level=error ts=2019-09-24T15:43:08.687515899Z caller=rule.go:360 msg="refreshing alertmanagers failed" err="alertmanager resolve: invalid lookup scheme \"https://user:pass\""
```

**Comment by FUSAKLA** [comment]
Hi, yeah that seems to be a bug in parsing the address sorry about it. The `+` is used to delimit DNS SD type in the address co it 

https://github.com/thanos-io/thanos/blob/749b378d408094c4472c11d0255bbda30d99e513/cmd/thanos/rule.go#L626-L628

**Comment by FUSAKLA** [comment]
Hi, yeah that seems to be a bug in parsing the address, sorry about it. The `+` is used to delimit DNS SD type in the address.

https://github.com/thanos-io/thanos/blob/749b378d408094c4472c11d0255bbda30d99e513/cmd/thanos/rule.go#L626-L628

**Comment by ivotimev** [comment]
A workaround I'm using for now is to prefix the url with a '+', which appears to work.

**Comment by FUSAKLA** [comment]
@ivotimev should be fixed in master now so you can try it out.
 In case the issue would persist, please feel free to open the issue again.
