### ISSUE TITLE
compactor should skip error bucket and continue to compact other buckets

### ISSUE THREAD

**Issue by Wing924** [thanos-io/thanos#1574]
**Thanos, Prometheus and Golang version used**
Thanos v0.7.0
Prometheus 1.12.0

**What happened**
compact stops on error state:
```
level=error ts=2019-09-26T08:53:38.437788092Z caller=main.go:213 msg="running command failed" err="error executing compaction: compaction failed: compaction failed for group 0@{monitor=\"worker-4\",replica=\"a\"}: compact blocks [/cache/compact/0@{monitor=\"worker-4\",replica=\"a\"}/01DKQQRPP0C79RN0DH0DPAARX1 /cache/compact/0@{monitor=\"worker-4\",replica=\"a\"}/01DKRWJT6GPN212X3H8FKC8BQ8 /cache/compact/0@{monitor=\"worker-4\",replica=\"a\"}/01DKSQZ1VX0P2HGSBVPBWBD1TA /cache/compact/0@{monitor=\"worker-4\",replica=\"a\"}/01DKTKCRQNNQSZN5TSZWE9NY9D]: write compaction: chunk 8 not found: reference sequence 0 out of range"
```

**What you expected to happen**
I know it's known problem #1331 but compact should skip this rather than exit 1.
Restarting compactor don't solve this issue because it get same error and exit and other buckets don't get compact.

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

```
level=error ts=2019-09-26T08:53:38.437788092Z caller=main.go:213 msg="running command failed" err="error executing compaction: compaction failed: compaction failed for group 0@{monitor=\"worker-4\",replica=\"a\"}: compact blocks [/cache/compact/0@{monitor=\"worker-4\",replica=\"a\"}/01DKQQRPP0C79RN0DH0DPAARX1 /cache/compact/0@{monitor=\"worker-4\",replica=\"a\"}/01DKRWJT6GPN212X3H8FKC8BQ8 /cache/compact/0@{monitor=\"worker-4\",replica=\"a\"}/01DKSQZ1VX0P2HGSBVPBWBD1TA /cache/compact/0@{monitor=\"worker-4\",replica=\"a\"}/01DKTKCRQNNQSZN5TSZWE9NY9D]: write compaction: chunk 8 not found: reference sequence 0 out of range"
```

**Anything else we need to know**

**Comment by krasi-georgiev** [comment]
> Restarting compactor don't solve this issue because it get same error and exit and other buckets don't get compact.

this is probably because the block is cached locally. Try deleting the local cache folder and start the compactor again.
The workaround until the proper fix should probably be that the compactor should try to re-download the block after some time and keep retrying to compact.

**Comment by bwplotka** [comment]
Also it should be fixed on master (there was problem with cancelled deletions that was corrupting local disk)
