### ISSUE TITLE
compact: Partially uploaded blocks should not be deleted

### ISSUE THREAD

**Issue by dupondje** [thanos-io/thanos#1577]
thanos, version 0.7.0 (branch: HEAD, revision: c6eaf68bec32aefd280318eaef6121d6ddb20d10)
  build user:       root@aa355daaf987
  build date:       20190902-15:31:30
  go version:       go1.12.5

**What happened**
Our S3 bucket (via Minio) was down for a couple of days. We fixed it, and blocks were getting uploaded again by the sidecar process.

But we have a compact running with --wait, so it continuously check to compact blocks.
This works fine, but went wrong due to older blocks getting uploaded now.

A block that was getting uploaded, got deleted by the compact process:
thanos[523]: level=info ts=2019-09-26T09:12:10.994606305Z caller=compact.go:303 msg="deleted malformed block" block=01DNK5RYZZMWV2CQN50BG0GYVH

And compaction started to fail:
thanos[523]: level=warn ts=2019-09-26T09:31:33.403993848Z caller=prober.go:154 msg="changing probe status" status=unhealthy reason="error executing compaction: compaction failed: compaction failed for group 0@{replica=\"A\"}: gather index issues for block /var/tmp/data/compact/0@{replica=\"A\"}/01DNK5RYZZMWV2CQN50BG0GYVH: open index file: try lock file: open /var/tmp/data/compact/0@{replica=\"A\"}/01DNK5RYZZMWV2CQN50BG0GYVH/index: no such file or directory"
thanos[523]: level=error ts=2019-09-26T09:31:33.409340587Z caller=main.go:213 msg="running command failed" err="error executing compaction: compaction failed: compaction failed for group 0@{replica=\"A\"}: gather index issues for block /var/tmp/data/compact/0@{replica=\"A\"}/01DNK5RYZZMWV2CQN50BG0GYVH: open index file: try lock file: open /var/tmp/data/compact/0@{replica=\"A\"}/01DNK5RYZZMWV2CQN50BG0GYVH/index: no such file or directory"

**What you expected to happen**
There should be some logic inside Thanos that doesn't process blocks yet that are getting uploaded. Cause now it deleted a block that was still getting uploaded with all problems related.

**How to reproduce it (as minimally and precisely as possible)**:
Kill your bucket for more then --consistency-delay of the compactor, and start it again.
Blocks are getting uploaded and the compactor processes/deletes them directly.

**Anything else we need to know**
I got it fixed by stopping the compactor and let the sidecar ship the deleted block again.
But it would be nice if this was handled more cleanly :)

**Comment by krasi-georgiev** [comment]
Could you read  @bwplotka's proposal and note if this will solve this case?
https://github.com/thanos-io/thanos/blob/master/docs/proposals/201901-read-write-operations-bucket.md

if it is already mentioned in the proposal than can close it as a duplicate.

**Comment by dupondje** [comment]
I checked the proposal, but this doesn't seem to match this case.
The biggest problem is that it checks the ulid to see if the block is older than the delay.

But if for some reason blocks were not uploaded to the bucket within that delay, it seems like it will still remove the blocks because it thinks they are broken.

**Comment by krasi-georgiev** [comment]
thanks. than I will let @bwplotka comment on this.

**Comment by krasi-georgiev** [comment]
@dupondje or could you maybe give some idea on how do you think this can be solved?

**Comment by dupondje** [comment]
I don't know if its possible to check the modified time of the blocks instead of just checking the ulid?
And only delete/compact/whatever the block if now() - ulid > delay && now() - ulid > delay?

This way you don't process just uploaded blocks.
