### ISSUE TITLE
store: insufficient byte pool size when loading buckets

### ISSUE THREAD

**Issue by jabbrwcky** [thanos-io/thanos#1580]
The thanos-querier of our installation failed yesterday, caused by an `allocate chunk bytes: pool exhausted` error.

Inspection revealed that the pool.BytesPool is using a range of pooled `[]byte` sizes from `2e5` (200KiB) to `5e6` (500MiB).

The `bucketChunkReader` requests `[]byte` of 16000 bytes that are handed the smallest possible pooled buffer (200KiB) causing each `[]byte` requested from the pool to occupy 184 KiB more than required for the read 16000 bytes.

This means that in our current installation with a max. pool size of 4GiB the pool can only accomodate 21.474 chunks (327,67 MiB), which is too small for chunks up to ~500 MiB.

**Used Thanos version: Thanos 0.7.0**

master branch still has these settings.

The store should either reduce the minimal sizer to the used size or ditch the BytesPool in favour of directly using sync.Pool for the required slices of the given size.

As far as I can tell, the Store is the only user of `pool.BytesPool` in the codebase.

**Comment by der-eismann** [comment]
We ran into the same error message, although we didn't dig that deep, so I'm not sure if the cause is the same. Maybe some guide to choose a correct `chunk-pool-size` value would help - we set it to 8 GB already and after 4 days we hit the described error. I just counted our bucket - we have ~2100 objects à 512 MB with a total size of 1,16 TB.
We also use thanos 0.7.0.

**Comment by bwplotka** [comment]
ACK nice finding!

Definitely something to improve. We are working on rewriting this part as https://github.com/thanos-io/thanos/issues/1471 initiative, so this is really important info.

Sounds like for a short term workaround we could try allowing smaller bucket, approved your PR.

cc @zhulongcheng @ppanyukov
