### ISSUE TITLE
feature request: selectively avoid downsampling, keep high resolution metrics for configured time periods

### ISSUE THREAD

**Issue by jfreeland** [thanos-io/thanos#1589]
Sorry for the noise if this is already possible.

I'm wondering if it's possible to configure and/or set time periods where I would like to avoid having metrics downsampled over time and keep high resolution metrics for various things during some period of time.

For instance, if I have a major outage and want to be able to go back and reference the 1m resolution for months on end, but my standard 30m,5m,1m would downsample the data after a couple weeks.

Or if I have a large event and I want to be able to reference this data the following year at the same time.

**What happened**

Today, my data gets downsampled as configured.

**What you expected to happen**

I expect to have the ability to configure (either beforehand or after the fact) that, for instance, from 2019-09-30 12:35:00 to 2019-09-30 14:15:00 I never want this data downsampled.

**Comment by krasi-georgiev** [comment]
Why not just make a backup of those blocks and open them separately from the production deployment? I think those will load even on a vanilla Prometheus.

**Comment by jfreeland** [comment]
Thanks Krasi.

Bartek also responded to my inquiry via Slack today.  He pointed out that downsampling does not actually remove any data but rather the optional retention that does, and if I want to avoid having events downsampled, I could just keep all resolutions/data forever.

Your feedback also makes sense and I will explore using this option longer term as well.

**Comment by krasi-georgiev** [comment]
Thanks. In that case might be best to close the issue, try the suggestions and reopen if it doesn't solve your use case.
