### ISSUE TITLE
recieve: Panics

### ISSUE THREAD

**Issue by dtrejod** [thanos-io/thanos#1594]
**Thanos, Prometheus and Golang version used**
```sh
$ ./thanos --version
thanos, version 0.7.0 (branch: master, revision: baf2f3a03757c0260250d93aa8ef41a79a829bb6)
  build user:       circleci@54f32563bbc6
  build date:       20191001-13:19:04
  go version:       go1.12.5
```

Prometheus version 2.12.0

**What happened**

Go routine panic.

**What you expected to happen**

No go routine panic

**How to reproduce it (as minimally and precisely as possible)**:
Simply start a receiver --
```sh
./thanos receive --log.format=logfmt --log.level=debug --tsdb.path=./test/data --objstore.config-file=./test/bucket_config.yml --receive.replication-factor=1
```

**Full logs to relevant components**

<details>Logs
<p>
level=debug ts=2019-10-01T17:51:34.346053081Z caller=main.go:122 msg="maxprocs: Leaving GOMAXPROCS=[8]: CPU quota undefined"
level=info ts=2019-10-01T17:51:34.346457856Z caller=main.go:170 msg="Tracing will be disabled"
level=warn ts=2019-10-01T17:51:34.346500366Z caller=receive.go:143 component=receive msg="setting up receive; the Thanos receive component is EXPERIMENTAL, it may break significantly without notice"
level=debug ts=2019-10-01T17:51:34.346746109Z caller=receive.go:192 component=receive msg="setting up tsdb"
level=info ts=2019-10-01T17:51:34.350840387Z caller=head.go:509 component=receive component=tsdb component=tsdb msg="replaying WAL, this may take awhile"
level=info ts=2019-10-01T17:51:34.351074421Z caller=head.go:557 component=receive component=tsdb component=tsdb msg="WAL segment loaded" segment=0 maxSegment=4
level=info ts=2019-10-01T17:51:34.35128205Z caller=head.go:557 component=receive component=tsdb component=tsdb msg="WAL segment loaded" segment=1 maxSegment=4
level=info ts=2019-10-01T17:51:34.351416083Z caller=head.go:557 component=receive component=tsdb component=tsdb msg="WAL segment loaded" segment=2 maxSegment=4
level=info ts=2019-10-01T17:51:34.352002711Z caller=head.go:557 component=receive component=tsdb component=tsdb msg="WAL segment loaded" segment=3 maxSegment=4
level=info ts=2019-10-01T17:51:34.352230301Z caller=head.go:557 component=receive component=tsdb component=tsdb msg="WAL segment loaded" segment=4 maxSegment=4
level=info ts=2019-10-01T17:51:34.360157392Z caller=head.go:509 component=receive component=tsdb msg="replaying WAL, this may take awhile"
level=info ts=2019-10-01T17:51:34.360413948Z caller=head.go:557 component=receive component=tsdb msg="WAL segment loaded" segment=0 maxSegment=4
level=info ts=2019-10-01T17:51:34.360588495Z caller=head.go:557 component=receive component=tsdb msg="WAL segment loaded" segment=1 maxSegment=4
level=info ts=2019-10-01T17:51:34.360715952Z caller=head.go:557 component=receive component=tsdb msg="WAL segment loaded" segment=2 maxSegment=4
level=info ts=2019-10-01T17:51:34.360832443Z caller=head.go:557 component=receive component=tsdb msg="WAL segment loaded" segment=3 maxSegment=4
level=info ts=2019-10-01T17:51:34.360974741Z caller=head.go:557 component=receive component=tsdb msg="WAL segment loaded" segment=4 maxSegment=4
level=info ts=2019-10-01T17:51:34.374679961Z caller=head.go:509 component=receive component=tsdb component=tsdb msg="replaying WAL, this may take awhile"
level=info ts=2019-10-01T17:51:34.375273668Z caller=head.go:557 component=receive component=tsdb component=tsdb msg="WAL segment loaded" segment=0 maxSegment=5
level=info ts=2019-10-01T17:51:34.3757924Z caller=head.go:557 component=receive component=tsdb component=tsdb msg="WAL segment loaded" segment=1 maxSegment=5
level=info ts=2019-10-01T17:51:34.375991581Z caller=head.go:557 component=receive component=tsdb component=tsdb msg="WAL segment loaded" segment=2 maxSegment=5
level=info ts=2019-10-01T17:51:34.376171243Z caller=head.go:557 component=receive component=tsdb component=tsdb msg="WAL segment loaded" segment=3 maxSegment=5
level=info ts=2019-10-01T17:51:34.37632788Z caller=head.go:557 component=receive component=tsdb component=tsdb msg="WAL segment loaded" segment=4 maxSegment=5
level=info ts=2019-10-01T17:51:34.37643955Z caller=head.go:557 component=receive component=tsdb component=tsdb msg="WAL segment loaded" segment=5 maxSegment=5
level=debug ts=2019-10-01T17:51:34.37734948Z caller=receive.go:250 component=receive msg="setting up hashring"
level=debug ts=2019-10-01T17:51:34.37738744Z caller=receive.go:302 component=receive msg="setting up http server"
level=debug ts=2019-10-01T17:51:34.377648418Z caller=receive.go:308 component=receive msg="setting up grpc server"
level=debug ts=2019-10-01T17:51:34.377683868Z caller=receive.go:353 component=receive msg="setting up receive http handler"
level=info ts=2019-10-01T17:51:34.377706991Z caller=factory.go:39 component=receive msg="loading bucket configuration"
level=info ts=2019-10-01T17:51:34.400789386Z caller=receive.go:432 component=receive msg="starting receiver"
panic: send on closed channel

goroutine 481 [running]:
main.runReceive.func5(0xc000155440, 0x0)
        /go/src/github.com/thanos-io/thanos/cmd/thanos/receive.go:269 +0x77
github.com/oklog/run.(*Group).Run.func1(0xc00298ec00, 0xc0024900f0, 0xc0000b30e0)
        /go/pkg/mod/github.com/oklog/run@v1.0.0/group.go:38 +0x27
created by github.com/oklog/run.(*Group).Run
        /go/pkg/mod/github.com/oklog/run@v1.0.0/group.go:37 +0xbe
</details>

**Anything else we need to know**
Issue arose since merging - https://github.com/thanos-io/thanos/pull/1480

CC @squat

**Comment by squat** [comment]
Yes, I see exactly what is wrong. It’s a one-like fix. I’ll submit a PR
ASAP.
