### ISSUE TITLE
Delete series for object storage.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#1598]
**Goals:**
* Allow Delete series from blocks kept in an object storage

**Use cases:**
* GDPR
* Delete corrupted / cardinality bomb series
* Series based retention! (e.g aggregates: https://github.com/thanos-io/thanos/issues/903)

**Related:**
* https://github.com/thanos-io/thanos/issues/415 - /delete_series for sidecar
* https://github.com/thanos-io/thanos/issues/903 - aggr based retention

It's a dry issue, design to come. (:

**Comment by bwplotka** [comment]
Challenges:
* How to handle long-running job for that? Should it be compactor? How to coordinate with the compactor if not? How to measure progress?
* Is it even worth to add tombstones logic? 
  * For GDPR we care of data complete removal, not just unvisible
  * For aggr retention as well - we care about data size. Tombstones will only slow all down and add size.

**Comment by SuperQ** [comment]
My opinion:
* The compactor seems like the right place for this.
* I think following the tombstones logic is fine. It works well for Prometheus itself.
* Adding the `clean_tombstones` endpoint/function is probably the right way to deal with purging if necessary.

**Comment by bwplotka** [comment]
Yup @SuperQ 

As we talked offline tombstones are probably no go, as they are not immutable. At least not in the form that is implemented in Prometheus. We might be though able to add deletion requests to each block, then having a compactor to include that during compaction and lazy rewrite. It would be nice to have some solution that will also fit https://github.com/thanos-io/thanos/issues/903

**Comment by bwplotka** [comment]
Still valid. Help wanted.

**Comment by SidharthBansal** [comment]
Hello, I am looking forward to contributing to this for GSoC 2020. How shall I start?

**Comment by infa-kparida** [comment]
This will be a super useful feature for decommissioning  prometheus clusters.Looking forward to it +1

**Comment by bwplotka** [comment]
Good point! 

Looks like we did not find anyone for GSoC, we will try with Summer Community Bridge. (:

**Comment by SidharthBansal** [comment]
What is the timeline for `Summer Community Bridge` and what is the link where I can apply?

**Comment by bwplotka** [comment]
@idvoretskyi might know more.

**Comment by idvoretskyi** [comment]
@bwplotka we'll announce this later in April/early May.

**Comment by SidharthBansal** [comment]
Great thanks

**Comment by idvoretskyi** [comment]
@SidharthBansal in the meantime, feel to track the repo https://github.com/cncf/soc/tree/master/communitybridge; we'll post the updates there.

**Comment by SidharthBansal** [comment]
Ok thanks for the link.
Just want to ask a question. My college is till 30 June 2020, then I have
summer vacations. So, will I be eligible for community bridge?

**Comment by idvoretskyi** [comment]
@SidharthBansal we don't have any specific college-related restrictions.

Also, please see - https://docs.linuxfoundation.org/docs/communitybridge-mentorship/mentees#Mentees-EligibilityRules.

**Comment by SidharthBansal** [comment]
That's great!

**Comment by SidharthBansal** [comment]
what does
> Not be subject to any existing obligations to third parties (such as
contractual obligations to an employer) that would restrict or prohibit
your participation in the Mentorship program

this criterion mean?

**Comment by idvoretskyi** [comment]
@SidharthBansal I assume this discussion is out of scope for this repo.

Please raise your questions by opening an issue at https://github.com/cncf/soc, or directly at https://support.communitybridge.org/.

**Comment by SidharthBansal** [comment]
ok thanks

**Comment by ranjithkumar007** [comment]
Hi, Is there any proposal draft/design doc for this feature? 
I am interested in participating in Community Bridge and would like to contribute to this feature. I am trying to get familiar with the architecture and codebase of Thanos. For this feature, I am still going through the linked discussions and how delete_series is implemented in Prometheus. 
Any pointers/suggestions to get started would be really helpful :smiley:

**Comment by bwplotka** [comment]
It's part of CommunityBridge projects: https://github.com/cncf/mentoring/blob/master/communitybridge/2020/q2/project_ideas.md#metrics-deletion (:

**Comment by VineethReddy02** [comment]
@bwplotka 
Delete series in Thanos is expected to be the same as delete series recently implemented in the cortex?
Are there any design docs on the use-cases and implementation on this enhancement?
If not can I create a design doc and start documenting the use-cases & design?

**Comment by darshanime** [comment]
I have started writing a doc on this (which is very much a WIP)
Happy to collaborate 😊 - https://docs.google.com/document/d/1L8PJu0ScDTrWp0mfPKYu2GcJU19nkQKLe1joD4vNncg/edit?usp=sharing

**Comment by theunisbotha** [comment]
Hi! I am a bit late to the party, but I will be more than happy to help contribute to this issue! :) How can I get involved?

**Comment by bwplotka** [comment]
Hi! 

So it's a big topic and we definitely can attack that from many angles. First of all, we need solid design. Looks like we can build up something from what @darshanime started if he does not mind. 

Just note that this issue is part of the GSoC project of @Harshitha1234 (: She is just onboarding on Thanos & Prometheus but it does not mean everyone else who wants to help has to just wait. We can collaborate on design straight away!

Depending on what @darshanime thinks... do you think we can use your design doc as a starting point? Can you maybe give Thanos maintainer permission, so we can moderate it? 

Eseentially we can accumulate some ideas there together. I don't think the suggested solution in this doc is what we want, but hey... I'm might be wrong (:

**Comment by darshanime** [comment]
Hi, I've changed the permission to allow edits. Please feel free to use in whatever way you see fit 🙏

**Comment by Harshitha1234** [comment]
Working on this currently :)

**Comment by Harshitha1234** [comment]
In progress... :)

**Comment by midnightconman** [comment]
Can we have an update on this, please? Maybe a link to some WIP, design doc, etc.

**Comment by Harshitha1234** [comment]
Sure! Link to the design doc #2780 
Will soon link to the WIP PR ;)

**Comment by midnightconman** [comment]
thank you :-) Really looking forward to this.

**Comment by Harshitha1234** [comment]
#3075, still needs few modifications and coming soon :)

**Comment by infa-kparida** [comment]
This is still required

**Comment by Harshitha1234** [comment]
Still valid!

**Comment by bwplotka** [comment]
This is already doable by `thanos tools rewrite` (: Should w close?

**Comment by bwplotka** [comment]
Ideally we can focus on tracking automation and embedding into API if we want as @Harshitha1234 started in separate issues 🤗

**Comment by kesor** [comment]
> This is already doable by `thanos tools rewrite` (: Should we close?

How exactly is this doable? Is there a link to the documentation of how to do `delete_series` using `thanos tools rewrite`? Have been finding plenty of issues asking for this feature, and now it says its "done", but there is zero information on how to actually do it.

**Comment by huyifeng0522** [comment]
> > This is already doable by `thanos tools rewrite` (: Should we close?
> 
> How exactly is this doable? Is there a link to the documentation of how to do `delete_series` using `thanos tools rewrite`? Have been finding plenty of issues asking for this feature, and now it says its "done", but there is zero information on how to actually do it.

Can not agree more，I tried `thanos tools rewrite`  but it did not work

**Comment by yeya24** [comment]
Sorry for the delay. I will add a document to demonstrate how to use the rewrite tool to delete and relabel series.

**Comment by yeya24** [comment]
PTAL for pr https://github.com/thanos-io/thanos/pull/4701.

**Comment by yeya24** [comment]
Though this is something supported already by the bucket rewrite tool, I still think it useful to implement the tombstone approach like https://github.com/thanos-io/thanos/pull/3075. The code is there and I can take it over.

I feel this can coexist with `bucket rewrite`. Tombstone file is doing some series filtering online so query performance will be impacted a little bit and the deletion can be applied lazily (compactor), no whole block modification is required.

I am still interested in this so I want to reopen this issue.

**Comment by Ishmeet** [comment]
is there an api ?

**Comment by hartfordfive** [comment]
Any updates on this issue?  I would like to know how I can manually delete series easily in the bucket without having to run compactor?

**Comment by MichaHoffmann** [comment]
> Any updates on this issue? I would like to know how I can manually delete series easily in the bucket without having to run compactor?

I dont think we have anything for that yet!

**Comment by Kot-o-pes** [comment]
Hello, ive come across running out of s3 space and unfortunately there is no way to delete blocks by label, instead i need to get id of each needed block and then mark it by id, it would be nice lets say to add flag `-l label=value` to `thanos tools mark`

**Comment by gillg** [comment]
Could be interesting indeed, but the only filter is the tenant as I'm aware.
But side question, what do you mean by "running out of S3 space" ?? It's literally unlimited, what is your limit?

**Comment by mwalz0** [comment]
Seems like `thanos tools bucket rewrite --rewrite.to-delete-config-file` does this, but only on a per-block level. This is not ideal because besides the date ranges of each block, there is no way to filter through and identify which blocks have the metric series in question.

To make matters worse, my blocks are very large (several gigabytes), so it requires downloading large blocks to wherever the tool is running and then processing all the series in the block. I have not done this successfully yet as I run into memory errors every time. Not sure how to move forward besides trying to run this on a more hefty server. Are my blocks too large and this is preventing me from doing this?
