### ISSUE TITLE
query UI: announced labelsets column does not distinguish labels from different sets

### ISSUE THREAD

**Issue by devnev** [thanos-io/thanos#1601]
**Thanos, Prometheus and Golang version used**:

From /status:

Version 0.7.0
Revision c6eaf68bec32aefd280318eaef6121d6ddb20d10
Branch HEAD
BuildUser circleci@f199bdee6152
BuildDate 20190902-15:43:19
GoVersion go1.12.5

**Object Storage Provider**:

N/A

**What happened**:

In case of a thanos query having a store that is itself another thanos query that is announcing all the labelsets from its own stores, the first thanos query ends up displaying a long list of k=v labels without any way to see the boundaries of the label sets.

**What you expected to happen**:

announced labelsets column groups the labels in each labelset

**How to reproduce it (as minimally and precisely as possible)**:

- run two prometheuses with thanos sidecars and different external labels
- run a thanos query with both the sidecars as stores
- run another thanos query with the previous query as its store
- look at the stores UI of the last thanos query

**Full logs to relevant components**:

N/A

**Anything else we need to know**:

N/A

**Environment**:

N/A

**Comment by bwplotka** [comment]
Yup :+1: Thanks for the report. Help wanted - frontend bug.
