### ISSUE TITLE
Add UI (e.g bucket web) to Compactor

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#1657]
I would like to propose an optional UI to the compactor, which will render what blocks we have access to same as `bucket web`.

AC:
* Compactor having UI with similar view as `thanos bucket web`

**Comment by jojohappy** [comment]
What is the difference between `thanos bucket web`?

**Comment by squat** [comment]
I think the main difference is that it runs as a daemon and you can access it whenever. I am a big fan of surfacing this UI easily ((((:

**Comment by bwplotka** [comment]
Yes and everyone needs compactor anyway, so it would fit perfectly.

**Comment by squat** [comment]
ack, I started hacking on this last week, I can put up a PR soon (:

**Comment by bwplotka** [comment]
:heart:

**Comment by vsxen** [comment]
how to build gstatic all js&cs file into thanos binary?

**Comment by vsxen** [comment]
hi @squarejaw    how to build gstatic js&cs file into thanos binary , can you help me ?

**Comment by bwplotka** [comment]
Not yet done and in progress.

**Comment by bwplotka** [comment]
@squat
