### ISSUE TITLE
Disable dependabot and add process for updating all deps after each release 

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#1659]
We are kind of behind dependencies and being spammed by 
It would be nice to configure dependabot to do all in one PR. I can't see such an option so I have created a support ticket.

Should it be a release shepherd responsibility?

AC:
* After every release, we upgrade all our dependencies.

cc @brancz @domgreen @GiedriusS @metalmatze @adrien-f @FUSAKLA opinions?

**Comment by brancz** [comment]
I do what is it that is keeping us from merging these PRs? It seems like continuously doing this is a better idea then at once. Do we not have the confidence? Is it too much?

Generally speaking this still seems like a good idea in theory, I want to understand what's making it not useful in practice (and/or if we _could_ make it useful :slightly_smiling_face: ).

**Comment by bwplotka** [comment]
Sure, so problems with current approach:

* Each merge of such dep PR creates conflict in go.mod (in most cases). Bot re submitting another dep PRs in this case, but we have to wait for CI etc. At least 20m wait time for each PR. For ~50 deps it takes in worst case it takes 16h (: Not fun.
* We can have some dependency hell with indirect deps. This means that one PR can update one dep, but in another we have to downgrade. It might be not very efficient to takle on each dep basis

**Comment by brancz** [comment]
It's probably worth giving the dependabot folks this feedback. I'd say let's make it release shepherd responsibility, that seems like a reasonable thing (of course one off bumps are not discouraged).

**Comment by bwplotka** [comment]
Ticket sent, no response

**Comment by metalmatze** [comment]
5 days later, did you get a response in the meantime?

**Comment by bwplotka** [comment]
Nope: It is also Github support as it was acquired. No response at all ):

**Comment by bwplotka** [comment]
Actually forget about a support ticket, look at this: https://github.com/dependabot/feedback/issues/5 :eyes: 

Will describe our use case and will check if we can help in any way.
