### ISSUE TITLE
Compact: occur `EntityTooSmall` error when put file to Tencent COS

### ISSUE THREAD

**Issue by NearTan** [thanos-io/thanos#1665]
Firstly, actually, `EntityTooSmall` error is a mistake return from COS, it should be `EntityTooLarge` (has been confirmed by the Tencent COS developer, will be fixed later).

In this issue, thanos compact generated an `index` file that size is 16.8 GiB, which is more than the maximum size (5 GiB) via simple upload.

So can we have a multi part upload implementation in the `Upload` function since the mozillazg/go-cos project does not provide a direct way to upload an oversize file?

PTAL @jojohappy 

![image](https://user-images.githubusercontent.com/4445695/67091398-1abb6300-f1df-11e9-89bf-e6f3091dfd71.png)

[Tencent COS document](https://intl.cloud.tencent.com/document/product/436/14518):
![image](https://user-images.githubusercontent.com/4445695/67091806-3ffca100-f1e0-11e9-9b1c-c64aec5bd7e2.png)

**Comment by jojohappy** [comment]
@NearTan Thanks for reporting! I'll try to fix it soon.

**Comment by jojohappy** [comment]
It is still valid. Reopen.

**Comment by jojohappy** [comment]
Still valid.

**Comment by deadjoker** [comment]
Still valid. Will it be fixed?
I got this error:
```
level=warn ts=2021-01-20T17:50:49.835778878Z caller=intrumentation.go:54 msg="changing probe status" status=not-ready reason="compaction: group 0@5133856710326479987: upload of 01EWGCSJZ8W1W19ND760Q5KTZ5 failed: upload index: upload file /data/compact/0@5133856710326479987/01EWGCSJZ8W1W19ND760Q5KTZ5/index as 01EWGCSJZ8W1W19ND760Q5KTZ5/index: upload cos object: PUT https://xxxx.cos.ap-beijing.myqcloud.com/01EWGCSJZ8W1W19ND760Q5KTZ5%2Findex: 400 EntityTooSmall(Message: Your proposed upload is smaller than the minimum allowed object size., RequestId: NjAwODZjOTBfY2ZhZjJhMDlfN2Q4ZF8yYTY1OGY5, TraceId: OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjN2FkOTNkYjVhZGFlOWFmMWQ4YTUwZTAxNzUzMzgxMGY=)"
```

**Comment by jojohappy** [comment]
@deadjoker @NearTan Oh, sorry for the delayed response. I have missed it for a long time and will take a look this weekend.

**Comment by NearTan** [comment]
https://github.com/thanos-io/thanos/commit/e26e2944d1225f7450cecc157a3e81e5c7f3dc03

I've done a quick fixing for your reference.

**Comment by jojohappy** [comment]
> [e26e294](https://github.com/thanos-io/thanos/commit/e26e2944d1225f7450cecc157a3e81e5c7f3dc03)
> 
> I've done a quick fixing for your reference.

Thanks! PR is welcome.

**Comment by deadjoker** [comment]
> [e26e294](https://github.com/thanos-io/thanos/commit/e26e2944d1225f7450cecc157a3e81e5c7f3dc03)
> 
> I've done a quick fixing for your reference.

How can I compile the code which can make it run successfully in the container? 
I run the self-compiled 'thanos' with error
`standard_init_linux.go:178: exec user process caused "exec format error"`
Should I add some specific envs while compiling?

**Comment by deadjoker** [comment]
> > [e26e294](https://github.com/thanos-io/thanos/commit/e26e2944d1225f7450cecc157a3e81e5c7f3dc03)
> > I've done a quick fixing for your reference.
> 
> How can I compile the code which can make it run successfully in the container?
> I run the self-compiled 'thanos' with error
> `standard_init_linux.go:178: exec user process caused "exec format error"`
> Should I add some specific envs while compiling?

It runs successfully after I replace the base image. 
What's more I find the upload process is much faster than before.
Thx a lot :)
