### ISSUE TITLE
Campactor should work directly on object storage

### ISSUE THREAD

**Issue by oded-dd** [thanos-io/thanos#1673]
Currently we encounter an issue where the compactor requires a disk for the compaction process. Once finished the disk can be deleted as the data is not needed there any more. This work can be done on S3 directly instead. As the work is asynchronous we will pay in CPU but it should not be expansive as this is a batch running from time to time. Managing the disk locally is not to complicated but does not make sense in this case as the compactor should be decoupled from Prometheus entirely.

**Comment by GiedriusS** [comment]
Perhaps the proposal (code) here https://github.com/thanos-io/thanos/pull/1567 could be reused?
