### ISSUE TITLE
Ready state handling of sidecar

### ISSUE THREAD

**Issue by jabbrwcky** [thanos-io/thanos#1677]
We experienced some bumps upgrading to thanos 0.8.1 (docker image).

Looking into sidecar I noted that the ready state of the sidecar is only set in the initial loading of prometheus labels:

https://github.com/thanos-io/thanos/blob/64af185e73978986c7955d2b3e8ad49e33bb099c/cmd/thanos/sidecar.go#L167-L186

The recurring check updates the 'prometheus_up' metric, but not the sidecar ready state:

https://github.com/thanos-io/thanos/blob/64af185e73978986c7955d2b3e8ad49e33bb099c/cmd/thanos/sidecar.go#L197-L210

Is this intentional? 

I assume when prometheus is considered non-healthy/-ready, the sidecar should report the same.

Please correct me if I am wrong.

**Comment by kakkoyun** [comment]
Hey @jabbrwcky, I have worked on related issues, looks like I have missed this part. I'll have a look at it.

**Comment by povilasv** [comment]
I think this was intentional https://github.com/thanos-io/thanos/pull/1395#issuecomment-523013201 as   we had a discussion on slack https://cloud-native.slack.com/archives/CL25937SP/p1565945595078500

**Comment by bwplotka** [comment]
Yes, readiness it's only assumed for the initial readiness. Blips are not changing the healthiness probe as there is not much that sidecar can do, how restart/container restart would help in this case (healthiness probe is for this case).

Also I don't see the difference in logic vs pre 0.8.1. What exactly you would expect here? (:

**Comment by jabbrwcky** [comment]
We experienced complete failures of queries on the querier because one prometheus instance stopped responding to HTTP request (i/o timeouts) and the querier included the prometheus/sidecar as source.

I would expect that the querier would return a partial result in such a case. Do I understand this correctly?

**Comment by bwplotka** [comment]
That's correct. This logic can be controlled by `query.partial-response`. Do you have it set to false maybe now?

**Comment by jabbrwcky** [comment]
It should be true. I cannot reproduce it at the moment because the prometheus instance in question is behaving at the moment.

So if query.partial-response should take care of this I'll verify that we have set it to true in the configs.
