### ISSUE TITLE
docs: Document Thanos Sharding 

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#1699]
As done in proposal: https://github.com/thanos-io/thanos/pull/1501

AC:
 * Thanos time and block sharding should be documented.

**Comment by VarunVats9** [comment]
@bwplotka : I don't have any experience on thanos, would you suggest, if I should take up this task ?

**Comment by bwplotka** [comment]
We need that still! @daixiang0 any update?

**Comment by daixiang0** [comment]
I would update it in few days.

**Comment by bwplotka** [comment]
Almost there (:
