### ISSUE TITLE
receive: always got oom and killed by system

### ISSUE THREAD

**Issue by GuyCheung** [thanos-io/thanos#1701]
**Thanos, Prometheus and Golang version used**:
Thanos: 0.8.1
Prometheus: 2.13.1

**Object Storage Provider**: s3

**What happened**: thanos-receive will got oom and killed by system

**What you expected to happen**: thanos-receive can manage the memory limit and avoid been killed by system

**Anything else we need to know**:
I deployed thanos receive and prometheus on the same machine (48G memory), prometheus will keep 30 minutes data and thanos receive keep 6 hours data in local, and thanos receiv always been killed after 6/7 hours due to oom.

**Environment**:
- OS (e.g. from /etc/os-release): Ubuntu 16

**Comment by brancz** [comment]
Can you share more details about your setup please? Is the Prometheus you have ingesting into a receive process on the same node?

**Comment by GuyCheung** [comment]
@brancz Sure. Actually, I have deployed the Prometheus, Thanos receive and Thanos store on the same node, the detail command line as below:

```shell
# Prometheus

/data/prometheus/prometheus --config.file=/etc/prometheus/prometheus.yml --web.enable-lifecycle --storage.tsdb.retention.time=30m --storage.tsdb.no-lockfile --storage.tsdb.wal-compression --storage.tsdb.min-block-duration=10m --storage.tsdb.max-block-duration=10m

# Thanos receive

/data/thanos/bin/thanos receive --log.level=info --grpc-address=0.0.0.0:19219 --http-address=0.0.0.0:19210 --remote-write.address=0.0.0.0:19211 --objstore.config-file=/data/thanos/conf/bucket.yml --tsdb.path=/data/thanos/receiver-data --tsdb.retention=6h --receive.hashrings-file=/data/thanos/conf/hashrings.json --receive.hashrings-file-refresh-interval=5m --receive.local-endpoint=http://192.168.31.4:19211/api/v1/receive --label=receiver="192.168.31.4:19211" --receive.replication-factor=3

# Thanos store

/data/thanos/bin/thanos store --http-address 0.0.0.0:19220 --grpc-address 0.0.0.0:19229 --objstore.config-file=/data/thanos/conf/bucket.yml --data-dir=/data/thanos/store-data --index-cache-size=250MB --chunk-pool-size=2GB --store.grpc.series-max-concurrency=200 --max-time=-6h

```

I had tried to set the Prometheus storage.tsdb.retention.time to 30m so that the Prometheus could release more memory, but unfortunately, it still took about 7G ~ 10G.

The node is 32c48G,  and because the Thanos store will take about 7G also, there are only about 30G for the Thanos receive component, and it will be killed due to oom.

just let me know if anything else details u need to know, thanks a lot!

**Comment by brancz** [comment]
By having a 10min Block size you’re duplicating you’re index 3 times until retention kicks in. Can you check the amount of metrics inserted and active time series on the Prometheus and receive component?

That’s 

prometheus_tsdb_head_series

And

rate(prometheus_tsdb_head_samples_appended_total[5m])

**Comment by GuyCheung** [comment]
@brancz sorry for the later reply, I collector the graphs u need as below(I have 4 hosts current after running 8h):

## Prometheus
- prometheus_tsdb_head_series: the series from 400k to 700k

![image](https://user-images.githubusercontent.com/1456257/68114682-97657580-ff31-11e9-910f-2c27be7943c9.png)

- rate(prometheus_tsdb_head_samples_appended_total[5m]): the rate from 24k to 36k

![image](https://user-images.githubusercontent.com/1456257/68114845-fa570c80-ff31-11e9-9990-9b8b8d0f653a.png)


## Thanos Receive

- prometheus_tsdb_head_series: receive should retention data every 2h, and it's peak point close to 4M now.

![image](https://user-images.githubusercontent.com/1456257/68115042-6c2f5600-ff32-11e9-8458-0c7f732eccfd.png)

- rate(prometheus_tsdb_head_samples_appended_total[5m]): the rate quite close each other, from 85k to 90k

![image](https://user-images.githubusercontent.com/1456257/68114930-31c5b900-ff32-11e9-82f6-484f379188c2.png)

**Comment by brancz** [comment]
Can you also share the corresponding go runtime heap metrics?

**Comment by GuyCheung** [comment]
@brancz I arranged the go memstats heap metrics as below:

## Prometheus (same time as previous reply)

- go_memstats_heap_objects
![image](https://user-images.githubusercontent.com/1456257/68275197-ecc29380-00a5-11ea-81a7-a23265386064.png)

- go_memstats_heap_inuse_bytes
![image](https://user-images.githubusercontent.com/1456257/68275269-21cee600-00a6-11ea-9dde-0f6e160ee854.png)

- go_memstats_heap_alloc_bytes
![image](https://user-images.githubusercontent.com/1456257/68275299-357a4c80-00a6-11ea-92cf-f64ae8fc81e4.png)


## Thanos Receive (same time as previous reply)

- go_memstats_heap_objects
![image](https://user-images.githubusercontent.com/1456257/68275381-6eb2bc80-00a6-11ea-9f2a-729d698409eb.png)

- go_memstats_heap_inuse_bytes
![image](https://user-images.githubusercontent.com/1456257/68275420-9013a880-00a6-11ea-85e3-7551aa2c0221.png)

- go_memstats_heap_alloc_bytes
![image](https://user-images.githubusercontent.com/1456257/68275454-acafe080-00a6-11ea-93d7-ee75777091b2.png)


## Prometheus (when oom)

- go_memstats_heap_objects
![image](https://user-images.githubusercontent.com/1456257/68275685-5abb8a80-00a7-11ea-8432-41a4a0f6a972.png)

- go_memstats_heap_inuse_bytes
![image](https://user-images.githubusercontent.com/1456257/68275721-7030b480-00a7-11ea-9cef-8414a388848d.png)

- go_memstats_heap_alloc_bytes
![image](https://user-images.githubusercontent.com/1456257/68275759-7f176700-00a7-11ea-86b4-6a60da46e834.png)

## Thanos Receive (when oom)

- go_memstats_heap_objects
![image](https://user-images.githubusercontent.com/1456257/68275533-ea146e00-00a6-11ea-90d0-24c5208c3e76.png)

- go_memstats_heap_inuse_bytes
![image](https://user-images.githubusercontent.com/1456257/68275547-f8628a00-00a6-11ea-809a-2f3ae08c5051.png)

- go_memstats_heap_alloc_bytes
![image](https://user-images.githubusercontent.com/1456257/68275570-07e1d300-00a7-11ea-9996-16da1e2ac1e1.png)

**Comment by brancz** [comment]
Generally speaking this looks as expected, you're just ingesting a lot of data, and that's going to need a lot of resources. Your setup looks pretty much aligned with ours. I would suggest to distribute the setup across multiple nodes instead of all on one.

**Comment by GuyCheung** [comment]
yes, I think should be as expected too. what I wonder know is that is there some way we can set the mem limit the Thanos or Prometheus process can use to avoid oom?

for example, I have 48G memmory, but I only want to Thanos use as much as 30G?

**Comment by brancz** [comment]
There is no such possibility today.

**Comment by GuyCheung** [comment]
while, thanks a lot anyway!
