### ISSUE TITLE
ci: Flaky test because of slow CI; Move to GitHub Actions?

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#1704]
Got this on doc's PR: https://circleci.com/gh/thanos-io/thanos/5575?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

`--- FAIL: TestRulePartialResponse (180.07s)` so timeout on achieving our goals within 3 minutes. We see it a lot due to CircleCI's slowness.

Let's investigate. This also bumps discussion about moving to faster CI, potentially Github Actions.

Should we try GitHub Actions? Help wanted! (: 

Tricky requirement:
* We have some secrets that we want to use only for PRs who are MAINTAINERS (!). This uses real S3 and GCS to run tests against (: CircleCI gave us such feature

AC: 
* Move to Github Actions

**Comment by metalmatze** [comment]
Do we already have faster builds from CircleCI through the CNCF? But I guess that's only about scheduling and not building itself?

**Comment by bwplotka** [comment]
No, we are on open source tier. CNCF advised us to move to GH actions which is claimed to be now way faster. Alternative is Azure pipelines.

**Comment by ppanyukov** [comment]
Azure pipelines are pretty good. There is a pretty good story there on having secrets (like ssh keys) and secret variables, and service principal links to anything in Azure (obviously!). 

The downside is there is a need for separate org there, all that account linking and management etc. The whole thing being MSFT could be quite overwhelming to newcomers.

**Comment by bwplotka** [comment]
Another flaky test: https://circleci.com/gh/thanos-io/thanos/5768?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
```
bucket_e2e_test.go:118: unexpected error: upload chunks: upload file /tmp/test_bucketstore_e2e870919390/01DT360EKBV7PPYWK055TKZAZG/chunks/000001 as 01DT360EKBV7PPYWK055TKZAZG/chunks/000001: upload s3 object: The specified bucket does not exist
```

**Comment by bwplotka** [comment]
Another one repeating constantly:

```
--- FAIL: TestRulePartialResponse (180.03s)
		if len(alrts) != len(expAlertLabels) {
			return errors.Errorf("unexpected alerts length %d", len(alrts))
		}
```

Due to timeout again.

**Comment by bwplotka** [comment]
Sitll valid.

**Comment by bwplotka** [comment]
With e2e in GH actions it's good enough. Did not see much flakinesses (:
