### ISSUE TITLE
Add e2e Benchmarking for CI

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#1707]
Something like [prombench](https://github.com/prometheus/prombench) but for Thanos (: 

We would love to have some auto benchmark to run on certain PRs to compare versions' resource usage.

I did something like this manually with [thanosbench](https://github.com/thanos-io/thanosbench) as mentioned [here](https://github.com/thanos-io/thanosbench/blob/master/benchmarks/lts/README.md), so:

Dataset generated offline and exactly the same for every test run.

For a start Querier and Store GW tests:

* Start store GW for version A and B
* Start Querier for version A and B
* Perform some queries like
 * Instant queries
 * Short range queries
 * Long range queries
 * Cardinality queries (e.g touching 100k series)
 
Then give dashboard  / Prometheus UI with resource consumption and queries latency.

### Why not just run on staging/production environment? 

Because this might be not quite deterministic: dataset changes all the time (compactions, new blocks retention), queries are different and not isolated.

Help wanted!  (:

**Comment by jojohappy** [comment]
I'd like to take it. So questions about this proposal:
* Should we use one of cloud kubernetes service, e.g. GKE like prombench?
* How about the permission? Only maintainer can run the test in a PR?

**Comment by bwplotka** [comment]
> Should we use one of cloud Kubernetes service, e.g. GKE like prombench?

Yes, however, we might be able to get away with GH actions and `kind` potentially (: 
As the first step, we might want to have it as part of `thanosbench` against any given `Kubernetes` 

> How about the permission? The only maintainer can run the test in a PR?

That's correct.

**Comment by rajibmitra** [comment]
I would like to work on this as part of community bridge program if its okay.  @bwplotka  @jojohappy 
cc @GiedriusS

**Comment by kdanW** [comment]
Hi. If is the project still available? I would like to work on this under community bridge mentorship if it is available

**Comment by bwplotka** [comment]
@rajibmitra @kdanW please apply for this project here: https://docs.linuxfoundation.org/display/DOCS/Mentees

**Comment by rajibmitra** [comment]
I have applied , thanks @bwplotka  , looking forward to it.

**Comment by kdanW** [comment]
I have applied as well. Thanks @bwplotka

**Comment by bwplotka** [comment]
Interesting work started by Grafana on this field, it's worth to sync with them: https://docs.google.com/document/d/1_fVDL9EGVjWSdZTYTvE8Ey_g8FlTY_7DVGazuTAWqFc/edit

(:

**Comment by yeya24** [comment]
https://github.com/prometheus/prombench/blob/master/funcbench/README.md is a useful tool to benchmark specific functions and I believe this is easy to integrate after we move to Github Actions. We can easily reuse the docker images from Prombench to implement a similar workflow.

1. Github comments to trigger Github Actions
2. Trigger function benchmark
3. Post the result back to comment

**Comment by yeya24** [comment]
For doing micro-benchmarks between 2 go bench functions, we can reuse funcbench as well. It is not difficult to extend it to achieve this purpose.

**Comment by bwplotka** [comment]
Yes, but I believe this particular issue is for e2e, so not
micro-benchmarks (: Let's keep the discussion focused.

**Comment by geekodour** [comment]
Thanks for sharing the grafana doc @bwplotka :) little surprised that they didn't mention https://github.com/kubernetes/test-infra/tree/master/prow which kind of resembles the proposed solution; but does feel like an overlkill for smaller projects to self host and maintain.

We're planning for `kind` support for prombench too, but that'll mostly be for adding more tests/queries/e2e test of the test-infra itself etc; Interested to know if it'll be useful to run benchmarks aswell.
