### ISSUE TITLE
receive: create a gRPC remote_write endpoint

### ISSUE THREAD

**Issue by blockloop** [thanos-io/thanos#1710]
I understand the compatibility reasons for creating a remote_write endpoint that adheres to the Prometheus standard. Would you consider enabling a gRPC endpoint to enable pushing metrics from arbitrary gRPC sources? Ideally it would use a gRPC Stream to improve performance.

**Comment by brancz** [comment]
I think I would want something like this to be experimental, but if we can prove it to have a significant improvement over the existing one, then I'd even go a step further and attempt to make Prometheus send remote write via gRPC.

**Comment by blockloop** [comment]
I've started work on this here: https://github.com/blockloop/thanos/tree/bjones/receive/use-grpc
