### ISSUE TITLE
Filter metrics that are written by sidecar to S3

### ISSUE THREAD

**Issue by clausa20** [thanos-io/thanos#1726]
Hello,
is it possible to filter what metrics are wanted to be written in the remote storage (S3) by the sidecar?
for example I would like to write only metrics that has a label for example remote=1
some_metric{remote="1"}

I don't want to save all metrics in remote storage, I want to save just some of them.
If not, is there another way I can get that result?

Thanks.

**Comment by GiedriusS** [comment]
Currently, there is no such feature. The closest you can get to this is with `metric_relabel_configs`.

**Comment by FUSAKLA** [comment]
You could possibly set up new prometheus instance to federate just those metrics you are interested and add the sidecar to it as a workaround.
