### ISSUE TITLE
Thanos store hungs up on Initializing Bucket store

### ISSUE THREAD

**Issue by uvaisibrahim** [thanos-io/thanos#1730]
Hi,

Somebody, please tell me what is actually happening when the logs for Thanos store-gateway shows this?

level=info ts=2019-11-07T08:30:48.398215615Z caller=flags.go:75 msg="gossip is disabled"
level=info ts=2019-11-07T08:30:48.398667804Z caller=factory.go:39 msg="loading bucket configuration"
level=debug ts=2019-11-07T08:30:48.401134194Z caller=store.go:128 msg="initializing bucket store"

My concern is Thanos store-gateway is just hangs up here showing the store-gateway component is down in the Query Layer UI. But the container(K8s pod) is still showing as running without any errors. How to resolve this condition?

Thanks,
Uvais Ibrahim

**Comment by GiedriusS** [comment]
Hi, closing in favor of https://github.com/thanos-io/thanos/issues/1455. We could definitely be more verbose here so that our users would know what is actually happening.
