### ISSUE TITLE
How can I configure storage type to NFS in Thanos ? Any example?

### ISSUE THREAD

**Issue by raz08** [thanos-io/thanos#1731]
**Thanos, Prometheus and Golang version used**:

**Object Storage Provider**:

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by FUSAKLA** [comment]
Hi, Thanos is not planning to support any distributed filesystems such as NFS at least for now.
Please refer to the documentation about the experimental filesystem storage support https://thanos.io/storage.md/#filesystem
