### ISSUE TITLE
rule: Alerts will not be deleted after curl -X POST localhost:10902/-/reload.

### ISSUE THREAD

**Issue by Kirchen99** [thanos-io/thanos#1739]
**Thanos, Prometheus and Golang version used**:

0.8.1

**What happened**:
I deleted alerts file and used curl to reload thanos. But the alerts are still in thanos-ruler.

**What you expected to happen**:
The alerts should be disappeared from thanos-ruler

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl apply -f rules.yaml`
```---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rule-test
  namespace: monitoring
data:
  test_rules_alerts.rules.yaml: |-
    groups:
    - name: test.alarm
      rules:
      - alert: TEST-ALARM
        expr: vector(1)
```
`curl -X POST localhost:10902/-/reload.`

Then the alert is in thanos-rule.
And now:

`kubectl delete -f rules.yaml`
`curl -X POST localhost:10902/-/reload.`

The alert is not disappeared.

**Full logs to relevant components**:
```
{"caller":"rule.go:441","level":"info","msg":"reload rule files","numFiles":1,"ts":"2019-11-11T14:45:15.926305365Z"}

{"caller":"rule.go:441","level":"info","msg":"reload rule files","numFiles":0,"ts":"2019-11-11T14:45:27.957372263Z"}
```

**Comment by GiedriusS** [comment]
Probably related to this: https://github.com/thanos-io/thanos/pull/1439
