### ISSUE TITLE
Thanos storage type FILESYSTEM-Error parsing commandline arguments: unknown long flag '--cluster.address'

### ISSUE THREAD

**Issue by Rajashekharaiah-M** [thanos-io/thanos#1740]
Trying to setup Thanos (Demo setup) using storage type FILESYSTEM. I took master code base and built it, as LOCAL FILESYSTEM storage fix is on master.
But I'm getting thanos: error: unknown long flag '--cluster.address'.

**Thanos, Prometheus and Golang version used**:
Thanos  :  master
Golang : 1.13

**Object Storage Provider**: FILESYSTEM

**What happened**:

**What you expected to happen**: Error parsing commandline arguments: unknown long flag '--cluster.address'
thanos: error: unknown long flag '--cluster.address'

**How to reproduce it (as minimally and precisely as possible)**: Take master branch code , custom build and deploy

**Full logs to relevant components**:Error parsing commandline arguments: unknown long flag '--cluster.address'
thanos: error: unknown long flag '--cluster.address'

**Anything else we need to know**:

**Comment by jojohappy** [comment]
Hi, All `--cluster.*` flags belonged to Gossip cluster, we have removed Gossip implementation since v0.5.0. You should remove the `--cluster.*` flags.

**Comment by Rajashekharaiah-M** [comment]
Hi jojohappy, Where should I remove this flag.

**Comment by squat** [comment]
Thanos is complaining that `--cluster.address` is not a valid flag. You must not specify it when running the binary.

Can you please share exactly what command you are running?

**Comment by Rajashekharaiah-M** [comment]
I'm just adding thanos in Prometheus source. 

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
spec:
    thanos:
        baseImage: affirmed/thanos
        version: v0.8.0
        peers: thanos-peers.monitoring.svc:10900
        objectStorageConfig:
             key: thanos.yaml
             name: thanos-objstore-config

And my thanos.yaml is like 

{{- define "thanos" -}}
type: FILESYSTEM
config:
  directory: "/data/thanos"
{{- end -}}

After I deploy prometheus operator with this config, the thanos sidecar logs are.

Error parsing commandline arguments: unknown long flag '--cluster.address'
thanos: error: unknown long flag '--cluster.address'

**Comment by squat** [comment]
You’re deploying thanos sidecar automatically with Prometheus Operator? The this issue is because you are using incompatible versions of thanos and Prometheus Operator. To use thanos >=0.4.0 you need to use Prometheus operator >=0.31.0. 

xref: https://github.com/coreos/prometheus-operator/commit/901346bd552274f4c4e3de4aae1dcc4a3abe5668

**Comment by Rajashekharaiah-M** [comment]
Yes, version conflicts. Thank you.
