### ISSUE TITLE
query: UI doesn't persist Thanos-specific settings

### ISSUE THREAD

**Issue by SuperQ** [thanos-io/thanos#1743]
When using the Thanos query UI, the additional settings like "deduplication", "partial response", etc are not persisted to the URL the same way settings like "stacked" are. This makes it difficult to share URLs.

Also problematic is that the UI defaults to "Only raw data", which can be expensive on large queries.

**Comment by SuperQ** [comment]
It looks like this was at least partially fixed by https://github.com/thanos-io/thanos/issues/1463.

**Comment by FUSAKLA** [comment]
Agree this is annoying. Quickly looking at the UI it should be only:
- [ ] deduplication
- [ ] partial response 

Regarding the default down sampling, would you suggest the automatic as a default?

**Comment by SuperQ** [comment]
Yes, I think automatic should be the default.

**Comment by bwplotka** [comment]
User can decide what is by default using `query.auto-downsampling`

In terms of URL settings, we added downsampling parameter: https://github.com/thanos-io/thanos/pull/1562 definitely this issue is valid to add all of them.

**Comment by SuperQ** [comment]
@bwplotka That seems to only affect queries from things like Grafana. When you use the UI, it has separate defaults that aren't affected by the command line flag.

**Comment by bwplotka** [comment]
Ah, good point, then I think either this flag should set this default, or we should have another. I think the former is preferable.

**Comment by obiesmans** [comment]
@bwplotka : maybe a thanos-specific datasource for grafana could be a neat long-term solution ?
