### ISSUE TITLE
query: merge discontinuous metrics

### ISSUE THREAD

**Issue by silencev** [thanos-io/thanos#1744]
I'm new to Thanos, thanks for your great work!

I setup 2 Prometheus servers with Thanos sidecar to be the HA pair.
in some unstable network situation, the metrics is discontinuous because of scrape timeout:

**dedup=true**
![圖片](https://user-images.githubusercontent.com/24366323/68831705-11dc8500-06ea-11ea-8c26-5cb3dc18d814.png)

but if set **dedup=false**, I found the metrics can connect together at the same point
![圖片](https://user-images.githubusercontent.com/24366323/68831770-43555080-06ea-11ea-85f2-05c9f8078e22.png)

It looks like Thanos Querier only pick up one of the time series data.

1) Just wondering is it possible to merge the data point in this situation?
2) What's the dedup strategy Thanos Query uses?

Thanks

### Versions
thanos v0.8.1
Prometheus v2.13.1

**Comment by FUSAKLA** [comment]
Hi, thanos currently uses penalty based algorythm which chooses primary replica and only switches to next one after some lvl of degradation. The reason for this is that the two replicas can has slightly different data and if it would switch between those immediately when the first is missing them the results could be "jumpy". 
Does this at least a bit answers your question?

**Comment by FUSAKLA** [comment]
The penalization logic can be found here
https://github.com/thanos-io/thanos/blob/a3ab54566ce65741ba37fec5c152d18a80fcfdac/pkg/query/iter.go#L490

**Comment by silencev** [comment]
@FUSAKLA thanks! let me trace the code for `penalty` algorythm :-]
