### ISSUE TITLE
Labels on Bucket Web UI chunks

### ISSUE THREAD

**Issue by cmanzi** [thanos-io/thanos#1749]
**Thanos, Prometheus and Golang version used**:
Thanos: quay.io/thanos/thanos:v0.8.1
Prometheus: quay.io/prometheus/prometheus:v2.12.0

**Object Storage Provider**: 
S3

**What happened**:
Bucket Web UI shows correct number of 'rows' Prometheus instances, but the labels on the left only show '1, 2, 3, etc.'. See attached image. From the screenshots I've seen, it seems like they should be showing the 'prometheus' external labels (I have verified that these labels are available). I didn't see any configurations that would affect this.

<img width="1906" alt="Screen Shot 2019-11-15 at 5 17 12 PM" src="https://user-images.githubusercontent.com/54186611/68982249-e0d48100-07cb-11ea-8787-59486d88a233.png">

**What you expected to happen**:
Labels in Bucket UI reflect the corresponding Prometheus instance. 

**How to reproduce it (as minimally and precisely as possible)**:
Set up Thanos v0.8.1 exporting Prometheus blocks to S3.

**Full logs to relevant components**:
```
{"caller":"main.go:170","level":"info","msg":"Tracing will be disabled","ts":"2019-11-15T21:06:42.848374555Z"}
{"caller":"factory.go:39","level":"info","msg":"loading bucket configuration","ts":"2019-11-15T21:06:42.849385857Z"}
{"address":"0.0.0.0:8080","caller":"bucket.go:344","level":"info","msg":"Listening for query and metrics","ts":"2019-11-15T21:06:42.866589769Z"}
{"caller":"bucket.go:390","level":"info","msg":"synchronizing block metadata","ts":"2019-11-15T21:06:43.068597925Z"}
{"caller":"bucket.go:410","level":"info","msg":"downloaded blocks meta.json","num":12,"ts":"2019-11-15T21:06:52.686028839Z"}
{"caller":"bucket.go:390","level":"info","msg":"synchronizing block metadata","ts":"2019-11-15T21:36:43.070105368Z"}
{"caller":"bucket.go:410","level":"info","msg":"downloaded blocks meta.json","num":12,"ts":"2019-11-15T21:36:43.49424035Z"}
{"caller":"bucket.go:390","level":"info","msg":"synchronizing block metadata","ts":"2019-11-15T22:06:43.072916663Z"}
{"caller":"bucket.go:410","level":"info","msg":"downloaded blocks meta.json","num":12,"ts":"2019-11-15T22:06:43.472230775Z"}
{"caller":"bucket.go:390","level":"info","msg":"synchronizing block metadata","ts":"2019-11-15T22:36:43.07521795Z"}
{"caller":"bucket.go:406","err":"Access Denied","level":"error","msg":"Failed to downloaded block metadata","ts":"2019-11-15T22:36:49.731659057Z"}
{"caller":"runutil.go:95","err":"Access Denied","level":"error","msg":"function failed. Retrying in next tick","ts":"2019-11-15T22:36:49.731718439Z"}
{"caller":"bucket.go:390","level":"info","msg":"synchronizing block metadata","ts":"2019-11-15T22:37:43.076819802Z"}
{"caller":"bucket.go:410","level":"info","msg":"downloaded blocks meta.json","num":12,"ts":"2019-11-15T22:37:43.442198732Z"}
{"caller":"bucket.go:390","level":"info","msg":"synchronizing block metadata","ts":"2019-11-15T23:06:43.069413192Z"}
{"caller":"bucket.go:410","level":"info","msg":"downloaded blocks meta.json","num":15,"ts":"2019-11-15T23:06:43.407193341Z"}
```

**Anything else we need to know**:

**Comment by bwplotka** [comment]
Yes, this is due to the limitation of UI library we used. 

Help wanted to fix it (:

**Comment by cmanzi** [comment]
@bwplotka I'd be interested in helping out. Any details you can point me to regarding this issue?

**Comment by bwplotka** [comment]
BTW you should see those labels below, just not at the first column, but below. See: https://github.com/thanos-io/thanos/pull/1248 for details, can't find the discussion now why it was not done all in the first column.

**Comment by cmanzi** [comment]
@bwplotka Thanks. Turns out I fixed it be correctly reading the docs...I did open a PR https://github.com/thanos-io/thanos/pull/1756 to set the default label to `prometheus`. Seems like this would make sense as a default label to look for. I will look over that other issue, thanks.
