### ISSUE TITLE
compactor: Ideas to use less disk space

### ISSUE THREAD

**Issue by Wing924** [thanos-io/thanos#1767]
**Thanos, Prometheus and Golang version used**:
quay.io/thanos/thanos:v0.8.1

**Object Storage Provider**:
S3

**What happened**:
compactor use up all disk (250G) while the biggest block size is 27G and repeatedly restart.
<img width="415" alt="スクリーンショット 2019-11-19 23 52 56" src="https://user-images.githubusercontent.com/8895721/69219502-d7c71500-0b27-11ea-8322-30aeb14ff0c1.png">

**What you expected to happen**:
According to #1007, final block =~ base block * 7 =~ 27 * 7 = 189G < 250G
it should be compacted without error, but got disk full.

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

<details>Logs
<p>

```
level=info ts=2019-11-20T08:46:17.301507455Z caller=compact.go:1069 msg="start of GC"
level=info ts=2019-11-20T08:46:17.308941982Z caller=compact.go:1075 msg="start of compaction"

level=debug ts=2019-11-20T09:29:27.374673792Z caller=compact.go:875 compactionGroup="0@{monitor=\"worker-101\",replica=\"a\"}" msg="downloaded and verified blocks" blocks="[/cache/compact/0@{monitor=\"worker-101\",replica=\"a\"}/01DRN9T5ZPM5NT425P0JZTB8T1 /cache/compact/0@{monitor=\"worker-101\",replica=\"a\"}/01DRTBAWEFZYN8Q6JCFZJ3W6AZ /cache/compact/0@{monitor=\"worker-101\",replica=\"a\"}/01DRZG7XW1V36HM2QJ4NKHP2X7 /cache/compact/0@{monitor=\"worker-101\",replica=\"a\"}/01DS4N123W7KYMXEHJDQ8S064M /cache/compact/0@{monitor=\"worker-101\",replica=\"a\"}/01DS9SQW9GH45D3C0K4HEXQ5J3 /cache/compact/0@{monitor=\"worker-101\",replica=\"a\"}/01DSEYV4ZFNZ0NN5FZ8419Y0GM /cache/compact/0@{monitor=\"worker-101\",replica=\"a\"}/01DSM3EVYTQEKTV7HNCCK8FZJ1]" duration=43m10.040431776s
level=warn ts=2019-11-20T09:41:52.941250072Z caller=prober.go:154 msg="changing probe status" status=unhealthy reason="error executing compaction: compaction failed: compaction failed for group 0@{monitor=\"worker-101\",replica=\"a\"}: compact blocks [/cache/compact/0@{monitor=\"worker-101\",replica=\"a\"}/01DRN9T5ZPM5NT425P0JZTB8T1 /cache/compact/0@{monitor=\"worker-101\",replica=\"a\"}/01DRTBAWEFZYN8Q6JCFZJ3W6AZ /cache/compact/0@{monitor=\"worker-101\",replica=\"a\"}/01DRZG7XW1V36HM2QJ4NKHP2X7 /cache/compact/0@{monitor=\"worker-101\",replica=\"a\"}/01DS4N123W7KYMXEHJDQ8S064M /cache/compact/0@{monitor=\"worker-101\",replica=\"a\"}/01DS9SQW9GH45D3C0K4HEXQ5J3 /cache/compact/0@{monitor=\"worker-101\",replica=\"a\"}/01DSEYV4ZFNZ0NN5FZ8419Y0GM /cache/compact/0@{monitor=\"worker-101\",replica=\"a\"}/01DSM3EVYTQEKTV7HNCCK8FZJ1]: 2 errors: write compaction: write chunks: no space left on device; sync /cache/compact/0@{monitor=\"worker-101\",replica=\"a\"}/01DT42AGVNXNG3FWAEZHY8E5F0.tmp/chunks/000180: file already closed"
level=error ts=2019-11-20T09:41:52.945570325Z caller=main.go:215 msg="running command failed" err="error executing compaction: compaction failed: compaction failed for group 0@{monitor=\"worker-101\",replica=\"a\"}: compact blocks [/cache/compact/0@{monitor=\"worker-101\",replica=\"a\"}/01DRN9T5ZPM5NT425P0JZTB8T1 /cache/compact/0@{monitor=\"worker-101\",replica=\"a\"}/01DRTBAWEFZYN8Q6JCFZJ3W6AZ /cache/compact/0@{monitor=\"worker-101\",replica=\"a\"}/01DRZG7XW1V36HM2QJ4NKHP2X7 /cache/compact/0@{monitor=\"worker-101\",replica=\"a\"}/01DS4N123W7KYMXEHJDQ8S064M /cache/compact/0@{monitor=\"worker-101\",replica=\"a\"}/01DS9SQW9GH45D3C0K4HEXQ5J3 /cache/compact/0@{monitor=\"worker-101\",replica=\"a\"}/01DSEYV4ZFNZ0NN5FZ8419Y0GM /cache/compact/0@{monitor=\"worker-101\",replica=\"a\"}/01DSM3EVYTQEKTV7HNCCK8FZJ1]: 2 errors: write compaction: write chunks: no space left on device; sync /cache/compact/0@{monitor=\"worker-101\",replica=\"a\"}/01DT42AGVNXNG3FWAEZHY8E5F0.tmp/chunks/000180: file already closed"
```

</p>
</details>

**Anything else we need to know**:

running command:
```
thanos compact
      --compact.concurrency=1
      --data-dir=/cache
      --log.level=debug
      --objstore.config-file=/config/bucket.yml
      --retention.resolution-1h=15d
      --retention.resolution-5m=30d
      --retention.resolution-raw=90d
      --wait
```

base blocks sizes:
```
8.81468214187771G 21 objects   s3://my_bucket/01DRN9T5ZPM5NT425P0JZTB8T1/
24.49346103426069G 51 objects  s3://my_bucket/01DRTBAWEFZYN8Q6JCFZJ3W6AZ/
24.632513377815485G 52 objects s3://my_bucket/01DRZG7XW1V36HM2QJ4NKHP2X7/
24.634988240897655G 52 objects s3://my_bucket/01DS4N123W7KYMXEHJDQ8S064M/
24.644460477866232G 52 objects s3://my_bucket/01DS9SQW9GH45D3C0K4HEXQ5J3/
24.639022399671376G 52 objects s3://my_bucket/01DSEYV4ZFNZ0NN5FZ8419Y0GM/
24.570704349316657G 51 objects s3://my_bucket/01DSM3EVYTQEKTV7HNCCK8FZJ1/
```

**Comment by GiedriusS** [comment]
Hi, what are the lengths of those blocks in terms of time range? I wouldn't be surprised if `thanos compact` is trying to carve out a "bigger" block out of those.

**Comment by Wing924** [comment]
@GiedriusS This is inspect output

|            ULID            |        FROM         |        UNTIL        |   RANGE   | UNTIL-DOWN | #SERIES |   #SAMPLES    |  #CHUNKS   | COMP-LEVEL | COMP-FAILED |                LABELS                 | RESOLUTION |  SOURCE   |
|----------------------------|---------------------|---------------------|-----------|------------|---------|---------------|------------|------------|-------------|---------------------------------------|------------|-----------|
| 01DRN9T5ZPM5NT425P0JZTB8T1 | 01-11-2019 15:54:30 | 02-11-2019 09:00:00 | 17h5m30s  | 22h54m30s  | 865,871 | 3,297,416,260 | 27,371,967 | 3          | false       | monitor=worker-101,replica=a          | 0s         | compactor |
| 01DRTBAWEFZYN8Q6JCFZJ3W6AZ | 02-11-2019 09:00:00 | 04-11-2019 09:00:00 | 48h0m0s   | -8h0m0s    | 870,110 | 9,242,252,462 | 77,039,437 | 3          | false       | monitor=worker-101,replica=a          | 0s         | compactor |
| 01DRZG7XW1V36HM2QJ4NKHP2X7 | 04-11-2019 09:00:00 | 06-11-2019 09:00:00 | 48h0m0s   | -8h0m0s    | 875,631 | 9,259,300,497 | 77,178,629 | 3          | false       | monitor=worker-101,replica=a          | 0s         | compactor |
| 01DS4N123W7KYMXEHJDQ8S064M | 06-11-2019 09:00:00 | 08-11-2019 09:00:00 | 48h0m0s   | -8h0m0s    | 876,758 | 9,263,109,760 | 77,222,684 | 3          | false       | monitor=worker-101,replica=a          | 0s         | compactor |
| 01DS9SQW9GH45D3C0K4HEXQ5J3 | 08-11-2019 09:00:00 | 10-11-2019 09:00:00 | 48h0m0s   | -8h0m0s    | 875,209 | 9,285,109,617 | 77,399,360 | 3          | false       | monitor=worker-101,replica=a          | 0s         | compactor |
| 01DSEYV4ZFNZ0NN5FZ8419Y0GM | 10-11-2019 09:00:00 | 12-11-2019 09:00:00 | 48h0m0s   | -8h0m0s    | 876,710 | 9,269,496,817 | 77,272,187 | 3          | false       | monitor=worker-101,replica=a          | 0s         | compactor |
| 01DSM3EVYTQEKTV7HNCCK8FZJ1 | 12-11-2019 09:00:00 | 14-11-2019 09:00:00 | 48h0m0s   | -8h0m0s    | 880,459 | 9,287,637,886 | 77,425,878 | 3          | false       | monitor=worker-101,replica=a          | 0s         | compactor |

**Comment by Wing924** [comment]
@GiedriusS Do you need any additional info?

**Comment by asandulescu** [comment]
@Wing924 I think we're experiencing the same issue.
Did you ever manage to figure out what was happening?

**Comment by hari2192** [comment]
We are also experiencing same issue - anyone able to solve this ?

**Comment by bwplotka** [comment]
What exactly it too much? (: What is expected here? (:

**Comment by hari2192** [comment]
@bwplotka 

Few questions:
1. Is thanos compactor creates bigger blocks [compacted] using the smaller blocks [un-compacted] ? If so, when the bigger block has been created why it is not deleting the smaller blocks ? 
At this moment we see smaller blocks [un-compacted] remain under local disk space of thanos compactor.
2. Once the bigger block [compacted] has been moved to object storage, is thanos compactor suppose to delete it from local disk space ?
3. Is there any benchmark to pick the right size for thanos-compactor local disk based on samples ingested or un-compacted block size ?

Above questions are based on my understanding from reading about thanos compactor from information available on old [issues](https://github.com/thanos-io/thanos/issues/1007) reported for thanos compactor disk space usage.

Also, if my understanding is not correct around thanos compactor operation then could you please your understanding on how this thing works?

**Comment by andrei-dobre-ts** [comment]
Hello, we also experience a problem where the compactor downloads more data form S3 than available on the node storage. Is it possible to:
1. Configure the number of blocks brought from S3?
2. Configure the maximum possible size of a single S3 block?
(running thanos 0.8.1)

**Comment by markmsmith** [comment]
Are there still plans to reduce the amount of disk space used?

**Comment by pracucci** [comment]
> 1. Is thanos compactor creates bigger blocks [compacted] using the smaller blocks [un-compacted] ? If so, when the bigger block has been created why it is not deleting the smaller blocks ?
>    _At this moment we see smaller blocks [un-compacted] remain under local disk space of thanos compactor._

Both the source blocks (inputs) and the compacted block (output) are deleted once the compacted block has been successfully uploaded to the bucket. You should see blocks on the local disk only for on-going compactions.

> 2. Once the bigger block [compacted] has been moved to object storage, is thanos compactor suppose to delete it from local disk space ?
>    _At this moment bigger block remains under local disk space._

Yes.

> 3. Is there any benchmark to pick the right size for thanos-compactor local disk based on samples ingested or un-compacted block size ?

I know I'm going to give you an indirect answer, but we're using the Thanos `BucketCompactor` in the Cortex blocks storage too, and [this is what we do suggest for production setups](https://cortexmetrics.io/docs/blocks-storage/compactor/#compactor-disk-utilization). Keep in mind that the highest block range period in Thanos is 2 weeks. 

> 4. Since we are facing thanos-compactor getting restarted and loosing its data stored in local disk space and also it might be cancelling ongoing compaction and downsample operations. what could be implications of this ? Is thanos-compactor expected to re do all the work which has been cancelled by sudden restarts ?

The compactor will restart from scratch the work it was doing at the time it has been abruptly terminated.
