### ISSUE TITLE
bucket with type FILESYSTEM is not supported

### ISSUE THREAD

**Issue by UdayVishwakarma** [thanos-io/thanos#1768]
**Thanos, Prometheus and Golang version used**:

thanos, version 0.8.1 (branch: HEAD, revision: bd8278859b2321aaaa7514edde764816cc039d34)
  build user:       root@2227d9a2fdb1
  build date:       20191014-12:03:55
  go version:       go1.13.1

**Object Storage Provider**:
FILESYSTEM
**What happened**:
I tried running store with below command 
```
./thanos store --data-dir /home/ubuntu/thanos/data --http-address 0.0.0.0:19191 --grpc-address 0.0.0.0:19090 --objstore.config-file /home/ubuntu/thanos/thanos_storage.yaml
 ``` 

I get error `caller=main.go:200 err="store command failed: create bucket client: bucket with type FILESYSTEM is not supported".`

contents of thanos_storage.yaml is 

```
type: FILESYSTEM
config:
  directory: "/home/ubuntu/thanos/data"
```
**What you expected to happen**:

Thanos store to run using filesystem
**How to reproduce it (as minimally and precisely as possible)**:
- download latest Thanos version from releases
- start the store with command above with --objstore.config-file and file contents as above
**Full logs to relevant components**:
```
./thanos store --data-dir /home/ubuntu/thanos/data --http-address 0.0.0.0:19191 --grpc-address 0.0.0.0:19090 --objstore.config-file /home/ubuntu/thanos/thanos_storage.yaml
level=info ts=2019-11-20T11:07:37.651512947Z caller=main.go:170 msg="Tracing will be disabled"
level=info ts=2019-11-20T11:07:37.652173682Z caller=factory.go:39 msg="loading bucket configuration"
level=error ts=2019-11-20T11:07:37.652302315Z caller=main.go:200 err="store command failed: create bucket client: bucket with type FILESYSTEM is not supported"
```

**Anything else we need to know**:

@bwplotka

**Comment by GiedriusS** [comment]
Hello! Please use the `master` version - https://github.com/thanos-io/thanos/commit/b7f3ac9e758d29765f8a0b676f898fef72d73e3a this has not been in any official release yet!
