### ISSUE TITLE
Thanos compactor stuck on downsampling?

### ISSUE THREAD

**Issue by Jonnymcc** [thanos-io/thanos#1771]
**Thanos, Prometheus and Golang version used**: image: quay.io/thanos/thanos:v0.8.0

**Object Storage Provider**: S3

**What happened**: Compactor started downsampling and appeared to make no progress. It eventually hit the memory limit (40GB) for the pod in Kubernetes and is terminated.

**What you expected to happen**: A log message saying that a block has been downsampled. My understanding is that each block would be downloaded, downsampled, and then uploaded back to the bucket.

**How to reproduce it (as minimally and precisely as possible)**: Not sure.

**Full logs to relevant components**:

```
level=info ts=2019-11-21T00:19:33.796596397Z caller=compact.go:1069 msg="start of GC"
level=info ts=2019-11-21T00:19:33.797001158Z caller=compact.go:1075 msg="start of compaction"
level=info ts=2019-11-21T00:19:33.831505526Z caller=compact.go:264 msg="compaction iterations done"
level=info ts=2019-11-21T00:19:33.831529668Z caller=compact.go:271 msg="start first pass of downsampling"
level=info ts=2019-11-21T00:28:48.542147196Z caller=downsample.go:257 msg="downloaded block" id=01DRGCN74V2S71A5VAR5GS9ERX duration=9m14.046528213s
```
This is where the log ends.

**Anything else we need to know**:
Bucket total size > 1TB
Number of objects in bucket ~ 10.5k
Total size of 01DRGCN74V2S71A5VAR5GS9ERX in bucket is 40.2GB

**Comment by bwplotka** [comment]
It's OOM and while we optimized the downsampling process a lot, there still has to be more memory than biggest block.
