### ISSUE TITLE
Remote read in Store API has a high overhead

### ISSUE THREAD

**Issue by nextus** [thanos-io/thanos#1774]
**Thanos, Prometheus and Golang version used**:

```
thanos, version 0.8.1 (branch: HEAD, revision: bd8278859b2321aaaa7514edde764816cc039d34)
  build user:       root@2227d9a2fdb1
  build date:       20191014-12:03:55
  go version:       go1.13.1
```
```
prometheus, version 2.14.0 (branch: HEAD, revision: edeb7a44cbf745f1d8be4ea6f215e79e651bfe19)
  build user:       root@df2327081015
  build date:       20191111-14:27:12
  go version:       go1.13.4
```
```
/usr/bin/thanos sidecar --log.level=info --log.format=logfmt --grpc-address=0.0.0.0:10901 --http-address=0.0.0.0:10902 --prometheus.url=http://localhost:9090/prometheus --tsdb.path=/opt/prometheus/data --objstore.config-file=/etc/thanos/s3.yaml
/usr/bin/thanos query --log.level=info --log.format=logfmt --grpc-address=0.0.0.0:10903 --http-address=0.0.0.0:10904 --query.partial-response --store=localhost:10901
/opt/prometheus/prometheus --config.file=/etc/prometheus/prometheus.yml --web.external-url=http://0.0.0.0:9090/prometheus/ --storage.tsdb.path=/opt/prometheus/data --storage.tsdb.retention.time=6h --storage.tsdb.max-block-duration=2h --storage.tsdb.min-block-duration=2h --query.timeout=30s --query.max-concurrency=8 --web.enable-admin-api
```

**Object Storage Provider**:
S3

**What happened**:
Response time is 10 times slower using Store API than using Prometheus API endpoint for specific requests.

**What you expected to happen**:
Less overhead in response time using Store API.

**How to reproduce it (as minimally and precisely as possible)**:
Compare response time during querying data with large amount of samples.

**Anything else we need to know**:
I have built a very simple setup to rid of any overhead by network and other components:
`Thanos query --> Thanos sidecar --> Prometheus`
Each of it runs on the same server and  loopback interface is used for IPC.

So there are two queries which are self-explanatory:
```
$ curl -sw '%{time_total} %{size_download}\n' -o /dev/null 'http://localhost:10904/api/v1/series?match[]=http%3Ainternal_request_client%3Aresponses_by_path' 
9.869466 27584266
$ curl -sw '%{time_total} %{size_download}\n' -o /dev/null 'http://localhost:9090/prometheus/api/v1/series?match[]=http%3Ainternal_request_client%3Aresponses_by_path' 
1.227189 22965566
```
As the result I got a response with ~35700 series.
Response size from Store API is larger due to lack of external labels in Prometheus API's response. Don't know whether it is expected behavior or not.

I tried querying with older Prometheus instance before [remote read streaming](https://prometheus.io/blog/2019/10/10/remote-read-meets-streaming/) was implemented and after ~7 seconds I get an error about exceeding sample limit while using Store API:
```
desc = query Prometheus: request failed with code 400 Bad Request; msg exceeded sample limit (50000000)
``` 
Requesting directly from the Prometheus API still works though.

As I can see, Prometheus is a bottleneck during the Store API querying wastes a lot of CPU cycles.
There are [flamegraphs](http://www.brendangregg.com/flamegraphs.html) which can help to shed light on the root cause of this overheard. The [short.svg](https://nextus.me/pub/thanos/short.svg) and [long.svg](https://nextus.me/pub/thanos/long.svg) were recorded during the Prometheus API and Store API querying respectively. GitHub doesn't allow to attach SVG files so had to use shared hosting. Sorry about that.

**Comment by nextus** [comment]
I may suggest that there is some inefficient algorithm with querying metadata from Prometheus (`/series` endpoint) using remote read API comparing to HTTP Prometheus API.

**Comment by bwplotka** [comment]
Hi, thanks for reporting!

It looks to me like there is no regression, you just ask for a huge amount of data, and in previous Prometheus, we shutdown on a huge amount of samples, vs in newer we rely on latency and timeout.

Thanks for the flamegraphs, it actually shows things as expected, the majority of CPU is spent on encoding chunks. To resolve this we need: https://github.com/prometheus/prometheus/pull/5882 .. need to get back to this (: 

I have two ideas on how to improve things even further:
* Extend Series method of StoreAPI with some `onlySeries bool` or enum. This is to let know all implementations to do not send any samples, just labels of series. We might adjust the response, or just stream series with zero chunks. I think the latter makes sense.
* Sidecar then based on this can decide to use `series` API of prometheus instead of remote read (: 


cc @GiedriusS @squat to check on me if that makes sense (:

**Comment by bwplotka** [comment]
We propose this: https://github.com/thanos-io/thanos/issues/1822

**Comment by nextus** [comment]
One of the real use case.

There is a [label_values](https://grafana.com/docs/grafana/latest/features/datasources/prometheus/#query-variable) function in Grafana templating which is relies on `/series` API calls. So, some invocations with a huge amount of series can be much slower using Thanos query rather than Prometheus.
