### ISSUE TITLE
thanos receive: storing locally fails with err="failed to non-fast add: out of bounds"

### ISSUE THREAD

**Issue by kai-laufer** [thanos-io/thanos#1775]
**Thanos, Prometheus and Golang version used**:
- Thanos: thanos, version 0.7.0 (branch: HEAD, revision: c6eaf68bec32aefd280318eaef6121d6ddb20d10), go version:       go1.12.5
- Prometheus: prometheus, version 2.12.0 (branch: HEAD, revision: 43acd0e2e93f9f70c49b2267efa0124f1e759e86), go version:       go1.12.8

**Object Storage Provider**:
- Ceph RadosGW (S3)

**What happened**:
I've configured thanos receive today and everything seemed to be fine. Now I see billions of log entries like this:
```2019-11-21T14:38:56.650807+01:00 hostname thanos-receiver[25350]: level=error ts=2019-11-21T13:38:56.65035947Z caller=handler.go:307 component=receive component=receive-handler msg="storing locally" err="failed to non-fast add: out of bounds" endpoint=http://hostname:19291/api/v1/receive```
I don't see any data gaps yet but I want to use it in production and I have to be sure that everything works fine and as expected. 

**What you expected to happen**:
No log entries with level=error ;-)

**How to reproduce it (as minimally and precisely as possible)**:
I've configured thanos receive and prometheus remote write. I don't really know how to reproduce this. I see the error in the log as soon as I start thanos receive and WALs are loaded.

**Full logs to relevant components**:
<p>

```
2019-11-21T14:38:56.650807+01:00 hostname thanos-receiver[25350]: level=error ts=2019-11-21T13:38:56.65035947Z caller=handler.go:307 component=receive component=receive-handler msg="storing locally" err="failed to non-fast add: out of bounds" endpoint=http://hostname:19291/api/v1/receive
```
</p>

**Anything else we need to know**:
The S3-bucket has already around 900 GB and I'm using it for a month now. So a lot of data...
It would be really really nice to have a documentation for Thanos receive. At the moment there is only this document: https://thanos.io/proposals/201812_thanos-remote-receive.md/

**Environment**:
- OS (e.g. from /etc/os-release): Debian GNU/Linux 10 (buster)
- Kernel (e.g. `uname -a`): Linux hostname 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u2 (2019-08-08) x86_64 GNU/Linux

Please let me now if you need further information.

**Comment by squat** [comment]
hi @kai-laufer, over the past month we’ve made a ton of improvements to thanos receive, including fixing those out of bound errors (#1563, #1616, #1627). Please test using the latest thanos which includes these fixes :)

**Comment by kai-laufer** [comment]
Hi again,

with the latest version I'm getting those errors:

<p>

```
2019-11-21T17:38:29.646033+01:00 hostname thanos-receiver[31198]: level=error ts=2019-11-21T16:38:29.645958946Z caller=handler.go:332 component=receive component=receive-handler msg="storing locally" err="failed to non-fast add 92 samples: out of bounds" endpoint=http://hostname:19291/api/v1/receive
2019-11-21T17:38:29.647066+01:00 hostname thanos-receiver[31198]: level=warn ts=2019-11-21T16:38:29.646980763Z caller=writer.go:82 component=receive component=receive-writer msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=83
```

</p>

I'll let it run for a while an I'll keep an eye on that. Maybe the messages disappear.

**Comment by squat** [comment]
This is good, it means that thanos is correctly identifying samples and rejecting them. It will be sending the correct status code to Prometheus so that prom doesn’t continue to re-try sending those samples forever, which used to happen and was the cause of those millions of logs.

At the heart of it, the cause of these errors is that Prometheus is sending samples that are older than the beginning of the open tsdb block in thanos. That could be because there is clock skew in your system, or because Prometheus is just catching up and once it is up to date the errors will stop. Please check the clocks and let us know if the errors stop.

**Comment by kai-laufer** [comment]
Hi @squat,
thanks again! It looks much better now. This issue can be closed now.
