### ISSUE TITLE
Ruler: Add authentication options query

### ISSUE THREAD

**Issue by diemus** [thanos-io/thanos#1778]
version:0.8.1

        http://user:password@xxxx.com/api/v1/query?dedup=true&partial_response=false&query=probe_failed_due_to_http_status_code+%21%3D+0&time=2019-11-22T14%3A37%3A10.387097931%2B08%3A00
        level=error ts=2019-11-22T06:37:10.53514552Z caller=rule.go:775 err="unmarshal query instant response: invalid character '<' looking for beginning of value" 

I copy the url to postman and it returns a json result. it seems the ruler can not perform a basic auth request

**Comment by bwplotka** [comment]
Yup, let's get back to this. It would be nice to add authentication options similar as we plan to do against Alermanager https://github.com/thanos-io/thanos/issues/606

It would really nice to have it composed as a `query.config<-files>` instead of `query.file-sd` FileSD we have in Thanos, similar to the Prometheus scrape config: 

```
	// A set of query parameters with which the target is scraped.
	Params url.Values `yaml:"params,omitempty"`
	// The HTTP resource path on with Query API endpoint.
	Path string `yaml:"path,omitempty"`
	// The URL scheme with which to fetch metrics from targets.
	Scheme string `yaml:"scheme,omitempty"`
       // List of addresses with dns prefixes.
       StaticAddresses []string `yaml:"file_sd_configs,omitempty"`
       // List of file  configurations (our FileSD supports different dns lookup)
       FileSDConfigs []*file.SDConfig `yaml:"file_sd_configs,omitempty"`
       HTTPClientConfig       config_util.HTTPClientConfig     `yaml:",inline"`
```

cc @simonpasquier

**Comment by daixiang0** [comment]
@bwplotka does anyone take this?

**Comment by simonpasquier** [comment]
@daixiang0 I'll send a PR today

**Comment by daixiang0** [comment]
@simonpasquier cool
