### ISSUE TITLE
ruler: silently mangles rules read from config (subqueries)

### ISSUE THREAD

**Issue by bjakubski** [thanos-io/thanos#1779]
Thanos official docker 0.8.1.
Also checked with master 8a8f576a go 1.13

**What happened**:

When investigating thanos ruler alerting rules not firing I've noticed that thanos mangled all my rules that used subquery with offset.

Rules shown (and executed) in ruler are different than ones in config files with rules.

**What you expected to happen**:

rules read cannot be altered and should be executed as-is

**How to reproduce it (as minimally and precisely as possible)**:

I've reduced offending query to a simple case:
```
rate(some_metric[1h:5m] offset 1d)
```
it is nonsensical, but it is enough to demonstrate a problem
Case can be reproduced in single command

```
thanos rule --query foobar --rule-file <(echo 'groups: [ {name: test, rules: [{ alert: Test, expr: "rate(some_metric[1h:5m] offset 1d)" }] } ]')
```

After accessing localhost:10902 one can see that instead of
```
rate(some_metric[1h:5m] offset 1d)
```
thanos ruler shows
```
rate(some_metric[1h:5m])
```

While this minimal example has nonsensical expr: my real query demonstrating this problem works as expected under normal circumstances i.e. if I go to thanos query and execute my query with "offset" added back where it should be I get proper results.

I was only able to reproduce this problem when there in query there both subquery and offset used.

This is quite serious as it is a *silent* failure. Nothing visible happens. But queries are mangled and (in my case) they never alert when they should if queries were untouched.

**Comment by bjakubski** [comment]
This seems to be prometheus problem. Same thing happens with bare prometheus.
I'll try to confirm/report upstream tomorrow

**Comment by bwplotka** [comment]
Yup, I played with this on Prometheus side as well and it looks really similar issue is there.

**Comment by bjakubski** [comment]
https://github.com/prometheus/prometheus/pull/6373
