### ISSUE TITLE
reloader: config reloader doesn't trigger normally in k8s when secret has updated

### ISSUE THREAD

**Issue by wujie1993** [thanos-io/thanos#1780]
**Thanos, Prometheus and Golang version used**:

thanos: v0.8.1
prometheus: v2.13.1
golang: v1.13.1

**Object Storage Provider**:

**What happened**:

The reloader does not trigger properly when the configuration file is changed using the mv command or by modifying the secret with k8s. In other words, when an event occurs that causes the inode of the configuration file to change, the reloader does not trigger properly.

**What you expected to happen**:

When the secret corresponding to the configuration file is updated in k8s or the original configuration file is overwritten with the mv command, the reloader should trigger a reload.

**How to reproduce it (as minimally and precisely as possible)**:

1. prepare the demo
```
package main

import (
	"context"
	"fmt"
	"net/url"
	"os"

	"github.com/go-kit/kit/log"
	"github.com/thanos-io/thanos/pkg/reloader"
)

const (
	logFormatLogfmt = "logfmt"
	logFormatJson   = "json"
)

func main() {
	logger := log.NewLogfmtLogger(log.NewSyncWriter(os.Stdout))
	logger = log.With(logger, "ts", log.DefaultTimestampUTC)
	logger = log.With(logger, "caller", log.DefaultCaller)

	reloadURL, _ := url.Parse("http://localhost:9090/-/reload")
	r := reloader.New(logger, reloadURL, "/etc/prometheus/config/prometheus.yml", "/etc/prometheus/config_out/prometheus.yml", nil)
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	if err := r.Watch(ctx); err != nil {
		fmt.Println(err)
	}
}
```

This case means that watching /etc/prometheus/config/prometheus.yml.If there is a change, then update to /etc/prometheus/config_out/prometheus.yml and trigger http://localhost:9090/-/reload to reload.

2. prepare two config file

/etc/prometheus/config/prometheus.yml
```
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
```

/etc/prometheus/config/prometheus1.yml
```
global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 30s
```

3. running the demo

4. update config file using `mv` command

```
mv -f /etc/prometheus/config/prometheus1.yml /etc/prometheus/config/prometheus.yml
```

**Full logs to relevant components**:

```
level=info ts=2019-11-22T09:46:29.6807622Z caller=reloader.go:315 msg="Prometheus reload triggered" cfg_in=/etc/prometheus/config/prometheus.yml cfg_out=/etc/prometheus/config_out/prometheus.yml rule_dirs=
level=info ts=2019-11-22T09:46:29.6808464Z caller=reloader.go:162 msg="started watching config file and non-recursively rule dirs for changes" cfg=/etc/prometheus/config/prometheus.yml out=/etc/prometheus/config_out/prometheus.yml dirs=
```

**Anything else we need to know**:

**Comment by daixiang0** [comment]
In fact there is too many issue about `rename` event in fsnotify, like [issue1](https://github.com/fsnotify/fsnotify/issues/214), [issue2](https://github.com/fsnotify/fsnotify/issues/26) and so on.
The fsnotify author reject this feature from OS/platform level.
Since thanos is cross-platform as well, maybe we need to keep same action with fsnotify does.
cc @thanos-io/thanos-maintainers
