### ISSUE TITLE
Missing Down Sampled Data

### ISSUE THREAD

**Issue by weedmaps-andychan** [thanos-io/thanos#1808]
**Thanos, Prometheus and Golang version used**:
Thanos: 0.8.1
Prometheus: v2.14.0
Golang: 

```
/ # thanos --version
thanos, version 0.8.1 (branch: HEAD, revision: bd8278859b2321aaaa7514edde764816cc039d34)
  build user:       circleci@a2c5dc5a83e9
  build date:       20191014-12:16:51
  go version:       go1.13.1
/ #
```

**Object Storage Provider**: AWS S3

**What happened**:
When using the following query in Thanos for 7 days metrics, we are missing a day of calculated metrics ONLY we are using auto/5m/1hr downsampling.  With RAW Data only, everything works fine.

`rate(container_cpu_usage_seconds_total{container_label_io_rancher_project_name="wm-thanos-production",container_label_io_rancher_project_service_name="wm-thanos-production/autoflower"}[30s])
`

**What you expected to happen**:
No missing data

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:
It is happening in our production environment and don't see any warning or errors in compactor.

**Anything else we need to know**:
We had compactor retention turned on previously and we are losing all of the data.  We turned off the retention so we preserved the raw data.

```
COMPACTOR_RETENTION_RESOLUTION_RAW=0d
COMPACTOR_RETENTION_RESOLUTION_5M=0d
COMPACTOR_RETENTION_RESOLUTION_1H=0d
```

**Comment by bwplotka** [comment]
Hi, you are not missing the data, your `rate` does not make sense for this query. e.g 5m resolution will have one sample per 5m, so if you rate with `[30s]` you will never have 2 samples which is required by rate (3 is recommended). If you want to query downsampled data you need `rate[1h]` for `5m` or larger for `1h` resolution.

We talked about this in our KubeCon talk: https://kccncna19.sched.com/event/UagR/thanos-deep-dive-inside-a-distributed-monitoring-system-bartlomiej-plotka-frederic-branczyk-red-hat (see slides attached)
 
TODO: Document it better on our docs.

**Comment by weedmaps-andychan** [comment]
Thanks!  This helps.
