### ISSUE TITLE
Clean partially downloaded index-cache.json

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#1810]
Looks like we missed this: https://cloud-native.slack.com/archives/CK5RSSC10/p1574932985449600

In case of crash do index-cache.JSON being partially downloaded/created we have garbage that store GW cannot handle right now. This requires manual cleanup of local disk which is not great.

AC:
* Handle partial index-cache JSON on store GW

**Comment by fatsheep9146** [comment]
I'd like to help with this.

I think we can check if the error returned by function `loadIndexCacheFileFromFile` is `unmarshal index cache`, then we can just skip/delete this one, let the function `WriteIndexCache` create a new one. 

@bwplotka What do you think?

**Comment by bwplotka** [comment]
Yup, that sounds good.
