### ISSUE TITLE
querier: Limit LabelNames; LabelValues to certain time period.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#1811]
Something that Cortex is doing is that `LabelNames;LabelValues` by default are limited to active series only on ingesters (so let's say in Thanos world to Thanos receiver or Prometheus for latest 2h). This is due to the fact that when you query you are usually interested in autocompletion for fresh metrics.

We are now exploring if we can apply the same logic for Thanos e.g limit `LabelNames` and `LabelValues` and `Series` (by default) on Querier QueryAPI to 2h. 

IF we don't do it, StoreGateway will have to load portions of the blocks in memory for full-time retention, for all store APIs, which is something we wanted to avoid. It was briefly mentioned here: https://github.com/thanos-io/thanos/issues/39 Also currently this is limited to raw data only, so it's already scoped for certain setups with retention for older blocks.

**Comment by ppanyukov** [comment]
Do I understand correctly this does not affect the query execution and any memory limits for that?

**Comment by bwplotka** [comment]
Which memory limits you have in mind?

**Comment by ppanyukov** [comment]
The limits on memory taken during query execution, as this PR attempts to address.

https://github.com/thanos-io/thanos/pull/1747

**Comment by bwplotka** [comment]
Yes, I still don't see how limits improve those methods. This issue is required to have fulfill this: https://github.com/thanos-io/thanos/issues/1813

**Comment by pracucci** [comment]
I would be glad to work on this. Few questions:

- Should the period be configurable?
- Should we introduce a breaking change enforcing a default of `2h`, or should we keep an unlimited default just introducing an option to slim it down?

> We are now exploring if we can apply the same logic for Thanos e.g limit LabelNames and LabelValues and Series (by default) on Querier QueryAPI to 2h.

FYI, Cortex doesn't enforce any short default for the `Series`. It currently uses Prometheus defaults, which is the entire history. Do we want to change this in Thanos, and enforce a default of `2h` for `Series` as well?

**Comment by bwplotka** [comment]
Nice! 
> Should the period be configurable?
yes
> Should we introduce a breaking change enforcing a default of 2h, or should we keep an unlimited default just introducing an option to slim it down?
We can introduce a breaking change if needed, but we need to be explicit in changelog. The question is, should we?

So what makes me think we should have `unlimited` default, for now: is the fact that if user goes to the dashboard with some templates using those APIs and asks for data month ago it will get label values for active series. Let's say he had `eu4-production` cluster month ago and now not, he won't be able to see it in his Grafana variables, right? (: I think it's should be a Thanos user choice.

I think simultaneously we should start a discussion about: 

* templates https://grafana.com/docs/features/datasources/prometheus/#templating being based on time
* LabelNames/LabelValues being based on time

In terms of `series` those are already based on time, but we should in similar way define a default if not time range is specified, based on some flag we define: "just introducing an option to slim it down?"

**Comment by brancz** [comment]
I personally think this should actually even be a query parameter on the API endpoints. I believe there are even issues about this on Prometheus. A Prometheus with many blocks is just as affected by this as Thanos/Cortex are. I feel by default those endpoints should only respond with the active label names/values everywhere.

**Comment by davkal** [comment]
> This is due to the fact that when you query you are usually interested in autocompletion for fresh metrics.

I'd challenge this fact, and I've been bitten by this in post-mortems where I set the time picker in Grafana to the time of incident and then tried to get typeahead suggestions for instances that at the time of querying were long gone.
Currently Cortex's series API ignores `start` and `end`, so I don't get the behavior I expect.
The downside would be though that if those non-recent queries would take long (e.g. >2s) then it's kind of pointless anyway for tab completion.

**Comment by bwplotka** [comment]
I agree with the functionality and latency aspect here as I mentioned:

> So what makes me think we should have unlimited default, for now: is the fact that if the user goes to the dashboard with some templates using those APIs and asks for data month ago it will get label values for active series. Let's say he had `eu4-production` cluster month ago and now not, he won't be able to see it in his Grafana variables, right?

In terms of Thanos there is a clear improvement to be done for series  http://github.com/thanos-io/thanos/issues/1822

@davkal so if Prometheus upstream would have `labelNames` and `labelValues` with parameters  `start` and `end` time, I guess it's trivial to make sure Grafana passes those in e.g dashboards templates? Also, are those APis used in `Explore UI` as well?

**Comment by davkal** [comment]
> so if Prometheus upstream would have labelNames and labelValues with parameters start and end time, I guess it's trivial to make sure Grafana passes those in e.g dashboards templates? Also, are those APis used in Explore UI as well?

Theoretically yes. But so far it's been more nuanced:

- We're using the label API for the initial request to populate the metrics selector and metrics suggestions in the query field. So far that's unbounded and in Prometheus would return *all* lifetime labels AFAIK.
- For the label completion we're using the series API because it allows us facetting: returning subsets of possible label spaces as opposed to the whole label space. The series API supports time parameters and we make use of that.
- We have not used the series API for the initial metrics selector requests because an empty series API request would in effect return all series and historically had poor performance (and returned much more data than needed).

When time parameters are supported by the API, it's trivial to plug them in for both dashboards and Explore.

**Comment by brancz** [comment]
I believe this is still something we want to work on.

**Comment by bwplotka** [comment]
Still valid.

**Comment by bwplotka** [comment]
TODO: Propose a new API to Prometheus.

**Comment by bwplotka** [comment]
Proposed: https://github.com/prometheus/prometheus/issues/6865

**Comment by bwplotka** [comment]
Still needed (:

**Comment by bwplotka** [comment]
Blocked on Prometheus issue.

**Comment by bwplotka** [comment]
This is done on Prometheus, so we can do here as well.

**Comment by bwplotka** [comment]
This was done on Prometheus side, so we can start using it! Help wanted

**Comment by bwplotka** [comment]
The params were added but limit not introduced yet @kakkoyun is working on it.
