### ISSUE TITLE
Should reloader reload empty configuration files ？

### ISSUE THREAD

**Issue by yahaa** [thanos-io/thanos#1812]
**Thanos, Prometheus and Golang version used**:
* thanos v0.5.0

**Object Storage Provider**:

**What happened**:
When I add the following test case(case 3) to pkg/reloader/reloader_test.go `TestReloader_ConfigApply` ，i found that reloader reload the empty cfgFile to cfgOutputFile, so the configuration of prometheus is overwritten by the empty file。
```go
switch rel {
			case 1:
				// Initial apply seen (without doing nothing)

				// Output looks as expected?
				f, err := ioutil.ReadFile(output)
				testutil.Ok(t, err)

				testutil.Equals(t, `
config:
  a: 1
  b: 2
  c: 3
`, string(f))

				// Change config, expect reload in another iteration.
				testutil.Ok(t, ioutil.WriteFile(input, []byte(`
config:
  a: changed
  b: $(TEST_RELOADER_THANOS_ENV)
  c: $(TEST_RELOADER_THANOS_ENV2)
`), os.ModePerm))
			case 2:
				f, err := ioutil.ReadFile(output)
				testutil.Ok(t, err)

				testutil.Equals(t, `
config:
  a: changed
  b: 2
  c: 3
`, string(f))
				// Change config, expect reload in another iteration.
				testutil.Ok(t, ioutil.WriteFile(input, nil, os.ModePerm))
			case 3:
				f, err := ioutil.ReadFile(output)
				testutil.Ok(t, err)

				testutil.Equals(t, `
config:
  a: changed
  b: 2
  c: 3
`, string(f))
```

**What you expected to happen**:
In the case 3 above,i expect the final configuration file to remain the same of case 2,but i got `""`，so I want to ask if it is reasonable to reload the empty configuration file ？

```text
exp: "\nconfig:\n  a: changed\n  b: 2\n  c: 3\n"

got: ""
```

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:
```go
if r.cfgOutputFile != "" {
    b, err := ioutil.ReadFile(r.cfgFile)
    if err != nil {
         return errors.Wrap(err, "read file")
    }

   // Would skipping empty file execution logic be a good solution？
    if len(b) == 0 {
        return nil
    }
}
```

**Comment by bwplotka** [comment]
I think yes. This is because we want to delegate validation of the given configuration file to the Prometheus itself. This way Prometheus can tell properly signal it via metric and log line and fallback to the old configuration as expected. We are just allowing to watch and reload Prometheus file, nothing more
