### ISSUE TITLE
Make the IndexCache shared cache friendly

### ISSUE THREAD

**Issue by pracucci** [thanos-io/thanos#1815]
Currently, the `IndexCache` is an in-memory cache whose exposed interface allow to cache single Postings and Series. In Cortex we've an experimental TSDB blocks storage integration based on Thanos and we would like to introduce a shared index cache (based on Memcached).

The current `IndexCache` interface is not shared cache friendly, due to the fact that the exposed functions allow to query/cache single items. In a shared cache implementation, this would require a single round trip for each cache key. We would like to change the `IndexCache` to `MultiPostings()` / `MultiSeries()` to make it shared cache friendly and - before working on it - we would like to reach some consensus.

## Proposal

We propose to switch the `IndexCache` to the following interface:

```
type IndexCache interface {
    // MultiPostings fetches multiple postings - each identified by a labels set -
    // and return a map containing cache hits. In case of no cache hit, an empty
    // map is returned.
    MultiPostings(b ulid.ULID, keys []labels.Label) (map[label.Label][]byte, error)

    // MultiSeries fetches multiple series - each identified by ID - from the cache
    // and return a map containing cache hits. In case of no cache hit, an empty
    // map is returned.
    MultiSeries(b ulid.ULID, ids []uint64) (map[uint64][]byte, error)

    SetPostings(b ulid.ULID, l labels.Label, v []byte)
    SetSeries(b ulid.ULID, id uint64, v []byte)
}
```

- Read path: load postings and series - for a single block - within a single round trip
- Write path: keep setters for single cache keys because (a) ease to integrate (nothing to do) (b) memcached doesn't support multi set (c) no synchronous requirements in the cache write path, so multiple `SetSeries()` for the same block can be shortly buffered in the cache implementation and then stored with a single multi set API call (ie. supported by Redis)

_We currently propose to only change the `IndexCache` interface to allow Cortex using a custom index cache based on Memcached, but we're open to work on adding a shared cache support to Thanos too in subsequent PRs if there's some interest._

**Comment by bwplotka** [comment]
Yes! As discussed offline this is definitely something we have to introduce. Shared cached is the key to horizontally scale Store GW in terms of request traffic with some round-robin on top.

Making it multiXXX is the same way we use it right now (we iterate because of the current interface). 

> MultiPostings(b ulid.ULID, keys []labels.Labels) (map[label.Labels][]byte, error)
I think it;'s a typo and you meant `labels.Label` in map (: 

It's totally fine to have `Memcached` support, for now, we can add others later if really needed.

**Comment by pracucci** [comment]
> Yes! As discussed offline this is definitely something we have to introduce.

Excellent. I will work on it next week.

> I think it's a typo and you meant labels.Label in map (:

Ops, yes. Fixed the issue description.

> It's totally fine to have Memcached support, for now, we can add others later if really needed.

So would you see OK a PR to add memcached index cache support directly into Thanos?

**Comment by bwplotka** [comment]
> So would you see OK a PR to add memcached index cache support directly into Thanos?

Definitely.
