### ISSUE TITLE
Thanos compactor empty chunks

### ISSUE THREAD

**Issue by salapat11** [thanos-io/thanos#1818]
Prometheus: 2.9.2
Thanos: v0.5.0
Object Storage Provider: S3

Thanos compactor logs show "caller=streamed_block_writer.go:139 emptychunkshappened,skipseries".  What cause the empty chunks and how to avoid them?

**Comment by bwplotka** [comment]
Thanos code automatically avoids those, but there were at some point produced by Prometheus. Not need to worry too much about this, but it's interesting if that still happens on with Prometheus.

Let us know if that's the case or if you see any serious issue caused by this. (:

**Comment by salapat11** [comment]
There were lot of warnings in the Compactor log but did not impact the compactor.  I was only concerned if there maybe gaps in the samples

**Comment by bwplotka** [comment]
No, if chunks are empty, then there was no data in the first place. It's rather suggesting potentially Prometheus inefficiently produce empty chunks in an unnecessary way for some edge case.

**Comment by salapat11** [comment]
Thanks for the clear explanation, @bwplotka
