### ISSUE TITLE
Add no-chunks `Store.Series` option to StoreAPI 

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#1822]
Querier HTTP `/series` [API](https://prometheus.io/docs/prometheus/latest/querying/api/#finding-series-by-label-matchers) is returning metadata, so series matched by labels.

For Thanos this uses StoreAPI.Series which also returns full chunks for whole requested time period. However the only labelset is required. 

I would propose:
* Extend Series method of StoreAPI with some `no-chunk` bool or enum. This is to let know all implementations to do not send any samples, just labels of series. We might adjust the  response, or just stream series with zero chunks. I think the latter makes sense.
* Sidecar then based on this can decide to use series API of Prometheus instead of remote read (:

**Comment by daixiang0** [comment]
I would like to do this. Before it, i want to confirm the work:

- Add an option like `seriers-address` which uses the rule of StoreAPI
- Support sidecar read from series API

**Comment by GiedriusS** [comment]
Hi @daixiang0,

> I would like to do this. Before it, i want to confirm the work:
> 
>     * Add an option like `seriers-address` which uses the rule of StoreAPI
> 
>     * Support sidecar read from series API

What do you mean by 
> Add an option like `seriers-address` which uses the rule of StoreAPI

?

Btw, the original proposal by @bwplotka IMHO makes sense. We should also probably mention in this ticket that it came from https://github.com/thanos-io/thanos/issues/1774 and should fix it.

**Comment by bwplotka** [comment]
Please elaborate @daixiang0 (: what `rule` here means?
