### ISSUE TITLE
upload Prometheus data into AWS S3 failed!

### ISSUE THREAD

**Issue by KeepCaim** [thanos-io/thanos#1828]
**Thanos, Prometheus and Golang version used**:
```
prometheus, version 2.10.0 (branch: HEAD, revision: d20e84d0fb64aff2f62a977adc8cfb656da4e286)
  build user:       root@a49185acd9b0
  build date:       20190525-12:28:13
  go version:       go1.12.5
```
```
thanos, version 0.9.0-rc.0 (branch: HEAD, revision: b61c2a54e48b3dfdcdf8eec6c2b5f6b2d2de9bbd)
  build user:       root@9943636e3897
  build date:       20191127-17:32:15
  go version:       go1.13.1
```

**Object Storage Provider**:
s3
**What happened**:
bucket_config.yaml
```
type: S3
config:
  bucket: "thanos-prometheus"
  endpoint: "pub1-bjyt.s3.360.cn"  # s3 domian
  region: "pub1-bjyt-s3"
  access_key: "dada3rTXZXmYwB"
  secret_key: "dadaTMX45GFEBwaCq7XyzVZR95gvCQhqAzneW"
  insecure: true
  signature_version2: false
  encrypt_sse: false
  put_user_metadata: {}
  http_config:
    idle_conn_timeout: 90s
    response_header_timeout: 2m
    insecure_skip_verify: false
  trace:
    enable: false
  part_size: 134217728
```

```
level=info ts=2019-12-03T10:28:08.672429921Z caller=shipper.go:349 msg="upload new block" id=01DV5FSQS0096979Z36ZCWCPH0
level=error ts=2019-12-03T10:28:08.702214798Z caller=shipper.go:316 msg="shipping failed" block=01DV5FSQS0096979Z36ZCWCPH0 err="upload meta file to debug dir: upload file /data/prometheus/thanos/upload/01DV5FSQS0096979Z36ZCWCPH0/meta.json as debug/metas/01DV5FSQS0096979Z36ZCWCPH0.json: upload s3 object: Copy Source must mention the source bucket and key: sourcebucket/sourcekey"
level=warn ts=2019-12-03T10:28:08.70419576Z caller=sidecar.go:311 err="failed to sync 4 blocks" uploaded=
```
Can you help me , @bwplotka
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by bwplotka** [comment]
Is it regression or you just start setting things up? i.e did it work on previous version?

**Comment by KeepCaim** [comment]
Thank you very much for your reply，I just started using thanos today.It's great, except for uploading data into s3

**Comment by GiedriusS** [comment]
Does it work if you switch to 0.8?

**Comment by bwplotka** [comment]
Unfortunately, we cannot reproduce it in our environments. 

It's also weird as this error happens to be on` CopyObject` version of PUT AWS operation not really PUT,  but we strictly upload here from filesystem...

Any luck with the older version? What S3 provider are you exactly using?

**Comment by KeepCaim** [comment]
thanks @GiedriusS @bwplotka , Now, our s3 not support trunk upload signature ...   
I'm going to use  federated  prometheus  witn thanos temporarily， local-storage.
