### ISSUE TITLE
compact: Hanging upload

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#1830]
As referred in https://gitlab.com/gitlab-com/gl-infra/infrastructure/issues/

TODO: Get more info, type of storage, last log line from @SuperQ

**Comment by cstyan** [comment]
As discussed on Slack, looks like we've just run into the same issue.

We're using GCS, last log line is:

```
level=info ts=2019-11-30T04:53:44.700533615Z caller=compact.go:440 msg="compact blocks" count=6 mint=1574899200000 maxt=1575072000000 ulid=01DTX9XYZZDSWKT2BRYM59CGT9 sources="[01DTS3ZE5QSVSC0D06PPH81ZKA 01DTSRJJXYNV5H9DZ806QT0JND 01DTTM1F3G68Y1107WNEA30XN7 01DTVFH73PH5AABGDM293P9V8K 01DTWAZY17ZXK645R1EP3YFST9 01DTX6DMWGMH65R10QX1QK7TV7]" duration=10m17.751658532s
```

So it looks like the upload is stuck, no log lines about those source blocks being deleted.

**Comment by bwplotka** [comment]
Do you think we can grab the pprof goroutines if that will happen again @cstyan @SuperQ

**Comment by SuperQ** [comment]
Yes, I'll see what I can do.

**Comment by bwplotka** [comment]
Still valid, pinning.

**Comment by bwplotka** [comment]
Still we need some timeout.

**Comment by bwplotka** [comment]
Still timeout pliz (:

**Comment by bwplotka** [comment]
Still todo

**Comment by bwplotka** [comment]
The task is quite easy: To ensure timeouts for uploads. (:

**Comment by SuperQ** [comment]
Still TODO.
