### ISSUE TITLE
Store server does not report error when some blocks cannot be read.

### ISSUE THREAD

**Issue by sanamana** [thanos-io/thanos#1846]
Versions:
Thanos: 0.8.1
Prometheus: 2.13
golang: 1.12.9

What happened:
The store server query processing identified the blocks that need to be read. However, some of the blocks were corrupted (reading the blocks errors out: 01DSMJ2YWJ508PWSGVX0Z4JDA1: preload chunks: preloaded chunk too small, expecting 2044).
When this happened the store server returned success.

Expected behavior:
When some blocks cannot be read, error should be returned to the client. 

More comments:
I looked at the code and it looks like this is not deterministic. The bucket.go uses github.com/oklog/run which returns error only if the first actor closes with error. Also the oklog package is not meant to be used in the it is being used by bucket.go.

**Comment by sanamana** [comment]
This is bug in the store component.

**Comment by bwplotka** [comment]
We actually use `errgroup` not oklog in the `bucket.go` in new code, exactly for this reason that oklog was not suitable there (: 


See: https://github.com/thanos-io/thanos/pull/1468

I believe that PR fixes this bug. Indeed I can see the error being dropped in older behavior if one block is fetched and second errors. Can you try `v0.9.0`?
