### ISSUE TITLE
command: force thanos to upload 

### ISSUE THREAD

**Issue by aslimacc** [thanos-io/thanos#1849]
Hello
Can I force thanos-sidecar to upload existing metrics to bucket because I don't want to loose 2 hours of metrics when I restart, considering that I don't want to use PVC 
Thanks

**Thanos, Prometheus and Golang version used**:
thanos: 0.32
prometheus: 2.14.0

**Object Storage Provider**:
gce-pd (standard)

**What happened**:
When I deleted prometheus+thanos-sidecar pod, I lost 2 hours metrics

**What you expected to happen**:
force upload metrics in bucket with CLI before deleting pod

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by daixiang0** [comment]
@bwplotka how about that add `/flush` to sidecar?

**Comment by bwplotka** [comment]
This not a sidecar problem. It's a Prometheus that has all metrics in memory/WAL.

We need this: https://github.com/prometheus/prometheus/pull/6424

And we might consider embedding some flush logic to sidecar indeed. Would be useful. But then same for Ruler.

But we need to be careful if we really want to do it in Thanos. You can already build sidecar that will do that  for you:

* Snapshot Prometheus
* Use https://github.com/observatorium/thanos-replicate to upload it (with some tweaking of replicate)

**Comment by bwplotka** [comment]
Closing as out of scope for now.

**Comment by underrun** [comment]
could this be revisited - currently thanos receive flushes on shutdown: https://github.com/thanos-io/thanos/pull/1480

alternately any links to gist or scripts or hacks to add to a deployment that would snapshot and upload on shutdown would be great as it's hard to figure out how a user would handle this from this thread and/or https://github.com/prometheus-junkyard/tsdb/issues/346 which both conclude that users can do this with a snapshot and upload somehow.

the somehow is very not obvious (or i'm missing something).

**Comment by Kampe** [comment]
I'd also like to see a resolution for this, losing 2 hrs of data on sidecar disposal is not ideal.

**Comment by toporek3112** [comment]
Ok, so I've been looking for an anwser but couldn't find one so I ask here.
Is it now possible to manualy trigger Thanos to flush?

**Comment by fpetkovski** [comment]
As @bwplotka mentioned above, this has to be done in Prometheus instead, and a similar issue was closed not so long ago https://github.com/prometheus/prometheus/issues/12261.

The reason why the Receiver can flush is because it runs the TSDB in the same process and has access to the necessary APIs. The sidecar runs out of process and there is no HTTP API in Prometheus to force a flush.

**Comment by toporek3112** [comment]
I see. Thank you for the fast response!
