### ISSUE TITLE
Upload container images for arm64 architecture

### ISSUE THREAD

**Issue by der-eismann** [thanos-io/thanos#1851]
Now that AWS announced their way more powerful M6g instances it will start to get interesting to move from x86 to the ARM architecture. You already provide binaries on the releases page, but the docker images are for x86 only. Could you maybe adjust your build pipeline and provide images for ARM like [prometheus does](https://hub.docker.com/r/prom/prometheus/tags)?

**Comment by bwplotka** [comment]
We can definitely consider this (: 

Help wanted to set it up.

**Comment by der-eismann** [comment]
I'd be happy to help, but unfortunately it seems like CircleCI [doesn't support it (yet)](https://ideas.circleci.com/ideas/CCI-I-900). There are some [hacky workarounds](https://github.com/zeprone/arm-circleci), but I'm not sure if this is the correct way. 

So actually I have no idea how to do this right now.

**Comment by daixiang0** [comment]
@bwplotka CircleCI does not support multi-arch for now but drone does.

**Comment by bwplotka** [comment]
I don't think we need any CI special feature for this:

Let's instead use the way Prometheus is doing this, so:
Docker build:
* https://github.com/prometheus/prometheus/blob/337a1fbffd17ad3c7952dadf1246ee6eedf57b01/Makefile.common#L213

And Dockerfile taking binaries from `promu` (we already use `promu` for the build process):
* https://github.com/prometheus/prometheus/blob/bca6e90ea6788100a56809e73f9eeaaa11480036/Dockerfile#L6

(:

**Comment by bwplotka** [comment]
Still valid, and in fact we have a PR ready - it's waiting on us to actually test it and update quay a bit.

**Comment by zosorock** [comment]
I am also looking into starting to test with m6g instances. Are there any prediction of when it will be available?

**Comment by autarchprinceps** [comment]
Is this still being worked on? I just tested and the thanos-sidecar in Prometheus is one of only a few containers that still make issues.

**Comment by bwplotka** [comment]
We had contributions to add the build/CI process. but I think there is some process of configuration on quay/dockerhub. To test and finish up.

cc @daixiang0

**Comment by daixiang0** [comment]
While I have no permission to test it, please help @bwplotka !

**Comment by xUnholy** [comment]
Available Thanos multi-arch images can be used here https://hub.docker.com/r/raspbernetes/thanos/tags?page=1&ordering=last_updated - This will support both arm64 and amd64, if armv7 is required it can be considered for adding. We'll be maintaining parity until upstream provides official support.

**Comment by bwplotka** [comment]
Let's talk offline then https://github.com/daixiang0

**Comment by daixiang0** [comment]
Take your time :)

**Comment by commixon** [comment]
Hello people! Is this still a valid thing? We would really like this as well (and are willing to help with anything as well)

**Comment by bwplotka** [comment]
Looks like it's getting quite a popular feature (: We already build such binaries - so you can easily build (`make crossbuild`) and upload to your own registry. Ideally we have someone who can configure docker registry for us 🙃 which is unlikely. For some reasons @daixiang0 had issues to access things from China I believe.

We will try to prioritize this on maintainer team (: Thanks!

**Comment by der-eismann** [comment]
FYI this is how we did it with GitHub actions, works fine for us so far:
https://github.com/rebuy-de/aws-nuke/blob/main/.github/workflows/release.yaml#L48-L78
Basically you need QEMU & buildx for docker, then it's possible to build for all arches.

**Comment by roidelapluie** [comment]
I don't think thanos requires this. I am happy to share promu with thanos.

**Comment by der-eismann** [comment]
till needed.

**Comment by autarchprinceps** [comment]
Still needed.

**Comment by der-eismann** [comment]
Remove the stale label please

**Comment by hanzZzZzZ** [comment]
Just found this issue, but I can confirm:
Still needed.

**Comment by ismashal** [comment]
We really needed this ARM64 supported official image into the docker hub and quay.io/thanos/thanos. As AWS already started the support graviton2 type images into the EKS. 
Thanks!

**Comment by WeiTangLau** [comment]
2 years later. Still needed

**Comment by firefixmaarten** [comment]
Still wanted :) +1

**Comment by GiedriusS** [comment]
https://quay.io/repository/thanos/thanos/manifest/sha256:ba0b9192a0db3693afcb220c4c1fc8578a1c25df20dc41697e57b3329fe1d7f8
https://hub.docker.com/layers/thanosio/thanos/main-2021-12-14-7793ab63/images/sha256-9dd0cee98ac7dc4f122e75d4fade9ba2452e8a9a2c0b8cb9a160e55ce1bae0f1?context=explore
We finally have arm64 images as well :tada: please test them out.

**Comment by WeiTangLau** [comment]
Hi @GiedriusS, given the latest release of v0.24.0 and v0.23.2 of thanos, the arm64 images are not built accordingly. Why is this so?

**Comment by jan-di** [comment]
@WeiTangLau Not a maintainer here, but i guess thats because the release candidates of those versions pre date the merge of this feature. See https://github.com/thanos-io/thanos/commits/v0.24.0. I think the next release (0.25) will have arm64 images.
