### ISSUE TITLE
Lock for compactors

### ISSUE THREAD

**Issue by sylr** [thanos-io/thanos#1869]
**Thanos, Prometheus and Golang version used**:

v0.8.1

**Object Storage Provider**:

Azure Blob Storage

**What happened**:

Had several jobs doing compaction at the same time (bogus configuration).

All jobs raced to do the compaction until deletion of old blobs where one did it faster than the others so the others failed.

**What you expected to happen**:

I'm wondering if we could have a lock written on the storage that prevents multiple compactors to run at the same time.

**Comment by GiedriusS** [comment]
Hi, have you seen https://thanos.io/proposals/201901-read-write-operations-bucket.md/? Seems like your request is a duplicate of that one.

**Comment by bwplotka** [comment]
Not really a duplicate of this, rather a dup of another proposal we used to work on here: https://github.com/thanos-io/thanos/pull/522

The problem here is how to do it without introducing extra dependency like etcd (: Or if really necessary, how to seamlessly introduce it.

**Comment by bwplotka** [comment]
Still valid.

**Comment by yeya24** [comment]
Still valid.
