### ISSUE TITLE
Move components names to `Ruler`, `Compactor`, `Querier` (`-er`)

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#1871]
It's maybe a minor but we should be consistent on naming. In the documentation, code and `thanos` command we have `rule, compact, downample, query` vs in some docs, deployments and most of the presentations we are leaking `Querier`, `Ruler`, `Compactor` 

This conflicts a bit with `Store Gateway` but we already have some discussion about renaming it: https://github.com/thanos-io/thanos/issues/1646

I would vote `-er` as it's more correct (aka `go` way of naming objects as well) and it avoids name collisions like `rule` (recording/alerting rule) vs `rule` (the component responsible for evaluating rules). 

**AC**: 
 < to agree>

Any thoughts?

**Comment by GiedriusS** [comment]
Makes sense, I agree.

**Comment by domgreen** [comment]
Why not also change `store` to `gateway` or `proxyer` whilst making changes?

**Comment by bwplotka** [comment]
Same for `receive` -> `receiver` I guess (:

**Comment by yeya24** [comment]
Anyone work on this issue? I guess I can take this 😆

**Comment by bwplotka** [comment]
Thanks. We need to decide what to do with metrics as well as they are all over the place with `query` `rule` etc, should we rename at once? @brancz any tips? (:

**Comment by bwplotka** [comment]
I think we need to be careful here as this minor consistency naming change might be not worth *everywhere* when introducing so many breaking changes ): Things like metrics, components will make our user life harder when upgrading.

**Comment by yeya24** [comment]
I think updating the metrics now might not be a good option. Just update the docs first.

**Comment by bwplotka** [comment]
:+1:

**Comment by brancz** [comment]
I feel like for how disruptive renaming the components would be, the gain would be too small. Yes we should be consistent in the metrics and component names, but in docs and presentations for the flow of the language we can use querier, ruler, etc. but otherwise the existing component names work just fine in my opinion and don't require changing.

**Comment by daixiang0** [comment]
@kakkoyun any process about this?

**Comment by bwplotka** [comment]
Due to compatibility issues I would say we stick to docs, new places we name things like Alert names, deployment names etc.

Metrics, command, and component names in code should stay for now.

**Comment by kakkoyun** [comment]
@daixiang0 This week I'll start working on this and primarily focus on docs.

**Comment by yeya24** [comment]
I am not sure is this still valid?

**Comment by kakkoyun** [comment]
@yeya24 Maybe we should break this into pieces. Like `thanos-mixin/compact` -> `thanos-mixin/compactor`,  `docs/compact`   -> `docs/compactor` and `cmd/compact` -> `cmd/compactor` etc.

WDYT?

**Comment by brancz** [comment]
I think we need to revisit our changes slightly here. I was under the assumption we’re only changing language in sentence form but keep technical references consistent so I think the mixin should use the command names in its structure and in let’s say alert descriptions use whatever is more fluent.

**Comment by kakkoyun** [comment]
My understanding from this issue was, we would eventually move to `*tor` naming schema, thus my changes.

And it's more clear now. 

Just to recap. we will keep structural build blocks (code references, filenames etc.) as in commands and only rename documentation (user guideline, alert message etc). Am I right?

**Comment by bwplotka** [comment]
Definitely, we have to find something consistent (: 

>  only changing language in sentence form
> keep technical references

What exactly this means? I assume:

* User `-er` `-or` in: 
  * While speaking about components
  * Presentations
  * Documentation
  * Code comments (?)
  * Log messages, traces?

* Keep the old way (and revert things that were made `-er` `-or`:
  * Metrics
  * Flags, configuration?
  * Code methods/structs
  * Package names

There are some gray areas like logging e.g which are not really tricky to change. I think we need to just put some list and agree on this. Anything else I missed?

**Comment by brancz** [comment]
That sounds perfect to me. I'll start applying that. Maybe it's worth documenting this in our [`CONTRIBUTING.md`](https://github.com/thanos-io/thanos/blob/master/CONTRIBUTING.md) ?

**Comment by bwplotka** [comment]
Definitely will add - and let's make sure we keep it up to date

**Comment by bwplotka** [comment]
Done: https://github.com/thanos-io/thanos/pull/2094

To close this issue we probably have to look through those items and ensure consistency. I know for sure there are metrics that are sometimes `compact` sometimes `compactor` etc.

**Comment by brancz** [comment]
I think we’re pretty close to having all the changes down for this. Only a few metric names have to be fixed I think.
