### ISSUE TITLE
Thanos side-car should be able to copy blocks to more than 1 remote storage endpoint.

### ISSUE THREAD

**Issue by sanamana** [thanos-io/thanos#1890]
We have the need to move the tsdb blocks from prometheus to more than 1 storage endpoint. I see that thanos side-car code enables it to write to only 1 remote storage endpoint. 

Is this something the community would be interested in?

I would like to modify this is such a way that multiple thanos side-car containers can be run against the same tsdb. I think if we make the location of side-car metadata file (thanos.shipper.json) configurable through a flag, then we can achieve this. I am open to other suggestions.

I will be happy to create a PR for this, if we can agree on the details.

**Comment by bwplotka** [comment]
Thanks for raising this. What about adding the ability to run multiple sidecars for this purpose? 

I think this might be tricky now due to single `thanos-shipper.json` but **if we would scope this by `thanos-shipper-<bucket-name>.json` this will be doable.** 

In any case, this change would be needed:
* even for single binary multi-target upload we would need to sync in two different files.
* the case when someone runs sidecar and then changes the target bucket in next rollout.

I would vote for starting with that first:

AC:
* Running two sidecars works   
  * Name of the shipper JSON file should be dependent on bucket name.

**Comment by sanamana** [comment]
Thank you for the feedback.

Here is our use-case. 

For our HA needs we run multiple tsdb nodes which contain same data as the other. And for DR these tsdb with multiple copies run in different regions. We have the thanos-sidecar deployed to write the blocks to ceph storage cluster local to the tsdb. So tsdb in region A will copy the blocks to ceph storage cluster in SLC. This has been good and works well.

We are having trouble when we try to use copy the blocks from one region to another.

And when the blocks are getting copied, the order in which the files get copied from one ceph region to another is not according to our needs. This is causing issues with compactors and store-server components. I don't see these issues on external storage getting solved completely.

So we wanted to explore the possibility of thanos-sidecar copying the blocks to 2 different storage clusters (bucket name being same). Since the object store configuration and side-car metadata is per side-car, I floated the idea of running 2 different thanos side-car containers, each with its own storage cluster configuration. 

The location of "thanos.shipper.json" and other files created by thanos side-car should be made configurable through a command flag. That will ensure that work done by a thanos side-car container is not affected by another one.

Let me know your thoughts. Our need is to copy blocks to different storage cluster, but keep the bucket name same.

**Comment by GiedriusS** [comment]
> Thanks for raising this. What's the use case for this?
> 
> What about adding the ability to run multiple sidecars for this purpose?
> 
> I think this might be tricky now due to single `thanos-shipper.json` but **if we would scope this by `thanos-shipper-<bucket-name>.json` this will be doable.**
> 
> In any case, this change would be needed:
> 
>     * even for single binary multi-target upload we would need to sync in two different files.
> 
>     * the case when someone runs sidecar and then changes the target bucket in next rollout.
> 
> 
> I would vote for starting with that first:
> 
> AC:
> 
>     * Running two sidecars works
>       
>       * Name of the shipper JSON file should be dependent on bucket name.

What if two buckets have the same name but different endpoints? :P Perhaps some kind of hashing needs to be used here over the whole objstorage configuration.
