### ISSUE TITLE
Thanos sidecar not triggering remote_read

### ISSUE THREAD

**Issue by iridian-ks** [thanos-io/thanos#1915]
**Thanos, Prometheus and Golang version used**:

    Image:         thanosio/thanos:v0.8.1
    Image:         prom/prometheus:v2.13.1

**Object Storage Provider**:

S3

**What happened**:

Used a separate remote_write data store while I was migrating between S3 buckets. The data in the remote datastore is queriable using the Prometheus API/CLI/UI. When using Thanos, it looks like it does not trigger the remote_read functionality.

**What you expected to happen**:

For Thanos to use the standard API for retrieving data.

**How to reproduce it (as minimally and precisely as possible)**:

Setup a prom/thanos container with remote_read/write. Query the data with Prometheus and the data comes back, but use the Thanos Querier and it does not retrieve that data.

**Full logs to relevant components**:

Thanos sidecar doesn't show much:

```
{"caller":"prometheus.go:247","component":"sidecar","level":"debug","msg":"started handling ReadRequest_STREAMED_XOR_CHUNKS streamed read response.","ts":"2019-12-19T18:40:56.805376235Z"}
{"caller":"prometheus.go:323","component":"sidecar","frames":0,"level":"debug","msg":"handled ReadRequest_STREAMED_XOR_CHUNKS request.","series":0,"ts":"2019-12-19T18:40:56.805478384Z"}
{"caller":"prometheus.go:247","component":"sidecar","level":"debug","msg":"started handling ReadRequest_STREAMED_XOR_CHUNKS streamed read response.","ts":"2019-12-19T18:40:56.906835125Z"}
{"caller":"prometheus.go:323","component":"sidecar","frames":0,"level":"debug","msg":"handled ReadRequest_STREAMED_XOR_CHUNKS request.","series":0,"ts":"2019-12-19T18:40:56.906927049Z"}
```

It also looks like Prometheus logs aren't very helpful either. It shows when it's remote_writing but not when remote_reading. I also don't see any kind of access logs to see the parity between CLI/UI/Thanos query options/arguments.

The most useful logs I can see in on the remote_write side I can see when it gets queried and when it's not.

Here's a log that gets written when I use the Prometheus UI:

```
{"caller":"log.go:27","level":"debug","msg":"Executed query","query":"SELECT time, name, value, labels FROM metrics WHERE name = 'mq_current_depth' AND time \u003e= '2019-12-13T23:03:00Z' AND time \u003c= '2019-12-14T00:08:00Z'  AND labels @\u003e '{\"prometheus_group\":\"prometheus\",\"prometheus_replica\":\"prometheus-readers-server-0\"}' ORDER BY time","ts":"2019-12-19T18:42:26.416Z"}
{"#timeseries":1,"caller":"log.go:27","level":"debug","msg":"Returned response","ts":"2019-12-19T18:42:26.425Z"}
```

**Anything else we need to know**:

When running the same query through Thanos these logs aren't showing up. I do know that the sidecar/thanos ARE connected and working. Going to *Stores* in the Thanos UI I see the Prometheus instance is there. When I query for *up* I can see the results are coming back as the same between Thanos/Prometheus. It's just the remote_read that's not being triggered.

Also, the Thanos Sidecar continuously logging ReadRequest probably means it's all connected. I'm not an expert though.

I guess I'm wondering if this is intentional or if this is something that should work. I would think that this should be something that works and was surprised to see that it doesn't.

**Comment by bwplotka** [comment]
Hi :wave: Thanks for reporting.

If I understand this right: You want to ask to use Thanos to fetch something from the different backend (which one?) through Prometheus. It comes to Prometheus exposing on its `remote read`  further `remote read` storage connected to the Prometheus, right?. From logs looks like Prometheus responds to remote read with no data, so yes sidecar seems to be connected properly. 

By looking at the current Prometheus code there should be no blocker - Prometheus uses exactly the same backend for `read` as for `query/query_range` endpoint. Are you sure you are running exactly the same query on both?

I would play with `/api/v1/read` directly and see if it returns the data you expect, but you might need to pass the data programmatically as it uses protobuf.

Ideally however for this purpose, I would implement integration: StoreAPI implementation as described here: https://thanos.io/integrations.md This allows to have native Thanos support without Prometheus as proxy.

**Comment by iridian-ks** [comment]
Hello! Thanks for responding and trying to help me out.

Your understanding of my goal is correct. I'm using Postgresql (Timescale) as remote_read/write location.

I'm definitely running the same query in Thanos as I am in Promethues, BUT even if it was a different query then I should see that showing up in the logs, right? The query I would see in the logs would just be different, but in this case there aren't any logs which indicates the query never makes it to the remote_read code path.

For the `/api/v1/read` endpoint, is this not what `promtool` is using? I tried using that to run my queries. Starting with Prometheus, my data is returned and the query  is showing up in the logs. When hitting Thanos, I get the same results as the UI. Is Promtool not using `/api/v1/read`?

RE StoreAPI: I don't yet have the time capacity to implement that on top of the Postgresql Prom Adapter. It does seem like a good idea to use Prometheus as a Proxy as it would essentially reduce the amount of code maintenance on the Thanos side, but I am not involved with this project (yet) so I must trust you with your word.
