### ISSUE TITLE
compactor: Race of sharded compactors causing data loss.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#1919]
As per discussion, https://github.com/thanos-io/thanos/pull/1901 sharding compactor is currently not fully safe. Please do not use it or use only for smaller setups.

We are working on this, but the reason is also partially explained in https://docs.google.com/document/d/1QvHt9NXRvmdzy51s4_G21UW00QwfL9BfqBDegcqNvg0/edit#

TL;DR:
* Compactor A for shard cluster = A is uploading the block X - upload takes more than 30m
* Compactor B is syncing all blocks. It see block X that is being uploaded for more than 30m, removing block.

**Comment by bwplotka** [comment]
The workaround here is to change `--consistencyDelay` on Compactor to larger value like `2h`, given upload time being quicker than this. This has side effect of compaction process being delayed by 2h which should be fine.

cc @mattrco

**Comment by bwplotka** [comment]
* [ ] Delay clean up of potential partial uploads to 2 days: https://github.com/thanos-io/thanos/pull/1937
* [ ] Add ModifiedTime attribute per object for all object storages and base on that: **Help wanted**.

**Comment by bwplotka** [comment]
@mattrco this should be fixed on master now.

**Comment by jaseemabid** [comment]
Thanks @bwplotka, is `--consistencyDelay` required for the master release too?

**Comment by bwplotka** [comment]
It is required but for different reasons, mainly for non-consistent object storages. I would suggest leaving the default value.
