### ISSUE TITLE
query: thanos-query A query another thanos-query B with replica labels doesn't return deduped metrics

### ISSUE THREAD

**Issue by 00arthur00** [thanos-io/thanos#1927]
thanos-query A query another thanos-query B with replica labels doesn't return deduped metrics.

thanos docker v0.9.0

**What happened**:
Let say, thanos query A and B:
A's setting:
``` markdown
  thanos-querierA:
    image: quay.io/thanos/thanos:v0.9.0
    command:
      - 'query'
      - '--grpc-address=0.0.0.0:10091'
      - '--http-address=0.0.0.0:10902'
      - '--store=thanos-querierB:10091'
```
B's setting:
``` markdown
  thanos-querierB:
    image: quay.io/thanos/thanos:v0.9.0
    command:
      - 'query'
      - '--grpc-address=0.0.0.0:10091'
      - '--http-address=0.0.0.0:10902'
      - '--query.replica-label=replica' ##<----note here
      - '--store=thanos-sidecar-1:10091'
      - '--store=thanos-sidecar-2:10091'
      - '--store=thanos-sidecar-3:10091'
      - '--store=thanos-sidecar-4:10091'
      - '--store=thanos-store-gateway:10091'
```

A(without replica-label) connects a store B(with replica-label). When query with A, we can see replica-label appears.

**What you expected to happen**:
Thanos query A should not show replica-label.

**How to reproduce it (as minimally and precisely as possible)**:
1. unzip the thanos.zip
2. run "docker-compose up -d"
3. visit "http://127.0.0.1:10903/graph?g0.range_input=1h&g0.max_source_resolution=0s&g0.expr=up&g0.tab=1", we have replic label "replica" appears.

[thanos.zip](https://github.com/thanos-io/thanos/files/4001391/thanos.zip)

**Comment by daixiang0** [comment]
Since you do not specify replica-label for query-A, query-A can not distinguish this label.
