### ISSUE TITLE
Supports logging with traceID

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#1930]
Feature Request:
Cortex component logs each request's traceID like something below 
```
level=debug ts=2019-12-29T20:00:00.142704226Z caller=logging.go:44 traceID=5b8343e5de934761 msg="GET /metrics (200) 3.837879ms"
```
And in the new version of Grafana, Loki data source supports derived fields so that users can jump to Jaeger directly from Grafana based on the traceID, see https://grafana.com/docs/grafana/latest/features/datasources/loki/#derived-fields.

So it would be nice that Thanos supports this feature as well.

**Comment by GiedriusS** [comment]
Seems like a duplicate of https://github.com/thanos-io/thanos/issues/1706 (:

**Comment by yeya24** [comment]
Yes it is a duplicate. Thanks @GiedriusS
