### ISSUE TITLE
Please upgrade to 2.15.1 for Prometheus dependency of go Mod

### ISSUE THREAD

**Issue by liguozhong** [thanos-io/thanos#1935]
github.com/prometheus/prometheus v1.8.2-0.20191126064551-80ba03c67da1 // Prometheus master v2.14.0

Prometheus master v2.15.1

**Comment by bwplotka** [comment]
Yup, that's the plan. We are waiting on 2.15.2 release though, fixing compaction on Windows: https://github.com/prometheus/prometheus/pull/6547

**Comment by bwplotka** [comment]
Also help wanted (:

**Comment by daixiang0** [comment]
@bwplotka happy to take this.

**Comment by bwplotka** [comment]
I depend on this for https://github.com/thanos-io/thanos/pull/1839 so I will take it if you don't mind (:

**Comment by daixiang0** [comment]
That is fine :)

**Comment by bwplotka** [comment]
But again, let's wait on upstream fix that we discussed on Prometheus IRC

**Comment by liguozhong** [comment]
![image](https://user-images.githubusercontent.com/9583245/71874594-4a826300-315d-11ea-9223-b0d4b984dc12.png)
2.15.2 release ，thanks @bwplotka
