### ISSUE TITLE
Docs for downsample cmd

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#1938]
I think we need docs for command `downsample` as well.

**Comment by GiedriusS** [comment]
Some parts are still missing in Thanos Receive and the documentation part is outlined here: https://github.com/thanos-io/thanos/issues/1093. However, the concern about `downsample` is true 👍 PRs welcome!

**Comment by yeya24** [comment]
Thanks, I change the title to `docs for downsample`.

**Comment by bwplotka** [comment]
PR is still there, pending for review.
