### ISSUE TITLE
Use block.MetaFetcher for all meta json syncs

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#1941]
This is to make sure we have consistent meta.json fetch logic for all command (e.g graceful partial block support)
AC:

* [ ] Use block.MetaFetcher inside verify command
* [ ] Use block.MetaFetcher inside bucket command

**Comment by daixiang0** [comment]
I would like to take this:)

**Comment by bwplotka** [comment]
It's also a good first task for @khyatisoneji 

She is our student as a part of CNCF Community Bridge program, and it sounds like a good introduction if you don't mind @daixiang0

**Comment by daixiang0** [comment]
Never mind, welcome @khyatisoneji
