### ISSUE TITLE
query: memory usage spikes

### ISSUE THREAD

**Issue by StupidScience** [thanos-io/thanos#1950]
**Thanos, Prometheus and Golang version used**:
Thanos: v0.8.1
Prometheus: v2.14.0

**Object Storage Provider**:

Azure Blob

**What happened**:

Few times a day query component try to consume a lot of memory. So due to memory limits and consequent OOMKiils I get it in CrashLoopBackoff state

**What you expected to happen**:

Moreless regular memory consumption.

**How to reproduce it (as minimally and precisely as possible)**:

Not sure if any special steps required.

Here is graph of memory consumption

![image](https://user-images.githubusercontent.com/32177073/71918099-9dc2d880-3192-11ea-9c46-646420b601c4.png)

**Comment by FUSAKLA** [comment]
Hi, sorry for the late reply.
Memory consumption of the querier component should be mostly driven by the queries coming in. 
Do you have any way to check what queries were sent to it during that time of spikes? Meanwhile, you might have to just enlarge those limits.

Grafana for example allows logging of datasource proxy calls etc so maybe try this or adding reverse proxy of some kind to loge those incoming requests.  Hopefully in the future Thanos will adopt new feature of Prometheus which is query log.

**Comment by StupidScience** [comment]
As you can see on the graph there is spike even around 4am when no one use our grafana and thanos as well, so I think it does not relate to coming queries.

**Comment by Allex1** [comment]
Seeing the exact same patterns with bonus that my querier also restarts even though it hasn't reached the limit and no errors in logs 
<img width="423" alt="Screen Shot 2020-04-01 at 10 58 25" src="https://user-images.githubusercontent.com/8087146/78113160-fd362a80-7407-11ea-8189-de8eb79fbd36.png">

**Comment by mpecarina** [comment]
@Allex1 same thing I am seeing, our querier pods restart because the readiness probe starts to fail when requests are blocked by a long running query

**Comment by kakkoyun** [comment]
@Allex1 Which metric are you using to check if it reaches the limit?
Do you out-of-memory kills in your scheduler system?
