### ISSUE TITLE
Is possible to extend the store api to support different type of storages?

### ISSUE THREAD

**Issue by foshantiger** [thanos-io/thanos#1958]
Is possible to extend the store api to support different type of storages, such as block storage(ceph rbd) or file system(ceph fs)?

**Comment by squat** [comment]
Hi @foshantiger, Thanos already supports running a component that exposes the Store API and reads from block storage. This component is called the Thanos Store Gateway. Ceph exposes an S3-compatible API so we support it today via the S3 configuration options. Please take a look at this doc to learn more the Store Gateway: https://github.com/thanos-io/thanos/blob/master/docs/components/store.md

And here to learn more about writing your object storage configuration: https://github.com/thanos-io/thanos/blob/master/docs/storage.md

Finally, Thanos also has beta support for reading directly from the from the local filesystem: https://github.com/thanos-io/thanos/blob/master/docs/storage.md#filesystem

**Comment by foshantiger** [comment]
Hi @squat, I checked for the docs，but it seems that the Thanos Store Gateway is still on top of object storage but not block storage? And there is no planned support for distributed filesystems(cephfs) but just local filesystem？

**Comment by squat** [comment]
Ah so sorry, I misread your question. Block storage is only supported as a local filesystem. If you are running ceph, we’d suggest exposing ceph object storage directly instead if possible. The other way we recommend to do this today is to run something like https://github.com/minio/minio to expose an object storage API on top of your filesystem

**Comment by foshantiger** [comment]
Thanks @squat ! I will close this.
