### ISSUE TITLE
sidecar: shipping compacted blocks memory usage

### ISSUE THREAD

**Issue by anas-aso** [thanos-io/thanos#1971]
**Thanos, Prometheus and Golang version used**:
Thanos: v0.9.0
Prometheus: v2.15.1

**Object Storage Provider**:
GCP & AWS

**What happened**:
High memory usage when running Sidecar with `--shipper.upload-compacted`
<img width="952" alt="Screenshot 2020-01-09 at 11 49 36 AM" src="https://user-images.githubusercontent.com/16538065/72061462-36ae3c80-32d6-11ea-867c-6acef88a4e33.png">
PS: The memory usage dropped after I removed `--shipper.upload-compacted` flag again.

**What you expected to happen**:
Normal memory usage (hundreds of megabytes) when uploading non-compacted blocks.
The memory usage should also go down once all old blocks are uploaded (the upload finished in the screenshot at 15:10 and I waited 1 hour more to see if it goes down or not ... it didn't)

**How to reproduce it (as minimally and precisely as possible)**:
30 days of Prometheus data that has ~200GB, then run Thanos Sidecar with `--shipper.upload-compacted`
Before adding Thanos Sidecar, Prometheus was running with the default `storage.tsdb.{max,min}-block-duration` values.

**Full logs to relevant components**:
Nothing really specially, just lines like this one 
```
{"caller":"shipper.go:349","id":"<BLOCKID>","level":"info","msg":"upload new block","ts":"<TIMESTAMP>"}
```

**Anything else we need to know**:
The setup has Thanos **only**. Other components are not deployed yet.

**Comment by bwplotka** [comment]
Thanks for report. 

We just upload in this case, so such usage would be odd. Are you sure you are not hitting the issue mentioned [in this blog post](https://bwplotka.dev/2019/golang-memory-monitoring/)?

What metric are you observing for memory usage? IF RSS then it does not show the full truth. Check `go_memory_allocs` instead.

**Comment by anas-aso** [comment]
Thanks @bwplotka for the quick reply. You are right, I was using `container_memory_usage_bytes`. After switching to `container_memory_working_set_bytes` I go a value of ~300MB.
Time to update all those Grafana dashboards 😄
