### ISSUE TITLE
thanos receive not able to send data to s3 on new install

### ISSUE THREAD

**Issue by kbsquared** [thanos-io/thanos#1973]
**Thanos, Prometheus and Golang version used**:
thanos 0.9.0
prometheus 2.15.2
golang go1.13.1

**Object Storage Provider**:
S3 Netapp StoreGrid

**What happened**:
I think this probably belongs in a user group but I couldn't find one so hoping you guys will kindly redirect me.
I'm trying to setup thanos receive and it's not writing up to my s3 storage.  After digging through the examples/doc, I've been able to enable debug logging and I see more detail, but I'm not sure what to make of it.  Any help to debug would be greatly appreciated.

I'm not sure if the message about empty external labels is accurate or just sending me on a wild goose chase.  I added external labels to my prometheus config and the behavior did not change.  After turning on the s3 trace they don't seem like they are talking about the same issue, not sure.

**What you expected to happen**:
blocks uploaded to s3 storage

**How to reproduce it (as minimally and precisely as possible)**:
Not sure as this is a new install and I'm not sure I've got everything setup correctly.

**Logs and configs to relevant components**:

<details>Logs
<p>

level=info name=receive ts=2020-01-09T11:59:29.271552133Z caller=shipper.go:349 component=receive msg="upload new block" id=01DY4ASME9T9WS4AV2NFVBDFYB
level=error name=receive ts=2020-01-09T11:59:29.145764468Z caller=shipper.go:316 component=receive msg="shipping failed" block=01DY43XZY1D5DNJGWXSJNRH1FM err="empty external labels are not allowed for Thanos block."
level=debug name=receive ts=2020-01-09T11:59:29.142826067Z caller=stdlib.go:89 component=receive s3TraceMsg=---------START-HTTP---------
level=debug name=receive ts=2020-01-09T11:59:29.143079635Z caller=stdlib.go:89 component=receive s3TraceMsg="HEAD /ocp-thanos/01DY43XZY1D5DNJGWXSJNRH1FM/meta.json HTTP/1.1\r"
level=debug name=receive ts=2020-01-09T11:59:29.143135285Z caller=stdlib.go:89 component=receive s3TraceMsg="HTTP/1.1 404 Not Found\r"
level=debug name=receive ts=2020-01-09T11:59:29.143161495Z caller=stdlib.go:89 component=receive s3TraceMsg=---------END-HTTP---------

</p>
</details>

<details>Prometheus config
<p>
global:
  scrape_interval:     30s
  evaluation_interval: 30s
  external_labels:
    cluster: master.ops.paas.domain.com
    replia: prometheus-thanos.ops.paas.domain.com

remote_write:
  - url: "https://thanos-receive-thanos.ops.paas.domain.com/api/v1/receive"
    bearer_token: <redacted>
    tls_config:
      insecure_skip_verify: true

scrape_configs:
  - job_name: 'OCP_thanos_ops'  
    honor_labels: true
    metrics_path: /federate
    scheme: https
    scrape_timeout: 25s
    tls_config:
      insecure_skip_verify: true
    bearer_token: <redacted>
    params:
      match[]:
        - '{__name__=~".+"}'
    static_configs:
      - targets:
        - 'prometheus-k8s-openshift-monitoring.ops.paas.domain.com'
        labels:
          cluster: master.ops.paas.domain.com
</p>
</details>

<details>s3 secret config
<p>
type: S3
config:
  bucket: ocp-thanos
  endpoint: ocp-thanos.s3.domain.com
  region: us-east-1
  access_key: <redacted>
  secret_key: <redacted>
  insecure: false
  http_config:
    insecure_skip_verify: true
  trace:
    enable: true
</p>
</details>

**Anything else we need to know**:

**Comment by yeya24** [comment]
Does this relate to https://github.com/thanos-io/thanos/pull/1882? This fix is included in the new 0.10.0 release, could you please try to update to it and see if this fix your problem @kbsquared

**Comment by kbsquared** [comment]
Not sure, but happy to give it a whirl.  Do you know of a way to make it try to write more quickly for testing?  After I restart it takes hours before it trys to write anything, makes testing tedious.

**Comment by yeya24** [comment]
Try this https://github.com/open-fresh/avalanche.

**Comment by squat** [comment]
No, I think he’s referring to speeding up the time it takes for receive to upload a block. 

You are in luck! We literally just merged a PR ago master a few hours ago that allows you to shorten the block duration via the `--tsdb.min-block-duration` and `--tsdb.max-block-duration` flags. Set these both to an equal value of eg 5min and blocks should get written and uploaded often

**Comment by kbsquared** [comment]
Thank you both for your assistance.

The tsdb thing was what I was looking for.  I didn't realized I needed to set it on the thanos container, I did it on the prometheus container first.  

Anyway, even with that latest build (master-2020-01-08-1d71579f) I'm still getting the same messages.

**Comment by yeya24** [comment]
@kbsquared  Sorry about that. Could you please provide the config yaml of your receive component?
Seems you don't configure the external label for your receive by `--label` flag.

**Comment by kbsquared** [comment]
Thanks.  So I added external_labels onto my prometheus config.  This error is talking about a label on the thanos receive config?  

      - args:
        - receive
        - --tsdb.path=/data/remote-write-receive-data
        - --tsdb.min-block-duration=5m
        - --tsdb.max-block-duration=5m
        - --debug.name=receive
        - --log.level=debug
        - --grpc-address=0.0.0.0:19891
        - --http-address=0.0.0.0:18091
        - --remote-write.address=0.0.0.0:19291
        - --objstore.config-file=/etc/prometheus/store-s3-secret.yaml

**Comment by yeya24** [comment]
> Thanks. So I added external_labels onto my prometheus config. This error is talking about a label on the thanos receive config?
> 
> ```
>   - args:
>     - receive
>     - --tsdb.path=/data/remote-write-receive-data
>     - --tsdb.min-block-duration=5m
>     - --tsdb.max-block-duration=5m
>     - --debug.name=receive
>     - --log.level=debug
>     - --grpc-address=0.0.0.0:19891
>     - --http-address=0.0.0.0:18091
>     - --remote-write.address=0.0.0.0:19291
>     - --objstore.config-file=/etc/prometheus/store-s3-secret.yaml
> ```

Yes, you need to add the external label to your receive config

**Comment by kbsquared** [comment]
Ok gotcha, digging for config examples, not sure where to add that...  Thanks again for the guidance.

**Comment by kbsquared** [comment]
Found this issue and that showed me how to get the labels into my config.  

![image](https://user-images.githubusercontent.com/30937545/72098334-e0e09100-32e3-11ea-8da2-ee598464c507.png)

Past this hurtle.  Thanks so much for the assist!
