### ISSUE TITLE
thanos-sidecar upload have no Disk read IO

### ISSUE THREAD

**Issue by 695097494** [thanos-io/thanos#1976]
**Thanos, Prometheus and Golang version used**:
```
image: prom/prometheus:v2.15.1
image: thanosio/thanos:master-2019-12-23-39f8623b
```
**Object Storage Provider**:
```S3```
**What happened**:
```We want to know how the sidecar works when the sidecar is uploading data```
**Full logs to relevant components**:
```
level=info ts=2020-01-22T08:09:54.762326304Z caller=shipper.go:349 msg="upload new block" id=01DZ64RX2AQT62HM5F3Y3956RQ
level=info ts=2020-01-22T08:10:24.763641865Z caller=shipper.go:349 msg="upload new block" id=01DZ64SB4FCGM89E1RKGSGT8JZ
level=info ts=2020-01-22T08:10:54.767722276Z caller=shipper.go:349 msg="upload new block" id=01DZ64TWDC5JXPC024VPSNA6TF
level=info ts=2020-01-22T08:10:59.159341539Z caller=shipper.go:349 msg="upload new block" id=01DZ64V9Q7ANCSFJY4TNRE38SH
level=info ts=2020-01-22T08:11:54.864134417Z caller=shipper.go:349 msg="upload new block" id=01DZ64WSJRTVNJY9SNYYDSRD67
level=info ts=2020-01-22T08:11:56.522417673Z caller=shipper.go:349 msg="upload new block" id=01DZ64X8KYK4MT6XWHBS45DKBV
level=info ts=2020-01-22T08:12:54.76093737Z caller=shipper.go:349 msg="upload new block" id=01DZ64Y73XZ7TP0QCYHKEYTQ3W
level=info ts=2020-01-22T08:13:54.768551852Z caller=shipper.go:349 msg="upload new block" id=01DZ64YW64AWEXRFRZXFJ006MP
level=info ts=2020-01-22T08:14:24.763958427Z caller=shipper.go:349 msg="upload new block" id=01DZ6519XR3JPJS9AYV0CX5EHJ
level=info ts=2020-01-22T08:14:54.825478713Z caller=shipper.go:349 msg="upload new block" id=01DZ6529QH000HT3ZNP8M86KE9
level=info ts=2020-01-22T08:16:24.765617999Z caller=shipper.go:349 msg="upload new block" id=01DZ654YVG7GGEGQTXWTAXMTBY
```

**Comment by 695097494** [comment]
thanos-sidecar、prometheus and Object Storage all working health,Object Storage can view data with prometheus

**Comment by FUSAKLA** [comment]
Hi, could you please explain more what is the issue? 
IIUC you are trying to verify that the sidecar is working and sending blocks to the object storage?

According to the log you sent it looks like it should be working ok.

**Comment by yeya24** [comment]
I have talked with him about this issue offline previously. His question is that he is using sidecar to upload blocks to s3, it works properly. But he cannot see any disk IO in the grafana dashboard for that upload operation. Do you guys have any hints about this?

**Comment by FUSAKLA** [comment]
Ok, thanks for clarifying!
The disk IO of sidecar would show up only once per 2h when the block is written by Prometheus to disk so you need to check for longer time range maybe?
And how do you observe the disko IO?

**Comment by 695097494** [comment]
sorry，I forgot to explain one thing, I changed the "--storage.tsdb.min-block-duration" and "--storage.tsdb.max-block-duration" time of prometheus to 15 seconds, so that I can more easily Good observation of the io of the sidecar process. I use pidstat to observe the io of the sidecar process. The following is the relevant configuration of my prometheus.


    ```
                - "--storage.tsdb.max-block-duration=15s"
                - "--storage.tsdb.min-block-duration=15s"
    ```
    
In our expectations, after we changed the configuration of prometheus to 15 seconds, the sidecar should upload data every 30 seconds. In fact, the sidecar also works exactly like this. You can see from the logs that the sidecar uploads every 30 seconds. Data once; but we are strange that we can't see any sidecar's read IO, only the network transmission IO of the sidecar process; we don't know where the sidecar process gets these data from and uploads, because if it is Reading from disk will definitely produce disk read IO

sidecar's log is as follows, It can be seen that the sidecar is regularly uploaded every 30 seconds

```
level=info ts=2020-01-22T07:46:55.309654495Z caller=shipper.go:349 msg="upload new block" id=01DZ63FSGN5Y12Y3WVM1CC1AA9
level=info ts=2020-01-22T07:47:24.750249057Z caller=shipper.go:349 msg="upload new block" id=01DZ63FW4QS0V0FZ1MBDP42NPW
level=info ts=2020-01-22T07:47:25.463644295Z caller=shipper.go:349 msg="upload new block" id=01DZ63GASGYA77E9PQSCRX2V98
level=info ts=2020-01-22T07:47:54.752000206Z caller=shipper.go:349 msg="upload new block" id=01DZ63GSEB2FTE2YHXPB8GYD4B
level=info ts=2020-01-22T07:47:55.954983679Z caller=shipper.go:349 msg="upload new block" id=01DZ63H82YNC4C6B3QXKQ7M16M

```

The following is the average IO of the sidecar's disk over a one minute period

```
            UID       PID    kB_rd/s   kB_wr/s kB_ccwr/s iodelay  Command
Average:    0       23494      0.00      0.40     0.40       0    thanos
```

**Comment by 695097494** [comment]
> Ok, thanks for clarifying!
> The disk IO of sidecar would show up only once per 2h when the block is written by Prometheus to disk so you need to check for longer time range maybe?
> And how do you observe the disko IO?

sorry，I forgot to explain one thing, I changed the "--storage.tsdb.min-block-duration" and "--storage.tsdb.max-block-duration" time of prometheus to 15 seconds, so that I can more easily Good observation of the io of the sidecar process. I use pidstat to observe the io of the sidecar process. The following is the relevant configuration of my prometheus.


    ```
                - "--storage.tsdb.max-block-duration=15s"
                - "--storage.tsdb.min-block-duration=15s"
    ```
    
In our expectations, after we changed the configuration of prometheus to 15 seconds, the sidecar should upload data every 30 seconds. In fact, the sidecar also works exactly like this. You can see from the logs that the sidecar uploads every 30 seconds. Data once; but we are strange that we can't see any sidecar's read IO, only the network transmission IO of the sidecar process; we don't know where the sidecar process gets these data from and uploads, because if it is Reading from disk will definitely produce disk read IO

sidecar's log is as follows, It can be seen that the sidecar is regularly uploaded every 30 seconds

```
level=info ts=2020-01-22T07:46:55.309654495Z caller=shipper.go:349 msg="upload new block" id=01DZ63FSGN5Y12Y3WVM1CC1AA9
level=info ts=2020-01-22T07:47:24.750249057Z caller=shipper.go:349 msg="upload new block" id=01DZ63FW4QS0V0FZ1MBDP42NPW
level=info ts=2020-01-22T07:47:25.463644295Z caller=shipper.go:349 msg="upload new block" id=01DZ63GASGYA77E9PQSCRX2V98
level=info ts=2020-01-22T07:47:54.752000206Z caller=shipper.go:349 msg="upload new block" id=01DZ63GSEB2FTE2YHXPB8GYD4B
level=info ts=2020-01-22T07:47:55.954983679Z caller=shipper.go:349 msg="upload new block" id=01DZ63H82YNC4C6B3QXKQ7M16M

```

The following is the average IO of the sidecar's disk over a one minute period

```
            UID       PID    kB_rd/s   kB_wr/s kB_ccwr/s iodelay  Command
Average:    0       23494      0.00      0.40     0.40       0    thanos
```

This is the command I use to query the disk IO

```
pidstat -d -p $thanos-sidecarPID 
```

**Comment by GiedriusS** [comment]
I have never used that tool but maybe you are missing the `-T ALL` option because Thanos Sidecar runs in more than one thread?

**Comment by 695097494** [comment]
> I have never used that tool but maybe you are missing the `-T ALL` option because Thanos Sidecar runs in more than one thread?

Thanks for the hint, I found the problem

**Comment by GiedriusS** [comment]
Nice! What was it? Does it mean that we can close this? :p

**Comment by 695097494** [comment]
> Nice! What was it? Does it mean that we can close this? :p
Yes, you can turn it off, this does not affect the use of thanos, it is just a small problem that I stumbled upon

**Comment by 695097494** [comment]
> Nice! What was it? Does it mean that we can close this? :p

Yes, you can turn it off, this does not affect the use of thanos, it is just a small problem that I stumbled upon
