### ISSUE TITLE
Thanos Receiver Design

### ISSUE THREAD

**Issue by tdinucci** [thanos-io/thanos#1993]
I am quite interested in the Thanos Receiver and am hoping someone can help me understand a couple of things.

_I have read https://thanos.io/proposals/201812_thanos-remote-receive.md and this is what lead to my questions._

1. Before reading the document I had assumed that the Receiver would write directly to long term storage but it would seem that this isn't the case.  What I understood from the doc was that there will be a new Prometheus instance (managed at the Thanos side) **_per_** Prometheus instance at the "tenant" side.  If I've understood the document correctly can you explain why this is?  I'm not seeing many up-sides.  

2. The doc states early on that "This component is not recommended in order to achieve a global view of data of a single tenant, for those cases the sidecar based approach with layered Thanos queriers is recommended" however it doesn't explicitly state why.  I'm thinking that it may be due to the overhead involved with maintaining all of Thanos side Prom instances but would appreciate confirmation.

Thanks

**Comment by brancz** [comment]
1) The receiver is essentially just the hot-write buffer that can be written/replicated to. It builds the immutable blocks of data like Prometheus does and uploads blocks like the sidecar would. It's mainly for when you _must_ push and/or want to remove the statefulness of the Promteheus and shift the storage management to the Thanos component.

2) Maybe we should have phrased that a bit different. We mainly meant that if you want to achieve just global view, and are in control of the Prometheus servers, you are better off using the sidecar approach.

**Comment by tdinucci** [comment]
Thanks for the quick response :)

Just so I'm clear.  Are you saying that there wouldn't be any new Prom instances at the Thanos side?  The receiver just writes to Prom compatible files and the data from these is later pushed to long term storage?

I imagine this is being done as a means of data compaction ahead of writing to long term storage?  It obviously introduces a point of failure though.  Are there any docs outlining recommended ways to ensure that if a Receiver dies the data that it's buffered isn't lost?

**Comment by squat** [comment]
Hi @tdinucci regarding question 1, Thanos receive does _not_ require a new Prometheus instance per Prometheus on the tenant side. All metrics received by Thanos Receive are written to a local TSDB and the these completed blocks are uploaded. The flow is:
app `<--scrape--` Prometheus `--remote-write-->` Thanos Receive Hashring `--write-->` local TSDB on disk `--upload-->` S3

Please let us know what part of the doc is confusing so we can clarify it going forward.

**Comment by squat** [comment]
@tdinucci there are two complimentary strategies to avoid losing data that is sent by Prometheus that has not yet been uploaded to S3.
1. Putting the TSDB on a persistent volume. Thanos Receive uses the same TSDB package as Prometheus, which features a WAL. This means that even if the process dies suddenly, all samples that have been ACK'd but not yet written to a full block in the TSDB are saved in the WAL. If the server uses some type of persistent storage, then next time the process starts back up, it can re-read the WAL and pick up again from where it left off.
2. Enable replication on Thanos Receive. With this feature you can enable dynamo-style replication of all data received. If you set the replication factor to 3, then Thanos Receive will only ACK a request when at least 2 nodes have successfully written the data to their local TSDB. Now, even if you lose a node AND its storage, you can guarantee that the data will be stored on at least one more node.

**Comment by tdinucci** [comment]
Thanks very much both of you for the help!

Having re-read the document with the context you've given it's clearer now.  However below is the paragraph that I became confused over in https://thanos.io/proposals/201812_thanos-remote-receive.md.

> Instead of directly scraping metrics, however, the Thanos receiver accepts Prometheus remote-write requests and writes these into a local instance of the Prometheus TSDB. Once successfully committed to the tenant’s TSDB, the requests return successfully. To prevent data leaking at the database level, each tenant has an individual TSDB instance, meaning a single Thanos receiver may manage multiple TSDB instances. The receiver answers Thanos store API requests and uploads built blocks of the Prometheus TSDB. Implementation-wise, this just requires wiring up existing components. As tenant’s data within object storage are separate objects, it may be enough separation to have a single bucket for all tenants, however, this architecture supports any setup of tenant to object storage bucket combination.

**Comment by squat** [comment]
Ack, at the risk of hindsight bias, would it be clearer to say simply:

> Instead of directly scraping metrics, however, the Thanos receiver accepts Prometheus remote-write requests and writes these into a local TSDB.

**Comment by tdinucci** [comment]
For me, yes that would be clearer.  Part of my confusion I think stemmed from this being a reasonably heavy paragraph and the diagram below contained no reference to any of this - so a lighter description may be helped.

Do you think it would be worth adding _why_ this is the case, maybe by appending something like the following to your sentence?

> ... where they are buffered until there is enough data to warrant finally writing to long term storage.

**Comment by omerlh** [comment]
Another follow up question: It is my understanding that Thanos receive is considered experimental and not ready for production (as the big warning on the start of the log specifies :)). Why is that? What is the plan for a production-ready release?

**Comment by omerlh** [comment]
> We mainly meant that if you want to achieve just global view, and are in control of the Prometheus servers, you are better off using the sidecar approach.

Can you please explain why? Working with receive is a lot simpler in a multi-cluster case - you just need one store per storage on each cluster. When using the side-car, you need to be able to query both the store and Prometheus from each cluster...

**Comment by squat** [comment]
> Can you please explain why? Working with receive is a lot simpler in a multi-cluster case - you just need one store per storage on each cluster. When using the side-car, you need to be able to query both the store and Prometheus from each cluster...

It’s a bit subjective but in the end it comes down to the relative difficulties of:
* ensuring open and secure ports to read metrics from sidecars of multiple clusters and configuring querier with every endpoint

vs
* running and maintaining an ingestion  hashring of receivers and scaling as needed

If all of the clusters are owned by you, then the former _can_ be quite easy and so the latter may not make sense. On the other hand, if you don’t control the clusters, then the former is likely not even an option.

**Comment by bluezoe** [comment]
> 2. Enable replication on Thanos Receive. With this feature you can enable dynamo-style replication of all data received. If you set the replication factor to 3, then Thanos Receive will only ACK a request when at least 2 nodes have successfully written the data to their local TSDB. Now, even if you lose a node AND its storage, you can guarantee that the data will be stored on at least one more node.

@squat 
for this option, it means multiple nodes will push same data to backend storage. Then in the storage there will be more than one copy for the same bulk?

**Comment by squat** [comment]
@bluezoe yes that's exactly right. With replication factor 3 there will be 3 copies in object storage. The querier will still correctly de-duplicate the results at query time. We are exploring building offline de-duplication into the compactor to directly compact these blocks in object storage.

**Comment by bluezoe** [comment]
@squat 
Is there any doc about how to configure multiple receivers for load distribution based on a hashring confg file? Seems this feature already supported but cannot find any doc about it.

**Comment by brancz** [comment]
The best thing right now is the original design doc.
