### ISSUE TITLE
Tiered storage

### ISSUE THREAD

**Issue by tdinucci** [thanos-io/thanos#1995]
I've not come across any documentation that makes me think Thanos currently supports tiered storage for long term data.  I recon this would be possible using systems like Alluxio however from a users point of view this will require the setup and maintenance of yet another system and it's something I can imagine would be generally useful for Thanos.

My use case is; we collect a lot of metric data (today ~1.5m points per second) and there are many dashboards and alert definitions reading this data continually.  Around 98% of our reads are for data that is less than 2 days old.

If fairly young data is being pushed to S3 then the transfer costs could end up being quite high and it _may_ be better to store data which is under 2 days old on disk, e.g. in Ceph.

Is there currently a way to achieve this?  If not would this be something you'd consider accepting from an external contributor - assuming the design was agreed upon?

**Comment by GiedriusS** [comment]
Hi! I'm not sure how this would avoid the costs in transferring the data - wouldn't this essentially mean that those costs will just come later, after 2 days instead of immediately? Or are you talking about how you don't want Thanos Store to serve such fresh data? Then perhaps something like `--max-time='-2d'` would help you out here. Documentation is available here: https://thanos.io/components/store.md/. In general I don't think I understand the problem here. Could you elaborate more?

Also, a proposal in a form of a PR is always welcome. I'm sure that the PRs would be accepted if the proposal was accepted. :smile:

**Comment by tdinucci** [comment]
Interesting, perhaps the `--min-time` and `--max-time` flags are what I'm looking for 🤔 Thanks for pointing this out!

My concern isn't so much the write transfer costs (which you are right to point out will be the same no matter when the writing is performed) but the cost of transfer due to reads.  Fresh data is going to be read much more frequently than older data and so if fresh data is stored on non-S3 storage then these costs wouldn't apply.

I'm now thinking that I could configure some stores with a min/max time covering 2 days and these could be backed by something like Ceph and then to configure other stores which are S3 backed to serve data that is older than 2 days.

Queries for young data (< 2d) would be sent to all stores (and the S3 backed stores will contain much of this young data) however since the S3 backed stores are configured to only serve data older than 2 days then they won't read from S3, meaning no (read) transfer costs.

Have I understood this correctly?

**Comment by GiedriusS** [comment]
Yes, you have understood it correctly. It should work the way you have described. That's the whole idea behind this feature. Please try it out and let us know if it works for you :smile:

**Comment by GiedriusS** [comment]
I guess it has worked out for you given that there are no further comments. I will close it to keep our issue tracker cleaner. Please shout at me if you need this reopened. Thanks!
