### ISSUE TITLE
query: chart displays very different data than Grafana (using Querier as backend) for long range query

### ISSUE THREAD

**Issue by jpalpant** [thanos-io/thanos#1998]
**Thanos, Prometheus and Golang version used**:

v0.10.0-rc1 for Querier and Store. Compactor running on the bucket as a cronjob once per day is v0.9.0. Prometheus is prom/prometheus:v2.13.1, and Sidecar is v0.9.0. 

**Object Storage Provider**: GCS

**What happened**: I have a set of metrics which track whether or not a healthcheck on a website returns a success status, or does not. 

<img width="1647" alt="Screen Shot 2020-01-14 at 3 28 31 PM" src="https://user-images.githubusercontent.com/9629191/72391634-87f96a00-36e2-11ea-89d8-67d4f84f5ded.png">

I'm interested in determining the "availability" within a given historical window. To do this, I count the sum of the values within that window, and divide by the count of the values within that window. To do that, I run a query like this:

```
sum(sum_over_time(stackdriver_uptime_url_monitoring_googleapis_com_uptime_check_check_passed{checked_resource_id="justin.palpant.us"}[7d])) / sum(count_over_time(stackdriver_uptime_url_monitoring_googleapis_com_uptime_check_check_passed{checked_resource_id="justin.palpant.us"}[7d]))
```

If I execute this as an instant query, I see roughly the result I expect:

<img width="1662" alt="Screen Shot 2020-01-14 at 3 37 10 PM" src="https://user-images.githubusercontent.com/9629191/72391980-bd528780-36e3-11ea-84c6-1a38af21d9ba.png">

I can also execute this as a range query, and see how this sliding window of availability has changed over time on the graph. If I do this, with "small" window, I see a nice graph with values roughly in the range I expect:

<img width="1655" alt="Screen Shot 2020-01-14 at 3 37 45 PM" src="https://user-images.githubusercontent.com/9629191/72392013-d1968480-36e3-11ea-83e7-21fcd8ab54b9.png">

If I do this in Grafana, which is configured to use the Querier as its PromQL backend, or the Prometheus Web UI, I see the same data. However, when I increase the time range, Querier's webUI begins to show different data, while Grafana's remains consistent with Prometheus - even though Grafana is using Querier as it's backend. For my current setup, this happens right around 7d, though I couldn't say why. Examples:

Grafana 7d query (correct data, routing query to Thanos!):
<img width="1621" alt="Screen Shot 2020-01-14 at 3 39 29 PM" src="https://user-images.githubusercontent.com/9629191/72392118-102c3f00-36e4-11ea-9bcf-3c084dafb271.png">

Prometheus Web UI (same data, no Thanos in the loop):
<img width="1680" alt="Screen Shot 2020-01-14 at 3 39 47 PM" src="https://user-images.githubusercontent.com/9629191/72392136-1a4e3d80-36e4-11ea-8564-b48976eaa632.png">

Thanos Querier UI (?):
<img width="1659" alt="Screen Shot 2020-01-14 at 3 40 24 PM" src="https://user-images.githubusercontent.com/9629191/72392171-2fc36780-36e4-11ea-919b-ea18ad47e508.png">

Notice how the value starts at 10, which shouldn't be possible with this type of query, and then has a very weird decreasing-at-the-end pattern. Since Grafana is querying Thanos for data, I think the issue may just be in the chart visualization, but I really have no idea.

Toggling the downsampling bar has no real effect, nor does changing "deduplication" or "partial response". I am running multiple Querier instances and accessing them behind NGINX, whereas Grafana access them via a k8s clusterIP. Querier is running with these args:

```
  - args:
    - query
    - --log.level=debug
    - --debug.name=$(POD_NAME)
    - --http-address=0.0.0.0:10902
    - --store=sidecar-0:10901
    - --store=store-0:10901
    - --store=store-1:10901
    - --query.auto-downsampling
    - --query.partial-response
    - --query.replica-label=prometheus_replica
```

Prometheus is a single instance, no HA, no deduplication to be done.

**What you expected to happen**: Thanos web UI chart aligns with Grafana chart of same data.

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

I can get these but don't really know what I'm looking for, please advise.

**Anything else we need to know**:

Happy to help track this down further if relevant, I've not contributed and so I don't know much about where to begin debugging or what's useful, but since this is a homelab I can test or change whatever we want.

**Comment by daixiang0** [comment]
Be clear, the different thing happen only with 10d+ query?

**Comment by jpalpant** [comment]
It switches at a 6.5d+ query - any query longer than that, and the graph changes.

**Comment by FUSAKLA** [comment]
Hi, just to be clear you mentioned `Toggling the downsampling bar has no real effect`, does this mean that you get the invalid data even with the option `only raw data` ?

Could you please open the browser network console and copy the exact range query which Grafana sends to the thanos datasource and do the same for the Thanos UI? So we can see what is the difference between those two requests. Hopefully that will tell us more.

**Comment by jpalpant** [comment]
Sorry for the delay! I have new information though, which might help. I was definitely wrong in my initial guess - this probably does not have anything to do with Grafana vs. Querier UI, but I still think there's a bug. I was able to reproduce this weird chart in Grafana as well.

@FUSAKLA, yes, correct - I do get this result even if I select the option "only raw data". But I believe it does have something to do with the interaction between downsampled and non-downsampled blocks. I noticed that the transition from the impossible result to the downward curve tended to happen at just a few days in the past, at around the same point in time where the compactor has produced the first blocks with lower resolution.

Another odd transition happens at the time that the `res: 3600000` blocks become available.

<img width="1620" alt="Screenshot 2020-01-31 13 53 21" src="https://user-images.githubusercontent.com/9629191/73577212-2864c380-4431-11ea-8b8b-640d131441f0.png">

**Comment by bwplotka** [comment]
Still to investigate.

> @FUSAKLA, yes, correct - I do get this result even if I select the option "only raw data". But I believe it does have something to do with the interaction between downsampled and non-downsampled blocks. I noticed that the transition from the impossible result to the downward curve tended to happen at just a few days in the past, at around the same point in time where the compactor has produced the first blocks with lower resolution.

Hm. If you chose only raw data, downsampling blocks are never used.
