### ISSUE TITLE
query: query crashes when start and end are equal and the step value is very large

### ISSUE THREAD

**Issue by Shadi** [thanos-io/thanos#2004]
**Thanos, Prometheus and Golang version used**:

thanos, version 0.9.0 (branch: HEAD, revision: 0833cad83db8b257a2275ec83a3d034c73659056)
  build user:       circleci@8e3da52515a2
  build date:       20191203-17:03:13
  go version:       go1.13.1

Prometheus version: 2.13.1

**Object Storage Provider**: Dell ECS

**What happened**:

Thanos Querier was constantly getting OOM killed in kubernetes, upon investigating a little bit we saw that the crash started to happen when a query was sent that had a start and end parameters with the same value, and the step was very large(10 years):

`start=1576796400&end=1576796400&step=315360000`

I tried these same parameters with another metric and it also either crashed the querier or the querier returned 502

We are still not sure how Grafana ended up sending this step value.

**What you expected to happen**:
A malformed query should not crash the querier

**How to reproduce it (as minimally and precisely as possible)**:
On Grafana: Use custom time range on the dashboard, and then set the start and end time to have the same value, set min step to a very large value(315360000), you can see the response code from the querier if you open the query inspector

Directly on the querier: `/api/v1/query_range?query=max_over_time(sum%20by%20(processor%2Ctopic)%20(consumer_partition_lag%7Bnamespace%3D~%22profile%22%2Cprocessor%3D~%22.*%22%7D)%5B315360000s%3A%5D)&start=1576796400&end=1576796400&step=315360000`

**Full logs to relevant components**:

<details>Logs
Trickster:
<p>

```
time=2020-01-15T10:08:14.621276959Z app=trickster caller=proxy/engines/httpproxy.go:50 level=error event="error downloading url" url="http://thanos-system-querier.svc.cluster.local:9090/api/v1/query_range?query=max_over_time(sum%20by%20(processor%2Ctopic)%20(consumer_partition_lag%7Bnamespace%3D~%22profile%22%2Cprocessor%3D~%22.*%22%7D)%5B315360000s%3A%5D)&start=1576796400&end=1576796400&step=315360000" detail="Get http://thanos-system-querier.cluster.svc.local:9090/api/v1/query_range?query=max_over_time(sum%20by%20(processor%2Ctopic)%20(consumer_partition_lag%7Bnamespace%3D~%22profile%22%2Cprocessor%3D~%22.*%22%7D)%5B315360000s%3A%5D)&start=1576796400&end=1576796400&step=315360000: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
```

</p>

Querier:
<p>

```
level=error ts=2020-01-15T09:55:10.999455296Z caller=engine.go:596 msg="error selecting series set" err="proxy Series(): Addr: 10.128.133.14:10901 LabelSets: [name:\"cluster\" value:\"env.production.ams1\" ,name:\"prometheus\" value:\"architects/thanos-system-infrastructure\" ,name:\"prometheus_replica\" value:\"prometheus-thanos-system-infrastructure-1\" ,name:\"replica_label\" value:\"infrastructure\" ] Mint: 1578895200000 Maxt: 9223372036854775807: receive series from Addr: 10.128.133.14:10901 LabelSets: [name:\"cluster\" value:\"env.production.ams1\" ,name:\"prometheus\" value:\"architects/thanos-system-infrastructure\" ,name:\"prometheus_replica\" value:\"prometheus-thanos-system-infrastructure-1\" ,name:\"replica_label\" value:\"infrastructure\" ] Mint: 1578895200000 Maxt: 9223372036854775807: rpc error: code = Canceled desc = grpc: the client connection is closing"
```

</p>
</details>

**Comment by GiedriusS** [comment]
Hi! Isn't that expected since you are trying to `sum` all of the samples that were produced over a period of 10 years (`315360000`)? :smile: I would recommend you to set `--store.grpc.series-sample-limit` to some kind of value. I have tried to reproduce this here but I was stopped by it:
```
Mint: 1576108800000 Maxt: 1579096800000: rpc error: code = Aborted desc = fetch series for block 01DY6M10MCWNM7G24G247MNTFN: preload chunks: exceeded samples limit: limit 50000000 violated (got 111936960)
```
:smile:

**Comment by Shadi** [comment]
Yes but I created this issue since the query crashed the querier, I was thinking that there should be some measure to prevent 1 query from doing this, I came across PR#1747 after I created the issue and I think it would help in cases like this.

**Comment by Shadi** [comment]
I solved the problem by setting a sample limit as suggested by @GiedriusS, but I still think having a limit on the querier side would be a better safeguard.
