### ISSUE TITLE
Separation of chunk storage to support object lifecycle management

### ISSUE THREAD

**Issue by craigfurman** [thanos-io/thanos#2014]
I'm interested in storing chunks in a separate bucket to indexes and metadata, in order to use object lifecycle management (GCS: https://cloud.google.com/storage/docs/lifecycle, but similar features may exist in other storage backends) to move older chunks to colder, cheaper storage (GCS nearline/coldline).

As I understand it, it pays to keep indexes warmer than chunks, as they can be accessed more readily by the store gateway for a given set of queries, and the chunks are only pulled when metrics contained in them are needed. I haven't validated this, and this issue is quite speculative, so I may well be wrong about this.

If users look at low-resolution historical metric data more often than they zoom in at higher resolution to a range in the past, then it may also make sense to allow a downsampled metric bucket to be configured for the compact and store components. It might make sense to split that into a separate issue though.

I'm not familiar with thanos internals, so I've tried to avoid speculating too much on implementation. What do you think? I'm happy to have a go at a PR if this is something more people are interested in.

**Comment by FUSAKLA** [comment]
Hi, thanks for sharing your use case. 
TBH I'm not personally familiar with those cold storages, it's latencies,API etc. But the idea sounds definitely interesting. 

@bwplotka do you think this would be something worth to consider?

**Comment by bwplotka** [comment]
I think object storage is cheap enough to store data for a long time. However, if you really want to use Coldline Storage or others you have still a couple of options without any change from our side.

For example:

*   Setting "data older than year" Set Storage Class to coldline if you don't expect anyone querying data older than a year ago. In fact, you can even set a `--min-time` flag to Store Gateway which also blocks access to this data. Then you can deploy another Store Gateway just for year+ data and hide it under some different endpoint. This might be tricky with meta.jsons as they are accessed very often (!)

* Create your own service which will run through all the blocks and Set Storage to coldline for some of them EXCLUDIN meta.json etc. Or maybe only for raw data and excluding downsampling etc. So you can do whatever you want at this point. 

Currently, we kind of store chunks in different places -> chunks are stored in `<ulid>/chunks` folder. Those chunks are for the time range specified in Block meta.json. So your separate service can set storage class separately for them. But if you don't query the time range for this data index is not used either.

Also I am not sure what are the latencies when using Thanos against Coldline storage etc - this one you might want to check on your own. (:

**Comment by craigfurman** [comment]
Thanks for replying @bwplotka. My motivation for using a different GCS bucket for chunks was to take advantage of object lifecycle management to automatically move the chunks to cold storage when they reach a certain age. As you say, this could also be done using a service that polls the bucket. Would the compactor be a reasonable place to put such functionality? The compactor already has lifecycle concerns (eviction of old data), but on the other hand this would introduce backend-specific (GCS in this case) functionality into it.

**Comment by bwplotka** [comment]
Yes, I believe we are not interested into embedding such code in Thanos for now. However there is nothing blocking you setting NO retention logic for Compactor and writing your own service which will set lifecycle for objects (:

**Comment by bwplotka** [comment]
Closing as resolved, unless you have further questions @craigfurman (: Thank for the discussion!
