### ISSUE TITLE
Thanos-rule : Bad query url in Alerts view

### ISSUE THREAD

**Issue by zenman94** [thanos-io/thanos#2024]
**Thanos, Prometheus and Golang version used**:
Thanos : 0.10.0
Go: go1.13.1
Prometheus: 2.15.2
Docker image : quay.io/thanos/thanos:v0.10.0 on all components

**Object Storage Provider**: Min.io

**What happened**:
On Ruler web UI, in Alerts section, all url is thanos-rule itself like : 
`https://thanos-rule.ihm/graph?g0.expr=...`
instead of 
`https://thanos-query.ihm/graph?g0.expr=...`

In Rules section all URL are OK.

**What you expected to happen**:
I need correct URL to view query in Thanos Query.

**How to reproduce it (as minimally and precisely as possible)**:
Go to Thanos Rule IHM, Alerts section and click one expr or alertname.

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by FUSAKLA** [comment]
Hi, thanks for report! 
Interesting, I remember it beeing fixed already https://github.com/thanos-io/thanos/pull/1488 🤔

**Comment by yeya24** [comment]
I can confirm this is a valid issue. Now we support this feature in ruler's rules page, but in its alerts page, we cannot jump to querier.

**Comment by daixiang0** [comment]
@zenman94 you must specify that with `--alert.query-url` or thanos rule use its web prefix path.

**Comment by zenman94** [comment]
Thanks for your work !
