### ISSUE TITLE
Use debian instead of alpine for go build

### ISSUE THREAD

**Issue by sylr** [thanos-io/thanos#2031]
Hi,

I wondering if we could consider switching from alpine to debian as base for the `Dockerfile.multi-stage`.

The reason of that is that Alpine is not a glibc based distro and this currently makes it hard to compile go with the `-race`  option, see https://github.com/golang/go/issues/14481.

Regards.

**Comment by GiedriusS** [comment]
I wonder how bigger the image would be. Are there any numbers? For building with `-race` I always build it locally and then use the binary so I never had this need myself.

**Comment by daixiang0** [comment]
Apline has a version for glibc i think while we do not use that version, like golang does.
`-race` is not the default flag for thanos.

**Comment by povilasv** [comment]
I don't think this is really an issue for a lot of people. I.e. if you want to run thanos with `-race` you will have to do `go build -race`, which means you are modifying makefile to do that. So why not modify Dockerifle too?

**Comment by sylr** [comment]
As I used thanos exclusively with docker tweaking the makefile was the next step but I guess I could also make another PR for that.
