### ISSUE TITLE
Katacoda course completion

### ISSUE THREAD

**Issue by bbkgh** [thanos-io/thanos#2041]
Hi. I'm waiting for [this katacoda course](https://www.katacoda.com/thanos/courses/thanos) to be completed from v0.8.1 release (about 3 months ago). specifically for _Introducing caching to Thanos_ lesson. Can you please consider it's completion in your future works?
Thanks

**Comment by bwplotka** [comment]
Cool, we would like to have that as well ! Help wanted :heart:

**Comment by daixiang0** [comment]
Is there more details about the cache course cover?
BTW, @bwplotka miss `pinned` label here.

**Comment by bwplotka** [comment]
We are still looking for a volunteer!

**Comment by bwplotka** [comment]
Still looking for help! (:

**Comment by VineethReddy02** [comment]
@bwplotka Can we start a google doc on listing the missing parts of Thanos that needs to be added to the course?

I can start documenting. And we can define the scope and priority based on the missing parts. WDYT?

**Comment by bwplotka** [comment]
This project is meant for Community Bridge, but definitely we can start some work - it's kind of unlimited bucket of work.

Do we need any doc for this? We can use this issue for this. 

Also we already have missing bits. If you look into tutorial dir there are placeholders. And the order of tutorials states the priority (:

**Comment by VineethReddy02** [comment]
@bwplotka 
Here are the Github pages to add projects for the upcoming cycle specific to community bridge & summer of docs

Community Bridge:
https://github.com/cncf/mentoring/blob/master/communitybridge/2020/q2/project_ideas.md

Summer of Docs:
https://github.com/cncf/mentoring/tree/master/seasonofdocs

**Comment by VineethReddy02** [comment]
As a heads-up on the katacoda course. I see the following scenario's as requirements for the course completion

**Existing Scenario:**
1. Intro: Global View and seamless HA for Prometheus

**TODO Scenarios:**

2. Intro: Downsampling and unlimited metric retention for Prometheus
3. Intro: Global and meta alerts with Thanos
4. Advanced: Connecting remote Prometheuses to Thanos using simple Envoy setup.
5. Advanced: Using Prometheus remote write to stream metrics to Thanos
6. Advanced: Query low tail latency with low cost: Introducing caching to Thanos

**Comment by bwplotka** [comment]
Sorry for late notice, but @VineethReddy02 we added this project as part of Community Bridge https://github.com/cncf/mentoring/pull/230 (:

**Comment by championshuttler** [comment]
Hey @bwplotka ! I am willing to get mentored for this issue for the Community Bridge program. Can you please help me in getting started with it?

Thanks

**Comment by Dhiraj240** [comment]
@bwplotka I am interested in this project for community bridge as a mentee, please provide further instructions to get started and I have submitted the CV and a resume is there anything else do we need to do?

**Comment by TeAmP0is0N** [comment]
Hey @bwplotka I am interested in this project for Season of Docs 2020, Please provide me further instructions to get started and to whom I should contact?

**Comment by MukulMaheshwari** [comment]
I would like to work on this in GSoD this year. Please tell me how to proceed & what work needs to be done.

**Comment by zacharysarah** [comment]
@bwplotka I will go ahead and remove Thanos from the GSoD page.

**Comment by bwplotka** [comment]
@soniasingla is on it!

**Comment by soniasingla** [comment]
https://github.com/thanos-io/thanos/pull/2840 here is the PR link 😄
