### ISSUE TITLE
Flaky Thanos Bucket Store E2E test

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#2046]
See https://circleci.com/gh/thanos-io/thanos/6803, for this error, we don't need to check the number of chunks of series response for each testcase, we just need to make sure the number of chunks is 0 when `skipChunks` option set to true.

**Comment by bwplotka** [comment]
Hm, I don't get it. Why we get this error in the first place?

**Comment by yeya24** [comment]
This error is weird. I just saw it yesterday and tested local in the master branch, sometimes the test passed but sometimes it failed. Let's see if it will appear again in CI.

**Comment by bwplotka** [comment]
https://circleci.com/gh/thanos-io/thanos/7056

**Comment by bwplotka** [comment]
if you want to help @daixiang0  this is affecting us a lot. It is super flaky nowadays, probably due to CircleCI slowness. Either we need to increase timeout.. or move to GithubActions: https://github.com/thanos-io/thanos/issues/1704

I would start by moving only e2e tests to https://github.com/thanos-io/thanos/issues/1704 and see how it goes. What do you think @daixiang0

**Comment by yeya24** [comment]
Maybe in the wrong issue? Should it be https://github.com/thanos-io/thanos/issues/2045 ?

Anyway, this bucket e2e test error is quite strange but seems not happened these 10 days. Maybe it is OK to close this. If I see the same error again, them I can reopen this issue.

**Comment by bwplotka** [comment]
Why closing this issue is fair? If it's impacting us?

**Comment by yeya24** [comment]
@bwplotka  Are you mentioning #2045  or this issue? 
If it is this issue, I haven't seen a similar error reproduced in CI in about 10 days. Seems all thing work properly in bucket e2e test

**Comment by bwplotka** [comment]
Yea, I mean overall e2e

**Comment by yeya24** [comment]
I am sorry, my bad. I am okay to keep it open and watch a long time until we all agree it is resolved
