### ISSUE TITLE
While updating Prometheus deps: don't forget about lack of MaxConcurreny in PromQL

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2064]
This PR https://github.com/prometheus/prometheus/pull/6701 introduced a kind of hidden change in behavior of PromQL: `MaxConcurrency` option is `Noop` if you don't use active tracker, which we don't. Let's decide and do either:

* Add active tracker
or 
* Add our own concurrency gate from `pkg/gate`

cc @gouthamve @pracucci as it probably affects Cortex as well.

Thanks @roidelapluie for the ping!

**Comment by pracucci** [comment]
Thanks @bwplotka for the heads up! Cortex will be affected as well.

> Add our own concurrency gate from pkg/gate

If you pick this option, what would you think to wrap with `pkg/gate`?

**Comment by bwplotka** [comment]
You mean wrap for metrics? Definitely happy with that.

**Comment by pracucci** [comment]
> You mean wrap for metrics? Definitely happy with that.

Sorry for not being clear about my previous question. One of the solutions listed in the PR description is "Add our own concurrency gate from pkg/gate". How that would work? How would you add it? I'm missing how to integrate it.

**Comment by bwplotka** [comment]
Ah yes!

I mean literally add
```
	{
		span, _ := tracing.StartSpan(srv.Context(), "querier_query_gate_ismyturn")
		err := s.queryGate.IsMyTurn(srv.Context())
		span.Finish()
		if err != nil {
			return errors.Wrapf(err, "failed to wait for turn")
		}
	}
	defer s.queryGate.Done()
```
Before calling PromQL query that's it ([source](https://github.com/thanos-io/thanos/blob/3b6b4fd3b6cca70dba743c090608eaeafea2ed41/pkg/store/bucket.go#L811))

For Cortex probably the same but per customer.
