### ISSUE TITLE
Let's be clear about thanos compact, one more time

### ISSUE THREAD

**Issue by Ultrafenrir** [thanos-io/thanos#2081]
Thanos version 0.9.0
Storage s3

I have read a couple articles related to this topic, and don't found straightforward answers on my questions.

I have a small setup for testing purposes ( 2 week retention of all resolution) , with around 200 GB metrics in my bucket to get understand how much resources thanos consumes, how it deal with geo distributed setup and so on.

My problem is, even with this small retention compact start getting OOMed on 16GB dedicated host when retention policies should start applying. 
So my question is how can thanos be promoted as storage with  "unlimited" retention if it start consuming so much resources with very small setup like mine?

How i can realize how much memory it will need if i expand retention policies up to 1 year for example?

Maybe i do not need to use compactor at all ? ( when i stop compactor, my store-gateway start consuming a lot of memory on startup instead of compactor)

**Comment by GiedriusS** [comment]
Hi! Resources usage is not infinite because we compact (and downsample after some time) blocks only up to a fixed amount of time range. In the `master` version you could try `--experimental.enable-index-header` to reduce the memory usage. Also, `v0.10.1` has lower memory usage during the compaction process. Please try these options and see if it helps!

**Comment by Ultrafenrir** [comment]
> Hi! Resources usage is not infinite because we compact (and downsample after some time) blocks only up to a fixed amount of time range. In the `master` version you could try `--experimental.enable-index-header` to reduce the memory usage. Also, `v0.10.1` has lower memory usage during the compaction process. Please try these options and see if it helps!

Thanks for the quick answer! Yes it solve all of my issues, my small setup start working like  a charm! Store consuming 5 times less memory and startup procedure take about 30 seconds instead of 5 min and compaction process now consumes 16x times less memory than before!!!
