### ISSUE TITLE
Rate Limit Feature Request

### ISSUE THREAD

**Issue by codyja** [thanos-io/thanos#2084]
Would it be possible to add rate limit capabilities to the Thanos components? For example, it would be nice if we have the sidecars send to object storage (using S3 currently) and say limit the transfer rate to 75Mbit on a 500Mbit internet pipe. Same thing with store gateway, if it's possible to limit the rate of connections/calls/traffic to the bucket store, that would be very nice and helpful.

**Comment by GiedriusS** [comment]
Hi! Shouldn't this be the responsibility of your host system to limit the resources a process could use? (:

**Comment by bwplotka** [comment]
Yes, I think it's actually server responsibility. Also, you can build a proxy or configure LINUX for this indeed (cgroups, docker etc). We might not want to inroduce something hacky for Thanos and maintain it when other amazing solutions are available for this (:
