### ISSUE TITLE
support multiple clusters in dashboards

### ISSUE THREAD

**Issue by omerlh** [thanos-io/thanos#2089]
Add a cluster selector to each dashboard query and a drop-down that allows you to select which cluster data you want to view (very similar to `kubernetes-mixin` dashboards). Users can define the label via the `dashboard` property:
```
  dashboard:: {
    prefix: 'Thanos / ',
    tags: error 'must provide dashboard tags',
    namespaceQuery: error 'must provide a query for namespace variable for dashboard template',
    showMultiCluster: true,
    clusterLabel: 'source_prometheus',
  },
```

This is how it will look like on the dashboard:

![image](https://user-images.githubusercontent.com/6730584/73604845-c4acd880-459f-11ea-8d1e-12a314a68845.png)

**Comment by atmosx** [comment]
hi, anyone working on this?

**Comment by Xtigyro** [comment]
+1

**Comment by jakuboskera** [comment]
@omerlh I have managed how to do it.

1. Uncomment key `.targetGroups .cluster` in a file `mixin/config.jsonnet` and put there value `up`
   ```jsonnet
    {
    ...
        targetGroups+:: {
            cluster: 'up',
        ...
        }
    ...
    }
   ```
1. (Optional) You can also uncomment key `.targetGroups .namespace`
1. Generate dashboards
   ```bash
   make examples
   ```
1. Dashboards will appear at folder `examples/dashboards/`
