### ISSUE TITLE
Ability to query store-gateway without active sidecar

### ISSUE THREAD

**Issue by Ultrafenrir** [thanos-io/thanos#2091]
Hi, this is a kind feature request. 
I current scheme, thanos query does not allow you query anything from a store if a sidecar that uploaded data into this store terminated already. 
My proposal is have ability to query historical data from store does even sidecar that uploaded it don't exist already. Mostly we need it for short-lifetime geo-distributed k8s clusters that make's some testing, analytics and send result to some bucket and then cluster will shortly terminated.

**Comment by GiedriusS** [comment]
Hi! Could you elaborate more on what doesn't work? What stops you from specifying the Thanos Store nodes with `--store` or just query them directly via gRPC if that's your thing? :P

**Comment by Ultrafenrir** [comment]
Thanks for the answer! Now i'm realized that all work smoothly. But my question comes from misleading error "No store matched for this query" when sidecar goes down. I think will be much better to have simple message no data points or something similar.
