### ISSUE TITLE
store: Fails to sync with object store and stops responding to queries

### ISSUE THREAD

**Issue by zygiss** [thanos-io/thanos#2098]
**Thanos, Prometheus and Golang version used**:

Thanos: "thanosio/thanos:v0.10.0" & "thanosio/thanos:master-2020-01-31-9b17ba18"
Prometheus: 2.15.2
Golang: 1.13.1

**Object Storage Provider**: GCS

**What happened**:

Two things:

1 - Thanos Store fails to sync with object store (`iter bucket` operations fail continuosly).
2 - Thanos Store stops responding to queries.

**What you expected to happen**:

Thanos Store reflects the current state of the blocks in object storage.  Thanos Store returns metrics being asked for.

**How to reproduce it (as minimally and precisely as possible)**:

Not found a reliable way to reproduce this so far.  Seems to occur several hours after Store startup and only on Stores fronting larger buckets (> 40k blocks).

**Full logs to relevant components (Store)**:
```

level=warn ts=2020-02-05T01:14:46.520268878Z caller=store.go:272 msg=\"syncing blocks failed\" err=\"MetaFetcher: iter bucket: Get https://storage.googleapis.com/storage/v1/b/thanos-01/o?alt=json&delimiter=%2F&pageToken=&prefix=&prettyPrint=false&projection=full&versions=false: write tcp 10.16.17.4:60590->209.85.145.128:443: write: broken pipe
level=warn ts=2020-02-05T01:17:46.520149565Z caller=store.go:272 msg=\"syncing blocks failed\" err=\"MetaFetcher: iter bucket: Get https://storage.googleapis.com/storage/v1/b/thanos-01/o?alt=json&delimiter=%2F&pageToken=&prefix=&prettyPrint=false&projection=full&versions=false: write tcp 10.16.17.4:60590->209.85.145.128:443: write: broken pipe
level=warn ts=2020-02-05T01:20:46.52003521Z caller=store.go:272 msg=\"syncing blocks failed\" err=\"MetaFetcher: iter bucket: Get https://storage.googleapis.com/storage/v1/b/thanos-01/o?alt=json&delimiter=%2F&pageToken=&prefix=&prettyPrint=false&projection=full&versions=false: write tcp 10.16.17.4:60590->209.85.145.128:443: write: broken pipe

```

**Anything else we need to know**:

##### Thanos Store parameters:
```
      --log.level=debug
      --data-dir=/var/thanos/store
      --index-cache-size=2GB
      --chunk-pool-size=4GB
      --experimental.enable-index-header
      --objstore.config=type: GCS
      config:
        bucket: "thanos-01"
```

Once Store enters this state, it doesn't recover for at least 10 hours (haven't waited longer).  A restart is the only workaround.

`thanos_objstore_bucket_operation_failures_total{bucket="thanos-01",operation="iter"}` counter steadily increases at `sync-block-duration` frequency (we're running with the default 3m interval).

##### Metrics

Store metrics when this occurred https://dpaste.org/A4zA/raw.

##### pprof

I collected all available profiling information from affected Store instance, this maybe is a bit excessive, but seemed prudent given that I've not found a way to reproduce this at will - 
[store-sync-failure-debug.zip](https://github.com/thanos-io/thanos/files/4158250/store-sync-failure-debug.zip).

Let me know if there's anything else I can add.

**Comment by GiedriusS** [comment]
The goroutine stack dump doesn't seem to indicate that something has been stuck for a long time. Are you sure that there are no network problems? The log errors seem to show that something odd is happening with the TCP connections that Thanos Store initiates while trying to synchronize the state.

**Comment by zygiss** [comment]
Thanks for reviewing this.  Yes, it might very well be a networking issue, so far I've not been able to confirm or deny that unfortunately, given the limited debugging tools available in GKE & Chrome OS.

What made me think that it might be a Thanos issue is that I always see the same four Store instances being affected by this (out of nine we have running in total).  The Store instances are deployed over two GCP VMs, and Stores on both of the VMs have had this problem.

Thanks again for taking a look, feel free to close this and I'll follow up if / when I have more details to add to the case.

**Comment by zygiss** [comment]
Short update on this one - this issue occurred once on 1/9 Store instances in the last two weeks.  The only thing that we changed was to reprovision the GCP VMs (`index-header` saves us RAM so we're scaling down).

Meanwhile, we came accross this Go HTTP2 bug https://github.com/golang/go/issues/30702 that might be the root cause of this.  We implemented the workaround to disable HTTP2 to see if this indeed is the case.

At this point I'm going to close this issue, given that nobody else is experiencing the same problem.  Thanks for reading!

**Comment by bwplotka** [comment]
Don't scale down just yet. The baseline memory might be reduced
significantly, but requests will take the same amount as before + bits that
were previously cached. So expect spikes. We are working to improve read
path as well, and make sure it's more deterministic (:

Make sure you do some load tests before scaling down.

**Comment by pracucci** [comment]
We just experienced this exact issue with the GCS objstore client in Cortex (using the Thanos objstore client): https://github.com/cortexproject/cortex/issues/2703

**Comment by zygiss** [comment]
@pracucci what version of Thanos objstore client are you using there?  We've not seen this problem occur with Thanos 0.11 and up.

Also, does the problem go away if you disable HTTP/2?  This was an acceptable workaround for us at the time, it didn't many any notable difference to performance or latency in Thanos Store.  Since Thanos 0.11 however we're back to using HTTP/2.

**Comment by pracucci** [comment]
> what version of Thanos objstore client are you using there? We've not seen this problem occur with Thanos 0.11 and up.

We've seen it while running the Cortex blocks storage (which vendors Thanos `master` and we keep it updated frequently), so was a commit has after Thanos `0.11`.

> Also, does the problem go away if you disable HTTP/2? This was an acceptable workaround for us at the time, it didn't many any notable difference to performance or latency in Thanos Store. Since Thanos 0.11 however we're back to using HTTP/2.

We didn't. We've seen the issue only once. Let's see how frequently it happens (at least, if it happens again) before following the path of disabling HTTP/2.

**Comment by bwplotka** [comment]
Hey, did we look on GCS client lib (added issue etc?)

We can (and should) upgrade our lib as well (:

**Comment by notque** [comment]
Just experienced this same issue. Trying to sort out a solution.

**Comment by Mr-Lee-long** [comment]
I also encountered this issue, which seems to be caused by timeouts when pulling data from COS. This is not a consistent problem and only occurs occasionally. Is there any parameter or configuration that can be optimized for this situation?

level=warn ts=2023-05-17T04:37:04.771055516Z caller=store.go:375 msg="syncing blocks failed" err="BaseFetcher: iter bucket: Get \"https://*******?delimiter=%2F&max-keys=1000&prefix=p18%2F\": dial tcp: lookup ******.com: i/o timeout"
level=warn ts=2023-05-17T04:40:33.551088834Z caller=store.go:375 msg="syncing blocks failed" err="BaseFetcher: iter bucket: Get \"https://******/?delimiter=%2F&max-keys=1000&prefix=p18%2F\": dial tcp: lookup ******.com: i/o timeout"
level=warn ts=2023-05-17T04:43:49.932251239Z caller=store.go:375 msg="syncing blocks failed" err="BaseFetcher: iter bucket: Get \"https://******/?delimiter=%2F&max-keys=1000&prefix=p18%2F\": dial tcp: lookup ******ud.com: i/o timeout"
