### ISSUE TITLE
Ruler: register sender errors (thanos_alert_sender_errors_total) metric. 

### ISSUE THREAD

**Issue by OGKevin** [thanos-io/thanos#2100]
**Thanos, Prometheus and Golang version used**:
Thanos: https://github.com/thanos-io/thanos/releases/tag/v0.10.1

**Object Storage Provider**:

**What happened**:
There is a bug in the code here: https://github.com/thanos-io/thanos/blob/7c02430c59c2d1d2491f2c5a587e9a74e5c1a423/pkg/alert/alert.go#L290-L318

The errors metric is not registered in the registry. This means that this metric is missing and therefore not exposed. 

**What you expected to happen**:
This metric to exist. 

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by bwplotka** [comment]
Ups!

**Comment by bwplotka** [comment]
Ok it's enough, we have too many of such issues. Let's automate this and add some test: https://github.com/thanos-io/thanos/issues/2102
