### ISSUE TITLE
Qustions about benchmark

### ISSUE THREAD

**Issue by daixiang0** [thanos-io/thanos#2108]
Sorry for filing #2095 before asking an issue! :(

I want to ask some questions as below:
- How many types of benchmark do we have?
-  How can users run benchmark(may be fixed by #2095)?
-  Is it necessary to post an official benchmark report for each release version?
-  Store benchmark may be related to disk type, query benchmark may be related to network speed,  resource is also an influencing factor, improve those factors would improve benchmark but limited i think, so where is the limit?(Of course, comparing benchmark with same resource is more meaningful )

cc @thanos-io/thanos-maintainers

**Comment by daixiang0** [comment]
update

**Comment by bwplotka** [comment]
> How many types of benchmark do we have?

Types?

Microbenchmarks and some attempts of e2e benchmarks in https://github.com/thanos-io/thanosbench.
Some ideas were also stated here: https://github.com/yeya24/thanos/pull/26#issuecomment-616067696

> How can users run benchmark(may be fixed by #2095)?

funcbench would be awesome. Some automation (but not bash scripts).

> Is it necessary to post an official benchmark report for each release version?

It would be nice to have such a rule. Similar to what Prometheus has: https://github.com/prometheus/prometheus/pull/7139#issuecomment-615932542

> Store benchmark may be related to disk type, query benchmark may be related to network speed, resource is also an influencing factor, improve those factors would improve benchmark but limited i think, so where is the limit? (Of course, comparing benchmark with same resource is more meaningful )

True. It'is all about the requirements we give. What are we optimize for? Latency?

**Comment by daixiang0** [comment]
update

**Comment by bwplotka** [comment]
I responded, what else is missing? If nothing, let's close this.
