### ISSUE TITLE
Can I import old metrics data from influxdb or other?

### ISSUE THREAD

**Issue by SamPeng87** [thanos-io/thanos#2112]
we test thanos in prometheus,is good jobs.
so we want to migrate thanos from influxdb。
how to best do it？

**Comment by bwplotka** [comment]
Hi :wave: 

I personally never used InfluxDB, but by looking on the documentation I think following procedure can work:

1. Deploy Prometheus + sidecar
2. Deploy rest of Thanos stack as you want
3. Connect Prometheus in (remote read config section) to InfluxDB using [prometheus-remote-read API](https://docs.influxdata.com/influxdb/v1.7/supported_protocols/prometheus/)

Now you collect metrics in new system, with the new system being able to query older metrics as well from influxDB for migration purposes. 

Maybe there are others, better ideas?

**Comment by bwplotka** [comment]
I hope that helped. (:  Let us know, otherwise closing.
