### ISSUE TITLE
readnessProbe checks failed of thanos bucket web

### ISSUE THREAD

**Issue by wujie1993** [thanos-io/thanos#2115]
**Thanos, Prometheus and Golang version used**:

thanos: 0.10.1
prometheus: 2.7.1
golang: 1.13.6

**Object Storage Provider**:

minio

**What happened**:

readnessProbe checks failed of thanos bucket web.

missing `statusProber.Ready()` after start bucket web

**What you expected to happen**:

running bucket web and curl /-/ready should return 200 ok.

**How to reproduce it (as minimally and precisely as possible)**:

running bucket web and curl /-/ready return 503 error.

**Full logs to relevant components**:

<details>Logs
<p>

```
level=info ts=2020-02-10T03:46:27.265300556Z caller=main.go:149 msg="Tracing will be disabled"
level=info ts=2020-02-10T03:46:27.266072914Z caller=factory.go:43 msg="loading bucket configuration"
level=info ts=2020-02-10T03:46:27.266886883Z caller=bucket.go:410 msg="synchronizing block metadata"
level=info ts=2020-02-10T03:46:27.268086808Z caller=prober.go:127 msg="changing probe status" status=healthy
level=info ts=2020-02-10T03:46:27.268113295Z caller=http.go:53 service=http/server component=bucket msg="listening for requests and metrics" address=0.0.0.0:10902
level=info ts=2020-02-10T03:46:27.358101897Z caller=bucket.go:430 msg="downloaded blocks meta.json" num=6
```

</p>
</details>

**Anything else we need to know**:

**Comment by yeya24** [comment]
Thanks for your report! Yes, I think we miss the `statusProber.Ready()` here.
@kakkoyun  Could you please take a look?

**Comment by kakkoyun** [comment]
Of course. @yeya24 feel free to assign it to me, I'll have a look at it.
