### ISSUE TITLE
thanos_objstore_bucket_last_successful_upload_time does not appear as prometheus exposed metrics

### ISSUE THREAD

**Issue by daguilarv** [thanos-io/thanos#2122]
**Thanos v0.8.1, Prometheus 3.3.0-3**:

**Object Storage Provider**:
Azure

**What happened**:
Thanos Sidecar dashboard does not show any value in "Last Uploaded time"

**What you expected to happen**:
Show the last uploaded time for the last prometheus block

**How to reproduce it (as minimally and precisely as possible)**:
Simply deploy a grafana  and import thanos-sidecar dashboard

**Comment by GiedriusS** [comment]
Has Prometheus produced at least one block and has it been uploaded successfully? Without that, it won't appear. Also, is it still reproducible on `master`?

**Comment by daguilarv** [comment]
> Has Prometheus produced at least one block and has it been uploaded successfully? Without that, it won't appear. Also, is it still reproducible on `master`?

Prometheus block duration is set to 15m  so several blocks were generated and uploaded to Azure blob storage. We have not tested with master version of thanos components so I can´t answer to the latest question.

**Comment by GiedriusS** [comment]
Could you please try that out? Also, is there any particular reason you are running such old Prometheus? I cannot reproduce this with 0.10.1 and 2.15.2, and with s3.

**Comment by daguilarv** [comment]
> Could you please try that out? Also, is there any particular reason you are running such old Prometheus? I cannot reproduce this with 0.10.1 and 2.15.2, and with s3.

Sure, I will try and let you know if the problem is solved with proposed configuration. Thanks for your support

**Comment by daguilarv** [comment]
Hi again,

I have just tested with prometheus 2.16.0 and thanos 0.10.1  and thanos_objstore_bucket_last_successful_upload_time is not shown in my prometheus /metrics path

Here is an screenshot of thanos sidecar grafana dashboard
![image](https://user-images.githubusercontent.com/26145647/74673832-59beec80-51b0-11ea-83af-33877e0ea8dc.png)

On the other hand, several blobs have been uploaded to our Azure Blob Storage metrics container

![image](https://user-images.githubusercontent.com/26145647/74673946-8f63d580-51b0-11ea-90ad-2ffee076b425.png)

**Comment by yeya24** [comment]
@daguilarv Hello,
could you please check the promql query in the `Last Upload Time` dashboard? You could directly do the same query in Grafana Explore page or in Thanos Query UI, and see if you can get any results.

I tried the Thanos Sidecar dashboard last week and it worked well for me.

**Comment by daguilarv** [comment]
> @daguilarv Hello,
> could you please check the promql query in the `Last Upload Time` dashboard? You could directly do the same query in Grafana Explore page or in Thanos Query UI, and see if you can get any results.
> 
> I tried the Thanos Sidecar dashboard last week and it worked well for me.

Used metric in dashboard query is no available in my prometheus instances, so query throws No data when executed

**Comment by yeya24** [comment]
I am sorry I don't have an Azure env, but I believe it is irrelevant?
The Prometheus `/metrics` endpoint only includes the metrics belong to Prometheus itself. So it is expected you cannot find  `thanos_objstore_bucket_last_successful_upload_time` there.

And I think maybe you can get the metric `thanos_objstore_bucket_last_successful_upload_time` in Thanos sidecar `/metrics` endpoint.  Or I think you can directly query it in Prometheus UI. Could you please check it?

**Comment by daguilarv** [comment]
> I am sorry I don't have an Azure env, but I believe it is irrelevant?
> The Prometheus `/metrics` endpoint only includes the metrics belong to Prometheus itself. So it is expected you cannot find `thanos_objstore_bucket_last_successful_upload_time` there.
> 
> `thanos_objstore_bucket_last_successful_upload_time` is supposed to show up in Thanos sidecar `/metrics` endpoint. Or you could directly query that metric in Prometheus UI as well. Could you please check it?

I´musing thanos-querier to get exposed metrics. Anyway, I will try pointing directly to thanos-sidecars
