### ISSUE TITLE
React UI migration

### ISSUE THREAD

**Issue by adrien-f** [thanos-io/thanos#2124]
👋 Greetings everyone!

When I started working on implementing the new React based UI from Prometheus into Thanos, I quickly realized that we're missing a lot of the newest endpoints preventing us from adopting a full React UI.

This issue is made to track what's missing and what's left to do as small and easy to do PR for everyone (and even first timers!).

* [ ] Add the base UI: https://github.com/thanos-io/thanos/pull/2121
* [ ] Status API, example from https://github.com/prometheus/prometheus/blob/master/web/api/v1/api.go I don't think all endpoints are interesting to keep!
```
r.Get("/status/config", wrap(api.serveConfig))
r.Get("/status/runtimeinfo", wrap(api.serveRuntimeInfo))
r.Get("/status/buildinfo", wrap(api.serveBuildInfo))
r.Get("/status/flags", wrap(api.serveFlags))
r.Get("/status/tsdb", wrap(api.serveTSDBStatus))
r.Post("/read", api.ready(http.HandlerFunc(api.remoteRead)))
```
* [ ] Query - Store Page
* [ ] Ruler - Alerts Page
* [ ] Ruler - Rules Page
* [ ] Bucket - Bucket Page

Did I miss anything ?

This migration can also be the opportunity to clean up a bit of the duplication we have with each API exposing components and provide a nice and simple interface.

I'm not a React expert yet so maybe let's organize ourselves in here and in #thanos-dev Slack channel to discuss if needed 😄

**Comment by vankop** [comment]
Unfortunately, this feature does not fix https://github.com/thanos-io/thanos/issues/1510 . We encounter same problem..

cc @d-ulyanov

**Comment by kakkoyun** [comment]
Still valid

**Comment by GiedriusS** [comment]
Valid.

**Comment by squat** [comment]
valid :)

**Comment by prmsrswt** [comment]
Still valid (:
