### ISSUE TITLE
Proposal: Add Couchbase as Backend

### ISSUE THREAD

**Issue by frank-dspeed** [thanos-io/thanos#2141]
Hi, My Name is Frank Lemanschik I am a Distributed Systems Engineer I found your project as I was dealing with some software stacks that implemented Prometheus but I think I have a more Efficient Solution for the problem it is even more simple :)

please watch only the index page to get a overview what t am talking about.

https://www.couchbase.com/

Imagine you could use Couchbase a Document Storage Solution that can handle infinity Data and easy Scales that also Scales Querys and Alerts and Everything needed Right Out Of the Box.

So when Prometheus Would use Couchbase as its backend! It Would get Instand HA and High Performance. https://couchbase.com it offers also a great go client that supports the binary Protocol. You can get Sub Milisecund Responses on Really Big Data Sets. Without Maintaining the sidecar layer your self. Couchbase is self Monitoring and Healing and is battle-tested.

So Storing the data as JSON in Couchbase and query it with N1QL a SQL Like Language for JSON will enable Unlimited Data Retention.

My Current solutions that I explored before i found you looked like let us translate SQL queries to N1QL to do the Prometheus integration because I am not a fan of go. 

Another alternate method I was thinking about is integrating a custom-json-backend in NodeJs that uses Couchbase.

But your familiar with go and you got already a code base you could easily make the dream come true via using simply your go knowledge and the Couchbase go SDK https://docs.couchbase.com/go-sdk/2.0/hello-world/start-using-sdk.html to integrate it directly as a driver into Prometheus

EVEN MORE, SLICK would it be to add Couchbase as Grafana EndPoint Directly this will allow using Couchbbase for Unlimited data even if Prometheus is not envolved so you can monitor directly via inserting into Couchbase.

**Comment by frank-dspeed** [comment]
If you would even just Integrate couchbase as storage for the data in Thanos it would be great but you need to store the raw data without blocks in that case so that the data stays query able in couchbase directly.

**Comment by bwplotka** [comment]
Hi, @frank-dspeed is it [April 1st](https://en.wikipedia.org/wiki/April_Fools%27_Day) already? :thinking: 

Let me ping @gouthamve from [the Cortex Team](https://github.com/cortexproject/cortex), they might be interested :muscle:

**Comment by bwplotka** [comment]
Jokes aside, you are welcome @frank-dspeed  to implement CoachDB under Thanos [gRPC StoreAPI](https://github.com/thanos-io/thanos/blob/master/pkg/store/storepb/rpc.proto#L25)  in any language you want. This way it will map to PromQL directly.

As Thanos project, we are optimized for using cheap object storages for data, but with our StoreAPI you can integrate easily.

**Comment by frank-dspeed** [comment]
Importent Couchbase is by no means CouchDB:) ok i will need to look into the storage api

**Comment by bwplotka** [comment]
Thanks! Let us know if you have any questions. Closing for now.
