### ISSUE TITLE
Incorporate failinit.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2142]
Hi, 

I would propose adding https://github.com/fatih/faillint/blob/master/README.md to our 'make lint' rule to avoid some inconsistencies like some packages we would like to not import:

* errors (we use pkg/errors)
* prometheus/tsdb (it was archived and moved to Prometheus module)
* prometheus/prometheus/pkg/testutils (we have our own)

Help wanted 🤗

**Comment by kadern0** [comment]
I'd be happy to help on this one

**Comment by bwplotka** [comment]
:tada:

**Comment by bwplotka** [comment]
At some point it would be nice to add prometheus client main package to not allowed list and only rely on promauto. This way we can ensure all our metrics are registered! 🤙 We might need/contribute this to make this happen: https://github.com/fatih/faillint/issues/7
