### ISSUE TITLE
docs/store: Document binaryindex-header usage and characteristics.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2154]
It would be nice to do before release.

AC:
* Explain how to use index-header for end-user.
* Explain characteristics (low baseline usage, but query spikes are expected)
* Note that it is still experimental.

cc @metalmatze @squat @brancz

**Comment by brancz** [comment]
We're still releasing this as an experimental feature, I think this is mostly required for when we make it default, but I agree. I think the original design is nice but maybe to detailed for the end user, so I do agree. How about we start a new section in the docs "Operational Guide"? I quite like this in [etcd's op-guide section](https://github.com/etcd-io/etcd/tree/master/Documentation/op-guide), where various aspects from alerting to expected/unexpected behaviors are documented from an operational perspective. What do you think?

**Comment by bwplotka** [comment]
Agree, I think Operational Guide sounds like good place for this content. We already have something like Troubleshooting.md that we should put there as well. Thanks 👍

**Comment by gburek-fastly** [comment]
I suggest an additional warning about open fd limits with this option. 

Our store nodes are each responsible for 7989 blocks in GCS and, until now, we have run store under systemd with a `LimitNOFILE=4096`. Enabling this flag meant an index header for each block and an open file for each block, resulting in our `process_open_fds` for thanos store going from 11 to the limit very quickly. 

Somehow, store came online but seemed to be unresponsive to StoreAPI queries until we raised the LimitNOFILE to `16384` and restarted.  Our `process_open_fds` then stabilized at ~8000, or `11 + num of blocks returned for the node`.

In hindsight the change [documented here](https://github.com/thanos-io/thanos/blob/master/docs/components/store.md#index-header) suggests that it will result in more open files, but I didn't immediately make the link between mmaped files and a ulimit setting for the process. Maybe a reminder to check ulimit would be helpful for others.

**Comment by jojohappy** [comment]
Still valid.

**Comment by bwplotka** [comment]
AC:
* Document ulimit impact
* Explain how index-header is obtained (not kept in compactor)
* Explain the characteristics

Potentially in compactor.md

**Comment by pracucci** [comment]
_There's the PR #2668 open._
