### ISSUE TITLE
Reflexion : Import old blocks in Thanos

### ISSUE THREAD

**Issue by gillg** [thanos-io/thanos#2157]
Hi,

I have a question about a use case. On prometheus project a tool is almost released to import old metrics from any system, in OpenMetric format and to a local runing Prometheus instance.

I see 2 scenarios :
* Prometheus has a sidecar : Blocs should be ingested I think... Everything will be ok for store gateway and bucket after that ? Metrics should be queriable ?
* Prometheus has a remote write configured to Thanos : Receiver will store all blocks in its local TSDB, what appends after that ? Everyting should works ?

Also, I'm not sure to totally undertand the new receiver component. It seems imprement the original Prometheus TSDB and store data localy but what appends after ? It acts as a sidecar or data are sent to bucket by another way ?

Regards

**Comment by brancz** [comment]
I recommend reading the design doc we wrote for the component. But you understood correctly, the receive component accepts the writes, produces the immutable blocks on disk every 2 hours and uploads them to object storage.

The sidecar and receive approach are fundamentally different, and each have their place. We offer deployment and use case flexibility you choose what fits your situation best :)

**Comment by gillg** [comment]
Ok, Thanks ! It's what I thought about receiver. But in this case two solutions are compatible to ingest imported blocs from the past with potential times overlapping ?
Or it will break thanos because it needs its own import system based on cluster components ?

**Comment by brancz** [comment]
Both are compatible, in fact we have a system running that now only ingests via the receive component, but used to use the sidecar, and everything works just fine with the historical data, and as you already said, for a short amount of time we had some overlap during the migration, but that worked just fine.

**Comment by gillg** [comment]
Great ! Many thanks for your answer ! I will make some tests soon ! :)
