### ISSUE TITLE
e2e: Add back removed e2e tests; Add ability to connect to certain host services from docker network

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2164]
See: https://github.com/thanos-io/thanos/pull/2138#discussion_r382133169 && https://github.com/thanos-io/thanos/pull/2138#discussion_r382136126

**Comment by bwplotka** [comment]
Still valid

**Comment by ranjithkumar007** [comment]
Hi, I would like to have a go at this.
We need to remove t.Skip() from [1](https://github.com/thanos-io/thanos/blob/2262f2601a2b04d0be7a951d1d962e698520c44e/test/e2e/rule_test.go#L180) and add back the [tests](https://github.com/thanos-io/thanos/pull/2138#discussion_r382136126) which used to be in `TestRulePartialResponse` right?

**Comment by bwplotka** [comment]
Yes!

**Comment by ranjithkumar007** [comment]
Thanks @bwplotka .

**Comment by bwplotka** [comment]
ping

**Comment by ranjithkumar007** [comment]
@bwplotka didn't get much time to have a look at this. Will try to do this weekend.
