### ISSUE TITLE
Not getting data beyond a certain date 

### ISSUE THREAD

**Issue by nicopapayann** [thanos-io/thanos#2165]
**Object Storage Provider**:
S3

**What happened**:

Not getting any data after a specific date. 3 clusters , 3 differents prometheus and thanos deployments pointing each on a different bucket S3. For about a week i wasnt able to access the data when using grafana after 22 january , yesterday that changed now i m not able to access after 5 February. 
This happened simultanesly on the 3 environements, i did a thanos verify bucket and a --repair nothing changed and nothing to report. No logs. 
Thing that is weird is that this happens each time the compactor creates on S3 a big chunk of data on the S3 bucket ( when created the from 23 january until 6 february , and when created the 6february till now )

  retentionResolutionRaw: 14d
  retentionResolution5m: 120d
  retentionResolution1h: 1y

**What you expected to happen**:

Expected to see all the data stored in S3.

**How to reproduce it (as minimally and precisely as possible)**:
Seems to happen everytime the compactor will create a new big chunk of data for a 14d period )

**Full logs to relevant components**:

No logs on thanos components
Did the thanos verify , --repair, inspect , nothing to mention

**Anything else we need to know**:

Running on kubernetes
helm chart
https://github.com/banzaicloud/banzai-charts/tree/master/thanos

**Comment by squat** [comment]
@nicopapayann just to be sure, the data is still in S3, right? And the new, compacted block actually has chunks with data? Otherwise, it seems like your store may not be successfully loading the larger, compacted blocks

**Comment by nicopapayann** [comment]
@squat yes this is the case, but i didnt find any way to fix this.
