### ISSUE TITLE
Thanos query is not fetching old data from s3

### ISSUE THREAD

**Issue by satyabhama** [thanos-io/thanos#2173]
We are trying to fetch old data from s3 storage via Grafana using thanos query.
We are not able to see old data and below error is coming in Thanos query

level=warn ts=2020-02-24T10:24:13.399884678Z caller=storeset.go:429 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from MonitoringStoreContainer:10911: rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 172.17.0.2:10911: connect: connection refused\"" address=MonitoringStoreContainer:10911

**Comment by squat** [comment]
Hi @satyabhama it looks like the address `172.17.0.2:10911` is either not accessible from the thanos querier or simply nothing is listening at that endpoint.

Could you maybe share more information about how you are running? e.g. config/manifests (it looks like maybe docker containers?)
Are you sure that the querier can actually hit that port?

-Lucas

**Comment by satyabhama** [comment]
Hey @squat we have thanos query and store running in one docker.
Query commands:

Command | ["query","--http-address=0.0.0.0:19192","--store=<prometheus url with thanos sodecar>:10912","--store=MonitoringStoreContainer:10911","--query.replica-label=replica"]
-- | --
Store commands:

Command | ["store","--objstore.config-file=/etc/thanos/prometheusconfig.yml","--data-dir==/thanos/store","--grpc-address=0.0.0.0:10911","--sync-block-duration=15m"]
-- | --

Could you please us from where IP 172.17.0.2:10911 is coming??

**Comment by squat** [comment]
Hi @satyabhama that IP is coming from Docker's service name resolution. 172.17.0.0/16 is the CIDR for the default Docker network, and 172.17.0.2 is apparently the IP being given to your Thanos Store container.

However, it seems that the port 10911 is not accessible. Are you sure that Docker is correctly exposing this port? Ie running Docker with the `--port` flag to expose the port

**Comment by squat** [comment]
Can you share the actual Docker commands you are running? Or if using Swarm, your Docker Swarm config?

**Comment by satyabhama** [comment]
In one docker container we have store and query component running and here is commands for that
Query commands:
Command | ["query","--http-address=0.0.0.0:19192","--store=:10912","--store=MonitoringStoreContainer:10911","--query.replica-label=replica"]
---------------------------------
Store commands:
Command | ["store","--objstore.config-file=/etc/thanos/prometheusconfig.yml","--data-dir==/thanos/store","--grpc-address=0.0.0.0:10911","--sync-block-duration=15m"]
-----------------------------
