### ISSUE TITLE
Add micro benchmarks to fetcher.go filters.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2174]
It would be awesome to learn if we need more concurrency etc there.

Those filters are critical for our components to learn about new blocks.

**Comment by grzkv** [comment]
Are we primarily talking about benchmarking the `Filter` functions?

**Comment by bwplotka** [comment]
That's correct, but maybe only for more complex ones. E.g like https://github.com/thanos-io/thanos/pull/2118

I no longer work on this, so feel free to grab this and finish :hugs:

**Comment by grzkv** [comment]
Great. I'll take it!

**Comment by bwplotka** [comment]
Awesome. Might be good to sync with @khyatisoneji, but she is busy recently so I am pretty sure she will be happy for you to continue benchmarking. (: 

Feel free to checkout my branch and get all changes, then work on top of it (:

**Comment by yashrsharma44** [comment]
Hey @bwplotka! I was wondering if this issue is not picked up yet, can I solve this issue? I will try and understand the requirements of this issue, before pushing in a PR!

**Comment by bwplotka** [comment]
Of crouse, go for it @yashrsharma44 if @grzkv is not active  :+1: 

You can see the https://github.com/thanos-io/thanos/pull/2118 for some start.

**Comment by grzkv** [comment]
@bwplotka @yashrsharma44 Sorry, I am short on time at least until the end of this week. Please feel free to pick it up.
