### ISSUE TITLE
Sidecar Startup failed   

### ISSUE THREAD

**Issue by JCchenxiang** [thanos-io/thanos#2175]
**Thanos, Prometheus and Golang version used**:
k8s   thanos-0.8.0  prometheus-2.14.0  

**What happened**:
-- When I start the container in the k8s cluster,the sidecar fails to start
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:
level=info ts=2020-02-24T13:09:21.781458223Z caller=main.go:170 msg="Tracing will be disabled"
level=info ts=2020-02-24T13:09:21.781807603Z caller=sidecar.go:129 msg="no supported bucket was configured, uploads will be disabled"
level=info ts=2020-02-24T13:09:21.782019987Z caller=main.go:257 component=sidecar msg="disabled TLS, key and cert must be set to enable"
level=info ts=2020-02-24T13:09:21.782236297Z caller=sidecar.go:307 msg="starting sidecar"
level=info ts=2020-02-24T13:09:21.782339631Z caller=main.go:353 msg="listening for requests and metrics" component=sidecar address=0.0.0.0:19191
level=info ts=2020-02-24T13:09:21.782390092Z caller=prober.go:143 msg="changing probe status" status=healthy
level=warn ts=2020-02-24T13:09:21.78339025Z caller=prober.go:154 msg="changing probe status" status=unhealthy reason="create watcher: too many open files"
level=info ts=2020-02-24T13:09:21.783462994Z caller=sidecar.go:240 component=sidecar msg="Listening for StoreAPI gRPC" address=0.0.0.0:19090
level=warn ts=2020-02-24T13:09:21.783512578Z caller=sidecar.go:165 msg="failed to fetch initial external labels. Is Prometheus running? Retrying" err="request flags against http://localhost:9090/api/v1/status/config: Get http://localhost:9090/api/v1/status/config: context canceled"
level=error ts=2020-02-24T13:09:21.783535819Z caller=main.go:215 msg="running command failed" err="create watcher: too many open files"
-- 
![image](https://user-images.githubusercontent.com/37063302/75155243-90fe4200-574a-11ea-8384-72bda68d502e.png)
-- 
![image](https://user-images.githubusercontent.com/37063302/75155296-b2f7c480-574a-11ea-8867-06a8507a219e.png)

**Anything else we need to know**:
-- I want to know why the sidecar failed to start

**Comment by daixiang0** [comment]
You need to ensure promtheus runs as expected first. Could you confirm this?

**Comment by JCchenxiang** [comment]
yes，I have solved it.

**Comment by fr-me-jim** [comment]
> yes，I have solved it.

Can you explain how you solved this issue please?
