### ISSUE TITLE
Metric name regex filter at sidecar level (ship only filtered data to external storage)

### ISSUE THREAD

**Issue by raz08** [thanos-io/thanos#2179]
Hi All,

Is there way we can add metric name regex filter at sidecar level? . Basically I want to ship or upload only aggregated data (*_total) to external storage. This is to avoid uploading all raw data(e.g. data from replica set or from multiple pods)  to external storage.

As of now Thanos sidecar does not support this as per my understanding. Is it possible to add feature/improvement on sidecar. I know sidecar is designed for lightweight and it will use less memory and cpu. Does it make sense keep light weight code at sidecar? 

In Thanos slack channel conversation with bwplotka. It is not possible to add with current existing design. https://cloud-native.slack.com/archives/CK5RSSC10/p1581673374484000

Any suggestions or opinions?

**Comment by bwplotka** [comment]
Hi :wave: 

Will respond in details soon, for now, you can read the conversation here: https://cloud-native.slack.com/archives/CK5RSSC10/p1581673374484000

**Comment by raz08** [comment]
HI @bwplotka ,

We had that conversation in slack channel. sorry for again creating it here, In slack we may lose chat history, so thought of having here in git hub.
