### ISSUE TITLE
Thanos Sidecar : no space left on device

### ISSUE THREAD

**Issue by desourav** [thanos-io/thanos#2187]
**Thanos, Prometheus and Golang version used**:
Prometheus : 2.12.0
Thanos : 0.7.0

**What happened**:

Thanos querier not showing older data. I dont see any issues with the logs of thanos querier but the sidecar shows the below logs.

**What you expected to happen**:
Expect to work as expected.

**How to reproduce it (as minimally and precisely as possible)**:
Prometheus PVC is set to '40Gi'

Thanos sidecar args :  

```
[
                'sidecar',
                '--log.level=debug',
                '--tsdb.path=/var/prometheus',
                '--prometheus.url=http://localhost:9090',
                '--objstore.config=type: S3

```
**Full logs to relevant components**:

```
level=warn ts=2020-02-25T15:56:11.809927921Z caller=shipper.go:333 msg="updating meta file failed" err="close /var/prometheus/thanos.shipper.json.tmp: no space left on device"
level=warn ts=2020-02-25T15:56:42.13484075Z caller=shipper.go:333 msg="updating meta file failed" err="close /var/prometheus/thanos.shipper.json.tmp: no space left on device"
level=warn ts=2020-02-25T15:57:11.824793932Z caller=shipper.go:333 msg="updating meta file failed" err="close /var/prometheus/thanos.shipper.json.tmp: no space left on device"
level=warn ts=2020-02-25T15:57:41.752328957Z caller=shipper.go:333 msg="updating meta file failed" err="close /var/prometheus/thanos.shipper.json.tmp: no space left on device"
```

**Comment by daixiang0** [comment]
It seems `/var/prometheus` has no space left and thanos can not update shipper file.
Could you call `du -sh /var/prometheus` to show the space usage?
I guess prometheus can not write new WALs too.
For production, if you use PVC, make it auto enlarge is a good choice to avoid no disk space issue.

**Comment by desourav** [comment]
Changed pvc to auto-enlarge as a remedy for this problem.
