### ISSUE TITLE
resolvePeers() overrides peer lookup behaviour in memberlist library

### ISSUE THREAD

**Issue by mattbostock** [thanos-io/thanos#219]
The `resolvePeers()` function in the `cluster` package tries to resolve the IP addresses for the cluster peers:
https://github.com/improbable-eng/thanos/blob/19ff509a4f658887f90ab543c79cc821762f64cd/pkg/cluster/cluster.go#L423-L476

It does this using the Go DNS resolver.

The memberlist library does the same thing, but uses TCP first in a bid to retrieve as many peers as possible:
https://github.com/hashicorp/memberlist/blob/ce8abaa0c60c2d6bee7219f5ddf500e0a1457b28/memberlist.go#L303-L306

Go's resolver may try TCP if the UDP query results in a truncated response, so maybe this is not an issue. But it seems like Thanos is doing more than it needs to - there's a lot of overlap between the code in these two places.

Should Thanos delegate DNS resolution for peers to the memberlist library, and is there a compelling reason for it to do its own resolution as it is currently?

**Comment by yeya24** [comment]
Can we close this issue now? Since cluster has been removed.

**Comment by povilasv** [comment]
:+1: closing the issue as gossip is removed.
