### ISSUE TITLE
image busybox dns resolution failed

### ISSUE THREAD

**Issue by k8sre** [thanos-io/thanos#2206]
k8s: 1.17.2
os: centos 7.6
kernel: 3.10.0-1062.el7.x86_64
thanos: v0.10.1

prometheus headless service is not  resolution by thanos-query container.
but ping is work

<img width="731" alt="WX20200302-221043@2x" src="https://user-images.githubusercontent.com/35365219/75683798-b7842600-5cd2-11ea-805c-353c279844ba.png">

**Comment by daixiang0** [comment]
I think the best place to ask is k8s community, it is a network issue indeed, which relates to your CNI and CNI config, even host iptables/firewall.

**Comment by k8sre** [comment]
> I think the best place to ask is k8s community, it is a network issue indeed, which relates to your CNI and CNI config, even host iptables/firewall.

others Pod container is work,only thanos
