### ISSUE TITLE
Query latency increased after upgrade Thanos v0.10.1 ->v 0.11.0

### ISSUE THREAD

**Issue by IKSIN** [thanos-io/thanos#2213]
**Thanos, Prometheus and Golang version used**:
Thanos: v0.11.0
Golang: 1.13.8

**Object Storage Provider**:
CEPH (S3)

**What happened**:
Query latency increased

**What you expected to happen**:
Same latency that on v0.10.1

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by IKSIN** [comment]
<img width="1636" alt="Screenshot 2020-03-03 at 16 51 23" src="https://user-images.githubusercontent.com/2960110/75784162-d9cd8080-5d72-11ea-9939-f37518693b59.png">
<img width="1581" alt="Screenshot 2020-03-03 at 14 44 04" src="https://user-images.githubusercontent.com/2960110/75784175-dc2fda80-5d72-11ea-8df9-2968ea46aef5.png">

**Comment by bwplotka** [comment]
Thanks for the reports.

Let's eliminate the unknown. The major changes to querying was:

* store timeout: you said you are running on ported 0.10.1 + this and it was fine, but are we sure ported commit was actually the same?
* index-header: However if not enabled, it should change nothing. Maybe we actually touched something? Will look.
* Refetch: We added this: https://github.com/thanos-io/thanos/pull/1985 Let's check for log msg: series size exceeded expected size; refetching or `thanos_bucket_store_series_refetches_total`
* Minio client update .. :man_shrugging: Worth to look?

Worth to check:

* If the same queries are running.
* CPU Profile differences

NOTE: You show graph with high latency metric for store GW, but this latency is really depending on Querier (due to our streaming round-robin behavior), so we don't really know if it's store being slow, or querier or yet another Store API :/

**Comment by bwplotka** [comment]
The easiest way would be to go back on master container images and do bi search. Maybe without index-header first?

**Comment by bwplotka** [comment]
Refetches are not the problem: https://cloud-native.slack.com/archives/CL25937SP/p1583249306101000?thread_ts=1583243694.092700&cid=CL25937SP

@d-ulyanov

**Comment by GiedriusS** [comment]
@IKSIN any updates on your investigation? I ran into the same problem and tried to do some digging but still couldn't find anything specific. I concur: refetches and JSON/binary index headers don't make a difference. I was wondering perhaps you've found something.

**Comment by d-ulyanov** [comment]
@GiedriusS hi!
We now focused on stabilizing v0.10, so this issue is postponed currently :(

**Comment by bwplotka** [comment]
No idea on our front either.  I hope for this to tell us more: https://github.com/thanos-io/thanos/pull/2305

**Comment by bwplotka** [comment]
Also it would be nice to figure it out before 0.12 release next week cc @squat

**Comment by bwplotka** [comment]
Wonder if we are not hitting this: https://github.com/prometheus/prometheus/issues/6968

**Comment by yeya24** [comment]
@IKSIN  What Prometheus version are you using? If you are using v2.17.0, maybe you could try the latest v2.17.1 release, which contains the fix for the query performance regression. Then we can check if this problem is in the Prometheus side.

**Comment by d-ulyanov** [comment]
we use v2.16, the problem is definitely not related to Prometheus.

**Comment by bwplotka** [comment]
Yea, also we are using some commit before 2.16 as a Prom dependency of
Thanos, plus the found regression was regarding head block, so something
else might cause it in Thanos.

Still in progress of expanding micro benchmarks.

Kind Regards,
Bartek

**Comment by mkabischev** [comment]
We did another try to update stores version (to latest master this time), but still got performance problem. According to pprof there were a lot of goroutines downloading postings from ceph.
```
529 @ 0x4313d0 0x405b78 0x405b4e 0x40583b 0xd5c432 0xd5c368 0xda43ec 0xda4727 0x856229 0x16bbc61 0x16d3ac0 0x887884 0x45f261
#	0xd5c431	github.com/minio/minio-go/v6.(*Object).doGetRequest+0x251				/go/pkg/mod/github.com/minio/minio-go/v6@v6.0.49/api-get-object.go:282
#	0xd5c367	github.com/minio/minio-go/v6.(*Object).Read+0x187					/go/pkg/mod/github.com/minio/minio-go/v6@v6.0.49/api-get-object.go:356
#	0xda43eb	github.com/thanos-io/thanos/pkg/objstore/s3.(*Bucket).getRange+0x1cb			/go/src/github.com/thanos-io/thanos/pkg/objstore/s3/s3.go:269
#	0xda4726	github.com/thanos-io/thanos/pkg/objstore/s3.(*Bucket).GetRange+0x76			/go/src/github.com/thanos-io/thanos/pkg/objstore/s3/s3.go:286
#	0x856228	github.com/thanos-io/thanos/pkg/objstore.(*metricBucket).GetRange+0xf8			/go/src/github.com/thanos-io/thanos/pkg/objstore/objstore.go:293
#	0x16bbc60	github.com/thanos-io/thanos/pkg/store.(*bucketBlock).readIndexRange+0xc0		/go/src/github.com/thanos-io/thanos/pkg/store/bucket.go:1275
#	0x16d3abf	github.com/thanos-io/thanos/pkg/store.(*bucketIndexReader).fetchPostings.func3+0xef	/go/src/github.com/thanos-io/thanos/pkg/store/bucket.go:1627
#	0x887883	golang.org/x/sync/errgroup.(*Group).Go.func1+0x63					/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57
```

Comparing to 0.10 version it’s extremely large number of such goroutines.
Also I saw very low number of touched postings and in the same fetched postings values were low as usual. It looks like postings aren’t cached at all and store tries to download them for each request.

![image](https://user-images.githubusercontent.com/864369/78254256-51233b00-74fe-11ea-8b78-c77978b30dd5.png)

![image](https://user-images.githubusercontent.com/864369/78254282-5aaca300-74fe-11ea-8dfa-26adfb46768d.png)

We tried `master-2020-03-31-b5298bac` image, so it has index-header enabled by default.

**Comment by bwplotka** [comment]
Was index-header enabled?  We might want to tweak concurrency of posting fetch. Might be the cause of slow downs if CPU is starved. What's the resource usage (CPU,mem) during those load tests?

**Comment by bwplotka** [comment]
Also we can tweak partitioning of posting fetches. Maybe we do too many  small fetches, it's better to group more? (here: https://github.com/thanos-io/thanos/blob/214ff4480e93f89a8e39b29fd4a43ccea1f61d3e/pkg/store/bucket.go#L1845)

Thanks for doing this BTW!

**Comment by mkabischev** [comment]
Yes, index-header was enabled. CPU, memory & network I/O all were much much lower than usual.
Also I fetched block-profile & and it looked like:
<img width="1778" alt="Screenshot 2020-04-02 at 16 38 18" src="https://user-images.githubusercontent.com/864369/78255815-7dd85200-7500-11ea-8da8-e162af24fdc1.png">
So it was just waiting for ceph responses.

**Comment by bwplotka** [comment]
oh this good to know.!

What's you cache size for posting, series? What if you increase that?
Does it mean Ceph is slow? I think we could try:

* LRU cache more (posting offset and symbols as well)
* Tweak partitioning for ceph. Maybe it;s more efficient to do more fine granular request or maybe less bigger ones - we need to check. Adjusting [this code](https://github.com/thanos-io/thanos/blob/214ff4480e93f89a8e39b29fd4a43ccea1f61d3e/pkg/store/bucket.go#L1845) would do (: 
* Split queries by time / by series (e.g cortex frontend)

**Comment by mkabischev** [comment]
There were no evictions/overflows in cache: 0 both for 0.10 and `master` versions.
Did you change logic about fetching postings in 0.11? I mean this picture looks like cache didn't work at all during "test" period.
![image](https://user-images.githubusercontent.com/864369/78265924-c21e1f00-750d-11ea-8c9b-3c8592fe954b.png)

**Comment by bwplotka** [comment]
Hah (: This looks really like IT is working, no? Looks like less series
bytes were touched in 0.12, so cache is used?

**Comment by mkabischev** [comment]
Hmm.. If cache works then *_fetched_* metrics should be low, and touched will be the same. touched=fetched+cached, correct? 

For me it looks like it didn't found postings in cache, tried to download them from ceph but a lot of request were canceled due to timeout. So why *_fetched_* metric is low as before.

Or I'm wrong?

**Comment by bwplotka** [comment]
Yea, `touch`-`fetch` = `cached`, but this graph can be very misleading. What if the proportion of scale Y is different (it is IMO)

Looks like in offline discussion you found that you have malformed index-header:

```
fetch series for block 01E4XPG3C5P9RACCM588PTM38Q: expanded matching posting: get postings: index header PostingsOffset: get postings offset entry: invalid size"
```

https://cloud-native.slack.com/archives/CL25937SP/p1585846203132900?thread_ts=1585832906.130800&cid=CL25937SP

**Comment by bwplotka** [comment]
Any update @mkabischev ?

I was right, we had a potential issue with partial writes, fixed here: https://github.com/thanos-io/thanos/pull/2371

**Comment by mkabischev** [comment]
There were no problems during index header generation, they're consisted. After I think that problem is here: https://github.com/thanos-io/thanos/blob/master/pkg/block/indexheader/binary_reader.go#L676...L684

**Comment by bwplotka** [comment]
> There were no problems during index header generation

Not generation, but reading.

**Comment by bwplotka** [comment]
Looking into sort.

**Comment by bwplotka** [comment]
First of all, this code is from https://github.com/prometheus/prometheus/blob/0cff72d756d3b0eb1690dce66b9ca62b32f1deb8/tsdb/index/index.go#L1533.

Secondly:

> There can be situation when value isn't really presented in e.offsets

It can't. As we have all labels from `LabelValues`. So we know all the callers will put known values. This is not well commented though and maybe somehow we do this somewhere. Still I think it can happen only malformed binary header that's why I think this happened to you. I fixed the root cause of possible malformation (only possibility hopefully). 

Question is can we make this code more resilient on those malformations anyway without the overhead (and have tests for). We can definitely put comment about the not found ranges etc. That positions for given value has to really exists...

**Comment by bwplotka** [comment]
> There were no problems during index header generation, they're consisted.  

How do you know? There will be no error/metric during crash or restart of store in  the middle of binary header creation

**Comment by bwplotka** [comment]
![image](https://user-images.githubusercontent.com/6950331/78587850-877df480-7835-11ea-93fb-8fa8f9c5785b.png)

**Comment by bwplotka** [comment]
Looks like @mkabischev is right this is something else as we though cc @squat 

We are investigating here: https://cloud-native.slack.com/archives/CL25937SP/p1585832906130800

**Comment by bwplotka** [comment]
Not all unexisting values triggers this: https://github.com/thanos-io/thanos/compare/posting-fix?expand=1

**Comment by bwplotka** [comment]
I believe with fixes linked above this can be closed :hugs:
