### ISSUE TITLE
Query: DNS Service Discovery not working in GKE

### ISSUE THREAD

**Issue by alunsford** [thanos-io/thanos#2220]
**Thanos, Prometheus and Golang version used**: 
Thanos: v0.10.1
Prometheus: 2.16.0

**Object Storage Provider**: GCS

**What happened**: When running multiple Store APIs behind a service (whether they are the Store component or a Prometheus Sidecar), Query will only pick one of the pods to discover.

**What you expected to happen**: I expected all pods behind the service to be discovered.

**How to reproduce it (as minimally and precisely as possible)**: I don't know if this happens outside of GKE, but in GKE, deploy multiple Store components or multiple Prometheus instances with side cars behind a single service. Add a `--store` flag to the run command for your Query component, following any of the dns formats (`dns+`, `dnssrv+`, etc). Only 1 of the stores will show as being discovered in the Query logs and in the Query UI. This is more obvious when you have multiple Sidecars behind a service with different replica labels. Every time you restart Query, you will see it pick one of the replicas but never all of them.

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by GiedriusS** [comment]
Hello. Does that DNS record point to multiple IP addresses? Have you checked with e.g. `dig`?

**Comment by jojohappy** [comment]
@alunsford Any update?

**Comment by alunsford** [comment]
Hey, really sorry for never getting back to this. The DNS record is the internal dns record for the kubernetes service. We followed the example in the Service Discovery documentation:

> DNS SRV record discovery also work well within Kubernetes. Consider the following example:
> 
> `--store=dnssrv+_grpc._tcp.thanos-store.monitoring.svc`

The services are deployed as NodePort types. We tried all of the different permutations listed under https://thanos.io/service-discovery.md/#dns-service-discovery without success. Ultimately we ended up programmatically generating a `store-endpoints.yaml` configmap to get around the issue.

**Comment by mkubaczyk** [comment]
Hi guys.
I had similar problem, but the fix is quite simple: just make your Service a Headless one (https://kubernetes.io/docs/concepts/services-networking/service/#headless-services). Then
you can easily take advantage of `dnssrv+_grpc._tcp.<SVC_NAME>.<SVC_NAMESPACE>.svc`.
