### ISSUE TITLE
query: doesn't return compacted data

### ISSUE THREAD

**Issue by StupidScience** [thanos-io/thanos#2221]
**Thanos, Prometheus and Golang version used**:
quay.io/thanos/thanos:v0.10.1

**Object Storage Provider**:
Azure Blob

**What happened**:
At some time (I believe after changing compacting retentions but still not sure) query doesn't show metrics older than 1 week(retention for raw metrics) although I can see them via thanos bucket
![image](https://user-images.githubusercontent.com/32177073/76073134-39fa3780-5faa-11ea-9784-40f7b855e497.png)

Flags of compact
```
    - --retention.resolution-raw=1w
    - --retention.resolution-5m=12w
    - --retention.resolution-1h=56w
```

**What you expected to happen**:

I expect that I'll be able to look all metrics.

**How to reproduce it (as minimally and precisely as possible)**:

Not sure

**Full logs to relevant components**:

Nothing interesting in logs

**Anything else we need to know**:
-

**Comment by GiedriusS** [comment]
What kind of query are you executing and with what `step`?

**Comment by StupidScience** [comment]
@GiedriusS I tried to set different steps, for example `5m`, `1h`, `24h` and some simple query without any time window definitions like 
```text
sum  by (pod_name)(container_cpu_usage_seconds_total{image!="",name=~"^k8s_.*",datacenter=~"$dc",namespace="$namespace",container_name=~"$container"})
```
Not sure, what exactly should I look for in store logs? There are a lot of them.

FYI looks like everything worked well until I changed compactor retentions.

**Comment by romoy** [comment]
Could you check if the raw data is in the object store?

**Comment by StupidScience** [comment]
@romoy how to do that? What should I look for? I sent screen from bucket before. It shows that data exists.
Also raw data not compacted data? I am able to query over raw data. But looks like I can't query over 5m and 1h resolution.

**Comment by romoy** [comment]
I'm experiencing https://github.com/thanos-io/thanos/issues/2290 with the same symptom, wanted to see if you were experiencing the same.

**Comment by StupidScience** [comment]
@romoy thanks for pointing out to your case. I drill down there and figure out what was wrong in my case. I enabled `auto-downsampling` for query and everything looks good now. Closing this.
