### ISSUE TITLE
query: Deduplication latency

### ISSUE THREAD

**Issue by yineima** [thanos-io/thanos#2222]
thanos version 
v0.9.0

prometheus version
 version 2.14.0

**Object Storage Provider**:
no use of object store，use local disk

**What happened**:
After useing query.replica-label for HA, lately I found queries consume much more time than before 
deduplication makes query slow
same query，not query range
deduplication cost 23s, however no deduplication  only cost 293ms.
this is a huge cost for HA

here is my Screenshot
![image](https://user-images.githubusercontent.com/7900766/76084337-a006af00-5fea-11ea-8065-129e2f35b086.png)

the query is  sum(rate(appnews_importable_bf_request_num{job="import_interface",product="Inews"} [1m] offset 24h))

appnews_importable_bf_request_num{job="import_interface",product="Inews"} offset 24h has about 1200 samples

![image](https://user-images.githubusercontent.com/7900766/76084873-d55fcc80-5feb-11ea-8dc6-5e6e38d71613.png)

I wonder Does it make sense？
or Is there any wrong with my usage？
 

**What you expected to happen**:
not too much worse proformace than before

hope you could reply this issue ASAP
this issus makes me crazy.
Thank you.

**Comment by bwplotka** [comment]
Thanks for this report.

So normally the overhead is unnoticeable, so there might be some bug there for your case here. It would be nice to dive deeper. What I find really suspicious is that `appnews_importable_bf_request_num{job="import_interface",product="Inews"} offset 24h` takes 322ms WITH Deduplication, but `sum(rate(appnews_importable_bf_request_num{job="import_interface",product="Inews"} [1m] offset 24h)` is suddenly 24s? That's kind of unlikely.

Let's dive deeper:

1. You say 1200 samples. But this is for instant query without range selector `[1m]`. Can we do instant query on console for `appnews_importable_bf_request_num{job="import_interface",product="Inews"}[1m] offset 24h`? If you have 1200 series I expect it to be something like 4x1200 samples. 
2. Can you check latency for `appnews_importable_bf_request_num{job="import_interface",product="Inews"}[1m] offset 24h` with and without deduplictation?

**Comment by bwplotka** [comment]
Also, Try without offset, but I think the issue that we are selecting all 24h+1m was fixed in v0.9.0 already.

**Comment by yineima** [comment]
> Thanks for this report.
> 
> So normally the overhead is unnoticeable, so there might be some bug there for your case here. It would be nice to dive deeper. What I find really suspicious is that `appnews_importable_bf_request_num{job="import_interface",product="Inews"} offset 24h` takes 322ms WITH Deduplication, but `sum(rate(appnews_importable_bf_request_num{job="import_interface",product="Inews"} [1m] offset 24h)` is suddenly 24s? That's kind of unlikely.
> 
> Let's dive deeper:
> 
> 1. You say 1200 samples. But this is for instant query without range selector `[1m]`. Can we do instant query on console for `appnews_importable_bf_request_num{job="import_interface",product="Inews"}[1m] offset 24h`? If you have 1200 series I expect it to be something like 4x1200 samples.
> 2. Can you check latency for `appnews_importable_bf_request_num{job="import_interface",product="Inews"}[1m] offset 24h` with and without deduplictation?

Thank you for your quick reply.
1.  with range selector [1m]. one serie could have 4 or 5 samples. 
So when I do instant query on console for  appnews_importable_bf_request_num{job="import_interface",product="Inews"}[1m] offset 24h with deduplication, I got this
![image](https://user-images.githubusercontent.com/7900766/76189127-dde71b80-6214-11ea-94ab-364dec4b13ff.png)

2.this is the latency comparsion for appnews_importable_bf_request_num{job="import_interface",product="Inews"}[1m] offset 24h

![image](https://user-images.githubusercontent.com/7900766/76190277-92823c80-6217-11ea-9872-024ce1b818f3.png)


3.this is the latency comparsion for appnews_importable_bf_request_num{job="import_interface",product="Inews"}[1m] 

![image](https://user-images.githubusercontent.com/7900766/76190313-ab8aed80-6217-11ea-9175-faae20358e58.png)


Thank you!

**Comment by yineima** [comment]
Does it may have some connection with query traffic?
I have set  --query.timeout 20m --query.max-concurrent 200 for query 
but I've not found any config of concurrent for sidecar

**Comment by bwplotka** [comment]
I mean try to not use the sidecar for anything else for period of tests (:

**Comment by daixiang0** [comment]
Do we have a tool or something to do pre-deduplication? If not, would be implemented it in compactor?

**Comment by bwplotka** [comment]
Yes. Please see: https://github.com/thanos-io/thanos/issues/1014 (:

**Comment by PowerSurj** [comment]
This seems still an issue. Deduplication adds significant latencies, particularly visible when queries have big number of series.
