### ISSUE TITLE
transport: Error while dialing dial tcp: lookup store on 127.0.0.11:53: no such host

### ISSUE THREAD

**Issue by linhuisheng** [thanos-io/thanos#2234]
I USE this docker-compose: https://github.com/ruanbekker/thanos-ha-prometheus-docker
Why not start store:
![image](https://user-images.githubusercontent.com/8087304/76166075-b2255080-6196-11ea-8c5e-3a20dea05799.png)

store:10905 | DOWN |   | 1970-01-01T00:00:00Z | 1970-01-01T00:00:00Z | 19ms ago | fetching store info from store:10905: rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = "transport: Error while dialing dial tcp: lookup store on 127.0.0.11:53: no such host"
-- | -- | -- | -- | -- | -- | --

![image](https://user-images.githubusercontent.com/8087304/76166083-c2d5c680-6196-11ea-8b1e-370faf72bdca.png)
query0_1         | level=debug name=query-0 ts=2020-03-08T15:44:28.080158001Z caller=storeset.go:335 component=storeset msg="checked requested storeAPIs" healthyStores=4 cachedStores=4
query0_1         | level=debug name=query-0 ts=2020-03-08T15:44:28.080190618Z caller=storeset.go:332 component=storeset msg="starting updating storeAPIs" cachedStores=4
query1_1         | level=warn name=query-1 ts=2020-03-08T15:44:33.058263676Z caller=storeset.go:429 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from store:10905: rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup store on 127.0.0.11:53: no such host\"" address=store:10905
query1_1         | level=debug name=query-1 ts=2020-03-08T15:44:33.058382078Z caller=storeset.go:335 component=storeset msg="checked requested storeAPIs" healthyStores=4 cachedStores=4
query1_1         | level=debug name=query-1 ts=2020-03-08T15:44:33.058698281Z caller=storeset.go:332 component=storeset msg="starting updating storeAPIs" cachedStores=4
query0_1         | level=warn name=query-0 ts=2020-03-08T15:44:33.081041181Z caller=storeset.go:429 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from store:10905: rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup store on 127.0.0.11:53: no such host\"" address=store:10905
query0_1         | level=debug name=query-0 ts=2020-03-08T15:44:33.081212356Z caller=storeset.go:335 component=storeset msg="checked requested storeAPIs" healthyStores=4 cachedStores=4
query0_1         | level=debug name=query-0 ts=2020-03-08T15:44:33.081344506Z caller=storeset.go:332 component=storeset msg="starting updating storeAPIs" cachedStores=4
query1_1         | level=warn name=query-1 ts=2020-03-08T15:44:38.059377223Z caller=storeset.go:429 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from store:10905: rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup store on 127.0.0.11:53: no such host\"" address=store:10905
query1_1         | level=debug name=query-1 ts=2020-03-08T15:44:38.059456518Z caller=storeset.go:335 component=storeset msg="checked requested storeAPIs" healthyStores=4 cachedStores=4
query1_1         | level=debug name=query-1 ts=2020-03-08T15:44:38.059535574Z caller=storeset.go:332 component=storeset msg="starting updating storeAPIs" cachedStores=4
query0_1         | level=warn name=query-0 ts=2020-03-08T15:44:38.082897317Z caller=storeset.go:429 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from store:10905: rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup store on 127.0.0.11:53: no such host\"" address=store:10905
query0_1         | level=debug name=query-0 ts=2020-03-08T15:44:38.08302093Z caller=storeset.go:335 component=storeset msg="checked requested storeAPIs" healthyStores=4 cachedStores=4
query0_1         | level=debug name=query-0 ts=2020-03-08T15:44:38.083103481Z caller=storeset.go:332 component=storeset msg="starting updating storeAPIs" cachedStores=4
![image](https://user-images.githubusercontent.com/8087304/76166092-d1bc7900-6196-11ea-9d76-f29aa96d93dd.png)

**Comment by jojohappy** [comment]
@linhuisheng Hi, your thanos store component did not started.  So you can not look up the `store`. Please check your docker compose config.
