### ISSUE TITLE
Probes should return the store status.

### ISSUE THREAD

**Issue by yfried** [thanos-io/thanos#2235]
As a user I wish to mark a thanos instance as unready/unhealthy if it cannot query any or all of its stores.
A simple solution would be to reature "TRUE" if all stores are UP, and "FALSE" otherwise. It would be even better if the probe can return a JSON with the store status instead of a simple "OK".

This will allow users who wish so to mark a thanos instance that can't query its store(s) as unavailable.

**Comment by daixiang0** [comment]
Would `ThanosRuleQueryHighDNSFailures` help? Please see https://github.com/thanos-io/thanos/blob/master/examples/alerts/alerts.yaml.

**Comment by yfried** [comment]
I'm not sure what you mean. On my setup `thanos_querier_store_apis_dns_lookups_total` is always 0.
Also, I have a specific store that is down now, so DNS query would work, but it still won't answer queries.

**Comment by jojohappy** [comment]
@yfried You can use `thanos_status{check=~"healthy|ready"}==0` to check status of all thanos components. Meanwhile use the query api to get the json data of metrics.

Hope for that will help.

**Comment by yfried** [comment]
Hi, I'm not sure about this metric. from what I can see, it doesn't show the store name, and as mentioned before, I have a store that's down for a few days, but it's not listed in this metric at all.

Also, what do you mean by:
> Meanwhile use the query api to get the json data of metrics.
?

**Comment by edliu-wish** [comment]
Any solution? I faced just the same issue
