### ISSUE TITLE
custom ca option for s3 storage

### ISSUE THREAD

**Issue by kbsquared** [thanos-io/thanos#2241]
**Thanos, Prometheus and Golang version used**: v0.10.1

**Object Storage Provider**: NetApp StorageGrid

**What happened**: No documentation or ability to specify a custom CA for internally provisioned certificates.

**What you expected to happen**:  Documentation on how to specify a custom CA chain, or if it's not available now, request it's added.

**How to reproduce it (as minimally and precisely as possible)**:  Use S3 storage with certificate signed by CA that is not already recognized by the node OS.

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by CitadelCore** [comment]
Still an issue
