### ISSUE TITLE
Query: FR: add filtering for the restricted access

### ISSUE THREAD

**Issue by nextus** [thanos-io/thanos#2244]
There are use cases when you need to provide limited access to your data for 3rd party consumers through restricted endpoints. Authorization can be based on presence specific label(s) in your request.

This feature existed in Prometheus `remote_read` client (called [`required_matchers`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_read)) but Thanos doesn't expose `remote_read` endpoint.

Currently, I just add simple matcher filtering here: https://github.com/thanos-io/thanos/blob/master/pkg/query/iter.go#L87 and build a custom binary for my own needs. But this feature seems useful for being implement in the right way in the upstream.

As I can see, `selector.relabel-config` semantic from Store can be applied here as well. Just want to hear your thoughts about what's the right way to implement this and what's the concerns.

**Comment by bwplotka** [comment]
Hi,

That's a valid request but all of those you can do using https://github.com/openshift/prom-label-proxy

We use that on production and it serves well (: This means we don't need to do this on Thanos side!

**Comment by bwplotka** [comment]
We think using https://github.com/openshift/prom-label-proxy is the way to go, but if you think something is still missing, we will reopen this issue! :hugs:  Thanks!
