### ISSUE TITLE
query can't get result of arithmetic binary operators between two scalars

### ISSUE THREAD

**Issue by wangyanzhao** [thanos-io/thanos#2245]
**Thanos used**: v0.10.1

**Object Storage Provider**: no use of object store

**What happened**: can't get result of arithmetic binary operators between two scalars, "No datapoints found". But it can get result from Prometheus.

![image](https://user-images.githubusercontent.com/12328857/76312447-10287400-630e-11ea-9e74-af7b8b2e1879.png)

**What you expected to happen**:

![image](https://user-images.githubusercontent.com/12328857/76315569-e4a88800-6313-11ea-81b6-4e4b76231bcd.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by GiedriusS** [comment]
What's `:node_cpu_utilisation:avg1m`? Does it have any label? FWIW I can query `sum(up) * 2` on 0.10.1 just fine. Could you please write some instructions on how to reproduce it?

**Comment by wangyanzhao** [comment]
All separate query is ok. Such as
1. :node_cpu_utilisation:avg1m

![image](https://user-images.githubusercontent.com/12328857/76339730-72489f80-6335-11ea-9045-90c604780696.png)

2. sum(kube_node_status_capacity_cpu_cores)

![image](https://user-images.githubusercontent.com/12328857/76339843-9c9a5d00-6335-11ea-8978-621d7f62fa31.png)

3. :node_cpu_utilisation:avg1m * 2

![image](https://user-images.githubusercontent.com/12328857/76340078-f26f0500-6335-11ea-9e74-331bc75ae143.png)

**Comment by wangyanzhao** [comment]
@GiedriusS

**Comment by wangyanzhao** [comment]
query "sum(:node_cpu_utilisation:avg1m) * sum(kube_node_status_capacity_cpu_cores)" is ok.

![image](https://user-images.githubusercontent.com/12328857/76380995-49ed8f00-638f-11ea-93e4-7bc14bcf91d9.png)

but in Promtheus, don't need sum, ":node_cpu_utilisation:avg1m * sum(kube_node_status_capacity_cpu_cores)" is ok.

**Comment by GiedriusS** [comment]
Still haven't gotten around to this exact issue but brainstormed an idea that we could run these correctness tests of PromQL in our CI: https://github.com/prometheus/prometheus/tree/master/promql/testdata on a simple Sidecar+Query setup.

**Comment by bwplotka** [comment]
Did we get onto this issue eventually?

**Comment by GiedriusS** [comment]
I couldn't reproduce this last time I have tried.

**Comment by bwplotka** [comment]
Awesome, let's close - if anyone can repro, just comment we will reopen :hugs:

**Comment by yeya24** [comment]
> Still haven't gotten around to this exact issue but brainstormed an idea that we could run these correctness tests of PromQL in our CI: https://github.com/prometheus/prometheus/tree/master/promql/testdata on a simple Sidecar+Query setup.

That sounds interesting. Cortex has https://github.com/cortexproject/cortex/pull/2203 to test the performance between its chunk and block storage. We can use a similar idea to do some AB testing between Prometheus and Thanos

**Comment by GiedriusS** [comment]
> > Still haven't gotten around to this exact issue but brainstormed an idea that we could run these correctness tests of PromQL in our CI: https://github.com/prometheus/prometheus/tree/master/promql/testdata on a simple Sidecar+Query setup.
> 
> That sounds interesting. Cortex has [cortexproject/cortex#2203](https://github.com/cortexproject/cortex/pull/2203) to test the performance between its chunk and block storage. We can use a similar idea to do some AB testing between Prometheus and Thanos

Maybe let's put this into a separate issue? What do you think? :P

**Comment by yeya24** [comment]
Sounds good to me. Would you like to open it? But I think https://github.com/prometheus/prometheus/tree/master/promql/testdata is not sufficient. If there is a promql fuzzer to randomly generate query, then it would be amazing.
