### ISSUE TITLE
cmd/thanos: Refactor run*(...) functions.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2248]
Hi :wave: 

Right now all our components can be run as a single commands. We do this via those ugly `run` functions with a sometimes a large number of arguments (one per each flag). e.g. https://github.com/thanos-io/thanos/blob/master/cmd/thanos/query.go#L132 It would be nice to fix this while preserving flags. The short fix would be to create config structs for each command that will be populated by flags, and then pass it to `run` functions?

AC:
* No more functions with 20+ arguments in Thanos.

**Comment by bwplotka** [comment]
Wonder if this helps https://github.com/peterbourgon/ff

**Comment by bwplotka** [comment]
@s-urbaniak as you were complaining about this :smiling_imp:

**Comment by PhilipGough** [comment]
@bwplotka I don't mind taking a stab at this if thats ok

**Comment by bwplotka** [comment]
Sure @PhilipGough :heart: 

Let us know here @PhilipGough what would be idea of end look .e.g. how you plan to achieve this. (:

**Comment by PhilipGough** [comment]
@bwplotka I did some work on the `sidecar` component only to get some feedback. See https://github.com/thanos-io/thanos/pull/2267

Basically, the idea I had was to decompose into smaller structs with related config and compose the config for the component from these.

Config structs are built by passing all flags into a func. The benefit here is that we wouldn't need to duplicate this info in each component, the downside (I haven't checked if its required) is the lack of ability to customise defaults in each component. Should the defaults always be the same?

I took a look at the package you linked and while it would probably work, would require a change from kingpin lib to flag package in stdlib. Maybe this is worth considering but I would have thought unlikely? 

I didn't see that the kingpin library had a way to populate struct fields directly during parse unfortunately

**Comment by bwplotka** [comment]
Almost done (:

**Comment by soniasingla** [comment]
@bwplotka i would like to play with this bug 😺

**Comment by PhilipGough** [comment]
@soniasingla I have some completed already but feel free to take any of the others. I am working through `query` at the moment, `compact` and `sidecar` are done.

**Comment by prmsrswt** [comment]
Still valid

**Comment by bwplotka** [comment]
As @MalloZup pointed, some commands are still to be done 🤗

**Comment by MalloZup** [comment]
ack

**Comment by bwplotka** [comment]
Maybe @idoqo, you want help here? Sounds like it's defined and we need this badly 🤗

**Comment by bwplotka** [comment]
I think querier, is almost done by @MalloZup , but let's look on other components if we can do the similar change as https://github.com/thanos-io/thanos/pull/3771#pullrequestreview-613076392

**Comment by idoqo** [comment]
While implementing the config struct for ruler, I noticed some advantage in the current approach (using the `run*` methods) and I'm not sure how to apply them to the "config structs" method yet.

Using  the `run*` methods as in https://github.com/thanos-io/thanos/blob/04ad33d79f676d4b78e866b6bfb893aed4ccff20/cmd/thanos/rule.go#L291), we can figure all the flags that are applicable to a component.

Abstracting those parameters into config structs could take that away for instance: [`shipperConfig`](https://github.com/thanos-io/thanos/blob/04ad33d79f676d4b78e866b6bfb893aed4ccff20/cmd/thanos/config.go#L125)  has four fields, but ruler only uses `allowOutOfOrderUpload `(i.e., `shipper.allow-out-of-order-uploads`). I feel like passing shipperConfig as a struct field for any config will imply that it accepts all four flags which is wrong.

**Comment by someshkoli** [comment]
If anyone was already working on `store` can pickup from here ✋🏾 didn't check earlier

**Comment by metonymic-smokey** [comment]
Are there any commands left to complete?
Wanted to take a stab at it since it's a good first issue

**Comment by yeya24** [comment]
Still valid
