### ISSUE TITLE
cmd: Ability to run multiple commands in single process.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2249]
It would be nice to be able to run many components as a single process. In a similar model, you can run Cortex. This is not a critical blocker but for demo purposes being able to run Querier + Compactor + Store in the same container for introduction demo would be a nice touch. (: 

Cortex is using this library: https://github.com/cortexproject/cortex/tree/master/pkg/util/services  It's great, but I wonder if such complexity is needed. For us, just different `run.Group` would do. The main problem is with discovery between those components in the same binary and configuration since we base on flags. Probably to solve this we would need to move all to config file...

The issue for some initial discussion on this.

**Comment by bwplotka** [comment]
Demo would be the only use case TBH, so quesiton is... is it worth pursuing.

**Comment by jojohappy** [comment]
Update.

**Comment by darshanime** [comment]
If the only usecase is easy demos, why not add a docker compose setup for thanos? 
It'll be as simple as [`docker-compose up`](https://docs.docker.com/compose/reference/up/) to get the entire stack up and running (using minio as bucket store would make it independent of external dependencies)

**Comment by bwplotka** [comment]
Looks like docker compose just landed on thanos-community org: https://github.com/prmsrswt/thanos-docker-compose

I think that's good enough for now..

I am not fan of having single comment to "rule them all", as so far we have feedback that what Loki and Cortex have causes major confusion here & there. Worth to rething. I think docker compose can help here greatly (:

**Comment by bwplotka** [comment]
I strongly believe that claiming that something is easier only because you can demo it easier with single process (but does not make sense for any realistic setups) is not a valid statement. 

Let's close this for now then :hugs:

**Comment by bwplotka** [comment]
There is actually one more use case: Just small home-size project e.g smart home telemetry etc (:

**Comment by bwplotka** [comment]
TODO. Nice as some good first issue potentially (:

Kind Regards,
Bartek Płotka (@bwplotka)

**Comment by SuperQ** [comment]
It's not just demos where this is useful. Small installs for users that are outside of Kubernetes need a lot of orchestration could use it.
