### ISSUE TITLE
store gw, compactor: Document supported actions for relabel config

### ISSUE THREAD

**Issue by kakkoyun** [thanos-io/thanos#2259]
Even though [compactor](https://thanos.io/components/compact.md/#flags) and [store gateway](https://thanos.io/components/store.md/#flags) provides a flag for relabeling configuration (`--selector.relabel-config`) and it says in the documentation that it behaves like Prometheus (https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config), it actually doesn't utilize label mutation actions, like `replace`, `labeldrop` etc. It's only used to keep or drop a block. 

https://github.com/thanos-io/thanos/blob/8a6746298ec39ccb40108e5517535e944d3920d3/pkg/block/fetcher.go#L400-L415

Documentation needs to be more clear about this. 
_Even better,  raise an error when one of the inefective rules specified._

cc @bwplotka 

**What happened**:

Specified a relabel config in Store and Compact, to drop a certain external label from blocks, and it didn't do anything. 

**What you expected to happen**:

I have expected Thanos to raise an error or log if it fails to execute a relabel action.
(Or actually do it, however apparently this is a design choice, so error would be good.)

**How to reproduce it (as minimally and precisely as possible)**:

* Specify `--selector.relabel-config` flag in Compactor, Store that uses a `labeldrop` action.
* Execute a query with a corresponding selector.

**Comment by bwplotka** [comment]
Also: We should block `hashmod` for compactor - it does not make sense :scream:

**Comment by bwplotka** [comment]
Let's add this here: https://thanos.io/sharding.md/
