### ISSUE TITLE
website: Dirs does not work. 

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2261]
Would be nice if dirs would show something meaningful like https://thanos.io/proposals even though https://thanos.io/proposals/201901-read-write-operations-bucket.md/ works (:

**Comment by kushthedude** [comment]
@bwplotka What do we need here, to have a page for `proposal` dirs which currently gives 404 ?

**Comment by bwplotka** [comment]
That's correct (:

**Comment by bwplotka** [comment]
Either some page, or maybe some special menu.. not sure

**Comment by bwplotka** [comment]
But it should not give 404... Maybe for each section like proposals, contributing, etc we should have index page?

**Comment by kushthedude** [comment]
> But it should not give 404... Maybe for each section like proposals, contributing, etc we should have index page?

What about having a readme for each section like `proposals,contributing etc` and which later can be used as index.md while making the website ?

**Comment by bwplotka** [comment]
That sounds epic! It will work like a charm for both GitHub and website,
nice idea! (:
