### ISSUE TITLE
stalebot: Differentiate between casual staleness and reminding 

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2262]
Hi, 

In Thanos Team Sync we decided that we need to actually have some `keep-alive` label for Thanos repository that allows us to not mark issues as stale after 1 month, but maybe in a different period - shorter or longer. It would be nice if we could just comment `/remind in 3 months.` (: 

I think that's doable with second stale bot (: 

Help wanted :+1:

**Comment by paulfantom** [comment]
There is a remind me bot available here: https://probot.github.io/apps/reminders/

**Comment by daixiang0** [comment]
@bwplotka i test it, just need to add to thanos repo then it is enough. See https://github.com/daixiang0/github-annual-report/issues/1

**Comment by bwplotka** [comment]
:+1:

**Comment by GiedriusS** [comment]
Hmm... what if we tell the `reminderbot` that we want to be reminded about an issue in 3 months but then `stalebot` closes it after 1 month of inactivity. Is that how it would work? Is there any direct integration between those two?

**Comment by bwplotka** [comment]
No, we will just special label to block stale bot e.g remind-instead. This
will enable remindbot instead. (:

**Comment by bwplotka** [comment]
It would be awesome to make progress on this! It keeps confusing community ):

**Comment by yeya24** [comment]
I tried the reminder bot, it seems that it only works for issues, not including PRs. Let me know what do you think about this. Is it enough or we want to make `reminder` work for PRs as well.

**Comment by bwplotka** [comment]
I think having this for issues is good enough for now, we can be more
strict on PRs as they get obsolete easily.

**Comment by bwplotka** [comment]
We actually fixed stale bot message and have remind bot as well :+1:
