### ISSUE TITLE
compactor: Simplify CLI flags

### ISSUE THREAD

**Issue by kakkoyun** [thanos-io/thanos#2266]
Currently, we have `--wait` and `--wait-interval` (recently added) to run compactor in repeated intervals. However, API could be simplified, by just keeping one. See the [discussion](https://github.com/thanos-io/thanos/pull/2265#pullrequestreview-374297408).
Before introducing any breaking changes, let's collect some feedback about the usage.

We should remove one of them before stabilizing the API. 
Adding this issue here keep track of it.

**Comment by yeya24** [comment]
Is it still valid?

**Comment by PhilipGough** [comment]
@kakkoyun, @bwplotka I was looking at continuing on with fixing #2248 and started to look at `compact` component first so naturally I came across this.

I was wondering if dropping the `wait` flag and setting `wait-interval` to a default of 0s and then add a check like 
```if interval != time.Second * 0 {
		// rununtil
	}
``` 
wouldn't achieve the same result as having both flags with `wait` defaulting to false currently?
Maybe this is confusing to the user though, wdyt?

**Comment by kakkoyun** [comment]
@PhilipGough We had the same discussion with @bwplotka, when we first add the flag https://github.com/thanos-io/thanos/pull/2265.

Since you also raised the same point, I think we should get rid of the additional flag. 
`wait-interval` also a bit misleading, `run-interval` maybe? 
Or if we can have an optional value for a flag, so that we can have `--wait` with the default interval and `wait=Xs` with the specified interval.

All in all, we can simplify and remove the extra flag.
