### ISSUE TITLE
compact: relabel doesn't seem to work

### ISSUE THREAD

**Issue by adrianmoisey** [thanos-io/thanos#2276]
**Thanos, Prometheus and Golang version used**: Golang: 1.13.8, Prometheus: 2.16.0, Thanos 0.11.0

Docker image tag: thanosio/thanos:v0.11.0

**Object Storage Provider**: S3

**What happened**: Using `--selector.relabel-config-file` with compact seems to cause it to ignore all metrics

**What you expected to happen**: I expect it to filter out a subset of my metrics

**How to reproduce it (as minimally and precisely as possible)**:
The following relabel config is used on both store gateway and compactor:
```
    - source_labels:
      - company_cluster
      regex: "k8s01"
      action: keep
```
This works on store gateway (I can confirm this by looking at the labels in the querier with and without the config).
If I apply this same config to compact, it doesn't seem to find any logs on S3:
```
level=info ts=2020-03-16T10:08:58.236772389Z caller=main.go:152 msg="Tracing will be disabled"
level=info ts=2020-03-16T10:08:58.236888733Z caller=factory.go:46 msg="loading bucket configuration"
level=info ts=2020-03-16T10:08:58.237369748Z caller=compact.go:386 msg="starting compact node"
level=info ts=2020-03-16T10:08:58.23739243Z caller=intrumentation.go:52 msg="changing probe status" status=ready
level=info ts=2020-03-16T10:08:58.237531455Z caller=intrumentation.go:64 msg="changing probe status" status=healthy
level=info ts=2020-03-16T10:08:58.237559276Z caller=http.go:56 service=http/server component=compact msg="listening for requests and metrics" address=0.0.0.0:19191
level=info ts=2020-03-16T10:08:58.237730264Z caller=compact.go:858 msg="start sync of metas"
level=info ts=2020-03-16T10:08:58.6458152Z caller=fetcher.go:368 component=block.MetaFetcher msg="successfully fetched block metadata" duration=408.03784ms cached=46 returned=16 partial=0
level=info ts=2020-03-16T10:08:58.645854874Z caller=compact.go:864 msg="start of GC"
level=info ts=2020-03-16T10:08:58.645864946Z caller=compact.go:872 msg="start of compaction"
level=info ts=2020-03-16T10:08:58.668436512Z caller=compact.go:910 msg="compaction iterations done"
level=info ts=2020-03-16T10:08:58.668487791Z caller=compact.go:313 msg="start first pass of downsampling"
level=info ts=2020-03-16T10:08:58.897931844Z caller=fetcher.go:368 component=block.MetaFetcher msg="successfully fetched block metadata" duration=229.395813ms cached=46 returned=16 partial=0
level=info ts=2020-03-16T10:08:58.898719673Z caller=compact.go:319 msg="start second pass of downsampling"
level=info ts=2020-03-16T10:08:59.241873599Z caller=fetcher.go:368 component=block.MetaFetcher msg="successfully fetched block metadata" duration=343.035759ms cached=46 returned=16 partial=0
level=info ts=2020-03-16T10:08:59.241996378Z caller=compact.go:324 msg="downsampling iterations done"
level=info ts=2020-03-16T10:08:59.242015301Z caller=retention.go:20 msg="start optional retention"
level=info ts=2020-03-16T10:08:59.50896084Z caller=fetcher.go:368 component=block.MetaFetcher msg="successfully fetched block metadata" duration=266.928512ms cached=46 returned=16 partial=0
level=info ts=2020-03-16T10:08:59.508999302Z caller=retention.go:41 msg="optional retention apply done"
level=info ts=2020-03-16T10:08:59.509009046Z caller=clean.go:25 msg="started cleaning of aborted partial uploads"
level=info ts=2020-03-16T10:08:59.828621969Z caller=fetcher.go:368 component=block.MetaFetcher msg="successfully fetched block metadata" duration=319.604241ms cached=46 returned=16 partial=0
level=info ts=2020-03-16T10:08:59.828659101Z caller=clean.go:50 msg="cleaning of aborted partial uploads done"
level=info ts=2020-03-16T10:13:58.237856562Z caller=compact.go:858 msg="start sync of metas"
level=info ts=2020-03-16T10:13:58.472914157Z caller=fetcher.go:368 component=block.MetaFetcher msg="successfully fetched block metadata" duration=234.991565ms cached=46 returned=16 partial=0
level=info ts=2020-03-16T10:13:58.472950888Z caller=compact.go:864 msg="start of GC"
```

**Anything else we need to know**: None

**Comment by bwplotka** [comment]
`company_cluster` what exactly label is? External_label for block right?

Also what values it can have?

**Comment by adrianmoisey** [comment]
That is correct. Here's a snippet from my prometheus config:
```
    global:
      evaluation_interval: 1m
      scrape_interval: 1m
      scrape_timeout: 10s
      external_labels:
        monitor: prometheus
        company_cluster: '$(CLUSTER)'
        company_region: '$(REGION)'
        replica: '$(HOSTNAME)'
```

Additionally, I run the queryer with `--query.replica-label=replica` for deduplication.

**Comment by adrianmoisey** [comment]
The values for `company_cluster` are currently only `k8s01` or `k8s02`.

**Comment by adrianmoisey** [comment]
This bug still exists.

**Comment by bwplotka** [comment]
Cool, How do you know it does not work? 

I would suggest upgrading to Compactor `v0.12.0` and going to our new UIs under `/loaded` and `/global` and check what blocks are actually loaded (:

**Comment by bwplotka** [comment]
Essentially it's unlikely it is a Thanos bug, because both store and compactor use exactly 1:1 the same code for deciding.

**Comment by adrianmoisey** [comment]
> I would suggest upgrading to Compactor `v0.12.0` and going to our new UIs under `/loaded` and `/global` and check what blocks are actually loaded (:

This is a great idea!
I did exactly this, and it's clear what's loaded and what isn't. Thank you 👏 

> Essentially it's unlikely it is a Thanos bug, because both store and compactor use exactly 1:1 the same code for deciding on label sharding

You're right. I'm unsure what I did that caused me to create this ticket, but it's clear that it's a user fault.

**Comment by bwplotka** [comment]
I assume alll works now? (:

**Comment by jojohappy** [comment]
@adrianmoisey You can also check the compact metrics how many blocks has been loaded or unloaded.
```
thanos_blocks_meta_synced{state="label-excluded"} 13
thanos_blocks_meta_synced{state="loaded"} 10
```

**Comment by adrianmoisey** [comment]
Just to close the loop here, using 0.12.1, I get the expected result. The UI is super helpful and confirms it's working.
I'm assuming that the issue was originally something I did wrong.
Thanks for the help!
