### ISSUE TITLE
rule: query parameter is not encoded properly in v0.11.0

### ISSUE THREAD

**Issue by tobiaszheller** [thanos-io/thanos#2281]
**Thanos, Prometheus and Golang version used**:
Thanos v0.11.0

**What happened**:

After upgrading thanos from v0.10.0 to v.0.11.0 thanos rule has stopped working.
I am using following setting for query:
```
--query=envoy-internal:80/thanos-query
```
It was working fine before asking for url `http://envoy-internal:80/thanos-query/api/v1/query`.
After upgrading to v0.11.0 query url with after hostname is not encoded properly:
`http://envoy-internal:80%2Fthanos-query/api/v1/query`.

**What you expected to happen**:

Encode url with path after hostname in valid way.

**How to reproduce it (as minimally and precisely as possible)**:

```
	scheme := "http"
	addr := "localhost:80/thanos"
	prefix := ""
	base := &url.URL{
		Scheme: scheme,
		Host:   addr,
		Path:   path.Join("/", prefix),
	}
	fmt.Println(base.String())
```
This is ☝️ more or less current implementation of parsing query URL which results in following output: `http://localhost:80%2Fthanos/`

I can prepare PR with fix.

**Comment by bwplotka** [comment]
Valid, help wanted, whoever has time (: Thanks for report! 

cc @simonpasquier @pgier maybe?

**Comment by bwplotka** [comment]
> I can prepare PR with fix.

Just noticed. Yes please @tobiaszheller fix would be nice

**Comment by tobiaszheller** [comment]
@bwplotka I have take a closer looks and it seems that it will require bigger changes: https://github.com/thanos-io/thanos/blob/5cb3c8758f07fa65ad6a0e97ea69732b14136adb/pkg/http/http.go#L133-L144
EndpointsConfig component expects slice of static addresses but only single PathPrefix.

I am not sure if I can modify that component without break compatibility. I saw that it also used in unmarshaling from config file, right?

**Comment by simonpasquier** [comment]
what about changing this part of the code and create one `query.Config` instance per `queryAddrs` item?

https://github.com/thanos-io/thanos/blob/2d7b214376d5ff2c1b322cecc9b96ed1127dddd7/cmd/thanos/rule.go#L298-L320

Something like:

```go
 for _, addr := range queryAddrs { 
 	if addr == "" { 
 		return errors.New("static querier address cannot be empty") 
 	} 
        // TODO: parse addr to extract path.
	queryCfg = append(queryCfg,
		query.Config{
			EndpointsConfig: http_util.EndpointsConfig{
				Scheme:          "http",
				StaticAddresses: []string{addr},
				PathPrefix:   path,
			},
		},
	)
 }

 var fileSDConfigs []http_util.FileSDConfig 
 if len(querySDFiles) > 0 { 
 	fileSDConfigs = append(fileSDConfigs, http_util.FileSDConfig{ 
 		Files:           querySDFiles, 
 		RefreshInterval: model.Duration(querySDInterval), 
 	})
	queryCfg = append(queryCfg,
		query.Config{
			EndpointsConfig: http_util.EndpointsConfig{
				Scheme:          "http",
				FileSDConfigs:   fileSDConfigs,
			},
		},
	)
 }
```

**Comment by bwplotka** [comment]
Thanks @simonpasquier for helping, I think I agree with Simon on this. (:

**Comment by bwplotka** [comment]
Fixed by https://github.com/thanos-io/thanos/pull/2288
