### ISSUE TITLE
query: old meta tags / external prometheus label

### ISSUE THREAD

**Issue by Gnoale** [thanos-io/thanos#2302]
**Thanos, Prometheus and Golang version used**:
thanos, version 0.11.0
go1.13.6
prometheus, version 2.6.0

**Object Storage Provider**:
S3

**What happened**:

I see a lot of these warning `No StoreAPIs matched for this query` from the query component, I want to get rid of this. I searched a bit in the codebase but I am not very familiar with Go.
I want to make sure these logs doesn't reflect some bad behaviour because I am having performance issues at the moment with the storage backend, I'd rather like not to add up some disturbing message to the situation, and make sure I can ignore it at least.
 
```
Mar 23 10:52:52 prometheus-3.kayrros thanos[77136]: level=warn ts=2020-03-23T10:52:52.481698523Z caller=proxy.go:293 err="No StoreAPIs matched for this query" stores="store Addr: 10.100.6.42:10901 LabelSets: [name:\"replica\" value:\"prometheus-3\" ] Mint: 1584849600000 Maxt: 9223372036854775807 queried;store Addr: 10.100.6.41:10901 LabelSets: [name:\"replica\" value:\"prometheus-2\" ] Mint: 1584849600000 Maxt: 9223372036854775807 queried;store Addr: 10.100.6.43:19090 LabelSets: [name:\"monitor\" value:\"codelab-monitor\" ][name:\"replica\" value:\"prometheus-2\" ][name:\"replica\" value:\"prometheus-3\" ] Mint: 1583831785464 Maxt: 1584950400000 queried"
``` 
I am using the same S3 bucket I was using for testing purpose at the beginning, with a test Prometheus setup with the following parameters
```
  external_labels:
    monitor: 'codelab-monitor'
```
This testing setup isn't used anymore and I wiped completely the bucket at some point, so I don't know how to get rid of it.

**Now** my configuration looks like this
```
  external_labels:
    replica: prometheus-2
```

**Comment by daixiang0** [comment]
Hi, the `external_labels` should be same, in your case, `prometheus-2` is not same as `prometheus-3`, so no data can be fetched. Hope it helps.

**Comment by Gnoale** [comment]
Hi, that's on purpose because the 2 prometheus server are replicas, I use the `--query.replica-label=replica`option in query.

**Comment by Gnoale** [comment]
btw I understand they should **not** be the same even without the replicas settings https://github.com/thanos-io/thanos/blob/master/pkg/query/storeset.go
```
// All producers should have unique external labels. While this does not check only StoreAPIs connected to
// this querier this allows to notify early user about misconfiguration. Warn only. This is also detectable from metric.
```

**Comment by Gnoale** [comment]
The tags are written in metadata json files by the sidecar component I think.
I worked around my issue by using `--store.response-timeout=2s` option on the query component.
No more timeout but eventually, the metrics are not all retrieved. This is not a Thanos issue, sorry for the noise.
