### ISSUE TITLE
query: Inconsistent "thanos_status" metric naming

### ISSUE THREAD

**Issue by MacroPower** [thanos-io/thanos#2315]
**Thanos, Prometheus and Golang version used**:

Thanos: 0.11
Promethus: 2.16
Golang: 1.13.6

**What happened**:

I was exploring some of the internal Thanos metrics, and noticed some inconsistencies with the query component.

Each component has a `thanos_status` metric, except query, where it is called `status`.

Results from `http://<query>/metrics`:
```
# HELP status Represents status (0 indicates success, 1 indicates failure) of the component.
# TYPE status gauge
status{check="healthy",component="query"} 1
status{check="ready",component="query"} 1
```

Results from `http://<compact/bucket/sidecar/store>/metrics`:
```
# HELP thanos_status Represents status (0 indicates success, 1 indicates failure) of the component.
# TYPE thanos_status gauge
thanos_status{check="healthy",component="sidecar"} 1
thanos_status{check="ready",component="sidecar"} 1
```

**What you expected to happen**:

Metric naming should be consistent across all components.

**Comment by MacroPower** [comment]
> 0 indicates success, 1 indicates failure

Additionally, this #HELP is the inverse of what it should be.

**Comment by jojohappy** [comment]
Hi, sorry for the inconsistent metrics, we will fix soon.

> > 0 indicates success, 1 indicates failure
> 
> Additionally, this #HELP is the inverse of what it should be.
This HELP message has been changed in this PR #2216 .
