### ISSUE TITLE
docs: Document Compactions better

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2320]
AC:
* It's here in https://thanos.io/components/compact.md/ that compaction are required and what their purpose. 
* The difference between downsampling and compactions is explained.

This is to avoid confusion like this: https://cloud-native.slack.com/archives/CK5RSSC10/p1585128421013300

Help wanted! :hugs:

**Comment by imskr** [comment]
Hi @bwplotka I would like to work on this!

**Comment by GiedriusS** [comment]
> Hi @bwplotka I would like to work on this!

Feel free to open up a PR which explains this :)

**Comment by shivaylamba** [comment]
Please open this

**Comment by prondubuisi** [comment]
> > Hi @bwplotka I would like to work on this!
> 
> Feel free to open up a PR which explains this :)

Hello @GiedriusS @bwplotka gone through the links on compactment docs and the discussion on slack, what extra information needs to be added to better document Compactions

**Comment by soniasingla** [comment]
hey @prondubuisi as per this comment : https://github.com/thanos-io/thanos/issues/2320#issue-587572004
Explanation about why compaction are required and the difference between downsampling and compactions. Feel free to suggest if you have something in mind :)

**Comment by faris789** [comment]
Would like to hear more about compaction vs downsampling. More particularly about their differences.

We were test running our thanos-compactor with downsampling disabled, we could see that the S3 blocks are getting merged. With that observation, I think compaction merges blocks in S3 bucket even when you have the downsampling disabled. By doing that I assume it would reduce calls from store to s3 and improve performance.
Correct me if I am wrong.

**Comment by kakkoyun** [comment]
Still valid and help wanted!
