### ISSUE TITLE
store: Consider fetching only requested aggregations from S3 chunks.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2321]
@d-ulyanov 

>  Thanos Store loads much more data from S3 than returns to Query because it loads full chunks and after that, if the chunk is in Thanos encoding - it will read only certain aggregates. We can split such queries into multiple: a) read few bytes to understand the encoding b) read only byte ranges with certain data 

This is indeed true. We should explore how we can fetch only aggregations and IF it's really worth doing as everything there is tightly compressed.

**Comment by d-ulyanov** [comment]
It could be definitely great, especially for huge queries.
We tested different queries and what we see is that Store can read 3Gb from S3, but really we need just 500Mb of this useful payload

**Comment by mkabischev** [comment]
I think that it has to be enabled only for chunks greater than some size. If chunk size is 10-20mb it's ok to download it in one query and then fetch aggregation for it. But for huge chunks it would be great.

We hacked small utility that shows query stats. There is some real example:
```
matchers:                [{EQ mode system} {EQ __name__ node_cpu_seconds_total}]
aggregates:              [COUNTER]
max resolution window:   12000
min time:                1584948180000 ( 2020-03-23T07:23:00Z )
max time:                1584959040000 ( 2020-03-23T10:24:00Z )
query range:             10860s
+-----------------------------------------+---------+-----------+------------+------------+
|                  STORE                  |  READ   |   SENT    |  DURATION  | FIRST SENT |
+-----------------------------------------+---------+-----------+------------+------------+
| thanos-store-hw                         | 2.2 GiB | 114.0 MiB | 22.038991s | 21.336815s |
+-----------------------------------------+---------+-----------+------------+------------+




matchers:                [{EQ __name__ node_cpu_seconds_total}]
aggregates:              [COUNT]
max resolution window:   12000
min time:                1584947940000 ( 2020-03-23T07:19:00Z )
max time:                1584959040000 ( 2020-03-23T10:24:00Z )
query range:             11100s
+-----------------------------------------+---------+-----------+------------+------------+
|                  STORE                  |  READ   |   SENT    |  DURATION  | FIRST SENT |
+-----------------------------------------+---------+-----------+------------+------------+
| thanos-store-hw                         | 2.3 GiB | 556.4 MiB | 30.701281s | 24.364588s |
+-----------------------------------------+---------+-----------+------------+------------+

```

For first subquery it uses only 5% of fetched data and it's very sad.

**Comment by GiedriusS** [comment]
> I think that it has to be enabled only for chunks greater than some size. If chunk size is 10-20mb it's ok to download it in one query and then fetch aggregation for it. But for huge chunks it would be great.

I would guess that this is what we ought to do.

> 
> We hacked small utility that shows query stats. There is some real example:
> 
> ```
> matchers:                [{EQ mode system} {EQ __name__ node_cpu_seconds_total}]
> aggregates:              [COUNTER]
> max resolution window:   12000
> min time:                1584948180000 ( 2020-03-23T07:23:00Z )
> max time:                1584959040000 ( 2020-03-23T10:24:00Z )
> query range:             10860s
> +-----------------------------------------+---------+-----------+------------+------------+
> |                  STORE                  |  READ   |   SENT    |  DURATION  | FIRST SENT |
> +-----------------------------------------+---------+-----------+------------+------------+
> | thanos-store-hw                         | 2.2 GiB | 114.0 MiB | 22.038991s | 21.336815s |
> +-----------------------------------------+---------+-----------+------------+------------+
> 
> 
> 
> 
> matchers:                [{EQ __name__ node_cpu_seconds_total}]
> aggregates:              [COUNT]
> max resolution window:   12000
> min time:                1584947940000 ( 2020-03-23T07:19:00Z )
> max time:                1584959040000 ( 2020-03-23T10:24:00Z )
> query range:             11100s
> +-----------------------------------------+---------+-----------+------------+------------+
> |                  STORE                  |  READ   |   SENT    |  DURATION  | FIRST SENT |
> +-----------------------------------------+---------+-----------+------------+------------+
> | thanos-store-hw                         | 2.3 GiB | 556.4 MiB | 30.701281s | 24.364588s |
> +-----------------------------------------+---------+-----------+------------+------------+
> ```
> 
> For first subquery it uses only 5% of fetched data and it's very sad.

Where could we get the source code of this? It would also be interesting to do some analysis from the point of view of Amazon's S3 pricing: there each request costs some very small amount of money. Could we add another column which shows how __many__ requests were made?

**Comment by bwplotka** [comment]
Can we have this hack utility upstreamed? Sound extremely useful (:

**Comment by d-ulyanov** [comment]
This tool is based on logs parsed from the trace, so first, we need to make PR with enriched traces then.
Currently, we added spans to Thanos v0.10 (we decided to stay on v0.10 because of performance degradation in v0.11, you know). So, maybe can publish it a bit later :)

@bwplotka this tool could be something separate or it could be a part of Thanos, what do you think?

**Comment by mkabischev** [comment]
> Can we have this hack utility upstreamed? Sound extremely useful (:

Yeah, sure. We started with enriching traces to understand what's happening in query/stores. But it became too complicated to analyze such traces (we need to expand a lot of spans/logs).

And this tools fetches trace from jaeger and converts it into another presentation. So why it's "hack utility" :)

**Comment by GiedriusS** [comment]
Any updates on this? :eye: @d-ulyanov

**Comment by d-ulyanov** [comment]
no updates currently, right now we're working on another issue. I think we'll continue investigations here in the second half of May.

**Comment by GiedriusS** [comment]
I think it would still be worth investigating this further.

**Comment by d-ulyanov** [comment]
still actual

**Comment by d-ulyanov** [comment]
still actual

**Comment by d-ulyanov** [comment]
reopen it, please

**Comment by d-ulyanov** [comment]
@krya-kryak is working on this issue

**Comment by bwplotka** [comment]
Any update 🤗 @d-ulyanov ?

Can we help?

**Comment by d-ulyanov** [comment]
hey @bwplotka, 
we moved to another issue now (problem with zooming into downsampled data), but we'll come back to this one definitely

**Comment by krya-kryak** [comment]
I did experiment on this, and it proved to be less than satisfactory.
The key issue is twofold:
* S3 API lacks support for multipart ranges, forcing clients to make new request for each part
* Thanos subchunks are interleaved, with each part no longer than 3200 bytes (and real life subchunks tend to be around a kilobyte). Moreover, there is no way to know for sure how many bytes would there be between two aggr_SUM subchunks (or another with aggr_COUNT being an exception)

With gap-based partitioner disabled (which is a must here) even a relatively simple query leads to hundreds of s3 requests, which produces dismal performance.

I honestly think it's not worth it.

**Comment by d-ulyanov** [comment]
@krya-kryak thank you for the research and detailed explanation. Is there any other idea on how to optimize reads from S3?
