### ISSUE TITLE
e2e: Add compaction, downsampling tests to `TestCompactWithStoreGateway`

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2324]
Solve todos introduced in https://github.com/thanos-io/thanos/pull/2313

**Comment by bwplotka** [comment]
Very needed1

**Comment by bwplotka** [comment]
cc @Harshitha1234 :hugs:

**Comment by Harshitha1234** [comment]
Still working on this! :)

**Comment by kakkoyun** [comment]
Reopened since @Harshitha1234 still working on this.

**Comment by bwplotka** [comment]
TODOS are here: https://github.com/thanos-io/thanos/blob/52595335a8bfcf0712f9cff0b5fa27a4a9568258/test/e2e/compact_test.go#L80
