### ISSUE TITLE
thanos store: No store matched for this query

### ISSUE THREAD

**Issue by gagado** [thanos-io/thanos#2326]
thanos version: 0.6.0

thanos query web: No store matched for this query

thanos sotre log：
read meta.json: invalid character '\\u008b' looking for beginning of value"
level=warn ts=2020-03-26T09:28:36.522935346Z caller=bucket.go:325 msg="error parsing block range" block=01E2Z1FVA38NDR15DY9FKT6YR1 err="read meta.json: invalid character 'ø' looking for beginning of value"
level=warn ts=2020-03-26T09:28:36.522989196Z caller=bucket.go:325 msg="error parsing block range" block=01E2ZF76DR26D6BAXY0PNQE8ER err="read meta.json: invalid character '<' looking for beginning of value"
level=warn ts=2020-03-26T09:28:36.523013321Z caller=bucket.go:325 msg="error parsing block range" block=01E2ZF79XSFX6KHBVPFJ6DV625 err="read meta.json: invalid character 'ø' looking for beginning of value"
level=warn ts=2020-03-26T09:28:36.523063309Z caller=bucket.go:325 msg="error parsing block range" block=01E2ZP318B5P2YGERASTEQZPYJ err="read meta.json: invalid character '{' after object key:value pair"

receive series from Addr: thanos-store1.srv.daling.com:10905 LabelSets: Mint: 1583668800000 Maxt: 1585209600000: rpc error: code = Aborted desc = fetch series for block 01E321KYDHEQN9KRXFV6FBYFG0: add chunk preload: reference sequence 0 out of rangereceive series from Addr: thanos-store2.srv.daling.com:10905 LabelSets: Mint: 1583668800000 Maxt: 1585209600000: rpc error: code = Aborted desc = fetch series for block 01E321KYDHEQN9KRXFV6FBYFG0: add chunk preload: reference sequence 0 out of range

help me. thanks.

**Comment by jojohappy** [comment]
HI, it seems that the block files in object store are malformed. Could you provide the Object Store provider?

**Comment by gagado** [comment]
I`m sorry so later. 
the Object Store provider is minio.
