### ISSUE TITLE
Stale bot marks closed PRs/Issues as "stale" 🤔

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2334]
Example: https://github.com/thanos-io/thanos/issues/1646#issuecomment-541683084

I think this is some bug.

**Comment by prmsrswt** [comment]
There's an [open issue about it](https://github.com/probot/stale/issues/263) on stale bot's repo. They think the GitHub API sometimes acts flaky, which causes this.

**Comment by bwplotka** [comment]
Lol
