### ISSUE TITLE
thanos.io: Make menu section collapsible.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2335]
It would be awesome if we could make our menu more compact. It's now very long due to more & more items. Worth to allow some dynamic behavior?

I mean this:

![image](https://user-images.githubusercontent.com/6950331/77825291-2c932180-7100-11ea-989a-44a325de823b.png)

Another cool improvement for @prmsrswt if you have time :beers: I know you applied for GSoC, so don't worry, for GSoC the UI is 10000% more exciting as it is about Thanos microservices UIs :hugs:

**Comment by prmsrswt** [comment]
This would be great. I think it shouldn't take much time to implement. And yeah, I have more than enough time now due to the current situation for better or worse.
