### ISSUE TITLE
compactor: Consider upper bound of block size

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2340]
Hi :wave: 

With vertical/offline deduplication we have a risk of oversized blocks. In the current design, this comes with the tradeoff of more difficult debug as well as at some point slower lookup. 

From my experience chunk file size does not matter, but the index size matter, so we might want to split blocks at a certain size. Question is.. what size (: (most likely configurable). Thoughts? @brancz @SuperQ @pracucci @pstibrany

**Comment by pracucci** [comment]
I'm probably missing some context. Is your plan to just split the result of compaction to multiple blocks or to shard blocks before running the compaction? I guess the first one, but I would prefer to avoid any misunderstanding from my side.

**Comment by bwplotka** [comment]
I think actually something between. Do that during compaction (:

**Comment by bwplotka** [comment]
I already exploring iterator interface on Prometheus side which could help with this

**Comment by pracucci** [comment]
This will leave still open the vertical scalability limit of a compactor, until blocks can't be sharded. What I mean is, if compacting blocks for the range X takes more time than X you have a scalability limit. Wouldn't blocks sharding in the compactor solve both?

**Comment by bwplotka** [comment]
Still relevant.

**Comment by ipstatic** [comment]
I think this is still relevant.

**Comment by SuperQ** [comment]
Yes, I just had a 480GB compaction, which means I need 1T of local disk to handle these events. It would be nice to be able to set an upper bound on TSDB block sizes.

**Comment by squat** [comment]
still relevant

**Comment by bwplotka** [comment]
@Biswajitghosh98 is on it (:
