### ISSUE TITLE
DNS store discovery with AWS ELB

### ISSUE THREAD

**Issue by omerlh** [thanos-io/thanos#2341]
Thanos querier support store discovery with DNS, which make it easier to dynamically add/remove stores without deploy.
The only issue is when the store running behind an ELB (the simple way to expose a service between clusters). ELB dns resolves to 3 IP addresses, so when using DNS discovery, each store appears 3 times - instead of once, which is very confusing.
It’s not purely a bug - but maybe if we can do only level of DNS resolving - so the discovery will stop at the ELB dns address, and not break it down to IPs. This is the behavior when adding the addresses manually...

**Comment by GiedriusS** [comment]
> Thanos querier support store discovery with DNS, which make it easier to dynamically add/remove stores without deploy.
> The only issue is when the store running behind an ELB (the simple way to expose a service between clusters). ELB dns resolves to 3 IP addresses, so when using DNS discovery, each store appears 3 times - instead of once, which is very confusing.
> It’s not purely a bug - but maybe if we can do only level of DNS resolving - so the discovery will stop at the ELB dns address, and not break it down to IPs. This is the behavior when adding the addresses manually...

I haven't used that before and maybe someone else hasn't as well so could you please explain this with example A records and so on? That would be clearer for other people who will read this in the future.

**Comment by omerlh** [comment]
Sure. ELB create A record pointing to 3 IPs behind it. So if I’m using DNS discovery I have:

SRV record -> A record (ELB per cluster) -> 3 IP addresses. 

So when using discovery, I actually see 3 stores instead of one. When suppling the store DNS manually (no discovery - just the A record), I get one store per cluster - although it is resolved to multiple IPs.

**Comment by bwplotka** [comment]
What exactly `--store` flag entry do you provide to querier? (:

**Comment by omerlh** [comment]
Let's say the SRV record is thanos.mycorporate.com, I used the following flag:
```
--store=dnssrv+thanos.mycorportate.com
```

**Comment by kuberkaul** [comment]
you should be able to use the ELB entry straight up without dnssrv and the classic lb will forward the query request to the underlying store. 

`--store=elbdns:10901`

**Comment by omerlh** [comment]
that's what we're doing right now, but this means that each time we're adding a new cluster we also need to add a new store and re-deploy thanos. This is why we wanted to use DNS discovery in the first place...
