### ISSUE TITLE
compact: Allows backing up blocks instead of straight removing to another bucket.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2344]
AC:
* Compactor is moving blocks to separate object storage instead of removing them during all( ??) block rewrites.

Something to consider which came up in the discussion with our users. (:

**Comment by GiedriusS** [comment]
> AC:
> 
>     * Compactor is moving blocks to separate object storage instead of removing them during all block rewrites.
> 
> 
> Something to consider which came up in the discussion with our users. (:

I guess it would be extra nice to have this when we will have series deletion. :+1:

**Comment by bwplotka** [comment]
Definitely. That's the idea, since the storing itself is cheap

**Comment by bwplotka** [comment]
This needs further discussion / design as per https://github.com/thanos-io/thanos/pull/2541#issuecomment-622447561

It's silly to just backup compaction blocks as not data is removed. However it might make sense to back up removals / vertical complications (:

**Comment by bwplotka** [comment]
As per discussion on our public meeting, we would aim for back up mode, where we back up ALL operations that can lead to data removal, which is:
* Vertical / offline dedup  /  per series retention compaction (not normal one!)
* Retention deletion
* Delete series someday

cc @hitha1234 @darshanime

**Comment by bwplotka** [comment]
still valid

**Comment by jujugrrr** [comment]
hi @bwplotka , not sure it's the best issue to ask the question, but I couldn't find a recommended way to backup Thanos data. Will this issue allow to use the compactor to do this?

I've seen we can do `thanos bucket replicate` this as well, but is it not reliable because the compactor might corrupt data while it's replicating?

**Comment by jujugrrr** [comment]
> hi @bwplotka , not sure it's the best issue to ask the question, but I couldn't find a recommended way to backup Thanos data(for disaster recovery). Will this issue allow to use the compactor to do this?
> 
> I've seen we can do `thanos bucket replicate` this as well, but is it not reliable because the compactor might corrupt data while it's replicating?

Would S3 bucket replication + `thanos bucket verify --repair` be a better approach. The replication won't delete files in the destination bucket  when deleted from the source bucket, but the verify might fix the overlap/duplicate created by the compactor from the source bucket?
