### ISSUE TITLE
How to Mitigate two hour in-memory prometheus data during restarts/failover/upgrade scenarios

### ISSUE THREAD

**Issue by dinesh4747** [thanos-io/thanos#2345]
Hi Team,

**Current setup:**

I am using using prometheus setup running along with thanos for extended storage to accomodate 2 months of data for longer persistence

- 2 Instances of prometheus (0 replica/1 replica) and both this instances enabled with thanos-sidecar
- thanos-sidecar subsequently writes data to GCS bucket for extended long term storage
- thanos querier connected to two instances and reading data via store gateway

Challenge/Issue in current setup:

**Despite of having long term storage we would still be losing potential data of real time/latest/current 2 hours.(storage.tsdb.max-block-duration=2h) - How do we handle the below cases?**

1. Backup/snapshot for older instance during upgrade will be an option (But it cannot be seamless and will fail to perform fault tolerance and post-facto)
2. 2 HA Instances of prometheus to handle DR scenarios but if both the instances fail then it will lose all 2 hours data with extreme case

**Question:**

Is there any efficient mechanism instilled within prometheus to save 2 hours data during restarts/crash recovery/upgrade? what measures/guidelines should we follow to minimize the data loss with less disruption

**Comment by bwplotka** [comment]
The persistent disk is the solution everyone uses. Available for most of the cloud providers. (:  Have you tried this?

**Comment by dinesh4747** [comment]
@bwplotka Thanks a lot for quick and timely response, Highly appreciated!!!

Yes I am leveraging persistent disk attached to my VMs in GCP but restarts or upgrade didn't help me picking up from last snapshot 

Do we need to follow or pass any additional parameters to get that right? do you have docs or issues related to this would ideally help a lot

**Comment by bwplotka** [comment]
> VMs in GCP but restarts or upgrade didn't help me picking up from last snapshot

What do you mean? Prometheus if ran on from the same directory as previously will get back what it can.

**Comment by yeya24** [comment]
@dinesh4747 Hi, since we already had an offline discussion about this problem on slack. Do you have any further questions about this? Otherwise, I think we can close this issue.

**Comment by GiedriusS** [comment]
> @dinesh4747 Hi, since we already had an offline discussion about this problem on slack. Do you have any further questions about this? Otherwise, I think we can close this issue.

I will close it, then :P Let us know if you have any more problems.
