### ISSUE TITLE
compact: Add backlog deduplication process

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2348]
Currently offline dedup attack on compaction only. We might want to triger it for old blocks in spare time (:

**Comment by bwplotka** [comment]
cc @kakkoyun @metalmatze

**Comment by yashrsharma44** [comment]
Hey @kakkoyun @metalmatze I was looking to solve this issue. Can you provide some details about it?
Thanks!

**Comment by bwplotka** [comment]
Still needed

**Comment by Biswajitghosh98** [comment]
@yashrsharma44 any leads on the topic ?

**Comment by bwplotka** [comment]
I think this is nice to have, but still we need offline deduplication to work properly. The blocker for true offline deduplication is the efficient algorithm that will accurately detect which replica to choose from multiple Prometheus-ues (or other sources) running in HA group.

Read more about this here: https://thanos.io/tip/components/compact.md/#vertical-compaction-use-cases

**Comment by bwplotka** [comment]
I don't think it's a good first issue @Biswajitghosh98  (:

**Comment by yeya24** [comment]
> Currently offline dedup attack on compaction only. We might want to triger it for old blocks in spare time (:

Can you add more details to the description? What's the action item for this issue? @bwplotka

**Comment by yeya24** [comment]
> Looks like this can be done via the rewrite tool, but with the penalty based deduplication?

This option seems feasible. We can support multiple blocks at once for bucket rewrite tool and enable penalty deduplication.

Another option is to have a separate command to do one-off compaction & deduplication for all blocks in the bucket?

**Comment by bwplotka** [comment]
> Looks like this can be done via the rewrite tool, but with the penalty based deduplication?

Yes, I like this idea.

> Another option is to have a separate command to do one-off compaction & deduplication for all blocks in the bucket?

Separate tool (as is rewrite for one-off) sounds like a better option 🤗
