### ISSUE TITLE
thanos store 0.11.0 panic

### ISSUE THREAD

**Issue by R4scal** [thanos-io/thanos#2355]
**Thanos, Prometheus version used**: 0.11.0, 2.16.0

**Object Storage Provider**: MinIO

**What happened**: 
```
panic: runtime error: slice bounds out of range [:76660] with capacity 512

goroutine 7631630 [running]:
github.com/thanos-io/thanos/pkg/store.(*bucketIndexReader).fetchPostings.func3(0xc00d86df68, 0x0)
	/go/src/github.com/thanos-io/thanos/pkg/store/bucket.go:1553 +0x6e3
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc03a6a2090, 0xc00037a070)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66
```

**What you expected to happen**: No panics

**How to reproduce it (as minimally and precisely as possible)**: data request for 90 days from grafana

**Thanos store options**:
```
store --http-address=0.0.0.0:10101 --grpc-address=0.0.0.0:10201 --data-dir=/data --objstore.config-file=/config/bucket_config.yml --selector.relabel-config-file=/config/store-relabel.yml --experimental.enable-index-header --index-cache-size=1000MB --chunk-pool-size=4GB --log.format=json
```

**Comment by bwplotka** [comment]
To me it looks like minio gave us  less data then we requested for :/ 

We might want to add some safeguards for this.

**Comment by bwplotka** [comment]
But anyway, it will fail the request, so we might need to look on minio what's wrong. Any logs on minio?

**Comment by R4scal** [comment]
No errors. I'm started  `bucket verify`, but size is 7Tb, for now it's still running.
We have metrics for 1 year, but I don't see any metrics on query after December 26. Maybe it's related.

**Comment by R4scal** [comment]
`bucket verify` finished without errors

**Comment by R4scal** [comment]
Any way to check the consistency of data chunks, not just indexes?

**Comment by bwplotka** [comment]
Yes, go through them and check checksums:
https://github.com/prometheus/prometheus/blob/master/tsdb/docs/format/chunks.md

**Comment by bwplotka** [comment]
I assume it  was just once, or every time you query this data? (:

**Comment by R4scal** [comment]
It crashes randomly, for last 3 days no crashes
