### ISSUE TITLE
query: /graph unusable on large __name__ set due to autocomplete

### ISSUE THREAD

**Issue by clhain** [thanos-io/thanos#2361]
thanos version: 0.11.0

We run a query instance that has a very large set of unique metric names (we're working to reduce them). Attempting to use the GUI at /graph causes the browser to go unresponsive for a long time as it grabs the list of values (a few seconds) and then renders the dropdown (a few dozen seconds). During that time the window is unresponsive. 

Grafana helpfully disables the autocomplete feature on large sets, is it possible to do something similar here?

**Comment by GiedriusS** [comment]
There is this: https://github.com/thanos-io/thanos/pull/2150. Just need someone to follow up and rebase on `master`.

**Comment by bwplotka** [comment]
Still a problem.

**Comment by bwplotka** [comment]
And something to tackle on React UI

cc @prmsrswt

**Comment by bwplotka** [comment]
still to fix on React UI potentially

**Comment by prmsrswt** [comment]
@clhain can you check if it's still a problem with the new React UI? We limit the dom rendering to 100 items at max, so it's shouldn't be a problem now.

https://github.com/thanos-io/thanos/blob/master/pkg/ui/react-app/src/pages/graph/ExpressionInput.tsx#L89

**Comment by clhain** [comment]
Hey, sorry I missed this update. I had a look at it in .13 and it's still unusable. Could be the match function running slowly as opposed to the actual rendering? Let me know if there's something else that would help debug, and thanks.

**Comment by GiedriusS** [comment]
If it's still laggy then you must have so many metrics. `label_names` and `label_values` APIs now support time limits so maybe that could be leveraged in the future? :thinking:

**Comment by ipstatic** [comment]
This is still an issue, even with thew new interface.

**Comment by jameskranz** [comment]
This is still an issue, although https://github.com/thanos-io/thanos/pull/3381 helps mitigate the issue. It makes thanos usable with huge metric sets, but means autocomplete is unavailable.

**Comment by CNG** [comment]
Still an issue.

**Comment by Nexucis** [comment]
I tested with ~150k of metrics. Works well, it's just a bit slow due to the network mainly. It would maybe need a way to warm the cache embedded in the PromQL editor

**Comment by yeya24** [comment]
Looks like we can close this issue if it works well with the new editor.

**Comment by kalebris** [comment]
This still seems to be a problem. It seems to be working much better on Firefox, but on Chrome we are still seeing huge delays due to autocomplete. After typing in 1 character the ui freezes up for a good while (30 seconds or so) before the options appear.

**Comment by B0go** [comment]
I am also seeing this on both Safari and Chrome, the autocomplete affects the expression writing capabilities and makes the experience very sluggish
