### ISSUE TITLE
thanos query error (Error executing query: multiple matches for labels: grouping labels must ensure unique matches)

### ISSUE THREAD

**Issue by lixwlixw** [thanos-io/thanos#2363]
thanos version v1.10.0
prometheus version 2.17.1   

promsql: sum(rate(container_cpu_usage_seconds_total{name=\~"^k8s_.*",image!=""}[5m]) * on (node) group_left() kube_node_labels{label_cluster=\~"test",label_region=~"prod"})   

Thanos query results : Error executing query: multiple matches for labels: grouping labels must ensure unique matches

prometheus query results:  {} | 7.005033120204937 (In line with normal expectations)

**Comment by jojohappy** [comment]
Hi, thanks for your reporting. But I can't reproduce in my env. Are the series returned by metrics `kube_node_labels{label_cluster=~"test",label_region=~"prod"}` and `rate(container_cpu_usage_seconds_total{name=~"^k8s_.*",image!=""}[5m])` as same as between thanos and your origin prometheus?

**Comment by lixwlixw** [comment]
yes

**Comment by lixwlixw** [comment]
kube_node_labels{label_cluster=~"test",label_region=~"prod"}

**Comment by lixwlixw** [comment]
kube_node_labels{label_cluster=~"test",label_region=\~"prod"}    the result is the same.        
sum(rate(container_cpu_usage_seconds_total{name=\~"^k8s_.*",image!=""}[5m]))  the result is the same.          
rate(container_cpu_usage_seconds_total{name=\~"^k8s_.*",image!=""}[5m])  too many(Warning! Fetched 14212 series, but displaying only first 10000.   )

**Comment by jojohappy** [comment]
Could you check the series returned from `kube_node_labels`, have multiple series with the same value of label `node`? If yes, you should aggregate them into one series group by label `node`.

**Comment by lixwlixw** [comment]
not at all

**Comment by lixwlixw** [comment]
not at all.
kube_node_labels{label_cluster=~"test",label_region=~"prod"}
prometheus (Total time series: 74) 
thanos (Total time series: 74)
