### ISSUE TITLE
Thanos does not offer a way to understand what queries are running and how long.

### ISSUE THREAD

**Issue by miclando** [thanos-io/thanos#2380]
Today in Prometheus you can enable the query log to get an understanding of what queries are running and how long they are taking.

how ever because Thanos side car uses remote read the queries executed are not logged.

how do you feel about allowing similar logging on the querier and the side cars?

**Comment by yeya24** [comment]
Thanos already supports different tracing backends https://github.com/thanos-io/thanos/blob/master/docs/tracing.md , you can get what queries are running and how long through the tracing system's UI

There is also an issue about better logging & tracing https://github.com/thanos-io/thanos/issues/1706

**Comment by bwplotka** [comment]
Duplicate of https://github.com/thanos-io/thanos/issues/1706
