### ISSUE TITLE
limiting the amount of data Thanos can query from prometheus 

### ISSUE THREAD

**Issue by miclando** [thanos-io/thanos#2381]
**Thanos, Prometheus version used:** 0.11.0, 2.16.0

**What happened:**

we believe that queries coming from the querier to the side car are causing a memory increase on the machine that fails the Prometheus server.

**What you expected to happen:** 
we expect the option to limit the size of the queries executed.

**How to reproduce it (as minimally and precisely as possible):** the issue is connected to our topology and data size.

**Querier side:**
based on Thanos documentation i do not see an option to limit the amount of data point retrieved only to limit the time out of the query excauted, which as far as i understand will not help as the connection will be timed out but the query will continue running.

**Side car side:**
no help full configuration is available.

**Prometheus side:**
the side car uses remote read to retrieve the data points from Prometheus. and Prometheus does offer a configuration to limit this using --storage.remote.read-sample-limit how ever it comes with a note This limit is ignored for streamed response types. and from what i read that is the way the side car reads data.

is there any other way to protect the system from such extreme large queries?

**Comment by miclando** [comment]
any sugestions?

**Comment by miclando** [comment]
after talking to @bwplotka there is no option to limit the amount of data taken from Prometheus by Thanos. the team is looking into the issue and there may be such an option in the future.

the only option that is currently available is limiting the query time out on the querier.
which will cancel a query when the time is exceeded.

**Comment by bwplotka** [comment]
Yes, as spoken offline the query timeout and --min-time option is the way to go here (:
