### ISSUE TITLE
Slow Query from SLB with Thanos Query to Thanos Sidecar and Thanos Store in VM

### ISSUE THREAD

**Issue by EusebiusAditya** [thanos-io/thanos#2387]
**Thanos, Prometheus and Golang version used**:
Thanos version = 0.11.0
Prometheus version = 2.16.0
Go Version = fo1.13.8

**Object Storage Provider**: S3

**What happened**:
We have very slow query time from our thanos query to our thanos sidecar and thanos store up to 30s - 1m, but whats weird is this only happens when our query is being used as a data source from grafana, when it's not being used by grafana, it queries normally (less than a second from both the sidecar and the thanos store) from our SLB. Even though when being used with grafana, there is no bottle neck in the cpu and memory usage in all of the thanos queries, thanos sidecar, and thanos store. 

Our current setup is we have an SLB which manages 5 thanos queries, which queries to 3 prometheus servers and a single thanos store.

grafana
|
SLB
| \ \
3 Thanos Query
| \ \ \
3 Thanos Sidecar + 1 Thanos Store

**What you expected to happen**:
Faster Query time when being used as a data source in grafana

**Anything else we need to know**:
We also have set up an autoscale for the thanos query, but due to the low usage, it hasnt been triggered yet

Any way is there anything I can do to improve this or optimise this ?

**Environment**:
- OS (e.g. from /etc/os-release): Ubuntu 18.04.4 LTS

**Comment by bwplotka** [comment]
Feel free to inspect network traffic between grafana and Thanos UI (: And catch what's wrong. Maybe Grafana dashboards are doing dozens on queries in same time?

**Comment by EusebiusAditya** [comment]
Yea we did, and well, our grafana have at least a thousand dashboard, so it is expected to receive thousands of queries at the same time, is there anywhere we can improve our set up?
