### ISSUE TITLE
visibility of upload_compacted progress

### ISSUE THREAD

**Issue by belm0** [thanos-io/thanos#2388]
We have a few months of compacted data to migrate to thanos storage.

I was hoping sidecar would have an HTTP UI with some stats, or at least some progress metrics.

I've only found this boolean:
```
# HELP thanos_shipper_upload_compacted_done If 1 it means shipper uploaded all compacted blocks from the filesystem.
# TYPE thanos_shipper_upload_compacted_done gauge
thanos_shipper_upload_compacted_done 0
```

Is there another way to monitor upload of compacted blocks?

**Comment by bwplotka** [comment]
Yes, this is just one-off jobs so it's not very well-instrumented maybe. Good point. No logs? Even on debug?

**Comment by bwplotka** [comment]
You can see progress by looking on Thanos Compactor UI in new Thanos release OR `thanos bucket web` (https://thanos.io/components/bucket.md/#web) from dev environment (:

**Comment by belm0** [comment]
We are just starting with Thanos and only have sidecar running, as recommended in the docs.

I haven't tried looking at debug logs.

It seems worth a progress metric on sidecar itself.

**Comment by bwplotka** [comment]
Still valid.
