### ISSUE TITLE
Delayed deletes: experience report

### ISSUE THREAD

**Issue by pstibrany** [thanos-io/thanos#2389]
This is more an experience report than an issue.

We have recently integrated Thanos (214ff4480e93) into Cortex 1.0, and deployed it to two clusters that use Thanos-based ("blocks") storage. This issue is a summary of our experience with latest "deleted delays" feature.

Cluster 1: this is a test cluster with ~50 tenants. We used 2 queriers, with 5 minutes blocks scan interval on the querier, max 2 tenants at once, and 5 parallel blocks scanned per tenant. After deploying updated Cortex with 48h deletion delay, and 24h ignore of deletion marks, number of storage operations from queriers grew considerably:

<img width="1075" alt="Screenshot 2020-04-07 at 10 29 59" src="https://user-images.githubusercontent.com/895919/78647353-c609c280-78ba-11ea-83d9-9649cbd52a53.png">

There are many new "get" operations due to fetching deletion marker, plus general growth of operations due to many more blocks being stored until they are deleted.

After updating delete delay options to use 12h delay (and 6h ignore), total number of stored blocks went down, which helped queriers to issue fewer operations. (Compactor deleted 3927 blocks in total, after it was restarted with updated settings).

<img width="1075" alt="Screenshot 2020-04-07 at 10 28 12" src="https://user-images.githubusercontent.com/895919/78647201-84791780-78ba-11ea-936a-5ee04f0eb95f.png">

Still nowhere to original numbers though.

Cluster 2: this cluster has single tenant, 10 queriers, 30s blocks scan interval on the queriers.

Similar to the first cluster, after deploying delayed deletion, number of operations went up:

<img width="1075" alt="Screenshot 2020-04-07 at 10 31 05" src="https://user-images.githubusercontent.com/895919/78647494-f6e9f780-78ba-11ea-83cb-476c5797624c.png">

To help with that, our first change was increase of the blocks scan interval by queriers to 5m... (we used 30s before to make sure that deleted blocks are discovered quickly. With delayed deletes, that's not required anymore).

<img width="1075" alt="Screenshot 2020-04-07 at 10 34 08" src="https://user-images.githubusercontent.com/895919/78647775-52b48080-78bb-11ea-92ce-a3d02a6ca547.png">

After that we have also decreased delete delay to 12h (and ignore for first 6h). This helped to remove ~360 blocks, and further drop ops/sec a little bit (to about ~12 ops/sec (without get_range).

<img width="1093" alt="Screenshot 2020-04-07 at 10 37 25" src="https://user-images.githubusercontent.com/895919/78648090-cce50500-78bb-11ea-907b-185ee48c424d.png">

-----

Is there a takeaway? I think there are some possible places where caching can be added – e.g. both positive and negative results for getting deletion marker, which currently isn't cached at all I believe, perhaps even shared cache between different meta fetchers across components might be a good idea (I can put together design proposal with some options).

**Comment by bwplotka** [comment]
That escalated quickly (:  Thanks for this. We can definitely cache deletion-mark as once found it likely never change.

**Comment by bwplotka** [comment]
This is fixes I suppose with metadata caching provided in 0.13.0-rc.01
