### ISSUE TITLE
ThanosRuleTSDBNotIngestingSamples firing without rules

### ISSUE THREAD

**Issue by brancz** [thanos-io/thanos#2391]
As mentioned in the code comment:

https://github.com/thanos-io/thanos/blob/1a2edf19475b854181e5abaa4b6f1c9caf2a1547/mixin/thanos/alerts/rule.libsonnet#L174-L175

This alert currently fires even if there are no rules loaded. We should ensure that it only fires if we are performing rule evaluations that should have written data.

@thanos-io/thanos-maintainers 

cc @lilic as she found this firing incorrectly in one of our clusters.

**Comment by brancz** [comment]
An easy metric we could add, although it wouldn't be 100% correct would be having a metric for the number of rule files and or rules loaded, so we can make the alert only fire if there is actually a rule in the first place, however, there could be recording rules that legitimately don't write any data, for example if they have a `> $threshold` filter.

**Comment by bwplotka** [comment]
Wow so actually it happened ;p

**Comment by brancz** [comment]
Poking around at the metrics that we have, I'm thinking that we should maybe change the alert definition all together, to instead of monitoring writing data, we observe rule evaluations. Something along the lines of:

```
sum without(strategy) (rate(prometheus_rule_evaluations_total{job="observatorium-thanos-rule"}[10m])) <= 0
```

Plus exposing the amount of rules loaded we can conditionally make this fire only if there are actually rules to be evaluated.
