### ISSUE TITLE
query: Force to get downsampled data in query parameter

### ISSUE THREAD

**Issue by hmlkao** [thanos-io/thanos#2399]
**Thanos, Prometheus and Golang version used**:
```
thanos, version 0.10.0 (branch: HEAD, revision: 698c7a922cd5dcaa53e305db5c2adb4e79d328ba)
  build user:       circleci@07a502f4439b
  build date:       20200113-14:49:31
  go version:       go1.13.1
```

**Configured Thanos Compact retention**
```
--retention.resolution-raw=12d
--retention.resolution-5m=30d
--retention.resolution-1h=18m
```

**What happened**:
We are using Thanos as Long Term Storage (>1 year) especially for wide range requests. The problem is that Grafana sends request to Thanos Query with `step` computed according to graph width.

**Example**:
When I choose range "Last 30 days", Grafana send `step=1200` (20m) and Thanos Query return raw data which doesn't cover the whole 30 days range and there is no way how to change it on datasource level.
Workaround is eg. add new variable to Grafana (eg. `$min_step`) and use it in Grafana in min_step but it require change in all dashboards.

**What you expected to happen**:
It would be great force to get compacted data from Thanos Query by query string param, eg. `source_resolution=5m` (similar to `max_source_resolution`). Then we would be able to configure in Grafana more datasources and force to get compacted data if needed.

**Comment by belm0** [comment]
> It would be great force to get compacted data from Thanos Query

I think you mean "downsampled" not "compacted"?

**Comment by hmlkao** [comment]
Yes, exactly. Sorry for confusing naming. Thanos Compact > compacted :)

**Comment by hmlkao** [comment]
I still thing this would be great feature.

**Comment by bwplotka** [comment]
Sorry we missed this one.

You can totally do that now, using `max_source_resolution` https://thanos.io/components/query.md/#auto-downsampling

**Comment by hmlkao** [comment]
This request is for different feature.

_Example_
If I set `max_source_resolution=5m`, I get raw OR downsampled data with 5m resolution based on `step`.
If I set `max_source_resolution=1h`, I get raw OR downsampled data with 5m resolution OR downsampled data with 1h resolution based on `step` (this is a little bit useless because it works exactly as `false` value).

But If I want to get ONLY downsampled data with 5m resolution I cannot do it any way now.

Thanos Query always return data of one kind (raw, 5m, 1h) so if it decide to return raw data (with retention 12d) for "Last 30 days", it will shows only last 12 days even if there are data with 5m resolution (with retention eg. 40d)...
So the request would be "query: Return data of more kinds" (then it would work `max_source_resolution` correctly), may be better solution...

**Comment by hmlkao** [comment]
@bwplotka Any update?

**Comment by bwplotka** [comment]
Hey, let's get back to this! (: 

> Thanos Query always return data of one kind (raw, 5m, 1h) so if it decide to return raw data (with retention 12d) for "Last 30 days", it will shows only last 12 days even if there are data with 5m resolution (with retention eg. 40d)...

Why you cannot specify step in a way that 5m data will be returned (OR raw if missing). I think we are missing rationales for this particular case. (:
