### ISSUE TITLE
Relabeling external labels in object store for Compact and Store

### ISSUE THREAD

**Issue by gburek-fastly** [thanos-io/thanos#2402]
Recently, we have added a new external label, `region` to our Prometheus configs, to let Thanos query over, say, a `us` or `emea` set of Prometheus nodes. This works well for queries against sidecars, but only new blocks uploaded to an object store have these new external labels. It also appears that Compact is no longer compacting across the label change boundary and is not able to downsample across it. 

It appears that the only way to use these new labels for already uploaded data is to shut down our compact node, edit every meta.json file in our object store to add the new label and restart our store nodes with an empty meta cache, so it will resync with the new labels. 

It would be great if store and compact could use [Prometheus' relabel_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config) to mutate the labels of a given block before operating on it or advertising it over StoreAPI. This should allow compact to compact and downsample across a label change and store would be able to return results that predate the label change. 

However, until relabling is available, it would be nice to have a `thanos bucket` command that relabels uploaded meta.json files according to a relabel config, or applies the latest label set to all other uploaded meta.json files that share a replica/deduplication label.

**Comment by bwplotka** [comment]
Thanks for this! :+1: 

We definitely thought about this during design process and from the implementation side, this is easy to achieve. However, it's easy to confuse the situation totally with sharding. It's already complex with all of the different external labels through the time we had.

I think we could definitely consider this at some point, but I see some other solution. You can totally temporarily relabel something  in the single relabeling flow so your sharding will work just fine for older format for example:

> It would be great if store and compact could use Prometheus' relabel_config to mutate the labels of a given block before operating on it or advertising it over StoreAPI. 

Can you elaborate on what your relabelling would look like?  I don't know your exact situation but let's say you have:

Prom: `cluster=A, region=us` 
Prom: `cluster=B, region=us` 
Prom: `cluster=C, region=us` 
Prom: `cluster=D, region=us` 
Prom: `cluster=X, region=emea` 

But you used to have no `region` label, so in relabeling do

```
- sources: [region, cluster]
  regexp ".+;(A|B|C)"
  target: region
  replacement; "us"
  action: replace
- sources: [region, cluster]
  regexp ".+;(D)"
  target: region
  replacement; "emea"
  action: replace
# Your actual sharding:
- sources: [region]
  regexp "us"
  action: keep
```

That would not work?

**Comment by bwplotka** [comment]
> However, until relabling is available, it would be nice to have a thanos bucket command that relabels uploaded meta.json files according to a relabel config, or applies the latest label set to all other uploaded meta.json files that share a replica/deduplication label.

Definitely that's something we can have among `thanos bucket` subcommands

**Comment by bwplotka** [comment]
Also we have `_block_id` exposed for relabelling so wonder if we could do some special function `ulidGreaterThan` in relabelling and base on this (:

**Comment by gburek-fastly** [comment]
> I think we could definitely consider this at some point, but I see some other solution. You can totally temporarily relabel something in the single relabeling flow so your sharding will work just fine for older format for example:

From what I can see in [store](https://github.com/thanos-io/thanos/blob/master/cmd/thanos/store.go#L250), relabelConfig is used for building the metaFetcher, but I don't see how the relabelConfig would affect query time selection of blocks. To put it another way, I see the relabel config above would allow a store node to fetch current and historical blocks that should have `region="us"`, but would a query with `{region="us"}` return the older chunks without that label? 

Similarly, if our sharding has several smaller regions grouped into one node, would a query with a specific region that is routed to the node be able to get the proper blocks for only one region among the many on the node?

**Comment by bwplotka** [comment]
ah, good point, yes it will fetch data, but external label would be not fixed :/

Yes. I think what you propose is a valid case TBH. If done in very limited way, I think it will be useful. We definitely need some larger discussion and design here. Essentially wonder what wrong can happen and how debuggable would be that. (: 

cc @brancz @metalmatze maybe you remember discussions around this... In September 2019? ;p 

Also happy Easter! Looks like we might have slower responses due to long weekend :hugs:

**Comment by bwplotka** [comment]
It might be easier to implement a tool for changing meta.jsons based on what you need but **be careful* as we cache meta.json in several places, so we expect it to be immutable. So at the end it might involve block copying anyway );

**Comment by bwplotka** [comment]
Very interesting thing, let's brough it on our public call this week https://thanos.io/community.md/

**Comment by gitperr** [comment]
Does tooling for this exist at the moment? I've been trying to relabel some external labels using https://thanos.io/tip/operating/modify-objstore-data.md/#relabel-series
but, to no avail :(

**Comment by yeya24** [comment]
There is no tool to do this atm.
But it should be fairly easy to implement it yourself.
You can just iterate blocks on your object store, edit `meta.json` file external labels to what you want.
