### ISSUE TITLE
query: Optionally make selector labels be required in matchers

### ISSUE THREAD

**Issue by dgl** [thanos-io/thanos#2405]
In Prometheus [remote_read](https://prometheus.io/docs/operating/configuration/#remote_read) configuration there is a `required_matchers` option. This is very similar to selectors in Thanos, but if a matcher is missing from a query Thanos currently sends the query to it (behaviour explained in #44).

It would be nice to be able to specify that a matcher must be present to query a particular store. This would allow to limit queries that are sent to a remote store. Ideally this would be configurable per store defined on query.

Our use case is combined with [Geras](http://github.com/G-Research/geras), potentially expensive Store API queries are made to Geras, even if we know Geras won't have results. This gets more complex when multiple parts of the Thanos hierarchy reference Geras, for example a global thanos-query may reference thanos-query in two clusters, we want queries to go to them without any restriction (i.e. normal Thanos behaviour), but that would mean multiple queries going to Geras (which is fine, because they get deduped, but it hurts latency). Being able to require `{source="geras"}` is specified in queries means we have a way to avoid extra unnecessary queries.

```
                                                +-----------------+
  +------------------------+  {source="geras"}  |                 |
  |                        +------------------->+                 |
  |                        |   (required)       |                 |
  |     Global             |                    |      Geras      |
  |     thanos-query       |                    |                 |
  |                        |                    |                 |
  |                        |                    |                 |
  +--+--------------+------+                    +-------+---------+
     |              |                                   ^
     |              |                                   |
     |              |  {source="thanos"}                |
     |              |  (not required in query)          | {source="geras"}
     |              |                                   | (required)
     |              |                                   |
     v              v                                   |
+----+------+   +---+----------+                        |
|           |   |              +------------------------+
|  thanos   |   |   thanos     |
|  cluster1 |   |   cluster2   |
|           |   |              |
+-----------+   +--------------+
```

The architecture could look something like this, we can use Geras as a custom Store API at either the global or cluster level, by specifying `{source="geras"}`, but because the source label is set to thanos (via `--selector`) on the cluster level thanos-query instances, we don't send queries to the wrong layer of the hierarchy (i.e. each layer can access geras locally, but not via a remote thanos-query instance).

I believe this should be generally applicable as a way to reduce latency in any Thanos configurations with high latency between components though. (We have been emulating this with multiple query instances with different store backends, where ruler talks to a different query backend than users do, but this is quite difficult to reason about, whereas this uses label matching in a more understandable way.)

**Comment by bwplotka** [comment]
I think that might be valid request... (: 

I would also rename those for consistency.

## Acceptance Criteria:

* Rename `--selector` to `--required-matchers` 
* Make sure those required matchers are semantically the same as remote read required matchers

Code: https://github.com/thanos-io/thanos/blob/0bb67bcbc3a75fb274c1649dcfdb13a8c2db4024/pkg/store/proxy.go#L203

Does it make sense @dgl? 

cc @Harshitha1234
 
cc @

**Comment by dgl** [comment]
@bwplotka That implies removing the ability to have selector labels that aren't required at query time in querier -- please don't do that; there are other use cases for those (e.g. I have one publicly documented in https://github.com/G-Research/thanos-remote-read/blob/master/docs/ruler.md -- essentially they can be used to add "external labels").

My thoughts on how to do this would be to have a per store configuration that says what labels are required, not just an option to query.

**Comment by bwplotka** [comment]
I see. Our impression was that `selector` is really historical thing I created when there was no dynamic meta propagation and no one uses it.

Ok, looks like we can split this issue into multiple steps. @Harshitha1234 would like to take it as her second Thanos contribution, so let's do it step by step! (: 

1. Since looks like selector label is still wanted, let's not remove it. Instead let's fix the flag description because as we found with @Harshitha1234 it is cryptic.
2. Let's add required matcher logic as in Prometheus: https://github.com/prometheus/prometheus/blob/fe802f29c99d76be27bf1b1e226ebb447fab4627/storage/remote/read.go#L172 to Thanos, but per Series call for now.

This is because it cannot be per store until: https://github.com/thanos-io/thanos/pull/2226 is done. Also @dgl please help in reviewing this, we would love to have more help! (: 

So step 3. Would be then to convert per `Series` required matcher to per store... 

Does it make sense? cc @metalmatze

**Comment by Harshitha1234** [comment]
Still needed! :)

**Comment by Harshitha1234** [comment]
Waiting for #2226 to be done for supporting per store :)

**Comment by arvidsnet** [comment]
I am also very interested in this feature - it would allow us to avoid using a lot of extra query components with different --selector-label parameters

**Comment by arvidsnet** [comment]
can we reopen this issue?
