### ISSUE TITLE
[FeatureRequest] mute prometheus alertmanagers using the Thanos sidecar

### ISSUE THREAD

**Issue by secustor** [thanos-io/thanos#2406]
We planning to use Thanos to allow to query multiple DC sites, where we are planning to use Prometheus. We plan to setup alerts on this Prometheus instances for the infrastructure and also using Ruler for e.g. VPN tunnels. Because of this we have to mute the Ruler and the DC Prometheus instances individually. 

It would be very useful that mutes set on the Ruler level would also effect alerts on the connected Prometheus instances. 

e.g. a mute for `dc=london` would disable all alerts in the referenced Prometheus server with the external label `dc=london` as the rules with the same labels in Ruler.

**Comment by bwplotka** [comment]
What do you mean mute? You mean silencers?

**Comment by secustor** [comment]
Yes, exactly.

**Comment by bwplotka** [comment]
Then it is out of scope of Thanos or Prometheus.

Silencers are [Alertmanager](https://prometheus.io/docs/alerting/alertmanager/) feature strictly. :hugs: so it will work across everything.
