### ISSUE TITLE
store: deal with slow object store backend

### ISSUE THREAD

**Issue by Gnoale** [thanos-io/thanos#2410]
**Thanos, Prometheus and Golang version used**:
thanos, version 0.11.0

**Object Storage Provider**:
S3

**What happened**:  
As a matter of fact I use an object store backend which has some performance issues, mostly high latency when fetching objects (95th ~150ms) no matter the object size.

What I understand so far of the impact with Thanos is it retrieve objects by parts, and so generates a lot of requests to fetch a given chunk (any hint about that welcome :-) )
I looked at the issue with `net/http/pprof`, most of the time is spent in locks waiting for hundreds of goroutines to complete, the function involved is `github.com/minio/minio-go/v6.Client.getObjectWithContext`    

My prometheus setup involved only 24 hours of retention time, the rest should be accessible in object store. 

Now, to workaround the issue I am tweaking the store parameters, in particular I would like to discard completely the object store when requesting stuff less than 24 hours old. 
I tried `--min-time=-12h` and various combination with sidecar but I still get the timeout. 

When I disable the store component the query are superfast (sidecar only)

**What you expected to happen**:
The time parameter should workaround the object store performance while requesting data available from sidecar endpoints.

**Comment by GiedriusS** [comment]
> **Thanos, Prometheus and Golang version used**:
> thanos, version 0.11.0
> 
> **Object Storage Provider**:
> S3
> 
> **What happened**:
> As a matter of fact I use an object store backend which has some performance issues, mostly high latency when fetching objects (95th ~150ms) no matter the object size.
> 
> What I understand so far of the impact with Thanos is it retrieve objects by parts, and so generates a lot of requests to fetch a given chunk (any hint about that welcome :-) )
> I looked at the issue with `net/http/pprof`, most of the time is spent in locks waiting for hundreds of goroutines to complete, the function involved is `github.com/minio/minio-go/v6.Client.getObjectWithContext`
> 
> My prometheus setup involved only 24 hours of retention time, the rest should be accessible in object store.
> 
> Now, to workaround the issue I am tweaking the store parameters, in particular I would like to discard completely the object store when requesting stuff less than 24 hours old.
> I tried `--min-time=-12h` and various combination with sidecar but I still get the timeout.
> 
> When I disable the store component the query are superfast (sidecar only)
> 
> **What you expected to happen**:
> The time parameter should workaround the object store performance while requesting data available from sidecar endpoints.

But `--min-time` is wrong in this case. You should do `--max-time=-12h` because max in this case means the point in time which is closer to the current time. 

Also, do you have Thanos Compactor running?

Without any particular suggestions on improvements, I'm afraid that this is unactionable.

**Comment by Gnoale** [comment]
Thanks ! 
I got confused with the parameter, it works very well indeed.
Yes I have the compactor running.

About improvements, I don't know how performance are usually with s3 object store for this use case.

My understanding is that the more sample ingested per unit of time you get, the more of chunks you will have since Prometheus store them by  2 hours groups.
We have a quite a lot of series (≃ 1.7 millions ≃ 340GB) on a period of 2 weeks.
I guess Thanos has to scrap a lot of chunks to find the requested data, hence a lot of `getObjectWithContext` requests.
Is it correct ?

**Comment by GiedriusS** [comment]
> Thanks !
> I got confused with the parameter, it works very well indeed.
> Yes I have the compactor running.
> 
> About improvements, I don't know how performance are usually with s3 object store for this use case.
> 
> My understanding is that the more sample ingested per unit of time you get, the more of chunks you will have since Prometheus store them by 2 hours groups.
> We have a quite a lot of series (≃ 1.7 millions ≃ 340GB) on a period of 2 weeks.
> I guess Thanos has to scrap a lot of chunks to find the requested data, hence a lot of `getObjectWithContext` requests.
> Is it correct ?

Yes. You can try increasing the index cache size on Thanos Store to reduce the number of requests or add end-result caching with Cortex's query-frontend.

**Comment by Gnoale** [comment]
Thanks for the hint, 
I am using the bucket component to replicate my data to aws s3 to compare perfs.
It seems it only replicate gradually as sidecar upload new blocks, is it the expected behaviour ?

**Comment by yinchengjian** [comment]
> Thanks for the hint,
> I am using the bucket component to replicate my data to aws s3 to compare perfs.
> It seems it only replicate gradually as sidecar upload new blocks, is it the expected behaviour ?

do you reslove this problem? if is ,could you give me some suggest，thank you
because you closed this problem

**Comment by Gnoale** [comment]
Nop, I do no use it anymore, but my performances issue seems to be solved by a major increase of performance on the object store side, plus an upgrade of thanos which use less memory while loading series and stopped oom.

**Comment by yinchengjian** [comment]
you solve this issue by an upgrade of thanos ?
and you use another data source to replace s3？
can you tell me in detail, thank you
