### ISSUE TITLE
Feasibility of having Thanos Receiver at scale  

### ISSUE THREAD

**Issue by varun-krishna** [thanos-io/thanos#2447]
Exploring ways to have Prometheus fully stateless at scale . 

Present setup : Thanos , GCS for Obj Storage , 2 HA Prometheus instances .

Would like to understand how scalable receiver would be for such a setup and the tradeoff from moving away from Thanos sidecar to receiver to achieve full statelessness for Prometheus (Worst case - loss in 2 Hrs of data)

**Comment by bwplotka** [comment]
Sure (: 

2 instances will work without 0 problems. We currently run Thanos Receive Cluster with ~5k Prometheus instances..  and 3x replication and it has still room to scale up (which we do every day) (: 

For details on ongoing work and documentation please visit https://github.com/thanos-io/thanos/issues/1093 and #thanos Slack channel :hugs:
