### ISSUE TITLE
Thanos Metrics across components

### ISSUE THREAD

**Issue by dinesh4747** [thanos-io/thanos#2452]
Hi Team

I am big fan of Thanos and using it all around in my frim and I wanted to thanks for all the work and craft in making up such an awesome product.

While we speak I am now focused on setting alarms via rules for all the Thanos components can someone route me to metric docs/alarms/dashboard json where I can set dashboard in grafana and creates alerts

**Comment by kakkoyun** [comment]
@dinesh4747 Thanks for your kind words. 

You can find example alert and dashboards definitions under [thanos-mixin](https://github.com/thanos-io/thanos/tree/master/mixin/thanos) subproject.

Cheers.

**Comment by dinesh4747** [comment]
@kakkoyun - Thanks for being humble and I see that in my thanos instance I don't see any metrics like thanos_querier-* and other thanos_objstore_bucket_failures_per_operation metric, Am I missing something here?

I am using thanos version - thanos-0.9.0

Does it require any exporters to be installed and or if I go with latest version then i would automatically start ingestion metrics across the components, any insights would be really helpful

**Comment by spencergilbert** [comment]
some of the metric names changed over new versions

**Comment by kakkoyun** [comment]
@dinesh4747 It doesn't require any exporter. I'd say make sure you actually scrape all the components. 
And @spencergilbert has a point. Make sure the metrics that you're looking for actually exists in your version.

**Comment by spencergilbert** [comment]
I ran into a similar thing - ended up just pulling an older version of the mixins at that time :+1:

**Comment by dinesh4747** [comment]
Thanks @kakkoyun @spencergilbert for the quick response, will double check on scrapping metrics and switch over to latest version as well
