### ISSUE TITLE
Include DCO instructions in Contributing Guide

### ISSUE THREAD

**Issue by StephenWeber** [thanos-io/thanos#2458]
While PRs are subject to a DCO signoff procedure (since #1388), this is not included in the Contributing Guide.

It looks like it should be a part of the steps provided in https://github.com/thanos-io/thanos/blob/master/CONTRIBUTING.md#pull-request-process but there may be other places it makes sense.

A great solution to this issue would include:
- actual command to run to sign off on commit changes
- explanation of what this means to the project
- a link to more information from the CNCF

**Comment by bwplotka** [comment]
Definitely :+1: 

Help wanted! :hugs:

**Comment by ranjithkumar007** [comment]
I am a newbie to Thanos. I would like to have a go at this.

**Comment by bwplotka** [comment]
Go for it!
