### ISSUE TITLE
Remove redundant type declaration

### ISSUE THREAD

**Issue by ranjithkumar007** [thanos-io/thanos#2467]
For example in [querier_test.go](https://github.com/thanos-io/thanos/blob/master/pkg/query/querier_test.go#L98), [v1_test.go](https://github.com/thanos-io/thanos/blob/master/pkg/query/api/v1_test.go#L55) currently, there are redundant type declarations
```
exp := []promql.Series{
	promql.Series{
		Metric: labels.FromStrings("zzz", "a"),
         ...
         }, 
	promql.Series{
		Metric: labels.FromStrings("zzz", "b"),
         ...
         },
```

We can remove this redundancy and simplify as 
``` I came across this while setting up my dev env for Thanos.
exp := []promql.Series{
	{
		Metric: labels.FromStrings("zzz", "a"),
         ...
         }, 
	{
		Metric: labels.FromStrings("zzz", "b"),
         ...
         },

```

**Comment by ranjithkumar007** [comment]
I would like to fix this if these changes are required.

**Comment by GiedriusS** [comment]
I believe this is done here already: https://github.com/thanos-io/thanos/pull/2463/files. Someone was faster than you, sorry! :smile:

**Comment by ranjithkumar007** [comment]
Extremely Sorry, Mybad! I didn't saw that. Shall I close the issue.

**Comment by GiedriusS** [comment]
Yes, let's close this in favor of that PR :+1: sorry again
