### ISSUE TITLE
Validate the sharding relabel action

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#2468]
As discussed [here](https://github.com/thanos-io/thanos/pull/2379#discussion_r404418937), currently [thanos sharding](https://thanos.io/sharding.md/#relabelling) only supports three relabel actions. However, we use the relabel process function from Prometheus, which accepts other relabel actions as well, but actually these unsupported actions don't do anything.

It would be nice to have a check/validation on the relabel config. If the action is not supported by thanos, we can tell users this is not supported and return error.

AC:
- Check the relabel config before the relabel process. If the configured action is not supported, tell the reason in the log and return error

**Comment by ranjithkumar007** [comment]
Would like to have a go at this.

**Comment by bwplotka** [comment]
Go for it!

**Comment by ranjithkumar007** [comment]
Unstale..

**Comment by GiedriusS** [comment]
Still relevant AFAIK.
