### ISSUE TITLE
compactor: Consider incrementing either `...group_compactions_total` or `...group_vertical_compactions_total` not both.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2469]
This is why metric testing and e2e tests are awesome! I found some unexpected cases that were surprising. One of them is that on vertical compaction we increment both vertical and normal compaction, which is confusing as it looks like in total we had 2 compactions, not one.

I think we should increment just either normal or vertical or just add a label to this metric (better).

Marking as bug, let's fix it.

**Comment by bwplotka** [comment]
Related TODO: https://github.com/thanos-io/thanos/blob/7c5bea680a5cdebbf127fa4f318f53c0818bd31c/test/e2e/compact_test.go#L511

**Comment by brancz** [comment]
I personally think this is the right behavior. Along the lines of total and corresponding error metric where total always includes errors.

**Comment by bwplotka** [comment]
Thanks. In this case, maybe we should rename / clarify this in HELP (:

**Comment by brancz** [comment]
Agreed!

**Comment by pracucci** [comment]
> I personally think this is the right behavior. Along the lines of total and corresponding error metric where total always includes errors.

Agree. It's also who TSDB metrics work:
- `prometheus_tsdb_compactions_total` (always increased)
- `prometheus_tsdb_vertical_compactions_total` (increased if the overlapping blocks are found during compaction)

**Comment by darshanime** [comment]
The TODO is already removed in https://github.com/thanos-io/thanos/commit/2654a10c3f02a89fa34a01c6af5bb28540ce6c40

The HELP text is currently:
```go
		Name: "thanos_compact_group_compactions_total",
		Help: "Total number of group compaction attempts that resulted in a new block.",


		Name: "thanos_compact_group_vertical_compactions_total",
		Help: "Total number of group compaction attempts that resulted in a new block based on overlapping blocks.",
```

Any ideas on whether it change it? One possible alternative can be:
```go
		Name: "thanos_compact_group_compactions_total",
		Help: "Total number of group compaction attempts that resulted in a new block regardless of cause.",


		Name: "thanos_compact_group_vertical_compactions_total",
		Help: "Total number of group compaction attempts that resulted in a new block based on overlapping blocks.",
```

**Comment by bwplotka** [comment]
Looks like this is done after all, thanks all for discussion (:
