### ISSUE TITLE
thanos store gateway: fatal error: concurrent map writes 

### ISSUE THREAD

**Issue by hawran** [thanos-io/thanos#2471]
**Thanos, Prometheus and Golang version used**:
thanos: 0.12.0
prometheus: 2.17.1
go: 1.13

**Object Storage Provider**:
ceph s3

**What happened**:
A couple of restarts during last two days because of internal errors.

**What you expected to happen**:
No such restarts.

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:
https://gist.github.com/hawran/f87f6b03aceac64553d9b2cd8e6c2532

**Anything else we need to know**:

**Comment by bwplotka** [comment]
Ack, looks like a bug to ship to 0.12.1  @squat 

Will look on this after breakfast

**Comment by squat** [comment]
+1 thanks for the report. will investigate

**Comment by bwplotka** [comment]
Fixed on `release-0.12`, should ported to master soon :hugs: 

Thanks for quick report!
