### ISSUE TITLE
Need help to configure thanos store and query component.

### ISSUE THREAD

**Issue by satyabhama** [thanos-io/thanos#2473]
I need help to configure thanos store and query component.
We are getting no space left error multiple times.
We have aws ECS cluster for thanos query and store component, which memory exctly store component use to store index cache (EBS or memory)???

**Comment by GiedriusS** [comment]
Hi! Apologies for the late answer. If I understood you correctly then tt depends on your configuration - Thanos Store can either use `memcached` or store the index cache in the memory. Also, it uses a bit of disk space to store what is called "index headers". They are essentially the same index files that Prometheus produces albeit with not all of the information, only with the information that lets Thanos lookup more data when a query comes in. The newest version uses a binary format of that which uses less disk space so if you have not updated yet to the newest version then you should consider that. I hope that helps :)
