### ISSUE TITLE
[Prometheus Ecosystem] Remote Write Server Side Traffic Mirroring + Obfuscator

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2480]
It's not strictly connected to Thanos, but as Thanos implements Receive (Remote Write API) we are looking at how to have more realistic staging environments. In order to do that we want to  "mirror / fork" portion of production traffic to other clusters APIs etc.

As part of this mirroring, data has to be obfuscated to avoid leaking of sensitive data, but also without totally changing the characteristic of data (e.g same number labels, labels values/names with the same amount of characters, etc).

In the future, we could add some more advanced features if needed (e.g load balancing).

Wonder if anyone in the community had been working on something like that already and has something to share/is already shared? @gouthamve @pracucci @tomwilkie @beorn7 @bboreham 

The idea came also from @halcyondude, Matt suggested that [ProxySQL](https://github.com/sysown/proxysql/wiki/Mirroring) is something like that but in the SQL world. Would be awesome to have the same for remote write (and Query API as well I guess, but let's think about it in a separate thread)  (: 

If there is nothing like that, it sounds like a good project idea in open source... :hugs:

**Comment by bwplotka** [comment]
Prometheus-user mailing list discussion: https://groups.google.com/forum/#!topic/prometheus-users/qhHgiEuZ8aY

**Comment by bwplotka** [comment]
For query traffic we have https://cortexmetrics.io/docs/operations/query-tee/ (:

**Comment by pracucci** [comment]
We also need traffic mirroring for the write path in Cortex (to progressively rollout the new blocks storage in production while keeping the old chunks storage running). In our case we need no obfuscation, but all other requirements match ours too.

**Comment by bwplotka** [comment]
Right now our discussions are floating in direction of generic L7 traffic mirroring... :thinking: Would that work @pracucci ?

**Comment by pracucci** [comment]
> Right now our discussions are floating in direction of generic L7 traffic mirroring... 🤔 Would that work @pracucci ?

I agree with L7, not sure about "generic" (depends what you have in mind about it).

On the Cortex side, I think we need to support HTTP and GRPC (because I do expect it to sit after the authentication layer and before the distributor), track performance metrics for each endpoint between the two backends, configure which backend is authoritative (and the response will be sent back always from the authoritative one).

**Comment by pracucci** [comment]
In Cortex we may need it soon and we m ay end up building a `write-tee` similar to the [`query-tee`](https://cortexmetrics.io/docs/operations/query-tee/). Are there strong opinions about not building a custom `write-tee` specifically tied to the Prometheus remote write protocol?

**Comment by pracucci** [comment]
In Cortex we ended up with something very easy based on Envoy. Given we didn't need obfuscation or sampling (but 100% traffic mirroring) we used Envoy. I've just shared a config example here:
https://github.com/cortexproject/cortex/pull/2556

**Comment by bwplotka** [comment]
Stil valid.
