### ISSUE TITLE
Compactor: Documentation clarification

### ISSUE THREAD

**Issue by jdfalk** [thanos-io/thanos#2482]
Could you clarify this line for me:
https://github.com/thanos-io/thanos/blob/master/cmd/thanos/compact.go#L141 
`141: "Experimental. When it is set true, this will given labels from blocks so that vertical compaction could merge blocks."+`

I assume you mean is as follows, but don't want to assume anything. 
`when it is set to true, compactor will ignore the given labels so that vertical compaction can merge the blocks.`

If I am correct, I created a pull request to change the wording. 
https://github.com/thanos-io/thanos/pull/2481

**Comment by kakkoyun** [comment]
@jdfalk Thanks for the issue and PR. My bad 🤦 I'm gonna review the PR.
