### ISSUE TITLE
Web route prefix is not applied on debug endpoints.

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#2486]
In Prometheus, if the web external path is set, then all Prometheus routes will be updated. There is a good example here https://www.robustperception.io/using-external-urls-and-proxies-with-prometheus

```
You should be aware that with this external URL, the /prometheus/ path prefix will be required for all HTTP access to Prometheus. 

The /metrics will be on http://localhost:9090/prometheus/metrics for example.
```

However, in thanos, if web route prefix is set to `/thanos`, only `/api/v1` endpoints will be updated to `/thanos/api/v1`. But other endpoints like `/metrics`, still serve on `/metrics`, we should add web route prefix to these endpoints as well.

AC:
- Endpoints like `/metrics` or `/-/ready` can work with web route prefix just like Prometheus.

**Comment by bwplotka** [comment]
Fixed on relase branch, v0.12.1 should have it

**Comment by yeya24** [comment]
This is not done.  #2489 only fixes the problem of duplicate registering the web route prefix.

**Comment by bwplotka** [comment]
Sorry, you are right, I confused things. Thanks @yeya24 !

**Comment by yeya24** [comment]
No worries. @bwplotka Feel free to edit the issue description, if it is not clear to you.

**Comment by ranjithkumar007** [comment]
@fengzixu are you working on this issue?

**Comment by yeya24** [comment]
Valid #2524

**Comment by ranjithkumar007** [comment]
will update this.

**Comment by ranjithkumar007** [comment]
calm down @stale-bot

**Comment by yeya24** [comment]
This pr should be review #2524, just need another :eye:  to take a look.

**Comment by yeya24** [comment]
Need another review.

**Comment by yeya24** [comment]
Still valid.
