### ISSUE TITLE
Error parsing commandline arguments: unknown long flag '--index-cache.config-file'

### ISSUE THREAD

**Issue by satyabhama** [thanos-io/thanos#2487]
we are trying to add thanos store configuration we are getting below error.
Error parsing commandline arguments: unknown long flag '--index-cache.config-file'
for all index cache related parameter we are getting this error

**Comment by bwplotka** [comment]
Use v0.12.0 and the above version. Documentation relates to `master` for now (:

**Comment by satyabhama** [comment]
@bwplotka we are using v2.4.0 version

**Comment by bwplotka** [comment]
Such an option did not exist back then. Please upgrade Thanos to `master` or upcoming v0.12.1 (should be today)

We are planning to improve our docs so it's much cleaner to which versions they related to https://github.com/thanos-io/thanos/issues/2488 :hugs: 

Sorry for the confusion!
