### ISSUE TITLE
Website documentation should be versioned.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2488]
As per our discussions here https://cloud-native.slack.com/archives/CL25937SP/p1585323322092300 and on Thanos Sync we agreed that we need improvement to our Hugo-based website that will allow exploring documentation part ([`docs/`](https://github.com/thanos-io/thanos/tree/master/docs)) per release version (and latest master) (: 

Help wanted :hugs: 

Maybe good as GSoC/Community project.

AC:
* ([`docs/`](https://github.com/thanos-io/thanos/tree/master/docs) should be versioned under https://thanos.io/getting-started.md/ on our website for each minor releases (`release-*` branches) and master.
* Allow user to tell in URL path what version to show.
* By default show docs from the latest release
* It should be easy to add new releases.

Ideally should be part as some preprocessing before Hugo, maybe as Go command (:

**Comment by bwplotka** [comment]
Cortex is doing the same :hugs:  https://github.com/thanos-io/thanos/issues/2488

**Comment by jaybatra26** [comment]
Hi!
We are trying to achieve something similar in Cortex. We have proposed to version specific pages to start with. We would sincerely appreciate feedback and suggestions on our [proposal](https://github.com/cortexproject/cortex/pull/2349/).

**Comment by jojohappy** [comment]
> Cortex is doing the same 🤗 [cortexproject/cortex#2349](https://github.com/cortexproject/cortex/pull/2349)

Cool!

**Comment by bwplotka** [comment]
AFAIK @jaybatra26 is helping with proposal only. We are adding this project to Community Bridge. :hugs:

**Comment by kushthedude** [comment]
@bwplotka Are we planning to achieve the versioned documentation similar to k8s.io ? Or do you have something else in mind?

**Comment by bwplotka** [comment]
Rather like https://prometheus.io/docs/introduction/overview/ (: 

![image](https://user-images.githubusercontent.com/6950331/80195792-4a2aac80-8614-11ea-9291-202b2a0d277d.png)

**Comment by kushthedude** [comment]
> Rather like https://prometheus.io/docs/introduction/overview/ (:
> 
> ![image](https://user-images.githubusercontent.com/6950331/80195792-4a2aac80-8614-11ea-9291-202b2a0d277d.png)

Nice, got it! I would to apply for the same😄

**Comment by thisisobate** [comment]
Wow! @bwplotka  This is the kind of issue I would love to contribute! Drafting my first PR as soon as possible

**Comment by agarwalrounak** [comment]
Hi @bwplotka! I am interested to get mentored for this issue for the Community Bridge program.  
Thus, I have applied as a mentee on the Community Bridge website for this project.
Hoping to getting interviewed and selected. Looking forward to it.

**Comment by bwplotka** [comment]
@thisisobate worth to check what Cortex did: https://github.com/cortexproject/cortex/pull/2349
