### ISSUE TITLE
Receive: option to backfill data

### ISSUE THREAD

**Issue by vishnubraj** [thanos-io/thanos#2490]
We want to migrate the old metric data from graphite to Thanos.. we wrote a script to export the data and send the data to thanos receive using remote write.. But thanos Receive rejects the data with below mentioned error.  Please enable the option to backfill the old data.

```
level=warn ts=2020-04-10T17:11:24.28541454Z caller=writer.go:86 component=receive component=receive-writer msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=100431
level=error ts=2020-04-10T17:11:24.285494928Z caller=handler.go:372 component=receive component=receive-handler msg="storing locally" err="failed to non-fast add 100431 samples: out of bounds: conflict" endpoint=http://opstest1.sjc2:19291/api/v1/receive 
```

**Comment by bwplotka** [comment]
Yes, this will not work. This is related to TSDB and why it backfilling is not possible through normal append interface. 

See this discussion: https://github.com/prometheus/prometheus/issues/535 and our design doc: https://docs.google.com/document/d/15wKdeFntgUmEnV8kqQ_5iQEIhXnwU8HNm0NKlkR0xk4/edit#

Let's keep this issue open to track this need. We are aware and we can do it outside of Prometheus, but we would prefer to have TSDB native solution.

In the mean time you backfill by uploading the blocks using sidecar for Prometheus or some for or `thanos bucket replicate` (with some changes)

**Comment by bwplotka** [comment]
cc @brancz as we spoke about this and why remote write method would be nice for backfilling even on Prometheus side.

**Comment by bwplotka** [comment]
Dup of https://github.com/thanos-io/thanos/issues/2599 (: Let's close this.
