### ISSUE TITLE
Improving contribution experience

### ISSUE THREAD

**Issue by RajatVaryani** [thanos-io/thanos#2493]
Problem: It is difficult to find issues to contribute to because it is unclear if anyone is working on it. We have to read the entire conversation to figure out if someone is working on it or not. 

Solution:
Assign folks to the issue or maybe add a label `Up for grabs` for issues which need new contributors and removing it when someone starts working on it. 

Thoughts?

**Comment by bwplotka** [comment]
Definitely! Ideally we can setup some prow for this


Very good idea!

Also you looks like you just found issue which is not assigned to anyone
yet... ((:

**Comment by RajatVaryani** [comment]
I can help in any way I can.  What would be the next steps?
