### ISSUE TITLE
compact: Blocks marked "compaction Failed" causing problems

### ISSUE THREAD

**Issue by belm0** [thanos-io/thanos#2495]
**Thanos, Prometheus and Golang version used**: v0.12.0-rc.1

**Object Storage Provider**: GCS

**What happened**:  Some compacted blocks migrated from Prometheus appear to have been marked with `compaction.failed=true` metadata.  It causes at least two problems:

  1. when compacting to higher orders, the Prometheus compaction library used by thanos will not consider any block range which includes a block marked "Failed"
  2. thanos seems to propagate the Failed flag to downsampled blocks, even though the generated blocks are presumably fine.  (I'm not sure if downsampled blocks themselves get compacted to higher orders, but if so this would block that also.)

**What you expected to happen**:

  * Some guidance on how to fix blocks marked compaction.failed.
  * `bucket verify` should flag compaction.failed blocks
  * **thanos-sidecar `--upload_compacted` should warn about compaction.failed blocks, and perhaps refuse to upload them**
  * thanos-compact perhaps should not propagate the failed flag to downsampled blocks.

**Anything else we need to know**:

Relevant code in prometheus compactor library:

https://github.com/prometheus/prometheus/blob/8224ddec23598152d7506b7b39f5235a77b5e036/tsdb/compact.go#L243-L249

**Comment by bwplotka** [comment]
That's new to us, I never seen this `compaction failed  = true`  in my life. (: I assume this status was present in Prometheus already...  Do you know the reason why that are failed?

**Comment by bwplotka** [comment]
My question before we even get further. Why this is bad? Looks like everything just works? We cannot compact failed compaction blocks, so otherwise there should be not really huge problem with one or two blocks being small... no?

**Comment by belm0** [comment]
As an experiment, we tried removing the `compaction.failed: true` from meta.json in 3 adjacent 6h blocks.   Thanos-compact was then able to compact the blocks fine, and we seem to be able to access the data for that time region.

We also have 54h blocks with the failed marker, so that will be a bigger test...

> Do you know the reason why that are failed?

No, though it may have been related to some disk-full situations we had on prometheus-sever.  However, so far the data in the corresponding blocks seems usable.

> My question before we even get further. Why this is bad? Looks like everything just works?

It's bad because a single block marked failed can taint the whole compaction system.  As in the example at https://github.com/thanos-io/thanos/issues/2413#issuecomment-617534752, it prevents higher order compaction, which in turn prevents downsampling.

And it's not limited to small blocks.  We had six 54h blocks marked failed, and it's preventing about 5 months of data from being downsampled to 1h.

**Comment by belm0** [comment]
I searched the prometheus-server logs for the offending block ID's.  There were no related errors in the logs.  

The only logs with the block id's are "found healthy block" (prometheus repair.go), and "upload new block" (thanos shipper.go)

**Comment by belm0** [comment]
I filed https://github.com/prometheus/prometheus/issues/7155 to prometheus regarding silently marking blocks `compaction.failed`, and to get clarity on how the system is intended to behave on these events (e.g. preserve failed output block and underlying blocks vs. preserve failed block only vs. preserve underlying blocks only).

One thing to investigate is whether thanos-compact may have received both the failed compaction blocks and the underlying blocks from `--upload_compacted` and perhaps proceeded to delete the underlying blocks.  (If so, that would be an argument for shipper not uploading failed compactions.)

**Comment by belm0** [comment]
TODO for bucket view:  list `compaction.failed` blocks with a clear note that they will interfere with normal operation of compaction and downsampling
