### ISSUE TITLE
Thanos sidecar not uploading older compacted datablocks. 

### ISSUE THREAD

**Issue by Mldhun** [thanos-io/thanos#2497]
**Thanos, Prometheus and Golang version used:** 
Promethus - version=2.16.0,
Thanos - thanos:v0.12.0
Object Storage Provider: G3

**Docker Run Options used**` - sudo docker  run  -d -v /prometheus_data/prometheus:/etc/prometheus -p 19190:19190 -p 19090:19090 --name prometheus-thanos-sidecar-cms thanosio/thanos:v0.12.0 sidecar --http-address 0.0.0.0:19090 --grpc-address 0.0.0.0:19190  --reloader.config-file /etc/prometheus/prometheus/prometheus.yml --prometheus.url http://metrics.myorderbox.aus-tx.colo:9090 --objstore.config-file=/etc/prometheus/thanos/objstore.config-file.yml --tsdb.path=/etc/prometheus/prometheus_data  --shipper.upload-compacted
`

**Setup Flow** - We had setup Promethus 3 months ago and now trying to setup thanos sidecar to ship the datablocks to s3.
             Now we've 3 months of datablocks in promethus server , its compacted by promethus. As per the thanos guildliness we've disabled the promethus compaction by pssing this option "    
             "--storage.tsdb.max-block-duration=2h",
             "--storage.tsdb.min-block-duration=2h""
**Next goal** - Need to start thanos sidecar to upload promethus data blocks (both older compacted bloacks & latest non-compacted block also)
             

**What happened:** We are getting below error on docker logs after starting thanos sidecar & its not uploading the old datablocks. 

"level=info ts=2020-04-21T11:17:00.4874704Z caller=shipper.go:226 msg="gathering all existing blocks from the remote bucket for check" id=01E6DZ8P90ZWQKHGJP0E0WA38D
level=error ts=2020-04-21T11:17:00.687286276Z caller=shipper.go:306 msg="found overlap or error during sync, cannot upload compacted block" err="get all block meta.: meta.json bkt get for 01DZCNZNP4SB2VVD8EY1V7HYSJ: The specified key does not exist."
level=warn ts=2020-04-  caller=sidecar.go:340 err="failed to sync 19 blocks" uploaded=0 "

**What we expected to happen:**
Since we're passing --shipper.upload-compacted thanos option, expecting thanos sidecar should upload old non-compact blocks also to s3. but its throwing above mentioned error and not uploaded the old blocks(i.e compacted data which promethus created before we disabling the compaction)

**Comment by belm0** [comment]
Overlapping blocks are a showstopper for thanos-compact.  You need to resolve that issue first.

https://github.com/thanos-io/thanos/blob/master/docs/operating/troubleshooting.md#overlaps
