### ISSUE TITLE
Compactor: Data is scattered over next compact restarts.

### ISSUE THREAD

**Issue by amadeuszkryze** [thanos-io/thanos#2499]
**Thanos, Prometheus and Golang version used**:
Thanos: 0.12.0
Prometheus: 2.15.2

**Object Storage Provider**: AWS

**What happened**: Data is scattered over following restarts in buckets:
![image](https://user-images.githubusercontent.com/37712172/79982770-1d0cbb80-84a7-11ea-928c-6f6c9ec85bb4.png)

**What you expected to happen**: I would expect to have consistent blocks over following restarts.

**How to reproduce it (as minimally and precisely as possible)**:
- Run compactor 
- Let it compact for some time
- Update/restart compactor
- Let it compact for some time
- Results

**Full logs to relevant components**: none

**Anything else we need to know**: I guess no.

**Comment by kakkoyun** [comment]
@amadeuszkryze Could you please provide a little bit more information?
What does your setup look like? Which components do you use? What flags do you use for compactor?

**Comment by amadeuszkryze** [comment]
**setup**: 10+ Prometheus instances with Thanos sidecars sending data to Thanos object storage, and then compactor does its magic with retention and resolution.
**components**: Bucket, Compactor, Query, Sidecar, Store
**flags**: 
```
          - 'compact'
          - '--data-dir=/opt/thanos/compact/data'
          - "--http-address=0.0.0.0:{{ port_definition[ 'thanos_compact_http' ] }}"
          - '--objstore.config-file=/opt/thanos/store/config/store.yml'
          - '--retention.resolution-raw=1y'
          - '--retention.resolution-5m=2y'
          - '--retention.resolution-1h=0d'
          - '--wait'
          - '--compact.concurrency=8'
          - '--log.level=info'`
```

**Comment by amadeuszkryze** [comment]
Additionally, after every stable Thanos release, whole stack is being redeployed with the newer version.

**Comment by amadeuszkryze** [comment]
The point is I'm not quite sure if this should be a block by block of 14days or such gaps are natural for this process I mean for every compactor restart. Please correct me if I'm mistaken :)

**Comment by bwplotka** [comment]
So we were changing recently what UI is showing. Can you update and check the following graphs `/loaded` `/global` on Compactor? Also, a clear screenshot of what is happening would be nice. Is this data overlapping or separate? (: 

Gaps might be moving because time is passing and maybe downsampling is slowly catching up. (: So as long as you don't see any issue with data, all should be good. You should look at that view only in case of problems really (: 

Closing but feel free to continue the discussion. We don't think it's a problem, but let's reopen if it is! (:

**Comment by bwplotka** [comment]
Also this graphs "scatter" means time scatter, maybe you thought it's some kind of placement? :thinking:
