### ISSUE TITLE
Compact - Network bandwidth limit option

### ISSUE THREAD

**Issue by vishnubraj** [thanos-io/thanos#2507]
The compact is using completely available network bandwidth in the network to download and upload the blocks from S3. 
Please provide the option to limit the network bandwidth available for compact service.

**Comment by GiedriusS** [comment]
Hello! I think this is out of the scope of the Thanos project. Please use the features provided by your OS to limit the (amount of) resources a process can use. For example, you can do that on Linux via cgroups: https://serverfault.com/questions/382547/how-to-limit-network-usage-for-concrete-application-in-linux-that-is-running-in.

**Comment by povilasv** [comment]
Yup, if you are running calico and Kubernetes you already can do that -> https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/#support-traffic-shaping
