### ISSUE TITLE
Idea: add correctness tests

### ISSUE THREAD

**Issue by GiedriusS** [thanos-io/thanos#2511]
Between the query that the users send to Thanos and what is actually used in the code some translation happens. For example, some translation happens here https://github.com/thanos-io/thanos/blob/55cb8ca38b3539381dc6a781e637df15c694e50a/pkg/store/matchers.go and https://github.com/thanos-io/thanos/blob/0bb67bcbc3a75fb274c1649dcfdb13a8c2db4024/pkg/query/querier.go#L151-L171. There might be bugs in that code. It would be nice to have a good way to test it out with a live Prometheus to see if everything really works as expected.

This came up from https://github.com/thanos-io/thanos/issues/2245. We could protect ourselves against this by running some kind of correctness tests.

Some ideas below.

We could add another e2e scenario where a block would be generated with known data that then would be added to a Prometheus instance that has Sidecar in front of it + uploaded to some remote storage that is picked up by Thanos Store. Then, we could run some (randomly generated) queries and see if we get the same results. In all of the cases, they should be the same if everything is correct.

I haven't looked into the Prometheus side of this too much but I have found that there is some kind of PromQL test suite: https://github.com/prometheus/prometheus/tree/master/promql/testdata. Perhaps we could adapt it and reuse the same?

Cortex has this A/B testing tool https://github.com/cortexproject/cortex/pull/2203. It could also be extended to include correctness tests.

Perhaps there is some kind of PromQL fuzzer that I am not aware of? :P Downsampled data probably shouldn't be a part of this.

Thoughts? :) 

/cc @yeya24

**Comment by yeya24** [comment]
Is it doable in our e2e? We can start one Promethues, one sidecar and a querier. And simply compare the query results of Prometheus and querier. 

https://github.com/prometheus/prometheus/tree/master/promql/testdata is great. But is it easy to add the metrics we need into the e2e Prometheus? The testdata is coupled with https://github.com/prometheus/prometheus/blob/84b4d079c8714be8e8ad071a35b0391df270364c/promql/test.go#L65:1 test framework.

Maybe we can extend the thanosbench. Put all the functionality there.

**Comment by brancz** [comment]
I think this type of thing is typically referred to as model based testing. I'm 100% for this! Thanos receive definitely could benefit from testing like this a lot as well!

**Comment by squat** [comment]
I think that in particular correctness of the interaction between compactor and stores would GREATLY benefit from this. There is a lot of subtlety in the interaction between all of the different metas, deletion markers etc

**Comment by GiedriusS** [comment]
Still valid.

**Comment by GiedriusS** [comment]
No updates from me :/ still valid IMHO

**Comment by GiedriusS** [comment]
No new updates from this front.

**Comment by GiedriusS** [comment]
Actually, https://github.com/thanos-io/thanos/pull/3631 is a start for this :P It's a bit different but still a step towards having automatic tests for PromQL compliance.

**Comment by yeya24** [comment]
Is this still valid? There is promql compliance test

**Comment by GiedriusS** [comment]
Don't think so, closing!
