### ISSUE TITLE
website (hugo): Add TOC on some pages larger than X words

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2512]
AC:
 * Setup: https://gohugo.io/content-management/toc/#template-example-toc-partial

This might mean we need to move to new markdown engine.

**Comment by kushthedude** [comment]
How about using Black Friday Engine? It is more similar to GitHub native markdown engine.

**Comment by bwplotka** [comment]
We use what already is available by Hugo, and Hugo deprecates it.

**Comment by kushthedude** [comment]
Hugo recently added support for Black Friday. We are using it in the k8s contributor site too.

**Comment by bwplotka** [comment]
Recently? It was a long time ago we are using BlackFriday already for at
least year, now they are moving:
https://gohugo.io/content-management/formats/#list-of-content-formats (did
not dive why)

**Comment by kushthedude** [comment]
> Hugo recently added support for Black Friday. We are using it in the k8s contributor site too.

Oops, My bad! I was talking about the Goldmark engine😅

**Comment by prondubuisi** [comment]
Hello @bwplotka , what is the issue here and how do I get started working on it?

**Comment by soniasingla** [comment]
hey @bwplotka, I would like to work on this issue. Can you please address on which pages the markdown is to be added? :)

**Comment by bwplotka** [comment]
I mentioned in the title. Maybe based on number of lines? Or number of sections? (`###` headers) e.g larger documents with more sections than 3 should have TOC :thinking:
