### ISSUE TITLE
limits: Add generic layer of limits  (e.g interceptors) for StoreAPI.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2527]
We can leverage gRPC interceptors to ensure configuring limits per chunks, series etc of StoreAPI

Open questions:
* partial result or total cancel?

**Comment by bwplotka** [comment]
Good point from @brancz  is that interceptor limit might be not enough. We can deduce how much chunks etc we will have without fetching them... so more on query planning side already.

**Comment by yashrsharma44** [comment]
I was working on a proposal for the above issue, and I had some queries regarding it. It would be really helpful for me to get some more clarity about the problem that we are trying to solve :sweat_smile: 

> We can deduce how much chunks etc we will have without fetching them

Are we looking something like pre-flight checks for this?

> so more on query planning side already.

Is this more like [Query Logging](https://prometheus.io/docs/guides/query-log/)?
@bwplotka

**Comment by VineethReddy02** [comment]
@bwplotka 
I see the existing configuration in querier to limit the large queries and responses are

_1. enablePartialResponse bool, 
2. queryTimeout time.Duration,
3. storeResponseTimeout time.Duration,_

Can I know what these configurations are missing to achieve in limiting the large queries and responses?

I have couple of questions here
1. So just to confirm will these interceptors be part of store API between querier & store, querier & sidecar right? as the query result is the aggregation of both.
2. And on what basis will grpc interceptors limit blocks? Based on the query range or based on the size of the block while querying the object store? 

This can help me to understand what additional configurations need to be added and how interceptor logic needs to be implemented.

**Comment by bwplotka** [comment]
Still in progress. Meant for a later task.

**Comment by bwplotka** [comment]
Still not done.

**Comment by bwplotka** [comment]
Proven to be hard. Let's start with "non-generic" ones first (:
