### ISSUE TITLE
Proposal: Upgrade vendor'ed Prometheus

### ISSUE THREAD

**Issue by gotjosh** [thanos-io/thanos#2531]
Hi everyone 👋,

Loving the work done on Thanos!

In Cortex, we vendor Prometheus through Thanos. Right now, we're in need of a feature that 2.18.0.rc-0 offers. While I understand that upgrading to an RC might be something unfeasible. I'd like to test the waters on what is possible and what is not.

At a glance, I see we're currently on ~v2.15.2. Is upgrading to something like v2.17.2, something that Thanos maintainers see as a possibility?

My thinking here is that although upgrading to an RC might be a bit more cautious. we can start doing some of the work now (by upgrading to 2.17.2) and therefore have a simple upgrade to path when the RC settles.

I'd be happy to do the work as long as it is something desirable. The below list is a very short attempt to document what needs to be done, any help on context already done would be appreciated.

List of changes

- [ ] `tsdb` moved to its own package. No longer part of `storage/tsdb`

**Comment by pracucci** [comment]
I'm OK reviewing a PR to upgrade Prometheus to the RC and keep it on hold until the stable release is out (adjusting the vendored Prometheus to the stable one once ready).

**Comment by brancz** [comment]
I think partly we wanted to wait for chunk iterators to land in prometheus/tsdb but I also have no objection to bumping more frequently.

@bwplotka any objections?

**Comment by bwplotka** [comment]
We already talked about it... https://cloud-native.slack.com/archives/CL25937SP/p1587978957437100

What we can do better to not repeat the same discussions all the time? I guess it was my bad to not create an issue for it. But at the same time @pracucci was already in this discussion.

**Comment by gotjosh** [comment]
I should have sync-ed up with @pracucci before opening this issue, apologies on that.

The feature I need is https://github.com/prometheus/prometheus/commit/24af5049bbf665376d8da3d72404d670cdabfa9d and rc0 was cut at https://github.com/prometheus/prometheus/commit/746820ede8c7c230477f7730a0b74459f7ff84c0.

Just to be clear and make sure we're all on the same page, I'll be attempting to upgrade based on the latter. I don't see anything in between that might be a risk (except maybe the jaeger work?).

**Comment by bwplotka** [comment]
I would say, let's aim for master/RC

**Comment by gotjosh** [comment]
Pretty sure the work done by @codesome and @pracucci addresses this?

**Comment by kakkoyun** [comment]
Closed by https://github.com/thanos-io/thanos/pull/2596 and https://github.com/thanos-io/thanos/pull/2658.
