### ISSUE TITLE
Store / Compactor UI do not work in airgapped environments

### ISSUE THREAD

**Issue by jimbobby5** [thanos-io/thanos#2539]
**Thanos, Prometheus and Golang version used**:

0.12.1

**Object Storage Provider**:

N/A

**What happened**:

Unable to load store-endpoint:/loaded/

**What you expected to happen**:

Able to see UI

**How to reproduce it (as minimally and precisely as possible)**:

Try UI without an internet connection

**Full logs to relevant components**:

```
GET https://www.gstatic.com/charts/loader.js net::ERR_NAME_NOT_RESOLVED
```
It looks like all JS is bundled in with the apps apart from this library.

**Anything else we need to know**:

**Comment by bwplotka** [comment]
Valid bug IMO, we want engineers to debug blocks while on airplane! (: 

cc @prmsrswt

**Comment by prmsrswt** [comment]
A quick solution would be to self-host the charts library. We can add the `loader.js` file with other libraries in `/pkg/ui/static/vendor/` directory.

If you like I can submit a quick PR for this.

**Comment by jimbobby5** [comment]
Sounds good to me!

**Comment by prmsrswt** [comment]
I found that locally storing the charts library is against their TOS. https://developers.google.com/chart/interactive/faq#offline

So I think we need to migrate to some other library.

**Comment by bwplotka** [comment]
Still todo (:
