### ISSUE TITLE
dev-tool: Lint/Static Analysis detecting append only slices.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2543]
Recently we made trivial bug: We forgot to clean reusable slice. Wonder if there is any technique we could detect this on CI. 

For human when we search of `duplicatedID` usages,we can clearly see it's only  defined and appended nothing more. Ref: https://github.com/thanos-io/thanos/issues/2459#issuecomment-621826378

:thinking: 

cc @pstibrany

**Comment by bwplotka** [comment]
Still to do (:

**Comment by yeya24** [comment]
This is useful. But how does the linter know whether one slice is reusable or not? That might require some comments on the slice like `lint:reusable` to note it should be reused.

**Comment by bwplotka** [comment]
This is the linter magic we need ;p Similar to how vet works.
