### ISSUE TITLE
querier: Redesign deduplication algorithm to be metric type agnostic or deduce counter type properly.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2547]
Our current short term fix ensures that we adjust deduplication for counters. This works for online dedup, but will not work for offline one, because we don't know what series is counter what is gauge etc... 

AC:
* Find better deduplication algorithm that does not require knowledge if the given series is counter or not OR reliably detect counter.

**Comment by bwplotka** [comment]
This is related to this discussion: https://github.com/thanos-io/thanos/issues/2401#issuecomment-621958839

It is also a blocker for full offline dedup: https://github.com/thanos-io/thanos/issues/1014

**Comment by bwplotka** [comment]
Some IRC discussion: https://matrix.to/#/!WaUKIfoqfiyWQhenET:matrix.org/$15883269359746PTuzR:matrix.org?via=matrix.org

**Comment by bwplotka** [comment]
Still needed (:

**Comment by bwplotka** [comment]
We seen also https://github.com/thanos-io/thanos/issues/2890 and another issue we see locally, so this seems like viable option in terms of improving existing penalty based algorithm.

**Comment by Reamer** [comment]
I think that is still needed.

**Comment by Reamer** [comment]
Still needed.

**Comment by bwplotka** [comment]
No no, Mr bot we need this, thanks for reminding.

**Comment by ankitjain28may** [comment]
Any updates on this, we are getting this issue while running `sum_over_time` on a metrics giving us double results.
