### ISSUE TITLE
TODO: Rename index cache YAML fields: type => backend, config => backend_config

### ISSUE THREAD

**Issue by pstibrany** [thanos-io/thanos#2570]
https://github.com/thanos-io/thanos/pull/2532 has introduced new cache config for caching bucket. In this PR, we use `backend` and `backend_config` YAML fields for selecting type of cache (memcached only for now), and its configuration.

This is different than what is used by index cache, where we use `type` and `config`. We would like to rename these to `backend` and `backend_config` as well at some point.

**Comment by ranjithkumar007** [comment]
This is to be done after #2532  gets merged, right?
I would like to fix this if it's ok.

**Comment by pstibrany** [comment]
> This is to be done after #2532 gets merged, right?

Yes.

> I would like to fix this if it's ok.

That would be great! Thanks.

**Comment by ranjithkumar007** [comment]
We also need to update [docs](https://thanos.io/components/store.md/#index-cache) to reflect renaming.

**Comment by ranjithkumar007** [comment]
We can close this now :)

**Comment by kakkoyun** [comment]
Closing as a result of the discussion on Slack https://cloud-native.slack.com/archives/CL25937SP/p1589816009201600.

Let us know if this is still desired.
