### ISSUE TITLE
master (future v0.13.0) Receive regression: Unexpected 2x memory usage for single tenant with multiTSDB change.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2573]
Single-tenant, similar ingestion just Thanos bump for Receiver for receive component.

`master-2020-04-23-28ea33b5` -> `master-2020-05-05-e5804d80`

![image](https://user-images.githubusercontent.com/6950331/81293622-84a93600-9065-11ea-9651-43be1fda8745.png)

A slight increase in CPU as well.

Potential reasons:
* Multi TSDB PRs https://github.com/thanos-io/thanos/pull/2564, https://github.com/thanos-io/thanos/pull/2563, https://github.com/thanos-io/thanos/pull/2557, https://github.com/thanos-io/thanos/pull/2012
*  Go 1.14

**Comment by bwplotka** [comment]
It's actually interesting pattern, potentially due to migration? 
![image](https://user-images.githubusercontent.com/6950331/81294302-95a67700-9066-11ea-9c92-7176409f5b43.png)

**Comment by brancz** [comment]
So at least for us this was an artifact of a messed up migration, we cleaned up the leftovers (which is why two identical TSDBs were running) and everything went back to normal.

**Comment by bwplotka** [comment]
Yes, this is mainly only in that case. Otherwise seems fine... except minor memory leak.

Can we for a start add `leaktest` fo all receive unit tests?
