### ISSUE TITLE
Rule: add ability to send POST requests

### ISSUE THREAD

**Issue by GiedriusS** [thanos-io/thanos#2577]
Feature request description
---

Thanos Rule currently sends everything with GET requests. We should add an option to send the requests as POST. Accordingly, the logs should be improved to also log the POST (form) parameters.

Rationale
---

The alerting / recording rules' expressions might be very long and not fit into the URI.

**Comment by yashrsharma44** [comment]
If no one is taking this issue, I am having a try :smile:

**Comment by yashrsharma44** [comment]
Hey @GiedriusS !
I was trying to wrap my head around the use case of this feature, so can you elaborate on what are the requirements and acceptance criteria for this issue?
##
Also can you elaborate more on this?
>The alerting / recording rules' expressions might be very long and not fit into the URI.

**Comment by GiedriusS** [comment]
> Hey @GiedriusS !
> I was trying to wrap my head around the use case of this feature, so can you elaborate on what are the requirements and acceptance criteria for this issue?
> 
> Also can you elaborate more on this?
> 
> > The alerting / recording rules' expressions might be very long and not fit into the URI.

There's no need for formal acceptance criteria - it's not work for us. At least for the majority of us.

Different implementations of HTTP browsers/servers have different limits on URL lengths. For example: https://technomanor.wordpress.com/2012/04/03/maximum-url-size/. How it stands right now, Thanos Rule encode everything into the URL when sending a request:

https://github.com/thanos-io/thanos/blob/2262f2601a2b04d0be7a951d1d962e698520c44e/pkg/promclient/promclient.go#L339

The recording or alerting rule might be too long and then it will get truncated when sending a request. That's why support for encoding request parameters via POST on `/api/v1/query` (and others) has been added. So:

* A new parameter needs to appear that controls whether GET or POST is used. We could theoretically convert everyone to use GET but very old versions do not support POST;
* The documentation needs to have verbiage about this;
* The tests need to be improved to test out this case.

**Comment by GiedriusS** [comment]
Still very valid & help welcome!

**Comment by jlr52** [comment]
@GiedriusS 

Hi I would love to contribute on this.

Does the ask only apply to `promclient.go` or does it apply to all queries in the repo that have post supported  in https://github.com/thanos-io/thanos/blob/0aa297bd00816ed5efe5d6dea117cb7059a3d7b1/pkg/query/api/v1.go like the following

```
	r.Get("/query", instr("query", api.query))
	r.Post("/query", instr("query", api.query))
	r.Get("/query_range", instr("query_range", api.queryRange))
	r.Post("/query_range", instr("query_range", api.queryRange))
	r.Get("/series", instr("series", api.series))
	r.Post("/series", instr("series", api.series))
	r.Get("/labels", instr("label_names", api.labelNames))
	r.Post("/labels", instr("label_names", api.labelNames))
```

**Comment by bwplotka** [comment]
It's only for Thanos Rule client side for Query API. There is no need to
change anything on server side (:

**Comment by GiedriusS** [comment]
We plan on using Thanos Ruler more at $WORK so we might just implement this not too long from now if no one else wants to take a stab at this.

**Comment by GiedriusS** [comment]
Still valid.

**Comment by mritunjaysharma394** [comment]
Hello everyone! If this issue is free to take, I would love to learn and work on this issue :smile:
