### ISSUE TITLE
query: add tests for endpoints + prefix tests

### ISSUE THREAD

**Issue by GiedriusS** [thanos-io/thanos#2582]
Coming from https://github.com/thanos-io/thanos/issues/2514#issuecomment-618513836.

We should add some similar tests to what Prometheus has here: https://github.com/prometheus/prometheus/blob/84b4d079c8714be8e8ad071a35b0391df270364c/web/web_test.go#L92. AFAICT it should be pretty easy to do:

* Refactor the route registering and starting of the HTTP server into a separate function
* Call it from a test & check all of the endpoints
* Add a test on what happens if a prefix has been specified

Should prevent https://github.com/thanos-io/thanos/issues/2581. Making a separate issue for this because this should encompass all of the endpoints that we expose to our users.

**Comment by bwplotka** [comment]
:+1: 

Help wanted

**Comment by tpaschalis** [comment]
I'll take a stab if there's no objection!

**Comment by kakkoyun** [comment]
@GiedriusS Does https://github.com/thanos-io/thanos/pull/2714 satisfy all the needs here?

**Comment by squat** [comment]
hm not quite, I think we should still test for combinations for external web prefix + web prefix. We identified last week that these are not yet completely correctly handled

**Comment by GiedriusS** [comment]
External/route prefix tests are being added in https://github.com/thanos-io/thanos/pull/2800.

**Comment by GiedriusS** [comment]
They have been added, closing.
