### ISSUE TITLE
ConsistencyDelayMetaFilter should filter on the block upload time and not the block creation time

### ISSUE THREAD

**Issue by pracucci** [thanos-io/thanos#2585]
The `ConsistencyDelayMetaFilter` filter currently filters out blocks based on the ULID time, which is the time when the block has been created:
https://github.com/thanos-io/thanos/blob/cfced59c652aca5c311baa22b519e107a20ba422/pkg/block/fetcher.go#L727

This means that if that actual consistency delay is the configured delay minus the upload time. If the delay is X but the block upload time is > X, the consistency delay is effectively ignored.

To correct approach would be checking the consistency delay against the "block upload completed timestamp" and, to do so, checking the `meta.json` creation time could be fine. However, object stores stores the "updated time" and not the "creation time", so I'm wondering how safe would be using it. Thoughts?

**Comment by bwplotka** [comment]
There was already issue for that...

**Comment by bwplotka** [comment]
I can't find this ticket ;p So let's keep this.

Definitely todo. We did not have just yet `modified` Time API in objstore that's the reason why. Modified will be just enough I think, even though creation would be better here.  The difficulty it so add working implementation of mod time to all implementations now.

We started some work in some old PRs. I think we also thought getting the `Size, ModTime`  in one method `Attr` which is common pattern.

**Comment by pracucci** [comment]
> We started some work in some old PRs. I think we also thought getting the Size, ModTime in one method Attr which is common pattern.

The problem of doing it is that we'll double the API calls for this specific use case, because most of the object stores allow to get it along with the `GET object` API call (as response HTTP headers).

How would you feel about changing the `BucketReader.Get()` signature from:
`Get(ctx context.Context, name string) (io.ReadCloser, error)`

To:
`Get(ctx context.Context, name string) (io.ReadCloser, *ObjectInfo, error)`

Where `ObjectInfo` is:
```
type ObjectInfo struct {
    Size uint64
    LastModified time.Time
}
```

With the contract that if such information are unavailable return returned `ObjectInfo` is `nil` (basically a best effort).

**Comment by pracucci** [comment]
On the other side, adding a `ObjectInfo()` function would reduce the surface change and it's also true that could be a piece of information that could be cached by https://github.com/thanos-io/thanos/pull/2579.

**Comment by pstibrany** [comment]
It seems weird for it to be part of `Get`, even when we try to optimize for number of requests (which is not a problem for all object stores). There may be legitimate use-cases to need that data without needing content of object. I think dedicated method would be better way to design this.

**Comment by pracucci** [comment]
After a brief [discussion on Slack](https://cloud-native.slack.com/archives/CL25937SP/p1589452781150800), looks there's consensus for adding the `Attributes(ctx, name) (ObjectInfo, error)` function to `BucketReader`, including `Size` and `LastModified` for now.

**Comment by bwplotka** [comment]
Still valid and actually possible thanks to recent changes. Some description why it's important you can see here: https://github.com/thanos-io/thanos/issues/2470

**Comment by bwplotka** [comment]
Question from my side: Should we cache in anyway the ModTime. I think yes.

**Comment by pstibrany** [comment]
> Question from my side: Should we cache in anyway the ModTime. I think yes.

We already cache modification time, if that’s what you’re saying.

**Comment by bwplotka** [comment]
:scream: That's perfect yes (if someone uses cache option for this).

Then it's quite easy work, marking as good first issue

**Comment by yeya24** [comment]
Valid. #2883 is open.

**Comment by pracucci** [comment]
Valid. #2883 is open.

**Comment by bwplotka** [comment]
https://github.com/thanos-io/thanos/pull/2883 still in progress.

**Comment by yeya24** [comment]
Not stale.
