### ISSUE TITLE
master (future v0.13.0): Thanos receive leaks goroutines.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2594]
We are chasing a bug that causes receiver to slowly leak memory. :hankey: 

![image](https://user-images.githubusercontent.com/6950331/81730873-1eb61780-9486-11ea-8f91-e590fd3f4d44.png)

Introduced most likely by any of  #2564, #2563, #2557, #2012 or Go 1.14 upgrade. 

cc @brancz  @squat 

Nothing obvious with leaktest: https://github.com/thanos-io/thanos/pull/2593

Let's grab some go routine dump.

**Comment by bwplotka** [comment]
Looks like it was uncutted WAL because of failed migration (we had unused tenants left behind).

**Comment by bwplotka** [comment]
![image](https://user-images.githubusercontent.com/6950331/82195654-7aeac280-98f0-11ea-986b-7170a03788c5.png)

**Comment by GiedriusS** [comment]
So we can close this, right? :P

**Comment by bwplotka** [comment]
Yes, sorry (:
