### ISSUE TITLE
Website (Hugo): Build a Versioning Plugin for Docs

### ISSUE THREAD

**Issue by thisisobate** [thanos-io/thanos#2598]
Referenced as a project topic on the [CNCF GitHub repository](https://github.com/cncf/mentoring/blob/master/communitybridge/2020/q2/project_ideas.md#versioned-website-docs), there's a huge need we look into devising a much better approach in solving the Thanos docs versioning issue. Personally, I think we can have a plugin that could easily automate the process of docs versioning on the Thanos website. You can have a look at my proposal here: https://github.com/thanos-io/thanos/pull/2554

Open questions: 

* Any ideas on how we can make the versioning process alot more better for Thanos?
* Do you think having a plugin do these things would work best?

Please your response is highly appreciated. Thank You

**Comment by bwplotka** [comment]
In making (:

**Comment by bwplotka** [comment]
@thisisobate is on it, and super close actually! (:

**Comment by thisisobate** [comment]
Done! 🤗 #2802
