### ISSUE TITLE
receive: Create proposal for backfiling on remote write

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2599]
As per our discussion [here](https://docs.google.com/document/d/165L9DVKHW0sS2PfKYsUCDikwq5XngKkCqTOVjzC6qQE/edit#heading=h.7dcto2wgvh4q) we decided to enable Remote Write backfilling.

Thoughts so far:
* Use cases: Lagging behind clusters (currently only 2h  is allowed, same with Cortex), clock skew for clusters, forgotten metrics, a batch job with old dataset, monitoring remote site. Artificial data.
* Something inefficient for a start is ok. We can aim for rare cases only. Someday as something continuous.
* Easiest would be to just open new TSDB on this case.

Help wanted, but the topic is extremely difficult. The design must-have apriori.

cc @gouthamve @pracucci  @brancz @richiH, @tomwilkie @squat

**Comment by itzg** [comment]
This use case is very important for us since even some normal amount of upstream metrics batch ingest will easily result in metrics with over an hour but within 2 hours of lag. The linked discussion in Cortex is very helpful, but ultimately doesn't help until it is implemented here in Thanos :)

**Comment by brancz** [comment]
This has also been discussed at the Prometheus dev summit. Once Prometheus implements it, we should probably follow the same strategy in Thanos. I believe it's unlikely that that will happen in the receive component, but that's a detail I believe.

**Comment by svenwltr** [comment]
Hello. Not quite sure if this issue is exactly the right one, but coming from https://github.com/thanos-io/thanos/issues/2490 I have an use case. Please tell me, if there is an ticket that fits better.

We are currently implementing [an anomaly detection](https://about.gitlab.com/blog/2019/07/23/anomaly-detection-using-prometheus/) with Thanos. It works well so far, but it is a quite complex query which needs data from up to 4 weeks ago. Due to the complexity it is more readable and has a better performance when reusing calculations by intermediate recording rules. Of course we do not have data from 4 weeks ago yet, because we just started to write the recording rules. Therefore we would need to wait full 4 weeks to be sure that the rules are working properly.

With backfilling we might be able to retrospectively calculate the recording rules and see the result immediately.

Of course we can inline most of the queries and skip the immediate recording rules, but this requires a lot of resources. Also it is impossible, when using a counter which does not have a `rate` recording rule yet, because something like `avg_over_time(rate(foobar[5m])[1w]` does not work.

<details>
  <summary>Here is an example rule file:</summary>

### The version without intermediate recording rules

```yaml
groups:
  - name: anomaly-detection-1m
    interval: 30s
    rules:
    - record: rule_action:wafsc_evaluations:rate1m:seasonal_prediction
      expr: >
        quantile(0.5,
          label_replace(
            avg_over_time(rule_action:wafsc_evaluations:rate1m[4h] offset 166h)
            + avg_over_time(rule_action:wafsc_evaluations:rate1m[1w])
            - avg_over_time(rule_action:wafsc_evaluations:rate1m[1w] offset 1w)
            , "offset", "1w", "", "")
          or
          label_replace(
            avg_over_time(rule_action:wafsc_evaluations:rate1m[4h] offset 334h)
            + avg_over_time(rule_action:wafsc_evaluations:rate1m[1w])
            - avg_over_time(rule_action:wafsc_evaluations:rate1m[1w] offset 2w)
            , "offset", "2w", "", "")
          or
          label_replace(
            avg_over_time(rule_action:wafsc_evaluations:rate1m[4h] offset 502h)
            + avg_over_time(rule_action:wafsc_evaluations:rate1m[1w])
            - avg_over_time(rule_action:wafsc_evaluations:rate1m[1w] offset 3w)
            , "offset", "3w", "", "")
        ) without (offset)

    - record: rule_action:wafsc_evaluations:rate1m:seasonal_prediction:z_score
      expr: >
        (
          rule_action:wafsc_evaluations:rate1m
          - rule_action:wafsc_evaluations:rate1m:seasonal_prediction
        ) / stddev_over_time(rule_action:wafsc_evaluations:rate1m[1w])
```

### The optimized version

```yaml
groups:
  - name: anomaly-detection-1m
    interval: 30s
    rules:
    - record: rule_action:wafsc_evaluations:rate1m:avg_over_time_1w
      expr: avg_over_time(rule_action:wafsc_evaluations:rate1m[1w])

    - record: rule_action:wafsc_evaluations:rate1m:stddev_over_time_1w
      expr: stddev_over_time(rule_action:wafsc_evaluations:rate1m[1w])

    - record: rule_action:wafsc_evaluations:rate1m:z_score
      expr: >
        (
          rule_action:wafsc_evaluations:rate1m -
          rule_action:wafsc_evaluations:rate1m:avg_over_time_1w
        ) / rule_action:wafsc_evaluations:rate1m:stddev_over_time_1w

    - record: rule_action:wafsc_evaluations:rate1m:seasonal_prediction
      expr: >
        quantile(0.5,
          label_replace(
            avg_over_time(rule_action:wafsc_evaluations:rate1m[4h] offset 166h)
            + rule_action:wafsc_evaluations:rate1m:avg_over_time_1w
            - rule_action:wafsc_evaluations:rate1m:avg_over_time_1w offset 1w
            , "offset", "1w", "", "")
          or
          label_replace(
            avg_over_time(rule_action:wafsc_evaluations:rate1m[4h] offset 334h)
            + rule_action:wafsc_evaluations:rate1m:avg_over_time_1w
            - rule_action:wafsc_evaluations:rate1m:avg_over_time_1w offset 2w
            , "offset", "2w", "", "")
          or
          label_replace(
            avg_over_time(rule_action:wafsc_evaluations:rate1m[4h] offset 502h)
            + rule_action:wafsc_evaluations:rate1m:avg_over_time_1w
            - rule_action:wafsc_evaluations:rate1m:avg_over_time_1w offset 3w
            , "offset", "3w", "", "")
        ) without (offset)

    - record: rule_action:wafsc_evaluations:rate1m:seasonal_prediction:z_score
      expr: >
        (
          rule_action:wafsc_evaluations:rate1m
          - rule_action:wafsc_evaluations:rate1m:seasonal_prediction
        ) / rule_action:wafsc_evaluations:rate1m:stddev_over_time_1w

```
</details>

**Comment by brancz** [comment]
There is work on [retroactive rule evaluations happening on Prometheus](https://github.com/prometheus/prometheus/issues/11) already. Once that's figured out there we'll probably implement the same mechanism in Thanos. We look at backfilling data more as a thing for retrofitting non Prometheus data into the system, retroactive rule evaluations may make use of the same infrastructure but should be a first class feature, at least eventually.

**Comment by sepich** [comment]
For those who found this issue via search: thanks to @bwplotka and @dipack95 work [on prometheus side](https://github.com/prometheus/prometheus/pull/7586) it is now possible to import custom data in prometheus text format into Thanos via https://github.com/sepich/thanos-kit/ `import` command. 
(It is currently reading all the imported data to memory, hope the feature would be implemented better in upstream version. Unfortunately we need this "yesterday" so can't wait anymore ;)

**Comment by bwplotka** [comment]
Currently, we have lots of backfill solutions that rely on block upload. We should invest in them and make them better.

BUT, this issue is for remote write backfill, which is in [dev and design by the amazing Grafana team!](https://docs.google.com/document/d/1Kppm7qL9C-BJB1j6yb6-9ObG3AbdZnFUBYPNNWwDBYM/edit). PTAL there.

**Comment by yeya24** [comment]
Since the OOO feature has been merged into main, I will close this issue. Feel free to reopen if you think it is not addressed.
