### ISSUE TITLE
Test CI for false positives.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2606]
Currently with have bug where `make docs` does not generate flags correctly. So we could put whatever in flags and it was not autogenerated, causing `make check-docs` to be always green.

Let's create some tests for our CI. I would propose a separate github action that will on purpose change some flag in code and expect `make check-docs` to fail. Maybe overengineering? But it's so easy to trust something and not notice it does not work... ):

**Comment by daixiang0** [comment]
Which bug? Is there any example or log about this?

**Comment by bwplotka** [comment]
Nope, not fixed yet.
