### ISSUE TITLE
query: Staleness problem

### ISSUE THREAD

**Issue by IKSIN** [thanos-io/thanos#2608]
**Thanos, Prometheus and Golang version used**:
thanos: v0.12.0

**Object Storage Provider**:
private CEPH (S3)

**What happened**:
See on `end_input` time and `resolution`:
<img width="1421" alt="Снимок экрана 2020-05-14 в 16 34 52" src="https://user-images.githubusercontent.com/2960110/81941650-c99f1080-9601-11ea-8588-d663b429de14.png">
<img width="1423" alt="Снимок экрана 2020-05-14 в 16 35 02" src="https://user-images.githubusercontent.com/2960110/81941676-cefc5b00-9601-11ea-8bd2-f6a2fda1be25.png">
Staleness functionality in prometheus library get rid of some points returned from thanos-stores.

**What you expected to happen**:
Return all data from store on any time_range

**How to reproduce it (as minimally and precisely as possible)**:
see on screenshots.

**Full logs to relevant components**:

**Anything else we need to know**:
I think, that we have few ways to resolve problem:
1. Update prometheus library and set `LookbackDelta` parameter > 5 min (need check)
2. Update query and move/duplicate points to needed timestamp. (Interpolate data for PromQL)
3. Update prometheus library to return all points from stores.

**Comment by daixiang0** [comment]
What is the ceph version?

**Comment by IKSIN** [comment]
CEPH does not matter, because thanos-stores return all data to query, and only in prometheus library points marked as staleness.

**Comment by bwplotka** [comment]
Nice, thanks for this. Funnily enough we just talked about this exact problem with @juliusv (: 

We need different lookbackDelta for different resolution I think, right? @juliusv

**Comment by bwplotka** [comment]
ref: https://matrix.to/#/!WaUKIfoqfiyWQhenET:matrix.org/$1589300436157120ZqIrC:matrix.org?via=matrix.org

**Comment by juliusv** [comment]
At a minimum, it would be good to add the `--query.lookback-delta` that we have in Prometheus to Thanos as well. However, since it's a global setting, it would apply to all time series, even the ones that are scraped a intervals <5m. Normally you wouldn't want to set this lookback delta higher than needed for everything, as that will result in old samples being returned for quite long (although explicit staleness markers already help with that).

**Comment by IKSIN** [comment]
I think that we need in dynamic lookback-delta inpdepended on resolution, forexample resolution/2.

**Comment by bwplotka** [comment]
Well. The main problem is that we can use different resolution in single PromQL eval (: 

So it can be [1h of raw data, 2w of 1h resolution, and 5h of 5m resolution] combined.

So I think we might need to think of something in the PromQL itself. @brian-brazil do you know how hard would be that?

Also we can temporarily add lookback delta per query as well :thinking:

**Comment by brian-brazil** [comment]
Varying resolution within one query is unlikely to wrok. What I'd do is present that to PromQL that looks real from the downsampled data - e.g. here you might provide interpolated samples every 1m.

It kinda depends on what the query is though.

**Comment by IKSIN** [comment]
@bwplotka @brian-brazil
Can we choose solution as soon as possible? I'm work on this problem now, and can to implement both solutions...

**Comment by bwplotka** [comment]
Can you elaborate more @brian-brazil ? So essentially you would actually for each downsampled data, actually expand it to have samples every 1m, fake interval? :thinking: 

What would be the corner cases? Why it depends on query?


Alternatively we could have 3 PromQL engines in Querier and chose what to use based on the returned data. Then we can evaluate for the given periods and contact the results. However for large steps and intervals, it would be most likely bad....

**Comment by brian-brazil** [comment]
> So essentially you would actually for each downsampled data, actually expand it to have samples every 1m, fake interval

Yes, something like that.

> Why it depends on query?

For e.g. sum_over_time you need different data than count_over_time to produce the desired result.

**Comment by bwplotka** [comment]
Looks like @IKSIN we could try that in `querier.go`

**Comment by IKSIN** [comment]
Ok! I try do it )

**Comment by bwplotka** [comment]
I am pretty sure we need special iterator for downsampled chunks.

**Comment by bwplotka** [comment]
> For e.g. sum_over_time you need different data than count_over_time to produce the desired result.

This is already well handled.

**Comment by d-ulyanov** [comment]
we still work on this, let's reopen

**Comment by bwplotka** [comment]
BTW do you know we can now stalenees Lookback delta?

However we might want to adjust it for different resolutions indeed

**Comment by d-ulyanov** [comment]
@bwplotka As I remember staleness lookback delta is not something new. Or it was changed recently somehow?

**Comment by bwplotka** [comment]
We just allow users to configure it on Querier from flag that's it.

**Comment by krya-kryak** [comment]
> BTW do you know we can now configure stalenees Lookback delta?
> 
> However we might want to adjust it for different resolutions indeed

Well, here's my attempt at it: https://github.com/thanos-io/thanos/pull/3277
