### ISSUE TITLE
How to decode chunks and get readable characters ?

### ISSUE THREAD

**Issue by nissrinchanisse** [thanos-io/thanos#2609]
**Object Storage Provider**:   GC

**What happened**:   encoding issue

I'm using python and getting the blocks in google cloud bucket  

I would like to know how can I decode chunks and what is their encoding.

Any help please ?

**Comment by bwplotka** [comment]
What chunks you have in mind? You can read exact block format here: https://github.com/prometheus/prometheus/tree/master/tsdb/docs/format :thinking: 

Curious what you are working on! (: 

Closing for now, feel free to ask follow up questions here or on slack.

**Comment by nissrinchanisse** [comment]
I would like to know what is the encoding of the chunks files stored in a GC bucket as octect-stream , and how to decode the data and get readable tsdb

**Comment by bwplotka** [comment]
Everything is inside: https://github.com/prometheus/prometheus/tree/master/tsdb/docs/format
