### ISSUE TITLE
.*: Elastic APM Go Agent is enabled even without tracing configuration

### ISSUE THREAD

**Issue by Sayrus** [thanos-io/thanos#2610]
**Thanos, Prometheus and Golang version used**: Thanos v0.12.2, Go 1.13.1 (quay.io/thanos/thanos:v0.12.2)

**Object Storage Provider**: Not relevant

**What happened**:
While investigating a bug with Elastic APM and Thanos, I found out that the Go Agent initialize itself (through `init()` in tracer.go) even if no tracer has been selected in Thanos.
This means that the if environment variables are provided, the agent start sending metrics (not traces) to Elastic APM-Server.

Moreover, this means that Elastic APM Agent configures itself with values from environment when they should be provided by Thanos Configuration. One example is the service_name. Elastic APM will default to `thanos` (automatically determined binary name, which is a problem: is it thanos-query? thanos-sidecar? ...) and update it once the Tracer is initialized by Thanos.
This lead to another bug where metrics are still scrapped with the wrong name because it is not properly updated (or deleted?). See elastic/apm-agent-go#770

As the default tracer of Elastic APM is `active`, it begins gathering metrics.
It will gather metrics even if no Elastic Server is configured and send them to localhost.

**What you expected to happen**:
Elastic-APM Agent should not start gathering metrics and send them unless explicitly enabled.

**How to reproduce it (as minimally and precisely as possible)**:
Configure only `ELASTIC_APM_SERVER_URL` and `ELASTIC_APM_SECRET_TOKEN` (if needed) and run Thanos. Elastic APM will receive Go Metrics from `thanos`.

Configure only `ELASTIC_APM_LOG_FILE` to `stdout` and `ELASTIC_APM_LOG_LEVEL` to `debug`
```
{"level":"debug","time":"2020-05-14T15:28:44Z","message":"gathering metrics"}
```
Elastic Agent is now gathering metrics to send them ... nowhere. 

**Full logs to relevant components**:
I don't know what to provide in this case, this should be enough:

<details>Logs
<p>

```
level=info ts=2020-05-14T15:28:14.065137206Z caller=main.go:152 msg="Tracing will be disabled"
{"level":"error","time":"2020-05-14T15:28:15Z","message":"config request failed: sending config request failed: Get http://localhost:8200/config/v1/agents?service.name=thanos: dial tcp 127.0.0.1:8200: connect: connection refused"}
{"level":"debug","time":"2020-05-14T15:28:44Z","message":"gathering metrics"}
{"level":"debug","time":"2020-05-14T15:28:44Z","message":"request failed: sending event request failed: Post http://localhost:8200/intake/v2/events: dial tcp 127.0.0.1:8200: connect: connection refused (next request in ~0s)"}
{"level":"debug","time":"2020-05-14T15:29:14Z","message":"gathering metrics"}
{"level":"debug","time":"2020-05-14T15:29:14Z","message":"request failed: sending event request failed: Post http://localhost:8200/intake/v2/events: dial tcp 127.0.0.1:8200: connect: connection refused (next request in ~1s)"}
{"level":"debug","time":"2020-05-14T15:29:44Z","message":"gathering metrics"}
{"level":"debug","time":"2020-05-14T15:29:45Z","message":"request failed: sending event request failed: Post http://localhost:8200/intake/v2/events: dial tcp 127.0.0.1:8200: connect: connection refused (next request in ~4s)"}
{"level":"debug","time":"2020-05-14T15:30:14Z","message":"gathering metrics"}
{"level":"debug","time":"2020-05-14T15:30:17Z","message":"request failed: sending event request failed: Post http://localhost:8200/intake/v2/events: dial tcp 127.0.0.1:8200: connect: connection refused (next request in ~9s)"}
{"level":"debug","time":"2020-05-14T15:30:44Z","message":"gathering metrics"}
{"level":"debug","time":"2020-05-14T15:30:53Z","message":"request failed: sending event request failed: Post http://localhost:8200/intake/v2/events: dial tcp 127.0.0.1:8200: connect: connection refused (next request in ~16s)"}
{"level":"debug","time":"2020-05-14T15:31:14Z","message":"gathering metrics"}
{"level":"debug","time":"2020-05-14T15:31:28Z","message":"request failed: sending event request failed: Post http://localhost:8200/intake/v2/events: dial tcp 127.0.0.1:8200: connect: connection refused (next request in ~25s)"}
{"level":"debug","time":"2020-05-14T15:31:44Z","message":"gathering metrics"}
```

</p>
</details>

**Anything else we need to know**:
If you need more information, feel free to ask.

I don't know if this can be solved by force disabling the Agent features before importing it or if I need to forward the problem to apm-agent-go. I'll open an issue there for the duplicate metrics.

Best regards,

**Comment by axw** [comment]
The simplest fix for this would be to add

```go
func init() {
    apm.DefaultTracer.Close()
}
```

in https://github.com/thanos-io/thanos/blob/master/pkg/tracing/elasticapm/elastic_apm.go

**Comment by bwplotka** [comment]
Looks like some terrible choice for library to do that ): 

Help wanted! I think @axw fix makes sense to me.

**Comment by axw** [comment]
> Looks like some terrible choice for library to do that ):

I kind of agree, but it's like this because it's optimised for instrumenting CRUD web apps, configured through environment variables. A little more colour in https://github.com/elastic/apm-agent-go/issues/770 if you care.

> Help wanted!

I'll send a PR next week, unless @Sayrus would like to take it.

**Comment by Sayrus** [comment]
@axw I used your snippet to create a PR. I think I can handle the follow-up of this issue.
