### ISSUE TITLE
Kudos semi-automation

### ISSUE THREAD

**Issue by homelessnessbo** [thanos-io/thanos#2617]
Henlo frens!

As discussed at previous [Thanos community meeting](https://docs.google.com/document/d/165L9DVKHW0sS2PfKYsUCDikwq5XngKkCqTOVjzC6qQE/edit#) on 13.05.2020 - we want to bring back the Friday shout-out process as it brings good value to the community and cheers up those brave souls who help other hopelessly lost in Thanos/Prometheus world seeking for help in CNCF slack channel.

Though, I know from experience it might be quite a tideous thing to do manually, especially now when community slack channel rolled over 1k members and amount of support demanded and provided is overwhelming. 

The basic idea I suggest here is:

* Choose a kudos tool. Some slack `/`-bot, there are dozens of them on the market. Problem with that one - most of them cost some moniz and with 1k users in the channel - it gets costly for a wallet of a mere mortal. 
So maybe it is worth setting up something like cloud function (here's [the simplest example](https://medium.com/@rav3n/building-a-serverless-acronym-bot-on-gcp-using-cloud-functions-bdbc3b47ca20)) that will catch webhooks and paste data with kudo-recipient to somewhat that can handle few lines of text for free? (Anything that can just hold few lines of text up to nearest coming Friday?) Most of the serverless platforms have some "free daily limit" that shall be hundreds of times higher than the capacity we actually need.
* Set up [Slack Workflow](https://slack.com/intl/en-nl/help/articles/360035692513-Guide-to-Workflow-Builder) greeting every new channel member with **non-overloaded** message about kudos possibility.
* Humanised shout-out every Friday to all the kudos recipients (Shall not be performed by a bot and shall not be bold copy-paste of the previous message, put some soul in it!) + little reminder that we have kudos in place and it would be amazing if everybody would use it. 

Let's discuss this. Anybody know free ready kudos tool?
What is our possibility to buy one?
What is our possibility to set up something small and cheap/free in some public cloud under some non-personal project?

**Comment by bwplotka** [comment]
Super nice, thanks for this, help wanted! (:

**Comment by bwplotka** [comment]
Thanks, but no, we need this. Help wanted. Hackathon offer still applies
Ivan ;p

**Comment by bwplotka** [comment]
@homelessnessbo :beers:  :beers:  :beers: Let's hack on this some day (:

**Comment by bwplotka** [comment]
We are on it @homelessnessbo 

![](https://media2.giphy.com/media/MM0Jrc8BHKx3y/giphy.gif)
