### ISSUE TITLE
Clarify which Prometheus versions are supported in the documentation

### ISSUE THREAD

**Issue by mattbostock** [thanos-io/thanos#262]
The documentation mentions Prometheus 2.0 storage (as opposed to, say, 2.x) yet the 'bucket verify' command checks for issues in later Prometheus versions.

We should clarify the documentation to be more explicit about which versions are supported.

**Comment by daixiang0** [comment]
@bwplotka it have bee clarified in getting-started.md:
```
* One or more [Prometheus](https://prometheus.io) v2.2.1+ installations with persistent disk.
```
