### ISSUE TITLE
Enabling compaction in prometheus for performance improvements

### ISSUE THREAD

**Issue by crsandeep** [thanos-io/thanos#2620]
Currently we have to disable compaction in prometheus for thanos sidecar to be able to upload blocks to object store. It would help in certain to enable compaction.

In our case we store data in prometheus for longer duration (up to a month). For any queries requiring less than 1 month data we use prometheus and for long term queries we use thanos. In these kind of cases it would be nice to have compaction enabled in prometheus so that prometheus performance will improve. This could also potentially help with performance in cases where we want to retain data longer in prometheus (lets say 1 month) and have sidecar store API serve data from tsdb and then have thanos store serve data for (1 month - infinite).

**Comment by Kampe** [comment]
We would also like the ability to store blocks locally for a duration for queries on "edge" sites to be useful.

**Comment by yeya24** [comment]
Still valid.

**Comment by fpytloun** [comment]
And how to enable it? If I remove `storage.tsdb.min-block-duration=2h`, sidecar fails:
```
level=error ts=2021-10-09T15:54:48.485314305Z caller=main.go:157 err="found that TSDB Max time is 3d and Min time is 2h. Compaction needs to be disabled (storage.tsdb.min-block-duration = storage.tsdb.max-block-duration)\nmain.validatePrometheus\n\t/home/circleci/project/cmd/thanos/sidecar.go:354\nmain.runSidecar.func3\n\t/home/circleci/project/cmd/thanos/sidecar.go:151\ngithub.com/oklog/run.(*Group).Run.func1\n\t/home/circleci/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\nvalidate Prometheus flags\nmain.runSidecar.func3\n\t/home/circleci/project/cmd/thanos/sidecar.go:152\ngithub.com/oklog/run.(*Group).Run.func1\n\t/home/circleci/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\nsidecar command failed\nmain.main\n\t/home/circleci/project/cmd/thanos/main.go:157\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"
```

**Comment by fpytloun** [comment]
Tried another solution - using Minio gateway with disk cache and point thanos-store to use it: https://docs.min.io/docs/minio-disk-cache-guide.html

**Comment by yeya24** [comment]
After another thought, I think it is already done to enable local compaction for Prometheus and it is safe. On the sidecar side, we just need to have `--shipper.ignore-unequal-block-size` flag to disable the check.
The shipper just uploads compaction level 1 block only to the object storage, which is by default.

**Comment by yeya24** [comment]
https://github.com/thanos-io/thanos/blob/main/docs/components/sidecar.md#sidecar 

> The --storage.tsdb.min-block-duration and --storage.tsdb.max-block-duration must be set to equal values to disable local compaction on order to use Thanos sidecar upload, otherwise leave local compaction on if sidecar just exposes StoreAPI and your retention is normal. The default of 2h is recommended. Mentioned parameters set to equal values disable the internal Prometheus compaction, which is needed to avoid the uploaded data corruption when Thanos compactor does its job, this is critical for data consistency and should not be ignored if you plan to use Thanos compactor.

I am not sure why there is a data corruption problem. For local Prometheus compaction, the compaction planning will exclude the freshest block so the newly created block won't be compacted in a time window (at least 2h). 

So for the sidecar shipper, it has 2h window to upload the new block. Unless it is done for > 2h then enabling local compaction is safe I guess.

**Comment by pvlltvk** [comment]
@yeya24 
Hi!
Sorry for the ping in the really old thread, but seems like it's the best thread to discuss. I'm thinking about enabling compaction but on Thanos Receive, not Prometheus. So 2 questions:
1. Am I right that the compaction process in Thanos Receive works in the same manner as in Prometheus? So basically it seems safe to have compaction in Thanos Receive in general
2. If Thanos Receive doesn't manage to send a new block to S3 for 2h and local compaction happens - what's the consequence of this? If Receive sends only block with compaction level 1 to S3 - seems like the worst case here is that the source block can be possibly removed by Thanos Receive, right?
