### ISSUE TITLE
ci/test: Flaky reloader test.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2622]
https://circleci.com/gh/thanos-io/thanos/9139?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

I remember @lilic was touching this test lately, so you mavbe you have idea? I  did not check closer yet (:

**Comment by lilic** [comment]
Was I? :) I was touching the rule test, not reloader one. https://github.com/thanos-io/thanos/blob/master/pkg/reloader/reloader_test.go#L167 If you think it's related to my changes, I can have a look, but did not touch that test specifically.

**Comment by bwplotka** [comment]
Ack, no worries, just yolo ping

**Comment by bwplotka** [comment]
Still very valid: https://circleci.com/gh/thanos-io/thanos/9566?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by cuotos** [comment]
Has anyone been able to replicate this anywhere other than circle?

**Comment by bwplotka** [comment]
Not really - it's just slow CI. Looking on this now

**Comment by bwplotka** [comment]
The problem is that's it's time based: 

```
	reloadsSeen := 0
		for {
			select {
			case <-ctx.Done():
				return
			case <-time.After(300 * time.Millisecond):
			}

			rel := reloads.Load().(int)
			if rel <= reloadsSeen {
				continue
			}
```

**Comment by bwplotka** [comment]
Fixed https://github.com/thanos-io/thanos/pull/2874

**Comment by kakkoyun** [comment]
Re-opening this issue again. Reloader test become flaky again.

**Comment by bwplotka** [comment]
Valid and flaky still.

Kind Regards,
Bartek Płotka (@bwplotka)

**Comment by bwplotka** [comment]
Let's get into this (: It's still causing problems: https://github.com/thanos-io/thanos/issues/2622
