### ISSUE TITLE
querier: Add deduplication + promSeries micro benchmarks, consider moving to heap sort for sorting chunks + dedup chunks first

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2626]
While doing work on deduplication I saw opportunity to make it much faster, some work need to be done on that. (: 

Saving for future.

**Comment by bwplotka** [comment]
Connected to https://github.com/thanos-io/thanos/issues/2303

**Comment by bwplotka** [comment]
And: https://github.com/thanos-io/thanos/issues/981

**Comment by yeya24** [comment]
Is this still valid and what's the action item?
