### ISSUE TITLE
Thanos can not work with geras ?

### ISSUE THREAD

**Issue by Jamlee** [thanos-io/thanos#2639]
I get the error msg:

```
level=warn ts=2020-05-21T18:15:12.582364511Z caller=storeset.go:429 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from geras:19000: rpc error: code = Unknown desc = No such name for 'metrics': 'tsd.rpc.received'" address=geras:19000
```

![image](https://user-images.githubusercontent.com/5196641/82591702-55043d00-9bd2-11ea-8aa6-2d9d631b0a13.png)

this is my docker-compose.yml
![image](https://user-images.githubusercontent.com/5196641/82591821-7cf3a080-9bd2-11ea-8aea-513b219e187b.png)

**Comment by GiedriusS** [comment]
Hi! Does it work with v0.12.2?

**Comment by Jamlee** [comment]
@GiedriusS let me try it agent.

**Comment by Jamlee** [comment]
solve it, https://github.com/G-Research/geras/issues/78
