### ISSUE TITLE
Is prometheus 2.0 supported?

### ISSUE THREAD

**Issue by Jamlee** [thanos-io/thanos#2640]
promtheus is too old for in result to some dashbaord in grafan in error.

![image](https://user-images.githubusercontent.com/5196641/82645210-19568b00-9c45-11ea-8619-90164b2d8a7b.png)

**Comment by metalmatze** [comment]
If at all, this is a Prometheus or Grafana question. 🙃
Prometheus 2.0 indeed is really old and there shouldn't be big blockers to upgrade to 2.17+.

**Comment by Jamlee** [comment]
@metalmatze Does thannos embed the promtheus 1.18 ?

**Comment by metalmatze** [comment]
Thanos is mostly up to date with the latest Prometheus. 😎

**Comment by Jamlee** [comment]
@mengskysama https://github.com/thanos-io/thanos/blob/134ef5d39728598d37a0bbfa58e42b5a6407cfa8/go.mod#L75

looks like the promtheus package is 1.18 .
