### ISSUE TITLE
Queries with 6 months range fetches only 5m blocks

### ISSUE THREAD

**Issue by d-ulyanov** [thanos-io/thanos#2641]
**Thanos, Prometheus and Golang version used**:
Thanos v0.12

**What happened**:
Steps:
- I opened dashboard for the last 6 months - data loaded just for the last 3 months (retention for 5m)
- Step sent to Thanos was 10800
- According to `step / 5`  Thanos queried only 5m blocks (Grafana calculated that I need ~1400 data points for 6 months, step 3h or 10800s)

Currently, Thanos uses `step / 5` for max source resolution:
```
maxSourceResolution, apiErr := api.parseDownsamplingParamMillis(r, step/5)
```

**What you expected to happen**:
I expect to see all data that I have in Object storage, doesn't matter in what resolution this data is.

Maybe it would be better to force loading 1h block if we definitely know that we don't have 5m for the requested time range and interpolate data points?

cc @bwplotka @IKSIN @krya-kryak

**Comment by d-ulyanov** [comment]
still reproducible

**Comment by d-ulyanov** [comment]
still reproducible

**Comment by d-ulyanov** [comment]
still actual

**Comment by kakkoyun** [comment]
@d-ulyanov Is this still valid? Have you tried with more recent version?

**Comment by d-ulyanov** [comment]
Is anything was done to fix it in recent versions?
It is still valid, yes.

**Comment by d-ulyanov** [comment]
not fixed yet :(

**Comment by d-ulyanov** [comment]
https://github.com/thanos-io/thanos/pull/3723 was merged, let's close this issue. 

@bwplotka could you add fix version to this issue?
