### ISSUE TITLE
store, compact: perfoming vast amounts of exist S3 calls

### ISSUE THREAD

**Issue by JensErat** [thanos-io/thanos#2643]
**Thanos, Prometheus and Golang version used**: 0.12.2, also master code

**Object Storage Provider**: S3

**What happened**:

We're running a larger Thanos setup. The S3 operations team sent us a notice we'd be executing very large numbers of S3 requests and asked for analysis.

We have been able to discover that most of those queries are exist calls, which both store and compact run to keep the index updated. In our case, this sums up to close to a million exist queries per hour over all thanos instances. By setting `--sync-block-duration=30m` we have been able to massively reduce the number of exist calls by a factor of ~10 (compact still doing lots of calls because of #2642).

**What you expected to happen**:

Reasonable number of calls. Although those calls are cheap in AWS (something like 5-10USD/day for this large system), on-prem systems might have different scalability and pricing (whether charged or not). And those calls put unnecessary load on thanos-store.

**How to reproduce it (as minimally and precisely as possible)**:

Explained in `fetcher.go:208`:

    // For 1y and 100 block sources this generates ~1.5-3k HEAD RPM. AWS handles 330k RPM per prefix.

The _really_ large number occurs because we use thanos store sharding with ~10 shards per thanos cluster, such that all the exist operations are executed ten times (as I understand, the relabel filter is applied after the exist calls are run). In each sync interval, thanos-store runs exists for each block, no matter which shard it belongs to. We have >>1y of data in S3.

**Full logs to relevant components**:

**Anything else we need to know**:

Some thoughts:

- I guess some quick win and large benefit would be to remember non-matching blocks on a best-effort base. Something like a in-memory hashmap that gets filled whenever we realize a block is not matching our selector. When listing the S3 bucket during sync operations, we could easily and cheaply match against this hashmap and filter checking existence for blocks that we will never care about anyway (ie.: just run exist once per thanos-store instance and block we don't care about). I was skimming through the code for some minutes, and it looks like we'd have to introduce some new dependencies between packages. I'd be fine with putting together some lines of codes if you can point me towards where we'd put this hashmap (or similar structure like timeout cache such that we do not have a memory leak if store runs for very long time and compact prunes lots of blocks, but I guess that's not really worth the effort).
- I guess one might even be able to provide some better heuristics. We will realize a block is gone if reading it fails (so we'd only need to scan for new blocks)? This might even enable skipping the whole exists-part entirely and just checking for new blocks (compare timestamps when listing the bucket). Might be more involved though. The directory listing is cheap again and could be run pretty often.
- Currently we have about one month of data available in Prometheus. compact has the default delete delay of 48h. I guess we could even safely increase the 30m refresh window to something <48h -- newer data is available in Prometheus anyway, and we will fetch compacted data in time anyway. Am I right with this?

**Comment by bwplotka** [comment]
We are aware and I believe it was fixed by more caching with memcached: https://github.com/thanos-io/thanos/issues/2389

If you experience this API burden I would recommend trying v0.13.0-rc.0 with that cache enabled (:

**Comment by bwplotka** [comment]
Let us know if this fixes the problem!

**Comment by bwplotka** [comment]
We recommend memcached for other cache items as well

**Comment by JensErat** [comment]
memcached resolved the issue indeed, s3 usage dropped massively for thanos-store. Just leaves the similar issue in compactor where @chrischdi already proposed a PR.
