### ISSUE TITLE
Docs: Pull Request Process described in CONTRIBUTING.md doesn't work as expected

### ISSUE THREAD

**Issue by prmsrswt** [thanos-io/thanos#2651]
The Pull Request Process as described in CONTRIBUTING.md gives us following steps:
```
$ mkdir -p $GOPATH/src/github.com/thanos-io
$ cd $GOPATH/src/github.com/thanos-io
$ git clone https://github.com/<your_github_id>/thanos.git
$ cd thanos
$ git remote add upstream https://github.com/thanos-io/thanos.git
$ git remote update
$ git merge upstream/master
$ make build
$ ./thanos -h
```

There are some minor problems here.

```
$ mkdir -p $GOPATH/src/github.com/thanos-io
```
In most of the cases, the environment variable GOPATH isn't set, so this command tries to create a folder at `/src/github.com/thanos-io` which is not what we want.
A possible solution is to run `GOPATH=$(go env GOPATH)` first.

Also, as we use Go modules we actually don't need to clone the repo inside the GOPATH, it works fine irrespective of the folder's location.

```
$ make build
$ ./thanos -h
```
Here, `./thanos -h` fails because after #2611 the `make build` outputs the `thanos` binary in `$GOBIN` instead of the current folder. Maybe we can run this using `$GOPATH/bin/thanos -h` but I guess the proper way would be to have the `$GOPATH/bin` directory in the `PATH` variable.

**Comment by prondubuisi** [comment]
Very correct @prmsrswt had this same exact issues!

**Comment by daixiang0** [comment]
@prmsrswt would you like to fix this?

**Comment by prmsrswt** [comment]
Yes, of course. I created this issue because I wanted to discuss first.
