### ISSUE TITLE
Store: Memory usage spikes on startup

### ISSUE THREAD

**Issue by nirlo** [thanos-io/thanos#2672]
**Thanos, Prometheus and Golang version used**:
v0.12.0

**Object Storage Provider**: s3

**What happened**:

We've recently moved out Thanos deployment from one cluster to another. We have a fairly large network of prometheus instances and Thanos sidecars; 5 clusters that span production deployments, 10s of review environments, exporters, and gitlab runners.

Before we moved the deployment, all components were running smoothly on version v0.11

We've had a similar issue in the past, scaling the size of the node to a `32gb` instance helped. 

These now live is in a similar instance and all other components works as expected, but the Store continuously attempts to use more memory than the node has and the pod crashes. There are no relevant logs unfortunately. The pod crashes repeatedly.

<img width="1601" alt="Screen Shot 2020-05-27 at 12 09 07 PM" src="https://user-images.githubusercontent.com/21220901/83045036-0a8c2180-a013-11ea-8d55-200b77a85e1b.png">

**What you expected to happen**:
Small spike in memory and the usage to simmer

**How to reproduce it (as minimally and precisely as possible)**:
Deploying Thanos store

**Full logs to relevant components**:
```
level=info ts=2020-05-27T15:53:01.298655367Z caller=main.go:152 msg="Tracing will be disabled"
level=info ts=2020-05-27T15:53:01.298780179Z caller=factory.go:46 msg="loading bucket configuration"
level=info ts=2020-05-27T15:53:01.299095946Z caller=inmemory.go:172 msg="created in-memory index cache" maxItemSizeBytes=131072000 maxSizeBytes=262144000 maxItems=math.MaxInt64
level=info ts=2020-05-27T15:53:01.299489125Z caller=options.go:23 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2020-05-27T15:53:01.299800782Z caller=store.go:314 msg="starting store node"
level=info ts=2020-05-27T15:53:01.300035828Z caller=intrumentation.go:64 msg="changing probe status" status=healthy
level=info ts=2020-05-27T15:53:01.300065118Z caller=http.go:56 service=http/server component=store msg="listening for requests and metrics" address=0.0.0.0:10902
level=info ts=2020-05-27T15:53:01.300243902Z caller=store.go:269 msg="initializing bucket store"
level=info ts=2020-05-27T15:53:02.819997488Z caller=fetcher.go:368 component=block.MetaFetcher msg="successfully fetched block metadata" duration=1.519702825s cached=188 returned=188 partial=0
```

**Anything else we need to know**:

configuration:
```
      store
      --log.level=info
      --index-cache-size=250MB
      --chunk-pool-size=6GB
      --objstore.config=type: S3
      config:
        bucket: *************
        endpoint: s3.amazonaws.com
```

**Environment**:
- kubernetes deployment

**Comment by nirlo** [comment]
I've attempted using the index cache as well to see if that would eliminate some of the issues as well, but the same rise and eventual eviction happens

**Comment by GiedriusS** [comment]
Unfortunately but some growth in RAM consumption at boot time is inevitable because Thanos needs to build binary index headers from the index files themselves. This can be mitigated a bit by lowering `--block-sync-concurrency` on Thanos Store to a lower number so that it would not try to sync so many blocks at once.
