### ISSUE TITLE
Frequent 404s from sidecar for local TSDB blocks

### ISSUE THREAD

**Issue by filippog** [thanos-io/thanos#2686]
Thanos 0.13.0rc0
Prometheus 2.7.1 from Debian
golang 1.14.3

```
thanos, version 0.13.0-rc.0 (branch: non-git, revision: non-git)
  build user:       pbuilder@deneb
  build date:       20200529-12:03:13
  go version:       go1.14.3
```

**Object Storage Provider**:

Swift with S3 middleware, Thanos is using S3 API

**What happened**:

We're migrating to Thanos and have recently started uploading blocks via sidecar, compaction is disabled on Prometheus. Historical data in the form of compacted blocks still exist on local TSDB, we haven't shipped that to object storage yet via `--shipper.upload-compacted`.

In the access logs I'm seeing quite a few frequent 404s for `meta.json` from the sidecar, e.g.

```
May 29 12:27:13 thanos-fe2001 proxy-server[24768]: 10.192.0.192 10.192.0.192 29/May/2020/12/27/13 HEAD /v1/AUTH_thanos/thanos/01E99CJ1FA7HBX663C6BS620VC/meta.json HTTP/1.0 404 - MinIO%20%28linux%3B%20amd64%29%20mi
nio-go/v6.0.53%20thanos-sidecar/0.13.0-rc.0%20%28go1.14.3%29 - - - - tx9f1e9f735e264759bb86d-005ed0ffa1 - 0.0363 S3 - 1590755233.301873922 1590755233.338170052 0
```

Upon inspection that ULID exists in the local TSDB and its `meta.json` looks like this

```
# cat metrics/01E99CJ1FA7HBX663C6BS620VC/meta.json
{
        "ulid": "01E99CJ1FA7HBX663C6BS620VC",
        "minTime": 1590451200000,
        "maxTime": 1590516000000,
        "stats": {
                "numSamples": 46999339,
                "numSeries": 81646,
                "numChunks": 430116,
                "numBytes": 57598135
        },
        "compaction": {
                "level": 3,
                "sources": [
                        "01E97ERDHBHQQ3YMZ5D9HK8GPG",
                        "01E97NM4QB2Q8XBWAGTSKQF2YA",
                        "01E97WFW1EWREXT5GXV075P4PE",
                        "01E983BK9PWCJBSQZV7G3X2QEV",
                        "01E98A7AJTBVC106VB51NNQTS4",
                        "01E98H31T2N9NSJKNCM6WH6W30",
                        "01E98QYS1ZM8E36ZWJ4GXCJCS8",
                        "01E98YTG9CK13D562D8TEMGE4R",
                        "01E995P7HD4K4VHCAPD3BECRBX"
                ],
                "parents": [
                        {
                                "ulid": "01E983BPM8S0J8P557Q0MAX5NM",
                                "minTime": 1590451200000,
                                "maxTime": 1590472800000
                        },
                        {
                                "ulid": "01E98QYT0DF5HS40B2BJWGK19A",
                                "minTime": 1590472800000,
                                "maxTime": 1590494400000
                        },
                        {
                                "ulid": "01E99CHZR3F6E6T5154ZQ2ZNV8",
                                "minTime": 1590494400000,
                                "maxTime": 1590516000000
                        }
                ]
        },
        "version": 1
}
```

**What you expected to happen**:

The sidecar to ignore scanning on object storage for already-compacted local blocks, which are not going to be uploaded anyways unless running with `--shipper.upload-compacted` (the current sidecar isn't)

**How to reproduce it (as minimally and precisely as possible)**:

Run sidecar with already-compacted local TSDB blocks and no `--shipper.upload-compacted`, observe the sidecar scanning object storage for `meta.json` for local TSDB blocks already compacted

**Full logs to relevant components**:

No error logs on the sidecar side, I can provide debug logs though if needed

**Anything else we need to know**:

**Comment by filippog** [comment]
Woot woot! Thanks for the quick fix :tada:

**Comment by bwplotka** [comment]
Question: should the fix go to 0.13.0 as well? It was fixed on master only

**Comment by filippog** [comment]
IMHO yes it should, it is a self-contained and straightforward fix

**Comment by bwplotka** [comment]
Cool, will cherry pick
