### ISSUE TITLE
Add about external_labels in katacoda tutorial

### ISSUE THREAD

**Issue by soniasingla** [thanos-io/thanos#2690]
```global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: eu1
    replica: 0
```

In the tutorial, https://katacoda.com/thanos/courses/thanos/1-globalview, it is important to add more information (note) about commands.

**Comment by bwplotka** [comment]
For those kind of issues I think "just" PR is totally  ok (: This is something small, not requiring huge discussion :hugs: 

Thanks anyway!

**Comment by soniasingla** [comment]
I am on it !
