### ISSUE TITLE
Thanos store disk space issue after version upgrade.

### ISSUE THREAD

**Issue by shivani-hotstar** [thanos-io/thanos#2693]
**Thanos, Prometheus** 
thanos, version 0.12.2 (branch: HEAD, revision: 52e10c6e0f644ea98fd057e7fbece828d8dd07c7)
  build user:       circleci@241aa351893e
  build date:       20200430-16:37:24
  go version:       go1.13.1

prometheus, version 2.15.2 (branch: HEAD, revision: d9613e5c466c6e9de548c4dae1b9aabf9aaf7c57)
  build user:       root@688433cf4ff7
  build date:       20200106-14:50:51
  go version:       go1.13.5

**What happened:**

We were facing thanos memory issue so we heard that new thanos version has some fixes regarding issue .
Upgraded from v0.9.0 to v0.12.2 .
After upgradation memory issue seems fine but different issue occurs .
Thanos-store starts eating up lots of disk .

**Full logs to relevant components: (thanos-store pod)**

You can see the order of the action in log file:

`level=warn ts=2020-05-31T16:51:31.420794929Z caller=bucket.go:460 msg="loading block failed" elapsed=89.233952ms id=01E8JDV4D82TEWGN1RSFNVDGQH err="create index header reader: write index header: new binary index header writer: mkdir /var/thanos/store/01E8JDV4D82TEWGN1RSFNVDGQH: no space left on device"
level=warn ts=2020-05-31T16:51:31.423133848Z caller=bucket.go:460 msg="loading block failed" elapsed=90.095255ms id=01E9MHKNGBD9TN8SXYVDC378PA err="create index header reader: write index header: new binary index header writer: mkdir /var/thanos/store/01E9MHKNGBD9TN8SXYVDC378PA: no space left on device"
level=warn ts=2020-05-31T16:51:31.428205856Z caller=bucket.go:460 msg="loading block failed" elapsed=81.427465ms id=01E8P2JFNAEKTT4709E16E6QJK err="create index header reader: write index header: new binary index header writer: mkdir /var/thanos/store/01E8P2JFNAEKTT4709E16E6QJK: no space left on device"
level=warn ts=2020-05-31T16:51:31.461041204Z caller=bucket.go:460 msg="loading block failed" elapsed=86.174891ms id=01E8K9A1D8WPJNNGK1DMAZNZCN err="create index header reader: write index header: new binary index header writer: mkdir /var/thanos/store/01E8K9A1D8WPJNNGK1DMAZNZCN: no space left on device"
level=warn ts=2020-05-31T16:51:31.510246012Z caller=bucket.go:460 msg="loading block failed" elapsed=132.89501ms id=01E8WGJ96VGHDNXVRQ8M7PECQM err="create index header reader: write index header: new binary index header writer: mkdir /var/thanos/store/01E8WGJ96VGHDNXVRQ8M7PECQM: no space left on device"`

Thanos store pod disk went to full usage .

As per thanos new release https://github.com/thanos-io/thanos/releases/tag/v0.12.0  breaking fix .I tried adding **--delete-delay=0s** this flag but pod start giving me error invalid flag.

**Comment by bwplotka** [comment]
"Lots" means how much disk? (:

**Comment by bwplotka** [comment]
Also can you try cleaning whole disk and restarting? Might be that some old stuff from older version is piling up

**Comment by shivani-hotstar** [comment]
On more debugging i came across the thanos-store local directory cache issue.
Thanos store configuration 
`spec:
      containers:
      - args:
        - store
        - --log.level=debug
        - --data-dir=/var/thanos/store
        - --objstore.config=$(OBJSTORE_CONFIG)`
Disk utilisation  went upto 100% .

Can you help me in understanding how thanos store manages  local cache . because this disk utilisation increased immediately after thanos version upgrade .

**Comment by bwplotka** [comment]
But what is the 100%? 10MB? 1GB?

**Comment by shivani-hotstar** [comment]
Thanos store using 100 gb volume .

**Comment by shivani-hotstar** [comment]
Hi,
We started facing thanos store cache storage issue again .
Thanos-store disk = 100GB
Image:       quay.io/thanos/thanos:v0.12.2

Logs from thanos-store pod 
`level=debug ts=2020-11-10T01:24:45.994640439Z caller=bucket.go:453 msg="loading new block" id=01D33EW949948MPRJ1K5KR3E20
level=debug ts=2020-11-10T01:24:45.994484358Z caller=bucket.go:453 msg="loading new block" id=01D2A17CRZMJKQX005HMW9P8SM
level=debug ts=2020-11-10T01:24:45.99472048Z caller=binary_reader.go:456 msg="failed to read index-header from disk; recreating" path=/var/thanos/store/01D33EW949948MPRJ1K5KR3E20/index-header err="try lock file: open /var/thanos/store/01D33EW949948MPRJ1K5KR3E20/index-header: no such file or directory"
level=debug ts=2020-11-10T01:24:45.99485228Z caller=binary_reader.go:456 msg="failed to read index-header from disk; recreating" path=/var/thanos/store/01D2A17CRZMJKQX005HMW9P8SM/index-header err="try lock file: open /var/thanos/store/01D2A17CRZMJKQX005HMW9P8SM/index-header: no such file or directory"
level=debug ts=2020-11-10T01:24:45.994951911Z caller=bucket.go:453 msg="loading new block" id=01D2A17AQ5FVTCZNKR9N4TRKST
level=debug ts=2020-11-10T01:24:45.994986921Z caller=binary_reader.go:456 msg="failed to read index-header from disk; recreating" path=/var/thanos/store/01D2A17AQ5FVTCZNKR9N4TRKST/index-header err="try lock file: open /var/thanos/store/01D2A17AQ5FVTCZNKR9N4TRKST/index-header: no such file or directory"
level=debug ts=2020-11-10T01:24:45.995011172Z caller=bucket.go:453 msg="loading new block" id=01D33EW7SPFKDNBM5E27JPERE7
level=debug ts=2020-11-10T01:24:45.995073162Z caller=binary_reader.go:456 msg="failed to read index-header from disk; recreating" path=/var/thanos/store/01D33EW7SPFKDNBM5E27JPERE7/index-header err="try lock file: open /var/thanos/store/01D33EW7SPFKDNBM5E27JPERE7/index-header: no such file or directory"
level=debug ts=2020-11-10T01:24:45.995104693Z caller=bucket.go:453 msg="loading new block" id=01D2A176BNX9855N7W500QX0S3
level=debug ts=2020-11-10T01:24:45.995184923Z caller=binary_reader.go:456 msg="failed to read index-header from disk; recreating" path=/var/thanos/store/01D2A176BNX9855N7W500QX0S3/index-header err="try lock file: open /var/thanos/store/01D2A176BNX9855N7W500QX0S3/index-header: no such file or directory"
level=warn ts=2020-11-10T01:24:46.033027648Z caller=bucket.go:460 msg="loading block failed" elapsed=38.577979ms id=01D2A1742GZ8D24NAEZ56GYFZS err="create index header reader: write index header: get symbols from object storage of 01D2A1742GZ8D24NAEZ56GYFZS/index: Invalid range specified: start=5 end=-1"
level=warn ts=2020-11-10T01:24:46.036772232Z caller=bucket.go:460 msg="loading block failed" elapsed=42.242973ms id=01D33EWAFTTNJ04CGGYBJWXTXJ err="create index header reader: write index header: get symbols from object storage of 01D33EWAFTTNJ04CGGYBJWXTXJ/index: Invalid range specified: start=5 end=-1"
level=warn ts=2020-11-10T01:24:46.03799573Z caller=bucket.go:460 msg="loading block failed" elapsed=43.357241ms id=01D33EW949948MPRJ1K5KR3E20 err="create index header reader: write index header: get symbols from object storage of 01D33EW949948MPRJ1K5KR3E20/index: Invalid range specified: start=5 end=-1"
level=warn ts=2020-11-10T01:24:46.03802423Z caller=bucket.go:460 msg="loading block failed" elapsed=43.070489ms id=01D2A17AQ5FVTCZNKR9N4TRKST err="create index header reader: write index header: get symbols from object storage of 01D2A17AQ5FVTCZNKR9N4TRKST/index: Invalid range specified: start=5 end=-1"
level=warn ts=2020-11-10T01:24:46.03804382Z caller=bucket.go:460 msg="loading block failed" elapsed=43.036788ms id=01D33EW7SPFKDNBM5E27JPERE7 err="create index header reader: write index header: get symbols from object storage of 01D33EW7SPFKDNBM5E27JPERE7/index: Invalid range specified: start=5 end=-1"
level=warn ts=2020-11-10T01:24:46.041207571Z caller=bucket.go:460 msg="loading block failed" elapsed=46.727302ms id=01D2A17CRZMJKQX005HMW9P8SM err="create index header reader: write index header: get symbols from object storage of 01D2A17CRZMJKQX005HMW9P8SM/index: Invalid range specified: start=5 end=-1"`

I cleaned up old data of old months manually and till last night the disk utilisation was at 6% . Today it reached to 80%
`/dev/nvme1n1             97.9G     79.2G     18.8G  81% /var/thanos/store`

Can someone help me in understanding what caused this issue.
Thanks in advance

**Comment by jimbobby5** [comment]
I see similar behaviour. On startup Thanos store seems to pull data from S3 until my PVC is full, which is 100Gb in my environment. Exploring the disk I see lots of large index-header files, order of hundreds of mb each. Is this expected?

**Comment by mogaal** [comment]
Ran into the same issue now. I have a bunch of metrics in my S3 bucket (2.8TB) and my 10GB PVC couldn't cope. Even if the documentation says "_does not need significant amounts of local disk space_" for 2.8TB of data 10GB isn't clearly enough.

I fixed it adding `--min-time=-1w` to storage API  and now my 10GB PVC is happy. I hope it helps.

**Comment by paulliss** [comment]
@samholidu Have you found a solution to your question?
Thank you in advance
