### ISSUE TITLE
Querier: Log query when error is "No StoreAPIs matched for this query"

### ISSUE THREAD

**Issue by Nuru** [thanos-io/thanos#2701]
**Thanos, Prometheus and Golang version used**:

Thanos: bitnami/thanos:0.12.2-scratch-r14
Prometheus: bitnami/prometheus:2.18.1-debian-10-r17

**Object Storage Provider**:

Minio S3

**What happened**:

I see in the Query logs things like 

```json
{
  "caller": "proxy.go:291",
  "err": "No StoreAPIs matched for this query",
  "level": "warn",
  "stores": "store Addr: 172.20.10.11:10901 LabelSets: [name:\"cluster\" value:\"test\" ,name:\"prometheus\" value:\"monitoring/po-prometheus\" ,name:\"prometheus_replica\" value:\"prometheus-po-prometheus-0\" ][name:\"cluster\" value:\"test\" ,name:\"prometheus\" value:\"monitoring/po-prometheus\" ,name:\"prometheus_replica\" value:\"prometheus-po-prometheus-1\" ] Mint: 1590053458667 Maxt: 1591034400000 filtered out;store Addr: 10.10.6.10:10901 LabelSets: [name:\"cluster\" value:\"test\" ,name:\"prometheus\" value:\"monitoring/po-prometheus\" ,name:\"prometheus_replica\" value:\"prometheus-po-prometheus-1\" ] Mint: 1591020714792 Maxt: 9223372036854775807 filtered out;store Addr: 10.10.15.141:10901 LabelSets: [name:\"cluster\" value:\"test\" ,name:\"prometheus\" value:\"monitoring/po-prometheus\" ,name:\"prometheus_replica\" value:\"prometheus-po-prometheus-0\" ] Mint: 1591020702805 Maxt: 9223372036854775807 filtered out",
  "ts": "2020-06-01T19:12:06.153822762Z"
}
```

This is concerning as it makes me think there is something wrong with my configuration. However, it can easily be triggered by a query with a non-existent cluster label like `up{cluster="foo"}`. This would be obvious (or at least reasonably easy to figure out) if the logger logged the query in the same message. 

**What you expected to happen**:

Please log the query when logging an error generated by a query. 

It would also be helpful if it logged the StoreAPI parameters it was trying to match. For example:

```json
"query": "up{cluster=\"foo\"}",
"storeFilter": { "LabelSets": [{"name":"cluster", "value":"foo"}], "Mint":1591063926150, "Maxt":1591063926150}
```

**How to reproduce it (as minimally and precisely as possible)**:

Run a query specifying an invalid value for an external label that Querier uses for de-duplication, e.g. `up{cluster="foo"}`

**Comment by sushanco** [comment]
I am seeing the same issue across a number of thanos version. It feels like there is something missing in the configuration however there is nothing obvious in debug logs.

**Versions:** 
Thanos: thanos/thanos:0.13.0
Prometheus: coreos/prometheus:v2.16.0

**Object Storage: AWS S3**

Thanos Query report the Store is UP and displays LabelSets as well. In the Thanos Store I can see metadata synced from S3 bucket to local filesystem. 

But when I execute an example query on Thanos Query returns: `No StoreAPIs matched for this query`

Log in Thanos Query pod:

`{"caller":"proxy.go:291","err":"No StoreAPIs matched for this query","level":"warn","stores":"store Addr: 172.30.142.55:10901 LabelSets: [name:\"cluster\" value:\"eu-ops\" ,name:\"prometheus\" value:\"monitoring/main\" ,name:\"prometheus_replica\" value:\"prometheus-main-0\" ][name:\"cluster\" value:\"eu-ops\" ,name:\"prometheus\" value:\"monitoring/main\" ,name:\"prometheus_replica\" value:\"prometheus-main-1\" ][name:\"cluster\" value:\"eu-test\" ,name:\"eu_test\" value:\"monitoring/main\" ,name:\"prometheus_replica\" value:\"prometheus-main-0\" ][name:\"cluster\" value:\"eu-test\" ,name:\"eu_test\" value:\"monitoring/main\" ,name:\"prometheus_replica\" value:\"prometheus-main-1\" ][name:\"cluster\" value:\"us-test\" ,name:\"prometheus_replica\" value:\"prometheus-main-0\" ,name:\"us_test\" value:\"monitoring/main\" ][name:\"cluster\" value:\"us-test\" ,name:\"prometheus_replica\" value:\"prometheus-main-1\" ,name:\"us_test\" value:\"monitoring/main\" ] Mint: 1594303200000 Maxt: 1594368000000 filtered out","ts":"2020-07-10T09:22:23.841442605Z"}`
