### ISSUE TITLE
quantile_over_time in downsampled data?

### ISSUE THREAD

**Issue by danielgblanco** [thanos-io/thanos#2706]
Apologies if this has been answered before, I have tried to find docs or any other answered questions but found none on this particular issue. I'm trying to understand how the downsampling done by the compactor affects percentile calculations.

If I understand correctly by looking at the [downsampler code](https://github.com/thanos-io/thanos/blob/9726c0dc6972b7a51749fba943f8d74b9f081c1e/pkg/compact/downsample/downsample.go), it aggregates last, sum, max, min, count, avg, counter resets etc. I'm assuming these are used in lieu of the functions that could be applied on raw data when doing aggregations and aggregation `<aggregation>_over_time()` queries.

My question is: how does `quantile_over_time` work on downsampled data if there are no buckets stored? Should we avoid using `quantile_over_time` on downsampled data?

**Comment by danielgblanco** [comment]
This is still a question I've not found an answer for in the treatment of `quantile_over_time` functions on downsampled data. Thanks.

**Comment by yeya24** [comment]
In the default case, Querier tries to get the downsampled `count` and `sum` chunks to use the calculated average value as the downsampled sample values.

So in this case, `quantile_over_time` will be evaluated based on the average data.
