### ISSUE TITLE
store: Adapt for objects changes (removals) faster

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#271]
Basically we sync metas every 3 minutes, but it can happen that compactor or repair command remove some unnecessary block in the time between syncs. This result in temporary query error: `receive series: rpc error: code = Aborted desc = fetch series for block 01C8DBKCT8TVC7KRDBC9TWBTPJ: preload postings: read postings range: get range reader: storage: object doesn't exist`

How to improve that?
- decrease the interval
- catch not found obj error or check for existence of block and handle that somehow (ignore these postings?)

**Comment by stevenkehrli-trelnex** [comment]
We're seeing this with master-2018-06-15-5b66b72.
Will it eventually resolve itself? Message has repeated every 5 minutes for over 30 minutes now.

**Comment by bwplotka** [comment]
We need this to solve this issue: https://github.com/thanos-io/thanos/pull/700

**Comment by bwplotka** [comment]
Closing in favor of: https://github.com/thanos-io/thanos/issues/271
