### ISSUE TITLE
Feature Request: Replicate can copy individual blocks

### ISSUE THREAD

**Issue by maulikjs** [thanos-io/thanos#2713]
So today we faced an issue where a few blocks were not copied to our destination bucket and I had to manually copy them over, I am still trying to figure out what went wrong but it would be a nice feature to have if the replicate can copy individual blocks over.

One another feature that would be really useful is to verify if all the blocks have been copied over between 2 buckets and maybe give a report for those which might have been missed.

**Comment by yeya24** [comment]
I think the first feature is nice and we can support it easily.

**Comment by bwplotka** [comment]
Well, replicate does exactly this. It compares those two buckets. So even
if we had additional logic, same bug might happened (: Let's dive into why
it was missed.

BTW what version you are using? Are you on Thanos tools replicate now?

**Comment by bwplotka** [comment]
Lets get back on this. Help wanted!

**Comment by yeya24** [comment]
Let me take this one. This can be implemented by adding specified blocks ID to blockFilter https://github.com/thanos-io/thanos/blob/master/pkg/replicate/scheme.go#L30.

**Comment by yeya24** [comment]
Still on it. Blocked by https://github.com/thanos-io/thanos/pull/2906

**Comment by kakkoyun** [comment]
@yeya24 Can we do anything to unblock #2906?

**Comment by yeya24** [comment]
@kakkoyun  Please help review #2906

**Comment by yeya24** [comment]
Will take this.
