### ISSUE TITLE
Compact doesn't create 5m and 1h downsampling

### ISSUE THREAD

**Issue by Kirchen99** [thanos-io/thanos#2717]
**Thanos, Prometheus and Golang version used**:
0.12.1

**Object Storage Provider**:
S3
**What happened**:
Compact creates no more 5m and 1h downsampling. At least it doesn't show any downsampling in Bucket-View, one month after it has been deployed in a Kubernetes Cluster.
![image](https://user-images.githubusercontent.com/9981745/83747329-c0352100-a660-11ea-9fa9-7c8aa95c7770.png)

**What you expected to happen**:
In Bucket-View it should show resolution 300,000 and 3,600,000 blocks after 1st March. For example: in another Kubernets Cluster:
![image](https://user-images.githubusercontent.com/9981745/83748834-10ad7e00-a663-11ea-9063-0ce8de28e71d.png)

**How to reproduce it (as minimally and precisely as possible)**:
We deployed Thanos in six Kubernetes Clusters and two of them encounter this problem. I don't know how to reproduce it.

**Full logs to relevant components**:
No Error Logs
<details>Logs
<p>

```
{"cached":1002,"caller":"fetcher.go:451","component":"block.BaseFetcher","duration":"3.621436779s","level":"info","msg":"successfully synchronized block metadata","partial":1,"returned":1002,"ts":"2020-06-04T10:21:55.071811873Z"}
{"cached":1002,"caller":"fetcher.go:451","component":"block.BaseFetcher","duration":"1.70153134s","level":"info","msg":"successfully synchronized block metadata","partial":1,"returned":1002,"ts":"2020-06-04T10:22:53.190645108Z"}
{"cached":1002,"caller":"fetcher.go:451","component":"block.BaseFetcher","duration":"2.8755667s","level":"info","msg":"successfully synchronized block metadata","partial":1,"returned":1002,"ts":"2020-06-04T10:23:54.322580917Z"}
{"cached":1002,"caller":"fetcher.go:451","component":"block.BaseFetcher","duration":"3.877160865s","level":"info","msg":"successfully synchronized block metadata","partial":1,"returned":1002,"ts":"2020-06-04T10:24:55.364763378Z"}
{"caller":"compact.go:764","duration":"9m59.687960761s","group":"0@{cluster=\"cluster-name\", replica=\"prometheus-1\"}","groupKey":"0@2247213478709824437","level":"info","msg":"uploaded block","result_block":"01E9ZA1NPFJA1J5E0QH35PXFGN","ts":"2020-06-04T10:25:49.450690283Z"}
{"caller":"compact.go:792","group":"0@{cluster=\"cluster-name\", replica=\"prometheus-1\"}","groupKey":"0@2247213478709824437","level":"info","msg":"marking compacted block for deletion","old_block":"01E9WKENZ9GBJKVEJGR1RD6KS3","ts":"2020-06-04T10:25:49.766825447Z"}
{"block":"01E9WKENZ9GBJKVEJGR1RD6KS3","caller":"block.go:157","group":"0@{cluster=\"cluster-name\", replica=\"prometheus-1\"}","groupKey":"0@2247213478709824437","level":"info","msg":"block has been marked for deletion","ts":"2020-06-04T10:25:49.795767855Z"}
```

</p>
</details>

**Anything else we need to know**:
Here shows the volume usage of the Compact:
![image](https://user-images.githubusercontent.com/9981745/83747961-bc55ce80-a661-11ea-81a7-9075366d2bcf.png)

Command:
```
/bin/thanos \
compact \
--log.level=info \
--log.format=json \
--data-dir=/data \
--wait \
--objstore.config-file=/etc/thanos/bucket.yaml \
--retention.resolution-raw=370d \
--retention.resolution-5m=370d \
--retention.resolution-1h=370d
```
Resources:
```
"resources": {
              "limits": {
                "cpu": "1",
                "memory": "32Gi"
              },
              "requests": {
                "cpu": "200m",
                "memory": "16Gi"
              }
            }
```

**Comment by Jakob3xD** [comment]
Hey, did you check the logs of the compactor?
It seems like it is crashing due to missing local space.

**Comment by Kirchen99** [comment]
> Hey, did you check the logs of the compactor?
> It seems like it is crashing due to missing local space.

Hi, it was crashing due to "no space left on device". Then we have increased the volume for the compactor and restarted it. It should have enough disk space now and we hope that it can work after the restart.
