### ISSUE TITLE
Broken links in TOC of Contributing page

### ISSUE THREAD

**Issue by soniasingla** [thanos-io/thanos#2729]
The `table-of-content` at  https://thanos.io/contributing/ contains the broken links.

I wonder may be we can remove it as per bug #2512 or we should fix it? :)

CC : @bwplotka @povilasv

**Comment by bwplotka** [comment]
Definitely we should switch all TOCs into automated ones! :heart: 

Good idea :muscle:

**Comment by soniasingla** [comment]
@bwplotka we can close this issue, it has been resolved :)

**Comment by pracucci** [comment]
Closed by https://github.com/thanos-io/thanos/pull/2689 and https://github.com/thanos-io/thanos/pull/2799.
