### ISSUE TITLE
Thanos compactor fails "no space left on device"

### ISSUE THREAD

**Issue by callingsid** [thanos-io/thanos#2734]
**Thanos, Prometheus and Golang version used**: Thanos v0.12.2 and Prometheus v2.14.0

**Object Storage Provider**: S3

**What happened**: The compactor runs without errors for few days and later it starts to crash. 
Note Deployed it on a k8's cluster on AWS.
                        

**What you expected to happen**: The compactor and store-gateway keeps running.

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

Uncomment if you would like to post collapsible logs:

<details>Logs
<p>

```level=info ts=2020-06-08T09:23:41.752734942Z caller=prober.go:137 msg="changing probe status" status=not-healthy reason="error executing compaction: compaction failed: 2 errors: compaction failed for group 0@958061825840561885: download block 01E7S5DQBTVTN3N7S210CC340H: copy object to file: write /data/compact/0@958061825840561885/01E7S5DQBTVTN3N7S210CC340H/chunks/000001: no space left on device; compaction failed for group 0@13512535539904676854: download block 01E7YA7MDGA52SVRQ1ESGRDQBC: copy object to file: write /data/compact/0@13512535539904676854/01E7YA7MDGA52SVRQ1ESGRDQBC/index: no space left on device"
level=error ts=2020-06-08T09:23:41.75276586Z caller=main.go:194 msg="running command failed" err="error executing compaction: compaction failed: 2 errors: compaction failed for group 0@958061825840561885: download block 01E7S5DQBTVTN3N7S210CC340H: copy object to file: write /data/compact/0@958061825840561885/01E7S5DQBTVTN3N7S210CC340H/chunks/000001: no space left on device; compaction failed for group 0@13512535539904676854: download block 01E7YA7MDGA52SVRQ1ESGRDQBC: copy object to file: write /data/compact/0@13512535539904676854/01E7YA7MDGA52SVRQ1ESGRDQBC/index: no space left on device"
```

</p>
</details>

**Anything else we need to know**:

Uncomment and fill if you use not casual environment or if it might be relevant.

**Environment**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:
We am using 2 Prometheus pods and they write to S3 using a single Store-gateway. 

Compactor args:
- args:
        - compact
        - --log.level=info
        - --data-dir=/data
        - --wait
        - --block-sync-concurrency=20
        - --compact.concurrency=20
        - --retention.resolution-raw=14d
        - --retention.resolution-5m=183d
        - --objstore.config-file=/etc/thanos/storage.yaml
        - --log.format=logfmt

Store-gateway args:
      - args:
        - store
        - --log.level=info
        - --log.format=logfmt
        - --data-dir=/data
        - --index-cache-size=500MB
        - --chunk-pool-size=500MB
        - --objstore.config-file=/etc/thanos/storage.yaml

**Comment by Jakob3xD** [comment]
Hey,
how much local space did you reserve for the compactor and how large are your 2h blocks?
Did you check if your local disk space runs full on compaction? If yes then you could first try to lower the compact.concurrency or increase the local disc space.

**Comment by bwplotka** [comment]
Small tip from our side: Compactor does not stream disk writes, so you need at least space to contain:

3x blocks of lvl 3
1x block of lvl 4

That's the max. 

For ideas on improving this, let's discuss here: https://github.com/thanos-io/thanos/issues/1767 (:  

Closing as dup of https://github.com/thanos-io/thanos/issues/1767
