### ISSUE TITLE
Gaps in graphs when using Thanos

### ISSUE THREAD

**Issue by keksecops** [thanos-io/thanos#2736]
**Thanos, Prometheus and Golang version used**:
Thanos: 0.12.2
Prometheus: 2.18.1
Golang: go1.13.1

**Object Storage Provider**:
Bucket on GCP

**What happened**:
When using Thanos datasource in Grafana small gaps appear randomly in the graphs for example in this query for the last 6 hours:

Using Prometheus:
![imagem](https://user-images.githubusercontent.com/53620865/84022023-87a58800-a97d-11ea-8c85-52280c1d9791.png)

Using Thanos:
![imagem](https://user-images.githubusercontent.com/53620865/84021911-575de980-a97d-11ea-8eef-9a1f5159a7a1.png)

**Query**: sum by (container) (irate(container_cpu_usage_seconds_total{job="kubelet", cluster="$cluster", namespace="$namespace", image!="", pod="$pod", container=~"$container", container!="POD",env="$env"}[4m]))

This gaps normally appear in rate/irate query functions.

In Thanos UI:
With deduplication on:
![imagem](https://user-images.githubusercontent.com/53620865/84022674-917bbb00-a97e-11ea-80f0-7dbd6abc9b10.png)

With dedup off:
![imagem](https://user-images.githubusercontent.com/53620865/84022695-980a3280-a97e-11ea-9fe9-6a0022d6d818.png)

**What you expected to happen**:
Deduplication works as expected (it works in other queries) and no gaps should appear in the graphs.

**How to reproduce it (as minimally and precisely as possible)**:
Use a query in grafana with rate()/irate() functions and switch between Thanos and Prometheus datasources. Gaps appear in Thanos datasource but not on the Prometheus one. 

**Anything else we need to know**:

Some more details:
- Thanos is attached to a prometheus in federation.
- Scrape interval in the federate job : 15s
- This is how my Thanos Store is configured:
```
      store
      --data-dir=/var/thanos/store
      --log.level=info
      --log.format=logfmt
      --http-address=0.0.0.0:10902
      --grpc-address=0.0.0.0:10901
      --objstore.config-file=/etc/config/object-store.yaml
      --index-cache-size=2GB
      --chunk-pool-size=4GB
      --store.grpc.series-max-concurrency=20
      --sync-block-duration=3m
      --block-sync-concurrency=20
```

- This is how my Thanos Query is configured:
```
      query
      --log.level=info
      --log.format=logfmt
      --grpc-address=0.0.0.0:10901
      --http-address=0.0.0.0:10902
      --query.replica-label=prometheus_replica
      --query.auto-downsampling
      --store.sd-dns-resolver=miekgdns
      --store=dnssrv+_grpc._tcp.thanos-store-grpc.monitoring.svc.cluster.local
      --store=dnssrv+_grpc._tcp.thanos-sidecar-grpc.monitoring.svc.cluster.local
      --store.sd-interval=5m
```

If there is anything else that needs to be shown just let me know. Thanks.

**Comment by bwplotka** [comment]
Thanks, can you first update Querier to `v0.13.0-rc.1` and see how it goes? 

I think you might hit: https://github.com/thanos-io/thanos/issues/981

How your other Prometheus results looks like? :hugs:

**Comment by keksecops** [comment]
Hi @bwplotka and thanks for looking at my problem . 
I updated Querier to v0.13.0-rc.1 but the problem persists.
Here's and example after updating the Querier that I manage to capture just now:
Query:
`sort_desc(sum by (pod) (irate(container_network_receive_bytes_total{job="kubelet", cluster="$cluster", namespace="$namespace", pod="$pod", env="$env"}[4m])))`

Prometheus:
![imagem](https://user-images.githubusercontent.com/53620865/84492819-a9b14a00-ac9e-11ea-8964-3ee6aa8dae52.png)

Thanos:
![imagem](https://user-images.githubusercontent.com/53620865/84492702-7e2e5f80-ac9e-11ea-8859-6d87c51db270.png)
The only thing I did was to change the datasource between Thanos and Prometheus.
The only temporary "fix" is to change the range to a bigger one ([4m] to [10m]).

My other metrics on Prometheus look fine in my perspective.
Regarding #981, it seems like a very similar problem but what I noticed in my case, is that the gaps are created when there are significant drops in the graphs, in metrics values in Prometheus.

**Comment by keksecops** [comment]
Updated to the latest version v0.13.0-rc.2. The problem still persists. 
Any more ideas on how to fix this?

**Comment by bwplotka** [comment]
Thanks all input. 

It feels to me like you hit this: https://github.com/prometheus/prometheus/issues/7349 Do you mind upgrading Prometheus to v2.18.2? It has to do with remote read endpoint. Actually it was seen only for certain remote read users, so the bug does not fill 100% as yours, but the symptom is exactly the same. Let's try.

What we know:
* It's when querying Prometheus via Thanos sidecar (right?). So it's not downsampling
* Range matters, but probably only because potential remote read bug which was fixed in 2.18.2
* Deduplication does not impact this

BTW for others, some discussion is also here: https://cloud-native.slack.com/archives/CK5RSSC10/p1592384913043300

**Comment by bwplotka** [comment]
Prom: 

![image](https://user-images.githubusercontent.com/6950331/85046055-cc080380-b187-11ea-9f06-b5d67e2e7f52.png)

Dup off:
![image](https://user-images.githubusercontent.com/6950331/85046071-d1fde480-b187-11ea-9f99-93d1808a5a12.png)

Dup on
![image](https://user-images.githubusercontent.com/6950331/85046084-d6c29880-b187-11ea-82f5-8232121b8921.png)

**Comment by bwplotka** [comment]
still with v2.18.2

**Comment by keksecops** [comment]
Current architecture (all deployed in K8s clusters):

Cluster Mon(Federation): 2 prometheus replicas that  scrape other clusters. This prometheus have both the thanos sidecar installed. This can be seen as the global prometheus that gathers all metrics from all environments.

Cluster Apps: 2 prometheus replicas for HA

Both prometheus in Cluster Mon will scrape the Cluster Apps prometheus. 

Thanos querier is installed in Cluster mon and has the following stores: 
![imagem](https://user-images.githubusercontent.com/53620865/85047767-315cf400-b18a-11ea-93f3-460cd3ae3bfc.png)
As you can see its both sidecars and the GCP bucket.

Now for the query tests: 
Query without sum:
![imagem](https://user-images.githubusercontent.com/53620865/85048323-13dc5a00-b18b-11ea-9f8f-c75686bf6928.png)
Query without irate: 
![imagem](https://user-images.githubusercontent.com/53620865/85048487-471ee900-b18b-11ea-9469-488b9d295f57.png)

If I Zoom in the Gap is still there: 
Prometheus Datasource
![imagem](https://user-images.githubusercontent.com/53620865/85048682-91a06580-b18b-11ea-955a-30180bef1797.png)

Thanos Datasource: 
![imagem](https://user-images.githubusercontent.com/53620865/85048777-b4327e80-b18b-11ea-9c9a-0984d2312a3b.png)

Zoom in on the second gap: 
![imagem](https://user-images.githubusercontent.com/53620865/85048880-d9bf8800-b18b-11ea-848a-daf63a387738.png)

With prometheus: 
![imagem](https://user-images.githubusercontent.com/53620865/85049062-21deaa80-b18c-11ea-8251-d97058af490d.png)

If I change the range from 4m to 5m the gap goes away: 
![imagem](https://user-images.githubusercontent.com/53620865/85049231-4cc8fe80-b18c-11ea-866e-51319a0ab3dd.png)


If you need anything more just ask. Thanks for the help.

**Comment by bwplotka** [comment]
Nice, can you zoom AND do the same comparison but on Prometheus UI for query WITHOUT rate and sum? :hugs:

**Comment by keksecops** [comment]
Prometheus UI: 
![imagem](https://user-images.githubusercontent.com/53620865/85054102-7174a480-b193-11ea-9f3b-b9bf77995b64.png)

Query without rate and sum : 
![imagem](https://user-images.githubusercontent.com/53620865/85054005-4ee28b80-b193-11ea-9e08-8936333672d5.png)


>Hm... How those federated replicas scrapes "others"? Does it mean the federated Prometheus-es >scrape "/federated" endpoint? And each replica scrape what?

Exactly! They scrape the /federate endpoint of the clusters apps prometheus-es. Each replica scrapes both prometheus-es in cluster apps.  The prometheus-es in cluster apps are behind a nginx ingress controller like prometheusdev.org.com  (don't know if I should have different endpoints for each prometheus in cluster apps like prometheusdev1.org.com and prometheusdev2.org.com).

>Also then when you compare graphs, you compare with which Prometheus-es? The Federated ones >or Apps ones?

I compare with the Federated ones.

**Comment by HongChenTW** [comment]
Hi, we're facing exactly the same issue, any updates on this?

**Comment by velavokr** [comment]
Hi, similar problem with gaps when using `avg` and `sum` aggregations over joined metrics.

`avg(histogram_quantile(0.5, sum(rate(my_bucket[$__rate_interval])) by (le,pod)) * on(pod) group_right(le) kube_pod_labels{my_pod_label="my_pod_label_value"})` makes gaps between pods.

`sum` similarly creates gaps, but `min` and `max` don't.

Here are unaggregated metrics from different pods.
![Screenshot from 2024-06-16 21-50-06](https://github.com/thanos-io/thanos/assets/10815678/98c837e8-ca47-4f84-9b89-799aa934c92b)
 
Here are same metrics aggregated by `min`
![Screenshot from 2024-06-16 21-49-27](https://github.com/thanos-io/thanos/assets/10815678/d52b1c90-e547-448f-a95e-3283387eed4a)

Here are same metrics aggregated by `avg`
![Screenshot from 2024-06-16 21-49-43](https://github.com/thanos-io/thanos/assets/10815678/487b2fa2-a2d0-4c82-925f-407d6f9b4fdf)
