### ISSUE TITLE
Gap in graph when enabling query.auto-downsampling

### ISSUE THREAD

**Issue by anoop2503** [thanos-io/thanos#2737]
**Thanos, Prometheus and Golang version used**:
- Thanos-sidecar = quay.io/thanos/thanos:v0.12.2
- Thanos-Querier = quay.io/thanos/thanos:v0.12.2
- Thanos-Store-Gateway = quay.io/thanos/thanos:v0.12.2
- Thanos-Compactor = quay.io/thanos/thanos:v0.12.2

**Object Storage Provider**:S3
**What happened**:

When I try to execute below query in thanos (with query.auto-downsampling enabled) for checking CPU usage for last 60days,  I can see some gap in the data. However, when I disable query.auto-downsampling flag, I can see the graph is showing correct result without any gap.

`sum by (kubernetes_io_hostname) (rate (container_cpu_usage_seconds_total{id="/",kubernetes_io_hostname=~"stg-val-node-prm.*"}[1m])) / sum by (kubernetes_io_hostname) (machine_cpu_cores{kubernetes_io_hostname=~"stg-val-node-prm.*"})`

**What you expected to happen**:
Thanos should display the data correctly even if I enable "query.auto-downsampling" flag

**How to reproduce it (as minimally and precisely as possible)**:
Important configuration in my deployments are given below:
Prometheus
`--storage.tsdb.retention=30d`

Thanos Compactor:
```
--retention.resolution-raw=180d
--retention.resolution-5m=365d
--retention.resolution-1h=0d
```

Thanos Querier:
`--query.auto-downsampling`

**Full logs to relevant components**:

**Anything else we need to know**:

I have started using thanos-compactor recently on an existing thanos cluster. I can see the data correctly (even if I enable query.auto-downsampling) from the date when I started running compactor in all cases. The data older than that date is having this problem. However, I can still see the data, if I try to zoom in for a shorter period time on an older date (even if I enable query.auto-downsampling).

**Comment by GiedriusS** [comment]
Hi! That's expected since you are using:
```
...
rate (container_cpu_usage_seconds_total{id="/",kubernetes_io_hostname=~"stg-val-node-prm.*"}[1m])
...
```

And with a big enough time range and with that option enabled, Thanos will start selecting downsampled data for your query. It starts using 5m downsampled hence you see those gaps. Consider using `$__interval` or converting `1m` into a variable, or using separate data sources.

**Comment by GiedriusS** [comment]
In fact, I think we should close this in favor of https://github.com/thanos-io/thanos/issues/813, https://github.com/thanos-io/thanos/issues/310, and all of the other issues regarding this.

**Comment by anoop2503** [comment]
Thanks @GiedriusS
