### ISSUE TITLE
Docs: add documentation on layered Thanos Query architecture

### ISSUE THREAD

**Issue by mickael-carl** [thanos-io/thanos#2750]
As discussed during the Thanos Community Meeting: the docs already do a fantastic job at describing how Thanos Query works, but what's missing is how to operate it (the [Operating section](https://thanos.io/operating/) currently only has 3 small-ish sections 🙁 ).

It would be nice to document the layered Thanos Query approach mentioned [here](https://thanos.io/operating/multi-tenancy.md/) as a first step, with some nice picture describing the actual setup.

Based on that we could then further expand to document more common setup (HA setups, sharding, etc).

I'd definitely be willing to take a stab at this 🙂

**Comment by bwplotka** [comment]
Still valid

**Comment by bwplotka** [comment]
To be done, help wanted.

**Comment by sidewinder12s** [comment]
Is there anything folks could point me towards on this?

We have a layered Thanos arch with sharded prometheus (recently added to the prom-operator chart) and the prometheus sharding seems to have broken our top level searching for the sharded clusters.

Prometheus Shards (4x) -> Thanos Sidecar -> Cluster Thanos Query -> Aggregate Thanos Query -> Grafana

When we look at the Cluster thanos query, we see the 4 shards when looking at Stores. But when we look at the aggregate thanos, it only has 1 store entry and every reload the replicaLabel changes indicating we're only seeing 1 store (and missing data when we query the aggregate query)

Is this an unsupported configuration?

(We were also looking at opening a dedicated ticket for this)

**Comment by craig5** [comment]
+1

**Comment by Blacklion14** [comment]
Hey @kakkoyun

**Comment by Blacklion14** [comment]
Hey @kakkoyun , I wanted to work on this issue and I have already done my initial setup , Can you point me from where I have to start in order to update the docs and fix this issue .  

> As discussed during the Thanos Community Meeting: the docs already do a fantastic job at describing how Thanos Query works, but what's missing is how to operate it (the [Operating section](https://thanos.io/operating/) currently only has 3 small-ish sections 🙁 ).
> 
> It would be nice to document the layered Thanos Query approach mentioned [here](https://thanos.io/operating/multi-tenancy.md/) as a first step, with some nice picture describing the actual setup.
 
Also the links in above comment are not working , so please can you point me ....

**Comment by iampramma** [comment]
Layered Thanos Query approach mentioned [here](https://thanos.io/operating/multi-tenancy.md/) badly needs more pointers. Pls do update this document!
