### ISSUE TITLE
sidecar 0.12.2 restarts daily on ec2

### ISSUE THREAD

**Issue by Allex1** [thanos-io/thanos#2758]
**Thanos, Prometheus and Golang version used**:
thanos, version 0.12.2 (branch: HEAD, revision: 52e10c6e0f644ea98fd057e7fbece828d8dd07c7)
  build user:       root@c1a6cf60f03d
  build date:       20200430-16:24:03
  go version:       go1.13.6

**Object Storage Provider**:
aws S3
**What happened**:
After upgrading from 0.8.1 to 0.12.2 and from prometheus 2.13 to 2.18.1 and kernel from 3.10.0-693 to 3.10.0-1127 on multiple ec2 vms sidecar restarts daily at around the same time. See attached.

<img width="1563" alt="Screen Shot 2020-06-13 at 11 38 58" src="https://user-images.githubusercontent.com/8087146/84564462-9075cf80-ad6a-11ea-84a3-6402837b757a.png">

Ram usage is ~ 50MB, instance has lots of ram available, no args were changed during the upgrade. The metrics volume is totally different across multiple clusters and I see the same behaviour on all of them.

args are:
`thanos sidecar --prometheus.url=http://127.0.0.1:9090 --tsdb.path=/var/lib/prometheus --objstore.config-file=/etc/bucket.yaml --log.level=debug`

I have the same versions (except kernel) on multiple k8s clusters started with the same arguments and don't see this behaviour.

**How to reproduce it (as minimally and precisely as possible)**:
Not sure how othher than use the same versions
**Full logs to relevant components**:
The only errors I see in the debug logs are:
```
caller=main.go:223 msg="caught signal. Exiting." signal=terminated
caller=intrumentation.go:54 msg="changing probe status" status=not-ready reason=null
caller=http.go:81 service=http/server component=sidecar msg="internal server shutdown" err=null
caller=intrumentation.go:66 msg="changing probe status" status=not-healthy reason=null
caller=intrumentation.go:54 msg="changing probe status" status=not-ready reason=null
caller=grpc.go:125 service=gRPC/server component=sidecar msg="gracefully stopping internal server"
caller=main.go:103 msg="maxprocs: No GOMAXPROCS change to reset%!(EXTRA []interface {}=[])" 
```

**Anything else we need to know**:

**Environment**:
- OS: centos7
- Kernel: 3.10.0-1127
- Others:

**Comment by bwplotka** [comment]
Thanks for letting us know, this sounds quite bizarre. What's your orchestrator system, how you deploy Thanos? Also please find out exact exit code and reason of restart. It sounds like something in your operating system is killing it. Since there is no error or panic, it's process being killed potentially. We need to track what signal is sent to process etc.

Kernel is quite old, but yea - try to find the status code of the process after it was stopped (:

**Comment by Allex1** [comment]
Thanks @bwplotka 
We use puppet4 for orchestration but nothing was changed except versions. I did miss to write the status code in systemd: 
`caller=main.go:223 msg="caught signal. Exiting." signal=terminated`

**Comment by bwplotka** [comment]
Yea, so it's a OS sending TERM signal, it's nothing on Thanos that does
this (:
