### ISSUE TITLE
no search result show on new thanos-querier UI with lower FF version

### ISSUE THREAD

**Issue by juzhao** [thanos-io/thanos#2761]
FF 54.0 (64-bit),Goto thanos-querier UI, and click "New UI", search metrics, example: ALERTS
no resutl show, no such issue with a higher version, example: 75.0 (64-bit)

thanos version="0.12.2"
Steps to Reproduce:
`1. Goto new thanos-querier UI with FF 54.0`

Actual results:
no result show

Expected results:
show search result correctly

FYI:
we can close this issue if we don't support the low FF version

**Comment by bwplotka** [comment]
Thanks for filling! 

cc @prmsrswt (:
