### ISSUE TITLE
Use unsafe slice project to ensure yolo conversion safety

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2778]
See the following discussion: https://twitter.com/mdlayher/status/1273378885946814469

AC:
* Port `yoloString` and https://t.co/Hf7rJ9s064?amp=1 to [`unsafeslice`](https://t.co/BwOVAGJVBA?amp=1)
* Enable `-race` on Thanos unit tests on CI.

Thanks for @mdlayher for hints :heart:

**Comment by kkc** [comment]
can I work on this one?

**Comment by kakkoyun** [comment]
@bwplotka It'd be great to have a well-tested internal package for this like: https://pkg.go.dev/github.com/bcmills/unsafeslice?tab=doc#AsString (https://github.com/bcmills/unsafeslice/blob/v0.1.0/unsafeslice.go#L141)

**Comment by bwplotka** [comment]
Not enough priority for this currently (: 

Let's close for now.
