### ISSUE TITLE
Feature: Compactor should be able to handle retention

### ISSUE THREAD

**Issue by posix4e** [thanos-io/thanos#2782]
**Thanos, Prometheus and Golang version used**:
Newest 

**Object Storage Provider**:
Any. In this case I'm using minio

It would be delightful to be able to have thanos automatically compact away results older than a certain number of days. We are very privacy centric at our company.

**Comment by GiedriusS** [comment]
Hi! It does via the `--retention.X` flags as described here: https://thanos.io/components/compact.md/#downsampling-resolution-and-retention. Is there something in there that doesn't work for your use case exactly?

**Comment by the-yash** [comment]
Hi. I have set my retention flags, 
     ```
     "--retention.resolution-raw=4h"
      - "--retention.resolution-5m=16h"
      - "--retention.resolution-1h=3d"
```

If I understand correctly, I should not be having any data after 3 days. However, I can query data older than that as well. Why is this happening?

**Comment by the-yash** [comment]
Hi. I have set my retention flags,
```
- "--retention.resolution-raw=4h"
- "--retention.resolution-5m=16h"
- "--retention.resolution-1h=3d"
```
If I understand correctly, I should not be having any data after 3 days. However, I can query data older than that as well. Why is this happening?

**Comment by posix4e** [comment]
Yes it's confusing. You should clearly explain what it takes to have data
actually expire.
