### ISSUE TITLE
Add search input for doc search on mobile version as well

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2789]
cc @thisisobate 

Looks like we have Algolia search on desktop, might be worth to add on mobile version as  well ^^

**Comment by thisisobate** [comment]
I implemented Algolia search in mobile as well. It's appended inside the hamburger menu

**Comment by thisisobate** [comment]
I guess I'll have to make it alot more visible and accessible for the mobile user.

Would work on this ASAP. 
Thanks for bringing this to my attention 😁👍

**Comment by bwplotka** [comment]
It works, I just did not click properly, all good. And @thisisobate also fixed menu logo, so amazing!
