### ISSUE TITLE
IAM Role: Access Denied in AWS GovCloud

### ISSUE THREAD

**Issue by clausa20** [thanos-io/thanos#2792]
Hello, 
I get Access Denied using IAM roles in GovCloud when running for example:

./thanos compact --wait --retention.resolution-raw=90d --retention.resolution-5m=180d --retention.resolution-1h=360d --objstore.config-file=/root/thanos/thanos-0.13.0.linux-amd64/bucket_config.yml --data-dir=/root/thanos/thanos-0.13.0.linux-amd64/data

level=info ts=2020-06-22T16:04:48.279448176Z caller=http.go:56 service=http/server component=compact msg="listening for requests and metrics" address=0.0.0.0:10902
level=error ts=2020-06-22T16:04:48.668062239Z caller=compact.go:386 msg="retriable error" err="compaction: sync: BaseFetcher: iter bucket: Access Denied"
level=error ts=2020-06-22T16:04:49.005389867Z caller=runutil.go:98 msg="function failed. Retrying in next tick" err="BaseFetcher: iter bucket: Access Denied"

It is running in a container using IRSA IAM roles assigned to the pod.
To see if roles works ok, I run the aws cli in the same pod and it works ok, but thanos fails. 
Also to discard that is a Role Policy error, I gave S3 full access, but thanos still fails.
I get AccessDenied error for thanos-store, thanos-compactor and thanos-sidecar.

It is running in GovCloud AWS.
I am using Thanos 0.13.0 version.

I've seen that this bug was fixed in https://github.com/thanos-io/thanos/issues/1494 
but for me it is stil failling with the described use case.

the bucket_config.yml:

```
type: S3
config:
  bucket: <My_Bucket>
  endpoint: s3.us-gov-west-1.amazonaws.com
  region: us-gov-west-1

  insecure: false
  signature_version2: false
  encrypt_sse: false
  put_user_metadata: {}
  http_config:
    idle_conn_timeout: 0s
    response_header_timeout: 0s
    insecure_skip_verify: false
  trace:
    enable: true
```

Maybe it has something to do with GovCloud Environment?

**Comment by GiedriusS** [comment]
Maybe. Perhaps it would be worth putting some HTTPS proxy such as https://mitmproxy.org/ in front of the endpoint and see what is the difference in the requests when the AWS CLI makes them, and when Thanos Compactor does that. Could you please try that and report the differences?

**Comment by trsreagan3** [comment]
I am seeing something similar but on non govcloud eks fargate with IAM roles, and only on the storegateway container (other containers seem to be ok from what I can tell).

**Comment by trsreagan3** [comment]
For me the fix was to create the service accounts with eksctl create iamserviceaccount with the override flag for each of the four users and attaching the same IAM policy to each user,  AFTER running the helm chart. Seems like something specific to eks cluster security.

**Comment by clausa20** [comment]
I comment to keep alive this issue.
@trsreagan3 can you give some details and examples about steps you did?

**Comment by Vchabs** [comment]
Can we reopen this? Still seeing similar issue in govcloud - it won't take IRSA
