### ISSUE TITLE
query: It took too long to query from Store gateway

### ISSUE THREAD

**Issue by hongyuxuan** [thanos-io/thanos#2797]
**Thanos, Prometheus and Golang version used**: 
prometheus-2.15.1, thanos-0.13.0-rc.0, go-1.14.2

**Object Storage Provider**:
S3(MinIO)

**What happened**:
I setted up an object storage cluster with MinIO，and I started a thanos component of store gateway that connected to MinIO with S3 adaptor.
I also started a thanos querier connected to the store gateway:
./thanos query --store localhost:19090(store gateway gRPC port)
I had about only 50GB data stored in MinIO，when I try to set a range query for 10days through store gateway like this:
node_filesystem_avail_bytes{instance='xxx'}
it took about up to 40s for response, it's amazing! Why it took so long?

**What you expected to happen**:
At least it won't take that long，how about a few hundred milliseconds or a few seconds?

**How to reproduce it (as minimally and precisely as possible)**:
Store Gateway:
`./thanos store --data-dir /data/store --objstore.config-file /etc/prometheus/bucket_config.yml --http-address 0.0.0.0:19191 --grpc-address 0.0.0.0:19090 --log.level=info`
Querier
`./thanos query --http-address=0.0.0.0:9090 --grpc-address=0.0.0.0:10901 --query.replica-label=replica --store localhost:19090`
![微信截图_20200623232807](https://user-images.githubusercontent.com/5389643/85423617-81342480-b5a9-11ea-9e60-cdc869d1548a.png)
![微信截图_20200623232912](https://user-images.githubusercontent.com/5389643/85423643-86916f00-b5a9-11ea-86c6-25b0e700e1dc.png)

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by GiedriusS** [comment]
It certainly shouldn't take that long. I can load months of data in lots of different panels on my deployment easily in 42 seconds. Let's do a quick check for starters: do you run Thanos Compact in your environment?

**Comment by hongyuxuan** [comment]
> It certainly shouldn't take that long. I can load months of data in lots of different panels on my deployment easily in 42 seconds. Let's do a quick check for starters: do you run Thanos Compact in your environment?

Yes, I ran. 
./thanos compact --data-dir=/data/compact --objstore.config-file=/etc/prometheus/bucket_config.yml --http-address=0.0.0.0:8081 --retention.resolution-raw=180d --retention.resolution-5m=180d --retention.resolution-1h=180d --wait

**Comment by yinchengjian** [comment]
> It certainly shouldn't take that long. I can load months of data in lots of different panels on my deployment easily in 42 seconds. Let's do a quick check for starters: do you run Thanos Compact in your environment?

so when we query store query, we don't run thanos compact?
why? have some reasons？
