### ISSUE TITLE
failing make test-e2e 

### ISSUE THREAD

**Issue by kjge** [thanos-io/thanos#2803]
**Thanos, and Golang version used:**
thanos master branch last commit 02ab6b84908e5458699655ab064a78afc0f9da9b
go version go1.14.4 darwin/amd64
mac 10.15.5
docker version 19.03.8

**What happened:**

running ```make test-e2e```  gives following error

```
unexpected error: the service querier-1 is not ready; err: Get "http://localhost:32808/-/ready": dial tcp [::1]:32808: connect: connection refused

unexpected error: failed to get mapping for port as container e2e_test_receive_replication_with_outage-receive-1 exited: exit status 1: docker container receive-1 failed to start: exit status 1

unexpected error: failed to get mapping for port as container e2e_test_query-receive-1 exited: exit status 1: docker container receive-1 failed to start: exit status 1

unexpected error: failed to get mapping for port as container e2e_test_receive_hashring-receive-1 exited: exit status 1: docker container receive-1 failed to start: exit status 1


```

even though  ```make docker``` is successful , can someone point me a direction?

**Comment by bwplotka** [comment]
I would look on docker container logs before the error happens. Anything interesting being printeD? (:

**Comment by kjge** [comment]
I checked the docker log before but didn't find anything that stands out

```
level=info ts=2020-07-07T02:51:53.619Z caller=main.go:231 msg="Starting Alertmanager" version="(version=0.20.0, branch=HEAD, revision=f74be0400a6243d10bb53812d6fa408ad71ff32d)"
level=info ts=2020-07-07T02:51:53.620Z caller=main.go:232 build_context="(go=go1.13.5, user=root@00c3106655f8, date=20191211-14:13:14)"
level=info ts=2020-07-07T02:51:53.624Z caller=cluster.go:161 component=cluster msg="setting advertise address explicitly" addr=172.26.0.2 port=9094
level=info ts=2020-07-07T02:51:53.642Z caller=cluster.go:623 component=cluster msg="Waiting for gossip to settle..." interval=2s
level=info ts=2020-07-07T02:51:53.705Z caller=coordinator.go:119 component=configuration msg="Loading configuration file" file=/shared/data/am/1/config.yaml
level=info ts=2020-07-07T02:51:53.714Z caller=coordinator.go:131 component=configuration msg="Completed loading of configuration file" file=/shared/data/am/1/config.yaml
level=info ts=2020-07-07T02:51:53.725Z caller=main.go:497 msg=Listening address=0.0.0.0:8080
level=info ts=2020-07-07T02:51:55.610Z caller=cluster.go:648 component=cluster msg="gossip not settled" polls=0 before=0 now=1 elapsed=2.0015497s
level=info ts=2020-07-07T02:52:03.612Z caller=cluster.go:640 component=cluster msg="gossip settled; proceeding" elapsed=10.0036739s
level=info ts=2020-07-07T02:52:24.791Z caller=main.go:536 msg="Received SIGTERM, exiting gracefully..."

```
honestly I am pretty stumped on this, It seems like the docker container shuts down before the test is ran ,  I feel like I am missing some basic setup, am I suppose to export certain variables somewhere? before I run `make test-e2e`

```        
 unexpected error: the service querier-1 is not ready; err: Get "http://localhost:33337/-/ready": dial tcp [::1]:33337: connect: connection refused
```

**Comment by jtlisi** [comment]
I recently got the integration test suite running on Mac OS 10.15.6 Catalina ran into a similar issue.

First, if you haven't yet, I highly recommend reinstalling Docker for Mac from scratch after upgrading to Catalina. Be sure to remove all of the system files. This is a helpful guide: https://nektony.com/how-to/uninstall-docker-mac

Second, the `make docker` command will build a docker image with the binary built using your OS. So the docker image produced on Mac OS X when running `make docker` will result in a error message that looks like:

```console
$ docker run thanos
exec user process caused "exec format error"
```

Instead you are going to want to build the image using the following make command:

```console
make docker-multi-stage
```

This will create an image with the proper OS and Arch.
