### ISSUE TITLE
need remote write config for Ruler

### ISSUE THREAD

**Issue by diemus** [thanos-io/thanos#2825]
since thanos have Receive to become a remote write point, it's very helpful if the Rule can have remote write config too. then everything can be query from the Store. the Ruler can be more stateless.

**Comment by brancz** [comment]
There is already an [accepted proposal](https://github.com/thanos-io/thanos/blob/master/docs/proposals/202005_scalable-rule-storage.md) for this. The devil's as always in the detail though, there are still some things to be figured out, such as how to replay `ALERT_FOR_STATE` from a query.

**Comment by brancz** [comment]
Closing here to focus discussion around the proposal.
