### ISSUE TITLE
Random duplicate/divided metric data value

### ISSUE THREAD

**Issue by supasteev0** [thanos-io/thanos#2836]
**Thanos, Prometheus and Golang version used**:
Thanos 0.12.2
Prometheus: 2.11.0

**Object Storage Provider**:
AWS S3
**What happened**:
I am  currently facing an issue in thanos query where metric data appears to be duplicated/doubled at random times , and then "divided by two" (returning the correct value).
I get the same result when checking deduplication and/or using non downsampled and downsampled data.
I also noticed that the division "moves over time", meaning I can see the drop in the graph at a different hour when I run the query at different times.

Here is the graphed query result: 

![thanos_divided_metric_data](https://user-images.githubusercontent.com/8753896/86371334-0c37ad80-bc81-11ea-9d1b-e00d52689df4.png)

The current architecture is: 
- one main kubernetes cluster running thanos query configured with multiple thanos queriers from other clusters
- each cluster has :
    - 2 prometheus pods with thanos sidecar
    - thanos query
    - thanos store
    - thanos compact.

**What you expected to happen**:

Have the correct metric data at any time

**How to reproduce it (as minimally and precisely as possible)**:

Run a query in thanos query with : 
`sum(container_cpu_usage_seconds_total{cluster="xxxx",namespace="xxxx"}) by (pod)`
on a long period of time (24 hours at least)

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by GiedriusS** [comment]
A few stupid questions as a sanity check:
* Is it the same if you upgrade to the latest and greatest version?
* What (or how many?) `--query.replica-label`s have you specified?
* Do the numbers line up i.e. if you add them manually together is it the same number when using `sum(...) by (pod)`? At the very least, could you please see what are the values of individual metrics and then the sum of it when you get such results?

**Comment by supasteev0** [comment]
Thanks for your reply.

- I haven't tried to upgrade to version 0.13 yet as it was released not long ago. Will give it a try.
- I have 2 --query.replica-label configured on all thanos queriers, which are custom labels configured in all Prometheus: "cluster" and "region". The default "prometheus-replica" label is also set on remote Prometheus (I can see it in the stores) , and contains the default value which is the name of the pod ("prometheus-0", "prometheus-1") but I did not add this label in --query.replica-label.
- The correct number for the metric is the one after the "drop" in the graph. I can actually check that because I also have Grafana installed on remote clusters, with prometheus as datasource, and I don't have the same behaviour: I can see the correct numbers in the remote Grafana, which is the one after the "drop".

**Comment by supasteev0** [comment]
For now, I have added: 
`--query.replica-label=prometheus_replica`
to thanos-query deployment.
It seems to have fixed the issue.

I was also wondering if having thanos-query + thanos compact + thanos store deployed on each cluster is absolutely necessary ?
Or should the main thanos-query be able to query remote sidecars directly ? (knowing that I can't have any TLS configured in any Thanos component). I tried to have only thanos-sidecar deployed via Prometheus operator on each cluster at first, but could not make it work (Thanos query unable to communicate with sidecar store). 
I have one S3 bucket per cluster, as it doesn't seem possible to store différent cluster metrics in the same bucket in sub path at the moment.

**Comment by jvelasquez** [comment]
> For now, I have added:
> `--query.replica-label=prometheus_replica`
> to thanos-query deployment.
> It seems to have fixed the issue.
> 
> I was also wondering if having thanos-query + thanos compact + thanos store deployed on each cluster is absolutely necessary ?
> Or should the main thanos-query be able to query remote sidecars directly ? (knowing that I can't have any TLS configured in any Thanos component). I tried to have only thanos-sidecar deployed via Prometheus operator on each cluster at first, but could not make it work (Thanos query unable to communicate with sidecar store).
> I have one S3 bucket per cluster, as it doesn't seem possible to store différent cluster metrics in the same bucket in sub path at the moment.

Hi @supasteev0 , 

I think there are ways to configure, but seems like the most frequent is deploying all components in all the workload clusters and having a "central" observer cluster (which can be any of your workload clusters) which connects via gRPC into other cluster's query service. You can do VPC peering and create internal Loadbalancers with proper firewall rules etc, no need to do TLS in that case. 

![image](https://user-images.githubusercontent.com/1578922/116382211-9606c780-a80d-11eb-9ff4-4cbe1e998ad6.png)
