### ISSUE TITLE
objstore: (Azure) API version to support Azure Stack Hub

### ISSUE THREAD

**Issue by dbrennand** [thanos-io/thanos#2839]
**Thanos, Prometheus and Golang version used**:
I am using the following [bitnami/thanos chart](https://github.com/bitnami/charts/tree/master/bitnami/thanos) and [bitnami/prometheus-operator chart](https://github.com/bitnami/charts/tree/master/bitnami/prometheus-operator). I decided to raise this issue here (upstream) as I believe this is a issue related to Thanos and not the bitnami helm chart.
Output from helm list:
```
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
prometheus-operator     monitoring      1               2020-06-29 15:24:58.8131642 +0100 BST   deployed        prometheus-operator-0.21.3      0.40.0
thanos                  monitoring      1               2020-07-03 12:58:10.3070806 +0100 BST   deployed        thanos-1.1.2                    0.13.0
```

I believe the docker image used can be found here: https://github.com/bitnami/bitnami-docker-thanos

**Object Storage Provider**:
Azure Storage provider

**What happened**:
The following error occurs when attempting to create an Azure blob container in a storage account on Azure Stack Hub:
```
level=error ts=2020-07-03T11:58:25.849805438Z caller=main.go:185 err="-> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.8.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=) =====\nDescription=The value for one of the HTTP headers is not in the correct format.\nRequestId:3ef6b3a4-61b6-0ace-5062-8f1434a085ba\nTime:2020-07-03T11:58:25.8485135Z, Details: \n   Code: InvalidHeaderValue\n   HeaderName: x-ms-version\n   HeaderValue: 2018-11-09\n   PUT https://thanosdata.blob.frn00006.azure.ukcloud.com/thanoscontainer?restype=container&timeout=61\
```

**What you expected to happen**:
Exactly this, as the [Azure Stack Hub storage provider](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-profiles-azure-resource-manager-versions?view=azs-2002#overview-of-the-2019-03-01-hybrid-profile) uses a different API version to public Azure.

![image](https://user-images.githubusercontent.com/52419383/86469157-c4705f00-bd30-11ea-9cc0-283c1203ccbc.png)

**How to reproduce it (as minimally and precisely as possible)**:
Helm version:
```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```
Kubernetes cluster version:
```
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"d2ea02d7bcf37724adabbdb9d37ede0cf2c0d627", GitTreeState:"clean", BuildDate:"2020-04-24T22:59:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
Using the bitnami/thanos helm chart, however, I believe this would occur no matter what version of Thanos is used. As far as I can see there is no way to configure the API version (x-ms-version header) for Thanos to pass to the azure-storage-blob-go SDK.

**Full logs to relevant components**:
Appropriate logs for error provided above.

**Anything else we need to know**:
Essentially, I guess this is a feature request to add something similar to this for the Azure storage provider [config](https://github.com/thanos-io/thanos/blob/master/pkg/objstore/azure/azure.go#L28):
```yaml
objstoreConfig: |-
  type: AZURE
  config:
    storage_account: "thanosdata"
    storage_account_key: "REDACTED"
    container: "thanoscontainer"
    endpoint: "blob.frn00006.azure.ukcloud.com/"
    max_retries: 0
    # Allow declaration of API version
    api_version: ChosenApiVersionHere
#...
```

**Comment by dbrennand** [comment]
Potentially useful code for this: https://github.com/Azure/azure-storage-blob-go/blob/3efca72bd11c050222deab57e25ea90df03b9692/azblob/zz_generated_container.go#L86

**Comment by dbrennand** [comment]
@vglafirov I see you are listed as the maintainer of the Azure object storage client. Is this possible? :-)

**Comment by dbrennand** [comment]
Still applicable.

**Comment by bwplotka** [comment]
Yup. Makes sense to us. PRs welcome (:

**Comment by wturner123** [comment]
Apologies, just missed this. I've picked this up on behalf of @dbrennand. 
Still needs fixing, but unsure who will be able to pick it up.

**Comment by kakkoyun** [comment]
Still valid and help wanted 🤗

**Comment by wiardvanrij** [comment]
I'm not sure if this is possible; azure-go uses `ServiceVersion` as a const and it has 0 methods to change this. One perhaps...could use a http roundtripper to 'hack' this in for each request. That's just not sane. Otherwise we could implement some function overrides. 
To be honest,  if we want this, we should create a feature request at azure-go.

**Comment by a01fe** [comment]
Has anyone found a workaround for this issue?

Besides not using Azure Stack Hub, which unfortunately is not an option for me 🤷‍♀️ 😹

**Comment by dbrennand** [comment]
> Has anyone found a workaround for this issue?
> 
> Besides not using Azure Stack Hub, which unfortunately is not an option for me 🤷‍♀️ 😹

Hi @a01fe 

I raised this issue a very long time ago, from what I recall, we ended up having to use a Public Azure storage account and it wasn't possible to use one on Azure Stack Hub due to the API version mismatch and having no way to specify a different one.

**Comment by a01fe** [comment]
@dbrennand ty for the reply! Looks like I'll have to do something like that. Hoping to use ASH storage since that's where our clusters are.
