### ISSUE TITLE
Store: limit queried chunks by bytes

### ISSUE THREAD

**Issue by pracucci** [thanos-io/thanos#2861]
In the PR https://github.com/thanos-io/thanos/pull/2858 we've introduced `ChunksLimiter` in the Thanos store to limit the number of chunks fetched by a single `Series()` call.

It could make sense to add a limit based on "chunks bytes" instead of "chunks count" (on in addition to "chunks count" if Cortex will need to support it) as a easier unit to work when doing capacity planning and fine tuning the Thanos store.

**Comment by pracucci** [comment]
_Still valid, some help wanted (should be easy to do)._

**Comment by mneverov** [comment]
Hi, I'd like to work on this.

@pracucci should a new limiter be added or should it replace the existing one?

**Comment by pracucci** [comment]
> @pracucci should a new limiter be added or should it replace the existing one?

I would be glad if we could keep support for limiting by number of chunks as well (at least in the code) because we're using it in Cortex.

**Comment by pracucci** [comment]
Still valid. The PR #3089 addresses it.
