### ISSUE TITLE
compactor: Enable vertical compaction without replica labels.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2870]
We use vertical compaction now on prod and it works super smooth. We do that for offline dedup of exactly the sample samples replicas, but it actually saves a lot of troubles on overlaps. Compactor just easily deals with that.

I would propose to allow enabling vertical compaction without any replicas dedup (: Thoughts? @brancz @metalmatze @kakkoyun

**Comment by brancz** [comment]
Generally happy with this.

There was a bug iirc where blocks with no labels were rejected or something along those lines. If this has been resolved (iirc some fake label was added or was discussed to be added), then we should be ok with this.

**Comment by kakkoyun** [comment]
Still valid.
