### ISSUE TITLE
reloader: Apply error in loop should not kill the sidecar.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2873]
There is no need to get the process down in this case and decrease availability, handle the error in a different way.

https://github.com/thanos-io/thanos/blob/5d7bb2bfe094048a47a979042bba4b6ceb31a8e0/pkg/reloader/reloader.go#L220

AC:
* Reloader error should not restart whole sidecar (similar to fail on Prometheus Configuration reload - it takes old file)
* Be nicer to external users of this package and introduce opts to constructor.

**Comment by mneverov** [comment]
hi, i'd like to work on this.
