### ISSUE TITLE
Thanos Query not able to fetch data from Thanos Store

### ISSUE THREAD

**Issue by sushanco** [thanos-io/thanos#2879]
**Thanos, Prometheus and Golang version used**:
Thanos: v0.13.0
Prometheus: v2.16.0
Prometheus Operator: v0.38.1

**Object Storage Provider**:
AWS S3

**What happened**:
Thanos Query UI displays the _Status_ of the only store I have as UP, in addition I can see the correct labels in the _Announced LabelSets_.
Also, I had a look at the data directory inside the Store pod, I can see all the block's metadata sync'd however when I execute any query on the Query UI I get **No StoreAPIs matched for this query**. 

In this setup is Sidecar uploads data to S3 bucket. Store is configured to read the S3 bucket and Query queries the Store.

Sidecar:
```
    - sidecar
    - --prometheus.url=http://localhost:9090/
    - --tsdb.path=/prometheus
    - --grpc-address=[$(POD_IP)]:10901
    - --http-address=[$(POD_IP)]:10902
    - --objstore.config=$(OBJSTORE_CONFIG)
```
Query:
```
    - query
    - --log.level=debug
    - --log.format=json
    - --grpc-address=0.0.0.0:10901
    - --http-address=0.0.0.0:10902
    - --store=dnssrv+_grpc._tcp.thanos-store.monitoring.svc.cluster.local
    - --query.timeout=5m
```
Store:
```
    - store
    - --log.level=debug
    - --log.format=json
    - --data-dir=/data
    - --grpc-address=0.0.0.0:10901
    - --http-address=0.0.0.0:10902
    - --objstore.config-file=/etc/prometheus/store-s3-config.yml
```

**What you expected to happen**:
Query to return result from Store.
 
**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

<details> Query Logs:
<p>
{"caller":"main.go:102","level":"debug","msg":"maxprocs: Leaving GOMAXPROCS=[4]: CPU quota undefined","ts":"2020-07-10T14:19:49.942128629Z"}
{"caller":"main.go:151","level":"info","msg":"Tracing will be disabled","ts":"2020-07-10T14:19:49.94237047Z"}
{"caller":"engine.go:311","level":"debug","msg":"Lookback delta is zero, setting to default value","ts":"2020-07-10T14:19:49.942685867Z","value":"5m0s"}
{"caller":"options.go:23","level":"info","msg":"disabled TLS, key and cert must be set to enable","protocol":"gRPC","ts":"2020-07-10T14:19:49.943651036Z"}
{"caller":"query.go:403","level":"info","msg":"starting query node","ts":"2020-07-10T14:19:49.943957429Z"}
{"caller":"intrumentation.go:60","level":"info","msg":"changing probe status","status":"healthy","ts":"2020-07-10T14:19:49.944084047Z"}
{"address":"0.0.0.0:10902","caller":"http.go:56","component":"query","level":"info","msg":"listening for requests and metrics","service":"http/server","ts":"2020-07-10T14:19:49.944134328Z"}
{"cachedStores":0,"caller":"storeset.go:331","component":"storeset","level":"debug","msg":"starting updating storeAPIs","ts":"2020-07-10T14:19:49.944387004Z"}
{"activeStores":0,"cachedStores":0,"caller":"storeset.go:334","component":"storeset","level":"debug","msg":"checked requested storeAPIs","ts":"2020-07-10T14:19:49.94447081Z"}
{"caller":"intrumentation.go:48","level":"info","msg":"changing probe status","status":"ready","ts":"2020-07-10T14:19:49.944429086Z"}
{"address":"0.0.0.0:10901","caller":"grpc.go:108","component":"query","level":"info","msg":"listening for serving gRPC","service":"gRPC/server","ts":"2020-07-10T14:19:49.944570088Z"}
{"cachedStores":0,"caller":"storeset.go:331","component":"storeset","level":"debug","msg":"starting updating storeAPIs","ts":"2020-07-10T14:19:54.944560358Z"}
{"activeStores":1,"cachedStores":0,"caller":"storeset.go:334","component":"storeset","level":"debug","msg":"checked requested storeAPIs","ts":"2020-07-10T14:19:54.949979085Z"}
{"address":"172.30.142.55:10901","caller":"storeset.go:372","component":"storeset","extLset":"{cluster=\"eu-ops\", prometheus=\"monitoring/main\", prometheus_replica=\"prometheus-main-0\"},{cluster=\"eu-ops\", prometheus=\"monitoring/main\", prometheus_replica=\"prometheus-main-1\"},{cluster=\"eu-test\", eu_test_b=\"monitoring/main\", prometheus_replica=\"prometheus-main-0\"},{cluster=\"eu-test\", eu_test_b=\"monitoring/main\", prometheus_replica=\"prometheus-main-1\"},{cluster=\"us-test\", prometheus_replica=\"prometheus-main-0\", us_test_b=\"monitoring/main\"},{cluster=\"us-test\", prometheus_replica=\"prometheus-main-1\", us_test_b=\"monitoring/main\"}","level":"info","msg":"adding new storeAPI to query storeset","ts":"2020-07-10T14:19:54.950074404Z"}
{"caller":"proxy.go:287","level":"debug","msg":"store Addr: 172.30.142.55:10901 LabelSets: [name:\"cluster\" value:\"eu-ops\" ,name:\"prometheus\" value:\"monitoring/main\" ,name:\"prometheus_replica\" value:\"prometheus-main-0\" ][name:\"cluster\" value:\"eu-ops\" ,name:\"prometheus\" value:\"monitoring/main\" ,name:\"prometheus_replica\" value:\"prometheus-main-1\" ][name:\"cluster\" value:\"eu-test\" ,name:\"eu_test_b\" value:\"monitoring/main\" ,name:\"prometheus_replica\" value:\"prometheus-main-0\" ][name:\"cluster\" value:\"eu-test\" ,name:\"eu_test_b\" value:\"monitoring/main\" ,name:\"prometheus_replica\" value:\"prometheus-main-1\" ][name:\"cluster\" value:\"us-test\" ,name:\"prometheus_replica\" value:\"prometheus-main-0\" ,name:\"us_test_b\" value:\"monitoring/main\" ][name:\"cluster\" value:\"us-test\" ,name:\"prometheus_replica\" value:\"prometheus-main-1\" ,name:\"us_test_b\" value:\"monitoring/main\" ] Mint: 1594303200000 Maxt: 1594382400000 filtered out","ts":"2020-07-10T14:22:14.215993424Z"}
{"caller":"proxy.go:291","err":"No StoreAPIs matched for this query","level":"warn","stores":"store Addr: 172.30.142.55:10901 LabelSets: [name:\"cluster\" value:\"eu-ops\" ,name:\"prometheus\" value:\"monitoring/main\" ,name:\"prometheus_replica\" value:\"prometheus-main-0\" ][name:\"cluster\" value:\"eu-ops\" ,name:\"prometheus\" value:\"monitoring/main\" ,name:\"prometheus_replica\" value:\"prometheus-main-1\" ][name:\"cluster\" value:\"eu-test\" ,name:\"eu_test_b\" value:\"monitoring/main\" ,name:\"prometheus_replica\" value:\"prometheus-main-0\" ][name:\"cluster\" value:\"eu-test\" ,name:\"eu_test_b\" value:\"monitoring/main\" ,name:\"prometheus_replica\" value:\"prometheus-main-1\" ][name:\"cluster\" value:\"us-test\" ,name:\"prometheus_replica\" value:\"prometheus-main-0\" ,name:\"us_test_b\" value:\"monitoring/main\" ][name:\"cluster\" value:\"us-test\" ,name:\"prometheus_replica\" value:\"prometheus-main-1\" ,name:\"us_test_b\" value:\"monitoring/main\" ] Mint: 1594303200000 Maxt: 1594382400000 filtered out","ts":"2020-07-10T14:22:14.216064706Z"}
{"cachedStores":1,"caller":"storeset.go:331","component":"storeset","level":"debug","msg":"starting updating storeAPIs","ts":"2020-07-10T14:22:14.94456761Z"}
</p>
</details>

<details> Store Logs:
<p>
{"caller":"bucket.go:472","elapsed":"320.143615ms","id":"01ECTWX7M3SCBJ6X2W6AWEXH51","level":"info","msg":"loaded new block","ts":"2020-07-10T14:19:38.799379641Z"}
{"caller":"bucket.go:472","elapsed":"546.499444ms","id":"01ECT8A2340AN60HW2FMMGKQQZ","level":"info","msg":"loaded new block","ts":"2020-07-10T14:19:38.800253685Z"}
{"caller":"bucket.go:472","elapsed":"436.845637ms","id":"01ECVAMNX9A54D9BYVWYZXKS8D","level":"info","msg":"loaded new block","ts":"2020-07-10T14:19:38.81362334Z"}
{"caller":"binary_reader.go:463","elapsed":"308.370027ms","level":"debug","msg":"built index-header file","path":"/data/01ECW63K3ZE1733ACPACP67YX3/index-header","ts":"2020-07-10T14:19:38.821278986Z"}
{"caller":"bucket.go:472","elapsed":"326.675514ms","id":"01ECW63K3ZE1733ACPACP67YX3","level":"info","msg":"loaded new block","ts":"2020-07-10T14:19:38.83909631Z"}
{"caller":"binary_reader.go:463","elapsed":"356.271707ms","level":"debug","msg":"built index-header file","path":"/data/01ECVHGDK4HJYXE9MT7W0JFFQJ/index-header","ts":"2020-07-10T14:19:38.846947181Z"}
{"caller":"binary_reader.go:463","elapsed":"362.973716ms","level":"debug","msg":"built index-header file","path":"/data/01ECVAMPB4PDCJF7ARBZD8XQNW/index-header","ts":"2020-07-10T14:19:38.856157947Z"}
{"caller":"bucket.go:472","elapsed":"375.948785ms","id":"01ECVHGDK4HJYXE9MT7W0JFFQJ","level":"info","msg":"loaded new block","ts":"2020-07-10T14:19:38.866528583Z"}
{"caller":"bucket.go:472","elapsed":"379.928606ms","id":"01ECVAMPB4PDCJF7ARBZD8XQNW","level":"info","msg":"loaded new block","ts":"2020-07-10T14:19:38.873011947Z"}
{"caller":"binary_reader.go:463","elapsed":"317.60763ms","level":"debug","msg":"built index-header file","path":"/data/01ECT8A1N8FN5ZC0ZPJXBRDK4D/index-header","ts":"2020-07-10T14:19:38.875763012Z"}
{"caller":"bucket.go:472","elapsed":"370.279365ms","id":"01ECT8A1N8FN5ZC0ZPJXBRDK4D","level":"info","msg":"loaded new block","ts":"2020-07-10T14:19:38.92832635Z"}
{"caller":"store.go:323","init_duration":"1.714322167s","level":"info","msg":"bucket store ready","ts":"2020-07-10T14:19:38.928766649Z"}
{"caller":"intrumentation.go:48","level":"info","msg":"changing probe status","status":"ready","ts":"2020-07-10T14:19:38.929180391Z"}
{"address":"0.0.0.0:10901","caller":"grpc.go:108","component":"store","level":"info","msg":"listening for serving gRPC","service":"gRPC/server","ts":"2020-07-10T14:19:38.929353214Z"}
{"cached":50,"caller":"fetcher.go:452","component":"block.BaseFetcher","duration":"386.162162ms","level":"info","msg":"successfully synchronized block metadata","partial":0,"returned":50,"ts":"2020-07-10T14:19:39.315032372Z"}
{"cached":50,"caller":"fetcher.go:452","component":"block.BaseFetcher","duration":"530.803255ms","level":"info","msg":"successfully synchronized block metadata","partial":0,"returned":50,"ts":"2020-07-10T14:22:39.459858073Z"}
{"cached":50,"caller":"fetcher.go:452","component":"block.BaseFetcher","duration":"458.341288ms","level":"info","msg":"successfully synchronized block metadata","partial":0,"returned":50,"ts":"2020-07-10T14:25:39.387448225Z"}
</p>
</details>

**Comment by ramesh-kumarjha** [comment]
I am getting the same issue only getting 2 hours data after that i am not getting data and data are push to s3 bucket 
--prometheus.url=http://127.0.0.1:9090/
    - --grpc-address=[$(POD_IP)]:10901
    - --http-address=[$(POD_IP)]:10902
    - --objstore.config=$(OBJSTORE_CONFIG)
    - --tsdb.path=/prometheus
    - --log.level=info
    - --log.format=logfmt

**Comment by PrabdeepBajaj** [comment]
Facing same issue , anyone got any solution ?

**Comment by abdennour** [comment]
somehow, thanos should support same parameter like `--no-sign-request` in AWS CLI

**Comment by zdelagrange** [comment]
Same issue, has anyone solved this?

**Comment by KyMidd** [comment]
@zdelagrange 's solution worked for me. I was seeing the Stores populated, and IRSA/IAM permissions on the Store endpoint were for sure right, but no data showed up for even simple queries like "up". Until I click the "Evaluation Time" box to go back a few hours, since we're currently just reading S3 blocks, which are a few hours outdated. 

So if you have this same issue, click the left arrow on "Evaluation Time" on the Graph tab on the Query component, and you might see logs appear.
