### ISSUE TITLE
bucket web: Selectable time range

### ISSUE THREAD

**Issue by wrossmann** [thanos-io/thanos#2880]
The current `bucket web` view gets pretty cramped once you get a few months of data stored, eg: 

![image](https://user-images.githubusercontent.com/4967671/87183092-4ebd4380-c29a-11ea-85d1-81e5e4cc2547.png)

I've only got stats back to October, and the window is as big as I can make it on my 4K monitor.

It would be nice to be able to define a time range for the view so that fresh blocks are larger than a couple pixels.

**Comment by prmsrswt** [comment]
@wrossmann This should be fixed in the new Block Viewer. We now have a range slider to select the time range you want to view.
