### ISSUE TITLE
bucket: Add a Store API endpoint that serves bucket stats

### ISSUE THREAD

**Issue by wrossmann** [thanos-io/thanos#2882]
Having a GRPC Store API endpoint for serving bucket metadata would be useful for graphing and tracking trends in bucket data, and would "liberate" the data from being the sole domain of the CLI bucket tools and the bucket web UI.

For quite some time I could never put a finger on why `thanos bucket web` seemed out of place, but I realized that it's because you have this wonderful ecosystem for collecting, querying, and displaying data, and the bucket metadata is this odd duck on the side with what seems like a completely custom workflow from soup to nuts.

**Comment by GiedriusS** [comment]
Hm... reading this again gave me an idea: is there a reason why we couldn't have it in Thanos Store or other components as well? Kind of like `Info()` but for the bucket's metadata.

**Comment by wrossmann** [comment]
That actually makes much more sense now that I think about it. The Store components are already sitting there with the bucket config and running an endpoint. I can also see having N extra bucket services could get a bit tedious for people with multiple stores.
