### ISSUE TITLE
Init all labeled counter metrics to 0

### ISSUE THREAD

**Issue by belm0** [thanos-io/thanos#2889]
**Thanos, Prometheus and Golang version used**:
thanos v0.13.0

**What happened**:
Thanos jobs counter metrics with labels are not initialized to 0 for the known labels.

For example, `thanos_compact_downsample_total{group="3600000@4233639831006398026"}` would not be exported by thanos-compact until the first 1h downsample after starting the server.  Prometheus queries are hard to manage with data series that disappear, it causes problems with `increase()`, etc.

**What you expected to happen**:
Per prometheus best practice, when thanos jobs start they should register the known label sets of counters so that the collector publishes a 0 value for the counters.

**Comment by bwplotka** [comment]
That's very valid. Help wanted :hugs:
