### ISSUE TITLE
Bucket verify overlap issue

### ISSUE THREAD

**Issue by vaibhavgulati** [thanos-io/thanos#2909]
Thanos bucket verify command is giving overlapping error issues(2):
level=warn ts=2020-07-20T10:58:52.546743255Z caller=overlapped_blocks.go:43 msg="found overlapped blocks" group=0@10334104636911659965 overlap="[mint: 1595102400000, maxt: 1595109600000, range: 2h0m0s, blocks: 3]
level=warn ts=2020-07-20T10:58:52.546893575Z caller=overlapped_blocks.go:43 msg="found overlapped blocks" group=0@2393572128038720598 overlap="[mint: 1595145600000, maxt: 1595152800000, range: 2h0m0s, blocks: 2]

**Comment by kakkoyun** [comment]
Hey @vaibhavgulati, thanks for reaching out.

Maybe I am missing something but that's what `bucket verify` suppose to do. Find out the issues with the blocks. Could you check out the documentation, https://thanos.io/components/tools.md/#bucket-verify and tell us what was the expectation and why it wasn't fulfilled?

Also, it'd be great if you could provide more information. Answering the questions that we've already put in the template would help. Don't you agree?

**Object Storage Provider**?
**What happened**?
**What you expected to happen**?
**How to reproduce it (as minimally and precisely as possible)**?
**Full logs to relevant components**?

**Comment by kakkoyun** [comment]
@vaibhavgulati Friedly ping. Any comments?
