### ISSUE TITLE
Query inconsistency when changing external label value

### ISSUE THREAD

**Issue by ahurtaud** [thanos-io/thanos#2912]
**Thanos, Prometheus and Golang version used**: thanos v0.14, prometheus v2.19.2

**Object Storage Provider**: S3

**What happened**:
When changing in prometheus the value of an externalLabel, prometheus will change the value for all its persistent data (externalLabels are not time-based in prometheus.)
Whereas on the object storage, they are updated after at most 2hours (time of first upload).
This leads to an inconsistent deduplication while querying both sidecar and store.
![Capture](https://user-images.githubusercontent.com/25080995/87955976-bd767a00-caae-11ea-8fdd-6cd8f48aa4a4.png)
(production_ready is one external label we have change on 15 July.)

Of course the issue "disappears" once prometheus retention is gone...

**What you expected to happen**:
Dont have conflicts between sidecar and store data.

**How to reproduce it (as minimally and precisely as possible)**:
1. Have prometheus send some data to objectstorage with custom external labels.
2. Change prometheus external labels value
3. Execute a thanos query matching both a store with previous external labels and live data from sidecar

**Anything else we need to know**:
I understand a fix is not easy for this as:
- it is not a bug in prometheus.
- Not much thanos can do... (maybe when external labels are conflicting on thanos queries? Always prefer sidecar ones?

**Comment by bwplotka** [comment]
Yes, currently it works as designed.

**Comment by bwplotka** [comment]
> Not much thanos can do... (maybe when external labels are conflicting on thanos queries? Always prefer sidecar ones?

Yea, for Querier those are just separate series.


What about adjusting `dedup` labels on Querier? You can add more than just one and maybe you can add some in a way that would mitigate your problem?

**Comment by ahurtaud** [comment]
Indeed adding it in the dedup labels list is not something I thought about. It should indeed fix the problem. Thanks for the tips!

Again, externalLabels are not meant to change a lot in the lifetime of a prometheus. We basically are using this one to enable paging once a new prometheus is created after memory, cpu etc is stable. We dont really need it in querying so yeah dedup can be a good option.

I am not sure if we want to do anything on thanos side for it...

**Comment by kakkoyun** [comment]
@ahurtaud It seems like everything works as it supposes to. Shall we close the issue?

**Comment by ahurtaud** [comment]
Yep closing it, adding the label to dedup mitigated our issue. Thanks
