### ISSUE TITLE
querier: Allow passing allow-list of store (IPs?) that should be used for query for debug purposes; Add multiselect on UI

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2919]
It would be awesome to add the ability to query only a subset of stores to detect which one is slow/ problematic etc (: It should be hidden option only for ad-hoc query.

**Comment by geobeau** [comment]
I am interested in doing it.

After looking at how to implement it, I have a design question: the query api uses the proxy as a `storepb.StoreServer` and the logic behind the store selection is done after calling `storepb.StoreServer.Series()`, however there is no way of passing an allowlist without extending the interface. Would be okay to change querier.proxy to use directly `ProxyStore` in place of `storepb.StoreServer`?

**Comment by bwplotka** [comment]
Awesome. I think it would be nice to avoid passing this in protobuf, but we could technically create some hints.

I would also avoid running just ProxyStore and changing methods. 

We have two options:
1. Pass through context as a best-effort thing
2. Extend protobuf

I would start for now with 1 and then 2 long term. WDYT? (:

**Comment by geobeau** [comment]
Pass through context seems good for me. 👍

**Comment by geobeau** [comment]
Hello, can you take a look at #2931 ? It's still in WIP as I need to finish the testing but I would like your input first.

**Comment by bwplotka** [comment]
I did, and left some comments. Good approach overall!

**Comment by bwplotka** [comment]
It's now done in https://github.com/thanos-io/thanos/pull/2931 and documented.
