### ISSUE TITLE
Query instances should error when there are no store instances in the cluster

### ISSUE THREAD

**Issue by mattbostock** [thanos-io/thanos#292]
If there are no store instances in the cluster, the query instance should periodically log an error, similar to the way we log an error if a node is alone in the cluster.

The aim is to quickly identify when a query instance has been able to connect to other query instance peers, but no store instance is known by the query instances.

The presence of statically-configured store nodes should prevent this error from appearing.

**Comment by Bplotka** [comment]
Revisiting this item and I am no longer sure if that is what we want. Similarly to Prometheus if you configure SD in such way that no data is there you will not have any targets and no error will be printed. I would say https://github.com/improbable-eng/thanos/issues/212 will help more in these cases, but no sure.. any thoughts?

**Comment by deejay1** [comment]
I'd rather not log the missing store, as it's not really needed for HA setups for example...

**Comment by Bplotka** [comment]
@deejay1 I think "store instance" here is just anything that exposes gRPC StoreAPI (so sidecar, store, ruler)

**Comment by deejay1** [comment]
@Bplotka ah, in that case ok, we should have at least one of {sidecar,store} available for query instances to work.

**Comment by yeya24** [comment]
Is this issue still valid?

**Comment by bwplotka** [comment]
It was mainly related to the gossip so not really (: Closing.
