### ISSUE TITLE
New component or tool: Thanos Debug UI aggregating Store/Rules/Target APIs results

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2920]
We are already discussing ideas like Rules UI for all alerts and rules in the Thanos & Prometheus systems as well as https://github.com/thanos-io/thanos/issues/1375 (Targets UI).

All of those does not really fit into Querier as those APIs can be different. The idea would be to add another component or tool like `thanos tools debug-ui` which will allow to:

* Discover all endpoints you point to
* Show Stores,Ruiles and Targets UIs

Further ideas are welcome (: 

cc @brancz

**Comment by bwplotka** [comment]
It could be combined with Block Viewer.

**Comment by brancz** [comment]
With the react UI move this should be trivial hopefully to have once in a single UI but keep the UIs on each component as well.

**Comment by bwplotka** [comment]
cc @prmsrswt @GiedriusS @squat

**Comment by prmsrswt** [comment]
Still valid, and on the roadmap.

Now that we have migrated the Block Viewer to React, we have a base to work upon.

**Comment by elysiumHL** [comment]
Still valid, this feature is very useful

**Comment by bwplotka** [comment]
I don't see this anymore TBH (: You can just run Querier locally at this point. Let's close it!
