### ISSUE TITLE
Rules HTTP API weirdness: nulls, different values for "same" field, lastEvaluation set to 0000

### ISSUE THREAD

**Issue by GiedriusS** [thanos-io/thanos#2938]
On top of:

https://github.com/thanos-io/thanos/pull/2865/commits/b2f1485e3239be07c93e68b404070d48b214965b from #2865 

With:
```
TZ=UTC PROMETHEUS_EXECUTABLE=~/dev/prometheus/prometheus ./scripts/quickstart.sh
```

Going to `localhost:19999/api/v1/rules?type=alert` gives:

```
{"status":"success","data":{"groups":[{"name":"example","file":"data/rules.yml","rules":null,"interval":30,"evaluationTime":0,"lastEvaluation":"0001-01-01T00:00:00Z","partial_response_strategy":"WARN","partialResponseStrategy":"ABORT"}]}}
```

Three things seem off to me:
* `rules` is null even though the branch contains https://github.com/thanos-io/thanos/pull/2888 which supposedly fixes this problem
* Two fields `partial_response_strategy` and `partialResponseStrategy` that should show the same value but they are different in this case :thinking: 
* `lastEvaluation` is _always_ set to `0001-01-01T00:00:00Z`

**Comment by yeya24** [comment]
@GiedriusS Is this fixed by https://github.com/thanos-io/thanos/pull/2925 already? 😄
