### ISSUE TITLE
Thanos-Reciever integration

### ISSUE THREAD

**Issue by Tikam02** [thanos-io/thanos#2942]
Is there any document, guide or tutorial regarding how to use thanos-receiver  component.
How to integrate thanos-receiver with Prometheus-operator or prometheus.

**Comment by kakkoyun** [comment]
@Tikam02 Thanos Receiver implements Prometheus Remote Write protocol. So anything sends remote-write messages can integrate with Thanos Receive. You can find related documentation using `remote write` as your search keyword. That said here are some pointers.

https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage

https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write

https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#remotereadspec

I hope this would help.
