### ISSUE TITLE
Fetch remaining data if chunk is bigger than 16000 bytes

### ISSUE THREAD

**Issue by pstibrany** [thanos-io/thanos#2945]
We have found a case where compactor can generate chunks [bigger than 16k](https://github.com/prometheus/prometheus/issues/5862). Currently when Thanos finds that it has loaded less than data than chunk length, it [returns error](https://github.com/thanos-io/thanos/blob/a64884b19dbe7a6c2613078a07409c89ce4e2508/pkg/store/bucket.go#L2029).

Instead of returning error, I propose to fetch remaining data instead in such case. Thoughts?

(This has been discussed at https://cloud-native.slack.com/archives/CL25937SP/p1595842211384500 as well)

**Comment by GiedriusS** [comment]
Fixed by https://github.com/thanos-io/thanos/pull/2956
