### ISSUE TITLE
Improve Receiver Documentation

### ISSUE THREAD

**Issue by kakkoyun** [thanos-io/thanos#2946]
The receiver needs more elaborate documentation.

We have seen a couple of issues that emphasizes the need. https://github.com/thanos-io/thanos/issues/2942 https://github.com/thanos-io/thanos/issues/2918#issuecomment-664449685

Better to add some pointers around integration

https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write
https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#remotereadspec

**Comment by adeniyistephen** [comment]
@kakkoyun Hi is it still open?

**Comment by kakkoyun** [comment]
Still valid.

**Comment by adeniyistephen** [comment]
Hello, @kakkoyun kindly provide Pointers and input for this issue. I would like to work on it.
