### ISSUE TITLE
Store: Increasing postings offsets ratio doesn't affect memory consumption

### ISSUE THREAD

**Issue by der-eismann** [thanos-io/thanos#2949]
**Thanos, Prometheus and Golang version used**: thanosio/thanos:v0.14.0, prom/prometheus:v2.20.0

**Object Storage Provider**: S3

**What happened**: I tried to tweak the memory consumption to get a lower value than the current 22 GB. I saw this description of the postings offset ratio [in the documentation](https://thanos.io/operating/binary-index-header.md/#impact-on-cpu-memory-and-disk) and tried this, but unfortunately it didn't have any effect on it. Not sure if I misunderstood something, but right now it looks like thanos is loading everything we have inside the RAM.

**What you expected to happen**: I expected the memory consumption to fall, of course with a trade off for the CPU.

**How to reproduce it (as minimally and precisely as possible)**:
- Run a thanos store instance with the default configuration on our bucket
- `container_memory_mapped_file` metric is at 20.13 GB
- Start thanos store instance with `--store.index-header-posting-offsets-in-mem-sampling=100` or even 200
- `container_memory_mapped_file` metric is still at 20.13 GB, which is the size of the `/var/thanos/store` folder

**Comment by der-eismann** [comment]
I just tried launching the store gateway with `--experimental.enable-index-cache-postings-compression`, but the memory consumption is still the same. Is there no way to reduce it?

**Comment by GiedriusS** [comment]
>     * `container_memory_mapped_file`

What about the residential set size? Have you tried checking out that?

**Comment by der-eismann** [comment]
Well, we actually noticed that after a while the consumption does drop indeed, it's just at the start that thanos is using up until the memory limit. But we could reduce the memory usage from 20 to 5 GB without it OOMing at all. So I guess the flags do work, it just takes a while.
