### ISSUE TITLE
Query: new UI doesn't honor --web.external-prefix or --web.route-prefix

### ISSUE THREAD

**Issue by mapshen** [thanos-io/thanos#2951]
**Thanos docker image version**: thanosio/thanos:v0.14.0

**What happened**:
Running Thanos Auery behind Nginx, with `--web.external-prefix=query` and `--web.route-prefix="/"`, so that Query is accessible at http://external.com/query. When you switch to "New UI" (http://external.com/query/new) in your browser:

1. the resulting page is blank;
2. all the buttons like "Graph" in the top navigation bar show links with `--web.external-prefix` snipped like "http://external.com/new/graph";
3. switch back to "Classic UI" directs me to "http://external.com/graph".

In addition, hitting URLs like "http://external.com/query/new/graph" returns blank pages.

**What you expected to happen**:
When you switch to "New UI" (http://external.com/query/new) in your browser:

1. the resulting page is not blank;
2. all the buttons like "Graph" in the top navigation bar show links with `--web.external-prefix` like "http://external.com/query/new/graph";
3. switch back to "Classic UI" directs me to "http://external.com/query/graph".

In addition, hitting URLs like "http://external.com/query/new/graph" doesn't return blank pages.

**How to reproduce it (as minimally and precisely as possible)**:
1. Run Thanos Query with `--web.external-prefix=query` and `--web.route-prefix="/"` on host `internal.com`
2. Configure Nginx for Query on host `external.com` with the following:
```
  location  /query/ {
    proxy_pass http://internal.com:10902/;
  }
```
3. Open up your browser, go to http://external.com/query and try switching to "New UI".

**Comment by prmsrswt** [comment]
This has been fixed in #2800 but hasn't made it to the release yet.

**Comment by mapshen** [comment]
@prmsrswt ah, thanks for this. Only searched through the issues, but not the pull requests. 

Looking forward to 0.15.0!

**Comment by mapshen** [comment]
I can confirm it's working in 0.15.0.
