### ISSUE TITLE
thanos ruler 0.13.0 meta.json not found error

### ISSUE THREAD

**Issue by youjiahe** [thanos-io/thanos#2953]
[root@thanos thanos]# /usr/local/thanos/thanos rule  --data-dir /usr/local/thanos/data  --eval-interval 30s  --rule-file /usr/local/thanos/rules.d/*.rules.yml  --alert.query-url http://10.92.206.68:9093  --alertmanagers.url http://10.92.206.69:9093  --grpc-address 0.0.0.0:10921  --http-address 0.0.0.0:10922  --objstore.config-file /usr/local/thanos/ecs-oss.yml  --query http://10.92.206.68:8090 
level=info ts=2020-07-29T07:13:02.043921352Z caller=main.go:151 msg="Tracing will be disabled"
level=error ts=2020-07-29T07:13:02.044604798Z caller=main.go:185 ***err="open /usr/local/thanos/data/01EEC86BFZ75CJS4HNJNVXJ926/meta.json: no such file or directory\nblock dir: ***\"/usr/local/thanos/data/01EEC86BFZ75CJS4HNJNVXJ926\"\ngithub.com/prometheus/prometheus/tsdb.repairBadIndexVersion.func1\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200420120812-fc3fb3265a0f/tsdb/repair.go:41\ngithub.com/prometheus/prometheus/tsdb.repairBadIndexVersion\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200420120812-fc3fb3265a0f/tsdb/repair.go:56\ngithub.com/prometheus/prometheus/tsdb.open\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200420120812-fc3fb3265a0f/tsdb/db.go:537\ngithub.com/prometheus/prometheus/tsdb.Open\n\t/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200420120812-fc3fb3265a0f/tsdb/db.go:495\nmain.runRule\n\t/app/cmd/thanos/rule.go:349\nmain.registerRule.func1\n\t/app/cmd/thanos/rule.go:171\nmain.main\n\t/app/cmd/thanos/main.go:183\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373\nopen TSDB\nmain.runRule\n\t/app/cmd/thanos/rule.go:351\nmain.registerRule.func1\n\t/app/cmd/thanos/rule.go:171\nmain.main\n\t/app/cmd/thanos/main.go:183\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373\npreparing rule command failed\nmain.main\n\t/app/cmd/thanos/main.go:185\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"

**Comment by bwplotka** [comment]
Hey, can we have more details, for example:

* What ruler was performing, what other log messages are there?
* Did ruler stopped after this error?
* Did you manage to mitigate it somehow or is it constantly crashing?
