### ISSUE TITLE
Announced LabelSets seeing all cluster and not just the one for the Endpoint

### ISSUE THREAD

**Issue by mei-ling** [thanos-io/thanos#2958]
**Thanos, Prometheus version used**:

Thanos Build version: 0.10.1
Prometheus-Operator version 8.14.0
Prometheus Build Version: 2.18.1

**Object Storage Provider**:

AWS S3

**What happened**:

We have Thanos-operator installed in one k8s cluster/AWS account and have Prometheus-operator installed in other accounts/k8s clusters. We're using the same S3 bucket that's located in the same account as Thanos-Operator for all the Prometheus instances.

Thanos-sidecar is installed in each of the Prometheus instances.  In our Thanos Query page, the Announced LabelSets is picking up all clusters info instead of the one cluster associated with the Endpoint.

<img width="1698" alt="Screen Shot 2020-07-29 at 4 58 36 PM" src="https://user-images.githubusercontent.com/11723005/88865718-76c70500-d1bd-11ea-842c-5e9f40b2a3d0.png">

**What you expected to happen**:

We would expect to see just the cluster info associated with its Endpoint, not all 3 cluster info.

Is it okay that we're using the one S3 bucket for everything? Either way, I'm not sure what is causing the LabelSets to be picking up all the cluster info for each Endpoint.

**Comment by bwplotka** [comment]
Sorry for lag in response, but this work as expected I believe.

> Thanos-sidecar is installed in each of the Prometheus instances. In our Thanos Query page, the Announced LabelSets is picking up all clusters info instead of the one cluster associated with the Endpoint.

What do you mean associated with endpoint? Looks like your thanos-query actually have data from those clusters that's it (:
