### ISSUE TITLE
Querier metrics for store/sidecar connectivity

### ISSUE THREAD

**Issue by hhsnow** [thanos-io/thanos#2961]
I would like to be able to monitor and alert on gRPC connectivity issues between Thanos querier and store/sidecar components. 

When queriers start up, if they are unable to fetch metadata from a configured --store, they throw warn logs and omit the store in the UI. 
```
level=warn ts=2020-07-30T10:45:09.886709248Z caller=storeset.go:487 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from example-store:443: rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = \"transport: Error while dialing dial tcp: lookup example-store on 172.20.0.10:53: no such host\"" address=example-store:443 
```
If a healthy store becomes unreachable, we see an info log, followed by the warn from above repeated.
```
level=info ts=2020-07-30T10:53:33.182800429Z caller=storeset.go:388 component=storeset msg="removing store because it's unhealthy or does not exist" address=example-store:443 extLset="{<external label set>}"
```
We also see a "Status: DOWN" in the UI for this store. (for a limited period?)

I would like to be able to be able to alert on individual stores being unhealthy, and track health over time, in case of intermittent issues.  Can a counter metric along the lines of this be added?
```
thanos_querier_store_apis_connection_error_total{addr="example-store:443", code="DeadlineExceeded"}
```
If it was an up/down gauge, that would be good too. My example is following the existing metric `thanos_querier_store_apis_dns_provider_results` which seems to be the only one to call out individual stores in it's labels.

**Comment by infa-kparida** [comment]
We are also looking for something like this.At present there is no way we can alert in case any store goes down

**Comment by infa-vmannam** [comment]
+1, Agree! along with alert, we'd also like to see the store endpoints in Querier UI despite it is DOWN for a long period. A simple rule can be like if it's present in the querier arguments it is good to show in UI along with irrespective of its status.

**Comment by litengfei-zz** [comment]
I have the same

**Comment by hhsnow** [comment]
commenting to remove stale label. still a needed feature for me.

**Comment by bwplotka** [comment]
That's a problematic one, mostly because the address is just an IP that can change anytime thus increasing cardinality. But I think after so many requests we would be willing to accept some contribution to actually put `address` in label. I definitely see much use of it.

Help wanted.

Related issue: https://github.com/thanos-io/thanos/issues/3014

**Comment by hhsnow** [comment]
removing stale

**Comment by hhsnow** [comment]
badbot :) Def still needed.
