### ISSUE TITLE
Research groupcache as alternative cache client to memcached

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2962]
I think something which would easy up Thanos deployment with cache is https://github.com/golang/groupcache This is project done my Memcached author and it's replicated in mem cache. The only tradeoff is gossip between replicas which is not that basd to setup.

To research and benchmark (:

**Comment by kakkoyun** [comment]
I have started experimenting with groupcache.

**Comment by bwplotka** [comment]
Needed!

**Comment by GiedriusS** [comment]
I'm working on this.

**Comment by GiedriusS** [comment]
My semi-working branch: https://github.com/GiedriusS/thanos/tree/experiment/groupcache_caching_bucket.

Some thoughts after working on this:

There is no way to remove a group after it has been registered with groupcache without changing groupcache's code itself. This means that if we were to use it at the Thanos Query level where we'd have to dynamically register/unregister groups (lists of StoreAPI nodes that they can see), groupcache's would need to be improved.

Another huge limitation is that groupcache doesn't serialize multiple requests into one HTTP/2 request. When opening a bigger dashboard, lots of requests are made and it can easily lead to:

```
2021/06/23 07:15:12 http: Accept error: accept tcp [::]:9091: accept4: too many open files; retrying in 10ms
2021/06/23 07:15:12 http: Accept error: accept tcp [::]:9091: accept4: too many open files; retrying in 20ms
```

This is also quite ineffective. Again, groupcache's code would need to be improved to be able to ask for multiple keys at once.

What's more, Thanos code assumes that all caches follow the same load/store model whereas groupcache loads everything during the load() phase. This is a bit awkward for us and we can work around this easily in almost all cases without changing our own caching interface besides the `iter:...` keys where the value is encoded before being stored in the cache. This means that our groupcache layer would need to know about the codec as well and in this way adding a dependency on the upper layer, making things a bit less clear. Hence, some smarter abstractions need to be made.

**Comment by iamrajiv** [comment]
@GiedriusS @onprem I want to work on this. I guess this work has to be completed in two parts. The first is to implement the [groupcache](https://github.com/golang/groupcache) back-end. The second part is to improve the performance.

**Comment by GiedriusS** [comment]
Yep, and for now, I would only focus on the caching bucket. Then we could move on to the other types of cache that we have in Thanos. This is because the latter is more involved since you'll have to inevitably change the internal cache interface a bit.

**Comment by iamrajiv** [comment]
@GiedriusS Got it. Also, changing the internal cache interface you mean changing `groupcache` code itself so that we can get away from `groupcache` drawbacks you mention [here](https://github.com/thanos-io/thanos/issues/2962#issuecomment-866603779).

**Comment by kernelpanic77** [comment]
Hello @GiedriusS ! I am relatively new to the Thanos project, but would love to get involved and potentially contribute. Any pointers or resources for me to get started and understand this issue better ?

Thanks, 
Ishan

**Comment by akshatdalton** [comment]
Hola! Thanos team. I am a newbie here, but I have other Open Source experience. I would love to contribute here along with learning about new technologies. It feels great that my contribution will be useful to many. I love to take on challenges. If this is an active issue I can work on, please do let me know. Or, if there is any other challenge that I need to complete first, I am ready for that. Looking forward to contributing here actively.

Thank You
Akshat
Open Source Enthusiast

**Comment by yeya24** [comment]
Still valid

**Comment by GiedriusS** [comment]
Already in Thanos. Follow up: https://github.com/thanos-io/thanos/issues/5037.
