### ISSUE TITLE
All result timestamps off by 1ms for certain floating-point input timestamps

### ISSUE THREAD

**Issue by juliusv** [thanos-io/thanos#2971]
This Cortex issue is relevant for Thanos as well: https://github.com/cortexproject/cortex/issues/2932

I'm getting the same timestamp behavior for the latest Thanos release v0.14.0, when passing in range query timestamps (`start` / `stop` of e.g. `1595846748.806` being parsed as `1595846748.805`).

**Comment by bwplotka** [comment]
Thanks!

We just need this: https://github.com/prometheus/prometheus/pull/4941

**Comment by bwplotka** [comment]
Quick fix is easy, help wanted
