### ISSUE TITLE
make go-lint failed

### ISSUE THREAD

**Issue by johncming** [thanos-io/thanos#2977]
**Thanos, Prometheus and Golang version used**:

only thanos, the version is a pr below.

**What happened**:

make go-lint failed in #2976 in local develop environment and failed occasionally in ci checks in github.

```
cannot detected files without copyright: you have unstaged changes.
M	pkg/rules/rulespb/rpc.pb.go
M	pkg/store/hintspb/hints.pb.go
M	pkg/store/storepb/prompb/remote.pb.go
M	pkg/store/storepb/prompb/types.pb.go
M	pkg/store/storepb/rpc.pb.go
M	pkg/store/storepb/types.pb.go
Please commit or stash them.
make: *** [go-lint] Error 1
```

local env:
```
➜  ~ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/john/Library/Caches/go-build"
GOENV="/Users/john/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/john/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bl/j9gvhbpj3p1c95wh767kj0qc0000gn/T/go-build001516030=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

diff detail: 
[pr_2976.txt](https://github.com/thanos-io/thanos/files/5022004/pr_2976.txt)

Can anyone see this. I checked this files that it's same as origin master.

**How to reproduce it (as minimally and precisely as possible)**:

In pr #2976 , run `make go-lint`

@bwplotka

**Comment by GiedriusS** [comment]
Could it be a line-ending problem? Are you running on Windows?

**Comment by johncming** [comment]
> [edit]
> 
> Actually, it seems like you are using an old version of a package:
> 
> ```
> 
> -const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package
> +const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package
> ```

Ye, this diff was created after running `make go-lint`. It's weird because I have an updated master branch from origin/master.

**Comment by yeya24** [comment]
I saw the CI passed. Is this still a problem? @johncming

**Comment by johncming** [comment]
> I saw the CI passed. Is this still a problem? @johncming

Yes, the ci passed. But the error msg I don't know why.  In local env, the error still here.
