### ISSUE TITLE
devtools: Changelog tooling. 

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#2999]
It would be awesome to automate changelog creation. This is to:

* Avoid issues like https://github.com/thanos-io/thanos/pull/2998
* Avoid changelog merge conflicts all the time
* Automate manual process during each release

I would propose some tooling that can work on PR / commit messages - to parse those. We can ensure via CI if commit has this or something. Would be awesome (: Maybe there is such tool already we could use? :thinking:

**Comment by paulfantom** [comment]
There is a project for that: https://github.com/github-changelog-generator/github-changelog-generator :)
