### ISSUE TITLE
Same url (with max time in future) got diffenent data from Prometheus  and  thanos query 

### ISSUE THREAD

**Issue by husoule** [thanos-io/thanos#3001]
**What happened**:
I want a query which endtime is a future time. If I play with Prometheus directly, I see the latest result being less then now + lookback-delta. This is as expected。 But via thanos query, it got the latest result data of future 5m.

via thanos query: 
![image](https://user-images.githubusercontent.com/5336915/89661464-4ee64880-d905-11ea-9605-78ab06332eb7.png)

Prometheus directly:
![image](https://user-images.githubusercontent.com/5336915/89661963-f5cae480-d905-11ea-9dc9-8e2b9f3b8fab.png)

**What you expected to happen**:
get the same data

**Anything else we need to know**:

**Environment**:
- OS (e.g. from /etc/os-release): centos7
- Kernel (e.g. `uname -a`): Linux VM_120_12_centos 3.10.107-1 
- Others: 
prometheus version: v2.18.1
thanos query version:  thanos:v0.12.0
thanos query args:

        - query
        - --log.level=debug
        - --query.auto-downsampling
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:9090
        - --query.partial-response
        - --query.replica-label=prometheus_replica
        - --query.replica-label=rule_replica

**Comment by bwplotka** [comment]
Ack, might be the deduplication (: But kind of when you ask for future - this is what deduplication interpolates ;p

**Comment by bwplotka** [comment]
How critical this is? Why it would cause issues?

**Comment by husoule** [comment]
> How critical this is? Why it would cause issues?

I have a stress test service platform for many users . Use prometheus+thanos+grafana to collect and display graphs of stress test data. The stress test data is more accurate in terms of time, but the user actually saw the data in the chart that has not yet occurred, which is unacceptable. So I adjusted prometheus' --query.lookback-delta=5s to reduce future data. And prometheus is as expected, but there will still be data for the next 5m after thanos. So in fact, in my scenario, future data is not needed. I don't know how to not get the data of future time via thaos query.
