### ISSUE TITLE
query: Can u make the response warnings optional?

### ISSUE THREAD

**Issue by litengfei-zz** [thanos-io/thanos#3004]
query API response warnings， but only query web knows this content. And rule does not this.
Can u make the response warnings optional?

**Thanos, Prometheus and Golang version used**:

**Object Storage Provider**:

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by GiedriusS** [comment]
I'm not sure if I understood the question but there is "partial_response_strategy" that controls what happens when Thanos Rule encounters an error/warning while querying.

**Comment by bwplotka** [comment]
Yes, just set this strategy to WARN (:

Kind Regards,
Bartek Płotka (@bwplotka)

**Comment by litengfei-zz** [comment]
> I'm not sure if I understood the question but there is "partial_response_strategy" that controls what happens when Thanos Rule encounters an error/warning while querying.

The problem is not partial response.
The case is that a prometheus goes down and the sidecar is running. 
the rule will logs:
level=error ts=2020-08-10T05:51:50.554377118Z caller=rule.go:729 component=rules err="read query instant response: expected 2xx response, got 422. Body: {\"status\":\"error\",\"errorType\":\"execution\",\"error\":\"expanding series: proxy Series(): Addr: 10.99.207.232:10901 LabelSets: [name:\\\"cluster\\\" value:\\\"10.99.207.232\\\" ,name:\\\"cluster_name\\\" value:\\\"hu0730\\\" ] Mint: -62167219200000 Maxt: 9223372036854775807: receive series from Addr: 10.99.207.232:10901 LabelSets: [name:\\\"cluster\\\" value:\\\"10.99.207.232\\\" ,name:\\\"cluster_name\\\" value:\\\"hu0730\\\" ] Mint: -62167219200000 Maxt: 9223372036854775807: rpc error: code = Unknown desc = query Prometheus: send request: Post http://localhost:9090/api/v1/read: dial tcp [::1]:9090: connect: connection refused\"}\n" query="(dataengine_alert_collect_lists{summary=\"datanode_MemHeapUsedM_max\"}) > 0"

sidecar logs:

level=warn ts=2020-08-10T05:53:32.452667671Z caller=sidecar.go:244 msg="heartbeat failed" err="request flags against http://localhost:9090/api/v1/status/config: Get http://localhost:9090/api/v1/status/config: dial tcp [::1]:9090: connect: connection refused"

**Comment by ikonyeama** [comment]
This is still ongoing, seeing this behaviour with rpc error: code = Unavailable desc = connection closed\"}\n" and caller=rule.go:738 component=rules err="read query instant response: expected 2xx response, got 422. This should be a warning imo.

**Comment by GiedriusS** [comment]
Sidecars now report "not ready" when they lose connection with Prometheus or when it is booting up (your case) so I think this is solved when you use service discovery.
