### ISSUE TITLE
Alert missing for bucket operation failures on the sidecar

### ISSUE THREAD

**Issue by SerialVelocity** [thanos-io/thanos#3005]
**Thanos, Prometheus and Golang version used**:
quay.io/prometheus/prometheus:v2.20.0
quay.io/thanos/thanos:v0.14.0

**Object Storage Provider**:
Scaleway S3 compatible object store

**What happened**:
The sidecar was failing to upload to the S3 (my fault) but no alerts were triggered.

**What you expected to happen**:
An alert to be triggered.

**How to reproduce it (as minimally and precisely as possible)**:
Set up a network policy that blocks uploading

**Full logs to relevant components**:
```
level=warn ts=2020-08-08T11:50:28.85471248Z caller=sidecar.go:285 err="check exists: stat s3 object: Get \"https://s3.nl-ams.scw.cloud/<bucket-name>/?location=<location>": dial tcp 163.172.208.8:443: connect: connection refused" uploaded=0
```

**Anything else we need to know**:
It looks like this used to work by having an alert on `thanos_objstore_bucket_operation_failures_total`. I actually found the issue when I looked at the thanos sidecar dashboard.

It looks like #2002 removed the alert. I think only ones with `_s3_`/`_gcs_` in the name were meant to be removed?

**Comment by SerialVelocity** [comment]
I haven't tried 0.15.0 but I don't see anything in the changelog

**Comment by brokencode64** [comment]
Seeing this issue too,  is it intentional?

**Comment by kakkoyun** [comment]
@brokencode64 I don't think it is intentional. We can always ask @daixiang0, if the removal was intentional. @daixiang0 WDYT?

@SerialVelocity In any case, if you think it is an alert that's needed or we are missing any other alerts, please feel free to contribute. I'd be happy to review and include it in the next release.

**Comment by daixiang0** [comment]
It is not intentional but a mistake, @SerialVelocity thanks for catching it!

**Comment by kakkoyun** [comment]
Still valid.
