### ISSUE TITLE
Openshift Container Storage as Thanos Store

### ISSUE THREAD

**Issue by clyang82** [thanos-io/thanos#3008]
I did not find OCS can be able to support in the this list - https://thanos.io/storage.md/
Do we have plan to support OCS as a thanos store? https://www.openshift.com/products/container-storage/
or do we have example to play with OCS? Thanks.

/cc @bwplotka  @brancz

**Comment by squat** [comment]
Hi @clyang82 do you know what OCS is built on top of? I seem to recall this was built on Ceph, which exposes an object-storage API that is S3-compatible. If this is the case, then we can use the S3 configuration settings for Thanos.

**Comment by clyang82** [comment]
Thanks @squat it is build on top of Ceph - https://www.openshift.com/blog/openshift-container-storage-4-introduction-to-ceph
That's great if we can use s3 configuration settings for Thanos. I may give it a try and provide update here then.

**Comment by bwplotka** [comment]
Cool, let us know!
