### ISSUE TITLE
bucket web: Expose information about blocks as metrics

### ISSUE THREAD

**Issue by 2nick** [thanos-io/thanos#3009]
Greetings, Thanos team! :)

We want to see information about stored blocks such as number of series/chunks/sample and used space in Grafana dashboards.
So the first proposal is to expose currently available data which is used in bucket web ui as metrics.
And the second is to add information about space used by blocks as in web ui as in metrics endpoint.

What do you think?

**Comment by bwplotka** [comment]
Hey, as per blocks numbers - it's already exposed by powerful metric `thanos_blocks_meta_synced`

**Comment by bwplotka** [comment]
As per space used, this is tricky, but if we can find a way to have aggregated metric for space used sure!

Ideally this metric is exposed by your cloud providers ;p

**Comment by 2nick** [comment]
> Hey, as per blocks numbers - it's already exposed by powerful metric `thanos_blocks_meta_synced`

I found only one place in the current master branch with this metric - it's in store and value is just a number of blocks.

We need full information about each block from its meta - resolution + number of its series, chunks, and samples.

If there is a place where a store or other component exposes such metrics could you please refer to a particular line. :)

> As per space used, this is tricky, but if we can find a way to have aggregated metric for space used sure!
> 
> Ideally this metric is exposed by your cloud providers ;p

We have in-house ceph cluster and can get aggregated stats from an exporter.

But we want more accurate info - for example, how much space is used by which resolution and by which Prometheus (as we have sharding by roles).

So it's much more interesting to get whole this information from one of Thanos's components. :)

As I can see it's could be possible to get this information during sync process using `BucketReader.Iter + BucketReader.Attributes` to do it driver-independently [here](https://github.com/thanos-io/thanos/blob/master/cmd/thanos/tools_bucket.go#L393).

So if you consider bucket web as an appropriate place for adding these metrics I'll try to implement it. :)
