### ISSUE TITLE
Replace leaktest with goleak

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3023]
As Prometheus did we probably want to replace leaktest with https://github.com/uber-go/goleak with per package pattern:

```
func TestMain(m *testing.M) {
	goleak.VerifyTestMain(m)
}
```

This way we don't need to put defer on every unit test which we often forget. It will harder to detect WHERE the leak happens but for CI we care more if it happens.

**Comment by bwplotka** [comment]
Help wanted!

**Comment by mneverov** [comment]
hi, i'd like to work on this

**Comment by bwplotka** [comment]
Please help! :heart:
