### ISSUE TITLE
receive: Use PathOrContent file for the hashring

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3026]
This: https://github.com/thanos-io/thanos/blob/a64884b19dbe7a6c2613078a07409c89ce4e2508/cmd/thanos/receive.go#L67

**Comment by squat** [comment]
Specifically, we should allow the Thanos receive component to _also_ take the hashrings configuration as content passed directly to the flag rather than _only_ as file

**Comment by Sylfrena** [comment]
so you mean that this flag should either take a file path or the file contents directly as string?

**Comment by squat** [comment]
yes, that's right :)) it should work just like the objstore flags, which use https://github.com/thanos-io/thanos/blob/master/pkg/extflag/pathorcontent.go#L29:6

**Comment by daksh-sagar** [comment]
@bwplotka Can I work on this, please?

**Comment by kakkoyun** [comment]
@daksh-sagar I have actually a PR to fix this https://github.com/thanos-io/thanos/pull/3121. Sorry I've forgotten to update this issue.

**Comment by daksh-sagar** [comment]
@kakkoyun It's allright 🤓

**Comment by kakkoyun** [comment]
#3121 is still open and waiting for review cc @squat
