### ISSUE TITLE
Thanos query does not gracefully handle a sidecar producer behind a multi-zone load balancer

### ISSUE THREAD

**Issue by mmerrill3** [thanos-io/thanos#3033]
**Thanos, Prometheus and Golang version used**:

thanos 0.14.0
prometheus 2.18.2

**Object Storage Provider**:
s3
**What happened**:
When I define a query component to start that has a --store configuration that points to a DNS name, and that DNS name is a multi-zone nginx ingress controller, we see the following in the logs:

level=info ts=2020-08-14T18:22:19.605653512Z caller=storeset.go:417 component=storeset msg="adding new storeAPI to query storeset" address=10.205.164.191:443 extLset="{cluster=\"qa-oregon\", prometheus=\"qa-monitoring/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\"}"
level=warn ts=2020-08-14T18:22:19.605686336Z caller=storeset.go:405 component=storeset msg="found duplicate storeAPI producer (sidecar or ruler). This is not advices as it will malform data in in the same bucket" address=10.205.163.177:443 extLset="{cluster=\"qa-oregon\", prometheus=\"qa-monitoring/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\"}" duplicates=2
level=info ts=2020-08-14T18:22:19.605796273Z caller=storeset.go:417 component=storeset msg="adding new storeAPI to query storeset" address=10.205.163.177:443 extLset="{cluster=\"qa-oregon\", prometheus=\"qa-monitoring/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\"}"
level=warn ts=2020-08-14T18:22:19.605886222Z caller=storeset.go:405 component=storeset msg="found duplicate storeAPI producer (sidecar or ruler). This is not advices as it will malform data in in the same bucket" address=10.205.165.116:443 extLset="{cluster=\"qa-oregon\", prometheus=\"qa-monitoring/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\"}" duplicates=3
level=info ts=2020-08-14T18:22:19.605976992Z caller=storeset.go:417 component=storeset msg="adding new storeAPI to query storeset" address=10.205.165.116:443 extLset="{cluster=\"qa-oregon\", prometheus=\"qa-monitoring/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\"}"

**What you expected to happen**:

Have the ability to know that the DNS url will resolve to multiple IP addresses, but those IP addresses all forward to the same store.

**How to reproduce it (as minimally and precisely as possible)**:

Setup a multi-zone nginx LoadBalancer type in AWS for nginx ingress controller.  Create an ingress for your prometheus side car that is implemented by this nginx ingress controller.  Now, in your query componet, point to that DNS name of the ingress.

**Full logs to relevant components**:
level=info ts=2020-08-14T18:22:19.605653512Z caller=storeset.go:417 component=storeset msg="adding new storeAPI to query storeset" address=10.205.164.191:443 extLset="{cluster=\"qa-oregon\", prometheus=\"qa-monitoring/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\"}"
level=warn ts=2020-08-14T18:22:19.605686336Z caller=storeset.go:405 component=storeset msg="found duplicate storeAPI producer (sidecar or ruler). This is not advices as it will malform data in in the same bucket" address=10.205.163.177:443 extLset="{cluster=\"qa-oregon\", prometheus=\"qa-monitoring/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\"}" duplicates=2
level=info ts=2020-08-14T18:22:19.605796273Z caller=storeset.go:417 component=storeset msg="adding new storeAPI to query storeset" address=10.205.163.177:443 extLset="{cluster=\"qa-oregon\", prometheus=\"qa-monitoring/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\"}"
level=warn ts=2020-08-14T18:22:19.605886222Z caller=storeset.go:405 component=storeset msg="found duplicate storeAPI producer (sidecar or ruler). This is not advices as it will malform data in in the same bucket" address=10.205.165.116:443 extLset="{cluster=\"qa-oregon\", prometheus=\"qa-monitoring/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\"}" duplicates=3
level=info ts=2020-08-14T18:22:19.605976992Z caller=storeset.go:417 component=storeset msg="adding new storeAPI to query storeset" address=10.205.165.116:443 extLset="{cluster=\"qa-oregon\", prometheus=\"qa-monitoring/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\"}"

**Anything else we need to know**:

Maybe an additional flag to pass to any thanos component to indicate that the DNS entry is a multi-zone entry, and gracefully handle this setup.

**Comment by nightvisi0n** [comment]
I also experienced the same issue in our thanos deployment.

thanos args:
```
      query
      --log.level=info
      --grpc-address=0.0.0.0:10901
      --http-address=0.0.0.0:10902
      --query.replica-label=slug
      --store=dns+[redacted]:32443
      --grpc-client-tls-secure
      --grpc-client-tls-cert=/tls/client/cert
      --grpc-client-tls-key=/tls/client/key
      --grpc-client-tls-ca=/tls/client/ca
      --grpc-client-server-name=thanos-server
```

The single store dns entry is pointing to 5 different IPv4 addresses. All of them serve the same thanos sidecar (k8s NodePort).  
Let me know if you need more information.
