### ISSUE TITLE
docs: internationalization (adding more languages)

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3037]
It would amazing to be more inclusive and translate our docs into multiple languages (: 

There are two items to solve this:
* Extend website as we did with @thisisobate on  version picker as well as use Hugo built-in support: https://gohugo.io/content-management/multilingual/
* Find contributors who would be willing to translate our docs. CNCF might help as well (:

**Comment by soniasingla** [comment]
@bwplotka I would love to help in this 🤗

Can you provide me some starting points? It will be really amazing 🎉

**Comment by soniasingla** [comment]
Valid and help wanted 🤗

**Comment by kakkoyun** [comment]
Still valid  and help wanted 🤗
