### ISSUE TITLE
New Query UI doesn't work with query frontend

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#3043]
**Thanos, Prometheus and Golang version used**:

Thanos master.

**What happened**:

The new query UI doesn't work with query frontend.

Setup:

Prometheus + Sidecar + Query + Query frontend

```bash

## Querier
thanos query --http-address="localhost:9091" --store="localhost:10903"

## Query frontend
thanos query-frontend --query-frontend.downstream-url="http://localhost:9091" --query-range.response-cache-config-file=test-conf --query-range.max-retries-per-request=0
```

When clicking `New UI` in the Query frontend address `http://localhost:10902`, I got `ERR_TOO_MANY_REDIRECTS`.
![Screenshot from 2020-08-17 16-03-30](https://user-images.githubusercontent.com/25150124/90439232-37e0ec80-e0a3-11ea-8784-d2c9d3097070.png)

**What you expected to happen**:

New UI should work in the above setup. 

Btw I also tested Prometheus + Query frontend, and set downstreamURL to prometheus addr. The Prometheus new UI works well. So I am wondering that is this problem coming from the new UI itself, not query frontend?

![Screenshot from 2020-08-17 16-06-07](https://user-images.githubusercontent.com/25150124/90439456-973efc80-e0a3-11ea-80b8-f425d29c786b.png)

**Anything else we need to know**:

**Comment by prmsrswt** [comment]
I investigated a bit into this and found some weird behavior around the redirects. One thing to note here is that the new UI works if you go directly to `localhost:10902/new/graph`.

In `pkg/ui/query.go` You can see that we redirect from `/new` to `/new/` (with a trailing slash) and the route `/new/*` gets handled by the `serveReactUI` handler.

If I directly perform an HTTP request with path `/new/` on Querier, I get

```
$ http --follow --all --max-redirects 4 :9091/new/


HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Date: Tue, 18 Aug 2020 07:35:25 GMT
Transfer-Encoding: chunked

<!doctype html>
<html>
<-- truncated -->
</html>
```

It works. The path `/new/` returns the React index page.

But if I do the same request on Query Frontend, I get

```
$ http --follow --all --max-redirects 4 :10902/new/


HTTP/1.1 302 Found
Content-Length: 28
Content-Type: text/html; charset=utf-8
Date: Tue, 18 Aug 2020 07:46:33 GMT
Location: /new/
Vary: Accept-Encoding

<a href="/new/">Found</a>.

HTTP/1.1 302 Found
Content-Length: 28
Content-Type: text/html; charset=utf-8
Date: Tue, 18 Aug 2020 07:46:33 GMT
Location: /new/
Vary: Accept-Encoding

<a href="/new/">Found</a>.

HTTP/1.1 302 Found
Content-Length: 28
Content-Type: text/html; charset=utf-8
Date: Tue, 18 Aug 2020 07:46:33 GMT
Location: /new/
Vary: Accept-Encoding

<a href="/new/">Found</a>.

http: error: Too many redirects (--max-redirects=4).
```

`/new/` is redirecting to `/new/` itself which results in an infinite loop of redirects.

One thing that came to my mind was that maybe the query frontend is removing the trailing slash request. If it's the case then the redirect from `/new` to `/new/` would result in an endless loop.

**Comment by prmsrswt** [comment]
> One thing that came to my mind was that maybe the query frontend is removing the trailing slash from the request, so /new/ becomes /new. If it's the case then the redirect from /new to /new/ would result in an endless loop.

I guess this is what's happening. I changed the default redirect from `/new` -> `/new/` to `/new` to `/new/graph` and it worked.
