### ISSUE TITLE
Feature request: client side encryption with minio/sio

### ISSUE THREAD

**Issue by appleciderjack** [thanos-io/thanos#3056]
Hi Thanos team:

In most enterprise settings, client encryption is a required feature. It looks like Minio go client does have some form of client side encryption listed here: 
https://github.com/minio/minio-go/pull/948/files
https://github.com/minio/sio

It would be fantastic and increase Thanos's enterprise footprints if this is supported! (Instead of team forking and maintaining their own branch)

**Thanos, Prometheus and Golang version used**:
Thanos 0.12.2
Golang 1.13

**Object Storage Provider**: S3

**Comment by appleciderjack** [comment]
Perhaps sse_c_key can be used? I will read up on it

**Comment by appleciderjack** [comment]
After some soul searching, I realize that Thanos and Prometheus are both full of partial reads on TSDB related files and thus would be impractical to apply client side decryption with.

**Comment by bwplotka** [comment]
Yes, definitely we use Range API a lot. But wonder if there is a way to encrypt in chunk to allow this? :thinking: 

BTW:
> (Instead of team forking and maintaining their own branch)

Is there any code you would like to contribute then? (: If it's useful for you might be useful for other.s

**Comment by appleciderjack** [comment]
Hello, there is a way to do this. Minio gives some hints on the use of a secure channel, described here: 

It would cut giant files into chunks, and encrypt/decrypt each one of them separately

https://docs.min.io/docs/minio-security-overview.html
```
plaintext   := chunk_0          ||       chunk_1          ||       chunk_2          ||       ...
                 |                         |                         |
                 |                         |                         |
               AEAD <- key, nonce + 0    AEAD <- key, nonce + 1    AEAD <- key, nonce + 2    ...
                 |                         |                         |
                 |                         |                         |
ciphertext  := sealed_chunk_0   ||       sealed_chunk_1   ||       sealed_chunk_2   ||       ...
```

It does depend on a key server (such as vault/kms) though.

**Comment by bwplotka** [comment]
Nice. Is there a valid use case for this? Why TLS and Server Side Encryption is not enough?

**Comment by appleciderjack** [comment]
Sure, this is a use case for enterprise that have their own s3 compatible endpoint, but does not support encryption inside said s3 endpoint.

The requirements for internal Prometheus/thanos team would be:
1. use internal s3 endpoint
2. encrypt data before storing in it via Thanos Sidecar (because the internal s3 is not supposed to be able to read our metrics)
3. decrypt data before reading it from Thanos Store. 

I agree this is fairly niche even among enterprise though!
