### ISSUE TITLE
lint: Add lint for commented code (: 

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3065]
It's so easy to commit commented code accidentally, wonder if we can have linter for this (:

**Comment by mneverov** [comment]
hi, i'd like to work on this

**Comment by mneverov** [comment]
@bwplotka 
I couldn't find any linters that do such checks so I [implemented one](https://github.com/mneverov/comment).
While doing so I understood why there is no linters exist: it is impossible to distinguish between a commented code and a valid comment.
The linter makes best attempt to do so and thanos passes the check. This is the result of running the linter on prometheus repo:

```
~/go/src/github.com/prometheus/prometheus/tsdb/chunkenc/xor.go:399:3: commented code
~/go/src/github.com/prometheus/prometheus/tsdb/querier.go:255:13: commented code
~/go/src/github.com/prometheus/prometheus/tsdb/querier.go:263:12: commented code
~/go/src/github.com/prometheus/prometheus/tsdb/db_test.go:1835:29: empty double comment
~/go/src/github.com/prometheus/prometheus/tsdb/chunkenc/chunk_test.go:119:3: commented code
~/go/src/github.com/prometheus/prometheus/tsdb/chunkenc/chunk_test.go:121:3: commented code
~/go/src/github.com/prometheus/prometheus/tsdb/chunkenc/chunk_test.go:188:3: commented code
~/go/src/github.com/prometheus/prometheus/tsdb/chunkenc/chunk_test.go:190:3: commented code
```

All labels in these findings actually give some context and seem to be legit except [1](https://github.com/prometheus/prometheus/blob/master/tsdb/chunkenc/chunk_test.go#L119), [2](https://github.com/prometheus/prometheus/blob/master/tsdb/chunkenc/chunk_test.go#L121), and [3](https://github.com/prometheus/prometheus/blob/master/tsdb/db_test.go#L1835) - double comment here.

**Comment by bwplotka** [comment]
@mneverov This is good! Sorry for the no response for so long time. Any chances to make a PR to add this to Thano? 🤗 Thanks!

**Comment by mneverov** [comment]
@bwplotka no worries.
sorry for not being clear, but I think it's not worth it. The linter gives you many false positives (although not at the moment). 
If you still think it might be valuable, the linter should be added in the list of all linters in golang-ci. I can create a PR for that.
