### ISSUE TITLE
store: Object Storage cache should be best effort

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3066]
Memcached failures took down some requests causing "bucket errors". We should make sure caching is best-effort only (: 

cc @squat @pracucci @pstibrany

**Comment by pracucci** [comment]
Do you have more details to share about the experienced issue? The object storage cache was built as best effort, so looks like you hit a side effect or bug.

**Comment by bwplotka** [comment]
@squat Might have more info. We have Memcached failures at the same time as bucket failures on read path, and we seen no S3 real problems. But I might be wrong (:

**Comment by squat** [comment]
We were investigating and incident where our thanos ruler was failing to evaluate rules and tracked the error down to the thanos store gateway failing API calls. We found that exactly coinciding with the rule evaluations, we had elevated errors in bucket operations in the thanos store:

query: `sum(rate(thanos_objstore_bucket_operation_failures_total{job=~"observatorium-thanos-store-shard.*"}[5m]))`
![image](https://user-images.githubusercontent.com/20484159/91051474-77b64f80-e620-11ea-8210-8563060061b1.png)

Investigating why the store was failing, we saw that we also had elevated memcached issues exactly during this time:

query: `sum by (operation, reason) (rate(thanos_memcached_operation_failures_total{job=~"observatorium-thanos-store-shard.*"}[5m]))`
![image](https://user-images.githubusercontent.com/20484159/91052098-47bb7c00-e621-11ea-935d-4329ba798c42.png)

We noticed no other errors in the cluster that would have indicated a general network issue during this time. I haven't had a second to dig into the store's cache->fallback->bucket code, but this could suggest that a cache timeout (treated differently than a cache miss) causes the entire bucket operation to fail. It is posible that networking for the Pod or the Node hosting the Pod was broken during exactly that time, causing both the best-effort requests to the cache AND the subsequent request to S3 to fail.

**Comment by pstibrany** [comment]
Caching does introduce a delay into bucket request processing, and if memcache server has troubles, this delay can increase. But single bucket request should only calls memcache once. Unfortunately we don't have any circuit-breaker around access to the memcache at the moment.

What timeout do you use for memcache server? In general, it should be very small, to avoid blocking (and possibly timing out entire bucket request) due to slow memcache access.

**Comment by kakkoyun** [comment]
Still valid and help wanted 🤗

**Comment by kakkoyun** [comment]
Still valid.
