### ISSUE TITLE
Limit size of blocks to X bytes on compaction.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3068]
This is to ensure the scalability of the compactor.

Tricky part: How to shard block, what label to put, or maybe vertical compaction?

**Comment by bwplotka** [comment]
On it now, proposal to moce.

**Comment by bwplotka** [comment]
Still in progres. Vertical block sharding has to be designed and implemented.

**Comment by bwplotka** [comment]
Proposal is half done: https://github.com/thanos-io/thanos/pull/3390 

The plan is to team up with LFX mentee for knowledge sharing 🤗

**Comment by someshkoli** [comment]
Hey @bwplotka, I'd like to pick this up again and work on it.

**Comment by bwplotka** [comment]
cc @idoqo 🤗

**Comment by oronsh** [comment]
How about a new flag to set max time range to apply compaction on? So if for example the compactor detects metadata with `now - min_time > max_compaction_timerange`  exclude the block

**Comment by alvinlin123** [comment]
Where is the proposal for this feature?

**Comment by bwplotka** [comment]
Here: https://github.com/thanos-io/thanos/pull/3390

**Comment by bwplotka** [comment]
Update: Currently compactor will not create bigger blocks than with the index configured with [`compact.block-max-index-size` (hidden flag)](https://github.com/thanos-io/thanos/blob/ce84ec521c99493e98fb17ec4bb1358b56a68ebb/cmd/thanos/compact.go#L731). Thus this issue can be closed.

I will add another one with more dynamic solution that actually can split blocks vertically.

**Comment by bwplotka** [comment]
Created for tracking https://github.com/thanos-io/thanos/issues/5437

**Comment by yeya24** [comment]
This feature is mainly about limiting block index size? Chunk sizes are not included

**Comment by BouchaaraAdil** [comment]
@bwplotka how can we control Block sizes?
weh have blocks that are over 100GB

```
Start Time: June 12, 2024 1:00 AM
End Time: June 18, 2024 1:00 AM
Duration: 6 days
Series: 56716960
Samples: 52166082084
Chunks: 462569560
----------------
Total size: 109.90 GiB
Chunks: 98.72 GiB (89.82%)
Index: 11.18 GiB (10.18%)
Daily: 18.32 GiB / day
----------------
Resolution: 0
Level: 4
Source: compactor
```

**Comment by julienlau** [comment]
I also experienced blocks with Total Size=180GiB and index size~7%.
Since then, I use the hidden compactor flag `--compact.block-max-index-size=1GB` but I don't know what are the side effects.
Could someone help me understand what it does ?
https://github.com/thanos-io/thanos/issues/5137

What would happend, if let's say I put 1MB ?
Will it just disable compaction, or will it also disable downsampling and delete cleanup ?

Is it possible to reopen this ?
/reopen

**Comment by julienlau** [comment]
```
	// TODO(bwplotka): This is short term fix for https://github.com/thanos-io/thanos/issues/1424, replace with vertical block sharding https://github.com/thanos-io/thanos/pull/3390.
	cmd.Flag("compact.block-max-index-size", "Maximum index size for the resulted block during any compaction. Note that"+
		"total size is approximated in worst case. If the block that would be resulted from compaction is estimated to exceed this number, biggest source"+
		"block is marked for no compaction (no-compact-mark.json is uploaded) which causes this block to be excluded from any compaction. "+
		"Default is due to https://github.com/thanos-io/thanos/issues/1424, but it's overall recommended to keeps block size to some reasonable size.").
		Hidden().Default("64GB").BytesVar(&cc.maxBlockIndexSize)
```
