### ISSUE TITLE
Tool: In-Place Relabelling for older data.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3069]
Totally doable request from @SuperQ:

> How possible would it be to write a tool that can basically run a series of metric_relabel_configs against a set of buckets? Basically, stop compaction, run relabel tool, start compaction again?
We're thinking about trying to cleanup some poor labeling choices on historical data. 

I would see this as `thanos tool <cmd>` that takes block ID (?) to recompact.

**Comment by SuperQ** [comment]
Not stale.

**Comment by yeya24** [comment]
https://github.com/thanos-io/thanos/pull/3707 This pr is WIP.

**Comment by SuperQ** [comment]
Not stale
