### ISSUE TITLE
Case studies and/or list of organisations using Thanos in Production

### ISSUE THREAD

**Issue by mattbostock** [thanos-io/thanos#307]
To help promote Thanos and help potential adopters to understand what its capabilities are, I think it would be good if we add some case studies.

To start with, this could be very basic. I'm thinking maybe a single line with:
- the organisation name
- the month and year
- the number of unique time-series ingested
- the rate of samples per second

We could add it to the README. With more detailed case studies, we could go into detail such as retention policies, number of buckets, and raw disk usage.

Example:

> Acme Inc - April 2018: 24k time-series, 20k samples/sec
> Foo Ltd - April 2018: 2M times-series, 200M samples/sec

@Bplotka: Since Improbable are already using Thanos, maybe you could be the first? I should be able to add our data soon.

**Comment by Bplotka** [comment]
Awesome idea! 

I assume you mean the state before Thanos? Also, I would add it to some separate page than README.md

Also maybe worth to extend this list with optional info about:
- number of Prometheus servers.
- current Prom configuration (retention, block size, etc)
- how meta monitoring is solved currently if any
- how global view is solved currently if any
- is there any HA currently in place

I would also like to specify some SLOs potential adopters aims for, for example:
- Is global view desired?
- How long you want to keep metrics for? 
- How many samples can you afford to drop in case of failures?
...but maybe that's a little bit too much (:

**Comment by mattbostock** [comment]
> I assume you mean the state before Thanos?

I'm not sure what you mean.

> Also, I would add it to some separate page than README.md

I was thinking we could include the brief summary in the README to start with while the number of users is small and the project is not yet in wide use. Once we have a lot of organisations, we could move it elsewhere?

> Also maybe worth to extend this list with optional info about:

That'd be great. I'm thinking that kind of information would be in the longer-form case study or in a separate page that we would link to from the README (or wherever the list of companies is).

> I would also like to specify some SLOs potential adopters aims for

I can maybe help with that in the near future.

**Comment by mattbostock** [comment]
Thanks @Bplotka - I meant that numbers used in Thanos.

This brings up an important point though - I think the numbers should represent the largest single Thanos cluster than can be queried as one datasource (rather than the sum of multiple clusters). If you're reliably federating across multiple clusters as one datasource, that should be fine to quote as one cluster.

**Comment by daixiang0** [comment]
@bwplotka where is the template? I do not find related case studies links. Do i miss something?

**Comment by bwplotka** [comment]
Yes, This idea kind of died (: 

However, I am excited as we have already some places like this: https://thanos.io/getting-started.md/#talks which I believe fulfills this issue in some way (:
