### ISSUE TITLE
Fix links; Move preprocess automation for Thanos website to Go

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3081]
Also improve link formating/lniting

AC:
* Version picker stuff (websitepreprocess script) should be moved to Golang so we can test and automate more)
* Should convert all Thanos related links to be local links
* Liche should tests future links not current one - the ones that will be produced, so we need to check against deploy when ready (some race condition is to solve between netlify is up and CI)
* Processing for website has to rearannge links a bit (different dir structure, tip etc)
* Pages from old version should point to the same version pages (so need to be moved to local refs)

Potentially me & @thisisobate will focus on this soon

**Comment by thisisobate** [comment]
Happy to focus on this alongside @bwplotka

**Comment by daixiang0** [comment]
Some fixed by #3106

**Comment by bwplotka** [comment]
We are on it with @thisisobate

**Comment by bwplotka** [comment]
TODO
Kind Regards,
Bartek Płotka (@bwplotka)

**Comment by kakkoyun** [comment]
Still valid and help wanted 🤗

**Comment by bwplotka** [comment]
Status: https://github.com/bwplotka/mdox was created. It's currently blocked on inefficient link checking (rate limiting from GH etc). Proposing this as GSoC project 🤗

**Comment by gdsoumya** [comment]
Hi @bwplotka I would like to work on this during GSoC 2021. I was going through the repo and I found some of the automation scripts here https://github.com/thanos-io/thanos/tree/main/scripts/website, is this all that you want to convert to golang?

**Comment by RavjotSandhu** [comment]
How to start working towards this?

**Comment by RavjotSandhu** [comment]
As far I can understand we need to move current automation scripts one consolidated mdox so that we can use them at other projects. Right @bwplotka ?

**Comment by RavjotSandhu** [comment]
@bwplotka @thisisobate

**Comment by bwplotka** [comment]
There is GSoC project for that already, and we are starting soon!

**Comment by bwplotka** [comment]
Defnitely in progress (: cc @saswatamcode

**Comment by vaibhavdugar** [comment]
Hey! I am a newbie, how can I start contributing to this project? And what are the pre-requisites to begin with this? Can someone help me out please.

**Comment by bwplotka** [comment]
Of course, feel free to help. But this particular issue should be closed (: Thanks for reaching. Feel free to grab any other issue that looks interesting.
