### ISSUE TITLE
Thanos Ruler - SHA in tmp filename generates high cardinality metrics. 

### ISSUE THREAD

**Issue by vanugrah** [thanos-io/thanos#3083]
Hey Thanos team 👋 , 

I'd like to start off by saying that I'm loving this ecosystem. Fabulous work 🎉 . That being said, I noticed something strange while reviewing thanos-ruler metrics: 

```
prometheus_rule_evaluation_failures_total{rule_group="/data/.tmp-rules/eng_ops_demo.alert.yaml.b05953802ce19734934a474645132658d2551b745f65c8e5eaaba4dc24bbefa6.ABORT;poe",strategy="abort"} 1
prometheus_rule_evaluations_total{rule_group="/data/.tmp-rules/eng_ops_demo.alert.yaml.b05953802ce19734934a474645132658d2551b745f65c8e5eaaba4dc24bbefa6.ABORT;poe",strategy="abort"} 11290
prometheus_rule_group_interval_seconds{rule_group="/data/.tmp-rules/eng_ops_demo.alert.yaml.b05953802ce19734934a474645132658d2551b745f65c8e5eaaba4dc24bbefa6.ABORT;poe",strategy="abort"} 30
prometheus_rule_group_last_duration_seconds{rule_group="/data/.tmp-rules/eng_ops_demo.alert.yaml.b05953802ce19734934a474645132658d2551b745f65c8e5eaaba4dc24bbefa6.ABORT;poe",strategy="abort"} 0.009306785
prometheus_rule_group_last_evaluation_timestamp_seconds{rule_group="/data/.tmp-rules/eng_ops_demo.alert.yaml.b05953802ce19734934a474645132658d2551b745f65c8e5eaaba4dc24bbefa6.ABORT;poe",strategy="abort"} 1.598387407251624e+09
prometheus_rule_group_rules{rule_group="/data/.tmp-rules/eng_ops_demo.alert.yaml.b05953802ce19734934a474645132658d2551b745f65c8e5eaaba4dc24bbefa6.ABORT;poe",strategy="abort"} 1
``` 

I noticed that the values of `rule_group` label were a little unexpected. At first I didn't understand why new tmp file were begin generated. After digesting [this section](https://github.com/thanos-io/thanos/blob/master/pkg/rules/manager.go#L310-L360) of the manager.Update method, it's clear that the need to generate tmp files under `/$dataDir/.tmp-rules` is to extract the partial response strategy field to be able to leverage upstream prometheus' rule manager. 

What I'm struggling to justify is the use of SHA256 to create the new filename: 
https://github.com/thanos-io/thanos/blob/master/pkg/rules/manager.go#L351

### Problems
I presume this is a quick way of handling collisions in the base filename across different paths. The downstream impact of this is likely unintended, but unfavourable nonetheless. There are two problems that I've identified with the use of SHA256 to ensure file uniqueness: 

1.) SHA's in label values in metrics generated by the prometheus ruleManager. 
Prometheus' [metric and relabeling best practices](https://prometheus.io/docs/practices/naming/) specifically call out that ID's in labels are not a good idea due to the potential for high cardinality: 
> Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.

Though the argument could be made that the cardinality will scale linearly with number of rule files, which even in large organization would be in the order of thousands/ tens of thousands. 

2.) Difficulty in correlating metrics with rule groups.
There is a high possibility that rule files may share names across directories. Moreover they may also share a group. For example there could be two files `/rules/team1/deadman_rules.yml` and `/rules/team2/deadman_rules.yml`. Both rule files would have metrics associated with them, but since the file names match the only way of identifying which metrics corresponds to which file would be the SHA. Having to calculate the SHA of the file path to correlate metrics to rule files is an unpleasant experience. 

### Potential Solutions
One possible way to address this issue would be to use [os.MkdirAll)](https://golang.org/pkg/os/#MkdirAll) and mirror the directory structure to ensure file uniqeness. Though mirroring changes in the directory structure could get a little complex (cleaning up empty directories for example). 

Another possibile solution could be to have the entire path in the file name. This would be fairly easy to implement and would address both the cardinalirty issue as well as the metrics identification issue. A caveat of this would be potentially long label values in the case of several nested directories of rule files. Though prometheus has decided not to restrict the length of labels as discussed in this issue: 
https://github.com/prometheus/prometheus/issues/1235

Would love to get your thoughts on this and potentially tackle this issue once a solution is agreed upon.

**Comment by bwplotka** [comment]
This is definitely a valid bug, kind of bad those IDs leaked to our metrics ): Thanks for spotting this!

> What I'm struggling to justify is the use of SHA256 to create the new filename:
https://github.com/thanos-io/thanos/blob/master/pkg/rules/manager.go#L351

Looks like the ID is only to have a quick way to know if the rule should be reloaded or not (if it changed). This avoids rereading those file content and calculating hash sum all the time.

 I think instead of this hash we could just store those in memory and I think that would be the fix

**Comment by bwplotka** [comment]
The hash is to differentiate between file dirs, will add comment

**Comment by bwplotka** [comment]
More: Hashes does not introduce any cardinality problem because this is just encoded full path. However it's bug because it's not really verbose

**Comment by bwplotka** [comment]
Fix: https://github.com/thanos-io/thanos/pull/3102 Please PTAL

**Comment by vanugrah** [comment]
@bwplotka  @kakkoyun  Thank you for the quick turn around! Y'all are rockstars!
