### ISSUE TITLE
Documentation 404.

### ISSUE THREAD

**Issue by rickdonato** [thanos-io/thanos#3086]
Links within Google are all returning 404. Most likey to new doc struture.

**Comment by bwplotka** [comment]
Thanks, we are on it: https://github.com/thanos-io/thanos/issues/3081

**Comment by bwplotka** [comment]
Ah, if you mean Google, it has to recrawl, but we might think about some redirect

**Comment by rickdonato** [comment]
You should be able to remove the pages from webmasters

**Comment by bwplotka** [comment]
Good point, TBD.

**Comment by bwplotka** [comment]
Still todo.
Kind Regards,
Bartek Płotka (@bwplotka)
