### ISSUE TITLE
v0.15.0-rc.0 Compactor Block Viewer: Does not work

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3093]
Looks like compactor `global` view does not forward API and css etc calls to correct endpoint: 

![image](https://user-images.githubusercontent.com/6950331/91546051-c95d2380-e919-11ea-9563-6e30a607cde9.png)

![image](https://user-images.githubusercontent.com/6950331/91546186-f6113b00-e919-11ea-960c-3578bc0f7699.png)

Even links point to just path without actual endpoint: 
![image](https://user-images.githubusercontent.com/6950331/91546239-0d502880-e91a-11ea-9b59-9955f83e5066.png)

cc @prmsrswt

**Comment by prmsrswt** [comment]
On It.

**Comment by prmsrswt** [comment]
@bwplotka against which branch I am supposed to create a PR if we want to include it in the next rc? `master` or `release-0.15` ? I have the fix ready, just need to create a PR.

**Comment by bwplotka** [comment]
release (:
Kind Regards,
Bartek Płotka (@bwplotka)

**Comment by bwplotka** [comment]
Fixed!
