### ISSUE TITLE
ui/docs: Create docs/UI features for best UX of using downsampling data

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#310]
Downsampled data have its limits. It increases query responsiveness, but it sometimes requires special usage to not miss spikes or other important behavior if required.

We need both:
- documentation explaining how to use it (e.g use aggregation over time with resolution time for the (most) correct data) and how to control what data is used. (raw vs downsampled)
- Better UI to support several features to help users

This not only tied to downsampling, but overall Prometheus metric usage for longer ranges. Basically every UI is doing "downsampling" on render time, since not all samples can fit into graph.

**Comment by daixiang0** [comment]
@bwplotka should we add a label like plan and make bot skip it?

**Comment by bwplotka** [comment]
No, we should update it monthly with status.

This is really important and as per UI it should be part of bucket UI.

Kind Regards,
Bartek

**Comment by bwplotka** [comment]
Nein, we need this still (:

**Comment by bwplotka** [comment]
still applicable

**Comment by bwplotka** [comment]
Please, don't close (: cc Prem

**Comment by bwplotka** [comment]
still valid

**Comment by bwplotka** [comment]
Still valid.
