### ISSUE TITLE
Add flag for making New UI a default.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3111]
We have an amazing new UI, but only when you click `New UI`. Let's add command flags to all components if user want new one by default or not. (: 

cc @prmsrswt

**Comment by bwplotka** [comment]
Still relevant.

Kind Regards,
Bartek Płotka (@bwplotka)

**Comment by prmsrswt** [comment]
@Oghenebrume50 is working on it. :)

**Comment by Oghenebrume50** [comment]
@prmsrswt just for context to make sure I am doing the right thing, the new UIs, are all preceded with `/new/  ` right?

**Comment by prmsrswt** [comment]
@Oghenebrume50 yes.

**Comment by Namanl2001** [comment]
We could make React UI as default and keep old UI under /classic as done in [prometheus/prometheus#8142](https://github.com/prometheus/prometheus/pull/8142) rather than adding flags to all components.

**Comment by bwplotka** [comment]
As discussed offline: We could add flag, but it takes a lot of effort.

**Comment by bwplotka** [comment]
Looks like new UI is actually fixed. Let's make sure we have upgraded version and then we can switch (:
