### ISSUE TITLE
query-frontend http: invalid Read on closed Body

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3113]
`level=warn ts=2020-09-02T10:32:32.374998059Z caller=frontend.go:198 org_id=fake traceID=1ea32ae91e7a739b msg="unable to parse form for request" err="http: invalid Read on closed Body"`

cc @yeya24

**Comment by yeya24** [comment]
@bwplotka Already opened an issue on the Cortex side. https://github.com/cortexproject/cortex/issues/3111

**Comment by melkorm** [comment]
Fixed in https://github.com/cortexproject/cortex/pull/3276

**Comment by bwplotka** [comment]
Thanks @melkorm !

**Comment by bwplotka** [comment]
Actually let's close once we pull Cortex dep! (:

**Comment by yeya24** [comment]
Thanks a lot for the work @melkorm!
