### ISSUE TITLE
thanos store with aliyun oss,loading block failed parsing time error 

### ISSUE THREAD

**Issue by PGDream** [thanos-io/thanos#3116]
- run args
objstore.config-file: kubernetes configmap volume object
thanos 
        - store
        - --log.level=debug
        - --data-dir=/data/
        - --objstore.config-file=/objstorage/objstorage.yaml
        - --grpc-address=0.0.0.0:19914
        - --index-cache-size=800MB
        - --sync-block-duration=30m
        - --http-address=0.0.0.0:19904
        - --min-time=-2d
        - --max-time=-1h
- objstore with aliyun oss store object
- run error
> level=warn ts=2020-09-03T03:23:07.900958954Z caller=bucket.go:454 msg="loading block failed" elapsed=5.341856ms id=01EH70PS3RZTN1CNNMPE0NFBDD err="create index header reader: write index header: new index reader: get object attributes of 01EH70PS3RZTN1CNNMPE0NFBDD/index: parse Last-Modified: parsing time \"Wed, 02 Sep 2020 09:00:41 GMT\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \"Wed, 02 Sep 2020 09:00:41 GMT\" as \"2006\""

**Comment by hanjm** [comment]
fixed by SabaPing  https://github.com/thanos-io/thanos/pull/2916, you can use version larger than 0.15 :)

**Comment by yeya24** [comment]
Hi @PGDream, as @hanjm mentioned, this has been fixed already. Can you please try the latest release? If this problem is still reproducible, please let us know
