### ISSUE TITLE
Website: Change default url "/tip/" routing to baseurl 

### ISSUE THREAD

**Issue by thisisobate** [thanos-io/thanos#3118]
**What happened**:  latest docs links to "thanos.io/tip" which doesn't look nice and causes linking to break in Google search results.

**What you expected to happen**: instead of default url "thanos.io/tip/components/", we could just route to baseurl "thanos.io/components/"

**Comment by caarlos0** [comment]
also, several links are 404s... e.g. the query frontend on the v0.15.0 release notes

**Comment by thisisobate** [comment]
@caarlos0 You mean the release notes on GitHub?

**Comment by caarlos0** [comment]
<img width="920" alt="image" src="https://user-images.githubusercontent.com/245435/92940186-2b8f4b80-f425-11ea-9231-16fbeb074295.png">

the query frontend link on the release notes on github.

**Comment by bwplotka** [comment]
On GH yup ): cc @kakkoyun

**Comment by kakkoyun** [comment]
@caarlos0 Release notes fixed and for the changelog, https://github.com/thanos-io/thanos/pull/3165 will fix it.

**Comment by caarlos0** [comment]
closing :)

**Comment by kakkoyun** [comment]
👍 Thanks, @caarlos0
