### ISSUE TITLE
grafana: Ensure Dashboard Vars Depending on LabelNames; LabelValues; Series are limited to certain time period / Add ability to set default in querier

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3119]
Currently unlimited time range for Label and LabelValues and Series Thanos APIs return and touch all the data as .. expected. This is great, but it does not make much sense for most of the cases.

We recently added time range parameters to those API endpoints for both Thanos & Prometheus: https://github.com/thanos-io/thanos/issues/1811 However we need to make sure that Grafana utilizes those. Otherwise Grafana always load years worth of series and labels every time params are refreshed.

Let's:
1. Add issue on Grafana side
2. Allow setting a sane default if time params are not specified. This is what Cortex team is doing - they allow fetching last 2h for non specified time ranges.

We also expect those endpoints to be cached in next iterations of Query Frontend (cc @kakkoyun ) but still this issue is valid.

Help wanted (:

**Comment by kakkoyun** [comment]
xref: https://github.com/grafana/grafana/issues/11184

**Comment by kakkoyun** [comment]
> Add issue on Grafana side
https://github.com/grafana/grafana/issues/27537

**Comment by kakkoyun** [comment]
> Allow setting a sane default if time params are not specified. This is what Cortex team is doing - they allow fetching last 2h for non specified time ranges.

https://github.com/thanos-io/thanos/pull/3147

**Comment by kakkoyun** [comment]
I'll handle what's left for this issue soon.

**Comment by kakkoyun** [comment]
/remind me to finish this in a week

**Comment by yeya24** [comment]
@kakkoyun Was this issue solved already by #3147?

**Comment by kakkoyun** [comment]
@yeya24 Only a minor part is left, we need to adjust the default values for the interval. I want to do it for 0.20.

/remind me to finish this next Monday
