### ISSUE TITLE
Can I use k8s ingress for thanos-querier in multi cluster setup?

### ISSUE THREAD

**Issue by PDVJAM** [thanos-io/thanos#3120]
Hi!
We use prometheus with thanos for monitoring of several k8s clusters. Main querier sees two other well if I just expose their 10901 ports outside of cluster. But if I put k8s nginx ingress controller before the queriers - main one can't connect to them.
For nginx ingress I use the following annotations:
```
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
```

thanos-querier has the following configuration:
```
        args:
        - query
        - --log.level=debug
        - --query.replica-label=prometheus_replica
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:9090
        - --store=dnssrv+thanos-store-gateway:10901 (local one)
        - --store=q1.example.com:443
        - --store=q2.example.com:443
```

Logs show:
`level=warn ts=2020-09-03T14:01:58.197402338Z caller=storeset.go:487 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from q1.example.com:443: rpc error: code = DeadlineExceeded desc = latest balancer error: connection closed" address=q1.example.com:443`

If there a way to use k8s nginx ingress with thanos querier? Or what is the best way to secure connection between two clusters?

**Comment by khadka-prakash** [comment]
For you reference, you can check out this link https://itnext.io/monitoring-kubernetes-workloads-with-prometheus-and-thanos-4ddb394b32c . Make sure to implement TLS in your ingress.

**Comment by avenda** [comment]
similar to #2978
