### ISSUE TITLE
404 errors for links in CLI flag text

### ISSUE THREAD

**Issue by spencergilbert** [thanos-io/thanos#3135]
**Thanos, Prometheus and Golang version used**:
Thanos: v0.15.0

**Object Storage Provider**:
N/A

**What happened**:
While working on the thanos helm-charts I noticed the links provided in the flag descriptions were 404ing ex: `https://thanos.io/tip/tracing.md/#configuration` should be `https://thanos.io/v0.15/thanos/tracing.md/#configuration`

**What you expected to happen**:
Proper linking to help onboarding and doc referencing :smile: 

**How to reproduce it (as minimally and precisely as possible)**:
Confirmed with `thanos query --help` will look to verify on the other components today as I work on charts.

**Full logs to relevant components**:
N/A

**Anything else we need to know**:

**Comment by Oghenebrume50** [comment]
I actually think this link (https://thanos.io/tip/thanos/tracing.md/#configuration) works fine, I should open a PR for this :thinking:  there are a bunch of these (https://thanos.io/tip/tracing.md/#configuration) in the docs, which doesn't work anymore
