### ISSUE TITLE
sidecar Azure blob storage: hard link block - operation not supported

### ISSUE THREAD

**Issue by AriannaDel** [thanos-io/thanos#3139]
**Thanos, Prometheus and Golang version used**:
Thanos version 0.14.0
Prometheus version 2.16.0

**Object Storage Provider**:
Azure blob storage 

**What happened**:
thanos-sidecar fails to upload blocks to Azure storage

**What you expected to happen**:
thanos-sidecar successfully uploads blocks to Azure storage

**How to reproduce it (as minimally and precisely as possible)**:
Create prometheus-thanos setup with Azure blob storage

**Full logs to relevant components**:
level=info ts=2020-09-08T12:32:11.980949544Z caller=sidecar.go:327 msg="starting sidecar"
level=info ts=2020-09-08T12:32:11.981332542Z caller=prober.go:127 msg="changing probe status" status=healthy
level=info ts=2020-09-08T12:32:11.981362341Z caller=http.go:53 service=http/server component=sidecar msg="listening for requests and metrics" address=0.0.0.0:10902
level=info ts=2020-09-08T12:32:11.981783039Z caller=prober.go:107 msg="changing probe status" status=ready
level=info ts=2020-09-08T12:32:11.981854039Z caller=grpc.go:98 service=gRPC/server component=sidecar msg="listening for StoreAPI gRPC" address=0.0.0.0:10901
level=info ts=2020-09-08T12:32:11.98751761Z caller=sidecar.go:195 msg="successfully loaded prometheus external labels" external_labels="{prometheus_group=\"dev-cluster\", prometheus_replica=\"$(HOSTNAME)\"}"
level=info ts=2020-09-08T12:32:11.993869177Z caller=reloader.go:286 component=reloader msg="Prometheus reload triggered" cfg_in=/etc/config/prometheus.yml cfg_out=/etc/prometheus-shared/prometheus.yml rule_dirs=
level=info ts=2020-09-08T12:32:11.994016476Z caller=reloader.go:154 component=reloader msg="started watching config file and non-recursively rule dirs for changes" cfg=/etc/config/prometheus.yml out=/etc/prometheus-shared/prometheus.yml dirs=
level=debug ts=2020-09-08T12:32:14.817934855Z caller=azure.go:233 msg="check if blob exists" blob=01EGH4DWYHX3JDV12RPX13F0JS/meta.json
level=debug ts=2020-09-08T12:32:14.823711725Z caller=azure.go:233 msg="check if blob exists" blob=01EGK27AAEMB1X1AXEYM4NPT03/meta.json
level=debug ts=2020-09-08T12:32:14.82647391Z caller=azure.go:233 msg="check if blob exists" blob=01EGN00MWC9PHG9RKY39YQRA9J/meta.json
level=debug ts=2020-09-08T12:32:14.830083692Z caller=azure.go:233 msg="check if blob exists" blob=01EGPXT7F73XZRBSJFDWY6S7PK/meta.json
level=debug ts=2020-09-08T12:32:14.833530074Z caller=azure.go:233 msg="check if blob exists" blob=01EGRVKVTTDQWWQXQBRF16SBAW/meta.json
level=debug ts=2020-09-08T12:32:14.836722557Z caller=azure.go:233 msg="check if blob exists" blob=01EGTSEBTRSZXDQX2888V2NSK4/meta.json
level=debug ts=2020-09-08T12:32:14.839438943Z caller=azure.go:233 msg="check if blob exists" blob=01EGWQ70T6C4P0R377SYDB90P1/meta.json
level=debug ts=2020-09-08T12:32:14.84206993Z caller=azure.go:233 msg="check if blob exists" blob=01EGYN0FBBXJ1TM795GRDHJSWT/meta.json
level=debug ts=2020-09-08T12:32:14.844680216Z caller=azure.go:233 msg="check if blob exists" blob=01EH0JT4CATTFW5ZAWN47V8R1Q/meta.json
level=debug ts=2020-09-08T12:32:14.847436802Z caller=azure.go:233 msg="check if blob exists" blob=01EH2GKEYKVMS3XM1VQAGJFQ06/meta.json
level=debug ts=2020-09-08T12:32:14.850150588Z caller=azure.go:233 msg="check if blob exists" blob=01EH4ED7M4KXC33NQHC86RB80M/meta.json
level=debug ts=2020-09-08T12:32:14.853211972Z caller=azure.go:233 msg="check if blob exists" blob=01EH6C733T4K958VCP2N7FGKYH/meta.json
level=debug ts=2020-09-08T12:32:14.856340256Z caller=azure.go:233 msg="check if blob exists" blob=01EH8A0AZJPSFN0NSJ5VSKXTMB/meta.json
level=debug ts=2020-09-08T12:32:14.859191641Z caller=azure.go:233 msg="check if blob exists" blob=01EHA7T0ETAJ5CA3V276BKX5AX/meta.json
level=debug ts=2020-09-08T12:32:14.862443724Z caller=azure.go:233 msg="check if blob exists" blob=01EHC5K2AXCAQE2XVCXG7FS0EX/meta.json
level=debug ts=2020-09-08T12:32:14.866197305Z caller=azure.go:233 msg="check if blob exists" blob=01EHE3C6VH6HN15F1WG2NVH3MF/meta.json
level=debug ts=2020-09-08T12:32:14.86912749Z caller=azure.go:233 msg="check if blob exists" blob=01EHG15SHW0KNXHBEGC5QA9MZE/meta.json
level=debug ts=2020-09-08T12:32:14.871919075Z caller=azure.go:233 msg="check if blob exists" blob=01EHHYZ5SPD8VB5SB1GFDS0X3Y/meta.json
level=debug ts=2020-09-08T12:32:14.87483086Z caller=azure.go:233 msg="check if blob exists" blob=01EHKWS0QB844J175GES6YJ12V/meta.json
level=debug ts=2020-09-08T12:32:14.878502941Z caller=azure.go:233 msg="check if blob exists" blob=01EHKWP8N921CGZJFRF2NGFFTN/meta.json
level=info ts=2020-09-08T12:32:14.881638625Z caller=shipper.go:349 msg="upload new block" id=01EHKWP8N921CGZJFRF2NGFFTN
level=error ts=2020-09-08T12:32:15.187483742Z caller=shipper.go:316 msg="shipping failed" block=01EHKWP8N921CGZJFRF2NGFFTN err="hard link block: hard link file chunks/000001: link /data/01EHKWP8N921CGZJFRF2NGFFTN/chunks/000001 /data/thanos/upload/01EHKWP8N921CGZJFRF2NGFFTN/chunks/000001: operation not supported"

**Comment by GiedriusS** [comment]
Hi! Don't think it is related to you using Azure at all. Thanos create a hardlink of block's files before trying to upload them so that in case they would get deleted by someone else e.g. Prometheus, we'd still be able to read them because we'd have a reference to the underlying inodes. It sounds like for whatever reason the Thanos Sidecar process cannot create those hardlinks. Could you please elaborate of the permission model you have on your deployment?

**Comment by AriannaDel** [comment]
Hi, I have looked into it and it seems like the problem is due to the fact that I am using Azure files as storage for Prometheus and reading the documentation I found out that Azure File does not support hard links so I think that's what is preventing the sidecar to behave as expected.

**Comment by GiedriusS** [comment]
> Hi, I have looked into it and it seems like the problem is due to the fact that I am using Azure files as storage for Prometheus and reading the documentation I found out that Azure File does not support hard links so I think that's what is preventing the sidecar to behave as expected.

Thank you for your investigation! Closing the issue then because I'm not sure if we can do anything. Support for hard links is necessary for the Thanos Sidecar component. Please comment again if this needs to be reopened.

**Comment by Venture200** [comment]
err="upload 01GHDK0GPTX1A13XYDCKQB5Y0P: hard link block: hard link file chunks/000001: link /var/lib/prometheus/01GHDK0GPTX1A13XYDCKQB5Y0P/chunks/000001 /var/lib/prometheus/thanos/upload/01GHDK0GPTX1A13XYDCKQB5Y0P/chunks/000001: operation not permitted" uploaded=0


hello, after upgrading thanos to 0.29 I am getting this error, do you know why @GiedriusS
