### ISSUE TITLE
store: Process start times growing linearly with blocks in objstore

### ISSUE THREAD

**Issue by gburek-fastly** [thanos-io/thanos#3150]
**Thanos, Prometheus and Golang version used**:

thanos, version 0.15.0 (branch: HEAD, revision: fbd14b49f95e7543883fedf9381a21127d4dda2b)
  build user:       root@d35b081d3e19
  build date:       20200907-09:29:21
  go version:       go1.14.2

**Object Storage Provider**: GCS 

**What happened**: The time that that Thanos Store takes to become Ready has steadily grown over the last few months, as our block count, including marked-for-deletion blocks, have grown. Currently, it takes about 20 min for the process to start and become ready for grpc query traffic. This makes recovery from OOMs and updates to configs dangerous, as process restarts must be coordinated between HA store nodes so that the service is not unavailable. 

**What you expected to happen**: Thanos Store process restart takes at most a few minutes. 

**How to reproduce it (as minimally and precisely as possible)**: 
1. Create GCS bucket with uploaded thanos blocks of type:
```
{state="loaded"} | 17291
{state="marked-for-deletion"} | 8543
{state="duplicate"} | 2795
{state="time-excluded"} | 2468
{state="no-meta-json"} | 7
{state="label-excluded"} | 0
{state="too-fresh"} | 0
{state="corrupted-meta-json"} | 0
{state="failed"} | 0
```
2. Configure thanos store to use that bucket via objstore.config and start the process
3. Monitor logs for `"duration="` to see the base fetcher duration

**Full logs to relevant components**:

```
level=info ts=2020-09-10T16:09:59.54113385Z caller=http.go:57 service=http/server component=store 
  msg="listening for requests and metrics" address=127.0.0.1:9090
level=info ts=2020-09-10T16:30:39.287137249Z caller=fetcher.go:453 component=block.BaseFetcher 
  msg="successfully synchronized block metadata" duration=20m39.746067576s cached=30429 returned=17226 partial=5
...
level=info ts=2020-09-10T16:31:42.380517614Z caller=store.go:329 
  msg="bucket store ready" init_duration=21m42.83945024s
```

**Anything else we need to know**:

It appears the bulk of the process start time is in https://github.com/thanos-io/thanos/blob/e0b7f7b32e9c1071586cb5fb1b4ed4f134235824/pkg/block/fetcher.go#L400, based on observing `thanos_objstore_bucket_operations_total`.

From `thanos_objstore_bucket_operations_total` we can chart the progress of the `f.wrapped.fetch` function, which appears to have two phases:
1. a highly concurrent `f.fetchMetadata(ctx)` phase 
2. a single threaded `(f *IgnoreDeletionMarkFilter) Filter` phase

When started cold, with no on-disk meta cache, `{operation="get"}` and `{operation="exists"}` rise in tandem. In this attached graph we see `fetchMetadata` completing within 1m 20s of process start. Then, only `{operation="get"}` continues to increase, at a much slower rate, for the next 10 or so minutes, at which point a chef converge restarted the process before it was ready.

![Screen Shot 2020-09-10 at 5 09 28 PM](https://user-images.githubusercontent.com/49920412/92830000-b02c8c00-f389-11ea-8b72-62aa7137db57.png) 

When the process is started with an already present on-disk meta cache, only `{operation="exists"}` operation count rises, as the files are being found and loaded from disk. However, the slow rate of `{operation="get"}` in the second phase appears the same as the cold start case. 
 
![Screen Shot 2020-09-10 at 5 18 31 PM](https://user-images.githubusercontent.com/49920412/92830028-b6bb0380-f389-11ea-96ef-344e975b2989.png)

When searching through the code, I was able to match the cold start rise of `{operation="get"}` and `{operation="exists"}` to `(f *BaseFetcher) loadMeta` and its use of [exists](https://github.com/thanos-io/thanos/blob/e0b7f7b32e9c1071586cb5fb1b4ed4f134235824/pkg/block/fetcher.go#L212) and [get](https://github.com/thanos-io/thanos/blob/e0b7f7b32e9c1071586cb5fb1b4ed4f134235824/pkg/block/fetcher.go#L239). 

Further code reading suggests that the slow rise of `{operation="get"}` operations appears to be from [IgnoreDeletionMarkFilter.Filter](https://github.com/thanos-io/thanos/blob/e0b7f7b32e9c1071586cb5fb1b4ed4f134235824/pkg/block/fetcher.go#L780) [metadata.ReadDeletionMark](https://github.com/thanos-io/thanos/blob/e0b7f7b32e9c1071586cb5fb1b4ed4f134235824/pkg/block/fetcher.go#L784)

The chart seems to show that we are naively fetching deletion marks for all blocks in the objstore, as `thanos_objstore_bucket_operations_total{operation="get"}` rises by ~30K before the process is ready for queries. Looking at the code, the single threaded nature of the [filter block](https://github.com/thanos-io/thanos/blob/e0b7f7b32e9c1071586cb5fb1b4ed4f134235824/pkg/block/fetcher.go#L432-L437) seems to fit the increase in Thanos Store process start time with number of blocks, as well. 

I think that there are a number of possible improvements to these filter functions, such as adding the same goroutine based concurrency to filters as fetchMetadata has, and/or caching deletion-marks on disk and using lightweight `exists` objstore calls to see if they exist before attempting to `get`.

It is possible a similar bug exists in Compact, as it uses a similar code path, but compact is not a user visible component and is not as sensitive to delays in start up time.

**Comment by GiedriusS** [comment]
Very nice investigation! It seems to me like we should implement concurrency there and re-use this value here https://github.com/thanos-io/thanos/blob/03b6991949601d82fe17c4fbd2a658f678f0a6a5/cmd/thanos/store.go#L42 in that filter + add locking around modifying `f.deletionMarkMap` to avoid modifying the `map` concurrently.

**Comment by bwplotka** [comment]
Just curious if you have PV for those store GW instance?

**Comment by JoseRIvera07** [comment]
Same problem here, I have more than 5k of blocks in gcs, and thanos-store component takes around 20min to load it. Is there any configuration to make this time decrease ?

**Comment by crsandeep** [comment]
Same issue for us too. Takes more than 25m.

**Comment by gburek-fastly** [comment]
Hopeful that #3500 and 0.18.0 speeds store start up, but have not had a chance to test the rc. Will update once we either get to the rc or deploy the 0.18.0 official release.

**Comment by kakkoyun** [comment]
@gburek-fastly Have you observed any improvements after #3500?

**Comment by kakkoyun** [comment]
Just as a stopgap solution, have you tried to utilize a shared cache (memcached)?
And one last question do you run compactor? If so how does your config look like?

**Comment by gburek-fastly** [comment]
@kakkoyun with 0.18.0, I have seen a reduction in startup time of store from approximately 2*N to N where N is the block count.  

Our block count (with store ` --max-time=-170h`) is: 

```
{state="failed"} | 0
{state="label-excluded"} | 0
{state="marked-for-no-compact"} | 0
{state="corrupted-meta-json"} | 0
{state="too-fresh"} | 0
{state="no-meta-json"} | 1
{state="duplicate"} | 8
{state="marked-for-deletion"} | 234
{state="time-excluded"} | 12275
{state="loaded"} | 26903
```

With 0.17.2: `ts=2021-02-16T20:29:06.957979067Z caller=store.go:332 msg="bucket store ready" init_duration=40m19.691307451s`
With 0.18.0: `ts=2021-02-16T21:00:20.674829232Z caller=store.go:332 msg="bucket store ready" init_duration=28m3.441506353s`

0.17.2: 
![image](https://user-images.githubusercontent.com/49920412/108127903-cf2df900-7060-11eb-8b56-b184dc82e5dd.png)

0.18.0: 
![image](https://user-images.githubusercontent.com/49920412/108127996-f71d5c80-7060-11eb-834b-3e41a2db05b4.png)

#3500 seems to reduce the 10m window where `get` operations are increasing to maybe 10s. The window where `iter` operations are rising remain similar, with 26m in 0.17.2 and 23m in 0.18.0

Our store nodes already use a shared index-cache in memcache, but not `store.caching-bucket`. 

We also run compact, but have have about 250 prometheus replicas and thanos sidecars uploading blocks, which results in our fairly large block count.

**Comment by gburek-fastly** [comment]
Looking more at logs, the bulk of the improvement is in https://github.com/thanos-io/thanos/blob/v0.18.0/pkg/block/fetcher.go#L437-L442

0.17.2: `ts=2021-02-16T20:33:31.264784686Z caller=fetcher.go:458 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=13m29.266629999s cached=39429 returned=26909 partial=68`
0.18.0: `ts=2021-02-16T20:04:53.292830948Z caller=fetcher.go:458 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=3m49.776358561s cached=39935 returned=26909 partial=0`

However, both versions still take ~24m from that point in start up to become ready for queries.

Looking at the code and logs, it seems the `iter` section coincides with the [addBlock](https://github.com/thanos-io/thanos/blob/master/pkg/store/bucket.go#L471) section of [SyncBlocks](https://github.com/thanos-io/thanos/blob/master/pkg/store/bucket.go#L365). Adding `thanos_bucket_store_block_loads_total` (which is incremented in [addBlock](https://github.com/thanos-io/thanos/blob/master/pkg/store/bucket.go#L487)) to the previous graph of `thanos_objstore_bucket_operations_total` I think confirms this:
![image](https://user-images.githubusercontent.com/49920412/108138070-0b1d8a00-7072-11eb-95f0-3d002fca69d0.png)

Looking closer at our node metrics, it appears we hit a ~60MB/s Sustained throughput limit on our disks during the 23m `iter` section. This implies `60MB/s *24 minutes = 86.4 GB` read on start up, which checks out. 

We should be able to increase our disk throughput and our `--block-sync-concurrency` to get this faster and stop linear growth of start up time.
