### ISSUE TITLE
Question: how to identify who is calling my pod?

### ISSUE THREAD

**Issue by daviddelucca** [thanos-io/thanos#3157]
Hello folks!

We are building some metrics to identify which pod is calling a specific application. For what I have read, it is possible using Thanos. Based on that, I have created a query like:

```
round(
  sum(
    irate(istio_requests_total{connection_security_policy!="mutual_tls", destination_workload_namespace=~"auth", destination_workload=~"auth", reporter="destination"}[5m])) by (source_workload, source_workload_namespace, response_code), 
0.001)
```

It's almost working I'm getting  strane value like `0.167`, `0.133`. Is possible to get values like an integer? I just want to count how many requests are coming from other pods to pod called "auth".

**Comment by yeya24** [comment]
Hi, seems this is a promql/istio question and not related to Thanos. If you have promql questions, it would be good to ask them in the Prometheus mailing list https://groups.google.com/forum/#!forum/prometheus-users.
