### ISSUE TITLE
How to fix "invalid magic number"

### ISSUE THREAD

**Issue by codwu** [thanos-io/thanos#3162]
**Thanos, Prometheus and Golang version used**:
Thanos v0.10.0
Prometheus v2.13.0

**Object Storage Provider**:
s3
**What happened**:
Thanos Compact crash during the compaction
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:
level=info ts=2020-09-14T05:01:16.707592944Z caller=http.go:78 service=http/server component=compact msg="internal server shutdown" err="error executing compaction: compaction failed: compaction failed for group 0@14174343542426306368: compact blocks [/data/compact/0@14174343542426306368/01EHZ8KRXQH9SSC0YB8EWC8T8Q /data/compact/0@14174343542426306368/01EHZFFG5Q3MYKTEJRQB4V3M8Z /data/compact/0@14174343542426306368/01EHZPB7DRFZTQW2YW9QN81F2F /data/compact/0@14174343542426306368/01EHZX6YPGERHKK4D2N482SJTQ]: invalid magic number a80e18db"

**Anything else we need to know**:

**Comment by bwplotka** [comment]
Looks like one of those blocks might be malformed? Try to clear local disk of compactor and rerun. Does it repeats?

**Comment by codwu** [comment]
I cleard local disk and restarted compactor. It still crashed with same error.

**Comment by codwu** [comment]
I deleted the blocks in the error log from my object store. The compactor is running again. However, I think we should provide a better way to handle this promblem without any data loss.

**Comment by GiedriusS** [comment]
That's true. AIUI it should be possible to fix some cases if we assume that the data itself is correct e.g. recalculate the CRC hashes. I suppose let's merge this into https://github.com/thanos-io/thanos/issues/3306.
