### ISSUE TITLE
querier --selector-label not working when query without label

### ISSUE THREAD

**Issue by shicheng001sg** [thanos-io/thanos#3163]
for example if I run querier with --selector-label=namespace="ns1"
I query with kube_namespace_labels{namespace="xxx"} , the querier --selector-label is working as expect, only return result when namespace matches "ns1"
but if I query with kube_namespace_labels only, without specifying any labels to match in the query, then querier will return all records if can find for kube_namespace_labels

**Comment by bwplotka** [comment]
What is the behavior you would expect?
