### ISSUE TITLE
Oracle Cloud Buckets support

### ISSUE THREAD

**Issue by Hanoko** [thanos-io/thanos#3164]
Hi,

Is there any plan to support Oracle Cloud buckets in any near future?

Best regards

**Comment by bwplotka** [comment]
We are happy to review PR that will add this (if there will be person maintaining this as well) (: 

So.. PR's welcome!

**Comment by Hanoko** [comment]
Hi, 

I am a system engineer, so I don't know much about coding with Go. But if anyone could help with this this I could do the tests and check if everything is working correctly. We are planning to work with a cluster of Prometheus on Oracle Cloud Kubernetes and we would like to use Thanos or Cortex. If this feature is not available we will have to use Victoria Metrics as it has support for saving the metrics on disk.

Thanks in advance and thanks for all the work on this project.

Br,
Pablo

**Comment by bwplotka** [comment]
Looks like Oracle Cloud is already supported by our S3 type client (: See: https://gist.github.com/owainlewis/2a8b54b94836eded67dfe037608c32a9

**Comment by bwplotka** [comment]
Can you try to run Thanos object storage against cloud Oracle storage?

See docs: https://thanos.io/tip/thanos/storage.md/#s3

You could run something very simple like https://thanos.io/tip/thanos/storage.md/#s3 to quickly check if storage access works (: 

Let us know, we can reopen if something is not working :hugs:
