### ISSUE TITLE
docs: Document must-have alerts for Thanos deployment. 

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#317]
For example:
- compaction halt
- sidecar upload fails or being stuck! 
- rule eval failed or being stuck (for both Prometheus and Ruler)
and more
- query that does not have access to statically configure storeAPIs

**Comment by Bplotka** [comment]
https://github.com/improbable-eng/thanos/pull/392

**Comment by FUSAKLA** [comment]
Is there anything left to be done?

**Comment by bwplotka** [comment]
Yes, I think we can improve linking alerts in our docs better. I am working on Thanos ruler alerts right now.

**Comment by daixiang0** [comment]
@bwplotka now we have alert docs, could close this?

**Comment by GiedriusS** [comment]
Given that mixins were merged and we now have alerts such as this: https://github.com/thanos-io/thanos/blob/d4279663fab7682a029b783556a0793aec6b6a7b/mixin/thanos/alerts/compactor.libsonnet#L28
I think this can be safely closed now as we will continually update those as time goes. LMK if you have objections :P
