### ISSUE TITLE
Alerts launched by Thanos Rule don't generate metrics (ALERTS / ALERTS_FOR_STATE)

### ISSUE THREAD

**Issue by limberger** [thanos-io/thanos#3170]
Hi!
I don't know if is a bug or a Issue, but alerts launched by Rule don't  generate metrics ALERTS and ALERTS_FOR_STATE!

**Comment by yeya24** [comment]
Hi @limberger What's your setup and how did you query the `ALERTS` and `ALERTS_FOR_STATE` metrics?

These two metrics are created in Thanos Rule, so if you want to query them, you just need to add one more `--store=<grpc address for your ruler>` flag to your Thanos querier, then I guess you can query the metrics.

**Comment by limberger** [comment]
Thanks! You Alright!!! It's working!
