### ISSUE TITLE
website: Fix Table of Content generation.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3171]
Something is broken. This used to be long list giving all the headlines, now it's partial: https://thanos.io/tip/coding-style-guide.md/

cc @thisisobate :thinking:

**Comment by bwplotka** [comment]
Related piece of code: https://github.com/thanos-io/thanos/blob/36b5f176f62d6eb287a2031d7a946b8ddf855827/website/layouts/_default/single.html#L11

We did not change much here so it looks like newer version of Hugo made this? Maybe it's customizable? It looks like it ignored lower lever sections (h3 and larger) for some reasons :thinking:

**Comment by thisisobate** [comment]
Yeah... I agree with you. But it seems the problem occurs only on the `coding-style-guide.md` page. Would look into this right away
@bwplotka

**Comment by thisisobate** [comment]
fixed #3175 
PTAL @bwplotka

**Comment by bwplotka** [comment]
Fixed <3
