### ISSUE TITLE
Thanos not retriving S3 data

### ISSUE THREAD

**Issue by vishnubraj** [thanos-io/thanos#3185]
I updated to Thanos 15.0 version two weeks before.

```
thanos, version 0.15.0-rc.0 (branch: HEAD, revision: 4ef1b8dfd38ed19c90b4a5d181cd0e37d57960e0)
  build user:       root@74b40d217562
  build date:       20200826-15:20:57
  go version:       go1.14.2
```
I have 90days data locally and the remaining (Last 1 year data) in S3
When I query via Thanos i only get the local data and don't get any of the S3 data. 
I enabled Debug log on the Thanos query and Thanos Store, but I don't see any suspicious message.

Can someone help me fix this?

```
/usr/bin/thanos sidecar --tsdb.path /instance1 --http-address=0.0.0.0:19090 --prometheus.url http://localhost:9090 --grpc-address=0.0.0.0:10912 --objstore.config-file /etc/prometheus/s3_aws_access.yml
/usr/bin/thanos query --http-address=0.0.0.0:19192 --store=prometheus1a.sjc2:10912 --store=127.0.0.1:10914 --query.replica-label=replica --query.timeout=2m --query.max-concurrent=12 --query.auto-downsampling --grpc-address=0.0.0.0:10913
/usr/bin/thanos store --data-dir=/data/store --max-time=-90d --objstore.config-file /etc/prometheus/s3_aws_access.yml --store.grpc.series-max-concurrency=100 --http-address=0.0.0.0:10902 --grpc-address=0.0.0.0:10914
```

<img width="1801" alt="Screenshot 2020-09-17 at 11 43 06 PM" src="https://user-images.githubusercontent.com/11851188/93565014-470bd080-f9a8-11ea-993b-cb29d43bea7a.png">

<img width="2034" alt="Screenshot 2020-09-17 at 11 49 07 PM" src="https://user-images.githubusercontent.com/11851188/93565024-4c691b00-f9a8-11ea-885a-307868fad62a.png">

**Comment by vishnubraj** [comment]
I am getting the below message in the Thanos query. What is meant by filtered out?

```
Sep 18 14:04:16 prometheus1a.sjc2 thanos[329800]: level=debug ts=2020-09-18T14:04:16.537173178Z caller=proxy.go:306 msg="store Addr: prometheus1a.sjc2:10912 LabelSets: [name:\"region\" value:\"sjc2\" ,name:\"replica\" value:\"prometheus1a\" ] Mint: 1592647200000 Maxt: 9223372036854775807 queried;store Addr: 127.0.0.1:10914 LabelSets: [name:\"region\" value:\"sjc2\" ,name:\"replica\" value:\"prometheus1a\" ][name:\"region\" value:\"sjc2\" ,name:\"replica\" value:\"prometheus1b\" ] Mint: 1564387200000 Maxt: 1592661854607 filtered out"
```

**Comment by vishnubraj** [comment]
Can someone help me with this, I downgraded Thanos to 0.12 version also but still it's not showing any data from S3. 
It's a very critical issue. Please

**Comment by yeya24** [comment]
Close this as #3193 is resolved.
