### ISSUE TITLE
Incorrect comment in DNS provider

### ISSUE THREAD

**Issue by bboreham** [thanos-io/thanos#3187]
This line is the only occurrence of `defaultPort` in this repo:
https://github.com/thanos-io/thanos/blob/00510b5ae7fbcfc42c735532069afead30c3bb01/pkg/discovery/dns/provider.go#L111

I believe what actually happens is it returns an error.

**Comment by bwplotka** [comment]
Good point, help wanted to fix it (:

**Comment by daksh-sagar** [comment]
Should the comment instead be `// returns an error when a port is not supplied` ?

**Comment by daksh-sagar** [comment]
Happy to take this issue 🙂

**Comment by bboreham** [comment]
> Should the comment instead be `// returns an error when a port is not supplied` ?

There are (at least) two cases: SRV and non-SRV, and your proposal would be incorrect for the SRV case.

**Comment by daksh-sagar** [comment]
> > Should the comment instead be `// returns an error when a port is not supplied` ?
> 
> There are (at least) two cases: SRV and non-SRV, and your proposal would be incorrect for the SRV case.

Is it Error for non-SRV and defaultPort for SRV ?

**Comment by bboreham** [comment]
> Is it Error for non-SRV and defaultPort for SRV ?

> > This line is the only occurrence of `defaultPort` in this repo:

i.e. it is impossible that the commented code will return it.

**Comment by bboreham** [comment]
The comment is still incorrect.

**Comment by Namanl2001** [comment]
@bboreham I'm looking into this.

**Comment by Namanl2001** [comment]
Hey, what I have found is that it returns error for non-SRV prefix, when a port is not supplied. 
While for SRV prefixes there is no need to specify a port, as the one from the SRV query results will be used.
