### ISSUE TITLE
Document query frontend in-memory cache config better

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#3189]
There is an example in-memory cache config for query frontend in the document https://github.com/thanos-io/thanos/blob/master/docs/components/query-frontend.md#in-memory. However, it is not very clear how to configure these values, what is the correct format, etc.

AC, we should document 4 items:

1. The format of `max_size`. Based on the flag in Cortex https://github.com/cortexproject/cortex/blob/master/pkg/chunk/cache/fifo_cache.go#L43, `A unit suffix (KB, MB, GB) may be applied.`

2. Based on https://github.com/cortexproject/cortex/blob/master/pkg/chunk/cache/fifo_cache.go#L105, if `max_size` and `max_size_items` are not set, then the cache won't be created. We should document this case clearly.

3. If one of `max_size` and `max_size_items` is configured, then there is no limit for another field. 

4. Maybe we can also add a link for the example in kube-thanos https://github.com/thanos-io/kube-thanos/blob/master/examples/all/manifests/thanos-query-frontend-deployment.yaml#L50-L54

For more context, please check the slack thread https://cloud-native.slack.com/archives/CK5RSSC10/p1600454916006900.

**Comment by daksh-sagar** [comment]
@yeya24 Hey, can I take this up ?

**Comment by RealRadOne** [comment]
@yeya24 Can I take this up?

**Comment by data-dude** [comment]
Docs can still be improved.  I had to search some comment section to find this.  I'm not sure why flags and example isn't documented. 

  ```
  --query-range.response-cache-config="config":
            "max_size": "512MB"
            "max_size_items": 0
            "validity": "6h"
          "type": "in-memory"
```
