### ISSUE TITLE
receive: relax quorum in case of 2 nodes

### ISSUE THREAD

**Issue by sepich** [thanos-io/thanos#3194]
**Thanos, Prometheus and Golang version used**:
v0.15.0

**Object Storage Provider**:
GCS

**What happened**:
Using single node thanos-receive and want to improve reliability a bit by adding the second node. Unfortunately due to 
https://github.com/thanos-io/thanos/blob/6fa6b4a18988ed11dd9392b399cde341ac36dc47/pkg/receive/handler.go#L386
I have to add 2 more nodes, to survive one node down.

**What you expected to happen**:
I understand the reasoning behind desire to have at least 2 copies of data, when you are SaaS and running on spot-instances.
But there could be other situations, for on-premises it could be "good enough" to have only single copy of data. It could be feasible to add a second node to make it possible to do maintenance with first one. But adding 2 more nodes could be "too much".
I propose to relax quorum to `1` for the case of `--receive.replication-factor=2` and add usual split-brain warning to the docs.
Because right now there is insist on majority at write-path, but read-path does not care about majority and would work with any amount of copies of data. Vertical compaction also works fine for 2 copies, which have not overlapping holes.

**How to reproduce it (as minimally and precisely as possible)**:
Here is docker-compose with 2 thanos-receive and prometheus with grafana
https://github.com/sepich/compose-playground/tree/thanos-quorum
Issue could be observed via `docker-compose stop thanos-receive-1`

**Full logs to relevant components**:
Prometheus logs:
```
ts=2020-09-20T13:07:30.335Z caller=dedupe.go:112 component=remote level=warn remote_name=5204bb url=http://thanos-receive-0:19291/api/v1/receive msg="Failed to send batch, retrying" err="server returned HTTP status 500 Internal Server Error: 2 errors: replicate write request, endpoint thanos-receive-1:10901: unexpected error, before quorum is reached: backing off forward request for endpoint thanos-receive-1:10901: target not available; replicate write request, endpoint thanos-receive-0:10901:"
```
Thanos receive-0 logs:
```
level=error ts=2020-09-20T13:07:32.8906771Z caller=handler.go:331 component=receive component=receive-handler err="2 errors: replicate write request, endpoint thanos-receive-1:10901: unexpected error, before quorum is reached: backing off forward request for endpoint thanos-receive-1:10901: target not available; replicate write request, endpoint thanos-receive-0:10901: unexpected error, before quorum is reached: backing off forward request for endpoint thanos-receive-1:10901: target not available" msg="internal server error"
```

**Anything else we need to know**:
I can work on PR if there is no objections.

**Comment by bwplotka** [comment]
It's not about quorum, it's just for reliability.

Our first question is do you really need replication factor 2 in this case. Replication is only needed for storage fail-safety, nothing more. For increased availability you can have replication factor =1 and two/three nodes, no? (:

**Comment by sepich** [comment]
Yes, you are correct - it is about reliability.
> you can have replication factor =1 and two/three nodes

Let's consider case of 2 nodes behind load balancer. (Both nodes are configured in Querier):
1. `replication-factor=1` and hashring.json empty
In this case each new connection gets to random node and we end up with a lot of stale markers and holes on graphs. Because each node gets only half of data, and the set is inconsistent.
Turn off any node and you miss half of recent data (which is not yet uploaded to S3)

2. `replication-factor=1` and hashring.json has both nodes
In this case no more staleness and holes on graphs. Metrics are resent to node where they are supposed to be, each node have only half of full set of data, but this half is consistent. 
But the same problem - I can't turn off any node, would miss half of recent data. And half of remote-write queries are begin to fail.

3. `replication-factor=2` and hashring.json has both nodes
Full metric set is stored on each node, doubles the storage consumption. If I turn off one node - all new data stops to be accepted. So I again do not see any recent data, because it is getting 500.

I propose to fix situation number 3. So that 2-node cluster in case of one node down would still be working and accept the remote-writes.

**Comment by bwplotka** [comment]
> replication-factor=1 and hashring.json empty
In this case each new connection gets to random node and we end up with a lot of stale markers and holes on graphs. Because each node gets only half of data, and the set is inconsistent.
Turn off any node and you miss half of recent data (which is not yet uploaded to S3)

Staleness markers does not work like this. They are introduced on scrape time, not on push time. Also inconsistent data is fine, this is only database side. Querier will merge data from two just fine.

In fact with proper setup and vertical compaction on, compactor will merge this data into one block anyway.

**Comment by bwplotka** [comment]
I feel like what you want is actually 1. with 2-3 nodes and vertical compaction on.

And yes, you will have (ideally only restart time) unavailability on the querying side, but no ingestion unavailability which you aim for.

**Comment by bwplotka** [comment]
Let's say we fix 3 as you propose. Consider following scenario:

* Two receives are up and ingesting each same (factor = 2)
* One is down (rolling upgrade). Second one is ingesting.
*First is back ingesting, now second is down. Now when you query you have short unavailability (gap) of some small amount of older data that was ingested by the second instance until it's up.

At the end with point no 3 we have exactly same availability level than point one, no? (:

**Comment by sepich** [comment]
> replication-factor=1 and hashring.json empty
Staleness markers do not work like this. They are introduced on scrape time, not on push time. 

Thank you for details!

> Also inconsistent data is fine, this is only database side. Querier will merge data from two just fine.

Unfortunately it is highly unreliable:
![image](https://user-images.githubusercontent.com/1803804/94482552-22063180-01e2-11eb-91f9-a9ce864db512.png)
After some time graphs becomes like this. Here is faster way to reproduce the issue:
<details>
  <summary>Steps</summary>

Here is docker-compose with prometheus sending data to nginx, which balances over 2 thanos-receive.
Both of the receives are added to thanos-query, and there is grafana to see the result.
https://github.com/sepich/compose-playground/tree/thanos-lb
- set the stage
```
git clone https://github.com/sepich/compose-playground.git
cd compose-playground
git checkout thanos-lb
```
- now edit file docker-compose.yml and uncomment lines 25-26, 47-48, 
```
#      - --receive.hashrings-file=/cfg/hashrings.json
#      - --receive.replication-factor=2
```
so we start in replicating mode first

- start and login to grafana on http://localhost:3000
`docker-compose up -d`
all graphs should be smooth now.

- now switch to `replica=1`, and comment the lines 25-26, 47-48 back
`docker-compose up -d`

- checkout graphs with `rate()` like `Thanos: receive` > `HTTP server` (screenshot above)

Data is written to `./data` subfolder. If you clean it up, and start in `replica=1` mode from empty - then graphs would be fine for some time and then go back to holes. In prod you usually get holes ;)

</details>

> At the end with point no 3 we have exactly the same availability level than point one, no? (:

In your invented situation - yes. I can invent another situation, for example:
It is not a "rolling upgrade" but old pc used for this server is down. It would take some time to fix it, maybe its disk data is lost. Then if i'm in 1 - i lost data not yet uploaded to s3 (plus holes on graphs above). 
In 3 - I'm failing ingestion for hours. 
In fixed 3 - i'm fine ;)

Why argue about situations? Maybe it's worth to provide more options for users to choose from, so they decide based on their situation.
You'd better share the drawbacks of lowering quorum for 2 - what is the downside?

**Comment by sepich** [comment]
We still have to run a 2-replica fork in production.
Would be nice to allow other users to do it too, and fix upstream.

**Comment by sepich** [comment]
Sorry for disturbing, I clearly understand the [burden](https://news.ycombinator.com/item?id=25940195) of maintaining of opensource project. It just contents of CONTRIBUTING.md which lead me to creation of this bug/PR.
Wouldn't mind still hear the drawback this change brings. 

Anyway, for those who found this bug autoclosed and are interested in the fix: https://github.com/sepich/thanos/blob/master/README.md

**Comment by Kampe** [comment]
This is a probelm we see as well over time with using 3 recieve nodes and a replication-factor=2

**Comment by GaoJiasheng** [comment]
Actually, I can totally understand why set the limit that must be more than 1 replica successfully when `replication-factor=2`. It makes sense and reasonable in some storage components such as ceph, S3.
let me share my scenario bah.
Now our receiver cluster contains 30 servers. for our company, the bussiness reliability is more important than reliability of monitoring system. so we want to keep monitoring system be reliable any time. The purpose of 2 replication-factor is for data querying and writing can work normally in case one instance is down.
for thanos/receiver, I don't think it's a pure storage component. it's an eco-system for observing business reliability and quality. so at most time, I think we don't care how many replicas in storage. (and anyway, the data in receiver will expire, and compact will compact the data). 
the point we more concerned is how can keep the thanos stable, how can digest data fluently and provide data for viewing at any scenarios.
so I alter the calculation logic of quorum. https://github.com/thanos-io/thanos/pull/4053
