### ISSUE TITLE
query-frontend: Reduce unnecessary downstream queries by maintaining downstream metadata

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#3196]
## Proposal

Now, the thanos query frontend component can split a large query into smaller pieces and send multiple smaller queries to a downstream thanos querier. However, some splitted queries are not necessary because they are outside the querier time range.

For example, I have a range query for 1w time range. It will be splitted into 7 queries, each one is 1d time range. But the querier only can query the latest 1d data, so 6 queries are unnecessary, and 1 query is cached. If I run the 1w range query again, then again 6 queries are unnecessary and they all hit the downstream querier...

Maybe we can do something smarter since the downstream is always thanos querier and it implements the `Store` API. The query frontend can easily get its time range by a `Info` gRPC request and maintain the [minTime, maxTime] range in a goroutine.

Pros:
1. Reduce unnecessary requests
1. This time range metadata can be reused in other endpoints such as `/api/v1/labels`, `/api/v1/series` as well.

Cons:
1. Keep sending `Info` gRPC requests is also a cost because proxy store sends `Info` requests to all its stores in a fanout way. Not sure whether this is useful without some experiments.
2. The cache part will be more complex?

Alternative
Have a goroutine to call Thanos querier `/api/v1/stores` API. This API also gives us the time range information as well as the current store list. This can help us update response cache when stores change.

This is just a proposal and I am not sure whether this feature is useful or not. Grafana dashboard usually shows graph for last `xd/xh`, so usually unnecessary queries caused by time range are rare.

**Comment by bwplotka** [comment]
Thanks for this proposal. This is totally doable I agree and there are couple options here. 

My main question though - is it worth it? As you said, polling `Info` or something like this on async or sync way would involve some complexity and network anyway. And the concurrent split queries that returns nothing, would be fast if Querier already knows it has access only to 1d, no? (: So what exactly we are optimizing for here?

**Comment by yeya24** [comment]
Right. I am thinking about whether this is necessary or not. Seems it is not useful, because the network requests are still there.
