### ISSUE TITLE
Thanos overloads alertmanager when connecting directly

### ISSUE THREAD

**Issue by sevagh** [thanos-io/thanos#3200]
Hello. I'm using Thanos 0.14.0. Initially, I was connecting to my alertmanagers via a load balancer url:
```
 --alertmanagers.url="http://alertmanager.mydomain.com" 
```
This worked fine. Then, I realized that in my Prometheus (non-Thanos) clusters I connect to the alertmanagers directly (via the prometheus.yml config), so I wanted to enforce the same behavior in Thanos.
I switched to an alertmanager config.yml file:
```
alertmanagers:
- http_config:
  static_configs:
  - am1:9093
  - am2:9093
```
Passed to `thanos rule` as follows:
```
--alertmanagers.config-file=/path/to/amconfig.yml
```
This works for a while until the alertmanagers started displaying the following error:
```
Limit of concurrent GET requests reached (32), try again later.
```
I increased the Alertmanager concurrency limit to 64, and hit the same error at the higher limit.

I eventually went back to using the loadbalancer URL instead of the config file. Is my config file somehow malformed? Is this expected with Thanos + Alertmanager?

**Comment by bwplotka** [comment]
Interesting, thanks for reporting!

 Let's investigate, this uses the same code path really just a different configuration. :thinking:  Help wanted for digging this.

**Comment by zkmrgirish** [comment]
@bwplotka I would like to work on this 🙂

**Comment by mneverov** [comment]
hi, I'd like to work on this

**Comment by mneverov** [comment]
@sevagh Increasing limit of simultaneous requests in alertmanager should help (search for `--web.get-concurrency` in the [changelog](https://github.com/prometheus/alertmanager/blob/a8ed0d58509d0251adcb159552b9ab098e206f1f/CHANGELOG.md) file).

The described configuration (one load balancer URL with `--alertmanagers.url="http://alertmanager.mydomain.com" `) creates one alertmanager sender with this URL. Each alert is sent once to that load balancer.

When you switched to the config file you configured two URLs. Two senders are created and each alert is sent to each of these alertmanagers. This is done intentionally. From the [alertmanager readme](https://github.com/prometheus/alertmanager/blob/a8ed0d58509d0251adcb159552b9ab098e206f1f/README.md#high-availability):

> Important: Do not load balance traffic between Prometheus and its Alertmanagers, but instead point Prometheus to a list of all Alertmanagers. The Alertmanager implementation expects all alerts to be sent to all Alertmanagers to ensure high availability.

So, for each alertmanager the load has doubled, hence the recommendation.

If you change the arguments to contain both alertmanager like ` --alertmanagers.url="http://am1:9093" --alertmanagers.url="http://am12:9093"` you should get the same `limit of concurrent requests` error.

**Comment by sevagh** [comment]
Thanks, I'll try this suggestion. But note that I also tested a concurrency of 64 with the same error:
>I increased the Alertmanager concurrency limit to 64, and hit the same error at the higher limit.

How high can this go? 128? Unconstrained? I'm wondering if I should start splitting up my Alertmanager meshes so that my 2 biggest Thanos environments aren't using the same one.

**Comment by mneverov** [comment]
Thanks for the reply, that is indeed odd. 
Could you also please check `thanos_alert_sender_errors_total` with both configurations?
Thanos doesn't have backoff, so if an alert POST failed for some reason it will be repeated without any delay.

**Comment by mneverov** [comment]
@sevagh could you please add a comment here if it did help (and the concurrency limit)?

**Comment by sevagh** [comment]
Sorry about that, I missed the last suggestions. I'll report back - still trying stuff. I can see "thanos_alert_sender_errors_total" climbs up to 200k+ in some cases. Right now out of my mesh of 5 alertmanagers, 2 of them are always exhibiting the error:
>Limit of concurrent GET requests reached (32), try again later.
This is so strange since the load balancing is supposed to be fair.

**Comment by sevagh** [comment]
I think we can rule this as PEBKAC. I simply had too many clients connected to Alertmanager. I doubt it is a magic incorrect Thanos behavior.

I think, IMO, the worse bug is that once Alertmanager gets into the state of printing "Limit of concurrent GET requests reached (32), try again later", it never recovers - but that's a bug I can file or investigate on the Alertmanager codebase.

**Comment by bwplotka** [comment]
:+1: Thanks!
