### ISSUE TITLE
 just question ,is thanos' object storage support hdfs，like hdp,cdh?

### ISSUE THREAD

**Issue by tonyC2016** [thanos-io/thanos#3202]
**Thanos, Prometheus and Golang version used**:

**Object Storage Provider**:

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by yeya24** [comment]
It is not supported. You can find all supported storage backend https://github.com/thanos-io/thanos/blob/master/docs/storage.md#configuration here.

**Comment by bwplotka** [comment]
HDFS is not object storage, but distributed filesystem. However, technically with proper implementation Thanos could work over HDFS with something like https://github.com/colinmarc/hdfs. Help wanted for contributing this (:

**Comment by tonyC2016** [comment]
> HDFS is not object storage, but distributed filesystem. However, technically with proper implementation Thanos could work over HDFS with something like https://github.com/colinmarc/hdfs. Help wanted for contributing this (:

i dont konw the different about object storage and distributed filesystem, and recently i study on the monitor,and i do a plan that flink+consul+pushgateway+prometues for monitor,but it cant fix the large storage,so i found the thanos  ,whether thanos and hdfs can fix the large storage

**Comment by tonyC2016** [comment]
> It is not supported. You can find all supported storage backend https://github.com/thanos-io/thanos/blob/master/docs/storage.md#configuration here.

i saw that, but i wanna konw whether thanos and hdfs (or something base on hdfs) can work together?coz hdfs can save larger data,and monitor need the history data
