### ISSUE TITLE
Thanos 0.15 does not start if S3 bucket conf is not set correctly

### ISSUE THREAD

**Issue by clausa20** [thanos-io/thanos#3208]
Hello,
I have set Thanos (prometheus sidecar, querier, store, compactor) with version 0.14.0.
I have some configuration that makes optional the setting to connect with S3 bucket, so if for example the bucket name does not exist, or access and secret keys are incorrect, then the querier and sidecar starts the same, even in logs there are errors about it cannot connect to S3, but I can access with curl or http the querier for example.

But when I try to update Thanos version to 0.15.0, I am not able to access with curl or http the querier due to it cannot access to S3.

I would be great if version 0.15.0 has the same behavior as 0.14.0, so I can keep using other features that Thanos provides.

Thanks.

**Comment by bwplotka** [comment]
Hey,

This is a good call, just curious why you would like to run Thanos with broken S3 bucket upload? What's the rationales?

Sorry for breaking the old behaviour, but let's first decide what is the proper one. We believe in fail fast approach. If sidecar immediately sees the upload is being broken, it might be much nice to fail fast and indicate the operator that something is wrong (e.g after rollout). If sidecar will ignore the error and just log / produce metric it might get unnotice, especially for those who does not have yet good alerting in place. (: WDYT?

Something you can do even now is to run two sidecars, one for exposing. second for uploading (:

**Comment by bwplotka** [comment]
As we speak there is issue that would be much easier to find out if sidecar would crash: https://github.com/thanos-io/thanos/issues/3198#issuecomment-697770550 (:

**Comment by clausa20** [comment]
@bwplotka the reason is because we have many environments, in dev environments for example, we don't want to create S3 buckets to reduce costs.

I am using the thanos-sidecar in prometheus operator, if the thanos-sidecar container fails, then the entire prometheus pod fails, and then the querier, etc... Prometheus Operator just allow 1 thanos-sidecar.

An idea could be to add a flag option in thanos to not fail if S3 is unreachable? then I can still use the other thanos features like prometheus HA?

**Comment by bwplotka** [comment]
> @bwplotka the reason is because we have many environments, in dev environments for example, we don't want to create S3 buckets to reduce costs.

I think you are missing some config template / management so you can have different configuration for those different environments? (: Why not, not setting the bucket config if you don't want upload?
