### ISSUE TITLE
ci: Link checker flakiness.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3210]
New link checker is flaky as well =D 

https://github.com/thanos-io/thanos/pull/3209/checks?check_run_id=1156310870

cc @daixiang0 

Life is hard.

**Comment by daixiang0** [comment]
Sad news :(

**Comment by bwplotka** [comment]
We removed it for now. Waiting for replacement.

**Comment by daixiang0** [comment]
I see istio uses htmltest, do not find flafkiness, shall we try it?
