### ISSUE TITLE
Create built-in deadman switch in Ruler

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3213]
TBD

**Comment by kakkoyun** [comment]
I guess still valid. We still wait for the description though.

**Comment by yeya24** [comment]
Is this still valid?

**Comment by OGKevin** [comment]
I do have a use case for this, atm I've had to manually define always firing alerts. So to have this build in ruler would be nice. If @bwplotka can write criteria/design etc I would love to have a look at implementing it. 

My idea: check if downstream prom API's are reachable and if so continue to fire the alert. If it's not reachable, stop firing the alert. In case AM is down the heartbeat also fails. So with this method, you have the whole alerting chain.
