### ISSUE TITLE
Remove the need for specifying React UI's paths in `ui.go`

### ISSUE THREAD

**Issue by prmsrswt** [thanos-io/thanos#3216]
We are using client-side routing in the new React UI. This means that for all the client-side routes (ex. `/new/graph`, `/new/stores`, etc.) in the new UI, we need to serve the same `index.html`. Right now we maintain an array of paths in the Go code, named `reactAppPaths`. If the incoming request's path is found in this array, we directly serve the `index.html` file, otherwise, we return `404` or a file if one exists with the given path.

Instead of maintaining the array, we can replace `404` with the `index.html` file. This is a common model in serving single-page applications. If the incoming request corresponds to a static asset, return that asset, otherwise return the `index.html` file. If the given route doesn't exist, then we can show a 404 page directly on the client-side, using a default route in React.

**Comment by ajinkya359** [comment]
I would like to work on it.

**Comment by prmsrswt** [comment]
Closing this as this was fixed in #3647
