### ISSUE TITLE
ui: Add "Configuration Files" page

### ISSUE THREAD

**Issue by onprem** [thanos-io/thanos#3217]
Right now we have a page to show the CLI flags passed and the Runtime and Build information. It would be nice to have a page showing the contents of configuration files passed to a component as well. For example, the object storage configuration, or the rules config file.

**Some things to keep in mind:**
- In Thanos, we use a special type of flag called `PathOrContent`. The user can pass either path to a file or the contents of the file directly.
- We can have multiple configuration files in a component (or no files at all).
- Some configuration files may contain secrets in them. Ideally, we would like to hide/sensor those secrets when showing the files on the Web UI.

**Comment by aribalam** [comment]
I'm taking this up!

**Comment by aribalam** [comment]
cc @prmsrswt @bwplotka

**Comment by onprem** [comment]
Still needed.
