### ISSUE TITLE
Shipping sourcemaps for the React UI in production

### ISSUE THREAD

**Issue by prmsrswt** [thanos-io/thanos#3218]
Currently, we exclude the source-maps of React code from the production build. The JS code for web UI is minified in the final binary, so if someone gets an irrecoverable error on the UI the stack trace shown there will be very cryptic and not usable.

In the upcoming React 17 release, they have made the stack traces more usable in production builds of React ([more info here](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#native-component-stacks)). But to take the advantage of this we need to ship the source-maps in the binary as well.

The only con is the increased binary size. I am not sure about how much the difference there is in terms of final size, but let's ship source-maps unless the size difference is too significant.

**Comment by daksh-sagar** [comment]
@prmsrswt I tried the production build on react `17.0.0-rc.2` both with and without sourcemaps. The size of the build folder with source maps is `7.5 MB (78,56,383)` while that without sourcemaps is `1.5MB (16,09,355)`, quite a large difference.

**Comment by GiedriusS** [comment]
Since there's quite a difference, maybe let's only leave `main` and `runtime-main` source maps? This way we could still debug problems if they happen in _our_ code and the size difference shouldn't be too large. WDYT, @prmsrswt @daksh-sagar ?

**Comment by prmsrswt** [comment]
I checked and that'll reduce the size difference by quite a lot (about under 500KB). But I am not sure if it'll give us much value in return. If we don't include sourcemaps for a vast majority of code, we will not have proper stacktraces for a vast amount of crashes. Any thoughts on this?

**Comment by GiedriusS** [comment]
Then, I guess, we shouldn't do this at all if it causes such an increase in size. :thinking:

**Comment by prmsrswt** [comment]
Yes, let's close this for now.
