### ISSUE TITLE
Block Viewer: Allow deleting a block from Block Viewer itself

### ISSUE THREAD

**Issue by onprem** [thanos-io/thanos#3220]
We can implement block deletion from the Block Viewer UI itself. It'll be useful in case someone want's to delete overlapping or malformed blocks.

**Comment by ahmednasir91** [comment]
I've started working on this

**Comment by kakkoyun** [comment]
@ahmednasir91 Friendly ping. Any on-going PR that you can share?

**Comment by ahmednasir91** [comment]
@kakkoyun sorry for late reply, i got swamped with work and couldn't really complete it.

**Comment by prmsrswt** [comment]
No problems @ahmednasir91. Are you planning to continue your work on this or is it fine if somebody else takes this over?

**Comment by kakkoyun** [comment]
Still valid.
