### ISSUE TITLE
Block Viewer: Show size of the blocks in the UI

### ISSUE THREAD

**Issue by onprem** [thanos-io/thanos#3221]
The size of a block is a useful metric. We can show things like the overall size of a block, the size of it's index, the total size occupied by all blocks, etc. in the Block Viewer itself.

**Comment by aribalam** [comment]
I see that Prometheus has an API exposed to query currently stored TSDB Blocks (via `/api/query/v1/blocks`). But I am unable to find details of it in the Prometheus or Thanos docs. I am guessing the above required data will be queried using that API? 
Is there any relevant docs or resources where I can find details of such an API.

**Comment by roidelapluie** [comment]
Note that recently Prometheus BlockReader gained Size() function.

**Comment by bwplotka** [comment]
> I see that Prometheus has an API exposed to query currently stored TSDB Blocks (via /api/query/v1/blocks). But I am unable to find details of it in the Prometheus or Thanos docs. I am guessing the above required data will be queried using that API?
Is there any relevant docs or resources where I can find details of such an API.

We have other APIs for this and yes, it should be better documented - only block viewer is using it.

> Note that recently Prometheus BlockReader gained Size() function.

This is great but not very helpful for this issue, as we store all blocks in object storage (:

**Comment by roidelapluie** [comment]
> > I see that Prometheus has an API exposed to query currently stored TSDB Blocks (via /api/query/v1/blocks). But I am unable to find details of it in the Prometheus or Thanos docs. I am guessing the above required data will be queried using that API?
> > Is there any relevant docs or resources where I can find details of such an API.
> 
> We have other APIs for this and yes, it should be better documented - only block viewer is using it.
> 
> > Note that recently Prometheus BlockReader gained Size() function.
> 
> This is great but not very helpful for this issue, as we store all blocks in object storage (:

object storage does not implement the BlockReader interface?

**Comment by bwplotka** [comment]
Not directly.

**Comment by roidelapluie** [comment]
yes

**Comment by zerefwayne** [comment]
Hi @roidelapluie @prmsrswt I would like to take this up if it's still unresolved.

**Comment by saswatamcode** [comment]
@prmsrswt Is this issue still open? Would love to take this up!

**Comment by douglascamata** [comment]
Closing this as done with PR #7233, related to #7205.
