### ISSUE TITLE
Block Viewer: Allow downloading `meta.json` of a block

### ISSUE THREAD

**Issue by prmsrswt** [thanos-io/thanos#3222]
As all the metadata is already available on the Block Viewer for a block, we can also provide a button to download the `meta.json` for a block.

You can get more idea about programmatic file downloads using JS in [this blog post](https://blog.logrocket.com/programmatic-file-downloads-in-the-browser-9a5186298d5c/).

**Comment by bwplotka** [comment]
:+1:

**Comment by Oghenebrume50** [comment]
Hi @prmsrswt by metadata do you mean the details to the right of the attached screenshot?
![metadata](https://user-images.githubusercontent.com/37092867/94371075-9d38ec00-00eb-11eb-99fd-6ac3e9efdbf5.png)

**Comment by prmsrswt** [comment]
Yep this. The data you see on the right side originally comes from a file called `meta.json` inside a block. This file contains metadata about that particular block. Now that we have the metadata as a JS object, we can convert it to JSON again and offer it as a file to download.

**Comment by Oghenebrume50** [comment]
Alright, I would work on that.
