### ISSUE TITLE
Thanos Frontend Dashboard styles and .js broken in 0.15.0

### ISSUE THREAD

**Issue by clausa20** [thanos-io/thanos#3224]
Hello,

I have thanos deployed with kubernetes. I have querier pods plus a kubernetes service in the front. I have this option so I can access it externally through that service: - --web.external-prefix=/api/v1/namespaces/devenv/services/thanos-querier:http/proxy
without --web.route-prefix
with version 0.14.0 I can access to Thanos Querier Dashboad OK,

but when I update it to version 0.15.0 I cannot access to querier. But if I add this option  --web.route-prefix=/ I can access
but all the style is broken in the Dashboard. 
Looking into inspect of browser I can see for example this for most of files:

http://api/v1/namespaces/devenv/services/thanos-querier:http/proxy/static/vendor/js/jquery-3.5.0.min.js?v=fbd14b49f95e7543883fedf9381a21127d4dda2b

You can notice that it does not has the host:port after the http://

Only for 2 I see it correctly, for example:
http://**localhost:9999**/api/v1/namespaces/devenv/services/thanos-querier:http/proxy/graph

Has something changed in version 0.15.0 related to this?

Regards.

**Comment by aribalam** [comment]
@clausa20 Would you be able to specify how exactly to reproduce the issue. This might help us to know where to look.

**Comment by clausa20** [comment]
I just start thanos with kubernetes and a service, then I start a kubectl proxy --port=9999 and I try to browse it.
I see there is another Bug just raised, seems to be the same problem: https://github.com/thanos-io/thanos/issues/3226

**Comment by prmsrswt** [comment]
The PR to fix #3226 has been merged. Can you check if this bug still exists if you use a binary built from master.

**Comment by clausa20** [comment]
@prmsrswt seems that querier is fixed now, but the thanos frontend fails. It has in the path like double web.external-prefix, one to the frontend and other to the querier, I don't know if that is correct, but I get a Page Not Found 404:

http\://localhost:9999/api/v1/namespaces/devenv/services/**thanos-frontend:http**/proxy/api/v1/namespaces/devenv/services/**thanos-querier:http**/proxy/graph

**Comment by prmsrswt** [comment]
I think you wouldn't need to specify the external prefix like path two times, as query front-end is running inside the cluster, it can access the querier on its regular path instead of the kube-proxy one.

**Comment by clausa20** [comment]
@prmsrswt I just put http://localhost:9999/api/v1/namespaces/devenv/services/thanos-frontend:http/proxy/ in the browser, but Thanos adds automatically the api/v1/namespaces/devenv/services/thanos-querier:http/proxy/graph part, like attaching the thanos-querier web.external-prefix . That makes it break I guess.

**Comment by clausa20** [comment]
@prmsrswt I have changed the title, since you already fixed the querier, but the Frontend Dashboard  keeps failing.
I see there are many issues raised related to Dashboard access, seems to be all related.

**Comment by clausa20** [comment]
some news about this?

**Comment by yeya24** [comment]
Can you please try the new v0.16.0 release?

**Comment by yeya24** [comment]
Hi @clausa20 , Is this fixed or still a problem?
