### ISSUE TITLE
[Feature] sidecar: Refresh AWS object store credentials for 400 expired tokens

### ISSUE THREAD

**Issue by juiceblender** [thanos-io/thanos#3225]
Thanos version: 0.14.0

I think this is most relevant for @bwplotka :) 

**Object Storage Provider**: AWS.
 
**What happened**: 
Wondering if we could add a feature to reinitialise the client if it receives error code 400 for expired token, as detailed here: https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

Specfically this one, 
ExpiredToken | The provided token has expired. | 400 Bad Request | Client
-- | -- | -- | --

Use case below.

**How to reproduce it (as minimally and precisely as possible)**:
We have a multi cloud provider setup, where one cloud provider is IBM and the other is AWS. We have prometheus instances in both accounts with thanos sidecars with the aim of uploading them to AWS S3. 

For the AWS account we can rely on instance profile credentials, but for the one in IBM we can't. Using access/secret keys is not ideal for us since they have to be rotated and are generally a poorer choice. We decided to come up with a solution where we would leverage [Hashicorp Vault](https://www.vaultproject.io/). The architecture then becomes like this:

1. We would create a role in Vault which will generate AWS credentials that are rotated automatically by vault. 
2. A [Vault agent ](https://www.vaultproject.io/docs/agent) is configured alongside every sidecar in IBM. This agent continuously updates and rotates the keys - it does this in a way which writes out the credentials to a 'sink'. So e.g, in our case it's `/home/prometheus/.aws/credentials`. 
3. Thanos-sidecar picks up the credentials successfully. All this is working. 

This is where our setup starts to fail: 
--------
4. Eventually since those credentials only last 1 hour, they expire. Vault agent in this time would have automatically written out new credentials to `/home/prometheus/.aws/credentials` again, but `thanos-sidecar` does not reinitialise the client, so spends the rest of the time attempting to use old credentials. So it never is able to successfully upload blocks until it is restarted, at which point it will be good for 1 hour again. 

```
Sep 25 03:34:22 prometheus-grafana-staging-ibm-sjc4-us thanos-sidecar[24113]: level=warn ts=2020-09-25T03:34:22.805038929Z caller=sidecar.go:285 err="check exists: stat s3 object: 400 Bad Request" uploaded=0
Sep 25 03:34:52 prometheus-grafana-staging-ibm-sjc4-us thanos-sidecar[24113]: level=warn ts=2020-09-25T03:34:52.815605645Z caller=sidecar.go:285 err="check exists: stat s3 object: 400 Bad Request" uploaded=0
Sep 25 03:35:22 prometheus-grafana-staging-ibm-sjc4-us thanos-sidecar[24113]: level=warn ts=2020-09-25T03:35:22.836255488Z caller=sidecar.go:285 err="check exists: stat s3 object: 400 Bad Request" uploaded=0
```

I'm no go programmer, but digging through the code:
- Thanos uses minio. It uses a credentials chain as referenced in both the docs and the code here: 
https://github.com/thanos-io/thanos/blob/master/pkg/objstore/s3/s3.go#L184

```
chain = []credentials.Provider{
			&credentials.EnvAWS{},
			&credentials.FileAWSCredentials{},
			&credentials.IAM{
				Client: &http.Client{
					Transport: http.DefaultTransport,
				},
			},
```
- Minio supports the concept of expiring credentials, but that is only relevant to the STS generated ones. The file and environment credentials are only ever retrieved once, and never reloaded again. For example:
https://github.com/minio/minio-go/blob/v7.0.0/pkg/credentials/file_aws_credentials.go#L104
https://github.com/minio/minio-go/blob/v7.0.0/pkg/credentials/env_aws.go#L70
```
func (p *FileAWSCredentials) IsExpired() bool {
	return !p.retrieved
}
```
- Thanos at the moment just uses a single client throughout the lifetime of the sidecar. 
https://github.com/thanos-io/thanos/blob/9d638e92f318b777795e819edd444f3c74d45149/cmd/thanos/sidecar.go#L271

I'm not a go programmer so unsure if I understood the code properly but that's what I arrived at. I'm wondering if there are any thoughts on the feasibility of adding support for reinitialising the client when there's a 400 expired token? It would be AWS only so probably the change needs to happen in https://github.com/thanos-io/thanos/blob/master/pkg/objstore/s3/s3.go. 

Appreciate any feedback. Thanks!

**Comment by kakkoyun** [comment]
Hello @juiceblender, has this created any issues? Is this still wanted?

**Comment by juiceblender** [comment]
Hello kakkoyun, it would still be ideal if it came but for now we're manually rolling our keys.

**Comment by tkottary** [comment]
Are there any plans to fix this
