### ISSUE TITLE
support for multiple query-frontend.downstream-url 

### ISSUE THREAD

**Issue by jbianquetti-nami** [thanos-io/thanos#3227]
We want to use a frontend instance to aggregate query data from several thanos deployments on several clusters. 
To do so   `query-frontend.downstream-url` must support multiple definitions.  Any plan on this?

**Comment by bwplotka** [comment]
Hey, Query-frontend never aggregates data. Querier is for this purpose, so you would need to deploy Querier behind query-frontend in that place (or multiple those for HA). (: 

Hope this makes sense (:
