### ISSUE TITLE
Thanos Querier: Null Metrics

### ISSUE THREAD

**Issue by soniasingla** [thanos-io/thanos#3237]
Steps to reproduce: Visit https://katacoda.com/soniasingla/courses/thanos/2-lts 

https://cloud-native.slack.com/files/U0140KGTR5K/F01BUHSRUKB/screen_recording_2020-09-27_at_3.03.41_am.mov

This screen recording shows that there is a bug in the Thanos Querier because of which we can't see a dropdown menu with all the metric names.

Error found on console:

`pageConfig.allMetrics is null`

**Comment by soniasingla** [comment]
CC: @prmsrswt 😇

**Comment by yeya24** [comment]
I don't think this is a bug. It seems just an issue of your setup. Please make sure that store APIs are correctly registered in the querier and their status is `UP`.
