### ISSUE TITLE
Onboarding Development Documentation

### ISSUE THREAD

**Issue by yashrsharma44** [thanos-io/thanos#3250]
Currently, Thanos contains a nice contributing tab with details about working with the codebase - [link](https://thanos.io/tip/contributing/contributing.md/)

However, for developer-specific resources, I haven't found a concise page for it. 

For example, we had a lot of **_Community Bridge/GSoC students_** who worked on their project, and have some notes/blogs/docs that they wrote or referred while developing. Those are pretty useful, and if we can have a page which contains a one-stop resource for a specific component of **_(Thanos - UI / Backend)_**, that would be quite helpful for the new contributors to dive into a specific component and use the resources, instead of every new contributor compiling a list of resources, every time they dive into the details of the codebase.

This seems like a useful addition, so I would love some discussions about this, whether we want this or not, and if yes, then what are the things that we would like to add into.

cc @prmsrswt @Harshitha1234 @soniasingla @thisisobate @khyatisoneji 
I would also love suggestions from the new contributors, specifically any resources which would have made easier for them to get started @daksh-sagar @aribalam

**Comment by yashrsharma44** [comment]
A good example of how this could be useful is - [link](https://github.com/prometheus/prometheus/issues/7459)
TSDB contains very little resources to get started. However, many people have worked on it, and they were happy to share their experiences and understanding, and this is really helpful for new contributors to get started working on that component.

**Comment by thisisobate** [comment]
I think it's a very good approach for us to document our learnings and share directly on the website. I guess it's something similar to the Dev onboarding doc we planned to do earlier.

For us to achieve this, it's best we document our learnings in one central Google docs before considering pushing to GitHub. Reason is because having an unfinished work on website wouldn't look nice. 

As for the Google docs, we could use @khyatisoneji template and improve on it.

**Comment by kakkoyun** [comment]
Still valid and need help 🤗  I'm calling the Avengers(old mentees) to help! @yashrsharma44 @prmsrswt @Harshitha1234 @soniasingla @thisisobate @khyatisoneji and many others (you guys are too many 😅 ).

**Comment by yashrsharma44** [comment]
I might take a shot this weekend 😛

**Comment by thisisobate** [comment]
Same here

**Comment by soniasingla** [comment]
Yep, will take a look this weekend, probably!

**Comment by yashrsharma44** [comment]
I have added a PR for having a placeholder for adding docs for the development and specific details for each components - https://github.com/thanos-io/thanos/pull/3780

**Comment by Biswajitghosh98** [comment]
Hi @yashrsharma44 
I did spend some time in the last few weeks understanding the codebase. Let me know if you need help in the compactor and/or store components specifically :)

**Comment by thisisobate** [comment]
So I took a look at the placeholder PR @yashrsharma44 created which is looking great.
I figured the easiest way we can collaborate on this is probably via Google docs.

Just like I mentioned above, I think it would be nice if we continue with @khyatisoneji work.
Link to the docs [here](https://docs.google.com/document/d/1hluKPDKsSdOqcCpOnzr7-4PxLnUtrCl5d4-TVGch_D4/edit?usp=sharing).

I also figured the dev onboarding is mainly focused on the Thanos core of which I don't really have much expertise.

Regardless, I did some refactoring to the google docs above. Kindly take a look and add some ideas @soniasingla @yashrsharma44 @prmsrswt @Harshitha1234 @Oghenebrume50

**Comment by yashrsharma44** [comment]
Nice, I think we can ask @kakkoyun @bwplotka to comment on the docs, and once we agree on the content and structure, I will make a PR for the same - https://docs.google.com/document/d/1hluKPDKsSdOqcCpOnzr7-4PxLnUtrCl5d4-TVGch_D4/edit#

**Comment by yashrsharma44** [comment]
> Hi @yashrsharma44
I did spend some time in the last few weeks understanding the codebase. Let me know if you need help in the compactor and/or store components specifically :)

Feel free to add in details about the Compactor/Store that you have in the docs, would be nice to have it before we merge it as a PR :100:

**Comment by yashrsharma44** [comment]
This issue is solved through this PR #3882
