### ISSUE TITLE
receive: v0.16.0-rc.0 regression. Memory leak.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3265]
![image](https://user-images.githubusercontent.com/6950331/94788618-bda6c600-03cb-11eb-93ea-9582ac6375e7.png)

Fun! :upside_down_face:

**Comment by bwplotka** [comment]
Root cause is visible on profiles and indicates https://github.com/thanos-io/thanos/pull/2783

![image](https://user-images.githubusercontent.com/6950331/94916400-878a4480-04a6-11eb-97e4-cfe5a7cd5f4a.png)

It's snappy and recv gRPC parser holding memory. Either something is wrong with out manual "yolo" serializing / deserializing or bytes from gRPC serialized are still referenced somewhere and never cleaned during those snappy and parsing operations. ): 

```
File: thanos
Type: inuse_space
Time: Oct 1, 2020 at 11:41am (UTC)
Showing nodes accounting for 8247.98MB, 100% of 8247.98MB total
---------------------------------------------------------+------------
flat flat% sum% cum cum% calls calls% + context
---------------------------------------------------------+------------
3021.97MB 100% | google.golang.org/grpc.recvAndDecompress /go/pkg/mod/google.golang.org/grpc@v1.29.1/rpc_util.go:641
3021.97MB 36.64% 36.64% 3021.97MB 36.64% | google.golang.org/grpc.(*parser).recvMsg /go/pkg/mod/google.golang.org/grpc@v1.29.1/rpc_util.go:528
---------------------------------------------------------+------------
2833.95MB 100% | github.com/thanos-io/thanos/pkg/receive.(*Handler).receiveHTTP /go/src/github.com/thanos-io/thanos/pkg/receive/handler.go:291
2833.95MB 34.36% 71.00% 2833.95MB 34.36% | github.com/golang/snappy.Decode /go/pkg/mod/github.com/golang/snappy@v0.0.1/decode.go:63
---------------------------------------------------------+------------
```

I reverted just this commit and here we are: 
![image](https://user-images.githubusercontent.com/6950331/94916241-3aa66e00-04a6-11eb-9311-9b4b84502234.png)

**Comment by bwplotka** [comment]
Wonder @pstibrany and @pracucci if you seen something like this on your yoloString impl, but I most likely overdid something (: 

cc @brancz

**Comment by bwplotka** [comment]
I hoped I can escale without full blown benchmarks on Series gRPC + Serializing, but not really ;p

**Comment by pstibrany** [comment]
> Wonder @pstibrany and @pracucci if you seen something like this on your yoloString impl, but I most likely overdid something (:

I don't think so, but it's something to keep an eye on.

**Comment by bwplotka** [comment]
Fixed on release branch: https://github.com/thanos-io/thanos/pull/3327
