### ISSUE TITLE
Website: community and contributing links broken in landing page

### ISSUE THREAD

**Issue by thisisobate** [thanos-io/thanos#3270]
**What happened**:
community and contributing links broken in thanos.io

**Comment by Marymota** [comment]
Hi! I would like to be assigned to this issue.

**Comment by thisisobate** [comment]
Hi @Marymota,
Please feel free to jump on this issue. 
If you need any help or clarification, do let me know!

**Comment by thisisobate** [comment]
Fixed #3272
