### ISSUE TITLE
Thanos Store default data retention in local disk

### ISSUE THREAD

**Issue by heartTorres** [thanos-io/thanos#3271]
**Thanos, Prometheus and Golang version used**:
Thanos v0.15.0, rancher/prom-prometheus v2.17.2

**Object Storage Provider**:
AWS S3
**What happened**:
I am using Thanos Receiver, Rancher Prometheus and Thanos Store.
We set this config for the data retention. 
Prometheus = 12 hour 
Thanos Receiver = 3 days
Thanos Store = ?
**What you expected to happen**:
Is it possible to have a data retention as well in thanos store local disk? (the same way in Thanos Receiver and Thanos Prometheus). The current behavior right now, is that it looks like unlimited as it sychronize its blocks with the data S3 storage.
We only provisioned 5Gi for  Thanos Store. There is a chance that the volume disk might be full when months of data are already fetched. We would like to have only a data retention of let us say 5d only and automatically be removed in the local disk. I am not sure, but I cannot find this in the documentation or might be I have misunderstood the design? https://thanos.io/tip/components/store.md/#store

Please help.
**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by yeya24** [comment]
Thanos Store's local data dir only downloads the index-header of blocks in your object storage. It doesn't download the whole TSDB blocks so those data should be relatively small compared to the whole blocks. You can find more in the document https://thanos.io/tip/components/store.md/#store. Hope this helps.

```
It keeps a small amount of information about all remote blocks on local disk and keeps it in sync with the bucket.

In general, about 1MB of local disk space is required per TSDB block stored in the object storage bucket.
```

**Comment by heartTorres** [comment]
> Thanos Store's local data dir only downloads the index-header of blocks in your object storage. It doesn't download the whole TSDB blocks so those data should be relatively small compared to the whole blocks. You can find more in the document https://thanos.io/tip/components/store.md/#store. Hope this helps.
> 
> ```
> It keeps a small amount of information about all remote blocks on local disk and keeps it in sync with the bucket.
> 
> In general, about 1MB of local disk space is required per TSDB block stored in the object storage bucket.
> ```

Hi, Thanks for the reply. Yes they are only small. We only set around 1Gi for pvc to our thanos-store. Even if they are small, these header data will eventually consume the local disk (almost full). Does it mean, we need is just to delete them manually or create a job that will delete this index-header blocks.

**Comment by yeya24** [comment]
The index headers are fetched by the store periodically so if you delete them, they will be downloaded again.
I would say it is better to use a larger PVC.

**Comment by heartTorres** [comment]
> The index headers are fetched by the store periodically so if you delete them, they will be downloaded again.
> I would say it is better to use a larger PVC.

Alright. I will probably raise this in our meeting. I am planning to just to control the lifecycle in S3 to delete all data beyond 3 months. Thanks for the reply.
