### ISSUE TITLE
Broken Links on Contributing Page

### ISSUE THREAD

**Issue by kartikx** [thanos-io/thanos#3283]
This issue is similar to #3270, however that issue has since been closed, and I wasn't sure whether to reply to it. There are many broken links on [Thanos/Contributing](https://thanos.io/tip/contributing/contributing.md/). The ones I've found till now are:
* The Reporting a Vulnerability Link in [Feedback / Issues](https://thanos.io/tip/contributing/contributing.md/#feedback--issues)
* The CLI tools Link in [Components Naming](https://thanos.io/tip/contributing/contributing.md/#components-naming).
* The Proposal Link in [Adding New Features / Components](https://thanos.io/tip/contributing/contributing.md/#adding-new-features--components).

I would love to work on fixing this, if allowed to do so. I'll add more links to the above list as I find them.

**Comment by kakkoyun** [comment]
@kartikx Thanks a lot for reporting this. Please go ahead. We would appreciate the help.

**Comment by kakkoyun** [comment]
@kartikx FYI This could already be fixed https://github.com/thanos-io/thanos/pull/3272

**Comment by kartikx** [comment]
@kakkoyun Yes, I did take a look at that PR, it fixes the links on the Landing Page. The ones I've reported are on the Contributing Page, which require fixing `CONTRIBUTING.md`. I didn't notice changes to `CONTRIBUTING.md` in the list of Files changed, please correct me if wrong.
Just to clarify about the desired output, I notice that the `CODE_OF_CONDUCT` link on [CONTRIBUTING](https://thanos.io/tip/contributing/contributing.md/#contributing) works fine. It directs to the `CODE_OF_CONDUCT.md` file in the Thanos GitHub repo. Is that the desired output for the links I've mentioned as well? For eg. the Feedback/Issues should direct to [Security.md](https://github.com/thanos-io/thanos/blob/master/SECURITY.md)
