### ISSUE TITLE
receiver: 20% of CPU time is spent on GC

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3290]
![image](https://user-images.githubusercontent.com/6950331/95347494-d83ddb00-08b4-11eb-87c7-4887055ebcf9.png)

Looks like we could optimize this path a bit, probably pool more? Or use less pointers in our data structures. :thinking:

**Comment by brancz** [comment]
I wouldn't call that a bug, but yes agreed there seems to be room for optimizing.
