### ISSUE TITLE
Minio v6 -> v7 breaks for Ceph due to ListObjectsV2

### ISSUE THREAD

**Issue by sevagh** [thanos-io/thanos#3291]
Hello. When upgrading from Thanos 0.14.0 to 0.16.0-rc.0 (and 0.15.0 should have the same issue), this breaks with Ceph.

This is due to the minio client upgrade from v6 to v7: https://github.com/thanos-io/thanos/pull/2970/files

This breaks for me because the version of Ceph we operate has trouble with the ListObjectsV2 operation (if you look this up it's a known issue for minio/Ceph) - e.g. https://github.com/minio/minio-go/issues/1130

I can hotfix my own local clone of Thanos to add this:
```
diff --git a/pkg/objstore/s3/s3.go b/pkg/objstore/s3/s3.go
index 923a4253..26cfcc5d 100644
--- a/pkg/objstore/s3/s3.go
+++ b/pkg/objstore/s3/s3.go
@@ -309,6 +309,7 @@ func (b *Bucket) Iter(ctx context.Context, dir string, f func(string) error) err
        opts := minio.ListObjectsOptions{
                Prefix:    dir,
                Recursive: false,
+               UseV1: true,
        }
```
Maybe Ceph users are a small population that this doesn't matter.

**Comment by sevagh** [comment]
As for any practical suggestions - maybe allow a "UseV1 = true" config key in the AWS bucket config file?

**Comment by zygiss** [comment]
We're also running on Ceph and are affected by this.

I like the idea to have a bucket config option to revert to V1 of the ListObjects API in the interim, while we upgrade our Ceph installs.

**Comment by sevagh** [comment]
I made a PR for this.

**Comment by GiedriusS** [comment]
The PR has been merged so closing this! Thank you for this fix.
