### ISSUE TITLE
Broken Footer Links in Website

### ISSUE THREAD

**Issue by kartikx** [thanos-io/thanos#3293]
I found a related issue: #3081 , but thought to create a new issue to explain it better.

On every doc page there's a footer link asking for help to improve the Thanos documentation. Clicking on the link is supposed to lead to an Edit version of the file in GitHub. For eg. on the Thanos Quick Tutorial, this link would be: `https://github.com/thanos-io/thanos/edit/master/docs/thanos/quick-tutorial.md`.

The issue is that the generation of the footer is written using a `contentpreprocess.sh` script, which is coded to redirect to `/master/docs/${filename}`. Hence, the links will work fine for whatever pages are present in the `/docs` folder. However any other page (like Contributing, Code of Conduct, Quick Tutorial etc.) will 404.

**Comment by candlerb** [comment]
I found some more broken links:

* Go to thanos.io, click "Getting Started", click "Quick Tutorial".
* This brings you to https://thanos.io/tip/thanos/quick-tutorial.md/
* Now click on any of the links "Sidecar", "Querier/Query", "Store Gateway", "Compactor", "Ruler/Rule", which link to respectively:
    * https://thanos.io/tip/thanos/components/sidecar.md
    * https://thanos.io/tip/thanos/components/query.md
    * https://thanos.io/tip/thanos/components/store.md
    * https://thanos.io/tip/thanos/components/compact.md
    * https://thanos.io/tip/thanos/components/rule.md
* All of those give 404 errors. Adding a trailing slash doesn't help.

I believe the links should be like https://thanos.io/tip/thanos/quick-tutorial.md/#sidecarcomponentssidecarmd

**Comment by candlerb** [comment]
Another one: at either https://thanos.io/tip/components/sidecar.md/ or https://thanos.io/tip/components/receive.md/, click on the link "See *external labels* docs". This links to https://thanos.io/tip/storage.md#external-labels which gives a 404.

I couldn't find the correct link target which gives an overview of external labels.

**Comment by candlerb** [comment]
At https://thanos.io/tip/thanos/quick-tutorial.md/, under "See those components on this diagram:", is a broken image link.

![image](https://user-images.githubusercontent.com/44789/100437562-d4e6f480-3098-11eb-8bd0-ec478b7a3404.png)

It points to `../img/arch.jpg`

I don't know what the correct link is under thanos.io, but I found it in git as https://github.com/thanos-io/thanos/blob/master/docs/img/arch.jpg and https://raw.githubusercontent.com/thanos-io/thanos/master/docs/img/arch.jpg

**Comment by candlerb** [comment]
Dear bot, these broken links are all still broken.

**Comment by bwplotka** [comment]
Thanks for looking into this. This is a known issue that we slowly work on with automation explained [here](https://github.com/thanos-io/thanos/issues/3081). Let's close this as a duplicate 🤗 Feel free to help on the linked issue, to get things done!

**Comment by bwplotka** [comment]
Problem is that some docs are referenced as `.md` page, some as `/`
