### ISSUE TITLE
ui: Enable Status pages on the React UI for All components

### ISSUE THREAD

**Issue by onprem** [thanos-io/thanos#3297]
There are two pages `Runtime and Build Information` and `CLI Flags` in the React UI which makes sense for all Thanos components. Currently, they are only shown in the navigation bar for Thanos Querier. We want to show links to these pages in the Navbar for all components.

**Comment by Oghenebrume50** [comment]
Looking into this

**Comment by khyatisoneji** [comment]
Hey, @Oghenebrume50 are you still working on this issue?
If not I would love to take this one
