### ISSUE TITLE
compact: Stops processing on full disk

### ISSUE THREAD

**Issue by anas-aso** [thanos-io/thanos#3305]
**Thanos, Prometheus and Golang version used**:
thanosio/thanos:v0.15.0
prom/prometheus:v2.20.0

**Object Storage Provider**:
GCS

**What happened**:
Once the disk usage of Thanos Compact reached 100%, it aborted with the following error : 
```
error executing compaction: compaction: group 0@12005178724967806318: gather index issues for block /var/thanos/compact/compact/0@12005178724967806318/01EK513MWM7CBTBGP4TXXHXWWJ: open index file: try lock file: open /var/thanos/compact/compact/0@12005178724967806318/01EK513MWM7CBTBGP4TXXHXWWJ/index: no such file or directory
```
After that it deleted the new block's directory (almost) immediately and stopped processing any other blocks.
The graph below shows the disk usage ratio (used / capacity)
<img width="757" alt="Screenshot 2020-10-12 at 5 17 41 PM" src="https://user-images.githubusercontent.com/16538065/95763606-8aa7e080-0caf-11eb-837b-d19296f43f3b.png">
As a result, the high disk usage stayed unnoticed (since it went down to 50%) and compaction stopped working, but the process (thanos compact) was still running.

**What you expected to happen**:
Anything that would make such issue noticeable. For example:
- Thanos Compact process crashing
and/or
- Disk Usage stays at 100%

**How to reproduce it (as minimally and precisely as possible)**:
Provide Thanos Compact with just enough disk for it to download all non-compacted blocks and start creating the compacted one.
This are the flags I use:
```
      --wait
      --log.format=json
      --data-dir=/var/thanos/compact
      --objstore.config-file=/thanos_config.yaml
      --debug.max-compaction-level=4
      --downsampling.disable
      --delete-delay=0s
      --retention.resolution-1h=3d
      --retention.resolution-5m=3d
      --retention.resolution-raw=3d
```

Otherwise everything else is just a standard setup of Thanos.

**Full logs to relevant components**:
see above

**Anything else we need to know**:

**Comment by anas-aso** [comment]
I have hit the same issue again. Looking into the code, I found this hidden flag : https://github.com/thanos-io/thanos/blob/c534b6d4a2f9fdac572f3126adfc1fb3e1b17147/cmd/thanos/compact.go#L516 combining it with the metric `thanos_compactor_halted` did the job for me.

@bwplotka any idea why is this flag hidden ? I think it's useful to make issue with compaction more visible.

**Comment by bwplotka** [comment]
How you used this flag exactly? What do you expect?

You disabled halt on error? It helped you, but in most cases, you should run Compactor with persistent disk if you can, as we cache metadata and stuff, Restarting would not help then. Also if you hit the issue right now, you will see an issue soon as well - it got full for some reason -> most likely dataset you are compacting is huge. (:

**Comment by anas-aso** [comment]
@bwplotka by setting this one up, compact would restart on critical errors (full disk in my case) as a result `thanos_compactor_halted` will be set to 1 which I can alert on.
I know there is another metric for compaction failure, but I want to define an alert only if it will cause troubles (in the case of this issue compaction didn't run for more than a week).

I already run compact with persistent volume (as you've guessed the dataset I have is huge).

> if you hit the issue right now, you will see an issue soon as well 

I am setting another hidden flag `--debug.max-compaction-level=4` to make sure the biggest blocks (14 days ones) stay at a reasonable and predictable size.

Do you have any suggestion to solve this disk issue ? It's a little bit annoying that a huge disk is attached to Compact while it's usage is very low most of the time (I notice the disk usage peak every 2 week if I am not mistaken).
