### ISSUE TITLE
Block viewer: Show blocks marked for deletion

### ISSUE THREAD

**Issue by roidelapluie** [thanos-io/thanos#3308]
**Thanos, Prometheus and Golang version used**:

**Object Storage Provider**:

s3

**What happened**:

I am looking at the blocks viewer and I see overlapping blocks

![thanos2](https://user-images.githubusercontent.com/291750/95837679-27668e80-0d41-11eb-8a96-ebf05f5acabc.png)

**What you expected to happen**:

Blocks marked for deletion marked in a special way

![thanos](https://user-images.githubusercontent.com/291750/95837711-32212380-0d41-11eb-9ab8-19b2edd3be0d.png)

**Comment by kakkoyun** [comment]
@Shini31 Could this be the same issue as #3307?

**Comment by kakkoyun** [comment]
@prmsrswt Any input on this?

**Comment by prmsrswt** [comment]
They are in different rows so they are not necessarily overlapping here. Each unique downsampling resolution - compaction level gets its own row.

Although we are currently not differentiating blocks which are marked for deletions but we have that in our roadmap and hopefully will be implemented during this community bridge period.

**Comment by roidelapluie** [comment]
What I mean is to find blicks that have a deletion-mark.json file.

**Comment by Shini31** [comment]
> @Shini31 Could this be the same issue as #3307?

Yes, there is.
This feature will be very helpful to determine if there is an overlap issue or not.

**Comment by Shini31** [comment]
up?

**Comment by prmsrswt** [comment]
Yeah this is on our roadmap, help wanted!

**Comment by Shini31** [comment]
Good news!
I can help for the development, but i'm available for testing

**Comment by anuraagbarde** [comment]
Hello there! I have experience with working in React, as this is marked as a good first issue how can I contribute? Thanks.

**Comment by onprem** [comment]
We can break this down in some steps:
1. Extend the blocks API endpoint to expose which blocks are marked for deletion.
    * In Thanos, blocks which are going to get deleted have a file named `deletion-mark.json`, we can use this information to return an additional boolean in the API response, `markedForDeletion: true | false`.
2. Use this information in the React UI to visually distinguish the blocks which are marked for deletion.

The first step will require some Go knowledge, as our backend is written in Go, the second step, however, is purely React work.

**Comment by anuraagbarde** [comment]
Ok, I will look into this, thanks for the info.

**Comment by Shini31** [comment]
Up

**Comment by Shini31** [comment]
Up

**Comment by yeya24** [comment]
This is still nice to have.

**Comment by Shini31** [comment]
Up

**Comment by keremgocen** [comment]
Hello, is anyone working on this? I'm looking for something to contribute.

**Comment by keremgocen** [comment]
Up!
