### ISSUE TITLE
Is there any data sync delay between Thanos Receiver to S3 bucket

### ISSUE THREAD

**Issue by anoop2503** [thanos-io/thanos#3317]
This is a question regarding Thanos Receiver. 

Is there any data upload/sync delay between Thanos Receiver to S3 bucket (just as the sidecar is syncing data to S3 bucket in every 2 hours).

**Comment by bwplotka** [comment]
There is exactly the same delay as the Prom + sidecar. Thanos Receive is nothing more than just trimmed down Prometheus (just TSDB receiving data) (:

**Comment by bwplotka** [comment]
The same code for syncing and uploading is used.

**Comment by LordMilan** [comment]
bwplotka please dont give wrong info..i just verified it and its not 2 hours..its being synced in around 1 hr time for me

**Comment by LordMilan** [comment]
bwplotka please dont give wrong info..i just verified it and its not 2 hours..its being synced in around 1 hr time for me
