### ISSUE TITLE
i have 2 clusters in and i installed thanos in one server how can call remote server thanos sidecar

### ISSUE THREAD

**Issue by rameshkalluri** [thanos-io/thanos#3328]
**Thanos, Prometheus and Golang version used**:

**Object Storage Provider**:

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by GiedriusS** [comment]
What do you mean exactly? I suppose the answer is that you need the `--store` option on Thanos Query to make it "know" about Thanos Sidecar. Could you please elaborate on what have you tried, what happened, and what did you expect? (:
