### ISSUE TITLE
compact: need options to disable group blocks

### ISSUE THREAD

**Issue by diemus** [thanos-io/thanos#3329]
thanos version : v0.15.0

the compact often cause a high io on disk, I want disable the compact process. the only reason I need this component is to remove outdate blocks in s3. so perhaps we could add an option

**Comment by Sayrus** [comment]
I do think using `--debug.max-compaction-level=1` will disable grouping as all blocks are already level 1.

**Comment by diemus** [comment]
thanks, didn't know there is undocumented flag. i will try it. is there a way to see all undocumented flags?

**Comment by Sayrus** [comment]
I am not aware of any way to display them (as provided by Kingpin).
However, they can be found in the code as they all use the `.Hidden()` clause.

**Comment by diemus** [comment]
I can still see logs about compaction. like 

```
level=info ts=2020-10-19T01:57:01.838921566Z caller=compact.go:694 group="0@{thanos=\"rule\"}" groupKey=0@10172254955404798962 msg="compaction available and planned; downloading blocks" plan="[/home/work/data/compact/0@10172254955404798962/01EK3BWSP6K5JZGK3J3NNKB4G3 /home/work/data/compact/0@10172254955404798962/01EK3FANA7Z59HDZMM80Z0M2TQ]"
level=info ts=2020-10-19T01:57:19.797235664Z caller=compact.go:748 group="0@{thanos=\"rule\"}" groupKey=0@10172254955404798962 msg="downloaded and verified blocks; compacting blocks" plan="[/home/work/data/compact/0@10172254955404798962/01EK3BWSP6K5JZGK3J3NNKB4G3 /home/work/data/compact/0@10172254955404798962/01EK3FANA7Z59HDZMM80Z0M2TQ]" duration=17.958258229s
```

is there a way to stop downloading them?

**Comment by bwplotka** [comment]
To see all of the hidden flags you need to look at the code: https://github.com/thanos-io/thanos/blob/03b6991949601d82fe17c4fbd2a658f678f0a6a5/cmd/thanos/compact.go#L480

BTW why disabling compaction? Thanos system without compactons (similar to Prometheus) will not work well for longer retention.

**Comment by diemus** [comment]
the compact frequently download and upload blocks which cause an high disk io. this may affect other pods on the same host. I want disabling compaction, just use the compact to clean blocks in S3, since our retention is not very long.

this may not be a universal demand, if the numbers of blocks grows more and we need a longer retention,  I might have to find a special host to run this service.
