### ISSUE TITLE
query: many "update of store node failed" messages. But the store is always healthy.

### ISSUE THREAD

**Issue by ncastrocosta** [thanos-io/thanos#3332]
**Thanos, Prometheus and Golang version used**:
Thanos: 0.14.0
Prometheus: 2.20.1
Golang: go1.14.2

**Object Storage Provider**: S3

**What happened**:

When I query via Query component, I receive this warning: **receive series from Addr: 172.21.182.246:10901 LabelSets: [name:"monitor" value:"prometheus" ,name:"replica" value:"prometheus-0" ][name:"replica" value:"thanos-rule" ,name:"ruler_monitor" value:"prometheus" ] Mint: 1601056800000 Maxt: 1602871200000: rpc error: code = Canceled desc = grpc: the client connection is closing**

However, sometimes, for the same query, it works like expected. But a lot of times I receive this warning.

Could this be only a network problem? Ou could it be something else?

**What you expected to happen**:

I agree network issues may occur. But the number of times it happens is too high IMO - sometimes, many fails in sequence. So, I expected no warnings like that in that frequency.

I did some tests executing the query directly to the gRPC endpoint, using [this](https://github.com/thanos-io/thanos/blob/master/scripts/insecure_grpcurl_series.sh) script. So, when I executed against the Query component, sometimes it failed, sometimes it worked, just like using the browser. But when I executed against the Store component, it **never** failed, not once. So, because of that, I don't believe it would be a network issue. But I also have no idea what could it be.

**How to reproduce it (as minimally and precisely as possible)**:

Via the Query browser or using [this](https://github.com/thanos-io/thanos/blob/master/scripts/insecure_grpcurl_series.sh) script.

**Full logs to relevant components**:
| Query logs |
|---|
| 2020-10-16T19:25:01.590302174Z level=warn ts=2020-10-16T19:25:01.59014422Z caller=storeset.go:487 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from 172.21.182.246:10901: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=172.21.182.246:10901
2020-10-16T19:25:01.590578778Z level=info ts=2020-10-16T19:25:01.590509774Z caller=storeset.go:388 component=storeset msg="removing store because it's unhealthy or does not exist" address=172.21.182.246:10901 extLset="{monitor=\"prometheus\", replica=\"prometheus-0\"},{replica=\"thanos-rule\", ruler_monitor=\"prometheus\"}" |
|2020-10-16T19:25:01.591103508Z level=warn ts=2020-10-16T19:25:01.590974366Z caller=proxy.go:456 err="receive series from Addr: 172.21.182.246:10901 LabelSets: [name:\"monitor\" value:\"prometheus\" ,name:\"replica\" value:\"prometheus-0\" ][name:\"replica\" value:\"thanos-rule\" ,name:\"ruler_monitor\" value:\"prometheus\" ] Mint: 1601056800000 Maxt: 1602871200000: rpc error: code = Canceled desc = grpc: the client connection is closing" msg="returning partial response" |
|2020-10-16T19:25:03.09060154Z level=info ts=2020-10-16T19:25:03.090457108Z caller=storeset.go:417 component=storeset msg="adding new storeAPI to query storeset" address=172.21.182.246:10901 extLset="{monitor=\"prometheus\", replica=\"prometheus-0\"},{replica=\"thanos-rule\", ruler_monitor=\"prometheus\"}" |

Looking at the logs, It's strange to me the short time Query fails to update of store node and to add again to the storeset. And all the time the logs are like this.

Also, I never spotted the Store component presenting any failure status.

**Anything else we need to know**:

In this scenario, the Query component has only the StoreAPI of the Store component.

Thanks!

**Comment by isaccavalcante** [comment]
I'm also having the same problem

**Comment by ClumsyPotato** [comment]
Me too, some of my dasboards are pretty unstable because of this.
Using thanos 0.16.0-rc.0

**Comment by ncastrocosta** [comment]
@kakkoyun I noticed I was using very low resource limits for my kubernetes containers. When I increased the limits, the errors vanished. I also noticed that I used to have some timeouts, and I fixed that increased nginx timeouts for the query.
