### ISSUE TITLE
receive: Every restart receive flushes and uploads, potentially same data.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3335]
This is not biggy with vertical compaction enabled but sounds inefficient. Can we improve this?

Ideally, full flush and close should happen only on a scale down logic (so triggered from outside). In fact, the final shutdown should only happen when the block is available on store GW as well. :thinking:  cc @brancz @squat

**Comment by brancz** [comment]
Do we have data to back this up? As far as I know, the flush logic even deletes the WAL after it flushed and uploaded.
