### ISSUE TITLE
receive: Add e2e test for multi-tenancy.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3336]
It would be awesome to add extra test for writing data for 2 different tenants into single receive instance. This path is currently missing in our e2e tests: https://github.com/thanos-io/thanos/blob/066150a6d1e2df3c2398f76ee91a7b0f2c0f80ae/test/e2e/receive_test.go#L20

Help wanted!

**Comment by Chans321** [comment]
Can I take up this issue?

**Comment by kakkoyun** [comment]
@Chans321 Of course, go ahead, please :) Thanks

**Comment by Chans321** [comment]
#3474 resolves this issue :)

**Comment by bwplotka** [comment]
Wow, amazing! :muscle: 

Thanks!
