### ISSUE TITLE
Problem with chunk-pool-size and store panics in pkg/store.(*bucketChunkReader).loadChunks

### ISSUE THREAD

**Issue by sevagh** [thanos-io/thanos#3339]
Hello - since upgrading from Thanos 0.14.0 to 0.16.0-rc0, I started having my Store component fail to load blocks because of https://github.com/thanos-io/thanos/issues/1179

I adjusted chunk-pool-size up from 2GB to 8GB, 16GB, and now 50GB. On 50GB, I get a panic and the store crashes:
```
Oct 19 07:35:45 sv3-thanos4 thanos[47253]: panic: runtime error: slice bounds out of range [23301:14480]
Oct 19 07:35:45 sv3-thanos4 thanos[47253]: goroutine 2092987 [running]:
Oct 19 07:35:45 sv3-thanos4 thanos[47253]: github.com/thanos-io/thanos/pkg/store.(*bucketChunkReader).loadChunks(0xdffd9ddc20, 0x1f7c1c0, 0xe1eaa29040, 0xe1eaa0bca0, 0x5, 0x8, 0x6, 0xde5b01a0de402fe, 0x0, 0x0)
Oct 19 07:35:45 sv3-thanos4 thanos[47253]:         thanos/pkg/store/bucket.go:2099 +0xb87
Oct 19 07:35:45 sv3-thanos4 thanos[47253]: github.com/thanos-io/thanos/pkg/store.(*bucketChunkReader).preload.func3(0x0, 0x1ce13c0)
Oct 19 07:35:45 sv3-thanos4 thanos[47253]:         thanos/pkg/store/bucket.go:2066 +0x9f
Oct 19 07:35:45 sv3-thanos4 thanos[47253]: golang.org/x/sync/errgroup.(*Group).Go.func1(0xe1eaa25980, 0xe1eaa2f800)
Oct 19 07:35:45 sv3-thanos4 thanos[47253]:         go/pkg/mod/golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:57 +0x59
Oct 19 07:35:45 sv3-thanos4 thanos[47253]: created by golang.org/x/sync/errgroup.(*Group).Go
Oct 19 07:35:45 sv3-thanos4 thanos[47253]:         go/pkg/mod/golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup
```

This is when running a promql (histogram quantile) through Thanos Query on a pretty massive timeseries (count = 17424, that's some big cardinality).

**Comment by sevagh** [comment]
Is 50GB too high to use for chunk-pool-size?

**Comment by sevagh** [comment]
I believe similar to https://github.com/thanos-io/thanos/issues/3057

Not an exact duplicate since mine is in a different function, `loadChunks`. But maybe the underlying code is the same.

**Comment by GiedriusS** [comment]
I feel like maybe this topic should be brought up at the next community meeting to discuss how to move forward as it is tricky: it's _probably_ a radosgw bug and the question is whether do we want to be extra defensive here. What about other places, then?
