### ISSUE TITLE
tools: Be able to copy blocks of data for a give time-frame from one bucket to another.

### ISSUE THREAD

**Issue by maulikjs** [thanos-io/thanos#3340]
We recently ran into a problem where some of our blocks in the main s3 bucket got corrupted. So we have had to copy all the blocks for the month of September and there was no direct way of doing it. It would be awesome if we can include the logic for the time-range selector in the replicate tool or at least be able to list all the ULID for a given time range.

**Comment by bwplotka** [comment]
SGTM, help wanted :heart:

**Comment by bwplotka** [comment]
Replicate extension OR `tools bucket ls --max -- min` to print ULIDs to copy will suffice (:

**Comment by maulikjs** [comment]
I can take this up :)

**Comment by yeya24** [comment]
I am not very sure but is this the same as https://github.com/thanos-io/thanos/pull/2979?

**Comment by bwplotka** [comment]
I think so, as long as it can copy certain blocks (: cc @OGKevin

**Comment by OGKevin** [comment]
yea #2979 indeed does this. You give it a max and min time and replicator will replicate all the blocks that are within that time range.

**Comment by OGKevin** [comment]
This can be closed as #2979 got merged 😊
