### ISSUE TITLE
docs: Link official Katacoda tutorial in quick-start

### ISSUE THREAD

**Issue by ryan-dyer-sp** [thanos-io/thanos#3343]
https://katacoda.com/bwplotka/courses/thanos/1-globalview

I just went through the tutorial and it is broken at the very beginning.  The .yml files are not files, but instead directories.  Once I deleted the directories and touched new files, I was able to proceed through the tutorial without issue.

**Comment by bwplotka** [comment]
Thanks for pointing! Will update :heart:

**Comment by bwplotka** [comment]
Interesting, it looks like it works just fine for me.

Make sure to use official link: https://katacoda.com/thanos/courses/thanos/1-globalview

**Comment by ryan-dyer-sp** [comment]
https://thanos.io/tip/thanos/quick-tutorial.md/  This points to the link I mentioned.  So perhaps the docs need to be updated to point to the official link.

**Comment by bwplotka** [comment]
Correct. Thanks (:
