### ISSUE TITLE
Implement metrics metadata API

### ISSUE THREAD

**Issue by juliusv** [thanos-io/thanos#3345]
Currently multiple UI tools (such as PromLens and Grafana) surface metric metadata (HELP + TYPE information) to the user when building queries. This is very useful, but can only work when the PromQL-compatible endpoint also implements the metric metadata API endpoint (https://prometheus.io/docs/prometheus/latest/querying/api/#querying-metric-metadata). Thanos itself does not store this information for historical metrics yet, but it would be possible to obtain current metadata from Prometheus servers via a new feature in the Thanos Sidecar + Store protocol and then aggregate them into a response to the Query client. Would this be doable or am I missing something?

**Comment by GreenRover** [comment]
+1

**Comment by bwplotka** [comment]
Hey, sorry for the lag! 

It's definitely quite easy to work to do, and something we also planned for Exemplars: https://github.com/thanos-io/thanos/issues/3435

Work that has to be done is really similar to what we did with @s-urbaniak when we enabled federated Rules APIs: https://github.com/thanos-io/thanos/commit/c733564d44745af1a023bfa5d51d6d205404dc82#diff-ae8f55a2dc006142e7688086d880b8aceaac7406e5f88243fb56215867448f3e The Rules API was the first one on top of StoreAPI so it requires more changes. From now one adding new API should be trivial.

For example Targets API is in review and close to being merged: https://github.com/thanos-io/thanos/pull/3350

It's worth noting there are ideas to improve the code and configuration aspect [a little bit but it's not blocking](https://github.com/thanos-io/thanos/issues/2600).

## Currently steps to add federated API to Querier:

Will use @2nick contribution as an example as it was perfect.
 
From very high level (you need to check PR for details)

1. Add endpoint flag e.g for targets

![image](https://user-images.githubusercontent.com/6950331/100865885-d1d07780-348f-11eb-803c-d044acb4aec9.png)

2. Add new DNS provider

![image](https://user-images.githubusercontent.com/6950331/100866457-971b0f00-3490-11eb-955f-a34b28f52263.png)

3. Extend storeset 

![image](https://user-images.githubusercontent.com/6950331/100866485-a13d0d80-3490-11eb-9550-736fc6f561ea.png)

Currently, it tells Querier what endpoints have what APIs (exemplars, Store, Target, rules, metadata etc) (: 

4. Add HTTP API to Querier 

![image](https://user-images.githubusercontent.com/6950331/100866737-02fd7780-3491-11eb-893d-891eeb6d3adc.png)

 
5. If you want to fetch something from Prometheus add client method (will be used by sidecar)

![image](https://user-images.githubusercontent.com/6950331/100866670-ea8d5d00-3490-11eb-89bb-c173493a5d16.png)

6. Add new gRPC service 

e.g https://github.com/thanos-io/thanos/blob/d9796e8133310243bb65d38b73ac028bc92e1815/pkg/targets/targetspb/rpc.proto

```

/// Targets represents API that is responsible for gathering targets and their states.
service Targets {
    /// Targets has info for all targets.
    /// Returned targets are expected to include external labels.
    rpc Targets (TargetsRequest) returns (stream TargetsResponse);
}

message TargetsRequest {
    enum State {
        ANY = 0;
        /// This will make sure strings.ToLower(.String()) will match 'active' and 'dropped' values for
        /// Prometheus HTTP API.
        ACTIVE = 1;
        DROPPED = 2;
    }
    State state = 1;
    PartialResponseStrategy partial_response_strategy = 2;
}

message TargetsResponse {
    oneof result {
        /// structure with targets. It is up to server implementation to decide how many of those to put here within single frame.
        TargetDiscovery targets = 1;

        /// warning is considered an information piece in place of series for warning purposes.
        /// It is used to warn rule API users about suspicious cases or partial response (if enabled).
        string warning = 2;
    }
}
```

NOTE: Make sure types have `[(gogoproto.jsontag) = "activeTargets"];` so we can use the same types for json marshalling on HTTP APIs

7. Add new package and implement gRPC Service 

e.g for sidecar

![image](https://user-images.githubusercontent.com/6950331/100866903-40fa9b80-3491-11eb-8820-be9ae1eb6b9c.png)

e.g for merging results in querier:

![image](https://user-images.githubusercontent.com/6950331/100866978-612a5a80-3491-11eb-914e-244aaf4ea88c.png)

7.  Add unit tests
8.  Add e2e tests

**Comment by juliusv** [comment]
@bwplotka Wow, thanks for providing such a detailed guide for implementing this change! Your definition of "trivial" may be different from mine, as it still seems like quite a large change in terms of lines of code and touched files (maybe several days worth of work for someone new to Thanos?). But at least it seems conceptually straightforward then what needs to be done, and with those detailed steps it's much easier for anyone to pick it up!

**Comment by juliusv** [comment]
Regarding stalebot, I saw that @yeya24 created https://github.com/thanos-io/thanos/pull/3686 to address this a month ago, but there hasn't been a review yet.
