### ISSUE TITLE
receive: Data inside wal directory doesn't get deleted the same as the ULID directories

### ISSUE THREAD

**Issue by heartTorres** [thanos-io/thanos#3354]
**Thanos, Prometheus and Golang version used**:
 Thanos v0.15

**Object Storage Provider**:
S3
**What happened**:
I did set up 5 replicas of Thanos Receivers in our environment. I only set 3 hours of data retention.
The generated ULID directories are indeed being deleted after 3 hours. We only set a very small data retention to use a small pvc size (20Gi) as we are ingesting a lot of metrics. However, the data inside the **wal** directory seems keep on increasing. Is this an expected behavior? I was trying to check if there is an information in Thanos Documentation but I could not find it or maybe I have missed it.
**What you expected to happen**:
My expectation to happen is, after 3 hours of data retention, the data in the wal directory would also be deleted the same as the generated ULID directories. After waiting for 8 hours of monitoring, the wal data consumption keeps on increasing.
<img width="376" alt="Screen Shot 2020-10-22 at 8 55 38 PM" src="https://user-images.githubusercontent.com/65100615/96874643-f278db00-14a8-11eb-920c-4235d694bdbd.png">

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by kakkoyun** [comment]
After a block is cut from the head block, the WAL should be truncated. So you should have seen a reduction on `wal` directory. Could you please provide some logs may from your receiver nodes? Is there any errors? And also it would be nice to see your configuration.

**Comment by bwplotka** [comment]
However the truncation can happen after 3h (not necessarily 2h), so that might be expected.

Also too long of WAL was recently kept which was fixed on latest Prometheus, and pulled to latest Thanos (v0.16.0-rc.1), so please check it out :hugs:

**Comment by heartTorres** [comment]
> However the truncation can happen after 3h (not necessarily 2h), so that might be expected.
> 
> Also too long of WAL was recently kept which was fixed on latest Prometheus, and pulled to latest Thanos (v0.16.0-rc.1), so please check it out 🤗

I see!! Thanks for the reply. I'll check it out.

**Comment by heartTorres** [comment]
I'll be closing this ticket for now. Thank you for the reply.
