### ISSUE TITLE
Sidecar - is it possible to reduce 2h delay?

### ISSUE THREAD

**Issue by giovanni-ferrari** [thanos-io/thanos#3363]
Hello everyone,
I was wondering if it is possible to reduce the “ storage.tsdb.min-block-duration” and “ storage.tsdb.max-block-duration” parameters to lower values than 2h (e.g. 30m or 5m).
In my use case multiple Prometheus instances produce time series data that are then transferred via sidecar to a storage accessed by a thanos instance. The user accesses the thanos instance via grafana to plot the data, but it would be necessary to reduce the delay on which the data are shown.
Which are the implication of reducing storage.tsdb.min-block-duration and storage.tsdb.max-block-duration values? Is there any increase on risk of tsdb corruption?

All the best,
G.

**Comment by yeya24** [comment]
Hi, there shouldn't be gaps if you also configure sidecars as stores in the querier. Then the querier can query the recent 2h data directly from Prometheus so you don't need to wait for 2h.

**Comment by giovanni-ferrari** [comment]
Thank you for your response, but unfortunately i’m considering a scenario where the sidecars are not known a priori and are not directly accessible.

GF

**Comment by bwplotka** [comment]
This was already asked at the very beginning of Thanos and the answer is simple. You should not change min-block time for Prometheus. See this discussion: https://github.com/thanos-io/thanos/issues/263#issuecomment-377240062

IF you wish to not access sidecar data, you can think about remote-write deployment with https://thanos.io/tip/components/receive.md/ which comes with a different tradeoff = bit more complexity on the receiving (central) side. 

Let us know if you have any further questions ideally on #thanos CNCF slack (:
