### ISSUE TITLE
Query: external store API server with path cannot be added

### ISSUE THREAD

**Issue by paulden** [thanos-io/thanos#3364]
**Thanos, Prometheus and Golang version used**:

`v0.15.0`

**Object Storage Provider**:

AWS S3

**What happened**:

Hello everyone, thanks for your work on Thanos!
I want to deploy Thanos on a multi-cluster architecture, basically following this kind of architecture: https://banzaicloud.com/img/blog/thanos-operator/thanos-multi-cluster.png

I have three clusters:
- monitoring
- dev
- prod

My monitoring cluster is the entrypoint to monitor all clusters with tools such as Grafana and will need access to the dev and prod metrics. I deployed Thanos on these clusters using [Bitnami Helm chart](https://artifacthub.io/packages/helm/bitnami/thanos), I have GRPC ingresses up and running on each, with URLs such as `tooling.dev.myservice.com/thanos-grpc`. These ingresses point to local `thanos-querier`.

However, when I try to add these in the monitoring clusters, Thanos cannot resolve the endpoint.

Basically, on my monitoring cluster:
```
thanos query --store=tooling.dev.myservice.com/thanos-grpc
```
will fail due to `missing port` and 
```
thanos query --store=tooling.dev.myservice.com:443/thanos-grpc
```
will fail due to `address tcp/443/thanos-grpc: unknow port`.

In my case, it's not planned to have a dedicated DNS record specifically for Thanos, that is why I'm using a path.

**What you expected to happen**:

I can query an external cluster using these ingresses with paths. I'm open to other solutions if I'm missing something.

**How to reproduce it (as minimally and precisely as possible)**:

- Deploy Thanos on two different clusters A and B.
- Enable GRPC ingress with `thanos-querier` as its backend on cluster A, with endpoint such as `tooling.dev.myservice.com/thanos-grpc`
- Add this ingress on cluster B (`--store=tooling.dev.myservice.com:443/thanos-grpc`).

**Environment**:

- OS: Debian GNU/Linux 10 (buster)

**Comment by roysha1** [comment]
Experiencing it also on v0.14.0
