### ISSUE TITLE
Thanos Querier in simple setup much slower than Prometheus directly

### ISSUE THREAD

**Issue by wuestkamp** [thanos-io/thanos#3393]
**Thanos, Prometheus versions used**:
prometheus:v2.18.2
thanos:v0.16.0

**Object Storage Provider**:
None

**What happened**:
* Querying prometheus directly with example query takes 300 milliseconds.
* Querying thanos-query -> prometheus-thanos-sidecar -> prometheus takes 10 times as long (~3.4 seconds).
* Prometheus and Querier are in the same k8s cluster and namespace.
* The amount of data returned by the query is 27kB in both cases.
* There is only one prometheus instance.

**What you expected to happen**:
Not that much overhead.

**Thanos Query**
```
  - args:
    - query
    - --log.level=info
    - --query.replica-label=prometheus_replica
    - --store=dns+prometheus-operator-prometheus-0:10901
```

**Prometheus sidecar**
```
  - args:
    - sidecar
    - --prometheus.url=http://127.0.0.1:9090/
    - --tsdb.path=/prometheus
    - --grpc-address=0.0.0.0:10901
```

Is there any obvious misconfiguration or improvements we can try?

Thanks!

**Comment by bwplotka** [comment]
Things are changing from version to version, but it's definitely something to investigate. There will be some difference but not that large, but it also depends on the network. 

Thanks for reporting!

**Comment by wuestkamp** [comment]
I believe this specific huge slowness was caused by unwanted throttling through the k8s cfs quota issue https://github.com/kubernetes/kubernetes/issues/67577

Once cfs quota disabled there is a more reasonable delay.
