### ISSUE TITLE
thanos-compact generates exponential HEAD / GET HTTP requests on S3 minio

### ISSUE THREAD

**Issue by konvergence** [thanos-io/thanos#3394]
**Thanos, Prometheus and Golang version used**:

* Thanos version : 0.15.0
* Golang version:  ??

**Object Storage Provider**: minio

**What happened**:
* When I monitor nginx-ingress-controller, I can see that thanos-compact generates exponential HEAD / GET HTTP requests on S3 minio
* in 24h, I start with 48 requests/hour to finish with 5724 request/hour.

**What you expected to happen**:
* Even if thanos make more requests with the time, why is there exponential requests ?
[screenshot elasticsearch](https://ibb.co/gSNvmCm)

**How to reproduce it (as minimally and precisely as possible)**:
* just monitor the ingress logs, filtered on ` thanos-compact`

**Full logs to relevant components**:
* example of  ingress requests
```
172.16.110.151 - - [03/Nov/2020:09:58:53 +0000] "HEAD /thanos-k8s-storage-bucket/01EP60R1Y7T5NVW3ESSQKAX88H/meta.json HTTP/1.1" 200 0 "-" "MinIO (linux; amd64) minio-go/v7.0.2 thanos-compact/0.15.0 (go1.14.2)" 547 0.002 [minio-minio-minio] [] 10.42.0.159:9000 0 0.004 200 75ab3b29044508f01bfffd15eef9942f
```
* no more logs on thanos-compactor
* no more logs on minio

**Anything else we need to know**:

**Environment**:
- OS (e.g. from /etc/os-release): 
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
`Linux lab-k8s-operation 5.4.0-52-generic #57~18.04.1-Ubuntu SMP Thu Oct 15 14:04:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Others:

**Comment by bwplotka** [comment]
Exponential based on what? just time? If you restart it starts from lower number? (: 

Might be a bug, to investigate.

**Comment by konvergence** [comment]
You're right, I redid the whole installation a few days, because I wanted to be sure that I wasn't wrong.

But previously, I let thanos during 6 days, and  after this period, I get more than 425000 request/hour
[screenshot2](https://ibb.co/9GCFHhC)

But may be my config is not correct ?

my config is here

```
    retentionResolutionRaw: 30d
    retentionResolution5m: 120d
    retentionResolution1h: 1y

    consistencyDelay: 30m
```

**Comment by bwplotka** [comment]
It looks good, so looks like a bug (:

**Comment by konvergence** [comment]
Not sure this is a bug, as S3 storage is growing in the same trends, and may be more.
[screenshot3](https://ibb.co/FzKyRZb)

I will be monitoring more time to see if the ingress traffic becomes stable.

**Comment by bwplotka** [comment]
It will be growing (but not indefinitely) due to 2d delete delay if you never used Thanos before. (: 

Also created issue with feature request that will improve things a lot: https://github.com/thanos-io/thanos/issues/3408

**Comment by konvergence** [comment]
Hi bwplotka,

I think that there was something wrong during my first install because now the traffic became more stable.
During my first installation, I forgot to force the annotation on minio ingress

```
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/client-max-body-size: "0"
````

And I got an HTTP 413 "Payload Too Large" error after a while.
I changed it, but "Thanos side" on Prometheus seemed to have lost some of the chunk, and Thanos compator went up, despite I had corrected the ingress

Know, now since i reinstalled everything and purged the S3 it seems to stabilize.

But maybe there's an improvement that needs to be made to allow Thanos to restore proper treatment in the event of this disturbance with S3.

I will keep you inform of the evolution of HTTP request on my minio.

Regards

I will

**Comment by mfvanek** [comment]
We've faced with the similar issue while using Hitachi Content Platform (HCP) as a S3 compatible storage.
The issue is that HCP supports directories and treats them as separate objects, while [AWS S3 does not have a separate entity for directories](https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-folders.html).

In our case, during the operation of Thanos Compactor, empty directories remain in HCP and thousands of them accumulate over time. Thanos Compactor makes HEAD requests to each such directory, which leads to a significant load on S3 storage.
```
our_S3_tenant [13/Dec/2021:17:18:39 +0300] "HEAD /our_S3_bucket/01FN2VRY6EHVR12P7B3KVS7F7Y/meta.json HTTP/1.1" 404 0 our_S3_tenant@hs3 3 101 0
our_S3_tenant [13/Dec/2021:17:18:39 +0300] "HEAD /our_S3_bucket/01FN307S8GMZXVWD1CDBVCDXE7/meta.json HTTP/1.1" 404 0 our_S3_tenant@hs3 3 101 0
our_S3_tenant [13/Dec/2021:17:18:39 +0300] "HEAD /our_S3_bucket/01FN373GGHFVR2502VXM4HKRP0/meta.json HTTP/1.1" 404 0 our_S3_tenant@hs3 2 101 0
our_S3_tenant [13/Dec/2021:17:18:39 +0300] "HEAD /our_S3_bucket/01FN3DZ7RH0DGP25AB62HB5MVP/meta.json HTTP/1.1" 404 0 our_S3_tenant@hs3 3 101 0
```

Our solution at the moment is automated cleaning of empty directories in HCP using minIO client.

**Comment by BooNny95** [comment]
> We've faced with the similar issue while using Hitachi Content Platform (HCP) as a S3 compatible storage. The issue is that HCP supports directories and treats them as separate objects, while [AWS S3 does not have a separate entity for directories](https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-folders.html).
> 
> In our case, during the operation of Thanos Compactor, empty directories remain in HCP and thousands of them accumulate over time. Thanos Compactor makes HEAD requests to each such directory, which leads to a significant load on S3 storage.
> 
> ```
> our_S3_tenant [13/Dec/2021:17:18:39 +0300] "HEAD /our_S3_bucket/01FN2VRY6EHVR12P7B3KVS7F7Y/meta.json HTTP/1.1" 404 0 our_S3_tenant@hs3 3 101 0
> our_S3_tenant [13/Dec/2021:17:18:39 +0300] "HEAD /our_S3_bucket/01FN307S8GMZXVWD1CDBVCDXE7/meta.json HTTP/1.1" 404 0 our_S3_tenant@hs3 3 101 0
> our_S3_tenant [13/Dec/2021:17:18:39 +0300] "HEAD /our_S3_bucket/01FN373GGHFVR2502VXM4HKRP0/meta.json HTTP/1.1" 404 0 our_S3_tenant@hs3 2 101 0
> our_S3_tenant [13/Dec/2021:17:18:39 +0300] "HEAD /our_S3_bucket/01FN3DZ7RH0DGP25AB62HB5MVP/meta.json HTTP/1.1" 404 0 our_S3_tenant@hs3 3 101 0
> ```
> 
> Our solution at the moment is automated cleaning of empty directories in HCP using minIO client.

We have the same issue with thanos 0.27.0 version.

**Comment by Jaywoods2** [comment]
Hi ~, @mfvanek how to cleaning of empty directories in HCP using minIO client, Thanks .

**Comment by mfvanek** [comment]
Hi @Jaywoods2 
I cannot provide fully working solution at the moment because we didn't open-source it.
Try something like that (see **delete_block** method):
```python
import os
import urllib3
from minio import Minio
from minio.datatypes import Object
from logger_config import get_logger
from prometheus_flask_exporter import Counter, Gauge

clean_job_counter = Counter('clean_s3_job_counter', 'Clean counter')
clean_block_counter = Counter('clean_s3_block_counter', 'Cleaned blocks counter')
clean_timer_metric = Gauge('clean_s3_clean_timer', 'Timer clean job status')

urllib3.disable_warnings()
logging = get_logger()

client = Minio(
    os.getenv("S3_ENDPOINT"),
    access_key=os.getenv("S3_ACCESS_KEY"),
    secret_key=os.getenv("S3_SECRET_KEY"),
    http_client=urllib3.PoolManager(cert_reqs='CERT_NONE', assert_hostname=False)
)

def check_connection():
    try:
        client.get_bucket_versioning(os.getenv("S3_BUCKET"))
    except urllib3.exceptions.MaxRetryError:
        logging.info(f"Cleanup didn't started. Connection Error")
        exit(1)

def get_blocks():
    objects = client.list_objects(os.getenv("S3_BUCKET"))

    # Filter only directories that looks like prometheus TSDB-block.
    # Block names look like 26 alphanumeric chars plus a trailing slash (e.g. '01F4WJWD8RKQW0F848G53VZNVM/')
    return list(it for it in objects if len(it.object_name) == 27)


def check_if_empty(block: Object):
    list_result = list(client.list_objects(block.bucket_name, block.object_name + "meta.json"))
    return len(list_result) == 0


def delete_block(bucket, block_name):
    object_names_to_delete = list(
        x.object_name for x in client.list_objects(bucket, block_name, recursive=True))
    object_names_to_delete = sorted(object_names_to_delete, reverse=True)
    if len(object_names_to_delete) == 0:
        logging.info(f"Block {block_name} does not exist in {bucket} bucket.")
        return f"Block {block_name} does not exist in {bucket} bucket.\n"

    # client.remove_objects is not working properly with our S3 implementation, so we use remove_object in loop instead
    for object_name in object_names_to_delete:
        logging.info(f"Deleting {object_name}")
        client.remove_object(bucket, object_name)
    logging.info(f"Block {block_name} successfully deleted.")
    return f"Block {block_name} successfully deleted.\n"

@clean_timer_metric.time()
def clean_empty_blocks():
    blocks = get_blocks()
    blocks_count = len(blocks)
    non_empty_blocks = []
    clean_job_counter.inc()

    for i, block in enumerate(blocks):
        if check_if_empty(block):
            logging.info(f"[{i}/{blocks_count}] Deleting empty block {block.object_name}")
            delete_block(block.bucket_name, block.object_name)
            clean_block_counter.inc()
        else:
            logging.info(f"[{i}/{blocks_count}] Discovered block: {block.object_name}")
            non_empty_blocks.append(block)

    non_empty_blocks_count = len(non_empty_blocks)
    logging.info(
        f"Cleanup finished. Removed {blocks_count - non_empty_blocks_count} blocks."
        f"Discovered {non_empty_blocks_count} non-empty blocks.")
```
