### ISSUE TITLE
thanos store keeps crashlooping

### ISSUE THREAD

**Issue by kelly-brown** [thanos-io/thanos#3404]
**Thanos, Prometheus and Golang version used**:

v0.16.0

**Object Storage Provider**:
NetApp Storage Grid

**What happened**:
Crashlooping with this error.  NOTE: the deletion-mark.json doesn't even exist.  Block its complaining about changes with every loop.  Tried removing the block it's complaining about but it doesn't help.

level=error ts=2020-11-04T14:44:51.99943915Z caller=main.go:197 err="We encountered an internal error. Please try again.\nget file: 01EDD71A8WJAH3V0A6GMMSQWCH/deletion-mark.json\ngithub.com/thanos-io/thanos/pkg/block/metadata.ReadDeletionMark\n\t/go/src/github.com/thanos-io/thanos/pkg/block/metadata/deletionmark.go:56\ngithub.com/thanos-io/thanos/pkg/block.(*IgnoreDeletionMarkFilter).Filter\n\t/go/src/github.com/thanos-io/thanos/pkg/block/fetcher.go:784\ngithub.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetch\n\t/go/src/github.com/thanos-io/thanos/pkg/block/fetcher.go:434\ngithub.com/thanos-io/thanos/pkg/block.(*MetaFetcher).Fetch\n\t/go/src/github.com/thanos-io/thanos/pkg/block/fetcher.go:474\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).SyncBlocks\n\t/go/src/github.com/thanos-io/thanos/pkg/store/bucket.go:361\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).InitialSync\n\t/go/src/github.com/thanos-io/thanos/pkg/store/bucket.go:430\nmain.runStore.func4\n\t/go/src/github.com/thanos-io/thanos/cmd/thanos/store.go:321\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nfilter metas\ngithub.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetch\n\t/go/src/github.com/thanos-io/thanos/pkg/block/fetcher.go:435\ngithub.com/thanos-io/thanos/pkg/block.(*MetaFetcher).Fetch\n\t/go/src/github.com/thanos-io/thanos/pkg/block/fetcher.go:474\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).SyncBlocks\n\t/go/src/github.com/thanos-io/thanos/pkg/store/bucket.go:361\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).InitialSync\n\t/go/src/github.com/thanos-io/thanos/pkg/store/bucket.go:430\nmain.runStore.func4\n\t/go/src/github.com/thanos-io/thanos/cmd/thanos/store.go:321\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nsync block\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).InitialSync\n\t/go/src/github.com/thanos-io/thanos/pkg/store/bucket.go:431\nmain.runStore.func4\n\t/go/src/github.com/thanos-io/thanos/cmd/thanos/store.go:321\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nbucket store initial sync\nmain.runStore.func4\n\t/go/src/github.com/thanos-io/thanos/cmd/thanos/store.go:323\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nstore command failed\nmain.main\n\t/go/src/github.com/thanos-io/thanos/cmd/thanos/main.go:197\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"

**What you expected to happen**:
Need thanos store to run

**How to reproduce it (as minimally and precisely as possible)**:
Not sure.

**Full logs to relevant components**:

<details>Logs
<p>

level=debug ts=2020-11-04T14:42:53.278862199Z caller=main.go:91 msg="maxprocs: Leaving GOMAXPROCS=[14]: CPU quota undefined"
level=info ts=2020-11-04T14:42:53.279674953Z caller=main.go:138 msg="Tracing will be disabled"
level=info ts=2020-11-04T14:42:53.279900169Z caller=factory.go:46 msg="loading bucket configuration"
level=info ts=2020-11-04T14:42:53.280496665Z caller=inmemory.go:172 msg="created in-memory index cache" maxItemSizeBytes=131072000 maxSizeBytes=524288000 maxItems=maxInt
level=info ts=2020-11-04T14:42:53.281119965Z caller=options.go:23 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2020-11-04T14:42:53.281735123Z caller=store.go:387 msg="starting store node"
level=info ts=2020-11-04T14:42:53.281802048Z caller=store.go:319 msg="initializing bucket store"
level=info ts=2020-11-04T14:42:53.281844634Z caller=intrumentation.go:60 msg="changing probe status" status=healthy
level=info ts=2020-11-04T14:42:53.281867157Z caller=http.go:58 service=http/server component=store msg="listening for requests and metrics" address=0.0.0.0:10902
level=warn ts=2020-11-04T14:44:51.49874885Z caller=intrumentation.go:54 msg="changing probe status" status=not-ready reason="bucket store initial sync: sync block: filter metas: get file: 01EDD71A8WJAH3V0A6GMMSQWCH/deletion-mark.json: We encountered an internal error. Please try again."
level=info ts=2020-11-04T14:44:51.498821048Z caller=http.go:65 service=http/server component=store msg="internal server is shutting down" err="bucket store initial sync: sync block: filter metas: get file: 01EDD71A8WJAH3V0A6GMMSQWCH/deletion-mark.json: We encountered an internal error. Please try again."
level=info ts=2020-11-04T14:44:51.498904896Z caller=intrumentation.go:48 msg="changing probe status" status=ready
level=info ts=2020-11-04T14:44:51.49903877Z caller=grpc.go:114 service=gRPC/server component=store msg="listening for serving gRPC" address=0.0.0.0:10901
level=info ts=2020-11-04T14:44:51.99902569Z caller=http.go:84 service=http/server component=store msg="internal server is shutdown gracefully" err="bucket store initial sync: sync block: filter metas: get file: 01EDD71A8WJAH3V0A6GMMSQWCH/deletion-mark.json: We encountered an internal error. Please try again."
level=info ts=2020-11-04T14:44:51.999129961Z caller=intrumentation.go:66 msg="changing probe status" status=not-healthy reason="bucket store initial sync: sync block: filter metas: get file: 01EDD71A8WJAH3V0A6GMMSQWCH/deletion-mark.json: We encountered an internal error. Please try again."
level=warn ts=2020-11-04T14:44:51.99916776Z caller=intrumentation.go:54 msg="changing probe status" status=not-ready reason="bucket store initial sync: sync block: filter metas: get file: 01EDD71A8WJAH3V0A6GMMSQWCH/deletion-mark.json: We encountered an internal error. Please try again."
level=info ts=2020-11-04T14:44:51.999178209Z caller=grpc.go:121 service=gRPC/server component=store msg="internal server is shutting down" err="bucket store initial sync: sync block: filter metas: get file: 01EDD71A8WJAH3V0A6GMMSQWCH/deletion-mark.json: We encountered an internal error. Please try again."
level=info ts=2020-11-04T14:44:51.999202157Z caller=grpc.go:134 service=gRPC/server component=store msg="gracefully stopping internal server"
level=info ts=2020-11-04T14:44:51.999286452Z caller=grpc.go:147 service=gRPC/server component=store msg="internal server is shutdown gracefully" err="bucket store initial sync: sync block: filter metas: get file: 01EDD71A8WJAH3V0A6GMMSQWCH/deletion-mark.json: We encountered an internal error. Please try again."
level=error ts=2020-11-04T14:44:51.99943915Z caller=main.go:197 err="We encountered an internal error. Please try again.\nget file: 01EDD71A8WJAH3V0A6GMMSQWCH/deletion-mark.json\ngithub.com/thanos-io/thanos/pkg/block/metadata.ReadDeletionMark\n\t/go/src/github.com/thanos-io/thanos/pkg/block/metadata/deletionmark.go:56\ngithub.com/thanos-io/thanos/pkg/block.(*IgnoreDeletionMarkFilter).Filter\n\t/go/src/github.com/thanos-io/thanos/pkg/block/fetcher.go:784\ngithub.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetch\n\t/go/src/github.com/thanos-io/thanos/pkg/block/fetcher.go:434\ngithub.com/thanos-io/thanos/pkg/block.(*MetaFetcher).Fetch\n\t/go/src/github.com/thanos-io/thanos/pkg/block/fetcher.go:474\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).SyncBlocks\n\t/go/src/github.com/thanos-io/thanos/pkg/store/bucket.go:361\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).InitialSync\n\t/go/src/github.com/thanos-io/thanos/pkg/store/bucket.go:430\nmain.runStore.func4\n\t/go/src/github.com/thanos-io/thanos/cmd/thanos/store.go:321\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nfilter metas\ngithub.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetch\n\t/go/src/github.com/thanos-io/thanos/pkg/block/fetcher.go:435\ngithub.com/thanos-io/thanos/pkg/block.(*MetaFetcher).Fetch\n\t/go/src/github.com/thanos-io/thanos/pkg/block/fetcher.go:474\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).SyncBlocks\n\t/go/src/github.com/thanos-io/thanos/pkg/store/bucket.go:361\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).InitialSync\n\t/go/src/github.com/thanos-io/thanos/pkg/store/bucket.go:430\nmain.runStore.func4\n\t/go/src/github.com/thanos-io/thanos/cmd/thanos/store.go:321\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nsync block\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).InitialSync\n\t/go/src/github.com/thanos-io/thanos/pkg/store/bucket.go:431\nmain.runStore.func4\n\t/go/src/github.com/thanos-io/thanos/cmd/thanos/store.go:321\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nbucket store initial sync\nmain.runStore.func4\n\t/go/src/github.com/thanos-io/thanos/cmd/thanos/store.go:323\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nstore command failed\nmain.main\n\t/go/src/github.com/thanos-io/thanos/cmd/thanos/main.go:197\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"

</p>
</details>

**Anything else we need to know**:
Feel free to redirect me if I'm posting to the wrong place.  Any help would be appreciated.

**Comment by kelly-brown** [comment]
I think I'm running into the same issue reported here.  https://github.com/thanos-io/thanos/issues/2842 

I don't exactly know why it started but I had some overlapping blocks so I removed those, and then this started.  I was at v0.14.0, I decided to run with v.0.16.0 to see if it would change the behavior and it did not.  After finding issue 2842, I started up v0.11.0 and it's running.  It's looking a lot of errors but it finally finished and seems to be loading blocks now.

Should I bring all my components back to v0.11.0?  Am I stuck here now for some reason?

Again, thanks for any help anybody can provide.

**Comment by cphikmawan** [comment]
same issue using thanos version: v0.17.2 and GCS

```
level=info ts=2020-12-15T04:40:01.925378373Z caller=main.go:168 msg="caught signal. Exiting." signal=terminated
level=warn ts=2020-12-15T04:40:01.925491145Z caller=intrumentation.go:54 msg="changing probe status" status=not-ready reason=null
level=info ts=2020-12-15T04:40:01.925512395Z caller=http.go:65 service=http/server component=store msg="internal server is shutting down" err=null
level=info ts=2020-12-15T04:40:02.425807996Z caller=http.go:84 service=http/server component=store msg="internal server is shutdown gracefully" err=null
level=info ts=2020-12-15T04:40:02.425903289Z caller=intrumentation.go:66 msg="changing probe status" status=not-healthy reason=null
level=warn ts=2020-12-15T04:40:02.425962721Z caller=intrumentation.go:54 msg="changing probe status" status=not-ready reason=null
level=info ts=2020-12-15T04:40:02.425972915Z caller=grpc.go:123 service=gRPC/server component=store msg="internal server is shutting down" err=null
level=info ts=2020-12-15T04:40:02.425995073Z caller=grpc.go:136 service=gRPC/server component=store msg="gracefully stopping internal server"
level=warn ts=2020-12-15T04:40:02.426188217Z caller=store.go:337 msg="syncing blocks failed" err="filter metas: get file: 01E27E5T10ZPM34B51FEWJEWB8/deletion-mark.json: Get \"https://storage.googleapis.com/prometheus-tsdb/01E27E5T10ZPM34B51FEWJEWB8/deletion-mark.json\": context canceled"
level=info ts=2020-12-15T04:40:02.42652717Z caller=grpc.go:149 service=gRPC/server component=store msg="internal server is shutdown gracefully" err=null
level=info ts=2020-12-15T04:40:03.064991926Z caller=main.go:160 msg=exiting
level=info ts=2020-12-15T04:40:03.441013598Z caller=main.go:98 msg="Tracing will be disabled"
```

**Comment by kelly-brown** [comment]
To round back with what was happening to me...  Our S3 infrastructure had lost a node and my bucket was set to 'read-after-new-write' which for whatever reason was sending 500 errors when thanos would try to check if a file existed, rather than 404's.  Apparently this is known and accepted behavior.  I'm not an S3 expert so I had no clue, this was just the default.  I switched it to 'available' and that prevents the problem.  Apparently if you need to be 100% sure your data is consistent you wouldn't want to do that.  Anyway, this was on a netapp, but it's part of the s3 protocol.  I forgot all about this issue until somebody added to it.  So figured it best to provide an update.

**Comment by cphikmawan** [comment]
i was fixed my issue by reduce option `--delete-delay=6h` option to thanos-compact and `--ignore-deletion-marks-delay=3h` to thanos-store.

data block on my storage about 7TB. so it need some times to compaction, also there is my fault. i forgot all about cron for restarting thanos-store every 20min.

thanks.

**Comment by graqfreak** [comment]
Hi - I'm seeing a similar issue that relates to overlapped blocks, causing both compactor and storage not being able to start up.
I've tried the option of `--delete-delay=6h` to thanos-compact and `--ignore-deletion-marks-delay=3h` to thanos-store, unfortunately it hasn't worked so far. 

Any other ideas?

Ran the verification tool and the number of overlapped blocks is rather large. 

Thanos Version v0.19.0
Storage Provider: Internal Company, similar to Amazon S3

Logs of the compactor:
```
level=info ts=2021-07-29T02:35:56.726509258Z caller=factory.go:46 msg="loading bucket configuration"
level=info ts=2021-07-29T02:35:56.727076128Z caller=inmemory.go:172 msg="created in-memory index cache" maxItemSizeBytes=131072000 maxSizeBytes=262144000 maxItems=maxInt
level=info ts=2021-07-29T02:35:56.72747334Z caller=options.go:23 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2021-07-29T02:35:56.728331848Z caller=store.go:408 msg="starting store node"
level=info ts=2021-07-29T02:35:56.728459984Z caller=store.go:340 msg="initializing bucket store"
level=info ts=2021-07-29T02:35:56.728505412Z caller=intrumentation.go:60 msg="changing probe status" status=healthy
level=info ts=2021-07-29T02:35:56.728549548Z caller=http.go:62 service=http/server component=store msg="listening for requests and metrics" address=0.0.0.0:19191
level=warn ts=2021-07-29T02:36:02.973256123Z caller=intrumentation.go:54 msg="changing probe status" status=not-ready reason="bucket store initial sync: sync block: filter metas: filter blocks marked for deletion: get file: 01F6NY89CWFXRFDRQ0FQDM1HH5/deletion-mark.json: We encountered an internal error. Please try again."
level=info ts=2021-07-29T02:36:02.974374191Z caller=http.go:69 service=http/server component=store msg="internal server is shutting down" err="bucket store initial sync: sync block: filter metas: filter blocks marked for deletion: get file: 01F6NY89CWFXRFDRQ0FQDM1HH5/deletion-mark.json: We encountered an internal error. Please try again."
level=info ts=2021-07-29T02:36:02.974451176Z caller=intrumentation.go:48 msg="changing probe status" status=ready
level=info ts=2021-07-29T02:36:02.975950801Z caller=grpc.go:116 service=gRPC/server component=store msg="listening for serving gRPC" address=0.0.0.0:19090
level=info ts=2021-07-29T02:36:03.474576753Z caller=http.go:88 service=http/server component=store msg="internal server is shutdown gracefully" err="bucket store initial sync: sync block: filter metas: filter blocks marked for deletion: get file: 01F6NY89CWFXRFDRQ0FQDM1HH5/deletion-mark.json: We encountered an internal error. Please try again."
level=info ts=2021-07-29T02:36:03.474664254Z caller=intrumentation.go:66 msg="changing probe status" status=not-healthy reason="bucket store initial sync: sync block: filter metas: filter blocks marked for deletion: get file: 01F6NY89CWFXRFDRQ0FQDM1HH5/deletion-mark.json: We encountered an internal error. Please try again."
level=warn ts=2021-07-29T02:36:03.474735649Z caller=intrumentation.go:54 msg="changing probe status" status=not-ready reason="bucket store initial sync: sync block: filter metas: filter blocks marked for deletion: get file: 01F6NY89CWFXRFDRQ0FQDM1HH5/deletion-mark.json: We encountered an internal error. Please try again."
level=info ts=2021-07-29T02:36:03.474749694Z caller=grpc.go:123 service=gRPC/server component=store msg="internal server is shutting down" err="bucket store initial sync: sync block: filter metas: filter blocks marked for deletion: get file: 01F6NY89CWFXRFDRQ0FQDM1HH5/deletion-mark.json: We encountered an internal error. Please try again."
level=info ts=2021-07-29T02:36:03.474780012Z caller=grpc.go:136 service=gRPC/server component=store msg="gracefully stopping internal server"
level=info ts=2021-07-29T02:36:03.474854289Z caller=grpc.go:149 service=gRPC/server component=store msg="internal server is shutdown gracefully" err="bucket store initial sync: sync block: filter metas: filter blocks marked for deletion: get file: 01F6NY89CWFXRFDRQ0FQDM1HH5/deletion-mark.json: We encountered an internal error. Please try again."
level=error ts=2021-07-29T02:36:03.4750563Z caller=main.go:156 err="We encountered an internal error. Please try again.\nget file: 01F6NY89CWFXRFDRQ0FQDM1HH5/deletion-mark.json\ngithub.com/thanos-io/thanos/pkg/block/metadata.ReadMarker\n\t/home/circleci/project/pkg/block/metadata/markers.go:96\ngithub.com/thanos-io/thanos/pkg/block.(*IgnoreDeletionMarkFilter).Filter.func1\n\t/home/circleci/project/pkg/block/fetcher.go:825\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/home/circleci/go/pkg/mod/golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/errgroup/errgroup.go:57\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nfilter blocks marked for deletion\ngithub.com/thanos-io/thanos/pkg/block.(*IgnoreDeletionMarkFilter).Filter\n\t/home/circleci/project/pkg/block/fetcher.go:868\ngithub.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetch\n\t/home/circleci/project/pkg/block/fetcher.go:457\ngithub.com/thanos-io/thanos/pkg/block.(*MetaFetcher).Fetch\n\t/home/circleci/project/pkg/block/fetcher.go:497\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).SyncBlocks\n\t/home/circleci/project/pkg/store/bucket.go:395\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).InitialSync\n\t/home/circleci/project/pkg/store/bucket.go:464\nmain.runStore.func4\n\t/home/circleci/project/cmd/thanos/store.go:342\ngithub.com/oklog/run.(*Group).Run.func1\n\t/home/circleci/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nfilter metas\ngithub.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetch\n\t/home/circleci/project/pkg/block/fetcher.go:458\ngithub.com/thanos-io/thanos/pkg/block.(*MetaFetcher).Fetch\n\t/home/circleci/project/pkg/block/fetcher.go:497\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).SyncBlocks\n\t/home/circleci/project/pkg/store/bucket.go:395\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).InitialSync\n\t/home/circleci/project/pkg/store/bucket.go:464\nmain.runStore.func4\n\t/home/circleci/project/cmd/thanos/store.go:342\ngithub.com/oklog/run.(*Group).Run.func1\n\t/home/circleci/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nsync block\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).InitialSync\n\t/home/circleci/project/pkg/store/bucket.go:465\nmain.runStore.func4\n\t/home/circleci/project/cmd/thanos/store.go:342\ngithub.com/oklog/run.(*Group).Run.func1\n\t/home/circleci/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nbucket store initial sync\nmain.runStore.func4\n\t/home/circleci/project/cmd/thanos/store.go:344\ngithub.com/oklog/run.(*Group).Run.func1\n\t/home/circleci/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nstore command failed\nmain.main\n\t/home/circleci/project/cmd/thanos/main.go:156\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"
```
