### ISSUE TITLE
compactor: thanos-compact failed to do compaction

### ISSUE THREAD

**Issue by xiaozongyang** [thanos-io/thanos#3422]
# compactor: thanos-compact seems that it is not working
ping @shaulboozhiao @wujinhu
**Thanos, Prometheus and Golang version used**:

- thanos image: quay.io/thanos/thanos:v0.13.0
- prometheus iamge:  prom/prometheus:v2.20.0
- go version: 1.14.2

**Object Storage Provider**:
AliyunOSS
**What happened**:
1. Thanos compact print error logs as following
```
level=error ts=2020-11-05T13:21:53.561956626Z caller=runutil.go:98 msg="function failed. Retrying in next tick" err="incomplete view: meta.json file exists: 01EJ6B6R423DX4Q8DJXTGWX72M/meta.json: cloud not check if object exists: Head \"http://ali-thanos-storage.oss-cn-beijing-internal.aliyuncs.com/01EJ6B6R423DX4Q8DJXTGWX72M%2Fmeta.json?objectMeta\": net/http: timeout awaiting response headers"
level=error ts=2020-11-05T15:21:54.068763852Z caller=compact.go:375 msg="critical error detected; halting" err="compaction: group 0@17977903472349947771: pre compaction overlap check: overlaps found while gathering blocks. [mint: 1603144800002, maxt: 1603152000000, range: 1h59m59s, blocks: 2]: <ulid: 01EN2K69JMEZPBFBKKSN85P3XC, mint: 1603144800000, maxt: 1603152000000, range: 2h0m0s>, <ulid: 01EN9KCY087K6V2CECBZA71X72, mint: 1603144800002, maxt: 1603152000000, range: 1h59m59s>\n[mint: 1603152000000, maxt: 1603159200000, range: 2h0m0s, blocks: 2]: <ulid: 01EN2KKN0NVJ38HVPBNMP9VFC3, mint: 1603152000000, maxt: 1603159200000, range: 2h0m0s>, <ulid: 01EN9KY705Q1B41E0B12HHTVXR, mint: 1603152000000, maxt: 1603159200000, range: 2h0m0s>\n[mint: 1603180800000, maxt: 1603188000000, range: 2h0m0s, blocks: 2]: <ulid: 01EN2TMWW34BYRYYAQXNW6Q2A0, mint: 1603180800000, maxt: 1603188000000, range: 2h0m0s>, <ulid: 01EN9MTSJAZZ790N4YXYT8QDDW, mint: 1603180800000, maxt: 1603188000000, range: 2h0m0s>"
level=error ts=2020-11-05T18:31:53.45743365Z caller=runutil.go:98 msg="function failed. Retrying in next tick" err="BaseFetcher: iter bucket: listing aliyun oss bucket failed: Get \"http://ali-thanos-storage.oss-cn-beijing-internal.aliyuncs.com/?delimiter=%2F&encoding-type=url&marker=&prefix=\": net/http: timeout awaiting response headers"
level=error ts=2020-11-05T21:03:53.534831197Z caller=runutil.go:98 msg="function failed. Retrying in next tick" err="incomplete view: meta.json file exists: 01EJ4V4NCEGX5VDYBZ55D8S06Q/meta.json: cloud not check if object exists: Head \"http://ali-thanos-storage.oss-cn-beijing-internal.aliyuncs.com/01EJ4V4NCEGX5VDYBZ55D8S06Q%2Fmeta.json?objectMeta\": net/http: timeout awaiting response headers"
```
2. the metrics shows that no samples have been compacted,
```
prometheus_tsdb_compaction_chunk_samples_bucket{le="+Inf"} 0
prometheus_tsdb_compaction_chunk_samples_sum 0
prometheus_tsdb_compaction_chunk_samples_count 0

prometheus_tsdb_compaction_chunk_range_seconds_bucket{le="+Inf"} 0
prometheus_tsdb_compaction_chunk_range_seconds_sum 0
prometheus_tsdb_compaction_chunk_range_seconds_count 0

prometheus_tsdb_compaction_chunk_size_bytes_bucket{le="+Inf"} 0
prometheus_tsdb_compaction_chunk_size_bytes_sum 0
prometheus_tsdb_compaction_chunk_size_bytes_count 0
```
**What you expected to happen**:
1. no error logs
2. above metrics should tell that old samples were compacted

**Full logs to relevant components**:
full logs are in the attachment [thanos-compact.log](https://github.com/thanos-io/thanos/files/5504810/thanos-compact.log)

**Anything else we need to know**:

**Environment**:
- OS (e.g. from /etc/os-release): 
    - my process runs on a k8s container which I can't find file `/etc/os-release` 
- Kernel (e.g. `uname -a`):  `Linux ali-thanos-compact-5c49b977c8-xfr78 4.19.91-19.1.al7.x86_64 #1 SMP Tue May 26 19:19:43 CST 2020 x86_64 GNU/Linux`

**Comment by GiedriusS** [comment]
Hi! Are you sure that you can access that URL? This sounds like a network issue.

**Comment by wujinhu** [comment]
Hi @GiedriusS you can access oss-cn-beijing-internal.aliyuncs.com in vpc or internal network, so what's your network env?

**Comment by xiaozongyang** [comment]
Hi @GiedriusS @wujinhu   thanks for your reply and help.

ping @GiedriusS 
I'm sure I can access that URL, ping, the output of telnet and curl shows that it seems no network issues like firewall failures.

@wujinhu 
My pod is deployed on aliyun, I can get response when I ping the internal address.

**Comment by xiaozongyang** [comment]
@wujinhu I can find the `meta.json` file on oss console, but there is an error message about this file. What should I do next step?
error log is `level=error ts=2020-11-07T08:58:53.515846758Z caller=runutil.go:98 msg="function failed. Retrying in next tick" err="incomplete view: meta.json file exists: 01EECADB81BJC2E27E01W97MWQ/meta.json: cloud not check if object exists: Head \"http://ali-thanos-storage.oss-cn-beijing-internal.aliyuncs.com/01EECADB81BJC2E27E01W97MWQ%2Fmeta.json?objectMeta\": net/http: timeout awaiting response headers"
`
And the screenshot for the OSS console is
![WeChatWorkScreenshot_7f4c6245-94e6-437c-8de0-cdbd517c4ac2](https://user-images.githubusercontent.com/8848479/98529032-16655a80-22b8-11eb-9331-101902d01f65.png)

**Comment by xiaozongyang** [comment]
ping @GiedriusS @GiedriusS 

Are there any synchronization problems? We've got only one `thanos compact` pod  galobally.

**Comment by xiaozongyang** [comment]
ping @GiedriusS  @wujinhu

**Comment by xiaozongyang** [comment]
![image](https://user-images.githubusercontent.com/8848479/100182548-dd63f180-2f17-11eb-8f10-15012072a871.png)
I deploy thanos tools bucket web, and I get information shown as this picture. It may be incorret that the resolution of all buckets are 0.

**Comment by xiaozongyang** [comment]
Hi,

When I curl the metrics path of the thanos-compact process, I can't see the metric `thanos_compact_downsample_total` or `thanos_compact_downsample_failures_toal` in response. But I find these source which shows that these two counter registered on starting. Is it the evidence that shows downsampling is not running or something wrong?

```go
// called in runCompact
func newDownsampleMetrics(reg *prometheus.Registry) *DownsampleMetrics {
	m := new(DownsampleMetrics)

	m.downsamples = promauto.With(reg).NewCounterVec(prometheus.CounterOpts{
		Name: "thanos_compact_downsample_total",
		Help: "Total number of downsampling attempts.",
	}, []string{"group"})
	m.downsampleFailures = promauto.With(reg).NewCounterVec(prometheus.CounterOpts{
		Name: "thanos_compact_downsample_failures_total",
		Help: "Total number of failed downsampling attempts.",
	}, []string{"group"})

	return m
}
```

**Comment by xiaozongyang** [comment]
ping @GiedriusS  @bwplotka,
Help wanted, any other information should I provide for troubleshooting?

**Comment by xiaozongyang** [comment]
Finally, I find out that my `compactor` is halted. see [Troubleshooting; Common cases
](https://github.com/thanos-io/thanos/blob/master/docs/operating/troubleshooting.md#overlaps) for more details.

It is verified that when I send a HTTP request to metric port.

This issue will be closed, thanks for the guys' help, especially @GiedriusS @bwplotka @wujinhu
