### ISSUE TITLE
503 error code in query server

### ISSUE THREAD

**Issue by stylianosrigas** [thanos-io/thanos#3433]
**Thanos, Prometheus and Golang version used**:
Thanos v0.15.0

**Object Storage Provider**:
AWS S3

**What happened**:
Seeing 
```
level=error ts=2020-11-11T19:32:15.683334348Z caller=http.go:34 protocol=http http.component=server http.method=query_range http.request.id=57efa01f2e9334479bc3e9eab41599a4 http.code=503 http.time_ms=29273.072 http.error=503 msg="finished call"
```
I think that this happens in very long queries which either leads in a timeout or a cancelled call. Is there a way to solve this?

Do you know what can this be related to?

**Comment by banghuaji** [comment]
I have the same question.

Thanos v0.16.0

**Comment by stylianosrigas** [comment]
@banghuaji After some investigation, I found out that this happens either because of a timeout or because of a cancelled request. A cancelled request can be a Grafana dashboard that gets refreshed before the query is finished. This will cancel the request and give you the 503 error.

**Comment by GiedriusS** [comment]
Yep, you are correct, @stylianosrigas. But we should fix this behavior. I am closing this in favor of https://github.com/thanos-io/thanos/issues/3456 to keep everything under one hood. That issue has more information.
