### ISSUE TITLE
Mixin: add Grafana dashboard for query frontend

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#3434]
### Is your proposal related to a problem?

We are running thanos query frontend, but we don't have a dashboard for it right now. It would be very nice to have one dashboard to monitor the cache status, requests, etc.

### Describe the solution you'd like

Add a dashboard for query frontend to the mixin

**Comment by bistaastha** [comment]
Hi. I will be working on this :)

**Comment by yeya24** [comment]
@bistaastha That would be great! Please let me know if you have any questions.

**Comment by bistaastha** [comment]
Hi. I will be getting back to this issue after another week and will update the status here.
Apologies for getting sidetracked from this.

**Comment by vanugrah** [comment]
Hey folks - any updates on this? Would be quite useful to have.

**Comment by bistaastha** [comment]
Hi @yeya24 ! I have been unable to work properly on this. So can you please unassign me?

**Comment by jessicalins** [comment]
hey @yeya24 I'd like to work on this :)

**Comment by jessicalins** [comment]
I've added a PR with some basic metrics here: https://github.com/thanos-io/thanos/pull/4856

**Comment by GiedriusS** [comment]
@jessicalins thank you for your work! I think we can close this now :muscle:
