### ISSUE TITLE
compact does not delete expired blocks in s3

### ISSUE THREAD

**Issue by diemus** [thanos-io/thanos#3436]
thanos version 0.16.0

```
thanos compact 
--wait 
--compact.concurrency=32 
--data-dir=/data/thanos-compact 
--objstore.config-file=/thanos/bucket.yml 
--retention.resolution-raw=30d 
--retention.resolution-5m=30d 
--retention.resolution-1h=30d
```

the oldest block is 2020-09-18 when I start using object storage, it's about 2 month ago. yet the block is still there. the size of object storage is keep growing, and I didn't see any log about deleting blocks in compact.  only `marking compacted block for deletion`. is there anything wrong?

**Comment by diemus** [comment]
`thanos tools bucket cleanup` seems work, but I thought it should be a work for compact

**Comment by GiedriusS** [comment]
Cleaning up used to happen only at the end of an iteration. Has it ever finished one? The current Thanos version does that concurrently in addition to one time cleanup on boot. Only retention policies are applied at the end.

**Comment by diemus** [comment]
the log shows nothing to do for a long time
```
level=info ts=2020-11-13T01:44:28.111577438Z caller=fetcher.go:453 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.523405394s cached=6764 returned=6764 partial=1
level=info ts=2020-11-13T01:45:27.865940917Z caller=fetcher.go:453 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.27885666s cached=6764 returned=6764 partial=1
level=info ts=2020-11-13T01:46:28.203166318Z caller=fetcher.go:453 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.616543013s cached=6765 returned=6765 partial=1
level=info ts=2020-11-13T01:47:28.173953351Z caller=fetcher.go:453 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.587369586s cached=6765 returned=6765 partial=1
level=info ts=2020-11-13T01:48:28.125676465Z caller=fetcher.go:453 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.538805653s cached=6765 returned=6765 partial=1
level=info ts=2020-11-13T01:49:28.247706551Z caller=fetcher.go:453 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.661060133s cached=6765 returned=6765 partial=1
level=info ts=2020-11-13T01:50:27.920338715Z caller=fetcher.go:453 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.333640673s cached=6765 returned=6765 partial=1
level=info ts=2020-11-13T01:51:28.07630018Z caller=fetcher.go:453 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.489110364s cached=6765 returned=6765 partial=1
level=info ts=2020-11-13T01:52:28.029436084Z caller=fetcher.go:453 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.442636106s cached=6765 returned=6765 partial=1
level=info ts=2020-11-13T01:53:30.970500945Z caller=fetcher.go:453 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=5.383400221s cached=6765 returned=6765 partial=1
level=info ts=2020-11-13T01:54:27.860106108Z caller=fetcher.go:453 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.273630935s cached=6765 returned=6765 partial=1
level=info ts=2020-11-13T01:55:27.80910023Z caller=fetcher.go:453 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.222031408s cached=6765 returned=6765 partial=1
level=info ts=2020-11-13T01:56:27.690576515Z caller=fetcher.go:453 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.103269366s cached=6766 returned=6766 partial=1
level=info ts=2020-11-13T01:57:28.177227392Z caller=fetcher.go:453 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.590467052s cached=6766 returned=6766 partial=1
level=info ts=2020-11-13T01:58:27.986121338Z caller=fetcher.go:453 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.398838272s cached=6766 returned=6766 partial=1
level=info ts=2020-11-13T01:59:28.13868311Z caller=fetcher.go:453 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.550371056s cached=6766 returned=6766 partial=1
level=info ts=2020-11-13T02:00:28.203230738Z caller=fetcher.go:453 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.61610033s cached=6766 returned=6766 partial=1
level=info ts=2020-11-13T02:01:28.200301023Z caller=fetcher.go:453 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.613524653s cached=6766 returned=6766 partial=1
level=info ts=2020-11-13T02:02:27.834959614Z caller=fetcher.go:453 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.24789892s cached=6766 returned=6766 partial=1
level=info ts=2020-11-13T02:03:28.460833533Z caller=fetcher.go:453 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.873806921s cached=6766 returned=6766 partial=1
level=info ts=2020-11-13T02:04:27.712386276Z caller=fetcher.go:453 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.125585756s cached=6766 returned=6766 partial=1
level=info ts=2020-11-13T02:05:27.770157862Z caller=fetcher.go:453 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.182509793s cached=6766 returned=6766 partial=1
level=info ts=2020-11-13T02:06:27.950000374Z caller=fetcher.go:453 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=2.362901017s cached=6767 returned=6767 partial=1
```

I think this means a lot of iterations? 

the log does shows `start of GC` at the boot, but no cleanup actually happened since the first line of log.

**Comment by diemus** [comment]
I run `thanos tools bucket cleanup` to clean up manually. but it's seems only grouped blocks are mark as delete. the oldest data is still 2020-09-18. looks like the retention is now working as expect.

**Comment by fightdou** [comment]
I have the same problem. The data stored in the object will not be deleted

**Comment by GiedriusS** [comment]
All, what is the metric `thanos_compact_iterations_total` equal to on your Thanos Compactor instance(-s)?

**Comment by diemus** [comment]
`thanos_compactor_iterations_total=0`
`thanos_compactor_retries_total=10`

**Comment by diemus** [comment]
I notice 2 things. might related to this issue.

1. the compact does not downsample metrics. I have to run `thanos tools bucket downsample` to downsample.
2. the bucket viewer shows not all blocks are grouped, blocks upload by thanos ruler are not grouped. the duration of these blocks are 10minutes. is this the reason why `thanos_compactor_iterations_total=0` ?

**Comment by diemus** [comment]
found some errors in the log
```
level=error ts=2020-11-14T11:11:17.061560166Z caller=compact.go:375 msg="critical error detected; halting" err="compaction: group 0@6881101226606891260: compact blocks [/home/work/data/thanos-compact/compact/0@6881101226606891260/01EP7S24YSCAQZWZCMG2DFNS4J /home/work/data/thanos-compact/compact/0@6881101226606891260/01EP7WK96Z0G8BHKRAXP96XNC1 /home/work/data/thanos-compact/compact/0@6881101226606891260/01EP802RYC4BKQX1Q974V03965 /home/work/data/thanos-compact/compact/0@6881101226606891260/01EP83GY7A6CY5CCJPZB5MFBMH /home/work/data/thanos-compact/compact/0@6881101226606891260/01EP873HKNE28YM8JTRHZ00YKN /home/work/data/thanos-compact/compact/0@6881101226606891260/01EP8ARNDBKQ1AFCQ7BHHF2G9E]: populate block: chunk iter: cannot populate chunk 172067127071: segment doesn't include enough bytes to read the chunk - required:268435459, available:268435456"
level=error ts=2020-11-18T20:53:31.666989085Z caller=runutil.go:98 msg="function failed. Retrying in next tick" err="incomplete view: 11 errors: meta.json file exists: 01EQ0SM49MRX0VYZHVZEDDH23S/meta.json: stat s3 object: Last-Modified time format is invalid, failed with parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\"; meta.json file exists: 01EQ0WKSXKKCWQ7Z0N3DZJVCJK/meta.json: stat s3 object: Last-Modified time format is invalid, failed with parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\"; meta.json file exists: 01EM0AVWF9D6DX5H9282T7W66M/meta.json: stat s3 object: Last-Modified time format is invalid, failed with parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\"; meta.json file exists: 01EQ0XM9BG35VFHQYWPD4H38FF/meta.json: stat s3 object: Last-Modified time format is invalid, failed with parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\"; meta.json file exists: 01EQ10D2XSDMHG46AVVX5YS8DW/meta.json: stat s3 object: Last-Modified time format is invalid, failed with parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\"; meta.json file exists: 01EQ1076Y7KFWDPHEME2NF6SYH/meta.json: stat s3 object: Last-Modified time format is invalid, failed with parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\"; meta.json file exists: 01EQ10D11FPV0AS1XS1FRA41C7/meta.json: stat s3 object: Last-Modified time format is invalid, failed with parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\"; meta.json file exists: 01EQ0WFNFGK9NHX8QGFYA68B7C/meta.json: stat s3 object: Last-Modified time format is invalid, failed with parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\"; meta.json file exists: 01EQ1124ZEJGFXR8Q9HHKVH421/meta.json: stat s3 object: Last-Modified time format is invalid, failed with parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\"; meta.json file exists: 01EQ0WN5DXXBX10ZN9ZCK61CFK/meta.json: stat s3 object: Last-Modified time format is invalid, failed with parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\"; meta.json file exists: 01EQ0TRR5MMK542WM00X2YXPCS/meta.json: stat s3 object: Last-Modified time format is invalid, failed with parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\""
level=error ts=2020-11-20T14:55:28.574462775Z caller=runutil.go:98 msg="function failed. Retrying in next tick" err="incomplete view: meta.json file exists: 01EKZFCZET1CBJPT5C0GKA89AM/meta.json: stat s3 object: 505 HTTP Version Not Supported"
level=error ts=2020-11-20T15:38:27.650442268Z caller=runutil.go:98 msg="function failed. Retrying in next tick" err="incomplete view: meta.json file exists: 01EQAPX9SV7CK9H7RPZ2DZ2301/meta.json: stat s3 object: 505 HTTP Version Not Supported"
```

this one seems stop the group process
```
populate block: chunk iter: cannot populate chunk 172067127071: segment doesn't include enough bytes to read the chunk - required:268435459, available:268435456"
```

after this error, the log start repeat `successfully synchronized block metadata` for a lot of days. seems like it stucked

**Comment by kaynAw** [comment]
same problem

**Comment by fightdou** [comment]
I tested a single-node thanos v0.17.0 environment，thanos-compact can delete S3 bucket data...

`level=info ts=2020-11-24T08:01:26.258631836Z caller=compact.go:936 msg="start sync of metas"
level=info ts=2020-11-24T08:01:26.303412663Z caller=fetcher.go:458 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=3.024905ms cached=1 returned=1 partial=0
level=info ts=2020-11-24T08:01:26.34530078Z caller=fetcher.go:458 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=86.622598ms cached=1 returned=1 partial=0
level=info ts=2020-11-24T08:01:26.470754674Z caller=fetcher.go:458 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=125.359621ms cached=1 returned=1 partial=0
level=info ts=2020-11-24T08:01:26.470880159Z caller=compact.go:941 msg="start of GC"
level=info ts=2020-11-24T08:01:26.470944094Z caller=compact.go:953 msg="start of compactions"
level=info ts=2020-11-24T08:01:26.471131796Z caller=compact.go:985 msg="compaction iterations done"
level=info ts=2020-11-24T08:01:26.471208797Z caller=compact.go:371 msg="start first pass of downsampling"
level=info ts=2020-11-24T08:01:26.595277568Z caller=fetcher.go:458 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=124.026076ms cached=1 returned=1 partial=0
level=info ts=2020-11-24T08:01:26.595449868Z caller=compact.go:385 msg="start second pass of downsampling"
level=info ts=2020-11-24T08:01:26.721778942Z caller=fetcher.go:458 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=126.277866ms cached=1 returned=1 partial=0
level=info ts=2020-11-24T08:01:26.721984591Z caller=compact.go:392 msg="downsampling iterations done"
level=info ts=2020-11-24T08:01:26.847231516Z caller=fetcher.go:458 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=125.195727ms cached=1 returned=1 partial=0
level=info ts=2020-11-24T08:01:26.847365726Z caller=retention.go:31 msg="start optional retention"
level=info ts=2020-11-24T08:01:26.847417008Z caller=retention.go:40 msg="applying retention: marking block for deletion" id=01EQWGTM62D2GN97FABWN5A0G4 maxTime="2020-11-24 14:00:00 +0800 CST"
level=info ts=2020-11-24T08:01:26.854412627Z caller=block.go:161 msg="block has been marked for deletion" block=01EQWGTM62D2GN97FABWN5A0G4
level=info ts=2020-11-24T08:01:26.854467887Z caller=retention.go:46 msg="optional retention apply done"
level=info ts=2020-11-24T08:01:26.854484206Z caller=clean.go:33 msg="started cleaning of aborted partial uploads"
level=info ts=2020-11-24T08:01:26.854505452Z caller=clean.go:60 msg="cleaning of aborted partial uploads done"
level=info ts=2020-11-24T08:01:26.854634517Z caller=blocks_cleaner.go:43 msg="started cleaning of blocks marked for deletion"
level=info ts=2020-11-24T08:01:26.854670936Z caller=blocks_cleaner.go:57 msg="cleaning of blocks marked for deletion done"`

But a multi-node environment，thanos-compact have an error

`level=error ts=2020-11-23T18:06:28.582780892Z caller=compact.go:428 msg="critical error detected; halting" err="compaction: group 0@14654282991414940297: pre compaction overlap check: overlaps found while gathering blocks. [mint: 1606142128021, maxt: 1606147200000, range: 1h24m31s, blocks: 3]: <ulid: 01EQV2SE8JTHT5QGEN82MDA1T9, mint: 1606142127271, maxt: 1606147200000, range: 1h24m32s>, <ulid: 01EQV2SF64WQ7HDQ7766HDMGN4, mint: 1606142127585, maxt: 1606147200000, range: 1h24m32s>, <ulid: 01EQV2SGVJ3FPXHXGYTD5BY6E1, mint: 1606142128021, maxt: 1606147200000, range: 1h24m31s>"
`

**Comment by Shadi** [comment]
Have you tried the latest version(0.17.0)? I see in the changelog that #3115  was part of that release and it should decouple blocks deletion from compaction iterations.

**Comment by diemus** [comment]
the problem is not to clean the expired blocks. it's seems the retention policy is not work. so the block is not mark for deletion

**Comment by GiedriusS** [comment]
> found some errors in the log
> 
> ```
> level=error ts=2020-11-14T11:11:17.061560166Z caller=compact.go:375 msg="critical error detected; halting" err="compaction: group 0@6881101226606891260: compact blocks [/home/work/data/thanos-compact/compact/0@6881101226606891260/01EP7S24YSCAQZWZCMG2DFNS4J /home/work/data/thanos-compact/compact/0@6881101226606891260/01EP7WK96Z0G8BHKRAXP96XNC1 /home/work/data/thanos-compact/compact/0@6881101226606891260/01EP802RYC4BKQX1Q974V03965 /home/work/data/thanos-compact/compact/0@6881101226606891260/01EP83GY7A6CY5CCJPZB5MFBMH /home/work/data/thanos-compact/compact/0@6881101226606891260/01EP873HKNE28YM8JTRHZ00YKN /home/work/data/thanos-compact/compact/0@6881101226606891260/01EP8ARNDBKQ1AFCQ7BHHF2G9E]: populate block: chunk iter: cannot populate chunk 172067127071: segment doesn't include enough bytes to read the chunk - required:268435459, available:268435456"
> level=error ts=2020-11-18T20:53:31.666989085Z caller=runutil.go:98 msg="function failed. Retrying in next tick" err="incomplete view: 11 errors: meta.json file exists: 01EQ0SM49MRX0VYZHVZEDDH23S/meta.json: stat s3 object: Last-Modified time format is invalid, failed with parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\"; meta.json file exists: 01EQ0WKSXKKCWQ7Z0N3DZJVCJK/meta.json: stat s3 object: Last-Modified time format is invalid, failed with parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\"; meta.json file exists: 01EM0AVWF9D6DX5H9282T7W66M/meta.json: stat s3 object: Last-Modified time format is invalid, failed with parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\"; meta.json file exists: 01EQ0XM9BG35VFHQYWPD4H38FF/meta.json: stat s3 object: Last-Modified time format is invalid, failed with parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\"; meta.json file exists: 01EQ10D2XSDMHG46AVVX5YS8DW/meta.json: stat s3 object: Last-Modified time format is invalid, failed with parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\"; meta.json file exists: 01EQ1076Y7KFWDPHEME2NF6SYH/meta.json: stat s3 object: Last-Modified time format is invalid, failed with parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\"; meta.json file exists: 01EQ10D11FPV0AS1XS1FRA41C7/meta.json: stat s3 object: Last-Modified time format is invalid, failed with parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\"; meta.json file exists: 01EQ0WFNFGK9NHX8QGFYA68B7C/meta.json: stat s3 object: Last-Modified time format is invalid, failed with parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\"; meta.json file exists: 01EQ1124ZEJGFXR8Q9HHKVH421/meta.json: stat s3 object: Last-Modified time format is invalid, failed with parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\"; meta.json file exists: 01EQ0WN5DXXBX10ZN9ZCK61CFK/meta.json: stat s3 object: Last-Modified time format is invalid, failed with parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\"; meta.json file exists: 01EQ0TRR5MMK542WM00X2YXPCS/meta.json: stat s3 object: Last-Modified time format is invalid, failed with parsing time \"\" as \"Mon, 02 Jan 2006 15:04:05 GMT\": cannot parse \"\" as \"Mon\""
> level=error ts=2020-11-20T14:55:28.574462775Z caller=runutil.go:98 msg="function failed. Retrying in next tick" err="incomplete view: meta.json file exists: 01EKZFCZET1CBJPT5C0GKA89AM/meta.json: stat s3 object: 505 HTTP Version Not Supported"
> level=error ts=2020-11-20T15:38:27.650442268Z caller=runutil.go:98 msg="function failed. Retrying in next tick" err="incomplete view: meta.json file exists: 01EQAPX9SV7CK9H7RPZ2DZ2301/meta.json: stat s3 object: 505 HTTP Version Not Supported"
> ```
> 
> this one seems stop the group process
> 
> ```
> populate block: chunk iter: cannot populate chunk 172067127071: segment doesn't include enough bytes to read the chunk - required:268435459, available:268435456"
> ```
> 
> after this error, the log start repeat `successfully synchronized block metadata` for a lot of days. seems like it stucked

What implementation of S3 are you using? Sounds like it doesn't implement the API properly

**Comment by diemus** [comment]
it's an object storage service from my company and it implements S3 api. but I don't think its an error from implementation. most of the request are successful.  the compactor can compact blocks. it just the retention policy not work, no `deletion-mark.json` have been upload to that block.

**Comment by Kampe** [comment]
Seeing the same issues with GCP.

**Comment by boernd** [comment]
Think having the same issue. Using Openstack Swift via S3 API.

I see folders which contain the `deletion-mark.json` file but do not get deleted. `thanos_compact_iterations_total` stays `0`.

Example logs:
```
level=info ts=2020-12-02T09:56:58.988832547Z caller=compact.go:832 group="0@{...}" groupKey=0@14286684522565178406 msg="marking compacted block for deletion" old_block=01ENMMJ6P2SCD8VGFDDPWAEG7W
level=info ts=2020-12-02T09:56:59.083118519Z caller=block.go:161 group="0@{...}" groupKey=0@14286684522565178406 msg="block has been marked for deletion" block=01ENMMJ6P2SCD8VGFDDPWAEG7W

[...]

level=info ts=2020-12-02T10:00:49.433886158Z caller=clean.go:33 msg="started cleaning of aborted partial uploads"
level=info ts=2020-12-02T10:00:49.434803067Z caller=clean.go:60 msg="cleaning of aborted partial uploads done"
level=info ts=2020-12-02T10:00:49.43481784Z caller=blocks_cleaner.go:43 msg="started cleaning of blocks marked for deletion"
level=info ts=2020-12-02T10:00:49.434852027Z caller=blocks_cleaner.go:57 msg="cleaning of blocks marked for deletion done"
```

**Comment by diemus** [comment]
after I delete some blocks manually, the compactor now works as expected. I think there are some blocks with some problems that stop the compactor from working

**Comment by diemus** [comment]
I extract the code that I can apply the retention manually, I think it might help people with the same problem.

```go
package main

import (
	"context"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/prometheus/common/model"
	"github.com/prometheus/prometheus/pkg/relabel"
	"github.com/thanos-io/thanos/pkg/block"
	"github.com/thanos-io/thanos/pkg/compact"
	"github.com/thanos-io/thanos/pkg/logging"
	"github.com/thanos-io/thanos/pkg/objstore/client"
	"time"
)

func main() {
	filter := block.NewLabelShardedMetaFilter([]*relabel.Config{
		{
			SourceLabels: []model.LabelName{"thanos"},
			Action:       relabel.Keep,
			Regex:        relabel.MustNewRegexp(".*"),
		},
	})

	filters := []block.MetadataFilter{filter}

	logger := logging.NewLogger("debug", "logfmt", "test")
	ctx := context.TODO()

	retentionByResolution := map[compact.ResolutionLevel]time.Duration{
		compact.ResolutionLevelRaw: 30 * 24 * time.Hour,
		compact.ResolutionLevel5m:  30 * 24 * time.Hour,
		compact.ResolutionLevel1h:  30 * 24 * time.Hour,
	}

	confContentYaml := `
type: S3
config:
 bucket: "xxxxxx"
 endpoint: "xxxxx"
 access_key: "xxxxx"
 secret_key: "xxxxxx"
 signature_version2: true
 insecure: false
`

	bkt, err := client.NewBucket(logger, []byte(confContentYaml), nil, "aaa")
	if err != nil {
		logger.Log("msg", err)
		return
	}

	metaFetcher, err := block.NewMetaFetcher(logger, 32, bkt, "", nil, filters, nil)
	if err != nil {
		logger.Log("msg", err)
		return
	}

	blocksMarkedForDeletion := promauto.With(nil).NewCounter(prometheus.CounterOpts{})

	metas, _, err := metaFetcher.Fetch(ctx)
	if err != nil {
		logger.Log("msg", err)
		return
	}

	err = compact.ApplyRetentionPolicyByResolution(ctx, logger, bkt, metas, retentionByResolution, blocksMarkedForDeletion)
	if err != nil {
		logger.Log("msg", err)
		return
	}
}

```

**Comment by diemus** [comment]
the problems shows again, I have a strong feelings it's casued by some blocks with same time range. because this section of blocks are not grouped when other blocks are still grouping, this block may cause compactor stuck, I have to add a crontab to restart it every 6 hour.

The extra block was created in a migration of prometheus instance, it create 2 blocks with same time range.  one has 2 hours duration the other has less than one hour.

![image](https://user-images.githubusercontent.com/9145160/105968210-bf567100-60c1-11eb-81ea-ba9ba0fe22b8.png)

**Comment by diemus** [comment]
I delete the block with same time range, and it works again

**Comment by kakkoyun** [comment]
@diemus Do you think it is worth adding that code piece as a tool until we find the cause and fix the issue?

**Comment by diemus** [comment]
@kakkoyun I think it might help people who does not know how to run that code piece. as it for now, users can not find another way to delete expired blocks when compactor does not work as expected

**Comment by rsommer** [comment]
We are encountering similar problems. Compactor is running with the following settings:
`thanos compact --data-dir /var/cache/thanos --objstore.config-file /etc/prometheus/object_store.yml --retention.resolution-raw=30d --retention.resolution-5m=26w --retention.resolution-1h=26w --wait --deduplication.replica-label=replica --deduplication.func=penalty`
(the deduplication flags have just been added after the last update to 0.22)

From the thanos bucket view, there seem to be several problems:
![thanos_bucket_view](https://user-images.githubusercontent.com/178013/133751293-2e6be082-4798-4d23-9f7b-59cf834907f5.png)

At first, old blocks are not deleted, there should be no blocks older than 26 weeks.

But second (aside the time problems), I would expect to see blocks of all levels over the whole time period, not just for August 2020.

As far as I can see, there are no errors in the logs. Even if I run a manual cleanup, no error is logged but the blocks are not deleted.

The underlying object store is S3 on ceph with radosgw if that is of any importance.

**Comment by JohanElmis** [comment]
We have similar issues on a Google bucket: (Compact View in the graph).
All the raw-blocks still exist - even if the retention is set to only keep them for 8 days.
I have not tried to do any forced cleanup with the cmd. All? the old blocks contains a deletion-mark file.
We did have storage loading-issues before which seems to have been caused by that we used a single MemcacheD cache for several store-components (fetching data from AWS S3 and GCP store, but 1 cache).
Despite different global labels - it seems like it looked in the wrong place if the cache was in use.
Maybe messed up the cleanup due to this. Will do some more investigations.
<img width="2552" alt="Screenshot 2021-09-29 at 13 56 45" src="https://user-images.githubusercontent.com/3820361/135263916-46a8726a-e473-4114-b28b-6eea78154c52.png">

**Comment by yuanhuaiwang** [comment]
e are encountering similar problems

**Comment by yuanhuaiwang** [comment]
> Closing for now as promised, let us know if you need this to be reopened! 🤗

reopen

**Comment by yeya24** [comment]
@yuanhuaiwang Does https://thanos.io/tip/operating/compactor-backlog.md/ work for you?

**Comment by yeya24** [comment]
I will close this issue as it is not a bug, rather a scaling issue. For solving this problem https://thanos.io/tip/operating/compactor-backlog.md/ could help.
