### ISSUE TITLE
Error of "found that TSDB Max time is 1d12h and Min time is 2h. Compaction needs to be disabled" 

### ISSUE THREAD

**Issue by t2833813** [thanos-io/thanos#3447]
I am all new to thanos and Prometheus. When I download thanos and run Prometheus and try to use thanos to upload the data to Amazon S3, I have:

level=error ts=2020-11-15T08:33:49.801360398Z caller=main.go:171 err="yaml: unmarshal errors:\n  line 9: field list_objects_version not found in type s3.Config\ncreate S3 client\ngithub.com/thanos-io/thanos/pkg/objstore/client.NewBucket\n\t/app/pkg/objstore/client/factory.go:77\nmain.runSidecar\n\t/app/cmd/thanos/sidecar.go:237\nmain.registerSidecar.func1\n\t/app/cmd/thanos/sidecar.go:61\nmain.main\n\t/app/cmd/thanos/main.go:169\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\npreparing sidecar command failed\nmain.main\n\t/app/cmd/thanos/main.go:171\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"

I imagine it to be the problem of list_object_version, so I delete the line in yaml but got another error:

level=error ts=2020-11-15T08:47:05.562438869Z caller=main.go:197 err="found that TSDB Max time is 1d12h and Min time is 2h. Compaction needs to be disabled (storage.tsdb.min-block-duration = storage.tsdb.max-block-duration)\nmain.validatePrometheus\n\t/app/cmd/thanos/sidecar.go:319\nmain.runSidecar.func3\n\t/app/cmd/thanos/sidecar.go:137\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nvalidate Prometheus flags\nmain.runSidecar.func3\n\t/app/cmd/thanos/sidecar.go:138\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nsidecar command failed\nmain.main\n\t/app/cmd/thanos/main.go:197\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"

Is there anyone having clues for the situation I encountered? Thanks!

**Comment by GiedriusS** [comment]
Hi! The first "problem" happens because you are using a parameter that is only available in `v0.17.0-rc.0` and newer versions. The second "problem" happens because you haven't disabled compaction on the Prometheus side like the error message says. `--storage.tsdb.min-block-duration` needs to be equal to `--storage.tsdb.max-block-duration`. You can read more here: https://thanos.io/v0.4/components/sidecar/#deployment. Please close this issue if this helps!
