### ISSUE TITLE
web.enable-admin-api flag is not required for thanos sidecar

### ISSUE THREAD

**Issue by dudicoco** [thanos-io/thanos#3449]
Hi,

According to the documentation the the --web.enable-admin-api flag is required to allow sidecar to get metadata from Prometheus like external labels: https://github.com/thanos-io/thanos/blob/master/docs/components/sidecar.md

I've deployed the sidecar without the flag and experienced no issues in getting the external labels:
```
level=info ts=2020-11-15T14:16:48.550816681Z caller=sidecar.go:155 msg="successfully loaded prometheus external labels" external_labels="{prometheus_replica=\"prometheus-server-1\"}"
level=info ts=2020-11-15T14:16:48.550853162Z caller=intrumentation.go:48 msg="changing probe status" status=ready
```

Is the flag unnecessary?

Thanks

**Comment by yeya24** [comment]
Hi, this flag is not required and I think the doc is outdated. 
This issue duplicates with https://github.com/thanos-io/thanos/issues/3278 so I will close it.
If u still have questions about this, feel free to reopen the issue.

**Comment by dudicoco** [comment]
Thanks @yeya24
