### ISSUE TITLE
Thanos Store consumes so much memory when I query metrics based on 5 days and beyond

### ISSUE THREAD

**Issue by heartTorres** [thanos-io/thanos#3450]
Hi, 

I have set up Thanos components in our prod environment with the following replica numbers below.
1 - Thanos Store, 
5 - Thanos Receivers
1 -  Thanos Query

When I do query metrics atleast 24 hours from Grafana, the Thanos-Store consumes 10Gi ++ of RAM and eventually gets OOMKilled. 
We would like to query metric data atleast 30 days ago (as part of the requirements). But 24 hours already consumes a lot of memory. Is this an expected behavior?

Morever, querying in grafana with absolute time range for 7 days returns incomplete graph, there is no data shown in the graph even though I have data objects in in S3 since **November 8**, as shown on the images. But querying atleast **4 days** of data absolute time range, graphs are complete. See images below. Is this an expected behavior as well? max of 4 days in the time range for the query to work?

<img width="1070" alt="Screen Shot 2020-11-17 at 12 59 30 PM" src="https://user-images.githubusercontent.com/65100615/99348549-d19f7c00-28d4-11eb-8065-f8685105856f.png">

Continuing increasing the RAM might not be a good option for us as it is not cost efficient.
<img width="1327" alt="Screen Shot 2020-11-17 at 12 57 28 PM" src="https://user-images.githubusercontent.com/65100615/99348417-7c636a80-28d4-11eb-93f6-784eafa9149d.png">

**Comment by GiedriusS** [comment]
> Hi,
> 
> I have set up Thanos components in our prod environment with the following replica numbers below.
> 1 - Thanos Store,
> 5 - Thanos Receivers
> 1 - Thanos Query
> 
> When I do query metrics atleast 24 hours from Grafana, the Thanos-Store consumes 10Gi ++ of RAM and eventually gets OOMKilled.
> We would like to query metric data atleast 30 days ago (as part of the requirements). But 24 hours already consumes a lot of memory. Is this an expected behavior?
> 
> Morever, querying in grafana with absolute time range for 7 days returns incomplete graph, there is no data shown in the graph even though I have data objects in in S3 since **November 8**, as shown on the images. But querying atleast **4 days** of data absolute time range, graphs are complete. See images below. Is this an expected behavior as well? max of 4 days in the time range for the query to work?
> 
> <img alt="Screen Shot 2020-11-17 at 12 59 30 PM" width="1070" src="https://user-images.githubusercontent.com/65100615/99348549-d19f7c00-28d4-11eb-8065-f8685105856f.png">
> 
> Continuing increasing the RAM might not be a good option for us as it is not cost efficient.
> <img alt="Screen Shot 2020-11-17 at 12 57 28 PM" width="1327" src="https://user-images.githubusercontent.com/65100615/99348417-7c636a80-28d4-11eb-93f6-784eafa9149d.png">

Hi! Are you running Thanos Compactor?

**Comment by heartTorres** [comment]
> > Hi,
> > I have set up Thanos components in our prod environment with the following replica numbers below.
> > 1 - Thanos Store,
> > 5 - Thanos Receivers
> > 1 - Thanos Query
> > When I do query metrics atleast 24 hours from Grafana, the Thanos-Store consumes 10Gi ++ of RAM and eventually gets OOMKilled.
> > We would like to query metric data atleast 30 days ago (as part of the requirements). But 24 hours already consumes a lot of memory. Is this an expected behavior?
> > Morever, querying in grafana with absolute time range for 7 days returns incomplete graph, there is no data shown in the graph even though I have data objects in in S3 since **November 8**, as shown on the images. But querying atleast **4 days** of data absolute time range, graphs are complete. See images below. Is this an expected behavior as well? max of 4 days in the time range for the query to work?
> > <img alt="Screen Shot 2020-11-17 at 12 59 30 PM" width="1070" src="https://user-images.githubusercontent.com/65100615/99348549-d19f7c00-28d4-11eb-8065-f8685105856f.png">
> > Continuing increasing the RAM might not be a good option for us as it is not cost efficient.
> > <img alt="Screen Shot 2020-11-17 at 12 57 28 PM" width="1327" src="https://user-images.githubusercontent.com/65100615/99348417-7c636a80-28d4-11eb-93f6-784eafa9149d.png">
> 
> Hi! Are you running Thanos Compactor?

Hi, thanks for the reply. I have implemented time-based partitioning for Thanos Store. But I have not installed/deployed Thanos Compactor. I will try to install this and see if it would resolve our issue in prod.

**Comment by heartTorres** [comment]
Hi, I have already installed thanos compactor and time based partitioning in thanos store. But the problem still persists. The longer the time range, the bigger cpu it eats up and eventually gets killed. Screenshots below.

**Resources I alloted for Thanos Store:**
<img width="337" alt="Screen Shot 2020-11-20 at 3 11 26 PM" src="https://user-images.githubusercontent.com/65100615/99771561-50e6b700-2b44-11eb-9d9f-4e111c72d544.png">

**When I tried to query atleast 3 weeks data range:**
It consumed almost 4Gi of cpu, then it get oomkilled later on.
<img width="457" alt="Screen Shot 2020-11-20 at 3 13 13 PM" src="https://user-images.githubusercontent.com/65100615/99771647-6eb41c00-2b44-11eb-8e01-87569a1e49e1.png">

Also, it only shows incomplete data in grafana dashboard when I query data in range of 3 weeks:
I have data in S3, yet seems data are not correctly being retrieved from Thanos Store.

<img width="1339" alt="Screen Shot 2020-11-20 at 7 07 57 PM" src="https://user-images.githubusercontent.com/65100615/99795885-7fc25480-2b67-11eb-8770-cd94d45375aa.png">


But when I query in 5 days of data, graph is complete in grafana.
<img width="1335" alt="Screen Shot 2020-11-20 at 7 06 53 PM" src="https://user-images.githubusercontent.com/65100615/99795609-032f7600-2b67-11eb-9d81-4b36916efa9f.png">

**Comment by heartTorres** [comment]
I have already installed thanos-compactor and  added chunk-pool-size in thanos store, retention.resolution-raw=30d yet the Thanos Store still eats up 4Gi for CPU and 12Gi of RAM just to query 21 days of data, then gets oomkilled.

**Comment by heartTorres** [comment]
We have no choice but to increase the resource server, from 12Gi RAM we upgraded it to 32Gi RAM, just to achieve our requirements to query full metric data of 30 days. Since our 2 replicas Thanos-Store eats 7-8Gi RAM when query range is just 7 days. (Not cost efficient though) :(

**Comment by kakkoyun** [comment]
@heartTorres Could you please share your compactor and store configurations/flags? Depends on your data store could go heavy on memory. Also could you please check and share the level of compactions from your Bucket viewer UI?

That said, I highly recommend `hashmod` sharding for horizontal scalability of the store. It works pretty well for our data which considerably large data set. e.g https://github.com/thanos-io/kube-thanos/blob/master/jsonnet/kube-thanos/kube-thanos-store-shards.libsonnet

**Comment by heartTorres** [comment]
Hi sorry for the late reply. Below are the configs in my store and compactor.

Store:
      - args:
        - store
        - --log.level=warn
        - --data-dir=/var/thanos/store
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --objstore.config=$(OBJSTORE_CONFIG)
        - --min-time=-4w
        - --max-time=-3h
        - --chunk-pool-size=16GB
        - --index-cache-size=16GB

Compactor:
      - args:
        - compact
        - --wait
        - --log.level=info
        - --objstore.config=$(OBJSTORE_CONFIG)
        - --data-dir=/var/thanos/compact
        - --debug.accept-malformed-index
        - --retention.resolution-raw=30d

We are now able to query 30 days of data, however, we have dedicated 2 servers with 64GB Memory and 32G RAM just to achieve it. It is somehow expensive for resources. Our data is 320-327GB of data for a 30d metrics.
