### ISSUE TITLE
receive: too large gRPC message

### ISSUE THREAD

**Issue by domino7** [thanos-io/thanos#3453]
Messages sent to Thanos receiver fails when msg size is above 4MB due to gRPC maxRecvMsgSize = 4MB

**Thanos, Prometheus and Golang version used**:
Thanos: 0.15.0
Prometheus: 2.20.0
Golang: 1.15.4

**Object Storage Provider**:
AWS S3

**What happened**:
Messages sent to Thanos receiver fails when msg size is above 4MB due to gRPC maxRecvMsgSize = 4MB: 
`err="forwarding request to endpoint thanos-receiver-prometheus-0:10901: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4194776 vs. 4194304)"`

**What you expected to happen**:
Metrics should be accepted, receiver default grpc maxRecvMsgSize should be increased or make configurable via additional flag,  [code example with fix](https://github.com/SabreOSS/thanos/commit/51f48cace1773f2344c0f5e63896ddf5f004d086)
Problem was fixed after increasing grpc MaxRecvMsgSize to **64MB** in receiver (via additional custom flag).

**How to reproduce it (as minimally and precisely as possible)**:
Start Thanos Receiver, send metrics in grpc messages with size >4MB

**Example logs to relevant components**:

<details>Logs

<p>

```
level=error name=receiver ts=2020-11-12T06:48:36.068665815Z caller=handler.go:331 component=receive component=receive-handler err="forwarding request to endpoint thanos-receiver-prometheus-2:10901: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4850187 vs. 4194304)" msg="internal server error"
level=error name=receiver ts=2020-11-12T06:48:34.988160212Z caller=handler.go:331 component=receive component=receive-handler err="forwarding request to endpoint thanos-receiver-prometheus-0:10901: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4194776 vs. 4194304)" msg="internal server error"
level=error name=receiver ts=2020-11-12T06:48:34.224506555Z caller=handler.go:331 component=receive component=receive-handler err="forwarding request to endpoint thanos-receiver-prometheus-2:10901: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4850187 vs. 4194304)" msg="internal server error"
```

</p>

</details>

**Comment by GiedriusS** [comment]
> Messages sent to Thanos receiver fails when msg size is above 4MB due to gRPC maxRecvMsgSize = 4MB
> 
> **Thanos, Prometheus and Golang version used**:
> Thanos: 0.15.0
> Prometheus: 2.20.0
> Golang: 1.15.4
> 
> **Object Storage Provider**:
> AWS S3
> 
> **What happened**:
> Messages sent to Thanos receiver fails when msg size is above 4MB due to gRPC maxRecvMsgSize = 4MB:
> `err="forwarding request to endpoint thanos-receiver-prometheus-0:10901: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4194776 vs. 4194304)"`
> 
> **What you expected to happen**:
> Metrics should be accepted, receiver default grpc maxRecvMsgSize should be increased or make configurable via additional flag, [code example with fix](https://github.com/SabreOSS/thanos/commit/51f48cace1773f2344c0f5e63896ddf5f004d086)
> Problem was fixed after increasing grpc MaxRecvMsgSize to **64MB** in receiver (via additional custom flag).
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> Start Thanos Receiver, send metrics in grpc messages with size >4MB
> 
> **Example logs to relevant components**:
> Logs

Hi! Hmmm... have you encountered this while using Thanos Receive "normally" or have you followed some steps to reproduce this?

**Comment by norbertwnuk** [comment]
This is happening for rather standard Prometheus instance (2M samples scraped per minute) connected via remote write API, [remote_write](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) configuration itself does not control precise size of individual request (only number of samples), the same time decreasing this value has negative impact on E2E performance. We observe such errors even when max_samples_per_send is in range a few thousands (2-10k), apparently depending on number of labels in individual batch.
