### ISSUE TITLE
store: invalid date for max time causing store to get filtered out in thanos-query

### ISSUE THREAD

**Issue by joshulyne** [thanos-io/thanos#3454]
**Thanos, Prometheus and Golang version used**:
v0.16.0 - thanos
v2.17.1 - prometheus 

**Object Storage Provider**:
cleversafe s3

**What happened**:
thanos-query fails to fetch data past what's available in locally in prometheus. I believe the cause is the thanos-store components not having the proper min/max date. Therefore, the thanos-query component filters out those stores when querying. When I check the UI i see this for the stores:
![Screen Shot 2020-11-16 at 1 15 52 PM](https://user-images.githubusercontent.com/36134271/99309703-b407df00-280e-11eb-9b6e-014ae899fe9f.png)

The stores min and max date are incorrect for some reason even though in the thanos store configurations I have min/max dates set such as:
```
- --min-time=-4d
```
or 
```
- --max-time=-3d
- --min-time=-7d
```
etc...

**Full logs to relevant components**:

thanos-query logs:
<details>Logs
<p>

level=debug ts=2020-11-16T21:18:20.696965979Z caller=proxy.go:283 msg="store Addr: 192.168.233.97:10901 LabelSets:  Mint: 9223372036854775807 Maxt: -9223372036854775808 filtered out;store Addr: 192.168.237.228:10901 LabelSets: {k8s_cluster=\"ashburn-rdei-01\", prometheus=\"monitoring/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\"} Mint: 1602684000000 Maxt: 1603142297731 filtered out;store Addr: 192.168.224.33:10901 LabelSets: {k8s_cluster=\"ashburn-rdei-01\", prometheus=\"monitoring/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\"} Mint: 1603833497731 Maxt: 1604088000000 filtered out;Store Addr: thanos-store-sidecar.monitoring.svc.cluster.local:10901 LabelSets: {k8s_cluster=\"ashburn-rdei-01\", prometheus=\"monitoring/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\"} Mint: 1605528000000 Maxt: 9223372036854775807 queried;store Addr: 192.168.228.249:10901 LabelSets:  Mint: 9223372036854775807 Maxt: -9223372036854775808 filtered out;store Addr: 192.168.228.243:10901 LabelSets:  Mint: 9223372036854775807 Maxt: -9223372036854775808 filtered out;store Addr: 192.168.228.241:10901 LabelSets: {k8s_cluster=\"ashburn-rdei-01\", prometheus=\"monitoring/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\"} Mint: 1602883097731 Maxt: 1604006297731 filtered out"

</p>
</details>

^^ Here, all the datastores are filtered out except for the prometheus datastore (thanos-store-sidecar.monitoring.svc.cluster.local:10901)

Any and all advice would be appreciated for this!

**Comment by GiedriusS** [comment]
> **Thanos, Prometheus and Golang version used**:
> v0.16.0 - thanos
> v2.17.1 - prometheus
> 
> **Object Storage Provider**:
> cleversafe s3
> 
> **What happened**:
> thanos-query fails to fetch data past what's available in locally in prometheus. I believe the cause is the thanos-store components not having the proper min/max date. Therefore, the thanos-query component filters out those stores when querying. When I check the UI i see this for the stores:
> ![Screen Shot 2020-11-16 at 1 15 52 PM](https://user-images.githubusercontent.com/36134271/99309703-b407df00-280e-11eb-9b6e-014ae899fe9f.png)
> 
> The stores min and max date are incorrect for some reason even though in the thanos store configurations I have min/max dates set such as:
> 
> ```
> - --min-time=-4d
> ```
> 
> or
> 
> ```
> - --max-time=-3d
> - --min-time=-7d
> ```
> 
> etc...
> 
> **Full logs to relevant components**:
> 
> thanos-query logs:
> 
> ^^ Here, all the datastores are filtered out except for the prometheus datastore (thanos-store-sidecar.monitoring.svc.cluster.local:10901)
> 
> Any and all advice would be appreciated for this!

It sounds like Thanos Store is unable to synchronize its state with the content of your remote object storage. How do its logs look like?

**Comment by Stevenyu1982** [comment]
i have the same error, even enabled the debug log, but nothing special.

**Comment by Stevenyu1982** [comment]
from the storegateway , 

al=0
level=info ts=2020-11-30T12:12:43.53895406Z caller=fetcher.go:458 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=51.921623ms cached=0 returned=0 partial=0
level=info ts=2020-11-30T12:15:43.538280419Z caller=fetcher.go:458 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=51.226756ms cached=0 returned=0 partial=0
level=info ts=2020-11-30T12:18:43.53874826Z caller=fetcher.go:458 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=51.731658ms cached=0 returned=0 partial=0
level=info ts=2020-11-30T12:21:43.541927883Z caller=fetcher.go:458 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=54.707094ms cached=0 returned=0 partial=0
level=info ts=2020-11-30T12:24:43.538917675Z caller=fetcher.go:458 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=51.914761ms cached=0 returned=0 partial=0

from the thanos query
level=debug ts=2020-11-30T12:27:38.130688686Z caller=proxy.go:283 msg="Store Addr: 172.23.46.20:10901 LabelSets: {prometheus=\"monitoring/prometheus-kube-prometheus-prometheus\", prometheus_replica=\"prometheus-prometheus-kube-prometheus-prometheus-1\"} Mint: -62167219200000 Maxt: 9223372036854775807 queried;Store Addr: 172.18.213.29:10901 LabelSets: {prometheus=\"monitoring/prometheus-kube-prometheus-prometheus\", prometheus_replica=\"prometheus-prometheus-kube-prometheus-prometheus-0\"} Mint: -62167219200000 Maxt: 9223372036854775807 queried;Store Addr: 172.22.200.62:10901 LabelSets: {prometheus=\"monitoring/prometheus-kube-prometheus-prometheus\", prometheus_replica=\"prometheus-prometheus-kube-prometheus-prometheus-2\"} Mint: -62167219200000 Maxt: 9223372036854775807 queried;store Addr: 172.26.116.206:10901 LabelSets:  Mint: 9223372036854775807 Maxt: -9223372036854775808 filtered out;store Addr: 172.30.84.120:10901 LabelSets: {replica=\"thanos-ruler-2\", ruler_cluster=\"NodePort\"} Mint: 9223372036854775807 Maxt: 9223372036854775807 filtered out;store Addr: thanos-storegateway:10901 LabelSets:  Mint: 9223372036854775807 Maxt: -9223372036854775808 filtered out"
level=debug ts=2020-11-30T12:27:38.132042572Z caller=http.go:34 protocol=http http.component=server http.method=query http.request.id=01ERCHYTRJZAJHB6DXP67F6DJJ http.code=200 http.time_ms=1.997 msg="finished call"
level=debug ts=2020-11-30T12:27:40.801165746Z caller=storeset.go:341 component=storeset msg="starting updating storeAPIs" cachedStores=6
level=debug ts=2020-11-30T12:27:40.802258485Z caller=storeset.go:344 component=storeset msg="checked requested storeAPIs" activeStores=6 cachedStores=6

**Comment by yeya24** [comment]
This seems weird. From what I can see, the store cannot fetch any metadata from your bucket. 
Can you try the `thanos tools bucket ls` or `thanos tools bucket inspect` to see whether there are blocks in your object store?

**Comment by shawqi-voice** [comment]
facing the same issue here, adding the flag negative value to the max time `--max-time=-2w` to storegateway showing invalid date in thanos query stores tab

**Comment by amine250** [comment]
Having the same thing here.
Maybe because my s3 bucket doesn't actually hold any data of the given timerange. 

If this is the case, then the "Invalid date" is very very misleading.

**Comment by MrYueQ** [comment]
![image](https://user-images.githubusercontent.com/14846522/132842210-1129af70-c6cf-4d79-85fd-d73d2ebeccf9.png)

```yaml
thanos, version 0.22.0 (branch: HEAD, revision: 3656e290c8eb034e2e09e0afc79f087be88de481)
  build user:       root@61bcfbac7168
  build date:       20210721-15:22:37
  go version:       go1.16.6
  platform:         linux/amd64
```

```yaml
=/data/app/thanos/bin/thanos store --data-dir=/data/thanos \
                --log.format=json \
                --index-cache-size=4096MB  \
                --objstore.config-file=/data/app/thanos/conf.d/object.json \
                --min-time=-3w \
                --max-time=-2h \
                --index-cache.config-file=/data/app/thanos/conf.d/index.json \
                --tracing.config-file=/data/app/thanos/conf.d/trace.jaeger.yml \
                --store.caching-bucket.config-file=/data/app/thanos/conf.d/cache.json
```

**Comment by peetasan** [comment]
Hi, I have a similar issue with min/max time being invalid or infinity, `thanos tools bucket inspect` and `thanos tools bucket verify` return sensible data, no errors, on the web view I can also see that the blocks more or less are compacted in a correct way. 

So while I do have the data in my S3 bucket when I zoom out to more than 24h in Grafana I see no data for older than a couple of hours. (Thanos query points to sidecar as well as the relevant stores gateway)

Would appreciate some hints as to how to display all data in my bucket.

```
Sep 20 13:24:55 thanos-production-a-01 thanos[8572]: level=warn name=query-a ts=2021-09-20T13:24:55.309928886Z caller=proxy.go:279 component=proxy request="min_time:1631538900000 max_time:1631748000000 matchers:<name:\"cluster_name\" value:\"eks-production\" > matchers:<name:\"job\" value:\"prometheus\" > matchers:<name:\"instance\" value:\"prometheus-a\" > matchers:<name:\"__name__\" value:\"prometheus_tsdb_compactions_failed_total\" > max_resolution_window:480000 aggregates:COUNTER " err="No StoreAPIs matched for this query" stores="store Addr: 127.0.0.1:20903 LabelSets: {cluster_name=\"eks-production\", env=\"production\", replica=\"prometheus-a\"},{cluster_name=\"eks-production\", env=\"production\", replica=\"prometheus-b\"},{cluster_name=\"gke-production\", env=\"production\", replica=\"prometheus-a\"},{cluster_name=\"gke-production\", env=\"production\", replica=\"prometheus-b\"} Mint: 1632110400005 Maxt: 9223372036854775807 filtered out: does not have data within this time period: [1631538900000,1631748000000]. Store time ranges: [1632110400005,9223372036854775807];store Addr: <XX>:10901 LabelSets: {replica=\"prometheus-a\"} Mint: 1631959200108 Maxt: 9223372036854775807 filtered out: does not have data within this time period: [1631538900000,1631748000000]. Store time ranges: [1631959200108,9223372036854775807];store Addr: <XX>:10901 LabelSets: {replica=\"prometheus-b\"} Mint: 1631959200025 Maxt: 9223372036854775807 filtered out: does not have data within this time period: [1631538900000,1631748000000]. Store time ranges: [1631959200025,9223372036854775807];store Addr: 127.0.0.1:10905 LabelSets: {cluster_name=\"eks-production\", env=\"production\", replica=\"prometheus-a\"},{cluster_name=\"eks-production\", env=\"production\", replica=\"prometheus-b\"},{replica=\"prometheus-a\"},{replica=\"prometheus-b\"} Mint: 9223372036854775807 Maxt: -9223372036854775808 filtered out: does not have data within this time period: [1631538900000,1631748000000]. Store time ranges: [9223372036854775807,-9223372036854775808];store Addr: 127.0.0.1:10907 LabelSets: {cluster_name=\"gke-production\", env=\"production\", replica=\"prometheus-a\"},{cluster_name=\"gke-production\", env=\"production\", replica=\"prometheus-b\"} Mint: 1626429037862 Maxt: 1632139200000 filtered out: external labels [{cluster_name=\"gke-production\", env=\"production\", replica=\"prometheus-a\"} {cluster_name=\"gke-production\", env=\"production\", replica=\"prometheus-b\"}] does not match request label matchers: [cluster_name=\"eks-production\" job=\"prometheus\" instance=\"prometheus-a\" __name__=\"prometheus_tsdb_compactions_failed_total\"]"
```

**Comment by Khagesh16** [comment]
@yeya24 I am also having same issue. The thanos query is firing with infinite time range. Here is the log for thanos query. I do not see the query even reaching to thanos store. As I do not see any entry in thanos store logs.  

 - Do I need to set the labelSet for thanos store, can you please guide me how to do it?  

` Store Addr: 172.20.129.25:10901
    LabelSets:
    MinTime: 9223372036854775807
    MaxTime: -9223372036854775808
    filtered out due to: does not have data within this time period: [1726768864568,1726769164568].
    Store time ranges: [9223372036854775807,-9223372036854775808]`

**Comment by Khagesh16** [comment]
> This seems weird. From what I can see, the store cannot fetch any metadata from your bucket. Can you try the `thanos tools bucket ls` or `thanos tools bucket inspect` to see whether there are blocks in your object store?

Just gave a try to this, I do not see any blocks. But I do not see any error on thanos store as well. Not sure whats happening.
