### ISSUE TITLE
docs: Create a FAQ section

### ISSUE THREAD

**Issue by kakkoyun** [thanos-io/thanos#3468]
It'd be great to have a frequently asked questions section as part of our official website. Such like https://prometheus.io/docs/introduction/faq/

We are getting similar questions from the community over public slack channels and office hours. We can gather them together and help the community.

cc @bwplotka @brancz

**Comment by adeniyistephen** [comment]
@kakkoyun @bwplotka @brancz Hi, This is great, is they any pointer or input? I would love to work on this, Thanks.

**Comment by DARK-art108** [comment]
Can I work on this?

**Comment by kakkoyun** [comment]
@DARK-art108 @adeniyistephen, Of course, you can work on it. We need to collect those questions first. Slack channels would be a good place to start.

**Comment by adeniyistephen** [comment]
> @DARK-art108 @adeniyistephen, Of course, you can work on it. We need to collect those questions first. Slack channels would be a good place to start.

yes that sounds like a very good idea, what is the slack channel so we cam track does question. Thanks
