### ISSUE TITLE
compact: warn "unsupported type of io.Reader"

### ISSUE THREAD

**Issue by mxmorin** [thanos-io/thanos#3470]
**Thanos, Prometheus and Golang version used**:
```
thanos, version 0.17.0 (branch: HEAD, revision: 4899d9a3378c7dbd1f635f5271624cda8caec001)
  build user:       root@432c5bd5f94c
  build date:       20201118-17:38:06
  go version:       go1.15
  platform:         linux/amd64
```
**What happened**:
Since upgrade to 0.17, warns are printed to log compact file with 
`level=warn ts=2020-11-19T10:44:50.465036587Z caller=s3.go:399 msg="could not guess file size for multipart upload; upload might be not optimized" name=debug/metas/01EQG1MNBMGVW310107ED36HGP.json err="unsupported type of io.Reader
`

**Comment by yeya24** [comment]
Thanks for the reporting. I can see that the upload type is not supported from the code https://github.com/thanos-io/thanos/blob/master/pkg/block/block.go#L106. 

But since it is the debug meta file, so it is not a big problem and we have discussed deprecating this file. Anyway, I can open a pr to fix this.

**Comment by xiaodangjia457** [comment]
> Thanks for the reporting. I can see that the upload type is not supported from the code https://github.com/thanos-io/thanos/blob/master/pkg/block/block.go#L106.
> 
> But since it is the debug meta file, so it is not a big problem and we have discussed deprecating this file. Anyway, I can open a pr to fix this.

hello @yeya24 ,

is there any way can fix this error? i am trying to upload data to Aliyun OSS, always failed and log is : unsupported type of io.Reader, thanks for your reply.
