### ISSUE TITLE
GitPodify Thanos to help out!

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3475]
We are looking for contributors that will enable Thanos GitPod and thus helping with systematic racism (https://twitter.com/Code2040) 

Details: https://twitter.com/gitpod/status/1329141750196277249

Help wanted :hugs:

**Comment by mukul-mehta** [comment]
Hi, I'd like to work on this issue. It'll be my first contribution to this project. I'll get started with reading the docs mentioned on GitPod's website

**Comment by AdamDomagalsky** [comment]
May I take it?

**Comment by bwplotka** [comment]
Go for it!

**Comment by kakkoyun** [comment]
Closed by #3499
