### ISSUE TITLE
Replace promclient with client_golang API

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3479]
Would be nice to use official API, it works quite well recently (plus we maintain it as well) (: 

To replace: https://github.com/thanos-io/thanos/blob/f07d8bc33e10dbc8367fecc6102e07ba2a26334d/pkg/promclient/promclient.go#L483

To use instead: https://github.com/prometheus/client_golang/blob/master/api/prometheus/v1/api.go#L752

Just to reduce maintained code (: 

Help wanted!

**Comment by yeya24** [comment]
I see the `opts QueryOptions` argument in the function signature,  the official API doesn't support our own options like `dedup`, `partial_response`, etc IMO?

**Comment by kakkoyun** [comment]
Still valid and help wanted 🤗
