### ISSUE TITLE
Thanos Receivers eats big memory upon fresh re-installation then stabilize after few minutes

### ISSUE THREAD

**Issue by heartTorres** [thanos-io/thanos#3482]
Thanos v.0.15, rancher/prometheus v.2.17

**Thanos, Prometheus and Golang version used**:

**Object Storage Provider**:
S3
**What happened**:
Our prod is auto scaled. Thanos receivers have terminated due to OOMKilled. I did stop the remote_write from prometheus by deleting the ingress definition and increased the resources. After re-installation, 2 pods of thanos receivers have spiked up its memory to 5Gi++ (image below) when there are no remote write happening at that moment. We waited for around 3-5 minutes then the 2 pods resources have stabilized. Meaning the resources have maintained to 900Mi. That was the only time we routed back the remote_write. Is this an expected behavior? What has caused the thanos receivers to spiked up its resources when there is no remote_write configured yet?

Note* we have around 3000 objects in S3 and our prometheus 1 ULID is 8.9Gi.

**What you expected to happen**:
After re-installation, thanos receivers should have a stabilized resources as there is no remote_write traffic happening.

After fresh reinstallation without remote_write traffic yet.
<img width="821" alt="Screen Shot 2020-11-20 at 1 05 34 PM" src="https://user-images.githubusercontent.com/65100615/99761441-17f11700-2b31-11eb-9d47-c6e2a3b4d8d2.png">

Waited for around 5 mins to check if thanos receivers pods resources have stablized, then routed back the remote_write.
Screenshot below, it has been up for 2 hours. From the first screenshot, the memory without remote write traffic yet has spiked up to 5Gi++.

<img width="440" alt="Screen Shot 2020-11-20 at 1 08 02 PM" src="https://user-images.githubusercontent.com/65100615/99761586-6dc5bf00-2b31-11eb-9fdb-d0aa930b7067.png">

**Comment by bwplotka** [comment]
That's expected behavior due to rebuilding in-mem things from WAL. This is exactly what you can see when you restart Prometheus as we use the same database. You need to leave the memory for a startup, unfortunately. We can definitely try to optimize for it, but the question is, is it really worth it?

Still, we should document this better :hugs: 

We improved it recently, but I think v0.15.0 should have those improvements. 5GB is also really not much though. Some of our production receivers have a limit of 30GB, even though on a normal path they are not using more than 20GB and we ingest almost 2M million series each.

**Comment by heartTorres** [comment]
> That's expected behavior due to rebuilding in-mem things from WAL. This is exactly what you can see when you restart Prometheus as we use the same database. You need to leave the memory for a startup, unfortunately. We can definitely try to optimize for it, but the question is, is it really worth it?
> 
> Still, we should document this better 🤗
> 
> We improved it recently, but I think v0.15.0 should have those improvements. 5GB is also really not much though. Some of our production receivers have a limit of 30GB, even though on a normal path they are not using more than 20GB and we ingest almost 2M million series each.

Thanks for the reply. If this is an expected behavior then I guess, I will just inform my superiors about these facts.

Thank you.
