### ISSUE TITLE
Object storage deployment for MapR

### ISSUE THREAD

**Issue by mohanagandlla** [thanos-io/thanos#3484]
HI,
I have MapR FS system (POSIX client) now how do I deploy the object store for Thanos like any references for writing the MapR based yml config files?
and I am going to deploy the Thanos for Prometheus operator any best guidance?

**Comment by bwplotka** [comment]
You can try https://thanos.io/tip/thanos/storage.md/#filesystem 

Let us know if this works (:

**Comment by mohanagandlla** [comment]
Ya ok, I will try it on Monday and let you know the status.

**Comment by mohanagandlla** [comment]
Yep I have deployed that bucket on MapR FS with FS type but dont know whether it was success or not the UI is loading 
![image](https://user-images.githubusercontent.com/52690110/100086724-cf5c9500-2e73-11eb-8624-ee7fa0a59f5d.png)

**Comment by kakkoyun** [comment]
Could you please share your Thanos Sidecar configuration?
