### ISSUE TITLE
Thanos query deduplication influenced by "stale" metrics

### ISSUE THREAD

**Issue by omron93** [thanos-io/thanos#3485]
I'm running two Prometheus nodes scraping the same data and thanos query connecting to both nodes (sidecars assigned to those nodes)

**Thanos, Prometheus and Golang version used**:

thanos, version 0.16.0 (branch: HEAD, revision: dc6a1666bb68cd5c11be54452842e823f57668c5)
  build user:       root@ba806318d94d
  build date:       20201026-13:56:53
  go version:       go1.15

**Object Storage Provider**:
no

**What happened**:

If one promethes node is down the values returned from Thanos query aren't correct and seems to be influenced by "stale" metrics from the node being down.
![image](https://user-images.githubusercontent.com/3758789/99818901-120a2e80-2b4f-11eb-9fb8-fbcefd945901.png)
![image](https://user-images.githubusercontent.com/3758789/99818921-1afb0000-2b4f-11eb-8b52-34ac1915451e.png)
![image](https://user-images.githubusercontent.com/3758789/99818941-20f0e100-2b4f-11eb-8cc7-03f5da852334.png)

**What you expected to happen**:

Thanos query is returning just the values from the healthy/running node.

**How to reproduce it (as minimally and precisely as possible)**:
**Full logs to relevant components**:
**Anything else we need to know**:

Not sure how to provide more details. Can add later what's needed.

**Comment by kakkoyun** [comment]
Could you please share your Thanos Query configuration?

Also, have you checked the documentation for the related topic? https://thanos.io/tip/components/query.md/#partial-response

We have a flag for enabling partial response by default.
```
--query.partial-response   Enable partial response for queries if no
                                 partial_response param is specified.
                                 --no-query.partial-response for disabling.
```
