### ISSUE TITLE
[query] Thanos is inconsistent with the data returned by Prometheus

### ISSUE THREAD

**Issue by banghuaji** [thanos-io/thanos#3502]
**Thanos, Prometheus and Golang version used**:

Thanos: 0.16.0
Prometheus: 2.21.0
Golang: go1.15.2

**Object Storage Provider**:
AWS S3
**What happened**:

sometimes thanos is inconsistent with the data returned by Prometheus.
query proml:  histogram_quantile(0.99,sum by (le) (rate(nginx_http_request_duration_ms_bucket{host=~"xxx.com"}[1m])))

use prometheus ui we found
![image](https://user-images.githubusercontent.com/17561338/100110887-73603380-2ea8-11eb-9dbe-8042a239740d.png)

use thanos ui we found
![image](https://user-images.githubusercontent.com/17561338/100111298-ea95c780-2ea8-11eb-8f1e-a545e81d44d8.png)

**What you expected to happen**:
the result is different by promtheus and thanos at the sametime ,use histogram_quantile
**How to reproduce it (as minimally and precisely as possible)**:
when i used 【 sum by (le) (rate(nginx_http_request_duration_ms_bucket{host=~"xxx.com"}[1m])) 】as a record rule, the result is same by promtheus and thanos at the sametime 

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by yeya24** [comment]
Hi, can you please provide more info about your setup? Do you have a query-frontend or just the thanos querier?
