### ISSUE TITLE
After implementing memcached index cache, high bucket requests are seen in S3

### ISSUE THREAD

**Issue by wiardvanrij** [thanos-io/thanos#3504]
**Thanos, Prometheus and Golang version used**:

prometheus/prometheus:v2.20.1
thanos/thanos:v0.16.0

**Object Storage Provider**: AWS S3

**What happened**: Implemented --index-cache.config-file with MEMCACHED for the store.

**What you expected to happen**: Same behaviour as before, perhaps with less requests to S3. 

**How to reproduce it (as minimally and precisely as possible)**: Implement memcached index, and see the amount of requests made to the S3 bucket

11/16 is the date of the upgrade to memcached index. 
As you can see the amount of requests to S3 are of a factor 10 (which is huge imo). 
Since we use encryption on the bucket, the costs became quit high (again factor 10 now). 

![image](https://user-images.githubusercontent.com/5786097/100204086-b4d1fc80-2f03-11eb-8593-f322359afd6d.png)

**Comment by kakkoyun** [comment]
Could you please also share your configuration for Thanos store and Memcached?

**Comment by wiardvanrij** [comment]
I still have to investigate this further. I still occasionally have this behaviour but it's hard to pin-point
