### ISSUE TITLE
store: Query failure on Seg fault

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3511]
Similar to https://github.com/thanos-io/thanos/issues/3497

Reported by @arvidsnet

> not sure if it is the same issue, but I have SIGSEGV errors also in store 0.17. Attached logs.
[store-0.17.SIGSEGV.log](https://github.com/thanos-io/thanos/files/5595142/store-0.17.SIGSEGV.log)

(Marking as query failure as from v0.17.1 code should treat Seg faults as recoverable panics, if not - let us know :hugs: )

**Comment by arvidsnet** [comment]
unfortunately I do not know how to reproduce it. So far it happened only 2 times since upgrade to v0.17.

**Comment by kakkoyun** [comment]
Still valid. Need investigation.

**Comment by ediezh** [comment]
We are facing the same issue on 0.18
