### ISSUE TITLE
sidecar: reloader fails on ConfigMap mounts for rules

### ISSUE THREAD

**Issue by clmssz** [thanos-io/thanos#352]
Kubernetes `ConfigMap` volumes contain a `.data` directory, eg:
```
/ # ls -la /etc/prometheus
total 12
drwxrwxrwx    3 root     root          4096 May 24 08:03 .
drwxr-xr-x    6 root     root          4096 May 24 08:03 ..
drwxr-xr-x    2 root     root          4096 May 24 08:03 ..2018_05_24_08_03_36.264564876
lrwxrwxrwx    1 root     root            31 May 24 08:03 ..data -> ..2018_05_24_08_03_36.264564876
lrwxrwxrwx    1 root     root            26 May 24 08:03 prometheus.tmpl.yml -> ..data/prometheus.tmpl.yml
```
When using a ConfigMap volume mount as `reloader.rule-dir` , reloader fails and sidecar crashes :
 
```
level=error ts=2018-05-24T11:47:54.472408145Z caller=main.go:147 msg="running command failed" err="build hash: read /etc/prometheus-rules/..data: is a directory"
```

**Comment by Bplotka** [comment]
Thanks! More testing needed. PRs welcome (:

**Comment by szalai1** [comment]
Hi @bwplotka  @clmssz, 
Has anybody started working on this? If no I would like to.

**Comment by FUSAKLA** [comment]
Hi @szalai1, I think noone is working on it and I can confirm I see the log all the time.

If you want it would be great to solve this issue! So feel free to create PR :)

**Comment by brancz** [comment]
we recently wrote some code to handle this, in case someone is interested in transferring the approach: https://github.com/brancz/kube-rbac-proxy/pull/45

**Comment by FUSAKLA** [comment]
Great thanks for the info!  I'll take a look at this if noone will pick it.

**Comment by szalai1** [comment]
@FUSAKLA I didn't finish the work on this issue.

**Comment by povilasv** [comment]
FYI we had the same issue and the workaround is to set ` - --reloader.rule-dir=/etc/prometheus-rules/..data` .

We've been running like that for a while now and it works flawlessly.

**Comment by FUSAKLA** [comment]
Great, will try it out. Thanks!

**Comment by brancz** [comment]
I believe this still exists as originally reported.

**Comment by daixiang0** [comment]
Test at local and can not reproduce. @brancz @FUSAKLA
