### ISSUE TITLE
I would like write a unit test for a function in PR(#3289).

### ISSUE THREAD

**Issue by dsayan154** [thanos-io/thanos#3521]
Hi,

I have raised [this PR](https://github.com/thanos-io/thanos/pull/3289). Which I have manually tested is working as expected. But I do want to add a unit test for the Iter() function as requested in the below discussion.

Would be possible to add a unit test on this?

_Originally posted by @pracucci in https://github.com/thanos-io/thanos/pull/3289#discussion_r507783362_

I have gone through the Thanos repo, but can't understand how to write the tests and where to place these *test.go files. Any pointers on how shall I begin this task will be very helpful. 
cc: @pracucci @bwplotka @kakkoyun

**Comment by kakkoyun** [comment]
For that specific request, probably you need to use https://github.com/thanos-io/thanos/blob/b654074dfa749d6bf9eb7b6f7f88b89952949b62/pkg/objstore/objstore_test.go

It would be better to use #thanos-dev channel on CNCF slack or newly initialized Weekly Contributor meetings https://docs.google.com/document/u/1/d/137XnxfOT2p1NcNUq6NWZjwmtlSdA6Wyti86Pd6cyQhs/edit#
