### ISSUE TITLE
Doc: Relative links broken under Thanos section

### ISSUE THREAD

**Issue by Shavakan** [thanos-io/thanos#3523]
The relative links on the webpage documentation under Thanos section appear to be broken.
In terms of git, I'm referring to the files matching `docs/*.md` (not `docs/**/*.md`)

This is because of the trailing `/` character in the web urls (i.e. https://thanos.io/v0.17/thanos/quick-tutorial.md/).

It's tricky to apply an easy fix when considering both the webpage and GitHub.

**Comment by DARK-art108** [comment]
can I work on this issue?

**Comment by soniasingla** [comment]
@DARK-art108 please, go ahead :)

**Comment by DARK-art108** [comment]
@soniasingla could you please explain to me a little bit about the changes need to made in docs, I am not getting much from the above issues headline :)

**Comment by Shavakan** [comment]
I was trying to fix this myself before submitting as an issue, spent some time trying to figure out what is happening. I'm not really used to playing with netlify so @DARK-art108 please do go ahead. I'll share some of the things that I found, if that saves your time :)

If you go to the page that I linked, relative links like the architecture overview, or the links in h3 section header would appear broken. For instance, [this link](https://thanos.io/v0.17/thanos/quick-tutorial.md/#sidecarcomponentssidecarmd) is broken, because it's href-ing https://thanos.io/v0.17/thanos/components/sidecar.md instead of https://thanos.io/v0.17/components/sidecar.md .
I remember this was all fine back in v0.14 or maybe v0.15 - v0.16 i'm not sure because i didn't check.

If you go on GitHub (https://github.com/thanos-io/thanos/blob/master/docs/quick-tutorial.md), they are all normal.

I was suspecting that this issue is related to [this commit](https://github.com/thanos-io/thanos/commit/0b8507c75ae9dfd27eae16a8035eea27010d9715#diff-747a8f398395dde8e524d9f983784bd8441c5cfe4307b5a079be5412ee65c314)

**Comment by bwplotka** [comment]
Thanks for looking into this. This is a known issue that we slowly work on with automation explained [here](https://github.com/thanos-io/thanos/issues/3081). Let's close this as a duplicate 🤗 Feel free to help on the linked issue, to get things done!
