### ISSUE TITLE
query-frontend:Splliting and Retries for Labels can cause cascading failure

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3525]
We had a very small incident on one of our clusters where query frontend spammed 20k requests in same second against backend and saturated all CPUs of all store GW and Receivers. See:

 ![image](https://user-images.githubusercontent.com/6950331/100770520-44d8e000-33f5-11eb-8eaf-53cabfa674cb.png)

![image](https://user-images.githubusercontent.com/6950331/100771232-16a7d000-33f6-11eb-840e-cc67d9a12bf9.png)

For now, we turn off retries to 0

Open Question:
* Should split by enabled by default then?
*  Should retries be turn off by default?

On an unrelated note, it would be amazing to add a concurrency limit to all gRPC methods at the end (aka interceptor limit) we thought of cc @yashrsharma44 @yeya24 (:

**Comment by MalloZup** [comment]
@bwplotka and others I am working currently on the unrelated note about the interceptor limit on PR referenced.

What should from your experience be a good function which should handle the limit and how? 

tia :sun_with_face:

**Comment by MalloZup** [comment]
@bwplotka  I was reserching a bit on this and rate-limiting mechanism.

As suggested I looked at the `gate` construct which basically is already a `limiter`.

My question here in this issue:

since we do have already https://github.com/thanos-io/thanos/blob/058e22b5b5ed13b44856d8c4fe355a40091f6a97/cmd/thanos/query.go#L79

I can't follow how the  query frontend spammed 20k requests  if we do have by default a limit of `4`.

**Comment by MalloZup** [comment]
adding also as notes:

** cortex**
- https://docs.google.com/document/d/1lsvSkv0tiAMPQv-V8vI2LZ8f4i9JuTRsuPI_i-XcAqY/edit#
- https://github.com/cortexproject/cortex/pull/3374

**Comment by bwplotka** [comment]
> I can't follow how the query frontend spammed 20k requests if we do have by default a limit of 4.
I might miss something here. 

Well that's the key. We might not have it in all places. E.g we don't have it for LabelValues methods

**Comment by MalloZup** [comment]
ah ok now I get it ! {: thx ! I played a bit with the rate-limiting tockenBucket and worked quite nice. I think I will need to update the document.

I think the `NewBucketWithRate` could be something we could use https://github.com/juju/ratelimit#func--newbucketwithrate

but I think we might need some empirical data to see how much request we need to limit like the maximum and also the rate we allows the refill period...

**Comment by bwplotka** [comment]
> but I think we might need some empirical data to see how much request we need to limit like the maximum and also the rate we allows the refill period...

Oh I think the values should be configurable. It really will differ on what API is behind how much resources you have etc 🤔

**Comment by MalloZup** [comment]
yes, I agree that we need configurable ones but I was thinking we might have like defaults.

I do have looked how we have `global` options but I didn't had time to investigate more in details the Thanos options. something I want to investigate.. anyways today in Italy I need to survey the so much eating :grin:
