### ISSUE TITLE
Why the compactor component downsampling  not work

### ISSUE THREAD

**Issue by weinux2020** [thanos-io/thanos#3533]
Hi, I deployed thanos by docker-compose, use thanos:v0.17.1, and config compactor as follows:
----------------------------------------
  compactor:
    container_name: compactor
    image: quay.io/thanos/thanos:v0.17.1
    volumes:
    - /home/dockerfile/thanos/bucket_config.yaml:/bucket_config.yaml
    command:
    - compact
    - --data-dir=/var/thanos/compact
    - --objstore.config-file=bucket_config.yaml
    - --http-address=0.0.0.0:19191
    - --wait
    #- --downsampling.disable=false
    - --compact.concurrency=1
    - --delete-delay=5m
    - --retention.resolution-raw=1h
    - --retention.resolution-5m=10h
    - --retention.resolution-1h=100h
    depends_on:
    - minio
------------------------------------------------------------------------------------
downsampling log says it was done, but I can't see any downsampled data upload to the minio
![image](https://user-images.githubusercontent.com/69229846/100956112-baa68e00-3552-11eb-8894-b27f8afd5cc4.png)
![image](https://user-images.githubusercontent.com/69229846/100956185-e7f33c00-3552-11eb-86a9-62b7f7e20670.png)
![image](https://user-images.githubusercontent.com/69229846/100956210-f5102b00-3552-11eb-81f4-e8e0fe4a9c84.png)
![image](https://user-images.githubusercontent.com/69229846/100956237-02c5b080-3553-11eb-8d39-6cde351040b8.png)
 and I query data in the thanos query platfrom, and can't see any downsampled data:
![image](https://user-images.githubusercontent.com/69229846/100956381-4cae9680-3553-11eb-9385-1fe93849323a.png)

docker-compose file is:
`version: '2'
services:
  prometheus1:
    container_name: prometheus1
    image: prom/prometheus
    ports: 
      - 9090:9090
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    volumes:
    - /home/dockerdata/prometheus:/prometheus
    - /home/dockerfile/thanos/prometheus.yml:/etc/prometheus/prometheus.yml  
    command:
      - --web.enable-lifecycle
      - --web.enable-admin-api
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --storage.tsdb.min-block-duration=20m # small just to not wait hours to test :)
      - --storage.tsdb.max-block-duration=20m # small just to not wait hours to test :)
      - --storage.tsdb.retention.time=10m
    depends_on:
    - minio

  sidecar1:
    container_name: sidecar1
    image: quay.io/thanos/thanos:v0.17.1
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    volumes:
    - /home/dockerdata/prometheus:/var/prometheus
    - /home/dockerfile/thanos/bucket_config.yaml:/bucket_config.yaml
    command:
    - sidecar
    - --tsdb.path=/var/prometheus
    - --prometheus.url=http://prometheus1:9090
    - --objstore.config-file=/bucket_config.yaml
    - --http-address=0.0.0.0:19191
    - --grpc-address=0.0.0.0:19090
    depends_on:
    - minio
    - prometheus1

  prometheus2:
    container_name: prometheus2
    image: prom/prometheus
    ports:
      - 9091:9090
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    volumes:
    - /home/dockerdata/prometheus2:/prometheus
    - /home/dockerfile/thanos/prometheus2.yml:/etc/prometheus/prometheus.yml
    command:
      - --web.enable-lifecycle
      - --web.enable-admin-api
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --storage.tsdb.min-block-duration=20m 
      - --storage.tsdb.max-block-duration=20m
      - --storage.tsdb.retention.time=10m
    depends_on:
    - minio

  sidecar2:
    container_name: sidecar2
    image: quay.io/thanos/thanos:v0.17.1
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    volumes:
    - /home/dockerdata/prometheus2:/var/prometheus
    - /home/dockerfile/thanos/bucket_config.yaml:/bucket_config.yaml
    command:
    - sidecar
    - --tsdb.path=/var/prometheus
    - --prometheus.url=http://prometheus2:9090
    - --objstore.config-file=/bucket_config.yaml
    - --http-address=0.0.0.0:19191
    - --grpc-address=0.0.0.0:19090
    depends_on:
    - minio
    - prometheus2

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports: 
    - "3000:3000"

  # to search on old metrics
  storer:
    container_name: storer
    image: quay.io/thanos/thanos:v0.17.1
    volumes:
    - /home/dockerfile/thanos/bucket_config.yaml:/bucket_config.yaml
    command:
    - store
    - --data-dir=/var/thanos/store
    - --objstore.config-file=bucket_config.yaml
    - --http-address=0.0.0.0:19191
    - --grpc-address=0.0.0.0:19090
    depends_on:
    - minio  

  # downsample metrics on the bucket
  compactor:
    container_name: compactor
    image: quay.io/thanos/thanos:v0.17.1
    volumes:
    - /home/dockerfile/thanos/bucket_config.yaml:/bucket_config.yaml
    command:
    - compact
    - --data-dir=/var/thanos/compact
    - --objstore.config-file=bucket_config.yaml
    - --http-address=0.0.0.0:19191
    - --wait
    #- --downsampling.disable=false
    - --compact.concurrency=1
    - --delete-delay=5m
    - --retention.resolution-raw=1h
    - --retention.resolution-5m=10h
    - --retention.resolution-1h=100h
    depends_on:
    - minio 

  # querier component which can be scaled
  querier:
    container_name: querier
    image: quay.io/thanos/thanos:v0.17.1
    labels:
    - "traefik.enable=true"
    - "traefik.port=19192"
    - "traefik.frontend.rule=PathPrefix:/"
    ports: 
    - "19192:19192"
    command:
    - query
    - --query.auto-downsampling
    - --http-address=0.0.0.0:19192
   # - --store=sidecar1:19090
   # - --store=sidecar2:19090
    - --store=storer:19090
    - --query.replica-label=replica

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - 9000:9000
    volumes: 
      - "/home/minio/data:/data"
    environment:
      MINIO_ACCESS_KEY: "danny"
      MINIO_SECRET_KEY: "zw.........." 
    command: server /data
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - '9100:9100'
`
bucket_config.yaml :
`type: S3
config:
  bucket: "thanos"
  endpoint: 'minio:9000'
  access_key: "danny"
  insecure: true 
  signature_version2: false
  secret_key: "zw.........." 
  put_user_metadata: {}
  http_config:
    idle_conn_timeout: 90s
    response_header_timeout: 2m
    insecure_skip_verify: false
  trace:
    enable: false
  part_size: 134217728
`

thanks!

**Comment by yeya24** [comment]
https://github.com/thanos-io/thanos/blob/master/docs/components/compact.md#compactor We have this doc. 

Can you please make sure that your blocks satisfy the required duration? 
![Screenshot from 2020-12-02 22-41-51](https://user-images.githubusercontent.com/25150124/100961071-9e253a00-34ef-11eb-899e-d5b2aee948ad.png)



You can also check the `thanos_compact_downsample_total` metric. If it has > 0 value, then you should have downsampled blocks. If its value is > 0 but you still cannot find any downsampled blocks, I guess they are deleted by the compactor as you have a small retention setting.

**Comment by weinux2020** [comment]
@yeya24 Ok, Thanks, I will turn larger duration metric data for prometheus and thanos_compactor to validate. Maybe I had made very small duration, so thanos query platform didn't generation the thanos_compact_downsample_total metric.

**Comment by weinux2020** [comment]
@yeya24  Hi, I made this config for my thanos compactor and prometheus running 5 days ,  I see a block compacted over 40hours on the monio, but still not see any downsampled block, and no "thanos_compact_downsample_total" data found , could you help me?
![image](https://user-images.githubusercontent.com/69229846/101596309-cf41c500-3a2f-11eb-987c-c4ccd2103e0d.png)
![image](https://user-images.githubusercontent.com/69229846/101596326-d8329680-3a2f-11eb-825c-c882d38c5185.png)
![image](https://user-images.githubusercontent.com/69229846/101596472-16c85100-3a30-11eb-8261-5ecb5d5aa9d6.png)


    command:
    - compact
    - --data-dir=/var/thanos/compact
    - --objstore.config-file=bucket_config.yaml
    - --http-address=0.0.0.0:19191
    - --wait
    - --compact.concurrency=1
    - --delete-delay=5m
    - --retention.resolution-raw=11d
    - --retention.resolution-5m=30d
    - --retention.resolution-1h=40h
=============================
    command:
      - --web.enable-lifecycle
      - --web.enable-admin-api
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --storage.tsdb.min-block-duration=20d 
      - --storage.tsdb.max-block-duration=20d
      - --storage.tsdb.retention.time=20d

**Comment by weinux2020** [comment]
I saw the log as follows, why the downsampled block outdated and deleted? my retention.resolution-5m=30d.
-------------------------------------------------------------------------
storer           | level=info ts=2020-12-06T00:35:09.194864738Z caller=bucket.go:484 msg="loaded new block" elapsed=70.87817ms id=01ERTQHDMMPDWFGTV0E62H6M40
storer           | level=info ts=2020-12-10T00:35:11.458430286Z caller=bucket.go:413 msg="dropped outdated block" block=01ERTQHDMMPDWFGTV0E62H6M40
compactor        | level=info ts=2020-12-06T00:34:36.334683807Z caller=streamed_block_writer.go:176 msg="finalized downsampled block" mint=1607040000000 maxt=1607212760000 ulid=01ERTQHDMMPDWFGTV0E62H6M40 resolution=300000
compactor        | level=info ts=2020-12-06T00:34:36.334813705Z caller=downsample.go:284 msg="downsampled block" from=01ERTQH3ZN06WAHRBSAJRTQNGH to=01ERTQHDMMPDWFGTV0E62H6M40 duration=4.126637238s
compactor        | level=warn ts=2020-12-06T00:34:36.343866941Z caller=s3.go:399 msg="could not guess file size for multipart upload; upload might be not optimized" name=debug/metas/01ERTQHDMMPDWFGTV0E62H6M40.json err="unsupported type of io.Reader"
compactor        | level=info ts=2020-12-06T00:34:36.790439146Z caller=downsample.go:298 msg="uploaded block" id=01ERTQHDMMPDWFGTV0E62H6M40 duration=452.549395ms
compactor        | level=info ts=2020-12-10T00:39:09.293430892Z caller=compact.go:185 msg="marking outdated block for deletion" block=01ERTQHDMMPDWFGTV0E62H6M40
compactor        | level=info ts=2020-12-10T00:39:09.298257546Z caller=block.go:161 msg="block has been marked for deletion" block=01ERTQHDMMPDWFGTV0E62H6M40
compactor        | level=info ts=2020-12-10T00:44:09.15908478Z caller=blocks_cleaner.go:53 msg="deleted block marked for deletion" block=01ERTQHDMMPDWFGTV0E62H6M40

**Comment by yeya24** [comment]
Hi, sorry for the late reply. So that block was downsampled. It was deleted because it was compacted with other blocks and a new block with a higher compaction level was created. So the original blocks are marked outdated and removed.

**Comment by weinux2020** [comment]
@yeya24  Thank you for your reply , but I can't see any data in table 'thanos_compact_downsample_total', could you tell me how to config for scraping  that data?

**Comment by yeya24** [comment]
> @yeya24 Thank you for your reply , but I can't see any data in table 'thanos_compact_downsample_total', could you tell me how to config for scraping that data?

You can add your compactor as a scrape target in your Prometheus.

**Comment by weinux2020** [comment]
Ok, I will try, Thanks a lot , close this issue.
