### ISSUE TITLE
todo: Add info about Contributor Office Hours to our website.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3534]
Context: https://twitter.com/bwplotka/status/1334404169432788992

Help wanted :hugs:

**Comment by DARK-art108** [comment]
Can I work on this issue?

**Comment by soniasingla** [comment]
@DARK-art108 sure feel free to raise PR :)

**Comment by DARK-art108** [comment]
@soniasingla please explain a little bit more about this issue!!

**Comment by soniasingla** [comment]
Please go through this: https://docs.google.com/document/d/137XnxfOT2p1NcNUq6NWZjwmtlSdA6Wyti86Pd6cyQhs/edit?usp=sharing
 
You need to add this information on our website https://thanos.io/ in simple and informative language.

**Comment by DARK-art108** [comment]
Ok so I have explored some parts of the website and so it is good to add the Thanos contributing hour guidelines inside the community.md? @soniasingla

**Comment by soniasingla** [comment]
@DARK-art108 yes 💪🏻

**Comment by DARK-art108** [comment]
Ok I will surely do it 👍

**Comment by DARK-art108** [comment]
@soniasingla Please Review the PR :)

**Comment by yeya24** [comment]
Thanks for your contribution. As #3552 was merged, I will close this issue.
