### ISSUE TITLE
Add support for Cache storage

### ISSUE THREAD

**Issue by kamijin-fanta** [thanos-io/thanos#3535]
### Is your proposal related to a problem?

Currently, only in-memory and memcached caches are supported. However, if the user is already running another KVS, there wants to use it.

### Describe the solution you'd like

Add Redis support. There should be many users like Memcached.

### Describe alternatives you've considered

Cassandra,ScyllaDB is suitable for large environments. If accepted, I would like to add support for ScyllaDB instead of Redis.

### Additional context

none

**Comment by kakkoyun** [comment]
IMO, we shouldn't be aiming for adding support for multiple caching backends. We should rather simplify our caching layer and reduce the number of options. Personally, I think the caching layer should be closer to actual Thanos and I don't prefer to operate an additional layer of software for caching. It's hard to configure and tune the caching right now. For that, I have started this https://github.com/thanos-io/thanos/pull/3125 to simplify this layer. However, I couldn't find enough spare time to push it to the finish line. It's on top of my list.

**Comment by kamijin-fanta** [comment]
Thank you for your reply. I think it's a good idea to include Groupcache. It's very easy to use.

But what happens when the cluster reboots? The cache is purged with inmemory, memcached and groupcache. And I think there will be more access to object storage. This can be a problem for large-scale use. I feel that it is better to use KVS that can be persisted like Redis and Cassandra.

**Comment by kakkoyun** [comment]
This is already a problem regardless of the caching backend unless you are using a caching backend outside of your environment/cluster. And also the cache itself is volatile. By default, an item only is kept in cache for 24 hours for bucket cache for example.

So all in all, it's not our ultimate goal to minimize object store with caching. More backend means more complexity and more maintenance and operating burden. We want to avoid that as a project.

**Comment by kamijin-fanta** [comment]
thanks. I understood that it was not the goal of Thanos.

I'm looking forward to your PR 🙋
