### ISSUE TITLE
Add other service discovery support to Thanos

### ISSUE THREAD

**Issue by lilic** [thanos-io/thanos#3538]
### Is your proposal related to a problem?

We have been experiencing some DNS issues when Thanos query tries to perform rules and store address discovery. As both the store and rules as well as Thanos query are all in the same cluster, we thought it would be better to just use the same service discovery mechanisms that Prometheus already uses, e.g. Kubernetes, Consul, etc. We already use those discovery mechanisms for Prometheus in the same cluster and we have not had any problems with that while the DNS resolve issues were present often.

### Describe the solution you'd like

Prometheus uses a file to configure service discovery and from my understanding, this would fit well with Thanos, at least for Thanos query file config service discovery is already supported, my familiarity with rest of the code base is not as good, so feel free to correct me if this would not fit for other components of Thanos! 
Having the same format as Prometheus would allow us to potentially reuse the same code, but also make users' life easier as they can reuse the same configuration files.
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#configuration-file

### Describe alternatives you've considered

I have tried debugging DNS issues. 😫 😅 

Thanks for reading!

**Comment by kakkoyun** [comment]
@lilic A similar request raised by @brancz recently regarding Thanos Receive, he probably has ideas to contribute to this.

That being said, this could be useful. I'm also planning to introduce a service discovery mechanism to Query Frontend and Store to utilize in a distributed cache layer.

As @brancz already raised in an offline conversation, a possible downside would be the increased binary size and special needs for certain components (i.e receiver). cc @squat 

All in all, if there are no big objections, I think this is something we can give a shot.

Let's wait to here from other @thanos-io/thanos-maintainers as well.

**Comment by wiardvanrij** [comment]
I understand the use-case in the sense that there is no harm in having various options for discovery. Though I believe this should be based on the positive effects/arguments for having various options. It now feels like we opt for a new feature because there are "problems" with the first option. 

So regardless of this feature, I do believe the case for DNS discovery should be know and perhaps it's limitations. I.e. I would be nice to have an issue representing your DNS issue. Perhaps multiple people are having this issue, or perhaps some actually have a working solution.

**Comment by brancz** [comment]
I had not thought of the bigger picture (only thanos receive), and it was more of a brain dump on slack from me. I currently don't plan on implementing any of it.

**Comment by lilic** [comment]
>  It would be nice to have an issue representing your DNS issue. Perhaps multiple people are having this issue, or perhaps some actually have a working solution.

@wiardvanrij yes I plan on opening an issue, after we can reproduce it and the issue is verified to be about thanos query itself. But currently, the suspicion is that the issue does not have anything to do with thanos DNS discovery but with the (Kubernetes) cluster DNS flakes, as we have seen them with other components within the cluster.

@kakkoyun @brancz thanks for your answers, will wait if there are any objections from other members, otherwise what is the process to propose things further? Do I bring it up in a call or just continue on this issue? Thanks!

**Comment by brancz** [comment]
I think just following up here sounds good. I don't think I thought the thanos receive part through enough to meaningfully contribute from that end (as I said, it was just a wild idea that I dropped on slack).

I think what you proposed in terms of just starting to implement this within the querier for discovering stores is a great start, and should this work out well, then we can think about expanding it to other components.

**Comment by lilic** [comment]
To us this is still very much relevant and we would love to have this. :)

**Comment by kakkoyun** [comment]
Related proposal: https://github.com/thanos-io/thanos/blob/master/docs/proposals/210701_endpoint_discovery.md

**Comment by dntosas** [comment]
if we could push endpoint configuration to Thanos instead of pre-configuring the SD?

for example, a Thanos endpoint instance to send a request (even with creds etc etc) to Thanos Querier to add it as Store and start scraping. WDYT?

**Comment by wiardvanrij** [comment]
Reopening as I think its still quite relevant.

**Comment by hanjm** [comment]
I use [confd](https://github.com/kelseyhightower/confd) as Sidecar in production env. I think [consul-template](https://github.com/hashicorp/consul-template) is good for consul. watch consul service and render a endpoint file. 😄

**Comment by matej-g** [comment]
There's an umbrella issue / proposal under https://github.com/thanos-io/thanos/issues/4841, I believe we can close this.
