### ISSUE TITLE
Thanos receive high available (hashring) not work.

### ISSUE THREAD

**Issue by foshantiger** [thanos-io/thanos#3540]
**Thanos, Prometheus and Golang version used**:
Thanos: v0.13.0
Prometheus: v2.16.0

**Object Storage Provider**: S3

**What happened**:
We use thanos receive in k8s enviorment and receive deploy 3 instances(pods) for hashring,  then we shutdown a node where one of the receive pod deploy on or just delete one of the 3 receive pods, the entire thanos receive will not work, and prometheus will get 500 http status code when sending metrics to the receive remote write address.
 
The receive component config as below:
        - receive
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --remote-write.address=0.0.0.0:19291
        - --receive.replication-factor=1
        - --objstore.config=$(OBJSTORE_CONFIG)
        - --tsdb.path=/var/thanos/receive
        - --tsdb.retention=12h
        - --label=receive_replica="$(NAME)"
        - --label=receive="true"
        - --receive.hashrings-file=/etc/thanos/thanos-receive-hashrings.json
        - --receive.local-endpoint=$(NAME).thanos-receive.$(NAMESPACE).svc.cluster.local:10901

apiVersion: v1
data:
  thanos-receive-hashrings.json: |
    [
      {
        "hashring": "soft-tenants",
        "endpoints":
        [
          "thanos-receive-0.thanos-receive.thanos.svc.cluster.local:10901",
          "thanos-receive-1.thanos-receive.thanos.svc.cluster.local:10901",
          "thanos-receive-2.thanos-receive.thanos.svc.cluster.local:10901"
        ]
      }
    ]
kind: ConfigMap

**What you expected to happen**:
Receive can detect the unrechable instance and kick it off, continue to work properly.

**How to reproduce it (as minimally and precisely as possible)**:
Shutdown one k8s node where receive componet deploy on.

**Full logs to relevant components**:
level=error ts=2020-12-04T16:22:18.141795053Z caller=handler.go:282 component=receive component=receive-handler err="forwarding request to endpoint thanos-receive-0.thanos-receive.thanos.svc.cluster.local:10901: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: lookup thanos-receive-0.thanos-receive.thanos.svc.cluster.local on 10.96.0.10:53: no such host\"" msg="internal server error"
level=error ts=2020-12-04T16:22:18.141809185Z caller=handler.go:282 component=receive component=receive-handler err="forwarding request to endpoint thanos-receive-0.thanos-receive.thanos.svc.cluster.local:10901: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: lookup thanos-receive-0.thanos-receive.thanos.svc.cluster.local on 10.96.0.10:53: no such host\"" msg="internal server error"
level=error ts=2020-12-04T16:22:18.141866948Z caller=handler.go:282 component=receive component=receive-handler err="forwarding request to endpoint thanos-receive-0.thanos-receive.thanos.svc.cluster.local:10901: rpc error: code =

**Anything else we need to know**:

**Comment by foshantiger** [comment]
Just set --receive.replication-factor=3, then it works, I will close this issue.~

**Comment by Kampe** [comment]
While that may potentially solve the issue - that really doesn't explain the problem that's happening here.  I had similar issues when using receive in HA mode with the configmap reloader - it's a very poor user experience (even having to bring in the configmap reloader is a bit excessive) and the replication-factor configuration, let alone receive in general, is not well documented well either.

**Comment by Ygshvr** [comment]
@Kampe did you find any solution for this problem? I am still facing this issue with Thanos v0.26.0.
