### ISSUE TITLE
Reload Storage Config On Interval

### ISSUE THREAD

**Issue by midnightconman** [thanos-io/thanos#3548]
### Is your proposal related to a problem?

Yes, we use AWS as our cloud provider, which means we use s3 for cloud storage. We use SDK user / password to give various thanos components access to s3 (read / write). The AWS SDK user / password is exposed to the various thanos component pods as a kubernetes secret. Kubernetes supports updating secrets on-demand, but at the moment thanos components never reload storage config from drive.

### Describe the solution you'd like

Implement a storage config agent that would reload storage config on interval, allowing storage config secrets to be updated without deploying new pods.

### Describe alternatives you've considered

One alternative would be to keep things as they are and just reload pods, this would mostly work for compactor -- but we would run into issues with the sidecar and storegateway pods.

### Additional context

This would only be for `objstore.config-file`, flags cannot be updated on running processes... so `objstore.config` cannot be reloaded.

**Comment by kakkoyun** [comment]
@midnightconman How about watching the file changes and updating accordingly?

**Comment by midnightconman** [comment]
As I think about this more, we don't have any other portion of the config that is updated on interval (except endpoints). Maybe instead we could include updating the storage config via the reload api (or via another reload api just for the storage config)?
