### ISSUE TITLE
Thailand

### ISSUE THREAD

**Issue by nesara-cmd** [thanos-io/thanos#3549]
### Is your proposal related to a problem?

(Write your answer here.)

### Describe the solution you'd like

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by GiedriusS** [comment]
Hi! Sorry but this seems like spam. Closing it.

**Comment by nesara-cmd** [comment]
3649
