### ISSUE TITLE
Query: No thanos-specific metrics, e.g. thanos_objstore_bucket_last_successful_upload_time

### ISSUE THREAD

**Issue by timkahlke** [thanos-io/thanos#3550]
**Thanos, Prometheus and Golang version used**:

Thanos v. 0.16.0
Prometheus v2.22
GO v1.15

**Object Storage Provider**:
FILESYSTEM

**What happened**:
Thanos GUI doesn't show any Thanos-specific metrics, e.g., thanos_objstore_bucket_last_successful_upload_time, thanos_compactor_halted or thanos_blocks_meta_synced

**What you expected to happen**:
Get values for any of the thanos metrics

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

I'm pretty new to Thanos so I guess this is a configuration issue or misunderstanding on my part and would appreciate some help.

I have a HA-set up with 2 Prometheus instances + sidecar, query, one store (FILESYSTEM) which contains 2 months of data (no prometheus compaction, min/max time 2h) and now a compactor which I'm trying to debug. I read that there should be thanos-specific metrics about uploaded blocks, compaction etc but when I look for them in the Thanos GUI they aren't there. Any clues what I'm missing? All other metrics, de-duplication etc all works.

**Query**
/thanos query \
  --http-address "0.0.0.0:9080" \
  --grpc-address "0.0.0.0:10905" \
 --store "0.0.0.0:10901" \
  --store "0.0.0.0:10902" \
  --store "0.0.0.0:10904" \
  --query.replica-label "replica"

**Compactor**
thanos compact \
  --data-dir "/var/thanos/compactor" \
  --objstore.config-file "/etc/thanos/bucket.yml" \
  --http-address "0.0.0.0:10906" \
    --consistency-delay=30m \
    --retention.resolution-raw=0d \
    --retention.resolution-5m=0d \
    --retention.resolution-1h=0d \
    --block-sync-concurrency=20 \
    --compact.concurrency=1 \
    --wait

**Store**
thanos store \
  --data-dir "/var/thanos/store" \
  --objstore.config-file "/etc/thanos/bucket.yml" \
  --http-address "0.0.0.0:10903" \
  --grpc-address "0.0.0.0:10904" \
    --chunk-pool-size=8GB \
    --index-cache-size=2GB

**Comment by yeya24** [comment]
Hi, if you are looking for the metrics of thanos components, for example compactor, you can get its metrics in the `/metrics` endpoint.

If you want to query the compactor metrics via Thanos query web UI, its metrics must be scraped via a Prometheus job and you have a sidecar to query from the Prometheus.

**Comment by TTCGithub** [comment]
Well I'm new and confused!

**Comment by timkahlke** [comment]
Thanks yeya24, that makes total sense!
