### ISSUE TITLE
web: Case Studies md doc in Operating section.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3555]
As  Wiard proposed in our community meeting, it would be nice to start good example and have case studies with details like configuration setting.

Do you mind Wiard to starting this one? And propose some template? 🤗 

Also help wanted everyone else, especially those who runs Thanos on Prod. We are happy to provide Red Hat one as well.

**Comment by wiardvanrij** [comment]
Currently working on public relations approval for our company, but nonetheless I'll make a template proposal.

**Comment by bwplotka** [comment]
Looking at other companies that are willing to share some details and existing blog post we have linked in Thanos website (e.g https://build.thebeat.co/monitoring-the-beat-microservices-a-tale-of-evolution-4e246882606e) I think it has to be bigger than a single page (: 

I would propose another section: `Case Studies` and doc `How to add case study` under contributing. Then each doc per company WDYT?

**Comment by bwplotka** [comment]
I can start some initial work on website on separate branch (we have preview) and anyone can propose PR against that so we can incrementally work on this 🤗

**Comment by wiardvanrij** [comment]
> Looking at other companies that are willing to share some details and existing blog post we have linked in Thanos website (e.g https://build.thebeat.co/monitoring-the-beat-microservices-a-tale-of-evolution-4e246882606e) I think it has to be bigger than a single page (:
> 
> I would propose another section: `Case Studies` and doc `How to add case study` under contributing. Then each doc per company WDYT?

Even better.

**Comment by kakkoyun** [comment]
Still valid.

**Comment by jmichalek132** [comment]
We are also interested in contributing in this way.

**Comment by bwplotka** [comment]
Super nice!

**Comment by hoempf** [comment]
If it would help I can contribute our use case, still very fresh though ;) Our stack includes multi-tenant `thanos receive`, OpenID Connect integration (Keycloak) to authenticate the remote Prometheus shippers (which we don't fully control), the label-proxy-enforcer and Minio for long-term storage.

Let me know as soon as you want me to write up something, happy to help in any way I can, ❤️  this project :)

**Comment by wiardvanrij** [comment]
Thanks @hoempf - I'll block some time ASAP so I can create a template page and we can get this rolling!

**Comment by wiardvanrij** [comment]
Still needed
