### ISSUE TITLE
errors: Adapt new errors.MultiError or use tsdb_erros directly

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3559]
Help wanted. 🤗 

Our lib: https://github.com/thanos-io/thanos/blob/47f9a225cc525bb0c7669c77a7a16a52f0333cfc/pkg/errutil/multierror.go.go#L13

Ideally we can use directly [Prometheus one again](https://github.com/prometheus/prometheus/blob/3d8826a3d42566684283a9b7f7e812e412c24407/tsdb/errors/errors.go#L24)  (it was added tmp to help with Thanos upgrade on Cortex side),

**Comment by bsnyder788** [comment]
I'll work on this one!

**Comment by bsnyder788** [comment]
@bwplotka The multiError from Prometheus TSDB isn't exported for usage, so what were you thinking for this?

**Comment by khyatisoneji** [comment]
same question!

**Comment by bwplotka** [comment]
It is exported. See the `NewMulti` struct does not have to be. (:

Kind Regards,
Bartek Płotka (@bwplotka)

**Comment by bsnyder788** [comment]
I noticed that the NewMulti was exported, but that doesn't yield a nice replacement for type assertions or places where the current MultiError are embedded into a struct.

**Comment by bwplotka** [comment]
I would go case by case. We made it private to reduce complexity of usage
(should be one way of instantiating this). If you want embed, maybe we
should propose interface instead. (:

Ofc we can make it public as well, let's discuss if there are use cases.


Kind Regards,
Bartek Płotka (@bwplotka)

**Comment by bsnyder788** [comment]
The current usages in `pkg/block/fetcher.go` seems to be the more problematic ones to replace without the new multiError being public so it can be used in type assertions.

**Comment by Biswajitghosh98** [comment]
@bwplotka can we make TSDB `multiError` public in Prometheus so that we could use it in Thanos as well ? 
As @bsnyder788 mentioned earlier that for type assertion we need `multiError` to be public :) 
WDYT ?
