### ISSUE TITLE
DOC: Website contains some 404

### ISSUE THREAD

**Issue by MalloZup** [thanos-io/thanos#3569]
## Description:

I found two minor issue when navigating the webpage of thanos.

1)  when the user click following link:
![image](https://user-images.githubusercontent.com/10886597/101835535-38166380-3b3c-11eb-8ec3-07fecbbbec35.png)
link is https://github.com/thanos-io/thanos/edit/master/docs/thanos/integrations.md

it redirects actually to a 404. ( Maybe because i'm not maintainer)

2) it seems tthat https://thanos.io/tip/components/ was before https://thanos.io/tip/thanos/components/ 
but some pages are still referencing the  latter

Lot of links are broken in this page: 
https://thanos.io/tip/thanos/integrations.md/#integrations

E.g by https://thanos.io/tip/thanos/components/query.md
https://thanos.io/tip/thanos/components/sidecar.md

hope it helps :sunflower:

**Comment by DARK-art108** [comment]
Can I work on this issue?

**Comment by MalloZup** [comment]
@DARK-art108 woyld be great ! thx for your help

**Comment by bboreham** [comment]
Link to "Querier/Query" from https://thanos.io/tip/thanos/quick-tutorial.md/ also 404s.

**Comment by Namanl2001** [comment]
Is anyone working on this issue or could I take this up?

**Comment by MalloZup** [comment]
@Namanl2001  feel free to take this issue
