### ISSUE TITLE
query frontend: Flaky E2E test

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#3570]
**What happened**:

https://github.com/thanos-io/thanos/pull/3566/checks?check_run_id=1534028614

```
=== RUN   TestQueryFrontend/query_frontend_works_for_instant_query
queryAndAssert: Waiting for 1 results for query sum(up) without (instance)
=== RUN   TestQueryFrontend/query_frontend_works_for_range_query_and_it_can_cache_results
=== CONT  TestQueryFrontendMemcachedCache
Error:     query_frontend_test.go:467: query_frontend_test.go:467:
        
         unexpected error: unable to find metrics [thanos_frontend_split_queries_total] with expected values. Last error: <nil>. Last values: [2]
        
23:20:43 Killing query-frontend-1
```

The query splitting test case is flaky because we are using the current timestamp to send queries, which makes the splitting behavior non-deterministic.

**Comment by wiardvanrij** [comment]
Still relevant

**Comment by wiardvanrij** [comment]
If the start and end time falls between a new day (passed 23:59), it will see this as '24h' (default --query-range.split-interval). My guess is that certain behavior has an underlying bug or that I'm a lost in the complexity. It will need to double the testing values if the hour is "1" for `thanos_frontend_split_queries_total` and `cortex_cache_*` However, only `thanos_frontend_split_queries_total` will need to double its value on hour 0. `cortex_cache_*`'s do not. This makes no sense to me and I also can't figure out why..
