### ISSUE TITLE
sidecar: Use injectLabels optimizations

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3571]
AC:
* Use the same optimization as [here](https://github.com/thanos-io/thanos/pull/3568) but in the sidecar.

The nontrivial thing is to parse the map in an ordered fashion so labels are sorted: 
![image](https://user-images.githubusercontent.com/6950331/101897776-f8369700-3ba2-11eb-957f-bf4e82a400a9.png)

https://github.com/thanos-io/thanos/blob/4b89eea19e6c477e5d272aab9db6b46afee8d2bb/pkg/store/prometheus.go#L163

**Comment by Biswajitghosh98** [comment]
Hi @bwplotka!
I was looking forward to be a part of Thanos, and I'd like to start with this issue

**Comment by kakkoyun** [comment]
Still valid.

**Comment by longngn** [comment]
@bwplotka I'm looking into this issue. However, I stumbles across some problems:

1. Does Prometheus `/api/v1/series` API guarantee to return sorted labels?
2. Even if the API returns sorted labels, JSON spec and `encoding/json` package don't guarantee object ordering (see more: https://github.com/golang/go/issues/27179)
