### ISSUE TITLE
Config Validator / Checker

### ISSUE THREAD

**Issue by midnightconman** [thanos-io/thanos#3622]
### Is your proposal related to a problem?

At the moment I don't think there is a safe way of testing config sanity in CICD... I would want a flag on each component (could be shared), that would cause the app to exit 0 if config is sane and non-zero if config has issues OR we could have a separate application for this (maybe like a linter maybe add it to the `tool` subcommand)?

### Describe the solution you'd like

I would want a flag on each component (could be shared), that would cause the app to exit 0 if config is sane and non-zero if config has issues OR we could have a separate application for this (maybe like a linter)?

### Describe alternatives you've considered

An alternative approach would be to run the thanos binary and exit after a pre-defined period if no error is caught, this approach can be problematic (and result in false positives / negatives)

**Comment by kakkoyun** [comment]
Sounds really a good idea. There are lots of possibilities in this area. Some quick ideas: `--dry-run` mode or an additional tool the check all the configuration. The best way to hook into the flag library to generate all these necessary configuration checkers.

Open questions:
* How much do we want to validate?
* Configuration files? Types? Syntactic validation? or Semantic validation?
* Against which versions?
* Dependent flags

cc @bwplotka

**Comment by kakkoyun** [comment]
Still valid.
