### ISSUE TITLE
Docs should define the term "chunk"

### ISSUE THREAD

**Issue by bboreham** [thanos-io/thanos#3627]
The word is used in lots of places, e.g.:
https://thanos.io/tip/thanos/design.md/ "Chunk files hold a few hundred MB worth of chunks each."
https://thanos.io/tip/thanos/storage.md/ "This can be used to find chunk with samples in the chunk files."

It would be good to define it, like "a chunk is part of the data structure of Prometheus TSDB, holding up to 120 samples for a single timeseries".

**Comment by Biswajitghosh98** [comment]
Seems like we can define chunks at one place, and hyperlink the definition wherever it's used. WDYT? @GiedriusS @bboreham

**Comment by bwplotka** [comment]
This is actually also a Prometheus TSDB issue.

> a chunk is part of the data structure of Prometheus TSDB, holding up to
120 samples for a single timeseries".

But also a chunk .. file - is the file in TSDB block that contains up to
0.5GB worth of chunk entries in binary format.

Anyway, let's document better, thanks! (:

Kind Regards,
Bartek Płotka (@bwplotka)

**Comment by bboreham** [comment]
Personally I think hyper-linking every time is is used would get annoying.
You could have a "glossary" section in the docs that defines terms.
