### ISSUE TITLE
[Consult] Why do we remove the cache directory on downsampling failure

### ISSUE THREAD

**Issue by xiaozongyang** [thanos-io/thanos#3628]
Hi Thanos team, 

I'm got confused when I read the following source code. The code says that all cached directories will be removed on error.
```go
        // copy from https://github.com/thanos-io/thanos/blob/v0.17.2/cmd/thanos/downsample.go#L169-L173
	defer func() {
		if err := os.RemoveAll(dir); err != nil {
			level.Error(logger).Log("msg", "failed to remove downsample cache directory", "path", dir, "err", err)
		}
	}()
```
If we got an error during the downsampling job, and the message printed in stdout, but we can never find the working files. It's difficult to find out what happened without the working files.
Maybe we can should these files to another temporary directory (e.g. `/tmp`) for debugging instead of removing them.

**Comment by kakkoyun** [comment]
I guess we don't want to produce any form of garbage. We might consider moving them to `/tmp` or somewhere else when `debug` mode enabled. Of course, if this really needed. Have you ever encountered this use case? 

cc @bwplotka @yeya24

**Comment by bwplotka** [comment]
Agree, I think I would be curious how useful it would be.

Also imagine you have disk too low space error. If we don't remove then Compactor will not repair itself (:

**Comment by xiaozongyang** [comment]
Thank you guys for explaining these details. @kakkoyun @bwplotka 

> Of course, if this really needed. Have you ever encountered this use case?

Hi @kakkoyun,
Actually, we've run into some errors shown in the log, but when we find out it happened we can't find the actual file which causes the error. It's annoying to debug.

> Also imagine you have disk too low space error. If we don't remove then Compactor will not repair itself (:

Hi @bwplotka,
IMO, disk too low space is not the normal case may be something wrong, we can monitor and raise an alert about that or we increase the capacity of that disk instead of letting thanos repair that issue. 

Just correct me if I mis-undertood anything here.
