### ISSUE TITLE
Moving blocks from older version of Thanos S3 bucket to a new S3 bucket that's being used by a new version of Thanos. 

### ISSUE THREAD

**Issue by rmccarthy-ellevation** [thanos-io/thanos#3635]
We are rebuilding our monitoring stack and want to move the blocks that our current version of Thanos is storing in S3 to a new S3 bucket that will be used by our new and improved Thanos. Is this possible using the replication tool, or is there some other way? Can we move the blocks and have the new version of Thanos recognize them as data that can be queried?

**Comment by bwplotka** [comment]
You can totally do that straight away. Feel free to use *thanos tools
bucket replicate*

The format did not change much, so all is compatible.

Kind Regards,
Bartek Płotka (@bwplotka)
