### ISSUE TITLE
Support matchers in gRPC LabelNames and LabelValues requests

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#3637]
Initial support for label matchers API is done in https://github.com/thanos-io/thanos/pull/3566.

It just simply sends `Series` requests to stores and deduplicate the results at the API level.

It works but we might improve more by adding matchers to `LabelNames` and `LabelValues` gRPC requests to push down matchers to each store. Each store can get the matched labels and send them back. The network load would be better.

AC:
1. Add `matchers` to `LabelNames` and `LabelValues` gRPC requests
2. For each store, implement the logic to filter the labels based on the given matchers

**Comment by Biswajitghosh98** [comment]
@yeya24 While I'd like to give it a try.

**Comment by yeya24** [comment]
Sorry for being unclear. I am already working on this one. Currently blocked by #3639

**Comment by Biswajitghosh98** [comment]
No worries. I'll pick a different issue 😄

**Comment by pstibrany** [comment]
Hello, if there is no update on this, I would like to implement support for matchers in LabelNames and LabelValues calls in Thanos `store` (gateway) component. (`*BucketStore` type).

My plan is to mimick the implementation in Prometheus TSDB: basically call `blockSeries` with supplied matchers (in case of LabelValues, matchers would be extended with `labelName!=""`) but no chunk-fetching. From returned series set, code would extract unique label names or label values and return them. If no matchers were used, we would reuse current implementation.

My plan does not include implementing support for matchers in other `StoreServer` implementations.

@yeya24 Please let me know if you are still working on this or have other plans, or I can go ahead with my plan.

Thank you!

**Comment by bwplotka** [comment]
Sounds good to me! I think we started some work on sidecar but not for store.

**Comment by yeya24** [comment]
This has been solved. Close.
