### ISSUE TITLE
api: Ability to set default step for queries.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3651]
Default step does not make much sense if the scrape interval is common (e.g 15s). Getting too low makes things extremely slow for no good reason.

Flag on querier might be a good idea.

**Comment by spaparaju** [comment]
Will pick up this issue @bwplotka

**Comment by spaparaju** [comment]
I see Thanos Query got two possible ways to customise the downsample / resolution for queries:  

1. specify 'step' duration along with enabling 'enableAutodownsampling' to calculate 'max_source_resolution'
2. explicitly specify 'max_source_resolution'

I am trying to understand the purpose of two options to arrive at seemingly a single outcome: Query time downsampling. 
Is there an advantage of choosing one option over another?

**Comment by bwplotka** [comment]
Sorry for not answering @spaparaju but I am quite confused why we speak about downsampling here. 

Looks like https://github.com/thanos-io/thanos/pull/3740 did most of the work, so let's see if we can merge this 🤗
