### ISSUE TITLE
Compactor is not exposing thanos_compact_downsample_total metric.

### ISSUE THREAD

**Issue by Kami1135** [thanos-io/thanos#3658]
**Compactor Dockerfile**
```
ARG VERSION="v0.16.0"
FROM thanosio/thanos:${VERSION}
USER root
EXPOSE 10902
COPY conf/prod/bucket_config.yml /etc/thanos/bucket_config.yml
CMD ["compact", \
        "--log.level=info", \
        "--data-dir=/data", \
        "--objstore.config-file=/etc/thanos/bucket_config.yml", \
        "--http-address=0.0.0.0:10902", \
        "--retention.resolution-raw=0d", \
        "--retention.resolution-5m=0d", \
        "--retention.resolution-1h=0d", \
        "--compact.concurrency=1", \
        "--block-sync-concurrency=1", \
        "--wait"]
```

**Object Storage Provider**: S3 (bucket size = 30 TB, number of object: 100k)

**What happened**:
By querying  long term data(even 2 days) no data is returned and the error rate at thanos store grpc_server_handled_total and thanos_objstore_bucket_operation_failures_total(specifically at get_range) goes high and OOM kill of container(on 
r5.xlarge ec2 instance). upgraded to r5.2xlarge query doesn't improve any thing except OOM kill.

And on:

> thanos tools bucket downsample --objstore.config-file=config-prod.yml
> level=info ts=2020-12-21T12:40:49.66655364Z caller=main.go:98 msg="Tracing will be disabled"
> level=info ts=2020-12-21T12:40:49.666617356Z caller=factory.go:46 msg="loading bucket configuration"
> level=info ts=2020-12-21T12:40:49.668338286Z caller=downsample.go:150 msg="starting downsample node"
> level=info ts=2020-12-21T12:40:49.669097293Z caller=intrumentation.go:48 msg="changing probe status" status=ready
> level=info ts=2020-12-21T12:40:49.669126773Z caller=downsample.go:104 msg="start first pass of downsampling"
> level=info ts=2020-12-21T12:40:49.669701121Z caller=intrumentation.go:60 msg="changing probe status" status=healthy
> level=info ts=2020-12-21T12:40:49.669728677Z caller=http.go:58 service=http/server component=downsample msg="listening for requests and metrics" address=0.0.0.0:10902
> level=info ts=2020-12-21T12:41:28.539252268Z caller=fetcher.go:458 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=38.870098305s cached=17395 returned=15059 partial=0
> level=info ts=2020-12-21T12:41:28.575903002Z caller=downsample.go:119 msg="start second pass of downsampling"
> level=info ts=2020-12-21T12:41:45.344999069Z caller=fetcher.go:458 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=16.769056561s cached=17395 returned=15059 partial=0
> level=warn ts=2020-12-21T12:41:45.353912126Z caller=intrumentation.go:54 msg="changing probe status" status=not-ready reason=null
> level=info ts=2020-12-21T12:41:45.353955919Z caller=http.go:65 service=http/server component=downsample msg="internal server is shutting down" err=null
> level=info ts=2020-12-21T12:41:45.854193667Z caller=http.go:84 service=http/server component=downsample msg="internal server is shutdown gracefully" err=null
> level=info ts=2020-12-21T12:41:45.854267242Z caller=intrumentation.go:66 msg="changing probe status" status=not-healthy reason=null
> level=info ts=2020-12-21T12:41:45.854314314Z caller=main.go:160 msg=exiting

Upon further checking found out that thanos_compact_downsample_total is not exposed by compactor. Seems that downsample is not working here. 
Would like to hear what can be the possible issue and how to resolve it. As compactor is not throwing any err message.

And **thanos tools bucket verify --objstore.config-file=config-prod.yml** returns alot of block and all have this in common
```
"thanos": {
		"labels": {
			"cluster": "prod",
			"replica": "0"
		},
		"downsample": {
			"resolution": 0
		},
		"source": "compactor"
	}
```
and with a deletion marker:
``` 
"thanos": {
		"labels": {
			"cluster": "prod",
			"replica": "2"
		},
		"downsample": {
			"resolution": 0
		},
		"source": "sidecar"
```
and 
```
	"thanos": {
		"labels": {
			"cluster": "prod",
			"replica": "10"
		},
		"downsample": {
			"resolution": 0
		},
		"source": "ruler"
	}
```

Bucket view: 
--
![Screen Shot 2020-12-21 at 1 47 10 PM](https://user-images.githubusercontent.com/20557059/102757555-5168ac80-4393-11eb-8087-72d9c8d466ac.png)

**What you expected to happen**:
Expectation was querying long term data.

**Comment by Kami1135** [comment]
Long range queries now improved with this configuration:
```
CMD ["query", \
      "--http-address=0.0.0.0:9090", \
      "--grpc-address=0.0.0.0:9190", \
      "--query.replica-label=replica", \
      "--store.sd-files=/etc/thanos/thanos-targets.yml", \
      "--query.auto-downsampling", \
      "--query.partial-response", \
      "--query.timeout=1m", \
      "--query.max-concurrent=40", \
      "--store.response-timeout=2500ms"]
```
 but still struggling with downsampling thanos_compact_downsample_total (not even exposed by compactor).
 Will Really appreciate if someone  know if some unblock me here.

**Comment by CryptoTr4der** [comment]
+1
