### ISSUE TITLE
Give better log info regarding which memcached type the logs are from 

### ISSUE THREAD

**Issue by wiardvanrij** [thanos-io/thanos#3667]
When checking log messages from the Store, you could find something like this:

```
level=warn msg="failed to fetch items from memcached" err="read tcp 10.42.8.248:61293->10.42.8.159:11211: i/o timeout"
```

Yet it is not clear which memcached type is being referenced. This could be either the index cache or the bucket cache. 

It should include either `caching-bucket` or `index-cache` (somewhat in line with flags).

**Comment by wiardvanrij** [comment]
Still needed

**Comment by bwplotka** [comment]
Yes! Help wanted.

**Comment by wiardvanrij** [comment]
Done
