### ISSUE TITLE
Add a debug log for each error on memcached batch requests

### ISSUE THREAD

**Issue by wiardvanrij** [thanos-io/thanos#3668]
When doing batch requests on the memcached client, it will catch errors but continue if there are items in the batch present. As log message, IF an error exists, it will use the latest error received in the batch loop. While this is fine for 'info' messages, it would be nice to have a debug log in the batch loop. Logging every error that has been made.

**Comment by yeya24** [comment]
Hi, I don't have many experiences with Memcached. I think logging every error is okay, but is it too verbose? 
If one operation in batches fails, then other operations in this batch might fail too because now your Memcached is under a high load.

**Comment by wiardvanrij** [comment]
My idea was to change nothing regarding loglvl = info. Just log the latest. Yet I believe loglvl=debug should log every error. It is verbose, but if we enable debug mode, it should not be too verbose.

**Comment by wiardvanrij** [comment]
Still needed

**Comment by wiardvanrij** [comment]
I still have to make this :D
