### ISSUE TITLE
Ability to deduplicate labels on compact phase

### ISSUE THREAD

**Issue by elmariofredo** [thanos-io/thanos#3673]
### Is your proposal related to a problem?

Running prometheus in HA will produce duplicated data on object store, which is consuming twice as storage than expected. 

### Describe the solution you'd like

Compact component should accept `--compact.replica-label` similar to #1174 and delete duplicate blocks.

### Describe alternatives you've considered

None, if there is any please let me know.

**Comment by GiedriusS** [comment]
Hi, have you looked into vertical compaction: https://thanos.io/tip/components/compact.md/#vertical-compactions? I think it solves your problem.

**Comment by elmariofredo** [comment]
@GiedriusS yes! That's exactly what I was looking for, sorry I missed it in docs and I was looking just into list of compact command options and hidden options are not listed there 🙁. Thanks for reply!
