### ISSUE TITLE
lint: Add linter for go-kit/logger

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3680]
It would be awesome to detect those kinds of issues automatically on CI:

![image](https://user-images.githubusercontent.com/6950331/103285501-37a01880-49d6-11eb-9f0e-9195340748ef.png)

Let's research on go-kit/log project first if anything like this exists, if not we can write out own.

**Comment by imskr** [comment]
I can work on this @bwplotka assign me!

**Comment by bwplotka** [comment]
👍🏽 thanks!
