### ISSUE TITLE
Thanos receiver is showing more data than the retention period configured

### ISSUE THREAD

**Issue by anoop2503** [thanos-io/thanos#3683]
**Thanos, Prometheus and Golang version used**:

Thanos: thanos:v0.14.0

**Object Storage Provider**:
EBS only. No object storage configured.

**What happened**:
I have deployed thanos receiver as statefulset and configured the retention period as 4h. However, I can see last 8h of data.

**What you expected to happen**:
If the retention period is 4h, thanos receiver should store only 4h of data.

**How to reproduce it (as minimally and precisely as possible)**:
Set up thanos receiver with following args.

```
      - args:
        - receive
        - --http-address=0.0.0.0:10902
        - --tsdb.path=/data
        - --receive.replication-factor=1
        - --receive.local-endpoint=$(NAME).thanos-receiver.$(NAMESPACE).svc.cluster.local:10901
        - --remote-write.address=0.0.0.0:10908
        - --tsdb.retention=4h
```

**Environment**:
- OS (e.g. from /etc/os-release): RHEL 7

**Comment by bwplotka** [comment]
Hi, this is expected. Receiver deletes data in batches, same as Prometheus. Especially with such small retention, such delay in delete might happen.

We can however limit data return virtually as well if needed. Wonder if this is really important 🤗 What's your use case?
