### ISSUE TITLE
Use https://github.com/efficientgo/tools as "common" instead of our utils.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3684]
Hi,

I ported some of our core, simple Thanos packages as `testutil`, `closing`, `exhausting`, `path or content` and there is an opportunity to do more. The reason is that we have lot's of open source project that needs some of the cool libs we wrote.

There is of course anti-pattern of introducing common imports like this. We seen this with prometheus/common. The main problem is that it leaks to others depending on Thanos (e.g Cortex).

That's why with https://github.com/efficientgo/tools I made it extremely low dep (literally none) with focused multiple modules that are targeting only one dep if needed (e.g currently logging, kinping, core (no dep)).

I believe this allows us to not repeat effort everywhere and allow us to share our core libs wider (and build community). 

However, it's up to us and also Cortex if we want to introduce this. Cortex has it's own `common` module with even more stuff, but it has even more problems with dep hell. Any thoughts?

cc @kakkoyun @yeya24 @pracucci @brancz @squat 

Take your time, happy holidays!

**Comment by brancz** [comment]
Thanos is a monorepo through and through .. I don't really think it's worth splitting things like this out

**Comment by roidelapluie** [comment]
go1.17 will solve a bunch of the issues that makes it required to move this out of thanos: https://github.com/golang/go/issues/36460

**Comment by bwplotka** [comment]
How lazy loading will help with dependency hell and ensuring your other deps are not colliding with Thanos module deps?
