### ISSUE TITLE
Mixin: Substitute aggregate labels in ThanosSidecarPrometheusDown and similar alerts

### ISSUE THREAD

**Issue by codemug** [thanos-io/thanos#3699]
## Problem

Consider the `ThanosSidecarPrometheusDown` alert expression in the [mixin](https://github.com/thanos-io/thanos/blob/5c12d46b8ed3cc764560feb63e5b5255ee3b9e9a/mixin/alerts/sidecar.libsonnet#L12):

```
 sum by (job, pod) (thanos_sidecar_prometheus_up{%(selector)s} == 0)
```

The expression has a placeholder for selector labels but the aggregation on sum is being done by fixed labels `job` & `pod` which might not necessarily exist on a prometheus deployment. This kind of defeats the purpose of having mixins. Ideally, the label names in the `by` aggregator should also be substituted by the deployer. 

For a more effective mixin, the labels in the `by` aggregator should be replaced with a placeholder. 

The other two alerts that should also have this placeholder are:

* ThanosSidecarUnhealthy
* ThanosRuleRuleEvaluationLatencyHigh

**Comment by kakkoyun** [comment]
@codemug Thanks for opening this issue. We know there are a lot of work needs to be done for the mixin. Feel free to contribute. Help wanted.
