### ISSUE TITLE
Put `objstore` outside of Thanos main repo?

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3701]
Rationales:

* Even with Go 1.7 importing whole Thanos module is... hard. Lot's of `replace` statements and overall many dependencies.
* Release model is not within semver semantics.

We can actually have objstore as separate module. That might work as long as it's hermetic and does not use further Thanos imports. This will help importability but release model would be equally bad as now.

This module is so well defined and establish that it would be worth to main in separe repo.

Wonder @pracucci if it's not something Cortex and other projects would be interested more. Most likely it would improve chances for external maintainers just of this focused module. I definitely would love to use for other smaller OSS project, but don't want to due to Thanos deps. 🤔 

@brancz @kakkoyun @squat

**Comment by kakkoyun** [comment]
I wonder if we can use a nested module for this rather than extracting that out from the repo. Does anyone have any experience of this? I have seen an implementation of it on the open-telemetry repo.

FYI accepted lazy module proposal https://github.com/golang/go/issues/36460

cc @prmsrswt

**Comment by brancz** [comment]
I love this idea. I use the `objstore` package all the time for various projects and indeed having to import all of Thanos is a bit excessive.

**Comment by pracucci** [comment]
I would also embrace it 👍

**Comment by yeya24** [comment]
+1 to this and it would be good to continue if it is possible

**Comment by brancz** [comment]
This has really been grinding my gears so I started https://github.com/brancz/objstore which seems to work for the Parca project.

**Comment by brancz** [comment]
Goes without saying hopefully, more than happy to move this under the thanos org if anyone wants to take over from here.

**Comment by bwplotka** [comment]
Makes sense. I think @onprem you also created a fork of `objstore` somewhere? Maybe we can follow up on making some of it an official fork?

>  (I did end up removing an e2e test and the tracing wrapper both of which I don't need and didn't want to deal with).
