### ISSUE TITLE
Missing long term data

### ISSUE THREAD

**Issue by leoncard** [thanos-io/thanos#3704]
Hello, we are having an issue with the retention period on thanos.

We are using thanos v0.10.1 with the following configuration

--retention.resolution-raw=14d
--retention.resolution-5m=30d
--retention.resolution-1h=180d

i.e. 

14d of raw data
30d of 5m data
180d of 1h data

Our storage is minio.

When visualizing data, what we seem to have is

14d of raw data, which looks alright
42d of 25m data, where it should be 30 days with 5m retention
150d of 5h data, where it should be 180d with 1h retention

We are visualizing data with Grafana, which we initially thought could be the issue. 

So we started calling the api endpoint directly, and we still don't get the expected datapoints back.

Any suggestions on what we can do to debug the issue? It feels like something is wrong with the compression, or we have corrupt blocks.

**Comment by GiedriusS** [comment]
What queries are you sending exactly? Do the metrics appear if you use no functions/operators? With what options are you running Thanos Query? Do you have anything in front of it?

**Comment by leoncard** [comment]
Hello, thanks for replying,

The query could be as simple as `up`, with no functions or operators.

I'm running the pod with the following args

- query
- --log.level=info
- --log.format=logfmt
- --grpc-address=0.0.0.0:10901
- --http-address=0.0.0.0:10902
- --query.replica-label=prometheus_replica
- --query.auto-downsampling
- --store.sd-dns-resolver=miekgdns
- --store=dnssrv+_grpc._tcp.thanos-store-grpc.monitoring.svc.cluster.local
- --store=dnssrv+_grpc._tcp.thanos-sidecar-grpc.monitoring.svc.cluster.local
- --store=fh1-prom01.dun.fh:10901
- --store.sd-interval=5m

The issue also happens when calling the api within the `query` pod, so I would assume there is nothing in front of it.

For instance if I have the interval of October 9 - October 10, i.e. within the 180 days interval, I was expecting to have 1 hour (3600s) resolution.

http://localhost:10902/api/v1/query_range?query=up&start=1602226800&end=1602313200&step=3600&max_source_resolution=auto

But the query returns no data

{"status":"success","data":{"resultType":"matrix","result":[]}}

It starts returning data if I change the resolution to 18000 (5 hours).
