### ISSUE TITLE
Bucket rewrite tool can work on Prometheus blocks

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#3706]
### Is your proposal related to a problem?

In theory, Thanos supports `filesystem` bucket so we can use `thanos tools rewrite` to rewrite Prometheus TSDB blocks. However, because Prometheus blocks doesn't have `Thanos` labels in block meta, the step to upload the new block will fail. 

Error log:

```
level=info ts=2021-01-08T05:22:02.725621295Z caller=tools_bucket.go:917 msg="wrote new block after modifications; flushing" source=01ETGVB67TYCJ5XPVSDVESF8WM new=01EVG73JTQNQ0W175HBJGQ3BFH
level=info ts=2021-01-08T05:22:02.735921895Z caller=tools_bucket.go:926 msg="uploading new block" source=01ETGVB67TYCJ5XPVSDVESF8WM new=01EVG73JTQNQ0W175HBJGQ3BFH
level=error ts=2021-01-08T05:22:02.736121758Z caller=main.go:156 err="empty external labels are not allowed for Thanos block.\ngithub.com/thanos-io/thanos/pkg/block.Upload\n\t/home/yeya24/hub/gowork/thanos/pkg/block/block.go:93\nmain.registerBucketRewrite.func1.1\n\t/home/yeya24/hub/gowork/thanos/cmd/thanos/tools_bucket.go:927\ngithub.com/oklog/run.(*Group).Run.func1\n\t/home/yeya24/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nupload\nmain.registerBucketRewrite.func1.1\n\t/home/yeya24/hub/gowork/thanos/cmd/thanos/tools_bucket.go:928\ngithub.com/oklog/run.(*Group).Run.func1\n\t/home/yeya24/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\ntools bucket rewrite command failed\nmain.main\n\t/home/yeya24/hub/gowork/thanos/cmd/thanos/main.go:156\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"

```

(Write your answer here.)

### Describe the solution you'd like

Not sure if there is a good way to do this.

(Describe your proposed solution here.)

### Describe alternatives you've considered

Add a flag to specify external labels for the newly created blocks in rewrite.

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by yeya24** [comment]
Got a workaround for this now.
1. Use sidecar and filesystem as obj store to copy these blocks to another directory. After this step, external labels will be added.
2. Use rewrite tool
3. Copy the new block back to the TSDB directory.

**Comment by bwplotka** [comment]
Still let's reopen, I love this - we could make non Thanos version as well 🤗

**Comment by yeya24** [comment]
The easiest way to do this is to add one flag `--tsdb.blocks-dir`. With this flag, we know that the blocks are in one local directory and we don't require external labels checking in this case. Also with this flag we don't need to add the `FILESYSTEM` block config. 

What do you think about this approach? If it sounds good, I can take this one.

**Comment by bwplotka** [comment]
What problems we are solving BTW? 

* Is this about just `--tsdb.blocks-dir` shortcut for specifying full `--objstore.config`? We could add this flag and internally map to `--objstore.config=....` sheningans.

I would not and special code for tsdb local dir, but maybe instead `--tsdb-data` to indicate raw Prometheus blocks? That would allow same effect.

There might be a bigger problem on how to remove overlap with `promtool` - Ideally we could have generic operations on blocks on object storage level, and then `promtool` could just import this with FILESYSTEM` and we could have `Prometheus` scoped tool with reusing code.

**Comment by yeya24** [comment]
I feel using `--tsdb-data` with `FILESYSTEM` bucket and only `--tsdb-blocks-dir` the same thing. So this doesn't matter.
I am not sure about promtool, are we going to upstream this feature?

**Comment by bwplotka** [comment]
>  But there is some circular dependency problem if Prometheus needs to import Thanos, will this be a problem?

Yes I think this will be problematic, unless we put this in separate module 🤔 But let's not open this pandora box. 

Let's recommend using `thanos toiols bucket rewrite tool` with Prometheus - we can't use `promtool` so it's up to promtool to either port changes or just let `thanos tools` to do the work

**Comment by yeya24** [comment]
I am looking at this change. We can do this by adding a boolean value to this method signature to not check external labels https://github.com/thanos-io/thanos/blob/master/pkg/block/block.go#L92.

But this way it changes the [upload](https://github.com/thanos-io/thanos/blob/master/pkg/block/block.go#L71) API, is this an acceptable change?

**Comment by bwplotka** [comment]
It is an acceptable change, but it will involve lots of changes and worse API (more arguments, including bool ones). 


We can do different things:

* We can remove this check form `Upload` and add separate method that checks it. Then update some Upload callers that require this check.
* We create `upload(` method that has this bool value and `Upload` will use it with check = true. Then we can create `PromUpload` that will do this with check = false. 

WDYT?
