### ISSUE TITLE
Block Viewer: Overlapping blocks are not selectable/clickable

### ISSUE THREAD

**Issue by prmsrswt** [thanos-io/thanos#3709]
In the new Block Viewer, the overlapping blocks with same resolution and compaction level are rendered over each other. This means that you can only select the top-most block to view it's information. This is a major issue because now debugging this becomes significantly harder as you can't see the ULIDs of all of the overlapping blocks.

![Screenshot from 2021-01-08 14-02-49](https://user-images.githubusercontent.com/29674758/104093149-a458c400-52ae-11eb-8dec-1075f2dbf63f.png)

In the old UI, overlapping blocks were put in separate rows, doing this in the new UI would make sense as well.

![Screenshot from 2021-01-08 14-01-31](https://user-images.githubusercontent.com/29674758/104093164-c94d3700-52ae-11eb-9d6d-f820d98dc46f.png)

**Comment by Namanl2001** [comment]
I would like to work on this issue.

**Comment by yeya24** [comment]
This case happens a lot with the bucket rewrite tool. Help wanted!.

@Namanl2001 Please go ahead.
