### ISSUE TITLE
compactor: 1h downsampling data is not continuous

### ISSUE THREAD

**Issue by diemus** [thanos-io/thanos#3711]
**Thanos, Prometheus and Golang version used**:
```
thanos, version 0.17.0 (branch: HEAD, revision: 4899d9a3378c7dbd1f635f5271624cda8caec001)
  build user:       root@432c5bd5f94c
  build date:       20201118-17:38:06
  go version:       go1.15
  platform:         linux/amd64
```

**Object Storage Provider**:

S3 compatible service

**What happened**:
The data after downsampling to 1h is no longer continuous, the raw data and 5m downsampling does not have this problem. 

![image](https://user-images.githubusercontent.com/9145160/104143457-75e7ff80-53fa-11eb-97bf-4e46ac8d4695.png)
![image](https://user-images.githubusercontent.com/9145160/104143467-826c5800-53fa-11eb-82c4-60aef52aff58.png)
![image](https://user-images.githubusercontent.com/9145160/104143472-8d26ed00-53fa-11eb-81b4-136c6a3d3010.png)

there are parts of the data are continuous, it's not downsampling to 1h for now

![image](https://user-images.githubusercontent.com/9145160/104143724-a3817880-53fb-11eb-912c-776f07a4cbf2.png)

**What you expected to happen**:

all downsampling data should be continuous

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

I see some warning logs about downsampling, and don't know why
```
level=warn ts=2021-01-10T08:30:09.927386011Z caller=streamed_block_writer.go:114 msg="empty chunks happened, skip series" series="{__name__='xxxxxx'}"
level=warn ts=2021-01-10T08:30:10.26568195Z caller=streamed_block_writer.go:114 msg="empty chunks happened, skip series" series="{__name__='xxxxxx'}"
```

**Comment by mveroone** [comment]
Hi.
I think it's similar to my problem which i was about to post :
![image](https://user-images.githubusercontent.com/44051537/104159561-d887ce00-53ef-11eb-9190-0fd14fdc599f.png)
Do you think it's the same problem ?

**Comment by qube222pl** [comment]
@mveroone  take a look on my issue  #3721
It look exacly like your

**Comment by kakkoyun** [comment]
Hey @diemus, could you please share your compactor configuration? And also have you tried with the latest version of Thanos?

**Comment by diemus** [comment]
@kakkoyun  no special configuration for compactor, I'm using 0.17.0, it's the latest version at that time

```
thanos compact 
--wait 
--compact.concurrency=5
--data-dir=/xxx/thanos-compact 
--objstore.config-file=/xxx/bucket.yml 
--retention.resolution-raw=30d 
--retention.resolution-5m=30d 
--retention.resolution-1h=30d
```
