### ISSUE TITLE
Incosistent use of `.` in CLI description

### ISSUE THREAD

**Issue by MalloZup** [thanos-io/thanos#3713]
# Description
I have noticed that our cli is not consistent with the usage of `.` at the end of lines

example: 
```
  tools bucket verify [<flags>]
    Verify all blocks in the bucket against specified issues. NOTE: Depending on issue this might take time and will need downloading all specified blocks to disk.

  tools bucket ls [<flags>]
    List all blocks in the bucket

  tools bucket inspect [<flags>]
    Inspect all blocks in the bucket in detailed, table-like way
```
As you can see the 2nd and 3rd doesn't have `.`  **NOTE**: there are many others, the example is just showcasing

# Solving problem:

- 1) short-term: we should make the CLI more consistent. E.g. either remove all `.` or use it in all CLI parameters desc
- 2) long-term: create simple automation to verify that we don't omit those punctuations.

**Comment by bwplotka** [comment]
Yes. 

Better.: Create/find lint tool to check and fix it automatically ❤️

**Comment by MalloZup** [comment]
ok thx, updated it. I think the implicit point is to keep the `.` at the end to each phrase

**Comment by mattjw79** [comment]
PR #3227 only hits the short-term goal, at this point I don't know of a tool that would capture the long-term goal. I also noticed that the help messages also had a mix of upper and lower case beginnings, so the PR also fixes that.

**Comment by MalloZup** [comment]
thx @mattjw79 !

Regarding the tool, Imho I think there is not an existing one. But imho @bwplotka  meant we create our own one, or research,

as I do see the tool, would be something like:
-  based on regex,  would scan/find like a line in a recursive dir/codebase, find line
```	cmd := app.Command(component.Compact.String(), "Continuously compacts blocks in an object store bucket.")```

- then check if all lines contains `.` at the end and are capitalized in begin.
- run this tool/script etc in Makefile target

That would be the goal imho, but I agree that we could merge the pr originally and evaluate how we could implement this.

Maybe there are other alternatives, without creating in-house things. I dunno. Like `missspell` on our tool https://github.com/client9/misspell or other things.. thx for pr..

**Comment by sachinkumarsingh092** [comment]
> Maybe there are other alternatives, without creating in-house things.

Hi @bwplotka @MalloZup, there is a spelling check script (https://github.com/kubernetes-csi/csi-release-tools/blob/master/verify-spelling.sh) in https://github.com/kubernetes-csi/csi-release-tools which uses `misspell` internally. We can raise and implement the fix for `.` in `misspell` and then we can safely use it here.
WDYT.
