### ISSUE TITLE
x509 certificate signed by unknown authority

### ISSUE THREAD

**Issue by IbraheemAlSaady** [thanos-io/thanos#3719]
I have Thanos installed with MinIO, sidecar, query, and compactor.

MinIO is exposed through an ingress (it's on a different cluster) with a self-signed certificate generated by Cert Manager. 

I'm getting an error in Compactor: `err="BaseFetcher: iter bucket: Get \"https://somedomain.com/?location=\": x509: certificate signed by unknown authority\`

I have the same thing with the sidecar and query, TLS on the sidecar, and the query. and I get the same error of `x509 certificate signed by unknown authority` 

Any help would be appreciated

Kubernetes Version: 1.18.10
Helm version: 3.4.2
Thanos Chart version: 3.3.0

**Comment by kakkoyun** [comment]
Hey @IbraheemAlSaady, what is exactly the expected behaviour here? We don't use anything fancy for TLS, it's good old Go standard library. I believe either you're missing a configuration or you have a problem with your certificates. Could you please check?

**Comment by bseenu** [comment]
Even i am facing this issue when query component is calling sidecar, my thanos sidecar is running behind istio ingress and in my dev environment i use certs signed by fake CA and i see the same error, how do i skip verify of the certs 

```
bash-3.2$ grpcurl  localhost:443 grpc.health.v1.Health.Check
Failed to dial target host "localhost:443": x509: certificate signed by unknown authority
bash-3.2$ grpcurl  -insecure localhost:443 grpc.health.v1.Health.Check
{
  "status": "SERVING"
}
```
