### ISSUE TITLE
query: preload chunks: read range for 0: allocate chunk bytes: pool exhausted" msg="returning partial response"

### ISSUE THREAD

**Issue by yanc0** [thanos-io/thanos#3720]
**Thanos, Prometheus and Golang version used**:
Thanos v0.17.2
Prometheus v2.18.1

**Object Storage Provider**:
GCS

**What happened**:
Grafana dashboards are incomplete when selected time range is getting bigger (30 days)

**What you expected to happen**:
We expect thanos to be fine with relatively small time window

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:
<details>Logs from query component
<p>

```
level=warn ts=2021-01-14T18:08:57.964182436Z caller=proxy.go:458 err="receive series from Addr: thanos-store-gateway-2.thanos-store-gateway.default.svc.cluster.local:10901 LabelSets: {clusterName=\"automation\", prometheus=\"default/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\", region=\"europe-west1\"},{clusterName=\"automation\", prometheus=\"default/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-1\", region=\"europe-west1\"},{clusterName=\"barney\", prometheus=\"default/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\", region=\"europe-west1\"},{clusterName=\"barney\", prometheus=\"default/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-1\", region=\"europe-west1\"},{clusterName=\"chprod\", prometheus=\"default/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\", region=\"europe-west6\"},{clusterName=\"chprod\", prometheus=\"default/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-1\", region=\"europe-west6\"},{clusterName=\"euprod\", prometheus=\"default/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\", region=\"europe-west1\"},{clusterName=\"euprod\", prometheus=\"default/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-1\", region=\"europe-west1\"},{clusterName=\"eusandbox\", prometheus=\"default/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\", region=\"europe-west1\"},{clusterName=\"eusandbox\", prometheus=\"default/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-1\", region=\"europe-west1\"},{clusterName=\"integration\", prometheus=\"default/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\", region=\"europe-west1\"},{clusterName=\"integration\", prometheus=\"default/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-1\", region=\"europe-west1\"},{clusterName=\"observability\", prometheus=\"default/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\", region=\"europe-west1\"},{clusterName=\"observability\", prometheus=\"default/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-1\", region=\"europe-west1\"},{clusterName=\"staging\", prometheus=\"default/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\", region=\"europe-west1\"},{clusterName=\"staging\", prometheus=\"default/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-1\", region=\"europe-west1\"},{clusterName=\"usprod\", prometheus=\"default/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\", region=\"us-central1\"},{clusterName=\"usprod\", prometheus=\"default/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-1\", region=\"us-central1\"},{clusterName=\"ussandbox\", prometheus=\"default/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\", region=\"us-central1\"},{clusterName=\"ussandbox\", prometheus=\"default/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-1\", region=\"us-central1\"},{clusterName=\"wip\", prometheus=\"default/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\", region=\"europe-west1\"},{clusterName=\"wip\", prometheus=\"default/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-1\", region=\"europe-west1\"},{prometheus=\"default/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\"},{prometheus=\"default/prometheus-operator-prometheus\", prometheus_replica=\"prometheus-prometheus-operator-prometheus-1\"},{thanos_ruler_replica=\"thanos-ruler-ruler-ruler-0\"},{thanos_ruler_replica=\"thanos-ruler-ruler-ruler-1\"},{thanos_ruler_replica=\"thanos-ruler-ruler-ruler-2\"} Mint: 1588917600000 Maxt: 1610640000000: rpc error: code = Aborted desc = fetch series for block 01EW08TPXF6C012BVC39RR3DX6: preload chunks: read range for 0: allocate chunk bytes: pool exhausted" msg="returning partial response"

```

</p>
</details>

**Anything else we need to know**:
There is an issue related to this (#1179) but we see this log on the query component. Maybe there is a problem with our storage? Too much data in blocks? We tried to tweak the ` --chunk-pool-size` parameter in the store but it does not seem to be better.

What can we do next ?

Thanks !

**Comment by kakkoyun** [comment]
Hey @yanc0, is there a way to reproduce this for us?

**Comment by yanc0** [comment]
It's really hard to reproduce it I think. The GCS object storage contains ~9TB of blocks from multiple cluters.
Compactor works fine. There are 3 Stores with 20Gi of memory each.
Thanos does not seem to scale well if queries are requesting large window of time even if graphs are pretty simple (rate() of one metric for 6 months). Sorry but I don't have much information. We don't really know how to tweak our installation and how to avoid this error.

**Comment by bjakubski** [comment]
Just started getting this.
I noticed that suddenly time series generated by thanos ruler are mostly not there anymore. These rules are using older data (with varying "offset" passed: 1d, 7d, 14d, 21d, 28d). Ruler does not seem to be really complaining about anything. Standard dashboard for ruler shows nothing interesting.
Looking further I noticed that if I do a query directly in thanos UI I get results, but also big warning (in my case taking up whole 4k monitor display):
```
No store matched for this queryreceive (sic) series from Addr: thanos-global-store-recent.monitoring.svc.cluster.local:10901 LabelSets: [name:"environment" value:"prod" , ...][...] (BIGLISTOFLISTS) Mint: 1620495503439 Maxt: 1622396303439: rpc error: code = Aborted desc = fetch series for block 01F6V34AT65CP8NXBGWAPT2V96: preload chunks: read range for 0: allocate chunk bytes: pool exhausted
```
Edited to show only important parts.

Looking at standard Thanos Store dashboard for *two* of my stores (time sharded) the "grpc_server_handled_total" metric shows practically all calls for grpc_method="Series" have grpc_code="Aborted" from the time problems started to appear

Ruler 0.20.2
Store 0.19
query 0.10.1 (I know)

No recent upgrades happened.

For now it seems restarting store instances fixes situation, but I don't know for how long it will be ok...

**Comment by c4m4** [comment]
I have the same issue too

**Comment by aarontams** [comment]
Any updates?

I am hitting the same issue when querying with longer period.
```
receive series from Addr: xyz-objectstorage-0:10911 LabelSets: {replica="replica-0"} 
Mint: 1627245044263 Maxt: 1628632800000: rpc error: code = Aborted desc = fetch series for block 01FCAZGN1FC4G65P0TDNKJAWNR: preload chunks: read range for 3: allocate chunk bytes: pool exhausted
```

I don't have the same problem when local Block Volume is used.

**Comment by mozai** [comment]
Running into it myself (using thanos v0.19), and it's blocking both thanos query and thanos compact:

> receive series from Addr: 10.240.195.76:10901 LabelSets: {environment=\"gold\", region=\"ap-northeast-2\", replica=\"prometheus-server-0\"},{environment=\"gold\", replica=\"prometheus-server-0\"},{environment=\"gold\", replica=\"prometheus-server-1\"} Mint: 1606514340000 Maxt: 1632801600000: rpc error: code = Aborted desc = fetch series for block 01FG7VSFCXK1M9X4RVDN3C0BR7: preload chunks: read range for 0: allocate chunk bytes: pool exhausted"

Tried restarting "thanos store" -- same errors.  Tried restarting with `--chunk-pool-size=4GB` and it seems happy.  This site is less than a year old, I worry I'll have to bump it up to --chunk-pool-size=8GB a year from now.

**Comment by mozai** [comment]
I've bumped `--chunk-pool-size` up to 8GB after a couple months, not a year, and already I'm getting "allocate chunk bytes: pool exhausted" errors again for only 1d of time range.
