### ISSUE TITLE
Add support for IBM cloud object storage 

### ISSUE THREAD

**Issue by huikang** [thanos-io/thanos#3722]
### Is your proposal related to a problem?

Allow users to use IBM Cloud object storage as the persistent storage. One use case is to be leveraged by cortex project [1]

[1] https://github.com/cortexproject/cortex/issues/3692

**Comment by bwplotka** [comment]
We are happy to add one, feel free to contribute it (: 

PRs welcome. As the maintainer's Team we won't have time to add it ourselves but we are happy to guide, review and help to maintain it here.

Here is the document how to add it, it's pretty simple: https://thanos.io/v0.17/thanos/storage.md/#how-to-add-a-new-client

**Comment by huikang** [comment]
@bwplotka , thanks for your feedback. I am very willing to contributing. Could you please assign me this task?

**Comment by bwplotka** [comment]
You are assigned by just saying so!


Can you.. before jumping on this make sure IBM object storage cannot be used with `S3` provider? S3 provider done by `minio` client allows to connect to any S3 API-compatible object storage. Are we sure IBM provider does not work with that? 🤗

**Comment by huikang** [comment]
@bwplotka , thanks for your reminding. IBM object storage does provide s3 sdk. So there is no need to add a new client. Closing as it is done in the current implementation 👍

**Comment by bwplotka** [comment]
awesome. Please let us know if all works on IBM side!

**Comment by huikang** [comment]
@bwplotka , it works perfect out of box!

**Comment by 09jvilla** [comment]
Hi @huikang -- did you ever try this on Cortex, or just Thanos? Curious to know if this means Cortex supports it too.

**Comment by huikang** [comment]
> Hi @huikang -- did you ever try this on Cortex, or just Thanos? Curious to know if this means Cortex supports it too.

I tested on Cortext.

**Comment by huikang** [comment]
> Sweet - so you're saying it worked there too? Did you have to do anything different? or just fill out the blocks_storage_config and it worked?

sorry for the late reply. I just fill out the blocks_storage_config and it works since IBM COS has s3 compatible API.

**Comment by 09jvilla** [comment]
Great - thank you.

**Comment by zeusal** [comment]
Hello, sorry for reply in this issue.

Can anyone tell me the correct configuration for this case? I'm trying to configure thanos with IBM COS but I get an error.

My config is:

```type: S3
    config:
      bucket: "<BUCKET NAME>"
      endpoint: "s3.direct.eu-de.cloud-object-storage.appdomain.cloud"
      access_key: "<ACCESS KEY>"
      secret_key: "<SECRET KEY>"
      signature_version2: false
      aws_sdk_auth: false
      region: "eu-de"
      list_objects_version: "v1"
      trace:
        enable: true
