### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3725]
I think all is ready to do this on GitHub side: https://github.com/github/renaming

Any objections to this change next week? 🤗

**Comment by kakkoyun** [comment]
No objections here. It's already been more than a week since you opened this issue.
What do others think @thanos-io/thanos-maintainers?

**Comment by squat** [comment]
big plus 1. we'll likely need to do some chasing down of things in the docs/website generation

**Comment by prmsrswt** [comment]
And the CI config as well. Let's do this :+1:

**Comment by bwplotka** [comment]
Let's do it... today? (:

**Comment by bwplotka** [comment]
![image](https://user-images.githubusercontent.com/6950331/109327448-411bf480-7850-11eb-9124-b9048afd8289.png)

Done. Let's fires now.
