### ISSUE TITLE
query to store communication through NodePort service 

### ISSUE THREAD

**Issue by hbo88** [thanos-io/thanos#3731]
### Is your proposal related to a problem?

can't make inter Cluster query to query communication through NodePort service

### Describe the solution you'd like

Use NodePort service to make it possible that one querier from the Ops cluster use a second querier in another Cluster as store 
### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by bwplotka** [comment]
Hey I feel like it is a user question rather, so converting to the discussion.

This should be totally doable as long as "another cluster" has network access to NodePort services (: 

Can you check that first? If you can access while being inside cluster A any service behind NodePort Service that is running in Cluster B? (:

**Comment by bwplotka** [comment]
Actually Github disabled this option for now: https://github.com/github/feedback/discussions/2952#discussioncomment-263319

**Comment by hbo88** [comment]
Hello and thank you for your quick response, 

I just verified that I can access NodePort on one Cluster from the other cluster but I still get this error , where 30105 is my nodePort : 
`connection error: desc = \"transport: Error while dialing dial tcp: address tcp/30105\\\": unknown port\""`

**Comment by hbo88** [comment]
Solved , i just remover the double quote from the --store=''@IP:NodePort'  and it works

**Comment by bwplotka** [comment]
((:
Cool
