### ISSUE TITLE
compactor: Warnings on optional retention

### ISSUE THREAD

**Issue by kfirfer** [thanos-io/thanos#3739]
Thanos version: 0.17.2

Im getting from compactor this logs `already exists in bucket`:
```
{"caller":"retention.go:31","level":"info","msg":"start optional retention","ts":"2021-01-24T10:24:56.260315417Z"}
{"caller":"retention.go:40","id":"01EWPFEQGWTB8E5YA5JYGEMXA9","level":"info","maxTime":"2021-01-21 00:00:00 +0000 UTC","msg":"applying retention: marking block for deletion","ts":"2021-01-24T10:24:56.260335143Z"}
{"caller":"block.go:143","err":"file 01EWPFEQGWTB8E5YA5JYGEMXA9/deletion-mark.json already exists in bucket","level":"warn","msg":"requested to mark for deletion, but file already exists; this should not happen; investigate","ts":"2021-01-24T10:24:56.261179244Z"}
{"caller":"retention.go:40","id":"01EWPJ0M3BT302Y5348G1DFK7X","level":"info","maxTime":"2021-01-21 00:00:00 +0000 UTC","msg":"applying retention: marking block for deletion","ts":"2021-01-24T10:24:56.261200393Z"}
{"caller":"block.go:143","err":"file 01EWPJ0M3BT302Y5348G1DFK7X/deletion-mark.json already exists in bucket","level":"warn","msg":"requested to mark for deletion, but file already exists; this should not happen; investigate","ts":"2021-01-24T10:24:56.261993065Z"}
{"caller":"retention.go:46","level":"info","msg":"optional retention apply done","ts":"2021-01-24T10:24:56.262015451Z"}
```

I don't know exactly why

This are the retention congiruation:
```
  retentionResolutionRaw: 3d
  retentionResolution5m: 30d
  retentionResolution1h: 1y
```

Any idea why he prints it out ?

**Comment by kakkoyun** [comment]
Hello @kfirfer, could you provide a little more information about your stack? Let's make sure you run a single instance of the compactor. And also this could happen when compactor hasn't finished its run. Do you see any unexpected shutdown for the compactor process?

**Comment by Robbie558** [comment]
Hey @kakkoyun, I am experiencing the same issue, and am also on v0.17.2.

We are running a single compactor instance on a K8S cluster, pushing to an S3 bucket.  We do not see any shut downs / restarts of the compactor pod.  Our retention configuration is as follows:

```
--retention.resolution-raw=14d
--retention.resolution-5m=30d
--retention.resolution-1h=180d
```

This is occurring only on our production instance. We have an integration instance on the same version and with different retention periods 7d / 14d / 30d where this issue is not occurring.

**Comment by yuanhuaiwang** [comment]
> reopened

**Comment by yuanhuaiwang** [comment]
> Closing for now as promised, let us know if you need this to be reopened! 🤗

/reopen

**Comment by sobolevskaya-k** [comment]
@kfirfer @Robbie558 hello! do you resolve problems with not working retention? I have the same troubles

**Comment by CostisC** [comment]
Hi,
I am new to Thanos project, and this same issue brought me here. 
Retention policies:
```
--retention.resolution-1h = 20d
--retention.resolution-5m =15d
--retention.resolution-raw = 4d
```

**Comment by TomokiMuto** [comment]
In my case, a configuration error was causing the data to not be deleted. Specifically, despite being run on Docker, the directory specified with --data-dir was not set as persistent storage, causing the issue.

In my environment which is in the evaluation phase, containers are frequently being recreated. This was causing the deletion flags to be set again, resetting the deletion wait time and ultimately, preventing the data from being deleted.

**Comment by bobo182** [comment]
Hello,
I have a similar problem here. We are running prometheus and thanos (sidecar, store, compact, query) in containers on a "cluster" environment with two nodes. A few day ago, I have updated to thanosio/thanos:v0.32.5 (and prom/prometheus:v2.47.2).
This morning, I found messages from thanos compact like these on all nodes:

2024-01-10T10:18:43.776690123+01:00 compact: stdout F {"caller":"block.go:185","err":"file 01HCH6CKY1HZZJQ1QMYQCP9QEM/**deletion-mark.json already exists in bucket**","level":"warn","msg":"requested to mark for deletion, but file already exists; this should not happen; investigate","ts":"2024-01-10T09:18:43.775840039Z"}

In my case, data-dir IS persistent (see below).

Any hint how to resolve this situation? 
I have already tried to stop compactor, move the file, start compactor again. No success :-(

Here is how tha thanos compact containers are set up:

podman create -t --pod pod_prometheus --restart unless-stopped --user 1001:1001     \
        --log-opt path=/data/monitoring/data/logging/compact_c1_n2.json  \
        --log-level=warn     \
        -v /data/monitoring/etc/thanos:/etc/thanos  \
        -v /data/monitoring/data/logging:/data/logging:rw  \
        -v /data/monitoring/data/compact:/data/compact:rw   \
        -v /data/monitoring/data/store:/data/store:rw   \
        --name compact   \
        thanosio/thanos:v0.32.5  compact  \
            --log.level=warn  --log.format=json  \
            --data-dir=/data/compact    \
            --objstore.config-file=/etc/thanos/bucket.yml   \
            --http-address=0.0.0.0:10906  \
            --http-grace-period=10s  \
            --retention.resolution-raw=90d     \
            --retention.resolution-5m=120d       \
            --retention.resolution-1h=150d       \
            --consistency-delay=30m            \
            --wait              \
            --wait-interval=1m

Appreciate your input :-)

**Comment by pduchnovsky** [comment]
Joining thread since I have had the same issue, running in k8s
However, it went away after a few days, the number of warn messages kept getting smaller and smaller and then disappeared.
So to me it seems this has something to do with slowly processing the data or something.

**Comment by souvik8913** [comment]
Facing similar issue :
=01HN0MJXQVXER7ZBRCDCERZV2W
ts=2024-01-31T08:15:34.203847082Z caller=block.go:185 level=warn group="0@{monitor=\"prometheus\", replica=\"prometheus-0\"}" groupKey=0@3532490200403507638 msg="requested to mark for deletion, but file already exists; this should not happen; investigate" err="file 01HN0MJXQVXER7ZBRCDCERZV2W/deletion-mark.json already exists in bucket"
ts=2024-01-31T08:15:34.204125119Z caller=compact.go:1256 level=info group="0@{monitor=\"prometheus\", replica=\"prometheus-0\"}" groupKey=0@3532490200403507638 msg="marking compacted block for deletion" old_block=01HN0MMRAVXBDQQDGDDY1JBXPY
ts=2024-01-31T08:15:34.205521779Z caller=block.go:185 level=warn group="0@{monitor=\"prometheus\", replica=\"prometheus-0\"}" groupKey=0@3532490200403507638 msg="requested to mark for deletion, but file already exists; this should not happen; investigate" err="file 01HN0MMRAVXBDQQDGDDY1JBXPY/deletion-mark.json already exists in bucket"
ts=2024-01-31T08:15:34.205815917Z caller=compact.go:1256 level=info group="0@{monitor=\"prometheus\", replica=\"prometheus-0\"}" groupKey=0@3532490200403507638 msg="marking compacted block for deletion" old_block=01HN0MPJXV1PDV06V06W54898F
ts=2024-01-31T08:15:34.207107562Z caller=block.go:185 level=warn group="0@{monitor=\"prometheus\", replica=\"prometheus-0\"}" groupKey=0@3532490200403507638 msg="requested to mark for deletion, but file already exists; this should not happen; investigate" err="file 01HN0MPJXV1PDV06V06W54898F/deletion-mark.json already exists in bucket"
ts=2024-01-31T08:15:34.207502477Z caller=compact.go:1256 level=info group="0@{monitor=\"prometheus\", replica=\"prometheus-0\"}" groupKey=0@3532490200403507638 msg="marking compacted block for deletion" old_block=01HN0MRDGVTD1D5MTQZTD2FH1H
ts=2024-01-31T08:15:34.209100892Z caller=block.go:185 level=warn group="0@{monitor=\"prometheus\", replica=\"prometheus-0\"}" groupKey=0@3532490200403507638 msg="requested to mark for deletion, but file already exists; this should not happen; investigate" err="file 01HN0MRDGVTD1D5MTQZTD2FH1H/deletion-mark.json already exists in bucket"
ts=2024-01-31T08:15:34.209387556Z caller=compact.go:1256 level=info group="0@{monitor=\"prometheus\", replica=\"prometheus-0\"}" groupKey=0@3532490200403507638 msg="marking compacted block for deletion" old_block=01HN0MT83VP357JF8FTWKX52D4
ts=2024-01-31T08:15:34.211040192Z caller=block.go:185 level=warn group="0@{monitor=\"prometheus\", replica=\"prometheus-0\"}" groupKey=0@3532490200403507638 msg="requested to mark for deletion, but file already exists; this should not happen; investigate" err="file 01HN0MT83VP357JF8FTWKX52D4/deletion-mark.json already exists in bucket"
ts=2024-01-31T08:15:34.211320093Z caller=compact.go:1256 level=info group="0@{monitor=\"prometheus\", replica=\"prometheus-0\"}" groupKey=0@3532490200403507638 msg="marking compacted block for deletion" old_block=01HN0MW2PTCM367DWZM2FRKJEG



Also seeing the number of Objects increasing rapidly in Object Store .
Object Storage used: Open Stack swift
thanos : /thanos:v0.32.5
 args:
            - compact
            - --log.level=info
            - --data-dir=/tmp/thanos-compact
            - --objstore.config-file=/creds/swift_access_info.yml
            ###- --sync-delay=5m
            - --retention.resolution-raw=2d
            - --retention.resolution-5m=10d
            - --retention.resolution-1h=30d
            - -w
            ###- --delete-delay=24h
            ###- --sync-block-duration=5m
            - --compact.concurrency=15


Object Storage NUmber of Objects counts increasing rapidly:

Object Count45202
Size223.18 GB
Date CreatedJan 1, 1970
Public Access[Link](https://radosgw.jpe6c.jaws.jio.com/swift/v1/AUTH_d72777dde24340bea1d4504c47b4fc87/SRE_OBS_MON_STG001)

**Comment by alen-z** [comment]
A lot of:
```
requested to mark for deletion, but file already exists; this should not happen; investigate
```
Looking to find a solution...
