### ISSUE TITLE
Thanos multi tenancy based on a label

### ISSUE THREAD

**Issue by IbraheemAlSaady** [thanos-io/thanos#3741]
I'm trying to look for documentation regarding multi-tenancy setup with Thanos. All I can find is [this](https://thanos.io/tip/operating/multi-tenancy.md/) and it's really that clear to me.

What I'm looking for is basically to point my Grafana instance to an endpoint and I can pass a label filter to it (perhaps through a query param). Is this possible with the Thanos query component?

I have read around that some people are using the receiver component, is there another way?

My setup is as follows, I have a single Prometheus instance with the sidecar, and a query instance. Currently my Grafana is pointed at the querier. (There will be multiple clusters eventually)

There is a project on GitHub called [prom-label-proxy](https://github.com/openshift/prom-label-proxy), I'm trying to achieve the exact same goal, but with Thanos components

**Comment by bwplotka** [comment]
Sorry for the lag in response!

We actually recommend using https://github.com/prometheus-community/prom-label-proxy and our documentation assumes (and proposes) to use it on top of Thanos APIs! We actually maintain https://github.com/prometheus-community/prom-label-proxy (Note to use `prometheus-community` org not `openshift` fork 🤗 

Hope that makes sense, if not we can reopen. You can find cool example how to deploy something like you mention here: https://katacoda.com/thanos/courses/thanos/7-multi-tenancy

**Comment by IbraheemAlSaady** [comment]
Thanks for getting back to me for this @bwplotka. I’ll have a look
