### ISSUE TITLE
query-fronted: no-store header issue

### ISSUE THREAD

**Issue by shaikatz** [thanos-io/thanos#3742]
**Thanos, Prometheus and Golang version used**: 0.17.1

**What happened**: Having one querier with no available stores (querier is alive but prometheus is down on this cluster), makes our main querier to stop caching requests in the query frontend - since there is a `No store matched for this query` warning.

**What you expected to happen**: Since this is not a real issue as specified in the docs `NOTE: Having warning does not necessary means partial response (e.g no store matched query warning).`
I'm expecting to not pass `no-store` header on such cases, since we got our response.

**How to reproduce it (as minimally and precisely as possible)**: Add an empty querier to your querier that has a frontend in front of him and see how your `cortex_cache_hits` metrics goes flat.

**Comment by kakkoyun** [comment]
Hello @shaikatz, I really didn't understand what is exactly missing here? How does your stack look like? Do you use Querier with store gw/receiver/sidecar? Without any store (something that implements store api) we don't have any data? Do you want to cache empty responses?

cc @yeya24

**Comment by shaikatz** [comment]
Our architecture has one root querier, which is connected to queriers in multiple clusters.
For example we have clusters named: `clusters1, cluster2, cluster3` each of them as the corresponding external labels `cluster="clusterName"`.
Now let's assume cluster3 stores are down.
We sent a simple query, for example: `up{cluster="cluster1"}

The answer from that query will have the `no-store` header even though we got the correct response.

Hope that it makes the issue a bit more clear. 

Let me know if further info or explanation are needed.

**Comment by yeya24** [comment]
@shaikatz Is this case you mentioned valid? Is this reproducible? Ideally, if_ you already set `cluster="cluster1"` in your query, then by external label matching, the querier will only query clusters1 store. So no matter cluster3 is down or not, it doesn't affect the result.

**Comment by shaikatz** [comment]
I'm not sure why, but I cannot reproduce that.
You can close that for now.

**Comment by prmsrswt** [comment]
Thanks for the confirmation @shaikatz, I am closing this for now then.
