### ISSUE TITLE
sidecar: Allow sidecar to have write (no delete) access: Avoid deleting on failed upload.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3744]
Ideally, we don't want to give delete access to sidecar. And we don't need to delete partial uploads anymore as they are handled well on compactor/store gw sides.

Discussion https://cloud-native.slack.com/archives/CL25937SP/p1611572804008400

AC:
 * We can run a sidecar without Deletion Permission.

**Comment by SuperQ** [comment]
Yes, right now we need to give Object Admin level access to the sidecar, rather than just Create and Read.

**Comment by mayankshah1607** [comment]
Hi @bwplotka 
I'd love to take up this issue and make my first contribution here!

**Comment by mayankshah1607** [comment]
Just a very quick question - how many times should the upload be retried, and for how long?

**Comment by mayankshah1607** [comment]
I have opened a PR - https://github.com/thanos-io/thanos/pull/3756*
Not sure if this would be the right approach, would love to have some feedback :)

**Comment by bwplotka** [comment]
Looks like somehow we have two PRs for the same thing (: Which should we review? Sorry for the lag in reviewing.

Let's maybe first have PR that removes deleting (only for sidecar), that would be the first step, However, both PRs @Biswajitghosh98 and @mayankshah1607 are about retries which are quite controversial.

Sorry, I put retries in the title - I rather meant delete the deletion action for the sidecar and the sidecar will retry automatically on crash. Let's start there.

Improving retries is not as easy as we think, created separate issue for this: https://github.com/thanos-io/thanos/issues/3907
