### ISSUE TITLE
Thanos Store Gateway in one region not able to read from the bucket in another region

### ISSUE THREAD

**Issue by sathyendrasaran** [thanos-io/thanos#3746]
I have multicluster(eks) prometheus setup
prom1 -- us-east-1 -- s3 bucket (us-east-1)
prom2 -- eu-west-1 -- s3 bucket (eu-west-1 )
prom3 -- us-west-2 -- s3 bucket (us-west-2 )

---

I have a single Thanos setup in us-west-2 region(eks)
store gateway 1 -- us-east-1 bucket
store gateway 2 -- eu-west-1 bucket
store gateway 3 -- us-west-2 bucket

store gateway 3 works fine since it get data from same region bucket
store gateway 1 & 2 fails with access denied error
each store gateway  has s3 buckets properly configured with corresponding s3 region endpoints

----

The same thanos setup when installed in us-east-1 region(eks)
store gateway 1 works fine since it get data from same region bucket
store gateway 2 & 3 fails with access denied error

---

I am looking for a setup with single thanos in single region with 3 store gateway pulling data from 3 s3 buckets in different regions

```
level=info ts=2021-01-26T03:04:26.848019748Z caller=grpc.go:153 service=gRPC/server component=store msg="internal server is shutdown gracefully" err="bucket store initial sync: sync block: incomplete view: 84 errors: meta.json file exists: 01EWNQFC7DATSW1YPEZ2E7S2G2/meta.json: stat s3 object: Access Denied.; meta.json file exists: 01EWNYB3K69A62GG7WPQ960PFQ/meta.json: stat s3 object: Access Denied.; meta.json file exists: 01EWNGKN38KW339WHEHS9ZJW59/meta.json: stat s3 object: Access Denied.; meta.json file exists: 01EWRGQTKD8WYSZ5NH9VQRS0X8/meta.json: stat s3 object: Access Denied.; meta.json file exists: 01EWNGKN0FZ9Y5GG24254ZRH5K/meta.json: stat s3 object: Access Denied.; meta.json file exists: 01EWPST0KMGYP6SSWW96MWGDEN/meta.json: stat s3 object: Access Denied.; meta.json file exists: 01EWPST0FHDKK3C0MBA3B9DEV4/meta.json: stat s3 object: Access Denied.; 
```

**Comment by kakkoyun** [comment]
@sathyendrasaran  It looks like you are having authorization issues with your object store bucket. Could you please make sure you have the correct access permissions?
