### ISSUE TITLE
Remove Outdated examples Thanos/Helm

### ISSUE THREAD

**Issue by Thilaknath** [thanos-io/thanos#3751]
### Is your proposal related to a problem?

The examples under this repository for Thanos/Helm are outdated by a year and significant changes have been made to the Kube-Prometheus helm charts. It would be helpful for the community to have the latest example in order to have Thanos sidecar configured with kube-Prometheus chart supported by the Prometheus community 

Provide examples in this [section](https://github.com/thanos-io/thanos/tree/master/tutorials) and update Thanos documentation [here](https://thanos.io/v0.13/thanos/quick-tutorial.md/) 

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by Thilaknath** [comment]
@daixiang0 @BradErz  Can you help point me to the configuration of a Thanos sidecar?

**Comment by bwplotka** [comment]
Here is the project that might help you (:

 https://github.com/thanos-io/kube-thanos (check YAML manifests)

**Comment by bwplotka** [comment]
In a separate track, we are looking into a way of ensuring generated helm chart: https://github.com/thanos-io/thanos/issues/1820 🤗

**Comment by bwplotka** [comment]
Oh actually let's keep this issue so we remove outdated charts to avoid confusion!
