### ISSUE TITLE
sidecar: Overlap spotted by uploader while there shouldn't be 

### ISSUE THREAD

**Issue by mveroone** [thanos-io/thanos#3753]
**Thanos, Prometheus and Golang version used**:
 * Thanos 0.17.2 (using bitnami helm chart v3.5.0)
 * prometheus : 2.20.0
 * Sidecar :
```
thanos, version 0.17.2 (branch: HEAD, revision: 37e6ef61566c7c70793ba6d128f00c4c66cb2402)
  build user:       root@92283ccb0bc0
  build date:       20201208-10:00:57
  go version:       go1.15
  platform:         linux/amd64

```

**Object Storage Provider**:
Google Cloud Storage

**What happened**:
My bucket holds data until January 20th, 3PM CET
I'm trying to upload a single (compacted) block to it, that hold data from January 27th 1am to 7am : (meta.json)
```
{
	"ulid": "01EX1H4MB45AR5EBPNXPFCMSDG",
	"minTime": 1611705600000,
	"maxTime": 1611727200000,
	"stats": {
		"numSamples": 261304399,
		"numSeries": 96427,
		"numChunks": 2166227
	},
	"compaction": {
		"level": 2,
		"sources": [
			"01EX0WH4Y933NEAFJXD3D503XP",
			"01EX13CW65TA9M26FYYNBSAR6A",
			"01EX1A8KE4T1HRRZPHKKYC6R2K"
		],
		"parents": [
			{
				"ulid": "01EX0WH4Y933NEAFJXD3D503XP",
				"minTime": 1611705600000,
				"maxTime": 1611712800000
			},
			{
				"ulid": "01EX13CW65TA9M26FYYNBSAR6A",
				"minTime": 1611712800000,
				"maxTime": 1611720000000
			},
			{
				"ulid": "01EX1A8KE4T1HRRZPHKKYC6R2K",
				"minTime": 1611720000000,
				"maxTime": 1611727200000
			}
		]
	},
	"version": 1
}
```

And sidecar says there is an overlap which seems wrong ? 

**What you expected to happen**:
Upload of compacted blocks with no real overlap successful.

**How to reproduce it (as minimally and precisely as possible)**:
1. Have a thanos with raw and compacted blocks stopping at a certain date.
2. Upload a compacted prometheus block of a later date by configuring sidecar over another data directory where you've copied a single block.

**Full logs to relevant components**:
Here is the log from the sidecar, fromatted for better readabilit. As you cans ee, it says there's an overlap, but according to the block's metadata, there isn't ?

<details>Logs
<p>

```
01EX1H4MB45AR5EBPNXPFCMSDG is blocked; overlap spotted:
[mint: 1606521600000, maxt: 1607493600000, range: 270h0m0s, blocks: 3]:
    <ulid: 01EV6Q4HG3AQBRDRGWKMQZ9YBG, mint: 1606521600000, maxt: 1607493600000, range: 270h0m0s>,
    <ulid: 01EV6M4SWGVD1H5VVAA4V6KYEG, mint: 1606521600000, maxt: 1607493600000, range: 270h0m0s>,
    <ulid: 01EV6RR4VF47K9HMHAP70E5JJE, mint: 1606521600000, maxt: 1607493600000, range: 270h0m0s>
[mint: 1608660000000, maxt: 1608854400000, range: 54h0m0s, blocks: 2]:
    <ulid: 01EV6PMVZQSZS39E4JS04PA2Z2, mint: 1608660000000, maxt: 1608854400000, range: 54h0m0s>,
    <ulid: 01ETBXEBW1K46YBAQ1ZC35B1ZM, mint: 1608660000000, maxt: 1608854400000, range: 54h0m0s>
[mint: 1610323200000, maxt: 1610496000000, range: 48h0m0s, blocks: 2]:
    <ulid: 01EVWWYFDZ5E612X0G55JB3WXP, mint: 1610323200000, maxt: 1610496000000, range: 48h0m0s>,
    <ulid: 01EVWWRSG05RHQMRH9KETH5NYQ, mint: 1610323200000, maxt: 1610496000000, range: 48h0m0s>
[mint: 1610668800000, maxt: 1610841600000, range: 48h0m0s, blocks: 2]:
    <ulid: 01EW76CC06WYB693PGQ33NQ1PJ, mint: 1610668800000, maxt: 1610841600000, range: 48h0m0s>,
    <ulid: 01EW76JAGY62K6Q27ATS0PDNG2, mint: 1610668800000, maxt: 1610841600000, range: 48h0m0s>
[mint: 1606327200000, maxt: 1606521600000, range: 54h0m0s, blocks: 2]:
    <ulid: 01EV6PCWN7H8F2339GDKYRT0D3, mint: 1606327200000, maxt: 1606521600000, range: 54h0m0s>,
    <ulid: 01ER6CR8XY6QEZ5ZMG4G0ZQ656, mint: 1606327200000, maxt: 1606521600000, range: 54h0m0s>
[mint: 1607688000000, maxt: 1608660000000, range: 270h0m0s, blocks: 3]:
    <ulid: 01EV6NGPYFJWSCP014N4ZMZ06A, mint: 1607688000000, maxt: 1608660000000, range: 270h0m0s>,
    <ulid: 01EV6R4WAPFQS64FXZ0VAC7NWJ, mint: 1607688000000, maxt: 1608660000000, range: 270h0m0s>,
    <ulid: 01EV6RNRN15203F8544ZDH3XRP, mint: 1607688000000, maxt: 1608660000000, range: 270h0m0s>
[mint: 1609632000000, maxt: 1609826400000, range: 54h0m0s, blocks: 4]:
    <ulid: 01EVQRBFRQ1PSGZAPTKH7ANEAJ, mint: 1608854400000, maxt: 1609977600000, range: 312h0m0s>,
    <ulid: 01EVEES95PVSRZBNNNPEYFHVKX, mint: 1608854400000, maxt: 1609977600000, range: 312h0m0s>,
    <ulid: 01EVQRE19RV6TK7G87R6X3GPMR, mint: 1608854400000, maxt: 1609977600000, range: 312h0m0s>,
    <ulid: 01EWGA8VDVFMRGHEA8R618YSAJ, mint: 1609632000000, maxt: 1609826400000, range: 54h0m0s>
[mint: 1609977600000, maxt: 1610150400000, range: 48h0m0s, blocks: 2]:
    <ulid: 01EVJKD4G44YVK8VDXCJ03GP6T, mint: 1609977600000, maxt: 1610150400000, range: 48h0m0s>,
    <ulid: 01EVJK9657B4TV2HH9TN4T543D, mint: 1609977600000, maxt: 1610150400000, range: 48h0m0s>
[mint: 1610150400000, maxt: 1610323200000, range: 48h0m0s, blocks: 2]:
    <ulid: 01EVQR7PN32B40XZ89D20TKF19, mint: 1610150400000, maxt: 1610323200000, range: 48h0m0s>,
    <ulid: 01EVQR2MPVN99QFQTG9S11SXTT, mint: 1610150400000, maxt: 1610323200000, range: 48h0m0s>
[mint: 1610496000000, maxt: 1610668800000, range: 48h0m0s, blocks: 2]:
    <ulid: 01EW21J4JY1TDEAB6JW16DF1BS, mint: 1610496000000, maxt: 1610668800000, range: 48h0m0s>,
    <ulid: 01EW21Q993RDJ60PNPSDSFJMN5, mint: 1610496000000, maxt: 1610668800000, range: 48h0m0s>
[mint: 1610841600000, maxt: 1611014400000, range: 48h0m0s, blocks: 2]:
    <ulid: 01EWCBCVZD4GBWND60HMRVD7FB, mint: 1610841600000, maxt: 1611014400000, range: 48h0m0s>,
    <ulid: 01EWCB5WAFXKYNQZG4N4KFQGPK, mint: 1610841600000, maxt: 1611014400000, range: 48h0m0s>
[mint: 1607493600000, maxt: 1607688000000, range: 54h0m0s, blocks: 2]:
    <ulid: 01ES952XK6HJ6EERWDK5B1ZP2N, mint: 1607493600000, maxt: 1607688000000, range: 54h0m0s>,
    <ulid: 01EV6PWEQRCNW0PP5PXX555KZD, mint: 1607493600000, maxt: 1607688000000, range: 54h0m0s>
```
</p>
</details>

**Anything else we need to know**:

I had previously run the sidecar without uploading compacted block which meant my thanos bucket had a "hole". I've deleted all these uncompacted blocks and their metadata in case overlap meant there were existing blocks older than the one being uploaded, but that didn't help.

I've tried removing even more blocks from the GCS bucket but without success.

**Comment by mveroone** [comment]
I'm wondering whether I could try to upload blocks directly by copying the files from prometheus to GCS.
Will try that monday.

**Comment by bwplotka** [comment]
I see a problem.

You need to ensure `meta.json` exists with Thanos metadata section (e.g with external label sets). Otherwise you can just copy yes. The problem you might be seeing is that you push blocks from different Prometheus-es but Thanos has no idea which block is from what Prometheus without putting external labels into meta.json. `Sidecar` does this automatically on upload. Any manual copy will literally miss this phase and result with overlaps for everything. You query can be super funky as well if your metrics in each of block will have exactly same labels from two different Proms. That' why external labels are essential. You can manually edit meta.json and add this section, but ideally you use sidecar to upload all of it.
Have you checked `upload-compacted` flag of sidecar?

Hope that helps 🤗

**Comment by bwplotka** [comment]
I think there might be a need for simple upload utility on Thanos tooling to do this. WDYT?

**Comment by mveroone** [comment]
In theory, the upload-compacted flag seems sufficient in my opinion, but
the overlap error message is hard to understand, and the side-car does not
move past the blocking block.

I still don't understand what's wrong in my situation.

Now sure, a more precise tooling to be able to list, and select for
uploading each block could be nice. Or more simply a flag `--upload-since`
followed by a timestamp(us) argument maybe.

**Comment by mveroone** [comment]
I'm trying to perform the manual upload today.
I had to disable the compactor to avoid the aborted partial deletion mechanism.
Then I'll try to move the metas in the debug folder and append the thanos metadata inside.

Let me know if you have any idea about why the sidecar is reporting overlapping though. thanks.

**Comment by mveroone** [comment]
It was painful (I had to build thanos metadata manually) but it worked !!
![image](https://user-images.githubusercontent.com/44051537/106585690-e1c80e80-6547-11eb-9e71-db013d803954.png)
Now because of compaction i still have holes in the dataset but much smaller, so it'll have to do.

I'll leave it up to you to decide whether the initial bug needs digging, let me know how I can assist on that.
And if I were to emit a suggestion, it'd be to have the sidecar skip blocks that fail because of overlap and move on to the next ones to avoid a soft-lock of the uploader process.

**Comment by kakkoyun** [comment]
Happy that everything works now @mveroone. If you prefer you can create an issue regarding your suggestions on the sidecar.
Closing this one for now.
