### ISSUE TITLE
Binaries for Thanos 0.18.0

### ISSUE THREAD

**Issue by joancafom** [thanos-io/thanos#3757]
Hi,

I have noticed that [the latest tagged release](https://github.com/thanos-io/thanos/releases/tag/v0.18.0) for Thanos (0.18.0) does only include the source code. Usually, previous versions did include the binaries for different platforms and a set of _Release Notes_ (see [0.17.0](https://github.com/thanos-io/thanos/releases/tag/v0.17.0) and [0.17.0-rc.0](https://github.com/thanos-io/thanos/releases/tag/v0.17.0-rc.0)).

The [release candidate 0.18.0-rc.0](https://github.com/thanos-io/thanos/releases/tag/v0.18.0-rc.0) does include them, will you be updating tagged version 0.18.0 with them too?

**Comment by bwplotka** [comment]
Yes it looks like the release is somehow in.. progress? 🤔 cc @squat 

Thanks for pointing!

**Comment by squat** [comment]
Thanks for bringing this up.  I think the release job in circle CI failed and had to be retried! It's released now :))))

**Comment by bwplotka** [comment]
<3
