### ISSUE TITLE
query: Do not fail SRV lookup if one A record is non existing

### ISSUE THREAD

**Issue by AndrewNiven1** [thanos-io/thanos#3766]
**Thanos, Prometheus and Golang version used**: v0.17.1

**Object Storage Provider**: ABS

**What happened**: We are using a Thanos Query to monitor other Thanos Queries in our deployment. The top level Query points at a DNS SRV record set, which points at DNS A records containing the URLs of lower level Thanos Queries. This works well when the SRV record set only points to A records that exist, but if the SRV record set points to at least 1 A record that does not exist, it discovers none of the records at all (i.e. it gets stuck failing to find the non-existent A record and does not move on to the existing ones).

**What you expected to happen**: We expected Thanos Query to ignore non-existent DNS A records and carry on to resolve existing A records.

**How to reproduce it (as minimally and precisely as possible)**:
- Spin up three Thanos Queries - one will be designated high level (HL), and two will be designated low level (LL)
- Create a DNS A record pointing at the loadbalancer service IP address of one of the Queries (LL1). Do not do the same for LL2.
- Create a DNS SRV record set pointing at port 10901 of the A record used for LL1, and the A record you would have used for LL2 if you had made it.
- Point the HL Query at the DNS SRV record set you have made. Look at its logs. You should see that, as the LL2 does not exist, LL1 will not be found - it gets stuck failing to find LL2.
- Now make a DNS A record for LL2. Go back to your HL Query. After it has refreshed (which may require deleting the pod and restarting it) it should now successfully discover both LL2 and LL1.

**Full logs to relevant components**:

Real DNS address replaced with <QUERY_A_RECORD_1>. Expected behaviour in the below log would be for it to also attempt to discover other A records, not just to fail to contact QUERY_A_RECORD_1 repeatedly.

```
level=info ts=2021-02-03T07:49:47.53214303Z caller=main.go:98 msg="Tracing will be disabled"
level=info ts=2021-02-03T07:49:47.534145678Z caller=options.go:23 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2021-02-03T07:49:47.534414798Z caller=query.go:506 msg="starting query node"
level=info ts=2021-02-03T07:49:47.535481977Z caller=intrumentation.go:60 msg="changing probe status" status=healthy
level=info ts=2021-02-03T07:49:47.53551168Z caller=http.go:58 service=http/server component=query msg="listening for requests and metrics" address=0.0.0.0:10902
level=info ts=2021-02-03T07:49:47.535731096Z caller=intrumentation.go:48 msg="changing probe status" status=ready
level=info ts=2021-02-03T07:49:47.535884107Z caller=grpc.go:116 service=gRPC/server component=query msg="listening for serving gRPC" address=0.0.0.0:10901
level=error ts=2021-02-03T07:49:47.56779347Z caller=query.go:395 msg="failed to resolve addresses for storeAPIs" err="look IP addresses \"<QUERY_A_RECORD_1>.\": lookup <QUERY_A_RECORD_1>. on 10.0.0.10:53: no such host"
level=info ts=2021-02-03T07:49:52.53724839Z caller=storeset.go:387 component=storeset msg="adding new storeAPI to query storeset" address=10.0.193.115:10901 extLset="{replica=\"simon-thanos-global-ruler-0\", ruler_cluster=\"\"}"
level=error ts=2021-02-03T07:50:17.542800408Z caller=query.go:395 msg="failed to resolve addresses for storeAPIs" err="look IP addresses \"<QUERY_A_RECORD_1>.\": lookup <QUERY_A_RECORD_1>. on 10.0.0.10:53: no such host"
level=error ts=2021-02-03T07:50:47.57059395Z caller=query.go:395 msg="failed to resolve addresses for storeAPIs" err="look IP addresses \"<QUERY_A_RECORD_1>.\": lookup <QUERY_A_RECORD_1>. on 10.0.0.10:53: no such host"
level=error ts=2021-02-03T07:51:17.584973393Z caller=query.go:395 msg="failed to resolve addresses for storeAPIs" err="look IP addresses \"<QUERY_A_RECORD_1>.\": lookup <QUERY_A_RECORD_1>. on 10.0.0.10:53: no such host"
level=error ts=2021-02-03T07:51:47.57140777Z caller=query.go:395 msg="failed to resolve addresses for storeAPIs" err="look IP addresses \"<QUERY_A_RECORD_1>.\": lookup <QUERY_A_RECORD_1>. on 10.0.0.10:53: no such host"
```

**Anything else we need to know**:

**Comment by bwplotka** [comment]
> Object Storage Provider: ABS

What's ABS? (: 

I think it makes sense, I like this idea. Help wanted!  

I personally like to fail fast. Missing A record means something is not well configured, so you might be having a partial response on the query side. I think with some flag we are happy to have this logic you proposed enabled. I wonder if some `--non-strict-mode` flag global to .. Thanos 🤔 

To me something this case sounds like unhealthy DNS server, no?

Open question: What if all A records are nonexisting?

**Comment by AndrewNiven1** [comment]
Hi Bartlomiej, thanks for your response. ABS is Azure Blob Storage. 

In our proposed architecture, missing A records are expected behaviour. We want to define a list of possible service instance names in our SRV record set: at any given moment some of these service instances will be up, and some will not be. If the DNS A record does not exist, it is because the service instance associated with it is not spun up, and vice versa. We would like Thanos Query to look through the SRV record set, resolve A records if they exist (thus finding existing service instances) and skip A records if they do not exist (thus skipping non-existing service instances). 

If all A records are non-existing, we see the same problem - Thanos will try to find one of the A records, fail, and get stuck on it, never attempting to discover any of the others.

Please let me know if you have any other questions!

Thanks,

Andrew

**Comment by bwplotka** [comment]
Nice, In wonder if @idoqo might want to try to help here, it might be easy, but might require a flag, let's see 🤗

**Comment by bwplotka** [comment]
Talked on 1:1 offline: Even if we cannot reproduce this anymore, let's put a unit test for it, so we can ensure there is no regression in future (: WDYT? @idoqo

**Comment by bwplotka** [comment]
Place where we might adjust the code: https://github.com/thanos-io/thanos/blob/main/pkg/discovery/dns/resolver.go#L117
You can adjust test like this: https://github.com/thanos-io/thanos/blob/5aa5e415de405949d56e96d99ac7afc73987a763/pkg/discovery/dns/resolver_test.go#L140

**Comment by idoqo** [comment]
So I created a unit test scenario to reproduce this (in the draft PR) and it currently passes without any change to the code. @AndrewNiven1 can you help take a look? Maybe we could figure how to better replicate this use case in the test.

**Comment by AndrewNiven** [comment]
Hi idoqo, thanks for this. I've just bumped our version of Thanos, from v0.17.1 to 0.19.0, and I'm now no longer seeing the problem. It's been intermittent in the past, so I'll let you know if it comes back and we can have a look at replicating it more reliably.

**Comment by bwplotka** [comment]
Cool, thanks both @idoqo and @AndrewNiven
