### ISSUE TITLE
e2e  TestReceive/replication_with_outage is flaky

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3774]
See: https://github.com/thanos-io/thanos/pull/3773/checks?check_run_id=1838083024#step:5:2345

**Comment by Abhishek357** [comment]
> See: https://github.com/thanos-io/thanos/pull/3773/checks?check_run_id=1838083024#step:5:2345

No check run found with ID 1838083024 for this pull request. :thinking:
