### ISSUE TITLE
Documentation for running and understanding tests.

### ISSUE THREAD

**Issue by Chans321** [thanos-io/thanos#3776]
Docs on thanos architecture are really great and help beginners to understand various components of thanos really well! As a new contributor, I found it a little difficult to run and understand the tests on my own. It would be great if there are some reference docs on the unit and e2e tests as well!

**Comment by kakkoyun** [comment]
@Chans321 Thanks for reporting. 
Could be handled as part of https://github.com/thanos-io/thanos/issues/3250

Help wanted 🤗

**Comment by yashrsharma44** [comment]
Hi @Chans321 , thank you for posting this issue, I have had the same experience of being a newbie contributor at start, so can totally relate to the issues :)

Would be really awesome if you could pinpoint some details about what would you want in the developer docs as such, we will make sure that those points are covered and not missed.

**Comment by yashrsharma44** [comment]
I have [added](https://github.com/thanos-io/thanos/pull/3817/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R216) some documentation for running tests, let me know if you need anything more on the docs - @Chans321
