### ISSUE TITLE
repair: Add unit tests for repair procedure

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#378]

**Comment by bwplotka** [comment]
I think I am fine with this being closed... No priority, no interest (:

**Comment by yashrsharma44** [comment]
Hey @bwplotka! I was looking to solve this issue, can you provide some details about the problem and any approach to solve this? As it would be my first stab to send in a PR, any suggestions would be good!

**Comment by bwplotka** [comment]
Hm, I think TBH our repair is really quite old, and there was no recent issue that was added so this is no priority anymore. I will close this for now. 

 Definitely there are more more important issues to solve. I will go through our issues and mark some of them as `good first issue` ok @yashrsharma44 ? (: 

Thanks! :hugs:

**Comment by yashrsharma44** [comment]
Sure @bwplotka!
