### ISSUE TITLE
[Store] - Thanos Store taking too long to be ready

### ISSUE THREAD

**Issue by ncastrocosta** [thanos-io/thanos#3785]
Thanos: 0.14

**Object Storage Provider**: S3

**What happened**:

I have Thanos deployed in two EKS clusters, each in a region (us-east-1 and us-west-2). And by chance I have noticed the Thanos Store pods are taking more time to be ready in us-west-2 region than in us-east-1. For both clusters, the memory/cpu allocated are the same, as well as the working machines types.

So, for example, in us-west-2, I see log messages with the elapsed time to load a new block around 20s. At the same time, in us-east-1, it takes only 3s.

**What you expected to happen**:

Given that the only difference between the clusters is the region and that it should be not enough reason for this elapsed time difference, **what could I investigate?**

**How to reproduce it (as minimally and precisely as possible)**:

Deploying the Thanos Store pod and checking the logs.

**Anything else we need to know**:

I have AWS Memcached enabled, for each region,  for the index and for the bucket. Machine type "cache.m6g.large".

Many thanks!

**Comment by bwplotka** [comment]
Hi! This depends on data size indeed. More blocks, means more `index-header` (on-disk cache) to be created on start. This should actually be visible for only first startup as long as you have a PVC for such pod. 🤗 

Some mitigations are possible e.g Thanos store [sharding](https://thanos.io/tip/thanos/sharding.md/)

Some related issues: https://github.com/thanos-io/thanos/issues/3150
