### ISSUE TITLE
sidecar: Timeout on high latency links

### ISSUE THREAD

**Issue by evoicefire** [thanos-io/thanos#3787]
**Thanos, Prometheus and Golang version used**:

Version: v0.15.0

**Object Storage Provider**: GCS

**What happened**: On some queries the sidecar closes connections (nginx 499 errors and envoy_proxy http2_client reset errors). This only seems to happen to storegateways that are connected over high latency links (1000ms+) the configuration is identical otherwise. 

The sidecar storageapi/object storage upload also times out.

**What you expected to happen**: I expect the query to succeed albeit somewhat slowly.

**How to reproduce it (as minimally and precisely as possible)**: In my scenario I is this particular query that is causing trouble:

            sum(
            avg_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate[24h])
            * on(namespace,pod, environment,location,name)
              group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel
            * on (namespace, pod, environment,location,name) group_left(label_slack_contact) kube_pod_labels
            ) by (namespace, workload, workload_type, label_slack_contact, environment,location,name) / sum(
              avg_over_time(kube_pod_container_resource_requests_cpu_cores[24h])
            * on(namespace,pod, environment,location,name)
              group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel
            * on (namespace, pod, environment,location,name) group_left(label_slack_contact) kube_pod_labels
            ) by (namespace, workload, workload_type, label_slack_contact, environment,location,name) < 0.5

**Full logs to relevant components**:

<details>Nginx
<p>

```
{ "msec": "1613098229.442", "connection": "16756763", "connection_requests": "22", "pid": "1130", "request_id": "afbccc29b952272eacc07dc6cd69a285", "request_length": "66", "remote_addr": "10.213.10.47", "remote_user": "", "remote_port": "32577", "time_local": "12/Feb/2021:02:50:29 +0000", "time_iso8601": "2021-02-12T02:50:29+00:00", "request": "POST /thanos.Store/Info HTTP/2.0", "request_uri": "/thanos.Store/Info", "args": "", "status": "499", "body_bytes_sent": "0", "bytes_sent": "93", "http_referer": "", "http_user_agent": "grpc-go/1.29.1", "http_x_forwarded_for": "", "http_host": "thanos.toda.company.net", "server_name": "thanos.toda.company.net", "request_time": "5.116", "upstream": "10.42.0.13:10901", "upstream_connect_time": "0.000", "upstream_header_time": "0.004", "upstream_response_time": "5.116", "upstream_response_length": "555", "upstream_cache_status": "", "ssl_protocol": "TLSv1.2", "ssl_cipher": "ECDHE-RSA-AES128-GCM-SHA256", "scheme": "https", "request_method": "POST", "server_protocol": "HTTP/2.0", "pipe": ".", "gzip_ratio": "", "http_cf_ray": "", "geoip_country_code": "" }


```

</p>
</details>

<details>Envoy
<p>

```
[2021-02-12T02:53:13.885Z] "POST /thanos.Store/Info HTTP/2" 0 - 5 0 5000 - "-" "grpc-go/1.29.1" "b06b2506-208b-4a7c-b48c-20cbdff528b3" "thanos.toda.company.net" "192.168.213.60:443"
[2021-02-12T02:53:10.212Z] "POST /thanos.Store/Series HTTP/2"
200 DC downstream_remote_disconnect 83 11493 8673
7440 "-" "grpc-go/1.29.1"

```

</p>
</details>

**Anything else we need to know**: Not that I can think of

**Comment by kakkoyun** [comment]
Hey @evoicefire, Thanks for reporting. Could you share your querier configuration? And have you tried to adjust the timeout values for querier?

**Comment by evoicefire** [comment]
Hi @kakkoyun 
Sure it is below. I have tried setting the timeout values to no effect (it seems the client is terminating the connections ie. sidecar ).

`query --log.level=info --grpc-address=0.0.0.0:10901 --http-address=0.0.0.0:10902 --query.replica-label=replica --query.timeout=5m --store.response-timeout=5m`

I've excluded the store definitions for the querier as there are many of them.

**Comment by gmintoco** [comment]
Still an issue at the moment

**Comment by evoicefire** [comment]
Still an issue

**Comment by gerases** [comment]
I seem to be seeing the same problem -- HTTP2 stream resets over high latency links. This can probably be simulated by using `tc`: https://www.pico.net/kb/how-can-i-simulate-delayed-and-dropped-packets-in-linux/
