### ISSUE TITLE
Receiver: non strict replication mode

### ISSUE THREAD

**Issue by squat** [thanos-io/thanos#3791]
Implement a non-strict replication mode where only one replica in the hashring is required to ack a request before returning a 200 to the client, no matter the replication factor. This allows for optimistic replication, which decreases the durability guarantee in cases of catastrophic loss of a replicaw's disk, while offering the trade-off of speeding up requests for clients.

WDYT @thanos-io/thanos-maintainers

**Comment by bwplotka** [comment]
I like it, but I think we can already to this with the quorumWrite=1 option (or something like this? 🙈 )

**Comment by squat** [comment]
We don't have a something like a `quorum` setting yet, and this is not quite the same thing as setting replication-factor=1, which means that the time series only ever gets sent to one replica and that's it. Using non-strict mode would mean that only one replica needs to ACK the write before we send a 200 to the client, but the time series would still get sent to all of the replicas dictated by the replication factor.

**Comment by julienlau** [comment]
I think it was implemented in https://github.com/thanos-io/thanos/pull/7669
