### ISSUE TITLE
query-frontend: Instant queries with large time range are not splitted.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3797]
This cause some latency differences between:

1. query instant: `avg_over_time(count(group(subscription_labels{ebs_account='6356154'}) by (_id,ebs_account)) by(ebs_account)[6d:300s])` for huge cardinality query takes 95s

![image](https://user-images.githubusercontent.com/6950331/107822778-90edbc80-6d76-11eb-8cde-4d45f1c511e6.png)

2. Query range for 6d 300s step (so some query kind of, just without average) `count(group(subscription_labels{ebs_account='6356154'}) by (_id,ebs_account)) by(ebs_account)` takes 40s
![image](https://user-images.githubusercontent.com/6950331/107822964-dd38fc80-6d76-11eb-9323-9b359086f95c.png)

Investigate.

**Comment by hitanshu-mehta** [comment]
@bwplotka I would like to work on this issue :)
