### ISSUE TITLE
ui: Update dependencies for the React UI

### ISSUE THREAD

**Issue by prmsrswt** [thanos-io/thanos#3811]
The node dependencies are quite out-of-date for the React UI, let's update to the latest version we can without breaking anything.

**Comment by saswatamcode** [comment]
I would love to take this up! This issue would involve upgrading all deps to their latest releases and dealing with any code changes that requires, right?

**Comment by ruddi10** [comment]
@prmsrswt  can I work on it?

**Comment by prmsrswt** [comment]
@saswatamcode yep that's exactly what is needed.

@ruddi10 Let's wait for @saswatamcode first and try to not have duplicated effort.

**Comment by saswatamcode** [comment]
@prmsrswt would love it if you can take a look at this and suggest some changes. I've upgraded the dependencies as much as possible, but some tests fail due to the upgrades and I'm not familiar with the testing architecture of the project yet. Also certain caveats exist due to these changes.

**Comment by prmsrswt** [comment]
Closing as it got fixed in #3813
