### ISSUE TITLE
Experiment with single Append Prometheus method is blocking us or not.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3812]
Ref: https://github.com/prometheus/prometheus/pull/8489#issuecomment-781442995

**Comment by metalmatze** [comment]
Did we already start working on this? Happy to help with it!

**Comment by bwplotka** [comment]
Nope 🤗 
I think essentially we need to upgrade to latest Prometheus and check if we can, with the totally new Appender API!

**Comment by bwplotka** [comment]
> Nope 🤗 

I mean, nope that someone started working on it, feel free to help 🤗
