### ISSUE TITLE
Docs: Update Architecture overview diagram

### ISSUE THREAD

**Issue by hitanshu-mehta** [thanos-io/thanos#3826]
Request to add Query-frontend and Receiver in the [diagram](https://github.com/thanos-io/thanos/blob/master/docs/img/arch.jpg).

**Comment by kakkoyun** [comment]
It'd be really nice to update those diagrams. Help wanted, so go ahead if anyone wants to do that :)

**Comment by algokun** [comment]
Hey, I would like to improve this diagram, can you tell me how to move forward?

**Comment by wiardvanrij** [comment]
Would be nice as first step to have the 'raw' diagram file :D 
/cc @bwplotka

**Comment by hitanshu-mehta** [comment]
Here is the google drawing [file](https://docs.google.com/drawings/d/15aHt9eo2hPps7wFH_cOup14hlBxmOcyEV4_t53W-gYc/edit?ths=true) of the diagram but edit access will be required.

**Comment by GiedriusS** [comment]
Closing because https://github.com/thanos-io/thanos/pull/4039 has been merged. Thanks @hitanshu-mehta for the ping!

**Comment by vanlongme** [comment]
Can you guys give me the raw of those diagram files to make change ?
