### ISSUE TITLE
Hashring Config

### ISSUE THREAD

**Issue by rickdonato** [thanos-io/thanos#3830]
Is there a way to update the hashring via a environment var? From what I can see there is not.

**Comment by bwplotka** [comment]
👋🏽  Thanks for asking!

What do you mean by `update`? Do you specifically mean dynamic change, or just starting up?

If the latter you can update it via file or directly passing multi-line string to flag:

```
--receive.hashrings-file=<path>
                                 Path to file that contains the hashring
                                 configuration. A watcher is initialized to
                                 watch changes and update the hashring
                                 dynamically.
      --receive.hashrings=<content>
                                 Alternative to 'receive.hashrings-file' flag
                                 (lower priority). Content of file that contains
                                 the hashring configuration.
```
If you use Kubernetes you can use `$(VAR)` pattern to fetch something from env var, if not then you might need sidecar e.g

Separate proposal would be to allow our `pathorcontent` flag to also substitute envvars, but sounds scope creep (:

**Comment by rickdonato** [comment]
Thanks. To provide more clarity. I'm running Thanos in ECS, which I do not believe supports the $(VAR) pattern.
Therefore at the point I scale I will need to update the task def for the ECS service. Ideally it would be good to provide the config settings for the hashring via an env var.
