### ISSUE TITLE
JSON logger with %v generate bad value

### ISSUE THREAD

**Issue by StephaneBrillant** [thanos-io/thanos#3837]
At 2 places the `%v` macro is used with the logger and is not supported
https://github.com/thanos-io/thanos/blob/46d010638bbd7ef73fb9355a18f398cb3d99a7eb/cmd/thanos/query.go#L559
https://github.com/thanos-io/thanos/blob/46d010638bbd7ef73fb9355a18f398cb3d99a7eb/cmd/thanos/rule.go#L724

**What happened**:
Logs generates result in dynamic key with MISSING value.
ex:
```
{"msg":"Duplicate store address is provided - %v","test":"(MISSING)"}
```

**What you expected to happen**:
Json logging play well with ElasticSearch type mapping. No dynamic key with MISSING value is reported

**Proposed fix**
Replace `%v` by string concatenation
ex: `logger.Log("msg", "Duplicate store address is provided - " + addr)`

**Comment by yeya24** [comment]
Thanks for catching this! Would you like to open a pr to fix it?

We can just change it to `level.Warn(logger).Log("msg", "Duplicate store address is provided", "addr", addr)`.

I am wondering if there is already a static linter for this.
