### ISSUE TITLE
Is Store Support for multiple matching ? label:"component: store" 

### ISSUE THREAD

**Issue by DreamDZhu** [thanos-io/thanos#3838]
selector.relabel-config  set

- action: keep
  regex: T-D3U13CRL04
  source_labels:
   - replica
   - name
 
the effect i want is to keep the extra_label for replica and name for T-D3U13CRL04 ,  but this configuration doesn't work ,What should I do

**Comment by bwplotka** [comment]
I think what you want is not supported, we only use relabelling to define match/selecting capabilities - to configure which store should be responsible for what data. I presume you want to change external labels on the data blocks, thus metrics?
