### ISSUE TITLE
Stop uploading debug meta files to obj store

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#3839]
### Is your proposal related to a problem?

(Write your answer here.)

![Screenshot from 2021-02-25 22-31-03](https://user-images.githubusercontent.com/25150124/109251357-509c2e80-77b9-11eb-95c9-86ce906ff219.png)

As agreed in one previous community meeting, we decided to remove the step of uploading debug meta files because seems it is hardly used.

@thanos-io/thanos-maintainers 

### Describe the solution you'd like

Remove step https://github.com/thanos-io/thanos/blob/12c826a86e0c1de65ea770caf7cecd61acb22f24/pkg/block/block.go#L106-L108 and related tests code.

**Comment by hitanshu-mehta** [comment]
Can i work on this issue?

**Comment by bwplotka** [comment]
Yes please @hitanshu-mehta !

**Comment by GiedriusS** [comment]
Maybe we should also remove whatever already meta files exist in the bucket already? https://github.com/thanos-io/thanos/issues/3397

**Comment by pstibrany** [comment]
I have found these files useful when tracking down history of some blocks during our data conversion. I would weakly prefer to keep them, as the overhead seems tiny.

**Comment by kakkoyun** [comment]
Still valid.

**Comment by pstibrany** [comment]
I think I was the only one for keeping the debug meta files. As I haven't had any use for them in last ~1year and instead suffered from trying to delete lots of them from object store, I am fine with getting rid of them.

(I hope my previous weak preference to keep them isn't what stalled the work here.)

**Comment by yeya24** [comment]
Still valid

**Comment by r0mdau** [comment]
I tried something, kudos to your work @hitanshu-mehta . I was trying to build thanos using this issue as example. I thought maybe it can helps.
