### ISSUE TITLE
[Question] - Thanos Query FrontEnd With Cached in AWS ElastiCache (Memcached)

### ISSUE THREAD

**Issue by DenysLP** [thanos-io/thanos#3844]
Hello guys,

I have a performance problem when I enable AWS ElastiCache (Memcached) for the Query FrontEnd component.

When I use the memory cache I can have a better performance, however, in AWS ElastiCache (Memcached) the result is not so satisfactory.

Has anyone been through this?

Every help is welcome.

Grateful,
Denys Ladislau

**Comment by wiardvanrij** [comment]
Hi, could you provide more information regarding which performance and perhaps a benchmark between the two setups? 
Also please share more details about your configuration/setup
