### ISSUE TITLE
thank you for this project!

### ISSUE THREAD

**Issue by deepthawtz** [thanos-io/thanos#385]
I'm really glad for this project, sorry to spam issues I just wanted to buy you guys a beer.

@GitCash send 0.008 BCH to @fabxc and @Bplotka

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/124/image.png)](https://gitcash.io/)
@fabxc,@Bplotka

**Comment by GitCash** [comment]
[![GitCash Tip Response](https://gitcash.io/tip/pic/125/image.png)](https://gitcash.io/)
@fabxc,@Bplotka

**Comment by Bplotka** [comment]
This is so awesome to hear! (: Thanks!

**Comment by fabxc** [comment]
Thanks :) Much appreciated.
