### ISSUE TITLE
Discrepancy between queries executed in thanos-query UI vs grafana

### ISSUE THREAD

**Issue by lcoelho88** [thanos-io/thanos#3859]
**Thanos, Prometheus and Golang version used**:

Thanos image: thanosio/thanos:v0.18.0
Prometheus image: quay.io/prometheus/prometheus:v2.25.0
Grafana image: grafana/grafana:7.3.2

**Object Storage Provider**:
- S3

**What happened**:

We are experiencing a big discrepancy between a query executed directly in thanos-query UI and in a dashboard in grafana. Namely, a query executed in thanos-query UI takes around 1 second to complete and, the very same query, is 5/6 times slower in grafana.

Below, it is possible to see a screenshot from thanos-query UI where the query took 1049ms and a screenshot from grafana, with the same query, that took around 5 times more to complete and present results in grafana ui. 

![Screenshot 2021-02-26 at 16 23 57](https://user-images.githubusercontent.com/36235033/109537184-86416000-7ab6-11eb-9fb5-ac827467552f.png)

![Screenshot 2021-02-26 at 16 22 48](https://user-images.githubusercontent.com/36235033/109537191-893c5080-7ab6-11eb-8016-68e94f89a6d1.png)

**What you expected to happen**:
The queries should take the same time to be executed both on thanos-query UI and grafana.

**How to reproduce it (as minimally and precisely as possible)**:

Thanos-query and thanos-store configs:

**Query:**
     - args:
       - query
       - --grpc-address=0.0.0.0:10901
       - --http-address=0.0.0.0:10902
       - --log.level=debug
       - --log.format=json
       - --query.auto-downsampling
       - --query.replica-label=replica
       - --store=thanos-sidecar.crm.svc.cluster.local:10901
       - --store=thanos-sidecar.observability.svc.cluster.local:10901
       - --store=thanos-store.crm.svc.cluster.local:10901
      
Note that the reason why we have two sidecars in store parameter, is because we have specific metrics stored only on "observability" prometheus and we also need to be able to access that info from thanos-query, on namespace "crm", while it is not shipped to S3.

**Store:**
     - args:
       - store
       - --log.level=debug
       - --log.format=json
       - --objstore.config-file=/config/bucket.yml
       - --grpc-address=0.0.0.0:10901
       - --http-address=0.0.0.0:10902
       - --data-dir=/var/thanos/store
       - |-
         --selector.relabel-config=
           - action: keep
             regex: "(crm|observability)"
             source_labels:
             - prometheus

Finally, below there is a print screen from grafana datasource:

![Screenshot 2021-03-01 at 17 47 21](https://user-images.githubusercontent.com/36235033/109537360-b12bb400-7ab6-11eb-96dc-d1e1fe13f7ce.png)
           
**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by GiedriusS** [comment]
What is the `step` that you see on the requests when you do them via Grafana vs. Thanos Query UI?

**Comment by lcoelho88** [comment]
Hi @GiedriusS,

In grafana the step is 120, as can be seen in the GET request below:

> https://metrics.observability._"mycompanydomain"_/api/datasources/proxy/57/api/v1/query_range?query=sum%20(container_memory_working_set_bytes%7Bcontainer!%3D%22POD%22%2Ccontainer!%3D%20%22%22%2Cpod%3D~%22.*%22%2Cnamespace%3D~%22crm%22%7D%20%2F%201024%20%2F%201024)%20by%20(pod)&start=1614510720&end=1614683520&**step=120**

In thanos-query UI it is 691:

>https://thanos.crm._"mycompanydomain"_/api/v1/query_range?query=sum (container_memory_working_set_bytes{container!="POD",container!= "",pod=~".*",namespace=~"crm"} / 1024 / 1024) by (pod)&dedup=true&partial_response=true&start=1614510937.114&end=1614683737.114&**step=691**&max_source_resolution=auto&_=1614682888059

With this information it is easy to understand the reason for the execution time discrepancy.

However, some notes regarding grafana integration with thanos:

- The step in grafana is automatically calculated and the 120 value is because we are using resolution 1/1 in grafana. If we change resolution, we can have performance improvements but we also lose data accuracy.

- Testing the same scenario, without thanos, pointing directly to a prometheus datasource that have same data as thanos (we have both scenarios running in our testing environment for comparison), even with step set as 120 (and resolution 1/1) on grafana, it is very quick to render data with no need to change resolution. Obviously, it is different to get data from local storage vs s3 and that explains the difference in performance but i wasn't expecting this difference of 5/6 times slower (or even worse if we increase the period or if we add more graphs to the dashboard).

So, my question: Is there anything that we are doing wrong in our configs or we will need to live with this performance? This can be a problem to use Thanos in production environments because it causes a bad user experiencing with this slowness.

Thank you,
BR

**Comment by GiedriusS** [comment]
> Hi @GiedriusS,
> 
> In grafana the step is 120, as can be seen in the GET request below:
> 
> ...
> So, my question: Is there anything that we are doing wrong in our configs or we will need to live with this performance? This can be a problem to use Thanos in production environments because it causes a bad user experiencing with this slowness.

Do you run Thanos Compactor? Do you have a common memcached instance shared between Thanos Store instances (if you have more than one)? Do you have query-frontend? Have you tuned the other knobs such as `--store.grpc.series-max-concurrency` appropriately? Is your remote object storage as close as it can possibly get geographically? These are some of the simple things you can do to improve the performance. If you tick all of the boxes then it's hard to tell, you'd have to profile / use tracing to understand where it is taking such a long time.

**Comment by lcoelho88** [comment]
Hi @GiedriusS, we run thanos-compactor with the following config and that part is ok because we can already see blocks downsampled:

```
      - args:
        - compact
        - --wait
        - --log.level=info
        - --log.format=json
        - --objstore.config-file=/config/bucket.yml
        - --data-dir=/var/thanos/compact
        - --debug.accept-malformed-index
        - --retention.resolution-raw=15d
        - --retention.resolution-5m=30d
        - --retention.resolution-1h=30d
        - --delete-delay=0s
        - --deduplication.replica-label=replica
```

So, briefly explaining our solution, We have several kubernetes namespaces and each namespace has the following components:

- prometheus + thanos sidecar
- thanos query
- thanos store

Additionally, there is one special namespace which we call "observability" that also runs thanos compact besides the mentioned components.

Then, on grafana, we have one datasource per namespace, pointing to corresponding thanos-query endpoint. 

Note that each thanos query, has configured the respective thanos-sidecar, the respective thanos-store and also the "observability" thanos-sidecar because we have specific metrics stored only on "observability" prometheus and we also need to be able to access it while it is not shipped to S3. Example of the config:

```
- args:
- query
- --grpc-address=0.0.0.0:10901
- --http-address=0.0.0.0:10902
- --log.level=debug
- --log.format=json
- --query.auto-downsampling
- --query.replica-label=replica
- --store=thanos-sidecar.crm.svc.cluster.local:10901
- --store=thanos-sidecar.observability.svc.cluster.local:10901
- --store=thanos-store.crm.svc.cluster.local:10901
```

We don't have memcache shared between thanos-stores because each thanos-store will only be invoked by it's own thanos-query, located in same namespace. Do you think that, for this specific solution, we would need memcache in each thanos-store, even if we don't have multiple thanos-query invoking it?

In addition, we tried query-frontend but we didn't see any improvement regarding performance on grafana side and, due to that, we removed it.

Regarding "store.grpc.series-max-concurrency", we are using default value (20) and, as mentioned above, considering that thanos-store has a relation on 1vs1 with thanos-queries in each namespace, it seems appropriate.

Finally our remote object store is S3, located in same region of EKS nodes.

Do you think that we are missing anything with this solution?

Thanks,
BR

**Comment by banghuaji** [comment]
![image](https://user-images.githubusercontent.com/17561338/110968285-4ae64180-8392-11eb-9dd7-8ee494211d55.png)
AT odd points Time (such as   1:01,3:01,5:01,...,23:01)，i have the same problem, query date from thanos receiver.

Thanos image: thanosio/thanos:v0.18.0
Prometheus image: quay.io/prometheus/prometheus:v2.21.0
Grafana image: grafana/grafana:7.3.2

Object Storage Provider: S3
I used thanos query、thanos receiver、thanos store
