### ISSUE TITLE
mixin: Introduce flexible multi-cluster/namespace mode for alerts and dashboards

### ISSUE THREAD

**Issue by kakkoyun** [thanos-io/thanos#3867]
This would be useful for users who don't use Kubernetes. In the current state of mixin we assume, there's a namespace label for all metrics. This is a Kubernetes term, it'd be better to be environment agnostic.

cc @metalmatze @brancz

**Comment by metalmatze** [comment]
Basically we should setup Thanos with systemd once and check that the mixin works as expected.
We could do something similar to the multi cluster mode that we have with the kubernetes-mixin and enable kuberentes in a config.

**Comment by brancz** [comment]
Aside from removing kubernetes labels .. is there really anything else we can do other than allowing the user to specify what label(s) make two clusters distinct?

**Comment by kakkoyun** [comment]
We'll definitely let them specify the labels and maybe we can provide a way to introduce different hierarchies that would both work for alerts and dashboards (e.g region, cluster, namespace etc). Basically, let them specify a layer. From that, we can inject a variable, a dropdown to dashboards and inject selectors/aggregators to alerts.

**Comment by brancz** [comment]
Makes sense :+1:

**Comment by kakkoyun** [comment]
Done.
