### ISSUE TITLE
thanos_compact_halted behaviour changed?

### ISSUE THREAD

**Issue by dswarbrick** [thanos-io/thanos#3868]
Thanos version 0.18.0, Prometheus version 2.24.1.
```
$ thanos --version
thanos, version 0.18.0 (branch: HEAD, revision: 60d45a02d46858a38013283b578017a171cf7b82)
  build user:       root@4cf3f59273a2
  build date:       20210127-12:18:59
  go version:       go1.15.7
  platform:         linux/amd64
```

**Object Storage Provider**: Cloudian Hyperstore

**What happened**:
Whilst recently trying to troubleshoot stability / reliability issues with our Cloudian Hyperstore S3 provider, we've had frequent "BaseFetcher: iter bucket: context deadline exceeded" logged by the compactor. In extreme cases, we've had "critical error detected; halting" errors.

In the past, we detected this with an alerting rule (`thanos_compact_halted == 1`). This was working up until about two weeks ago, with the same version of Thanos as mentioned above.

Somewhat suddenly, I have noticed that when we see the "critical error detected; halting" error now, a metrics scrape fails (i.e., `up{job="thanos-compact"} == 0`), so there is obviously also no `thanos_compact_halted` metric to alert on.

**What you expected to happen**:
Traditional / previous behaviour expected, with `thanos_compact_halted == 1`.

**How to reproduce it (as minimally and precisely as possible)**:
Running Thanos compactor as follows:
```
$ thanos compact --data-dir=/srv/thanos \
--objstore.config-file=/etc/prometheus/bucket.yml \
--delete-delay=24h \
--retention.resolution-raw=30d \
--retention.resolution-5m=180d \
--retention.resolution-1h=180d \
--bucket-web-label=monitor \
--block-viewer.global.sync-block-interval=10m \
--compact.cleanup-interval=20m \
--compact.concurrency=2 \
--wait
```
Some intervals tweaked to be more "gentle" to the S3 provider.

I suppose that iptables / nftables rules could be used to simulate loss of TCP connectivity to the S3 provider during a compaction run.

**Full logs to relevant components**:
```
Mar 02 10:47:17 thanos-compact thanos[12657]: level=warn ts=2021-03-02T10:47:17.663972658Z caller=intrumentation.go:54 msg="changing probe status" status=not-ready reason="syncing metas: BaseFetcher: iter bucket: context deadline exceeded"
Mar 02 10:47:17 thanos-compact thanos[12657]: level=info ts=2021-03-02T10:47:17.671376101Z caller=http.go:65 service=http/server component=compact msg="internal server is shutting down" err="syncing metas: BaseFetcher: iter bucket: context deadline exceeded"
Mar 02 10:47:17 thanos-compact thanos[12657]: level=error ts=2021-03-02T10:47:17.663708784Z caller=runutil.go:99 msg="function failed. Retrying in next tick" err="BaseFetcher: iter bucket: context deadline exceeded"
Mar 02 10:47:18 thanos-compact thanos[12657]: level=info ts=2021-03-02T10:47:18.171635062Z caller=http.go:84 service=http/server component=compact msg="internal server is shutdown gracefully" err="syncing metas: BaseFetcher: iter bucket: context deadline exceeded"
Mar 02 10:47:18 thanos-compact thanos[12657]: level=info ts=2021-03-02T10:47:18.171743173Z caller=intrumentation.go:66 msg="changing probe status" status=not-healthy reason="syncing metas: BaseFetcher: iter bucket: context deadline exceeded"
Mar 02 10:47:19 thanos-compact thanos[12657]: level=error ts=2021-03-02T10:47:19.946225522Z caller=compact.go:426 msg="critical error detected; halting" err="compaction: group 0@3160896766202963839: compact blocks [/srv/thanos/compact/0@3160896766202963839/01EZMEK2KTQWXHP26W40WB167R /srv/thanos/compact/0@3160896766202963839/01EZNA5ABXTHGY1FZCARPDVT36 /srv/thanos/compact/0@3160896766202963839/01EZP5MX0K2S12HZZNXVKJ36AB /srv/thanos/compact/0@3160896766202963839/01EZQ13RW3MPRPCRESW2RWV1D1 /srv/thanos/compact/0@3160896766202963839/01EZQWMD0AH583E1D25FHM7B7M /srv/thanos/compact/0@3160896766202963839/01EZRSN0B3RK36AXWC2G94MC50]: 2 errors: populate block: context canceled; context canceled"

(hours go by, before I noticed that it was dead, and tried to restart the service)

Mar 03 00:21:40 thanos-compact systemd[1]: Stopping Thanos compactor for Prometheus...
Mar 03 00:23:10 thanos-compact systemd[1]: thanos-compact.service: State 'stop-sigterm' timed out. Killing.
Mar 03 00:23:10 thanos-compact systemd[1]: thanos-compact.service: Killing process 12657 (thanos) with signal SIGKILL.
Mar 03 00:23:10 thanos-compact systemd[1]: thanos-compact.service: Main process exited, code=killed, status=9/KILL
Mar 03 00:23:10 thanos-compact systemd[1]: thanos-compact.service: Failed with result 'timeout'.
Mar 03 00:23:10 thanos-compact systemd[1]: Stopped Thanos compactor for Prometheus.
Mar 03 00:23:10 thanos-compact systemd[1]: Started Thanos compactor for Prometheus.
Mar 03 00:23:11 thanos-compact thanos[13582]: level=info ts=2021-03-03T00:23:11.52136275Z caller=factory.go:46 msg="loading bucket configuration"
...
```

**Anything else we need to know**:
It's possible that we are seeing a _different type_ of compactor halt than what we have seen in the past, since the S3 provider issues are fairly recent, and may be causing Thanos to fail in new / different ways.

If this is the expected behaviour, we will deal with it and add additional alerting to detect it in different ways.

**Comment by GiedriusS** [comment]
Hi. Are you sure that your compactor process simply didn't restart when it encountered such an error?

**Comment by dswarbrick** [comment]
There were some occasions when it bailed out with exit status 1 (despite the `--wait`), and since the systemd unit had `Restart=on-failure`, it was automatically restarted.

However, in many cases it simply shut down the http listener (and thus metrics endpoint), but the process remained running - to do what exactly, I don't know.

**Comment by GiedriusS** [comment]
> There were some occasions when it bailed out with exit status 1 (despite the `--wait`), and since the systemd unit had `Restart=on-failure`, it was automatically restarted.
> 
> However, in many cases it simply shut down the http listener (and thus metrics endpoint), but the process remained running - to do what exactly, I don't know.

Interesting :thinking: Could you upload the goroutines stack trace dump when it goes into such a state? You can find the data on the debug/pprof end-point on the port where you can find the metrics.

**Comment by dswarbrick** [comment]
I doubt that that will be possible, since the http endpoint is shutdown. It refuses http connections.

**Comment by GiedriusS** [comment]
Yes, sorry, you are correct. Are you absolutely sure that there isn't anything else in logs that may be of interest? Perhaps you have some time to try out https://golang.org/doc/gdb and see if with it you could get a goroutine dump? I'm afraid that there is no other way to understand what is going on.

**Comment by dswarbrick** [comment]
Unfortunately my logs for that instance only go back 7 days, and that is the only occurrence that I have in the logs of it going into such a state. I added a little more to the description above. There was nothing logged for several minutes leading up to the "changing probe status" entry, and nothing after the "critical error detected; halting" entry. I guess it really did halt - it just didn't exit. Maybe something waiting for a sync.WaitGroup?

If it goes into this zombie state again, I'll try to get a goroutine dump.

**Comment by dswarbrick** [comment]
This hasn't reocurred in my production environment (which is good), and I unfortunately don't have sufficient spare time right now to try to reproduce this in a lab environment. I will close this for now, but may reopen it if by some fluke it happens again.

**Comment by dswarbrick** [comment]
We had another occurrence of the halt this morning. It seems that it is more likely to occur during the large bi-weekly compact & downsample (which takes a few days on this instance).
```
Mar 19 04:34:57 thanos-compact thanos[6234]: level=info ts=2021-03-19T04:34:57.03063121Z caller=compact.go:748 group="0@{monitor=\"fra-prom2.fra\"}" groupKey=0@15631258114216240037 msg="downloaded and verified blocks; compacting blocks" plan="[/srv/thanos/compact/0@15631258114216240037/01F13BAWWFCCZBPADCH7DNEX8D /srv/thanos/compact/0@15631258114216240037/01F13J6M4F6WQMQ5ZRQPYZBNXV /srv/thanos/compact/0@15631258114216240037/01F13S2BCJ22Y1G0QK2022PFP8 /srv/thanos/compact/0@15631258114216240037/01F13ZY2MMXXQKV9XPQZR5BWF2]" duration=7m55.502277609s
Mar 19 04:35:20 thanos-compact thanos[6234]: level=info ts=2021-03-19T04:35:20.18981222Z caller=compact.go:748 group="0@{monitor=\"fra-prom1.fra\"}" groupKey=0@3160896766202963839 msg="downloaded and verified blocks; compacting blocks" plan="[/srv/thanos/compact/0@3160896766202963839/01F13BAWWFMXAYA3QNNA22E810 /srvthanos/compact/0@3160896766202963839/01F13J6M4AG928RJ0E0ZCD9G6Y /srv/thanos/compact/0@3160896766202963839/01F13S2BCASGV0WQXSV1JNV656 /srv/thanos/compact/0@3160896766202963839/01F13ZY2MBRTP0MWT38XZG0ZBG]" duration=8m18.660983872s
Mar 19 04:35:31 thanos-compact thanos[6234]: level=warn ts=2021-03-19T04:35:31.557206037Z caller=intrumentation.go:54 msg="changing probe status" status=not-ready reason="syncing metas: BaseFetcher: iter bucket: context deadline exceeded"
Mar 19 04:35:31 thanos-compact thanos[6234]: level=info ts=2021-03-19T04:35:31.578927118Z caller=http.go:65 service=http/server component=compact msg="internal server is shutting down" err="syncing metas: BaseFetcher: iter bucket: context deadline exceeded"
Mar 19 04:35:31 thanos-compact thanos[6234]: level=error ts=2021-03-19T04:35:31.556852779Z caller=runutil.go:99 msg="function failed. Retrying in next tick" err="BaseFetcher: iter bucket: context deadline exceeded"
Mar 19 04:35:31 thanos-compact thanos[6234]: level=error ts=2021-03-19T04:35:31.606417012Z caller=runutil.go:99 msg="function failed. Retrying in next tick" err="BaseFetcher: iter bucket: context canceled"
Mar 19 04:35:32 thanos-compact thanos[6234]: level=info ts=2021-03-19T04:35:32.117139661Z caller=http.go:84 service=http/server component=compact msg="internal server is shutdown gracefully" err="syncing metas: BaseFetcher: iter bucket: context deadline exceeded"
Mar 19 04:35:32 thanos-compact thanos[6234]: level=info ts=2021-03-19T04:35:32.117228472Z caller=intrumentation.go:66 msg="changing probe status" status=not-healthy reason="syncing metas: BaseFetcher: iter bucket: context deadline exceeded"
Mar 19 04:35:32 thanos-compact thanos[6234]: level=error ts=2021-03-19T04:35:32.580051995Z caller=compact.go:426 msg="critical error detected; halting" err="compaction: 2 errors: group 0@3160896766202963839: compact blocks [/srv/thanos/compact/0@3160896766202963839/01F13BAWWFMXAYA3QNNA22E810 /srv/thanos/compact/0@3160896766202963839/01F13J6M4AG928RJ0E0ZCD9G6Y /srv/thanos/compact/0@3160896766202963839/01F13S2BCASGV0WQXSV1JNV656 /srv/thanos/compact/0@3160896766202963839/01F13ZY2MBRTP0MWT38XZG0ZBG]: 2 errors: populate block: add series: context canceled; context canceled; group 0@15631258114216240037: compact blocks [/srv/thanos/compact/0@15631258114216240037/01F13BAWWFCCZBPADCH7DNEX8D /srv/thanos/compact/0@15631258114216240037/01F13J6M4F6WQMQ5ZRQPYZBNXV /srv/thanos/compact/0@15631258114216240037/01F13S2BCJ22Y1G0QK2022PFP8 /srv/thanos/compact/0@15631258114216240037/01F13ZY2MMXXQKV9XPQZR5BWF2]: 2 errors: populate block: add series: context canceled; context canceled"
```

I grep'ed for the error message in the code, and found the following in cmd/thanos/compact.go:
```go
            // The HaltError type signals that we hit a critical bug and should block
            // for investigation. You should alert on this being halted.
            if compact.IsHaltError(err) {
                if conf.haltOnError {
                    level.Error(logger).Log("msg", "critical error detected; halting", "err", err)
                    halted.Set(1)
                    select {}
                } else {
                    return errors.Wrap(err, "critical error detected")
                }   
            }
```
So it appears that the halting is intentional and supposed to serve some useful purpose.

I'm fairly sure the problem occurs when there is a socket level timeout in the fetching of blocks, due to an as-yet unresolved bug in the S3 service. What baffles me is that a common garden variety bug like that is not handled more gracefully.

**Comment by bwplotka** [comment]
👋🏽 Halting is on purpose. There is a flag you can disable. (: 

https://thanos.io/tip/components/compact.md/#halting

I don't think we should halt on timeout though. That's a bug 🙃

**Comment by yeya24** [comment]
Just saw this issue. @dswarbrick 
We met the same issue recently and the error is `context deadline exceeded`.

For us, the reason is that the wait-interval is too small, only 5m. But the data in the object storages are over 60k blocks. If there are too many data in the bucket, it takes a long time to iterate through all the objects and it is easy to take longer than the default 5m.

You can try to increase the interval to 15m or larger and see if the issue is still reproducible.

**Comment by dswarbrick** [comment]
@yeya24 As I understood, the the `--wait-interval` is merely a kind of cool-down period between consecutive runs, and shouldn't play a role _during_ compaction. We haven't hit this issue for a while in any case, so maybe our S3 service reliability has improved ;-)

**Comment by yeya24** [comment]
@dswarbrick That's right. But for the UI usage, it has another goroutine to sync block metas and uses wait interval as timeout https://github.com/thanos-io/thanos/blob/main/cmd/thanos/compact.go#L537.

**Comment by sowhat7** [comment]
> Just saw this issue. @dswarbrick
> We met the same issue recently and the error is `context deadline exceeded`.
> 
> For us, the reason is that the wait-interval is too small, only 5m. But the data in the object storages are over 60k blocks. If there are too many data in the bucket, it takes a long time to iterate through all the objects and it is easy to take longer than the default 5m.
> 
> You can try to increase the interval to 15m or larger and see if the issue is still reproducible.

I tried to modify this parameter, it seems to solve the problem of thanos compact restart
