### ISSUE TITLE
query: 0.19.0-rc.0 regression - Query with resolution. Graphs are dotted instead of lines

### ISSUE THREAD

**Issue by ahurtaud** [thanos-io/thanos#3872]
**Thanos, Prometheus and Golang version used**:
thanos v0.19.0-rc.0
prometheus v2.25.0
grafana v7.4.3

**What happened**:
We are validating 0.19.0-rc.0, by just upgrading the version, most of our grafana dashboards are becoming dotted graphs instead of lines. I suspect some resolution/step issue. As on thanos UI, it happens only when we set a resolution to 30s (our scrape interval)
![thanos-ui-reg](https://user-images.githubusercontent.com/25080995/109953116-eb2bce80-7cdf-11eb-93ec-0f252e69eaee.png)

Step is a default behaviour we have in our grafana dahsboards.

**What you expected to happen**:
Like v0.18.0 and like prometheus UI, having connected lines for the query.
![prometheus-ui](https://user-images.githubusercontent.com/25080995/109953093-e23afd00-7cdf-11eb-9267-48f0b56458f1.png)

**How to reproduce it (as minimally and precisely as possible)**:
Scrape something at 30s interval. Simple query raw metrics with a resolution of 30s. Compare Thanos replies vs prometheus reply.

**Comment by bwplotka** [comment]
Interesting. Thanks for reporting.

I wonder if it has something to do with the step changes we did with @hitanshu-mehta (https://github.com/thanos-io/thanos/pull/3740) 🤗

**Comment by hitanshu-mehta** [comment]
Yes. Resolution set in UI overwritten every time by this line.
https://github.com/thanos-io/thanos/blob/dfcfbe435c5722f67e4e4df50db915171ece4ff1/pkg/api/query/v1.go#L243
I can fix this :)
