### ISSUE TITLE
Add --max-time flag in thanos-sidecar

### ISSUE THREAD

**Issue by EusebiusAditya** [thanos-io/thanos#3876]
if possible can i request to add a max time to thanos sidecar if possible, this is very useful, to be able to give a time limit to thanos sidecar such that only the earlier/new (less than the max-time) metrics are processed by the sidecar, and let thanos-store handle all the older queries.

Currently using thanos 0.17.0 and there is no max-time flag in thanos-sidecar

**Comment by bwplotka** [comment]
Nice! I believe you can accomplish that already with `--min-time` flag. It's called `min-time` as it's the "earliest time" sidecar makes available 🤗 

```
     --min-time=0000-01-01T00:00:00Z
                                 Start of time range limit to serve. Thanos
                                 sidecar will serve only metrics, which happened
                                 later than this value. Option can be a constant
                                 time in RFC3339 format or time duration
                                 relative to current time, such as -1d or 2h45m.
                                 Valid duration units are ms, s, m, h, d, w, y.
```
https://thanos.io/tip/components/sidecar.md/#flags

I am quite sure this will work for you, but if not I will reopen, let us know 🤗

**Comment by EusebiusAditya** [comment]
@bwplotka would it be possible to open this, there could be a miss understanding on my part, but doesn't this min-time flag means that it will process data after the given date/time, which state in the description `which happened later than this value` but what i need is data before the value.
