### ISSUE TITLE
Give guidance that memcached should not be configured on loadbalancer level

### ISSUE THREAD

**Issue by wiardvanrij** [thanos-io/thanos#3879]
The 
```
config:
  addresses: []
```
Can be used in various ways. It should be clear that each memcached instance should be defined, rather than a 'main' instance E.g. "loadbalancer" adres. This is because the client does not do autodiscovery (Correct me if I'm wrong): https://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/AutoDiscovery.HowAutoDiscoveryWorks.html

# Plan

I will update the documentation to make this clear

**Comment by kakkoyun** [comment]
AFAIK you can use DNS service discovery or you can specify all. i.e https://github.com/thanos-io/thanos/blob/befb0257e8a3d49cb80b00794a4892abfb7ccb72/pkg/cacheutil/memcached_client.go#L81
Kubernetes e.g https://github.com/observatorium/deployments/blob/258c17c7889351cc7366a5c3b6162ad216d666d0/components/thanos.libsonnet#L241

@pstibrany @pracucci would know better.

But yes, let's improve documentation on this.

**Comment by wiardvanrij** [comment]
Right, thanks @kakkoyun . I will include that as well.  It's important to either use such DNS discovery or define the single targets yourself (in case of for example AWS). If you only define the k8s svc, you are going to have a bad time :)
