### ISSUE TITLE
make assets ends with error

### ISSUE THREAD

**Issue by roastiek** [thanos-io/thanos#3892]
**Thanos, Prometheus and Golang version used**:
main, 0.19.0rc0

**What happened**:
make assets fails with
```
rm -rf pkg/ui/react-app/node_modules/
make assets
.
.
.
$ react-scripts build
Creating an optimized production build...
Failed to compile.

./src/utils/index.ts
  Line 0:  Parsing error: Cannot read property 'map' of undefined


error Command failed with exit code 1.
```

**Anything else we need to know**:
`make assets` builds on 0.18.0 or older versions in the same enviroment.
I didn't find usage of `make assets` in any parts of ci build. So I cannot check if it should work or not.

`make react-app-test` works on all versions

**Comment by prmsrswt** [comment]
> I was able to replicate the issue. This is due to a `react-scripts` and TypeScript version issue, see [here](https://github.com/facebook/create-react-app/issues/9515). Thus, will possibly need to upgrade `react-scripts` to the latest version. This would however force us to bump `eslint` to v7 as well and will require a few refactors.

Thanks for digging this up. It'd be great if you can come up with a PR with the required changes. :)

**Comment by saswatamcode** [comment]
Sure! Will be raising a PR shortly.
