### ISSUE TITLE
Snappy compression failing for AWS Elasticache Memcached (Query Frontend)

### ISSUE THREAD

**Issue by narenreddycs** [thanos-io/thanos#3896]
**Thanos, Prometheus and Golang version used**:
v0.18.0

**Object Storage Provider**:
S3
**What happened**:
We are using AWS Elasticache Memcached as Thanos Query frontend. When we try to use snappy cache compression using the flag 

> --cache-compression-type=snappy

the cache is getting corrupted. 

**What you expected to happen**:
snappy compression is expected to work as this is supported for Memcached. 

**How to reproduce it (as minimally and precisely as possible)**:
Below is the config to use to reproduce

>     image: quay.io/thanos/thanos:v0.18.0
        args:
        - query-frontend
        - --log.level=info
        - --log.format=logfmt
        - --query-frontend.compress-responses
        - --http-address=0.0.0.0:9090
        - --query-frontend.downstream-url= <url>
        - --query-range.split-interval=12h
        - --labels.split-interval=12h
        - --query-range.max-retries-per-request=10
        - --labels.max-retries-per-request=10
        - --query-frontend.log-queries-longer-than=60s
        - --cache-compression-type=snappy
        - |-
          --query-range.response-cache-config="config":
            "addresses":
            - dns+<url>:11211
            "dns_provider_update_interval": "10s"
            "max_async_buffer_size": 10000
            "max_async_concurrency": 20
            "max_get_multi_batch_size": 0
            "max_get_multi_concurrency": 100
            "max_idle_connections": 100
            "timeout": "500ms"
            # "max_item_size": "10MiB"
            # "expiration": "24h"
          "type": "memcached"
        - |-
          --labels.response-cache-config="config":
            "addresses":
            - dns+<url>:11211
            "dns_provider_update_interval": "10s"
            "max_async_buffer_size": 10000
            "max_async_concurrency": 20
            "max_get_multi_batch_size": 0
            "max_get_multi_concurrency": 100
            "max_idle_connections": 100
            "timeout": "500ms"
            # "max_item_size": "10MiB"
            # "expiration": "24h"
          "type": "memcached"

**Full logs to relevant components**:

> level=error ts=2021-03-08T16:56:42.819776664Z caller=snappy.go:39 msg="failed to decode cache entry" err="snappy: corrupt input"
level=error ts=2021-03-08T16:56:48.406215152Z caller=snappy.go:39 msg="failed to decode cache entry" err="snappy: corrupt input"
level=error ts=2021-03-08T16:56:48.406215214Z caller=snappy.go:39 msg="failed to decode cache entry" err="snappy: corrupt input"
level=error ts=2021-03-08T16:56:48.406220283Z caller=snappy.go:39 msg="failed to decode cache entry" err="snappy: corrupt input"
level=error ts=2021-03-08T16:56:50.176965081Z caller=snappy.go:39 msg="failed to decode cache entry" err="snappy: corrupt input"
level=error ts=2021-03-08T16:56:50.176965401Z caller=snappy.go:39 msg="failed to decode cache entry" err="snappy: corrupt input"
level=error ts=2021-03-08T16:56:50.176965453Z caller=snappy.go:39 msg="failed to decode cache entry" err="snappy: corrupt input"
level=error ts=2021-03-08T16:56:52.624055364Z caller=snappy.go:39 msg="failed to decode cache entry" err="snappy: corrupt input"
level=error ts=2021-03-08T16:56:52.624094474Z caller=snappy.go:39 msg="failed to decode cache entry" err="snappy: corrupt input"
level=error ts=2021-03-08T16:56:52.624099175Z caller=snappy.go:39 msg="failed to decode cache entry" err="snappy: corrupt input"
level=error ts=2021-03-08T16:56:53.397166518Z caller=snappy.go:39 msg="failed to decode cache entry" err="snappy: corrupt input"
level=error ts=2021-03-08T16:56:53.397196509Z caller=snappy.go:39 msg="failed to decode cache entry" err="snappy: corrupt input"
level=error ts=2021-03-08T16:56:53.397219822Z caller=snappy.go:39 msg="failed to decode cache entry" err="snappy: corrupt input"
level=error ts=2021-03-08T16:56:53.442127263Z caller=snappy.go:39 msg="failed to decode cache entry" err="snappy: corrupt input"
level=error ts=2021-03-08T16:56:53.442130941Z caller=snappy.go:39 msg="failed to decode cache entry" err="snappy: corrupt input"
level=error ts=2021-03-08T16:56:53.442130982Z caller=snappy.go:39 msg="failed to decode cache entry" err="snappy: corrupt input"
level=error ts=2021-03-08T16:56:53.876045703Z caller=snappy.go:39 msg="failed to decode cache entry" err="snappy: corrupt input"
level=error ts=2021-03-08T16:56:53.876045969Z caller=snappy.go:39 msg="failed to decode cache entry" err="snappy: corrupt input"
level=error ts=2021-03-08T16:56:53.876045967Z caller=snappy.go:39 msg="failed to decode cache entry" err="snappy: corrupt input"

**Comment by GiedriusS** [comment]
If you try to get those values via `telnet` & decode it with https://github.com/kubo/snzip or something, does it work?

**Comment by narenreddycs** [comment]
Not able to reproduce the issue once I restarted the Memcached cluster to clear the cache.

**Comment by wiardvanrij** [comment]
I think this is valuable to investigate further. Thanos does a `isDiffVarintSnappyEncodedPostings` to check if an item is compressed. So even in the case that non-compressed items are posted, snappy encoding is enabled, it should be able to handle a mixture of items.
