### ISSUE TITLE
Cache LabelValues

### ISSUE THREAD

**Issue by fabxc** [thanos-io/thanos#39]
We should keep an eye on the `LabelValues` RPC to store nodes. It will always hit every single block, which can get particularly costly on GCS store nodes.

This data does rarely change and is only used for things like auto-completion. But for that it is called whenever the query UI opens up. Probably the query nodes themselves should already cache them.

**Comment by Bplotka** [comment]
Is that actually true? As far as I can tell from code, this only hits all blocks' index files which are already preloaded on store node, right?

**Comment by fabxc** [comment]
Yes, but we are still considering not caching those full files right? My thinking was even with, we could be token about tens of thousands of blocks at some point. And that might still get expensive then.
We also always have to do a full fanout to every single Prometheus server.

But you are generally right, this issue was probably opened as a pre-mature concern.

**Comment by Bplotka** [comment]
Ah, sorry, you're right. We will soon move out from this no-cache heaven.

**Comment by fabxc** [comment]
Mh, I'll close this for now. On store nodes that data is served entirely from memory now anyway. The full fanout is probably not an issue anymore with that.

**Comment by bwplotka** [comment]
We are exploring loading blocks on demand, so it's time to reopen this as values would be no longer in memory. (:

Worth to note that mostly `__name__` arg is heavily used, so we might want to cache all of it.

The alternative would be implementing the time limit on this. Also related to the: https://github.com/thanos-io/thanos/issues/39

**Comment by ppanyukov** [comment]
@bwplotka 

> The alternative would be implementing the time limit on this. Also related to the: #39

couldn't help noticing this issue is related to itself, surely a mistake :)

**Comment by bwplotka** [comment]
yup, fixed!
