### ISSUE TITLE
Add tests for the request logging

### ISSUE THREAD

**Issue by yashrsharma44** [thanos-io/thanos#3923]
PRs for request logging #3361 #2849 contains some string manipulation, which might create unnecessary panic as observed in #3921 

Would be nice to write tests for making sure panics do not happen.

**Comment by ashish493** [comment]
Any type of checklist for solving this issue? 
Like do we have to use some tesing framework like ginkgo or like create some basic functional tests like this 
```
func TestPanic(t *testing.T) {
    defer func() {
        if r := recover(); r == nil {
            t.Errorf("The code did not panic")
        }
    }()

    // The following is the code under test
    OtherFunctionThatPanics()
}
```
I'm bit confused :(

**Comment by yashrsharma44** [comment]
> Like do we have to use some tesing framework like ginkgo

We could start with making simple Go-tests, no need to look for any testing framework.

We can also write up unit tests for different functions out in the logging [package](https://github.com/thanos-io/thanos/tree/main/pkg/logging) 
* For starters, you can take a look at the [`grpc.go`](https://github.com/thanos-io/thanos/blob/main/pkg/logging/grpc.go), and add unit tests for the functions that are working, would be nice to have a defined behaviour for them
