### ISSUE TITLE
Generate Structs for Flags or Output machine-reable description for flags

### ISSUE THREAD

**Issue by kakkoyun** [thanos-io/thanos#3924]
To be able to conveniently generate type-safe configurations for Thanos. This could be utilized by the configuration projects (e.g `kube-thanos` or similar projects). We would like to have structs that define flags and configuration for Thanos.

Flags could be generated from those structs or structs can be generated from existing flags.
Any change should be seamless to users, we shouldn't change any behaviour.

Any ideas? WDYT?

@thanos-io/thanos-maintainers 

related: https://github.com/thanos-io/kube-thanos/pull/184

**Comment by brancz** [comment]
Self-describing-binaries is kind of how I see this. I like this idea a lot. I personally think just a json blob that describes the subcommands and flags of those is a really fantastic start. Little can do a lot here I believe.

**Comment by kakkoyun** [comment]
@brancz Great idea! Having a subcommand to output this would be an amazing convenience. I wonder if something similar already exists?

**Comment by roidelapluie** [comment]
Something like https://github.com/alecthomas/kong might help you.

**Comment by roidelapluie** [comment]
There is also https://github.com/bwplotka/flagarize

**Comment by kakkoyun** [comment]
@bwplotka's gonna kill me how I've forgotten about `flagarize` 🙈

**Comment by bwplotka** [comment]
Nah, fllagarize is dead 🙃 


I would vote for https://github.com/openproto/protoconfig as this was created exactly for this purpose.

**Comment by bwplotka** [comment]
I just had chat with @smintz, co-creator of similar project https://github.com/protoconf/protoconf, I think we plan to join forces into going for proto based configuration (alongside flags ofc)
