### ISSUE TITLE
mixin: Add dedicated read/write dashboards

### ISSUE THREAD

**Issue by kakkoyun** [thanos-io/thanos#3926]
We could benefit from dedicated read/write dashboards. Similar to cortex https://github.com/grafana/cortex-jsonnet/blob/main/cortex-mixin/dashboards/writes.libsonnet, https://github.com/grafana/cortex-jsonnet/blob/main/cortex-mixin/dashboards/reads.libsonnet

**Comment by jmichalek132** [comment]
Still relevant
