### ISSUE TITLE
mixin: Add SLO-based alerts and dashboards

### ISSUE THREAD

**Issue by kakkoyun** [thanos-io/thanos#3927]
As stated in the title, we'd like to have SLO-based alerts and dashboards.

We have started a document to determine Thanos SLOs. Feel free to contribute.
https://docs.google.com/document/d/1OTe2hfnlQHO8eBhvjwFK80pDGNY68WgjkoJNat7GZ_g/edit?usp=sharing

cc @metalmatze

**Comment by jmichalek132** [comment]
Still relevant
