### ISSUE TITLE
mixin: Add alert tests

### ISSUE THREAD

**Issue by kakkoyun** [thanos-io/thanos#3932]
As stated in the title, we need to add basic `promtool` tests for all the alerts we have in mixin. At the very least, they will help us to catch templating issues with our alerts.

**Comment by roidelapluie** [comment]
I think mixtool would compile + test the mixins.

**Comment by metalmatze** [comment]
Yup, indeed this is a great example for the usage of mixtool! Happy to adjust mixtool if something is missing for this here.

**Comment by metalmatze** [comment]
A really great example for writing alert tests should be: https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/tests.yaml
Running them is explained here: 
https://github.com/kubernetes-monitoring/kubernetes-mixin#running-the-tests

**Comment by metalmatze** [comment]
@jmichalek132 wants to work on this! Let us know on Slack if you need help. Thanks!

**Comment by jmichalek132** [comment]
Still relevant
