### ISSUE TITLE
Disk Space recommendation for Thanos Store Gateway

### ISSUE THREAD

**Issue by kirinnee-atomi** [thanos-io/thanos#3939]
Quick question:

How do I estimate the amount Thanos Store Gateway disk size based on the amount of retention I need? Does it pull and cache metrics locally or does it only store index?

**Comment by GiedriusS** [comment]
On boot, Thanos Store builds the binary index header of each block & stores them on disk: https://thanos.io/tip/operating/binary-index-header.md/. So, it depends on how big the blocks are. If the number of metrics that you ingest over time is roughly the same then you could multiply the size of one binary index header by the number of the blocks that you have to estimate the disk size requirement.

**Comment by kirinnee-atomi** [comment]
Yes it does, thank you very much
