### ISSUE TITLE
objstore.DownloadDir() doesn't correctly cleanup on failure

### ISSUE THREAD

**Issue by pracucci** [thanos-io/thanos#3941]
**What happened**:
We've seen an error like this:
```
msg="failed to remove file on partial dir download error" file=/data/compact/0@5679675083797525161-1614499200000-1614506400000/01EZM4R375DDZC1F52B9HV7S8G err="remove /data/compact/0@5679675083797525161-1614499200000-1614506400000/01EZM4R375DDZC1F52B9HV7S8G: directory not empty"
```

From a quick look at the `DownloadDir()` implementation ([code](https://github.com/thanos-io/thanos/blob/main/pkg/objstore/objstore.go#L226)) I think it doesn't cleanup cleanup on failure when the downloaded directory contains subdirectories too (eg. block `chunks/`).

I see a couple of issues:
1. `downloadedFiles` is not populated when `DownloadDir()` is called recursively
2. `downloadedFiles` is populated with the `dst` and not actually the downloaded file, but then we delete it we call `os.Remove()` (non recursive)

**What you expected to happen**:

Fixing the logic should be easy, but I'm not sure what's the desired behaviour. Do we expect `DownloadDir()` to delete everything including subdirectories?

**Comment by bwplotka** [comment]
Yup, thanks!

**Comment by pracucci** [comment]
> Ideally it deletes all it downloaded if requested. WDYT?

I do agree. I'm actually thinking whether it's easier to change `DownloadDir()` logic and **not** make the use of any recursion. Now we have the ability to `Iter()` objects recursively, so we could just leverage on it. This would simplify the fix.

**Comment by pracucci** [comment]
> Could you please print the whole directory tree of when this happens if possible?

Yeah. Unfortunately happened on a customer cluster and I was just got this report (I wasn't actively debugging it).

**Comment by GiedriusS** [comment]
> > Could you please print the whole directory tree of when this happens if possible?
> 
> Yeah. Unfortunately happened on a customer cluster and I just got this report (I wasn't actively debugging it).

I presume your customer doesn't run code from `v0.19.0-rc.1`? So, this issue is probably from `v0.18.0` i.e. before https://github.com/thanos-io/thanos/pull/3031 ?

**Comment by saswatamcode** [comment]
I think this bug would arise when the `downloadedFile` array is populated with a `dst` that hasn't been downloaded. This possibly should cause `DownloadFile` to return an error though and the array wouldn't be appended. Was there any other error just before this? It would be easier to figure out the flow then.
