### ISSUE TITLE
Instrument http_request_duration_seconds metric with exemplars

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#3944]
From the discussion https://github.com/thanos-io/thanos/discussions/3938, we think it is a good start to instrument https://github.com/thanos-io/thanos/blob/main/pkg/extprom/http/instrument_server.go#L44 with Exemplars.

Exemplar example: 
1. https://github.com/weaveworks/common/pull/202

Help is welcomed!

**Comment by metalmatze** [comment]
I am going to assign this to myself as I got it working from a Thanos standpoint for the most part. :tada: 
![Screenshot from 2021-03-26 01-44-35](https://user-images.githubusercontent.com/872251/112561112-d91be800-8dd4-11eb-8f98-2a4b2d05fa23.png)
Right now I'm unable to actually make it work in Grafana, but that should be all for the most part.

Probably, worth noting that I had to use the histogramVec directly as client_golang `ObserveWithExemplar` doesn't work with currying right now. I'll open an issue.
