### ISSUE TITLE
Circular dependency on github.com/cortexproject/cortex

### ISSUE THREAD

**Issue by vatine** [thanos-io/thanos#3949]
**Thanos, Prometheus and Golang version used**:

Go: v1.16
Thanos: github.com/thanos-io/thanos@v0.18.0

**Object Storage Provider**: N/A

**What happened**: I got a build error, trying to build thanos in a fresh docker container

**What you expected to happen**: I expect to not get a build error.

**How to reproduce it (as minimally and precisely as possible)**:

In a newly-started golang:1.16.2-buster, make sure all packages are updated, create a directory under /go, cd into it, create a go module, then do "go get github.com/thanos-io/thanos@v0.18.0".

This is part of the next round of data gathering for my "gochecker" project, where I am trying to look at a section of the Go eco-system and gather some statistics around "testing", "formatting", and "buildability". By running all the fetches through an Athens proxy, I can get an analysis of a few seed modules and all transitive dependencies. Unfortunately, this is what I saw trying to build the latest Thanos.

**Full logs to relevant components**:

<details>Logs
<p>

```
root@5eb45653a0f4:/go# apt-get upgrade
root@5eb45653a0f4:/go# apt-get install -y python3.7, python3-pip
root@5eb45653a0f4:/go# mkdir test
root@5eb45653a0f4:/go# cd test
root@5eb45653a0f4:/go/test# go version
go version go1.16.2 linux/amd64
root@5eb45653a0f4:/go/test# go mod init test
go: creating new go.mod: module test
root@5eb45653a0f4:/go/test# go get github.com/thanos-io/thanos@v0.18.0
go: downloading github.com/thanos-io/thanos v0.18.0
go get: github.com/thanos-io/thanos@v0.11.0 updating to
	github.com/thanos-io/thanos@v0.18.0 requires
	github.com/cortexproject/cortex@v1.5.1-0.20201111110551-ba512881b076 requires
	github.com/thanos-io/thanos@v0.13.1-0.20201030101306-47f9a225cc52 requires
	github.com/cortexproject/cortex@v1.4.1-0.20201030080541-83ad6df2abea requires
	github.com/thanos-io/thanos@v0.13.1-0.20201019130456-f41940581d9a requires
	github.com/cortexproject/cortex@v1.3.1-0.20200923145333-8587ea61fe17 requires
	github.com/thanos-io/thanos@v0.13.1-0.20200807203500-9b578afb4763 requires
	github.com/cortexproject/cortex@v1.2.1-0.20200805064754-d8edc95e2c91 requires
	github.com/thanos-io/thanos@v0.13.1-0.20200731083140-69b87607decf requires
	github.com/cortexproject/cortex@v0.6.1-0.20200228110116-92ab6cbe0995 requires
	github.com/prometheus/alertmanager@v0.19.0 requires
	github.com/prometheus/prometheus@v0.0.0-20190818123050-43acd0e2e93f requires
	k8s.io/client-go@v12.0.0+incompatible: reading http://192.168.1.2:3000/k8s.io/client-go/@v/v12.0.0+incompatible.mod: 404 Not Found

```

</p>
</details>

**Anything else we need to know**:

Uncomment and fill if you use not casual environment or if it might be relevant.

**Environment**: The golang:1.16.2-buster docker image, with updated packages.
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Others:

**Comment by bwplotka** [comment]
Thanks for raising! This might similar to https://github.com/thanos-io/thanos/issues/3832 so closing this one to avoid duplication and confusion. I will try to help how to quickly resolve it (TL;DR manual adjustment to go.mod is required) 🤗 Feel free to comment there!
