### ISSUE TITLE
Jaeger ForceTracing not work

### ISSUE THREAD

**Issue by zcong1993** [thanos-io/thanos#3951]
thanos use `X-Thanos-Force-Tracing` as `JaegerDebugHeader` key [https://github.com/thanos-io/thanos/blob/90015469cc81e7532a995527aa903262988d0199/pkg/tracing/jaeger/jaeger.go#L55](https://github.com/thanos-io/thanos/blob/90015469cc81e7532a995527aa903262988d0199/pkg/tracing/jaeger/jaeger.go#L55), but jaeger client always convert request header key to lowercase before compare, [https://github.com/jaegertracing/jaeger-client-go/blob/v2.25.0/propagation.go#L139-L147](https://github.com/jaegertracing/jaeger-client-go/blob/v2.25.0/propagation.go#L139-L147), so the debug header key is never equal to `X-Thanos-Force-Tracing`.

**Comment by conorevans** [comment]
https://www.jaegertracing.io/docs/1.22/client-libraries/#baggage

> Limitation: since HTTP headers don’t preserve the case, Jaeger recommends baggage keys to be lowercase-kebab-case, e.g. my-baggage-key-1.

This should probably be updated in the Jaeger tracer. Happy to take it on if a maintainer agrees (and feel free to assign it to me while there, if that's welcomed - thanks).

**Comment by yeya24** [comment]
@conorevans Thank you, please go ahead! :+1:
