### ISSUE TITLE
docs: Compator page image is broken; add data about web viewer

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3954]
1. The image is not resized properly and goes outside of the column. (: 

(https://thanos.io/tip/components/compact.md/)
![image](https://user-images.githubusercontent.com/6950331/112213282-cd35f780-8c15-11eb-8777-b33216fe9eb5.png)

2. Compactor exposes `/loaded` and `/global` endpoints on HTTP port which gives amazing block UI explained [here](https://thanos.io/tip/components/tools.md/#bucket-web). Would be nice to add this information 🤗

**Comment by RavjotSandhu** [comment]
Sir would please give a little more context as to what to do? As far I understood this current image is to be replaced with that blocKUI one. Am I right?

**Comment by RavjotSandhu** [comment]
Yup I'm gonna try it out. Previously was infected with covid, right now viva and evaluations are going on. Would give it a shot soon

**Comment by GiedriusS** [comment]
Closed via https://github.com/thanos-io/thanos/pull/4361

**Comment by GiedriusS** [comment]
Oh, sorry, the 2nd point is not done yet. Help welcome :hugs:

**Comment by Itaachime** [comment]
@GiedriusS Can u please elaborate what is the requirement of second point because it is not clear to me

**Comment by ianbillett** [comment]
@sandeep1785 
> Compactor exposes /loaded and /global endpoints on HTTP port which gives amazing block UI explained here. Would be nice to add this information
I would interpret that as a request to add the information exposed by `/loaded` and `/global` endpoints to the compactor UI :+1:
