### ISSUE TITLE
Swift: Error detected but not handled while uploading a file to the bucket

### ISSUE THREAD

**Issue by ubcharron** [thanos-io/thanos#3958]
**Thanos, Prometheus and Golang version used**: Thanos version github.com/thanos-io/thanos v0.13.1-0.20210108102609-f85e4003ba51 (from Cortex 1.7.0)

**Object Storage Provider**: Swift

**What happened**: An index file failed to be uploaded to Swift, but I think the error was not detected by the error-handling code.

The Cortex compactor reported that it successfully uploaded an entire block (chunks, meta and index file). However, in Swift, the index file does not exist for that block. We looked at Swift's own logs, and there is no record of the index ever being uploaded. Additionally, a warning was recorded by Thanos (see logs below).

I believe that `swift.Upload()` may have encountered an error, yet returned nil.

**What you expected to happen**: If a file does is not successfully uploaded, the caller of `swift.Upload()` should be notified that there was an error so it can retry.

**How to reproduce it (as minimally and precisely as possible)**: I don't know what precise conditions led to this, but a timeout seems involved. I think the error in `Upload()` was caught by `Close()` but not by `Copy()`. However, only errors in `Copy()` are returned to the caller. Since `Close()` is called from "`defer CloseWithLogOnErr(..)`", `Upload()` returned nil and its caller did not know the upload might have failed.

https://github.com/thanos-io/thanos/blob/main/pkg/objstore/swift/swift.go#L315

**Full logs to relevant components**:

Logs from the Cortex compactor:
```json
{  
  "caller": "runutil.go:124",
  "err": "upload object close: Timeout when reading or writing data",
  "level": "warn",
  "msg": "detected close error",
  "ts": "2021-03-20T05:12:44.877771796Z"
}
{
  "bucket": "tracing: cortex-tsdb-prod04",
  "caller": "objstore.go:159",
  "component": "compactor",
  "dst": "01F16ZRT8TYA08VJQR1ZPCC5EP/index",
  "from": "data/compact/0@14583055817248146110/01F16ZRT8TYA08VJQR1ZPCC5EP/index",
  "group": "0@{__org_id__=\"1\"}",
  "groupKey": "0@14583055817248146110",
  "level": "debug",
  "msg": "uploaded file",
  "org_id": "1",
  "ts": "2021-03-20T05:12:44.877834603Z"
}
{
  "caller": "compact.go:810",
  "component": "compactor",
  "duration": "4m41.662527735s",
  "group": "0@{__org_id__=\"1\"}",
  "groupKey": "0@14583055817248146110",
  "level": "info",
  "msg": "uploaded block",
  "org_id": "1",
  "result_block": "01F16ZRT8TYA08VJQR1ZPCC5EP",
  "ts": "2021-03-20T05:12:45.140243007Z"
}
{
  "caller": "compact.go:832",
  "component": "compactor",
  "group": "0@{__org_id__=\"1\"}",
  "groupKey": "0@14583055817248146110",
  "level": "info",
  "msg": "marking compacted block for deletion",
  "old_block": "01F15H6D6CXE1ASE788HQECHM4",
  "org_id": "1",
  "ts": "2021-03-20T05:12:45.627586825Z"
}
```

**Anything else we need to know**: I wasn't sure if I should open an issue in Cortex or Thanos. I apologize if it's not in the right place.

**Comment by pracucci** [comment]
After some discussion in https://github.com/cortexproject/cortex/issues/4055, it turnes out the Swift client `Upload()` returns no error if it fails closing the writer, but it should. Issue is here:
https://github.com/thanos-io/thanos/blob/2e212f4c9b32e27fd8ad7c90f4060942e8adbf11/pkg/objstore/swift/swift.go#L315
