### ISSUE TITLE
For each write to Thanos/receive,  add limit to the allowed number of samples

### ISSUE THREAD

**Issue by spaparaju** [thanos-io/thanos#3964]
### Is your proposal related to a problem?
Yes

Currently Thanos based hosted monitoring services lack protection to limit the number of samples that can be accepted at 'Thanos receive' component. 

### Describe the solution you'd like

For each write call, define a configurable upper bound (at Thanos receive component) to the number of samples that can be received.
### Describe alternatives you've considered

None

### Additional context

PR for this proposal : https://github.com/thanos-io/thanos/pull/3963

**Comment by metalmatze** [comment]
I'm wondering if that should be really part of the Thanos Receiver and not some other proxy in front of the Receiver. 
Maybe it still fits into the Receiver Route once the Receiver is split into Receiver and Receiver Route?

**Comment by spaparaju** [comment]
The idea behind this knob is to protect, configure resources at Receiver pods

**Comment by ianbillett** [comment]
still relevant

**Comment by spaparaju** [comment]
still relevant
