### ISSUE TITLE
Component Receiver --tsdb.retention=0d didn't work

### ISSUE THREAD

**Issue by yutian-github** [thanos-io/thanos#3965]
**Thanos, Prometheus and Golang version used**:

**Object Storage Provider**:

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by yutian-github** [comment]
When I used Receiver to recieve kubenetes metrics and config --tsdb.retention=0d, but found the tsdb metrics blocks is still generated locally,

**Comment by yeya24** [comment]
@yutian-github Setting retention to `0d` disables retention. And having retention enabled doesn't mean there is no TSDB block generated.

**Comment by yutian-github** [comment]
> @yutian-github Setting retention to `0d` disables retention. And having retention enabled doesn't mean there is no TSDB block generated. Hope this helps.

Thanks for your reply. So setting retention to 0d always means no limit on the local disk.
