### ISSUE TITLE
Query-frontend Data faults In Grafana

### ISSUE THREAD

**Issue by DreamDZhu** [thanos-io/thanos#3972]
my thanos query-frontend start command is :

docker run -d --network host --name thanos-queryfrontend -v /etc/thanos:/etc/thanos thanosio/thanos:v0.19.0-rc.2 \
 query-frontend \
--http-address=192.168.12.105:15902 \
--query-frontend.downstream-url=http://192.168.12.105:11902 \
--query-range.split-interval=12h \
--labels.split-interval=12h \
 --labels.max-retries-per-request=10 \
 --query-range.align-range-with-step \
 --query-frontend.compress-responses \
 --query-range.partial-response \
 --query-range.request-downsampled

but in grafana , when i look up historical data , there is a lack of data 
![微信图片_20210325144703](https://user-images.githubusercontent.com/8407917/112430360-ff139f00-8d78-11eb-932d-1c25f95c436e.png)
**query-frontend**

if i set grafana data source to query , there would be no such situation
![query](https://user-images.githubusercontent.com/8407917/112430632-603b7280-8d79-11eb-89dd-bb3b161eebe6.png)
**query**

why is this happening ?  because of query-frontend cahing or what else ??

**Comment by yeya24** [comment]
@DreamDZhu Yes, it might be related to caching. But I need to investigate. Do you configure any HTTP parameters in your Prometheus datasource? Like downsampling?

**Comment by DreamDZhu** [comment]
> @DreamDZhu Yes, it might be related to caching. But I need to investigate. Do you configure any HTTP parameters in your Prometheus datasource? Like downsampling?

Thank you for your reply 。 In  compact , I set 5 minutes of down-sampling data and 60 minutes of down-sampling data for 60 days 。

I think I found the cause of the problem.

Since my sidecar was set cmd  :   
       -min-time=-2h  
 and my store set cmd :
      --store_min_time: -180d
      --store_max_time: -2h

When the local prometheus generates the TSDB data, because the block is too large and the network is limited, it is not uploaded to the object storage in time, which leads to the data fault between the sidecar and the store merge query.

At this point Using queryfrontend to query ,  his cache causes this problem in the grafana.

I'd like to ask how to set queryfrontend cache expiration date ?

**Comment by GiedriusS** [comment]
> > @DreamDZhu Yes, it might be related to caching. But I need to investigate. Do you configure any HTTP parameters in your Prometheus datasource? Like downsampling?
> 
> @yeya24 Thank you for your reply 。 In compact , I set 5 minutes of down-sampling data and 60 minutes of down-sampling data for 60 days 。
> 
> I think I found the cause of the problem.
> 
> Since my sidecar was set cmd :
> -min-time=-2h
> and my store set cmd :
> --store_min_time: -180d
> --store_max_time: -2h
> 
> When the local prometheus generates the TSDB data, because the block is too large and the network is limited, it is not uploaded to the object storage in time, which leads to the data fault between the sidecar and the store merge query.
> 
> At this point Using queryfrontend to query , his cache causes this problem in the grafana.
> 
> I'd like to ask how to set queryfrontend cache expiration date ?

`expiration` parameter should control that (https://thanos.io/tip/components/query-frontend.md/#memcached). Have you tried it? Thank you for digging into this! As this is a non-issue, I will close this to keep our issue tracker a bit tidier. I hope you understand :hugs:
