### ISSUE TITLE
Have easier to way to tell the progress of compactor (and downsampling)

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#3985]
Currently, you need to check Thanos Compact UI and check if all older blocks are bigger. There should be only up to 5 of 2h, 8h and 2d blocks. Rest should be compacted to 2w. Similar for downsampled blocks. 

Or you can check the number of compactions per day to see if the number stabilizes. 

Both ways are pretty manual. I would propose adding metric suggesting the backlog of compaction to make. This requires potentially changing our compaction planner logic, which is already planned for https://github.com/thanos-io/thanos/issues/3405

**Comment by 2nick** [comment]
I'm trying to figure out the way of reporting progress and think that there are 2 possible ways:

1. API with JSON response
2. Prometheus metrics

In my opinion for both ways would be enough to give out:
- block id
- group id for the block
- compaction state of the group
- compaction state for the block

Probably it's reasonable to give a time of block's state change as a metric value.

OFC it's possible to implement own readers for all stages to report bytes progress, but it looks like "overkill".

WDYT?

**Comment by vanugrah** [comment]
Yes please! I spent the weekend trying to answer that question since we have a huge compaction backlog and I couldn't think of a simple instrumentation to add. Largely because currently compaction planning is iterative, so we'd need to simulate multiple plan invocations per group to accurately determine how many compaction runs would need to happen per group to reach the desired state. 

As a user - I'd love to see an overall compaction percentage for the bucket as well as compaction progress for each group. I'm going to think more about this problem and report back.

**Comment by kernelpanic77** [comment]
Hello @bwplotka! I am relatively new to the Thanos project but would love to get involved and potentially contribute. Any pointers or resources for me to get started with Thanos. So that I could get a better understanding of the project and this issue?

Thanks,
Ishan

**Comment by yeya24** [comment]
> Yes please! I spent the weekend trying to answer that question since we have a huge compaction backlog and I couldn't think of a simple instrumentation to add. Largely because currently compaction planning is iterative, so we'd need to simulate multiple plan invocations per group to accurately determine how many compaction runs would need to happen per group to reach the desired state.
> 
> As a user - I'd love to see an overall compaction percentage for the bucket as well as compaction progress for each group. I'm going to think more about this problem and report back.

Sounds like a promising way to go!

**Comment by yeya24** [comment]
> Another idea that @yeya24 came up with is calculating retention progress, once we have finished working on compaction and downsampling progress. Broadly, it will also be on the same lines i.e. simulation and exporting metrics.

Let's have another issue to track this.
