### ISSUE TITLE
FIPS compliant Thanos Docker image 

### ISSUE THREAD

**Issue by infa-kparida** [thanos-io/thanos#3997]
### Is your proposal related to a problem?

Ye.FIPS 140-2 is a set of cryptographic standards that all  application may need to adhere to If you work with US government entities .We are setting up thanos for monitoring in some of the GovCloud environments and need thanos to be FIPS compliant. 

### Describe the solution you'd like

  Provide an docker image with FIPS encryption enabled

**Comment by GiedriusS** [comment]
Hi, could you please share on what are the exact requirements? For people outside of US, it might be hard to understand this. Is it something like https://github.com/arhea/docker-fips-library? Are there any test suites which would tell us whether a Docker image is FIPS compliant?

**Comment by conorevans** [comment]
+1 on this
