### ISSUE TITLE
Flaky test case metadata API fanout

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#4012]
**Thanos, Prometheus and Golang version used**:

**Object Storage Provider**:

**What happened**:

https://github.com/thanos-io/thanos/pull/4010/checks?check_run_id=2249690066#step:5:1828

Because the output string is too long, the error message is truncated so it is hard to know what's the diff.

**What you expected to happen**:

The result from Prometheus metadata API and Thanos querier metadata API should be the same.

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by yeya24** [comment]
Reproduced in my fork.

```
        Diff:
        --- Expected
        +++ Actual
        @@ -11,4 +11,4 @@
          (string) (len=23) "go_memstats_alloc_bytes": ([]metadatapb.Meta) (len=2) {
        -  (metadatapb.Meta) type:"gauge" help:"Number of bytes allocated and still in use." ,
        -  (metadatapb.Meta) type:"counter" help:"Total number of bytes allocated, even if freed." 
        +  (metadatapb.Meta) type:"counter" help:"Total number of bytes allocated, even if freed." ,
        +  (metadatapb.Meta) type:"gauge" help:"Number of bytes allocated and still in use." 
          },
```

Looks like the order is not deterministic.

**Comment by bwplotka** [comment]
Got another case: https://github.com/thanos-io/thanos/pull/3993/checks?check_run_id=2270461607#step:5:1100

**Comment by bwplotka** [comment]
Still got one https://github.com/thanos-io/thanos/pull/4039/checks?check_run_id=2306541486#step:5:2260 unless I failed to rebase properly 🤔

**Comment by yeya24** [comment]
I think this is fixed. New prs are not affected by this test case. Can we close this now?

**Comment by yeya24** [comment]
Marked this as resolved, closing now.
