### ISSUE TITLE
sidecar/compactor: make storing debug meta.json optional

### ISSUE THREAD

**Issue by asbjxrn** [thanos-io/thanos#402]
Every time sidecar or compactor uploads a block, a copy of the meta.json for the block is stored in debug/metas. These files are never deleted even when the block itself is deleted during compaction and build up over time. Some blobstores have a large minimum block size which can make the storage consumed by these files significant.

It would be nice if the storing of these files were optional.

**Comment by Bplotka** [comment]
Makes sense, although it is extremely useful to track down what happened in case of any issue (: So I would suggest having debug/metas `on` by default.

**Comment by jhaohai** [comment]
Can we archive the deleted blocks' metas into large metas?

**Comment by bwplotka** [comment]
Why bigger file is better that multiple smalls? Limit of number of files in object store?
