### ISSUE TITLE
Negative offset with flag --enable-feature=promql-negative-offset

### ISSUE THREAD

**Issue by vsile** [thanos-io/thanos#4022]
Prometheus v2.26.0 has the flag `--enable-feature=promql-negative-offset` to enable negative offset.
It works fine. 

But I can't enable it with Thanos 0.19.0.
It looks like the flag is not available for Thanos Query.
So the next query `my_metric_status offset -24h` fails with the error `1:31: parse error: unexpected <op:-> in offset, expected duration`

Is this feature implemented?

**Comment by yeya24** [comment]
No, it is not included in Thanos 0.19.0.
But as we use Prometheus as a library, this is easy to do.
Just add one more flag in querier to enable it. Help wanted.

**Comment by bwplotka** [comment]
Help wanted!

**Comment by bwplotka** [comment]
Discussion what's needed is here: https://github.com/thanos-io/thanos/pull/4026#discussion_r608204658 🤗

**Comment by vsile** [comment]
Hello!
I keep looking for a solution to enable negative offset in Thanos..

The [PR](https://github.com/thanos-io/thanos/pull/4026) of @yeya24 looks good.
It is unlikely that there will be many similar flags in Prometheus.
It would be fine to receive the PR in the current implementation.

**Comment by metonymic-smokey** [comment]
I was considering working on this issue. I had a few doubts:
1. An `--experimental` flag needs to be added. This will be like the `--enable-features` flag in Prom and will accept comma separated strings.
Should this flag be global or added to the Query component?
2. If the list of features in the `--experimental` flag contains negative offset and @ modifier, those will be enabled.
Is this what is expected?

Thanks!

**Comment by vsile** [comment]
I tested new version thanosio/thanos:main-2021-10-14-fa476b5f
It seems the negative offset still doesn't work.
![изображение](https://user-images.githubusercontent.com/9244347/137335310-da5834b0-8f75-40d1-8d4a-59e6ff894401.png)

Thanos is running successfully (no errors).

But query fails with the error "negative offset is disabled"

![изображение](https://user-images.githubusercontent.com/9244347/137337965-ad3a9c91-ded3-4298-a3d2-a5561f0787ce.png)
