### ISSUE TITLE
add the new promQL editor

### ISSUE THREAD

**Issue by Nexucis** [thanos-io/thanos#4028]
Hello,

a new PromQL editor has been added into the webapp of Prometheus in v2.26.

Do you think it would be a good idea to have it as well ? Also as an experimental editor ? Or directly as the main editor ?

**Comment by wiardvanrij** [comment]
Hi, 

This seems a logical step as the autocomplete feature is really neat!
Would you be interested in implementing this? 

For reference, this was a previous upgrade/update of the Thanos UI; https://github.com/thanos-io/thanos/pull/2412

**Comment by Nexucis** [comment]
yup I can do it :)
