### ISSUE TITLE
Print flags in sorted order when showing --help output

### ISSUE THREAD

**Issue by idoqo** [thanos-io/thanos#4034]
The output of `$component --help` (e.g., `rule --help`) doesn't seem to follow any pattern currently. It will help to make the output more deterministic, say by printing the supported arguments and flags in sorted order. 

For example, while working on #3993, I noticed that small changes to how flags get parsed resulted in huge diffs in the generated docs (which in turn is generated from the help output). Outputting sorted flags will:
- help ensure that changes in the generated docs are minimal when flags are moved around in the code.
- group related flags (for instance, flags starting with `--query.*` would end up being grouped together).

**Comment by bwplotka** [comment]
Help wanted. It would be helpful! 🤗

**Comment by wiardvanrij** [comment]
Can be closed :)
