### ISSUE TITLE
Thanos sidecar is unable to to write to AWS S3 storage

### ISSUE THREAD

**Issue by subrata83** [thanos-io/thanos#4060]
We are trying to deploy Thanos sidecar with Prometheus  in EKS using Prometheus-community/kube-prometheus-stack. AWS S3 has been used as backend storage

We have referred below documentation to deploy Thanos sidecar

https://aws.amazon.com/blogs/opensource/improving-ha-and-long-term-storage-for-prometheus-using-thanos-on-eks-with-s3/

Prometheus  deployed successfully and thanos sidecar is also running fine. But when when we look into logs , it says "Access denied" and hence files are not written to bucket

**Thanos, Prometheus and Golang version used**:
Prometheus:- v2.25.2
Thanos :- v0.17.2

**Object Storage Provider**:  AWS/S3

**What happened**: Thanos sidecar is not writing data to AWS/S3. Throwing error of access denied

**What you expected to happen**: Thanos  sidecar should write data to AWS S3

**How to reproduce it (as minimally and precisely as possible)**:

->
We are trying to deploy Thanos sidecar with Prometheus  in EKS using Prometheus-community/kube-prometheus-stack. AWS S3 has been used as backend storage

We have referred below documentation to deploy Thanos sidecar

https://aws.amazon.com/blogs/opensource/improving-ha-and-long-term-storage-for-prometheus-using-thanos-on-eks-with-s3/

Prometheus  deployed successfully and thanos sidecar is also running fine. But when when we look into logs , it says "Access denied" and hence files are not written to bucket

**Thanos, Prometheus and Golang version used**:
Prometheus:- v2.25.2
Thanos :- v0.17.2

**Object Storage Provider**:  AWS/S3

**What happened**: Thanos sidecar is not writing data to AWS/S3. Throwing error of access denied

**What you expected to happen**: Thanos  sidecar should write data to AWS S3

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an AWS EKS cluster
2. Create  S3 repository
3. Create a S# bucket policy to allow read/write access to bucket
4. Create a IAM service account with above policy
5. Create Object store config referring bucket created above
6. Deploy Prometheus with Thanos sidecar using Prometheus/kube-prometheus-stack
7. Check S3 bucket

**Full logs to relevant components**:

**Anything else we need to know**:

We are trying to deploy Thanos sidecar with Prometheus  in EKS using Prometheus-community/kube-prometheus-stack. AWS S3 has been used as backend storage

We have referred below documentation to deploy Thanos sidecar

https://aws.amazon.com/blogs/opensource/improving-ha-and-long-term-storage-for-prometheus-using-thanos-on-eks-with-s3/

Prometheus  deployed successfully and thanos sidecar is also running fine. But when when we look into logs , it says "Access denied" and hence files are not written to bucket
Steps to replicate are as follows
1. Create an AWS EKS cluster
2. Create  S3 repository
3. Create a S# bucket policy to allow read/write access to bucket
4. Create a IAM service account with above policy
5. Create Object store config referring bucket created above
6. Deploy Prometheus with Thanos sidecar using Prometheus/kube-prometheus-stack
7. Check S3 bucket

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by wiardvanrij** [comment]
The error indicates that there is a permission issue. I would recommend re-checking your IAM OICD provider, IAM policy, IAM role and the attached policy ARN. 
Please confirm that your pod is able to talk with S3 by having the appropriate access rights.

**Comment by subrata83** [comment]
Thanks all for your response . it started working after we removed encryptsse= true from S3 object config

**Comment by winem** [comment]
Just in case anyone comes across this issue: 

Removing the encryption means that the data put into the S3 bucket won't be encrypted on rest. The issue can also be fixed with the following Thanos configuration: 
```
type: s3
config:
  ...
  sse_config:
    type: SSE-S3
```
