### ISSUE TITLE
Broken links in the documentation

### ISSUE THREAD

**Issue by JanKerstens** [thanos-io/thanos#4063]
On page https://thanos.io/v0.1/thanos/getting-started.md/
there are many links broken. The link to github to propose changes doesn't work either.

E.g.  
https://thanos.io/v0.1/kube/manifests/thanos-query.yaml
https://thanos.io/v0.1/thanos/components/query.md

![image](https://user-images.githubusercontent.com/2088377/114839853-897a7c00-9dd6-11eb-9d6d-9875211ab0a2.png)

**Comment by wiardvanrij** [comment]
Thank you so much but we aim to fix this on all levels using #3081

Problem is that we aim for those links to work on both GH mardown level as well website ):
