### ISSUE TITLE
Flaky targets  API E2E test case 

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#4069]
Example failure https://github.com/thanos-io/thanos/runs/2352937384.

This problem sometimes can be found locally, but it is hard to reproduce it every time. More investigation is needed.

From what I can see so far, the program will be blocked in https://github.com/thanos-io/thanos/blob/main/test/e2e/targets_api_test.go#L114. The client waits for the response until context timeout.

**Comment by pracucci** [comment]
What if we temporarily skip the test, until we get back to fixing it? Looks like it's failing in most CI runs.

**Comment by yeya24** [comment]
Not sure if the issue still exists, maybe let's enable the test case another time?

**Comment by matej-g** [comment]
Let's do it :+1:  - https://github.com/thanos-io/thanos/pull/4819

**Comment by yeya24** [comment]
I don't think this is reproducible anymore so let's close.
