### ISSUE TITLE
Thanos doesn't support new function clamp() in Prometheus 2.26

### ISSUE THREAD

**Issue by liangli1213** [thanos-io/thanos#4071]
clamp() is a new function involved by Prometheus 2.26, but Thanos 0.19 doesn't support it, with below error:
`Error executing query: 1:1: parse error: unknown function with name "clamp"`

**Comment by yeya24** [comment]
This should be fixed by https://github.com/thanos-io/thanos/pull/4094.

**Comment by kakkoyun** [comment]
Fixed by #4094.
