### ISSUE TITLE
Receiver: Large quantity of 409 conflict rejection after network fluctuation

### ISSUE THREAD

**Issue by ethernoy** [thanos-io/thanos#4077]
**Thanos, Prometheus and Golang version used**:

Thanos: Bitnami 0.18.0 scratch r5
Prometheus: Bitnami 2.26.0

**Object Storage Provider**:

MinIO (on-prem)

**What happened**:

![image](https://user-images.githubusercontent.com/15870761/115221774-98499180-a13c-11eb-9c4f-dd6702eb38b9.png)

I configured a thanos deployment similar to the diagram above. It works smoothly at the beginning. However, when the connection between one of the app cluster to management cluster become unstable for 5-10 min (remote write cannot reach receive for several minutes), the response time of thanos receiver service increases from ms level to s level (5-10s) and keeps for around 30min. 

During this period:
- The prometheus in the related app cluster receives a large number of 409 conflict response
- Thanos receiver produces many similar logs: "Error on ingesting out-of-order samples" in this period

**What you expected to happen**:

Prometheus is able to write to Thanos receiver even data is old

**How to reproduce it (as minimally and precisely as possible)**:

Disrupt network between remote Prometheus and Thanos for a while, then resume.

**Full logs to relevant components**:

Duplicated "Error on ingesting out-of-order samples", it should be meanless to post all of them?

**Anything else we need to know**:

Can you briefly explain what is behind the "Error on ingesting out-of-order samples" error?

**Comment by Kampe** [comment]
See the same thing, this was at a time, a limitation of prometheus itself.  With the introduction of being able to backfill data this can now be a reality.  I do wish this becomes a feature of Thanos.

**Comment by ethernoy** [comment]
I did some research on the log and related source code, found that the out-of-order error was thrown because the prometheus-replica-label was not correctly configured on app-cluster, resulted in samples with the same label but different timestamp being generated in different Prometheus and remote written to Thanos receive.

**Comment by wiardvanrij** [comment]
> I did some research on the log and related source code, found that the out-of-order error was thrown because the prometheus-replica-label was not correctly configured on app-cluster, resulted in samples with the same label but different timestamp being generated in different Prometheus and remote written to Thanos receive.

Would this have prevented your issue? I.e. is there still something we should investigate/sort out here? 
Also, thanks so much for the clear issue & diagram 🙌  

> Can you briefly explain what is behind the "Error on ingesting out-of-order samples" error?
I'll cross-post this in Slack so someone could give some input here.

**Comment by ethernoy** [comment]
> Would this have prevented your issue? I.e. is there still something we should investigate/sort out here?

Yes, I believe this have prevented my "out-of-order" issue, because the metric label is no longer duplicated between metrics from different app prometheus. However, I can still encounter "409 out-of-bound" issue from time to time, it should be related to insufficient resources of Thanos Receiver (it cannot ingest metrics as fast as Prometheus produces them).

> I'll cross-post this in Slack so someone could give some input here.

Thank you. I think it would be clearer if the documentation includes a section about the common error Thanos may produce and how to solve them. Let me know if I can help :) Glad to contribute.

**Comment by wiardvanrij** [comment]
Definitely, feel free to make a PR towards: https://thanos.io/tip/operating/troubleshooting.md/ with perhaps this information about receive and hopefully some more deeper information about the out-of-order error

**Comment by bwplotka** [comment]
> Can you briefly explain what is behind the "Error on ingesting out-of-order samples" error?

This happens if you have samples coming out-of order. So remote write sends us a sample for timestamp 1 for series A, then with time 2 for series A, then if we got sample from series A with time 1  now, it will error with out-of-order problem. (:

**Comment by ethernoy** [comment]
> Definitely, feel free to make a PR towards: https://thanos.io/tip/operating/troubleshooting.md/ with perhaps this information about receive and hopefully some more deeper information about the out-of-order error

Sure, I will consolidate my observation and the related solution to that page :)

**Comment by wiardvanrij** [comment]
Aweomse, thanks!
