### ISSUE TITLE
Thanos panic due to go-grpc-middleware logging

### ISSUE THREAD

**Issue by Wander1024** [thanos-io/thanos#4080]
**Thanos, Prometheus and Golang version used**:
Thanos: 0.15.0
Prometheus 2.19.2
golang 1.15.5

**Object Storage Provider**:

**What happened**:
Thanos-Receive panic due to go-grpc-middleware  call the abnormal Error() in interceptor.

**What you expected to happen**:
fix this issue.

**How to reproduce it (as minimally and precisely as possible)**:
it's hard to reproduce. 

**Full logs to relevant components**:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x767b2b]

goroutine 48441409129 [running]:

github.com/pkg/errors.(*withStack).Error(0x0, 0x24efb88, 0x5)
        <autogenerated>:1 +0x2b
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.finishServerSpan(0x2a58980, 0xc41e49a6f0, 0x2a8e960, 0x3f7bc20, 0x29f9d00, 0x0)

        /app/vendor/github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing/server_interceptors.go:85 +0x3de
github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.StreamServerInterceptor.func1(0x2362040, 0xc38e362160, 0x2a72200, 0xcb80dd94a0, 0xcb80dd9400, 0xcb80dd9420, 0x2a58980, 0xc41e49a6c0)

        /app/vendor/github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing/server_interceptors.go:48 +0x18a
github.com/thanos-io/thanos/pkg/tracing.StreamServerInterceptor.func1(0x2362040, 0xc38e362160, 0x2a72320, 0xcb80dd9480, 0xcb80dd9400, 0xcb80dd9420, 0x29b4a79, 0x0)

        /app/pkg/tracing/grpc.go:42 +0x134
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1(0x2362040, 0xc38e362160, 0x2a72320, 0xcb80dd9480, 0x14, 0xc994ef1180)

        /app/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:49 +0x5f
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).StreamServerInterceptor.func1(0x2362040, 0xc38e362160, 0x2a72680, 0xc3aba79140, 0xcb80dd9400, 0xcb80dd9440, 0xcb80dd9460, 0xcb80dd9400)

        /app/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go:121 +0xeb
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1(0x2362040, 0xc38e362160, 0x2a72680, 0xc3aba79140, 0xca5f92ac68, 0x40cf58)

        /app/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:49 +0x5f
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1(0x2362040, 0xc38e362160, 0x2a72680, 0xc3aba79140, 0xcb80dd9400, 0x2609c68, 0x2a58980, 0xc41e49a660)

        /app/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:58 +0xcf
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0c972b6c0, 0x2a83ba0, 0xd0f7b07500, 0xc3c966aa00, 0xc3821b19b0, 0x3f19120, 0x0, 0x0, 0x0)
        /app/vendor/google.golang.org/grpc/server.go:1336 +0x511

google.golang.org/grpc.(*Server).handleStream(0xc0c972b6c0, 0x2a83ba0, 0xd0f7b07500, 0xc3c966aa00, 0x0)
        /app/vendor/google.golang.org/grpc/server.go:1409 +0xc66

google.golang.org/grpc.(*Server).serveStreams.func1.1(0xd8a9c8b6f0, 0xc0c972b6c0, 0x2a83ba0, 0xd0f7b07500, 0xc3c966aa00)
        /app/vendor/google.golang.org/grpc/server.go:746 +0xa1

created by google.golang.org/grpc.(*Server).serveStreams.func1
        /app/vendor/google.golang.org/grpc/server.go:744 +0xa1
```

**Anything else we need to know**:

**Comment by Wander1024** [comment]
it likes memory corruption.
I already added the `debug.SetPanicOnFault(true)`. it triggered the panic, but seems `grpcPanicRecoveryHandler` are not working.

**Comment by kakkoyun** [comment]
Thanks for reporting.
@yashrsharma44 Any ideas around this?

**Comment by Wander1024** [comment]
it likes memory corruption.
I added the `debug.SetPanicOnFault(true)` in 0.15.0.
`go-grpc-middleware` might triggered the `memory corruption` and raised panic

**Comment by Wander1024** [comment]
Seems the go-grpc-middleware `ChainStreamServer` func has a issue.
there are 3 funcs `F1, F2,F3`.  F3 function is used to recover panic.
these funcs execution is `F1-F2-F3` order in `ChainStreamServer` func.
But if F2 raise panic, F3 can't to catch it. we need using F1 to catch it.


maybe it need to change `[]grpc.ServerOption` list order like
```
grpcOpts := []grpc.ServerOption{
  grpc.MaxSendMsgSize(math.MaxInt32),
  grpc_middleware.WithUnaryServerChain(
	  grpc_recovery.UnaryServerInterceptor(grpc_recovery.WithRecoveryHandler(grpcPanicRecoveryHandler)),
	  met.UnaryServerInterceptor(),
	  tracing.UnaryServerInterceptor(tracer),
  ),
  grpc_middleware.WithStreamServerChain(
	  grpc_recovery.StreamServerInterceptor(grpc_recovery.WithRecoveryHandler(grpcPanicRecoveryHandler)),
	  met.StreamServerInterceptor(),
	  tracing.StreamServerInterceptor(tracer),
  ),
}

```

**Comment by yashrsharma44** [comment]
Thanks for debugging the issue!
It seems like the behaviour of `grpc_middleware.WithUnaryServerChain` and `grpc_middleware.WithStreamServerChain` has been changed, due to which the original ordering of functions have changed. Earlier, it used to be in the reverse order, something like `F3 would propagate error from F2 and F1`, but now with this [PR](https://github.com/grpc-ecosystem/go-grpc-middleware/pull/385) we are using [`grpc-go` ordering](https://github.com/grpc/grpc-go/commit/d0235e4d6be307de7d197d94248f678a414cb864) which is `F1 would handle the error for F2 and F3`, which seems to have freaked the ordering. 

Let me make a PR to address the ordering if that makes sense.

**Comment by wiardvanrij** [comment]
Thanks so much for this issue and the follow up PR! As I believe this is now fixed and merged, i'll close this issue 🎉
