### ISSUE TITLE
Thanos Receivers Auto Scale

### ISSUE THREAD

**Issue by heartTorres** [thanos-io/thanos#4092]
**Thanos, Prometheus and Golang version used**:
 Rancher prometheus v2.18.2
 Thanos v0.15
 AWS s3

**What happened**:
We are using Thanos Receivers in our clusters with around 1200 nodes and these nodes are still keep on increasing.
We manually increase the replicas of pods Thanos Receivers as well the config whenever it gets OOMKilled as the node counts of the cluster increases.

We are thinking to do the auto scale in automatically the Thanos Receivers pods but we are caught on some problems:
1.   We need to fire up nodes on odd numbers 3,5,7 due to quorum. (this can be done via autoscaling group)
2.  We need to update the hash ring config to add the newly added receivers (nodes) 

Currently, we are doing this manually in our infra, whenever an alarm is hit and we would like to automate this task.

Hope someone can give me some light

**Comment by squat** [comment]
Hi @heartTorres please take a look at the Thanos Receive Controller. We built this and use it internally at red hat to automatically generate the configmap for our thanos receiver statefulsets: https://github.com/observatorium/thanos-receive-controller

**Comment by heartTorres** [comment]
Oh. Alright. I will take a look at this and try this out on our cluster. Thank you for this info. @squat

**Comment by wiardvanrij** [comment]
> Oh. Alright. I will take a look at this and try this out on our cluster. Thank you for this info. @squat

Closing for now, let us know if we could improve somewhere or if you have more questions!

**Comment by Hackmeat** [comment]
i have a question for those who use the receive-controller. How do you change the namespace which he is checking? the logs are showing that the controller is searching the default namespace, not the one where he is deployed in
