### ISSUE TITLE
Why does Thanos save data bigger than Prometheus and can not be displayed with Grafana?

### ISSUE THREAD

**Issue by btdan** [thanos-io/thanos#4097]
Hi, I am new to Thanos and have some question to solve. Can somebody be kind enough to help me?
**[Problem Description]**
Thanos can receive from Prometheus with remote write. But the data saved by Thanos receiver is much bigger than that saved by Prometheus on local disk for the same time period.
Grafana can not display data from Thanos query meanwhile can display the data from Prometheus.

**[Description in detail]**
At first, I have installed Prometheus and it runs very well. The data saved by Prometheus on local disk can be displayed by Grafana. The data source of Grafana is set as:
http://127.0.0.1:9090
and The remote write section in Prometheus config file is as follows:
remote_write:
- url: http:// 127.0.0.1:10908/api/v1/receive

Secondly, I start Thanos receive with the command as follows:
thanos receive \
    --tsdb.path "/metricsData" \
    --grpc-address 0.0.0.0:10907 \
    --http-address 0.0.0.0:10909 \
    --receive.replication-factor 1 \
    --label "receive_replica=\"0\"" \
    --label "receive_cluster=\"eu1\"" \
    --receive.local-endpoint 127.0.0.1:10907 \
    --receive.hashrings-file /hashring.json \
    --remote-write.address 0.0.0.0:10908 \
    --objstore.config-file "/bucket.yml"

And Thanos can receive data from Prometheus. But the data is much bigger than saved by Prometheus on local disk. That is to say, the data saved by Prometheus is about 1.9MB, and meanwhile the data collected and saved by Thanos receiver is about 31.8MB. It is much bigger.
Both of the data is for the same time period. 

I start Thanos query as ：
thanos query --http-address 0.0.0.0:19192 --store 127.0.0.1:10907

After I set the data source of Grafana as Thanos with the parameter:
127.0.0.1:19192
The data saved by Thanos can not be displayed by Grafana successfully. There is nothing to display.
And the tip from Thanos receive is :

level=info ts=2021-04-23T06:03:36.283803736Z caller=handler.go:330 component=receive component=receive-handler msg="empty timeseries from client" tenant=default-tenant

So I do not know how to solve this problem. Can somebody help me ?
Thanks very much.
Best wishes.

**Comment by yeya24** [comment]
Sorry for the late reply.

`level=info ts=2021-04-23T06:03:36.283803736Z caller=handler.go:330 component=receive component=receive-handler msg="empty timeseries from client" tenant=default-tenant` 

This log is normal but a little bit misleading. Prometheus server is remote writing some metadata to your Thanos receiver, not samples.

I am not sure about the data size problem. Are you still seeing the same behavior? What thanos version are you using?
