### ISSUE TITLE
thanos Can't find historical data

### ISSUE THREAD

**Issue by xufei56789** [thanos-io/thanos#4098]
### Problem Description：
1. thanos Can't find historical data
2. Complete data in the s3 bucket
3.   query output error log :    err="No StoreAPIs matched for this query" 
### Start method：
store： store --data-dir /data/thanos/store --objstore.config-file /data/bucket_config.yaml --http-address 0.0.0.0:10906 --grpc-address 0.0.0.0:10905
query：query --http-address 0.0.0.0:10904 --grpc-address 0.0.0.0:10903  --store 0.0.0.0:10905

**Comment by wiardvanrij** [comment]
Hi, please check the UI on the query component and check -> stores. You'll see which stores are exposed (and with what labels). 

Could you provide more information? 

- How your data looks like (i.e screenshot of query component store page)
- Configuration settings
- Versions used
- How we could reproduce this problem

**Comment by yeya24** [comment]
If your data is old, you need to use range query in your thanos query UI and make sure the selected time range and downsampling param is correct.

I will close this issue and feel free to reopen it if it is not solved.
