### ISSUE TITLE
How to start mutil endpoint?

### ISSUE THREAD

**Issue by btdan** [thanos-io/thanos#4099]
[Problem Description]
How to start mutil endpoint in one system or several system?

[Description in detail]
I read this document  with url   https://thanos.io/v0.18/components/receive.md/
And copy the same hashring.json as my own config.
That is to say, the content of hashring.json:
_[
    {
        "endpoints": [
            "127.0.0.1:10907",
            "127.0.0.1:11907",
            "127.0.0.1:12907"
        ]
    }
]_

I start thanos receiver successfully with the command as follows:
_thanos receive \
    --tsdb.path "/metricsData" \
    --grpc-address 0.0.0.0:10907 \
    --http-address 0.0.0.0:10909 \
    --receive.replication-factor 1 \
    --label "receive_replica=\"0\"" \
    --label "receive_cluster=\"eu1\"" \
    --receive.local-endpoint 127.0.0.1:10907 \
    --receive.hashrings-file /hashring.json \
    --remote-write.address 0.0.0.0:10908 \
    --objstore.config-file "/bucket.yml"_

After start Thanos receive and Prometheus.
I get the tip as follows:

ts=2021-04-23T08:56:06.945Z caller=dedupe.go:112 component=remote level=warn remote_name=026329 url=http://127.0.0.1:10908/api/v1/receive msg="Failed to send batch, retrying" err="server returned HTTP status 503 Service Unavailable:
2 errors: backing off forward request for endpoint 127.0.0.1:12907: target not available; forwarding request to endpoint 127.0.0.1:11907: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial
 tcp 127.0.0.1:11907: connect: connection refused\""

From the tip above, I think that means there are no endpoint 127.0.0.1:11907 and 127.0.0.1:12907.
I try to start as follows:
_thanos receive \
    --tsdb.path "/metricsData" \
    --grpc-address 0.0.0.0:10907 \
    --http-address 0.0.0.0:10909 \
    --receive.replication-factor 1 \
    --label "receive_replica=\"0\"" \
    --label "receive_cluster=\"eu1\"" \
    --receive.local-endpoint 127.0.0.1:**11907** \
    --receive.hashrings-file /hashring.json \
    --remote-write.address 0.0.0.0:10908 \
    --objstore.config-file "/bucket.yml"_

I only change the local-endpoint 10907 to 11907
But it exit with error. Can somebody be kind enough to tell me how to solve this problem?
Thanks very much.

**Comment by wiardvanrij** [comment]
The hashring endpoints consists of a list of receive components you have running. 
Change the config to:

```
[
    {
        "endpoints": [
            "127.0.0.1:11907",
        ]
    }
]
```
As this is the only instance you are running. Or add more receivers and add their endpoints to the hashring config.
