### ISSUE TITLE
thanos: Expose Thanos APIs to OpenAPI/protobuf and expose on website and UIs

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#4102]
In order to improve Thanos usage for users, we would like to define our APIs both HTTP and gRPC in protobuf/OpenAPI and expose those in the website. This would allow users to use tools for documentation, validation, type checking and even code generation to use our APIs efficiently. During this, we also expect collaboration with the Prometheus project to be similar on Prometheus' side. https://github.com/cncf/mentoring/blob/master/summerofcode/2021.md#port-the-prometheus-api-to-openapi. 

### Acceptance Criteria:

* Define all APIs in protobuf (for consistency). 
* Use protobuf to generate code to use on our server.
* Be able to generate OpenAPI from protobuf.
* Define all configuration potentially in protobuf too: https://github.com/openproto/protoconfig
* Optionally we would like to have on the index page on every Thanos component server.

**Comment by NBNARADHYA** [comment]
Hey guys 🙋‍♂️, I'm Nikhil.

I saw this project on the LFX projects and it needs a mentee for the project. I have applied for this project on the LFX Mentorship website and I would love to work on this ! 😃

**Comment by bwplotka** [comment]
Asked for some feedback on `buf` Slack: https://bufbuild.slack.com/archives/CRZ680FUH/p1622737333123900
