### ISSUE TITLE
Sidecar S3 bucket Access Denied with full IAM s3 access 

### ISSUE THREAD

**Issue by vbabitskiy** [thanos-io/thanos#4103]
**Thanos, Prometheus and Golang version used**:

Prometheus: **2.26.0**
Thanos: **0.19.0**

**Object Storage Provider**: **s3**

**What happened**:

Thanos sidecar container is not able to upload debug meta file to S3.

**What you expected to happen**:

Metafile uploaded to S3

**How to reproduce it (as minimally and precisely as possible)**:

Thanos objectstore config:
```
type: S3
config:
  bucket: thanos_s3_bucket
  endpoint: thanos_bucket_endpoint
  signature_version2: false
```
Thanos uses IAM credentials retrieved from an instance profile.
IAM profile has full access to S3
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": "*"
        }
    ]
}
```

There is no problem if IAM role has ADMIN access to AWS:
e.g.
```{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}
```

**Full logs to relevant components**:

<details>Logs
<p>

```
{"caller":"shipper.go:337","id":"01F4029SF12WKX9MDT5SDG56PN","level":"info","msg":"upload new block","ts":"2021-04-23T20:41:18.90804455Z"}
{"caller":"sidecar.go:277","err":"upload 01F4029SF12WKX9MDT5SDG56PN: upload debug meta file: upload s3 object: Access Denied","level":"warn","ts":"2021-04-23T20:41:19.518267218Z","uploaded":0}
```

</p>
</details>

**Anything else we need to know**:

**Environment**:
- OS Ubuntu: **18.04**
- Docker: **20.10.6**
- Kernel: **5.4.0-1038-aws**

**Comment by wiardvanrij** [comment]
I think this works because the 'admin' role allows access to the KMSAccess part of your account.

Check out: https://thanos.io/tip/thanos/storage.md/#s3 -> S3 Server-Side Encryption

I think there are two ways here; either add a policy to the role/user or make some general rule/setting on how to deal with server-side encryption that allows a s3 user to to the encrypt en decrypt parts.

A bit rusty here, as it's been a while since I configured this on AWS :)

**Comment by vbabitskiy** [comment]
Hello @wiardvanrij 
Yes, you were right. The S3 bucket had an unclear Server-Side Encryption configuration.
I updated the S3 encryption configuration and the IAM policy with required KMS actions and it works now.

Thank you for pointing me in the right direction.
Close the question.
