### ISSUE TITLE
0.20.0.rc-0 query: --target - Querier OOM when having circular reference ?

### ISSUE THREAD

**Issue by ahurtaud** [thanos-io/thanos#4106]
**Thanos, Prometheus and Golang version used**:
thanos v0.20.0-rc0
prometheus v2.26.0

**What happened**:
I tried the new experimental `--target` flag to get the aggregated targets view on querier.
I am using the same service as store (which contains Sidecars + Store + Rulers)
```
        - --store=dns+thanos-query-main-store-api.argos-qa.svc:10901
        - --target=dns+thanos-query-main-store-api.argos-qa.svc:10901
```
The page loaded indefinitely until an OOM on the querier.
After Investigation, I suspect the thanos ruler (discovered in my target flag) to do a circular reference leading to infinite number of calls to sidecar.
When scaling the ruler to zero (and waiting for the querier to remove the ruler endpoints), everything works instantly.

**What you expected to happen**:
[To be confirmed]: Thanos ruler should not redirect targets Services to the registered queriers ?

**How to reproduce it (as minimally and precisely as possible)**:
- Start a querier with 1sidecar/1prometheus
- Start 1 ruler which target the querier
- Set the querier --target flag to "sidecar + ruler"

**Anything else we need to know**:
[Slack discussion](https://cloud-native.slack.com/archives/CL25937SP/p1619190579189000)
- I think this is a common setup in kubernetes with the dns+ discovery of all components providing a storeAPI (gRPC) service. (Getting all Sidecar/Store/Ruler components in the same kubernetes service)

Heap while the targets were infinitely loading (before OOM at 10GiB). This querier is empty normally (200MiB usage).
[heap.pdf](https://github.com/thanos-io/thanos/files/6375574/heap.pdf)

**Comment by ahurtaud** [comment]
I wrote a quick step-by-step script to reproduce.
Please take care when executing commands on your localdev as some can have side-effect.
The goal is to have an helper to reproduce, please understand all the commands you type:
```bash
# Put in your PATH prometheus v2.26.0 and thanos 0.20.0.rc-0

# Write very simple prometheus.yml file
cat > /tmp/4106-prometheus.yml <<EOF
global:
  scrape_interval: 5s
  external_labels:
    monitor: 'prometheus1'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
EOF

# Start components but not the Ruler yet
prometheus --config.file=/tmp/4106-prometheus.yml > /dev/null 2>&1 &
thanos sidecar > /dev/null 2>&1 &
thanos query --store=localhost:10901 --store=localhost:10903 --target=localhost:10901 --target=localhost:10903 --http-address="0.0.0.0:8080" --grpc-address="0.0.0.0:50000" > /dev/null 2>&1 &

# Open http://localhost:8080/targets -> it works fine

# Start the ruler component (already registered in the querier)
thanos rule --http-address="0.0.0.0:8081" --grpc-address="0.0.0.0:10903" --query="localhost:8080" --data-dir="rulerdata/" > /dev/null 2>&1 &

# Reopen # Open http://localhost:8080/targets -> it failed in infinite load. And querier is eating all your memory!

#Clean all components
killall prometheus thanos # Take care here if you have already some processes running
# Somehow on my local thanos query is not killed??
ps aux | grep thanos
# kill -9 <remaining PIDs

# remove prometheus config created above
rm /tmp/4106-prometheus.yml
```

**Comment by yeya24** [comment]
I think it is more like a configuration problem. By design, targets API only supports Sidecar so you should only add Sidecar endpoints to the `--target` flag.
If you include other stores like ruler or store gateway, querier will recognize them as Targets API implementers as well and send gRPC requests to them.  I don't think there is a good solution for it now except checking the store types by hardcoding.  But we have one proposal https://thanos.io/tip/proposals/202101_endpoint_discovery.md/ and I think this can be easily solved once that is done.

**Comment by ahurtaud** [comment]
yeah ok, it would means we have to create a new service for sidecars only :/

**Comment by yeya24** [comment]
> yeah ok, it would means we have to create a new service for sidecars only :/

Do you have a svc for Prometheus? Add the sidecar port to it would be fine.

**Comment by ahurtaud** [comment]
We don't have service for our prometheus no (functionally sharded, we have ~10+ prometheus per cluster).
We have 1 service for the storeAPI (Sidecar + Rule + Store) that we use for Query `--store`.
Anyway I am fine for closing it, if it is how it should be.
