### ISSUE TITLE
Store: the memory don't release after store load the data

### ISSUE THREAD

**Issue by SundayCloud** [thanos-io/thanos#4119]
**Thanos, Prometheus and Golang version used**:
thanos: 0.19

**Object Storage Provider**:

**What happened**:

when we query the latest 30 days data, we find store node has a memory increase, for example 52% , but after serval hours , the store don't release the memory, still 52% , I think it is a big problem
**What you expected to happen**:
I expect that the memory will be released some time after the query has ended

**How to reproduce it (as minimally and precisely as possible)**:
query the latest 30 days data
**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by wiardvanrij** [comment]
Hi, could you perhaps include pprof profiles and share them. Ideally via https://share.polarsignals.com/ ? 
I personally have not experienced the case you describe in our store component. Also I'm curious what caching options you use. If in-memory cache is used, it's going to be FIFO.. which sort of explains it. 
Could you also share more configuration details?
