### ISSUE TITLE
Alert relabelling for Thanos Rule

### ISSUE THREAD

**Issue by trutty** [thanos-io/thanos#4122]
### Is your proposal related to a problem?

Prometheus has a powerful alert relabelling feature to dynamically rewrite the label set of an alert before sending it to an Alertmanager. See 
- https://prometheus.io/docs/prometheus/latest/configuration/configuration/#alert_relabel_configs
- https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config

Thanos Rule is currently missing this feature, so a migration from Prometheus is not possible without loosing functionality. 

The idea to have alert relabelling was proposed some time ago with https://github.com/thanos-io/thanos/issues/660.

### Describe the solution you'd like

Thanos Rule could implement the same functionality as Prometheus and supply a command line flag to provide the YAML configuration. As far as I see it, most of the source code is reusable with https://github.com/prometheus/prometheus/tree/main/pkg/relabel.

### Describe alternatives you've considered

none

### Additional context

I could provide a PR which would implement the feature.

**Comment by yeya24** [comment]
Yeah, it would be good to have this feature. If you have a pr already please go ahead! Thanks.
