### ISSUE TITLE
Add metric around failed Store endpoints from Query node

### ISSUE THREAD

**Issue by dgrizzanti** [thanos-io/thanos#4124]
### Is your proposal related to a problem?

We have a use case where we'd like to alert/monitor on Store instances that a given Query node can't reach (either because it went down, has a network failure, etc). I see entries in the log for these failures but no metrics that represent that. I noticed there is a metric for DNS lookups though so maybe this could be an easy extension to that?

Example log statement I am referring to

```
 level=warn ts=2021-04-29T21:03:20.75684565Z caller=storeset.go:458 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from test.net:10901: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=test.net:10901
```

### Describe the solution you'd like

A metric available at `/metrics` that shows a `up` style metric whether this endpoint can be reached or not

### Additional context

Happy to work on this if someone could point me in the right direction. Thanks!

**Comment by wiardvanrij** [comment]
This was discussed during some meetings, so I think this is something which can be useful for more people.

**Comment by dgrizzanti** [comment]
Ok, not knowing the inner workings that well, my thought was to mark the store endpoint "up" on first connection (when it successfully is added to the store list) and flip it 0 when it gets removed. In my log example, that store endpoint doesn't show up on the stores page anymore.

I think I'm ok ignoring cases of network blips where a single or handful of queries fail. The grpc metrics should handle that I believe.

**Comment by karlism** [comment]
Just linking it here: https://github.com/thanos-io/thanos/issues/3014

**Comment by dgrizzanti** [comment]
Opened a draft PR for this #4169 if folks can take look and give me feedback. Thanks!
