### ISSUE TITLE
Block Viewer: --web.route-prefix flag inconsistent/unexpected redirects

### ISSUE THREAD

**Issue by lorenzo-biava** [thanos-io/thanos#4128]
**Thanos, Prometheus and Golang version used**:

Thanos v0.20.0

**Object Storage Provider**:
Not relevant

**What happened**:
Trying to reach the bucketweb tool from a reverse proxy. Setup as following (which works fine with the query component):
- `--web.external-prefix=thanos/bucketweb/`
- `--web.route-prefix=/`

while the reverse proxy (Ambassador) is using:
```
      prefix: /thanos/bucketweb/
      rewrite: /
```

If I hit:
- `/thanos/bucketweb/blocks` works fine
- `/thanos/bucketweb/api/v1/blocks` works fine
- `/thanos/bucketweb/` redirects to `/thanos/bucketweb` and it breaks

Other combination of those parameters create a whole lot of funky behaviors.

**What you expected to happen**:

Hitting `/thanos/bucketweb/` redirects to `/thanos/bucketweb/blocks`.

**How to reproduce it (as minimally and precisely as possible)**:

See before.

**Full logs to relevant components**:

**Anything else we need to know**:

Looks like the redirect is just missing `/blocks` [here](https://github.com/thanos-io/thanos/blob/main/cmd/thanos/tools_bucket.go#L364), comparing that with [Query](https://github.com/thanos-io/thanos/blob/main/cmd/thanos/query.go#L548)

This behavior was introduced by https://github.com/thanos-io/thanos/pull/3690

**Comment by wiardvanrij** [comment]
Thanks for the report. I haven't tried to reproduce it, but seems like a logical bug which should be squashed! :)

**Comment by onprem** [comment]
I tried reproducing it and looks like it affects all UI components regardless of `--web.route-prefix`. Looks like it's an artifact of switching to the new UI as default. I'll take a look at this.

**Comment by onprem** [comment]
This got fixed recently and we have a new Thanos release v0.20.2 out with the fix. :)
