### ISSUE TITLE
Add tracing for federated exemplar API

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#4130]
### Describe the solution you'd like

Instrument tracing spans for the federated APIs. This should include the proxy (querier) side as well as the leaf store sides.

**Comment by Hangzhi** [comment]
May I work on this?

**Comment by yeya24** [comment]
Sure, feel free to take it. @Hangzhi

**Comment by ianbillett** [comment]
Hey @Hangzhi :wave: - are you working on this? I can't see any active branches or forks. If not - I'm happy to take this on.

**Comment by Hangzhi** [comment]
@ianbillett Please take this on! Sorry for leaving this inactive.
