### ISSUE TITLE
Support optional query stats parameter

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#4170]
### Is your proposal related to a problem?

(Write your answer here.)

Prometheus instant query and range query APIs support an optional stats field to return the timing stats of the executed query.

Thanos should implement the same functionality. For implementation, please check the code in Prometheus:
https://github.com/prometheus/prometheus/blob/main/web/api/v1/api.go#L466-L470
https://github.com/prometheus/prometheus/blob/main/web/api/v1/api.go#L387-L391

### Describe the solution you'd like

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by ranulf10** [comment]
@Aser <transferencia ``
