### ISSUE TITLE
thanos_store_nodes_grpc_connections goes absent on unhealthy store.

### ISSUE THREAD

**Issue by OGKevin** [thanos-io/thanos#4177]
**Thanos, Prometheus and Golang version used**:
Thanos: v0.17.2 (checked master code and it's still there)

**What happened**:
Have a chained query: q1 --> q2. You will see a metric `thanos_store_nodes_grpc_connections` with the appropriate external labels for q2 at pov of q1. Kill q2, and the metric with the external label of q2 goes absent at pov of q1.

**What you expected to happen**:
The metric to not go absent but rather go to 0. As the help message indicates: 
```
# HELP thanos_store_nodes_grpc_connections Number of gRPC connection to Store APIs. Opened connection means healthy store APIs available for Querier.
# TYPE thanos_store_nodes_grpc_connections gauge
```

**How to reproduce it (as minimally and precisely as possible)**:
Explained above.

**Code hints**
https://github.com/thanos-io/thanos/blob/de700f3d3ae24cfa83084d20a99d991cf1b6d9ff/pkg/query/storeset.go#L348-L359
https://github.com/thanos-io/thanos/blob/de700f3d3ae24cfa83084d20a99d991cf1b6d9ff/pkg/query/storeset.go#L152-L153

**Comment by wiardvanrij** [comment]
Would this issue (and PR) resolve your problem? https://github.com/thanos-io/thanos/issues/4124

**Comment by OGKevin** [comment]
@wiardvanrij yes, i made some review comments on the PR 👍🏾

**Comment by OGKevin** [comment]
Comment with some additional explanation: https://github.com/thanos-io/thanos/pull/4169#issuecomment-839574599

**Comment by bwplotka** [comment]
Agree, thanks for doing, looks like we are finally on the same page (:
