### ISSUE TITLE
bucket inspect: support machine-readable output formats

### ISSUE THREAD

**Issue by matthiasr** [thanos-io/thanos#4180]
### Is your proposal related to a problem?

When I want to do an action on a specific subset of blocks, I need a list of those blocks.
`thanos tools bucket ls` gives me a list of *all* buckets, but does not allow filtering.
`thanos tools bucket inspect` does exactly the filtering it needs, but the output is geared towards human readability.
I need to do `awk` gymnastics to extract the block ID.

### Describe the solution you'd like

Add a `--output` / `-o` flag to `thanos tools bucket inspect`, which allows selecting output formats.
Ideas for formats:

* `table`: current format, default
* `id`: block IDs only, similar to `ls`
* `csv`: quoted comma-separated values
* `tsv`: tab-separated values, great for consumption with Unix tools
* `json`: JSON encoding (exact format tbd), great for consumption with `jq` or scripting languages

### Describe alternatives you've considered

* Currently possible:
```
thanos tools bucket inspect … | awk '$1 == "|" && $2 != "ULID" { print $2 }'
```
* add label filtering to `bucket ls` – solves my concrete issue, but is less generally useful. Making all the information machine readable allows all kinds of integrations. Harder to judge whether the filter is correct.

### Additional context

I chose the proposed flag to be in line with `kubectl`s multiple outputs.
I don't think Thanos needs the full power of that just yet but keeping the flags similar makes them easier to remember.

**Comment by wiardvanrij** [comment]
Well explained and I think this would provide good value. Would you be interested on creating this feature or an initial draft for it?

**Comment by matthiasr** [comment]
Unfortunately I won't have the time anytime soon, but I wanted to put the idea out there 😃

**Comment by someshkoli** [comment]
Created an initial draft for this, PTAL @wiardvanrij  @matthiasr

**Comment by wiardvanrij** [comment]
PR still open, relevant
