### ISSUE TITLE
PromQL editor is crashing after going to the next line and pressing multiple space

### ISSUE THREAD

**Issue by Nexucis** [thanos-io/thanos#4184]
**Thanos, Prometheus and Golang version used**:
Thanos: v0.20.0

**What happened**:
I started to type an expression then go to the next line and press multiple times space. The PromQL editor is crashing as you can see below in the gif.

![bug_thanos](https://user-images.githubusercontent.com/4548045/117157607-02aa3500-adbf-11eb-8e9c-9e52e806daf5.gif)

**What you expected to happen**:
The PromQL editor doesn't crash

I compared today the code between Prometheus and Thanos regarding this specific topic and I didn't find what is the diff that would cause that.
It's working fine in Prometheus.

**Comment by squat** [comment]
Hi @Nexucis, thanks for reporting this bug. Do you have the experimental editor checkbox enabled in prometheus as well? Also, what version of prometheus did you compare with?

Thanks in advance for the info!

**Comment by Nexucis** [comment]
yes I have the checkbox enabled in Prometheus. I tried with the last version (v2.26.0) and also with the prometheus demo: https://prometheus.demo.do.prometheus.io/

**Comment by Nexucis** [comment]
ah that's interesting, when I'm running the react app with `yarn start`, the bug doesn't appear. This is sooooo weird :o

**Comment by Nexucis** [comment]
ok so the good thing is the bug isn't related to the PromQL extension. it's only related to codemirror.

The bad thing is I don't really get why the build step would break something. But clearly there is something happening at this moment since when launching the UI through `yarn start`, nothing wrong is happening with codemirror.

**Comment by Nexucis** [comment]
ah it could come on how the assets are built. That's not the same way used in Prometheus and that's the only difference I found between Prometheus and Thanos regarding the build of the UI.

**Comment by Nexucis** [comment]
or not ....
I build the react-app and use a static server to serve it and the bug is there. So the problem is really when the react-app is built.
Back to understand and find what is the difference between the build of the react-app in Prometheus and in Thanos

**Comment by saswatamcode** [comment]
I managed to reproduce this. Seems like there's some range error that codemirror handles in Prometheus but not in Thanos. On testing, I found that in Thanos, editor crashes with the following dom,
![Screenshot 2021-05-09 at 10 47 24 AM](https://user-images.githubusercontent.com/51132453/117561402-1b169a00-b0b4-11eb-927e-222b046a9950.png)
![Screenshot 2021-05-09 at 10 41 03 AM](https://user-images.githubusercontent.com/51132453/117561329-87dd6480-b0b3-11eb-9846-34ae9862926e.png)
whereas Prometheus does not crash but shows an `Unexpected expression`(red squiggles) error in the UI with the following dom,
![Screenshot 2021-05-09 at 10 48 05 AM](https://user-images.githubusercontent.com/51132453/117561420-439e9400-b0b4-11eb-9e55-e5fb35972719.png)
![Screenshot 2021-05-09 at 10 42 07 AM](https://user-images.githubusercontent.com/51132453/117561318-72683a80-b0b3-11eb-8a16-a6e887e7e569.png)
Tested with the latest commits on both.

**Comment by Nexucis** [comment]
yes indeed. That's because in the 2nd case, you have the PromQL linter that is called by codemirror. And `test es       f` is not a correct PromQL expression. You can deactivate the linter, the autocompletion and the coloration highlighting, so you are not confused by the "regular errors" shown by the linter and the "not regular errors" which are visible in the console.

You can reproduce it with just writting something in the first line then go to the next line and smash the space until it crashes.

**Comment by saswatamcode** [comment]
Oh okay. Then it's probably an issue caused by build. Will try to test this further.
