### ISSUE TITLE
Create exemplar only for sampled traces

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#4186]
### Is your proposal related to a problem?

Now Thanos creates exemplars for all traces. However, if a trace is not sampled, then it is unnecessary to create an exemplar.

### Describe the solution you'd like

Modify code in https://github.com/thanos-io/thanos/blob/main/pkg/extprom/http/instrument_server.go#L120 like [this example](https://github.com/weaveworks/common/pull/202/files#diff-29d7cb6219a01fc80b731ac8004ac0f5edd5a1be507b164939ba4a4d1caf9ac2R70), checking whether the trace is sampled before creating the exemplar.

**Comment by Namanl2001** [comment]
I think we just need to add one more condition check [here](https://github.com/thanos-io/thanos/blob/e043efb3dbd598a97e04b10a81c61fad4ec52307/pkg/extprom/http/instrument_server.go#L121)

```
if ok && spanCtx.IsSampled() 
```

Should I go ahead with this change and make a PR?

**Comment by yeya24** [comment]
Yes, please go ahead.
One thing to mention here is that we currently only support Jaeger as we cast it to jaeger span. It would be good to support exemplars for other trace providers as well.

**Comment by wiardvanrij** [comment]
Thanks @yeya24 , this is what I was wondering and didn't thought this could be fixed this way. Awesome!
