### ISSUE TITLE
Feature request: 'Local' filesystem storage for Production usage

### ISSUE THREAD

**Issue by wiardvanrij** [thanos-io/thanos#4195]
### Community Note
- This is a central issue to see if there is a need for this feature. Please be involved in giving your use-case and input to shape this issue. 
- Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritise this request.
- If you are interested in working on this issue or have submitted a pull request, please leave a comment.
- Feel absolutely free to propose solutions, feedback, etc! 

### Intro

For storage options (https://thanos.io/tip/thanos/storage.md) we have various options. In general they are all based on 'object storage' solutions. 

Filesystem storage is available but with a non-production status https://thanos.io/tip/thanos/storage.md/#filesystem : 

>This storage type is used when user wants to store and access the bucket in the local filesystem. We treat filesystem the same way we would treat object storage, so all optimization for remote bucket applies even though, we might have the files locally.

> NOTE: This storage type is experimental and might be inefficient. It is NOT advised to use it as the main storage for metrics in production environment. Particularly there is no planned support for distributed filesystems like NFS. This is mainly useful for testing and demos.

### Use-case

There have been input regarding the need for an object store compatible storage solution. Especially in an 'on-prem' cluster, one might create extra overhead on their storage solution. 

One could wonder if we could increase performance and ease of use if one could use a generic storage solution.
 
### Describe the solution you'd like

- Allow for the usage of a 'generic' persistent volume in a production setup.

**This needs more input from the community.** 

### Describe alternatives you've considered

N/A , but can be added by the community.

**Comment by cg-cri-gl** [comment]
To start of , would be good to know what the reasons are for choosing the  _object storage_  storageType for storing data? They can't be limited to ease of use (i.e. no manual intervention required for fill-ups of the fs) ...
Maybe some developer can share some info about this.  
Afterwards, one would be able to ponder if the benefits / requirements of a object storage  could be / are already  found in a distributed  fs , for instance. 
To put the question other-way-round: what are the reason(s) the _local filesystem_  storageType does not suffice (excluding its inherent limitations for IO heavy loads) ?

**Comment by bobykus31** [comment]
remind
