### ISSUE TITLE
Define store API behavior on returned time range

### ISSUE THREAD

**Issue by fabxc** [thanos-io/thanos#42]
When we query the store API, we define a time window. When we retrieve chunks from block data, they do not align with that query window. For chunks crossing the query window at beginning and wend we could always decode the chunk, drop irrelevant samples, and encode new chunks. 

This however can be quite a few CPU cycles and allocations. The bandwidth overhead of just sending the full chunks is minor AFAICS. It might be a good idea to just send chunks as they are and have the query layer ensure we skip over irrelevant samples.

For the current sidecar implementation, we guarantee to return exactly the relevant data since we query raw datapoints and encode them as a chunk. But this might not be the case indefinitely – we eventually might want to get a chunk-based API upstream that's similar to the store API.

Any concerns with this proposal?

**Comment by Bplotka** [comment]
Yeah, this is quite important to agree on. 

Basically we have 2 options:
A) align chunks within exact time range on store nodes, thus:
- additional CPU overhead
- less data on wire

B) not doing additional  `decoding` & `encoding` on store node, thus:
- saving CPU cycles and allocs, 
- sending maybe unnecessary data on the wire.
- having bit different API contract, where we ask for time range but we allow response (chunks) to not align perfectly.

**I am up for option B**. Query needs to decode it anyway and we can keep store nodes, IO intensive only. So basically we adds more bits into wire and changes store API contract a little bit, which is a fair trade-off.
