### ISSUE TITLE
Thanos Receivers minimum tsdb retention 

### ISSUE THREAD

**Issue by heartTorres** [thanos-io/thanos#4203]
Hi, 

Since our clusters are on increasing, we are now on the plans to maximize our pods memory consumption. Our receivers have this config args "--tsdb.retention=3h" where we set the data retention on its local disk. We are planned to set it to 30m, 1h, however, after we waiting for 2 hours, no data were sent to S3. We know that 2 hrs is the default config. Is there anyway receivers upload the data to s3 in span of 30mins or 1h? In thanos sidecar, it is working properly but in our receivers, data were not uploaded to S3, after setting it in less than 2 hrs.

Hope someone can give me some light. Thank you.

**Comment by yeya24** [comment]
So if the retention is 3h, then everything works well for receiver, but if you set retention to 30mins, then there is no data?
Is there any error log?

**Comment by heartTorres** [comment]
> So if the retention is 3h, then everything works well for receiver, but if you set retention to 30mins, then there is no data?
> Is there any error log?

There is no error in the log. But is there any configuration to force the thanos receivers to upload the data in 30 min?
I read the documentation but seems not. 
We are using thanos v.0.15

**Comment by Kampe** [comment]
Thanos doesn't support backfilling any data it seems.

**Comment by btdan** [comment]
Hi, the parameter and value  --tsdb.retention=3h   means that the raw samples will be retrained on local storage from 3 hours. There is nothing to do with the frequecy of sending data to the remote object storage such as S3. 
I think so.
I am also puzzling about how to set the frequecy of sending data to the remote object storage with the command  thanos receive

**Comment by heartTorres** [comment]
I have set it to 1h and data were sent to S3. So we  decided to use 1h for now. I'll close this ticket. Thanks

**Comment by julienlau** [comment]
Hi,
According to this : 
https://stackoverflow.com/questions/75845334/testing-thanos-object-storage-upload-without-waiting-2-hours

You can achieve this by acting on tsdb.min-block-duration and tsdb.max-block-duration
You should put the same values for both and the value you choose should correspond to the time interval between uploads to S3.
