### ISSUE TITLE
Website: Fix indentation of longer titles in the menu

### ISSUE THREAD

**Issue by wiardvanrij** [thanos-io/thanos#4209]
### Is your proposal related to a problem?

When a submenu has child pages with relatively long titles, it becomes a bit hard to read. 
For example one could assume that 'Troubleshooting' is a sub-sub item of 'Reverse proxy'. 

![image](https://user-images.githubusercontent.com/5786097/117568526-0391de00-b0c1-11eb-9d86-bae70b8f9dc2.png)

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/5786097/117568557-3cca4e00-b0c1-11eb-961d-077901308b7a.png)

### Describe alternatives you've considered

Maybe add some smooth horizontal rule (don't mind my paint skillz)

![image](https://user-images.githubusercontent.com/5786097/117568594-700cdd00-b0c1-11eb-8993-16747e7e5221.png)

**Comment by Aman-Codes** [comment]
Hi @wiardvanrij I would like to work to on it!

**Comment by wiardvanrij** [comment]
> Hi @wiardvanrij I would like to work to on it!

Go for it! 💯
