### ISSUE TITLE
Website: Docs for v20 returns "Page not found"

### ISSUE THREAD

**Issue by krak7602** [thanos-io/thanos#4210]
**What happened**: Doumentation page for v20 of Thanos is provided under "tip". The v20 link returns a "page not found"

**What you expected to happen**: 

**How to reproduce it**: 
1. Go to home page of [Thanos](https://thanos.io/).
2. Try visiting the [v20 documentation](https://thanos.io/v0.20/thanos/getting-started.md).

**Anything else we need to know**: This is my first time contributing to this project. So, I am unsure if this is just an avoided issue.

**Comment by wiardvanrij** [comment]
Thank you! Seeing the PR, fix is on the way! 🎉

**Comment by bwplotka** [comment]
Thanks for spotting! 

It's there btw: https://thanos.io/v0.20/thanos/getting-started/ but we miss  entry for v0.20 on 
![image](https://user-images.githubusercontent.com/6950331/117635904-34811a00-b178-11eb-8960-e35d30cb9bc6.png) (https://github.com/thanos-io/thanos/blob/86fd8100612e8de5cd29e4d0d813346c50d110f1/website/hugo.yaml#L26)

Also hopefully we can have this lined and ensured better with  https://github.com/thanos-io/thanos/issues/3081 cc @saswatamcode

**Comment by bwplotka** [comment]
Actually @thisisobate found the root cause quite quickly: https://github.com/thanos-io/thanos/pull/4212
