### ISSUE TITLE
Thanos Query API does not expose config endpoint on Prometheus

### ISSUE THREAD

**Issue by Tiemma** [thanos-io/thanos#4216]
I have a deployment which queries a prometheus server deployment for the config deployed on it.

This is done via the `/api/v1/status/config` endpoint

I recently switched to Thanos and noticed the route mappings are changed for a `thanos query` run on the same configuration.

I did find that the APIs are registered on this endpoint to communicate with the native prometheus API via the thanos proxy.

https://github.com/thanos-io/thanos/blob/main/pkg/api/query/v1.go#L162

Is there by chance a remapping for that particular endpoint as I cannot find anything in the source representing that?

I also cannot use the sidecar option as some clients prefer a native option or have a fully thanos driven prometheus setup across multiple environments.

**Comment by yeya24** [comment]
No, I don't think this is our goal.
We do proxy some APIs like Rules, Targets, Exemplars on thanos query for sidecars.
But `/api/v1/status/config` is a special one. IMO we don't need a global view for this API. Why you cannot just query it from your Prometheus service?

**Comment by Tiemma** [comment]
Hello

For this, we use the endpoint to check if the thanos instance does expose a proper prometheus endpoint.

As of now, the `api/v1/flags` endpoint is exposed and this solved our use case.

If there are no issues, we can close the issue.
