### ISSUE TITLE
Thanos Receiver: local receiver not committing to TSDB block when forward fails 

### ISSUE THREAD

**Issue by ethernoy** [thanos-io/thanos#4230]
**Thanos, Prometheus and Golang version used**: 

- Thanos 0.19.0 (Bitnami image thanos:0.19.0-scratch-r0) 
- Prometheus 2.26.0 (Bitnami image prometheus:2.26.0-debian-10-r6)
- Golang: not sure (this Thanos image is based on scratch OS, cannot run `go version` in it)

**Object Storage Provider**: 

MinIO RELEASE.2021-02-14T04-01-33Z

**What happened**:

I was running a Thanos receive statefulset with 3 replicas and a soft hashring configured. TSDB retention was set to 4 hrs. Everything was OK at the beginning until **I manually used `dd` to fill up the PVC of receiver-2**. Receiver-2 couldn't write anything to WAL as expected, but receiver-0 and receiver-1 did not work as expected either. Symptoms of receiver-0 and receiver-1 include:

1. (Expected) stdout/err was flooded with log similar to `level=error ts=2021-05-13T06:21:27.100387377Z caller=handler.go:340 component=receive component=receive-handler err="forwarding request to endpoint thanos-receive-2.thanos-receive-headless.observability.svc.cluster.local:10901: rpc error: code = Internal desc = store locally for endpoint thanos-receive-2.thanos-receive-headless.observability.svc.cluster.local:10901: commit samples: write to WAL: log samples: write /var/thanos/receive/default-tenant/wal/00000189: no space left on device" msg="internal server error"`
1. (Unexpected) thanos-query cannot return metrics from any receivers after fill-out event
1. (Unexpected) thanos-bucket-web cannot see any block from any of the receivers, including those blocks already compacted in receiver local PVC before the fill-out event
![image](https://user-images.githubusercontent.com/15870761/118088182-42919d80-b3f9-11eb-9a1a-2cc1e007ba4d.png)
note: no block from receiver is listed above, only blocks in object storage are listed.
1. (Unexpected) object-storage no longer receives block uploaded from receivers after the fill-out event
1. (Unexpected) thanos-receive-0 and thanos-receive-1 no longer compact WAL to TSDB blocks after fill-out event
![image](https://user-images.githubusercontent.com/15870761/118087310-f003b180-b3f7-11eb-850d-410ded22d59c.png)
the latest block was committed at UTC 03:10
![image](https://user-images.githubusercontent.com/15870761/118087329-f8f48300-b3f7-11eb-8170-782518747cd4.png)
new WAL was still being generated at UTC 06:31
1. (Unexpcted) **as a result of point 5, thanos-receive-0 and thanos-receive-1 no longer comply with TSDB retention setting, old blocks were not deleted after it went out of retention window, hence PVC usage of these two instances will increase indefinitely until it reaches size limit and breaks the application**
![image](https://user-images.githubusercontent.com/15870761/118088419-9f8d5380-b3f9-11eb-82f6-d7b801d3a460.png)

**What you expected to happen**:
Thanos-receive-0 and thanos-receive-1 can work normally even if thanos-receive-2 is down. Metrics that should be processed by thanos-receive-2 according to the hashing should be either dropped or processed by 0 or 1.

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup a multi-replica thanos-receiver with soft-hashring configured
2. Break one of them by filling up its storage (or just shut it down perhaps)
3. Observe the other replica, they should no longer function normally and produce the symptoms listed above

**Full logs to relevant components**:

<details>Logs
<p>

**Thanos-receive-0 and thanos-receive-1:**

level=error ts=2021-05-13T06:48:42.505592554Z caller=handler.go:340 component=receive component=receive-handler err="forwarding request to endpoint thanos-receive-2.thanos-receive-headless.observability.svc.cluster.local:10901: rpc error: code = Internal desc = store locally for endpoint thanos-receive-2.thanos-receive-headless.observability.svc.cluster.local:10901: commit samples: write to WAL: log samples: write /var/thanos/receive/default-tenant/wal/00000189: no space left on device" msg="internal server error"

**Thanos-receive-2:**

level=error ts=2021-05-13T06:49:40.195783741Z caller=handler.go:340 component=receive component=receive-handler err="store locally for endpoint thanos-receive-2.thanos-receive-headless.observability.svc.cluster.local:10901: commit samples: write to WAL: log samples: write /var/thanos/receive/default-tenant/wal/00000189: no space left on device" msg="internal server error"

</p>
</details>

**Anything else we need to know**:

1. Is it possible to keep other thanos receivers in the same hashring working when one of the receivers goes down? I think it is important for high availability.
2. Prometheus introduced an experimental flag `--storage.tsdb.retention.size` in recent versions, will it be feasible to introduce this feature to Thanos receivers once it is official released? Although it cannot prevent the overlapping issue from denying retention settings (see comment below), it can still help to better protect storage from being filled up.
3. Maybe we need a best practice documentation for receivers? e.g. hashring setup, retention setup, etc.

**Comment by ethernoy** [comment]
In addition, the case listed above is not the first time I encounter this situation. In another environment, there are 6 replicas of Thanos receiver, one of them "thanos-receive-4" encountered an unexpected overlap block issue:

![image](https://user-images.githubusercontent.com/15870761/118089792-58a05d80-b3fb-11eb-97ea-42639a85ee8e.png)

After the overlap issue occurred, thanos-receive-4 stopped deleting outdated blocks and eventually filled all of its PVC. Then other receivers stopped deleting outdated blocks as well. In the end, all PVC of Thanos receivers were fully filled up and cannot be resumed without emptying their PVC.

**Comment by wiardvanrij** [comment]
When I read it like this, I assume we should alter the healthy state of such instance. I'm pretty sure that if the instance without storage would be killed (so for k8s == unhealthy) than it would/should be removed from the ring. 

In your case; if `receiver-2` would exit fatal (the disk is full == unhealthy, so that would make sense maybe), that should resolve the rest. Or.. we should check response codes & back-off / kick something out of the ring.

**Comment by ethernoy** [comment]
> When I read it like this, I assume we should alter the healthy state of such instance. I'm pretty sure that if the instance without storage would be killed (so for k8s == unhealthy) than it would/should be removed from the ring.
> 
> In your case; if `receiver-2` would exit fatal (the disk is full == unhealthy, so that would make sense maybe), that should resolve the rest. Or.. we should check response codes & back-off / kick something out of the ring.

@wiardvanrij  I think for the disk-full situation, the receivers should react differently according to their status:

- the disk-full receiver: should go into unhealthy state/terminate/start to clean up old block or WAL logs to make space
- other receivers within the same hashring: should at least continue to serve receive requests and enforce retention policy normally. It will be a plus if they can be aware of the disk-full receiver and can discard the request to-be-forwarded to that receiver until it recovers.

**Comment by Ygshvr** [comment]
@ethernoy how this issue was solved? and what was the replication factor that you were using?

**Comment by ethernoy** [comment]
> @ethernoy how this issue was solved? and what was the replication factor that you were using?

Nah it wasn't solved, we just enlarge the PVC we were using as a workaround.

About the replication factor, if you are talking about thanos-receive replication, we used 1.
