### ISSUE TITLE
Thanos compact is not deleting the old series

### ISSUE THREAD

**Issue by yasharne** [thanos-io/thanos#4244]
**Thanos, Prometheus and Golang version used**:
Thanos 0.20.1 with go1.16.3

**Object Storage Provider**: S3

**What happened**: 
When I run the sidecar for the first time, I ran it with the flag `--shipper.upload-compacted` to upload the older blocks to the S3 (blocks until April 25th in the picture), then I stopped it and now it is running without the `--shipper.upload-compacted` flag
Then I deployed the compact component and it is compacting the blocks correctly but as you see in the image below it is not deleting the old blocks coming from the sidecar (blocks until April 25th):
![image](https://user-images.githubusercontent.com/7656049/118625711-7d237d80-b7df-11eb-87aa-ba0ec4bd73e9.png)

**What you expected to happen**:
Delete the old blocks after compression

**How to reproduce it (as minimally and precisely as possible)**:
Upload the older blocks on the Prometheus using `--shipper.upload-compacted`  on the sidecar

**Comment by yeya24** [comment]
@yasharne How is the raw blocks retention configured in the compactor?

**Comment by yasharne** [comment]
Hi @yeya24
There no retention configuration on the compactor, here are the flags:
```
--wait
--wait-interval=5m
--consistency-delay=0s
--data-dir=/var/thanos/compact
--objstore.config=...
```

**Comment by yeya24** [comment]
If retention is not configured, old series won't be deleted.

**Comment by yasharne** [comment]
@yeya24 even if the source is `sidecar`?

**Comment by yasharne** [comment]
![image](https://user-images.githubusercontent.com/7656049/120059746-870f7100-c068-11eb-84c2-5d34168f2b15.png)
The Old block is from April 14th and the compactor has also compacted this block but the main block which is coming from the sidecar is not deleted
@yeya24

**Comment by yeya24** [comment]
@yasharne No matter what `source` you have, you need to configure retention to delete old blocks.
I will close this issue as it is a configuration problem. Let me know if you have further questions.
