### ISSUE TITLE
UX improvement of thanos.io

### ISSUE THREAD

**Issue by adithyapaib** [thanos-io/thanos#4246]
### Is your proposal related to a problem?

I would like to make the site improve the UX of the thanos.io website

**Comment by wiardvanrij** [comment]
We are always open to suggestions and improvements. Could you make this more actionable? I.e. propose what you have in mind? Thanks!

**Comment by adithyapaib** [comment]
I would like to fix various white spacing and negative spacing issues,
The font of the website can be changed,
would like to add a meta-theme tag for better a UX on phones 
would like to add color to the scroll bar (the colors mentioned here are the same as the purple color of thanio.io theme)
