### ISSUE TITLE
Thanos Store will go into OOM instead of degrading or providing a helpful error.

### ISSUE THREAD

**Issue by flaker** [thanos-io/thanos#4256]
Thanos: 0.20.1
Prometheus: 2.19.0 (go1.14.4)
Golang: 1.16.3

/ # /bin/thanos --version
thanos, version 0.20.1 (branch: HEAD, revision: 10023e4882414baa56a8955057f2678f1e724e8c)
  build user:       circleci@22b1af3c9a07
  build date:       20210430-12:46:55
  go version:       go1.16.3
  platform:         linux/amd64

**Object Storage Provider**: S3

**What happened**:

When querying > 7 days of data, the Thanos store container will OOM (32gb)

**What you expected to happen**:

Slower performance or some form of error response instead of going into full failure.

**How to reproduce it (as minimally and precisely as possible)**:

There's not a lot that can be added. A query with an aggregation over a somewhat long period (in my case is more than >7 days) can trigger this behavior.

**Full logs to relevant components**:

**Anything else we need to know**: 

There is no compaction going on so I assume a number of blocks will have to be queried and processed to serve the query.

I have't been able to find some form of "max-memory" command line option to control this. Is this behavior as expected? The need of data for aggregation requires all the blocks to be loaded in memory at the same time? is there a known workaround for this?

Thank you.

**Comment by bwplotka** [comment]
Valid point. There is no max memory in the Go option, unfortunately, but there is a lot we can do to have a similar experience. 

Before we start thinking about future improvements, can you check existing limits store GW offers? 

```
  --store.grpc.series-max-concurrency=20
                                 Maximum number of concurrent Series calls.
      --store.grpc.series-sample-limit=0
                                 Maximum amount of samples returned via a single
                                 Series call. The Series call fails if this
                                 limit is exceeded. 0 means no limit. NOTE: For
                                 efficiency the limit is internally implemented
                                 as 'chunks limit' considering each chunk
                                 contains 120 samples (it's the max number of
                                 samples each chunk can contain), so the actual
                                 number of samples might be lower, even though
                                 the maximum could be hit.
      --store.grpc.touched-series-limit=0
                                 Maximum amount of touched series returned via a
                                 single Series call. The Series call fails if
                                 this limit is exceeded. 0 means no limit.
```

Source: https://thanos.io/tip/components/store.md/

**Comment by flaker** [comment]
Hi @bwplotka thanks for your answer.

So I took this dashboard that I know can OOM our store easily and tailored the options you mentioned to numbers that allow for 1 week of data to be retrieved without a debug message complaining about some limit (well, actually only one that seemed way higher than the rest). I.e.:

```yaml
        - "--store.grpc.series-max-concurrency=4"
        - "--store.grpc.touched-series-limit=1000"
        - "--store.grpc.series-sample-limit=300"
```

As soon as I query for 3 weeks, I will go into an OOM again. So it's likely that I am using these options in an incorrect way. Is there any guidance around on how to tune them? Every link I follow either takes me to the same link you posted or to a verbatim copy.

I was also thinking that maybe our data is particularly wasteful in some way. Any way to diagnose that?

Thank you for your help.

**Comment by flaker** [comment]
@NesterenkoMisha , no, in the end I worked on the metrics trimming what was not needed, some work left but it's working for my usual workflow. If I remember and understand correctly, compaction might have also helped but we haven't implemented it yet.
