### ISSUE TITLE
running thanos in a K8S cluster without internet access

### ISSUE THREAD

**Issue by strus38** [thanos-io/thanos#4263]
### Is your proposal related to a problem?

Currently, it seems that Thanos is requiring getting its JS script from internet:
https://github.com/thanos-io/thanos/blob/main/pkg/ui/templates/bucket.html
This is a blocking point for air-gapped K8S cluster.

### Describe the solution you'd like

Provide all the necessary scripts if internet is not accessible.

**Comment by wiardvanrij** [comment]
Seems logical to do. Note to whoever wants to pick this up; perhaps check if any other components or places contain external resources.

**Comment by Aman-Codes** [comment]
I would like to work on this issue.

**Comment by onprem** [comment]
Ah sorry I missed this. Vendoring the Google charts library is against their terms so we can't really do anything about that. Our solution was to not use Google Charts at all and we are doing that in the New React based UI (which works without internet access).

**Comment by strus38** [comment]
Exactly, using the new ui makes it working. Then what should be done is maybe just an option to remove the 'classic ui' button from the interface, so nobody is tempted to use it in an air-gapped environment. Would that be possible?

**Comment by onprem** [comment]
Yes, we are planning to remove the Old UI completely in future (there's already a PR open for that).
