### ISSUE TITLE
Changing the thanos_store_nodes_grpc_connections implementation

### ISSUE THREAD

**Issue by wiardvanrij** [thanos-io/thanos#4267]
## Intro

I wanted to make a brand new issue to include all information from previous issues/pull-requests and slack discussions into one fresh issue. I will provide some extra context and background information. This should resolve some discussions we are having and move this forward. I feel this is useful as this had quite some discussions before over quite some period.

## Is your proposal related to a problem?

This issue relates to:
https://github.com/thanos-io/thanos/pull/4169
https://github.com/thanos-io/thanos/issues/4124

https://github.com/thanos-io/thanos/issues/3014

https://github.com/thanos-io/thanos/issues/4177

## Background and context

First we need to start with the reason `--store-strict` was implemented. This can be read here: https://thanos.io/tip/proposals/202001_thanos_query_health_handling.md/

Thanos Query updates the list of healthy store nodes every 5 seconds. It does that by sending the `Info()` call via gRPC.

### How --store works

The last successful check is noted in the `LastCheck` field. At this point if that fails, we note the error and remove the store node from the set of active store nodes. If it succeeds then it becomes a part of the active store set.

After `--store.unhealthy-timeout` passes since `LastCheck` then it also gets removed from the UI. At this point we would forget about it completely.

With regards to the metric `thanos_store_nodes_grpc_connections` - this gets instantly removed if the store is unhealthy and it does not wait for the `--store.unhealthy-timeout` to pass. 

### How --store-strict works

This only allows static defined store nodes. 

If the health check fails, we note the error but do not remove the store from the active store set AND Thanos Query will always retain the last successfully retrieved information via the Info() gRPC method. 

**Thus, they will always be considered as part of the active store set.**

With regards to the metric `thanos_store_nodes_grpc_connections` -  This simply **does not** get updated until the node returns into a healthy state.

## My take about static targets & strict store

The feature of `--store-strict` IMO unintendedly created a bug because we 'ignore' the activity of the store node to keep it in the active store set even if its unhealthy. This then also does not remove the metric anymore, but also does not reflect the actual state. 

Regardless of anything, this should be fixed.

However I do not think the 'liveness' of the `thanos_store_nodes_grpc_connections` metric should be limited to the `--store-strict` argument. 
Yes, it implies strictness. But `--store-strict` ALSO adds different features that might not be useful or even breaking to users who's sole intent is to have a solid `thanos_store_nodes_grpc_connections` metric. 

For example the Query component will always query unhealthy store nodes. Which might poses different issues for users. A user needs to deal with this, in order to have a working `thanos_store_nodes_grpc_connections` metric. Which seems not logical. 

To sum this up; A user should not have to use `--store-strict` for a working metric while the intend for `--store-strict` is created for one goal: 

> Update the health check logic to properly handle the case when a node disappears in terms of a caching layer.

To further add; it implies only `--store-strict` expects stores to be up. Let's be honest: we also expect `--store` to have atleast 1 store node that is not unhealthy.  The reason we more **explicitly** want to keep stores up on `--store-strict` is to deal with the caching layer. Regardless we still want to check metrics for stores, even on "non-strict mode"

## Static target vs Dynamic

To move towards a solution I wanted to describe something about static vs dynamic targets. 

**I believe that any target that uses `dns+` or `dnssrv+` is dynamic. Any other target is static.**
If we start the Query Component with `--store=somehost:10902` then we have a 'source of truth' and we can (and should?) keep the metric `thanos_store_nodes_grpc_connections` alive and update its value to reflect the status. See my description above about the working of `--store` - it instantly removes the metric if the store node is unhealthy at the moment.
 
## Describe the solution you'd like

_**(refer as solution 1)**_ 

Let's not bother (I mean this in a good way) between `--store` vs `--store-strict` for a metric. 

- If a target is static, we should keep the metric and update its value to reflect the actual status
- If a target is dynamic (so; `dns+` or `dnssrv+` , we should keep current behaviour) 

### Why remove dynamic store node metrics

Because it's not reliable. 

- Store node goes down
- Query goes does down
- Query goes back up
- Query has **no** knowledge of that dynamic store and thus would NOT have any metric about it

We need to update documentation that one could only have stable monitoring on `thanos_store_nodes_grpc_connections`  if they define static targets. 

## Describe alternatives you've considered

_**(refer as solution 2)**_

Don't make a difference between static vs dynamic targets and always keep the metric alive. It still should have the clear documentation that this is only reliable if static targets are used. 
Another downside is that if users who have a lot of fluctuating targets, it could 'spam' the metric full. That said, I doubt if this is an actual problem as the metric is fairly generic. It only contains the `external_labels` and `store_type` labels. Not an ip, hostname and such. 

_**(refer as solution 3)**_

Keep `--store` as it is and only implement this metric behaviour on `--store-strict`. 
This could make sense if new features extend on the more 'strict' part and assumptions and we deal with `--store` as volatile store nodes.  

## Additional context

There are 3 options, I just want to make clear that either way it would resolve everyones problems. We just have to pick the most logical one. Obviously this is open for other suggestions.

**Comment by dgrizzanti** [comment]
@wiardvanrij thanks for digging into this and creating the new issue. I think having all this context is incredibly helpful and gives the correct amount of background for us to make in an informed decision 🙂 

That being said, I'm good with Solution 1 or 2, though I think Solution 1 is likely more straightforward.

**Comment by bwplotka** [comment]
> To sum this up; A user should not have to use --store-strict for a working metric while the intend for --store-strict is created for one goal:
> Update the health check logic to properly handle the case when a node disappears in terms of a caching layer.
> To further add; it implies only --store-strict expects stores to be up. Let's be honest: we also expect --store to have atleast 1 store node that is not unhealthy. The reason we more explicitly want to keep stores up on --store-strict is to deal with the caching layer. Regardless we still want to check metrics for stores, even on "non-strict mode"

Well, that's only partially true. "Update the health check logic to properly handle the case when a node disappears in terms of a caching layer." - let's be specific. I think `strict` was added to make sure that:

* We have response caching.
* We have a store that is down, and ofc k8s service discovery take down store out of DNS result, so Querier can't see that there was previously any store if dns+, dnssrv+ are used.
* Despite this, partial response is not triggered, Querier thinks we had consistent data so returns success. 
* Data with gap is cached.

Overall we ensure that we return API errors (or warnings, depending on `PartialResponseStrategy`) when the strict store is down. We also cache last successful metadata yues. That's why it's called "strict".

> With regards to the metric thanos_store_nodes_grpc_connections - This simply does not get updated until the node returns into a healthy state.

We don't have a connection so I would fix this and put 0 for not alive connections.

# Summary

I like solution 1 + let's fix `thanos_store_nodes_grpc_connections` for strict nodes.

So the end state could look like this:

I would advise against solution 2. It can give a false impression that you can avoid using `absent` but you can't as the metric is cached and if process crashes you will miss alert (metric will "unregister" such lost store API automatically)

**Comment by dgrizzanti** [comment]
> `--endpoint` (because with @hitanshu-mehta we want to move it to be more generic): `best-effort` endpoint that is expected to be there or not.
> 
> If such endpoint is unhealthy (does not respond to Info) we DON'T fail query.
> 
> Yet we:
> 
> * register the connection metric (as 0) as soon as we know the address if static.  If dynamic then we don't and metric is more fluid for purpose. For static ones we also never unregister.
> * I would also keep last cached metadata on store page

@bwplotka one clarification question on this point. Can we define what we mean by "dynamic" here? Based on the current definition for passing in `--store`

```
--store=<store> ... 
Addresses of statically configured store API
servers (repeatable). The scheme may be
prefixed with 'dns+' or 'dnssrv+' to detect
store API servers through respective DNS
lookups.
```

I'd say the `dns+` and `dnssrv+` would be dynamic and anything else (IP or hostname + port) are static. Also, based on how I believe `--store.sd-files=<path>` works, that takes a list of IP/hostname combinations as well so those should also be considered static.

Any disagreement there?

Thanks!

**Comment by wiardvanrij** [comment]
Still relevant
