### ISSUE TITLE
ruler: probes are not started while WAL is being replayed

### ISSUE THREAD

**Issue by OGKevin** [thanos-io/thanos#4280]
**Thanos, Prometheus and Golang version used**: 
Thanos: [20e8105ec5b697a4755f2ff735509924173bd5cf](https://github.com/thanos-io/thanos/tree/20e8105ec5b697a4755f2ff735509924173bd5cf)

**What happened**:
Ruler crashed and was restarted, it now needs to replay the WAL. However, the probes are started after the WAL has been read, This code 
https://github.com/thanos-io/thanos/blob/f2564a7afabe930e789588ad0397a2b539a4ff79/cmd/thanos/rule.go#L320-L323
eventually calls `head.Init` in tsdb that replays the wall. The health probes are started afterwards here: https://github.com/thanos-io/thanos/blob/f2564a7afabe930e789588ad0397a2b539a4ff79/cmd/thanos/rule.go#L531-L537

This means that while ruler is reading the WAL, the liveness probe will fail and you end up in a crash loop unless you significantly increase the initial delay.
 

**What you expected to happen**:
Probe be the first thing to get started while the rest of ruler starts up. Reading WAL should be considered healthy but not ready. While failure to read WAL should be unhealthy.

**Comment by bwplotka** [comment]
Valid bug. Maybe @ianbillett want to try to fix it? 🤗

**Comment by bwplotka** [comment]
BTW note that we are close to make stateless ruler happen (https://github.com/thanos-io/thanos/pull/4250), but WAL will be still there 🙃

**Comment by OGKevin** [comment]
Cool, I'm also happy to work on this. Was just not sure if this was an actual bug or not.

**Comment by ianbillett** [comment]
@OGKevin nice report! Since you reported the bug, you have the right to fix it . It doesn't seem _too_ complicated, so a nice opportunity for you to get a commit into the Thanos code base :)

To fix, I think we just need to change the ordering of the ruler startup (as you point out above) so that we initialise the probes, and mark ourselves as healthy before then initialising the TSDB.

**Comment by OGKevin** [comment]
So due to the current dependency chain, the current order makes sense. 

HTTP and GRPC server need Rule Manager,  Rule Manager needs tsdb. 

I can think of 2 solutions atm:
1. Start HTTP server first with probes, and later register the additional `/api` routes to HTTP and start GRPC server once Rule Manager has been set up.
2. Create some "complex" implementations for HTTP and GRPC server that run fully on start and return errors until the status probe is set to ready. So basically make them status probe aware. But this most likely would require more discussion to come up with a design. This one could also introduce null pointer bugs.

**Comment by bwplotka** [comment]
I think we need 2 but it won't be complex. It will be exactly the same as https://github.com/thanos-io/thanos/blob/13ab756417b068a73a0b23c983f57b51658bf563/pkg/receive/multitsdb.go#L383 (: so some readiness struct that will tell API when to return success.
