### ISSUE TITLE
Thanos needs to support OSS authentication without configuring AccessKeyId and AccessKey

### ISSUE THREAD

**Issue by aapelismith** [thanos-io/thanos#4284]
### Is your proposal related to a problem?

Thanos needs to support OSS authentication without configuring AccessKeyId and AccessKey.
(Access via ECS binding role)

### Describe the solution you'd like
The Alibaba Cloud OSS SDK does not support AssumeRole in any way. 
For reference, here are some code examples:

[https://github.com/hashicorp/terraform/blob/d35bc0531255b496beb5d932f185cbcdb2d61a99/internal/backend/remote-state/oss/backend.go#L563](https://github.com/hashicorp/terraform/blob/d35bc0531255b496beb5d932f185cbcdb2d61a99/internal/backend/remote-state/oss/backend.go#L563)

**Comment by aapelismith** [comment]
Aliyun ecs metadata server  address:

http://100.100.100.200/latest/meta-data/ram/security-credentials/

you can get AccessKeyId and AccessKey via http://100.100.100.200/latest/meta-data/ram/security-credentials/{role_name}

**Comment by wiardvanrij** [comment]
Do you mean this? https://thanos.io/tip/thanos/storage.md/#aliyun-oss

**Comment by aapelismith** [comment]
@wiardvanrij yes

**Comment by aapelismith** [comment]
https://github.com/aliyun/aliyun-oss-go-sdk/blob/e3c86e545ae0c37a2c6b04a967bf6fadd76fa071/oss/conf.go#L47

I might submit a PR to solve this problem.

**Comment by aapelismith** [comment]
``` 
   type: ALIYUNOSS
    config:
      endpoint: ""
      bucket: ""
      access_key_id: ""
      access_key_secret: ""
```
access_key_id, access_key_secret It is not necessary to provide when the ECS instance is bound to the RAM Role, but it is clear that Thanos does not support it.

**Comment by wiardvanrij** [comment]
Right, I misunderstood your question. I thought you wanted auth via the keys :) Would be great if you could create support for that. We are definitely open for this.
