### ISSUE TITLE
port for 'store_gateway' job should be 19091 in thanos tutorial

### ISSUE THREAD

**Issue by juzhao** [thanos-io/thanos#4289]
thanos tutorial
https://katacoda.com/thanos/courses/thanos/2-lts
step 1, prometheus0_eu1.yml file
```
  - job_name: 'store_gateway'
    static_configs:
      - targets: ['127.0.0.1:19092']
```
port for 'store_gateway' should be 19091 compared with step 3
Deploying store for "EU1" Prometheus data part

**Comment by bwplotka** [comment]
Nice, thanks for pointing, help wanted to fix it!

**Comment by sandeep1785** [comment]
Hey Hi 😊 Is this issue still open as i can see it is merged already 24 days ago so why is this in open stage ? Any specific reason. if it is open i would love to take this up

**Comment by juzhao** [comment]
fix is fixed and merged
