### ISSUE TITLE
Will thanos support aliyun oss (similar like S3)

### ISSUE THREAD

**Issue by rmrf** [thanos-io/thanos#429]
Aliyun OSS https://www.alibabacloud.com/en/product/oss as I try with thanos, it's not working yet, would like to see Thanos supporting it. :)

**Comment by Bplotka** [comment]
If this store has S3 API and has strong consistency - all is possible, but we need someone to implement an client code for it (: Looking for volunteers!

Similar question as https://github.com/improbable-eng/thanos/issues/409

**Comment by gagado** [comment]
now，thanos can support Aliyun OSS?

**Comment by gagado** [comment]
@bwplotka now，thanos can support Aliyun OSS?

**Comment by gagado** [comment]
@ryane @bwplotka now, I use thanos with aliyun oss, but have a error:Please use virtual hosted style to access.
help me.thank you.

**Comment by ringtail** [comment]
@bwplotka @rmrf Hi guys, I will fix this issue.

**Comment by jojohappy** [comment]
@ringtail Hi, we have an open PR #1573 to implement it, welcome to review if you'd love to.

**Comment by jojohappy** [comment]
@rmrf @ringtail Now Thanos supports Aliyun OSS, further information is [here](https://github.com/thanos-io/thanos/blob/master/docs/storage.md#aliyun-oss).
