### ISSUE TITLE
Proposal: Environment Variables Substitution for PathOrContent flag.

### ISSUE THREAD

**Issue by uhthomas** [thanos-io/thanos#4293]
As part of the [v0.2.0 - 2018.12.10 changelog](https://github.com/thanos-io/thanos/blob/464f8fb61c375543145eeb6a6ffc2c06a6819299/CHANGELOG.md#v020---20181210), the following environment variables are deprecated:
- S3_BUCKET
- S3_ENDPOINT
- S3_ACCESS_KEY
- S3_INSECURE
- S3_SIGNATURE_VERSION2

What are the alternatives? Why do these still exist in the quickstart if they are deprecated?

The environment variables are still being parsed, is this on purpose?

See https://github.com/thanos-io/thanos/blob/7e9958d061818446fa36e2e0e800744dd0522674/pkg/objstore/s3/s3.go#L512-L515

**Comment by uhthomas** [comment]
Reading the code further, it looks like these environment variables are only used for tests.

What is the recommended way to substitute environment variables into the Thanos config?

**Comment by bwplotka** [comment]
Thanks for reporting. The recommended way is to use Kubernetes eval substitution and direct flag content passing when running on k8s or some sed pre-exec command.

## Proposal

I would like to actually propose something more versatile. Already commented: https://github.com/bwplotka/mdox/pull/33#discussion_r642991603 (cc @saswatamcode) the idea would be to extend our `PathOrContent`  struct to enable env substitution on parsing. I would vote for the similar convention as k8s: `$(ENV)`

WDYT @thanos-io/thanos-maintainers ?

**Comment by bwplotka** [comment]
Changed the title of this issue, let me know if that makes sense

**Comment by kakkoyun** [comment]
@saswatamcode @bwplotka Is this functionality provided with #4327? Shall we close this?

**Comment by saswatamcode** [comment]
Yes, functionality is implemented by PR. I think the quickstart script also works. But is there a need to update the tests that use env variables? 🙂

**Comment by kakkoyun** [comment]
Done by #4327
