### ISSUE TITLE
Compact: Unknown long flag '--compaction.concurrency'

### ISSUE THREAD

**Issue by vibgy** [thanos-io/thanos#4294]
Unknown flag

```
error parsing commandline arguments: [/bin/thanos compact --log.level=info --objstore.config-file=/volumes/secret/objectstore/thanos.yaml --data-dir=/volumes/data --compaction.concurrency=3 --selector.relabel-config=
  - source_labels: [_replica]
    action: keep
    regex: ^.+-us-central1-.+$
 --retention.resolution-raw=30d --retention.resolution-5m=120d --retention.resolution-1h=1y --bucket-web-label=compact-us-central1 --wait]: unknown long flag '--compaction.concurrency'
thanos: error: unknown long flag '--compaction.concurrency'
```

**Thanos, Prometheus and Golang version used**:
```
thanos, version 0.19.0 (branch: HEAD, revision: ba6c5c4726ff52807c7383c68f2159b1af7980bb)
  build user:       circleci@2b62ab01da9f
  build date:       20210331-12:33:41
  go version:       go1.15.10
  platform:         linux/amd64
```

**Object Storage Provider**: GCS

**What happened**: Command line flag `compaction.concurrency` is not working

**What you expected to happen**: Should be able to set `compaction.concurrency` on the command line

**How to reproduce it (as minimally and precisely as possible)**: Try the command: `thanos compact --compaction.concurrency=1`
 
**Full logs to relevant components**:
```
error parsing commandline arguments: [/bin/thanos compact --log.level=info --objstore.config-file=/volumes/secret/objectstore/thanos.yaml --data-dir=/volumes/data --compaction.concurrency=3 --selector.relabel-config=
  - source_labels: [_replica]
    action: keep
    regex: ^.+-us-central1-.+$
 --retention.resolution-raw=30d --retention.resolution-5m=120d --retention.resolution-1h=1y --bucket-web-label=compact-us-central1 --wait]: unknown long flag '--compaction.concurrency'
thanos: error: unknown long flag '--compaction.concurrency'
```

**Anything else we need to know**: None.

**Comment by squat** [comment]
Hi @vibgy the flag is supposed to be `--compact.concurrency`, not `--compaction.concurrency`. Did you find this indirect flag in a document somewhere? If so, let's correct that.

**Comment by vibgy** [comment]
Ah. The docs here uses `--compaction.concurrency`  - https://github.com/thanos-io/thanos/blob/f2564a7afabe930e789588ad0397a2b539a4ff79/docs/components/compact.md#cpu
