### ISSUE TITLE
query: Query errors don't get replayed and queries silently fail on second try

### ISSUE THREAD

**Issue by RiRa12621** [thanos-io/thanos#4301]
**What happened**:
An error in a query displays an error. If that is "clicked away" by clicking the little x, the same error is not displayed again, when the query is run again, even if it is at a later time 

**What you expected to happen**:
Show the error again

**How to reproduce it (as minimally and precisely as possible)**:
enter falsey query, see error, click little x, run the same query again. 

Version:

<h2></h2>
version | 0.20.0-rc.0
-- | --
0dfd10788c5ffbe5fca5547336ee868319a5119a
HEAD
circleci@c193b4737e52
20210423-12:06:20
go1.16.3

**Comment by bwplotka** [comment]
Thanks, wonder if it's the same on Prometheus UI 🤔

**Comment by prashant-kush** [comment]
This still look likes valid.
