### ISSUE TITLE
ruler: does not show alert rule durations like Prometheus does

### ISSUE THREAD

**Issue by rackeric** [thanos-io/thanos#4302]
### Is your proposal related to a problem?

Moving from Prometheus to Thanos and I am now noticing that Ruler does not show alert rule duration in the UI like Prometheus would show. I think it is important to show this so we can know how long the rule needs to be firing before alerting when troubleshooting.

### Describe the solution you'd like

Prometheus UI shows alert duration in the "for:" field as shown in below screenshot, it would be nice to have similar in the Thanos Ruler UI, screenshot example below.

Prometheus Alerts UI:
![prom_screenshot](https://user-images.githubusercontent.com/4127665/120679681-11881400-c45f-11eb-843a-b0730e6f60d1.png)

Thanos Ruler Alerts UI:
<img width="876" alt="Screen Shot 2021-06-03 at 11 35 14 AM" src="https://user-images.githubusercontent.com/4127665/120680339-cde1da00-c45f-11eb-940d-149bdb41eac1.png">

### Describe alternatives you've considered

Tried finding a flag or option which could enable this but did not fine one.

### Additional context

Did not find any related issues for this.

**Comment by Hangzhi** [comment]
I would like to work on this issue.

**Comment by rackeric** [comment]
I'll look into addressing this as well since will be very useful to us.

**Comment by rackeric** [comment]
Please see https://github.com/thanos-io/thanos/pull/4340

**Comment by GiedriusS** [comment]
Closed via https://github.com/thanos-io/thanos/pull/3678/files#diff-50298ee275ead9b6ba3dcc1a556430c41d6ba48a8a4b12e26c83cece720f9bdbR89-R94. Thanks for your PR again!

**Comment by onprem** [comment]
Closing as #4340 is merged.
