### ISSUE TITLE
Queries against Prometheus are considerably faster than against Thanos Querier -> sidecar -> Prometheus setup

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#4304]
Recently benchmarked the setup and noticed my query was running 7s through StoreAPI, but it took 4s on Prometheus.

We did many optimizations, but there is still a slowness to optimize. I suspect Querier potentially (we never benchmarked it fully), 

Some customers notices slowness too:

```
The same query agains prometheus and the thanos querier.
For all queries I run a warmup query to ensure that all data are cached localy.
Prometheus take:  appr 5s to query a 2 day range
Thanos take: appr 26s  to query a 2 day range (the range Prometheus can provide)
Thanos take: appr 55s  to query a 2 day range (a range in past)
```

We had past mentions like https://github.com/thanos-io/thanos/issues/631 (for 1y data though).

Of course, query-push down work we planned would help, but not for all  queries, so this ticket is to benchmark that particular path (mentioned in the title)

**Comment by PowerSurj** [comment]
Still an issue. I've been through all duplicate posts and i didn't find a fix.
