### ISSUE TITLE
receive: Replica count exceeds replication factor although it does not?

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#4305]
```
level=debug ts=2021-05-27T00:57:03.170460586Z caller=handler.go:641 component=receive component=receive-handler msg="failed to handle request" err="replica count exceeds replication factor"
replicas: 6
receive.replication-factor=2
```

I don't really understand this, replica does not exceed replication 🤔

**Comment by bwplotka** [comment]
This might need more info, I suspect 2 replicas were just up. Worth to document this error/failure mode better

**Comment by squat** [comment]
This is saying that a receiver A got a forwarded message from receiver B.

B said "this is copy number 6 of the time series."

A looks at it's configuration and says "huh, replication factor is only 2, so why did i get copy number 6? This must be a mistake"

**Comment by ianbillett** [comment]
I don't think we need to do anything serious here apart from maybe re-wording the error message slightly. Perhaps this is slightly clearer?
> request replica number exceeds receiver's replication factor
