### ISSUE TITLE
sidecar: file permission issue for envsub config file

### ISSUE THREAD

**Issue by OGKevin** [thanos-io/thanos#4307]
**Thanos, Prometheus and Golang version used**:
Thanos: v0.21.0

**What happened**:
https://github.com/thanos-io/thanos/pull/4173 changed file permission. This resulted in denying access to "all users"(the last digit). In a scenario where you are using the default users for Prometheus and Thanos container, Prometheus can not read the output file.

This can be fixed by changing the last digit to 4(read) or 5(read and execute).

**What you expected to happen**:
Prometheus be able to read the output config from sidecar

**How to reproduce it (as minimally and precisely as possible)**:
Run v0.21.0 with the default users

**Full logs to relevant components**:

<details>Logs
<p>

```
level=error ts=2021-06-04T09:35:32.730Z caller=main.go:289 msg="Error loading config (--config.file=/config/thanos-prometheus-config.envsubst.generated.yaml)" err="open /config/thanos-prometheus-config.envsubst.generated.yaml: permission denied"
```

</p>
</details>

**Comment by onprem** [comment]
Fixed in #4308
