### ISSUE TITLE
Add Katacoda tutorial for Thanos Receive component

### ISSUE THREAD

**Issue by ianbillett** [thanos-io/thanos#4314]
### Is your proposal related to a problem?

Currently no guided tutorial for Thanos receive.

### Describe the solution you'd like

Katacoda tutorial for Thanos receive, like for querier.

### Describe alternatives you've considered

Adding to the documentation - the interactivity of Katacoda is key.

### Additional context

Personally, I have found the Katacoda [tutorials](https://github.com/thanos-io/thanos/tree/main/tutorials/katacoda/thanos) incredibly helpful in getting up to speed with how different components in the Thanos project work.

Ideally, we would have a tutorial for each major piece of functionality so that new users are able to understand the project, and the motivations for each component.

My proposal is to add a Katacoda tutorial for Thanos Receive.

This issues is more for visibility than anything else. Unless there are wild objections, I will start working on this today :hugs:

**Comment by bwplotka** [comment]
Thanks! Help wanted. Any proposed flow of such tutorial we could do? (:

**Comment by ianbillett** [comment]
As with any good tutorial, we need to keep it simple enough to understand while answering the main questions a new user will have. For example:
* Why would I want to do this?
* How does this work?
* How do I configure this setup?

There is lots of good documentation out there for receive: [docs page](https://thanos.io/tip/components/receive.md/), [Thanos remote write proposal](https://thanos.io/tip/proposals/201812_thanos-remote-receive.md/), [Pros/Cons of allowing remote write in Prometheus doc](https://docs.google.com/document/d/1H47v7WfyKkSLMrR8_iku6u9VB73WrVzBHb2SB6dL9_g/edit#heading=h.2v27snv0lsur). The work here is about distilling this information into an beginner-friendly, step-by-step tutorial.
