### ISSUE TITLE
store: Loading block index fails 

### ISSUE THREAD

**Issue by blemmenes** [thanos-io/thanos#4317]
**Thanos, Prometheus and Golang version used**:

Thanos 0.20.1 via quay.io/thanos/thanos:v0.20.1
Prometheus was on 2.13.0, updated to 2.27.1 as part of trouble shooting.

**Object Storage Provider**:
Self-hosted Ceph cluster. No updates/changes to cluster version etc preceded issue.

**What happened**:
Store instance is no longer able to load the block index file in order to create the index-header file on the local filesystem.

**What you expected to happen**:
Store instance to load block index and create index-header.

**How to reproduce it (as minimally and precisely as possible)**:
Unknown at this time.

**Full logs to relevant components**:
Log snip from the store node as there are lots of blocks and it is unable to load any of the blocks, including all of them would be excessive IMO.

<details>Store Logs
<p>
level=debug ts=2021-06-07T20:29:09.996894511Z caller=bucket.go:545 msg="loading new block" id=01DN3SDSJ2M80BRJVJJRAFV7XH
level=debug ts=2021-06-07T20:29:09.997027562Z caller=binary_reader.go:467 msg="failed to read index-header from disk; recreating" path=/thanos/store/01DN3SDSJ2M80BRJVJJRAFV7XH/index-header err="try lock file: open /thanos/store/01DN3SDSJ2M80BRJVJJRAFV7XH/index-header: no such file or directory"
level=warn ts=2021-06-07T20:29:10.007431747Z caller=bucket.go:552 msg="loading block failed" elapsed=41.294333ms id=01F7811WNKQB0FD2PZDSK81MDY err="create index header reader: write index header: new index reader: get TOC from object storage of 01F7811WNKQB0FD2PZDSK81MDY/index: 416 Requested Range Not Satisfiable"
level=debug ts=2021-06-07T20:29:10.007477177Z caller=bucket.go:545 msg="loading new block" id=01F76V0X955GEBWGS77Q4WZWAM
level=debug ts=2021-06-07T20:29:10.007505945Z caller=binary_reader.go:467 msg="failed to read index-header from disk; recreating" path=/thanos/store/01F76V0X955GEBWGS77Q4WZWAM/index-header err="try lock file: open /thanos/store/01F76V0X955GEBWGS77Q4WZWAM/index-header: no such file or directory"
level=warn ts=2021-06-07T20:29:10.016616716Z caller=bucket.go:552 msg="loading block failed" elapsed=36.986954ms id=01EDWYWQH3E320P80J05JPXWQK err="create index header reader: write index header: new index reader: get TOC from object storage of 01EDWYWQH3E320P80J05JPXWQK/index: 416 Requested Range Not Satisfiable"
level=debug ts=2021-06-07T20:29:10.016669573Z caller=bucket.go:545 msg="loading new block" id=01D84F3QEPDJDGQM1HS2M608VH
level=debug ts=2021-06-07T20:29:10.016785039Z caller=binary_reader.go:467 msg="failed to read index-header from disk; recreating" path=/thanos/store/01D84F3QEPDJDGQM1HS2M608VH/index-header err="try lock file: open /thanos/store/01D84F3QEPDJDGQM1HS2M608VH/index-header: no such file or directory"
level=warn ts=2021-06-07T20:29:10.02653565Z caller=bucket.go:552 msg="loading block failed" elapsed=31.947943ms id=01F789D3W5BVKWTRKAFTHFR40X err="create index header reader: write index header: new index reader: get TOC from object storage of 01F789D3W5BVKWTRKAFTHFR40X/index: 416 Requested Range Not Satisfiable"
level=debug ts=2021-06-07T20:29:10.026586058Z caller=bucket.go:545 msg="loading new block" id=01F77V4AN48ETM7N0X4Z9PBW38
level=debug ts=2021-06-07T20:29:10.026615979Z caller=binary_reader.go:467 msg="failed to read index-header from disk; recreating" path=/thanos/store/01F77V4AN48ETM7N0X4Z9PBW38/index-header err="try lock file: open /thanos/store/01F77V4AN48ETM7N0X4Z9PBW38/index-header: no such file or directory"
level=warn ts=2021-06-07T20:29:10.036488238Z caller=bucket.go:552 msg="loading block failed" elapsed=56.468173ms id=01DQBZWWSGKDSTMVKVGHMY67KT err="create index header reader: write index header: new index reader: get TOC from object storage of 01DQBZWWSGKDSTMVKVGHMY67KT/index: 416 Requested Range Not Satisfiable"
level=debug ts=2021-06-07T20:29:10.036529575Z caller=bucket.go:545 msg="loading new block" id=01DJSZRFRTRPYJC3KPZ4JQ7N47
level=debug ts=2021-06-07T20:29:10.03659077Z caller=binary_reader.go:467 msg="failed to read index-header from disk; recreating" path=/thanos/store/01DJSZRFRTRPYJC3KPZ4JQ7N47/index-header err="try lock file: open /thanos/store/01DJSZRFRTRPYJC3KPZ4JQ7N47/index-header: no such file or directory"
level=warn ts=2021-06-07T20:29:10.044457822Z caller=bucket.go:552 msg="loading block failed" elapsed=36.981103ms id=01F76V0X955GEBWGS77Q4WZWAM err="create index header reader: write index header: new index reader: get TOC from object storage of 01F76V0X955GEBWGS77Q4WZWAM/index: 416 Requested Range Not Satisfiable"
level=debug ts=2021-06-07T20:29:10.044499385Z caller=bucket.go:545 msg="loading new block" id=01DZ89ARV4ZD6H60HWWEKVWSDR
level=debug ts=2021-06-07T20:29:10.044529374Z caller=binary_reader.go:467 msg="failed to read index-header from disk; recreating" path=/thanos/store/01DZ89ARV4ZD6H60HWWEKVWSDR/index-header err="try lock file: open /thanos/store/01DZ89ARV4ZD6H60HWWEKVWSDR/index-header: no such file or directory"
level=warn ts=2021-06-07T20:29:10.051423756Z caller=bucket.go:552 msg="loading block failed" elapsed=34.754308ms id=01D84F3QEPDJDGQM1HS2M608VH err="create index header reader: write index header: new index reader: get TOC from object storage of 01D84F3QEPDJDGQM1HS2M608VH/index: 416 Requested Range Not Satisfiable"
level=debug ts=2021-06-07T20:29:10.051465145Z caller=bucket.go:545 msg="loading new block" id=01DY86XM3AFG4T1J8JPXMDRE2Z
level=debug ts=2021-06-07T20:29:10.05149236Z caller=binary_reader.go:467 msg="failed to read index-header from disk; recreating" path=/thanos/store/01DY86XM3AFG4T1J8JPXMDRE2Z/index-header err="try lock file: open /thanos/store/01DY86XM3AFG4T1J8JPXMDRE2Z/index-header: no such file or directory"
level=warn ts=2021-06-07T20:29:10.054035219Z caller=bucket.go:552 msg="loading block failed" elapsed=321.587937ms id=01DY874Y45E8BM6VEP8M4CD5CM err="create index header reader: write index header: new index reader: get TOC from object storage of 01DY874Y45E8BM6VEP8M4CD5CM/index: 416 Requested Range Not Satisfiable"
</p>
</details>

**Anything else we need to know**:
```  
command:
    - 'store'
    - '--log.level=debug'
    - '--data-dir=/thanos/store'
    - '--objstore.config-file=/thanos/bucket_config.yaml'
    - '--grpc-address=0.0.0.0:10901'
    - '--http-address=0.0.0.0:10902'
```
Deployment was working fine, at some indeterminate time the store component stopped being able to get bucket index files and create index-headers. Store container was using a persistent volume, for testing I removed/recreated the persistent volume, exec'ing into the container shows only `meta-syncer` under `/thanos/store/`.

Our RGW nodes are showing HTTP 200s for all HEAD/GET requests for the block meta.json and index files:
```
2021-06-07 20:15:20.231 7f36ee308700  1 beast: 0x55bc60fb2700: 10.240.230.40 - - [2021-06-07 20:15:20.0.231051s] "HEAD /thanos-grr/01F730QX861SF74H617Z8HQFGZ/meta.json HTTP/1.1" 200 0 - "MinIO (linux; amd64) minio-go/v7.0.10 thanos-store/0.20.1 (go1.16.3)" -
2021-06-07 20:01:12.155 7fd516858700  1 beast: 0x55b51b83a700: 10.240.230.40 - - [2021-06-07 20:01:12.0.15509s] "HEAD /thanos-grr/01F730QX861SF74H617Z8HQFGZ/meta.json HTTP/1.1" 200 0 - "MinIO (linux; amd64) minio-go/v7.0.10 thanos-store/0.20.1 (go1.16.3)" -
2021-06-07 20:10:12.127 7fd4dcfe5700  1 beast: 0x55b51f8bc700: 10.240.230.40 - - [2021-06-07 20:10:12.0.127065s] "HEAD /thanos-grr/01F730QX861SF74H617Z8HQFGZ/meta.json HTTP/1.1" 200 0 - "MinIO (linux; amd64) minio-go/v7.0.10 thanos-store/0.20.1 (go1.16.3)" -
2021-06-07 20:12:20.227 7fd492750700  1 beast: 0x55b51c862700: 10.240.230.40 - - [2021-06-07 20:12:20.0.227059s] "HEAD /thanos-grr/01F730QX861SF74H617Z8HQFGZ/meta.json HTTP/1.1" 200 0 - "MinIO (linux; amd64) minio-go/v7.0.10 thanos-store/0.20.1 (go1.16.3)" -
2021-06-07 20:17:02.579 7fd53a09f700  1 beast: 0x55b529e1c700: 10.240.230.40 - - [2021-06-07 20:17:02.0.579046s] "HEAD /thanos-grr/01F730QX861SF74H617Z8HQFGZ/meta.json HTTP/1.1" 200 0 - "MinIO (linux; amd64) minio-go/v7.0.10 thanos-store/0.20.1 (go1.16.3)" -
2021-06-07 20:12:31.791 7fc8e8837700  1 beast: 0x5555c7e0a700: 10.240.230.40 - - [2021-06-07 20:12:31.0.791058s] "GET /thanos-grr/01F730QX861SF74H617Z8HQFGZ/index HTTP/1.1" 206 5 - "MinIO (linux; amd64) minio-go/v7.0.10 thanos-store/0.20.1 (go1.16.3)" bytes=0-4
2021-06-07 20:16:36.411 7fc864f30700  1 beast: 0x5555c9a84700: 10.240.230.40 - - [2021-06-07 20:16:36.0.411047s] "HEAD /thanos-grr/01F730QX861SF74H617Z8HQFGZ/meta.json HTTP/1.1" 200 0 - "MinIO (linux; amd64) minio-go/v7.0.10 thanos-store/0.20.1 (go1.16.3)" -
2021-06-07 20:16:47.955 7fc88b77d700  1 beast: 0x5555c6838700: 10.240.230.40 - - [2021-06-07 20:16:47.0.955046s] "HEAD /thanos-grr/01F730QX861SF74H617Z8HQFGZ/index HTTP/1.1" 200 0 - "MinIO (linux; amd64) minio-go/v7.0.10 thanos-store/0.20.1 (go1.16.3)" -
```

**Comment by ianbillett** [comment]
@blemmenes I'm not an expert in this area, but it _feels_ like there is some kind of resource contention. Couple of questions I would ask: 
* Do you have CPU / Memory stats for the store during this period? 
* How many blocks are in the storage? 
* How much data is in the storage?

**Comment by blemmenes** [comment]
@ianbillett Thanks for taking a look. Yeah, I would think then it would get at least _some_ of the indexes, but I'm _definitely_ not an expert. :)

- System has 32GB of RAM and ~600MB used while it's trying to load blocks.
- 4 core system < 15% used (load 1.2 - 1.5)
- 661 blocks
- 3.6TB in this bucket

There is another store node using this same ceph cluster without issue, and several more using a different (but identical version cluster) have as well.

Thanks,
Berant

**Comment by blemmenes** [comment]
Anyone have any thoughts on this, or steps I can take to isolate/provide more detail?

**Comment by ianbillett** [comment]
@blemmenes reading through this issue again - the key problem appears to be the `416 Requested Range Not Satisfiable` errors being returned from Ceph when we requested the `*/index` file.

I would try and run the s3 e2e [tests](https://thanos.io/v0.2/thanos/storage.md/#aws-s3-configuration) against your Ceph storage to attempt to localise this problem to one with fewer variables :)

**Comment by blemmenes** [comment]
@ianbillett I'll take a look at running those tests and will let you know.

However, for context I have have several other thanos store instances running against these Ceph clusters without issues, same thanos version, same cluster, same credentials (different buckets) etc. This store instance was also running for a year ish without issue?

**Comment by ianbillett** [comment]
Without a reliable way to reproducel, this issue is going to be very difficult to debug I'm afraid.

The `416`s in the errors look like they are coming from the storage layer, so this could be a issue on the Ceph side too :)

**Comment by blemmenes** [comment]
@ianbillett So finally had a chance to sit down and try messing with these test and it seems like I'm doing something wrong. A `make test-local` works fine, however `make test-e2e` fails. It seems like it's still trying to spin up a local minio instance vs. using our ceph cluster.

Here are the variables I have set:
```
export THANOS_TEST_OBJSTORE_SKIP=GCS,AZURE,SWIFT,COS,ALIYUNOSS
export S3_ACCESS_KEY=<snip>
export S3_SECRET_KEY=<snip>
export S3_ENDPOINT=<endpoint FQDN>
export S3_INSECURE="true"
export S3_ENCRYPT_SSE="false"
export S3_SIGNATURE_VERSION2="true"
```

```
<snip>
11:36:43 Killing querier-1
11:36:43 Killing store-gw-1
11:36:44 Killing minio-8080
--- PASS: TestStoreGateway (20.31s)
    --- PASS: TestStoreGateway/query_works (4.04s)
    --- PASS: TestStoreGateway/remove_meta.json_from_id1_block (2.17s)
    --- PASS: TestStoreGateway/upload_block_id5,_similar_to_id1 (3.07s)
    --- PASS: TestStoreGateway/delete_whole_id2_block_#yolo (3.04s)
=== CONT  TestToolsBucketWebExternalPrefixAndRoutePrefix
11:36:45 Starting minio-8080
11:36:46 Ports for container: e2e_test_tools_bucket_web_external_prefix_and_route_prefix-minio-8080 Mapping: map[8080:49326]
11:36:46 minio-8080: Attempting encryption of all config, IAM users and policies on MinIO backend
11:36:47 Starting toolsBucketWeb-1
11:36:48 toolsBucketWeb-1: level=warn name=toolsBucketWeb-1 ts=2021-09-13T15:36:48.455835174Z caller=tools_bucket.go:357 msg="different values for --web.route-prefix and --web.external-prefix detected, web UI may not work without a reverse-proxy."
11:36:48 toolsBucketWeb-1: level=info name=toolsBucketWeb-1 ts=2021-09-13T15:36:48.458115141Z caller=factory.go:46 msg="loading bucket configuration"
11:36:48 toolsBucketWeb-1: level=info name=toolsBucketWeb-1 ts=2021-09-13T15:36:48.458990559Z caller=intrumentation.go:48 msg="changing probe status" status=ready
11:36:48 toolsBucketWeb-1: level=info name=toolsBucketWeb-1 ts=2021-09-13T15:36:48.459334852Z caller=intrumentation.go:60 msg="changing probe status" status=healthy
11:36:48 toolsBucketWeb-1: level=info name=toolsBucketWeb-1 ts=2021-09-13T15:36:48.459360013Z caller=http.go:63 service=http/server component=bucket msg="listening for requests and metrics" address=:8080
11:36:48 toolsBucketWeb-1: level=info name=toolsBucketWeb-1 ts=2021-09-13T15:36:48.459630175Z caller=tls_config.go:191 service=http/server component=bucket msg="TLS is disabled." http2=false
11:36:48 toolsBucketWeb-1: level=error name=toolsBucketWeb-1 ts=2021-09-13T15:36:48.4601012Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="BaseFetcher: iter bucket: Get \"http://e2e_test_tools_bucket_web_external_prefix_and_route_prefix-minio-8080:8080/toolsBucketWeb_test/?location=\": dial tcp: lookup e2e_test_tools_bucket_web_external_prefix_and_route_prefix-minio-8080: no such host"
11:36:48 Ports for container: e2e_test_tools_bucket_web_external_prefix_and_route_prefix-toolsBucketWeb-1 Mapping: map[8080:49328 9091:49327]
11:37:48 toolsBucketWeb-1: level=error name=toolsBucketWeb-1 ts=2021-09-13T15:37:48.460140904Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="BaseFetcher: iter bucket: Get \"http://e2e_test_tools_bucket_web_external_prefix_and_route_prefix-minio-8080:8080/toolsBucketWeb_test/?location=\": dial tcp: lookup e2e_test_tools_bucket_web_external_prefix_and_route_prefix-minio-8080: no such host"
11:38:48 toolsBucketWeb-1: level=error name=toolsBucketWeb-1 ts=2021-09-13T15:38:48.460304057Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="BaseFetcher: iter bucket: Get \"http://e2e_test_tools_bucket_web_external_prefix_and_route_prefix-minio-8080:8080/toolsBucketWeb_test/?location=\": dial tcp: lookup e2e_test_tools_bucket_web_external_prefix_and_route_prefix-minio-8080: no such host"
11:39:48 toolsBucketWeb-1: level=error name=toolsBucketWeb-1 ts=2021-09-13T15:39:48.460664847Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="BaseFetcher: iter bucket: Get \"http://e2e_test_tools_bucket_web_external_prefix_and_route_prefix-minio-8080:8080/toolsBucketWeb_test/?location=\": dial tcp: lookup e2e_test_tools_bucket_web_external_prefix_and_route_prefix-minio-8080: no such host"
11:40:48 toolsBucketWeb-1: level=error name=toolsBucketWeb-1 ts=2021-09-13T15:40:48.460676394Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="BaseFetcher: iter bucket: Get \"http://e2e_test_tools_bucket_web_external_prefix_and_route_prefix-minio-8080:8080/toolsBucketWeb_test/?location=\": dial tcp: lookup e2e_test_tools_bucket_web_external_prefix_and_route_prefix-minio-8080: no such host"
11:41:48 toolsBucketWeb-1: level=error name=toolsBucketWeb-1 ts=2021-09-13T15:41:48.461189578Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="BaseFetcher: iter bucket: Get \"http://e2e_test_tools_bucket_web_external_prefix_and_route_prefix-minio-8080:8080/toolsBucketWeb_test/?location=\": dial tcp: lookup e2e_test_tools_bucket_web_external_prefix_and_route_prefix-minio-8080: no such host"
11:42:48 toolsBucketWeb-1: level=error name=toolsBucketWeb-1 ts=2021-09-13T15:42:48.460730033Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="BaseFetcher: iter bucket: Get \"http://e2e_test_tools_bucket_web_external_prefix_and_route_prefix-minio-8080:8080/toolsBucketWeb_test/?location=\": dial tcp: lookup e2e_test_tools_bucket_web_external_prefix_and_route_prefix-minio-8080: no such host"
11:43:48 toolsBucketWeb-1: level=error name=toolsBucketWeb-1 ts=2021-09-13T15:43:48.46078491Z caller=runutil.go:101 msg="function failed. Retrying in next tick" err="BaseFetcher: iter bucket: Get \"http://e2e_test_tools_bucket_web_external_pr
        _testmain.go:83 +0x14b

goroutine 50 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000630000)
        /home/blemmenes/git/thanosgopath/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xb9
created by go.opencensus.io/stats/view.init.0
        /home/blemmenes/git/thanosgopath/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x92

goroutine 625 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0x7f9424380c68, 0x72)
        /usr/local/go/src/runtime/netpoll.go:229 +0x89
internal/poll.(*pollDesc).wait(0xc004c25800, 0x2, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc004c25800)
        /usr/local/go/src/internal/poll/fd_unix.go:402 +0x22c
net.(*netFD).accept(0xc004c25800)
        /usr/local/go/src/net/fd_unix.go:173 +0x35
net.(*TCPListener).accept(0xc00059b4b8)
        /usr/local/go/src/net/tcpsock_posix.go:140 +0x28
net.(*TCPListener).Accept(0xc00059b4b8)
        /usr/local/go/src/net/tcpsock.go:262 +0x3d
net/http.(*Server).Serve(0xc00011c0e0, {0x1659388, 0xc00059b4b8})
        /usr/local/go/src/net/http/server.go:3001 +0x394
net/http/httptest.(*Server).goServe.func1()
        /usr/local/go/src/net/http/httptest/server.go:308 +0x6a
created by net/http/httptest.(*Server).goServe
        /usr/local/go/src/net/http/httptest/server.go:306 +0x6f
```
