### ISSUE TITLE
Does thanos support more than one object storage (more than one client)?

### ISSUE THREAD

**Issue by SkrPaoWang** [thanos-io/thanos#4321]
Does thanos support more than one object storage (more than one client)?

Like I want to use both google cloud and aws for object storage.

**Comment by wiardvanrij** [comment]
Multiple backends per component? No. Implementing multiple components (i.e. twice store) with each their own backend; Sure.

Perhaps you could explain your use-case further? Use our issue template if you may :)

**Comment by SkrPaoWang** [comment]
Thank you for your response.
But what does multiple components mean? Does that having multiple thanos instance deployed in the cluster, and each one has their own backend?

**Comment by squat** [comment]
Hi @SkrPaoWang, yes, that's right. One single instance of a Thanos component cannot connect to multiple object storages simultaneously. Instead, you need to deploy multiple instances of a component, i.e. Thanos store gateway one configured against GCP and one configured against AWS, to achieve this desired effect
