### ISSUE TITLE
Thanos query component tuning

### ISSUE THREAD

**Issue by yasharne** [thanos-io/thanos#4322]
Hi
Right now, we have a Prometheus server that is working fine and is the main data source in our grafana with more than a thousand dashboards and many alert rules. 
Now I have deployed the Thanos components to the Kubernetes and want to replace the default Prometheus in our grafana with the Thanos `query-frontend`
The `query-frontend` component has 2 replicas and each of them has a resource limit of `1Gi of ram and 1 CPU core`. Here are the command-line flags for this component:
```
            - --query-frontend.compress-responses
            - --query-frontend.downstream-url=http://thanos-query-http.thanos.svc:10902
            - --query-frontend.log-queries-longer-than=5s
            - --query-range.split-interval=24h
            - --query-range.response-cache-max-freshness=1m
            - --query-range.max-retries-per-request=5
            - --query-range.response-cache-config-file=/etc/thanos/frontend.yml
            - --labels.max-retries-per-request=10
            - --labels.split-interval=12h
            - --cache-compression-type=snappy
```
And the `cache` config is:
```
    type: IN-MEMORY
    config:
      max_size: "0"
      max_size_items: 2048
      validity: "6h"
```

The `query` component has 3 replicas and each of them has a resource limit of `2Gi of ram and 2 CPU cores`. Here are the command-line flags for this component: 
```
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:10902
            - --query.replica-label=replica
            - --query.auto-downsampling
            - --query.partial-response
            - --store.response-timeout=60s
            - --query.max-concurrent=20
            - --query.max-concurrent-select=5
            - --store=prometheus-01.x.y.z:10901
            - --store=prometheus-02.x.y.z:10901
            - --store=thanos-store-grpc.thanos.svc:10901
```
When I open the `query-frontend` UI, I can get any single metric I want without any problem, but when I replace the `Prometheus` address with the `query-frontend` address in the grafana, I start to get a lot of `504` errors from the `query-frontend`. although I have enabled `partial response`:

![image](https://user-images.githubusercontent.com/7656049/121311843-0b3fdf00-c91a-11eb-8ebe-b1d8c58f2dfd.png)

 I don't see any logs inside any of `query` pods and `query-frontend` is not showing any logs as well because of #4320 
In the mean while, here is the resource usage of the `query-frontend` component:

![image](https://user-images.githubusercontent.com/7656049/121307457-41c72b00-c915-11eb-9ed4-eb36c311221b.png)

And the `query` component

![image](https://user-images.githubusercontent.com/7656049/121307403-32e07880-c915-11eb-9ab0-8033b1935980.png)

It is not even close to the resource limits.

For the final step, I execute the same query inside both `thanos query-frontend` and `prometheus`, the query is `Disk usage` of the group of servers over the last 30 days, as you see the Prometheus is responding much faster than the thanos:

![image](https://user-images.githubusercontent.com/7656049/121313026-3bd44880-c91b-11eb-8a49-a5c19de18c3f.png)

![image](https://user-images.githubusercontent.com/7656049/121313062-47277400-c91b-11eb-8182-c223c9005932.png)

**Comment by yeya24** [comment]
So what's the issue exactly? We don't have any best practices for tuning Thanos query and Thanos query frontend now.

**Comment by yasharne** [comment]
Hi @yeya24 as you see the `query` and `query-frontend` are not reaching their resource limitation but for older queries (like 2 months) they will return 503 error and there is a huge difference between Prometheus's response time and Thanos's response time (the two last screenshots)
