### ISSUE TITLE
Thanos Receiver continuously hogs memory even after stopping remote_write requests

### ISSUE THREAD

**Issue by whitleykeith** [thanos-io/thanos#4329]
**Thanos, Prometheus and Golang version used**:

Thanos: docker.io/bitnami/thanos:0.20.2-scratch-r1
Prometheus: varies

**Object Storage Provider**: S3

**What happened**: When using the Thanos Receiver to ingest data pushed from multiple Prometheus instances, the Receiver consumes more memory, as expected. However, after stopping remote_write from the Prometheus instances, we can see that each receiver pod is still consuming a lot of memory, even 6-8+ hours after the instances have stopped sending metrics to Thanos. This is long passed our configured TSDB retention time of 3h. I can see that the memory does decrease *slightly* overtime, but it's almost trivial compared to the total memory usage (6GB of memory freed compared to ~230GB being used across all pods). We also do have the shipper enabled which is why we reduced our TSDB retention. 

**What you expected to happen**: I expected the Thanos Receiver pods to peak memory usage at peak remote_write (which did happen), and then gc the memory once remote_write requests stopped (did not happen). Looking at the graph, I would expect the memory usage panel to follow a similar curve as CPU/Disk/Network

**How to reproduce it (as minimally and precisely as possible)**: Install Thanos Receiver (I used the bitnami helm chart) and configure it with a soft hashring and throw a lot of metrics at it. 

**Full logs to relevant components**: No logs but metrics 
![thanosgc](https://user-images.githubusercontent.com/21354274/121577457-875c2480-c9f7-11eb-9a5b-5fb9e7b10364.png)

**Anything else we need to know**:

Update: After leaving it for another day I see that the memory usage for the pods hasn't changed significantly. I decided to cycle one of the pods and that pod's memory usage dropped from around 50GB to 1GB.

**Comment by whitleykeith** [comment]
Quick update: I decided to switch the image from bitnami to thanosio/thanos:v0.21.1 and while I do see slightly better GC I'm still seeing the issue. 

Moreover, I added the Thanos dashboards to my Grafana to troubleshoot further and I'm seeing something a bit weird. Currently I have 4 Receiver pods that are reporting around 40GB memory usage each. This is true around 24hrs after the peak load (around 55GB/Pod) and 18hrs after disabling remote_write in the clusters sending that amount of data. Currently the only cluster the receiver is hearing from is the cluster Thanos is installed on (relatively small cluster that usually requires a few gigs of memory/receiver pod). 

![Screenshot from 2021-06-15 10-31-01](https://user-images.githubusercontent.com/21354274/122072520-a5de6900-cdc5-11eb-83d8-09cb0524dcb4.png)

Couple of observations that I saw:

1. Looks like Thanos is freeing up memory whenever it's shipping some of the data, but it's just not a lot...
2. There's roughly 1GB of data on disk that never seems to get cleaned up. Going into the pod and running `du -ch | grep M` gives me this:

```45.8M	./var/thanos/receive/default-tenant/01F87N7Z0RX9W8K1SE5QBXKA7E/chunks
84.0M	./var/thanos/receive/default-tenant/01F87N7Z0RX9W8K1SE5QBXKA7E
52.6M	./var/thanos/receive/default-tenant/01F87W3P885A27XPC4RE2AF8NS/chunks
93.2M	./var/thanos/receive/default-tenant/01F87W3P885A27XPC4RE2AF8NS
110.3M	./var/thanos/receive/default-tenant/chunks_head
24.8M	./var/thanos/receive/default-tenant/wal/checkpoint.00000395
672.3M	./var/thanos/receive/default-tenant/wal
959.8M	./var/thanos/receive/default-tenant
959.8M	./var/thanos/receive
959.8M	./var/thanos
```

I'm assuming this is just expected behavior. The prometheus currently writing to the receiver has two pods so I'm thinking that's the reason for the two chunks and that there aren't any chunks from the now-deleted clusters sitting on disk. 

3. Looking at the Thanos mixin dashboard for Receive, I can see that the memory usage panel that leverages the go metrics shows this:

![Screenshot from 2021-06-15 10-29-54](https://user-images.githubusercontent.com/21354274/122074721-716bac80-cdc7-11eb-8225-93cac338f2bc.png)

This memory usage is around what I would expect from the Receiver so I'm confused as to why each pod is consuming 40GB if the go metrics are only showing around 2-3 GB per pod (I have no other containers running with the receiver pods).

**Comment by whitleykeith** [comment]
adding some pprof captures to aid in debugging per slack convo

[before_free_in_use.pdf](https://github.com/thanos-io/thanos/files/6711741/before_free_in_use.pdf)
[before_free_alloc.pdf](https://github.com/thanos-io/thanos/files/6711742/before_free_alloc.pdf)
[before_free_alloc_objects.pdf](https://github.com/thanos-io/thanos/files/6711743/before_free_alloc_objects.pdf)
[before_free_inuse_objects.pdf](https://github.com/thanos-io/thanos/files/6711744/before_free_inuse_objects.pdf)
[after_free_inuse_objects.pdf](https://github.com/thanos-io/thanos/files/6711745/after_free_inuse_objects.pdf)
[after_free_inuse_space.pdf](https://github.com/thanos-io/thanos/files/6711746/after_free_inuse_space.pdf)
[after_free_alloc_objects.pdf](https://github.com/thanos-io/thanos/files/6711747/after_free_alloc_objects.pdf)
[after_free_alloc_space.pdf](https://github.com/thanos-io/thanos/files/6711748/after_free_alloc_space.pdf)

**Comment by chiragg6** [comment]
@whitleykeith hi,  
I am also facing the same issue. Any solution did you got.

**Comment by whitleykeith** [comment]
@chiragg6 nope, never found a fix. I tried using `GODEBUG=madvdontneed=1` as that seemed to be a fix for similar issues but no dice

**Comment by K890** [comment]
I am using version `v0.28.0` and still facing the exact issue mentioned here. 
I am running thanos receive component with HPA with 8GB as requested memory. With ~75 requests per seconds from my prometheus instances, there are 4 thanos-receive pods running with ~7GB of memory consumption. With every new prometheus instances, ~5 requests per seconds increase in seen on thanos and the memory consumption goes up by ~500MB per thanos-receive replica. 

1. Is this an expected behavior?
2. Is there any other way I can push prometheus metrics from multiple servers to a single server?

**Comment by fpetkovski** [comment]
In case @whitleykeith  is still interested in this issue: there is no compactor running in the receiver, which means data from the head is flushed to disk during writes. If writes stop, data will be held in memory indefinitely.

Since this issue was opened, we've added TSDB pruning to the receiver to deal with this problem: https://thanos.io/tip/components/receive.md/#tenant-lifecycle-management.

**Comment by K890** [comment]
Based on the document, `tsdb.retention` deals with a situation when the incoming data stops and we want to flush the in-memory data to objectstorage. But if the data is continuously coming in, is the current memory usage normal(details in previous comment)? Is the data held in-memory to faster querying purpose?

In my understanding, we should be able to write the incoming data to the disk and send it to object storage periodically. Not sure of the reason to hold data in-memory.

**Comment by fpetkovski** [comment]
I think your comment is not really related to the original problem, so it would have been best to open a new issue. But in general, memory will be proportional to the amount of data sent, and the increase in memory looks reasonable. You can also use Prometheus federation to centralize data, or use a Thanos Query to connect directly to those Prometheus instances without remote writing.
