### ISSUE TITLE
query:  high memory usage

### ISSUE THREAD

**Issue by mbeck3026** [thanos-io/thanos#4330]
**Thanos, Prometheus and Golang version used**:

thanos, version 0.20.1 (branch: HEAD, revision: 10023e4882414baa56a8955057f2678f1e724e8c)
  build user:       circleci@22b1af3c9a07
  build date:       20210430-12:46:55
  go version:       go1.16.3
  platform:         linux/amd64

**Object Storage Provider**:
OCI object store (S3 compatible)

**What happened**:

We run a thanos v20.1 cluster with 3 receivers, the number of series it handles is ~ 8.5M.
We have 3 queriers  that use the receivers as stores ( additionally with one objectstore gateway and 2 thanos rulers ). 
To keep the queriers from running out of memory we have to allocate them > 70GB each, and their performance from the web UI is very sluggish (particularly when autocomplete is enabled).  The memory is consumed as soon as the pod comes online  and will peak typically right after initialization, so not a memory leak.   

I assume we are doing something incorrectly as another team in our organization uses thanos in a sidecar deployment and their  querier averages  < 100MB of ram and is much more responsive when running on approximately half our dataset.  Is there anything I should be looking for in the configuration that might cause issues?  Could it be high label cardinality on metrics?  
Any suggestions?

Thanks.

**What you expected to happen**:

Queriers are responsive and use much lower memory

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

The heap profile: https://share.polarsignals.com/14a6d90/
Alloc pprof:          https://share.polarsignals.com/bbd5c9a/

The heap profile **appears** to show that the memory is used primarily by receiving messages on the grpc store api.
The grpc rate on the queriers is also quite high.

Looking at the metrics the cardinality looks like this:

```
Highest cardinality labels:
60331 __name__
20199 id
14957 name
14023 mountpoint
8121 container_id
7940 pod
6627 uid
5434 device
3963 secret
3592 instance
3335 address
3198 topic
3183 replicaset
2809 pod_ip
2446 label_pod_template_hash
1806 label_modifiedAt
1738 dialer_name
1626 created_by_name
1589 scrape_job
1479 image

Highest cardinality metric names:
87222 goldpinger_peers_response_time_s_bucket
70362 container_tasks_state
56151 container_memory_failures_total
31260 kubelet_runtime_operations_duration_seconds_bucket
29383 storage_operation_duration_seconds_bucket
28966 kafka_cluster_partition_atminisr
28887 kafka_log_log_numlogsegments
28839 kafka_cluster_partition_underreplicated
26827 kube_pod_status_phase
26579 kafka_cluster_partition_underminisr
23744 apiserver_request_duration_seconds_bucket
23729 kafka_log_log_size
21906 container_fs_writes_total
21823 container_fs_reads_total
21339 kube_pod_container_status_waiting_reason
18694 kafka_log_log_logstartoffset
18656 node_cpu_seconds_total
18527 kubelet_docker_operations_duration_seconds_bucket
18246 kube_pod_container_status_terminated_reason
18078 kube_pod_container_status_last_terminated_reason
```

The heap memory appears to me (not a go memory expert - maybe this is normal ) to vary significantly over the runtime of the pod:

![querier-memory](https://user-images.githubusercontent.com/423850/121579797-4b21c780-c9e9-11eb-8339-d28f68c1fc7b.png)

I also wondered if this could be caused by high metric churn.  We have multiple k8s cluster with different versions of exporters pushing metrics to our receivers.  Some metrics have changed label names in those different versions so we may have the same metric name with mismatching label sets, constantly being pushed.  I wasn't sure if that would cause a grpc call to the querier to update its auto-completion metadata.  

I would appreciate any help.

Thank you.

**Comment by mbeck3026** [comment]
Sorry posted before I was finished.
Alloc pprof:  https://share.polarsignals.com/bbd5c9a/

The heap profile **appears** to show that the memory is used primarily by receiving messages on the grpc store api.
The grpc rate on the queriers is also quite high.

Looking at the metrics the cardinality looks like this:

```
Highest cardinality labels:
60331 __name__
20199 id
14957 name
14023 mountpoint
8121 container_id
7940 pod
6627 uid
5434 device
3963 secret
3592 instance
3335 address
3198 topic
3183 replicaset
2809 pod_ip
2446 label_pod_template_hash
1806 label_modifiedAt
1738 dialer_name
1626 created_by_name
1589 scrape_job
1479 image

Highest cardinality metric names:
87222 goldpinger_peers_response_time_s_bucket
70362 container_tasks_state
56151 container_memory_failures_total
31260 kubelet_runtime_operations_duration_seconds_bucket
29383 storage_operation_duration_seconds_bucket
28966 kafka_cluster_partition_atminisr
28887 kafka_log_log_numlogsegments
28839 kafka_cluster_partition_underreplicated
26827 kube_pod_status_phase
26579 kafka_cluster_partition_underminisr
23744 apiserver_request_duration_seconds_bucket
23729 kafka_log_log_size
21906 container_fs_writes_total
21823 container_fs_reads_total
21339 kube_pod_container_status_waiting_reason
18694 kafka_log_log_logstartoffset
18656 node_cpu_seconds_total
18527 kubelet_docker_operations_duration_seconds_bucket
18246 kube_pod_container_status_terminated_reason
18078 kube_pod_container_status_last_terminated_reason
```

The heap memory appears to me (not a go memory expert - maybe this is normal ) to vary significantly over the runtime of the pod:

![querier-memory](https://user-images.githubusercontent.com/423850/121579797-4b21c780-c9e9-11eb-8339-d28f68c1fc7b.png)

I also wondered if this could be caused by high metric churn.  We have multiple k8s cluster with different versions of exporters pushing metrics to our receivers.  Some metrics have changed label names in those different versions so we may have the same metric name with mismatching label sets, constantly being pushed.  I wasn't sure if that would cause a grpc call to the querier to update its auto-completion metadata.  

I would appreciate any help.

Thank you.

**Comment by wiardvanrij** [comment]
I think we have spoken on Slack, thanks for creating this issue! 👍

**Comment by kidharb** [comment]
I'm seeing high CPU and memory (50gb) on version 20.2 of query. I don't have an object store. I picked up this issue when one of the teammates said his Grafana dashboard was taking very long to load after changing to the Thanos endpoint. He changed it back (Directly to Prometheus) and it was responsive again.
I am still investigating this issue and will be angle to provide more info if required

**Comment by Shinhye-Yun** [comment]
> notified of this issue when one of the teammates said his Grafana dashboard was taking very long(20 seconds) to load after changing to the Thanos endpoint. He changed it back (Directly to Prometheus) and it was responsive(<2 seconds) again. I have 3 Thanos sidecars and 1 Query (query is consuming high CPU and high memory).
> I am still investigating this issue and want to downgrade as part of my investigation.
> This is the first version of Thanos I'm running so I don't have a baseline to compare to.

I know it's almost a year ago, but were you able to find any solution? I am facing same issue when try to call same metrics with specific label.

**Comment by kidharb** [comment]
@Shinhye-Yun I did not find a solution. I eventually migrated away from Thanos / Prometheus to VictoriaMetrics https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html
