### ISSUE TITLE
Thanos queirier unable to connect to sidecar

### ISSUE THREAD

**Issue by ChristopherVishoot** [thanos-io/thanos#4331]
**Thanos, Prometheus and Golang version used**:
thanos: charts.bitnami.com/bitnami 3.17.8
prometheus-operator with sidecar: charts.bitnami.com/bitnami6.0.0
sidecar image: docker.sel.inc/bitnami/thanos:0.20.2-scratch-r1
--

**What happened**:
I have successfully installed:
* Thanos sidecars for the prometheus agents
* Storage Gateway pointing to the s3 storage 
* CNAB to install prometheus + thanos sidecar on VM

Currently, I am trying to point the Thanos Querier to the Thanos sidecar. For the sake of simplicity, I have even installed the kube-prometheus chart on the same namespace as the Thanos Chart.

I am able to see that the storage unit has been successfully installed through the Query logs below:

`level=info ts=2021-06-10T17:01:27.335676921Z caller=bucket.go:555 msg="loaded new block" elapsed=72.93339ms id=01F7VDVKVPG1HC716MKZ7CH9JA
level=info ts=2021-06-10T17:04:27.247103408Z caller=fetcher.go:476 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=112.484546ms cached=35 returned=35 partial=0`

However, when I try to point to the corresponding Thanos sidecar, I continously receive the following error message:
`Error while dialing dial tcp: lookup prometheus-kube-prometheus-prometheus.thanos.svc.cluster.local on 10.43.0.10:53: no such host\"" address=prometheus-kube-prometheus-prometheus.thanos.svc.cluster.local:10901`

I have verified that the hostname: prometheus-kube-prometheus-prometheus.thanos.svc.cluster.local is resolvable through a nslookup box on the same thanos namespace.

Also, when going to the Thanos UI, and clicking on the stores, it says that there are no stores registered to that Thanos instance.
![image](https://user-images.githubusercontent.com/56844141/121589776-54f8fa00-c9ec-11eb-9034-204b53bd053c.png)

**What you expected to happen**:
The Thanos instance to pick up the storage unit which the Querier can see.

**How to reproduce it (as minimally and precisely as possible)**:
helm install my-release bitnami/thanos
Here are the helm values that I am using for the helm install thanos chart:
`---
  existingObjstoreSecret: "thanos-objstore-config"
  metrics: 
    enabled: "true"
  querier: 
    dnsDiscovery: 
      enabled: "true"
      sidecarsNamespace: "thanos"
  query: 
    logLevel: "debug"
    stores: "{prometheus-kube-prometheus-prometheus.thanos.svc.cluster.local:10901,thanos-storegateway.thanos:10901}"
  queryFrontend: 
    ingress: 
      enabled: "true"
      hostname: "thanos.appstest.ad.selinc.com"
      tls: "true"
  storegateway: 
    enabled: "true"`

**Full logs to relevant components**:

Thanos Log Qurier.
[thanos-querier.log](https://github.com/thanos-io/thanos/files/6634115/thanos-querier.log)
Thanos Sidecar Logs
[thanos-sidecar-logs.log](https://github.com/thanos-io/thanos/files/6634124/thanos-sidecar-logs.log)

**Comment by yeya24** [comment]
@ChristopherVishoot I don't have any experience about the bitnami chart. Can you check that service `prometheus-kube-prometheus-prometheus` exists in `thanos` namespace and port 10901 is exposed?

**Comment by ChristopherVishoot** [comment]
![image](https://user-images.githubusercontent.com/56844141/121602140-b8d6ef00-c9fb-11eb-9af4-1c9416dea35a.png)
Alright, so I have validated the service, and then made sure that the correct port was exposed.
![image](https://user-images.githubusercontent.com/56844141/121602202-cee4af80-c9fb-11eb-9abc-631194400e01.png)

I have also updated the Quirer to point to the service endpoint with the correct port, and yet the same error is still occurring (unable to find the host).

The new endpoint:
kube-prometheus-prometheus-thanos.thanos:10901

Other things of interest: 
When I look at the pod containing the thanos sidecar, I notice that it isn't exposing the grpc 10901 port.
![image](https://user-images.githubusercontent.com/56844141/121602973-ef613980-c9fc-11eb-845b-04ad6ee90d43.png)


I also have noticed that the bitnami chart for the thanos service is creating a headless service.

**Comment by yeya24** [comment]
Well, I am not sure. I don't understand why it is configured as a headless service. A normal service with clusterIP would work I think. You can try it and see if it works for you. 
It would be better if you can also open an issue on the bitnami's repo.

**Comment by ChristopherVishoot** [comment]
OK! I'll go ahead and just ask the Bitnami folks about this. Even I'm confused to why they did that.
