### ISSUE TITLE
Is there any way to query downsampling data in Thanos?

### ISSUE THREAD

**Issue by SkrPaoWang** [thanos-io/thanos#4333]
Is there any way to query downsampling data in Thanos?
Does thano query provide this functionality?

**Comment by ianbillett** [comment]
@SkrPaoWang I'm afraid I don't fully understand your question. Please can you try to provide more context on the problem you are trying to solve so we can help you get an answer :+1:

**Comment by yeya24** [comment]
In the thanos query UI, you can set the max downsample level. Please take a look at the docs as well https://thanos.io/tip/components/query.md/#auto-downsampling if you'd like to access API directly.

I will close this issue. In case you have more questions, feel free to reopen it.
