### ISSUE TITLE
Large Go routines spikes on cancelled/flaky gRPC requests.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#4335]
Both receivers and Querier which suggests proxy stream logic:

![image](https://user-images.githubusercontent.com/6950331/121652680-ce97f300-ca93-11eb-8b82-28f5754eb236.png)

https://share.polarsignals.com/7759cdd/
https://share.polarsignals.com/c5ae02f/

Store too, but I believe it's different since those are not aligned and pointing to memcache. (Note: Spike is actually from those Read poll ones (currently 11). The 250 number is stable).

![image](https://user-images.githubusercontent.com/6950331/121652952-19196f80-ca94-11eb-8985-add5ac764b50.png)

https://share.polarsignals.com/21a658c/

**Comment by bwplotka** [comment]
NOTE: It does not impact the resources much

**Comment by wiardvanrij** [comment]
I saw this and I knew I had something like this a while ago. Just perhaps for inspiration (as I don't think they ARE related) i'll drop this here: https://github.com/thanos-io/thanos/issues/2872
