### ISSUE TITLE
Thanos Component Mixin Dashboards should show CPU & Memory limits.

### ISSUE THREAD

**Issue by ianbillett** [thanos-io/thanos#4338]
### Is your proposal related to a problem?

Debugging out internal monitoring stack with @bwplotka using the Thanos mixin dashboards - we struggled to tell if compoments were exceeding their allowed threshold because these are not present in the dashboards by default.

(Write your answer here.)

### Describe the solution you'd like

Add 'standard' expected metrics to the component dashboards:
* CPU limits & requests.
* Memory limits & requests.

(Describe your proposed solution here.)

### Describe alternatives you've considered

None.

### Additional context

There will almost certainly be some really good example of these out in the wild. Two starting points:
* https://github.com/rhobs/configuration/blob/main/observability/dashboards/telemeter.libsonnet
* https://github.com/kubernetes-monitoring/kubernetes-mixin

**Comment by ianbillett** [comment]
Suggested labels: `good first issue`, `component: mixins`

**Comment by wiardvanrij** [comment]
As this requires more metrics than Thanos is actually exposing (I.e. node / kube-api metrics) - Would this not make sense to leave this at a totally different dashboard? 

I personally have dashboards like this:

![image](https://user-images.githubusercontent.com/5786097/121910732-6107f300-cd2f-11eb-950d-94f8a148ed79.png)

and 

![image](https://user-images.githubusercontent.com/5786097/121910801-72e99600-cd2f-11eb-8fec-1dd6a73c8e6b.png)

With a global view like:

![image](https://user-images.githubusercontent.com/5786097/121910857-7f6dee80-cd2f-11eb-90c3-a346f64b581e.png)


These dashboards are (correct me if I'm wrong) also included in the Prometheus operator. If we would include these stats, you create a dependency on those metrics but also (I think) certain rules required for it.

**Comment by fktkrt** [comment]
Yes, these are included in the kubernetes-mixin and that is included in promethues-operator in a generalised fashion. This means that you have to choose the appropriate dashboard for these stats, then filter for the namespace in question to see these metrics for everything under that ns. 

Some tool has similar metrics on their operational overview dashboard to make troubleshooting performance issues easier, Loki comes to mind, if I am right.

**Comment by yeya24** [comment]
IMO these CPU & Memory limits are specific to Kubernetes env. The dashboards from Kubernetes mixin are sufficient for this use case and I feel it is not a good idea to add them to Thanos mixin.

**Comment by bwplotka** [comment]
I think mixin is fine, the only thing is that probably we should not reuse the same dashboards we have now. 

Reason is that there is a difference between monitoring dashboards and deep down quick debugging dashboards which can have 100 graphs.

**Comment by ianbillett** [comment]
@wiardvanrij & @yeya24 you both raise an important point I hadn't considered. For the core Thanos project to remain environment neutral we can't introduce environment-specific dependencies into the mixin, we can only use metrics that are exported from the core project itself.

I still think there is scope to include relevant CPU & memory information from the `go_*` family of metrics, but I'm not sure exactly what quite yet.

@bwplotka I think you meant to post that comment in https://github.com/thanos-io/thanos/issues/4401 :) (which I hadn't yet created during the meeting yesterday).
