### ISSUE TITLE
Store: Healthy state but unable to respond to queries

### ISSUE THREAD

**Issue by wiardvanrij** [thanos-io/thanos#4341]
Version: 17.2

It started with an error:
```
2021-06-14 08:23:55	Unsolicited response received on idle HTTP channel starting with "HTTP/1.1 204 No Content\r\nConnection: close\r\n\r\n"; err=<nil>
```

Not sure if this error log is related, but that Store now also goes into a state where every query takes 2 minutes (and fails), which is in line with our Query Timeout on the Querier (2m) a few minutes later.

![image](https://user-images.githubusercontent.com/5786097/121884700-8555d680-cd13-11eb-9719-72414e560f8e.png)

We have had this issue before, but I couldn't figure out what was happening. Normally I would have killed the store in question. Now I've tried to debug further.  I started with some GRPC calls. I.e.:

```
grpcurl -plaintext -import-path=/Users/wiard/go/src/github.com/gogo/protobuf/ -import-path=pkg/ -proto=store/storepb/rpc.proto localhost:10901 thanos.Store/Info
```

This grpc call on `thanos.Store/Info` works perfectly on every store, even the 'bugged' store in question. 
However when I changed the method to `thanos.Store/Series`, something else happend. 
For a healthy store it would near instantly finish the request (no response, which is fine and correct). For this store in question, when doing the `thanos.Store/Series` call, it would not do anything for minutes until I just cancel it myself.

Related profiles:

goroutines: https://share.polarsignals.com/e993e10/
samples-cpu: https://share.polarsignals.com/c355425/
alloc-1: https://share.polarsignals.com/d4bb4dc/
alloc-2: https://share.polarsignals.com/a768879/
alloc-3: https://share.polarsignals.com/e7218f4/

threadcreate: https://share.polarsignals.com/963240a/ 

A note here, the raw data for thread create looks like this as I'm not seeing the 13@ 0x0 in the profile (?)
```
threadcreate profile: total 14
13 @
#	0x0

1 @ 0x103c9bb 0x103d125 0x103d3f2 0x104262b 0x10679c8 0x106f4c1
#	0x103c9ba	runtime.allocm+0x15a			/usr/local/opt/go/libexec/src/runtime/proc.go:1474
#	0x103d124	runtime.newm+0x44			/usr/local/opt/go/libexec/src/runtime/proc.go:1794
#	0x103d3f1	runtime.startTemplateThread+0xb1	/usr/local/opt/go/libexec/src/runtime/proc.go:1863
#	0x104262a	runtime.LockOSThread+0x6a		/usr/local/opt/go/libexec/src/runtime/proc.go:3845
#	0x10679c7	runtime.ensureSigM.func1+0x47		/usr/local/opt/go/libexec/src/runtime/signal_unix.go:883
```

### What I think

I think 'something' went banana's which caused the store to stay in a healthy state while it is actually broken on a part regarding Series. I.e. responding to queries. 

I also think this has to do with some form of DOS to itself in relation to Memcached. This is not the first time we have this issue, but when it does; it happens on a Monday morning. This somewhat makes sense. Cache has a TTL, since it was weekend and hardly anyone is doing queries, we hit our TTL and we basically have zero cache.
Now Monday morning, people start to hit dashboards. Not only are we not having cache, we also have to fill cache. I think hitting the stores 'cold' will result in a massive hit towards memcached and it would break something. 

I have checked our metrics regarding memcached and I don't see the behaviour here. Yes, we have some increase in cache usage (fetch/store) but it's not massive. No big spikes. Yet I still think this is very much so related to the issue nonetheless.

### FYI

As you can see in the graph, after debugging and such, I've just killed the pod containing this store and everything went back to normal

**Comment by wiardvanrij** [comment]
Still relevant I think

**Comment by Evreke** [comment]
Similar issue here with 0.18.0. The Thanos Store will no longer service requests for S3 data, but will remain healthy. Restart brings everything back to normal.

Seems that this log messages is relevant to problem - `Unsolicited response received on idle HTTP channel starting with "HTTP/1.1 204 No Content\r\nConnection: close\r\n\r\n"; err=<nil>`
