### ISSUE TITLE
Bad gateway error when Post request to Thanos api from grafana

### ISSUE THREAD

**Issue by jatindersandhu** [thanos-io/thanos#4345]
Thanos, Prometheus and Golang version used:

Thanos: 
thanos --version
thanos, version 0.17.2 (branch: rhaos-4.7-rhel-8, revision: e08776699e995facd3260ebfec4c29c4d3bd4943)
  build user:       root@3d4eeeb5b403
  build date:       20210521-04:48:20
  go version:       go1.15.7
  platform:         linux/amd64
Prometheus: varies

Object Storage Provider:  not know

What happened: We have Thanos for our open shift environment. As our environment run as Openshift multiple tenants. We use thanos to give POD level metrics to different tenants. Tenant can only see the their namespace metrics. For that we have thanos port and thnos tenant port (9092). Tenant get metrics on 9092 by using the token belong to their namespace. Each tenant use grafana as see metrics and grafana alerts for alerting. When thanos is configred as data source in grafana it is working fine for GET requests but POST request come with Bad  request. 
Here is GET and POST result on grafana.
![122049672-addfde00-cdb0-11eb-9c5a-3a2348c41f5a](https://user-images.githubusercontent.com/45833435/122221590-68d6ad00-ce7f-11eb-8a2d-bf3f2e0fafbf.png)
![122050658-aa992200-cdb1-11eb-8b14-ab81aac4c97e](https://user-images.githubusercontent.com/45833435/122221593-696f4380-ce7f-11eb-87be-d60e88d90c2e.png)

What you expected to happen: I expected both GET and POST should work. As grafana usually send POST request for Alerts so Alerts are not working for tenants. Although we tested the GET and POST directly on Thanos port 9090 , it is working but it not working teanent services.. Thanos main port is not exposed only tenant service and port (9092) is exposed.

How to reproduce it (as minimally and precisely as possible): Install thanos tenant port service and use grafana 8 beta version to test the data source for both GET and POST request.

Full logs to relevant components: No logs , 

Anything else we need to know:

This is critical for us , may be we are missing minor configuration when using tenant service.

**Comment by yeya24** [comment]
As the grafana issue mentioned, how is your prom label proxy configured?
