### ISSUE TITLE
query: exemplar support file-sd

### ISSUE THREAD

**Issue by hanjm** [thanos-io/thanos#4346]
Current [`--exemplar`](https://github.com/thanos-io/thanos/blob/main/cmd/thanos/query.go#L109) endpoint flag only support dns-sd, 
Could we need implement file-sd  like [`--store.sd-files`](https://github.com/thanos-io/thanos/blob/main/cmd/thanos/query.go#L119) endpoint flag?

**Comment by hanjm** [comment]
seems discovery api is refactoring. #2600

**Comment by yeya24** [comment]
@hanjm We have an ongoing [pr](https://github.com/thanos-io/thanos/pull/4282) to support auto-discovery for store type, which means you just need to specify the `endpoint` of stores. If the store itself implements Exemplar API (like Sidecar and Receiver), it will be enabled automatically.

But this doesn't touch the file sd part. Do you think that proposal solves your problem?

**Comment by hanjm** [comment]
@yeya24 Your work for exemplar is great, thank you.
file-sd is very useful in some scene. some cloud provider place deployment in diffrent k8s cluster, so cannot use k8s headless service. I deploy thanos cluster(with 70+ sidecar,  use --store.sd-files discovery sidecar endpoint.
recently, i try to introduce exemplar feature in metrics system. but --exemplar can not use file-sd. I try to add support on fork branch with repeating store.file-sd code.

when #4282 is merged, add file-sd support will be more easy.
