### ISSUE TITLE
Thanos compactor repeats compacting and repair of first bucket 

### ISSUE THREAD

**Issue by Robbie558** [thanos-io/thanos#4347]
**Thanos, Prometheus and Golang version used**:
Thanos:  0.17.2 (Go: 1.5)
Prometheus: 2.1.1 (Go: 1.10)
Both are running as native processes on the same host.

**Object Storage Provider**:
S3 Storage: Minio

**What happened**:
Compaction and downsampling of data fails to occur and the S3 storage bloats as the compactor process continually repairs and and compacts the first bucket it retrieves.  We have manually cleared down the buckets from S3 to ensure it is not an issue particular to a buckets content, but each time it gets stuck in a loop as seen in the logs.  

The repetition can be seen in the bucket explorer, appearing as a stack of buckets against the same time period all with the source `compactor.repair` and the same `numSamples`, `numSeries` and `numChunks`.

**What you expected to happen**:
Thanos compactor repairs a bucket, compacts it and moves on to the next, with down sampling eventually kicking in.  As a worst case scenario I'd be okay with it marking the bucket as bad and moving on.

**How to reproduce it (as minimally and precisely as possible)**:
Unclear, our process configurations are as follows:
**Prometheus**
`/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus --storage.tsdb.retention=7d --web.console.libraries=/etc/prometheus/console_libraries --web.console.templates=/etc/prometheus/consoles --web.listen-address=0.0.0.0:9090 --web.external-url= --storage.tsdb.max-block-duration=2h --storage.tsdb.min-block-duration=2h
`
**Thanos SIdecar:**
`/opt/thanos/current/thanos sidecar --grpc-address=0.0.0.0:10901 --http-address=0.0.0.0:10902 --log.format=logfmt --log.level=info --objstore.config-file=/opt/thanos/thanos-objstore-config.yml --prometheus.url=http://127.0.0.1:9090 --tsdb.path=/var/lib/prometheus`

**Thanos Compactor**
`/opt/thanos/current/thanos compact --log.level=info --log.format=logfmt --http-address=0.0.0.0:10903 --objstore.config-file=/opt/thanos/thanos-objstore-config.yml --data-dir=/var/thanos/compact --consistency-delay=2h --retention.resolution-raw=1d --retention.resolution-5m=14d --retention.resolution-1h=30d --block-sync-concurrency=20 --compact.concurrency=1 --wait --delete-delay=48h`

**Full logs to relevant components**:

<details>Logs
<p>

```
level=info ts=2021-06-16T10:38:28.807247675Z caller=compact.go:953 msg="start of compactions"
level=info ts=2021-06-16T10:38:28.807510473Z caller=compact.go:705 group="0@{clusterName=\"ExternalServices\"}" groupKey=0@12213061260468943465 msg="compaction available and planned; downloading blocks" plan="[0xc0009802d0 0xc000980000 0xc0000fe5a0 0xc0000ca3c0]"
level=info ts=2021-06-16T10:38:51.645518677Z caller=compact.go:629 msg="Repairing block broken by https://github.com/prometheus/tsdb/issues/347" id=01F83BXDX8DTMQB86PY6FFDRYC err="invalid, but reparable block /var/thanos/compact/compact/0@12213061260468943465/01F83BXDX8DTMQB86PY6FFDRYC: found 84 chunks outside the block time range introduced by https://github.com/prometheus/tsdb/issues/347"
level=info ts=2021-06-16T10:39:05.38351858Z caller=fetcher.go:458 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=337.66267ms cached=91 returned=91 partial=292
level=info ts=2021-06-16T10:39:36.417797163Z caller=compact.go:662 msg="uploading repaired block" newID=01F8A6EJZJJ7BS6SSCMQ8JP5EH
level=warn ts=2021-06-16T10:39:36.41813296Z caller=s3.go:399 msg="could not guess file size for multipart upload; upload might be not optimized" name=debug/metas/01F8A6EJZJJ7BS6SSCMQ8JP5EH.json err="unsupported type of io.Reader"
level=info ts=2021-06-16T10:39:37.885505196Z caller=compact.go:667 msg="deleting broken block" id=01F83BXDX8DTMQB86PY6FFDRYC
level=warn ts=2021-06-16T10:39:37.891513651Z caller=block.go:143 msg="requested to mark for deletion, but file already exists; this should not happen; investigate" err="file 01F83BXDX8DTMQB86PY6FFDRYC/deletion-mark.json already exists in bucket"
```
</p>
</details>

**Anything else we need to know**:

**Environment**:
- OS: <pre>Ubuntu 16.04.4 LTS&quot;</pre>
- Kernel: 4.4.0-210-generic
- Disk: >500GB free

We tried processing this data alongside data produced by Prometheus on our K8S cluster, but had to break out the data to a separate S3 bucket and run a separate compactor to identify this issue.

**Comment by shovelend** [comment]
Please reopen, issue is still occurring.
