### ISSUE TITLE
receiver:Error happens when Thanos receiver restart

### ISSUE THREAD

**Issue by btdan** [thanos-io/thanos#4355]
I start thanos receive with the following command:
**nohup thanos receive \
    --tsdb.path "/00_data/newData2"  \
    --grpc-address 0.0.0.0:10907 \
    --http-address 0.0.0.0:10909 \
    --receive.replication-factor 1 \
    --label "receive_replica=\"0\"" \
    --label "receive_cluster=\"chaosuan\"" \
    --receive.local-endpoint 127.0.0.1:10907 \
    --receive.hashrings-file /aiops/hashring.json  \
    --remote-write.address 0.0.0.0:10908 \
--objstore.config-file  "/aiops/bucket.yml"  > /thanos_receive.log 2>&1 &**

And it is started successfully. However, When I want to restart it. I will kill it at first,just as follows:
First, use the command  
**ps aux|grep thanos** 
To get the pid of thanos receive process.
Second, use the comand 
**kill -9 pid**
To kill the thanos receive process successfully.

But when I restart it, I get the log infomation as follows:

**level=error ts=2021-06-18T02:14:17.844919669Z caller=handler.go:351 component=receive component=receive-handler err="store locally for endpoint 127.0.0.1:10907: get appender: TSDB not ready" msg="internal server error"
level=error ts=2021-06-18T02:14:17.949085916Z caller=handler.go:351 component=receive component=receive-handler err="store locally for endpoint 127.0.0.1:10907: get appender: TSDB not ready" msg="internal server error"
level=error ts=2021-06-18T02:14:18.053413114Z caller=handler.go:351 component=receive component=receive-handler err="store locally for endpoint 127.0.0.1:10907: get appender: TSDB not ready" msg="internal server error"
level=error ts=2021-06-18T02:14:18.157106897Z caller=handler.go:351 component=receive component=receive-handler err="store locally for endpoint 127.0.0.1:10907: get appender: TSDB not ready" msg="internal server error"
level=error ts=2021-06-18T02:14:18.260468876Z caller=handler.go:351 component=receive component=receive-handler err="store locally for endpoint 127.0.0.1:10907: get appender: TSDB not ready" msg="internal server error"
level=error ts=2021-06-18T02:14:18.364044131Z caller=handler.go:351 component=receive component=receive-handler err="store locally for endpoint 127.0.0.1:10907: get appender: TSDB not ready" msg="internal server error"
level=error ts=2021-06-18T02:14:18.467160187Z caller=handler.go:351 component=receive component=receive-handler err="store locally for endpoint 127.0.0.1:10907: get appender: TSDB not ready" msg="internal server error"
level=error ts=2021-06-18T02:14:18.571137629Z caller=handler.go:351 component=receive component=receive-handler err="store locally for endpoint 127.0.0.1:10907: get appender: TSDB not ready" msg="internal server error"
level=error ts=2021-06-18T02:14:18.67459527Z caller=handler.go:351 component=receive component=receive-handler err="store locally for endpoint 127.0.0.1:10907: get appender: TSDB not ready" msg="internal server error"
level=error ts=2021-06-18T02:14:18.778662786Z caller=handler.go:351 component=receive component=receive-handler err="store locally for endpoint 127.0.0.1:10907: get appender: TSDB not ready" msg="internal server error"
level=error ts=2021-06-18T02:14:18.88193053Z caller=handler.go:351 component=receive component=receive-handler err="store locally for endpoint 127.0.0.1:10907: get appender: TSDB not ready" msg="internal server error"
level=error ts=2021-06-18T02:14:18.985214245Z caller=handler.go:351 component=receive component=receive-handler err="store locally for endpoint 127.0.0.1:10907: get appender: TSDB not ready" msg="internal server error"
level=error ts=2021-06-18T02:14:19.088658691Z caller=handler.go:351 component=receive component=receive-handler err="store locally for endpoint 127.0.0.1:10907: get appender: TSDB not ready" msg="internal server error"**

Thanks very much

**Comment by ianbillett** [comment]
Hey @btdan - from logs files it clearly looks like the TSDB gets into an unrecoverable state after you send the `SIGKILL` signal.

To be honest, I'm not really surprised by that. Processes cannot catch or act upon `SIGKILL` - they just get killed right in the middle of whatever they are doing and don't get a chance to clean-up.

Thanos [catches](https://github.com/thanos-io/thanos/blob/d587ac90f67da1894af8ef62547d8e0dfb3cc5f6/cmd/thanos/main.go#L164) and cleans up on `SIGTERM`, which 
you would reasonably expect to proceed `SIGKILL` with some grace period.

In my opinion there is nothing out of the ordinary here, this is kind of what we expect to happen when we forcibly kill Thanos without giving it the chance to clean up.

Since Thanos consumes the TSDB from the upstream Prometheus project, I would suggest you raise the issues there if you want to ask further questions.
