### ISSUE TITLE
compactor: add concurrent downsampling

### ISSUE THREAD

**Issue by GiedriusS** [thanos-io/thanos#4363]
### Is your proposal related to a problem?

It kind of is, downsampling isn't the fastest.

### Describe the solution you'd like

A flag such as `--downsample.concurrency=` on Thanos Compact. Then, a specified number of would-be downsampled concurrently.

### Describe alternatives you've considered

Running multiple Thanos Compact instances working on different external labels but it's a pain to set up and maintain.

### Additional context

N/A

**Comment by pawanakhil** [comment]
hey @GiedriusS , I am new to this repo as it's labeled easy can I take this up ? It would be great if you can guide me through this.

**Comment by yeya24** [comment]
I will take this one as we need this feature.
