### ISSUE TITLE
[docs] Fix broken links in the Getting Started page

### ISSUE THREAD

**Issue by atarax665** [thanos-io/thanos#4364]
**What happened**:

While going through [Getting Started](https://thanos.io/tip/thanos/getting-started.md/) page of Thanos Doc website I found a list of broken links. Here they are:

| Hyperlinked Text     | URL |
| ----------- | ----------- |
| MAINTAINERS.md     | https://thanos.io/tip/MAINTAINERS.md       |
| CONTRIBUTING.md   | https://thanos.io/tip/CONTRIBUTING.md        |
| here   | https://thanos.io/tip/examples/dashboards/dashboards.md        |
| here   | https://thanos.io/tip/scripts/quickstart.sh        |
| alerts  | https://thanos.io/tip/examples/alerts/alerts.md       |
| on GitHub here   | https://github.com/thanos-io/thanos/edit/main/docs/thanos/getting-started.md        |

This is happening because the following markdown files are not available in the ```docs``` directory. 

**Proposed Solution**:

I can make a copy of the required markdown files and add them to the docs folder. So that they can be rendered successfully on the website.

**Comment by ianbillett** [comment]
Thanks for raising this @atarax665 :+1:  Would you please mind raising a PR and fixing these links? Thanks :hugs:

**Comment by matej-g** [comment]
Just noticed this as I was browsing the 'Getting Started' page. Has this been picked up? If not I am happy to put together a fix.
