### ISSUE TITLE
Bucket rewrite: able to mark original blocks for deletion after new blocks are created

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#4387]
### Is your proposal related to a problem?

Bucket rewrite tool supports block deletion and relabeling. It creates a new block and the original block is left unchanged. Usually, the old block can be removed. But it requires another step to mark the original block.

### Describe the solution you'd like

It would be handy to have a flag to mark the original blocks for deletion after the new blocks created successfully. This flag should work only in none dry run mode.

**Comment by yeya24** [comment]
Thoughts? @bwplotka @onprem @GiedriusS

**Comment by GiedriusS** [comment]
Makes total sense. For some reason I thought that we were doing this automatically already

**Comment by yeya24** [comment]
Assign this myself.

**Comment by GiedriusS** [comment]
Fixed in https://github.com/thanos-io/thanos/pull/4392.
