### ISSUE TITLE
Thanos query timeout but thanos still working on?[Thnaos-query][v 0.1.5.0]

### ISSUE THREAD

**Issue by renchili** [thanos-io/thanos#4390]
**Thanos, Prometheus and Golang version used**:

  thanos, version 0.15.0 (branch: HEAD, revision: fbd14b49f95e7543883fedf9381a21127d4dda2b)
  build user:       root@d35b081d3e19
  build date:       20200907-09:29:21
  go version:       go1.14.2

**Object Storage Provider**:
  prometheus, version 2.19.3 (branch: HEAD, revision: 657ba532e42f1db8d7c77bf802378643da0d3118)
  build user:       root@b99e50bced7c
  build date:       20200724-12:20:53
  go version:       go1.14.6

**What happened**:
We set this flag `--query.timeout=90s ` but there chance query still alive > the 90s
And this if happens very frequently we observed two abnormalities:
1 goroutine increasing very fast
![image](https://user-images.githubusercontent.com/33677006/124056588-982d1280-da58-11eb-91fe-74dfba395f6e.png)
2 memory usage increasing very fast and release or oom (we running thanos-query with 32GB)
![image](https://user-images.githubusercontent.com/33677006/124056805-fa861300-da58-11eb-9dc1-25e0d85e2cb0.png)

**What you expected to happen**:
We expected the memory will be GC and query to Prometheus query will be immediately recycled or dropped when timeout is triggered

**How to reproduce it (as minimally and precisely as possible)**:

quey Thanos with slow query with 100-200 Prometheus as store endpoints and the data be queried considerably be 0.1-1million time series
send 3  queries concurrently to Thanos query in very short time simulate grafana Prometheus alerting plugin, and repeat it with  < 60s timeout from the sender(curl call with a timeout at 60s)
repeat it 3-4 times each bath with a wait for 60s

**Full logs to relevant components**:

No error log when this happens

**Anything else we need to know**:

Not Os level related we running the official Thanos query container

**Comment by renchili** [comment]
here is the goroutine profile:
[apm_profile_1624609946569.zip](https://github.com/thanos-io/thanos/files/6745072/apm_profile_1624609946569.zip)

**Comment by ianbillett** [comment]
Thanks for raising this @renchili and providing relevant information :+1:  

At face value, the spiking go routine behaviour above appears to correlate with https://github.com/thanos-io/thanos/issues/4335
