### ISSUE TITLE
Add Adopter list to README.md too 

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#4395]
Currently those are only in our website. Let's at least add them to Readme as a link. (:

**Comment by slayer321** [comment]
Hii @bwplotka, I will like to contribute to this project can you assign it to me.

We only need to add [this](https://github.com/thanos-io/thanos/blob/06ae3b892321b1d4db231aead60df1666b917749/website/data/adopters.yml) link to the README.md right?

**Comment by sandeep1785** [comment]
Hi. I just made a PR for this above. Please let me know if any changes are required.

**Comment by yeya24** [comment]
Closed due to #4408
