### ISSUE TITLE
Thanos query timeout

### ISSUE THREAD

**Issue by shirpx** [thanos-io/thanos#440]
Hi,
i connected LB to my thanos-query servers as a datasource in grafana, 
when trying to query 7 days back on redis dashboard
i see that the query servers cpu raises but not enough for it to die,
but after that the datasource just becomes inaccessible and i can’t query at all,
the datasource becomes accessible again only after restarting the thanos-query container on the query servers(never get’s back to work without a reset)

thanos query graphs:
![thanos query network](https://user-images.githubusercontent.com/33197846/43132386-49dc7a9c-8f44-11e8-8b00-e142c27d1a47.png)
![thanos-query-cpu-metric](https://user-images.githubusercontent.com/33197846/43132390-4caf1a68-8f44-11e8-82f2-1774dfc19e72.png)
![thanos query memory](https://user-images.githubusercontent.com/33197846/43132409-54c6889e-8f44-11e8-9df8-37ac7f4d6e7d.png)
![thanos-query-dashboard](https://user-images.githubusercontent.com/33197846/43132395-4f6f3f3a-8f44-11e8-87a8-e1f99266210f.png)
![thaos-query dashboard 2](https://user-images.githubusercontent.com/33197846/43132401-50e35694-8f44-11e8-9ddc-f9b49c142537.png)

timeout directly throw thanos http access:
![thanos-query timeout](https://user-images.githubusercontent.com/33197846/43132414-59db4aae-8f44-11e8-8995-f48206433b5f.png)

it’s important to mention that my prometheus servers can handle 7 days on the redis dashboard when querying them directly and it’s looks like thanos-query uses more prometheus resources than querying directly.
[redisDashboard.txt](https://github.com/improbable-eng/thanos/files/2223145/redisDashboard.txt)

![queryvsdirectly](https://user-images.githubusercontent.com/33197846/43132510-b8e96418-8f44-11e8-83e2-5468aeb20fc9.png)

i have 2 prometheus servers scarping in the region i am querying on and in the dashboard i’m querying only for that region. 

the resources of my query severs and my prometheus servers in that region are equal (for comparison purposes due this issue)

my query servers resources:  min 2 servers with 12 vCPUs, 76 GB (autoscaled)
my prometheus servers resources:
2 servers with 12 vCPUs, 76 GB

in the query logs i see this error:
level=error ts=2018-07-24T08:24:50.715483428Z caller=proxy.go:117 err=“fetch series for [{monitor codelab-monitor} {replica prometheus-master-us-central1-a-1}]: rpc error: code = Canceled desc = context canceled”

nothing is special in the sidecar logs

**Comment by bradleybluebean** [comment]
Not sure if this helps but I posted a comment on a similar sounding issue
https://github.com/thanos-io/thanos/issues/455#issuecomment-529716776

**Comment by krasi-georgiev** [comment]
Cold you try with the latest Thanos version as  Bartek added remote read streaming and it should fix this problem.
https://github.com/thanos-io/thanos/pull/1268

**Comment by krasi-georgiev** [comment]
Just noticed that the streaming PR got merged just after 2.12 was cut so need to wait for the 2.13 Prometheus release or just use the master image.
https://github.com/prometheus/prometheus/commits/master?after=26e8d25e0b0d3459e5901805de992acf1d5eeeaa+34

**Comment by bwplotka** [comment]
Wait or use our image we prepared Which is essentially 2.12 + remote read
extended protocol: `quay.io/thanos/prometheus:v2.12.0-rc.0-rr-streaming`
It's used in production already. (:
