### ISSUE TITLE
Improve guidance for helping users debug performance issues  

### ISSUE THREAD

**Issue by ianbillett** [thanos-io/thanos#4401]
### Is your proposal related to a problem?

This project receives a large number of performance related questions of the form:
* Why is `<component>` using so much memory?
* Please help, `<component>` is running slowly.

The level & detail of information provided in these reports can vary quite a lot. The standard bug report that users fill out only asks them for relevant logs for a given component. In the process debugging an issue, the folks involved usually end up sharing screenshots of queries that eventually help us debug the issue.

This creates two problems:
* There is often significant latency between the user raising the issue, and the requisite information being shared to enable debugging.
* Only experienced maintainers with significant relevant context know what additional metrics and information to ask for. This means newbie contributors (me) can't help progressing user performance tickets.

### Describe the solution you'd like

I would like Thanos to follow the example set by upstream Prometheus ([1](https://github.com/prometheus/prometheus/issues/8955#issuecomment-864622070),[2](https://github.com/prometheus/prometheus/issues/8310#issuecomment-754054140),[3](https://github.com/prometheus/prometheus/issues/7669#issuecomment-663868593)), and produce a set of deep dive / internals dashboards. This would then form the standard request for information from users when a performance related issue is raised.

This would improve the quality and velocity of communication: the users knows the information they will be asked for, newbie contributors can request the information if it has not yet been provided.

#### How?

These dashboards will be maintained in the `thanos/mixin` directory, separately from the existing 'overview' dashboards.

To make it as easy as possible for users to get these dashboards into their Grafana instances, we will:
* Vendor the resulting JSON outputted in the local directory.
* Upload the JSON to grafana.com so users can import it with a simple ID - [example](https://grafana.com/grafana/dashboards/12054).

### Describe alternatives you've considered

Keep doing what we're doing - and muddle through :man_shrugging:  

### Additional context

Kind of related to https://github.com/thanos-io/thanos/issues/4338

**Comment by jmichalek132** [comment]
still relevant
