### ISSUE TITLE
Receive component is getting terminated

### ISSUE THREAD

**Issue by spaparaju** [thanos-io/thanos#4405]
Thanos-receive process (on a Kubernetes environment) is getting terminated with an error.

**Thanos, Prometheus and Golang version used**:

quay.io/thanos/thanos:v0.20.0-rc.0

**Object Storage Provider**:

S3

**What happened**:
Thanos Receive pods are getting terminated with an application error.

**What you expected to happen**:

NO termination of Thanos receive pods with an application error.

**How to reproduce it (as minimally and precisely as possible)**:
Not known at this time. These terminations are observed with a heap usage of 30G+ and are happening very in-frequently.

**Full logs to relevant components**:

`nc1.1.1(0x1b6d400, 0xc1a145db80, 0x1fae790, 0xc32a431980, 0xc0faaddc70, 0x40e2f8)
                 /home/circleci/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20201207153454-9f6bf00c00a7/chain.go:51 +0x5f
github.com/grpc-ecosystem/go-grpc-middleware/v2.ChainStreamServer.func1(0x1b6d400, 0xc1a145db80, 0x1fae790, 0xc32a431980, 0xc32b02c5e8, 0x1d2fbe8, 0x1f9f070, 0xc2a93b2a80)
  /home/circleci/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20201207153454-9f6bf00c00a7/chain.go:60 +0xd1
google.golang.org/grpc.(*Server).processStreamingRPC(0xc169da0ea0, 0x1fb86d8, 0xc172c80900, 0xc32b026400, 0xc16a079ec0, 0x2ceb220, 0x0, 0x0, 0x0)
  /home/circleci/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1336 +0x535
google.golang.org/grpc.(*Server).handleStream(0xc169da0ea0, 0x1fb86d8, 0xc172c80900, 0xc32b026400, 0x0)
  /home/circleci/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1409 +0xc68
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0819c8050, 0xc169da0ea0, 0x1fb86d8, 0xc172c80900, 0xc32b026400)
  /home/circleci/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
  /home/circleci/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa5`

`goroutine 946895386 [select]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc1f6e4f130, 0x1, 0x0, 0x0, 0x0, 0x0)
  /home/circleci/go/pkg/mod/google.golang.org/grpc@v1.29.1/internal/transport/controlbuf.go:395 +0xff
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc146e92300, 0x0, 0x0)
  /home/circleci/go/pkg/mod/google.golang.org/grpc@v1.29.1/internal/transport/controlbuf.go:513 +0x1dd
google.golang.org/grpc/internal/transport.newHTTP2Server.func2(0xc0170a9980)
  /home/circleci/go/pkg/mod/google.golang.org/grpc@v1.29.1/internal/transport/http2_server.go:291 +0xd7
created by google.golang.org/grpc/internal/transport.newHTTP2Server
  /home/circleci/go/pkg/mod/google.golang.org/grpc@v1.29.1/internal/transport/http2_server.go:288 +0x1110`

**Anything else we need to know**:

None at this time. Will update with more findings.

**Comment by GiedriusS** [comment]
The goroutine dump seems to be incorrectly formatted. Could you copy it verbatim? And does it happen with the newest version?

**Comment by spaparaju** [comment]
not tested yet with the new Thanos release 21.x
