### ISSUE TITLE
Querier can deduplicate select call

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#4407]
### Is your proposal related to a problem?

In a complex promql query, a metric might be used multiple times in an expr. For example, https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/alerts/resource_alerts.libsonnet#L43-L62.

```
              sum(namespace_memory:kube_pod_container_resource_requests:sum{%(ignoringOverprovisionedWorkloadSelector)s})
                /
              sum(kube_node_status_allocatable{resource="memory"})
                >
              ((count(kube_node_status_allocatable{resource="memory"}) > 1) - 1)
                /
              count(kube_node_status_allocatable{resource="memory"})
```

For this query, thanos query will perform 1 time {__name__="namespace_memory:kube_pod_container_resource_requests:sum"} `select` and 3 times {__name__="kube_node_status_allocatable", resource="memory"} `select`. 

You can find that this is totally unnecessary. It would be good to be able to find this case and only perform select once for {__name__="kube_node_status_allocatable", resource="memory"}.

Another common pattern is to calculate the error rate. For example, one query would be,

```
some_metrics{type="error"} / some_metrics
```

In this case, `select` will be executed twice but it is unnecessary as `{__name__="some_metrics"}` already covers the case of `some_metrics{type="error"}`

Last case, a promql might look like:

```
some_metrics{type="error"} / some_metrics{type="success"}
```

It is also possible to make the series query to be `{__name__="some_metrics", type=~"error|success"}` so that only one `Select` call is needed. 

### Describe the solution you'd like

I don't have any solution for this now. Thanos depends on the prometheus query engine so it is not easy to do something at Thanos sidecar in this case. Prometheus also has this kind of problem, but it is not a critical problem for them as it only performs queries on local TSDB.

### Describe alternatives you've considered

Deal with this case in the query frontend? This might be a good idea and easier to change, but the query frontend needs to be aware of promql.

### Additional context

Why this is important for us?

We use central queries with multiple sidecars at edge clusters. Each `Select` call would fanout to all edge clusters and network latency is really a big concern. It would be good to reduce unnecessary calls and I think the performance would be much better.

**Comment by GiedriusS** [comment]
It can work the other way too: if someone is asking for a metric `foo{}` then we can reuse the results of that request for all queries that use the same metric + any kind of matchers e.g. `foo{bar="baz"}`

**Comment by yeya24** [comment]
@GiedriusS The cache solution makes sense to me. Can we use an in memory cache with short ttl in querier for deduplication?

**Comment by yeya24** [comment]
@GiedriusS I am trying to add a cache to each querier instance. But the problem is that the `select` function is now concurrent so that we cannot wait for the `select` results to be cached.

**Comment by bwplotka** [comment]
During community hours we talked about this and indeed there is opportunity to either:
* Cache
* Singleflight (easier) between series (even with different matches)

But also worth to mention that Query pushdown and singleflight on lower nodes (e.g store GW, sidecar) is also a viable option.


NOTE: What about singleflight on Store API gRPC level?

**Comment by yeya24** [comment]
`(histogram_quantile(0.99, sum by(job, le) (rate(http_request_duration_seconds_bucket{handler="query",job=~".*thanos-query.*"}[5m]))) > 40 and sum by(job) (rate(http_request_duration_seconds_bucket{handler="query",job=~".*thanos-query.*"}[5m])) > 0)`

Another example of duplicate select query.

**Comment by GiedriusS** [comment]
https://github.com/thanos-io/thanos/pull/4290 has been running in prod here for the past couple of months but I suppose it is worth investing time looking into whether it is possible to pushdown this logic to the gRPC level.

**Comment by GiedriusS** [comment]
The new promql-engine does this exactly so I'm closing the ticket.
