### ISSUE TITLE
Weak cryptographic primitive used in `pkg/receive/config.go` file

### ISSUE THREAD

**Issue by iamrajiv** [thanos-io/thanos#4415]
## Description

MD5 is a relatively weak encryption/hashing algorithms. Go's official documentation also warns against the usage of [MD5](https://golang.org/pkg/crypto/md5/). The most common alternative for the insecure algorithm can be the use of SHA512 instead of MD5.

**Comment by yeya24** [comment]
Same as https://github.com/thanos-io/thanos/pull/4164.
