### ISSUE TITLE
multi-tenancy: Tenant aware Target API

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#4424]
Current Target API does not have tenancy capabilities: We cannot match those by label and allow storage to pick only targets for relevant data. 

AC:
 * Targets API supports passing label matcher
 * Querier us able to match according Target API based on external labels
 * Target API is able to advertise it's external labels

Open question: Can we somehow make Prometheus target API multi-tenant?

**Comment by yeya24** [comment]
What's the label of a target?
