### ISSUE TITLE
receive: Auto tunable write rate limit for ingesting receive based on configurable resource limits

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#4425]
*AC*:
* Benchmark receive and gather the latest (average) consumption of memory and CPU (mainly mem) per single write request, stored number of series and samples (after GC run)
* Implement a function that calculates remaining pool of write requests we can consume in given moment based on user provided CPU and Mem limits
   * leave some room for querying traffic
* Enforce rate limit based on this.

Alternatively, we could check Heap memory allocated and compare with limit and decide to shut down a portion of request (random? based on tenant ID? based client IP? - what's worse -> all users have partial samples, or portion of users has no data (IMO latter)).

NOTE: Enforcing per tenant or per IP limits is no goal here. We want to do that part before request goes into Thanos ring -> as we do with Gubernator on Observatorium side.

**Comment by LeviHarrison** [comment]
Going further with this, I think it would be cool if receivers could expose such a rate limit/traffic indicator to load balancers which could use that to make routing decisions.
