### ISSUE TITLE
e2e: Add ascii diagrams for each of the e2e integration tests

### ISSUE THREAD

**Issue by ianbillett** [thanos-io/thanos#4429]
### Is your proposal related to a problem?

Understanding the topology of e2e integration tests is non-trivial.

### Describe the solution you'd like

Add ascii diagrams to each of the integration test topologies.

### Additional context

I've had some positive feedback from @squat & @GiedriusS [here](https://github.com/thanos-io/thanos/pull/4368#pullrequestreview-702087041) that ascii diagrams included in the receiver integration tests ([1](https://github.com/thanos-io/thanos/blob/main/test/e2e/receive_test.go#L116-L142),[2](https://github.com/thanos-io/thanos/blob/main/test/e2e/receive_test.go#L215-L250),[3](https://github.com/thanos-io/thanos/blob/main/test/e2e/receive_test.go#L322-L356)) were useful in helping them understand the non-trivial topologies used in our integration tests.

We should extend this to all integration tests to help readers gain context quickly.

**Comment by ianbillett** [comment]
Suggested labels `help-wanted`, `good first issue`.

**Comment by bwplotka** [comment]
Ambitious! =D I am not sure if that makes sense tbh. Maybe we need some documentation entry first to teach contributor to make them (:
