### ISSUE TITLE
loadMeta: Reduce the number of queries with object stores

### ISSUE THREAD

**Issue by wuming333666** [thanos-io/thanos#4447]
### Is your proposal related to a problem?

When performing compact operations, part of the time is spent on repeatedly finding metafiles；
Is it possible to cache the block that has been looked up.

### Describe the solution you'd like

fetch.go--> loadMeta
```
if m, seen := f.cached[id]; seen {
		return m, nil
	}
```

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by wiardvanrij** [comment]
I'm actually not sure if the compactor uses the memcached cache. Perhaps a win could be made there. Other than that, I think it would be interesting to investigate where some wins could be made regarding the amount of requests made to the object store. 
Especially in environments with SSE/SSL/etc , each requests is adding up to the costs (KMS actions).

**Comment by yeya24** [comment]
@wuming333666 I am wondering if this issue is still valid? As we discussed before, caching the metadata might cause a consistency issue.
