### ISSUE TITLE
Querier provides different query results on each execution of same query. 

### ISSUE THREAD

**Issue by dmilind** [thanos-io/thanos#4450]
**Thanos, Prometheus and Golang version used**:
Thanos: v0.21.1
Prometheus: 2.28.0
golang: go1.16.5
--

**Object Storage Provider**:
azure container storage 

**What happened**:
I have Thanos set up with 5 pods of the receiver. Prometheus sends samples correctly to thanos receive. When I hit query on querier, each time I see different results. For example If I hit simple `up` query on querier, at one instance of time I see 50 pods up, after execution again I see 23, then 78, then again 50 and sometimes empty metric. 

For testing I initially kept single instance of receive, upon hitting same query multiple times, I found identical result set, then I increased the replica to 2, and from here result set was different on each query execution. I dont see any flip from prometheus side since single prometheus instance is being used. 

Is this normal behavior or is there anything I am missing ? 

**What you expected to happen**:
Query result must be identical 

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:
Receive configs 
```
 args:
            - receive 
            - --log.level=info
            - --log.format=json
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:10902
            - --remote-write.address=0.0.0.0:10903
            - --grpc-grace-period=2m         
            - --tsdb.path=./thanos/receive/objstorage
            - --objstore.config=$(OBJSTORE_CONFIG)
            - --receive.local-endpoint=$(INSTANCE).thanos-receive-svc.monitor.svc.cluster.local:10901
            - --receive.hashrings-file=/var/thanos/receive/hashring/thanos-receive-hashring.json
            - --receive.hashrings-file-refresh-interval=5m
            - --tsdb.retention=1d
            - --receive.replication-factor=1
            - --label=receive="true"
            - --label=replica="$(INSTANCE)"
            - --receive.tenant-header=THANOS-TENANT
            - --receive.default-tenant-id=default-tenant
``` 

Querier Configs: 
```
            - query 
            - --log.level=info
            - --log.format=json
            - --grpc-address=0.0.0.0:10904
            - --http-address=0.0.0.0:10905
            - --web.route-prefix=thanos/querier
            - --web.external-prefix=thanos/querier
            - --query.replica-label=tenant
            - --query.timeout=15m
            - --query.partial-response
            - --store=dns+thanos-receive-svc:10901
            - --store=dns+thanos-store-svc:10906
            - --store.unhealthy-timeout=5m

```

**Comment by wiardvanrij** [comment]
I think you should re-check your de-duplication on the query. I.e. you have `--query.replica-label=tenant` but I would have assumed a label like `receive_replica`

**Comment by dmilind** [comment]
@wiardvanrij  I tried this option but no luck still I am seeing same behaviour. 
can someone please provide any details on this ?

**Comment by hanjm** [comment]
the arg --query.replica-label=tenant is wrong，shoud be --query.replica-label=replica

**Comment by dmilind** [comment]
This is getting serious issue for my team since, grafana dashboards are not giving consistent data and false alerts are also getting triggered. If anyone is aware/worked on this issue please suggest here

**Comment by dmilind** [comment]
> the arg --query.replica-label=tenant is wrong，shoud be --query.replica-label=replica

Let me try this

**Comment by dmilind** [comment]
@hanjm  I applied this `--query.replica-label=replica` as well but still same issue

**Comment by dmilind** [comment]
I am keeping identical flags for querier and receive here: 
`--label=receive_replica="$(INSTANCE)"` - from receive 
`--query.replica-label=replica` from querier 

still issue persists

**Comment by ianbillett** [comment]
@dmilind my debugging strategy here would be:
* Run the querier and get one set of results
* Run the querier again and get another set of results
* Diff the two results and ask yourself - what is different about the data?
* Can you identify a pattern in the data?
* Grab an open source Thanos Query dashboard and see if anything looks funky - do the stores change frequently?

**Comment by dmilind** [comment]
@ianbillett  I gave second attempt for debugging as you said 
* ran querier with simple (up) query) first time and got 1 result means one thanos component pod was up 
* ran second time with same query and got 3 results this time
* Everytime I re-execute again different num of results are provided 
* for few result only the diff is receive pod replica name 
* Pattern in data is so random like one time receive-1 will provide output along with other 2 receive pods and next time only receive 1 will give single data 
* Store changes on every query or reload

**Comment by ianbillett** [comment]
> for few result only the diff is receive pod replica name
So that is progress - it sounds like the problem is that only some of the stores are executing your query. At this point I would try being explicit about the DNS names of the stores instead of using the DNS service discovery. 

At this point, without a whole bunch more information (logs, screenshots, video) we (the Thanos community) will struggle to help you diagnose the problem and navigate towards a solution.

You need to help us help you :hugs:

**Comment by dmilind** [comment]
What I am guessing is 

1. Samples sent by Prometheus are not available on all thanos receive at one particular instance of time. One of the thanos pod is having the sample but other pod is missing those samples 
2. During this time when querier hits receiver, result will be shown depending on the samples sustained by receiver.  If no samples are replicated on one of the receiver then empty results are shown. 

Am I correct here ?

**Comment by dmilind** [comment]
@ianbillett Upon using static stores instead of DNS SD, everything is working as expected, not seeing any metric flipping anymore. 
But since I am using HPA, its will be little hard to update the store everything (assuming predeclared unused stores are not making any issue). 

Also why DSN SD is providing flipped metrics result ?
