### ISSUE TITLE
Compactor:failed to run compactor and  deletion-mark.json is remained in my Minio

### ISSUE THREAD

**Issue by tydhot** [thanos-io/thanos#4456]
I have run my compactor with that command line:

<img width="675" alt="image" src="https://user-images.githubusercontent.com/27889201/126308456-f9ec711f-021d-4503-b6ef-2e454e681b01.png">

but it failed and the log looks liked:
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/27889201/126308490-28a60350-ec30-4b85-bbeb-296f33142154.png">

It exist and the Minio's log file didn't be deleted and has deletion-mark.json remained looks like that:
<img width="913" alt="image" src="https://user-images.githubusercontent.com/27889201/126308647-80f687a4-7f2c-44ff-95ae-d36a85558cfd.png">

Is there anything wrong with my operation OR there is a bug?

**Comment by ianbillett** [comment]
Reading the [docs](https://thanos.io/tip/components/compact.md/#block-deletions)
> Instead, blocks are marked for deletion by uploading deletion-mark.json file for the block that was chosen to be deleted.

I don't see anything out of the ordinary here - is anything happening that you are expecting to happen?

**Comment by tydhot** [comment]
@ianbillett Thank you for your reply. I got it about the deletion-mark. But the Compactor will shutdown after compact once. Is that normal condition?

**Comment by yeya24** [comment]
@tydhot You need another flag. Please check the docs.

```
By default thanos compact will run to completion which makes it possible to execute in a cronjob. Using the arguments --wait and --wait-interval=5m it’s possible to keep it running.
```
