### ISSUE TITLE
Display markers in the bucket UI

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#4472]
### Is your proposal related to a problem?

There is no way to tell whether a block has been marked for deletion or no-compaction right now.

### Describe the solution you'd like

Now the bucket UI displays the meta.json file for each block. Though deletion markers are not part of the meta.json file, we can add some additional information to that block or use even different colors to represent the state?

Thoughts? @onprem

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by onprem** [comment]
Yes, this is already planned as part of the LFX project going on.
cc @adzshaf

**Comment by yeya24** [comment]
Still valid

**Comment by jtougas** [comment]
Is this still in the works?
