### ISSUE TITLE
ThanosMixin: Dashboard "all" selector not working

### ISSUE THREAD

**Issue by ethernoy** [thanos-io/thanos#4488]
**Thanos, Prometheus and Golang version used**:
Thanos: 0.20.2-scratch-r1 (bitnami)
Prometheus: 2.27.1 (bitnami)

**Object Storage Provider**:
MinIO

**What happened**:
I imported the Thanos receive dashboard from ThanosMixin and it cannot show anything when selecting "all" in job selector.
![image](https://user-images.githubusercontent.com/15870761/127091304-e1f6833a-a246-433a-bf2d-1635b45f729a.png)

It can work when I select a dedicated job from the selector.
![image](https://user-images.githubusercontent.com/15870761/127091516-9fc2d8b4-6a92-4dc0-978f-9c7d7c841686.png)

**What you expected to happen**:
The dashboard can work under "all" job selector.

**How to reproduce it (as minimally and precisely as possible)**:
Import Thanos receive dashboard from this repository and use "all" in job selector.

**Anything else we need to know**:
It can be fixed by changing the PromQL selector of job variable from `job="$job"` to `job=~"$job"` because "all" variable in Grafana is supposed to work in regular expression mode of PromQL selector. I have verified this solution in my local environment.

![image](https://user-images.githubusercontent.com/15870761/127091722-63f6c058-ba7a-4c0a-8e96-9bfd2507c221.png)

I am happy to create a PR for fixing this issue in all ThanosMixin dashboards :)

**Comment by wiardvanrij** [comment]
> I am happy to create a PR for fixing this issue in all ThanosMixin dashboards :) 

Yes please!
