### ISSUE TITLE
thanos store aliyunoss 报错

### ISSUE THREAD

**Issue by python-it** [thanos-io/thanos#4507]
![image](https://user-images.githubusercontent.com/32905701/127792105-8cdb5260-7b06-4184-b60f-43103f6f44b7.png)
![image](https://user-images.githubusercontent.com/32905701/127792140-561d84de-0ff7-406e-90b9-b285fd6509de.png)
![image](https://user-images.githubusercontent.com/32905701/127792179-05449d2f-e5b8-4b11-bd74-2c31d2dd4e02.png)

**Comment by yeya24** [comment]
Please use the correct configuration format https://thanos.io/tip/thanos/storage.md/#aliyun-oss
