### ISSUE TITLE
reference sequence out of range during downsample

### ISSUE THREAD

**Issue by stevenkehrli-trelnex** [thanos-io/thanos#453]
**Thanos, Prometheus and Golang version used**

thanos, version 0.1.0-rc.2 (branch: master, revision: a4128358e9df68170a4df7f0d4c7bef2bab2c3ca)
  build user:       root@Stevens-MacBook-Pro.local
  build date:       20180723-21:11:41
  go version:       go1.10.1

**What happened**

Hitting "reference sequence out of range" in chunks.go Chunk() method, line 348. ref is 240518168584, seq is 56, off is 8. len(s.bs) is 56.

**What you expected to happen**

downsample to complete successfully

**How to reproduce it (as minimally and precisely as possible)**:

run compact / downsample on directory linked below

**Full logs to relevant components**

https://s3-us-west-2.amazonaws.com/steven-thanos/01CH49QVMT66BKRGRZFXZS9Q4F.zip

compressed folder that repros the issue. 15.77GB compressed. 38.33GB uncompressed.

**Comment by bwplotka** [comment]
Definitely not enough info. Sequence out of range happens only when you have corrupted block which might indicate something wrong with your setup.

It was long ago, do you mind rechecking on `v0.1.0` release?

**Comment by GiedriusS** [comment]
Does this still happen? I can't download the relevant files.
