### ISSUE TITLE
ruler: Add metric that indicates instant query failures

### ISSUE THREAD

**Issue by OGKevin** [thanos-io/thanos#4545]
### Is your proposal related to a problem?

When ruler fails to evaluate rules due to HTTP error. There is no metric that indicates this as shown by the following piece of code:
https://github.com/thanos-io/thanos/blob/e9ef82bfb13ac5121538605e0b2c0e6f12ec9764/cmd/thanos/rule.go#L731-L747

The metric `thanos_rule_evaluation_with_warnings_total` will only get a value if the request succeeded with warnings. So In case of an error like the following: 

```
level=error ts=2021-08-10T07:49:05.668088944Z caller=rule.go:738 component=rules err="read query instant response: expected 2xx response, got 422. Body: {\"status\":\"error\",\"errorType\":\"execution\",\"error\":\"found duplicate
 series for the match group {namespace=\\\"cw-monitoring\\\", pod=\\\"prometheus-1-alertmanager-0\\\"} on the right hand-side of the operation: [{namespace=\\\"cw-monitoring\\\", node=\\\"gke-gc-prd-kube-app0-default-green-58d2d9d
a-7vlb\\\", pod=\\\"prometheus-1-alertmanager-0\\\"}, {namespace=\\\"cw-monitoring\\\", node=\\\"gke-gc-prd-kube-app0-default-green-58d2d9da-g13i\\\", pod=\\\"prometheus-1-alertmanager-0\\\"}];many-to-many matching not allowed: ma
tching labels must be unique on one side\"}\n" query="container_memory_rss{image!=\"\",job=\"cadvisor\"} * on(namespace, pod) group_left(node) max by(namespace, pod, node) (label_replace(kube_pod_info, \"pod\", \"$1\", \"exported_
pod\", \"(.+)\"))"       
```

Which is spit out at: https://github.com/thanos-io/thanos/blob/e9ef82bfb13ac5121538605e0b2c0e6f12ec9764/cmd/thanos/rule.go#L739

You will only know this if you happened to look in the logs.
### Describe the solution you'd like

Add a metric that indicates instant query failures. A traditional HTTP request and success rate metric will be more then enough to indicate problems.

**Comment by bwplotka** [comment]
Thanks for reporting!

We already should have HTTP client metric for this (if not we can add those as part of this ticket)

**Comment by OGKevin** [comment]
I see no mention of metrics in the [promclient](https://github.com/thanos-io/thanos/blob/50dac9bcf73cd1c7c6c8aef9171214e1e427aed0/pkg/promclient/promclient.go), is there another client that already has such metrics?

**Comment by OGKevin** [comment]
@bwplotka can you check if the linked PR is going in the right direction or did you have smt else in mind?

**Comment by bwplotka** [comment]
I have exactly this in mind!
