### ISSUE TITLE
Query-frontend displaying code level dump back to the user

### ISSUE THREAD

**Issue by spaparaju** [thanos-io/thanos#4558]
A query resulting in HTTP 500 and displaying code level dump back to the user

**Thanos, Prometheus and Golang version used**:
quay.io/thanos/thanos:v0.20.0-rc.0

**Object Storage Provider**:

**What happened**:
A Query fired from Thanos Query-frontend resulted in error (HTTP 500). User 

**What you expected to happen**:
A human readable message indicating the failure of the query
**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:
<img width="1529" alt="query-frontend" src="https://user-images.githubusercontent.com/42730908/130132182-7cc70769-77b2-4113-88ea-28a64ea476c3.png">

**Anything else we need to know**:

**Comment by yeya24** [comment]
Hello @spaparaju, can you add more details and logs?

**Comment by spaparaju** [comment]
@yeya24 updated the issue with the screenshot. Could not capture the logs. This query is resulting in HTTP 500.

**Comment by GiedriusS** [comment]
How does the Stores page look like? Is it the same with the newest version?

**Comment by yeya24** [comment]
@spaparaju Is it related to query frontend? If you are just using querier without the query frontend, can you still reproduce the issue?

**Comment by spaparaju** [comment]
@GiedriusS the stores were looking healthy (as per the stores page) and the other queries that I tried (after encountering this problem) were successful. 

@yeya24 Yes, its related to query-frontned. Unfortunately the environment that I could reproduce this problem does not have routes to Thanos Query component.

**Comment by yeya24** [comment]
I still don't think this relates to the query frontend. This error is the partial response warning from Thanos Queriers Series API.
Query frontend is just simply a proxy and displays what it gets from the querier.
If we want to improve it, we need to do more fine grained checking on the querier side.
