### ISSUE TITLE
using service account to upload to s3 is failing

### ISSUE THREAD

**Issue by bseenu** [thanos-io/thanos#4559]
**Thanos, Prometheus and Golang version used**:

thanos : v0.22.0
prometheus : 2.24.0

**Object Storage Provider**:

s3

**What happened**:

thanos sidecar is getting access denied from s3 when using service account role instead of access_key and secret

**What you expected to happen**:

data to be uploaded to s3

**How to reproduce it (as minimally and precisely as possible)**:

I am using the prometheus helm chart - and associating the existing serviceaccount and adding the thanos as side car, here is my config

```
- name: thanos-sidecar
              image: quay.io/thanos/thanos:v0.22.0
              args:
                - sidecar
                - --log.level=debug
                - --prometheus.url=http://127.0.0.1:9090
                - --min-time=-2h
                - |
                    --objstore.config=type: s3
                    config:
                      bucket: <<bucket-name>>
                      endpoint: s3.us-west-2.amazonaws.com
                      signature_version2: false
                      insecure: true
                      http_config:
                        insecure_skip_verify: true
                      trace:
                        enable: true
```

**Full logs to relevant components**:

```
level=debug ts=2021-08-12T02:41:29.344177464Z caller=stdlib.go:89 s3TraceMsg=---------START-HTTP---------
level=debug ts=2021-08-12T02:41:29.344443407Z caller=stdlib.go:89 s3TraceMsg="HEAD /01FCVDBWQXBWD0Z5S443RGX66W/meta.json HTTP/1.1\r"
level=debug ts=2021-08-12T02:41:29.344503227Z caller=stdlib.go:89 s3TraceMsg="HTTP/1.1 403 Forbidden\r"
level=debug ts=2021-08-12T02:41:29.344523818Z caller=stdlib.go:89 s3TraceMsg=---------END-HTTP---------
level=warn ts=2021-08-12T02:41:29.344606589Z caller=sidecar.go:310 err="check exists: stat s3 object: Access Denied." uploaded=0
```

**Anything else we need to know**:

It is not permission issue, head-object needs s3:GetObject permission which i have added 

https://docs.aws.amazon.com/cli/latest/reference/s3api/head-object.html

**Comment by ianbillett** [comment]
Hey @bseenu - our [documentation](https://thanos.io/v0.2/thanos/storage.md/#aws-s3-configuration) seems to indicate that setting `secret_key` is mandatory for S3.
> To configure S3 bucket as an object store you need to set these mandatory S3 variables in yaml format stored in a file:

Please can you elaborate on the following?
> thanos sidecar is getting access denied from s3 when using service account role instead of access_key and secret

**Comment by bseenu** [comment]
we prefer to use the service account which has the iam role annotation which will be having s3 previleges

And i came across the following blog post which shows the configuration using the service account 

https://aws.amazon.com/blogs/opensource/improving-ha-and-long-term-storage-for-prometheus-using-thanos-on-eks-with-s3/

**Comment by james-callahan** [comment]
For what it's worth, we successfully use thanos with Amazon IRSA. We add the following annotations to the service accounts of thanos:
```yaml
    eks.amazonaws.com/role-arn: arn:aws:iam::OURACCOUNTID:role/thanos-SOMEUNIQUEID
    eks.amazonaws.com/sts-regional-endpoints: "true"
```

That role has the permissions from https://thanos.io/tip/thanos/storage.md/#s3
i.e.
```
                "s3:ListBucket",
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:PutObject"
```

**Comment by lewandowskim1988** [comment]
It looks like Thanos update to `v0.24.0` resolved this issue. Now I am able to use `IAM Role` without any problems with the same policy that was previously attached to `IAM User`.
