### ISSUE TITLE
Overflowing Logos In the Website

### ISSUE THREAD

**Issue by CIPHERTron** [thanos-io/thanos#4560]
Some company logos on the https://thanos.io/ website are overflowing from their respective containers
For example `Cloud & Heat`, `Infinite Devices`

**Screenshot of the same**:
![Screenshot from 2021-08-12 11-42-47](https://user-images.githubusercontent.com/56754747/129147434-42fb458c-365d-41b1-8243-8947995e24e5.png)

**Environment**:
- OS (e.g. from /etc/os-release): Ubuntu 20.04
- Kernel (e.g. `uname -a`): Linux Kernel 5.8

**Comment by bwplotka** [comment]
Yes, help wanted 🤗

**Comment by CIPHERTron** [comment]
I would love to work on it @bwplotka. Could you please assign it to me?😊
