### ISSUE TITLE
Use npm instead of yarn for building the react app

### ISSUE THREAD

**Issue by Nexucis** [thanos-io/thanos#4562]
Hi team,

Prometheus is going to replace the usage of `yarn` by `npm` when building the react-app. (through this PR: https://github.com/prometheus/prometheus/pull/9198)

This decision is coming from the move of codemirror-promql into the main repository prometheus/prometheus as sub web module. It's just to be aligned in term of technology used between the react-app and the sub web module that would be contained in the Prometheus repository.

Full context is available here: https://github.com/prometheus/prometheus/pull/9188#discussion_r686615732

I was simply wondering if you would like to follow this change as well.
This decision doesn't necessary impact Thanos as you are not part of the Prometheus repositories.
It's just to know if you would like to be aligned as well in term of web technologies let's say.

**Comment by wiardvanrij** [comment]
+1 from me, to keep the code-base in line with Prometheus

**Comment by onprem** [comment]
This makes sense to me as well. Having common tooling makes a lot of sense, since both projects share a lot of contributors.
