### ISSUE TITLE
Blurred open graph image in `thanos.io`

### ISSUE THREAD

**Issue by iamrajiv** [thanos-io/thanos#4569]
## Description

![Screenshot 2021-08-17 at 3 50 11 AM](https://user-images.githubusercontent.com/42106787/129636460-d626c4e1-07ea-424e-a1e3-c6b0387fc3b5.jpg)

When we check [https://thanos.io/](https://thanos.io/) in [https://metatags.io/](https://metatags.io/) a blurred image of the card is coming it is because we are using [https://github.com/thanos-io/thanos/blob/main/website/static/icon-light.png](https://github.com/thanos-io/thanos/blob/main/website/static/icon-light.png) image which is very small in size.

We can update the open graph image with a more clear image or maybe with this [https://github.com/thanos-io/thanos/blob/main/website/static/thanos-twitter.png](https://github.com/thanos-io/thanos/blob/main/website/static/thanos-twitter.png).

**Comment by iamrajiv** [comment]
@bwplotka @yeya24 Can I work on this?

**Comment by GiedriusS** [comment]
@iamrajiv sure, feel free!
