### ISSUE TITLE
query-frontend: match[] query parameters not passed to downstream querier

### ISSUE THREAD

**Issue by crsandeep** [thanos-io/thanos#4580]
Thanos version - v0.22.0

**What happened**:

I made a labels API query to query-frontend ex: `/api/v1/label/cluster/values?start=1628762940&end=1628784540&match[]=go_goroutines`
But match[] query parameter was not sent to downstream querier

**What you expected to happen**:
match[] parameter sent to downstream querier

**How to reproduce it (as minimally and precisely as possible)**:
Start prometheus and let it scrape its own metrics and then start query-frontend and use prometheus as downstream url. Make a labels API call with match[] query parameter.

**Anything else we need to know**:
I believe the matcher param is not being read for labels API here https://github.com/thanos-io/thanos/blob/main/pkg/queryfrontend/labels_codec.go#L276-L289 unlike series API https://github.com/thanos-io/thanos/blob/main/pkg/queryfrontend/labels_codec.go#L320-L323. Any reason to not read match[] param for labels API? I can send a PR to fix this if this is a valid issue.

**Comment by yeya24** [comment]
Valid issue. Thanks for the reporting. The `match[]` parameter is relatively newly added so we don't have its support in the query frontend. Help wanted.

**Comment by crsandeep** [comment]
Great. I will work on this and send a PR soon.
