### ISSUE TITLE
only keep some of the metrics in the object storage

### ISSUE THREAD

**Issue by yasharne** [thanos-io/thanos#4588]
### Is your proposal related to a problem?

Most of the metrics we are collecting in our Prometheus server does not worth keeping for long, like CPU usage and disk usage. on the other hand, some other metrics are very important like the ones that describe the business status so that's why we wanted to use Thanos to keep those important metrics longer

### Describe the solution you'd like

Add the ability to define which metrics I want to keep longer and which ones I don't want to keep longer so it wouldn't occupy the object storage with the useless data

**Comment by GiedriusS** [comment]
I believe this feature request is covered by: https://github.com/thanos-io/thanos/issues/903

**Comment by GiedriusS** [comment]
I assume that the thumbs up means agreement so closing this to avoid duplicates :+1:
