### ISSUE TITLE
Reloader configuration doubles CPU usage

### ISSUE THREAD

**Issue by MioOgbeni** [thanos-io/thanos#4590]
**Thanos, Prometheus and Golang version used**:
```
thanos, version 0.22.0 (branch: HEAD, revision: 3656e290c8eb034e2e09e0afc79f087be88de481)
  build user:       circleci@d99a55512da0
  build date:       20210721-15:34:46
  go version:       go1.16.6
  platform:         linux/amd64
```

Using the Thanos image: `thanosio/thanos:v0.22.0`
Prometheus: `prom/prometheus:v2.29.0`

**Object Storage Provider**:
**AWS S3**

**What happened**:
After implementing Thanos config reload feature, I experienced increase of CPU from something about 50-100m to 200-300m.

**What you expected to happen**:
I unexpected that this feature will have too big impact to resources.

**How to reproduce it (as minimally and precisely as possible)**:
It's very easy to reproduce on my setup. With totally same statefulset configs:

Prometheus pod CPU usage is about 200-300m, when sidecar args contains this rows,
```
--reloader.config-file=/etc/prometheus-config/prometheus.yml
--reloader.config-envsubst-file=/etc/prometheus-shared/prometheus.yml
--reloader.rule-dir=/etc/prometheus-config/rules
```
prometheus args contains,
```
--config.file=/etc/prometheus-shared/prometheus.yml
```
and both containers mount 
```
volumeMounts:
- mountPath: /etc/prometheus-shared/
   name: prometheus-config-shared
```
with
```
volumes:
- emptyDir: {}
   name: prometheus-config-shared
```

**Anything else we need to know**:
When I remove this config parts, pod CPU usage drop to about 50-100m.

With another config reloader (jimmidyson/configmap-realod) is CPU usage also low. 

Maybe it can be same issue like this #3051 Is possible that this issue appeared again?

**Comment by bwplotka** [comment]
It might be. Thanks for reporting, let's profile this code. But also extra 100m might be low harm 🙈 

Help wanted!
