### ISSUE TITLE
External Storage Link Leads to Page Not Found Error

### ISSUE THREAD

**Issue by sennatitcomb** [thanos-io/thanos#4596]
Clicking on the link to "Example Deploying sidecar using official Prometheus Helm Chart in the External Storage" leads to a page not found error.

**Comment by amino19** [comment]
@ianbillett: Now it's #4647, ig!

**Comment by kunaljain0212** [comment]
@ianbillett There seems to be no response on the current PR about the failing CI, shall I create a new PR for this issue?

**Comment by ianbillett** [comment]
@kunal-kushwaha https://github.com/thanos-io/thanos/pull/4647 is failing [here](https://github.com/thanos-io/thanos/pull/4647/checks?check_run_id=3541829428#step:5:138)?
