### ISSUE TITLE
Prometheus '@' modifier

### ISSUE THREAD

**Issue by sevagh** [thanos-io/thanos#4600]
https://prometheus.io/blog/2021/02/18/introducing-the-@-modifier/
https://prometheus.io/docs/prometheus/latest/querying/basics/#modifier

Is this supported by Thanos yet?

**Comment by sevagh** [comment]
It's a bit hard to search for the `@` string but I couldn't find it.

**Comment by yeya24** [comment]
Not supported yet.

**Comment by sevagh** [comment]
Any known plans or roadmap? Thanks.

**Comment by yeya24** [comment]
Help wanted for this and a common experiment feature flags as mentioned https://github.com/thanos-io/thanos/pull/4026#discussion_r610467612

**Comment by yeya24** [comment]
Solved by #4679.
