### ISSUE TITLE
Thanos Store GW, large query failed, error message "read: connection reset by peer"

### ISSUE THREAD

**Issue by sowhat7** [thanos-io/thanos#4615]
thanos version: v0.22
prometheus version: v2.24.0
Object Storage Provider: S3
thanos store arg index-cache-size: 4GB
thanos store arg chunk-pool-size: 32GB

**What happened:**
Query data in one week is normal, more than two weeks will fail. And log an error message "read: connection reset by peer". The thanos-store-gateway container is running normally. 
Is the minio client connection timed out? Should I adjust the network connection parameters? But I don’t seem to find a suitable parameter
![079027b0c552f5834b2fb81b8c7d6cb](https://user-images.githubusercontent.com/20253793/131514618-cea059d4-12d0-4c6e-8f88-ea69bed8c8dc.png)
![f9488114ec5e9b5aa0abcaf26549eb7](https://user-images.githubusercontent.com/20253793/131514824-7c7647ae-97b2-4ccd-b4b1-5c4e570e7c7d.png)

**What you expected to happen:**
I can query the data within a month

**How to reproduce it**
Query large amounts of data

**Storage Gate Way log**
level=debug ts=2021-08-31T02:56:15.373424373Z caller=bucket.go:1073 msg="stats query processed" stats="&{blocksQueried:0 postingsTouched:763 postingsTouchedSizeSum:105290551 postingsToFetch:0 postingsFetched:0 postingsFetchedSizeSum:0 postingsFetchCount:0 postingsFetchDurationSum:0 cachedPostingsCompressions:0 cachedPostingsCompressionErrors:0 cachedPostingsOriginalSizeSum:0 cachedPostingsCompressedSizeSum:0 cachedPostingsCompressionTimeSum:0 cachedPostingsDecompressions:763 cachedPostingsDecompressionErrors:0 cachedPostingsDecompressionTimeSum:9631832853 seriesTouched:55808 seriesTouchedSizeSum:6640640 seriesFetched:0 seriesFetchedSizeSum:0 seriesFetchCount:0 seriesFetchDurationSum:0 chunksTouched:55808 chunksTouchedSizeSum:39959347 chunksFetched:55808 chunksFetchedSizeSum:4661979947 chunksFetchCount:6954 chunksFetchDurationSum:50515669650672  10.227.93.118:38720->10.193.111.151:80: read: connection reset by peer"

**Comment by yeya24** [comment]
Looks like too much data are fetched. Does your compactor have downsampling enabled?

**Comment by sowhat7** [comment]
> Looks like too much data are fetched. Does your compactor have downsampling enabled?

My compactor has enabled downsampling, the configuration is as follows
- "--retention.resolution-raw=1d"
- "--retention.resolution-5m=40d"
- "--retention.resolution-1h=0d"

**Comment by MrYueQ** [comment]
@yeya24  hi. 
I often encounter this problem. Especially when the query range is relatively large. Storage gateway prompt read: connection reset by peer

thanos version
```yaml
/data/app/thanos/bin/thanos --version
thanos, version 0.23.0-rc.0 (branch: HEAD, revision: 81841aed4a9e3d6f6ed772fea287f04504d164f3)
  build user:       root@d1bae1e2c93c
  build date:       20210908-14:46:03
  go version:       go1.16.7
  platform:         linux/amd64
```

thanos compact systemctl config

```yaml
/data/app/thanos/bin/thanos  compact  -w \
              --wait-interval=3m \
              --compact.cleanup-interval=3m \
              --compact.concurrency=4 \
              --compact.skip-block-with-out-of-order-chunks \
              --downsample.concurrency=4 \
              --block-sync-concurrency=60 \
              --tracing.config-file=/data/app/thanos/conf.d/trace.jaeger.yml \
              --block-meta-fetch-concurrency=64 \
              --objstore.config-file=/data/app/thanos/conf.d/object.json \
              --data-dir=/data/compact/  \
              --delete-delay=4h \
              --retention.resolution-raw=5d  \
              --retention.resolution-5m=15d  \
              --retention.resolution-1h=0d
```
