### ISSUE TITLE
in docs/components/receive.md, should add tsdb.min-block-duration flag

### ISSUE THREAD

**Issue by ahfuzhang** [thanos-io/thanos#4631]
tsdb.min-block-duration=2h
tsdb.max-block-duration=2h

I think we'd better add thoes tow flags in doc. thanks

**Comment by yeya24** [comment]
The default TSDB block duration is `2h` so I guess it is not needed to have?
But I agree adding these flags makes the document more clear. Would you mind opening a pr to update the doc? @ahfuzhang

**Comment by brettpalmberg** [comment]
Good Evening. Are these flags valid for the receiver?

**--tsdb.min-block-duration=2h
--tsdb.max-block-duration=2h**

If so, can the flags be added to the documentation for receive component here: https://thanos.io/tip/components/receive.md/#flags?

cc @yeya @ahfuzhang

**Comment by yeya** [comment]
please stop mention me, it's not me, thanks.

**Comment by brettpalmberg** [comment]
> Good Evening. Are these flags valid for the receiver?
> 
> **--tsdb.min-block-duration=2h --tsdb.max-block-duration=2h**
> 
> If so, can the flags be added to the documentation for receive component here: https://thanos.io/tip/components/receive.md/#flags?
> 
> cc @yeya @ahfuzhang

Oops, meant to cc @yeya24
