### ISSUE TITLE
[Feature Request] Store: cache bucket support local disk cache within time range

### ISSUE THREAD

**Issue by hanjm** [thanos-io/thanos#4638]
### Is your proposal related to a problem?

In time-based partitioning store gateway, Do we need a tools to sync the bucket full blocks files to local disk for store-gateway accerate? 

### Describe the solution you'd like
Implement a tools subcommand, download full blocks and keep time range sync, 
with --min-time --max-time --selector.relabel-config flag.

### Additional context

https://thanos.io/v0.22/components/store.md/#caching-bucket
https://thanos.io/tip/components/store.md/#time-based-partitioning

**Comment by yeya24** [comment]
What's the use case exactly? Blocks syncing at the start is only one-off, which is the same as the usage of a cmd tool?

**Comment by hanjm** [comment]
> What's the use case exactly? Blocks syncing at the start is only one-off, which is the same as the usage of a cmd tool?

Like caching-bucket chunks, but in local disk. https://thanos.io/tip/components/store.md/#caching-bucket

**Comment by hanjm** [comment]
still valid

**Comment by hanjm** [comment]
hi @bwplotka @GiedriusS @yeya24 , Do you think we could implement a boltdb local cache provider?  like cortex use boltdb as index caching https://github.com/cortexproject/cortex/blob/master/pkg/chunk/local/boltdb_index_client.go#L228. If OK, I can start implement.
