### ISSUE TITLE
Create Standalone Graphs for Thanos Running Outside of Kubernetes

### ISSUE THREAD

**Issue by jdfalk** [thanos-io/thanos#464]
Currently all the example graphs are made for running thanos in kubernetes. Please add examples for users not running thanos in kubernetes.

**Comment by sumanpatra** [comment]
How can grafana use data source from thanos querier http port lets say http://thanos:19192

Is this possible and supported by latest thanos release?

**Comment by bwplotka** [comment]
@sumanpatra yea, Grafana was always able to use Thanos HTTP endpoint as it implements std Prometheus Query API

**Comment by brancz** [comment]
If we abstract the labelling away in a thanos-mixin, then we could have interop for any environment. cc @metalmatze

**Comment by sumanpatra** [comment]
Yes I have configured, but it is not pulling any data as stores marked as down. #1095

**Comment by sumanpatra** [comment]
Seems code are designed to suit object storage/kubernetes only. My intention was to remote store and then check the functionality absence of object storage.

**Comment by brancz** [comment]
We have the Thanos mixin now which allows you to configure the alerting rules and dashboards for any type of environment. https://github.com/thanos-io/thanos/tree/master/mixin/thanos
