### ISSUE TITLE
Add labeldrop to sidecar

### ISSUE THREAD

**Issue by snuggie12** [thanos-io/thanos#4640]
### Is your proposal related to a problem?

We create around 8-12 external labels that are used in alerts to establish annotations, but are label dropped before being sent to Alert Manager.

It would be nice if sidecar had relabeling allowing this. Beyond making the information noisy, I think these extraneous labels also impacts storage and/or memory?

### Describe the solution you'd like

I'm guessing somewhere around [here](https://github.com/thanos-io/thanos/blob/bd134d7a823708fa135e7a6931e76f581be5f879/cmd/thanos/sidecar.go#L386-L389) relabeling is added? I know different components restrict which actions. AFAIK I only need `labeldrop`.

Not sure if this needs considered, but maybe there's some worry about dropping the built in prometheus EL's so I don't know if those need prevented from being dropped?

### Describe alternatives you've considered

It looks like maybe receive can achieve this though I'm currently happy with the sidecar mode and it seems that's preferred in the documentation as well.

### Additional context

I'm on 0.20, but AFAICT latest also doesn't have this functionality. If I made a mistake let me know.

**Comment by yeya24** [comment]
> It would be nice if sidecar had relabeling allowing this. Beyond making the information noisy, I think these extraneous labels also impacts storage and/or memory?

External labels only affect the metadata IIRC and have little impact on storage/memory cost.

> We create around 8-12 external labels that are used in alerts to establish annotations, but are label dropped before being sent to Alert Manager.

Can you give an example of this use case?

**Comment by snuggie12** [comment]
> > It would be nice if sidecar had relabeling allowing this. Beyond making the information noisy, I think these extraneous labels also impacts storage and/or memory?
> 
> External labels only affect the metadata IIRC and have little impact on storage/memory cost.

I thought I was reading it impacts the storage on the storegateway pod metadata. The documentation says each block should use 6MB but we're seeing 13MB. Regardless it is annoying.

> > We create around 8-12 external labels that are used in alerts to establish annotations, but are label dropped before being sent to Alert Manager.

> Can you give an example of this use case?

We create an external label such as `grafanaUrl` which has the environment specific domain name (e.g. grafana.foo.com vs grafana.foo-dev.com) stored in it. These are used for annotations in prometheus alerts and then dropped before going to AM. If there's a better way of achieving that I'm happy to switch to that.

**Comment by yeya24** [comment]
IIUC, these environment specific labels only applies to your alerts on Prometheus. Having these labels on the alerts is a better choice I think. Is this applicable in your case?

**Comment by snuggie12** [comment]
That's true though doesn't really work with gitops workflow or working with our developers. A given dev doesn't need to know the URL to grafana in a given environment, but rather can just template it in from external labels:
```
# how we do it now with no work for a dev
annotations:
  grafana_dashboard: {{ $externalLabels.external_grafana_url }}/foo/bar

# what a dev would need to do, per environment, accurately every time
annotations:
  grafana_dashboard: https://grafana.internal.foo.com/bar/baz # note that foo.com is only for one env and would be different in others
```

Though this is just my use case. There are possibly other people who don't want certain external labels added to their thanos data.

**Comment by snuggie12** [comment]
I agree on point 1 about size as it appears as if the labels are stored in `meta.json` so now it is more an annoyance showing up in logs and UIs, etc.

**Comment by snuggie12** [comment]
@yeya24 Is `meta.json` the only place they are located? If I edit that file will I achieve what I'm trying to do?
