### ISSUE TITLE
Interactive example does not work for MacOS 

### ISSUE THREAD

**Issue by metonymic-smokey** [thanos-io/thanos#4642]
**Thanos, Prometheus and Golang version used**: latest,2.29,1.16

**Object Storage Provider**:
Local filesystem

**What happened**:
The interactive example, `examples/interactive/interactive_test.go` does not run for MacOS users.  The `go test ` command results in an error. 

**What you expected to happen**:
The example should run without an error and the UI should open in a browser when it runs. 

**How to reproduce it (as minimally and precisely as possible)**:
Run `make docker`. Then run `go test interactive_test.go -test.timeout=9999m` in `examples/interactive. `

**Anything else we need to know**:

**Comment by matej-g** [comment]
Hey @metonymic-smokey, would you mind posting what is the exact error you get? 

AFAIK the interactive test has not been really tried on platforms other than Linux, but would be nice if we can make it work on MacOS as well.

**Comment by yeya24** [comment]
@matej-g The error I got locally:

```
❯ go test interactive_test.go -test.timeout=9999m
# github.com/containerd/cgroups
/Users/yeya24/go/pkg/mod/github.com/containerd/cgroups@v1.0.1/memory.go:463:14: undefined: unix.Eventfd
/Users/yeya24/go/pkg/mod/github.com/containerd/cgroups@v1.0.1/memory.go:463:30: undefined: unix.EFD_CLOEXEC
/Users/yeya24/go/pkg/mod/github.com/containerd/cgroups@v1.0.1/utils.go:70:8: undefined: unix.CGROUP2_SUPER_MAGIC
/Users/yeya24/go/pkg/mod/github.com/containerd/cgroups@v1.0.1/utils.go:77:18: undefined: unix.CGROUP2_SUPER_MAGIC
FAIL    command-line-arguments [build failed]
FAIL
```

**Comment by matej-g** [comment]
Hm it looks like we're hitting this https://github.com/containerd/cgroups/issues/19. The package is used in `e2emonitoring` in `efficientgo/e2e`. We will probably need to find a way to solve this in the upstream.

In the meantime, perhaps we have the tests without the monitoring endpoint, which would remove the dependency on `e2emonitoring` - which is nice-to-have but it is not essential for the interactive tests to run. WDYT?

**Comment by yeya24** [comment]
> In the meantime, perhaps we can have the tests without the monitoring endpoint, which would remove the dependency on e2emonitoring - which is nice-to-have but it is not essential for the interactive tests to run. WDYT?

SGTM!

**Comment by matej-g** [comment]
If anyone MacOS user can confirm this works :slightly_smiling_face:  - https://github.com/thanos-io/thanos/pull/4726

**Comment by metonymic-smokey** [comment]
I'll test this out tomorrow.
Thanks!

**Comment by yeya24** [comment]
Close now as it is fixed.
