### ISSUE TITLE
Use Thanos-Query or new Component to be compatible with Kiali

### ISSUE THREAD

**Issue by heartTorres** [thanos-io/thanos#4643]
### Is your proposal related to a problem?
Hello everyone, we are using Thanos receivers clusters.

Variables:
AWS EKS autoscale with around 1000 to 1300 nodes.

Monitoring tools:
Prometheus installed via Kube-stack-prometheus helm chart, 
Kiali, Istio, Jaeger, Grafana

Problem:
Our prometheus is already at 60GB Memory and still gets OOM Killed.
Removing unnecessary metrics is not yet an option as we do not know yet which metrics are being used in kiali and jaeger.
We have installed Thanos Components -> receivers, compactor, store and query. We set grafana's datasource thanos-query (which solved the query load when a lot of people queries in grafana ui).
Then we tried to use Thanos Query as datasource for Kiali however, we found out that there are apis from prometheus itself that it gets (not possible).

### Describe alternatives you've considered
Kiali needs prometheus to query data, is it possible thanos would also create a component or support a datasource for kiali in the future? :)

**Comment by yeya24** [comment]
Is this problem related to Thanos itself? 

> Use Thanos-Query or new Component to be compatible with Kiali

IIUC Kiali is compatible with any Prometheus Query API so Thanos Query is definitely compatible. If the problem is the memory usage of your Prometheus instance, try sharding or removing high cardinality metrics (you can check from the TSDB status page).

**Comment by heartTorres** [comment]
Hello @yeya24 , when we point our kiali to Thanos-Query there were some errors in kiali pod e.g. Kiali calls endpoint /config/status and many more errors. So what we just did was, we pointed the Grafana's datasource as is to Thanos Query but in Kiali we set its datasource to Prometheus. It still gets metrics I guess from Thanos  Query via the remote_read.

Closing this ticket. Thanks
