### ISSUE TITLE
Metrics of type ALERTS and ALERTS_FOR_STATE not ending up in objectstore

### ISSUE THREAD

**Issue by erikeverts** [thanos-io/thanos#4652]
**Thanos, Prometheus and Golang version used**:
Thanos store:
./thanos --version
thanos, version 0.18.0 (branch: HEAD, revision: 60d45a02d46858a38013283b578017a171cf7b82)
  build user:       root@4cf3f59273a2
  build date:       20210127-12:18:59
  go version:       go1.15.7
  platform:         linux/amd64

Thanos ruler:
 ./thanos --version
thanos, version 0.21.1 (branch: HEAD, revision: 3558f4a5adc8d4068f82528570a439d440f98b9d)
  build user:       root@744cf7ef4576
  build date:       20210604-12:11:58
  go version:       go1.16.5
  platform:         linux/amd64

Thanos receiver: 
./thanos --version
thanos, version 0.21.1 (branch: HEAD, revision: 3558f4a5adc8d4068f82528570a439d440f98b9d)
  build user:       root@744cf7ef4576
  build date:       20210604-12:11:58
  go version:       go1.16.5
  platform:         linux/amd64

**Object Storage Provider**:
Amazon S3
config file:
```
type: S3
config:
  bucket: "redacted"
  endpoint: "s3-external-1.amazonaws.com"
  access_key: "redacted"
  insecure: false
  signature_version2: false
  secret_key: "redacted"
```

**What happened**:
When alerts are generated by thanos ruler a metric of type ALERTS is also generated and stored in the local TSDB for thanos ruler. Thanos ruler also has a config for the objetstore. These metrics however don't end up in the objectstore and as such are not queryable from thanos query. Also when a prometheus instance which sends its metrics to thanos receiver has metrics if this type, these metrics do end op in the local tsdb for thanos query but don't end up in the object storage.
I am able to query for these types of metrics with thanos query, but only the ones that are on the local tsdb of thanos receiver. When selecting the thanos store only in thanos query, none of these metrics show up.

**What you expected to happen**:
The metrics for these types to be stored in object storage.

**How to reproduce it (as minimally and precisely as possible)**:
Make thanos ruler generate an alert. Then use thanos query to look for metrics of type ALERT, choosing the thanos store as source. 
or
Have a prometheus instance send metrics of the ALERT type, then use thanos query to search for this metric choosing only thanos store as source.
**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by yeya24** [comment]
Looks like a configuration issue. Can you see any TSDB blocks in your object storage created by Thanos ruler?

**Comment by erikeverts** [comment]
Do the blocks keep the same foldername (guid) when they are uploaded to objet storage? Else I don't really know how to find them in the object storage. 
But it must be noted that also metrics of this type that are received by thanos receiver are not in object storage while other metrics received by the same receiver and sent from the same prometheus are.

**Comment by erikeverts** [comment]
We have upgraded our thanos store version from 0.18 to 0.22 and now the issue seems to no longer exist. It might be a bug in 0.18.

**Comment by ianbillett** [comment]
I think we can safely close this issue if bumping to the most recent version fixed your issue :+1:
