### ISSUE TITLE
E2E Tests: Consider enabling race detector for test binary

### ISSUE THREAD

**Issue by matej-g** [thanos-io/thanos#4664]
Enabling race detector for E2E tests could help us in catching concurrency problems early on (see context here: https://github.com/thanos-io/thanos/issues/4579#issuecomment-917716313).

We could introduce a separate Dockerfile to build image specifically for testing, with separate `promu` config (we'll need to enable CGO and use a non-Alpine based image).

**Comment by bwplotka** [comment]
Yes 👍🏽

**Comment by tend2infinity** [comment]
Hey, I wanted to work on this issue, can anyone give me some guidance regarding this, thank you!

**Comment by matej-g** [comment]
Hey @tend2infinity, I'd say go for it!

As for guidance, it is written in the description in a kind of condensed form, but I believe we need to:
- Adjust (or probably create a new one really) Dockerfile which will take as a base image something else other than the Alpine image - the problem is the [race detector](https://go.dev/blog/race-detector) depends on having CGO enabled, which is not part of the Alpine image
- Add a new configuration for `promu` (utility which Thanos uses to build binaries) to ensure the binary for testing is actually build with CGO enabled. Have a look at current config in `.promu.yml` to get the picture.
- Adjust the `make` targets to use the new Dockerfile / build configuration for E2E tests.

If I still haven't cleared out something, feel free to ask!

**Comment by tend2infinity** [comment]
Hey thanks a lot @matej-g , I was actually kinda confused but now it seems clear, I'll ask if I get stuck into something

**Comment by matej-g** [comment]
This is actually in-progress, we just need a bit more :heart: to resolve races that have already been detected, see my comment in https://github.com/thanos-io/thanos/pull/5066#issuecomment-1056935086. These should be addressed before the race detection is merged, otherwise we'll (logically) end up with failing CI tests. Hopefully I'll (or someone else?) will be able to find the time to take a look soon :disappointed:.

cc @tend2infinity
