### ISSUE TITLE
Ruler: custom labels with HA causing compact failures

### ISSUE THREAD

**Issue by atjones0011** [thanos-io/thanos#4670]
**Thanos, Prometheus and Golang version used**:
Thanos 0.22.0
Prometheus 2.29.1
Go 1.16.6

**Object Storage Provider**:
AWS S3

**What happened**:
Compaction is failing because of overlapping blocks caused by Ruler replicas with identical labels. The matching labels come from the `labels` block of the CRD.

**What you expected to happen**: 
Ruler to include a replica label per pod even when custom labels are provided in the CRD. This ensures that a unique set of labels are given to each replica when running in HA.

**How to reproduce it (as minimally and precisely as possible)**:
In a ThanosRuler CRD:
* Set replicas > 1
* Provide one or more labels

Meeting these conditions causes the default thanos_ruler_replica label to not be provided and an identical set of labels to be provided on two separate Thanos Ruler replicas.

**Comment by yeya24** [comment]
@atjones0011 Can you show the `ThanosRuler` CRD you are using? 
Btw this sounds like an issue of Prometheus Operator.

If custom labels are specified, it still needs to add a `thanos_ruler_replica` label for different replicas to differentiate replica data instead of using identical labels.

Can you help open an issue on the prometheus operator repo? I am happy to help fix it if maintainers from prometheus-operator agree. cc @simonpasquier

**Comment by yeya24** [comment]
I guess for Thanos ruler, it recommends using 2 ThanosRuler crs for different replicas so that you can specify different `labels` and `dropLabels` for ruler. For one CRD with 2 replicas, it is not flexible enough. This seems like a bug.

**Comment by simonpasquier** [comment]
I agree with @yeya24, the documentation about ThanosRulerSpec.labels says:

> Labels configure the external label pairs to ThanosRuler. If not provided, default replica label thanos_ruler_replica will be added as a label and be dropped in alerts.

I guess that we can make it clearer that if you specify your own labels, you need to provide a replica-like label as well as the matching "drop label" directive.

**Comment by atjones0011** [comment]
Setting the label as `thanos_ruler_replica="$(POD_NAME)"` is exactly what I needed to resolve the problem. The replica label is now being set with the pod name and there's no longer duplicate blocks. Thanks for the help!
