### ISSUE TITLE
Thanos querier http_requests_total metric reports 503 status code

### ISSUE THREAD

**Issue by yaron-idan** [thanos-io/thanos#4675]
### Discussed in https://github.com/thanos-io/thanos/discussions/4630

<div type='discussions-op-text'>

<sup>Originally posted by **yaron-idan** September  2, 2021</sup>
Hey,
We are using Thanos to aggregate results from multiple k8s clusters.
Lately we've been seeing a rise in 503 error status codes emitted from the query container in our thanos-external-querier pod. 
These errors are indicated by a rise in the `http_requests_total{job="thanos-external-querier-query",code=~"5.*"}` metric.
However, when we look at the logs - there doesn't seem to be a log correlated to these errors.
We've tried to increase verbosity of by enabling debug log for the query component but there is still no indication of the request causing these errors.
What would be the proper way to troubleshoot this issue? 
We have a few clients querying thanos, mainly grafana dashboards and our monitoring system (Icinga), I highly suspect these errors originate from a human user loading a grafana dashboard as they are only manifested during working hours. Is there any way to validate this?</div>

**Comment by matej-g** [comment]
Hey @yaron-idan, what does the rest of your setup look like? What stores is the query pointing to? Seeing anything interesting in logs of those components? My initial thought is whether the issue actually does not occur further down the stack and gets propagated to query.

**Comment by yaron-idan** [comment]
Hey @matej-g, thanks for reaching out.
Our thanos querier is pointing at ~10 stores, which translate to 2-3 prometheus instances in each of our kubernetes clusters. 
I've checked the logs of the thanos sidecars attached to each prometheus instance, and also for the query-frontend that we have deployed in front of the cluster querier, but I can't find any logs that can help me pinpoint the issue.
Could the 5xx errors originate from the thanos sidecar? Would making logs for this component more verbose there can help?

**Comment by matej-g** [comment]
Hm looking quickly [at the code](https://github.com/thanos-io/thanos/blob/main/pkg/api/api.go#L261), `503` could be coming from receiving timeout / cancellation error.

Trying to increase verbosity of any component which you think might be causing the issue could help. Another thing that comes to my mind - if you're suspecting this is being triggered by particular queries, you could: 1) if you have tracing infrastructure in place, you could leverage tracing by using `tracing.config` flag and seeing if there is anything going with those suspicious queries; 2) enable query logging by using `request.logging-config` or `request.logging-config-file` and again try to investigate logs of any suspicious queries.
