### ISSUE TITLE
Exemplar: Can not set partial response.

### ISSUE THREAD

**Issue by hanjm** [thanos-io/thanos#4676]
**Thanos, Prometheus and Golang version used**:

**Object Storage Provider**:
COS
**What happened**:
query_exemplar response error: 
error: "retrieving exemplars: proxy Exemplars: receiving exemplars from exemplars client &{0xc000b2a000}: rpc error: code = Unimplemented desc = unknown service thanos.Exemplars"

**What you expected to happen**:
partial response with warning.
**How to reproduce it (as minimally and precisely as possible)**:
Thanos Query 0.23 beta + a old version sidecar not support exemplar
**Full logs to relevant components**:

**Anything else we need to know**:

seems missing flag to control exemplar partial reponse

**Comment by hanjm** [comment]
if a add a flag and pass it to NewExemplarsHandler, https://github.com/thanos-io/thanos/blob/main/pkg/api/query/v1.go#L798, thanos-query run OOM when query.

pprof heap is here 
```
File: thanos
Type: inuse_space
Time: Sep 18, 2021 at 9:52pm (CST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top10
Showing nodes accounting for 461.11MB, 97.97% of 470.68MB total
Dropped 66 nodes (cum <= 2.35MB)
Showing top 10 nodes out of 37
      flat  flat%   sum%        cum   cum%
  256.06MB 54.40% 54.40%   256.06MB 54.40%  github.com/pkg/errors.callers
  140.52MB 29.85% 84.26%   142.02MB 30.17%  github.com/pkg/errors.(*withMessage).Error
   23.50MB  4.99% 89.25%   271.56MB 57.69%  github.com/pkg/errors.New (inline)
   16.95MB  3.60% 92.85%   288.50MB 61.30%  github.com/thanos-io/thanos/pkg/exemplars.(*exemplarsServer).Send
    7.98MB  1.70% 94.54%     7.98MB  1.70%  google.golang.org/grpc/internal/transport.newBufWriter
       6MB  1.27% 95.82%        6MB  1.27%  reflect.New
    3.61MB  0.77% 96.59%     3.61MB  0.77%  bufio.NewReaderSize
    3.50MB  0.74% 97.33%     4.04MB  0.86%  fmt.Sprintf
       2MB  0.42% 97.76%     3.50MB  0.74%  github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/tracing.(*opentracingClientReporter).PostCall
       1MB  0.21% 97.97%        3MB  0.64%  google.golang.org/grpc/internal/status.(*Error).Error
(pprof)

```

**Comment by yeya24** [comment]
So actually partial response in the Exemplars API works, right? @hanjm Can you help confirm this?

If the flag works, then let's rename the issue to discuss the exemplars limit.

**Comment by hanjm** [comment]
I found seems missing exemplar.partial-response flag, so i add exemplar.partial-response flag in https://github.com/hanjm/thanos/commit/681608cb180641ec2fbc9d3ca0bea170d6bb723a, Partial response works in my brach.

**Comment by yeya24** [comment]
I see. @hanjm Looks like we have this config in the struct but forget to add a flag for it. Would you like to open a pr for it?

**Comment by hanjm** [comment]
> I see. @hanjm Looks like we have this config in the struct but forget to add a flag for it. Would you like to open a pr for it?

ok.

**Comment by hanjm** [comment]
I am investigate it.  from pprof heap, it seems too many warning message consume the memory.

i add a debug log to (*exemplarsServer).Send https://github.com/thanos-io/thanos/blob/main/pkg/exemplars/exemplars.go#L42

```go
func (srv *exemplarsServer) Send(res *exemplarspb.ExemplarsResponse) error {
	if res.GetWarning() != "" {
		err := errors.New(res.GetWarning())
		log.Printf("err message size: errors:%d, srv.warnings:%d, res.GetWarning():%d",
			len(err.Error()),
			len(srv.warnings),
			len(res.GetWarning()))
		srv.warnings = append(srv.warnings, err)
		return nil
	}
```

it will print a lot of logs like 
```
2021-09-19_12:19:54 2021/09/19 04:19:54 err message size: errors:130, srv.warnings:4277283, res.GetWarning():130

```

**Comment by hanjm** [comment]
then i print svr.warnings first ten message.

```go
func (srv *exemplarsServer) Send(res *exemplarspb.ExemplarsResponse) error {
	if res.GetWarning() != "" {
		err := errors.New(res.GetWarning())
		if len(srv.warnings) == 100 {
			log.Printf("err message size: errors:%d, srv.warnings:%d, res.GetWarning():%d, srv.warnings:%+v",
				len(err.Error()),
				len(srv.warnings),
				len(res.GetWarning()),
				srv.warnings[:10],
			)
		}

		srv.warnings = append(srv.warnings, err)
		return nil
	}

```

it print a log like
```
2021/09/19 06:09:37 err message size: errors:130, srv.warnings:100, res.GetWarning():130, srv.warnings:[receiving exemplars from exemplars client &{0xc0000a0700}: rpc error: code = Unimplemented desc = unknown service thanos.Exemplars
github.com/thanos-io/thanos/pkg/exemplars.(*exemplarsServer).Send
        /Users/jimmiehan/github.com/hanjm/thanos/pkg/exemplars/exemplars.go:45
github.com/thanos-io/thanos/pkg/exemplars.(*exemplarsStream).receive
        /Users/jimmiehan/github.com/hanjm/thanos/pkg/exemplars/proxy.go:193
github.com/thanos-io/thanos/pkg/exemplars.(*Proxy).Exemplars.func1
        /Users/jimmiehan/github.com/hanjm/thanos/pkg/exemplars/proxy.go:133
golang.org/x/sync/errgroup.(*Group).Go.func1
        /Users/jimmiehan/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57
runtime.goexit
        /Users/jimmiehan/sdk/go1.16.3/src/runtime/asm_amd64.s:1371 receiving exemplars from exemplars client &{0xc0000a0700}: rpc error: code = Unimplemented desc = unknown service thanos.Exemplars
github.com/thanos-io/thanos/pkg/exemplars.(*exemplarsServer).Send
        /Users/jimmiehan/github.com/hanjm/thanos/pkg/exemplars/exemplars.go:45
github.com/thanos-io/thanos/pkg/exemplars.(*exemplarsStream).receive
        /Users/jimmiehan/github.com/hanjm/thanos/pkg/exemplars/proxy.go:193
github.com/thanos-io/thanos/pkg/exemplars.(*Proxy).Exemplars.func1
        /Users/jimmiehan/github.com/hanjm/thanos/pkg/exemplars/proxy.go:133
golang.org/x/sync/errgroup.(*Group).Go.func1
        /Users/jimmiehan/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57
runtime.goexit
        /Users/jimmiehan/sdk/go1.16.3/src/runtime/asm_amd64.s:1371 receiving exemplars from exemplars client &{0xc0000a0700}: rpc error: code = Unimplemented desc = unknown service thanos.Exemplars
github.com/thanos-io/thanos/pkg/exemplars.(*exemplarsServer).Send
        /Users/jimmiehan/github.com/hanjm/thanos/pkg/exemplars/exemplars.go:45
github.com/thanos-io/thanos/pkg/exemplars.(*exemplarsStream).receive
        /Users/jimmiehan/github.com/hanjm/thanos/pkg/exemplars/proxy.go:193
github.com/thanos-io/thanos/pkg/exemplars.(*Proxy).Exemplars.func1
        /Users/jimmiehan/github.com/hanjm/thanos/pkg/exemplars/proxy.go:133
golang.org/x/sync/errgroup.(*Group).Go.func1
        /Users/jimmiehan/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57
runtime.goexit

```

so, The conclusion seems misuse `pkg/errors`, wrap a error message twice.

**Comment by hanjm** [comment]
Seems it is better if keep one `warning` in single gRPC bid-stream call. instead of multi `warning` . @yeya24  do you think so?

**Comment by MrYueQ** [comment]
Hi. The version of thanos has been rolled back to 0.22. In addition, in the current version, --query-frontend.downstream-url uses the load balancing mechanism, and the load balancing mechanism is weighted round-robin. No matter how the client's IP changes. The upstream of the backend will only be routed to the same IP.

thanos-query host resource
![image](https://user-images.githubusercontent.com/14846522/133921906-8018cf29-e294-4860-b330-2daa076771c8.png)

thanos-query-frontend host resource

![image](https://user-images.githubusercontent.com/14846522/133921931-06aab056-f66e-4d1f-9c05-8cf6fcf9bf54.png)

![image](https://user-images.githubusercontent.com/14846522/133922251-b8d1fcc7-06e7-4ce5-9ff6-700c1f5ce798.png)

**Comment by hanjm** [comment]
If the store-api target not implement exemplar API, err is `rpc error: code = Unimplemented desc = unknown service thanos.Exemplars`. the grpc bid-steam loop will be infinite loop due to the wrong error handing.
https://github.com/thanos-io/thanos/blob/main/pkg/exemplars/proxy.go#L195
```
for {
		exemplar, err := exemplars.Recv()
		if err == io.EOF {
			return nil
		}

		if err != nil {
			err = errors.Wrapf(err, "receiving exemplars from exemplars client %v", stream.client)

			if stream.request.PartialResponseStrategy == storepb.PartialResponseStrategy_ABORT {
				return err
			}

			if err := stream.server.Send(exemplarspb.NewWarningExemplarsResponse(err)); err != nil {
				return errors.Wrapf(err, "sending exemplars error to server %v", stream.server)
			}

			continue
		}

		if w := exemplar.GetWarning(); w != "" {
			if err := stream.server.Send(exemplarspb.NewWarningExemplarsResponse(errors.New(w))); err != nil {
				return errors.Wrapf(err, "sending exemplars warning to server %v", stream.server)
			}
			continue
		}

		select {
		case stream.channel <- exemplar.GetData():
		case <-ctx.Done():
			return ctx.Err()
		}
	}
```

**Comment by hanjm** [comment]
Fix at PR #4676

**Comment by MrYueQ** [comment]
![image](https://user-images.githubusercontent.com/14846522/133927413-b6880331-e8cb-438d-afb0-33adf9fbedbf.png)
![image](https://user-images.githubusercontent.com/14846522/133927423-6b5ee58b-e191-4be4-93bf-92c2c6c92184.png)

**Comment by hanjm** [comment]
> Hi. The version of thanos has been rolled back to 0.22. In addition, in the current version, --query-frontend.downstream-url uses the load balancing mechanism, and the load balancing mechanism is weighted round-robin. No matter how the client's IP changes. The upstream of the backend will only be routed to the same IP.


@MrYueQ  Seems not relevent? Please feel free to open another issue ~
