### ISSUE TITLE
specifally query thnoas sidecars from thanos queriers when using grafana  

### ISSUE THREAD

**Issue by denniceritchie** [thanos-io/thanos#4691]
While writing queries in grafana, How can I mention I need the data to be fetched from specific sidecars only for faster retrieval instead of store gateway?

**Comment by yeya24** [comment]
There are two ways I can think of:
1. Use a recent time range. Sidecar always has the latest data while store gateway usually has not so updated data. If you select a recent query time range then it is possible to skip store gateway.
2. You can use store filtering in the Thanos UI to only query sidecars. But it is not easy to do this in Grafana. IIRC you can only set customQueryParams in the datasource configuration but it is global for this datasource.

**Comment by hanjm** [comment]
Try set store gateway flags --max-time=1d to serve only time 1 day ago.

**Comment by hanjm** [comment]
the querier will use sidecar/store external label as first filter.
for example:
there are two prometheus，one config `team='a'` external label. another config `team='b'` external label.
if the query is 'up{team='a'}'，it only query the first one prometheus sidecar.

the store gateway has relabel config filter and time range filter，it can on serve a part of labels or time range across all the blocks. for example， set store gateway flags --max-time=1d to serve only time 1 day ago.

**Comment by yeya24** [comment]
@denniceritchie Will close this issue for now. Let me know if you still have other questions.
