### ISSUE TITLE
Data inconsistency between vanilla Prometheus & Thanos + Prometheus Operator

### ISSUE THREAD

**Issue by om3171991** [thanos-io/thanos#4698]
Hi Team,

We have onboarded Thanos 1 month back and we are seeing some data consistency issues between vanilla Prometheus & Thanos.

![image](https://user-images.githubusercontent.com/86664910/134562254-d220b5c3-8768-4a1e-b62a-b42c42683023.png)
![image](https://user-images.githubusercontent.com/86664910/134562376-8d5c0a58-5709-4c9d-acf2-514836008a81.png)
![image](https://user-images.githubusercontent.com/86664910/134563948-63346516-c89a-4716-b23b-4ff77d943247.png)

Image1 is from Thanos querier where data is coming from sidecar & object store with Max 5m down-sampling 
image2 is from Prometheus which has its local storage to persist data 
image3 is again from Thanos with Raw data points.

but the difference between metric values between these screenshots is huge and causing an issue with alerting and visualization of metrics over Grafana dashboards.

Can someone please suggest where can I look for a potential issue?

Thanos version: v0.20.0

**Comment by yeya24** [comment]
How many Prometheus instances are you running? If you are running with more than 1 Prometheus then inconsistency is possible because of how Thanos deduplication works.

**Comment by om3171991** [comment]
@yeya24 - currently 1 instance of Prometheus is running for Thanos. No replica till now but yeah we will have some in the future so can you share some insight/reading material on deduplication of metric by Thanos with multiple replicas.

**Comment by alpadotsh** [comment]
I am running into similar issues when a simple query `sum by (namespace, pod) (rate(istio_requests_total{response_code=~"5.."}[15m])) / sum by (namespace, pod) (rate(istio_requests_total[15m]))
` returns abnormal results, i.e. `> 1`.
