### ISSUE TITLE
thanos failed to store data 

### ISSUE THREAD

**Issue by wangshiboqq** [thanos-io/thanos#4705]
thanos failed to store data

**Comment by wangshiboqq** [comment]
![image](https://user-images.githubusercontent.com/4270095/134798086-1c1198ea-4deb-40ca-a888-626212124a27.png)

**Comment by wangshiboqq** [comment]
thanos store --data-dir /data/storage/thanos/store --objstore.config-file /usr/local/thanos/bucket_config.yaml --http-address 0.0.0.0:39191 --grpc-address 0.0.0.0:39090 --log.level=debug

**Comment by wangshiboqq** [comment]
thanos query --http-address 0.0.0.0:29090 --grpc-address 0.0.0.0:29091 --query.replica-label monitor --store 10.39.193.212:19091 --store 10.39.193.212:39090 --log.level=debug

**Comment by wangshiboqq** [comment]
[root@monitor-01 store]# pwd
/data/storage/thanos/store
[root@monitor-01 store]# ll
total 16
drwxr-xr-x 2 root root     6 Sep 26 15:21 meta-syncer

**Comment by wangshiboqq** [comment]
doese anyone have any idea for this issue? I could not find any useful log...

**Comment by yeya24** [comment]
For sidecar, `Max Time` is infinite is expected.
Store gateway doesn't have any data in the object storage right now so the output seems correct besides the `invalid data` issue.

Which object storage are you using?

**Comment by amewayne** [comment]
Encountered the same problem. I checked  out **thanos.shipper.json** in prometheus tsdb directory. this is what it looks like
`{
	"version": 1,
	"uploaded": null
}`
