### ISSUE TITLE
Thanos Block UI do not show all blocks in v0.23.0

### ISSUE THREAD

**Issue by MioOgbeni** [thanos-io/thanos#4722]
thanos, version 0.23.0 (branch: HEAD, revision: fe0d695e8df8619f2e6588e6259230a13535001a)
build user:       circleci@80970a8015b2
build date:       20210927-14:57:42
go version:       go1.16.8
platform:         linux/amd64

**What happened**:
Hi. I noticed, that new version of Thanos don't show all block from S3 in Block UI.

How you can see on image below. Left side is version v0.22.0 and right side is v0.23.0 (same blocks, same time-range). Also I noticed that ordering of block series is wierd in new version, but it's just a matter of opinions
https://imgur.com/Url1Ee3

**How to reproduce it (as minimally and precisely as possible)**:
Only change version of image, all setting still same.
I'm running Thanos with this flags
```     
tools
bucket
web
--http-address=0.0.0.0:8080
--log.level=info
--log.format=logfmt
--objstore.config-file=/conf/objstore.yml
--refresh=15m
--timeout=5m
```
**Full logs to relevant components**:
I think that log is useless, because it also remained the same, but here it is.

```
level=info ts=2021-10-01T08:50:33.038571732Z caller=factory.go:49 msg="loading bucket configuration"
level=info ts=2021-10-01T08:50:33.23525002Z caller=intrumentation.go:48 msg="changing probe status" status=ready
level=info ts=2021-10-01T08:50:33.334704042Z caller=intrumentation.go:60 msg="changing probe status" status=healthy
level=info ts=2021-10-01T08:50:33.334778343Z caller=http.go:63 service=http/server component=bucket msg="listening for requests and metrics" address=0.0.0.0:8080
ts=2021-10-01T08:50:33.335664274Z caller=log.go:168 service=http/server component=bucket level=info msg="TLS is disabled." http2=false
level=info ts=2021-10-01T08:50:53.638430742Z caller=fetcher.go:476 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=20.403049851s duration_ms=20403 cached=319 returned=108 partial=0
```

**Comment by yeya24** [comment]
I am not sure why this happened. Probably it is still sync block metadatas? Is this issue still happening?

**Comment by MioOgbeni** [comment]
Hi. Yes it is still happening. These blocks are not displayed during several days continuous running of the pod. I think that it has something to do with new UI feature "#4462 UI: Highlighting blocks overlap in the Block UI.", because missing blocks are basically overlapping with already compacted blocks on higher lvl of compaction and only these blocks are missing from UI. But when I turn on this "highlighting" feature in UI, there is not shown any block.

I wanted to look into the code to see if this feature was properly implemented, but I have not found the time for this.
