### ISSUE TITLE
query: Query API is unresponsive but health/ready APIs report healthy/ready

### ISSUE THREAD

**Issue by AdmiralGT** [thanos-io/thanos#4766]
**Thanos, Prometheus and Golang version used**: Thanos v0.23.0-rc.1

**Object Storage Provider**: Azure, accessed via a managed identity.

**What happened**: I have deployed 2 Thanos query nodes, Prometheus, Thanos query frontend, Ruler, Store, Grafana in multiple Azure k8s service clusters using thanos, kube-prometheus-stack and grafana helm charts. The Query nodes are configured in a hierarchical fashion, such that one query node collects metrics solely from the cluster and the other queries the query node in every deployed cluster. Query Frontend sits in front of the top level query node.

The query API of the top level query node is completely unresponsive and does not respond or timeout API calls. I've tried using the different API endpoints e.g. query, labels but they are all unresponsive. However, both the healthy and ready APIs are reporting success and I'm not seeing any significant logs in the query node other than some SRV records failing to be resolved (which is expected as those clusters are currently down).

The query API in the low level query node is also fine and I can query metrics from the cluster, I just am unable to query metrics covering multiple clusters.

**What you expected to happen**: Query API to respond to queries when pod is reported healthy or timeout.

**How to reproduce it (as minimally and precisely as possible)**: I don't have exact reproduction steps. I have deployed multiple clusters and in 6, the top level query API has come up successfully while in 2, query API was unresponsive. Restarting the Query pod has resolved the issue in one cluster but since the healthy API is reporting success, this is not happening automatically.

**Comment by AdmiralGT** [comment]
I've attached a couple of outputs from the goroutine endpoint while this is happening.

[goroutines.tar.gz](https://github.com/thanos-io/thanos/files/7329479/goroutines.tar.gz)

**Comment by ahurtaud** [comment]
Hello,

Same issue for me with similar setup.
Issue is always happening on the same platform (the biggest query leaf)
[profilegoroutine2.pdf](https://github.com/thanos-io/thanos/files/7351769/profilegoroutine2.pdf)
[profile-goroutines.pdf](https://github.com/thanos-io/thanos/files/7351771/profile-goroutines.pdf)
.

**Comment by pentlander** [comment]
Same here, we ran into significant downtime due to this issue. I think it would be worth releasing a patch version with this fix.
