### ISSUE TITLE
Shipper: allow uploading compacted overlapping blocks?

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#4787]
### Is your proposal related to a problem?

If vertical compaction is enabled at the compactor side, then it is okay to upload out of order blocks to the remote bucket and the overlapping check is not needed.

### Describe the solution you'd like

Have a new shipper flag to ignore the overlap checker. This could be a hidden flag as the vertical compaction flag in the compactor is also hidden.

**Comment by hanjm** [comment]
+1

**Comment by hanjm** [comment]
I think it is reasonable.

**Comment by metonymic-smokey** [comment]
Will work on this next.

**Comment by metonymic-smokey** [comment]
Should `receive.MultiTSDB` in receive have an extra parameter added too, since it invokes `shipper.New` or should that just be set to some default?

**Comment by bwplotka** [comment]
Overall makes sense to me (:
