### ISSUE TITLE
Thanos receiver alert fire when component is deployed but not used

### ISSUE THREAD

**Issue by psandhu79** [thanos-io/thanos#4788]
The following alert in the examples

  - alert: ThanosReceiveNoUpload
    annotations:
      description: Thanos Receive {{$labels.instance}} has not uploaded latest data
        to object storage.
      runbook_url: https://github.com/thanos-io/thanos/tree/main/mixin/runbook.md#alert-name-thanosreceivenoupload
      summary: Thanos Receive has not uploaded latest data to object storage.
    expr: |
      (up{job=~".*thanos-receive.*"} - 1)
      + on (job, instance) # filters to only alert on current instance last 3h
      (sum by (job, instance) (increase(thanos_shipper_uploads_total{job=~".*thanos-receive.*"}[3h])) == 0)
    for: 3h
    labels:
      severity: critical

This alert fires when the thanos reciever is deployed but not in use , i was expecting no alerts to fire if component is not in use

**Comment by psandhu79** [comment]
@brancz is another metric available to see if any data exists to be uploaded ??

**Comment by tl-eirik-albrigtsen** [comment]
I have also been seeing this alert fire (on thanos 0.34.0) and it doesn't look like there's anything wrong with the receiver:

metric (dumped from pod) indicates it SHOULD have done 3 uploads:

> thanos_objstore_bucket_operation_duration_seconds_bucket{bucket="t7r-thanos-eks-development",operation="upload",le="+Inf"} 3

confirmed by other metrics:
> thanos_objstore_bucket_operation_transferred_bytes_bucket{bucket="t7r-thanos-eks-development",operation="upload",le="+Inf"} 3
> thanos_objstore_bucket_operations_total{bucket="t7r-thanos-eks-development",operation="upload"} 3

with NO failed uploads:
> thanos_objstore_bucket_operation_failures_total{bucket="t7r-thanos-eks-development",operation="upload"} 0
> thanos_shipper_upload_failures_total{tenant="thanos"} 0

however:
> thanos_shipper_uploads_total{tenant="thanos"} 1

i.e. the counter in the alert only incremented once over a 32h time period
there's also no failure counters incremented anywhere, and no errors in the logs, but it does seem that every upload cycle the receiver says that the "Write block resulted in an empty block" so maybe that's a clue?

basically all upload cycles look likes this:
```
ts=2024-02-21T21:04:52.963504437Z caller=head.go:1331 level=info component=receive component=multi-tsdb tenant=thanos msg="Head GC completed" caller=truncateMemory duration=1.466725ms
ts=2024-02-21T21:04:52.963614849Z caller=checkpoint.go:100 level=info component=receive component=multi-tsdb tenant=thanos msg="Creating checkpoint" from_segment=14749 to_segment=14750 mint=1708476210372
ts=2024-02-21T21:04:52.967788383Z caller=head.go:1293 level=info component=receive component=multi-tsdb tenant=thanos msg="WAL checkpoint complete" first=14749 last=14750 duration=4.24861ms
ts=2024-02-21T23:04:52.93047251Z caller=multitsdb.go:398 level=info component=receive component=multi-tsdb tenant=thanos msg="Compacting tenant"
ts=2024-02-21T23:04:52.966986508Z caller=compact.go:521 level=info component=receive component=multi-tsdb tenant=thanos msg="write block resulted in empty block" mint=1708476210372 maxt=1708476210373 duration=36.46391ms
ts=2024-02-21T23:04:52.97074664Z caller=head.go:1331 level=info component=receive component=multi-tsdb tenant=thanos msg="Head GC completed" caller=truncateMemory duration=1.523942ms
ts=2024-02-22T01:04:52.930295913Z caller=multitsdb.go:398 level=info component=receive component=multi-tsdb tenant=thanos msg="Compacting tenant"
ts=2024-02-22T01:04:52.963072474Z caller=compact.go:521 level=info component=receive component=multi-tsdb tenant=thanos msg="write block resulted in empty block" mint=1708476210373 maxt=1708476210374 duration=32.732417ms
```

does this indicate a failure / misconfiguration somewhere, or is this ok?

thanos args:

```yaml
  - args:
    - receive
    - --log.level=info
    - --log.format=logfmt
    - --grpc-address=0.0.0.0:10901
    - --http-address=0.0.0.0:10902
    - --remote-write.address=0.0.0.0:19291
    - --objstore.config=$(OBJSTORE_CONFIG)
    - --tsdb.path=/var/thanos/receive
    - --label=replica="$(NAME)"
    - --label=receive="true"
    - --tsdb.retention=8d
    - --receive.local-endpoint=127.0.0.1:10901
    - --receive.hashrings-file=/var/lib/thanos-receive/hashrings.json
    - --receive.replication-factor=1
    - --receive.hashrings-algorithm=ketama
    - --receive.default-tenant-id=thanos
    - --store.limits.request-series=100000
```

**Comment by suryapandian** [comment]
> Closing for now as promised, let us know if you need this to be reopened! 🤗

Please open
