### ISSUE TITLE
thanos-store can not query long-time ago data

### ISSUE THREAD

**Issue by ly123-liu** [thanos-io/thanos#4798]
version: 0.12.0

we use thanos-store with remote oss storage , on the oss bucket ,we can see long-time block exists, but when we use thanos-query to connect thanos-store to query long-time ago data, shows no block found, why?

oss data shows this block is update 2021.04.29
![image](https://user-images.githubusercontent.com/57338370/138441344-cd89530a-caef-408e-95b3-0ef87d426ad7.png)

when we use grafana to query, we can only find data with 2021.09.16 ,why ?
![image](https://user-images.githubusercontent.com/57338370/138441295-7afc4ae7-cc6d-48eb-98d6-3104fca07980.png)

thanos-store log shows:
![image](https://user-images.githubusercontent.com/57338370/138441506-3a159d20-bb64-4304-8848-b485398ed625.png)

**Comment by yeya24** [comment]
Your thanos version is a little bit old. Some questions about your setup first:
1. Have you enabled auto downsampling in your querier?
2. Have you set any downsampling params in the Grafana datasource?

**Comment by lancanming** [comment]
hello, may I know how did you solve this issue?
