### ISSUE TITLE
Thanos Query Frontend - 1 month dataset Dashboard "Bad Gateway"

### ISSUE THREAD

**Issue by louij2** [thanos-io/thanos#4799]
**Thanos, Prometheus and Golang version used**: 0.23.1 & go1.16.8

**Object Storage Provider**: Azure

**What happened**: Ran a large dashboard retrieving metrics over 1 month. Got a bad gateway error.

**What you expected to happen**: To show the dashboard metrics

**How to reproduce it (as minimally and precisely as possible)**: Just open dashboard that queries 1 month of metrics

**Full logs to relevant components**:
![image](https://user-images.githubusercontent.com/2940588/138656690-da31ccc0-ea79-4e59-a856-0e3e5078ec36.png)

**Anything else we need to know**:

**Comment by louij2** [comment]
64GB mem and still bad gateway, probably need to try containers

**Comment by louij2** [comment]
I gave the VM 64 cores and 128GB memory and it seems to load. I guess I need to re-deploy everything in containers if I have such huge requirements to load 1 dashboard every month, as everything else loads fine with 2 core 8GB memory.

**Comment by heyitsmdr** [comment]
We're also seeing this as well, for some of our more computationally expensive queries. They are all being terminated in Grafana with 502s right at the 30s mark. Does the Query Frontend have a hard-coded timeout of 30 seconds? I found [this timeout](https://github.com/thanos-io/thanos/blob/main/pkg/queryfrontend/request.go#L27) for `ThanosQueryRangeRequest` but cannot yet find where it is actually used.

**Comment by louij2** [comment]
> We're also seeing this as well, for some of our more computationally expensive queries. They are all being terminated in Grafana with 502s right at the 30s mark. Does the Query Frontend have a hard-coded timeout of 30 seconds? I found [this timeout](https://github.com/thanos-io/thanos/blob/main/pkg/queryfrontend/request.go#L27) for `ThanosQueryRangeRequest` but cannot yet find where it is actually used.
> 
> EDIT: We were able to narrow this down to the [dataproxy.timeout](https://grafana.com/docs/grafana/latest/administration/configuration/#timeout) setting within Grafana. It was defaulted to `30s` and was causing our datasource proxy requests to time out after 30s despite the upstream components having longer timeouts set. Maybe this will help someone else with a similar set up.

This was the solution, wow was it a long journey. I wish someone picked up on it sooner!
