### ISSUE TITLE
Thanos Compactor & store-gateway crashing when more than 1000 directories in Bucket s3

### ISSUE THREAD

**Issue by jfpucheu** [thanos-io/thanos#4800]
**Thanos, Prometheus and Golang version used**:
thanos Version: 0.23.1

**Object Storage Provider**: S3

**What happened**:

Thanos Compactor & store-gateway crashing when more than 1000 directories in Bucket s3

**What you expected to happen**: continue working

**How to reproduce it (as minimally and precisely as possible)**:
Create more than 1000 directories in S3 Bucket 

**Full logs to relevant components**:

Uncomment if you would like to post collapsible logs:

<details>Logs
<p>

level=info ts=2021-10-25T20:44:21.973985358Z caller=grpc.go:160 service=gRPC/server component=store msg="internal server is shutdown gracefully" err="bucket store initial sync: sync block: BaseFetcher: iter bucket: Truncated response should have continuation token set"
level=error ts=2021-10-25T20:44:21.974188558Z caller=main.go:157 err="Truncated response should have continuation token set\nBaseFetcher: iter bucket\ngithub.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetchMetadata\n\t/app/pkg/block/fetcher.go:377\ngithub.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetch.func2\n\t/app/pkg/block/fetcher.go:438\ngithub.com/golang/groupcache/singleflight.(*Group).Do\n\t/go/pkg/mod/github.com/golang/groupcache@v0.0.0-20210331224755-41bb18bfe9da/singleflight/singleflight.go:56\ngithub.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetch\n\t/app/pkg/block/fetcher.go:436\ngithub.com/thanos-io/thanos/pkg/block.(*MetaFetcher).Fetch\n\t/app/pkg/block/fetcher.go:497\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).SyncBlocks\n\t/app/pkg/store/bucket.go:433\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).InitialSync\n\t/app/pkg/store/bucket.go:502\nmain.runStore.func4\n\t/app/cmd/thanos/store.go:365\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\nsync block\ngithub.com/thanos-io/thanos/pkg/store.(*BucketStore).InitialSync\n\t/app/pkg/store/bucket.go:503\nmain.runStore.func4\n\t/app/cmd/thanos/store.go:365\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\nbucket store initial sync\nmain.runStore.func4\n\t/app/cmd/thanos/store.go:367\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\nstore command failed\nmain.main\n\t/app/cmd/thanos/main.go:157\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"

</p>
</details>

**Anything else we need to know**:
seems link to minio issue:

https://github.com/minio/minio-go/issues/1130

**Comment by GiedriusS** [comment]
Given that the option there is exactly for this case and no response, I am closing this issue to keep our issue tracker clean. Please let us know if this persists!
