### ISSUE TITLE
Add out-of-order blocks to bucket verify

### ISSUE THREAD

**Issue by AndrewNiven1** [thanos-io/thanos#4804]
### Is your proposal related to a problem?

When a Compactor halts due to an out-of-order (OOO) block, there are normally several OOO blocks that need to be tidied up before Compactor can safely run again. At the moment, Compactor only tells me about the first OOO block that it finds - so I need to go through quite a long cycle of identifying a broken block, deleting the broken block, and restarting compactor, multiple times before the storage account is clean.

### Describe the solution you'd like

I would like `thanos tools bucket verify` to check for OOO blocks, and to tell me about all of the ones that it finds.

### Describe alternatives you've considered

n.a.

### Additional context

n.a.

**Comment by yeya24** [comment]
Are you looking for a tool to check OOO chunks or OOO blocks? If it is the latter one, the verify tool can already tell your all overalapped blocks for a group I think.

**Comment by AndrewNiven1** [comment]
Just to be clear on terminology, what would you consider a chunk and what would you consider a block?

My experience last week was that `thanos tools bucket verify` gave me a list of overlapped blocks, all of which I deleted. When I restarted Thanos Compactor, it then halted on a block which hadn't been part of the output of `verify`. I don't have a note of the error message, but it was because the block contained a small number (1 or 2) of out-of-order time series, rather than the whole block being out of order, if this is what your question is referring to. Is the issue here that `verify` only verifies that the timestamps of the blocks themselves are in order, but doesn't verify the time series within them?

**Comment by metonymic-smokey** [comment]
@AndrewNiven1 this describes the difference between chunks and blocks - https://thanos.io/tip/thanos/design.md/#metric-data-backup 

Another question: When you ran `tools bucket verify` did you receive any warning about OOO series, along with overlapping blocks? 
The index issues checked during mention any OOO series.

**Comment by yeya24** [comment]
> When I restarted Thanos Compactor, it then halted on a block which hadn't been part of the output of verify. I don't have a note of the error message, but it was because the block contained a small number (1 or 2) of out-of-order time series rather than the whole block being out of order, if this is what your question is referring to.

Yes, out of order time series and halting is related to OOO chunks and has nothing to do with OOO blocks.

>  Is the issue here that verify only verifies that the timestamps of the blocks themselves are in order, but doesn't verify the time series within them?

The verify tool already supports verifying all series by default. But this is another step after checking the overlapped blocks. So if you failed the previous check, the check for OOO chunks won't start.

Can you try the latest main branch? With https://github.com/thanos-io/thanos/pull/4727/files#diff-ff9912cc5d78d6a548e6ba9cc818cd48e67f7ee5e23a817107cc84ba55c68e02R331 and debug log level we are already able to show all out of order chunks.

**Comment by AndrewNiven1** [comment]
Hi both, thanks for your answers. I was using v0.23.0-rc.1, so I don't have that last PR which would hopefully provide what I want. Unfortunately I already tidied up the ABS that was causing problems, so I can't reproduce the issue or do any testing on it. What I remember is:

- I ran `tools bucket verify`, which gave me a list of overlapping blocks
- I deleted these blocks
- I ran `tools bucket verify` again, without the `repair` flag, which did not report any issues
- I ran Thanos Compactor, which halted because of an OOO series

As you say, Thanos should already do what I want it to, so either there's a bug or I've missed something - in either case I don't think there's much more to be discussed here until I can reproduce the issue. I'll try and do this when I get time.

Thanks both

**Comment by AndrewNiven1** [comment]
Hi again,

I'd like to reopen this issue, as I'm seeing the same behaviour again. 

When compactor is running against a certain ABS, it fails with the following error message:

```level=warn ts=2021-11-26T07:48:58.625467572Z caller=intrumentation.go:54 msg="changing probe status" status=not-ready reason="error executing compaction: compaction: group 0@17975502000459606275: blocks with out-of-order chunks are dropped from compaction:  /data/compact/0@17975502000459606275/01FKQ2QTPC73X07XKW7VS1E8JG: 1/438729 series have an average of 1.000 out-of-order chunks: 1.000 of these are exact duplicates (in terms of data and time range)"```

There are several similar error message referring to the same block.

If I run `thanos tools bucket verify` over the ABS account, using `--issues=index_known_issues`, I would expect to see the out of order time series - as I understand it, the line you linked above ([this one](https://github.com/thanos-io/thanos/blob/78391ded0f4821f650ed2c4f097b505f4fa30713/pkg/block/index.go#L331)) that flags OOO series is run as part of the `index_known_issues` check. However, I see no error message:

```developer@DESKTOP-3VQU89P:~/work/temp/2111$ docker build . --no-cache | grep 01FKQ2QTPC73X07XKW7VS1E8JG
Step 4/4 : RUN thanos tools bucket verify --log.level=debug --issues=index_known_issues --id=01FKQ2QTPC73X07XKW7VS1E8JG --objstore.config-file=/objstore.yml
level=debug ts=2021-11-29T14:25:29.069639483Z caller=azure.go:374 msg="check if blob exists" blob=01FKQ2QTPC73X07XKW7VS1E8JG/meta.json
level=debug ts=2021-11-29T14:25:29.461829594Z caller=azure.go:295 msg="getting blob" blob=01FKQ2QTPC73X07XKW7VS1E8JG/meta.json offset=0 length=0
level=debug ts=2021-11-29T14:25:29.461953931Z caller=azure.go:374 msg="check if blob exists" blob=01FKQ2QTPC73X07XKW7VS1E8JG/meta.json
level=debug ts=2021-11-29T14:25:34.977022191Z caller=azure.go:326 msg="set size to go to EOF" contentlength=983 size=983 length=0 offset=0 name=01FKQ2QTPC73X07XKW7VS1E8JG/meta.json
```

This is the same if I enable the `--repair` flag. 

This is using the most up to date version of master as of this morning (main-2021-11-26-78391ded).

For what it's worth, I'm aware that one of our microservices is sometimes pushing out-of-order time series, and I'm trying to get that fixed, but in the meantime we need to be able to easily identify and repair these out-of-order series.

I'm curious about why the out-of-order series is picked up by the check in the Compaction routine, but not in the Verify routine - I'm going to try and compare the code and see what the difference is.

Any help (or pointing out that I've done something wrong) would be much appreciated.

**Comment by AndrewNiven1** [comment]
I've run verify again - the first time I ran it I didn't get a summary at the end, but this time I did. The final output is as follows:

```
level=debug ts=2021-11-29T15:50:24.250768867Z caller=index_issue.go:64 verifiers=index_known_issues verifier=index_known_issues stats="{TotalSeries:49402 OutOfOrderSeries:0 OutOfOrderChunks:0 DuplicatedChunks:0 OutsideChunks:0 CompleteOutsideChunks:0 Issue347OutsideChunks:0 OutOfOrderLabels:0 SeriesMinLifeDuration:2m44.631s SeriesAvgLifeDuration:1h58m21.913s SeriesMaxLifeDuration:1h59m30.219s SeriesMinLifeDurationWithoutSingleSampleSeries:2m44.631s SeriesAvgLifeDurationWithoutSingleSampleSeries:1h58m21.913s SeriesMaxLifeDurationWithoutSingleSampleSeries:1h59m30.219s SeriesMinChunks:1 SeriesAvgChunks:3 SeriesMaxChunks:4 TotalChunks:187632 ChunkMinDuration:2m44.631s ChunkAvgDuration:31m9.876s ChunkMaxDuration:1h59m0s ChunkMinSize:54 ChunkAvgSize:147 ChunkMaxSize:1251 SingleSampleSeries:0 SingleSampleChunks:0 LabelNamesCount:212 MetricLabelValuesCount:1319}" id=01FN2SC2A7B4K022T6FBWPWTJP
```
It looks to me like this is only actually verifying a single block, so my issue here is really just the same as https://github.com/thanos-io/thanos/issues/4878. If you agree I'm happy to close this issue in favour of that one.

**Comment by yeya24** [comment]
Close as #4878 was closed. Thanks @AndrewNiven1
