### ISSUE TITLE
Broken dependency on github.com/efficientgo/tools/core

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#4806]
```
go: github.com/thanos-io/thanos@v0.13.1-0.20201030101306-47f9a225cc52 requires
	github.com/efficientgo/tools/core@v0.0.0-20210129205121-421d0828c9a6: invalid version: unknown revision 421d0828c9a6
````

I don't get why but some users and even fresh code of Prometheus can fail due to `github.com/efficientgo/tools/core` invalid version. And indeed this commit is weird https://github.com/efficientgo/tools/commit/421d0828c9a6

We have to do something about it, so posting for awareness, did not have time yet.

Also covered in https://cloud-native.slack.com/archives/CL25937SP/p1634836273003000

**Comment by matej-g** [comment]
It's strange, I'm not sure how that reference got into `go.mod`, but the ref is for a commit on a branch from this PR https://github.com/efficientgo/tools/pull/5, so it does not on the main branch. I'll bump the version to latest `main` and that should resolve it.
