### ISSUE TITLE
Store: Make initial sync more robust

### ISSUE THREAD

**Issue by matej-g** [thanos-io/thanos#4810]
I stumbled upon this during some tests - if the [initial sync](https://github.com/thanos-io/thanos/blob/main/cmd/thanos/store.go#L365) fails, this stops the whole initialization of a store and the process quits. The connection error might, however, be just ephemeral (e.g. the store is not ready yet or there was a temporary issue with the connection). It might be worthwhile to retry the initial sync in such cases, in order not to cause the process to exit directly after one failed attempt.

**Comment by matej-g** [comment]
I think this is still valid

**Comment by shaoyi1997** [comment]
Hi! I can take this issue :)

**Comment by PlytonRexus** [comment]
Hi! Is this issue still valid?

**Comment by Kartik-Garg** [comment]
I have raised a working PR against this issue :)

**Comment by Kartik-Garg** [comment]
@matej-g if the [PR](https://github.com/thanos-io/thanos/pull/6050) fixes this issue, can we close this issue now with respect to the PR? :smile:

**Comment by matej-g** [comment]
@Kartik-Garg yes please, thank you 🙇
