### ISSUE TITLE
Rules: support external-label matcher. [Feature Request]

### ISSUE THREAD

**Issue by hanjm** [thanos-io/thanos#4812]
### Is your proposal related to a problem?

In sidecar mode, fanout rules api may response lots of rules. Could we support external-label based matcher, a bit like grafana? 
![image](https://user-images.githubusercontent.com/7621241/139385395-25f8db6e-32a2-452d-a516-be5af52f9388.png)

**Comment by yeya24** [comment]
It would be good to support this in Prometheus first. I think this makes sense for example in multi tenant mode

**Comment by hanjm** [comment]
> It would be good to support this in Prometheus first. I think this makes sense for example in multi tenant mode

I make a issue in Prometheus just now. 
Yeah, in multi tenant mode, prom-label-proxy can be auto inject tenant_id matcher.
