### ISSUE TITLE
Support Aliyun Oss

### ISSUE THREAD

**Issue by SecretSun** [thanos-io/thanos#482]
Will you support Aliyun Oss ?
 
https://www.alibabacloud.com/en/product/oss 

I try with thanos, it's not working yet, would like to see Thanos supporting it.

**Comment by Bplotka** [comment]
Nothing will be done without community support, so if you want it, you can help writing down the adapter for it. See steps here: https://github.com/improbable-eng/thanos/blob/master/docs/storage.md#how-to-add-a-new-client

Plus we need someone who will be ok to maintain that code (:

**Comment by yeya24** [comment]
Anyone working on this? If not, I'd like to take this

**Comment by jojohappy** [comment]
@yeya24 Thanks for your help! Maybe it will improve practice for Thanos in China.

**Comment by SecretSun** [comment]
Cool...

**Comment by shaulboozhiao** [comment]
I have implemented  Aliyun OSS objstore .

**Comment by jojohappy** [comment]
@SecretSun Now Thanos supports Aliyun OSS, further information is [here](https://github.com/thanos-io/thanos/blob/master/docs/storage.md#aliyun-oss).
