### ISSUE TITLE
frontend/docu: Inconsistant naming downstream-tripper-config

### ISSUE THREAD

**Issue by Jakob3xD** [thanos-io/thanos#4824]
### Is your proposal related to a problem?

Naming about `downstream-tripper-config` is inconsistent.
```
thanos: error: unknown long flag '--query-range.downstream-tripper-config'
```

### Describe the solution you'd like

Replace `query-range` with `query-frontend`.
https://github.com/thanos-io/thanos/blob/main/docs/components/query-frontend.md?plain=1#L108
https://github.com/thanos-io/thanos/blob/main/CHANGELOG.md?plain=1#L50

**Comment by yeya24** [comment]
Nice find. Help wanted.
