### ISSUE TITLE
Allow query-frontend to have multiple query backends

### ISSUE THREAD

**Issue by d-shi** [thanos-io/thanos#4826]
### Is your proposal related to a problem?

We are running multiple k8s clusters in dev and production. The thanos configuration is the same in dev and prod. They each have a single thanos-query that talks to all the thanos-sidecars in each cluster in that environment.

We would like to have a single thanos-query-frontend that we point Grafana to in order to get both dev and prod metrics. One way would be to configure the prod thanos-query to also talk to the thanos-sidecars in dev, but this would require opening up networking between all the dev VPCs and the prod VPC where we run thanos-query. Instead, it would be great to only need to open up network between the single prod VPC where thanos-query-frontend is running and the dev VPC where thanos-query is running.

### Describe the solution you'd like

Just like how thanos-query can be configured to talk to multiple thanos-store API backends, it would be useful to allow thanos-query-frontend to talk to multiple thanos-query backends.

### Describe alternatives you've considered

The alternative mentioned above is supported, but requires opening up much more networking communication between dev and prod environments.

**Comment by GiedriusS** [comment]
Mhm, how query-frontend should know to which Query it should route the request in your case?

**Comment by d-shi** [comment]
I was hoping to have it route to all of the thanos-query instances specified, and aggregate/dedupe the results, just like how thanos-query does with the store API endpoints.

**Comment by GiedriusS** [comment]
So, why not put another Thanos Query instance on top of another Thanos Query that could perform these things? Then query-frontend could be at the very top. 🤔

**Comment by d-shi** [comment]
Oh I see, I didn't realize that was a possibility to stack thanos-query on top of another thanos-query. That could work then. Thanks for your help! Feel free to close this unless you think there are other valid use cases for this request.

**Comment by GiedriusS** [comment]
Let's close this to keep our issue tracker cleaner. Thank you for using Thanos!

**Comment by zakariais** [comment]
@d-shi
Did u able to achieve, we are looking to do the same thing
Any reference you can give us?
