### ISSUE TITLE
Add tracing support for compaction

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#4832]
### Is your proposal related to a problem?

We have some metrics in the compactor of its overall status. But right now it is hard to track the status and time taken for each compaction run.

### Describe the solution you'd like

Add tracing support for compactor and instrument different steps in compaction. For example:
1. Block planning
2. Block download
3. Block verification
4. Block compaction
5. Block upload

**Comment by matej-g** [comment]
I belive https://github.com/thanos-io/thanos/pull/4903 should solve this
