### ISSUE TITLE
Thanos compactor producing too big blocks

### ISSUE THREAD

**Issue by bobykus31** [thanos-io/thanos#4833]
**Thanos, Prometheus and Golang version used**:
Thanos 0.23.1
Prometheus 2.30.2

**Object Storage Provider**:
NetApp StorageGRID kinda s3 obj storage

**What happened**:

After compactor's first stage run (I suppose it is dedup???) some block became  extremely big. Like

```
|            ULID            |        FROM         |        UNTIL        |     RANGE      |   UNTIL-DOWN    |  #SERIES   |    #SAMPLES     |    #CHUNKS    | COMP-LEVEL | COMP-FAILED |                            LABELS                             | RESOLUTION |  SOURCE   |
|----------------------------|---------------------|---------------------|----------------|-----------------|------------|-----------------|---------------|------------|-------------|---------------------------------------------------------------|------------|-----------|
| 01FJ7WYM7P9A0TQX5HFYZR5MPB | 19-08-2021 00:00:00 | 02-09-2021 00:00:00 | 336h0m0s       | -296h0m0s       | 6,254,060  | 283,164,613,922 | 2,433,576,583 | 5          | false       | monitor=production,pod=kubesvc-k8s                            | 0s         | compactor |
```

which results to  

`707183107867 1286 objects s3://ocsysinfra-prometheus-metrics/01FJ7WYM7P9A0TQX5HFYZR5MPB/`

aka 658G

Then downsampler fails because node is running out of  disk space.

**What you expected to happen**:

Is there any way to reduce / manage the size or range of  blocks produced by compactor so downsampler will not run into disk space issue?

**Environment**:
- OS (e.g. from /etc/os-release): Ubuntu 20.04.3 LTS
- Kernel (e.g. `uname -a`): 5.4.0-80-generic
- Others:

**Comment by yeya24** [comment]
@bobykus31 Can you please take a look at the index file size?

**Comment by bobykus31** [comment]
yes, sure, its ~16G big


`2021-10-17 21:11 18243019751   s3://ocsysinfra-prometheus-metrics/01FJ7WYM7P9A0TQX5HFYZR5MPB/index`

also 1284 512Mb chunks are present there

```
s3cmd ls  -r  s3://ocsysinfra-prometheus-metrics/01FJ7WYM7P9A0TQX5HFYZR5MPB | grep chunks | wc -l
1284
```

**Comment by yeya24** [comment]
> yes, sure, its ~16G big
> 
> `2021-10-17 21:11 18243019751 s3://ocsysinfra-prometheus-metrics/01FJ7WYM7P9A0TQX5HFYZR5MPB/index`
> 
> also 1284 512Mb chunks are present there
> 
> ```
> s3cmd ls  -r  s3://ocsysinfra-prometheus-metrics/01FJ7WYM7P9A0TQX5HFYZR5MPB | grep chunks | wc -l
> 1284
> ```
> 
> Is it related to COMP-LEVEL somehow? With COMP-LEVEL 4 I see block size is reasonably small/big. With 5 some are really big.

Yeah ideally we don't want to produce such big blocks from the compactor so you can configure the max compaction level to 4 instead of 5.
For this super big block, I am not really sure if there is a workaround now. You have too many chunks/samples and you need to downsample it to make it smaller ASAP. Is it possible to increase the storage size to make downsampling succeed?

**Comment by bobykus31** [comment]
Thats all right. It is good to know  reducing compaction level can help.
