### ISSUE TITLE
Rule: Support limit feature introduced by Prometheus v2.31.0 

### ISSUE THREAD

**Issue by hanjm** [thanos-io/thanos#4837]
### Is your proposal related to a problem?

[Prometheus v2.31.0](https://github.com/prometheus/prometheus/releases/tag/v2.31.0) introduce a new feature about rules: add the ability to limit number of alerts or series. https://github.com/prometheus/prometheus/pull/9541
I'd like to implement this feature with thanos-ruler :)

**Comment by yeya24** [comment]
Please go ahead!

**Comment by yeya24** [comment]
Closed by #4837
