### ISSUE TITLE
when add nginx basic authentication to the query , queryfrontend cannot request the query to get data

### ISSUE THREAD

**Issue by DreamDZhu** [thanos-io/thanos#4844]
**Thanos, Prometheus and Golang version used**: 0.23.1

**Object Storage Provider**: aliyun

**What happened**:

When I add nginx basic authentication to the query , 

auth_basic "Basic Authorization";
auth_basic_user_file /etc/nginx/basic_auth_file;

auth user : admin  auth passwd : admin

 the queryfrontend cannot request the query to get data

![image](https://user-images.githubusercontent.com/8407917/140868987-05305f1c-3771-4865-b171-a814ee86276e.png)

**What you expected to happen**:

I hope that query frontend still has proper access to query data when all components are basic authentication on

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:
level=error ts=2021-11-09T05:32:27.317881424Z caller=retry.go:73 org_id=anonymous msg="error processing request" try=0 err="context canceled"
level=error ts=2021-11-09T05:32:36.706454915Z caller=retry.go:73 org_id=anonymous msg="error processing request" try=0 err="context canceled"
level=error ts=2021-11-09T05:33:08.036321816Z caller=retry.go:73 org_id=anonymous msg="error processing request" try=0 err="context canceled"
level=error ts=2021-11-09T05:34:17.317520275Z caller=retry.go:73 org_id=anonymous msg="error processing request" try=0 err="context canceled"
level=error ts=2021-11-09T05:41:46.793805155Z caller=retry.go:73 org_id=anonymous msg="error processing request" try=0 err="context canceled"

**Anything else we need to know**:

**Comment by yeya24** [comment]
Query frontend supports downstream config and http client config is supported in sidecar https://github.com/thanos-io/thanos/commit/c98324b8f938574c4e2a4a4344005b116ad806cb as well.

It would be good to merge these to a more common config struct.

**Comment by someshkoli** [comment]
> Query frontend supports downstream config and http client config is supported in sidecar https://github.com/thanos-io/thanos/commit/c98324b8f938574c4e2a4a4344005b116ad806cb as well.
> 
> It would be good to merge these to a more common config struct.
> 
> Thoughts @someshkoli @GiedriusS ?

Would be a good addition along with using single http(thanks/http) client across. Had seen instances  of code duplication wrt this ^
