### ISSUE TITLE
Thanos sidecar: Does not upload old blocks

### ISSUE THREAD

**Issue by aymericDD** [thanos-io/thanos#4851]
**Thanos, Prometheus and Golang version used**:

``` bash
thanos, version 0.23.1 (branch: HEAD, revision: 5327cd8b9bd56ce4912fe602197ad04ab2722b18)
  build user:       root@0acc901868e9
  build date:       20211005-12:08:29
  go version:       go1.16.8
  platform:         linux/amd64
```

**Object Storage Provider**:

S3

**What happened**:

When I remove a block from the upload list of the thanos.shipper.json file the block is not uploaded and the removed block is re-added to the list of uploaded blocks into the `thanos.shipper.json` file.

**What you expected to happen**:

Except the block to be uploaded to S3.

**How to reproduce it (as minimally and precisely as possible)**:

Remove the block from the list of the `thanos.shipper.json` file and wait 30s maximum and check into the block has been uploaded. 

**Full logs to relevant components**:

If the block **01FM6WR6HA4SQZGTB2ACWM657M** is removed from the list of the uploaded blocks into the file `thanos.shipper.json` we should see this log into the sidecar component :

<details>Logs
<p>

```
level=info ts=2021-11-11T07:00:35.39399252Z caller=shipper.go:337 msg="upload new block" id=01FM6WR6HA4SQZGTB2ACWM657M
```

</p>
</details>

**Anything else we need to know**:

**Comment by GiedriusS** [comment]
Have you deleted it from S3? :smiley:

**Comment by aymericDD** [comment]
Yes, I need to re-upload old blocks because they are not anymore present after an S3 outage. :cry:

**Comment by GiedriusS** [comment]
Have you tried shutting down sidecar, editing the file, starting sidecar again, then?

**Comment by aymericDD** [comment]
Yes, I have tried to do that.

**Comment by aymericDD** [comment]
Never mind. The problem is not related to Thanos but the S3 outage. Sorry for that.

**Comment by GiedriusS** [comment]
:+1: np
