### ISSUE TITLE
store: Thanos store does not support reloading of configuration

### ISSUE THREAD

**Issue by pjastrzabek** [thanos-io/thanos#4855]
I'm rendering s3 bucket config using vault injector and after refreshing AWS credentials (after expiration)  I'd like to 'notify' / trigger reload of thanos store.
I tried to send some signals to store like -HUP, I see in logs that they are being noticed, but credentials used for accessing bucket (in AWS in my case) are still old ones.

I found similar issue for **ruler** component
https://github.com/thanos-io/thanos/issues/4432

I ended up restarting thanos with -9
```
pkill -9 thanos
```

which is causing small downtime, but works

I tried to use /-/reload endpoint but store component does not seem to expose it

**Object Storage Provider**: AWS

**What happened**:

**What you expected to happen**:
Thanos store should have a way to trigger reload of bucket config without downtime.

**How to reproduce it (as minimally and precisely as possible)**:
1. Start thanos store with reference to config file with short living credentials inside
2. When AWS credentials expire component will start complaining
3. execute pkill -1 thanos
4. Component should reload config with new credentials

**Comment by yeya24** [comment]
Reloading object store credentials is not supported right now. But it would be good to make it hot reloadable.

**Comment by pjastrzabek** [comment]
I was hoping that maybe that problem will be fixed as a result of adding aws-sdk ( https://github.com/thanos-io/thanos/pull/4667 ) but unfortunately it isn't (tested on 0.26.0)
Issue is still valid. There is no way of using thanos store with temporary credentials without downtime, because once credentials are expired component needs to be restarted to use newly rendered credentials.

**Comment by pjastrzabek-roche** [comment]
Still valid.

After updating thanos (to version that contains AWS SDK ) usage of temporary credentials is possible, we render credentials with vault injector inside /home/.aws/credentials

But after credentials are refreshed thanos component still has to be restarted, cause it does not reload them.

**Comment by pjastrzabek-roche** [comment]
I'd like to propose to reopen this bucket.

In certain places company policies force us to use only temporary credentials.
When AWS S3 bucket is used as a thanos store it means that every 12h (that is the longest validity of AWS STS token) we need to restart every thanos component that talks to AWS S3 bucket.

It's potentially a cause for brief unavailability and is very heavy operation.

**Comment by edgrz** [comment]
+1 to it.

In our case it's also causing constant unwanted restarts.

**Comment by AronllStone** [comment]
+1

It would be great to have a soft reload when mTLS certificates have been updated (e.g., by using a sidecar container or when the secret has been modified, etc).

**Comment by tokarev-artem** [comment]
+1
