### ISSUE TITLE
Improvement on Azure Object Storage Docs and/or azure object config validation

### ISSUE THREAD

**Issue by worldspawn** [thanos-io/thanos#4867]
Hi folks. I just spent a few hours trying to thanos query to connect to azure storage. The example in the docs includes a lot fieldname with no examples of the values.

```
type: AZURE
config:
  storage_account: ""
  storage_account_key: ""
  container: ""
  endpoint: ""
```

So my first crack was to put `https://<storageaccount>.blob.core.windows.net` as the value of endpoint. This results in query just crashing out with no error after the output level=debug ts=2021-11-14T08:40:41.878900465Z caller=azure.go:165 msg="creating new Azure bucket connection" component=store. All i see apart from that is exit code 2.

Anyway after rummaging around azure.go i arrived at https://github.com/thanos-io/thanos/blob/d72bff0de8a420c824743a4cedf7879419afe6cd/pkg/objstore/azure/helpers.go#L89 and I now realise that endpoint should have a value like `blob.core.windows.net`.

### Describe the solution you'd like

Please make the use of the "endpoint" field clear in the docs. Some example values (not "") wouldn't be a bad idea too.

Also, the silent mystery crash could use some error output, or alternatively when validating the conf, validate that endpoint doesn't contain https? Maybe that is just [a-z0-9\.]+

### Additional context

I'm a complete noob with this stack

**Comment by wiardvanrij** [comment]
Hi, cheers for making this issue and addressing the difficulty. 

I agree on the config part, this has actually been a somewhat long standing issue to make those more useful. To give you a bit more context; we auto generate these. However that does not provide the defaults nor for example sane values (: 

For the `not("")` ; https://github.com/thanos-io/thanos/blob/d72bff0de8a420c824743a4cedf7879419afe6cd/pkg/objstore/azure/azure.go#L133

So, I think it should be;
- Improve usage documentation for Azure Storage
- Improve handling of certain inputs in the storage config. To be precise: `https://` makes it crash without any useful information. 

Let me know if I missed something and thanks again!

**Comment by worldspawn** [comment]
That sounds like everything. Cheers 🍻

**Comment by HighWatersDev** [comment]
Facing the same issue. Anyway to provide a full config using MSI with example values in this issue?
