### ISSUE TITLE
Impossible to move from --store to --endpoint

### ISSUE THREAD

**Issue by thibautmery** [thanos-io/thanos#4871]
**Thanos, Prometheus and Golang version used**:
Thanos docker => quay.io/thanos/thanos:v0.23.1

**What happened**:

I want to upgrade my thanos query that hit other thanos query. I change the version of thanos (last one v0.23.1) and I modifies --store to use --endpoint (because --store is deprecated). 

But the docker always restart => 
```
thanos: error: unknown long flag '--endpoint'
```

**What you expected to happen**:

It should work same as --store command.

**How to reproduce it (as minimally and precisely as possible)**:

Using command docker-compose:
```
command:
- "query"
- "..."
- "--endpoint=my-thanos-dns-entry:XXXX"
```

**Anything else we need to know**:
Thanos only forward request to other thanos.

**Comment by GiedriusS** [comment]
`--endpoint` is only in the `main` version of Thanos, it's not in `0.23.1` (:

**Comment by thibautmery** [comment]
Oh yes "in the future" it will be replaced. Thanks :)
