### ISSUE TITLE
store:fetch series for block xxx: preload chunks: ... msg="returning partial response

### ISSUE THREAD

**Issue by t00350320** [thanos-io/thanos#4877]
**Thanos, Prometheus and Golang version used**:
thanos:0.16.0

**Object Storage Provider**: s3

**What happened**:  query pops errors:
10.89.16.155:10901  is our thanos-store ,
level=warn ts=2021-11-19T16:33:30.504935088+08:00 caller=proxy.go:464 err="receive series from Addr: 10.89.16.155:10901 LabelSets: {tsnode=\"10-64-62-68\"} Mint: 1597903200 Maxt: 1637305200: rpc error: code = Aborted desc = fetch series for block 01FMVEP5RTW35JQBP7S5CJ4WV3: preload chunks: read range for 0: read 59119 bytes but got 45574 name rtcapi_bill/01FMVEP5RTW35JQBP7S5CJ4WV3/chunks/000001" msg="returning partial response"

in thanos-store, it goes into:  readChunkRange

So, i check thanos-store's performance, CPU&MEM&DISK is normal.  why it throw this error?

**What you expected to happen**:
return datas

**How to reproduce it (as minimally and precisely as possible)**:

every time

**Full logs to relevant components**:
level=warn ts=2021-11-19T16:33:30.504935088+08:00 caller=proxy.go:464 err="receive series from Addr: 10.89.16.155:10901 LabelSets: {tsnode=\"10-64-62-68\"} Mint: 1597903200 Maxt: 1637305200: rpc error: code = Aborted desc = fetch series for block 01FMVEP5RTW35JQBP7S5CJ4WV3: preload chunks: read range for 0: read 59119 bytes but got 45574 name rtcapi_bill/01FMVEP5RTW35JQBP7S5CJ4WV3/chunks/000001" msg="returning partial response"

**Comment by hanjm** [comment]
Could try [thanos tools](https://thanos.io/tip/components/tools.md/#bucket-verify) verify this block and paste the output logs? thanks
