### ISSUE TITLE
Compactor: Support --min-time/--max-time filter.

### ISSUE THREAD

**Issue by hanjm** [thanos-io/thanos#4884]
### Is your proposal related to a problem?

For my case, the compactor halt or broken for some reason. the compact progress will very be lag. 
Then i restart compactor, beacuse the bucket has many blocks, I prefer it could process the more fresh blocks first. but currently, the compactor will start process the oldest block.

### Describe the solution you'd like

So, Could we add a time filter like the thanos-store componet does?

**Comment by yeya24** [comment]
The request itself is valid. 
Another way to do this is to do compaction planning from the freshest blocks. Right now all blocks are planned in time increasing order so fresh blocks are processed last. Maybe this can be done via a flag in the planner side.

**Comment by yeya24** [comment]
After 1:1 with @metonymic-smokey, we think reversing the planning order would work, but it is not as easy as it looks. So it is good to start adding the min/max time filter first.
But for users, they need to know the required time range for compaction levels to set these flags correctly.

**Comment by jordy1024** [comment]
Work in progress.

**Comment by yeya24** [comment]
Addressed by #4909
