### ISSUE TITLE
Expose 'path' parameter for store configuration.

### ISSUE THREAD

**Issue by pjastrzabek** [thanos-io/thanos#4912]
I would like to use thanos store with 'path bucket lookup style' option from minio.

In minio code I see there is an assumption
https://github.com/minio/minio-go/blob/e55f8d731cb4343f4be9361525221d8752fa75a6/api.go#L308

`
	// Sets bucket lookup style, whether server accepts DNS or Path lookup. Default is Auto - determined
	// by the SDK. When Auto is specified, DNS lookup is used for Amazon/Google cloud endpoints and Path for all other endpoints.
	clnt.lookup = opts.BucketLookup
`

I am not sure why this option is the default one, but if it's an option it would be nice to have a way of setting it in thanos.

Minio client gives such option:
`
mc alias set s3 https://s3.dualstack.eu-central-1.amazonaws.com KEY SECRET --debug --path on
`

Possible options are **on**, **off** or **auto**

Because thanos does not expose that option via BucketConfig, when I am using AWS as a store minio sdk uses 'auto' option which in AWS case means path=off.

This is causing issues for us in one highly secured deployment where all traffic goes via customer firewall, where only static list of endpoints is possible (when path=on bucket name is part of host header, so host header is different for each bucket).
Also bucket names are leaking via DNS queries.

### Describe the solution you'd like
We'd like to have new setting in store config:

`bucket_lookup_type: on`

Which would explicitly configure bucket lookup style.

### Describe alternatives you've considered

After checking minio code 
https://github.com/minio/minio-go/blob/e55f8d731cb4343f4be9361525221d8752fa75a6/pkg/s3utils/utils.go#L77
We see that if bucket name contains '.' path option is set to 'on'.
Indeed, problem does not occur for us if we use bucket names with a dot.

But we cannot ensure that this will always be the case (we do not own all buckets on our platform).

### Additional context
https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html

**Comment by pjastrzabek** [comment]
After digging a bit deeper I began to suspect why "dns lookup style" became the default option in minio for AWS & GCP.

"Path based lookup" became deprecated some time ago by Amazon, but quickly that deprecation was reverted, because it became an issue for many customers.

https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/

I think both option will stay with us for a bit longer moment so maybe it's still worth supporting setting that option explicitly in thanos. Especially that it's likely that AWS & GCP deprecation will be not in sync.

Absolute minimal patch that adds some support is:

```
diff --git a/pkg/objstore/s3/s3.go b/pkg/objstore/s3/s3.go
index 610ac6cf..aec30cd7 100644
--- a/pkg/objstore/s3/s3.go
+++ b/pkg/objstore/s3/s3.go
@@ -88,6 +88,7 @@ type Config struct {
 	PartSize    uint64    `yaml:"part_size"`
 	SSEConfig   SSEConfig `yaml:"sse_config"`
 	STSEndpoint string    `yaml:"sts_endpoint"`
+	BucketLookupType uint64 `yaml:"bucket_lookup_type"`
 }

 // SSEConfig deals with the configuration of SSE for Minio. The following options are valid:
@@ -248,6 +249,7 @@ func NewBucketWithConfig(logger log.Logger, config Config, component string) (*B
 		Creds:     credentials.NewChainCredentials(chain),
 		Secure:    !config.Insecure,
 		Region:    config.Region,
+		BucketLookup: minio.BucketLookupType(config.BucketLookupType),
 		Transport: rt,
 	})
 	if err != nil {
```

Even though there is some 'default setting logic' inside minio library. I think issue better fits thanos project, because there is no way to override it in thanos.

**Comment by hanjm** [comment]
💪  It's reasonable. I think use `S3ForcePathStyle` as field name will better. aligning with the s3 sdk https://github.com/aws/aws-sdk-go/blob/v1.42.12/aws/config.go#L127
