### ISSUE TITLE
[Proposal] Refactoring the website and documentation

### ISSUE THREAD

**Issue by wiardvanrij** [thanos-io/thanos#4921]
### Is your proposal related to a problem?

We are almost reaching for 10k stars and I personally see a stronger usage of Thanos every day. Also if we look at our Slack, the influx of various questions are only growing. This can be caused by various things. For example the docs/etc is unclear, there are a lot of new people, the stack is complex, etc.

I would like to segment the "problem" into multiple sections.

#### In general

- When I'm introducing Thanos to companies/teams, they read the website and are having a hard time to find clear information on what Thanos exactly is, how it does it and exactly why it does it. 
- The same goes for the more technical information. For example if we talk about flags or certain configuration sections. The docs provide information on what it does. Not on the **why** it does it, or why it is necessary. 
- The project is running for a while. This is by the way my personal feeling, I believe we kept building on what we had and not really revisited structure, information, etc.

#### In technical

- Working on the website is done by both a more technical part (Hugo), with certain scripts (for flags, generation, etc) and then a part content. While also maintaining a history of previous Thanos versions. This makes it somewhat hard to actually iterate on it for good section of users.
- At the moment we lack some guidelines or pointers to help creating more/better content. For example an image format or certain diagram tools that also allow iterations. 

#### Breakdown

So to continue to breakdown this problem, it IMO causes a few things: 

- It makes it harder for someone to be more involved in the project for the long term (i.e. provide a PR). 
- We lack variety in the work that is being done (A lot of PR's are based on technical challenges that are often presented by the more technical users. There is still enough work to be done on other aspects in the project).
- We get more questions which is an indication we should improve to make those clear. Also by having a more generic involvement by creating an easier 'way in', we expand the community more. 
- It costs time to be supportive at this moment to the wide group of users. If we could fix their problems in a fundamental way, we clear the path to be more involved in other issues that _should_ need more dedicated attention. 

### Describe the solution you'd like

I honestly think it's time to reconsider the entire website as a whole. 
We have a pretty though "story to tell" and I feel we need an UX/UI expert to convert this technical story in an easy to understand website that covers the project to a completely new user (even non-tech user!) towards the more advanced technical deep-dives and a few things in between.

I also think it requires some "knowledge sessions" from heavy experienced users to explain some reasonings, technical information, etc. that then could be "translated" into useful context and information on the website. 

Regardless, I don't have a concrete solution set in stone and this is merely a proposal to see if I'm going into the right direction. If it is, I'm going to need help to make it into more actionable items and maybe an actual proposal document.

### Describe alternatives you've considered

I tried to make some (structural) changes on the docs, see here: https://github.com/thanos-io/thanos/pull/4206 
However, this took a lot of time and I'm actually not confident that it improves on the goal. We still adhere to the same structure/standards. I'm still open to get that merged, though I actually felt there should perhaps be a more structural solution.

### Additional context

I think in some sense this proposal is also part of growing the community and allowing more people to get involved in an easier way.

**Comment by saswatamcode** [comment]
Thanks for this! 💫

> Working on the website is done by both a more technical part (Hugo), with certain scripts (for flags, generation, etc) and then a part content. While also maintaining a history of previous Thanos versions. This makes it somewhat hard to actually iterate on it for good section of users.

Yes, the current website generation setup is slow (in terms of feedback loop). I was wondering how to improve the experience and came up with a few ideas for this,
- Adding configs & commands for only generating `tip` documentation and website, which can be run locally by contributors.
- Adding command for skipping links during mdox formatting, so contributors can quickly format and commit while changing (CI will check links fully)
- Have a page in Contributing section, which maps what to run/test with a part of the codebase

WDYT? 🙂

> We have a pretty though "story to tell" and I feel we need an UX/UI expert to convert this technical story in an easy to understand website that covers the project to a completely new user (even non-tech user!) towards the more advanced technical deep-dives and a few things in between.

This could pair well with a community demo instance (#4606) so users can actually read about and play around with certain components right from the website!

Also, this seems like a good fit for some documentation-based mentorship programs like [GSoD](https://developers.google.com/season-of-docs)! 🙂

**Comment by wiardvanrij** [comment]
> Also, this seems like a good fit for some documentation-based mentorship programs like GSoD! 🙂

Wow, that's really cool. Thanks for sharing!

**Comment by bwplotka** [comment]
Thanks! I think we might need some help here from UX professionals (:
