### ISSUE TITLE
Thanos Ruler fails to evaluate all recording rules correctly

### ISSUE THREAD

**Issue by sharathfeb12** [thanos-io/thanos#4924]
I am currently running Thanos v0.24.0-rc.0.

Few recording rules are evaluated fine while few recording rules seems to be last evaluated 2 days back. This happens very frequently.  Restarting the pod fixes the issue temporarily. This issue is reproducible on v0.23.0 as well.

Here is the args passed to the ruler:

    - rule
    - --log.level=info
    - --log.format=logfmt
    - --grpc-address=0.0.0.0:10901
    - --http-address=0.0.0.0:10902
    - --objstore.config=$(OBJSTORE_CONFIG)
    - --data-dir=/thanos/data
    - --eval-interval=1m
    - --label=rule_replica="$(NAME)"
    - --alert.label-drop=rule_replica
    - --remote-write.config-file=/etc/thanos/conf/rw-config.yaml
    - --query=dnssrv+_http._tcp.observatorium-thanos-query.monitoring.svc.cluster.local
    - --rule-file=/etc/thanos/rules/*/*.yaml

![image](https://user-images.githubusercontent.com/24534706/144770921-d9bddd67-72b1-40a4-b1c3-bb921f954edd.png)

**Comment by GiedriusS** [comment]
Hello, could you please dump the goroutine stacks when this happens and upload them?

**Comment by bwplotka** [comment]
Thanks for reporting! pprof profiles available at `/debug/pprof/goroutines` done at the moment of things being stuck, would be super helpful!

**Comment by jleloup** [comment]
Isn't this issue similar to https://github.com/thanos-io/thanos/issues/4772 ?

**Comment by jleloup** [comment]
I think the .pprof file I uploaded there is actually more relevant in this issue as the behaviour I got in my Thanos Ruler is more comparable to this issue as restarting those pods helped only for some dozens of minutes before failing again to process records.

Link to the .pprof: https://github.com/thanos-io/thanos/issues/4772#issuecomment-984635383

**Comment by ahurtaud** [comment]
I have the same issue on v0.24.0 (but was valid in 0.23 also)
Here the goroutine pprof after long time being stuck:
[ruler-goroutine.zip](https://github.com/thanos-io/thanos/files/7813564/ruler-goroutine.zip)
