### ISSUE TITLE
Query: high number of goroutines due to partial deadlock

### ISSUE THREAD

**Issue by aymericDD** [thanos-io/thanos#4925]
**Thanos, Prometheus and Golang version used**:

thanos, version 0.23.1 (branch: HEAD, revision: 5327cd8b9bd56ce4912fe602197ad04ab2722b18)
  build user:       root@0acc901868e9
  build date:       20211005-12:08:29
  go version:       go1.16.8
  platform:         linux/amd64

**Object Storage Provider**:

- S3

**What happened**:

The number of goroutines of the thanos query component explode when the number of requests is growing :
![image](https://user-images.githubusercontent.com/8859832/144855202-0ac794cf-888a-46cd-9e38-b72ae5f785e5.png)
![Selection_144](https://user-images.githubusercontent.com/8859832/144856747-145d13b5-042e-4e58-9bf8-14362f52208a.png)

The Thanos query stack all queries and never return responses. No logs are returned because the goroutines are blocked due to a semaphore problem. Cf goroutine pprof :  
[pprof.thanos.goroutine.005.pb.gz](https://github.com/thanos-io/thanos/files/7661057/pprof.thanos.goroutine.005.pb.gz)

**What you expected to happen**:

All requests must work and the number of goroutines must not grow. 

**How to reproduce it (as minimally and precisely as possible)**:

It is difficult to reproduce it. The way to reproduce it is to spam the query with a lot of requests.

**Full logs to relevant components**:

No logs are displayed when the partial deadlock is in place. 

**Anything else we need to know**:

**Comment by aymericDD** [comment]
The issue is fixed by https://github.com/thanos-io/thanos/pull/4795 
Can this fix be backported to v0.23.1 to avoid outages ? This is very critical for production environments. Thanks for your support and thanks @GiedriusS  for the fix :+1:

**Comment by aymericDD** [comment]
PR to backport fix to release-23 https://github.com/thanos-io/thanos/pull/4926

**Comment by yeya24** [comment]
Close as the new release is out.
