### ISSUE TITLE
Add flag to "thanos tools bucket ls" to exclude marked blocks

### ISSUE THREAD

**Issue by snuggie12** [thanos-io/thanos#4929]
### Is your proposal related to a problem?

I was trying to prepare a for loop to do rewrites and accidentally did rewrites on blocks that were marked for deletion. This ended up creating overlaps which prevented compactor from starting up.

### Describe the solution you'd like

It'd be nice if `ls` had an option to exclude blocks marked for deletion.

### Describe alternatives you've considered

Alternatively maybe `rewrite` should refuse to rewrite a block marked for deletion?

**Comment by yeya24** [comment]
@snuggie12 Makes sense. This filtering can be done at the fetcher filters. Help wanted!
