### ISSUE TITLE
receive: implement prometheus flag--storage.tsdb.retention.size in receive

### ISSUE THREAD

**Issue by jmichalek132** [thanos-io/thanos#4937]
### Is your proposal related to a problem?

There is a risk thanos receive can fill up it's disk / volume when disk usage is not monitored even when --tsdb.retention is set since blocks within the time range can grow over time. This can potentially lead to outages.

### Describe the solution you'd like

Implement prometheus flag `--storage.tsdb.retention.size`.
This was originally an experimental prometheus feature and I know prometheus experimental features are not usually implemented in thanos however as of prometheus version [2.29.0](https://github.com/prometheus/prometheus/blob/main/CHANGELOG.md#2290--2021-08-11) it was promoted to a stable feature. 

### Describe alternatives you've considered

Adding disks space usage as recommend alert for thanos receive. 

### Additional context

Not sure what changes would be required to implement this, but I would be willing to work on this.

**Comment by bwplotka** [comment]
Notes from meeting:

* Use case - better reliability.
* Tricky for multi-tenant TSDB. 
* Ideas:
   * Separate go routine that checks what blocks were uploaded what's not. 
   * Make replica unready for ingestion.
