### ISSUE TITLE
Unblock `main`

### ISSUE THREAD

**Issue by GiedriusS** [thanos-io/thanos#4947]
After https://github.com/thanos-io/thanos/pull/1906 we need to create:
* https://quay.io/thanos/thanos-linux-amd64
* https://quay.io/thanos/thanos-linux-arm64
* https://hub.docker.com/r/thanosio/thanos-linux-amd64
* https://hub.docker.com/r/thanosio/thanos-linux-arm64

Following the same naming as https://quay.io/repository/prometheus/prometheus-linux-amd64, https://quay.io/repository/prometheus/prometheus-linux-arm64, and so on.

Need to perform the following actions to avoid these problems in the future:
* Add `thanosbot` user as the owner of the `thanosio` organization on Dockerhub because otherwise it is impossible to create a new repository there;
* Fix quay.io credentials in password storage. Google has noticed a "strange pattern" when I tried to log into quay.io with Google SSO and asked me to enter a number sent via SMS. Impossible to work around this by myself.

Assigning to @bwplotka because due to 2FA I cannot perform these actions :'/ 

Example failing run: https://app.circleci.com/pipelines/github/thanos-io/thanos/8364/workflows/f709bc0b-713e-4de6-80be-813a1a474124/jobs/17614

**Comment by bwplotka** [comment]
Thanks for clear steps. Doing this now.

**Comment by bwplotka** [comment]
* Repos created
* Thanosbot has admin access (not sure if this is a good pattern) to both quay and dockerhub.

Retried, let's see

**Comment by bwplotka** [comment]
Let's see now https://app.circleci.com/pipelines/github/thanos-io/thanos/8372/workflows/5948f554-82f0-4dd9-b0a2-a1ffac1972be

**Comment by bwplotka** [comment]
I think it almost works. I think latest is pushed instead of `main-sha` that's why the issue: https://app.circleci.com/pipelines/github/thanos-io/thanos/8372/workflows/5948f554-82f0-4dd9-b0a2-a1ffac1972be

**Comment by GiedriusS** [comment]
Fixed in https://github.com/thanos-io/thanos/commit/7793ab637780826c88741a4783f0b3ae7dffe6a4 :tada: Images available now:
https://hub.docker.com/layers/thanosio/thanos/main-2021-12-14-7793ab63/images/sha256-9dd0cee98ac7dc4f122e75d4fade9ba2452e8a9a2c0b8cb9a160e55ce1bae0f1?context=explore
https://quay.io/repository/thanos/thanos/manifest/sha256:ba0b9192a0db3693afcb220c4c1fc8578a1c25df20dc41697e57b3329fe1d7f8
