### ISSUE TITLE
Thanos-query does not query data after running for a period of time, health check is ok, but query api timeout.

### ISSUE THREAD

**Issue by DemonLee0719** [thanos-io/thanos#4948]
**Thanos, Prometheus and Golang version used**:
thanos: 0.23.1
prometheus: 2.31.1
openshift: v3.11.88
k8s: v1.11.0

**Object Storage Provider**: None

**What happened**:
when i   ` curl http://thanos-query-pod-cluster-ip:9090/-/healthy`  return ok,
but `curl http://thanos-query-pod-cluster-ip:9090/api/v1/query?query=up`    timeout.
Only one of the three pods will have this situation.
Something must be happening inside this pod, but the log can't see anything.
The configuration file is as follows
![BE5F69CFD1C6D676DF4BE0DD70A941E8_IMAGE#1639447710769#jpg](https://user-images.githubusercontent.com/27336596/145923210-fb784fcb-5998-4170-8e37-f2229df4fc68.jpg)

![B2C4556DAEE1D5188017714AE70843E7_IMAGE#1639447710769#jpg](https://user-images.githubusercontent.com/27336596/145923428-935a5da7-3288-49ec-b43d-1422d198fdd6.jpg)
![820847D5DF9D14E85EDB011DCB7646C1_IMAGE#1639447710770#jpg](https://user-images.githubusercontent.com/27336596/145923665-07924659-3441-46b9-8242-9de63e5c631c.jpg)
![930989E1D572B67CB3DFAB85EA6B4543_IMAGE#1639447710770#jpg](https://user-images.githubusercontent.com/27336596/145923681-b119d87a-9a84-49fa-82b0-2040fb11d844.jpg)
![B8DBA10D4EEC7BE29B019F44F06A4784_IMAGE#1639447710769#jpg](https://user-images.githubusercontent.com/27336596/145923686-5b971606-13f5-43ea-9797-912a316b4cce.jpg)
![B81D8101C6D67A3D6E5F1384BD6F4311_IMAGE#1639447710770#jpg](https://user-images.githubusercontent.com/27336596/145923694-4d5ad8fc-d8c1-46fe-b192-88412212e6d7.jpg)
![BAEE4F062BA91A4175D340C69EF04EF9_IMAGE#1639447710771#jpg](https://user-images.githubusercontent.com/27336596/145923697-baaeab27-45a0-49c8-9840-7601e19392ac.jpg)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by DemonLee0719** [comment]
livenessProbe url modified to  `/api/v1/query?query=up`. When thanos-query does not work, the pod will be restarted.this is my solution, But not the best solution.

**Comment by hanjm** [comment]
same issue with https://github.com/thanos-io/thanos/issues/4766. please use 0.23.2 rc https://github.com/thanos-io/thanos/releases/tag/v0.23.2-rc.0 or 0.24.0 rc

**Comment by DemonLee0719** [comment]
> livenessProbe url modified to `/api/v1/query?query=up`. When thanos-query does not work, the pod will be restarted.this is my solution, But not the best solution.
