### ISSUE TITLE
Error executing query: query timed out in expression evaluation from Thanos Querier

### ISSUE THREAD

**Issue by kimcagayat** [thanos-io/thanos#4952]
Error executing query: query timed out in expression evaluation from Thanos Querier

**Thanos, Prometheus and Golang version used**:

/ # thanos --version
thanos, version 0.12.2 (branch: HEAD, revision: 52e10c6e0f644ea98fd057e7fbece828d8dd07c7)
  build user:       circleci@241aa351893e
  build date:       20200430-16:37:24
  go version:       go1.13.1

**Object Storage Provider**: Azure Storage Account

**What happened**: Error executing query: query timed out in expression evaluation from Thanos Querier when executing "node_cpu_seconds_total" and some other queries.

**What you expected to happen**: It should show some result since it is working before.

**Comment by hanjm** [comment]
1. what about the query metrics size? you can execute `count(node_cpu_seconds_total)` to exeplan that, general speaking , if the count more than 10k, it will be slowly.

2. The version 0.12.2 seems very very old. Could you try the latest version? [0.22](https://github.com/thanos-io/thanos/releases/tag/v0.22.0) or [0.23.2](https://github.com/thanos-io/thanos/releases/tag/v0.23.2-rc.0)?

**Comment by kimcagayat** [comment]
Hi @hanjm, will get the details

**Comment by kimcagayat** [comment]
Here's the value I got after executing count(node_cpu_seconds_total) from thanos: 42100

**Comment by hanjm** [comment]
> Hi @hanjm, will get the details. Is upgrading thanos to the latest version will improve the query timeouts?

yes. but 42k time series also too large to make ad-hoc query. are you want to get total cpu usage? you could optimize by recording_rule. https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/

Please read this blog provide more technology detail about PromQL https://valyala.medium.com/how-to-optimize-promql-and-metricsql-queries-85a1b75bf986

**Comment by kimcagayat** [comment]
Thanks @hanjm for the feedback. Does updating the Thanos querier needs update as well on Thanos Sidecar?

**Comment by hanjm** [comment]
It is recommended keep
