### ISSUE TITLE
thanos images are not available for armv7 architecture

### ISSUE THREAD

**Issue by 212850a** [thanos-io/thanos#4953]
Thanks to https://github.com/thanos-io/thanos/issues/1851 there are thanos images available for arm64 architecture, but there is still gap with armv7. It would be really helpful to get images for armv7 as stable Raspbian OS is still 32 bit (64 bit is still beta).

**Comment by wiardvanrij** [comment]
My 2 cents; It would be nice to chain a few things here. 

- #4965 for not having to pin sha.
- #4989 for having an up-to-date build process and enabling parallelism
- #4988 for actually implementing that parallelism so we don't hit an inefficiency issue while building

I think eventually all those things make it really easy to implement this :+1:

**Comment by laurivosandi** [comment]
ARMv7 Docker image is still missing
