### ISSUE TITLE
Improve documentation about deduplication

### ISSUE THREAD

**Issue by wiardvanrij** [thanos-io/thanos#4959]
Use-case: https://cloud-native.slack.com/archives/CK5RSSC10/p1639588902066100?thread_ts=1639588902.066100&cid=CK5RSSC10

Good question about deduplication and (I think) a good answer as well. Let's create documentation as it's valuable information. 

I will update this issue later with better context as I'm on mobile now.

**Comment by Navya-Andra** [comment]
@wiardvanrij I am new to opensource and would like to take up this issue. Can you please guide me in contributing if the issue is still open

**Comment by wiardvanrij** [comment]
> @wiardvanrij I am new to opensource and would like to take up this issue. Can you please assign it to me if the issue is still open

Of course! Welcome :)

**Comment by Navya-Andra** [comment]
@wiardvanrij made the pull request. Please provide the feedback - https://github.com/thanos-io/thanos/pull/5004
