### ISSUE TITLE
Memcached client can start high numbers of goroutines

### ISSUE THREAD

**Issue by bboreham** [thanos-io/thanos#4967]
[this behaviour was observed with the code inside Cortex, but I believe it's called the same way inside Thanos]

This code: https://github.com/thanos-io/thanos/blob/397fcb19d93b2a279b57ad10ff1aea811f62345c/pkg/cacheutil/memcached_client.go#L460-L482

starts a goroutine for each batch requested, then if the admin has set a bound on concurrency they will mostly block here:
https://github.com/thanos-io/thanos/blob/397fcb19d93b2a279b57ad10ff1aea811f62345c/pkg/cacheutil/memcached_client.go#L503-L510

For large queries there can be millions of keys here: https://github.com/thanos-io/thanos/blob/8f278cdb5793684c71ab67dd4d75c7cabec887bc/pkg/store/bucket.go#L2198-L2200

We run with `max-get-multi-concurrency=100` and `max-get-multi-batch-size=100`
so we can have hundreds of thousands of goroutines doing nothing.

I think it would be better to avoid starting the goroutines until the gate will allow them to proceed, or perhaps run a pool of goroutines to do the work.

**Comment by GiedriusS** [comment]
Perhaps this could be worked to always have a constant number of worker goroutines?

**Comment by hanjm** [comment]
I write a general `doWithBatch` function, it could process both concurrency control and batch control. May be it fit this also?
https://github.com/thanos-io/thanos/blob/main/pkg/cacheutil/redis_client.go#L280-L307

**Comment by 4molybdenum2** [comment]
```golang
        const numConcurrentRoutines = 10

	batchJobs := make(chan []string, numResults)
	results := make(chan *memcachedGetMultiResult, numResults)

	defer close(results)

	for i:=1; i<=numConcurrentRoutines; i+=1 {
		go c.worker(i, batchJobs, results, ctx) // worker function will call the getMultiSingle() function which will enforce max-concurrency
	} // initialzes 10 concurrent batchJobs

	for batchStart := 0; batchStart < len(keys); batchStart += batchSize {
		batchEnd := batchStart + batchSize
		if batchEnd > len(keys) {
			batchEnd = len(keys)
		}

		batchKeys := keys[batchStart:batchEnd]
		batchJobs <- batchKeys
	}
	close(batchJobs)
```

I was thinking something like this? That being said I am not too familiar with the code...

**Comment by wiardvanrij** [comment]
We should however consider if this is actually the case at Thanos. Granted that I was running a version ~0.17-0.18ish but I had a consistent amount of goroutines equal to I believe `max_get_multi_concurrency`. Certainly not the > hundreds of thousands of goroutines you are experiencing. 

Though I also figured that I could not really understand why it would keep the routines alive when not using it ^^ I guess regardless of the actual impact, such a thing should perhaps get fixed.
