### ISSUE TITLE
Thanos Querier not returning data more than 2 days

### ISSUE THREAD

**Issue by dpachiappan** [thanos-io/thanos#4971]
**Thanos Version: **thanos:v0.19.0-rc.0

**Object Storage Provider**: Amazon S3

**What happened**:

Thanos Querier is not returning data more than 2 days old.

**What you expected to happen**:  We expect data to be shown for any date and time range that we chose as the data is stored in the s3 bucket with 1 year retention.

**How to reproduce it (as minimally and precisely as possible)**:

Attached the image for reference.

![image](https://user-images.githubusercontent.com/2790411/146597620-61558185-8873-471f-91b0-70eb91bc741d.png)

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by GiedriusS** [comment]
Do you have Thanos Store running and connected to Thanos Query with `--store`?
