### ISSUE TITLE
Consider using true consistent hashring impl in Receive

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#4972]
I just noticed that our receive hashring was never... hashring (: 

Our mod hash is quite naive and has problems to shard our data when changes occur. Every time new replica is added or removed series shards are jumping across replicas. IF we want more dynamic system we need to fix this.

cc @spaparaju @squat @jmichalek132  @onprem 

AC: 

* Use some hashring implementation (e.g https://github.com/serialx/hashring) to fix this.

Read more about the problem here: https://www.toptal.com/big-data/consistent-hashing

The key challenge is how to distribute hashring without key value store. I assume we can do it using our https://github.com/observatorium/thanos-receive-controller

PS: Once we fix this we could play with different thanos-receive-controller semantics: We could reshape hashring on every pod restart with little impact!

**Comment by squat** [comment]
Just to for correctness: our hashring _is_ a hashring, however it's not a consistent hashring! I totally support this; it's one of the main improvements I suggested during last year's Thanos Receiver kubecon talk. This would be a big help to help us horizontally scale receiver sets without having metrics bounce around everywhere.

**Comment by bwplotka** [comment]
Hm, I don't think module hash can be called hashing, but nevertheless, I think we are on the same page! (((:

**Comment by bisakhmondal** [comment]
> PS: Once we fix this we could play with different thanos-receive-controller semantics: We could reshape hashring on every pod restart with little impact!

Hi guys! I can improve this module. I have recently developed an efficient infrastructure with hash rings.  Even there are several research papers on the same.

My basic approach would be 
1. Use `xxhash` (extremely fast) to encode the entities (server-id/name) for buckets (analogy of servers in a cluster) by pivoting them in a circle with the necessary replication factor and routing the balls (entities that we want to route ). The hashing implementation that we can leverage is https://ai.googleblog.com/2017/04/consistent-hashing-with-bounded-loads.html
> Our mod hash is quite naive and has problems to shard our data when changes occur. Every time new replica is added or removed series shards are jumping across replicas.

2. This type of load rebalancing takes a lot of memory. I know the right tool to mitigate the issue. introducing `jump consistent hashing`. https://arxiv.org/pdf/1406.2294.pdf

I am looking forward to working on this project for GSoC 2022. I am new in thanos : ) With the right guidance from you guys, I am sure that I can pull it off. 
What do you think about the small fragment of the proposal that I just proposed? Please do let me know. Thank you!

**Comment by burntcarrot** [comment]
+1 for @bisakhmondal's idea. Using `xxhash` seems like a good choice.

I personally don't know @bisakhmondal, but I believe they can be a suitable contributor for this idea.

**Comment by bwplotka** [comment]
Sounds promising (: Make to apply through GSoC website.

**Comment by Rahul7171** [comment]
Hi all. I am Excel, and I im interested in contributing to this project for GSoC '22. I have joined the community, and have been looking into Thanos too. I am thinking of attending the event that was posted on the community to get up to speed with Thanos  general.

Is this alright? And are there any prerequisites I need to complete to increase my chances, or to write a good proposal? Thank you!
