### ISSUE TITLE
Include promtool in the official Thanos image

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#4980]
### Is your proposal related to a problem?

promtool is very handy when performing operations related to TSDB data. For example, dump TSDB samples and analyze TSDB index. This is very useful in Thanos receiver.

I want to take a look at what labels in a tenant's blocks but there is no such tooling in the Thanos pod.

### Describe the solution you'd like

Download the promtool binary in Thanos Dockerfile

**Comment by wiardvanrij** [comment]
I believe a container should do one thing, and do that good. This generally means one binary / running process. For example how we handle logs, that uses a sidecar. Using promtool could also be done with a sidecar. That removes moving parts in the original container (and also the extra weight/size).

However I also understand the value that it brings so I'm also a bit on the fence on what would be the best solution :)
