### ISSUE TITLE
Receiver: instrument multitsdb tenant series tracing tag correctly

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#5002]
At https://github.com/thanos-io/thanos/blob/main/pkg/store/multitsdb.go#L274, a `tenant` tag is added. But it uses `ClientAddContextTags` method and that method is only used in gRPC method calls. In the case of tenant's local TSDB, there is no gRPC call anymore so the instrumentation doesn't work.

I expect to see https://github.com/thanos-io/thanos/blob/main/pkg/store/multitsdb.go#L172 get properly instrumented with the tenant tag.

Screenshot of the traces for tenant series call:
![image](https://user-images.githubusercontent.com/25150124/147407941-ad805a65-6e15-44e9-b5d1-2ac370afa975.png)

**Comment by wiardvanrij** [comment]
Added tag `good first issue` - even though this is somewhat deeper into the tech, I think with the comment from @yeya24 it should be a fun thing to pick up. Feel free to ask help if needed.

**Comment by metonymic-smokey** [comment]
From a quick look at the linked code references, I think adding a tag to the context [here](https://github.com/thanos-io/thanos/blob/main/pkg/store/multitsdb.go#L172) should fix it?

**Comment by yeya24** [comment]
> From a quick look at the linked code references, I think adding a tag to the context [here](https://github.com/thanos-io/thanos/blob/main/pkg/store/multitsdb.go#L172) should fix it?

Yeah I think so, would you like to give it a try?

**Comment by metonymic-smokey** [comment]
I'll start working on it over the weekend.

**Comment by metonymic-smokey** [comment]
Opened a draft PR. Please let me know if I'm proceeding in the right direction. Many thanks!
