### ISSUE TITLE
Alerts  page Jump to localhost when viewing

### ISSUE THREAD

**Issue by ThorManager** [thanos-io/thanos#5009]
Hello Dear developer：
        Query When viewing the alerts page, if an alarm is triggered, click on the rule and jump to localhost, please help to check it out, thank you very much, and look forward to your reply
![image](https://user-images.githubusercontent.com/96821352/147653117-b8a002b1-d06d-4a07-82b0-e1c75f9d3bd2.png)

**Comment by GiedriusS** [comment]
Hi, do you have `--alert.query-url` set? Thanos Query uses that for formatting the URL. If it is not specified, it uses the listening IP/port. It seems like that is your case. I recommend setting that parameter. Closing this issue to keep the issue tracker clean. Let me know if that helps 😁

**Comment by ThorManager** [comment]
Thank you very much. I saw it when I sent it. I'm sorry to waste your time😁

**Comment by ThorManager** [comment]
Can you provide the API document of receive ~ I want to write my own monitoring plug-in😁
