### ISSUE TITLE
Thanos Query’s query_exemplars API behaviour differs from Prometheus’s

### ISSUE THREAD

**Issue by paulgrav** [thanos-io/thanos#5011]
**Thanos, Prometheus and Golang version used**:  main-2021-12-23-cb447781, v2.31.1, ??

**Object Storage Provider**:

Backblaze B2 using S3 API

**What happened**:

I have a Grafana 8.3.3 instance configured to with a Prometheus datasource that points to Thanos Query. I noticed that Grafana would not display exemplars when the datasource was Thanos Query, but functioned as expected when Prometheus itself was the datasource.

**What you expected to happen**:

I expected behaviour between Prometheus and Thanos to be consistent so that exemplars would be displayed in Grafana.

**How to reproduce it (as minimally and precisely as possible)**:

1. Install Grafana 
2. Install Thanos
3. Configure a datasource in Grafana to point to Thanos Query
4. Navigate to Explore and execute any query e.g., `up{app="prometheus"}`

Mouse-over the Exemplars icon and note that the tooltip displays `Exemplars for this query are not available`
Open your browser’s debug console and note all the failed requests to: `https://<grafanahostname>/api/datasources/proxy/1/api/v1/query_exemplars`

**Full logs to relevant components**:

Grafana makes an API call to determine if exemplars are available. If the API call is successful then exemplars are enabled, otherwise they are disabled.

This is the line of code in the Grafana code base that performs the check: https://github.com/grafana/grafana/blob/43c81ddd23f574ab2bba8c23e008a6cc003028f3/public/app/plugins/datasource/prometheus/datasource.ts#L872

I can emulate the API check using curl: `curl -v -d query=test http://localhost:9090/api/v1/query_exemplars`

The response to the above API call differs between Prometheus and Thanos.

**Prometheus**

```
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Wed, 29 Dec 2021 12:22:38 GMT
< Content-Length: 30
< 
* Connection #0 to host localhost left intact
{"status":"success","data":[]}
```

**Thanos**

```
< HTTP/1.1 400 Bad Request
< Access-Control-Allow-Headers: Accept, Accept-Encoding, Authorization, Content-Type, Origin
< Access-Control-Allow-Methods: GET, OPTIONS
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: Date
< Cache-Control: no-store
< Content-Type: application/json
< Vary: Accept-Encoding
< X-Thanos-Trace-Id: 2c8274dc001f4912
< Date: Wed, 29 Dec 2021 12:25:34 GMT
< Content-Length: 126
< 
{"status":"error","errorType":"bad_data","error":"rpc error: code = Code(400) desc = cannot parse \"\" to a valid timestamp"}
```

**Anything else we need to know**:

N/A

**Comment by yeya24** [comment]
Questions about your setup:
Have you configured Prometheus running with exemplar storage?

Have you configured exemplar stores in your thanos querier?

**Comment by yeya24** [comment]
The fix is straightforward. We can use `parseTimeParam` to parse time so that a default value can be set when time is not specified https://github.com/thanos-io/thanos/blob/main/pkg/api/query/v1.go#L824.

Related code in Prometheus: https://github.com/prometheus/prometheus/blob/main/web/api/v1/api.go#L499

**Comment by paulgrav** [comment]
> Questions about your setup: Have you configured Prometheus running with exemplar storage?
Yes. I’ve set `enable-feature=exemplar-storage` in my Prometheus setup. And I’ve also set `send_exemplars: true` in the `remoteWrite` config.

> Have you configured exemplar stores in your thanos querier?
I wasn’t aware that was required. I have configured Thanos Receive with `--tsdb.max-exemplars=10000`, I thought that was sufficient. 

I do receive exemplars if I handcraft a query to Thanos Query. So I assumed my Thanos setup was configured correctly. e.g.,

```
➤ curl -v -d query='my_requests_total{app="prom-py"}' -d start=1640770731.689 -d end=1640801540.689   http://localhost:10902/api/v1/query_exemplars | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1:10902...
* Connected to localhost (::1) port 10902 (#0)
> POST /api/v1/query_exemplars HTTP/1.1
> Host: localhost:10902
> User-Agent: curl/7.77.0
> Accept: */*
> Content-Length: 78
> Content-Type: application/x-www-form-urlencoded
> 
} [78 bytes data]
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Access-Control-Allow-Headers: Accept, Accept-Encoding, Authorization, Content-Type, Origin
< Access-Control-Allow-Methods: GET, OPTIONS
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: Date
< Content-Type: application/json
< Vary: Accept-Encoding
< X-Thanos-Trace-Id: 6fa5b6f75271c276
< Date: Wed, 29 Dec 2021 18:12:39 GMT
< Transfer-Encoding: chunked
< 
{ [14519 bytes data]
100 14584    0 14506  100    78   291k   1602 --:--:-- --:--:-- --:--:--  339k
* Connection #0 to host localhost left intact
{
  "status": "success",
  "data": [
    {
      "seriesLabels": {
        "__name__": "my_requests_total",
        "app": "prom-py",
        "instance": "10.42.2.229:8000",
        "job": "kubernetes-pods",
        "namespace": "prom-py",
        "pod": "prom-py-6d475ccd9d-drkxz",
        "pod_template_hash": "6d475ccd9d",
        "receive": "true",
        "tenant_id": "default-tenant"
      },
      "exemplars": [
        {
          "labels": {
            "span_id": "eca10f934f4f9479",
            "trace_id": "ee0dc9ff17d22219c68a4a56e09b94f3"
          },
```

**Comment by yeya24** [comment]
> I wasn’t aware that was required. I have configured Thanos Receive with --tsdb.max-exemplars=10000, I thought that was sufficient.
I do receive exemplars if I handcraft a query to Thanos Query. So I assumed my Thanos setup was configured correctly. e.g.,

Yeah, then that's all good. Seems the exemplar store is auto discovered since 0.23.0
