### ISSUE TITLE
Some labels rules defined by Prometheus can't get the custom labels value ？

### ISSUE THREAD

**Issue by ThorManager** [thanos-io/thanos#5013]
Dear developer

Can't I get some labels defined by myself when I need to set the global view, For example, I defined that {{$labels. Role}} is empty when the role alarms. Is there a way to solve it?
![image](https://user-images.githubusercontent.com/96821352/147736326-a7925933-dee6-4a8e-9288-4d7a490fe3cb.png)
![image](https://user-images.githubusercontent.com/96821352/147736355-0dbb95dd-69b0-4542-a310-faa6a57a0eb9.png)

**Comment by yeya24** [comment]
That's more like a question to prometheus rules configuration.

To use the label from template, you need to have role label in your metric.
