### ISSUE TITLE
store on local filesystem for X (ex:days) and on S3 beyond X 

### ISSUE THREAD

**Issue by korenlev** [thanos-io/thanos#5016]
### Is your proposal related to a problem?

  highest performance for shorter-lived data (queries to local ssd)
  lower performance for longer-lived data (queries to s3)

### Describe the solution you'd like

define 2 types of object storage options , assign 1 for initial period and the other for beyond X

OR:
dynamically defined storage option based on certain criteria ?
### Describe alternatives you've considered

none

**Comment by GiedriusS** [comment]
This is already possible with options `--min-time` and `--max-time` just that queries will be actually executed in memory, in a central location due to the lack of https://github.com/thanos-io/thanos/issues/305. Thus, I suggest closing this :smile:

**Comment by korenlev** [comment]
just to be clear please: 
is the current logic to check first the Prometheus local persistent disk ? 
if the store is defined as aws s3 and Prometheus local disk has the requested metrics  (Chunk/s) for that requested time period - will aws s3 be contacted at all ?

**Comment by yeya24** [comment]
If both s3 and Prometheus store are in the requested time range, then they will be contacted at the same time and querier will merge the results and do some deduplication.

**Comment by korenlev** [comment]
greatly appreciate your swift reply guys ! closing this
