### ISSUE TITLE
Recording rules in rules page don't look good with dark theme

### ISSUE THREAD

**Issue by GiedriusS** [thanos-io/thanos#5024]
It seems like the recording rule panel doesn't have the necessary styling applied to it in the dark mode:
![Screenshot from 2022-01-03 18-29-21](https://user-images.githubusercontent.com/2377233/147955261-112d0984-c478-4f9d-823a-7514f004422b.png)
![Screenshot from 2022-01-03 18-30-53](https://user-images.githubusercontent.com/2377233/147955265-125b2da0-4ac0-472c-bbab-2ca6bc2f413b.png)

**Comment by secrashi** [comment]
Hello, I would like to work on this. Can you assign it to me?

**Comment by jaiakash** [comment]
Hello, I like to contribute to this issue.

**Comment by Laconty** [comment]
Hi @GiedriusS! There was no updates more than month, so I would like to make tiny contribution by this one

**Comment by secrashi** [comment]
Hello, sorry I wasn't able to get a hold of this in the past month. I'll unassign myself, please feel free to contribute to this.

**Comment by matej-g** [comment]
Go for it @Laconty 👍

**Comment by solrac97gr** [comment]
Is this Issue finished? I see the merge in the PR, maybe is better close the Issue

**Comment by matej-g** [comment]
You're right @solrac97gr!  https://github.com/thanos-io/thanos/pull/5151 resolved it, let's close this, thanks!
