### ISSUE TITLE
irate/rate query issue on the deduplicated metrics

### ISSUE THREAD

**Issue by gabrielbatir** [thanos-io/thanos#5025]
**Thanos, Prometheus and Golang version used**:

Thanos deployed with kube-prometheus. Initial issue detected while using thanos 0.23.1. Upgraded only thanos query to 0.24.0 but still having this issue.

Thanos compact:
`compact                                                                                                                                                                             --wait                                                                                                                                                                              --log.level=info                                                                                                                                                                    --log.format=logfmt                                                                                                                                                                 --objstore.config=$(OBJSTORE_CONFIG)                                                                                                                                                --data-dir=/var/thanos/compact                                                                                                                                                       --debug.accept-malformed-index                                                                                                                                                      --retention.resolution-raw=360d                                                                                                                                                     --retention.resolution-5m=360d                                                                                                                                                      --retention.resolution-1h=360d                                                                                                                                                      --delete-delay=8h                                                                                                                                                                   --deduplication.replica-label=prometheus_replica                                                                                                                                    --deduplication.replica-label=rule_replica                                                                                                                                          --deduplication.replica-label=replica  `

Thanos query: 
`query                                                                                                                                                                               --grpc-address=0.0.0.0:10901                                                                                                                                                        --http-address=0.0.0.0:9090                                                                                                                                                         --log.level=debug                                                                                                                                                                   --log.format=logfmt                                                                                                                                                                 --query.replica-label=prometheus_replica                                                                                                                                            --query.replica-label=rule_replica                                                                                                                                                  --query.replica-label=replica                                                                                                                                                       --store=dnssrv+_grpc._tcp.prometheus-network-monitoring-thanos-sidecar.network-monitoring.svc.cluster.local                                                                         --store=dnssrv+_grpc._tcp.thanos-store-network-monitoring.network-monitoring.svc.cluster.local                                                                                      --query.timeout=5m                                                                                                                                                                  --query.lookback-delta=15m                                                                                                                                                          --query.auto-downsampling`

Prometheus: quay.io/prometheus/prometheus:v2.29.2
`  --web.console.templates=/etc/prometheus/consoles                                                                                                                                           --web.console.libraries=/etc/prometheus/console_libraries                                                                                                                                   --config.file=/etc/prometheus/config_out/prometheus.env.yaml                                                                                                                        --storage.tsdb.path=/prometheus                                                                                                                                                     --storage.tsdb.retention.time=5d                                                                                                                                                    --web.enable-lifecycle                                                                                                                                                              --storage.tsdb.no-lockfile                                                                                                                                                          --web.external-url=https://prom-network-monitoring                                                                                                      --web.route-prefix=/                                                                                                                                                                --storage.tsdb.max-block-duration=2h                                                                                                                                                --storage.tsdb.min-block-duration=2h    `

Thanos sidecar version: 0.23.1

**Object Storage Provider**:
Minio

**What happened**:
This is one of the metrics where this issue manifests:
![counter](https://user-images.githubusercontent.com/15245568/148035396-221e21a2-a3ed-47fb-9fc0-62599edca06c.jpg)

This is how an irate looks like:
![irate](https://user-images.githubusercontent.com/15245568/148035421-6508833e-106a-447d-8c61-fc1714a66aaa.jpg)

The red line is the irate of the deduplicated metric while the yellow and blue are the irates for the metrics from prometheus.

Pressing Execute multiple times, sometimes the graph looks like this:
![irate2](https://user-images.githubusercontent.com/15245568/148035519-0e7319ec-69d0-41ee-9341-44d44a95ccf7.jpg)

**What you expected to happen**:
I would expect for the irate of the deduplicated metric to look like the original from prometheus.

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:
I could not find any error in thanos compact or thanos query logs.

**Anything else we need to know**:
This is how a rate query looks like on the same metric:
![rate](https://user-images.githubusercontent.com/15245568/148035561-71f0652f-01ea-4a8e-a2f5-ecd1ebc6ce3e.jpg)

It looks somewhat better then the irate query but I would have expected to be closer to the query on the original data from prometheus.

This is how the values of the original and deduplicated metrics look like:

![counter_values](https://user-images.githubusercontent.com/15245568/148039264-e9a2f6f9-5129-4ffa-ba13-40dfe800217e.jpg)
The third line is the deduplicated metric.

Is this a bug or something wrong in my configuration?

**Comment by yeya24** [comment]
Deduplication doesn't work in your case because that's for 1:1 deduplication so mainly in receiver cases.
In the case of HA prometheus, you cannot do deduplication and the two series merge into one. I think that's the reason why irate won't work for you. If you disable deduplication then it should work.

**Comment by gabrielbatir** [comment]
Now I noticed that the deduplicated stream actually contains the metrics from both prometheus replicas and in most cases the values are identical for both.
I am not really sure how irate works but could this be the issue?

Could this be fixed by using --deduplication.func=penalty for the compactor? From the docs this option seems to break irate in other ways.

**Comment by gabrielbatir** [comment]
@yeya24 From what I can see at https://thanos.io/tip/components/compact.md/#enabling-vertical-compaction in order to enable vertical compaction I need to use that hidden flag. 
From that page I understand that it is not enabled by default yet in my case, as you can see above, I do have it but compact does vertical compaction.

Maybe the note at https://github.com/thanos-io/thanos/blob/56d99eb8123aedc51d66645f3424e0177fc10b3e/cmd/thanos/compact.go#L719 could be put in the documentation.

**Comment by RayHuangCN** [comment]
I meet the same case.

**Comment by yeya24** [comment]
> Could this be fixed by using --deduplication.func=penalty for the compactor? From the docs this option seems to break irate in other ways.

Ideally it should solve the issue but now the functionality is not very stable when downsampling is also enabled so I wouldn't recommend enabling it.

> Maybe the note at could be put in the documentation.

Yeah that's a good idea. Would you like to contribute and update the doc?
