### ISSUE TITLE
How long has the directory been compressed? It cannot be cleaned up. It must be cleaned up manually. If it is not cleaned up, there will be data disorder

### ISSUE THREAD

**Issue by ThorManager** [thanos-io/thanos#5029]
report errors： get segment range: segments are not sequential\nopening storage
Data disorder：
![image](https://user-images.githubusercontent.com/96821352/148151854-6ab99deb-cfe2-4f99-82d5-0ce6d9cb0ef3.png)

**Comment by yeya24** [comment]
Hi @ThorManager, what directory did you mean here? The directory of your object storage bucket or something else?
