### ISSUE TITLE
Bucket tool: support other type of matchers in replicate

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#5038]
### Is your proposal related to a problem?

Bucket replicate tool supports matchers to select data blocks with specified matchers. But now it just supports equal matchers and it is not very flexible to specify multiple values (tenants/clusters).
In case I need to replicates blocks from multiple clusters, then I have to use multiple thanos replicates.

It would be great to support all kind of matchers in the selector. If it is not that flexible from command line args, it would be good to also read matchers from files, too.

**Comment by GiedriusS** [comment]
Perhaps the new `matchers` functionality (code) from Alertmanager could be used here?

**Comment by kama910** [comment]
Hello, may I work on this issue?

**Comment by yeya24** [comment]
@kama910 Sure please go ahead!
