### ISSUE TITLE
Query failed to query historical data after adding store 

### ISSUE THREAD

**Issue by ThorManager** [thanos-io/thanos#5039]
After adding a store to query, the historical data cannot be queried. Check that there is historical data in the store
![image](https://user-images.githubusercontent.com/96821352/148505157-6f924ccd-d778-4516-a25e-72063bb47034.png)
![image](https://user-images.githubusercontent.com/96821352/148505187-17ff03c9-7fbe-444d-b0a9-c252ad803d79.png)
![image](https://user-images.githubusercontent.com/96821352/148505229-230077e1-8cd3-4f1e-8e12-39db39685ff7.png)

**Comment by yeya24** [comment]
@ThorManager Looks like the old data get downsampled and the raw data has been deleted due to retention.
You can query the old data by changing `Only raw data` to some value else, for example 1h.

**Comment by ThorManager** [comment]
Hi， After changing only raw data, there is no old data
![image](https://user-images.githubusercontent.com/96821352/148518119-98b172bd-9058-4246-a853-bd43e510ddd2.png)

**Comment by yeya24** [comment]
@ThorManager I meant you should change `Only raw data` to other options like `5m downsampled` or `1h downsampled data`.

**Comment by yeya24** [comment]
Hi @ThorManager, does the solution work for you?
