### ISSUE TITLE
Bucket UI: search by ULID should only show the group that contains the searched block

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#5044]
### Is your proposal related to a problem?

I am trying to search one block using the bucket web search feature.

![image](https://user-images.githubusercontent.com/25150124/148662322-e3ff257c-04eb-489f-9fe1-e0cbe08e6ba5.png)

As you can see, the web page still contains a lot of empty groups, which means that the searched block is not at that group.

I have to scroll down all the way to group 67 to find my block. It is not very easy to use and find that block from UX.

![image](https://user-images.githubusercontent.com/25150124/148662351-793c4f92-2a0e-4a33-a48b-2061786cef0e.png)

### Describe the solution you'd like

When using the search feature, only show the group that contains my search result (the block). If the searched block is not there, I expected to see some message like `block not exist`.

**Comment by tend2infinity** [comment]
Hey, I would like to work on this issue, Please assign this to me, Thank you!

**Comment by yeya24** [comment]
Hi @tend2infinity, feel free to work on it!

**Comment by tend2infinity** [comment]
Hey @yeya24 just let me know any changes in this PR

**Comment by yeya24** [comment]
Close by #5102
