### ISSUE TITLE
Advertise docs on settings

### ISSUE THREAD

**Issue by jarlva** [thanos-io/thanos#5048]
I've spent the last two days trying to find how to limit compactor memory/cpu. It's mission impossible!
The only thing I found, indirectly, is via a mention in https://artifacthub.io/packages/helm/bitnami/thanos/2.3.1
Specifically `resources.limits`. What's the syntax?
Where can I find that info? Please make it easier to find. Examples are welcome!

**Comment by yeya24** [comment]
Please check our docs and I think it is mentioned https://thanos.io/tip/components/compact.md/#resources.
