### ISSUE TITLE
Sidecar The host list cannot be viewed after startup

### ISSUE THREAD

**Issue by ThorManager** [thanos-io/thanos#5052]
![image](https://user-images.githubusercontent.com/96821352/148739100-467699a7-95e1-4c2f-a1bb-29ccd7dc2162.png)
![image](https://user-images.githubusercontent.com/96821352/148739117-211225fb-3b1c-4816-862e-e8ce09c88c1e.png)
There are no errors in the query sidecar log
![image](https://user-images.githubusercontent.com/96821352/148739198-0146e5f9-45a7-4c8f-9c4a-627dd9e2bfc0.png)
![image](https://user-images.githubusercontent.com/96821352/148739224-74f17b04-b7cf-4a6c-992c-0b135bb11c95.png)
![image](https://user-images.githubusercontent.com/96821352/148739267-26445859-53c8-4647-b6de-3cd228e2da43.png)

**Comment by yeya24** [comment]
What's your version of thanos query and how do you configure your sidecars to your thanos query? Using the --store flag or --endpoint flag?

I am not 100% sure about whether targets federation is enabled automatically or not.

**Comment by ThorManager** [comment]
Hi,my thanos version is 0.24.0-rc.2，configured --store 
![image](https://user-images.githubusercontent.com/96821352/148741045-3dbc8525-e7cc-44b9-90cc-d0bcaf5051c0.png)

**Comment by yeya24** [comment]
I think you can either switch to endpoint flag or use target flag to specify sidecar ip. This should work for targets federation

**Comment by ThorManager** [comment]
Sorry, you can provide yaml configuration of endpoint. I don't quite understand the official website. Thank you

**Comment by ThorManager** [comment]
![image](https://user-images.githubusercontent.com/96821352/148742019-055e52f3-a05c-4af4-b378-ea83ec370625.png)

**Comment by ThorManager** [comment]
I saw an error

 tset msg="update of node failed" err="getting metadata: fallback fetching info from 192.168.10.29:1721: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=192.168.10.29:1721

**Comment by yeya24** [comment]
@ThorManager  So what thanos query version are you using? If you are using the latest release then I think query targets can be discovered automatically. Can you please try it?

Otherwise, the only way I can think of is to add `--target` flag with your sidecar addresses manually.

**Comment by yeya24** [comment]
Close as this I think this is just a configuration question. @ThorManager Let me know if this doens't work for you and feel free to reopen the issue.
