### ISSUE TITLE
Does thanos supports Oracle Cloud

### ISSUE THREAD

**Issue by vickyvikas7988** [thanos-io/thanos#5062]
Hi,

Do Thanos support Oracle Cloud (OCI)?

We would like to use Oracle Object Storage.

Please suggest

**Comment by GiedriusS** [comment]
https://github.com/thanos-io/thanos/pull/4661

**Comment by hyder** [comment]
You can use OCI's object storage S3 compatible interface until #4661 is accepted. See https://medium.com/oracledevs/monitoring-multiple-oke-clusters-with-prometheus-thanos-and-grafana-part-1-df11df7013f1 for an example using running on OCI's managed K8s service.

**Comment by vickyvikas7988** [comment]
Thanks @hyder
