### ISSUE TITLE
Thanos QFE seems to be caching inconsistently

### ISSUE THREAD

**Issue by sharathfeb12** [thanos-io/thanos#5075]
Thanos QFE version: v0.24.0
Thanos Querier version: v0.24.0

We are using Thanos QFE as the front-end component to handle splitting and caching of query results. However, we see inconsistent results while querying from QFE vs querying from Querier directly. 

It looks like lot of data points are omitted and straight lines joining the gap seem to be common across multiple graphs. Below is one of the graphs where we see straight line pattern between 14th to 18th.

![image](https://user-images.githubusercontent.com/24534706/150058167-4f2bc040-19d6-41ed-8189-56aaef167564.png)

When I query querier directly, I see the changes in the metrics reported correctly.

![image](https://user-images.githubusercontent.com/24534706/150058715-051ee45a-4566-4f01-9f61-84f1d67cdf50.png)

QFE config: 

      containers:
      - args:
        - query-frontend
        - --log.level=error
        - --log.format=logfmt
        - --http-address=0.0.0.0:9090
        - --query-frontend.downstream-url=http://observatorium-thanos-query.monitoring.svc.cluster.local.:9090
        - --query-range.split-interval=24h
        - --labels.split-interval=24h
        - --query-range.max-retries-per-request=5
        - --query-range.max-query-parallelism=30
        - --labels.max-query-parallelism=10
        - --query-range.response-cache-max-freshness=1m
        - --labels.response-cache-max-freshness=1m
        - --labels.max-retries-per-request=10
        - --query-frontend.log-queries-longer-than=10s
        - |-
          --query-range.response-cache-config="config":
            "addresses":
            - "dnssrv+_client._tcp.observatorium-thanos-query-frontend-memcached.monitoring.svc.cluster.local:11211"
            "dns_provider_update_interval": "10s"
            "max_async_buffer_size": 10000
            "max_async_concurrency": 20
            "max_get_multi_batch_size": 0
            "max_get_multi_concurrency": 0
            "max_idle_connections": 1000
            "max_item_size": 128MiB
            "expiration": 240h
            "timeout": "500ms"
          "type": "memcached"
        - |-
          --labels.response-cache-config="config":
            "addresses":
            - "dnssrv+_client._tcp.observatorium-thanos-query-frontend-memcached.monitoring.svc.cluster.local:11211"
            "dns_provider_update_interval": "10s"
            "max_async_buffer_size": 10000
            "max_async_concurrency": 20
            "max_get_multi_batch_size": 0
            "max_get_multi_concurrency": 0
            "max_idle_connections": 100
            "max_item_size": 128MiB
            "expiration": 240h
            "timeout": "500ms"
          "type": "memcached"

**Comment by GiedriusS** [comment]
Is it the same if you drop all items from Memcached? How could we reproduce this?

**Comment by sharathfeb12** [comment]
There is no guaranteed way to do this as it seems to be intermittent. But, it's very frequent. The only way seems to be bouncing the memcached pods and re-executing query to fill up "correctly". However, this happens again in a while for a random dashboard.

**Comment by wiardvanrij** [comment]
What I would like to see is a dashboard without Grafana's magic to infer the points together. Create a dashboard that has the raw data points. As I'm fairly confident that you are indeed missing data and that it is cached like that. 
Could you also check if you see any errors from your stores, indicating query failure and/or OOM things? Also any errors related to calling memcached? 

Also, just something extra;
`"max_item_size": 128MiB` ? :) 

That seems excessive. I would lower this by a lot and also check if your memcached instance allows for the value that you set here.
