### ISSUE TITLE
Thanos Querier not able to query to query data more than 2 days

### ISSUE THREAD

**Issue by dpachiappan** [thanos-io/thanos#5078]
I have deployed Thanos operator to deploy the Thanos Components, Querier, Receiver and store replica in our setup. Prometheus is using remote write to push the changes to Thanos receiver, that stores the data in S3 bucket.

I can see the data in the S3 bucket that is more than 6 months old. However, the thanos querier only shows the data for last 2 days. The historical data for more than 2 days is not showing up in querier.

Thanos Querier helm chart values:

queryFrontend:
HTTPIngress:
host: query-monitoring.dev-us-east-1.tscloudservice.com
rule: {}
storeGateway: {}
storeEndpoint:
url: dns+thanos-receiver-tenant-a.monitoring.svc.cluster.local:10907

**Object Storage Provider**:

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by fktkrt** [comment]
Could you please share your Query config/flags? My guess is that it doesn't contain the Store Gateway, which would be needed to access the data stored in the S3 bucket.

**Comment by dpachiappan** [comment]
Thanks for getting back. We do have store configuration updated in the querier. Here is the Argument to the thanos querier pod.

   Args:
      query
      --grpc-address=0.0.0.0:10901
      --http-address=0.0.0.0:10902
      --log.level=info
      --query.replica-label=prometheus_replica
      --query.replica-label=receive_replica
      --store=dns+thanos-receiver-tenant-a.monitoring.svc.cluster.local:10907
      --store=dnssrvnoa+_grpc._tcp.thanos-thanos-rule.monitoring.svc.cluster.local
      --store=dnssrvnoa+_grpc._tcp.thanos-thanos-store.monitoring.svc.cluster.local
    State:          Running

I have also attached the screen shot of the querier UI that shows the store API configurations.


![image](https://user-images.githubusercontent.com/2790411/150904347-019fdb55-2b44-4cd8-b623-22e5326b7ab0.png)

**Comment by dpachiappan** [comment]
Here is the screenshot of the Thanos querier for the last 2 weeks where it shows data only till 12th Jan.  Metrics before 12th Jan is not available in the querier.

![image](https://user-images.githubusercontent.com/2790411/150906710-605bb9e1-6ec3-4190-8b04-f3cd7f68388b.png)


Few details to troubleshoot.

1.  I verified the data in the thanos store data directory and I can see the indexer file for the data older than 6 months. Hence, it is clear that the store Gateway has the information for the metrics older than 6 months. However, the querier is not able to fetch the data older than 2 weeks.

**Comment by dpachiappan** [comment]
I tried filtering the store API to see if querier can query only the thanos store. I still get the empty result for queries earlier than a week.

Attached the screenshot for reference. Thanks again for your help. Let me know if you need any other information to troubleshoot this issue.

![image](https://user-images.githubusercontent.com/2790411/150908261-a68daded-fd94-4b57-a832-d43fbae25345.png)

**Comment by dpachiappan** [comment]
I see the below logs in Thanos querier that might be of interest for further troubleshooting.

level=warn ts=2022-01-22T05:52:48.244896903Z caller=storeset.go:490 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from 10.193.12.11:10907: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=10.193.12.11:10907
level=info ts=2022-01-22T05:52:48.245025626Z caller=storeset.go:379 component=storeset msg="removing store because it's unhealthy or does not exist" address=10.193.12.11:10907 extLset="{receive_replica=\"thanos-receiver-tenant-a-0\", tenant_id=\"default-tenant\"}"
level=warn ts=2022-01-22T05:52:53.245342618Z caller=storeset.go:490 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from 10.193.12.11:10907: rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = \"transport: Error while dialing dial tcp 10.193.12.11:10907: connect: no route to host\"" address=10.193.12.11:10907
level=warn ts=2022-01-22T05:52:58.246800179Z caller=storeset.go:490 component=storeset msg="update of store node failed" err="getting metadata: fetching store info from 10.193.12.11:10907: rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = \"transport: Error while dialing dial tcp 10.193.12.11:10907: connect: no route to host\"" address=10.193.12.11:10907

**Comment by dpachiappan** [comment]
I had resolved the issue by restarting the minio service. 

Minio is not able to fetch the data from S3 bucket. This caused the store gateway unable to fetch the metrics older than a certain number of days.

Restarting minio helped the store gateway fetch the blocks from S3 bucket. 

Had to restart the Thanos querier as it was still unresponsive to the queries older than 4 days.

After performing the above procedure, thanos is able to query the older metrics without any issue.

Thanks for the continued support.
