### ISSUE TITLE
tools: bucket rewrite uploaded my local path to Azure storage

### ISSUE THREAD

**Issue by ehrnst** [thanos-io/thanos#5097]
**Thanos, Prometheus and Golang version used**: thanos 0.22, latest on local computer

**Object Storage Provider**: Azure

**What happened**:

object storage path was replaced with local path after rewrite.

![image](https://user-images.githubusercontent.com/21357174/150792164-cbe18422-386c-40f3-b1fe-753dfc8bbca1.png)

**What you expected to happen**:

After running `./thanos.exe tools bucket rewrite --delete-blocks --rewrite.to-delete-config-file config.yaml --objstore.config-file objectstore.yaml --id <id>` i expected the rewritten blobs to be uploaded to `<blobId>\chunks` but instead they where uploaded what my local working path looked like. Resulting in no data in any query hitting those blobs.

config yaml

`- matchers: '{__name__="http_client_requests_seconds_*", __app__="consent"}'`

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**: error from query front

`Error executing query: expanding series: proxy Series(): Addr: 10.0.1.247:10901 LabelSets: {prometheus="monitoring/k8s", prometheus_replica="prometheus-k8s-0"},{prometheus="monitoring/k8s"} Mint: 1622539414700 Maxt: 9223372036854775807: receive series from Addr: 10.0.1.247:10901 LabelSets: {prometheus="monitoring/k8s", prometheus_replica="prometheus-k8s-0"},{prometheus="monitoring/k8s"} Mint: 1622539414700 Maxt: 9223372036854775807: rpc error: code = Unknown desc = Addr: 10.131.0.85:10901 LabelSets: {prometheus="monitoring/k8s", prometheus_replica="prometheus-k8s-0"},{prometheus="monitoring/k8s"} Mint: 1622539414700 Maxt: 1643025600000: receive series from Addr: 10.131.0.85:10901 LabelSets: {prometheus="monitoring/k8s", prometheus_replica="prometheus-k8s-0"},{prometheus="monitoring/k8s"} Mint: 1622539414700 Maxt: 1643025600000: rpc error: code = Aborted desc = fetch series for block 01FSTDYS9Y1FNXHMS8EXAPZYQE: load chunks: get range reader: X-Ms-Error-Code: [BlobNotFound]`

**Anything else we need to know**:

I tried to take the data in the blob refrerenced in the error and move the files to the correct path. then I re-ran the same query, but result was the same, only referencing another ID.

**Comment by wiardvanrij** [comment]
Regardless of the cause, we need to make it better so we can prevent this behaviour from the tool
