### ISSUE TITLE
Thanos Query is failing to handle requests

### ISSUE THREAD

**Issue by Lord-Y** [thanos-io/thanos#5154]
Hello guys,

I already post this [here on the slack channel](https://cloud-native.slack.com/archives/CK5RSSC10/p1637938692373400) but this time, I'm going to put it in an issue to track it.

I'm running thanos since version 0.6.X and I'm so glad to use it.
So far everything works except that since many months in production, I'm having alerts like `Thanos Querier is failing to handle XXX% of "query_range" requests.` twice a day (sometimes more)
I put some thanos components logs in debug, I don't have any clue of what's wrong.

Here is my architecture:
- 2 VMs (n1-standard-32 so 32 CPU/120.00 GB) with:
  - prometheus
  - thanos sidecar, query, store and the compactor is running ONLY on first machine
  - nginx
- 1 production kubernetes cluster with [prometheus-adapter](https://github.com/kubernetes-sigs/prometheus-adapter) installed

`prometheus-adapter` (version v0.9.1 but previously v0.8.X) is calling thanos query through the LB in from of the 2 VMs in order to scale pods or not.

I'm actually running thanos version:
```bash
thanos, version 0.23.1 (branch: HEAD, revision: 5327cd8b9bd56ce4912fe602197ad04ab2722b18)
  build user:       root@0acc901868e9
  build date:       20211005-12:08:29
  go version:       go1.16.8
  platform:         linux/amd64
```

```bash
prometheus, version 2.31.1 (branch: HEAD, revision: 411021ada9ab41095923b8d2df9365b632fd40c3)
  build user:       root@9419c9c2d4e0
  build date:       20211105-20:35:02
  go version:       go1.17.3
  platform:         linux/amd64
```

OS version:
```bash
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```
I recently switch to Debian 11 this month but it was Debian 10 before.

Thanos config:
```bash
ARGS="sidecar \
      --log.level=info \
      --tsdb.path=/data/prometheus/XXXXX/ \
      --prometheus.url=http://0.0.0.0:9090 \
      --objstore.config-file=/etc/prometheus/XXXXX/secrets/thanos-storage.yml \
      --grpc-address=0.0.0.0:10901 \ # sidecar gprc address
      --http-address=0.0.0.0:10902 \ # sidecar http address
```

```bash
ARGS="query \
      --log.level=debug \
      --selector-label='environment=\"XXXXX\"' \
      --grpc-address=0.0.0.0:10903 \ # query grpc address
      --http-address=0.0.0.0:10904 \ # query http address
      --store=0.0.0.0:10905 \  # store gprc address
      --store=0.0.0.0:10901 \  # sidecar gprc address
      --web.external-prefix=XXXXX/thanos/ \
      --query.replica-label=prometheus_replica"
```

```bash
ARGS="store \
      --log.level=info \
      --grpc-address=0.0.0.0:10905 \ # store gprc address
      --index-cache-size=500MB \
      --chunk-pool-size=8GB \
      --http-address=0.0.0.0:10906 \  # store http address
      --data-dir=/data/thanos/XXXXX/store \
      --objstore.config-file=/etc/prometheus/XXXXX/secrets/thanos-storage.yml"
```

```bash
ARGS="compact \
      --log.level=info \
      --http-address=0.0.0.0:10912 \ # compactor address
      --data-dir=/data/thanos/XXXXX/compactor \
      --objstore.config-file=/etc/prometheus/XXXXX/secrets/thanos-storage.yml \
      --wait-interval=15m \
      --retention.resolution-raw=180d \
      --retention.resolution-1h=30d \
      --retention.resolution-5m=14d \
      --wait"
```

My storage provider is Google Cloud Storage

The the query logs, I have lines like:
```bash
level=debug ts=2022-02-02T15:40:47.32878574Z caller=proxy.go:281 component=proxy request="min_time:1643816326000 max_time:1643816446000 matchers:<type:NEQ name:\"ingress\" > matchers:<type:RE name:\"controller_pod\" value:\".*\" > matchers:<type:RE name:\"controller_class\" value:\".*\" > matchers:<type:RE name:\"controller_namespace\" value:\".*\" > matchers:<type:RE name:\"ingress\" value:\".*\" > matchers:<name:\"__name__\" value:\"nginx_ingress_controller_response_size_sum\" > aggregates:COUNTER " msg="Series: started fanout streams" status="Store Addr: 0.0.0.0:10901 LabelSets: {cluster=\"XXXXX\", environment=\"XXXXX\", prometheus_replica=\"yyyyyyyyyyyyyyyyyyyy\"} Mint: 1643731200006 Maxt: 9223372036854775807 queried;store Addr: 0.0.0.0:10905 LabelSets: {cluster=\"XXXXX\", environment=\"XXXXX\", prometheus_replica=\"yyyyyyyyyyyyyyyyyyyy\"},{cluster=\"XXXXX\", environment=\"XXXXX\", prometheus_replica=\"zzzzzzzzzzzzzzzzzzzz\"} Mint: 1626912000004 Maxt: 1643810400000 filtered out: does not have data within this time period: [1643816326000,1643816446000]. Store time ranges: [1626912000004,1643810400000]"
```

The hours of the alerts don't match the hours of those logs.
When I'm zooming on the grafana and match the hours of the alerts, I don't see any spikes on Thanos dashboards (query, store etc)

On Thanos UI, everything is green.
In the graph part of Thanos UI, when I'm applying `http_requests_total{code=~"5..", job=~"thanos-querier.*", handler="query"}` query I can the result is `http_requests_total{cluster="XXXXX", code="503", environment="XXXXX", handler="query", instance="0.0.0.0:10904", job="thanos-querier", method="post"} 1`

Any help on how to improve things or what am I missing?
I googled, githubed etc but nothing help me to resolve this issue.

PS: load cpu/ram on both VMs are okay

**Comment by yeya24** [comment]
> level=debug ts=2022-02-02T15:40:47.32878574Z caller=proxy.go:281 component=proxy request="min_time:1643816326000 max_time:1643816446000 matchers:<type:NEQ name:\"ingress\" > matchers:<type:RE name:\"controller_pod\" value:\".*\" > matchers:<type:RE name:\"controller_class\" value:\".*\" > matchers:<type:RE name:\"controller_namespace\" value:\".*\" > matchers:<type:RE name:\"ingress\" value:\".*\" > matchers:<name:\"__name__\" value:\"nginx_ingress_controller_response_size_sum\" > aggregates:COUNTER " msg="Series: started fanout streams" status="Store Addr: 0.0.0.0:10901 LabelSets: {cluster=\"XXXXX\", environment=\"XXXXX\", prometheus_replica=\"yyyyyyyyyyyyyyyyyyyy\"} Mint: 1643731200006 Maxt: 9223372036854775807 queried;store Addr: 0.0.0.0:10905 LabelSets: {cluster=\"XXXXX\", environment=\"XXXXX\", prometheus_replica=\"yyyyyyyyyyyyyyyyyyyy\"},{cluster=\"XXXXX\", environment=\"XXXXX\", prometheus_replica=\"zzzzzzzzzzzzzzzzzzzz\"} Mint: 1626912000004 Maxt: 1643810400000 filtered out: does not have data within this time period: [1643816326000,1643816446000]. Store time ranges: [1626912000004,1643810400000]"

This log didn't bring any harm. It just means that the time range you queried is not within the store's time range. So the query will try to fetch data from your sidecar because the data there is newer. This is a very common case when you fetch the latest data.

**Comment by Lord-Y** [comment]
@yeya24 Sorry but why didn't closed the issue? I'm still don't know what's causing the "failing to handle requests" and how to solve it. Do you have any ideas?

**Comment by yeya24** [comment]
> @yeya24 Sorry but why didn't closed the issue? I'm still don't know what's causing the "failing to handle requests" and how to solve it. Do you have any ideas?

It is the expected behavior and you don't have to solve it. It is how thanos works
