### ISSUE TITLE
client for Azure should handle permission errors

### ISSUE THREAD

**Issue by ludydoo** [thanos-io/thanos#5172]
**Thanos, Prometheus and Golang version used**:
Thanos 0.24.0

**Object Storage Provider**:
Azure

**What happened**:
We are using `azure-pod-identity` to grant pods access to azure resources. In this case, we have a `thanos-store` Identity.
This Identity is allowed the `Storage Blob Data Reader` role on the storage account. 

The documentation speficies that the `thanos-store` should only have read access. (only `thanos-compactor` and `thanos-sidecar` should have write access). Though, it seems that the azure client tries to create the azure container regardless. In this case, there is a permission error.

```
error creating Azure blob container
```

See here https://github.com/thanos-io/thanos/blob/d0249f17e8ff561dbbedb491f4525d93518cb43b/pkg/objstore/azure/azure.go#L190-L207

In this block, I would check if the container already exists before trying to create it. Or handle the permission error.

**Comment by GiedriusS** [comment]
Seems like a good idea to check whether the container already exists before creating. Thanks for the thorough issue report. PRs welcome! :beers:

**Comment by phillebaba** [comment]
I have been looking at refactoring the Azure implementation while updating the SDK dependencies, in the hopes to make it a bit easier to read. Will make sure to add this while I am at it unless someone creates a PR before me.
