### ISSUE TITLE
Rule: Alertmanager config creation does not error out when provided with an URL with an empty scheme

### ISSUE THREAD

**Issue by jessicalins** [thanos-io/thanos#5186]
**Thanos version used**: 0.24.0

**Object Storage Provider**: S3

**What happened**:
When configuring [alertmanagers.url](https://github.com/thanos-io/thanos/blob/main/cmd/thanos/config.go#L207) to for example:
```bash
dnssrv+_http._tcp.example.com
```
The Alertmanager configuration still gets created and Thanos Rule errors out with:

```bash
unsupported protocol scheme
```
The error is returned only when Thanos tries to [post](https://github.com/thanos-io/thanos/blob/main/pkg/alert/alert.go#L457) to the specified alert URL.

This seems to happen because the URL gets parsed [here](https://github.com/thanos-io/thanos/blob/main/pkg/alert/config.go#L92) by `url.Parse` and it does not create an error, even if the scheme is not in the format as expected from the [tests](https://github.com/thanos-io/thanos/blob/main/pkg/alert/config_test.go#L85)

Since `Scheme` is empty this [logic](https://github.com/thanos-io/thanos/blob/main/pkg/alert/config.go#L99) does not happen and `Scheme` remains empty, causing it to return an error just when trying to post to the configured URL.

**What you expected to happen**:

It would be nice to error out earlier, maybe during the config creation:
https://github.com/thanos-io/thanos/blob/main/pkg/alert/config.go#L92-L95

**How to reproduce it (as minimally and precisely as possible)**:
* Change `alertmanagers.url` config to a URL that has this format: `dnssrv+_http._tcp.example.com`
* It is also possible to change one of the test cases in [config_test.go](https://github.com/thanos-io/thanos/blob/main/pkg/alert/config_test.go#L47) and verify that the resulting struct does have an empty `Scheme` field.

cc @matej-g @saswatamcode

**Comment by Harshitavkb26** [comment]
Hi, @matej-g. I am interested in working on this issue.

**Comment by matej-g** [comment]
Hey @Harshitavkb26 go for it :rocket:

**Comment by jessicalins** [comment]
hi, what is the status of this issue? In case no one is working on it I can pick it up :)

**Comment by matej-g** [comment]
@jessicalins go for it!

**Comment by matej-g** [comment]
I'm wondering if there's space to unify the formats between all configs / components :thinking:, since that DNS directive is being used with other components. Maybe there is way to reuse or adapt this to use the `discovery/dns` package?

**Comment by matej-g** [comment]
Resolved by https://github.com/thanos-io/thanos/pull/5405, closing :raised_hands:
