### ISSUE TITLE
Query: missing alerts in UI when working with sharded Prometheus

### ISSUE THREAD

**Issue by jleloup** [thanos-io/thanos#5190]
Thanos Query UI only shows a subset of alert occurrences in `Alerts` when Thanos stores are sidecars in [sharded](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/shards-and-replicas.md) Prometheus instances.

**Thanos, Prometheus and Golang version used**:

* Thanos: 0.24.0
* Prometheus 2.33.1
* Prometheus Operator: 0.54.0

**Object Storage Provider**:

* S3

**What happened**:

Thanos Query `Alerts UI` shows me only the alert occurence from one of the shard.

Example: ![Screen Shot 2022-02-28 at 14 59 17](https://user-images.githubusercontent.com/20790125/155996820-bb02174e-7636-4c4e-9f62-82cb6131df18.png)

I this screenshots: Thanos Query shows results only from the shard 0.

**What you expected to happen**:

Thanos Query `Alerts UI` should show me the all occurrences of the alert from all shards.

In the previous example: there should be four results: two from shard 0 (as being displayed in the scren shot) but also two from shard 1.

**How to reproduce it (as minimally and precisely as possible)**:

* Deploy prometheus with two shards using prometheus-operator [sharding feature](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/shards-and-replicas.md)
* Configure Thanos Query using **dnssrv** to discover those sidecars as stores
* Create a test alert in Prometheus using a metric available in both shards: `prometheus_build_info > 0` is a suitable use case for this.

**Anything else we need to know**:

I suspect this behaviour comes from the act that Thanos Query UI deduplicates RulesAPI results as it expects multiple similar results from Prometheus replicas.
Then Prometheus shards are probably being treated as replicas right now while in fact they are exposing different RulesAPI results that have to be merged before being displayed in UI so Thanos Query could display those alerts regardless of their origin shard.

**Comment by yeya24** [comment]
> Deploy prometheus with two shards using prometheus-operator [sharding feature](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/shards-and-replicas.md)

I am not familiar with the sharding feature but I remembered that sharding is only sharding scrape targets, right? For alerts two Prometheus are evaluating the same rules so the alerts should be the same?

**Comment by GiedriusS** [comment]
This is by design. It deduplicates the results automatically according to the labels you have specified. If there is a firing and a not firing alert then it shows you the firing one. Perhaps we could add a checkbox for "Deduplication enabled" or something like that to this page but I'm not sure about the value of such a feature because from Alertmanager's perspective if the alert is firing from at least one replica then the final status of the alert is firing.

**Comment by jleloup** [comment]
> > Deploy prometheus with two shards using prometheus-operator [sharding feature](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/shards-and-replicas.md)
> 
> I am not familiar with the sharding feature but I remembered that sharding is only sharding scrape targets, right? For alerts two Prometheus are evaluating the same rules so the alerts should be the same?

prometheus-operator sharding does indeed spread targets across a set of prometheus instances by using relabelling with a hasmod & keeping only results that happens to match the shard number (as dictated by the operator).

While two shards replicas happens to process the same targets, thus should evaluate the same alerts as a result: this does not apply to other shards.

Basically I am looking for a way to ensure that Thanos deduplicates replicas of the same shard but still consider shards as if they were different prometheus instances, which essentially they are.

I'll check for a way to achieve this by refining my deduplication labels: the usual labels identifying only a prometheus instance name does not work as-is since all shards shares the same name as they are coming from the very same `Prometheus` custom ressource.
So then I hope the prometheus-operator allows users to have something like a `shard` label that I can include in thanos query deduplication flags.

**Comment by jleloup** [comment]
> This is by design. It deduplicates the results automatically according to the labels you have specified. If there is a firing and a not firing alert then it shows you the firing one. Perhaps we could add a checkbox for "Deduplication enabled" or something like that to this page but I'm not sure about the value of such a feature because from Alertmanager's perspective if the alert is firing from at least one replica then the final status of the alert is firing.

A `Deduplication Enabled` checkbox in the Rule UI would not solve my issue as I still want deduplication to remove duplicated results coming from replicas while letting results from different shards to make it through.

I understand that this is not a Thanos issue per se and that the Thanos Query flag `--query.replica-label` is precisely meant for this purpose.
I haven't found a suitable label yet though since prometheus-operator does not set anything useful, I suspect this will end with a relabelling applied to all targets fetching shard name from pod names.
