### ISSUE TITLE
tools: test rules

### ISSUE THREAD

**Issue by FUSAKLA** [thanos-io/thanos#5191]
Hi, I'm in need of unit testing Thanos rules and so far had no issues using a promtool since no one used the `partial_response_strategy` configuration option until now.

Looking at the Prometheus code, the only thing exported is the [`RulesUnitTest`](https://github.com/prometheus/prometheus/blob/e25a5992555527d26e53ea4d24e1b8bf16528c58/cmd/promtool/unittest.go#L42) function. 
Since it uses file names as parameters, there is no way to drop the config option before unmarshalling.

I can think of few options:
  - Suggest users to delete the config option by themselves before using the `promtool` something like
     ```bash
     find ./thanos-rules/ -name "*.yaml" -not -name "*_test.yaml" -print0 | LC_ALL=C sort -z | xargs --null yq -i 'del(.groups.[].partial_response_strategy)'
      ```
   - Add a tools sub-command that will just do this, so it's easier for the user and does not require to state the filed name outside our codebase but still leave the user with the promtool
   - Do the above into tmp files and run the tests on those and cleanup afterwards
   - Try to ask for exporting the unit test code, so it can be used
   - Copy most of the code :confounded: 
   

Any suggestions? I'd be happy to implement any of those, just wanted to agree on the solution first.
Thanks for any suggestions in advance!

**Comment by matej-g** [comment]
If can get upstream folks to export those methods, I think that would be the cleanest way to go. It also looks like this would be analogous with what we already do for [`tools rules-check`](https://github.com/thanos-io/thanos/blob/main/docs/components/tools.md#rules-check).

**Comment by FUSAKLA** [comment]
Yeah, I implemented that back then and hoped that the code will be exported for unit testing as well now, but unfortunately It's not.
I know exporting methods on demand in Prometheus was never an easy task, but sure that would be the cleanest way to do.
