### ISSUE TITLE
Compactor/Store: Thanos Store memory consumption keeps increasing, might be due to block compaction / deletion not behaving as expected

### ISSUE THREAD

**Issue by Janesee3** [thanos-io/thanos#5211]
**Thanos, Prometheus and Golang version used**: 
```
thanos, version 0.22.0 (branch: HEAD, revision: 3656e290c8eb034e2e09e0afc79f087be88de481)
  build user:       circleci@d99a55512da0
  build date:       20210721-15:34:46
  go version:       go1.16.6
  platform:         linux/amd64
```

**Object Storage Provider**: AWS S3

**What happened**:
I've been running the Thanos setup for around 1.5years now across multiple environments. Each environment has its own set of Prometheus, Thanos stack and S3, but the setup is identical. Recently, it has come to my attention that the **memory usage of Thanos Store in some environments has been steadily increasing over the months** and it is concerning.

I inspected the web UI for the Thanos Store component in one of my envs (lets call this **Environment A**), and noticed that there is a large number of `resolution: 0` blocks, spanning from May 2021 till now, which is almost a year (see blue blocks below). The memory usage of Thanos Store in this component stands at **around 12-13GB now, up from 10GB earlier this year**.

![Screenshot 2022-03-03 at 9 51 54 AM](https://user-images.githubusercontent.com/13880404/156683302-16613a12-fabd-417e-b8d2-d7bfd5126395.png)

In another environment, **Environment B** (similar setup, but same compaction / retention settings), the number of `resolution: 0` blocks are much lesser, spanning only from Sep 2021 till now. However, even though in this environment, Thanos Store consumes about an average of 6GB memory now, its memory consumption was also increasing steadily over the past 3 months, from low 5GB to now high 6GB.

![Screenshot 2022-03-03 at 9 52 15 AM](https://user-images.githubusercontent.com/13880404/156683409-5974797c-df04-4700-ba9b-98a8ac33e6e4.png)

My suspicion is that because of the build up of `resolution: 0` blocks, Thanos Store's memory usage increases. 

**What you expected to happen**:

1. With the same compaction and retention settings across environments, I expected the block distribution (eg. number of `resolution: 0` blocks) to be the same. However, it looks like both Environment A and B (named above) have different distribution. 
2. I expect that the memory usage of the Thanos Store component to stay at a steady state since we do delete metrics. With the following Compactor settings, I'd have expected that there should only be 3 months' worth of `resolution: 0` blocks in both environments:
```
    - --log.level=info
    - --log.format=json
    - --http-address=0.0.0.0:10902
    - --objstore.config-file=/etc/config/object-store.yaml
    - --data-dir=/var/thanos/compact
    - --consistency-delay=30m
    - --retention.resolution-raw=30d
    - --retention.resolution-5m=120d
    - --retention.resolution-1h=1y
    - --block-sync-concurrency=20
    - --compact.concurrency=2
    - --wait
```

**Anything else we need to know**:
- Thanos Compact is running fine in both environments, with no error logs in the past 90 days.
- Might not be too relevant but I have 4-6 Prometheus instances sending metrics to Thanos / S3. 
- In each environment, I'm running 2 Thanos Store replicas (pods) and a single Thanos Compact pod.

**Comment by hanjm** [comment]
1. So many `resolution: 0` blocks, Seems Thanos compact does not work as expected.  Could you inspect `thanos_compact_halted{}` metrics and reply to the issue? if the Thanos compactor stop working this metric will be set to 1.
2. Could you help dump a heap profile of Thanos-Store and reply to the issue? (`go tool pprof thanos-store-ip: 10902/debug/pprof/heap`)
   My initial analysis is Thanos-Store will mmap the binary-index by default, so the memory consumed will be increased if blocks count growly, you can try two ways to optimize it. 
 - Add a flag `--store.enable-index-header-lazy-reader` to Thanos-Store, it will only mmap index on need.
 - Shard by time https://thanos.io/tip/components/store.md/#time-based-partitioning.

**Comment by Janesee3** [comment]
Thanks for the reply @hanjm 

Here is what I found based on your suggestions: 

1. Looks like the Thanos Compactor has indeed halted on both of my environments. To be exact, for **env A it has halted since 1st May 2021**, and for **env B it halted since 20th Sept 2021**. 
* Unfortunately, my system's log storage deletes logs older than 3 months so I wouldn't be able to tell what happened.
* I have yet to follow this documentation (https://github.com/thanos-io/thanos/blob/main/docs/operating/troubleshooting.md#overlaps), but I will try to resolve the overlap block issues and update on this issue again.

2. Here's the heap profile for Thanos Store in **environment A**:
```
File: thanos
Type: inuse_space
Time: Mar 7, 2022 at 10:10am (+08)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 3941.35MB, 93.56% of 4212.49MB total
Dropped 258 nodes (cum <= 21.06MB)
Showing top 10 nodes out of 48
      flat  flat%   sum%        cum   cum%
 1960.29MB 46.54% 46.54%  1960.29MB 46.54%  github.com/prometheus/prometheus/tsdb/encoding.(*Decbuf).UvarintStr (inline)
 1286.30MB 30.54% 77.07%  3783.64MB 89.82%  github.com/thanos-io/thanos/pkg/block/indexheader.newFileBinaryReader
  419.50MB  9.96% 87.03%   419.50MB  9.96%  github.com/thanos-io/thanos/pkg/block/indexheader.newFileBinaryReader.func3
  114.79MB  2.72% 89.75%   114.79MB  2.72%  github.com/prometheus/prometheus/tsdb/index.NewSymbols
   67.76MB  1.61% 91.36%    67.76MB  1.61%  bufio.NewReaderSize (inline)
   45.56MB  1.08% 92.44%    45.56MB  1.08%  bytes.makeSlice
   24.09MB  0.57% 93.02%    24.09MB  0.57%  bufio.NewWriterSize (inline)
   11.01MB  0.26% 93.28%    87.56MB  2.08%  github.com/minio/minio-go/v7.Client.dumpHTTP
       7MB  0.17% 93.44%    58.19MB  1.38%  net/http.(*Transport).dialConn
    5.05MB  0.12% 93.56%    29.90MB  0.71%  github.com/thanos-io/thanos/pkg/block.(*MetaFetcher).Fetch
(pprof)
```

* Ok, I'll try adding the `--store.enable-index-header-lazy-reader` flag. I think we'll have to fix the Compactor issue first before moving on to optimise Thanos Store.

**Comment by hanjm** [comment]
@Janesee3  For the first point, Just reboot the Thanos-Compactor, It will restart the compact progress and may reproduce the issue, then we could catch the error log.

**Comment by Janesee3** [comment]
Thanks @hanjm, I'm trying this out in my environments now and Compactor is beginning to slowly clear the backlogs of blocks to compact. It looks like it will take a few days for it to catch up (attached screenshot of blocks compaction below for Environment A). 

![image](https://user-images.githubusercontent.com/13880404/157223180-bac685cd-71f6-4d51-9315-035faac9ff79.png)


Thanks for your help, I will monitor my system's memory usage after the compaction is completed and update the issue with the conclusion.

**Comment by Janesee3** [comment]
**Update:** After resuming compaction for about a week, Thanos Store memory usage in most of my environments has dropped drastically. For example, Environment A Thanos Store memory usage dropped from 12Gb -> 2Gb! 

However, one of my environment is experiencing an issue where **Thanos Compact keeps running out of disk space** while compacting despite me increasing it from 100Gi -> 300Gi. I'm using EBS persistent storage for the Thanos Compact pod. The fact that even 300Gi is insufficient makes me suspect something else must be wrong. 

What are some other ways I can debug the disk space issue with Thanos Compact? I tried to calculate the amount of disk space I should allocate to Thanos Compact (following [thanos docs](https://github.com/thanos-io/thanos/blob/main/docs/components/compact.md#disk) and this [user's suggestion](https://www.reddit.com/r/kubernetes/comments/koyys3/comment/ghul7wr/?utm_source=share&utm_medium=web2x&context=3)), but I got some oddly small number. 

Here's the number of samples ingested per second that my system ingests in a day
![Screenshot 2022-03-15 at 7 02 46 PM](https://user-images.githubusercontent.com/13880404/158366970-026445ca-f925-49ab-a906-6c29c7523508.png)

Not sure if this is helpful but it looks like only around 30 - 50Gb of space is used when I inspect the `/var/thanos/compact` folder which is mounted as an EBS volume.
![image](https://user-images.githubusercontent.com/13880404/158367530-ed03c11e-35c5-4775-adaf-76352b9f2173.png)

**Comment by Janesee3** [comment]
In my production environment, I'm seeing a different kind of compaction error. It looks like some of the blocks within a compaction group are corrupted. 

![Screenshot 2022-03-18 at 10 05 14 AM](https://user-images.githubusercontent.com/13880404/159390156-90e9ea75-7633-4ca0-a9be-a8253e1b7d77.png)

After investigating each of the block on S3 in the error message, I noticed some of them are missing the `chunks` folder. I suppose if we delete these corrupted blocks (those without the `chunks` folder), the error should go away? I think my issue is similar to this other issue - https://github.com/thanos-io/thanos/issues/4296
