### ISSUE TITLE
Stateless Rule: Rollout - Alert For State is lost across restart - Blinking alerts

### ISSUE THREAD

**Issue by ahurtaud** [thanos-io/thanos#5219]
**Thanos, Prometheus and Golang version used**:
thanos v0.25

**What happened**:

I implemented the stateless mode for the rule component.
When my rulers (k8s deployments) rollouts, every alerts already firing before the rollouts with a long `for` clause (lets say 30minutes) will be in Pending for that amount of time and firing again after 30minutes.

And because of our alertmanager config, alerts are `resolved` after 5minutes...

**What you expected to happen**:

I would like the alerts to still have a state for the `for` clause, maybe with ALERT_FOR_STATE metrics sent to the receivers?

Is it a valid issue? Is there anything I misunderstood / Do others have same issue?

Thanks

**Comment by yeya24** [comment]
If I understand correctly, in Prometheus, the state persistence across restart is by checking `ALERTS_FOR_STATE` time series. As mentioned by https://ganeshvernekar.com/blog/google-summer-of-code-2018-with-prometheus#1-persist-for-state-of-alerts-1.

I need to double check if this mode supports this by using the upstream rule manager. And we need more E2E tests to verify this.

**Comment by yeya24** [comment]
Yeah, I can confirm this is a bug. Working on the fix and tests now.

**Comment by ahurtaud** [comment]
Yeah I know this will not be an as "easy as it looks" hence creating directly a github issue.
I think it is fair to agree that ALERT_FOR_STATE must be queryable through the same query endpoint. 
(meaning stateless ruler MUST remote_write to thanos receive (or other) and register it in the query path of that ruler.)
 
From what I read from Ganesh, When ruler restarts, it queries ALERT_FOR_STATE for each alertname, and applies the same state if found:
something like that:
![Screen Shot 2022-03-08 at 09 56 24](https://user-images.githubusercontent.com/25080995/157202378-0c98b99c-10be-4104-9d53-ed12b20b4ad0.png)
![Screen Shot 2022-03-08 at 09 56 18](https://user-images.githubusercontent.com/25080995/157202364-1786d777-aaa8-4a10-a4e0-60f0da4b23ad.png)

WDYT?

**Comment by yeya24** [comment]
Yeah, i think that's correct. Right now we just need to implement the Querier interface for Thanos Querier so that we can fetch that time series from it.

**Comment by yeya24** [comment]
Created https://github.com/prometheus/prometheus/pull/10443 on upstream prometheus to address one of the issue. After that one is merged then I can open the pr to fix this.

**Comment by ahurtaud** [comment]
referencing https://github.com/thanos-io/thanos/pull/5230 for implementation of the fix.

**Comment by yeya24** [comment]
I will close this one as the feature was merged into main already. Let us know how the feature works
