### ISSUE TITLE
compact: panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by danielmotaleite** [thanos-io/thanos#5227]
**Thanos, Prometheus and Golang version used**:
Plain  quay.io/thanos/thanos:v0.25.0 image usage

**Object Storage Provider**:
s3

**What happened**:
thanos compact panic when after "block has no labels left, creating one" 

**What you expected to happen**:
Pick up the block and fix any problem

**How to reproduce it (as minimally and precisely as possible)**:
Can only reproduce in my setup

**Full logs to relevant components**:
<details>Logs
<p>
level=warn ts=2022-03-09T22:29:34.958833744Z caller=fetcher.go:723 msg="block has no labels left, creating one" 'replica'=deduped
level=debug ts=2022-03-09T22:29:34.959129098Z caller=fetcher.go:321 component=block.BaseFetcher msg="fetching meta data" concurrency=32
panic: assignment to entry in nil map

goroutine 304 [running]:
github.com/thanos-io/thanos/pkg/block.(*ReplicaLabelRemover).Modify(0xc00056fef0, 0x1ff5568, 0xc000b0aac0, 0xc0062f2240, 0xc000aed1c0, 0x0, 0x0)
        /home/circleci/project/pkg/block/fetcher.go:724 +0x406
github.com/thanos-io/thanos/pkg/block.(*BaseFetcher).fetch(0xc00070d9e0, 0x1ff5568, 0xc000b0aac0, 0xc000b0a7c0, 0xc000716280, 0x5, 0x5, 0xc000b0db80, 0x1, 0x1, ...)
        /home/circleci/project/pkg/block/fetcher.go:464 +0x64e
github.com/thanos-io/thanos/pkg/block.(*MetaFetcher).Fetch(0xc00070de00, 0x1ff5568, 0xc000b0aac0, 0x8, 0xc, 0x0, 0x0)
        /home/circleci/project/pkg/block/fetcher.go:497 +0x9f
github.com/thanos-io/thanos/pkg/compact.(*Syncer).SyncMetas(0xc000395880, 0x1ff5568, 0xc000b0aac0, 0x0, 0x0)
        /home/circleci/project/pkg/compact/compact.go:131 +0xac
github.com/thanos-io/thanos/pkg/compact.(*BucketCompactor).Compact(0xc000b271f0, 0x1ff5568, 0xc000b0aac0, 0x0, 0x0)
        /home/circleci/project/pkg/compact/compact.go:943 +0x285
main.runCompact.func7(0xc000584d80, 0x458d29)
        /home/circleci/project/cmd/thanos/compact.go:393 +0xf1
main.runCompact.func8.1(0x45d964b800, 0xc000244e60)
        /home/circleci/project/cmd/thanos/compact.go:448 +0x5c
github.com/thanos-io/thanos/pkg/runutil.Repeat(0x45d964b800, 0xc000b357a0, 0xc000213f08, 0x0, 0x0)
        /home/circleci/project/pkg/runutil/runutil.go:75 +0x88
main.runCompact.func8(0x0, 0x0)
        /home/circleci/project/cmd/thanos/compact.go:447 +0x1ff
github.com/oklog/run.(*Group).Run.func1(0xc0000c92c0, 0xc0007169b0, 0xc00064c390)
        /home/circleci/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38 +0x27
created by github.com/oklog/run.(*Group).Run
        /home/circleci/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:37 +0xbb

</p>
</details>

**Anything else we need to know**:

looks like it is the same issue as https://github.com/thanos-io/thanos/issues/2975 , probably the fix was reverted in some way

**Comment by danielmotaleite** [comment]
actually i'm not so sure now that i was using 0.25.0, i requested a update from 0.21.1 to 0.25.0, but as it is now working, maybe i checked the logs from a pod still in v0.21.1
right now, in a confirmed v0.25.0 pod, it is not giving the error anymore

**Comment by yeya24** [comment]
Cool. So looks like this is an old bug. Can we close it now?

**Comment by danielmotaleite** [comment]
yes, closing, compact have been running since without any new error, so it was something fixed between 0.21.1 and 0.25.0
thanks for the help and thanos
