### ISSUE TITLE
Shipper: select series from blocks to upload

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#5235]
### Is your proposal related to a problem?

context: https://cloud-native.slack.com/archives/CK5RSSC10/p1647331478693149

The main request is to select only required serieses and upload them to the object storage. This enables dropping high cardinality series earlier before they are persistent to the object storage, avoiding running bucket rewrite tool later, which saves more operational cost.

### Describe the solution you'd like

Basically just add a hook to shipper. When there is a new block created, shipper will do a local compaction (or rewrite) for that block and creates a new block with the series we want to keep. Then upload the new block.

For series processing, I recommend using the relabel config format so that not only series selection but also more actions can be used.

### Additional context

With adding this feature, the sidecar will be heavier, and more computation needed. Ideally this compaction post processing step can be added directly into Prometheus as a hook to avoid running it in the sidecar for duplicate computation.

**Comment by fpetkovski** [comment]
Another alternative would be to apply relabeling during the compaction process.

**Comment by yeya24** [comment]
I think we can do both.
Sidecars and compactors sometimes are controlled by different teams. Sidecar is on the client side and compactor is another side.

To do this on the compaction, I hope we can support the modifiers approach or something similar on upstream TSDB.

**Comment by yeya24** [comment]
> Ideally this compaction post processing step can be added directly into Prometheus as a hook to avoid running it in the sidecar for duplicate computation.

I think this is still the right way to go rather than doing this in the sidecar.

**Comment by snuggie12** [comment]
If done on the sidecar as relabeling, would this also include #4640 ? I still have a lot of extraneous external labels that clutters up logs, tools, etc.

For compactor side, would it be wasteful/taxing to attempt to remove series if it was already removed on the 2-hour block level? I think when I've done rewrites on 2-week blocks it takes a very long time even if the metrics don't exist. Would it be enforced only on uncompacted blocks or all levels or configurable?

**Comment by yeya24** [comment]
> If done on the sidecar as relabeling, would this also include https://github.com/thanos-io/thanos/issues/4640 ? I still have a lot of extraneous external labels that clutters up logs, tools, etc.

Doing this on the sidecar means bringing compaction and TSDB to the sidecar. The sidecar will consume more resources and might impact the read performance. It is totally doable I think and the thing is whether we want to support it or not.

I still hope that Prometheus can support compaction time relabeling so that when the TSDB generates the 2h block it filters out the unnecessary series, which covers your use case.

**Comment by yeya24** [comment]
Close as discussed, shipper is not suitable for this work.
