### ISSUE TITLE
querier: Unexpected high heap usage for Targets API 

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#5257]
At one customer's setup, we found pretty high heap usage of the structure I would not expect (errors of target API?). 7GB allocated by what looks like bookkeeping target warnings looks suspicious.

See heap profile (https://share.polarsignals.com/6b0ae0c/) -  make sure to use the `inuse_alloc` option to see the full picture at the used bytes on the heap in the moment of profile snapshot.

Internal investigation: https://bugzilla.redhat.com/show_bug.cgi?id=2055305

**Comment by bwplotka** [comment]
Initially `inuse` looks either like some leak in target warnings errors, or literally, all requests have a large number of errors:

![image](https://user-images.githubusercontent.com/6950331/160931263-a10e674d-278a-4452-9649-6a0bd95b888f.png)

This is quite insane, we see that somehow our code did `errors.New` [here](https://github.com/thanos-io/thanos/blob/0e714dc98eadfe4e8c2cda1fa0e95669f9d5c4d0/pkg/targets/targets.go#L196) 16 million times and never cleaned those. 

![image](https://user-images.githubusercontent.com/6950331/160932988-3d0cb4fd-a324-457c-9b47-82de4831be33.png)

So unless all target requests in this process got 16 million warnings from the sidecar, we have to have a leak. `resp` goes outside of the scope in the same function:

![image](https://user-images.githubusercontent.com/6950331/160933872-58f5dfd8-57b0-45cb-ad17-df2714bdebf4.png)

But `resp.warning` is passed further. Warnings are not saved anywhere for long.

![image](https://user-images.githubusercontent.com/6950331/160934096-84831cab-df71-4b81-ac1a-468232410737.png)

So two things may happen:

1. I missed someplace where warnings were kept and never released by GC
2. Sidecar has a bug (or actually there were that many warnings) in Target handler

**Comment by bwplotka** [comment]
2 is impossible - we never send warning in current code of sidecar: https://github.com/thanos-io/thanos/blob/de0e3848ff6085acf89a5f77e053c555a2cce550/pkg/targets/prometheus.go#L35

**Comment by bwplotka** [comment]
Looking on the goroutines list we got from customer I see:

2 goroutines running `func (s *Proxy) Targets(`  (two waiting on `for resp := range respChan {` one 
2 waiting on Targets errgroup 
2 in `(*targetsStream).receive(` (one receiving msg from client `target, err := targets.Recv()`, second wrapping error it got from Recv...

All acceptable other than receiving error message from one target - but it should close that receive goroutine just fine. 🤔 

Next step is to repro it locally

**Comment by bwplotka** [comment]
Can't repro easily (added tests https://github.com/thanos-io/thanos/pull/5260), so to me:

A) It was a past version bug (are we sure it's still reproducible?)
B) Somehow we discover 16 millions fake targets? (Can't see bug in code, but might be configuration error)
C) Some other Thanos implementation of TargetAPI is used than sidecar?

**Comment by hanjm** [comment]
I notice it use `Thanos-Query: 0.22.0`, i think https://github.com/thanos-io/thanos/issues/4676#issuecomment-922413448 is relevant, it has fixed by https://github.com/thanos-io/thanos/pull/4681.
