### ISSUE TITLE
Redis integration support TLSConfig

### ISSUE THREAD

**Issue by alileza** [thanos-io/thanos#5310]
### Is your proposal related to a problem?

Support TLS for redis integration

### Describe the solution you'd like

Add new Redis Client Config for tls enabled, and add TLSConfig [here](https://github.com/thanos-io/thanos/blob/main/pkg/cacheutil/redis_client.go#L149)

### Additional context

If I understand correctly currently there's no way we can connect to redis with TLS enabled

**Comment by pharaujo** [comment]
I was trying out Redis support in query-frontend using AWS ElastiCache with "encryption in transit" enabled and also ran into this problem.

**Comment by pharaujo** [comment]
I believe this is still needed
