### ISSUE TITLE
Fix or Remove blog reference

### ISSUE THREAD

**Issue by wiardvanrij** [thanos-io/thanos#5316]
In our docs we have a link and this is now failing:

```
error: 		docs/getting-started.md:125: "https://improbable.io/games/blog/thanos-prometheus-at-scale" not accessible even after retry; status code 0: Get "https://ims.improbable.io/insights": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

A quick view, and it seems to be moved/gone. Either update the docs with the correct link or remove it (:

**Comment by jmjf** [comment]
If this is open, I'll take it.

Is [this](https://www.improbable.io/blog/thanos-prometheus-at-scale) the correct article?

**Comment by wiardvanrij** [comment]
> 

Oh, I think it is! :) nice find
