### ISSUE TITLE
Is there a proper way or order on restarting thanos components?

### ISSUE THREAD

**Issue by kimcagayat** [thanos-io/thanos#5327]
Is there a proper way or order on restarting thanos components?

Thanos-store endpoint is not showing up on thanos interface. We have below thanos components:

NAME                                                     READY   STATUS    RESTARTS   AGE
alertmanager-prometheus-prometheus-oper-alertmanager-0   2/2     Running   0          163d
busybox-deployment-86bd996c75-6n2tw                      1/1     Running   4000       166d
nginx-nginx-ingress-controller-5ddb978857-px7p9          1/1     Running   0          163d
nginx-nginx-ingress-default-backend-7565667d48-xb5vb     1/1     Running   0          166d
prometheus-grafana-69db4c9d75-qj4zt                      2/2     Running   0          97d
prometheus-kube-state-metrics-95d956569-pbh59            1/1     Running   0          161d
prometheus-msteams-9c46cc5c7-v2z5q                       1/1     Running   76         160d
prometheus-prometheus-node-exporter-6gsbw                1/1     Running   0          152d
prometheus-prometheus-node-exporter-7mkqx                1/1     Running   0          152d
prometheus-prometheus-node-exporter-f9j7h                1/1     Running   0          152d
prometheus-prometheus-node-exporter-fjcjk                1/1     Running   0          152d
prometheus-prometheus-node-exporter-k2r25                1/1     Running   0          152d
prometheus-prometheus-node-exporter-wkkmw                1/1     Running   0          152d
prometheus-prometheus-oper-operator-58cc49b8f5-gb9hr     2/2     Running   0          84d
prometheus-prometheus-prometheus-oper-prometheus-0       4/4     Running   1          98m
sleep-557747455f-s7l72                                   1/1     Running   0          166d
thanos-bucket-55f5cfd879-d6wq6                           1/1     Running   0          111d
thanos-compactor-0                                       1/1     Running   3          140d
thanos-querier-8dc7d6d6b-cq8rs                           1/1     Running   0          20h
thanos-store-0                                           1/1     Running   0          16m

thanos-store-0  keeps on restarting at not showing up on our thanos interface. Also, port 10901 is not reachable from the pod itself.

Here's a capture of node where thanos-store is using:

![image](https://user-images.githubusercontent.com/96174080/166854073-ded11628-1082-46ef-8b56-3cc4550cf953.png)

**Comment by wiardvanrij** [comment]
No, the order does not matter. But you are running in a few other problems here;
- Very old version (but that's 'okay-ish'0
- Your store gets evicted due to lack of storage
- Port 10901 is GRPC, so make sure you test it like that as well.

**Comment by kimcagayat** [comment]
Hi @wiardvanrij, appreciate you response. The initial issue I had is that. I cannot telnet port 10901 from the pod itself and from the thanos querier pod. Where do I check and how do I know if there’s anything wrong with the port? Sorry I’m kind of new to this. Thanks.

**Comment by wiardvanrij** [comment]
So I assume you are not seeing it in the UI of Thanos querier. Then I would look at those logs. 
If you need more guidance, do fill in our template ;)





**Thanos, Prometheus and Golang version used**:



**Object Storage Provider**:

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:



**Anything else we need to know**:

**Comment by kimcagayat** [comment]
**Thanos, Prometheus and Golang version used:**

Thanos Version:0.12.2, GoVersion: go1.13.1
Prometheus Version: 2.25.0, GoVersion: go1.15.8
Object Storage Provider:

**What happened:**
Thanos-Store not showing up from Thanos-Querier interface

**What you expected to happen:**
It should be showing up like on our production which has the same versions.

How to reproduce it (as minimally and precisely as possible):
![image](https://user-images.githubusercontent.com/96174080/167991159-dcb08c53-a1a6-4019-9709-3e6900aac605.png)

Full logs to relevant components:

Anything else we need to know:

**Comment by yeya24** [comment]
Due to lack of response, I will close this issue. Feel free to reopen it if you still have this issue
