### ISSUE TITLE
query: component stuck/stalled + goroutines > 10k + hit max concurrent queries

### ISSUE THREAD

**Issue by parkedwards** [thanos-io/thanos#5346]
**Thanos, Prometheus and Golang version used**:

```
$ thanos --version

thanos, version 0.23.0 (branch: HEAD, revision: fe0d695e8df8619f2e6588e6259230a13535001a)
  build user:       circleci@80970a8015b2
  build date:       20210927-14:57:42
  go version:       go1.16.8
  platform:         linux/amd64
```

We're using the official thanos docker image from the public registry (from `thanosio/thanos`)

**Object Storage Provider**:
S3

**What happened**:
We've been successfully running a Thanos cluster for around a year now - we've got some storegateways fronting s3, thanos sidecars on the prometheus nodes, and a query-frontend + query component (just 1x replica atm)

However, over the weekend, we ran into an issue where the `query-frontend` component (ingress to all our grafana, ruler, and developer querying) started timing out on all queries

digging further, it appears that our `query` component itself went silent for around 72 hours (silent = logs stopped, but pod was still healthy + passing health checks).  the last registered error log was over a week ago, which exceeds when we started to notice the timeouts

digging EVEN FURTHER, it appears that the `query` component got stalled - to test this, we were able to get queries running again by rebooting the `query` pod

I also noticed that, during this "outage", we saw:
* num of goroutines spike up to > 10k
* the `query` component hitting max concurrent queries, which is defaulted to 20
![image](https://user-images.githubusercontent.com/19556538/167457019-1d046002-cb01-44dd-bc1c-42013634d5d6.png)

FYI: our issue appears to have the same symptoms as the following, past issues:
https://github.com/thanos-io/thanos/issues/705
https://github.com/thanos-io/thanos/issues/4766
https://github.com/thanos-io/thanos/issues/4925
https://github.com/thanos-io/thanos/issues/5079

**What you expected to happen**:
We'd expect the `query` component to either NOT brick, or fail health checks if it does so our k8s scheduler could replace it

**How to reproduce it (as minimally and precisely as possible)**:
Not 100% sure, this appears to be somewhat symptomatic of a goroutine leak

**Full logs to relevant components**:

Can't seem to find helpful logs, since the `query` component went silent after experiencing the goroutine leak.  But here are our `query` flags, for posterity

```
    Args:
      query
      --log.level=info
      --log.format=logfmt
      --grpc-address=0.0.0.0:10901
      --http-address=0.0.0.0:10902
      --query.replica-label=prometheus_replica
      --query.replica-label=replica
      --query.replica-label=prometheus
      --store=dnssrv+_grpc._tcp.prometheus-kube-prometheus-prometheus-thanos.monitoring.svc.cluster.local
      --store=dnssrv+_grpc._tcp.thanos-storegateway-0.monitoring.svc.cluster.local
      --store=dnssrv+_grpc._tcp.thanos-storegateway-1.monitoring.svc.cluster.local
      --store=dnssrv+_grpc._tcp.thanos-storegateway-2.monitoring.svc.cluster.local
      --store=dnssrv+_grpc._tcp.thanos-ruler.monitoring.svc.cluster.local
      --store=dnssrv+_grpc._tcp.thanos-receive.monitoring.svc.cluster.local
      --store=<our prometheus DNS records>
```

**Anything else we need to know**:

**Comment by parkedwards** [comment]
hey @wiardvanrij maybe im dumb, but i can't seem to spit out a file output that the polar signals tool likes.  you mind providing me a command or two to do so? i've tried

```
curl <internal query host>/debug/pprof/goroutine -o output.pb

# or
curl <internal query host>/debug/pprof/goroutine?debug=1 -o output.pb

# or
curl <internal query host>/debug/pprof/goroutine?debug=2 -o output.pb

# and
gzip ./output.pb
```

but no dice

**Comment by GiedriusS** [comment]
Is it the same with 0.24.0 or any newer version? Wouldn't be surprised if you are running into [this](https://github.com/thanos-io/thanos/pull/4795).

**Comment by wiardvanrij** [comment]
> hey @wiardvanrij maybe im dumb, but i can't seem to spit out a file output that the polar signals tool likes. you mind providing me a command or two to do so? i've tried
> 
> ```
> curl <internal query host>/debug/pprof/goroutine -o output.pb
> 
> # or
> curl <internal query host>/debug/pprof/goroutine?debug=1 -o output.pb
> 
> # or
> curl <internal query host>/debug/pprof/goroutine?debug=2 -o output.pb
> 
> # and
> gzip ./output.pb
> ```
> 
> but no dice

The default output should be a x.pb.gz file. If you would omit the -o. So you can just do your first command and say it's foo.pb.gz

**Comment by parkedwards** [comment]
@wiardvanrij gah! so close.  here it is:
https://share.polarsignals.com/cdfe34b/

**Comment by parkedwards** [comment]
@wiardvanrij we actually just experienced this leak just now, i was able to export a pprof here

https://share.polarsignals.com/b33f04f/

**Comment by GiedriusS** [comment]
Seems like I was correct. I think you are running into https://github.com/thanos-io/thanos/pull/4795. Please try upgrading to 0.24.0 or 0.23.1.

**Comment by parkedwards** [comment]
yo @GiedriusS @wiardvanrij -- things seem quiet after bumping to `v0.24.0`.  thanks again for your help, and I can close this out

til next time!
