### ISSUE TITLE
QueryFrontend: compile regex once when matching strings

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#5349]
From code https://github.com/thanos-io/thanos/blob/main/pkg/queryfrontend/roundtrip.go#L123, we are compiling the regex every time to match strings. This can be optimized by only compiling the regex once and checking if the string matches.

```go
			matched, err := regexp.MatchString("/api/v1/label/.+/values$", r.URL.Path)
			if err == nil && matched {
				return labelValuesOp
			}
```

**Comment by sandipanpanda** [comment]
Hi, I am new to Thanos and would like to help in fixing this.

**Comment by yeya24** [comment]
Please go ahead. @sandipanpanda

**Comment by sandipanpanda** [comment]
Yes, I am working on it.

**Comment by Akshit42-hue** [comment]
Hey @jgbernalp, I would like to give it a try

**Comment by djdongjin** [comment]
I think this can be closed now. @yeya24

**Comment by yeya24** [comment]
Thanks @djdongjin.
