### ISSUE TITLE
Compactor/Store Gateway/Bucket UI: Enable finding overlapping block make frontend crash

### ISSUE THREAD

**Issue by antonincms** [thanos-io/thanos#5359]
**Thanos, Prometheus and Golang version used**:

* Thanos `quay.io/thanos/thanos:v0.25.2`
* Thanos `quay.io/thanos/thanos:v0.26.0`
* Thanos `quay.io/thanos/thanos:v0.27.0`
* ...
* Thanos `quay.io/thanos/thanos:v0.36.0`

**Object Storage Provider**:

AWS S3

**What happened**:

On the frontend using google chrome, on the loaded blocks page when ticking the `Enable finding overlapping block` ...

On google chrome I get the error 
```
TypeError: Cannot read properties of undefined (reading 'thanos')
    in t
    in L
    in j
    in x
    in j
    in div
    in h
    in n
    in Da
```

and on firefox I get : 
```
TypeError: i[0][0] is undefined
    in t
    in L
    in j
    in x
    in j
    in div
    in h
    in n
    in Da
```

**Full logs to relevant components**:

Compactor logs filtered by component=bucketUI : 
```
level=warn ts=2022-05-12T12:27:10.72680398Z caller=ui.go:204 component=bucketUI msg="Could not get file" err="AssetInfo pkg/ui/static/react/static/js/main.eec2650e.chunk.js.map not found" file=pkg/ui/static/react/static/js/main.eec2650e.chunk.js.map
level=warn ts=2022-05-12T12:27:10.68813083Z caller=ui.go:204 component=bucketUI msg="Could not get file" err="AssetInfo pkg/ui/static/react/static/js/2.f69d72f3.chunk.js.map not found" file=pkg/ui/static/react/static/js/2.f69d72f3.chunk.js.map
level=warn ts=2022-05-12T12:27:10.787708375Z caller=ui.go:204 component=bucketUI msg="Could not get file" err="AssetInfo pkg/ui/static/react/static/css/main.e128754d.chunk.css.map not found" file=pkg/ui/static/react/static/css/main.e128754d.chunk.css.map
level=warn ts=2022-05-12T12:27:10.748746088Z caller=ui.go:204 component=bucketUI msg="Could not get file" err="AssetInfo pkg/ui/static/react/static/css/2.3288c2bf.chunk.css.map not found" file=pkg/ui/static/react/static/css/2.3288c2bf.chunk.css.map
```
**Anything else we need to know**:

**Comment by pippitt** [comment]
Same issue, hopefully helpful data from chrome dev tools console
```
2.f69d72f3.chunk.js:2 TypeError: Cannot read properties of undefined (reading 'thanos')
    at main.eec2650e.chunk.js:1:142741
    at Array.map (<anonymous>)
    at main.eec2650e.chunk.js:1:142604
    at main.eec2650e.chunk.js:1:142809
    at Object.ga [as useMemo] (2.f69d72f3.chunk.js:2:1220063)
    at t.useMemo (2.f69d72f3.chunk.js:2:1157829)
    at main.eec2650e.chunk.js:1:142539
    at Jo (2.f69d72f3.chunk.js:2:1216397)
    at Wa (2.f69d72f3.chunk.js:2:1225289)
    at ws (2.f69d72f3.chunk.js:2:1263796)
```

**Comment by yeya24** [comment]
Got the same issue.
![image](https://user-images.githubusercontent.com/25150124/171452622-37108112-5935-4e01-a4cb-a6c41f793816.png)

**Comment by mfilocha** [comment]
Same for 0.26.0

**Comment by SKUndef** [comment]
+1

**Comment by shanaider** [comment]
same this error on iamge: thanos:0.27.0

**Comment by GreenRover** [comment]
+1

**Comment by matej-g** [comment]
Yeah, hit this today as well, this should not be a big issue to fix

**Comment by fredpan** [comment]
Same problem... Any solution?

**Comment by bmgante** [comment]
Same problem here. Any solution on this?

**Comment by pie-r** [comment]
Same in 0.29.0

**Comment by caoimheharvey** [comment]
Same in 0.31.0

**Comment by harsh-ps-2003** [comment]
@yeya24 @matej-g I found a similar issue in Bucket UI as well. When I click `enable finding overlapping blocks` I get this :
<img width="1280" alt="Screenshot 2023-08-06 at 11 17 52 AM" src="https://github.com/thanos-io/thanos/assets/119954739/af7fdfca-62dc-453d-9c8b-a6f227bb142d">

I am currently trying to work on this issue. See [this](https://cloud-native.slack.com/archives/CL25937SP/p1691163306346409) message on slack for more information.

**Comment by awcodify** [comment]
Any updates? 
Also happened in 0.30.2

**Comment by imgfrost** [comment]
would love this to get resolved, having a massive issue with overlapping blocks, so having a UI that would show this would be ideal.

**Comment by aslafy-z** [comment]
I implemented a potential fix at https://github.com/thanos-io/thanos/pull/6768, but have no overlapping blocks in my thanos instances. Can someone with overlapping blocks try it? @imgfrost maybe?
I pushed an amd64 docker image based on the main branch at `docker.io/zadki3l/thanos:0.32-fix-overlapping-blocks`

**Comment by hayk96** [comment]
@aslafy-z seems it's the same. Didn't work for me. I had a problem related to the overlapped blocks and couldn't find them by using the image `docker.io/zadki3l/thanos:0.32-fix-overlapping-blocks`.

**Comment by aslafy-z** [comment]
@hayk96 @wiardvanrij @imgfrost @hsolberg can you please try  again? I added the compiled source to the docker image. `docker.io/zadki3l/thanos@sha256:d11e4dfa1de67040d4fef935e7bd6340d95c00efb0b56c8e7da709b4682fb986`

**Comment by m5lapp** [comment]
Thanks @aslafy-z, I gave it a try and it does seem to detect overlapping blocks successfully:
![Screenshot 2023-11-06 at 15 25 42](https://github.com/thanos-io/thanos/assets/64704718/9ac3ddfb-2e24-4674-868f-2833fbbcdad1)

**Comment by atobaum** [comment]
same in v0.34.1

**Comment by jumakasy** [comment]
same in v.0.36.0

**Comment by pureiboi** [comment]
I have added a fix. I have tested with my object store in S3 bucket. 

Seems to be working for me.

Someone might want to verify the same

**Comment by GiedriusS** [comment]
Fixed in https://github.com/thanos-io/thanos/pull/7644

**Comment by BourgoisMickael** [comment]
I see the fix is in unreleased, could you patch as well previous versions, like make a 0.34.2
