### ISSUE TITLE
[Compact] Implement Bucket Lock on Thanos Compactor to Avoid Multiple Compactors Operating on Same Bucket

### ISSUE THREAD

**Issue by ethernoy** [thanos-io/thanos#5370]
### Is your proposal related to a problem?

Thanos compactor is not designed to be run in parallel. However, there exists a use case where a new Thanos compactor instance needs to run when there is an old compactor running, and the old instance shall terminate afterwards (imagine we are doing blue-green deployment on Thanos solution). It would be great if the new Thanos compactor instance suspends operation until there is no other active compactor running.

### Describe the solution you'd like

Let Thanos compactor put a file representing a time limited lock on the bucket when it normally starts a compaction operation. The file should contain the follwing information:

- Thanos compactor instance id
- Thanos compactor semVer
- Lock start time (should be the time when the compactor starts the current compaction operation)
- Lock end time (should be start time + a time period larger than a normal compaction operation)

When a Thanos compactor tries to start a compaction operation, it first checks whether there is such a lock file on a bucket, and only overwrites the lock file and proceeds if all of the following conditions satisfy:

- The current compactor has higher or equal version than the version in lock, **and** 
- Current time > lock end time **or** the lock is put by the current compactor

If none of the condition above satisfies, the compactor either terminates itself or sleep for a fixed period before trying again.

### Describe alternatives you've considered

N/A

### Additional context

I can submit PR if this solution is preferred.

**Comment by yeya24** [comment]
> However, there exists a use case where a new Thanos compactor instance needs to run when there is an old compactor running, and the old instance shall terminate afterwards (imagine we are doing blue-green deployment on Thanos solution).

This is a little bit weird to me because Thanos Compactor is just a cron job. It is not an online component like Thanos Query, Storage Gateway, etc. It is a component that runs totally in the background. I think blue-green deployment is unnecessary for it.

> It would be great if the new Thanos compactor instance suspends operation until there is no other active compactor running

What's your environment? Are you running k8s or something else?

**Comment by yeya24** [comment]
I think this is out of Thanos compactor's scope as it is for this usecase only. Doing blue-green deployment for the compactor is really a special usecase and ideally your CD tool should be able to exclude compactor from blue green deployment if possible. Other solution is to have an init container to wait until other compactors are terminated.

I'll close this issue for now. If there are other use cases then let me know.
