### ISSUE TITLE
Docs: Find a replacement for Katacoda.com for tutorials

### ISSUE THREAD

**Issue by matej-g** [thanos-io/thanos#5385]
Katacoda.com is officially being shutdown by 15th June: https://www.oreilly.com/online-learning/leveraging-katacoda-technology.html 

We should find an alternative provider to which we can move or (temporarily) remove Katacoda tutorials from docs.

**Comment by squat** [comment]
:( a one month warning is really short notice. Let's try to find something else for sure

**Comment by matej-g** [comment]
As a project we got an (unwritten?) offer from https://instruqt.com/ which is kind of a similar platform, although this would be free only for 1000 user hours, so it would not be a permanent solution. Either way, it's one of a readily available alternatives, even if just to bridge us to a permanent solution.

**Comment by matej-g** [comment]
Another alternative @saswatamcode found: https://killercoda.com, which seem to have a more generous free tier.

**Comment by saswatamcode** [comment]
Seems like this is causing a lot of trouble: https://github.com/kubernetes/website/issues/33936

**Comment by matej-g** [comment]
Yep, I'd say let's agree on an alternative (Killercoda is the winner for me right now) and I'll take care of porting to the new provider.

**Comment by bwplotka** [comment]
Referenced our issues publically https://twitter.com/bwplotka/status/1531291197649694732

**Comment by ebauman** [comment]
Hey folks, I'm the lead dev for HobbyFarm (https://github.com/hobbyfarm/hobbyfarm), a browser-based learning tool created to address this need. I'd love to toss our hat into the ring as a solution you could look at using!

**Comment by wuestkamp** [comment]
hey @matej-g, just reach out to us on https://killercoda.com/support and we check your crashing environments. We also provide larger environments for open source projects.

**Comment by matej-g** [comment]
Thanks @wuestkamp for the tip, I'll take a look at support :+1:

**Comment by squat** [comment]
Big thanks to @Akshit42-hue for your work on porting the Thanos tutorials to work on Killercoda! I made a new GH repo today that hosts the tutorials: https://github.com/thanos-io/tutorials
Tomorrow I'll try to finish setting up our Killercoda account

**Comment by wuestkamp** [comment]
Would you be ok if we feature https://killercoda.com/thanos-tutorials on the Killercoda main page?

**Comment by Akshit42-hue** [comment]
> Would you be ok if we feature https://killercoda.com/thanos-tutorials on the Killercoda main page?
+1 From my side
WDYT // @matej-g @squat @bwplotka

**Comment by matej-g** [comment]
@squat did you manage to finalize the creation of the account etc.? That account link https://killercoda.com/thanos-tutorials actually leads to the account I was testing with, so it does not include the latest or 'official' scenario versions (since it points to my fork).

But happy to hand it over to @squat so we can keep the nice URL.

**Comment by matej-g** [comment]
It took a bit but we're finally there, thanks for all the assistance @wuestkamp!

The tutorials are now live under https://killercoda.com/thanos (if you'd still like to feature them on the main page, we're all for it :heart:).

**Comment by wuestkamp** [comment]
We linked Thanos on the Killercoda main page! Nice work everyone :)
