### ISSUE TITLE
Provide option to disable block mark deletion and mark no compaction from bucket UI

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#5390]
In Prometheus, admin level functionalities like delete series are not provided through UI.
But in Thanos, now it is supported to mark deletion and mark no compaction from bucket UI. This is an admin-level operation and requires admin permissions. Some users might not want to expose those functionalities from bucket UI to their users.

We can have an option to disable those functionalities from UI or make those features not enabled by default.

**Comment by yeya24** [comment]
Still valid

**Comment by Vaani-pathariya** [comment]
hello @yeya24 i am new to thanos but i would love to work on this issue . also i new to devops as well , so can you suggest some me some resources to get to understand the project more . Since long , i have been working on react so i think i can work on the issue

**Comment by yeya24** [comment]
@Vaani-pathariya https://thanos.io/tip/thanos/quick-tutorial.md/ is a great resource to start.
This issue doesn't require much knowledge about Thanos. Some UI/backend knowledge is good enough.

**Comment by harsh-ps-2003** [comment]
<img width="1280" alt="Screenshot 2023-08-06 at 10 45 33 AM" src="https://github.com/thanos-io/thanos/assets/119954739/08684e8f-55df-4124-9020-964f372d9af5">

@yeya24 I far as I can understand, do you want a checkbox to disable block mark deletion and mark no compaction separately or together. Also can you clarify where exactly do you want it.
If nobody else is working on the issue I can give it a try!!

**Comment by yeya24** [comment]
@harsh-ps-2003 I think we want a new flag to disable this functionality. When the flag is set, users shouldn't be able to add markers in the UI.
I don't think we need to add any checkbox in the UI itself
