### ISSUE TITLE
Use original Minio upstream for Minio client

### ISSUE THREAD

**Issue by B0go** [thanos-io/thanos#5393]
Issue https://github.com/thanos-io/thanos/issues/5130 reports two problems, the incompatibility between the local development Minio version and Apple silicon and the need to go back to using Minio's upstream instead of a fork. We opted to keep that issue focused on the local development and create a new one to return to the upstream because this second part is way more complicated.

The context why Thanos is now using a fork of Minio's client can be found here: https://github.com/thanos-io/thanos/issues/3967

@wiardvanrij also provided this example of problems related to using the fork: https://github.com/thanos-io/thanos/issues/5101

To return using the upstream, we need to figure out how to solve the race condition problem stated in the original task (prior to migrating to the fork) so we can help Minio team and move back to the original repository

**Comment by bwplotka** [comment]
Are you planning to help here, otherwise I might have time to fix it. We can get back to upstream with config option mentioned https://github.com/minio/mc/issues/3376#issuecomment-806013131 or we can propose fix to upstream

**Comment by B0go** [comment]
I do plan on helping with other Thanos issues, but I believe you have more context to address this one @bwplotka :)

**Comment by oded-dd** [comment]
Hey, Any update on that? IMDSv2 is a security requirement, hence, we can not leave those hanging fruits

**Comment by markmsmith** [comment]
I believe this can be closed, as it was resolved as part of https://github.com/thanos-io/thanos/issues/5101 .
We are successfully using IMDSv2 with Thanos in our environment.
