### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by Akshit42-hue** [thanos-io/thanos#5397]
**What happened**:
In the https://thanos.io/v0.1/thanos/getting-started.md/#all-in-one-example page while clicking on "here" the "Page Not Found"
error pops-up  same with [dashboards](https://thanos.io/v0.1/thanos/getting-started.md/#dashboards) and [alerts](https://thanos.io/v0.1/thanos/getting-started.md/#alerts)

**Comment by matej-g** [comment]
I think that's because that is a very outdated documentation (for `v0.1`), I don't think it makes sense fixing this since the links, docs etc. might not exist anymore. I'd suggest closing this rather.
