### ISSUE TITLE
Error when reloading file

### ISSUE THREAD

**Issue by xiexg** [thanos-io/thanos#5403]
Hello,
When I updated the prometheus rule file, the sidecar container printed an error message and I'm not modifying this file
![image](https://user-images.githubusercontent.com/50699734/171548997-c88ac107-c945-46e6-b363-3ea6888f0ad0.png)

Version:
- thanos 0.25.1
- kubernetes v1.18.4

**Comment by xiexg** [comment]
hello @matej-g, 
- This is my rule files, mount to the sidecar container as configMap volume, Directory is "/config/prometheus/rules"

![image](https://user-images.githubusercontent.com/50699734/172748909-0ec583b4-073d-4850-99ff-9566630614e1.png)

1. When I update yz_pod_alerts.yml files, the error comes from yz_etcd_alerts.yml file, but it does not affect yz_pod_alerts.yml file update

![image](https://user-images.githubusercontent.com/50699734/172750527-1c70fc45-53b4-4542-8dac-6abf0e40c738.png)

2. I want to know what causes it. Is this related to the soft link of the file?

**Looking forward to your reply, thanks**

**Comment by matej-g** [comment]
Not sure, AFAIK we should be following symlinks, looking [at the code](https://github.com/thanos-io/thanos/blob/main/pkg/reloader/reloader.go#L333).

I'm not sure how exactly you provision those rule files, but maybe there's something strange. Is that a full output? Looking at the directory name, it contains `rules/..2022_<etc>`, which seems strange, maybe a missing slash?

**Comment by xiexg** [comment]
I modified the "--reloader.rule-dir" parameter, from "/config/prometheus/rules" to "/config/prometheus/rules/", it solved my problem
However, I don’t understand the meaning of slash. What is the difference between slash and missing slash?

**Comment by matej-g** [comment]
Hm that is curious, the slash at the end should not make a difference as far as I can tell (and I'm not sure if that's what helped fixing your case). But if this works for you now we can close this issue :+1:.

**Comment by xiexg** [comment]
Ok, I will close this issue, thank you
