### ISSUE TITLE
store gateway一直在加载数据，无法启动

### ISSUE THREAD

**Issue by whc9527** [thanos-io/thanos#5406]
部署方式: 容器化部署
Thanos版本: quay.io/thanos/thanos:v0.24.0

公司的Metrics是存储在S3上的，通过Thanos Store组件来进行查询，数据量很大.
![image](https://user-images.githubusercontent.com/17898805/172119412-07792347-eed6-4a92-b3ad-d4932ece4ea7.png)

thanos store的启动参数
`
      - args:
        - store
        - --log.level=info
        - --log.format=logfmt
        - --data-dir=/var/thanos/store
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --objstore.config=$(OBJSTORE_CONFIG)
        - --ignore-deletion-marks-delay=24h
`
```
snow@snowdeMacBook-Pro faxing % k -n hawkeye logs -f thanos-store-0
......
level=info ts=2022-06-06T02:42:49.179917755Z caller=bucket.go:574 msg="loaded new block" elapsed=13.156809847s id=01FX493XX5YKJ8FHCP9JHTWZ8W
level=info ts=2022-06-06T02:42:49.237509797Z caller=bucket.go:574 msg="loaded new block" elapsed=13.260538912s id=01FTFA06XKNHXDJEGAGKW69814
level=info ts=2022-06-06T02:42:49.264018479Z caller=bucket.go:574 msg="loaded new block" elapsed=13.325067012s id=01FT57925QRQN9DV0MYTJAKNE7
......
```

哪位大牛可以帮忙看下这个问题不，目前已经加载了4个多小时的数据了，但POD依然没有启动，非常感谢!!

**Comment by yeya24** [comment]
You can try to shard your store gateway using time sharding or hash sharding.

**Comment by whc9527** [comment]
> You can try to shard your store gateway using time sharding or hash sharding.

@yeya24 
大佬，time sharding这个我有了解，是通过--min-time/--max-time来切，hash sharding这个功能我只在receiver组件做集群的时候用到过，请教下在store里这个功能有啥文档可以参考的吗？感谢了

**Comment by yeya24** [comment]
@whc9527 https://thanos.io/tip/thanos/sharding.md/#relabelling would be a good example

**Comment by whc9527** [comment]
> @whc9527 https://thanos.io/tip/thanos/sharding.md/#relabelling would be a good example
@yeya24 
非常感谢，豁然了，我看下咋搞
