### ISSUE TITLE
Add configurable parallelism to objstore.DownloadDir and objstore.UploadDir

### ISSUE THREAD

**Issue by gburek-fastly** [thanos-io/thanos#5414]
Our environment has large blocks that are comprised of many chunks: 
```
512 MiB      gs://-/01G53KK11WRQTSM7M2W1217H5H/chunks/002371
512 MiB      gs://-/01G53KK11WRQTSM7M2W1217H5H/chunks/002372
512 MiB      gs://-/01G53KK11WRQTSM7M2W1217H5H/chunks/002373
187.95 MiB   gs://-/01G53KK11WRQTSM7M2W1217H5H/chunks/002374
1.16 TiB     gs://-/01G53KK11WRQTSM7M2W1217H5H/chunks/
1.18 TiB     gs://-/01G53KK11WRQTSM7M2W1217H5H/
```

They are slow to upload and download:
```
"duration":"5h40m44.011902037s","msg":"downloaded and verified blocks; compacting blocks"
...
"duration":"8h9m20.598265105s","msg":"uploaded block"
```

It appears that thanos [iterates through a bucket](https://github.com/thanos-io/thanos/blob/main/pkg/objstore/objstore.go#L263) and downloads these files sequentially and it does [the same for uploading them](https://github.com/thanos-io/thanos/blob/main/pkg/objstore/objstore.go#L183). 

It would be a huge performance boost for compact nodes to be able to concurrently upload and download the individual objects that a block is comprised of.

**Comment by kakkoyun** [comment]
This is fixed by https://github.com/thanos-io/thanos/pull/5475
