### ISSUE TITLE
Receive: Allow specifying tenant-specific external labels

### ISSUE THREAD

**Issue by fpetkovski** [thanos-io/thanos#5434]
### Is your proposal related to a problem?

We would like to partition and select tenant blocks from Receivers in an arbitrary manner.

### Describe the solution you'd like

I would like to be able to add additional external labels to tenants created in Thanos Receivers. 
Currently it is only possible to add external labels to Receivers directly, but not to individual tenants created in those Receivers. Having a header like `THANOS-TENANT-LABELS` that will set external labels when the tenant TSDB is created could be a possible solution.

### Describe alternatives you've considered

Running tenant-specific Prometheus instances, but that can be hard to manage at a larger scale.

**Comment by squat** [comment]
I think this make a lot of sense. It's also something that could integrate pretty naturally into the tenant configuration file. If this were the path, we might want to change to yaml for the configuration so we can more naturally mirror a prometheus relabel-config.

**Comment by hamees-sayed** [comment]
Hello, I'm interested in contributing to this project as a part of lfx mentorship program. Any related PR or docs I can check out to get started?

**Comment by ahsenkamal** [comment]
Hey folks, came here from the LFX mentorship projects and I'd like to contribute to this. Any help on where to get started?

**Comment by rajivharlalka** [comment]
I was going through the coed base and  wanted to understand more on how multi-tenancy is currently achieved in Thanos as it wasn't very much clear with the docs as well.It would be great if I may get some relevant blogs/papers as related to what currently is implemented. Thanks in advance.

**Comment by sharadgaur** [comment]
> Hey folks, came here from the LFX mentorship projects and I'd like to contribute to this. Any help on where to get started?

I think you can start from adding external labels to hashring config [here](https://github.com/thanos-io/thanos/blob/main/pkg/receive/config.go#L44). Currently, its only support tenant name as external label value for [tenant-label-name](https://github.com/thanos-io/thanos/blob/main/cmd/thanos/receive.go#L835) command line flag.

**Comment by haanhvu** [comment]
@saswatamcode @fpetkovski PR #5777 only does the main parts of the proposal #5720 Should we create an issue to track doing the remaining parts, before moving the proposal to `proposals-done`?
