### ISSUE TITLE
Thanos Compact not downsampling to 1h resolution

### ISSUE THREAD

**Issue by PowerSurj** [thanos-io/thanos#5435]
**Thanos, Prometheus and Golang version used**:

thanos, version 0.27.0 (branch: HEAD, revision: f68bb366d18557a5347e6b38013f363ad5be05a4)
  build user:       root@708554d4fa46
  build date:       20220705-14:57:42
  go version:       go1.17.11
  platform:         linux/amd64

**Object Storage Provider**:
Azure

**What happened**:

When i check the existing blocks resolutions, i can only see 5min downsampling the furthest.
There are no downsampled blocks for 1h.

This leads to early undesired block deletions as we run Thanos Compact with arguments ` --retention.resolution-raw=40h --retention.resolution-5m=10d --retention.resolution-1h=55d`
Data blocks get deleted on 10d mark

**What you expected to happen**:

Blocks to be downsampled to 1h resolution before they are deleted by `--retention.resolution-5m` imposed interval.

**How to reproduce it (as minimally and precisely as possible)**:

Thanos Compact POD arguments:
`compact --wait --log.level=debug --log.format=json --objstore.config=$(OBJSTORE_CONFIG) --data-dir=/var/thanos/compact --debug.accept-malformed-index --retention.resolution-raw=40h --retention.resolution-5m=10d --retention.resolution-1h=365d --delete-delay=48h --consistency-delay=30m --deduplication.replica-label=prometheus_replica --deduplication.replica-label=rule_replica`

**Full logs to relevant components**:

I did not find errors in the logs relate to downsampling

**Environment**:
We use only one Thanos Compact as per recommendations.
We also have Thanos Sidecar container for Prometheus POD and Thanos Store POD

**Comment by yeya24** [comment]
In order to downsample 1h blocks, block with 10d time range is required. Did you see your 5m downsampled blocks got deleted even if the time range is larger than 10d?

**Comment by PowerSurj** [comment]
We observe exactly that. The 5m blocks don't get compacted to 1h blocks and all those 5m blocks get deleted after 10d.

**Comment by yeya24** [comment]
What I mean is that the 5m block needs to be compacted to at least 10d time range long. Not 10d after its creation time.

If your block is not large enough then it won't be downsampled to 1h block

**Comment by PowerSurj** [comment]
Alright, thanks for the hint.  I will try higher value for the `--retention.resolution-5m`.
FYI, looking at my current block i do have 10 days worth 5m blocks.

Oldest 5m block resolution Start Time: August 18, 2022 1:00 AM
Recent 5m block resolution End Time: August 28, 2022 1:00 AM

![Screen Shot 2022-08-29 at 19 44 31](https://user-images.githubusercontent.com/52036509/187254565-57df087a-8784-4f87-ba56-fd57d8029e9c.png)

**Comment by PowerSurj** [comment]
I tested with retention.resolution-5m=12d just giving it a bit more time and still no luck.
Still not having 1h retention blocks produced.

**Comment by yeya24** [comment]
> looking at my 5m blocks, there is a 10 days worth contiguous time range

You need to have each single 5m block larger than 10d duration to get it downsampled to 1h resolution. Not multiple 5m blocks time duration combined.

The source code is here https://github.com/thanos-io/thanos/blob/main/cmd/thanos/downsample.go#L306.

For the default compaction level settings https://github.com/thanos-io/thanos/blob/main/cmd/thanos/compact.go#L56, compaction level 4 block has 2d duration and level 5 block has 14d duration. So in order to get a block that is at least 10d duration large you need to make sure it gets compacted to level 5. I would say you could try 5m block retention > 14d to see if it works for you.

**Comment by PowerSurj** [comment]
I'll have to test this, yet.
@yeya24 do you mind giving an example of proposed configuration?
If I get it correctly, I just have to further increase the retention.resolution values.

**Comment by PowerSurj** [comment]
That fixed it! Thank you!
