### ISSUE TITLE
ThanosSidecarPrometheusDown error no metrics thanos_objstore_bucket_operation_failures_total

### ISSUE THREAD

**Issue by Alexvianet** [thanos-io/thanos#544]
ThanosSidecar do not provide thanos_objstore_bucket_operation_failures_total by 

https://github.com/improbable-eng/thanos/blob/master/examples/alerts/alerts.md
- alert: ThanosSidecarBucketOperationsFailed
is not working

steps to reproduce:
curl http://ThanosSidecarIP:10902/metric

**Comment by GiedriusS** [comment]
It was a bug but now I think that these were removed by https://github.com/improbable-eng/thanos/commit/8f247d671fad6bbdaf3d957610f43cfb5ffaf4c4. Could you double check?
