### ISSUE TITLE
Race condition in proxy store

### ISSUE THREAD

**Issue by fpetkovski** [thanos-io/thanos#5458]
**Thanos, Prometheus and Golang version used**: 
Thanos version: thanosio/thanos:main-2022-06-23-f60b6598

**What happened**:
A Querier crashed several times with the following message

> Message:   east1-2\", replica=\"thanos-receiver-17\"},{k8s_cluster="[redacted]", replica=\"thanos-receiver-17\"},{k8s_cluster="[redacted]", replica=\"thanos-receiver-17\"},{k8s_cluster="[redacted]", replica=\"thanos-receiver-17\"},{k8s_cluster="[redacted]", replica=\"thanos-receiver-17\"},{k8s_cluster="[redacted]", replica=\"thanos-receiver-17\"},{k8s_cluster="[redacted]", replica=\"thanos-receiver-17\"},{k8s_cluster="[redacted]", replica=\"thanos-receiver-17\"},{k8s_cluster="[redacted]", replica=\"thanos-receiver-17\"},{k8s_cluster="[redacted]", replica=\"thanos-receiver-17\"},{k8s_cluster="[redacted]", replica=\"thanos-receiver-17\"},{k8s_cluster="[redacted]", replica=\"thanos-receiver-17\"},{k8s_cluster="[redacted]", replica=\"thanos-receiver-17\"},{k8s_cluster="[redacted]", replica=\"thanos-receiver-17\"},{k8s_cluster="[redacted]", replica=\"thanos-receiver-17\"},{k8s_cluster="[redacted]", replica=\"thanos-receiver-17\"},{k8s_cluster="[redacted]", replica=\"thanos-receiver-17\"} Mint: -9223372036854775808 Maxt: 9223372036854775807: rpc error: code = Canceled desc = grpc: the client connection is closing"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x158f678]

> goroutine 631657 [running]:
github.com/thanos-io/thanos/pkg/query.(*endpointRef).Series(0xc000cb9a40, {0x21fe8d0, 0xc00ba115f0}, 0xc, {0x0, 0x1, 0x1})
  <autogenerated>:1 +0x38
github.com/thanos-io/thanos/pkg/store.(*ProxyStore).Series.func1()
  /app/pkg/store/proxy.go:314 +0xf5f
golang.org/x/sync/errgroup.(*Group).Go.func1()
  /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
  /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x92

**What you expected to happen**:
I would expect Querier to handle the removal of a store gracefully while executing a query.

**How to reproduce it (as minimally and precisely as possible)**:
The issue is hard to reproduce locally since it seems to be caused by a race condition when a query is executed and a store is removed from the endpoints at the same time.

This is where the panic originates from
https://github.com/thanos-io/thanos/blob/f644d75586e60d86e2861cb5a9bceb7bee98188b/pkg/store/proxy.go#L314

**Comment by matej-g** [comment]
Thanks for the report. I'm wondering if this is coming from the endpoint update logic, where we set the store client to `nil` if metadata for store client is not available upon receiving info, which would explain why we see panic (trying to call `Series` on nil client. See this condition:
https://github.com/thanos-io/thanos/blob/4de555db87d38d69b78602c1e1d0fb8ed6e0371b/pkg/query/endpointset.go#L642

In receiver's info server logic, there might be case where info API will return with store metadata == `nil`, if receiver's store is [not ready](https://github.com/thanos-io/thanos/blob/4de555db87d38d69b78602c1e1d0fb8ed6e0371b/cmd/thanos/receive.go#L364) (which might be the case when a receiver is shutting down). This would mean that at one moment, the store client is there but once it's start to shut down and update occurs, we might be setting the store client to `nil` in a middle of a query execution.

I don't think it makes sens to have that conditional removal of the store client under normal circumstances, though we need to be able to remove if we encounter a component with older version not exposing info API (where we assume on the 1st metadata call that the store API exists). 

I'll take a look how we could address this, but I'm also not able to 100% confirm this is the root of the issue, as it's not straightforward to reproduce.

**Comment by matej-g** [comment]
@fpetkovski In your tests with my branch from #5468, did you still encounter this? Is it safe to assume this fixed it? :slightly_smiling_face:

**Comment by fpetkovski** [comment]
This is a bit hard to reproduce because it's a race condition. We can close the issue and I'll reopen it if I see it again :)

**Comment by fpetkovski** [comment]
We are not seeing this problem anymore. Thanks for the quick fix!
