### ISSUE TITLE
--prometheus.http-client-file  Format exam?

### ISSUE THREAD

**Issue by jianghenglz** [thanos-io/thanos#5462]
### Is your proposal related to a problem?

--prometheus.http-client-file=<file-path> Path to YAML file or string with http client configs. see Format details : ...

### Describe the solution you'd like

Format exam?

I want --prometheus.http-client-file  Format exam!!!

**Comment by jianghenglz** [comment]
sidecar  
 caller=sidecar.go:172 msg="failed to fetch prometheus version. Is Prometheus running? Retrying" err="expected 2xx response, got 401. Body: Unauthorized\n"

**Comment by yeya24** [comment]
We do need documentation for this. Help wanted.

**Comment by mark4409** [comment]
For reference, I've had trouble getting the following format to work in this file for basic authentication to prometheus:

```
basic_auth_users:
  test: ydgt87y37yt7y437to7y43o7ygfohuhiuehfiudfukfsfgfiurhfre
```

However I have had success with the following:

```
basic_auth:
  username: test
  password: test
```
