### ISSUE TITLE
Memcached client not configured with dial timeout

### ISSUE THREAD

**Issue by roystchiang** [thanos-io/thanos#5478]
**Thanos, Prometheus and Golang version used**:
We use Cortex, but under the hood the Thanos version is d1acaea2a11a3e4db6bb435c98dea63c517e3530

**Object Storage Provider**:

S3

**What happened**:

We run Cortex, and the store-gateway component heavily utilizes the Thanos bucket store

When memcached cluster is unresponsive, the query times out on the cache path, instead of timing out fast, and go directly to the bucket store.

**What you expected to happen**:

Cache failure should not result in query failure. We can configure the dialtimeout on the memcached client so when the cluster is unresponsive, we still have a chance to get data from object store directly.

we can configure the memached client dialtimeout, which will fail faster.

https://github.com/thanos-io/thanos/blob/main/pkg/cacheutil/memcached_client.go#L243

https://github.com/cortexproject/cortex/blob/34bb142b129bd781539001fb1629cf2f3ed54b82/pkg/chunk/cache/memcached_client.go#L144

**How to reproduce it (as minimally and precisely as possible)**:

Restart memcached while performing queries

**Full logs to relevant components**:

<details>Logs
<p>

```
level=warn ts=2022-06-07T19:27:20.241823574Z caller=memcached_client.go:461 name=index-cache msg="failed to fetch items from memcached" numKeys=2 firstKey=S:01G4EWW6D96D2JAFRVSPBQNA2A:753353152 err="dial tcp 10.0.20.35:11211: connect: connection timed out"
```

</p>
</details>

**Anything else we need to know**:

**Comment by yeya24** [comment]
Yeah, I think this makes sense. @roystchiang Would you like to open a PR?

**Comment by roystchiang** [comment]
yup! I will be more than happy to :)

**Comment by roystchiang** [comment]
after taking a closer look at the memcached client, we are correctly setting the dial timeout. https://github.com/themihai/gomemcache/blob/master/memcache/memcache.go#L233

it turns out to be a misconfiguration on our side :(
