### ISSUE TITLE
Metrics from Shipper are not completely wired up

### ISSUE THREAD

**Issue by GiedriusS** [thanos-io/thanos#548]
https://github.com/improbable-eng/thanos/blob/1e1f9e5c613e4ea69f4a1aef8555fc2401aad500/cmd/thanos/sidecar.go#L250 here `nil` is passed which means that metrics coming from the Shipper won't be visible which are registered here: https://github.com/improbable-eng/thanos/blob/1e1f9e5c613e4ea69f4a1aef8555fc2401aad500/pkg/shipper/shipper.go#L33
However, they are not modified at all so perhaps this should just be removed as metrics coming from other sources such as the separate buckets are enough?

**Comment by daixiang0** [comment]
@GiedriusS seem fixed?

**Comment by GiedriusS** [comment]
Yep, fixed indeed! Thanks for the ping. Closing.
