### ISSUE TITLE
Repair non-empty XOR chunks during 1h downsampling

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#5482]
### Is your proposal related to a problem?

Follow up issue mentioned in https://github.com/thanos-io/thanos/pull/5453#discussion_r915392669.

https://github.com/thanos-io/thanos/pull/5453 solves the issue that if an empty XOR chunk is encountered, it will be skipped during 1h downsampling. However, if the chunk is not empty, compactor will throw an error and start halting.

In this case, there is still no way to solve it to continue downsampling unless we mark it. We can definitely improve this situation.

### Describe the solution you'd like

Add more features to the `bucket tools repair` to handle this case. If the XOR chunk still contains enough samples, we can choose to downsample the chunk to 5m downsampled Aggr chunk first and then continue the 1h downsampling. If it doesn't have enough samples, we can continue and don't need to contain it in the 1h downsampled block (we can control this via a flag if necessary).

**Comment by sharadgaur** [comment]
@yeya24 is okay if I take a stab at it.

**Comment by Kartik-Garg** [comment]
Raised a [PR](https://github.com/thanos-io/thanos/pull/6137) in regards to this issue.
