### ISSUE TITLE
Typo in storage.md file

### ISSUE THREAD

**Issue by bishal7679** [thanos-io/thanos#5485]
### Is your proposal related to a problem?

**There is a typo in storage.md file**

![Screenshot (178)](https://user-images.githubusercontent.com/70086051/178134790-7c337345-caa6-4ec5-99e7-ae0dea4474b4.png)

And also `#names` looks good instead of #names

![Screenshot (179)](https://user-images.githubusercontent.com/70086051/178134932-84fb0b5d-adae-409f-a5f8-f6316db2edb6.png)

### Describe the solution you'd like

It should be `corresponding` not `coresponding`

and also 

![Screenshot (180)](https://user-images.githubusercontent.com/70086051/178134952-f78cf393-2854-4f10-bf9b-77e16654509a.png)

**Comment by mervyd** [comment]
> ### Is your proposal related to a problem?
> **There is a typo in storage.md file**
> 
> ![Screenshot (178)](https://user-images.githubusercontent.com/70086051/178134790-7c337345-caa6-4ec5-99e7-ae0dea4474b4.png)
> 
> And also `#names` looks good instead of #names
> 
> ![Screenshot (179)](https://user-images.githubusercontent.com/70086051/178134932-84fb0b5d-adae-409f-a5f8-f6316db2edb6.png)
> 
> ### Describe the solution you'd like
> It should be `corresponding` not `coresponding`
> 
> and also
> 
> ![Screenshot (180)](https://user-images.githubusercontent.com/70086051/178134952-f78cf393-2854-4f10-bf9b-77e16654509a.png)
