### ISSUE TITLE
Receiver: Metrics with out-of-order labels get accepted

### ISSUE THREAD

**Issue by matej-g** [thanos-io/thanos#5499]
**Thanos, Prometheus and Golang version used**:
Latest Thanos (`0.27.0`)

**What happened**:
Receiver happily accepts metrics with out-of-order labels. By itself, this seemed to be acceptable (i.e. TSDB will append them without complaining). But this is causing issues in compactor, which expects labels to be in order and this causes it to get into a crash loop.

This is similar to situation that happened previously with https://github.com/prometheus/prometheus/pull/5372. Though we're in remote write land and we may assume in most cases we are getting metrics from 'official' clients that should adhere to the labels ordering, this cannot be guaranteed with all clients (as is evidenced by our related issue https://github.com/thanos-io/thanos/issues/5497, which we caused by running some custom tests with an 'unofficial' client from https://github.com/observatorium/up).

**What you expected to happen**:
I would expect the receiver to handle this, at least in a minimal fashion, to prevent potential issues with compactor down the line. Possible options:
- Silently fix label ordering
- Warn about wrong label order
- Both of the above
- Refuse request as bad request
- Make this configurable

**Comment by douglascamata** [comment]
Can Receive know if the labels are out of order without having to effectively copy, **sort** the copy, and then and compare to the original? 🤔

**Comment by matej-g** [comment]
Prometheus considers bad request to be unrecoverable errors (unlike e.g. server errors), so it should not retry on such response. This is equivalent to how we handle requests with invalid samples or exemplars. I tried to describe it more in depth in the PR description.

**Comment by douglascamata** [comment]
Awesome. It sounds like a good flow. Thanks for the explanation. 🙇

**Comment by hanem100k** [comment]
uuh, google does not like the suffix of this, found a lot of issues with out-of-order samples, but this with labels was buried:)

Running 0.34 thanos-receivers and It does work accordingly to the above, drops the requests:)

<img width="1456" alt="image" src="https://github.com/thanos-io/thanos/assets/24683520/c15b443d-9097-4597-b7fd-62b171c384bf">

I'm sending writes from Prometheus instances, however, remote_write config doesn't seem to have an option to send sorted, which is weird because the spec explicitly states that stuff should be sorted, it might make sense to make sure give the possibility before egressing.

Either way, is there a way I can explicitly sort? or just labelkeep blocks in order? @matej-g @douglascamata 

Thanks!

**Comment by MichaHoffmann** [comment]
Oh I don't think Prometheus should write ooo labels in remote write, is there something else writing?

**Comment by hanem100k** [comment]
> Oh I don't think Prometheus should write ooo labels in remote write, is there something else writing?

It's only promethesis, hundreds of them. Most of them are on version 2.50, with a couple still on 2.26, let me see if the old ones are causing the issue

**Comment by MichaHoffmann** [comment]
Can you run receivers with debug logging? I think they should log the offending labels then iirc.

**Comment by hanem100k** [comment]
checked the versions:

<img width="1705" alt="image" src="https://github.com/thanos-io/thanos/assets/24683520/4e327bee-c562-463f-ae4c-f40c5a727d2e">
We run quite a few, unfortunately, tho it doesn't seem to be version specific, newest is having the same issues.

> Can you run receivers with debug logging? I think they should log the offending labels then iirc.

Yes they do log it, tho it is very very spammy, I mean we're having this issue all over the place, hence wanting to defer manual labelkeep:)

**Comment by hanem100k** [comment]
<img width="803" alt="image" src="https://github.com/thanos-io/thanos/assets/24683520/a302fdf8-783c-49fa-8476-367d5fbd870a">
`ts=2024-04-09T19:14:37.119330063Z caller=writer.go:123 level=debug component=receive component=receive-writer 
tenant=default-tenant msg="Out of order labels in the label set" lset="
labels:<name:\"__name__\" value:\"prometheus_tsdb_compaction_chunk_range_seconds_count\" > 
labels:<name:\"cluster\" value:\"xyz\" > 
labels:<name:\"instance\" value:\"172.19.88.162:9090\" > 
labels:<name:\"job\" value:\"prometheus\" > 
labels:<name:\"namespace\" value:\"xyz" > 
labels:<name:\"pod_container_init\" value:\"false\" > 
labels:<name:\"pod_container_name\" value:\"xyz\" > 
labels:<name:\"pod_container_port_number\" value:\"9090\" > 
labels:<name:\"pod_container_port_protocol\" value:\"TCP\" > 
labels:<name:\"pod_controller_kind\" value:\"StatefulSet\" > 
labels:<name:\"pod_label_app\" value:\"xyz\" > 
labels:<name:\"pod_label_app_kubernetes_io_managed_by\" value:\"xyz\" > 
labels:<name:\"pod_label_component\" value:\"xyz\" > 
labels:<name:\"pod_label_release\" value:\"prometheus\" > 
labels:<name:\"pod_name\" value:\"xyz\" >
labels:<name:\"pod_node_name\" value:\"xyz\" >
labels:<name:\"pod_phase\" value:\"Running\" >
labels:<name:\"pod_ready\" value:\"true\" >
labels:<name:\"prometheus\" value:\"xyz\" >
labels:<name:\"prometheus_replica\" value:\"xyz\" >
labels:<name:\"rule_group\" value:\"xyz\" > 
labels:<name:\"pod_container_name\" value:\"xyz\" > 
labels:<name:\"pod_container_port_number\" value:\"xyz\" > 
labels:<name:\"pod_container_port_protocol\" value:\"TCP\" > 
labels:<name:\"pod_controller_kind\" value:\"ReplicaSet\" > 
labels:<name:\"pod_label_app\" value:\"xyz\" > 
labels:<name:\"pod_label_release\" value:\"xyz\" > 
labels:<name:\"pod_name\" value:\"xyz\" > 
labels:<name:\"pod_node_name\" value:\"xyz\" > "
`

*hand edited values, might have syntax errors

**Comment by MichaHoffmann** [comment]
That lset also has a couple duplicate labels after rule_group! That's really weird

**Comment by hanem100k** [comment]
looking at an another one: 
<img width="1003" alt="image" src="https://github.com/thanos-io/thanos/assets/24683520/0542c32d-4bbb-49c9-9c6c-024d1f8e776e">

This is not sorted to being with, tho it duplicates again, even the node.

Will debug tomorrow, but I think the logging might be wrong, (we are consuming these currently with another layer of big prom instances and did not notice any label duplication or weirdness like the above. Ofc those are scraping)
