### ISSUE TITLE
Grafana shows wrong values when alerts triggered.

### ISSUE THREAD

**Issue by 605adi** [thanos-io/thanos#5531]
I have created alerts using node-exporter, prometheus and grafana.

Grafana Query used for CPU Usage and Memory Usage :-

100 * (1 - avg(rate(node_cpu_seconds_total{mode=“idle”, instance=“custom:port” , job=“nodeexporter”}[1m])))

((node_memory_MemTotal_bytes{instance="ip",job="node-exporter"}	 - node_memory_MemAvailable_bytes{instance="ip",job="node-exporter"}) / node_memory_MemTotal_bytes{instance="ip",job="node-exporter"}) * 100

when the alerts triggered it sends an alerts but the actual problem is when i compare alerts with GCP or the machine, alerts its shows different values. like in GCP its 45% then in Grafana its 80%.

How to solve this problem Grafana alerts showing wrong values how to get the exact values.

**Steps tried:-**

Changed scrape_interval to 5s.
changed CPU query
checked prometheus collecting the same data as it shows in Grafana.

**Prometheus.yml file:-**

global:

scrape_interval: 15s

evaluation_interval: 15s

alerting:

alertmanagers:

- static_configs:

    - targets:
rule_files:

scrape_configs:

job_name: "prometheus"static_configs:
targets: [“customip:port”]

**Comment by hanjm** [comment]
It is not thanos issue. The `node_cpu_seconds_total` is the sum of all cpu cores use seconds. you need divide to the number of cores.
refrence:  https://github.com/prometheus/node_exporter/blob/master/docs/node-mixin/lib/prom-mixin.libsonnet#L57
