### ISSUE TITLE
gRPC connections metric has long label values

### ISSUE THREAD

**Issue by SuperQ** [thanos-io/thanos#5540]
**Thanos, Prometheus and Golang version used**:

latest - v0.27.0

**What happened**:

When running a survey of long label values on our system I discovered Thanos was responsible for generating the longest label name length

```
thanos_store_nodes_grpc_connections{external_labels="..."}
```

The maximum length is 154436 characters.

This is likely because of the large number of Prometheus instances we have writing to a cluster-wide S3 bucket.

**What you expected to happen**:

This label needs to be removed or modified to limit the length to something more sane.

**How to reproduce it (as minimally and precisely as possible)**:

Have stores serving lots of buckets with lots of external labels.

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by SuperQ** [comment]
CC @hitanshu-mehta

**Comment by yeya24** [comment]
I agree to remove the label `external_labels`. Using the endpoint address here might be a better solution to represent each store.

**Comment by haanhvu** [comment]
I'll work on this

**Comment by haanhvu** [comment]
Hi @yeya24 from what I see in:

https://github.com/thanos-io/thanos/blob/ee512aed1fece177b9257e80ba6c6c5d5986620a/pkg/query/endpointset.go#L193-L202

We have `external_labels` and `store_type`. Do you think it's safe to remove both or just `external_labels`?

> Using the endpoint address here might be a better solution to represent each store.

Could you please show me where I can take the endpoint address from?

**Comment by yeya24** [comment]
Removing external labels only should be good.

**Comment by bwplotka** [comment]
We have been discussing this in the past. The endpoint address was assumed not stable enough (e.g. same store API replica on restart would have different IP). On top of that IP does not give you a lot, when debugging querier using this metric.

To me, we have two solutions:

A) Remove ext label label totally.
B) Enforce label limit by checking if we external labels label value is larger than X (e.g let's say 1000 chars). If yes, capping it to `<first 1000 chars of external labels>(...)`.

What about B?

**Comment by haanhvu** [comment]
> We have been discussing this in the past. The endpoint address was assumed not stable enough (e.g. same store API replica on restart would have different IP). On top of that IP does not give you a lot, when debugging querier using this metric.
> 
> To me, we have two solutions:
> 
> A) Remove ext label label totally. B) Enforce label limit by checking if we external labels label value is larger than X (e.g let's say 1000 chars). If yes, capping it to `<first 1000 chars of external labels>(...)`.
> 
> What about B?

If there're no other better labels to replace here, then +1 for B.

**Comment by SuperQ** [comment]
I would much prefer A. The gRPC metrics are useful to alert on, but I would use tracing data to do debugging.

**Comment by SuperQ** [comment]
One thing that would be more useful than just the IP, would be to propagate the SRV record names through. This would allow the dnssrv store flag lists to be more useful.

**Comment by bwplotka** [comment]
Ok, so my proposal would be to:

* Always trim external labels to e.g. 1000 chars.
* Add a `[]string` flag to querier like `querier.conn-metric.labels` that allows specifying NO, or any of the labels like `external_labels`, `store_type`, `record_name` (default `external_labels`, `store_type`) which will switch labels the `thanos_store_nodes_grpc_connections` has. 

This allows user to choose as they want and also would avoid breaking compatibility.

**Comment by SuperQ** [comment]
@bwplotka LGTM.

**Comment by Akshit42-hue** [comment]
Hey @haanhvu, are you still working on it ?

**Comment by yeya24** [comment]
Closed by https://github.com/thanos-io/thanos/pull/5785
