### ISSUE TITLE
Receive: Allow setting hashing algorithm per tenant in hashrings config

### ISSUE THREAD

**Issue by fpetkovski** [thanos-io/thanos#5567]
### Is your proposal related to a problem?

When running Thanos Receivers, I would like to be able to set the hashing algorithm individually for each tenant.

### Describe the solution you'd like

The algorithm could be added as a field in the hashrings config.

### Describe alternatives you've considered

The only alternative is to set the hashing globally for all tenants, which has the following drawbacks:
* Changing the hashing algorithm will cause a very large series churn which will lead to big memory spikes. This makes migrations to different algorithms challenging.
* It is hard to experiment with different hashing strategies on real production data.

**Comment by RainrainWu** [comment]
Hi @fpetkovski, I just took a look at the source code and thought I can take care of this.
May I give it a try?

**Comment by haanhvu** [comment]
I'll work on this

**Comment by haanhvu** [comment]
will finish soon^^

**Comment by haanhvu** [comment]
will finish soon^^
