### ISSUE TITLE
Receiver: reduce network bandwidth when ingesting data

### ISSUE THREAD

**Issue by fpetkovski** [thanos-io/thanos#5572]
### Is your proposal related to a problem?

We noticed that our intra-AZ egress costs tripled when we migrated from HA Prometheus pairs to receivers. We would have expected costs to go up by around 50% only due to the added replication factor.

### Describe the solution you'd like

Looking at the code, it seems that forwarding requests between receivers is done by encoding remote-write requests in protobuf. This could be the potential reason and we might be able to reduce bandwith by encoding requests with snappy.

### Describe alternatives you've considered

No alternatives found so far

**Comment by fpetkovski** [comment]
Cortex seems to support this already: https://github.com/cortexproject/cortex/blob/master/pkg/util/grpcencoding/snappy/snappy.go

**Comment by bwplotka** [comment]
LGTM. thanks for noticing!

**Comment by squat** [comment]
cool. let's see. I didn't really understand how to read the `network ingester` graph from that issue as it has negative values for the bandwidth.

**Comment by fpetkovski** [comment]
Yeah the graphs are a bit strange. I'll give this thing a shot next week and measure changes in transmitted bytes from receivers.
