### ISSUE TITLE
how to solve problem

### ISSUE THREAD

**Issue by mongoliaredmountain** [thanos-io/thanos#5576]
level=info ts=2022-08-08T03:16:11.854528377Z caller=options.go:27 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2022-08-08T03:16:11.854760378Z caller=factory.go:50 msg="loading bucket configuration"
level=error ts=2022-08-08T03:16:11.854822567Z caller=main.go:132 err="yaml: line 2: mapping values are not allowed in this context\nparsing config YAML file\ngithub.com/thanos-io/thanos/pkg/objstore/client.NewBucket\n\t/app/pkg/objstore/client/factory.go:53\nmain.runSidecar\n\t/app/cmd/thanos/sidecar.go:306\nmain.registerSidecar.func1\n\t/app/cmd/thanos/sidecar.go:73\nmain.main\n\t/app/cmd/thanos/main.go:130\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\npreparing sidecar command failed\nmain.main\n\t/app/cmd/thanos/main.go:132\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"

<img width="955" alt="image" src="https://user-images.githubusercontent.com/22609864/183332225-6d6920ff-0d04-4e07-9846-6e9c76cd73c4.png">

This problem how to solve？

**Comment by GiedriusS** [comment]
I think it needs to be:
```yaml
type: S3
config:
  ...
```

Notice how there's no spaces before "config:".

**Comment by ADITYADAS1999** [comment]
type: s3
config: 
  access_key_id: kvMgKi6doSwB1md
  access_key_secret: 9e563QISa0g1GDSqcLPqWcCQFADYs
  bucket: thanos
  endpoint: "192.168.58.204"
  insecure: true

![yaml validation](https://user-images.githubusercontent.com/58718316/183554705-1ce1d63e-9d34-47b7-9a9d-b793d90a06d2.PNG)

**Comment by ADITYADAS1999** [comment]
hey i thing thats useful
