### ISSUE TITLE
Store : OOMKilled - exit code 137

### ISSUE THREAD

**Issue by chalut01** [thanos-io/thanos#5577]
**Thanos, Prometheus and Golang version used**: 0.26.0

Hi,
From the following issue https://github.com/thanos-io/thanos/issues/3665. I get an error "OOMKilled - exit code 137" many time.
Do you have any suggestions?

**My args**
--store.grpc.series-sample-limit=0'
--log.level=info'
--data-dir=/var/thanos/store'
--index-cache.config-file=/thanos-conf/thanos-store-redis.yaml'
--chunk-pool-size=8GB'
--store.grpc.series-max-concurrency=10'
--sync-block-duration=5m'
--block-sync-concurrency=10'
--objstore.config-file=/thanos-conf/s3.yaml'
--store.enable-index-header-lazy-reader'
--min-time=-360d'
--max-time=-120d'

**resources limit**
    cpu: '4'
    memory: 25Gi

**log**
[thanos-store-1h-5b44d8c479-dr8fj.log](https://github.com/thanos-io/thanos/files/9293443/thanos-store-1h-5b44d8c479-dr8fj.log)

**Comment by oronsh** [comment]
I think it's the label values, when passed a mathcer, if external label it would try to fetch all series to match on.
I opened a PR with a fix:
https://github.com/thanos-io/thanos/pull/5596
