### ISSUE TITLE
Compactor: Prometheus TODO metrics will disappear when everything is done

### ISSUE THREAD

**Issue by jabdoa2** [thanos-io/thanos#5587]
**Thanos, Prometheus and Golang version used**:

Everything up to current master.

**Object Storage Provider**: irrelevant here

**What happened**:

Compactor records its todos in `thanos_compact_todo_compaction_blocks`, `thanos_compact_todo_deletion_blocks` and `thanos_compact_todo_downsample_blocks`. Those metrics are very helpful when something is todo. However, they disappear when everything is done which makes it hard to differentiate between (a) everything is done and (b) compactor is not working properly.

**What you expected to happen**:

Those metrics should return 0 when nothing is todo.

**How to reproduce it (as minimally and precisely as possible)**:

1. Start compactor
2. Give it something to do
3. Check metrics endpoint. Metrics should be present
4. Wait until everything is done
5. Check metrics endpoint again. Metrics should be gone.

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by yeya24** [comment]
This behavior is expected because the metrics are gauges. We need to reset the labels every iteration to clean up stale metrics from previous iterations. Otherwise, the cardinality would grow infinitely.

> However, they disappear when everything is done which makes it hard to differentiate between (a) everything is done and (b) compactor is not working properly.

Compactor not working is usually tracked by some other more meaningful metrics like `up{job="thanos-compactor}`.

**Comment by jabdoa2** [comment]
> Compactor not working is usually tracked by some other more meaningful metrics like `up{job="thanos-compactor}`.

Yeah that does not help. We had that check and it stopped working in Dezember. We noticed just in August this year. You need to monitor at least the halted metric but even that is not reliable as it becomes unhalted on every restart.

Monitoring the rate of complete iterations is the best we currently have. However, its far from optimal. It would be nice to properly monitor outstanding work to make sure we do not backlog too much. I understand that those are labled gauges. Can we have a overall gauge with becomes 0? That would be more helpful than the labeled ones to us.

**Comment by yeya24** [comment]
Yep so you can monitor the halt metrics along with the progress metrics.

Unfortunately it is not easy to make it 0 by default. But you can use the way I mentioned to turn it to 0 and then you can use rate for it.

**Comment by jabdoa2** [comment]
> For the overall gauge you can use the query I mentioned to turn it to 0 when no compaction required.

Please have a look at my initial issue: This metric is also null when compactor is not running. We really got issues monitoring compactor without noise because metrics are unstable. This eventually leads to fatigue and people will stop trusting the monitoring. We had a broken compactor for almost a year because people mostly ignored the issue because retarting the pod fixed it for a while. So no that is not a proper solution in my opinion.



> Yep so you can monitor the halt metrics along with the progress.

As I stated above: Halt suffers a similar issue. It will become 0 after restart making people believe that everything is working now. We are looking for a robust way to monitor compactor. We got workarounds at the moment but still would like a reliable metric without false positives and flapping.

**Comment by yeya24** [comment]
> Please have a look at my initial issue: This metric is also null when compactor is not running.

That's totally a different question. You could use something like `absent(compact_xxx_build_info)` to make sure compactor is running. If you want to ensure not halting you could combine the two.

You have to combine the multiple metrics together and get a complete view. There is no perfect solution now for you to look at one metric only. If you have any idea feel free to contribute.

**Comment by jabdoa2** [comment]
> > Please have a look at my initial issue: This metric is also null when compactor is not running.
> 
> That's totally a different question. You could use something like `absent(compact_xxx_build_info)` to make sure compactor is running. If you want to ensure not halting you could combine the two

Unfortunately, that metric also exists when compactor is broken.

For now we settled with an ugly workaround and check if we got at least one complete iteration within the last two hours. It ain't nice but with such a low limit we don't get false positives.

**Comment by SuperQ** [comment]
I wonder if this is somewhat fixed now, there is a `Set(0)` in the compaction code.

**Comment by jabdoa2** [comment]
We switched to compactor cronjobs. Those either succeed or fail so it became a non issue for us. Unfortunately, we no longer scrape the metric so I cannot tell.

**Comment by jabdoa2** [comment]
Thanks for verifying!
