### ISSUE TITLE
Docs: Update object storage provider details

### ISSUE THREAD

**Issue by Akshit42-hue** [thanos-io/thanos#5592]
In the object storage provider [docs](https://thanos.io/tip/thanos/storage.md/#supported-clients) we have missing Oracle Object Storage details

**Comment by matej-g** [comment]
@Akshit42-hue make sense! Do you want to add it? :slightly_smiling_face:

**Comment by Akshit42-hue** [comment]
> @Akshit42-hue make sense! Do you want to add it? slightly_smiling_face

Well, yes if someone guides me :)

**Comment by yeya24** [comment]
Yeah we definitely need to add docs for OCI object storage. Thanks for finding it.
We should have an owner for it, too.

**Comment by MahendraBishnoi29** [comment]
i'm interested if someone guides how to do this?

**Comment by aarontams** [comment]
Thanos spitted the Object Storage component from https://github.com/thanos-io/thanos repo to https://github.com/thanos-io/objstore repo. My [PR](https://github.com/thanos-io/objstore/pull/15) was in objstore repo and only updated https://github.com/thanos-io/objstore/blob/main/README.md.

I will have a PR to update https://github.com/thanos-io/thanos/blob/main/docs/storage.md when I have free cycle.

Feel free to assign to me.

**Comment by sonali-rajput** [comment]
> Thanos spitted the Object Storage component from https://github.com/thanos-io/thanos repo to https://github.com/thanos-io/objstore repo. My [PR](https://github.com/thanos-io/objstore/pull/15) was in objstore repo and only updated https://github.com/thanos-io/objstore/blob/main/README.md.
> 
> I will have a PR to update https://github.com/thanos-io/thanos/blob/main/docs/storage.md when I have free cycle.
> 
> Feel free to assign to me.

Does any issue need to be assigned first before working or making a PR for it?

**Comment by Akshit42-hue** [comment]
> > Thanos spitted the Object Storage component from https://github.com/thanos-io/thanos repo to https://github.com/thanos-io/objstore repo. My [PR](https://github.com/thanos-io/objstore/pull/15) was in objstore repo and only updated https://github.com/thanos-io/objstore/blob/main/README.md.
> > I will have a PR to update https://github.com/thanos-io/thanos/blob/main/docs/storage.md when I have free cycle.
> > Feel free to assign to me.
> 
> Does any issue need to be assigned first before working or making a PR for it?

Hey @sonali-rajput, thank you for your interest. You can directly open a PR :)

**Comment by aarontams** [comment]
Here is the PR: https://github.com/thanos-io/thanos/pull/5778

**Comment by ShivangShandilya** [comment]
Please close this issue
