### ISSUE TITLE
Add metrics to PromQLShardingMiddleware

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#5606]
### Is your proposal related to a problem?

Now we don't have any instrumentation to the `PromQLShardingMiddleware` so we might miss some very important stats.
I'd like to see metrics like Number of shardable queries and non-shardable queries.

### Describe the solution you'd like

The implementation should be straightforward to add two counters to the middleware

**Comment by idoqo** [comment]
Hi @yeya24, Trying to work on this [here](https://github.com/idoqo/thanos/tree/sharded-query-metrics), but not sure how to try it out Can you help provide some sample shardable queries?

**Comment by yeya24** [comment]
> here

Hi @idoqo, I checked that branch and the code looks good! For not shardable query you could try `up` and shardable query you could try `sum(up) by (job)`. Let me know if this works for you or not.
