### ISSUE TITLE
Remove hardcoded labels in store shard matcher

### ISSUE THREAD

**Issue by fpetkovski** [thanos-io/thanos#5625]
### Is your proposal related to a problem?

We currently hardcode certain labels in shard matchers because they should not be take account for sharding
https://github.com/thanos-io/thanos/blob/67880caabffac1f693954d8ce51715973a369e2b/pkg/store/storepb/shard_info.go#L45-L48

### Describe the solution you'd like

We should completely remove the `__name__` label as it should be okay to shard on it.
The `le` label should be propagated through the query analyzer instead. This will remove coupling on PromQL in Thanos Stores.

### Additional context

Slack thread: https://cloud-native.slack.com/archives/CL25937SP/p1661110514624489

**Comment by haanhvu** [comment]
I'll work on this
