### ISSUE TITLE
Potential race condition between compactor applying retention or compaction and store gateway syncing metas.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#564]
With compaction or retention logic we have one "writer" that creates new blocks (compaction) and  deletes blocks that were source of it. 

The problem with our readers (store) is that syncing is periodically every X seconds. So it might happen that we query store during time of compactor remove the block, but store did not sync yet. There is no watch logic for Bucket API.

The simplest solution is to defer deletion in some time in future  to address potential eventual consistency of store Gateway internal state (and potentially bucket itself) 

Acceptance criteria:
- Store Gateway will have loaded new block before old compaction source blocks are deleted.
- Store Gateway handling paritally deleted, empty or non existent TSDB block, despite having cached meta-index file.

This unfortunately requires the heavy modification of compactor Plan logic to understand the edge cases like:
* Compactor creates new block. Defers source block deletions and suddenly stopped working. 
  * After restart compactor needs to detect that block overlap is because of defered deletion. 
  * What if bucket shows newly created block as partial? (eventual consistency), What if compactor crashed before upload completed? How to differentiate those two?
  * What if defered deletion fails in between?

This has to be done and is planned to be done EOY

**Comment by bwplotka** [comment]
@sylr 
```
level=warn ts=2019-05-09T09:15:07.187245371Z caller=bucket.go:296 msg="loading block failed" id=01D8R2ZMQZFT1T7Z1SA6CMMZWN err="new bucket block: load index cache: read index cache: decode file: EOF"
```
Your error might be related

**Comment by bwplotka** [comment]
This will be fixed by: https://github.com/thanos-io/thanos/issues/1528 help wanted (:

**Comment by Reamer** [comment]
Why we doesn't trigger a resync with remote in reader component (thanos store), if a block (deleted by compactor) isn't found?

**Comment by bwplotka** [comment]
@Reamer 

We can, but still sync takes time, so ideally we can do it in a smarter way as defined by https://github.com/thanos-io/thanos/issues/1528

**Comment by bwplotka** [comment]
@khyatisoneji is on it (:

**Comment by bwplotka** [comment]
We are super close to merge the fix! But not yet fixed.

**Comment by bwplotka** [comment]
Fixed by https://github.com/thanos-io/thanos/pull/2136
