### ISSUE TITLE
compactor: cannot rentiton

### ISSUE THREAD

**Issue by yuanhuaiwang** [thanos-io/thanos#5659]
**Thanos, Prometheus and Golang version used**:
thanos 0.24.0

**Object Storage Provider**:
S3
**What happened**:
compactor cannot rentiton beause of deleted-mark.json 
**What you expected to happen**:
compactor should rentition
**How to reproduce it (as minimally and precisely as possible)**:
   ---retention.resolution-raw=15d
    - --retention.resolution-5m=15d
    - --retention.resolution-1h=15d
    - --consistency-delay=30m
    - --delete-delay=48h
    - --compact.concurrency=4
    - --objstore.config-file=/conf/objstore.yml
    - --wait
**Full logs to relevant components**:
level=info ts=2022-08-30T09:19:26.351548755Z caller=retention.go:41 msg="applying retention: marking block for deletion" id=01G9KSCXGWZ5VYX6TJKDNDN54M maxTime="2022-08-04 00:00:00 +0000 UTC"
level=warn ts=2022-08-30T09:19:26.354552516Z caller=block.go:191 msg="requested to mark for deletion, but file already exists; this should not happen; investigate" err="file 01G9KSCXGWZ5VYX6TJKDNDN54M/deletion-mark.json already exists in bucket"
level=info ts=2022-08-30T09:19:26.354582217Z caller=retention.go:41 msg="applying retention: marking block for deletion" id=01G9KPTWVVCT8GV2HE6QNKN144 maxTime="2022-08-04 00:00:00 +0000 UTC"
level=warn ts=2022-08-30T09:19:26.357577286Z caller=block.go:191 msg="requested to mark for deletion, but file already exists; this should not happen; investigate" err="file 01G9KPTWVVCT8GV2HE6QNKN144/deletion-mark.json already exists in bucket"
level=info ts=2022-08-30T09:19:26.35761284Z caller=retention.go:41 msg="applying retention: marking block for deletion" id=01GA5DGBYSNKGQMQEX33GK4K3X maxTime="2022-08-11 02:00:00 +0000 UTC"
level=warn ts=2022-08-30T09:19:26.360437458Z caller=block.go:191 msg="requested to mark for deletion, but file already exists; this should not happen; investigate" err="file 01GA5DGBYSNKGQMQEX33GK4K3X/deletion-mark.json already exists in bucket"
level=info ts=2022-08-30T09:19:26.360462288Z caller=retention.go:41 msg="applying retention: marking block for deletion" id=01G9XZ3RWWY75C455WSTTDX2WJ maxTime="2022-08-08 00:00:00 +0000 UTC"
level=warn ts=2022-08-30T09:19:26.363390118Z caller=block.go:191 msg="requested to mark for deletion, but file already exists; this should not happen; investigate" err="file 01G9XZ3RWWY75C455WSTTDX2WJ/deletion-mark.json already exists in bucket"
level=info ts=2022-08-30T09:19:26.363413183Z caller=retention.go:41 msg="applying retention: marking block for deletion" id=01GA5MC42TG73K7XF6MSZKSQV6 maxTime="2022-08-11 04:00:00 +0000 UTC"
level=warn ts=2022-08-30T09:19:26.366245798Z caller=block.go:191 msg="requested to mark for deletion, but file already exists; this should not happen; investigate" err="file 01GA5MC42TG73K7XF6MSZKSQV6/deletion-mark.json already exists in bucket"
level=info ts=2022-08-30T09:19:26.366273124Z caller=retention.go:41 msg="applying retention: marking block for deletion" id=01G9XZ9KKZFSYKZB82J9X86WFS maxTime="2022-08-08 00:00:00 +0000 UTC"
level=warn ts=2022-08-30T09:19:26.369253899Z caller=block.go:191 msg="requested to mark for deletion, but file already exists; this should not happen; investigate" err="file 01G9XZ9KKZFSYKZB82J9X86WFS/deletion-mark.json already exists in bucket"
level=info ts=2022-08-30T09:19:26.369280545Z caller=retention.go:41 msg="applying retention: marking block for deletion" id=01G9Y16N4EGVN6XCJG2WW21AXN maxTime="2022-08-04 00:00:00 +0000 UTC"
level=warn ts=2022-08-30T09:19:26.372218468Z caller=block.go:191 msg="requested to mark for deletion, but file already exists; this should not happen; investigate" err="file 01G9Y16N4EGVN6XCJG2WW21AXN/deletion-mark.json already exists in bucket"

**Anything else we need to know**:

**Comment by yeya24** [comment]
Is it an issue? If the file already exists then the blocks will be finally deleted anyway.

**Comment by yeya24** [comment]
I feel the compactor issue is still related to the backlog. We have a document about troubleshooting it https://thanos.io/tip/operating/compactor-backlog.md/.

**Comment by yeya24** [comment]
Close this due to no response. Feel free to reopen if it is still an issue
