### ISSUE TITLE
Support S3 storage class

### ISSUE THREAD

**Issue by ArpStorm1** [thanos-io/thanos#5663]
### Is your proposal related to a problem?

Hello!!
We need support to use other storage classes than STANDARD in S3.
The default storage class in S3 is STANDARD, and it is also the mose expensive one.
We would like to get a configuration option to use STANDARD_IA storage class or even GLACIER if needed.

### Describe the solution you'd like

An option in the config file to choose the required storage class.

### Describe alternatives you've considered

Using STANDARD is expensive.

### Additional context

MinIO client is supporting S3 storage class, so it would be nice to use this feature in Thanos as well

**Comment by juanrh** [comment]
I'm interesting on working on this

**Comment by juanrh** [comment]
I've been investigating this a bit. I first though I could pass `config.put_user_metadata:X-Amz-Storage-Class: STANDARD_IA` to setup STANDARD_IA storage class, but that was failing with 

```
level=warn ts=2022-09-01T09:19:09.362133Z caller=sidecar.go:344 err="upload 01G95BH5DQDC8SKB97JBG79V9T: upload chunks: upload file /Users/jrodrig/systems/prometheus/latest/data/thanos/upload/01G95BH5DQDC8SKB97JBG79V9T/chunks/000001 as 01G95BH5DQDC8SKB97JBG79V9T/chunks/000001: upload s3 object: X-Amz-Storage-Class unsupported user defined metadata name" uploaded=0
```

which is a validation done in https://github.com/minio/minio-go/blob/master/api-put-object.go#L188. It looks like in Minio the storage class has to be specified in [`PutObjectOptions.StorageClass`](https://pkg.go.dev/github.com/minio/minio-go/v7#PutObjectOptions). I did a test hardcoding that as follows:

```diff
gijrodrig-mac:thanos jrodrig$ git diff
diff --git a/pkg/objstore/s3/s3.go b/pkg/objstore/s3/s3.go
index 1e0ae3fe..11e28668 100644
--- a/pkg/objstore/s3/s3.go
+++ b/pkg/objstore/s3/s3.go
@@ -541,6 +541,7 @@ func (b *Bucket) Upload(ctx context.Context, name string, r io.Reader) error {
                        PartSize:             partSize,
                        ServerSideEncryption: sse,
                        UserMetadata:         b.putUserMetadata,
+                       StorageClass: "STANDARD_IA",
                },
        ); err != nil {
                return errors.Wrap(err, "upload s3 object")
jrodrig-mac:thanos jrodrig$ 
```

and when I test it against S3 as follows I see objects with Storage class Standard-IA uploaded by the sidecar in S3

```bash
rm ${PROM_ROOT}/data/thanos.shipper.json # force reupload
~/go/bin/thanos sidecar \
    --tsdb.path            ${PROM_ROOT}/data \
    --prometheus.url       "http://localhost:9090" \
    --objstore.config='type: S3
prefix: thanos-test-standard-ia
config:
  endpoint: s3.us-east-1.amazonaws.com
  region: us-east-1
  bucket: MY_BUCKET
  trace:
    enable: true'
```

We could pass the storage class in the config so it is available in `type Bucket struct` in pkg/objstore/s3/s3.go. One option is adding a new key, but another one is allowing to specify it in `config.put_user_metadata:X-Amz-Storage-Class: STANDARD_IA`  (as `X-Amz-Storage-Class` is already a documented key https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html#API_PutObject_RequestSyntax  and with a constant in vendor/github.com/minio/minio-go/v7/constants.go), and in `Bucket.Upload` we could move it from `minio.PutObjectOptions.UserMetadata` and put in in `minio.PutObjectOptions.StorageClass`.  
So I'd like advice on the following to go ahead with this task:

- Do you prefer using `config.put_user_metadata:X-Amz-Storage-Class: STANDARD_IA`  to specify the storage class (by moving `X-Amz-Storage-Class` to `minio.PutObjectOptions.StorageClass` in `Bucket.Upload` as described above), or a new key for https://thanos.io/tip/thanos/storage.md/#s3?
- Is there any other method besides `func (b *Bucket) Upload` from pkg/objstore/s3/s3.go that should be modified?

Thanks

**Comment by juanrh** [comment]
I was working using https://github.com/openshift/thanos master as base branch, which is very different to https://github.com/thanos-io/thanos main. So the approach above (https://github.com/juanrh/thanos/commits/5663) won't work. I'll investigate how todo it for the correct base branch

**Comment by amitsetty** [comment]
This looks great!

**Comment by juanrh** [comment]
@yeya24 https://github.com/thanos-io/objstore/pull/25 is ready for review when you have some time. Thanks

**Comment by juanrh** [comment]
@yeya24 can you please take a look to https://github.com/thanos-io/objstore/pull/25 when you have some time. Thanks

**Comment by juanrh** [comment]
Thanks for taking a look @matej-g !
