### ISSUE TITLE
Old version of protoc not compatible with newer Apple Silicon laptops

### ISSUE THREAD

**Issue by pedro-stanaka** [thanos-io/thanos#5665]
**Thanos, Prometheus and Golang version used**:

Thanos: 06a64d69
Golang: 1.18.5

**What happened**:

When running `make go-lint` I get the following result:

```
▶ make go-lint 
all modules verified
>> verifying modules being imported
>> linting all of the Go files GOGC=
>> ensuring Copyright headers
>> ensuring generated proto files are up to date
>> fetching protoc@3.4.0
make[1]: *** [$GOROOT/1.18.5/bin/protoc-3.4.0] Error 1
make: *** [go-lint] Error 2
```

This is due to the fact that protoc 3.4.0 (version required by Thanos) was released back in 2017 when Apple Silicon wasn't still around. Therefore, the platform `darwin/arm64` is not supported and the script `scripts/installprotoc.sh` can't install it.

**What you expected to happen**:

To be able to run linting on my local machine without problems.

**How to reproduce it (as minimally and precisely as possible)**:

1. On a Apple Silicon machine, clone thanos
2. Run `make go-lint`

**Anything else we need to know**:

**Environment**:
- OS (e.g. from /etc/os-release): MacOS 12.5.1
- Kernel (e.g. `uname -a`): `Darwin shopstation.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64`

**Comment by fpetkovski** [comment]
I think this is fixed now with #5666. Could we close the issue?
