### ISSUE TITLE
proxy: pre-calculate hash at leaf nodes

### ISSUE THREAD

**Issue by GiedriusS** [thanos-io/thanos#5682]
### Is your proposal related to a problem?

We could increase the performance by calculating the hash of a chunk at the leaf node instead of the querier: https://github.com/thanos-io/thanos/pull/5296#discussion_r966899425

### Describe the solution you'd like

Add another field with the hash and use it.

**Comment by yeya24** [comment]
> Add another field with the hash and use it.

Can you please elaborate more on where to add the field for hashes? The `Series` API?

**Comment by pedro-stanaka** [comment]
Once we have more details here, I would be inclined to take a stab at this one.

**Comment by GiedriusS** [comment]
Idea is to calculate this [hash](https://github.com/thanos-io/thanos/blob/32a6c4e03af48ddce7fdb77253c7ba3108030e00/pkg/store/proxy_heap.go#L133) by the sender so that it would be less work on the querier (:

**Comment by yeya24** [comment]
https://github.com/thanos-io/thanos/blob/32a6c4e03a/pkg/store/storepb/types.proto#L23 If I understand correctly, we can add one more nullable hash field to the chunk itself and populate it at stores?

**Comment by pedro-stanaka** [comment]
@GiedriusS can we close this in light of #5703

**Comment by GiedriusS** [comment]
Yep :+1: thanks for your work on this! :muscle:
