### ISSUE TITLE
Bump efficientgo/e2e to latest v0.13.0 release

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#5700]
### Is your proposal related to a problem?

Right now, thanos is using https://github.com/efficientgo/e2e/commit/37e916144e6b7731f83608056f83e3ab9947862a, which currently has a dependency to `github.com/go-openapi/spec@v0.20.5`.

But this commit introduces an issue of go module checksum mismatch when `GOPROXY` is not pointing to `proxy.golang.org`, ref: https://github.com/go-openapi/spec/issues/156.

### Describe the solution you'd like

Bumping up the e2e framework to the latest `v0.13.0` version should fix this issue. Help wanted.

**Comment by Akshit42-hue** [comment]
Hey @yeya24, we just need to change the version of e2e framework to the latest v0.13.0 version ? If yes then I like to pull this issue to the finish line :)

**Comment by yeya24** [comment]
No, a lot of APIs have been changed so you need to update them all.

**Comment by yeya24** [comment]
I will assign this myself.
