### ISSUE TITLE
Query Frontend: cache sharding query analysis

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#5715]
### Is your proposal related to a problem?

Considering a lot of queries are executed in a regular basis (like alerting and recording rules evaluation), it might be unnecessary to  analyze the same query everytime. We could introduce a LRU cache to cache the `QueryAnalysis` result or `error`.

### Describe the solution you'd like

Use `github.com/hashicorp/golang-lru` as the LRU cache and add it to the `QueryAnalyzer`. Probably there are better LRU implementations but the idea should be similar.

**Comment by Rahulkumar2002** [comment]
Hello Ben, I would like to work on this issue.

**Comment by GiedriusS** [comment]
Fixed in https://github.com/thanos-io/thanos/pull/5749. Thx @Rahulkumar2002 :muscle:

**Comment by Rahulkumar2002** [comment]
> Fixed in https://github.com/thanos-io/thanos/pull/5749. Thx @Rahulkumar2002 :muscle: 

No problem 😊
