### ISSUE TITLE
replace crypto/sha256 with github.com/minio/sha256-simd

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#5722]
### Is your proposal related to a problem?

Currently `crypto/sha256` is mainly used for calculating hash of files we upload/download to/from the object store.
As shown from https://github.com/minio/sha256-simd, the performance is much better than `crypto/sha256` in golang.

### Describe the solution you'd like

Simply replace the library.

### Additional context

Thanos also builds images for other arches like `freebsd` and `ppc64le`, those might not be supported.

**Comment by utukJ** [comment]
Hi @yeya24. Does this work? https://github.com/thanos-io/thanos/pull/5738

**Comment by yeya24** [comment]
@utukJ Thank you, I think that works.
Have you verified, does it work for all archs? For unsupported arch, does it still work like fallbacking into the stdlib.

**Comment by utukJ** [comment]
Thanks for the feedback @yeya24 . I've fixed the import grouping you mentioned. However, I'm not sure how to verify this:

> Have you verified, does it work for all archs? For unsupported arch, does it still work like fallbacking into the stdlib.

**Comment by matej-g** [comment]
I guess you'd have to try and build an image for one of the mentioned unsupported archs:

> Thanos also builds images for other arches like freebsd and ppc64le, those might not be supported.

**Comment by bwplotka** [comment]
Fixed in https://github.com/thanos-io/thanos/pull/5738
