### ISSUE TITLE
Series limits are not effective in Thanos Store

### ISSUE THREAD

**Issue by GiedriusS** [thanos-io/thanos#5733]
### Is your proposal related to a problem?

We want to limit queries so that they wouldn't try to download millions of series. However, our current limits are only applied after fetching postings. This is because to find out, for example, the number of matching series, you need to perform intersection on postings depending on the given matchers. To have a practical limit here, Thanos Store might possibly download gigabytes of data.

### Describe the solution you'd like

Add a byte limit for fetched postings in Thanos Store.

### Describe alternatives you've considered

I don't think there are any alternatives here? :thinking:

**Comment by matej-g** [comment]
This might be of interest @saswatamcode @douglascamata
