### ISSUE TITLE
Netlify: select a new build image

### ISSUE THREAD

**Issue by nate-double-u** [thanos-io/thanos#5743]
Notice from Netlify
> After November 15, 2022, builds for this site will fail unless you [update the build image](https://app.netlify.com/sites/cloudevents-io/settings/deploys#build-image-selection).

As reported via deploy logs:
> DEPRECATION NOTICE: Builds using the Xenial build image will fail after November 15th, 2022.
> 
> The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.
All Netlify builds using the Xenial build image will begin failing in the week of November 15th, 2022.
>
> To avoid service disruption, please select a newer build image at the following link:
https://app.netlify.com/sites/etcd/settings/deploys#build-image-selection
>
> For more details, visit the build image migration guide:
> https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239

**Comment by nate-double-u** [comment]
Looks like the folks on the Netlify Team for thanos are:
* @bwplotka
* @brancz
* @GiedriusS

Let me know if this appropriate, or if it should be updated.

**Comment by matej-g** [comment]
Hey @nate-double-u are you able to manage the team? Would it be possible to add all maintainers (https://github.com/thanos-io/thanos/blob/main/MAINTAINERS.md)?

**Comment by nate-double-u** [comment]
> Hey @nate-double-u are you able to manage the team? Would it be possible to add all maintainers (https://github.com/thanos-io/thanos/blob/main/MAINTAINERS.md)?

I think Thanos is on an enterprise plan, so this wouldn't affect the billing, but I'm hesitant to volunteer folks for stuff -- we've got several maintainers on the Netlify team list already. Though, I'd be happy to add you to the Netlify team.

Also, a separate note: the [CNCF project maintainers list](https://github.com/cncf/foundation/blob/main/project-maintainers.csv) looks like it is out of date @matej-g -- I see you're listed as a maintainer in this repo, but you're not on that list (which is my first lookup for stuff like this).

**Comment by nate-double-u** [comment]
Followup: I've sent a Netlify team invite to your listed email @matej-g
