### ISSUE TITLE
Websute Getting Started docs link broken

### ISSUE THREAD

**Issue by dohnto** [thanos-io/thanos#5756]
Link in https://thanos.io/v0.28/thanos/getting-started.md/#maintainers page directs me to https://thanos.io/maintainers.md/ which results in 404.

**Comment by egomezbpedro** [comment]
Hi @dohnto,

I've been checking and I do not experience the same behaviour for older or newer version like 0.31. Can you share any newer insights about this error?

cheers.

**Comment by dohnto** [comment]
This still happens also for 0.31:
```
$ curl -is https://thanos.io/maintainers.md/ | head -n1
HTTP/2 404 
```

**Comment by dohnto** [comment]
ok, but the `tip` now links to https://thanos.io/tip/thanos/maintainers.md/

Lets close this then.
