### ISSUE TITLE
Thanos sidecar makes too much 404 Not Found Error to s3 object storage

### ISSUE THREAD

**Issue by wotkddl21** [thanos-io/thanos#5762]
I'm using thanos-sidecar with prometheus.  
In prometheus pod, there are 3 containers (prometheus, config-reloader, thanos-sidecar)  
Also there are several thanos components. (thanos-store, thanos-compactor, thanos-query, thanos-ruler)  
The thanos-store,compactor, sidecar watch the same s3 object bucket.  
For 2 months, I used a managed s3 object storage.  
According to the csp, there are too many 404 Not Found Errors from the bucket which the thanos-sidecar uploads the blocks to.  
To check the reason, I made a minio s3 storage in my k8s cluster and change the objstore.config of thanos-sidecar and store from managed to minio object storage.  (thanos-compactor watches the old s3 object bucket now)  
And then I traced the calls at the minio console.  
![image](https://user-images.githubusercontent.com/57653556/194221785-77ce5dd9-76ee-4884-90e8-5f34cbd33a1e.png)  
![image](https://user-images.githubusercontent.com/57653556/194222173-3cdd933c-efd5-484b-a43e-bc69be6855f4.png)  

For every 3 minutes, the thanos-sidecar or store causes 404 not found error.
How can I fix it?

prometheus container
  - args:
    - --web.console.templates=/etc/prometheus/consoles
    - --web.console.libraries=/etc/prometheus/console_libraries
    - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
    - --storage.tsdb.path=/prometheus
    - --storage.tsdb.retention.time=10d
    - --web.enable-lifecycle
    - --web.route-prefix=/
    - --web.config.file=/etc/prometheus/web_config/web-config.yaml
    - --storage.tsdb.max-block-duration=2h
    - --storage.tsdb.min-block-duration=2h

config-reloader
- args:
    - --listen-address=:8080
    - --reload-url=http://127.0.0.1:9090/-/reload
    - --config-file=/etc/prometheus/config/prometheus.yaml.gz
    - --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml
    - --watched-dir=/etc/prometheus/rules/prometheus-monitoring-prometheus-rulefiles-0

thanos-sidecar
  - args:
    - sidecar
    - --prometheus.url=http://127.0.0.1:9090/
    - --grpc-address=:10901
    - --http-address=:10902
    - --objstore.config-file=/etc/objstore-config/bucketconfig.yaml
    - --tsdb.path=/prometheus
    - --log.level=info
    - --log.format=logfmt
    - --min-time=-10d

thanos-store
  - args:
    - store
    - --log.level=debug
    - --objstore.config-file=/etc/objstore-config/bucketconfig.yaml
    - --ignore-deletion-marks-delay=1d
    - --grpc-address=0.0.0.0:10901
    - --http-address=0.0.0.0:10902
    - --data-dir=/var/thanos/store

**Comment by yeya24** [comment]
@wotkddl21 Can you share what objects are being requested by the sidecar and get 404? Is it `meta.json` file?

Ideally this shouldn't happen as the sidecar has cache for uploaded metadata. So the 404 will happen once for each block, so should be 2h interval for each prometheus deployment.

**Comment by wotkddl21** [comment]
> @wotkddl21 Can you share what objects are being requested by the sidecar and get 404? Is it `meta.json` file?
> 
> Ideally this shouldn't happen as the sidecar has cache for uploaded metadata. So the 404 will happen once for each block, so should be 2h interval for each prometheus deployment.

@yeya24 How can I get the request that the sidecar made?
The fact that the interval of 404 request should be 2hours is reasonable
But in my case the sidecar makes the 404 error with the 3 minutes of interval
Though I uploaded 2 pictures, the 404 errors from the thanos sidecar were more than 1000

**Comment by yeya24** [comment]
Since you are viewing the Minio console does it have that information? Or maybe you can enable some kind of server side access logs to see if we can get that data?

**Comment by wotkddl21** [comment]
> 

@yeya24 At the Minio console, the information on the screenshot is all (just error code and method without any specific information)
I think I cant get the server side access log

**Comment by wotkddl21** [comment]
I got some server side access log!!!
After changing the object storage from the minio to the ECS, I can get the access log below.
Full target : thanos/01GHENB4SBWDRGZM6R6ZYSAMPJ/deletion-mark.json
protocol: s3
request type: GET

That bucket 01GHENB4SBWDRGZM6R6ZYSAMPJ was created at 2022-11-10 02:00.
The request sent by the thanos store was created at 2022-11-15:16:23

Now my main question is that is there any way to stop thanos store requesting the deletion-mark.json?
( p.s. As far as I know, the amazon s3 always generates the deletion-mark.json but the ECS does not.)

**Comment by wotkddl21** [comment]
In my case, I had stopped the compactor because of the server bug about the ECS s3.
So it leads the block uploaded in the s3 doesn't have deletion-mark.json and no-compaction.json at all.
After I started the compactor, the amount of 404 error per seconds decreased.
In conclusion, that was my bad.
If you want to use thanos architecture (especially the store), don't forget running the compactor
