### ISSUE TITLE
Receive: Ketama replication quorum handling is incorrect

### ISSUE THREAD

**Issue by matej-g** [thanos-io/thanos#5784]
**Thanos, Prometheus and Golang version used**:
Thanos `0.28.0` (present on latest `main` as well)

**What happened**:
When reading through code, I have noticed an issue with how we handle quorum in receive replication. Until now when only single hashing algorithm was available (`hashmod`), the batching mechanism ensured all series from a batch end up on an individual node. This means that for example, with replication factor 3, the replicated requests were being batched in a way that they end up on 3 different replicas, sent in 3 separate requests. 

The way quorum is calculated is based off the formula in https://github.com/thanos-io/thanos/blob/main/pkg/receive/handler.go#L582 and e.g. with replication factor 3, we need to confirm 2 writes succeeded.

With change to `ketama`, the replication batching gets more complex, due to the fact that the series are more dispersed (see changes in https://github.com/thanos-io/thanos/pull/5604). This means that instead of batching into fewer bigger replication requests, we are batching into smaller, "replica-endpoint" requests. The end result is, using again example of replication factor 3, that we have many more requests and series are being written in more than 3 requests (this number will depend on how many replicas there are in the deployment).

The problem is we still determine quorum based on the formula linked above. However, it is incorrect to assume the replication succeeded based on the number calculated from the formula above - with `ketama` hashing, we need more confirmed writes than with `hashmod`, because the series are batched into **larger** number of requests than the replication factor (from which we calculate quorum).

**What you expected to happen**:
I expect, when using `ketama` hashing, the quorum writes are confirmed correctly.

**How to reproduce it (as minimally and precisely as possible)**:
Setup a receiver deployment with `--receive.hashrings-algorithm=ketama` and `--receive.replication-factor=3` and observe the behavior described.

**Anything else we need to know**:
With current way we are batch series for `ketama`, it is not trivial to confirm the quorum, because the combination of endpoints where each individual series might end up is not same for whole batch (as was the case for `hashmod`).

cc @PhilipGough @fpetkovski

**Comment by fpetkovski** [comment]
Thanks for reporting this. I think you are right, quorum calculation is now incorrect!

Maybe the solution would be to revert back to using `replica` as the key, and store the endpoint in the value of the `wreqs` map alongside the `prompb.WriteRequest`?

**Comment by matej-g** [comment]
I'm trying a slightly different approach (based on grouping by endpoint), I'll be back with a PR.

**Comment by matej-g** [comment]
In the end I could not figure out a way to make changes backwards compatible for `ketama` if we switched to endpoint-grouped requests.

Instead I'm trying a different approach to verify quorum by counting successful requests per replica, I'm interested in reviews / opinions. So far all my tests seem to show it works as expected.

https://github.com/thanos-io/thanos/pull/5791

**Comment by bwplotka** [comment]
Thanks everybody! I would really vote for making https://github.com/thanos-io/thanos/issues/5807 work. Let's see if there is some easy solution there (: We can talk on PromCon too!
