### ISSUE TITLE
Support for "Out-of-order"

### ISSUE THREAD

**Issue by kojderszymon** [thanos-io/thanos#5787]
Is there any work related to support for "Out-of-order" samples, similar to what Mimir did - https://github.com/grafana/mimir/pull/1753, planned (due to changes in Prometheus - https://github.com/prometheus/prometheus/pull/11075)?

**Comment by yeya24** [comment]
The code is there and I believe we just need to add a flag to enable OOO samples feature and add some test cases.

**Comment by dextras** [comment]
@yeya24 do you know if there is anybody is working currenlty on this topic and if there is any issue for that?

**Comment by matej-g** [comment]
Hi @dextras, take a look at https://github.com/thanos-io/thanos/pull/5839, this has been now added as experimental feature in Thanos, available on latest `main`. I believe this issue can be closed now.

**Comment by dextras** [comment]
Thanks @matej-g for this information. Indeed the issue can be closed.

**Comment by matej-g** [comment]
I will re-open this for now, as a reminder to add more finishing touches, as it seems we need to ensure we flush the OOO head in receivers. This currently does not happen for the OOO head, only for 'normal' head.

**Comment by saswatamcode** [comment]
@matej-g what is left to complete out of order support? Would love to address this! 🙂

**Comment by GiedriusS** [comment]
We use it in prod and everything works well after the recent fixes. Closing.

**Comment by matej-g** [comment]
@saswatamcode too bad I did not document what's missing, but looks like everything is working as it should, so closing this is fine
