### ISSUE TITLE
Receive: make exemplars storage a flag

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#5789]
### Is your proposal related to a problem?

Right now Thanos Receiver hardcoded `exemplarStorage` to true here https://github.com/thanos-io/thanos/blob/main/cmd/thanos/receive.go#L86.

For users who don't need exemplars at all, this introduces additional overhead on the TSDB side. We should make it configurable to turn on/off for this feature. Even in Prometheus this is not enabled by default.

### Describe the solution you'd like

Add a new flag in Thanos Receiver.

**Comment by yeya24** [comment]
Ah actually for Receiver we can disable exemplar storage by setting max exemplars to 0, which is the default value.
However, in TSDB there is code like this https://github.com/prometheus/prometheus/blob/main/tsdb/head_append.go#L133.

Even if the max exemplar is 0, as long as the flag is enabled then TSDB will allocate a buffer for exemplars. Maybe we should change the logic in the tsdb side to avoid the allocation.

**Comment by flenoir** [comment]
Hi, if we want to activate exemplars, what value could be set for max exemplar ? 
could it be just 1 ? or any specific number ? 

regards

**Comment by yeya24** [comment]
@flenoir Hi, any value that is > 0 can activate exemplars feature, but in that case only 1 exemplar can be kept.

**Comment by fpetkovski** [comment]
Can we disable exemplar storage when exemplars is set to 0?
