### ISSUE TITLE
Query Frontend: Vertical sharding `without` labels is failing to return results

### ISSUE THREAD

**Issue by sdufel** [thanos-io/thanos#5798]
**Thanos, Prometheus and Golang version used**: Latest main (35a3e3d58217fed35e83f72c913f55b633ad444a)

**Object Storage Provider**: GCS

**What happened**:
When running queries which make use of the `ignoring` keyword for vector matching through a query frontend which has vertical sharding enabled, no results are returned.

**What you expected to happen**:
The results of the query should return as expected.

**How to reproduce it (as minimally and precisely as possible)**:
Run a single query frontend with vertical sharding enabled, queriers, and some kind of store

Run a query-frontend with vertical sharding enabled
Given two series which differ in labels only by name and one label, construct any vector match query using the `ignoring`
keyword:
```
# foo{pod="pod1", lbl="a"} 1
# bar{pod="pod1", lbl="b"} 1

foo and ignoring(lbl) bar
```
The query will return no results, even if there are the requisite series on each side of the `and` operator.

The version of this query using inclusion rather than exclusion does work:
```
foo and on (pod) bar
```
This will return the expected results

**Comment by yeya24** [comment]
Thanks!
I am not sure if this case would be covered by the PromQL compliance test, but at least we should enable the PromQL test somehow (maybe daily) to make sure it works as expected.
