### ISSUE TITLE
Query: Does Thanos query priorityze between Sidecar over Storegateway?

### ISSUE THREAD

**Issue by druanoor** [thanos-io/thanos#5800]
Hi.

Does Thanos Query prioritize Sidecar store over Storegateway Store when they both share the serving time partition?

![image](https://user-images.githubusercontent.com/51286702/196713730-10ab426f-88cc-4a57-b74b-239de0be49d6.png)

**Comment by yeya24** [comment]
I think this question has been answered in Slack already https://cloud-native.slack.com/archives/CK5RSSC10/p1666188108476609 so close now.
