### ISSUE TITLE
Thanos querier not deduplicating properly against statsd_exporter metrics

### ISSUE THREAD

**Issue by mazad01** [thanos-io/thanos#5812]
**Thanos, Prometheus and Golang version used**: Thanos 0.28.1, Prometheus 2.39.1, go1.18.7

**What happened**: We have a thanos querier that is serving 2 prometheus replicas. Each prometheus replica has its own statsd_exporter. After sending a metric with the same name to our statsd_exporter endpoint (which then prometheus scrapes), we can see the metric lines (from each replica respectively). After clicking dedupe in the UI, it only shows the data points from one of the replicas (not both). 

**What you expected to happen**: The metrics to be viewed as a single line that is an aggregation across both replicas.

**Comment by mazad01** [comment]
Here is a screenshot of the lines of the metrics when dedupe is disabled. You can see both replicas having its own line.
![Capture4](https://user-images.githubusercontent.com/7851832/197287933-28a477ed-6bc0-4718-aeff-edb1dac41fd9.PNG)

Here is when dedupe is checked in the UI. The line isnt aggregated, and it looks like only metrics from one of the replicas was chosen.


![Capture5](https://user-images.githubusercontent.com/7851832/197288037-063b4830-fa31-47ea-83b6-3229cb109ddc.PNG)

And yes I'm running the `--query.replica-label` param to use `oaas_replica` as the value (since that is the names of our prometheus replicas

**Comment by yeya24** [comment]
I think that's expected. 
The two Prometheus instances are not really replicas of each other since they have their own statsd exporters and different data. Thanos deduplication just simply picks one sample over the two.

I don't think it is a bug. If the data differs between 2 replicas then you need to have a way to aggregate the data somehow.

**Comment by matej-g** [comment]
I'd agree with what @yeya24 said, deduplication simply means picking one replica over the other, so this should be a non-issue.
