### ISSUE TITLE
support s3 storage class

### ISSUE THREAD

**Issue by yanglaoshi666** [thanos-io/thanos#5813]
Deployment version 0.28.1 supports S3 storage class from the deployment document, but the log does prompt that user-defined class name is not supported. Is there no merging issues #5663?

**Comment by yeya24** [comment]
@yanglaoshi666 Can you share the error from the logs?

**Comment by yanglaoshi666** [comment]
type: S3
prefix: monitor
config:
  endpoint: s3.us-west-2.amazonaws.com
  region: us-west-2
  bucket: thanos
  put_user_metadata:
    X-Amz-Storage-Class: STANDARD_IA
  trace:
    enable: false
  part_size: 67108864
  bucket_lookup_type: auto




thanos, version 0.28.1 (branch: HEAD, revision:
41a8ce61c90734b81986b273e154e96358333f92)
  build user:       ***@***.***
  build date:       20221006-18:35:08
  go version:       go1.18.7
  platform:         linux/amd64



./thanos tools bucket verify --objstore.config-file
/opt/soft/thanos/bucket.yml
level=info ts=2022-10-23T10:32:37.065050661Z caller=factory.go:50
msg="loading bucket configuration"
level=info ts=2022-10-23T10:32:37.065455716Z caller=verify.go:138
verifiers=overlapped_blocks,index_known_issues msg="Starting verify task"
level=info ts=2022-10-23T10:32:37.065481539Z caller=overlapped_blocks.go:29
verifiers=overlapped_blocks,index_known_issues verifier=overlapped_blocks
msg="started verifying issue"
level=info ts=2022-10-23T10:32:37.140614763Z caller=fetcher.go:470
component=block.BaseFetcher msg="successfully synchronized block metadata"
duration=75.121239ms duration_ms=75 cached=0 returned=0 partial=0
level=info ts=2022-10-23T10:32:37.140647151Z caller=index_issue.go:33
verifiers=overlapped_blocks,index_known_issues verifier=index_known_issues
msg="started verifying issue" with-repair=false
level=info ts=2022-10-23T10:32:37.152681143Z caller=fetcher.go:470
component=block.BaseFetcher msg="successfully synchronized block metadata"
duration=12.01551ms duration_ms=12 cached=0 returned=0 partial=0
level=info ts=2022-10-23T10:32:37.152720623Z caller=index_issue.go:75
verifiers=overlapped_blocks,index_known_issues verifier=index_known_issues
msg="verified issue" with-repair=false
level=info ts=2022-10-23T10:32:37.152739226Z caller=verify.go:157
verifiers=overlapped_blocks,index_known_issues msg="verify task completed"
level=info ts=2022-10-23T10:32:37.1528897Z caller=main.go:161 msg=exiting



./thanos tools bucket ls   --objstore.config-file
/opt/soft/thanos/bucket.yml
level=info ts=2022-10-23T10:31:14.225461216Z caller=factory.go:50
msg="loading bucket configuration"
level=info ts=2022-10-23T10:31:14.295705989Z caller=fetcher.go:470
component=block.BaseFetcher msg="successfully synchronized block metadata"
duration=69.844741ms duration_ms=69 cached=0 returned=0 partial=0
level=info ts=2022-10-23T10:31:14.295741342Z caller=tools_bucket.go:462
msg="ls done" objects=0
level=info ts=2022-10-23T10:31:14.295872508Z caller=main.go:161 msg=exiting





upload s3 object: X-Amz-Storage-Class unsupported user defined metadata
name" uploaded=0


cat thanos.shipper.json
{
        "version": 1,
        "uploaded": null
}


When I use STANDARD S3, I can upload successfully


Ben Ye ***@***.***> 于2022年10月23日周日 14:53写道：

**Comment by yanglaoshi666** [comment]
monitor16 thanos[22211]: level=warn ts=2022-10-23T14:20:39.034692132Z caller=sidecar.go:345 err="upload 01GG2FT5H6R0WENDPT9R8EET9G: upload chunks: upload file /opt/soft/prometheus/data/thanos/upload/01GG2FT5H6R0WENDPT9R8EET9G/chunks/000001 as 01GG2FT5H6R0WENDPT9R8EET9G/chunks/000001: upload s3 object: X-Amz-Storage-Class unsupported user defined metadata name" uploaded=0

**Comment by yanglaoshi666** [comment]
upgrade 0.29.0 fixed

**Comment by yeya24** [comment]
Yeah this feature is added in v0.29.x.
