### ISSUE TITLE
Could you add the "last_value" and "duration" to "ALERTS" ?

### ISSUE THREAD

**Issue by X-Mars** [thanos-io/thanos#5815]
### Is your proposal related to a problem?

Could you add the "last_value" and "duration" to "ALERTS" ?

### Describe the solution you'd like

None

### Describe alternatives you've considered

None

### Additional context

None

**Comment by X-Mars** [comment]
@nikzayn  Hi, maybe i can't do it....
<img width="1354" alt="QQ20221029-212610@2x" src="https://user-images.githubusercontent.com/18095822/198834095-80e7163b-a05d-4e52-a199-51da5b1988c3.png">

**Comment by matej-g** [comment]
Hi @nikzayn no need for assigning, feel free to work an issue. Although I'd first like some better description from @X-Mars, it's not obvious to me what exactly is being requested here and why?

**Comment by X-Mars** [comment]
Hi @matej-g , I can got alerts list by 'ALERTS', but it doesn't have "last value / start time / duration time".
Thanks for your help.
![QQ20221031-172426](https://user-images.githubusercontent.com/18095822/198975855-90b99d83-0f01-4b57-ac56-f64f245f155f.png)

**Comment by yeya24** [comment]
I think this is some feature request for Prometheus instead as Thanos is just using Prometheus library for this.

**Comment by matej-g** [comment]
I'd agree with @yeya24, I think if so, then it should be taken upstream to Prometheus. I'll close this for now.
