### ISSUE TITLE
Receive: very verbose logging

### ISSUE THREAD

**Issue by fpetkovski** [thanos-io/thanos#5825]
**Thanos, Prometheus and Golang version used**: 
thanosio/thanos:main-2022-10-07-a4e33415

**What happened**:
Thanos receivers now use the store proxy to fan out to different TSDBs. This leads to very verbose warn logs in the form of:
```
Store ... filtered out: does not have data within this time period
```

**What you expected to happen**:
I would expect such logs to have a debug level, or not be emitted at all.

**Comment by kama910** [comment]
@fpetkovski hello, may I work on this issue?

**Comment by fpetkovski** [comment]
Sure, I will assign it to you.
