### ISSUE TITLE
Getting "vector cannot contain metrics with the same labelset" while querying large data

### ISSUE THREAD

**Issue by Nikhils09** [thanos-io/thanos#5830]
**Thanos and Prometheus version**:
**Thanos**: 0.28.1
**Prometheus**: 2.38.0

**Object Storage Provider**: S3

**What happened**: I'm using Prometheus and Thanos to Monitor Jira, when I try to query large data using **sum** or **rate** it gives me:
```
Error executing query: vector cannot contain metrics with the same labelset

```

**How to reproduce it (as minimally and precisely as possible)**: Here's the one of the query in which I'm getting the issue:
```
sum(increase(jira_user_login_count_total{job="job_name"}[1h]))
```

**Environment**:
- OS :  Ubuntu 20.04.5

**Comment by yeya24** [comment]
Please let us know your Thanos setup first. @Nikhils09

**Comment by fpetkovski** [comment]
This looks like duplicate series ended up in the engine. I wonder if you configured any replica labels in the querier.

**Comment by Nikhils09** [comment]
Hi @fpetkovski, I was running Prometheus and Thanos on AWS EC2, seems like it's some issue with Prometheus external labels, I was passing instance_id in it, although data was uploading successfully on S3 but it was throwing **Label issues** in Grafana, I fixed it by changing labels to something like this:
```
global:
  scrape_interval: 1m
  evaluation_interval: 1m
  external_labels:
    cluster: monitoring-dev
    replica: 0
```

**Comment by fpetkovski** [comment]
That's great, thanks for sharing your config. Is it safe to close this issue now?

**Comment by Nikhils09** [comment]
Sorry for responding late, you can close this.
