### ISSUE TITLE
Three levels tutorial: Basic setup, Long Term Storage, Alerting.

### ISSUE THREAD

**Issue by jturolla** [thanos-io/thanos#584]
Hi all, I'm interested in building a 3 level setup tutorial on getting started with Thanos. Understanding all the components took me some time once I started evaluating Thanos, and I believe we can benefit from more adoption and contributors by making it easier for newcomers. Now that  at my company we're handling an infrastructure with about 20 Prometheus and long term retention I feel I can contribute to that.

This would cover the 3 scenarios to deploy Thanos:

1. **Basic Setup** - allows you to query against multiple Prometheus, without long term retention.
2. **Long term retention** - allows you the same as the basic setup, but introduces block storage to increase your retention arbitrately, will cover compaction and bucket management.
3. **Alerting** - allows you to alert against data from multiple Prometheus.

As a bonus, I'm planning on bringing new kubernetes manifests with statefulsets and deployment of all the resouces.

This would also allow to clean up the docs to remove references to gossip.

I'm already working on that and should have a PR early next week, if you have any comments please reach me.

### Pros: 

- Will make Thanos easier for newcomers, understanding the multiple components is usually an issue for the ramp up.
- Consolidate the getting started guide with current developments and do a much needed docs update;
-  Removes outdated references to deprecated concepts from docs that sometimes distract people.

### Cons: 

- None? 🤷‍♀️

**Comment by bwplotka** [comment]
That would be great, thanks!

**Comment by wangchengxxxin** [comment]
Cool while I do not make it clear after 1 day to set sidecar and query within 2 Prometheus. Hope your PR.

**Comment by jturolla** [comment]
I apologise for the delays, I'll find the time to develop this asap. Thanks
for the interest.

**Comment by ashish-yad** [comment]
That will be really helpful, as I'm struggling to set up long-term retention thing.

**Comment by GiedriusS** [comment]
Perhaps this could be considered done as we have Katacoda tutorials, @bwplotka @jturolla? (:

**Comment by jturolla** [comment]
Sure, thanks.

**Comment by daixiang0** [comment]
Now Katacoda tutorials cover basic setup, and docs cover long term storage and alerting.
@jturolla do you think they are enough, or maybe in a better place?

**Comment by bwplotka** [comment]
Yes, this should be solved with Katacoda tutorials. (:
