### ISSUE TITLE
Compaction TODO metrics have too high a cardinality

### ISSUE THREAD

**Issue by SuperQ** [thanos-io/thanos#5841]
**Thanos, Prometheus and Golang version used**:

Thanos v0.28.1

**Object Storage Provider**:

N/A

**What happened**:

The metrics `thanos_compact_todo_compactions`, `thanos_compact_todo_downsample_blocks`, etc include a `group` label that can make the cardinality of the metric reach thousands in large deployments. This label doesn't provide a lot of value.

**What you expected to happen**:

Remove the `group` label from compaction TODO metirics.

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by yeya24** [comment]
Almost all the compaction metrics have the label `group`, right? Why it is an issue for the TODO metrics?

**Comment by Akshit42-hue** [comment]
Working on it :)

**Comment by yeya24** [comment]
> I have a WIP change to remove group label from all of the compactor metrics if people find this acceptable.

I think it is still valuable to have a label to identify each compaction group so that we can identify some key metrics like failutres.
Unfortunately the current label `group` is not a good identifier cause I cannot tell which cluster/tenant it is from the given label hash.

**Comment by SuperQ** [comment]
Metrics should identify when there are compaction failures worth investigating. The actual identity of what is failing can be determined from the logs.

**Comment by yeya24** [comment]
Let's do it. I think we should remove this label as the hash doesn't mean anything. However, I am wondering if we should still keep the downsampling information as another label.

**Comment by SuperQ** [comment]
Downsample resolution sounds like a useful label.
