### ISSUE TITLE
Thanos with Scaleway S3 objstore - The XML you provided was not well-formed

### ISSUE THREAD

**Issue by kladiv** [thanos-io/thanos#5857]
Hi here,
i need your support for the error below from thanos-sidecar.

- I installed `kube-prometheus-stack` with `thanos-sidecar` enabled (quay.io/thanos/thanos:v0.28.1)
- I created the `thanos-objstore-config` with contents below:

```
apiVersion: v1
kind: Secret
type: Opaque
data:
  objstore.yml: dHl.......NmEK
```

the base64 is:

```
type: S3
config:
  bucket: thanos-storage
  endpoint: s3.nl-ams.scw.cloud
  region: nl-ams
  access_key: SCW...
  secret_key: ...
```

and in kube-prometheus-stack i defined:

```
  prometheusSpec:
    thanos:
      objectStorageConfig:
        name: thanos-objstore-config
        key: objstore.yml
```

If i look at thanos-sidecar logs i see:

```
level=info ts=2022-11-03T07:59:20.899986877Z caller=shipper.go:334 msg="upload new block" id=01GGTG5BMR6EKD2XFCQWAE32A7
level=warn ts=2022-11-03T07:59:23.59810388Z caller=sidecar.go:345 err="upload 01GGTG5BMR6EKD2XFCQWAE32A7: upload chunks: upload file /prometheus/thanos/upload/01GGTG5BMR6EKD2XFCQWAE32A7/chunks/000001 as 01GGTG5BMR6EKD2XFCQWAE32A7/chunks/000001: upload s3 object: The XML you provided was not well-formed or did not validate against our published schema." uploaded=0
level=info ts=2022-11-03T07:59:50.90297074Z caller=shipper.go:334 msg="upload new block" id=01GGTG5BMR6EKD2XFCQWAE32A7
level=warn ts=2022-11-03T07:59:53.371073167Z caller=sidecar.go:345 err="upload 01GGTG5BMR6EKD2XFCQWAE32A7: upload chunks: upload file /prometheus/thanos/upload/01GGTG5BMR6EKD2XFCQWAE32A7/chunks/000001 as 01GGTG5BMR6EKD2XFCQWAE32A7/chunks/000001: upload s3 object: The XML you provided was not well-formed or did not validate against our published schema." uploaded=0
```

This is another log in debug mode:

```
level=debug ts=2022-11-03T19:18:00.312494604Z caller=stdlib.go:105 s3TraceMsg=---------START-HTTP---------
level=debug ts=2022-11-03T19:18:00.312609801Z caller=stdlib.go:105 s3TraceMsg="HEAD /jetdeploy-thanos-storage/01GGZCKBNP36D3NF8BW499QBR2/deletion-mark.json HTTP/1.1\r\nHost: s3.nl-ams.scw.cloud\r\nUser-Agent: MinIO (linux; amd64) minio-go/v7.0.37 thanos-sidecar/0.28.1 (go1.18.7)\r\nAuthorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20221103/nl-ams/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**\r\nX-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\r\nX-Amz-Date: 20221103T191800Z\r\n\r"
level=debug ts=2022-11-03T19:18:00.3126362Z caller=stdlib.go:105 s3TraceMsg="HTTP/1.1 404 Not Found\r\nContent-Type: application/xml\r\nDate: Thu, 03 Nov 2022 19:18:00 GMT\r\nX-Amz-Id-2: txa38f0b76d4184abc883b5-00636413e8\r\nX-Amz-Request-Id: txa38f0b76d4184abc883b5-00636413e8\r\nContent-Length: 0\r"
level=debug ts=2022-11-03T19:18:00.31264929Z caller=stdlib.go:105 s3TraceMsg=---------END-HTTP---------
level=warn ts=2022-11-03T19:18:00.312847265Z caller=sidecar.go:345 err="upload 01GGZCKBNP36D3NF8BW499QBR2: upload chunks: upload file /prometheus/thanos/upload/01GGZCKBNP36D3NF8BW499QBR2/chunks/000001 as 01GGZCKBNP36D3NF8BW499QBR2/chunks/000001: upload s3 object: Content-Type unsupported user defined metadata name" uploaded=0
```

Can you support me on this error?
I use Scaleway S3 Object Storage

Thank you

**Comment by alex5517** [comment]
I have the same issue with HCP for Cloud Scale for multipart uploads.

Hitachi uses the same xsd as AmazonS3 - What I suspect is that they are running in strict mode where Amazon S3 does not. 

Logs from HCP-CloudScale:
`2022-11-01 10:03:31.739 WARN [http-nio-80-exec-2] S3ObjectUtils XML '<CompleteMultipartUpload xmlns=""><Part xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><PartNumber>1</PartNumber><ETag>5f0cc9778afe6dc19dc364e2673f8d03</ETag></Part><Part xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><PartNumber>2</PartNumber><ETag>bf2ebedc90103f013f7e95f8abc10e5f</ETag></Part></CompleteMultipartUpload>' failed to validate against S3CompleteMultipartUploadRequest.xsd
`

From Amazon Docs it seems that the request syntax should be different.
https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html

Seems Thanos is not inserting xmlns here:
`<CompleteMultipartUpload xmlns=""`
But it is inserting within the part? - Based on Amazon docs, this is not the correct way to do it.

**Comment by kladiv** [comment]
Maybe the issue can be similar to one below?
https://community.cloudflare.com/t/r2-multipart-uploads-not-working-with-minio-client/396536/14

**Comment by alex5517** [comment]
Seems like it could be fixed in newer version of mino-go client.
https://github.com/minio/minio-go/issues/1702

**Comment by kladiv** [comment]
What version of minio-go use Thanos (0.28.1 or 0.29.0) ?

**Comment by matej-g** [comment]
We're on [`7.0.37`](https://github.com/thanos-io/thanos/blob/main/go.mod#L55), so if this really as easy as bumping the version, might be quick fix?

**Comment by kladiv** [comment]
![Screenshot_20221104-230831](https://user-images.githubusercontent.com/1803926/200082429-a77d9745-01f7-4878-aa98-b2ec7b9a1248.png)
According to Scaleway discussion (in their Slack channel) it seems quite long they will support missing fields and resolve the issue (i guess).

Are you able to solve the issue in Thanos implementation of minio-go library ?

**Comment by kladiv** [comment]
Hi @matej-g 
in the [minio-io issue](https://github.com/minio/minio-go/issues/1702) they talk about the problem starts from v. 7.0.37.

The _objstore go.mod_ you linked is pinnee to a previous version, but the [Go.mod](https://github.com/thanos-io/thanos/blob/main/go.mod#L55) in the _main/_ is pinned to 7.037.

They both need to be upgraded?

**Comment by matej-g** [comment]
Hey @kladiv, since the actual object storage code has been recently separated and put into the https://github.com/thanos-io/objstore, so version that's pinned there should be the decisive one. It looks like we use `minio-go` in the main Thanos repository only for some auxiliary methods.

So if we this issue is supposed to be present only starting from `7.0.37`, it should not be in the object storage _yet_. Either way it could not hurt to update the package version to the latest release.

**Comment by metalmatze** [comment]
Just updated my Thanos yesterday as well and ran into this. Let me see if updating the dependency and running the newer compator with this will help.

**Comment by yeya24** [comment]
I will close this one since https://github.com/thanos-io/thanos/pull/5867 has been merged. We just need to release the `29.1` version including this fix.

**Comment by metalmatze** [comment]
@GiedriusS, do you plan on releasing v0.29.1 soon-ish?

**Comment by filippog** [comment]
I've been hit by the same issue (i.e. minio-go breaking on S3-compatible storage), when can we expect 0.29.1 to be released? thank you!
