### ISSUE TITLE
Thanos query server can not show graph with data from a replica

### ISSUE THREAD

**Issue by jackyym** [thanos-io/thanos#587]
thanos: v0.1.0-rc.2
prometheus: v2.3.2

I have tow prometheus instances(replica A & replica B) on tow nodes  and startup them in docker.
The prometheus(replica B) started to pull metric data from a exporter and  a few days later I start 
prometheus(replica A) to pull this metric data.But now I get graph from query server web ui like this:
![image](https://user-images.githubusercontent.com/7010223/47344941-33805e00-d6dc-11e8-8e55-5551c02be510.png)
The first half graph is from replica B and the second half from A but the middle part is missing.
The graph from prometheus( replica B):
![image](https://user-images.githubusercontent.com/7010223/47344757-c240ab00-d6db-11e8-9bd3-b16c96cc7744.png)
The graph from prometheus( replica A):
![image](https://user-images.githubusercontent.com/7010223/47344798-dc7a8900-d6db-11e8-9cd0-2b53258c9ac4.png)
I think the missing part should load from prometheus(replica B).

I also config the ttl as "--storage.tsdb.retention=8760h" with all prometheus instances.

**Comment by bwplotka** [comment]
Hey, you have only Global view, no object storage yet, right? What Thanos UI (querier) shows with deduplication being off (deduplication button)

**Comment by jackyym** [comment]
@bwplotka 
hi~ yes, I only use the prometheus local storage and the graph  with deduplication being off  is:
![image](https://user-images.githubusercontent.com/7010223/47362889-106ba380-d708-11e8-9ee5-c9248846d876.png)
The graph  with deduplication being on is:
![image](https://user-images.githubusercontent.com/7010223/47362975-43ae3280-d708-11e8-8b46-108e40c80d9f.png)

**Comment by domgreen** [comment]
It does not look like deduplication is being run in the first screen shot so this could be a configuration issue. Could you send the config / params specifically about ound the query node.

**Comment by jackyym** [comment]
@domgreen 
yes, in the first screen I forgot to click the deduplication button and the last tow was correct.
I have 3 nodes for thanos cluster:sidecarA , sidecarB,  querynode and I just run "docker run ......" without config file for thanos.

I run command on sidecarA deployed against prometheus(replica A):
sudo docker run --network=host -d  xxxx/thanos:v0.1.0-rc.2 sidecar --prometheus.url http://localhost:9090 --tsdb.path /mnt/promdata --grpc-address 0.0.0.0:19091 --cluster.address 0.0.0.0:19391 --cluster.peers $(querynode):19391 --http-address 0.0.0.0:19191

run command on sidecarB deployed against prometheus(replica B):
sudo docker run --network=host -d  xxxx/thanos:v0.1.0-rc.2 sidecar --prometheus.url http://localhost:9090 --tsdb.path /mnt/promdata --grpc-address 0.0.0.0:19091 --cluster.address 0.0.0.0:19391 --cluster.peers $(sidecarA):19391 --http-address 0.0.0.0:19191

run command on querynode:
sudo docker run --network=host -d  xxxx/conviva/thanos:v0.1.0-rc.2 query --http-address 0.0.0.0:19192 --grpc-address 0.0.0.0:19092 --cluster.address 127.0.0.1:19391  --cluster.peers $(sidecarB):19391 --query.replica-label replica

**Comment by jackyym** [comment]
@domgreen 
By the way I look into the souce code and I saw a test case:
![image](https://user-images.githubusercontent.com/7010223/47473057-9b04ed80-d843-11e8-9348-98dc443ea9a3.png)
In my case the gap between replica A and  replica B can be a few days. Maybe these sample datas are ignored by the deduplication strategy.

**Comment by jackyym** [comment]
done

**Comment by GiedriusS** [comment]
Could you elaborate more, @jackyym? Sorry for the late response, this one fell through the cracks.
