### ISSUE TITLE
All: Include examples in all documentation

### ISSUE THREAD

**Issue by jdfalk** [thanos-io/thanos#594]
thanos, version 0.1.0 (branch: HEAD, revision: 301925295dc9b2fd82942cd4165cf19ad8fe55e5)
  build user:       jenkins@build
  build date:       20181021-04:24:29
  go version:       go1.10.3

**What happened**
Thanos help should display examples for each option.  For instance:
`--alert.query-url=ALERT.QUERY-URL    The external Thanos Query URL that would be set in all alerts 'Source' field` 
What format should the URL be in? Should it accept `http://` or just be `alert.foo.bar` 

`--query=<query> ...        Addresses of statically configured query API servers (repeatable).`
Should that be a full ip and port? Just an IP? 

The documentation is inconsistent in documenting usable examples.

**Comment by bwplotka** [comment]
Valid issue.

**Comment by daixiang0** [comment]
@bwplotka still need this?
