### ISSUE TITLE
Allow removing markers from object storage

### ISSUE THREAD

**Issue by fpetkovski** [thanos-io/thanos#5946]
### Is your proposal related to a problem?

The `thanos tools bucket mark ` command can only create new markers at the moment. It would be nice to allow it to also remove existing markers from object storage.

One use case is removing no-compaction markers which the Compactor adds when it estimates that the new block's index size will exceed the configured limit. An admin can increase the limit and remove this markers to retry compacting those blocks.

### Describe alternatives you've considered

An alternative is to have a custom script, but this defeats the purpose of having a thanos tools package.

**Comment by maheshbaliga** [comment]
Hi @fpetkovski, I will start working on this issue. I will need some help, since this will be my first issue here. Will get back with questions, if any. Thanks.
