### ISSUE TITLE
Fix link sharing with stores filtering

### ISSUE THREAD

**Issue by GiedriusS** [thanos-io/thanos#5951]
Parameter `g0.store_matches` appears in the URL but it is ignored by the UI. React code should use that parameter to enable filtering on the given StoreAPIs. 

How to reproduce?
- Start Query and enable filtering in the UI;
- Select some StoreAPIs and see `g0.store_matches` appear in the URL
- Open that URL
- See that store filtering doesn't apply

**Comment by haru-02** [comment]
hey @GiedriusS , i would like to work on this issue. I forked the repo and I am trying to set up a local dev environment. I followed these steps here to set up a local setup.

https://github.com/thanos-io/thanos/blob/12d48d86586a0da6e0c98845a4759d954f20f264/CONTRIBUTING.md#pull-request-process

How can i run and view the ui so that i can gain a better understanding ? can you please guide me on that ? thank you so much.

**Comment by GiedriusS** [comment]
Sorry for closing, fat fingers. Thanks for your interest! Have you seen the instructions at https://github.com/thanos-io/thanos/tree/main/pkg/ui/react-app? Typically you would want to start up Thanos Query independently and then run the React app as a separate process using the instructions. Then you can edit the UI code and see the changes live. Let me know if this helps

**Comment by haru-02** [comment]
thank you. I will check this link and try it.

**Comment by haru-02** [comment]
hey i got the front end ui running. We have to start up thanos query by running `make web-serve` on the thanos directory right ?

**Comment by GiedriusS** [comment]
You can try using https://github.com/thanos-io/thanos/blob/main/scripts/quickstart.sh or https://github.com/thanos-community/thanos-docker-compose to start up a sample Thanos environment. Have you seen them?

**Comment by haru-02** [comment]
thanks, will look into it :+1:

**Comment by ShivamTyagi12345** [comment]
Hi , Is this issue available? I would love to take this up @GiedriusS

**Comment by GiedriusS** [comment]
Yep, I think @haru-02 has disappeared somewhere. Feel free to pick this up!

**Comment by PradyumnaKrishna** [comment]
Hey @GiedriusS, I would like to work on this issue.

**Comment by ShivamTyagi12345** [comment]
Yes @PradyumnaKrishna please go ahead
