### ISSUE TITLE
Enable bootstraping stores outside of the main repo

### ISSUE THREAD

**Issue by fpetkovski** [thanos-io/thanos#5965]
### Is your proposal related to a problem?

I am currently exploring the possibility to expose Stackdriver metrics through the Thanos store API. I tried to create a new store as a separate project, but generating the necessary protobuf and gRPC stubs was quite challenging and required a lot of hacking and scripting.

### Describe the solution you'd like

It would be nice if we had a simple way to bootstrap a new project that implements the Store API. It could unlock some interesting use cases where we can use Thanos to query data from various external services.

### Describe alternatives you've considered

Right now my toy project is part of Thanos itself, but I don't think integrating everything in the main repo is a viable solution.

### Additional context

It actually works:

<img width="1053" alt="Screenshot 2022-12-14 at 09 03 14" src="https://user-images.githubusercontent.com/1286231/207539836-cb26aa48-58b4-42e8-ab1e-a8cc77b459e6.png">

**Comment by yeya24** [comment]
What's the proposed solution for this? Isn't it as easy as implementing the Store API itself? Like how https://github.com/G-Research/geras does.

**Comment by fpetkovski** [comment]
In theory yes, but generating the gRPC and protobuf stubs is quite challening outside of the main repo. Also keeping up to date with changes can be cumbersome. Ideally there should be a command/script that we can run to bootstrap a store.

I was thinking we could use something like buf.io for distributing the proto files.
