### ISSUE TITLE
[tools] bucket cleanup does not delete blocks in Azure Storage Backend

### ISSUE THREAD

**Issue by verejoel** [thanos-io/thanos#5968]
**Thanos, Prometheus and Golang version used**:
thanos, version 0.29.0 (branch: HEAD, revision: 194e1fadf4302341a0c70c28c0e3f3c658616c19)
  build user:       root@a0c7bba6c208
  build date:       20221103-14:28:25
  go version:       go1.19.3
  platform:         linux/amd64

**Object Storage Provider**: Azure @vglafirov

**What happened**: After marking blocks for deletion and running `thanos tools bucket cleanup`, marked blocks are still present in the storage backend.

**What you expected to happen**: Blocks marked with 'deletion-mark.json' should be removed when `thanos tools bucket cleanup` is run.

**How to reproduce it (as minimally and precisely as possible)**:
 1. Stop compactor.
 1. Find a block ID to delete in Azure Storage container
 1. `export BLOCK=<block-id-to-delete>`
 1. `thanos tools bucket mark --objstore.config-file=/path/to/objstoreconfig.yaml --id=$BLOCK --marker=deletion-mark.json --details="overlapping blocks"`
 1. Verify that `deletion-mark.json` has been added to the specified block in the storage backend.
 1. `thanos tools bucket cleanup --objstore.config-file=/path/to/objstoreconfig.yaml`
 1. Observe that the marked block has not been deleted from backend storage.

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by yeya24** [comment]
Did you see any error logs while running the cleanup tool?

**Comment by yeya24** [comment]
Nvm I think I got it. You need to set `delete-delay` when running the cleanup command. The default delay is 48h so blocks marked for deletion need to wait 2d. You can set the value to 0 while running the cleanup tool to delete those blocks immediately.

**Comment by verejoel** [comment]
Hey @yeya24 thank you, I was missing this. Sorted now!
