### ISSUE TITLE
thanos compactor fails with `populate block: chunk iter: cannot populate chunk 8: segment index 0 out of range`

### ISSUE THREAD

**Issue by mateuszdrab** [thanos-io/thanos#5978]
**Thanos, Prometheus and Golang version used**: thanos:0.29.0

**Object Storage Provider**: s3/minio

**What happened**:

Similarly to issue https://github.com/thanos-io/thanos/issues/1300, I've had too little storage assigned to the compactor so it built a big backlog and only started processing it after expansion of the volume yesterday. However, overnight, it halted due to the error below and restarting the compactor reproduces the same exact error message with the same blocks.

**What you expected to happen**:
Compact or skip and continue with the rest of the backlog. There are still over 300 compactions in the todo, and about half has been done

**How to reproduce it (as minimally and precisely as possible)**:
Not sure

**Full logs to relevant components**:
```
level=error ts=2022-12-18T03:30:59.254203234Z caller=compact.go:488 msg="critical error detected; halting" err="compaction: group 0@16259223971946823639: compact blocks [/data/compact/0@16259223971946823639/01GGM8RSMD74KF170SH7VJKGKE /data/compact/0@16259223971946823639/01GGMFMH57QV6C6GJ45MAH49EN /data/compact/0@16259223971946823639/01GGMPG8DMKVJVJMWAP97M84R5 /data/compact/0@16259223971946823639/01GGMXBZP09041HM47Y47HDXQJ]: populate block: chunk iter: cannot populate chunk 8: segment index 0 out of range"
```

**Comment by mateuszdrab** [comment]
> Do you have a retention policy configured in the compactor or in the bucket itself? 
> 
> 
> 
> As a workaround, you might want to add a no-compact mark to the blocks for which compaction fails so that the compactor can get unstuck.

Hi @fpetkovski 

Thanks for replying

I configured the retention on the compactor, not the bucket.

I suspect the issue could be due to partial upload or a corrupted block, but I'm not sure how to verify.

I do I mark the block as do not compact?

Another thing is, the error mentions a few blocks I think, so it's hard to tell which one is an actual issue.

**Comment by fpetkovski** [comment]
> I configured the retention on the compactor, not the bucket.

Could the retention kick in while blocks are getting uploaded?

> I do I mark the block as do not compact?
Another thing is, the error mentions a few blocks I think, so it's hard to tell which one is an actual issue.

You can use the `thanos tools mark` command for this: https://thanos.io/tip/components/tools.md/#bucket-mark and mark all blocks reported in that error.

**Comment by mateuszdrab** [comment]
@fpetkovski upon browsing minio looking for the chunks mentioned in the error, I found that there was a chunk `01GGMXBZP09041HM47Y47HDXQJ` that did not have a chunks directory, just meta.json and index so I deleted the chunk and compaction resumed. Must have been an incomplete upload. 
Would be nice if Thanos could flag and continue with other blocks or even delete such chunks (the chunk was dated over a month ago).

**Comment by pjastrzabek-roche** [comment]
We have the same issue in one bucket, but there are a lot of chunks like this, so deleting them one by one did not help.
Is there some way to find all broken chunks and mark them all at once?

**Comment by pjastrzabek-roche** [comment]
We have the same issue in one bucket, but there are a lot of chunks like this, so deleting them one by one did not help.
Is there some way to find all broken chunks and mark them all at once?

**Comment by mateuszdrab** [comment]
> We have the same issue in one bucket, but there are a lot of chunks like this, so deleting them one by one did not help.
> 
> Is there some way to find all broken chunks and mark them all at once?
> 
> 

Have you tried https://thanos.io/tip/components/tools.md/#bucket-verify ?

**Comment by pjastrzabek-roche** [comment]
Thanks for the tip.
Problematic chunk looks like this
```
level=debug ts=2023-01-16T01:32:32.303097377Z caller=index_issue.go:140 verifiers=overlapped_blocks,index_known_issues verifier=index_known_issues stats="{TotalSeries:49338 OutOfOrderSeries:0 OutOfOrderChunks:0 DuplicatedChunks:0 OutsideChunks:0 CompleteOutsideChunks:0 Issue347OutsideChunks:0 OutOfOrderLabels:0 SeriesMinLifeDuration:0s SeriesAvgLifeDuration:865ms SeriesMaxLifeDuration:15.001s SeriesMinLifeDurationWithoutSingleSampleSeries:14.656s SeriesAvgLifeDurationWithoutSingleSampleSeries:14.976s SeriesMaxLifeDurationWithoutSingleSampleSeries:15.001s SeriesMinChunks:1 SeriesAvgChunks:1 SeriesMaxChunks:1 TotalChunks:49338 ChunkMinDuration:0s ChunkAvgDuration:865ms ChunkMaxDuration:15.001s ChunkMinSize:9223372036854775807 ChunkAvgSize:0 ChunkMaxSize:-9223372036854775808 SingleSampleSeries:46487 SingleSampleChunks:46487 LabelNamesCount:194 MetricLabelValuesCount:1168}" id=01GJ73EN2DN1XFHEA6087NFTQ7
level=debug ts=2023-01-16T01:32:32.303142098Z caller=index_issue.go:57 verifiers=overlapped_blocks,index_known_issues verifier=index_known_issues msg="no issue" id=01GJ73EN2DN1XFHEA6087NFTQ7
```
What's weird is chunkMaxSize -9223372036854775808 (which is very round number in hex).
I have 49 chunks like this.

**Comment by mchinkov-ionos** [comment]
> @fpetkovski upon browsing minio looking for the chunks mentioned in the error, I found that there was a chunk `01GGMXBZP09041HM47Y47HDXQJ` that did not have a chunks directory, just meta.json and index so I deleted the chunk and compaction resumed. Must have been an incomplete upload. Would be nice if Thanos could flag and continue with other blocks or even delete such chunks (the chunk was dated over a month ago).

Yes, I've had the same thing! Debugged half-day via `thanos` command line, found nothing, and then simple brute-force chunk deletion from S3 itself solved the problem!

**Comment by outofrange** [comment]
This happens for us every few weeks, either due to some underlying network issues or other problems, not sure yet.

But fixing this is quite painful; usually it's
- restart compactor
- look for error / wait until problematic block is addressed
- get block id from logs and delete
- rinse and repeat

I had no luck with `bucket verify`, but will test again - maybe I already deleted affected blocks manually when testing it, not sure anymore.
But even if it works, it takes a long time, and having to download _everything_ or setting up a backup bucket for automatic repair is more hassle than I'd expect to get a list of blocks with no chunks attached to them, to manually delete - if it'd work that way.

**Comment by bobykus31** [comment]
Is there any way to download and check why bucket is "segment index  out of range"?

**Comment by jotweh** [comment]
You can set the no-compact marker like this:
```
thanos tools bucket mark --id=01HQZD47X047YW61ZSYHFYJC8K --marker=no-compact-mark.json --objstore.config-file=thanos-objstore.yaml --details="manually marked for no-compact due to error: 'chunk iter: cannot populate chunk 8 from block"
```

where thanos-objstore.yaml looks like this:
```yaml
type: S3
config:
  bucket: your-s3-bucket-name
  endpoint: s3.us-east-1.amazonaws.com
  insecure: false
  signature_version2: false
  sse_config:
    type: "SSE-S3"
```
