### ISSUE TITLE
For AWS S3 configuration for Sidecar , Store , Compactor getting Access Denied  

### ISSUE THREAD

**Issue by argadepp** [thanos-io/thanos#5996]
Hi , 

I am using Thanos with S3 as Object Store but for accessing it have created the IAM role with proper permitions but Compactor , Store and Sidecar are not able to fetch and Upload the data .

Getting error as below 

Please help 

ubuntu@ip-172-31-44-92:~/prom$ kubectl logs -n monitoring thanos-compactor-68c8cd4568-zml5g
level=info ts=2022-12-23T11:35:42.779321827Z caller=factory.go:52 msg="loading bucket configuration"
level=info ts=2022-12-23T11:35:42.780795372Z caller=compact.go:389 msg="retention policy of raw samples is enabled" duration=720h0m0s
level=info ts=2022-12-23T11:35:42.780949094Z caller=compact.go:396 msg="retention policy of 5 min aggregated samples is enabled" duration=720h0m0s
level=info ts=2022-12-23T11:35:42.781056974Z caller=compact.go:399 msg="retention policy of 1 hour aggregated samples is enabled" duration=87600h0m0s
level=info ts=2022-12-23T11:35:42.78262769Z caller=compact.go:619 msg="starting compact node"
level=info ts=2022-12-23T11:35:42.782786916Z caller=intrumentation.go:56 msg="changing probe status" status=ready
level=info ts=2022-12-23T11:35:42.783076946Z caller=compact.go:1291 msg="start sync of metas"
level=info ts=2022-12-23T11:35:42.784228744Z caller=intrumentation.go:75 msg="changing probe status" status=healthy
level=info ts=2022-12-23T11:35:42.785155538Z caller=http.go:73 service=http/server component=compact msg="listening for requests and metrics" address=0.0.0.0:10902
level=info ts=2022-12-23T11:35:42.785491452Z caller=tls_config.go:195 service=http/server component=compact msg="TLS is disabled." http2=false
level=error ts=2022-12-23T11:35:46.305773127Z caller=compact.go:499 msg="retriable error" err="compaction: sync: BaseFetcher: iter bucket: Access Denied"
level=warn ts=2022-12-23T11:35:49.818119304Z caller=intrumentation.go:67 msg="changing probe status" status=not-ready reason="syncing metas: BaseFetcher: iter bucket: Access Denied"
level=info ts=2022-12-23T11:35:49.818164708Z caller=http.go:84 service=http/server component=compact msg="internal server is shutting down" err="syncing metas: BaseFetcher: iter bucket: Access Denied"
level=info ts=2022-12-23T11:35:49.818376318Z caller=http.go:103 service=http/server component=compact msg="internal server is shutdown gracefully" err="syncing metas: BaseFetcher: iter bucket: Access Denied"
level=info ts=2022-12-23T11:35:49.818412988Z caller=intrumentation.go:81 msg="changing probe status" status=not-healthy reason="syncing metas: BaseFetcher: iter bucket: Access Denied"
level=error ts=2022-12-23T11:35:49.818442281Z caller=runutil.go:100 msg="function failed. Retrying in next tick" err="BaseFetcher: iter bucket: Access Denied"
level=error ts=2022-12-23T11:35:53.410829698Z caller=main.go:161 err="BaseFetcher: iter bucket: Access Denied\nsyncing metas\nmain.runCompact.func6\n\t/app/cmd/thanos/compact.go:410\ngithub.com/thanos-io/thanos/pkg/runutil.Repeat\n\t/app/pkg/runutil/runutil.go:74\nmain.runCompact.func14\n\t/app/cmd/thanos/compact.go:560\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594\ncompact command failed\nmain.main\n\t/app/cmd/thanos/main.go:161\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594"

**Comment by yeya24** [comment]
Please make sure you give enough permissions for the IAM role.

**Comment by argadepp** [comment]
Below is the Policy attached to the IAM Role and have added the OIDC Provider in trust relation 

{

    "Version": "2012-10-17",

    "Statement": [

        {

            "Sid": "Statement",

            "Effect": "Allow",

            "Action": [

                "s3:ListBucket",

                "s3:GetObject",

                "s3:DeleteObject",

                "s3:PutObject"

            ],

            "Resource": [

                "arn:aws:s3:::thanos-metrics-s3storage/*",

                "arn:aws:s3:::thanos-metrics-s3storage"

            ]

        }

    ]

}

**Comment by argadepp** [comment]
Hi ,

Have changed the Trust Relation policy with wildcard for namespaces and service account post that it's working fine .

Thanks

**Comment by rbudiharso** [comment]
> Hi ,
> 
> Have changed the Trust Relation policy with wildcard for namespaces and service account post that it's working fine .
> 
> Thanks

How do you do this actually? I'm facing the same issue

**Comment by argadepp** [comment]
Have changed in IAM Role trust relationships as per below. Also make sure while using the IAM role for service account you are passing the annotation in helm chart.

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "ec2.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
        },
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::account_number:oidc-provider/oidc.eks.us-east-2.amazonaws.com/id/OIDC_OF_EKS_CLUSTER"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringLike": {
                    "oidc.eks.us-east-2.amazonaws.com/id/OIDC_OF_EKS_CLUSTER:sub": "system:serviceaccount:*:*",
                    "oidc.eks.us-east-2.amazonaws.com/id/OIDC_OF_EKS_CLUSTER:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}

**Comment by pakhip09** [comment]
Hi, I am getting same error although I have applied same Policy attached to the IAM Role and IAM Role trust relationships. Can you help here.

**Comment by argadepp** [comment]
Which Prometheus you are using. Here have used prometheus-community/kube-prometheus-stack version 10.0.0 and for Thanos have used https://artifacthub.io/packages/helm/bitnami/thanos also refer 

https://aws.amazon.com/blogs/opensource/improving-ha-and-long-term-storage-for-prometheus-using-thanos-on-eks-with-s3/

There is no issue with Prometheus version, also check  that correct OIDC is there present in Identity Provider .

Add this line in Trust Relationship 

"oidc.eks.us-east-2.amazonaws.com/id/OIDC_OF_EKS_CLUSTER:sub": "system:serviceaccount:*:*"

**Comment by pakhip09** [comment]
Thanks, now it's working.
