### ISSUE TITLE
How is prometheus container memory distributed?

### ISSUE THREAD

**Issue by SanthoshiMekala** [thanos-io/thanos#6014]
Hi,

We do not have Thanos stores, instead we are using Prometheus storage for the same. We have configured thanos as a sidecar in the prometheus-shard manifests. We configured 48GB as prometheus container memory limit. We see the container memory usage is above 40GB but when we check the heap size using heap profiling, it is showing around 10GB. We are confused about the remaining memory usage. Could you please let me know, how does the memory consumtion distributed in the prometheus container?
Thanos Version: v0.29.0
Prometheus Version: v2.40.0

Thanks!

**Comment by yeya24** [comment]
The remaining memory is used for Mmap in Prometheus TSDB and those memory is not part of the heap profile.
I will close this issue as it is actually a Prometheus question.
