### ISSUE TITLE
*: Replace deprecated `gorilla/mux` dependency

### ISSUE THREAD

**Issue by matej-g** [thanos-io/thanos#6023]
We commonly use `gorilla/mux` router for different web servers within Thanos, however the project has been deprecated recently (https://github.com/gorilla#gorilla-toolkit) and is no longer actively maintained. We should replace it with an alternative that's still maintained.

**Comment by jatinagwal** [comment]
I would like to work on this, matej. Finding an alternative for this . If anyone had a name in mind, pls mention here.
Thank you :)

**Comment by pgier** [comment]
@jatinagwal I'm not sure what the requirements are, but you could try just using the default golang http mux.
https://pkg.go.dev/net/http#ServeMux
And if you need more features, maybe use Chi
https://github.com/go-chi/chi

**Comment by matej-g** [comment]
I think @pgier summed it up nicely 👍 , I'm personally fine with either standard library or other alternative (`chi` or `gin`), if we find out we need extra features not available in the standard library.

**Comment by matej-g** [comment]
@jatinagwal feel free to take this though! And open a PR with one of these alternatives, we can take the discussions from there if any preferences appears.

**Comment by zeus2611** [comment]
@matej-g i would like to contribute in this too. Can you guide me how i can get started with fixing this issue.

**Comment by jatinagwal** [comment]
> I think @pgier summed it up nicely +1 , I'm personally fine with either standard library or other alternative (`chi` or `gin`), if we find out we need extra features not available in the standard library.

@matej-g I believe we are already using standard http library for routing . And, gorilla/mux is used as an indirect dependency for weavework,so we can't remove that. Please correct me if I am wrong.

**Comment by jwillker** [comment]
It seems like @jatinagwal is right.

You can view the usage of the gorilla/mux usage by running in the thanos repository:
```bash
$ go mod why github.com/gorilla/mux                                                                                                                                  
  github.com/gorilla/mux
  github.com/thanos-io/thanos/internal/cortex/util/log
  github.com/weaveworks/common/server
  github.com/gorilla/mux
```

### Weaveworks usage:
https://github.com/thanos-io/thanos/blob/e94c136a4217f196375eb967757f4d97fad1256c/internal/cortex/util/log/log.go#L15

### Weaveworks gorilla usage:
https://github.com/weaveworks/common/blob/7c2720a9024d7fdf5f4668321a4fcddf7b461b27/server/server.go#L13


So this causes an "indirect dependency" here: 
https://github.com/thanos-io/thanos/blob/e94c136a4217f196375eb967757f4d97fad1256c/go.mod#L37

So maybe there's nothing to do here. 
Just wait for this issue to be solved: https://github.com/weaveworks/common/issues/272

**Comment by matej-g** [comment]
You're right folks, I misread the dependencies within Thanos, we do indeed use the standard library. Than this is a no-op as @jwillker pointed out. Closing.
