### ISSUE TITLE
Thanos Compactor not deleting data after retention date is over

### ISSUE THREAD

**Issue by kakashi96** [thanos-io/thanos#6037]
**Thanos, Prometheus and Golang version used**:
thanos, version 0.27.0 (branch: HEAD, revision: https://github.com/thanos-io/thanos/commit/f68bb366d18557a5347e6b38013f363ad5be05a4)
build user: root@708554d4fa46
build date: 20220705-14:57:42
go version: go1.17.11
platform: linux/amd64

**Object Storage Provider**:
Azure HDD
**What happened**:
According to the retetntion policy written the data is supposed to delete after 90 days but it still remains in the azure storage and doesn't get deleted
**What you expected to happen**:
the downsampled data to be deleted after 90 days
**How to reproduce it (as minimally and precisely as possible)**:
```
["compact","--log.level=info","--log.format=logfmt","--http-address=0.0.0.0:10905","--data-dir=/tmp/compact","--
retention.resolution-raw=90d","--retention.resolution-5m=90d","--retention.resolution-1h=90d","--consistency-
delay=30m","--objstore.config-file=/conf/thanos/objstore.yml","--compact.concurrency=1","--delete-delay=48h","--wait-
interval=2h","--compact.cleanup-interval=1h","--wait"],

```
**Full logs to relevant components**:
No error found in the error log

**Comment by yeya24** [comment]
Please follow https://thanos.io/tip/operating/compactor-backlog.md/.

**Comment by kakashi96** [comment]
The solutions provided are not feasible by me i.e scale up and use bucket tools
I want to actually find the bug that's causing me the issue of not deleting the blocks.

**Comment by yeya24** [comment]
Have you followed the doc? If you did, please share us the todo metrics and compaction iteration metrics mentioned in the doc.
Otherwise, I don't think we can help you cause it is an issue of your setup rather than a bug.

**Comment by kakashi96** [comment]
here are all the todo metrics from compaction to deletion block
<img width="925" alt="block" src="https://user-images.githubusercontent.com/68124692/212000733-6a211c49-a091-4449-b11f-85760ab94b3c.PNG">
<img width="665" alt="Capture" src="https://user-images.githubusercontent.com/68124692/212000743-a1c46be7-7551-4132-ba14-5105bd55110a.PNG">
<img width="934" alt="compact" src="https://user-images.githubusercontent.com/68124692/212000748-6f81de20-d51b-40e8-aed7-9e912d84eec6.PNG">
<img width="953" alt="delete" src="https://user-images.githubusercontent.com/68124692/212000750-3b0a91e8-3d1a-4f14-a8ef-5ed70941a5b5.PNG">
<img width="927" alt="downsample" src="https://user-images.githubusercontent.com/68124692/212000752-0feccc4b-37dd-478e-b5e3-5e447c754fc6.PNG">

**Comment by yeya24** [comment]
Yeah from the metrics you shared looks like there are compaction backlogs. Can you double check the `thanos_compact_iterations_total` metric as well?

**Comment by kakashi96** [comment]
yup it's 0 too, any idea on how to proceed further?
<img width="898" alt="iter'" src="https://user-images.githubusercontent.com/68124692/212009127-79f2ad45-59ca-405f-948a-a6c726b920e6.PNG">

**Comment by yeya24** [comment]
> yup it's 0 too, any idea on how to proceed further?

Please follow the document above to scale your compactor.

**Comment by kakashi96** [comment]
Due to monetary issues we can not scale the compactor or add a new bucket.
is there some bug causing this issue or is scaling the only possible solution?
