### ISSUE TITLE
[Feature] Rule: Add file SD for alertmanagers

### ISSUE THREAD

**Issue by FUSAKLA** [thanos-io/thanos#607]
Rule node needs (or at least should) send alerts to all Alertmanager instances in the Alertmanager cluster.

Now if you add another Alertmanager instance you need to redeploy the Rule node with additional command line flag.

Adding `file_sd` now widely adapted in other Thanos components would allow to add new instances dynamically.

**Comment by ivan-valkov** [comment]
Hey @FUSAKLA , nice suggestion. Just wondering, do you have a specific use case for this right now? Is it blocking you, or is it a general feature request?

**Comment by FUSAKLA** [comment]
The use case is as I mentioned if I add another Alertmanager instance to the AM cluster I'd need to redeploy the Rule node with command line added since you need to send alerts to all those AM instances.

It's definitely not blocking me.
So yes, it's more of a general feature request that would ease the deployment and transition from Prometheus federation based infrastructure.
