### ISSUE TITLE
Error executing query: "Unexpected token '<','<html> <h'.. is not a valid json

### ISSUE THREAD

**Issue by Nikhils09** [thanos-io/thanos#6075]
**Thanos and Prometheus version**:
**Thanos**: 0.28.1
**Prometheus**: 2.38.0

**Object Storage Provider**: S3

**What happened**: I'm using Prometheus and Thanos to Monitor Jira, when I try to query older data (7 days or older) using sum or rate it gives me:
```
Error executing query: "Unexpected token '<','<html> <h'.. is not a valid json
```
**Note**: It works fine for recent data that is not older than 7 days.

How to reproduce it (as minimally and precisely as possible): Here's the one of the query in which I'm getting the issue:
```
sum(rate(jira_request_duration_on_path_count{job="job name"}[5m])) by (instance_id)
```
Environment:
- OS : Ubuntu 20.04.5

I would appreciate any help in resolving this issue. Thank you!

**Comment by vivekkikani** [comment]
SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON

**Comment by fpetkovski** [comment]
This looks like a timeout or an error response from a proxy like nginx. Is there any way you can verify whether this is the root cause

**Comment by Nikhils09** [comment]
I'm actually running Thanos query behind a nginx reverse proxy, so probably that can be the issue.

**Comment by fpetkovski** [comment]
You can try setting the timeout on nginx to a higher value to see if it helps.

**Comment by Nikhils09** [comment]
Thanks, I'll give it a try

**Comment by naseel1** [comment]
Uncaught Javascript Error > Unexpected token < <html>
<h"... is not valid JSON can you help solve this problem

**Comment by naseel1** [comment]
Uncaught Javascript Error > Unexpected token <
<h"... is not valid JSON can you help solve this problem in odoo website

**Comment by Nikhils09** [comment]
Hi @fpetkovski, I tried adding timeout in nginx config but still getting the same issue.

**Comment by reyshazni** [comment]
I found that one simple solution is by deactivating Modsecurity in my NGINX ingress.

**Comment by judo2000** [comment]
How do you deactivate mode security in NGINX?  I'm getting the same error

**Comment by tejastank** [comment]
Before for me nginx virtual host file details 

client_max_body_size 5M;

I fix this to new value 

client_max_body_size 20M;

Same concern resovled successful

Thanks,
Tejaskumar Tank
