### ISSUE TITLE
thanos-sidecar: Not able to upload data only every 2 hours

### ISSUE THREAD

**Issue by apinter** [thanos-io/thanos#6115]
**Thanos, Prometheus and Golang version used**:
Thanos version: v0.30.1
Prometheus version: v2.41.0
GKE version: v1.23.14-gke.1800

**Object Storage Provider**:
GCS

**What happened**:
The Thanos sidecar is uploading metrics data every 2 hours to GCS. We currently have 30+ clusters with Thanos and Prometheus deployed on, while we would prefer to monitor each and every cluster from a single instance of Grafana. We achieved this by naming one of our cluster the "central monitoring" cluster which reads the data from GCS. However, the rate at which the data is uploaded from other cluster to GCS and visualized in this central cluster is 2+hours. Would need to make this setting more frequent, but research failed us so far..

**What you expected to happen**:
Be able to change the frequency of metrics data upload to object storage from 2 hours to something more near-realtime. Preferably without the need to publish anything on any of the clusters and continue to use GCS as our storage where data is read out from.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy Prometheus with [prometheus-community helm chart](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) in 2 separate GKE/k8s clusters
2. Check Grafana in the "central" cluster - where monitoring is intended to happen - for data.

Our `values` are available here: 
- https://pastebin.com/B9Hi03uThttps://pastebin.com/B9Hi03uT
- https://pastebin.com/V0tCByAj

**Full logs to relevant components**:

**Anything else we need to know**:

**Environment**:
v1.23.14-gke.1800

**Comment by yeya24** [comment]
You can point your Thanos querier to Thanos sidecar so that you can read data for the recent 2 hours.

**Comment by matej-g** [comment]
This was also discussed on Slack, I think there was no follow up, so I'm closing it.
