### ISSUE TITLE
Receives meta monitoring queries do not deduplicate data

### ISSUE THREAD

**Issue by abaguas** [thanos-io/thanos#6120]
**Thanos version used**:

v0.30.2

**What happened**:

I configured head_series_limit as documented in https://thanos.io/tip/components/receive.md/#understanding-the-configuration-file, however the meta_monitoring_limit_query was not deduplicating the data, despite the `--query.replica-label` configured in the querier. This dropped metrics becaused the number or series reported by the querier was a multiple (replication factor) of the real value.

**What you expected to happen**:

I expected duplication to be in place, since the queriers used for metamonitoring were configured accordingly.

**How to reproduce it (as minimally and precisely as possible)**:

Any metamonitoring query provided that the replication factor is larger than 1.

**Comment by GiedriusS** [comment]
Solved in https://github.com/thanos-io/thanos/pull/6121 :bow:
