### ISSUE TITLE
switching from query.engine prometheus to thanos,  Occasionally requests will be panic

### ISSUE THREAD

**Issue by jicanghaixb** [thanos-io/thanos#6141]
Thanos, Prometheus and Golang version used:
v0.30.2

What happened:
after switching from query.engine prometheus to thanos,  Occasionally requests will be panic
What you expected to happen:
query not panic requests

How to reproduce it (as minimally and precisely as possible):

Full logs to relevant components:

Uncomment if you would like to post collapsible logs:

详情
Logs
level=info ts=2023-02-20T06:47:57.403968472Z caller=tls_config.go:232 service=http/server component=query msg="Listening on" address=[::]:11904
 level=info ts=2023-02-20T06:47:57.404015075Z caller=tls_config.go:235 service=http/server component=query msg="TLS is disabled." http2=false address=[::]:11904
level=info ts=2023-02-20T06:48:02.407805096Z caller=endpointset.go:411 component=endpointset msg="adding new rule with [storeAPI rulesAPI]" address=178.48.202.16:11910 extLset="{replica=\"ezMon-178.48.202.16\"}"
level=info ts=2023-02-20T06:48:02.407854521Z caller=endpointset.go:411 component=endpointset msg="adding new sidecar with [storeAPI rulesAPI exemplarsAPI targetsAPI MetricMetadataAPI]" address=178.48.202.10:11901 extLset="{ezmon_datacenter=\"collectors1\", replica=\"ezMon-178.48.202.10\"}"
level=info ts=2023-02-20T06:48:02.407869547Z caller=endpointset.go:411 component=endpointset msg="adding new sidecar with [storeAPI rulesAPI exemplarsAPI targetsAPI MetricMetadataAPI]" address=178.48.202.12:11901 extLset="{ezmon_datacenter=\"collectors2\", replica=\"ezMon-178.48.202.12\"}"
level=info ts=2023-02-20T06:48:02.407892022Z caller=endpointset.go:411 component=endpointset msg="adding new store with [storeAPI]" address=178.48.202.15:11905 extLset="{ezmon_datacenter=\"collectors1\", replica=\"ezMon-178.48.202.10\"},{ezmon_datacenter=\"collectors1\", replica=\"ezMon-178.48.202.11\"},{ezmon_datacenter=\"collectors1\", replica=\"ezMon-178.48.202.17\"},{ezmon_datacenter=\"collectors2\", replica=\"ezMon-178.48.202.12\"},{ezmon_datacenter=\"collectors2\", replica=\"ezMon-178.48.202.13\"},{replica=\"ezMon-178.48.202.15\"},{replica=\"ezMon-178.48.202.16\"}"
level=info ts=2023-02-20T06:48:02.407910217Z caller=endpointset.go:411 component=endpointset msg="adding new sidecar with [storeAPI rulesAPI exemplarsAPI targetsAPI MetricMetadataAPI]" address=178.48.202.13:11901 extLset="{ezmon_datacenter=\"collectors2\", replica=\"ezMon-178.48.202.13\"}"
level=info ts=2023-02-20T06:48:02.407923292Z caller=endpointset.go:411 component=endpointset msg="adding new sidecar with [storeAPI rulesAPI exemplarsAPI targetsAPI MetricMetadataAPI]" address=178.48.202.11:11901 extLset="{ezmon_datacenter=\"collectors1\", replica=\"ezMon-178.48.202.11\"}"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d6ba04]
goroutine 69701 [running]:
github.com/thanos-community/promql-engine/worker.(*Worker).start(0xc004dbcf00, 0x7fc50750a230?, {0x2bf43e0?, 0xc006d391c0?})
github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/worker/worker.go:71 +0x84
created by github.com/thanos-community/promql-engine/worker.Group.Start
github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/worker/worker.go:29 +0x4b
....
evel=info ts=2023-02-20T06:49:35.393142408Z caller=options.go:26 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
 level=info ts=2023-02-20T06:49:35.393793693Z caller=query.go:785 msg="starting query node"
level=info ts=2023-02-20T06:49:35.393909778Z caller=intrumentation.go:75 msg="changing probe status" status=healthy
 level=info ts=2023-02-20T06:49:35.39397009Z caller=http.go:73 service=http/server component=query msg="listening for requests and metrics" address=0.0.0.0:11904
 level=info ts=2023-02-20T06:49:35.394105637Z caller=intrumentation.go:56 msg="changing probe status" status=ready
level=info ts=2023-02-20T06:49:35.394238619Z caller=grpc.go:131 service=gRPC/server component=query msg="listening for serving gRPC" address=0.0.0.0:11903
level=info ts=2023-02-20T06:49:35.394231631Z caller=tls_config.go:232 service=http/server component=query msg="Listening on" address=[::]:11904
level=info ts=2023-02-20T06:49:35.394274023Z caller=tls_config.go:235 service=http/server component=query msg="TLS is disabled." http2=false address=[::]:11904
level=info ts=2023-02-20T06:49:40.402604522Z caller=endpointset.go:411 component=endpointset msg="adding new sidecar with [storeAPI rulesAPI exemplarsAPI targetsAPI MetricMetadataAPI]" address=178.48.202.13:11901 extLset="{ezmon_datacenter=\"collectors2\", replica=\"ezMon-178.48.202.13\"}"
level=info ts=2023-02-20T06:49:40.402673933Z caller=endpointset.go:411 component=endpointset msg="adding new store with [storeAPI]" address=178.48.202.15:11905 extLset="{ezmon_datacenter=\"collectors1\", replica=\"ezMon-178.48.202.10\"},{ezmon_datacenter=\"collectors1\", replica=\"ezMon-178.48.202.11\"},{ezmon_datacenter=\"collectors1\", replica=\"ezMon-178.48.202.17\"},{ezmon_datacenter=\"collectors2\", replica=\"ezMon-178.48.202.12\"},{ezmon_datacenter=\"collectors2\", replica=\"ezMon-178.48.202.13\"},{replica=\"ezMon-178.48.202.15\"},{replica=\"ezMon-178.48.202.16\"}"
 level=info ts=2023-02-20T06:49:40.402691969Z caller=endpointset.go:411 component=endpointset msg="adding new sidecar with [storeAPI rulesAPI exemplarsAPI targetsAPI MetricMetadataAPI]" address=178.48.202.10:11901 extLset="{ezmon_datacenter=\"collectors1\", replica=\"ezMon-178.48.202.10\"}"
level=info ts=2023-02-20T06:49:40.402703684Z caller=endpointset.go:411 component=endpointset msg="adding new sidecar with [storeAPI rulesAPI exemplarsAPI targetsAPI MetricMetadataAPI]" address=178.48.202.11:11901 extLset="{ezmon_datacenter=\"collectors1\", replica=\"ezMon-178.48.202.11\"}"
level=info ts=2023-02-20T06:49:40.402723016Z caller=endpointset.go:411 component=endpointset msg="adding new rule with [storeAPI rulesAPI]" address=178.48.202.16:11910 extLset="{replica=\"ezMon-178.48.202.16\"}"
level=info ts=2023-02-20T06:49:40.402735059Z caller=endpointset.go:411 component=endpointset msg="adding new sidecar with [storeAPI rulesAPI exemplarsAPI targetsAPI MetricMetadataAPI]" address=178.48.202.12:11901 extLset="{ezmon_datacenter=\"collectors2\", replica=\"ezMon-178.48.202.12\"}"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d6ba04]
 goroutine 279447 [running]:
github.com/thanos-community/promql-engine/worker.(*Worker).start(0xc01e0e25d0, 0xc00bb13f70?, {0x2bf43e0?, 0xc021fc3300?})
github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/worker/worker.go:71 +0x84
created by github.com/thanos-community/promql-engine/worker.Group.Start
github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/worker/worker.go:29 +0x4b

level=info ts=2023-02-20T06:52:11.6902562Z caller=endpointset.go:411 component=endpointset msg="adding new rule with [storeAPI rulesAPI]" address=178.48.202.16:11910 extLset="{replica=\"ezMon-178.48.202.16\"}"
level=info ts=2023-02-20T06:52:11.690268267Z caller=endpointset.go:411 component=endpointset msg="adding new sidecar with [storeAPI rulesAPI exemplarsAPI targetsAPI MetricMetadataAPI]" address=178.48.202.12:11901 extLset="{ezmon_datacenter=\"collectors2\", replica=\"ezMon-178.48.202.12\"}"
level=info ts=2023-02-20T06:52:11.690279939Z caller=endpointset.go:411 component=endpointset msg="adding new sidecar with [storeAPI rulesAPI exemplarsAPI targetsAPI MetricMetadataAPI]" address=178.48.202.10:11901 extLset="{ezmon_datacenter=\"collectors1\", replica=\"ezMon-178.48.202.10\"}"
level=info ts=2023-02-20T06:52:11.690307325Z caller=endpointset.go:411 component=endpointset msg="adding new store with [storeAPI]" address=178.48.202.15:11905 extLset="{ezmon_datacenter=\"collectors1\", replica=\"ezMon-178.48.202.10\"},{ezmon_datacenter=\"collectors1\", replica=\"ezMon-178.48.202.11\"},{ezmon_datacenter=\"collectors1\", replica=\"ezMon-178.48.202.17\"},{ezmon_datacenter=\"collectors2\", replica=\"ezMon-178.48.202.12\"},{ezmon_datacenter=\"collectors2\", replica=\"ezMon-178.48.202.13\"},{replica=\"ezMon-178.48.202.15\"},{replica=\"ezMon-178.48.202.16\"}"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d6ba04]
goroutine 277575 [running]:
 github.com/thanos-community/promql-engine/worker.(*Worker).start(0xc00b12b7d0, 0x0?, {0x2bf43e0?, 0xc012497c40?})
github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/worker/worker.go:71 +0x84
created by github.com/thanos-community/promql-engine/worker.Group.Start
github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/worker/worker.go:29 +0x4b

**Comment by fpetkovski** [comment]
Thanks for reporting this issue. We will cut a new release this week which should help resolve this issue. I will post here once a new version is out.

**Comment by GiedriusS** [comment]
A ton of problems were fixed over the last year so please comment again if this is still happening.
