### ISSUE TITLE
After adding  --store.limits.request-samples, the thanos query failed to start

### ISSUE THREAD

**Issue by yuan-yueping** [thanos-io/thanos#6177]
thanos  version: v0.22.0

After adding  --store.limits.request-samples, the thanos query failed to start.

When I want to add the --store.limits.request-samples parameter to the thanos query, the query fails to start, and the prompt is as follows: "thanos: error: unknown long flag '--store.limits.request-samples'" How should I configure and use this parameters. Thanks

![截屏2023-03-02 17 29 36](https://user-images.githubusercontent.com/58799869/222388171-869b73d4-0902-471a-b5e4-330da8eb5f0d.png)

My configuration is as shown below
![截屏2023-03-02 17 30 46](https://user-images.githubusercontent.com/58799869/222388455-afe43509-7d21-45da-b717-94e7d9835e40.png)

**Comment by fpetkovski** [comment]
This field was added very recently so you should use the 0.31.0-rc version.
