### ISSUE TITLE
compact: compact still tries to downsample the block, when it has the no-downsample-mark.json

### ISSUE THREAD

**Issue by yangfan-njupt** [thanos-io/thanos#6179]
**Thanos, Prometheus and Golang version used**: Thanos v0.30.2

**Object Storage Provider**: ceph

**What happened**:
I have a block that is broken, and when it was downsampled, the compact will halt with failed checksums.
So i I want to skip the downsamp for this block by the #5945 .
But when I marked this block with `no-downsample-mark.json`, the compact still halt because of this block.

**What you expected to happen**:
The compact skipping the downsamp of this block.

**Anything else we need to know**:
I checked the source code after the problem, and found that there is a function `NoDownsampleMarkedBlocks()` for finding marked blocks, which is defined but not used. Maybe it has something to do with this?
https://github.com/thanos-io/thanos/blob/fe3f5d24192570038e9576307e1b31794920a1f3/pkg/compact/downsample/downsample.go#L790-L791

**Comment by michalschott** [comment]
Similar issue here.
