### ISSUE TITLE
tracing in OTLP support configuring `service_name`

### ISSUE THREAD

**Issue by fatsheep9146** [thanos-io/thanos#6184]
### Is your proposal related to a problem?

For now, if we enable thanos tracing in [OTLP](https://thanos.io/tip/thanos/tracing.md/#opentelemetry-otlp) and push the traces into jaeger, the traces will displayed with a default service name `OTLPResourceNoServiceName`, which is little bit confusing,

![image](https://user-images.githubusercontent.com/11855957/223021273-73bf7bf7-50ed-4af1-bb7d-3cb7fbfa084c.png)

So I think we should support `service_name` option in OTLP config, in order to make the traces more clear in jaeger and any other systems to display traces.

![image](https://user-images.githubusercontent.com/11855957/223021483-b3b8ac73-e13c-4dc9-a70a-7f32532d1287.png)

### Describe the solution you'd like

Support `service_name` option in OTLP config, in order to make the traces more clear in jaeger and any other systems to display traces.

**Comment by ahurtaud** [comment]
The PR is valid to me, however, if you want to do it before using the next version.
Setting `OTEL_SERVICE_NAME` environment variable works ;)
