### ISSUE TITLE
Disable vertical sharding when `scalar` function is present

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#6209]
**What happened**:

In Cortex, we have seen 2 bugs caused due to `scalar` function related to vertical sharding.

1. https://github.com/cortexproject/cortex/issues/5207 `scalar(sum by (xx) (metric))` will be shardable but we cannot handle scalar type response. And the result itself is `scalar` type and we don't have a way to merge.

2. https://github.com/cortexproject/cortex/issues/5205 Another issue but this time `scalar` is used to be the parameter.

**What you expected to happen**:

There is no bugs in vertical sharding caused by `scalar`. We should just disable `scalar` for vertical sharding to avoid any edge cases we might hit.

**Comment by yeya24** [comment]
@fpetkovski Would love to hear your opinion on this.

**Comment by fpetkovski** [comment]
Makes sense to me. If there are known bugs caused by it, I let's go ahead and disable sharding or expressions that contain `scalar` 👍
