### ISSUE TITLE
Documentation for GitHub Codespaces

### ISSUE THREAD

**Issue by samruddhikhandale** [thanos-io/thanos#6211]
Hi 👋 

I am Samruddhi, a Software Engineer for GitHub, working with the [GitHub Codespaces](https://github.com/features/codespaces) team, and a maintainer for the [devcontainers](https://github.com/devcontainers) org 👩‍💻

I was looking at the [thanos-io/thanos](https://github.com/thanos-io/thanos) repo which has a pretty cool [devcontainer configuration](https://github.com/thanos-io/thanos/blob/main/.devcontainer/devcontainer.json) setup ✨ 

[GitHub Codespaces](https://docs.github.com/en/codespaces/overview) is a cloud-based development environment that uses your dev container to provide great contributor and maintainer experiences for all users of your project 🪄

🙅‍♀️ No one would ever have to worry about setting up their local machines, adding tools/runtimes for a specific project (which most frequently contradicts with their current environment) and spend hours before even starting their actual work 🙅‍♀️

Would you be willing to accept improvements to your current [devcontainer config](https://github.com/thanos-io/thanos/blob/main/.devcontainer/devcontainer.json) and a documentation to improve the GitHub Codespaces experience? 💁‍♀️

Thanks,
Samruddhi

// cc @craiglpeters

**Comment by matej-g** [comment]
Thank you @samruddhikhandale, I'm sure we'd be happy to accept improvements! Feel free to open a PR, I'd be happy to take a look and help move it forward.

**Comment by samruddhikhandale** [comment]
Awesome, thank you! I'll paste a link here when it's ready.

**Comment by douglascamata** [comment]
I think this can be closed now that #6232 has been merged? WDYT, @matej-g?

**Comment by samruddhikhandale** [comment]
Yep, we can close this. Thank you!
