### ISSUE TITLE
Improvement to compactor levels

### ISSUE THREAD

**Issue by dmitriy-lukyanchikov** [thanos-io/thanos#623]
I want to make changes to code to make it possible to choose compaction blocks size.
For example to choose last level of compaction not 14 days but 4 days. In some cases if metrics is more than 2 millions there is possibility that 14 days block will be almost 100GB size, but they are needed because need to create 1h downsample to reduce size of database for old metrics.

Also i notice that there is strange condition for downsample creation process, ofr 1h blocks need to have block that contain at least 10 days of metrics, but some of the blocks contain less with maximum size of compaction, Can i change condition to create 1h blocks if compaction level is maximum possible in thanos?

@bwplotka

**Comment by bwplotka** [comment]
>  14 days block will be almost 100GB size

Can I get more info, why this is a problem? (:
