### ISSUE TITLE
improvment to compactor to run on range of storage

### ISSUE THREAD

**Issue by dmitriy-lukyanchikov** [thanos-io/thanos#624]
Hello guys, i have an idea how to optimize resource usage for compactor if you need to compact and downsample different storages. We can make changes to compactor logic. The idea is next:
1) make changes to code so it is possible to run across range of storages in same provider with the same credentials for easier implementation
2) after all loops of compaction and downsampling is completed for one of the storage, not wait but start run on other storage

potentially there can be issues if one of the storage is not compacted and big it can take long time, but if start to run on fresh data one compactor can possible to compact and downsample at least 4 different storage. Need test to make sure, but anyway it is better than use 1 huge VM instead of 4 different huge VMs for compaction. Does it make sense to you @bwplotka

**Comment by bwplotka** [comment]
Hi, Sorry for delay.

Sure, I think it makes sense for small to medium setup. When you don't have lots of sources and you are sure that compactor is fast enough to compact everything fast enough.

I would be worried for bigger setups, when you push from tens/hundreds (?) of Prometheuses into single bucket. In the worst case, even single compactor might be not fast enough. We never seen that issue on the wild, but technically with large enough data sets and lot's of scrapers that might hit us.

Anyway, I feel like fixing both cases makes sense:
* compactor shared between multple buckets
* compactor shared between set of sources within bucket (much more difficult to implement)

The question is how if issue you mentionedis is more important than others for users (and you) if it just a matter of huge VM, if yes - worth to fix this.

One way you can achieve it even now is set up a CronJob (e.g via CronJob Kubernetes resource) to  4 single compactor runs (1 per each bucket). Look for compactor `--wait` flag you can set tu false. (:
