### ISSUE TITLE
Thanos bucket command to upload blocks created by Prometheus Snapshot

### ISSUE THREAD

**Issue by nicolastakashi** [thanos-io/thanos#6263]
### Is your proposal related to a problem?

Not directly!
But when you need to recreate Prometheus disks for some reason and you don't want to lose the data, be able to upload the blocks created using the Prometheus Snapshot feature.

Another use case would be if you are scaling down the number of Prometheus shards you have and you don't want to loose the collected data which is less than 2h for example.

### Describe the solution you'd like

Thanos bucket could expose a command to allow users specify the snapshot dir and than upload the blocks available on this directory.

### Describe alternatives you've considered

Nothing comes to my mind for now.

### Additional context

N/A

**Comment by ZaynJiang** [comment]
I am also facing this issue where, while scaling up Prometheus using Thanos, the Thanos query component can successfully retrieve the data, but when scaling down, data is lost. This appears to be in conflict with the intended design goals of Thanos

**Comment by nicolastakashi** [comment]
> I am also facing this issue where, while scaling up Prometheus using Thanos, the Thanos query component can successfully retrieve the data, but when scaling down, data is lost. This appears to be in conflict with the intended design goals of Thanos

This command is already available in Thanos Tool
