### ISSUE TITLE
No metric for "update of endpoint failed" query errors

### ISSUE THREAD

**Issue by jpds** [thanos-io/thanos#6280]
### Is your proposal related to a problem?

I use stacked queriers in a particular environment where there is no internal DNS and the queriers are set to talk to each other over plain IP. I noticed that there's no metric available for this error:

```
level=warn ts=2023-04-13T10:01:44.174609028Z caller=endpointset.go:416 component=endpointset msg="update of endpoint failed" err="getting metadata: fallback fetching info from [fd10:XX]:10901: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=[fd10:XX]:10901
```

All the available `thanos_query_*` metrics seem to either be `_dns_failures_total` or `_dns_lookups_total`. The closest metric for spotting network errors is `thanos_store_nodes_grpc_connections` but that doesn't provide error counts over time.

**Comment by jpds** [comment]
I didn't look beyond the `thanos_` metrics so didn't see that `grpc_client_handled_total{grpc_code="DeadlineExceeded"}` covers this.

Perhaps an "Available metrics" is needed under the "Operating" part of the docs for easier discovery?

**Comment by fpetkovski** [comment]
True, this could be detected by looking at `grpc_client_handled_total{grpc_method="Info"}`.

**Comment by matej-g** [comment]
So which action do we want to do here? Are we fine with inferring this from the gRPC metric? Technically, we use info method only on endpoint update AFAIK, so it should give us the information we want, it's just less readable then having directly something like separate metrics for failed endpoint updates.

**Comment by Chandan-DK** [comment]
Hi! I would like to work on this. 
So, is a separate metric needed in this case?
