### ISSUE TITLE
Routing Alerts to AlertManager from Thanos Ruler - How to set custom PromQL address?

### ISSUE THREAD

**Issue by diranged** [thanos-io/thanos#6284]
### Is your proposal related to a problem?

When we have the `thanos-ruler` pods pointing to a `thanos-query-frontend` endpoint, our alerts get a nice friendly `Alert Source: https://…./query/…` label that helps our developers get right to the source of the alert.

However, when we run the `thanos-ruler` pods against either Amazon Managed Prometheus or Grafana Cloud, we get a shortened URL that just gives us a query-path .. the problem is neither Grafana Cloud nor Amazon Managed Prometheus provide a `/graph` endpoint.

### Describe the solution you'd like

It would be ideal if there were a few options here..

1. Allow us to templatize the URL to anything we want (with the alert query as an argument).
2. Have some native understanding of the Grafana /explore endpoint URL structure and allow us to route to that.

### Additional context

https://cloud-native.slack.com/archives/CK5RSSC10/p1681574164937839

**Comment by bwplotka** [comment]
Great issue! 

## The acceptance criteria

* Thanos Rule has configuration flag that allows customizing (template?) Alert Source field.

**Comment by matej-g** [comment]
PR has been merged ✅, thank you @zhuoyuan-liu 🙇

**Comment by jkroepke** [comment]
@diranged 

> Have some native understanding of the Grafana /explore endpoint URL structure and allow us to route to that.

Do you have such an template to share?
