### ISSUE TITLE
kubernetes-helm: Bring sample up to date with latest prometheus helm chart

### ISSUE THREAD

**Issue by rubenvw-ngdata** [thanos-io/thanos#6301]
**Thanos, Prometheus and Golang version used**: Thanos v0.31.0 Prometheus helm chart v 20.0.2

**Object Storage Provider**: NA

**What happened**: 

The sidecar configuration for the official prometheus helm chart is not up to date (https://github.com/thanos-io/thanos/tree/main/tutorials/kubernetes-helm):
* It doesn't know that configmapReload can be simply disabled
* it doesn't describe the solution for the alert manager.
* sidecarContainers is no longer an array
* even after doing the changes to fix the above, it fails mounting the new volumes and secrets.

**What you expected to happen**: 

To find a working configuration with the latest prometheus chart version.

**How to reproduce it (as minimally and precisely as possible)**: Try to run the configuration from the docs

**Full logs to relevant components**: NA

**Anything else we need to know**: NA

**Comment by matej-g** [comment]
Thanks for flagging this @rubenvw-ngdata, if you'd be up to working on this let me know 🙂

**Comment by rubenvw-ngdata** [comment]
@matej-g So far I haven't got it working yet. If I get it working, I can share the configuration.

**Comment by TheSwarnim** [comment]
Hi @matej-g, can I pick this task

**Comment by matej-g** [comment]
@TheSwarnim Go for it!

**Comment by rubenvw-ngdata** [comment]
Hi @TheSwarnim, is there any progress on this?

**Comment by ashutosh887** [comment]
I would like to work on this now @rubenvw-ngdata Sir 

Please assign
