### ISSUE TITLE
Slow requests to multiple prometheus using HA with sidecars and query

### ISSUE THREAD

**Issue by dmitriy-lukyanchikov** [thanos-io/thanos#631]
**Thanos, Prometheus and Golang version used**
```
thanos, version 0.1.0 (branch: master, revision: 3bb4076af3fcf6d166d6690581af22cee086cc8d)
  build user:       circleci@90ace2f33852
  build date:       20181108-16:06:28
  go version:       go1.10.5
```
Prometheus 2.5.0

**What happened**
I create this infrastructure:
- all infrastructure working in aws in the same network and region and connected to each other using local aws ip addresses for faster connection
- install 8 different Prometheus servers for different type of data. 
- Every prometheus have replica for HA. 
- Every prometheus have uniq label for deduplication on thanos query component. 
- 4 prometheus have 30 days retention locally
- 4 prometheus have retention 1 year locally to keep data federated from fist 4 prometheus with retention 30 days
- each prometheus have near 3-4 millions of series
- install and configure thanos sidecar on each prometheus including servers with 1 year retention
- do not use thanos store and s3 storage, just thanos sidecar and thanos query for HA

All working fine and actually requests is only 1.5 or 2 times slower than directly querying prometheus, but only if using query that include result for 1-2 days. if i need to query 2 or more days in result the speed is dropping dramatically. 
What i try to do to inspect the problem.
- i run 1 and 2 server and the speed is the same.
- then i try to run sidecar locally on prometheus to use localhost to communicate between thanos sidecar and prometheus, but result is almost the same again.

with the one query its not the big deal but if you run grafana dashboard with 10 or mote graphs its almost impossible to see result if you choose time interval bigger than 1 week, it took almost 2 minutes to load it using thanos, but querying prometheus directly dashboard loads in 15 seconds.
For 1 days interval thanos load in 15 seconds, prometheus load in 6-7 seconds. We can give you any data or info you need because its blocking us to use thanos in production right now.

I suspect that there is needed some improvements in remote read api that thanos sidecar use to query prometheus, but i am not sure. Can you guys help to investigate and navigate how we can improve the code and what the problem may be.

**What you expected to happen**
I expected to see dropping of speed will be the same for all intervals of query comparing to prometheus directly
**How to reproduce it (as minimally and precisely as possible)**:
Just run data for bigger than 1 week and install sidecar and query thanos component, and try to run query for bigger than 1 week
**Full logs to relevant components**

**Anything else we need to know**

**Comment by bwplotka** [comment]
I am guessing thanos querier is on some remote cluster right?

I think you are definitely hiting the issue of basically high volume of data between thanos querier and prometheus. As you seen in your experiments that you provided on slack channel some of the data like:

```
d.lukyanchikov [5 days ago]
No  problem with numbers, run all locally, prometheus 2.5.0, thanos-query and thanos-sidecar all  configured to conenct thru localhost interface on one host. The query `count(job:node_cpu_usage_percentage:irate5m)` for 4 weeks on prometheus run near 2 seconds, on thanos near 27 seconds
```

The single request was taking 600 MB between thanos querier and prometheus (and sidecar in between). And all adds up:
- just raw one series for 4w takes ~2.5MB with 15s interval (compressed ~0.4 MB)
- raw samples for 2640 series, 4w is 6600MB
- after snappy compression (11-12x) it is ~600MB

This means that for your high number of series and samples (4w means 161 280 samples just for one series!), just sending it between cluster takes time, not mentioning deduplication for this number of samples.

We can definitely investigate the hot path and check the latency of every step in the query to check where it spends the most time. For this I would suggest using tracing we have built in Thanos (we can instrument it even further to make sure every we have enough spans). Thanos uses stackdriver, which you can quickly set up, but of course we can think about moving to open census for more flexibility. 

Definitely stream Remote read will improve latency and used memory by sidecar as we potentially don't need to encode/decode all which can take.. for example:

Assuming one sample can be encoded in ~20 nanosec (rough assumption) for your query it is ... 10s spent just in sidecar (:  

But even with fixes here & there, except the Remote Read and Distributed Query (which is really difficult to achieve), there is no other solution than... Downsampling! 

Which Thanos offers only if you use compactor + long term storage. It might be the solution that will help for you if you have so huge volume. 

There are some users who uses Trickster for caching query results with some successes, you might want to look on this as well.
