### ISSUE TITLE
Add checkbox in query frontend to force a trace to be collected

### ISSUE THREAD

**Issue by verejoel** [thanos-io/thanos#6311]
### Is your proposal related to a problem?

When troubleshooting performance or testing recent changes, it would be good if I could signal to the query frontend that I would like the `X-Thanos-Force-Tracing` header to be included in the request, to force tracing on the backend.

### Describe the solution you'd like

A checkbox that I can select that will force tracing.

### Describe alternatives you've considered

Currently we use curl or some other load testing framework to set these headers as needed. This would be a nice UX change on the GUI.

**Comment by Player256** [comment]
Hey @GiedriusS where I should add the checkbox in the ui specifically?
![Thanos _ Highly available Prometheus setup - Brave 29-07-2023 02_43_24](https://github.com/thanos-io/thanos/assets/92082372/c69d3e37-fc2d-487e-bdad-b2f5aea956d8)

**Comment by Vanshikav123** [comment]
Hello @GiedriusS I hope this message finds you well. I'm excited to introduce myself as a member of the Thanos community. I'm eager to contribute to the organization and help enhance the project. If possible, could you please consider assigning me this issue , I am also open to any guidance or feedback you can provide during the process.

**Comment by yeya24** [comment]
@Vanshikav123 Feel free to work on it as I feel no one is actively working on it now. We usually don't assign issues.
The implementation shouldn't be too hard. You can add `X-Thanos-Force-Tracing` to the query http request sent to Thanos backend.

**Comment by yeya24** [comment]
This seems closed by #6770
