### ISSUE TITLE
DATA RACE: logicalplan.Optimize(logicalOptimizers)

### ISSUE THREAD

**Issue by liguozhong** [thanos-io/thanos#6321]
**Thanos, Prometheus and Golang version used**:

	github.com/thanos-community/promql-engine v0.0.0-20230417154848-c2396ed5afd9
	github.com/thanos-io/objstore v0.0.0-20230201072718-11ffbc490204
	github.com/thanos-io/thanos v0.31.1-0.20230418080134-0c2af2155056

**Object Storage Provider**:
s3
**What happened**:
data race
**What you expected to happen**:
do not data race
**How to reproduce it (as minimally and precisely as possible)**:
run cortex ci

**Full logs to relevant components**:
![image](https://user-images.githubusercontent.com/9583245/235031242-568e74f0-caaa-4255-afb3-e943c3c1fa28.png)

**Anything else we need to know**:
The failure occurred in the ci environment in cortex.

```go
github.com/thanos-community/promql-engine/engine/engine.go
func(e *compatibilityEngine) NewRangeQuery
	lplan := logicalplan.New(expr, &logicalplan.Opts{
		Start:         start,
		End:           end,
		Step:          step,
		LookbackDelta: opts.LookbackDelta,
	})
	lplan = lplan.Optimize(e.logicalOptimizers)

```
this cortex test fail
```go
func TestChunkQueryable(t *testing.T) {
	t.Parallel()

	opts := promql.EngineOpts{
		Logger:             log.NewNopLogger(),
		ActiveQueryTracker: promql.NewActiveQueryTracker(t.TempDir(), 10, log.NewNopLogger()),
		MaxSamples:         1e6,
		Timeout:            1 * time.Minute,
	}
	for _, thanosEngine := range []bool{false, true} {
		for _, testcase := range testcases {
			for _, encoding := range encodings {
				for _, query := range queries {
					t.Run(fmt.Sprintf("%s/%s/%s/ thanos engine enabled = %t", testcase.name, encoding.name, query.query, thanosEngine), func(t *testing.T) {
						//parallel testing causes data race
						var queryEngine v1.QueryEngine
						if thanosEngine {
							queryEngine = engine.New(engine.Opts{
								EngineOpts:        opts,
								LogicalOptimizers: logicalplan.AllOptimizers,
							})
						} else {
							queryEngine = promql.NewEngine(opts)
						}

						store, from := makeMockChunkStore(t, 24, encoding.e)
						queryable := newMockStoreQueryable(store, testcase.f)
						testRangeQuery(t, queryable, queryEngine, from, query)
					})
				}
			}
		}
	}
}
```

**Comment by yeya24** [comment]
Umm, I think it is a bug we need to fix on Cortex side. This engine creation cannot be parallelized looks like so need to disable that in the test.

Let's have the issue on the Cortex repo instead X

**Comment by liguozhong** [comment]
In the cortex test, each engine is a new struct in run, which is theoretically the correct way to use it. 

/github.com/thanos-community/promql-engine/engine/engine.go
```go
func (o Opts) getLogicalOptimizers() []logicalplan.Optimizer {
	var optimizers []logicalplan.Optimizer
	if o.LogicalOptimizers == nil {
		optimizers = logicalplan.DefaultOptimizers
	} else {
		optimizers = o.LogicalOptimizers
	}
	return append(optimizers, logicalplan.TrimSortFunctions{})
}
```
My judgment is that the code of the thanos engine needs to be modified. 
`		optimizers = o.LogicalOptimizers
`For example, this line passing one array pointer to another is dangerous work. Because the outer array may be modified by another routine at runtime. We should duplicate this array in the engine. isn't it ?

```go
func (o Opts) getLogicalOptimizers() []logicalplan.Optimizer {
	var optimizers []logicalplan.Optimizer
	if o.LogicalOptimizers == nil {
		optimizers = logicalplan.DefaultOptimizers
	} else {
		optimizers = make([]logicalplan.Optimizer, len(o.LogicalOptimizers))
		copy(optimizers, o.LogicalOptimizers)
	}
	return append(optimizers, logicalplan.TrimSortFunctions{})
}
```

**Comment by liguozhong** [comment]
hi github , reopen issue please.

**Comment by liguozhong** [comment]
It would be great If we wait for more eyes to help confirm, we are rigorously evaluating whether cortex is a mature enough project to replace the current prometheus storage, and the current first interest meets the `data race` so that our confidence is dampened.

**Comment by liguozhong** [comment]
Maybe we will spend 1 or 2 years to confirm that the code of cortex is reliable enough. 
We have evaluated VictoriaMetrics before. Because it does not support wal, and the design of asyn writing to disk, VictoriaMetrics is evaluated as an unreliable TSDB.
so we are in the community Looking for a new prometheus TSDB.

Every datarace is a very critical issue, we should probably analyze why this happened in more detail

**Comment by yeya24** [comment]
I understand what you said. But since it is an issue in the tests of Cortex, please open an issue there first and we can see if there is a bug in the Cortex code or not.
And Thanos engine is a separate repo https://github.com/thanos-community/promql-engine, so if you think the data race is relevant please open an issue there instead of this repo. Thanks

**Comment by liguozhong** [comment]
ok
