### ISSUE TITLE
Proposal: expose bucket store queryStats as part of Series response hints

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#6344]
### Is your proposal related to a problem?

Thanos Store Gateway collects query stats in https://github.com/thanos-io/thanos/blob/main/pkg/store/bucket.go#L3050 during `Series` request. However, for projects that use Thanos as a library, such as Cortex, there is no way to utilize that queryStats.

The queryStats got collected and will only be logged in debug mode.  However, it is usually quite expensive to enable debug if we only want to utilize some of the fields in queryStats.

### Describe the solution you'd like

Add a bool field called to enable return queryStats in https://github.com/thanos-io/thanos/blob/main/pkg/store/hintspb/hints.proto#L22.

Accordingly, the query stats fields will be added into the hints response here https://github.com/thanos-io/thanos/blob/main/pkg/store/hintspb/hints.proto#L29.

**Comment by christopherzli** [comment]
Nice work, just curious why we only expose store gateway, but not entire store api including receiver. Would that be an extension?
