### ISSUE TITLE
Coding style guide ambiguous definition

### ISSUE THREAD

**Issue by omgnull** [thanos-io/thanos#6353]
**Thanos, Prometheus and Golang version used**:
Thanos: v0.31.0

**What happened**:
Style guide definition conflict.

1. Recommendation to `do something and hanle error`
  https://github.com/thanos-io/thanos/blob/v0.31.0/docs/contributing/coding-style-guide.md?plain=1#L94
  ```go
  runutil.CloseWithErrCapture(&err, f, "close file")
  ```

3. Recommendation to avoid `do something and hanle error`
  https://github.com/thanos-io/thanos/blob/v0.31.0/docs/contributing/coding-style-guide.md?plain=1#L401
  ```go
   s.doSomethingAndHandleError()
  ```

**What you expected to happen**:
No definition conflict

**Comment by Ayush9026** [comment]
Hello @omgnull i want to work on this issue.

**Comment by Ayush9026** [comment]
Hi @omgnull i want to work on this issue.

**Comment by saswatamcode** [comment]
Hmm, so I think the first style guide definition, is to guide around how to handle errors in `defer` statements, where you can't return the error, so you should use `runutil` methods, so handle them explicitly, and not ignore them

And the second is to avoid having shallow functions and to inline them to avoid unnecessary cognitive load.

I don't exactly see how those two conflict?

**Comment by bwplotka** [comment]
Thanks for the report, but I think you might have misunderstood the point 1.  

With 

```
runutil.CloseWithErrCapture(&err, f, "close file")
```

...we don't just `do something and handle error`. We actually "do something" and return error. Just the error can't be easily returned as @saswatamcode mentioned in the defer, plus we might have existing error in `err`. For this reason we might need this special pattern to return the error for closing (or attach an extra error) to the returned function error (`err`).

What would be the improvement to style guide in terms of wording to improve the next reader understanding of this? (:
