### ISSUE TITLE
Clarification about retention

### ISSUE THREAD

**Issue by pr3d1** [thanos-io/thanos#6366]
Hello!

I would like to see clarity on the retention settings. I read this in the compactor help:
```
--retention.resolution-raw=0d
                               How long to retain raw samples in bucket. 0d -
                               disables this retention
```
I read this [here](https://thanos.io/tip/components/compact.md/#enforcing-retention-of-data):
`By default, there is NO retention set for object storage data. This means that you store data forever, which is a valid and recommended way of running Thanos.`
And in the [source code](https://github.com/thanos-io/thanos/blob/bd2a0ac1fad8d9806656ce4982192d019ea3a5dc/pkg/compact/retention.go#L23) i found this comment: `// A value of 0 disables the retention for its resolution.`
I think this very confusing, because for me, turning off retention means that no data is retained. However, I think the setting does the opposite and keeps all the data. Can you clarify the documentation?
Many thanks!

**Comment by yeya24** [comment]
> I think this very confusing, because for me, turning off retention means that no data is retained

Disable retention means we won't do any retention on the data. It is the same behavior as Prometheus does. https://github.com/prometheus/prometheus/blob/80b7f73d267a812b3689321554aec637b75f468d/tsdb/db.go#L1486 If retention is configured as 0 then we don't do retention.
