### ISSUE TITLE
Unexpected response status when fetching server time error in thanos query dashboard

### ISSUE THREAD

**Issue by shruthidharani-4313** [thanos-io/thanos#6391]
I have installed the "monitoring" app (via rancher UI) which is provided by kubernetes. On top of it, I have deployed thanos-sidecar as 4th container in the prometheus pod running in cattle-monitoring-system with 3 containers. And this thanos-sidecar is able to push metrics to AWS s3 bucket (object-storage-config provides as input). 
```
prometheus-rancher-monitoring-prometheus-0                4/4     Running   0             28m
```

After this I have deployed following thanos components using bitnami/thanos chart
- Thanos Query
- Thanos Bucket Web
- Thanos Compactor
- Thanos Store Gateway 

```
Thanos chart was deployed enabling the following components:
- Thanos Query
- Thanos Bucket Web
- Thanos Compactor
- Thanos Store Gateway
```

I am not getting any kind of errors in these deployed thanos components pod's logs. And if I configure this thanos-query as a new data source in grafana dashboard, I am able to query and list the metrics without any issues. 

But I am aware of that Thanos-query gives a UI where we can execute the promql queries and get the metrics. What changes are required to access the thanos-query UI from within kubernetes rancher UI? Or is there any other possible and easy way to access thanos-query UI? I tried kubectl port-forward but I could not able to reach `http://127.0.0.1:${SERVICE_PORT}`  from my browser (got connection refused).

I tried accessing the thanos-query UI page by constructing the below URL
`https://ranchermanager.com/k8s/clusters/c-8b9ut/api/v1/namespaces/cattle-monitoring-system/services/http:thanos-query:9090/proxy/` which is just like how it is for other monitoring apps provided by prometheus `https://ranchermanager.com/k8s/clusters/c-8b9ut/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-prometheus:9090/proxy/graph`. but it doesn't work.
<img width="953" alt="thanos dashboard err" src="https://github.com/thanos-io/promql-engine/assets/74370667/50b87fff-e6f4-41af-90da-c83a9084afa9">

It would be really helpful if someone helps me to resolve this issue. I am not sure how to debug this issue as I am not seeing any error logs as such in the thanos components.

**Comment by Atrbear** [comment]
Hi, i am facing the same problem, can you tell me how to solve this?
