### ISSUE TITLE
Compact creating blocks way beyond max compaction level

### ISSUE THREAD

**Issue by douglascamata** [thanos-io/thanos#6400]
**Thanos, Prometheus and Golang version used**: Thanos v0.31.0, v0.30.2.

**Object Storage Provider**: S3

**What happened**

While running with `--debug.max-compaction-level=3` the Compactor has been intermittently generating blocks with with high compaction level (from 5 all the way to 28 sometimes, see picture below). 

This happens across all the block streams created/uploaded **by Receive**, in the same time ranges. 

Blocks created by Rulers are fine.

<img width="1797" alt="image" src="https://github.com/thanos-io/thanos/assets/159076/8658b528-d2df-486c-89f3-9cac2f285d5e">

**What you expected to happen**

To have blocks only at maximum compaction level 4, as they will be generated from the level 3 blocks. Level 4 blocks shouldn't be further compacted to generated level 5 or higher blocks.

**How to reproduce it (as minimally and precisely as possible)**

Not able to reproduce yet.

**Full logs to relevant components**

No relevant logs.

**Anything else we need to know**

On the most recent creation of high level blocks I could see that the Compactor container was rolled out. Unfortunately I don't have enough telemetry going back to the creation of other high-level blocks due to a 30 days retention on the Prometheus keeping this data.

**Comment by bwplotka** [comment]
This is common issue - as is - the compaction planning algorithm seems to be bit naive and cause multiple compactions, many times in place. We know it's in place as the source of those blocks is valid and the only consequence is multiple compactions done for no reason (unless we only change meta compaction level?) AND bump in compaction level to some number.

Definitely worth investigating but it never caused major problems.

**Comment by fpetkovski** [comment]
I feel like compaction level should not be exposed to users to control/limit since it's an internal detail. Limits on block duration/num series makes more sense.

**Comment by douglascamata** [comment]
@bwplotka ahhh, makes total sense then. When this happens I see that our Receives are also rolling out. So I suspect something's happening there when the head blocks isn't flushed and the new Receive's are replaying the WAL. Then it ends up generating two smaller blocks (supposition) that Compactor decides to concatenate later. 

Sounds like something that can be mitigated by the hidden flag `tsdb.memory-snapshot-on-shutdown` on Receive. 🤔

**Comment by douglascamata** [comment]
Confirmed through writing an e2e test. When Receives are configured with replication and to upload to object storage on graceful shutdown the head blocks get compacted/flushed and uploaded. 

Then a Compactor configured to deduplicate this data merges them together first horizontally, getting some extra levels from the Receive head block uploads (smaller than 2 hours and overlapping). Later it does the vertical compactions and the resulting levels will be higher than in the steady state of the system.

There's no issues besides some fragmentation in the block's compaction level... so I think we can close this? Up to you, @bwplotka and @fpetkovski.

**Comment by GiedriusS** [comment]
I think let's close it. I don't think this leads to any problems for the user?
