### ISSUE TITLE
Thanos query  get No data  if the time  is older than 2 weeks

### ISSUE THREAD

**Issue by btdan** [thanos-io/thanos#6401]
Hello, I have configued the thanos query and receive .And thanos receive can receive the data from prometheus and send to object storage system. And thanos query can query and return the result.
I find that I can query the data collected in about 2 weeks.
But if I query data which is older than 2 weeks, I get NO DATA. But in fact the data is stored in the object storage system.
The command of thanos receive is as follows:

**nohup thanos receive \
    --tsdb.path  "/aiops/webMonitor/"  \
    --grpc-address aaa.bbb.com:10907  \
    --http-address aaa.bbb.com:10909  \
    --receive.replication-factor 1  \
    --label "receive_replica=\"0\""  \
    --label "receive_cluster=\"webmonitor\""  \
    --receive.local-endpoint aaa.bbb.com:10907  \
    --receive.hashrings-file /aiops/hashring.json  \
    --remote-write.address aaa.bbb.com:10908  \
    --objstore.config-file "/aiops/bucket.yml" > /aiops/webMonitor/thanos_receive.log 2>&1 &**

and the comman thanos query is as follows:
**nohup thanos query --http-address aaa.bbb.com:19192 --grpc-address=aaa.bbb.com:10906  --store aaa.bbb.com:10907 > /aiops/webMonitor/thanos_query.log 2>&1 &**

For example, Today is May 31, if I query the data which is collected in May 15, I will get nothing at all. Just display NO DATA.
I don't know how to solve this problem. Can anyone help me?
Thanks very much. Best wishes.

**Comment by btdan** [comment]
I have found this url  https://github.com/thanos-io/thanos/issues/6312
the author mentioned that "It turned out to be an issue with the store configuration. I had --min-time=-4w which is filtering out the data outside of 4 weeks. After removing it, I am able to see all the data."

But however, I find nothing about --min-time in my configuration.
Thanks a lot

**Comment by mhoffm-aiven** [comment]
Do you have a store gateway configured somewhere?

**Comment by fpetkovski** [comment]
Thanks for reporting back @btdan, can we close the issue?

**Comment by btdan** [comment]
yes, we can close this issue.
Thanks for your help.

**Comment by Vidyasagar9390** [comment]
Hi @btdan how you solve this issue 
currently im faicng this issue
