### ISSUE TITLE
Thanos Ruler Component - S3 Error Warning Logs

### ISSUE THREAD

**Issue by shaheislam** [thanos-io/thanos#6436]
**Thanos, Prometheus and Golang version used**:

  name: thanos
  version: "11.6.8"

**Object Storage Provider**:
S3

**What happened**:

Do not expect these warnings to show up in Thanos Ruler component, although they are. This does not prevent the Ruler from triggering Alertmanager however why are these logs showing?

**What you expected to happen**:

No warning logs related to S3 access denied.

Setting Ruler within values.yaml 

  ruler:
    enabled: true
    alertmanagers: [http://alertmanager.info]
    existingConfigmap: thanos-ruler

level=warn ts=2023-06-12T08:17:24.353115099Z caller=rule.go:735 component=rules err="check exists: stat s3 object: Access Denied."
level=warn ts=2023-06-12T08:17:54.360456637Z caller=rule.go:735 component=rules err="check exists: stat s3 object: Access Denied."

**Anything else we need to know**:

**Environment**:
- OS (e.g. from /etc/os-release):
- Kernel - Linux a-1z8csdi2hvzu3 5.15.79-51.138.amzn2.x86_64 #1 SMP Mon Nov 28 18:44:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by shaheislam** [comment]
Further logs if required

❯ k logs thanos-ruler-0
E0612 10:01:06.556840   32575 memcache.go:255] couldn't get resource list for external.metrics.k8s.io/v1beta1: Got empty response for: external.metrics.k8s.io/v1beta1
level=info ts=2023-06-12T09:00:45.367598692Z caller=repair.go:56 component=tsdb msg="Found healthy block" mint=1686233841014 maxt=1686240000000 ulid=01H2E08CTXBR1NBFVAY8FJHHM6
level=info ts=2023-06-12T09:00:45.368344946Z caller=repair.go:56 component=tsdb msg="Found healthy block" mint=1686240021014 maxt=1686247200000 ulid=01H2E65006YRPKQC5MXFQ898JY
level=info ts=2023-06-12T09:00:45.369157Z caller=repair.go:56 component=tsdb msg="Found healthy block" mint=1686247221014 maxt=1686254400000 ulid=01H2ED0Q91X5XXJX4S2FRDN6WC
level=info ts=2023-06-12T09:00:45.369554739Z caller=repair.go:56 component=tsdb msg="Found healthy block" mint=1686254421014 maxt=1686261600000 ulid=01H2EKWEG1RDEP9VWQTZRS9001
level=info ts=2023-06-12T09:00:45.370332937Z caller=repair.go:56 component=tsdb msg="Found healthy block" mint=1686261621014 maxt=1686268800000 ulid=01H2ETR5RAPAJ9MYZC8XHB3R2M
level=info ts=2023-06-12T09:00:45.371095749Z caller=repair.go:56 component=tsdb msg="Found healthy block" mint=1686268821014 maxt=1686276000000 ulid=01H2F1KX0715CG4Q1K0JT5EWC4
level=info ts=2023-06-12T09:00:45.371915899Z caller=repair.go:56 component=tsdb msg="Found healthy block" mint=1686276021014 maxt=1686283200000 ulid=01H2F8FM7Y005P943VCBMP87PH
level=info ts=2023-06-12T09:00:45.372228922Z caller=repair.go:56 component=tsdb msg="Found healthy block" mint=1686283221014 maxt=1686290400000 ulid=01H2FFBBG5HBKPG0ZHHAESMPYG
level=info ts=2023-06-12T09:00:45.373042409Z caller=repair.go:56 component=tsdb msg="Found healthy block" mint=1686290400000 maxt=1686297600000 ulid=01H2FP584X3ZVQ6710F6GPH85D
level=info ts=2023-06-12T09:00:45.373848991Z caller=repair.go:56 component=tsdb msg="Found healthy block" mint=1686297600000 maxt=1686304800000 ulid=01H2FYJDDYFHCTCK6636F2SMYG
level=info ts=2023-06-12T09:00:45.374179166Z caller=repair.go:56 component=tsdb msg="Found healthy block" mint=1686304821014 maxt=1686312000000 ulid=01H2G3YH9R39FQA2SGNSDWQW8S
level=info ts=2023-06-12T09:00:45.374489385Z caller=repair.go:56 component=tsdb msg="Found healthy block" mint=1686312021014 maxt=1686319200000 ulid=01H2GAT8FZENKFG9PW0AQ17NYF
level=info ts=2023-06-12T09:00:45.374982431Z caller=repair.go:56 component=tsdb msg="Found healthy block" mint=1686319221014 maxt=1686326400000 ulid=01H2GHNZQYYJQY40MK5DVPVA89
level=info ts=2023-06-12T09:00:45.41227664Z caller=head.go:562 component=tsdb msg="Replaying on-disk memory mappable chunks if any"
level=info ts=2023-06-12T09:00:45.412307565Z caller=head.go:606 component=tsdb msg="On-disk memory mappable chunks replay completed" duration=6.725µs
level=info ts=2023-06-12T09:00:45.412317043Z caller=head.go:612 component=tsdb msg="Replaying WAL, this may take a while"
level=info ts=2023-06-12T09:00:45.414616815Z caller=head.go:648 component=tsdb msg="WAL checkpoint loaded"
level=info ts=2023-06-12T09:00:45.415767524Z caller=head.go:683 component=tsdb msg="WAL segment loaded" segment=37 maxSegment=42
level=info ts=2023-06-12T09:00:45.41746933Z caller=head.go:683 component=tsdb msg="WAL segment loaded" segment=38 maxSegment=42
level=info ts=2023-06-12T09:00:45.419325348Z caller=head.go:683 component=tsdb msg="WAL segment loaded" segment=39 maxSegment=42
level=info ts=2023-06-12T09:00:45.42025185Z caller=head.go:683 component=tsdb msg="WAL segment loaded" segment=40 maxSegment=42
level=info ts=2023-06-12T09:00:45.420409322Z caller=head.go:683 component=tsdb msg="WAL segment loaded" segment=41 maxSegment=42
level=info ts=2023-06-12T09:00:45.420809121Z caller=head.go:683 component=tsdb msg="WAL segment loaded" segment=42 maxSegment=42
level=info ts=2023-06-12T09:00:45.420831336Z caller=head.go:720 component=tsdb msg="WAL replay completed" checkpoint_replay_duration=2.310693ms wal_replay_duration=6.193788ms wbl_replay_duration=208ns total_replay_duration=8.52942ms
level=info ts=2023-06-12T09:00:45.421546088Z caller=rule.go:761 msg="a leftover lockfile found and removed"
level=info ts=2023-06-12T09:00:45.421974141Z caller=options.go:26 component=rules protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2023-06-12T09:00:45.423885389Z caller=factory.go:52 component=rules msg="loading bucket configuration"
level=info ts=2023-06-12T09:00:45.424096753Z caller=rule.go:746 component=rules msg="starting rule node"
level=info ts=2023-06-12T09:00:45.424184287Z caller=manager.go:944 component=rules msg="Starting rule manager..."
level=info ts=2023-06-12T09:00:45.424176769Z caller=manager.go:944 component=rules msg="Starting rule manager..."
level=info ts=2023-06-12T09:00:45.424207762Z caller=intrumentation.go:75 component=rules msg="changing probe status" status=healthy
level=info ts=2023-06-12T09:00:45.424244032Z caller=http.go:73 component=rules service=http/server component=rule msg="listening for requests and metrics" address=0.0.0.0:10902
level=info ts=2023-06-12T09:00:45.424260763Z caller=rule.go:895 component=rules msg="reload rule files" numFiles=1
level=info ts=2023-06-12T09:00:45.424338678Z caller=intrumentation.go:56 component=rules msg="changing probe status" status=ready
level=info ts=2023-06-12T09:00:45.424387295Z caller=tls_config.go:232 component=rules service=http/server component=rule msg="Listening on" address=[::]:10902
level=info ts=2023-06-12T09:00:45.424429546Z caller=tls_config.go:235 component=rules service=http/server component=rule msg="TLS is disabled." http2=false address=[::]:10902
level=info ts=2023-06-12T09:00:45.42443629Z caller=grpc.go:131 component=rules service=gRPC/server component=rule msg="listening for serving gRPC" address=0.0.0.0:10901
level=warn ts=2023-06-12T09:00:45.488167539Z caller=rule.go:735 component=rules err="check exists: stat s3 object: Access Denied."

**Comment by MichaHoffmann** [comment]
I think ruler is uploading blocks to object storage; for example for recording rules. To do that it needs access to cloud storage.
