### ISSUE TITLE
Sidecar: Shipper bytes uploaded metric

### ISSUE THREAD

**Issue by jpds** [thanos-io/thanos#6438]
### Describe the solution you'd like

I can't see a metric for the number of bytes the shipper has uploaded under:

- `thanos_objstore*`
- `thanos_shipper*`

This might be useful for helping debug replicas monitoring the same targets which should roughly be shipping the same amount of data.

**Comment by ritaCanavarro** [comment]
Hi,
I am interested in implementing this, if you do not mind 😄

**Comment by yeya24** [comment]
@ritaCanavarro Assigned to you.

**Comment by coleenquadros** [comment]
Hi @jpds, I was looking at the shipper.go file and I see this metric `thanos_shipper_uploads_total` I wanted to know how is this metric different from the expected shipper bytes uploaded

**Comment by ritaCanavarro** [comment]
Hi @yeya24 😊 
If you could review the PR: https://github.com/thanos-io/thanos/pull/6500?

Thanks!

**Comment by ritaCanavarro** [comment]
Hi 😊 
@yeya24 could you please code review the PR? 
PR: https://github.com/thanos-io/thanos/pull/6544

Best regards,
Rita Canavarro

**Comment by ritaCanavarro** [comment]
Hi @yeya24,
This change is being applied here: https://github.com/thanos-io/objstore/pull/66.
After some discussions, it was decided to move the implementation there.

**Comment by ritaCanavarro** [comment]
Hi @yeya24,
The metrics were implemented here:  https://github.com/thanos-io/objstore/pull/66 and are already merged to master.

**Comment by douglascamata** [comment]
Closing as #6544 got merged. 

Thank you, @ritaCanavarro 🙇
