### ISSUE TITLE
Add missing /-/healthy endpoint

### ISSUE THREAD

**Issue by danielmotaleite** [thanos-io/thanos#644]
**Thanos, Prometheus and Golang version used**

thanos_build_info{branch="master",goversion="go1.10.5",revision="9cec8371f78cd96dba7405885773eb7afc8556dc",version="0.1.0"} 1
improbable/thanos:master-2018-11-12-9cec837

**What happened**
on thanos-sidecar i have done this:

`curl localhost:10902/-/healthy`

**What you expected to happen**
Thanos-sidecar health status .. instead i got 404. Notice that /metrics do return successful

So while thanos-query return the /-/healthy endpoint, at least thanos-sidecar and thanos-store do not. They should exist for consistency and to help building proper healthchecks

i still haven't deployed thanos-rules and thanos-compact, so i can't tell if they are also missing the endpoint

**Comment by bwplotka** [comment]
This known. The advice is to use `/metrics` as healthy endpoint for now which nicely shows when service is ready. 

This might be not elegant as metrics endpoint is for different purposes, so PRs welcome (:

**Comment by FUSAKLA** [comment]
Hooray so this should be finally resolved, thanks @kakkoyun for helping with this and everyone reviewing :tada: 

Related PRs:
- [#1540](https://github.com/thanos-io/thanos/pull/1540) Thanos Downsample added `/-/ready` and `/-/healthy` endpoints.
- [#1538](https://github.com/thanos-io/thanos/pull/1538) Thanos Rule added `/-/ready` and `/-/healthy` endpoints.
- [#1537](https://github.com/thanos-io/thanos/pull/1537) Thanos Receive added `/-/ready` and `/-/healthy` endpoints.
- [#1460](https://github.com/thanos-io/thanos/pull/1460) Thanos Store Added `/-/ready` and `/-/healthy` endpoints.
- [#1534](https://github.com/thanos-io/thanos/pull/1534) Thanos Query Added `/-/ready` and `/-/healthy` endpoints.
- [#1395](https://github.com/thanos-io/thanos/pull/1395) Thanos Sidecar added `/-/ready` and `/-/healthy` endpoints to Thanos sidecar.
- [#1297](https://github.com/thanos-io/thanos/pull/1297) Thanos Compact added `/-/ready` and `/-/healthy` endpoints to Thanos compact.
