### ISSUE TITLE
Shipper doesn't upload OOO compacted blocks

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#6462]
**What happened**:

If OOO is enabled, then shipper won't upload those OOO compacted blocks because their compaction level is > 1 but shipper doesn't upload compacted blocks when OOO is enabled.

https://github.com/thanos-io/thanos/blob/main/pkg/shipper/shipper.go#L295

See https://github.com/cortexproject/cortex/issues/5402 also

**What you expected to happen**:

If out of order samples feature is enabled, shipper should still be able to upload those compacted blocks to objstore.

**How to reproduce it (as minimally and precisely as possible)**:

Run two Prometheus instances with the same external labels. Remote write to one receiver with object store configured and OOO enabled.

**Alternatives**:

I am not sure about Prometheus' logic of OOO block compaction. But it sounds weird because compaction should be turned off so even if we have overlapped blocks generated from OOO, we shouldn't do any local compaction but let compactors take care of it. Seems like TSDB instead always tries to compact overlapping blocks and we don't have a way to disable that.

**Comment by yeya24** [comment]
I am able to see blocks still being compacted due to overlapping. It was generated from OOO blocks.

```
{
	"ulid": "01H3BPCJCK1VR0PP9C9BQ6F35V",
	"minTime": 1687240800000,
	"maxTime": 1687241100000,
	"stats": {
		"numSamples": 1050,
		"numSeries": 35,
		"numChunks": 85
	},
	"compaction": {
		"level": 2,
		"sources": [
			"01H3BPAV0PM2039C54HDP3BG1Z",
			"01H3BPCHXCQPQYSG477FJY3RX7"
		],
		"parents": [
			{
				"ulid": "01H3BPAV0PM2039C54HDP3BG1Z",
				"minTime": 1687240800000,
				"maxTime": 1687241100000
			},
			{
				"ulid": "01H3BPCHXCQPQYSG477FJY3RX7",
				"minTime": 1687240800000,
				"maxTime": 1687241100000
			}
		]
	},
	"version": 1
}
```

**Comment by fpetkovski** [comment]
Is there a way to distinguish an OOO block from a regular one?

**Comment by yeya24** [comment]
@fpetkovski, there is a method to set compaction hints to out of order https://github.com/prometheus/prometheus/blob/main/tsdb/block.go#L196.

But this seems only available on lv1 block created from OOO head. After 1 compaction this hint will be removed.

**Comment by yeya24** [comment]
@fpetkovski Not sure if it works or not because source blocks will be deleted after compaction so shipper might miss that? I guess having a fsnotify watcher might work, but that over complicates things.

What's the downside if we just enable upload compacted blocks when OOO is enabled?

**Comment by yeya24** [comment]
@ahurtaud I think it is an interesting idea. But it is hard to ensure that within this delay the OOO block compaction will happen and we can get the l2 block.
One way I think is that we can skip l1 block with `from-out-of-order` hints. But we still need to support upload compacted block for the l2 block. It would be great if the l2 block can have some hints tbh.

**Comment by fpetkovski** [comment]
I wonder if we can modify the [duplicate filter](https://github.com/thanos-io/thanos/blob/main/pkg/block/fetcher.go#L597) to filter out source OOO blocks once a compacted version is available.

**Comment by yeya24** [comment]
@fpetkovski I was thinking about the same, but it requires the upload delay and I feel it cannot ensure we don't upload L1 blocks.
To me I feel it is simplest to just upload both blocks and enable vertical compaction.

**Comment by yeya24** [comment]
I think what we will do is to always enable shipper uploading compacted blocks in Cortex. It is used in ingester which is almost the same as receiver.
I found other than OOO samples scenario, there is no other way to generate compacted blocks at ingester so it should be safe to enable it.

**Comment by GiedriusS** [comment]
Should we enable uploading compacted blocks if OOO is enabled and then close this issue @yeya24 ?

**Comment by GiedriusS** [comment]
We now disable overlapping compaction in the TSDB/Receiver so this doesn't happen anymore. I'll close the ticket

**Comment by bmiguel-teixeira** [comment]
Hey,

Is there a MR or Release that contains this change/fix/improvement?

**Comment by wwilfinger** [comment]
> Is there a MR or Release that contains this change/fix/improvement?

My best guess is this: https://github.com/thanos-io/thanos/pull/7065
