### ISSUE TITLE
Receive: file reloading broken with k8s config maps or secrets

### ISSUE THREAD

**Issue by douglascamata** [thanos-io/thanos#6491]
**Thanos, Prometheus and Golang version used**:

Thanos: v0.30.2
Prometheus: N/A
Golang: N/A

**Object Storage Provider**: N/A

**What happened**:

Today I was debugging something with a colleague regarding Thanos’ fs watcher based configuration reloaders. Both implementations, which I call “new” (the PathContentReloader function) and “old”, have big problems with k8s config maps and secrets. 

We pushed new limits configuration to our Receive pods and they've never detected the file changes. In the past we also pushed hashring configuration changes that were never detected by the fs watcher and only became effective when Thanos re-read the whole file.

K8s config maps and secrets are using lots of symlinks. Every file inside inside them is a symlink. And the parent folder as well. From what we see, this makes file changes transparent to both implementations. :disappointed: 

**What you expected to happen**:

Thanos Receive to detect the changes in the files and reload them properly.

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy Thanos Receive in Kubernetes
2. Mount the hashring or limits configuration from a ConfigMap or Secret. 
3. Change the configuration mounted.
4. Confirm updated file is inside pods. 
5. Confirm Thanos Receive never reloaded them.
6. Open them manually, change something, save and exit.
7. Confirm Thanos Receive finally reloaded them.

**Full logs to relevant components**: N/A

**Anything else we need to know**:

We plan to try to open a PR to improve the new implementation, allowing it to detect such situation (file and its folder being symlinks) and default to re-read the file every 5s or so (maybe with some added logic to be smart and efficient about it). 

Some reading material to better understand the issue:

* https://github.com/kubernetes/kubernetes/issues/112677
* https://martensson.io/go-fsnotify-and-kubernetes-configmaps/
* https://ahmet.im/blog/kubernetes-inotify/

**Comment by douglascamata** [comment]
I think it should be fine, @manulpatel. Let us know when you have a PR ready. :)

**Comment by douglascamata** [comment]
Seems like we could solve the problem by trying to reloading the configuration when we get a "remove" event. At this point though I believe the `fsnotify`-based implementation is becoming increasingly complex and full of gotchas. Keeping only the polling-based solution seems attractive as it's a pretty simple and effective one. Waiting for a discussion with maintainers to see what we'll do moving forward.

**Comment by yashvardhanmishra** [comment]
Hi @douglascamata,

I would like to work on this issue and help resolve the problem with file reloading in Thanos Receive. I have experience with Kubernetes . Could you please assign this issue to me? I'm excited to work on it!

**Comment by douglascamata** [comment]
Hello @yashvardhanmishra. There's already a PR linked to this issue that should solve the problem: #6503.

**Comment by douglascamata** [comment]
Considering #6503 is merged, now we have ways to circumvent the symlink issues on both mechanisms used to reload configuration. We should migrate the hashring one to use the same mechanism as the tenant limit configuration, but this can be tracked in another issue.

Closing this as the problem's gone.
