### ISSUE TITLE
Spelling mistake in the documentation

### ISSUE THREAD

**Issue by TritonNet** [thanos-io/thanos#6492]
There is a spelling mistake in the example provided in the [Querier/Query](https://thanos.io/tip/thanos/quick-tutorial.md/#querierquery) section.

![image](https://github.com/thanos-io/thanos/assets/26731252/10d72c73-0dda-40f7-bbce-b8c6e792162f)

**Comment by fpetkovski** [comment]
Sure thing, feel free to raise a PR

**Comment by heliapb** [comment]
Hi @fpetkovski it was merged, I guess the issue can be closed

**Comment by squat** [comment]
@heliapb thanks :)
