### ISSUE TITLE
Store: `ExpandPostings` returning postings for time series not matched by matchers

### ISSUE THREAD

**Issue by rabenhorst** [thanos-io/thanos#6495]
**Thanos, Prometheus and Golang version used**:
[main 0651f334324572266844f73882e61d746ec7e91b
](https://github.com/thanos-io/thanos/tree/0651f334324572266844f73882e61d746ec7e91b)

**Object Storage Provider**: N/A

**What happened**:
When using Thanos from main (version stated above) with the Thanos Prometheus engine, we sporadically see `vector cannot contain metrics with the same labelset` error for specific queries. Running `sum by (__name__) (some_metric{some="label"})` for the metrics that triggered the error, we sometimes got additional time series for metrics different from `some_metric`. 

Further investigating we noticed that the bucket's `Series` call returns some thousand series, instead of two series we would expected according the the matchers in the request. Debugging lead us to `ExpandPostings` of the `blockSeriesClient`, which sometimes seems to return postings for times series that are not matched by the provided matchers. We were able to narrow it down to https://github.com/thanos-io/thanos/pull/6420 and removing this PR resolved the issue. We didn't investigate further yet and don't know which part of the PR is causing the issue, but we assume it might be a race condition, since it only happens sporadically.

**What you expected to happen**:
Don't see `vector cannot contain metrics with the same labelset` error or metrics for different time series being returned.

**How to reproduce it (as minimally and precisely as possible)**:
We were able to reproduce it by running a store against our production GCP bucket for specific tenants with index cache enabled, but weren't able to reproduce it with a bucket test yet.

**Full logs to relevant components**: N/A

**Anything else we need to know**: N/A

**Environment**:
It happens for both the production deployment and locally when pointing stores at our production buckets.

**Comment by fpetkovski** [comment]
@yeya24 I wonder if you are seeing this in Cortex as well.

**Comment by yeya24** [comment]
Thanks for the report. I was not aware of this issue and I haven't found anything weird so far. I will take a closer look today.

**Comment by GiedriusS** [comment]
I also run with that change and haven't seen anything like this.

**Comment by alanprot** [comment]
Hum...

Maybe I'm missing something but shouldn't  we have the "matcher type" on the cache key?

https://github.com/thanos-io/thanos/blob/e2123a9d217013e75eac732d3bfb3fa10911d909/pkg/store/cache/memcached.go#L136-L137

https://github.com/thanos-io/thanos/blob/e2123a9d217013e75eac732d3bfb3fa10911d909/pkg/store/cache/cache.go#L118-L127

**Comment by yeya24** [comment]
@rabenhorst Regarding the problematic query `sum by (__name__) (some_metric{some="label"})`, does it have issue for all metrics or only specificf metrics/series?

If you remove the `sum by` and run `some_metric{some="label"}`, can you share what series will be included in the response? For the additional time series added, do they have anything in common or there is nothing in common.

If you are able to connect your local Thanos to the bucket, then it would be really appreciated to run store gateway in debug mode and reproduce this issue.

**Comment by rabenhorst** [comment]
> It would be better to provide a unit test to reproduce this.

We spent quiet some time on debugging this already and didn't succeed yet in creating a test to replicate it. If we succeed implement test I will update this issue.

> @rabenhorst Regarding the problematic query `sum by (__name__) (some_metric{some="label"})`, does it have issue for all metrics or only specificf metrics/series?

It only happens for specific metrics and sporadically. It was hard to reproduce and narrow down to specific stores.

> If you are able to connect your local Thanos to the bucket, then it would be really appreciated to run store gateway in debug mode and reproduce this issue.

We managed to do that, but couldn't find out why it is happening yet and will try to debug further. I will post updates here, if we find something.

**Comment by yeya24** [comment]
@rabenhorst It would be great to hear if we have any other updates on this issue.

**Comment by rabenhorst** [comment]
> @rabenhorst It would be great to hear if we have any other updates on this issue.

As @fpetkovski and you just pointed out this might be fixed by #6575. While we were never able to reproduce the issue with a test, we can see if the issue is still reproducible with the setup where we saw the issue before.

**Comment by GiedriusS** [comment]
I saw a bunch of races in Thanos Store prod so either one of them might be causing this: https://github.com/thanos-io/thanos/issues/6583
https://github.com/thanos-io/thanos/issues/6584
https://github.com/thanos-io/thanos/issues/6585

**Comment by GiedriusS** [comment]
Do you have a way to consistently reproduce this?

**Comment by farodin91** [comment]
I don't think. My ruler is running into these issues multiple every minute. I see in trace that the query frontend is the main first component that shows any issue.

**Comment by farodin91** [comment]
We did run on 0.31.0 before.

**Comment by MichaHoffmann** [comment]
> 

Can you try again with latest main? Ruler was missing the deduplication fix from 0.32.0 but @saswatamcode added it recently.

**Comment by joaosilva15** [comment]
Hello. I tested with the new 0.32.2 and it did not fix my issue. In my case, it also happens while querying the sidecars.
I'm trying to simulate this in a more controlled environment but it seems to happen randomly.
In my case I'm running a query like `max_over_time(pipelinerun:deploy_step:duration_seconds[2h])`. The query uses a recording rule but when using the expanded expression everything works.

**Comment by MichaHoffmann** [comment]
Are you able to test with a nightly? We merged a fix for deduplication recently that was not yet released

**Comment by joaosilva15** [comment]
Hey @MichaHoffmann 👋 it indeed seems to have fixed my problem. Thank you for the fast response!

**Comment by MichaHoffmann** [comment]
awesome :tada:

**Comment by saswatamcode** [comment]
Please try out v0.32.3 as well! Thanks!

**Comment by joaosilva15** [comment]
Tested and it works 😄 thanks!

**Comment by fpetkovski** [comment]
I will close this issue and we can reopen it if necessary.
