### ISSUE TITLE
Thanos Store doesn't load new blocks

### ISSUE THREAD

**Issue by AlexandarY** [thanos-io/thanos#6558]
**Thanos, Prometheus and Golang version used**:
thanos, version 0.30.1 (branch: master, revision: 33b1850fb2c9a2cba36fad8f902a406b40b013c2)
  build date:       20230608-17:16:21
  go version:       go1.19.5
  platform:         linux/amd64

prometheus, version 2.33.5+ds1 (branch: debian/sid, revision: 2.33.5+ds1-2~bpo11+1)
  build user:       team+pkg-go@tracker.debian.org
  build date:       20220820-12:29:59
  go version:       go1.18.5
  platform:         linux/amd64

**Object Storage Provider**:
minio version RELEASE.2022-10-20T00-55-09Z (commit-id=a8332efa948fd84507158c1d95df33116ee58a5a)
Runtime: go1.19.2 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2022 MinIO, Inc.

**What happened**:
Thanos Store component fails to load new blocks from Object Storage. When this happens, I'm seeing the logs below show and afterwards I do not see the `blocks.BaseFatcher` to attempt to get new data from the Object Store. Restarting the `thanos store` does make it load new data, but after some  time the same issue occurs.

**What you expected to happen**:
Continue to load newly uploaded blocks.

**How to reproduce it (as minimally and precisely as possible)**:
Not sure how to reproduce it. It happens occasionally. I have a `thanos sidecar` pushing metrics to the Object Store every 2h. Prometheus server keeps data for 6h (used config suggested in Thanos docs).

**Full logs to relevant components**:
```
Jul 24 17:34:18 objstore02 thanos[104028]: level=debug ts=2023-07-24T21:34:18.807986113Z caller=fetcher.go:327 component=block.BaseFetcher msg="fetching meta data" concurrency=32
Jul 24 17:34:18 objstore02 thanos[104028]: level=info ts=2023-07-24T21:34:18.956323892Z caller=fetcher.go:478 component=block.BaseFetcher msg="successfully synchronized block metadata" duration=148.427972ms
 duration_ms=148 cached=114 returned=54 partial=0
Jul 24 17:34:18 objstore02 thanos[104028]: level=debug ts=2023-07-24T21:34:18.956436425Z caller=bucket.go:630 msg="loading new block" id=01H64X3TN7BQF5TEV9325SWGTJ
Jul 24 17:34:18 objstore02 thanos[104028]: level=debug ts=2023-07-24T21:34:18.956478289Z caller=bucket.go:630 msg="loading new block" id=01H64X3HMDR0QKMEBBJ83ESGKJ
Jul 24 17:34:18 objstore02 thanos[104028]: level=debug ts=2023-07-24T21:34:18.956492994Z caller=binary_reader.go:467 msg="failed to read index-header from disk; recreating" path=/var/cache/thanos/staging-st
ore/01H64X3TN7BQF5TEV9325SWGTJ/index-header err="try lock file: open /var/cache/thanos/staging-store/01H64X3TN7BQF5TEV9325SWGTJ/index-header: no such file or directory"
Jul 24 17:34:18 objstore02 thanos[104028]: level=debug ts=2023-07-24T21:34:18.956524269Z caller=binary_reader.go:467 msg="failed to read index-header from disk; recreating" path=/var/cache/thanos/staging-st
ore/01H64X3HMDR0QKMEBBJ83ESGKJ/index-header err="try lock file: open /var/cache/thanos/staging-store/01H64X3HMDR0QKMEBBJ83ESGKJ/index-header: no such file or directory"
Jul 24 17:34:18 objstore02 thanos[104028]: level=debug ts=2023-07-24T21:34:18.988097133Z caller=binary_reader.go:474 msg="built index-header file" path=/var/cache/thanos/staging-store/01H64X3HMDR0QKMEBBJ83E
SGKJ/index-header elapsed=31.547014ms
Jul 24 17:34:18 objstore02 thanos[104028]: level=info ts=2023-07-24T21:34:18.989195409Z caller=bucket.go:639 msg="loaded new block" elapsed=32.717706ms id=01H64X3HMDR0QKMEBBJ83ESGKJ
Jul 24 17:34:18 objstore02 thanos[104028]: level=debug ts=2023-07-24T21:34:18.992042956Z caller=binary_reader.go:474 msg="built index-header file" path=/var/cache/thanos/staging-store/01H64X3TN7BQF5TEV9325S
WGTJ/index-header elapsed=35.51466ms
Jul 24 17:34:18 objstore02 thanos[104028]: level=info ts=2023-07-24T21:34:18.992969539Z caller=bucket.go:639 msg="loaded new block" elapsed=36.535169ms id=01H64X3TN7BQF5TEV9325SWGTJ
Jul 24 17:34:18 objstore02 thanos[104028]: level=info ts=2023-07-24T21:34:18.99315259Z caller=bucket.go:568 msg="dropped outdated block" block=01H64DFXMWBVDZN8W6SB9NTEP6
Jul 25 10:46:42 objstore02 thanos[104028]: level=debug ts=2023-07-25T14:46:42.967063088Z caller=bucket.go:1114 msg="No block found" mint=1690123440000 maxt=1690156500000 lset="{environment=\"staging\",replica=\"A\"}"
Jul 25 10:46:42 objstore02 thanos[104028]: level=debug ts=2023-07-25T14:46:42.967139881Z caller=bucket.go:1114 msg="No block found" mint=1690123440000 maxt=1690156500000 lset="{environment=\"staging\", replica=\"B\"}"
```

**Anything else we need to know**:
`thanos store` config:

```
/usr/bin/thanos store --data-dir /var/cache/thanos/staging-store \
--objstore.config-file /etc/thanos/store/staging-bucket.yml \
--grpc-address '0.0.0.0:10911' \
--grpc-grace-period 2m \
--http-address '0.0.0.0:10912' \
--http-grace-period 2m \
--index-cache.config-file /etc/thanos/store/staging-cache.yaml \
--log.format logfmt \
--log.level debug
```
Cache config file:
```
---
type: in-memory
config:
  # Overall maximum number of bytes cache can contain. The value should be specified with a bytes unit (ie. 250MB).
  max_size: 250MB
  # Maximum size of single item, in bytes. The value should be specified with a bytes unit (ie. 125MB).
  max_item_size: 125MB

```

**Comment by AlexandarY** [comment]
Just saw in CHANGELOG.md that in `thanos 0.30.2` this fix - https://github.com/thanos-io/thanos/pull/6086 - was pushed for "Failure to close BlockSeriesClient cause store-gateway deadlock". Can anyone advise if this is the issue I'm experiencing?

**Comment by yeya24** [comment]
> Can anyone advise if this is the issue I'm experiencing

It is hard to tell whether this is the issue from the information you provided. I think it should be safe to upgrade from 0.30.1 to 0.30.2 and see if it helps

**Comment by AlexandarY** [comment]
> > Can anyone advise if this is the issue I'm experiencing
> 
> It is hard to tell whether this is the issue from the information you provided. I think it should be safe to upgrade from 0.30.1 to 0.30.2 and see if it helps

Will do that and keep and see if the issue persists. If it does, what additional info can I provide to pinpoint the root cause?

**Comment by AlexandarY** [comment]
I deployed thanos version `0.31.0` and the issue has not re-occurred. It does seem it was related to https://github.com/thanos-io/thanos/pull/6086. Thanks for the assistance! will close this issue.
