### ISSUE TITLE
Missing Label for Prometheus metric in Thanos UI and Grafana

### ISSUE THREAD

**Issue by BrimstoneXmk** [thanos-io/thanos#6580]
**Thanos, Prometheus and Golang version used**:
Thanos: 0.29.0
Prometheus: 2.32.1
Golang: go1.19.9

**What happened**:
We are not able to see UniqueID created for each prometheus instance by our application in Thanos.
However we are able to the same in Thanos-Receiver-default Pod

**What you expected to happen**:
We expected that the same UniqueID should be present on Thanos & Grafana UI for the particular metric.

How to reproduce it (as minimally and precisely as possible): We are not sure what is causing it. We just upgraded the RHACM version from 2.5 to RHACM 2.7.

**Full logs to relevant components**:

Thanos-receiver-default logs:

> lset="labels:<name:\"__name__\" value:\"node_cpu_seconds_total\" > labels:<name:\"ORIGINNODE\" value:\"worker0.uboat.os.fyre.ibm.com\" > labels:<name:\"ResourceID\" value:\"5f55d75297249d729993699b1038e011\" > labels:<name:\"TYPE\" value:\"gauge\" > labels:<name:\"_collectorType\" value:\"prom:node\" > labels:<name:\"_endpoint\" value:\"master1.uboat.os.fyre.ibm.com\" > labels:<name:\"_job\" value:\"node-exporter\" > labels:<name:\"_keyIndexName\" value:\"cf9e6ad7fa79346168858c0e76ccb7ab\" > labels:<name:\"account_id\" value:\"e3c8-393a\" > labels:<name:\"cluster\" value:\"uboat-cluster\" > labels:<name:\"container\" value:\"kube-rbac-proxy\" > labels:<name:\"cpu\" value:\"0\" > labels:<name:\"displayName\" value:\"prom:node_master1.uboat.os.fyre.ibm.com\" > labels:<name:\"endpoint\" value:\"https\" > labels:<name:\"host\" value:\"worker0.uboat.os.fyre.ibm.com\" > labels:<name:\"mode\" value:\"idle\" > labels:<name:\"namespace\" value:\"openshift-monitoring\" > labels:<name:\"pod\" value:\"node-exporter-z6dc2\" > labels:<name:\"resourceId\" value:\"5f55d75297249d729993699b1038e011\" > labels:<name:\"resourceType\" value:\"prometheus\" > labels:<name:\"service\" value:\"node-exporter\" > "

Thanos UI:
![image](https://github.com/thanos-io/thanos/assets/91735513/0257bf09-5cc1-4501-8de4-ba79fa06329c)

Grafana UI:
![image](https://github.com/thanos-io/thanos/assets/91735513/47a4d212-a79a-4c5a-aa34-3928d619eeb9)

**Environment**:
- Others: Linux/amd64 [ running on OCP 4.10.59 with RHACM 2.7 ]

**Comment by douglascamata** [comment]
@BrimstoneXmk how is this UniqueID being created? Is it a label of every metric? Is it an external label of your Prometheus? Sounds like it's better to contact Red Hat's support to get some help, as you mention Red Hat's ACM.
