### ISSUE TITLE
Explain checkbox is unavailable for any actions 

### ISSUE THREAD

**Issue by Vanshikav123** [thanos-io/thanos#6632]
### Is your proposal related to a problem?

The issue is in the thanos-query component , the Explain checkbox is unavailable when we use Prometheus as an engine .

### Describe the solution you'd like

The Explain checkbox should be available whenever we execute a query.

### Describe alternatives you've considered

Or a pop-up alert should be provided explaining the reason or any message of its unavailability.

### Additional context

N/A

**Comment by saswatamcode** [comment]
Hello! The PromQL explain functionality is only available with the Thanos engine https://github.com/thanos-io/promql-engine, and not with the old Prometheus engine.

But I agree, there should be something in the UI to mention the reason. Maybe not an alert, but a pop-up text can be shown when the user hovers over the disabled Explain checkbox. 🙂

**Comment by lmarques03** [comment]
Hi @saswatamcode, I would like to take a look into this.

**Comment by saswatamcode** [comment]
Sure @lmarques03 go ahead
