### ISSUE TITLE
Thanos Store Consuming more than 1tb

### ISSUE THREAD

**Issue by antikilahdjs** [thanos-io/thanos#6652]
**Thanos, Prometheus and Golang version used**:

**Object Storage Provider**: MiniO S3

**What happened**:

After upgraded to thanos to main release 0.32.0 my store consuming more than 1tb

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

My environment is large but is not possible consuming a lot of memory

**Full logs to relevant components**:

No have error logs because is not a "error" and in my mind have some bugs to consume a large memory
![image](https://github.com/thanos-io/thanos/assets/33559260/c51dce69-d278-4af4-89e6-446607c7e71a)

**Anything else we need to know**:

I guess somebody have the same issue https://github.com/thanos-io/thanos/issues/6643

**Comment by antikilahdjs** [comment]
I dont know what but I cant put the logs above.


ts=2023-08-24T12:34:06.125011295Z caller=bucket.go:688 level=info msg="loaded new block" elapsed=114.940907ms   id=01H8BN5ASF5X8M9V54AAMK5851
      
       ts=2023-08-24T12:34:06.125147681Z caller=bucket.go:688 level=info msg="loaded new block" elapsed=91.902982ms id=01H84SE60EDGGPXH25J41V3RTA
      
       ts=2023-08-24T12:34:06.126249174Z caller=bucket.go:688 level=info msg="loaded new block" elapsed=97.24188ms id=01H8JQRCMSBK0M3T6DPG22YWSX
      
       ts=2023-08-24T12:34:06.126397252Z caller=bucket.go:688 level=info msg="loaded new block" elapsed=27.721076ms id=01H81BJA6D6YVA6HH8PVYXCTH5
      
       ts=2023-08-24T12:34:06.128009632Z caller=bucket.go:688 level=info msg="loaded new block" elapsed=143.749793ms id=01H84BPQMPX2CD7H22JFAK6B8H
      
       ts=2023-08-24T12:34:06.129147822Z caller=bucket.go:688 level=info msg="loaded new block" elapsed=126.69885ms id=01H8FGREG8V94A77Y36274D0B5
      
       ts=2023-08-24T12:34:06.133370134Z caller=bucket.go:688 level=info msg="loaded new block" elapsed=83.718996ms id=01H84BPNCWKAEQ7DSA9QXD04K4
      
       ts=2023-08-24T12:34:06.149133599Z caller=bucket.go:688 level=info msg="loaded new block" elapsed=39.26834ms id=01H82MRWVVVZD8F0X0RVKRXQ6M
      
       ts=2023-08-24T12:34:06.150246343Z caller=store.go:435 level=info msg="bucket store ready" init_duration=1.049408679s
      
       ts=2023-08-24T12:34:06.150371507Z caller=intrumentation.go:56 level=info msg="changing probe status" status=ready
      
       ts=2023-08-24T12:34:06.150445712Z caller=grpc.go:131 level=info service=gRPC/server component=store msg="listening for serving gRPC" address=0.0.0.0:10901
      
       ts=2023-08-24T12:34:06.629308226Z caller=fetcher.go:487 level=info component=block.BaseFetcher msg="successfully synchronized block metadata" duration=479.043429ms duration_ms=479 cached=184 returned=184 partial=0
      
       ts=2023-08-24T12:37:06.389143308Z caller=fetcher.go:487 level=info component=block.BaseFetcher msg="successfully synchronized block metadata" duration=238.100715ms duration_ms=238 cached=184 returned=184 partial=0

**Comment by GiedriusS** [comment]
Let's move to https://github.com/thanos-io/thanos/issues/6643
