### ISSUE TITLE
Store: failing sanity check for nil postings

### ISSUE THREAD

**Issue by MichaHoffmann** [thanos-io/thanos#6660]
**Thanos, Prometheus and Golang version used**:

Thanos 0.32

**What happened

Some queries fail with:

```
Aborted desc = fetch series for block 01H8JGWBCKTRHFWHXRFRXEGDQX: expanded matching posting: expand: postings is nil for {customerKey=dev}. It was never fetched.
```

Stores provide no relevant logs.

**Comment by saswatamcode** [comment]
@yeya24 any idea on what could be happening here, as it seems like this path was touched in https://github.com/thanos-io/thanos/pull/6532? Relevant slack thread: https://cloud-native.slack.com/archives/CK5RSSC10/p1692865102631199
