### ISSUE TITLE
Query Frontend: consumes more memory (OOM)

### ISSUE THREAD

**Issue by chalut01** [thanos-io/thanos#6665]
Thanos Version v0.32.0
Everything is set up the same way, only the version is different. 
Before this, I realized that Store are consumes a lot of memory too. #6643  
I've decided to rollback all components to version v0.31.0. I'm hoping that this pprof can be useful.

[thanos-query-frontend-cpu.pb.gz](https://github.com/thanos-io/thanos/files/12445759/thanos-query-frontend-cpu.pb.gz)
[thanos-query-frontend-heap.pb.gz](https://github.com/thanos-io/thanos/files/12445760/thanos-query-frontend-heap.pb.gz)

<img width="1061" alt="Screenshot 2566-08-26 at 22 00 08" src="https://github.com/thanos-io/thanos/assets/22786179/75c17ee1-c398-4538-b321-0492fcd10bbe">

**Comment by mhoffm-aiven** [comment]
Can you provide a pprof dump and enable active query tracking please?

**Comment by chalut01** [comment]
Fixed in v0.32.2 !!
Thank you everyone for your hard work.

**Comment by chalut01** [comment]
![Screenshot 2566-09-01 at 22 00 49](https://github.com/thanos-io/thanos/assets/22786179/2bcb6e6e-9ad5-405a-a131-4fc616c1b104)

Update.

**Comment by MichaHoffmann** [comment]
Can you enable active query tracking please? Are you using thanos query engine?

**Comment by chalut01** [comment]
`thanos query-frontend
	--http-address=0.0.0.0:9090
	--labels.default-time-range=15m
	--labels.max-query-parallelism=50
	--labels.max-retries-per-request=2
	--labels.response-cache-config-file=/thanos-conf/thanos-query-frontend-redis.yaml
	--labels.response-cache-max-freshness=3m
	--labels.split-interval=3h
	--query-frontend.compress-responses
	--query-frontend.downstream-url=http://thanos-query.thanos
	--query-frontend.forward-header=Authorization
	--query-frontend.log-queries-longer-than=15s
	--query-range.max-query-parallelism=50
	--query-range.max-retries-per-request=2
	--query-frontend.downstream-tripper-config-file=/thanos-conf/thanos-query-frontend-tripper.yaml
	--query-range.response-cache-config-file=/thanos-conf/thanos-query-frontend-redis.yaml
	--query-range.split-interval=3h
	--query-range.partial-response
	--query-range.request-downsampled
	--log.level=info`
My configuration.

**Comment by chalut01** [comment]
Fixed. 
Upgrade to 0.32.5
