### ISSUE TITLE
[Compactor] decode postings: invalid size

### ISSUE THREAD

**Issue by ylazaar** [thanos-io/thanos#6745]
The compactor in my setup never runs and the container keeps failing with the following error:

```
ts=2023-09-21T12:37:50.748211273Z caller=azure.go:256 level=debug msg="getting blob" blob=01GT5CVYZNYFZDK93EJB8F8EQY/no-compact-mark.json offset=0 length=0
ts=2023-09-21T12:37:50.750633975Z caller=compact.go:597 level=error msg="retriable error" err="filter metas: filter blocks marked for no compaction: context canceled"
ts=2023-09-21T12:37:50.750748875Z caller=main.go:161 level=error err="group 0@10861838680888856476: invalid result block /data/compact/0@10861838680888856476/01HAVVWBTKQGZBRGS2M4JGRGXK: get all postings: decode postings: invalid size\ncompaction\nmain.runCompact.func7\n\t/app/cmd/thanos/compact.go:427\nmain.runCompact.func8.1\n\t/app/cmd/thanos/compact.go:481\ngithub.com/thanos-io/thanos/pkg/runutil.Repeat\n\t/app/pkg/runutil/runutil.go:74\nmain.runCompact.func8\n\t/app/cmd/thanos/compact.go:480\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598\ncritical error detected\nmain.runCompact.func8.1\n\t/app/cmd/thanos/compact.go:495\ngithub.com/thanos-io/thanos/pkg/runutil.Repeat\n\t/app/pkg/runutil/runutil.go:74\nmain.runCompact.func8\n\t/app/cmd/thanos/compact.go:480\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598\ncompact command failed\nmain.main\n\t/app/cmd/thanos/main.go:161\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598"
```

Tested on 0.32, 0.32.2 and 0.32.3 versions.
Prometheus version is v2.22.1

**Comment by ylazaar** [comment]
Any updates on this?

**Comment by yeya24** [comment]
Is it happening only for v0.32.X Thanos compactor?
Looks like it is compacting raw blocks and I am not sure if we changed that this release

**Comment by ylazaar** [comment]
Actually we started with an older version and after a while we enabled some prometheus rules and noticed this alert.
![image](https://github.com/thanos-io/thanos/assets/97945546/5e49b765-191e-49b8-9233-dbe7d0b442d5)
So my guess it never worked.
I enabled --no-debug.halt-on-error to get an idea where it actually fails. And tried to update to 0.32.0, 0.32.1, 0.32.2 and 0.32.3 but no change.

**Comment by yeya24** [comment]
> get all postings: decode postings

From this looks like the block is corrupted. Not sure if this is something that can be repaired by the bucket repair tool

**Comment by ylazaar** [comment]
@yeya24 how can force the deletion of said corrupted block?

**Comment by yeya24** [comment]
@ylazaar We have a bucket tool to mark this block as deletion

**Comment by ylazaar** [comment]
@yeya24 I have already tried that.
the odd thing is i cannot find these blobs in azure's storage.

**Comment by sai-vishal-kumar** [comment]
> @yeya24 I have already tried that. the odd thing is i cannot find these blobs in azure's storage.

I have the same issue, how did you fix it?
