### ISSUE TITLE
compactor backlog documentation : metric thanos_compact_downsample_total does not exists

### ISSUE THREAD

**Issue by gulecroc** [thanos-io/thanos#6780]
In the compactor backlog documentation, the second point mention to use `thanos_compact_downsample_total ` metric :
https://thanos.io/tip/operating/compactor-backlog.md/#detect-the-backlog

I can't find it with thanos v0.32.4, is the metric still exits ?

**Comment by yeya24** [comment]
Yes, the metric should be still there.

**Comment by gulecroc** [comment]
Ok the metric is only initiated when a fist iteration is completed, I find it on an other environnement
