### ISSUE TITLE
Drop problematic out-of-order blocks from cloud storage

### ISSUE THREAD

**Issue by Lord-Y** [thanos-io/thanos#6796]
### Is your proposal related to a problem?

Thanos compactor is halted when blocks are out of order:
```
Oct 12 09:53:21 REDACTED thanos-compactor[169890]: ts=2023-10-12T09:53:21.897360582Z caller=http.go:110 level=info service=http/server component=compact msg="internal server is shutdown gracefully" err="error executing compaction: compaction: group 0@4118268881288195826: blocks with out-of-order chunks are dropped from compaction:  REDACTED/0@4118268881288195826/01HB5ZXZE6W03HC04ATV6SCY04: 110/276154 series have an average of 1.027 out-of-order chunks: 0.000 of these are exact duplicates (in terms of data and time range)"
```

### Describe the solution you'd like

Can we have an opt-in option to automatically drop the block `01HB5ZXZE6W03HC04ATV6SCY04` as example in order to make the `compactor` run properly in the next runs?
I didn't saw any time difference between our servers so I manually removed problematic blocks. We have like 12 platforms so 12 buckets so I needed to drop X blocks in each of buckets.
Everything is now working properly and dropping a few blocks is not a problem at all for us.

Thx.

**Comment by Lord-Y** [comment]
So I wrote a script to make the cleaning.

**Comment by mrliptontea** [comment]
I only found out about it myself recently when dealing with halted compaction:

There is a hidden flag [`--compact.skip-block-with-out-of-order-chunks`](https://github.com/thanos-io/thanos/blob/v0.32.4/cmd/thanos/compact.go#L770-L771). If I understand it correctly, if such block is detected, it will be marked for deletion. However, such blocks shouldn't happen in normal operation, so I'd enable it to fix the problem, and once the blocks have been deleted, remove the flag.

**Comment by Lord-Y** [comment]
@mrliptontea thanks for sharing. I'll check and give a try.

**Comment by Lord-Y** [comment]
Alright I'll close this issue as the option is [here](https://github.com/thanos-io/thanos/blob/f959198b5f10796b8b415b40f2e5c0d12c643256/cmd/thanos/compact.go#L772).
