### ISSUE TITLE
query: Different results between local Prometheus/Remote Thanos

### ISSUE THREAD

**Issue by Aransh** [thanos-io/thanos#6814]
**Thanos, Prometheus and Golang version used**:
Prometheus: v2.47.1
Thanos-sidecar: v0.32.4
Thanos querier: v0.32.4

**What happened**:
We are migrating our architecture from "prometheus+grafana per cluster" to "prometheus+thanos per cluster + single grafana".
We have existing custom dashboards, most work just fine with Thanos (after adding filtering by cluster), but some seem to return different results when run on local prometheus of a cluster, or on the remote Thanos querier.
Example:
count_over_time(sum(<custom_metric>{cluster=~"$cluster"} == 1)by (cluster)  [24h:])

Running on prometheus local returns 48
Running on Thanos querier returns 18
Important to mention:
- Both prometheus and Thanos are running on clusters in the same time zone
- Same query without "count_over_time" returns the exact same data

**What you expected to happen**:
I expect Thanos queries to have the same result as Prometheus (which in this case we also verified and Prometheus' result is correct, while Thanos' isn't) 

**How to reproduce it (as minimally and precisely as possible)**:
Since you have no access to our custom metric, just a random example I tried to verify this is a general issue with "count_over_time":
count_over_time(sum(workqueue_adds_total{cluster="$cluster"})[24h:])
Running on prometheus local returns 2880
Running on Thanos querier returns 1440

**Comment by GiedriusS** [comment]
Which engine are you using?

**Comment by Aransh** [comment]
@GiedriusS both engines give the same result

**Comment by MichaHoffmann** [comment]
Also subqueries are not yet enabled in Thanos engine and trigger fallback I think.

**Comment by MichaHoffmann** [comment]
Count over time is not well defined for subqueries though. Probably your default step is different. Can you try with [24h:1m] for a test to see if it's different default subquery step?

**Comment by Aransh** [comment]
@MichaHoffmann That helps!
using [24h:30s] gives us the desired result on both local Prometheus and Remote Thanos, thanks a lot!

**Comment by SharonCohenAkamai** [comment]
I do not like this function to , but we didn't have a choice
What do you suggest to use instead ?

**Comment by GiedriusS** [comment]
I'm closing this issue as it looks like the original problem has been solved.

**Comment by mhoffm-aiven** [comment]
You might get rid of the subquery with a recording rule maybe but that has similar issues with lookback i assume; what do you want to achieve with the query?

**Comment by SharonCohenAkamai** [comment]
we have an application that run every 30 min , we want to check in specific time range ( 1d , 1w ...)  how many batches was finish successfully.
