### ISSUE TITLE
staticPathContent Rewrite method no need to writefile with 0666

### ISSUE THREAD

**Issue by zhoukejie-web** [thanos-io/thanos#6840]
staticPathContent Rewrite method no need to writefile with 0666
```
// Rewrite rewrites the file backing this staticPathContent and swaps the local content cache. The file writing
// is needed to trigger the file system monitor.
func (t *staticPathContent) Rewrite(newContent []byte) error {
	t.content = newContent
	// Write the file to ensure possible file watcher reloaders get triggered.
	return os.WriteFile(t.path, newContent, 0666)
}
```
I think it not a good permission for thanos receive

**Comment by zhoukejie-web** [comment]
anohter，it might not be appropriate for apikey in website code directly
```
{{ $tip := "tip"}}
<script nonce="93HDK8392dfjh4Gb" type="text/javascript"
    src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script nonce="93HDK8392dfjh4Gb" type="text/javascript"> docsearch({
        apiKey: '649aaeb84811844d97cb5aa0398b94d9',
        indexName: 'thanos',
        inputSelector: '#searchInput',
        algoliaOptions: { 'facetFilters': ["version:{{ $tip }}"] },
        debug: false // Set debug to true if you want to inspect the dropdown.
    });
</script>
```

**Comment by douglascamata** [comment]
> I think it not a good permission for thanos receive

And why is that? What are the problems you see with this? That type and method are only used in tests.

> anohter，it might not be appropriate for apikey in website code directly

How do you propose we deliver an api key that has to be used for documentation search that works by issuing requests from the client side? That is literally exactly how Docsearch + Algolia should be used according to their docs: https://docsearch.algolia.com/docs/DocSearch-v3#implementation.

**Comment by douglascamata** [comment]
Closing this as these are not a problem and there's no action to take. I'm happy to re-open if we are convinced otherwise.
