### ISSUE TITLE
Thanos UI : graceful shut down the ui web server in response to an operating system interrupt signal 

### ISSUE THREAD

**Issue by Vanshikav123** [thanos-io/thanos#6858]
### Is your proposal related to a problem?

When an operating system interrupt signal, like Ctrl+C, is received, the current version of the Thanos UI is unable to gracefully terminate its web server. This may result in unexpected server shutdowns, inconsistent data, and user annoyance.

### Describe the solution you'd like

I suggest putting in place a solution that enables the web server to gracefully shut down in response to an OS interrupt signal in order to improve the Thanos UI. Thus, data integrity and improved user experience are ensured, and the server will finish processing ongoing requests and shut down gracefully.

### Additional context
As of right now, sudden terminations from the Thanos UI web server can interfere with user actions and perhaps lead to persistent data problems.
Users will be able to use the conventional interrupt signal (such as Ctrl+C) in their terminal to gracefully terminate the Thanos UI server by putting this method into practice.
By adding this capability, the Thanos UI will be more user-friendly and in line with web server management best practices.

**Comment by Vanshikav123** [comment]
I have started working on this issue as of now

**Comment by yeya24** [comment]
Umm, have you tested that Thanos UI doesn't have graceful shutdown? I suppose all Thanos components already have the feature built-in.
If it doesn't have it then it would be nice to support it
