### ISSUE TITLE
Deprecated Metric Usage

### ISSUE THREAD

**Issue by AuHoppe** [thanos-io/thanos#6883]
**Issue:**
The v2 release of `kube-state-metrics` removes several deprecated metrics, one with usage here.

**Additional Context:**
Referenced at: https://github.com/kubernetes/kube-state-metrics/blob/release-1.9/docs/README.md#metrics-deprecation

**Resolution:**
`pkg/querysharding/analyzer_test.go` should be updated with the new `kube_node_status_capacity_memory_bytes` usage:
`kube_node_status_capacity_memory_bytes` ~ `kube_node_status_capacity{resource="memory",unit="byte"}`

**Comment by yeya24** [comment]
Thanks for the report.
`pkg/querysharding/analyzer_test.go` is just a test file and we are only use the metric as an example to test the query. There is no impact to us if the metric is deprecated.
