### ISSUE TITLE
retention based on space for `receive`

### ISSUE THREAD

**Issue by calestyo** [thanos-io/thanos#6921]
### Is your proposal related to a problem?

Hey.

Currently, `receive` provides only `--tsdb.retention=` which allows to set the retention based on time.<br>
If storage is however a bit more tight than usual, one can either only set this to very low values or risk that the filesystem runs full.

### Describe the solution you'd like

It would be nice if one would have, just like Prometheus, another option that allows for a retention based on some maximum space to be used.<br>
And ideally, if both, space and time based retentions are given, then both should be enforced.

### Describe alternatives you've considered

Doing some guesswork on which retention time the available space currently corresponds to.<br>
But the problem is obviously that this may depend on how compressible the metrics are and will change again if new hosts and/or metrics are added.

Thanks,
Chris.

**Comment by yeya24** [comment]
I think this feature request makes sense. Max bytes for retention is already available as a TSDB option so should be straightforward to support this feature. Help wanted!

**Comment by husnialhamdani** [comment]
Hi @yeya24, 
Can I take this? and could you please also give some more details on what to do?

**Comment by yeya24** [comment]
Please go ahead. You can add a new flag for max retention bytes and pass the flag when creating the tsdb.

**Comment by kartikaysaxena** [comment]
Since there is no update, can I work on this?

**Comment by husnialhamdani** [comment]
I’m still working on this.

**Comment by yeya24** [comment]
Should be closed by #6944

**Comment by calestyo** [comment]
Thanks :)
