### ISSUE TITLE
"Enable finding overlapping blocks" in the Store web UI causes an error

### ISSUE THREAD

**Issue by calestyo** [thanos-io/thanos#6924]
**Thanos, Prometheus and Golang version used**:
```
thanos, version 0.32.5 (branch: HEAD, revision: 750e8a94eed5226cd4562117295d540a968c163c)
  build user:       root@053ebc7b5322
  build date:       20231019-04:13:41
  go version:       go1.21.3
  platform:         linux/amd64
  tags:             netgo
```

**Object Storage Provider**:
Filesystem

**What happened**:
When I go to the web UI of the `store` component and the page with the "Loaded Blocks" I see my loaded blocks, but once I select the "Enable finding overlapping blocks" checkbox, I'm redirected to an error page:
> Aaaah! Something went wrong.
> Please file an issue in the Thanos issue tracker.
> View error details.

With the error details being:
```
TypeError: o[0][0] is undefined
    in t
    in be
    in xe
    in it
    in mt
    in div
    in F
    in n
    in PD
```

**Full logs to relevant components**:
Even with `--log.level=debug` there’s nothing appearing in the logs while the error occurs.

Any ideas?

Thanks,
Chris.

**Comment by yeya24** [comment]
Duplicated with https://github.com/thanos-io/thanos/issues/5359. Closing this one.

**Comment by calestyo** [comment]
Ah. I had seen that issue, but since I haven't even set up `compactor` yet, I thought it would be something else. Sorry.

**Comment by yeya24** [comment]
@calestyo No need to sorry. Compact & Store Gateway & Bucket UI share the same UI code for finding overlapping blocks. I have updated the title of the original issue to include other components
