### ISSUE TITLE
Query Frontend: queries with negative offset should check whether it is cacheable or not

### ISSUE THREAD

**Issue by yeya24** [thanos-io/thanos#6928]
Query with negative offset enabled queries latest or even data in the future. This affects the results cache in query frontend and it should respect the max cache freshness config.

Crossposting from https://github.com/cortexproject/cortex/issues/5678 as I believe Thanos has the same issue.

**Comment by Vanshikav123** [comment]
Hello @yeya24 i want to work on this !
