### ISSUE TITLE
Missing metrics when querying with recording rule

### ISSUE THREAD

**Issue by KihyeokK** [thanos-io/thanos#6963]
**Thanos, Prometheus and Golang version used**:
docker.io/bitnami/thanos:0.31.0-scratch-r12

**Object Storage Provider**:
GCS

**What happened**:
We recently started seeing missing metrics when a recording rule is used to query. When the original query expression associated with the recording rule is used, there are no missing metrics at all:

(Top graph is using recording rule, bottom graph is using normal query expression)
![recording_rule_vs_expr](https://github.com/thanos-io/thanos/assets/96888460/936cb8d7-8992-472a-88d5-7eeb4546ae7c)

We originally didn't have Thanos Ruler enabled, but we were somehow still able to query using recording rules configured for Prometheus. So we thought it might be because Thanos Ruler is not configured, so we then enabled Ruler to see if it solves the problem. However, the problem stayed the same when Ruler was configured, it was surely the Thanos Ruler that evaluated the recording rule, but there were still missing metrics. In the following picture we used a new recording rule configured for Thanos Ruler, that maps to the same expression as the original problematic recording rule:

![Thanos_ruler_enabled](https://github.com/thanos-io/thanos/assets/96888460/2e7fd8ec-7ef8-42ad-9220-6ebc9f3bb007)

Some interesting observations:
1. After a few days, we requeried the same time range as the first picture, using the same recording rule. Interestingly, there were no longer missing queries for that time range. However, this is not always the case, as in many cases we can still see missing metrics for other old time ranges.
2. Missing time range seem to correspond to the data blocks of different compaction levels (like 2h, 8h):
![2hr_block_missing](https://github.com/thanos-io/thanos/assets/96888460/585578dd-3e60-49d7-876a-59a22cb18d48)

 
**What you expected to happen**:
Metrics returned from query using recording rule has no missing data blocks.

**How to reproduce it (as minimally and precisely as possible)**:
Have Thanos Ruler enabled with a recording rule, writing to a remote storage, and have Thanos Query, Store, Compactor configured.

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by MichaHoffmann** [comment]
Can you upgrade to 0.32.5 and retry; 0.31 has some deduplication issues.

**Comment by KihyeokK** [comment]
Thank you for the fast response, will try the upgrade to 0.32.5.

**Comment by KihyeokK** [comment]
Upgrading to 0.32.5 seems to solve the issue, thank you for the help!

**Comment by KihyeokK** [comment]
> MichaHoffmann

Upgrading to 0.32.5 seems to solve the issue, thank you for the help!

**Comment by KihyeokK** [comment]
@MichaHoffmann Yes the issue can be closed :)
