### ISSUE TITLE
compact: "fatal error: concurrent map iteration and map write" on v0.32.5

### ISSUE THREAD

**Issue by s0rl0v** [thanos-io/thanos#6965]
**Thanos, Prometheus and Golang version used**:
official docker image v0.32.5

```
/ $ thanos --version
thanos, version 0.32.5 (branch: HEAD, revision: 750e8a94eed5226cd4562117295d540a968c163c)
  build user:       root@053ebc7b5322
  build date:       20231019-04:13:41
  go version:       go1.21.3
  platform:         linux/amd64
  tags:             netgo
```

**Object Storage Provider**: 
Azure Blob

**What happened**:
compactor crashed with `fatal error: concurrent map iteration and map write`

**What you expected to happen**:
compactor did not crash

**How to reproduce it (as minimally and precisely as possible)**: 
Happens every 2-3 days on our environments, very consistently.
One thing to say - we have quite a compaction backlog (80k blocks compaction backlog, 100k deletion and around 600 downsample backlog.

Steps:
1. Have compact with the following arguments:
```
      compact
      --log.level=info
      --log.format=logfmt
      --http-address=0.0.0.0:10902
      --data-dir=/data
      --retention.resolution-raw=7d
      --retention.resolution-5m=60d
      --retention.resolution-1h=180d
      --consistency-delay=30m
      --objstore.config-file=/conf/objstore.yml
      --downsample.concurrency=6
      --compact.concurrency=6
      --wait
```
2. Run it on against Azure objstore;
3. Observe a crash after few days.

**Full logs to relevant components**:
https://pastebin.com/frupguzC

**Anything else we need to know**:

**Comment by GiedriusS** [comment]
I think this was probably fixed by https://github.com/thanos-io/thanos/pull/6801. Care to try the newest RC or main?

**Comment by s0rl0v** [comment]
@GiedriusS Thank you Giedrius, there are no crashes so far on 0.33
