### ISSUE TITLE
Limit the resources used by the asynchronous cache filling process

### ISSUE THREAD

**Issue by damnever** [thanos-io/thanos#6975]
### Is your proposal related to a problem?

The async cache filling process may use a significant amount of CPU and network resources on both sides of the thanos-store and the cache service. This could potentially have a negative impact on regular query requests. Furthermore, frequently adjusting the configuration requires the thanos-store to be restarted.

### Describe the solution you'd like

One idea is to implement the circuit breaker pattern to dynamically limit the asynchronous cache filling requests when latency or timeouts increase significantly.

### Describe alternatives you've considered

Perhaps consider adding some additional options to reduce concurrency when there are ongoing user queries.

### Additional context

(Write your answer here.)

**Comment by yeya24** [comment]
This makes total sense. We found similar issues as well when backfilling a large amount of data to cache, especially postings.
Circuit breaker is a good idea.

**Comment by yeya24** [comment]
Is this issue ok to be closed?
