### ISSUE TITLE
Improve goDocs expierience; add reference.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#698]
Thanos Go packages is more & more often used as libraries, so it would be nice to generate nice godocs.

It looks not bad here: https://godoc.org/github.com/improbable-eng/thanos but most likely some additional examples and documentation would be nice to have. (: 

Also useful to explain more Bucket interface needed for our obj store providers.

**Comment by jojohappy** [comment]
I would like to do that. It can improve my English skills.

**Comment by jojohappy** [comment]
You are welcome! So could I continue to do the remaining works after my holidays?

**Comment by bwplotka** [comment]
Yes (: Enjoy your holidays for now (:

**Comment by jojohappy** [comment]
Sorry for the delay. But I think it is worth improving the docs and the AC.

**Comment by kakkoyun** [comment]
I'm happy to help if any help needed on this.

**Comment by daixiang0** [comment]
@jojohappy any update for this?

**Comment by daixiang0** [comment]
update
