### ISSUE TITLE
Deprecate query pushdown in favor of the distributed engine

### ISSUE THREAD

**Issue by MichaHoffmann** [thanos-io/thanos#6985]
### Is your proposal related to a problem?

Query pushdown into sidecars adds considerable complexity on the query path, yet the distributed promql-engine already can push down aggregations pretty well. Having only one component responsible of query pushdown and distribution will result in a simpler, more robust and well structured query path i think.

### Describe the solution you'd like

We should advertise to use the distributed mode of the thanos engine in our documentation and provide case studies of its usage while removing the query pushdown optimization from the sidecar. This should allow pretty efficient query path cleanup and reduce our bug surface.

**Comment by yeya24** [comment]
Is query pushdown still considered an experimental feature? If that's the case then deprecating it sounds ok to me.

> yet the distributed promql-engine already can push down aggregations pretty well

Is distributed promql-engine considered production ready at this point? I don't know if we need to wait for features like max samples limit, query stats, etc

**Comment by MichaHoffmann** [comment]
Its lacking those features you mentioned i think; but also we cannot configure them in querier yet ( same for non distributed thanos engine )
