### ISSUE TITLE
Rule: upgrade to v0.33.0: error in thanos url template

### ISSUE THREAD

**Issue by ahurtaud** [thanos-io/thanos#7002]
**Thanos, Prometheus and Golang version used**:
thanos v0.33.0

**What happened**:
Upgrading from v0.32 to v0.33.0, the thanos url advertised by our ruler cannot be opened back in thanos query anymore.
I think this is due to https://github.com/thanos-io/thanos/pull/6308

**What you expected to happen**:
Thanos urls to be clickable as before

**How to reproduce it (as minimally and precisely as possible)**:
We have not changed anything so it is using the default:
`--alert.query-template="/graph?g0.expr={{.Expr}}&g0.tab=1"`

**Anything else we need to know**:
I think this is due to some html encoding of spaces:
we are seeing urls like: 
`https://<redacted>/graph?g0.expr=%28max&#43;by&#43;%28namespace%2C&#43;pod%2C&#43;instance%2C&#43;container%29&#43;%28increase%28kube_pod_container_status_restarts_total%7Bnamespace%21~%22openshift-gitops%7Copenshift-marketplace%7Copenshift-pipelines%22%2Cprometheus%3D%22platform%22%7D%5B1h%5D%29%29&#43;%3E%3D&#43;4%29&g0.tab=1`

url decode:
![Screenshot 2023-12-21 at 15 49 08](https://github.com/thanos-io/thanos/assets/25080995/d3a4c754-df2a-4820-9138-503c1011c254)

When clicking on it, thanos query, opens it with:
![Screenshot 2023-12-21 at 15 51 05](https://github.com/thanos-io/thanos/assets/25080995/39080936-d8cc-41e5-93e4-2d2965d7a10f)

`https://<redacted>/graph?g0.expr=%20(max&g0.tab=1&g0.stacked=0&g0.range_input=1h&g0.max_source_resolution=0s&g0.deduplicate=1&g0.partial_response=0&g0.store_matches=%5B%5D&g0.engine=thanos&g0.analyze=0`

**Comment by ahurtaud** [comment]
I think of an issue between difference of url encode and html encode :/
spaces becoming: `&#43;` instead of `%20` for example

**Comment by kartikaysaxena** [comment]
From what I get, we are using `url.QueryEscape(expr)` in `tableLinkForExpression` which may be the cause of it as it escapes certain special characters including `+` (for space) although we have to convert it into `%20`
