### ISSUE TITLE
Querier: How to log instant queries 

### ISSUE THREAD

**Issue by PrayagS** [thanos-io/thanos#7005]
A lot of our queriers were being OOM killed out of a sudden.

We checked incoming requests from Grafana as well as the `http_requests_total` metric. Didn't see any unusually heavy queries from Grafana.

However, I saw an increased rate of requests on `/query` endpoint for the whole duration of this incident.

I want to track and log all the instant queries which come on `/query`. How do I do that?

Load balancer logs show me incoming requests from Grafana (all hitting `/query_range`).

I tried setting the log level to debug but all I saw were range queries.

Also tried setting `--query.active-query-path` but then the contents of that file only showed raw queries. No way to differentiate b/w range and instant queries.

**Comment by hanjm** [comment]
1. request logging https://thanos.io/tip/components/query.md
```
      --request.logging-config=<content>
                                 Alternative to 'request.logging-config-file'
                                 flag (mutually exclusive). Content
                                 of YAML file with request logging
                                 configuration. See format details:
                                 https://thanos.io/tip/thanos/logging.md/#configuration
      --request.logging-config-file=<file-path>
                                 Path to YAML file with request logging
                                 configuration. See format details:
                                 https://thanos.io/tip/thanos/logging.md/#configuration
```
2. tracing , query span just  like log.
https://thanos.io/tip/thanos/tracing.md
```
serviceName='thanos-query' and spanName in ('promql_instant_query','promql_range_query') 
```
span has a attribute name `query`.

**Comment by PrayagS** [comment]
Thanks a lot for bringing that up.

I glanced through it in the flags list but didn't see the complete configuration; I had a feeling that I would be flooded with logs if I enabled this.
