### ISSUE TITLE
Expose query.max-samples flag for Thanos Querier.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#703]
Thanks of upgrade of promQL package, we got new Prometheus change:
> [FEATURE] Make maximum number of samples per query configurable via `--query.max-samples` flag. #4513

Which gives ability to limit number of samples. This with max-concurrent queries, allows to calculate maximum amount of samples Querier can hold and set it accordingly.

Open question: Does max-samples helps with blocking OOMs of StoreAPI? At first glance, yes as we do max sample verify while we are iterating over messages from stream, so we will not fetch more much more samples than  `query.max-samples` define. (However store API implementation can buffer more e.g sidecar with non-streamed remote-read). 
 
*Acceptance Criteria:*
* expose query.max-samples for Thanos Querier
* Define default value. Should be unlimited (IMO. no)

CC @domgreen

**Comment by GiedriusS** [comment]
@bwplotka does this even make sense? Could you PTAL at this comment here: https://github.com/thanos-io/thanos/pull/1369#issuecomment-518697874?

**Comment by ppanyukov** [comment]
> Open question: Does max-samples helps with blocking OOMs of StoreAPI?

Short answer: no. Or more precisely, "it depends".

From my own tests:

- this is a difficult limit to use meaningfully;
- the actual memory allocated by PromQL very largely depends on the query and the cardinality;
- so querier can still OOM.

**Comment by fpetkovski** [comment]
@GiedriusS do you think it makes sense to allow configure this (or a similar limit) in the [lazySeriesSet](https://github.com/thanos-io/thanos/blob/de0e3848ff6085acf89a5f77e053c555a2cce550/pkg/query/iter.go#L306)?

**Comment by GiedriusS** [comment]
I think it's a bit too late there. I think the limit should apply before Recv() https://github.com/thanos-io/thanos/blob/main/pkg/store/proxy.go#L506
