### ISSUE TITLE
Thanos query param `dedup` does not take effect after add externalLabels for prometheus and thanos-ruler?

### ISSUE THREAD

**Issue by magiceses** [thanos-io/thanos#7033]
**Thanos, Prometheus and Golang version used**: thanos v0.31.0

**What happened**:
After add external label to thanos ruler, when i query metric through thanos-query
<img width="1769" alt="image" src="https://github.com/thanos-io/thanos/assets/50326171/0fdef218-7ab4-46f5-a2da-16c201b17c16">
<img width="1773" alt="image" src="https://github.com/thanos-io/thanos/assets/50326171/047075e8-09e3-432b-8fb9-2f57b11c8833">

the param is not taking effect? and the metrics on the second and third lines are exactly the same, just like:
<img width="1572" alt="image" src="https://github.com/thanos-io/thanos/assets/50326171/5dd8c880-0388-4775-b645-dd6dcbdb85b4">
<img width="1771" alt="image" src="https://github.com/thanos-io/thanos/assets/50326171/6db68639-8f45-4769-9166-d816c61fabb6">

and when i change the label to `{host_ip="10.20.0.7"}`, the metric become to one metric? why?
![image](https://github.com/thanos-io/thanos/assets/50326171/782daf4a-0daf-40af-b074-42c09d7b2842)

**How to reproduce it (as minimally and precisely as possible)**:
add the same external label to prometheus and thanos ruler

Anybody can help? This is a bug for thanos or i ignore some settings after add external labels?

**Comment by MichaHoffmann** [comment]
0.31 has had known dedup issues, can you try upgrading?

**Comment by MichaHoffmann** [comment]
There were a couple, the root cause was in the end that the store apis could under some circumstances involving external labels return unsorted responses but dedup replies on them being sorted

**Comment by magiceses** [comment]
which mean the `store apis`? I do not use thanos store gateway, i just use the sidecar/query/ruler

**Comment by MichaHoffmann** [comment]
Ah, I mean the gRPC store api; all of them implement it on one way or another!

**Comment by magiceses** [comment]
Got it , thanks very much.
By the way, does the 0.31.0 version bug you mentioned above refer to this link(https://github.com/thanos-io/thanos/issues/6257#issuecomment-1653169915) can explain the problem?

**Comment by MichaHoffmann** [comment]
> Got it , thanks very much. By the way, does the 0.31.0 version bug you mentioned above refer to this link([#6257 (comment)](https://github.com/thanos-io/thanos/issues/6257#issuecomment-1653169915)) can explain the problem?

Yes precisely that!

**Comment by magiceses** [comment]
execuse me, when i upgrade thanos-ruler from 0.31.0 to 0.32.0/0.33.0, the thanos ruler raise error: 
<img width="1780" alt="image" src="https://github.com/thanos-io/thanos/assets/50326171/c4fe5d53-019f-4635-9876-0a55354d2063">

Thanos-ruler cannot be upgraded directly from 0.31.0 to higher version? what else do i need to do? @MichaHoffmann

**Comment by MichaHoffmann** [comment]
I think that is a case of `https://github.com/thanos-io/thanos/pull/6107` and might need some solution like https://github.com/utilitywarehouse/thanos-manifests/pull/77/files maybe!

**Comment by magiceses** [comment]
it works! Thank you very much!!

**Comment by MichaHoffmann** [comment]
You're welcome!
