### ISSUE TITLE
alert.query-template added too much escaping to the expression

### ISSUE THREAD

**Issue by m-messiah** [thanos-io/thanos#7074]
**Thanos, Prometheus and Golang version used**: thanos v0.33.0, prometheus v2.45.2

**What happened**: After the upgrade from v0.30.0 and prometheus v2.44.0 the new alerts got too escaped strings.

For example: `Source: https://thanos.cluster.local/graph?g0.expr=count%28sum&#43;by&#43;%28node%29&#43;%28rate%28up%7Bjob%3D%22test%22%7D%5B5m%5D%29%29&#43;%3E&#43;0%29&#43;%3E&#43;20&g0.tab=1`

While it actually must be `https://thanos.cluster.local/graph?g0.expr=count(sum%20by%20(node)%20(rate(up%7Bjob%3D%22test%22%7D%5B5m%5D))%20%3E%200)%20%3E%2020&g0.tab=1&g0.stacked=0&g0.range_input=1h&g0.max_source_resolution=0s&g0.deduplicate=1&g0.partial_response=0&g0.store_matches=%5B%5D&g0.engine=prometheus&g0.analyze=0`

The problem is that the new escaped URL is impossible to use from non-html CLIs anymore, while previously it worked well.

**What you expected to happen**: URLs to be good

**How to reproduce it (as minimally and precisely as possible)**: Send alert for the query that contains spaces (to be encoded as `+` or other special characters

**Anything else we need to know**: It is unclear if it is related to thanos or prometheus, but alerts are definitely come from thanos-ruler. None of the params were changed from defaults.

**Comment by MichaHoffmann** [comment]
That should be fixed on latest main i think.

**Comment by m-messiah** [comment]
Yes, thank you. I tried and did not find it =)

Duplicate of https://github.com/thanos-io/thanos/issues/7002
