### ISSUE TITLE
[receiver] high resource utilization during the time of uploading TSDB blocks

### ISSUE THREAD

**Issue by hayk96** [thanos-io/thanos#7075]
### Issue summary
After upgrading the Thanos stack from version `0.26.0` to `0.32.3`, I've begun encountering issues such as high memory usage and frequent restarts of the `thanos-receive-router` (also known as `thanos-receive-distributor`) pods during TSDB block uploads. Additionally, there have been high latencies for incoming requests and numerous error logs like the following

```yaml
{"caller":"handler.go:373","component":"receive-handler","err":"context deadline exceeded","level":"error","msg":"internal server error","tenant":"default-tenant","ts":"2024-01-16T20:02:06.323528706Z"}
```

![Screenshot 2024-01-17 at 10 29 04](https://github.com/thanos-io/thanos/assets/46712946/fa496401-75df-49fd-843b-e7ffa1b73ec5)
![Screenshot 2024-01-17 at 10 38 45](https://github.com/thanos-io/thanos/assets/46712946/66cb9036-c97a-4efb-b29d-1a615e5f6193)

---
### Actions done
- Modifying certain flags to optimize performance proved unhelpful; even upgrading from version `0.32.3` to the latest version `0.33.0` had no effect.  
- Interestingly, reverting to version `0.26.0` significantly improved the performance of the receive-router component, making it approximately 10 times more efficient compared to version `0.33.0`. The noticeable difference in performance is evident in the images below.

---
### Stack details
- **Environment and deployment model:** Kubernetes via Bitnami Helm chart
- **Kubernetes version:** GKE 1.27
- **Object storage type**: GCP-GCS
- **Receive and Receive Ingester replicas:** 10 replicas every
- **Incoming requests per second:** ~800 r/s
- **Incoming samples per second:** ~800k

---
### pprof result
Here is the result of the CPU profiles for both versions
- [receive-router-heap-0.26.0 vs receive-router-heap-0.33.0](https://flamegraph.com/share/81191f09-b56b-11ee-a059-7a6c3496f108/81366870-b56b-11ee-a059-7a6c3496f108)
- [receive-router-profile-0.26.0 vs receive-router-profile-0.33.0](https://flamegraph.com/share/fcc90196-b56b-11ee-89c7-6ee284b23f20/fccfb819-b56b-11ee-89c7-6ee284b23f20)  

pprof binaries: [thanos-receive-router-pprof.zip](https://github.com/thanos-io/thanos/files/13967960/thanos-receive-router-pprof.zip)

**Comment by hayk96** [comment]
Confirming that the use of the `--receive.grpc-compression=none` field in version `0.33.0` was effective, and now the resource utilization is similar to that in version `0.26.0`. Thanks @MichaHoffmann!

**Comment by hayk96** [comment]
BTW should I add that flag in the `receive-ingesters` as well, does it make sense?

**Comment by douglascamata** [comment]
@hayk96 I don't think you need it there. The routers will take care of firing all the requests to achieve replication. The ingesters have nothing more to do than read the incoming non-compressed request and write the data.

**Comment by hayk96** [comment]
Maybe we can add this in the [Troubleshooting; Common cases](https://thanos.io/tip/operating/troubleshooting.md/#receiver)? What do you think?

**Comment by MichaHoffmann** [comment]
> Maybe we add this in the [Troubleshooting; Common cases](https://thanos.io/tip/operating/troubleshooting.md/#receiver)? What do you think?

I'm indifferent i think; Its a bit of a tradeoff between network bandwidth and CPU; and usually CPU is cheaper so i think defaulting to snappy here is the correct behavior. But then again you faced the regression during update and would have profited from an FAQ article about it. I dont know whats the best course of action tbh!

**Comment by douglascamata** [comment]
I have mixed opinions regarding this. CPU is usually cheaper than network bandwidth. Ingest latency is super important too. If to save network bandwidth we need to pay in latency, this is a very sensible decision. Latency with the compression in @hayk96's environment was awful compared to no-compression. And check that memory usage chart...
