### ISSUE TITLE
Query frontend,store: redis config sends "default" instead of username

### ISSUE THREAD

**Issue by AyalaEl** [thanos-io/thanos#7103]
thanos version: 0.34.0, 0.33.0, 0.32.5
Redis version: 6.0.16

**What happened**:
Thanos is sending "default" instead of configured username to redis cache

**What you expected to happen**:
Thanos sends the username I configured in the config yaml.

**How to reproduce it**:
Configure a redis 6 cluster with username and password.
Configure the thanos frontend with cache config file: 
Type: "REDIS"
config:
  username: "username"
  password: "password"
  addr: "address:port"

**Thanos 0.34.0 logs**: 
caller=main.go:135 level:error err="creating redis client: WRONGPASS invalid username-password pair"

The reddis logs show login attempts with username "default" and password "password"
I'm using images from dockerhub (thanosio/thanos)

**Comment by sergo3030** [comment]
I have the same issue! Did you find the fix?

**Comment by AyalaEl** [comment]
I didn't :(

I did find this code: 
https://github.com/thanos-io/thanos/blob/main/internal/cortex/chunk/cache/redis_client.go
I'm not sure if thats the correct file but It looks like they aren't even using the username.. (line 52)

**Comment by segevtsilis** [comment]
I also have this issue
