### ISSUE TITLE
Store Gateway query minio for index file with illegal characters (backslash)

### ISSUE THREAD

**Issue by henrikschristensen** [thanos-io/thanos#7110]
**Thanos, Prometheus and Golang version used**: 
thanos version 0.33.0, prometheus version 2.48.1

**Object Storage Provider**: 
s3 (minio)

**What happened**: 
When store gateway qyeries minio for chunk index file the file path includes backslash witch is illegal character. Log lines:
ts=2024-02-01T09:41:12.4362379Z caller=bucket.go:745 level=warn msg="loading block failed" elapsed=1.9361ms id=01HNHQFG94B87WRW5RBT3916VF err="create index header reader: write index header: new index reader: get object attributes of 01HNHQFG94B87WRW5RBT3916VF\\index: Object name contains unsupported characters."

**What you expected to happen**:
No errors

**How to reproduce it (as minimally and precisely as possible)**:
running both thanos and minio on windows servers

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by GiedriusS** [comment]
Thanks for the report! It seems like the fix should be as simple as avoiding `filepath.Join` and using `/`.

**Comment by henrikschristensen** [comment]
Maybe just using path.Join? It should be seperating with a forwardslash on all operating systems.

**Comment by douglascamata** [comment]
What's the Minio version here? Since when is this a problem?

**Comment by henrikschristensen** [comment]
this is a completely new setup, so I am on the latest release of minio.
