### ISSUE TITLE
Compactor:ThanosCompactHasNotRun

### ISSUE THREAD

**Issue by DanielCastronovo** [thanos-io/thanos#7111]
**Thanos, Prometheus and Golang version used**:

0.34

**Object Storage Provider**:
S3

**What happened**:
Alert has been generated by Prometheus : ThanosCompactHasNotRun

**Logs**
`caller=block.go:185 level=warn msg="requested to mark for deletion, but file already exists; this should not happen; investigate" err="file XXXXXXXXXXX/deletion-mark.json already exists in bucket"`

**What you expected to happen**:

Nothing, by the past all is worked as expected.
We use EBS service on AWS.

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Comment by mfoldenyi** [comment]
Same issue? https://github.com/thanos-io/thanos/issues/6707
