### ISSUE TITLE
Compactor & Store pod has Permission denied for block

### ISSUE THREAD

**Issue by swamipeddineni** [thanos-io/thanos#7113]
After updating thanos from v0.30.2 to v0.33.0, I am facing below for compactor and store pods

For Store Pods
ts=2024-02-01T13:56:58.877009934Z caller=bucket.go:742 level=warn msg="failed to remove block we cannot load" err="unlinkat /data/01HNAVR1BF982DF8SEGT02RB33/index-header: permission denied"
ts=2024-02-01T13:56:58.877057835Z caller=bucket.go:745 level=warn msg="loading block failed" elapsed=12.751151ms id=01HNAVR1BF982DF8SEGT02RB33 err="create index header reader: write index header: new index reader: get TOC from object storage of 01HNAVR1BF982DF8SEGT02RB33/index: open temp file: open /data/01HNAVR1BF982DF8SEGT02RB33/b9ca90e4-6e3e-4a31-bc5e-16833f3144cb.part-0: permission denied"
ts=2024-02-01T13:56:58.879092091Z caller=bucket.go:742 level=warn msg="failed to remove block we cannot load" err="unlinkat /data/01HNHYTR10SCTYS2KDQBZHH5XM/index-header: permission denied"
ts=2024-02-01T13:56:58.879129492Z caller=bucket.go:745 level=warn msg="loading block failed" elapsed=14.615302ms id=01HNHYTR10SCTYS2KDQBZHH5XM err="create index header reader: write index header: new index reader: get TOC from object storage of 01HNHYTR10SCTYS2KDQBZHH5XM/index: open temp file: open /data/01HNHYTR10SCTYS2KDQBZHH5XM/f8b096dc-4b6a-4124-9775-120c315e6d6a.part-0: permission denied"

For Compactor Pods
ts=2024-02-01T14:29:39.774372006Z caller=compact.go:1466 level=info msg="start of GC"
ts=2024-02-01T14:29:39.776717329Z caller=compact.go:1486 level=warn msg="failed deleting non-compaction group directories/files, some disk space usage might have leaked. Continuing" err="delete file/dir: read dir: open /data/compact/0@15098824445636559513: permission denied" dir=/data/compact
ts=2024-02-01T14:29:39.77676093Z caller=compact.go:1489 level=info msg="start of compactions"
ts=2024-02-01T14:29:39.777212434Z caller=compact.go:1109 level=info group="0@{region=\"EastUS\", tier=\"stg\"}" groupKey=0@15098824445636559513 msg="compaction available and planned" plan="[01HNG0HFB60N575CXSX85G2ZEK (min time: 1706702400004, max time: 1706709600000) 01HNG0HFTSWD1QT1JPH1C07EDE (min time: 1706702400004, max time: 1706709600000)]"
ts=2024-02-01T14:29:39.777238034Z caller=compact.go:1118 level=info group="0@{region=\"EastUS\", tier=\"stg\"}" groupKey=0@15098824445636559513 msg="finished running pre compaction callback; downloading blocks" plan="[01HNG0HFB60N575CXSX85G2ZEK (min time: 1706702400004, max time: 1706709600000) 01HNG0HFTSWD1QT1JPH1C07EDE (min time: 1706702400004, max time: 1706709600000)]" duration=4.1µs duration_ms=0
ts=2024-02-01T14:29:39.777400836Z caller=compact.go:502 level=error msg="retriable error" err="compaction: group 0@15098824445636559513: download block 01HNG0HFB60N575CXSX85G2ZEK: create dir: mkdir /data/compact/0@15098824445636559513/01HNG0HFB60N575CXSX85G2ZEK: permission denied"
ts=2024-02-01T14:30:23.363501959Z caller=fetcher.go:529 level=info component=block.BaseFetcher msg="successfully synchronized block metadata" duration=43.588950552s duration_ms=43588 cached=560 returned=450 partial=0
ts=2024-02-01T14:30:23.363725662Z caller=clean.go:34 level=info msg="started cleaning of aborted partial uploads"
ts=2024-02-01T14:30:23.363751762Z caller=clean.go:61 level=info msg="cleaning of aborted partial uploads done"
ts=2024-02-01T14:30:23.363764162Z caller=blocks_cleaner.go:44 level=info msg="started cleaning of blocks marked for deletion"
ts=2024-02-01T14:30:23.363845663Z caller=blocks_cleaner.go:58 level=info msg="cleaning of blocks marked for deletion done"
ts=2024-02-01T14:31:20.279298591Z caller=fetcher.go:529 level=info component=block.BaseFetcher msg="successfully synchronized block metadata" duration=41.121057077s duration_ms=41121 cached=560 returned=560 partial=0

Please help me solve this issue

**Comment by GiedriusS** [comment]
Hi, please see: https://github.com/thanos-io/thanos/pull/6107. You'll have to make adjustments in Kubernetes
