### ISSUE TITLE
frontend, store: query cancel floods logs with error messages related to redis cache context cancel

### ISSUE THREAD

**Issue by tekicode** [thanos-io/thanos#7140]
When queries are cancelled on the frontend, a flood of "context canceled" messages will arrive in the output logs of any thanos components that use redis cache

What is the appetite for reducing the log level of this message from ERR to DEBUG?

https://github.com/thanos-io/thanos/blob/4a82ba7f6998743f62e1926d5de8a70ac7e69366/internal/cortex/chunk/cache/redis_cache.go#L73

**Comment by yeya24** [comment]
THanks @NishantBansal2003, resolving now
