### ISSUE TITLE
compact: if compaction didn't run for a while, it seems to need more and more local disk space

### ISSUE THREAD

**Issue by calestyo** [thanos-io/thanos#7198]
**Thanos, Prometheus and Golang version used**:
```
# thanos --version
thanos, version 0.34.1 (branch: HEAD, revision: 4cf1559998bf6d8db3f9ca0fde2a00d217d4e23e)
  build user:       root@61db75277a55
  build date:       20240219-17:13:48
  go version:       go1.21.7
  platform:         linux/amd64
  tags:             netgo
```

**Object Storage Provider**:
filesystem

**What happened**:
As a consequence of #7197, my `compact` didn't run for like half a month and therefore a considerably amount of resolution 0 level 1 buckets piled up.

Once I restarted it, and despite some 60GB of local disk space being available, it soon entered it's silent failed-but-idle state again, once more because of not enough disk space.

I've had the same already a few month earlier, where I've then already had to increase the disk space to allow `compact` to run through, and this time I had to increase it even more.

It seems to me, that this situation comes from a rather unfortunate ordering of how the compaction goes on. It seem it first wants to do **all** level 2 buckets, then **all** level 3, then the ones with lowered resolution and so on.<br>
This means of course, that it will need not only more space on the remote storage, but I even got the feeling that e.g. for creating **all** the level 3 with resolution 300000 it first downloads **all** the level 3 with resolution 0, is that right?
<br>Especially the latter would of course mean, that the longer `compact` had’t run, the more local space it needs.

**What you expected to happen**:
Doing everything a bit more space-conscious, for example:
- For the local storage, download only those buckets of the previous level/resolution that are needed to generate **one** bucket of the next level/resolution. Once that is created, upload it, remove the local buckets and go on (at the same level) with the next time period.
- For the remote storage, don't even upload any intermediate levels/resolution, if these are anyway going to be replaced by higher levels. After my `compact` hadn't run or a while, it generated large amounts of level 2 and 3 buckets, which were soon after replaced by the same data at level 4 (and store will then use only these). So there's a lot of level 2/3 duplicates which are not only needlessly uploaded, but are then also retained for - per default 48h - without reason.<br>
   Even if it would be to complicated to prevent the needless upload in the first place, it would at least be nice, if such buckets would be somehow marked as "don't use", so that `store` isn't even toughing them and `compact` could deleted them **immediately** once they're no longer needed for compaction.

Cheers,
Chris.

**Comment by GiedriusS** [comment]
Have you seen https://github.com/thanos-io/thanos/issues/3405? I think it talks about the same problems.

**Comment by calestyo** [comment]
@GiedriusS Indeed it seems to be the same (or at least cover the same area)... and I hadn't spotted it when skimming through the existing reports.

Can you mark this a duplicate of the other?
