### ISSUE TITLE
Compact RAM calculation

### ISSUE THREAD

**Issue by arnitolog** [thanos-io/thanos#722]
I have one of the blocks which is ~7GB of size. And Compact can't do anything with it. It is OOM killed every time. Is there any way to instruct Compact to process big blocks piecemeal
Here is part of meta.json file:
	"version": 1,
	"ulid": "01CRYM9RYN78DFKZ73XB4H4WCP",
	"minTime": 1537401600000,
	"maxTime": 1538611200000,
	"stats": {
		"numSamples": 4489155614,
		"numSeries": 2088751,
		"numChunks": 39194144
	},
here is graphs for compact pod:
![image](https://user-images.githubusercontent.com/34036079/50997191-97bcfc00-152c-11e9-826e-47ba28ea0d9a.png)
here is an error:
level=info ts=2019-01-10T20:46:34.747142839Z caller=compact.go:822 msg="start of GC"
level=info ts=2019-01-10T20:46:34.78464068Z caller=compact.go:207 msg="compaction iterations done"
level=info ts=2019-01-10T20:46:34.784681757Z caller=compact.go:214 msg="start first pass of downsampling"
level=info ts=2019-01-10T20:48:27.547013191Z caller=downsample.go:212 msg="downloaded block" id=01CRYM9RYN78DFKZ73XB4H4WCP duration=1m52.526675454s
fatal error: runtime: out of memory

**Comment by GiedriusS** [comment]
Compactor now supports sharding so you could use that as a temporary workaround but we could definitely provide some guidance on how much RAM is needed since it seems like this is a recurring topic: https://github.com/thanos-io/thanos/issues/1928
