### ISSUE TITLE
Tracing: Add missing sampler types

### ISSUE THREAD

**Issue by matej-g** [thanos-io/thanos#7230]
### Is your proposal related to a problem?

We are still missing some additions to our tracing setup and we should support more samplers out of the box. The initial work has been done here https://github.com/thanos-io/thanos/pull/6306, but we're still missing some adjustments.

### Describe the solution you'd like

See the suggestions here: https://github.com/thanos-io/thanos/pull/6306#pullrequestreview-1412768449

### Describe alternatives you've considered
N/A

### Additional context
There was a draft PR that began work (https://github.com/thanos-io/thanos/pull/6359) on this but so far it hasn't moved

**Comment by NeerajNagure** [comment]
Hi,I would like to work on this.Can you please assign it to me?
