### ISSUE TITLE
Receive: high in flight requests and high context deadline exceeded and ingestion latency in main branch

### ISSUE THREAD

**Issue by jnyi** [thanos-io/thanos#7248]
**Thanos, Prometheus and Golang version used**:
Thanos: 0.35.0-dev
Golang: go1.21.7

<img width="862" alt="Screenshot 2024-03-31 at 10 04 21 PM" src="https://github.com/thanos-io/thanos/assets/96499497/c8c1ee0a-455e-4c48-b9e3-6fc61171cc3b">

**Object Storage Provider**: s3

**What happened**: 
switch from v0.34.1 -> v0.35.0-dev experience high in flight requests, found this https://github.com/thanos-io/thanos/pull/7045, did a few things:
1. increased `receive.forward.async-workers` to a large number, the issue remains
2. reverted above pr and test, issue still persists

**What you expected to happen**:
With async writes, the write latency should improve.

**How to reproduce it (as minimally and precisely as possible)**:

Our receive commands (we split receive into router and ingestor modes), below is the args for router:
```
      receive
      --debug.name=pantheon-writer
      --log.format=logfmt
      --log.level=debug
      --http-address=0.0.0.0:10902
      --http-grace-period=5m
      --grpc-address=0.0.0.0:10901
      --grpc-grace-period=5m
      --hash-func=SHA256
      --label __replica__="$(NAME)"
      --receive.grpc-compression=none
      --receive.default-tenant-id=unknown
      --receive.tenant-label-name=__tenant__
      --remote-write.address=0.0.0.0:19291
      --receive-forward-max-backoff=5s
      --receive-forward-timeout=5s
      --receive.hashrings-algorithm=ketama
      --receive.hashrings-file=/var/thanos/config/hashring.json
      --receive.hashrings-file-refresh-interval=3m
      --receive.replication-factor=3
```

**Full logs to relevant components**:

full goroutine:
[full_goroutine.txt](https://github.com/thanos-io/thanos/files/14819571/full_goroutine.txt)

**Anything else we need to know**:

**Comment by GiedriusS** [comment]
Not sure I get the report. Are you saying that even after reverting the latency didn't go back? :thinking:

**Comment by jnyi** [comment]
Actually I suspect it is special to our setup because we use multi az hashring, will debug more with tracing:

```
[
    {
        "endpoints": [
            {
                "address": "thanos-receive-rep0-0.thanos-receive-svc:10901",
                "az": "isolation-rep-0"
            },
            {
                "address": "thanos-receive-rep0-1.thanos-receive-svc:10901",
                "az": "isolation-rep-0"
            },
            {
                "address": "thanos-receive-rep1-0.thanos-receive-svc:10901",
                "az": "isolation-rep-1"
            },
            {
                "address": "thanos-receive-rep1-1.thanos-receive-svc:10901",
                "az": "isolation-rep-1"
            },
            {
                "address": "thanos-receive-rep2-0.thanos-receive-svc:10901",
                "az": "isolation-rep-2"
            },
            {
                "address": "thanos-receive-rep2-1.thanos-receive-svc:10901",
                "az": "isolation-rep-2"
            }
        ],
        "hashring": "thanos-receive"
    }
]
```

**Comment by jnyi** [comment]
We see large forward delays but grpc latency is low:

<img width="408" alt="Screenshot 2024-04-08 at 2 47 40 PM" src="https://github.com/thanos-io/thanos/assets/96499497/ea2b1976-d4b4-4f13-8214-bfed4986a9a2">

<img width="490" alt="Screenshot 2024-04-08 at 2 49 08 PM" src="https://github.com/thanos-io/thanos/assets/96499497/051b69a6-43e9-4ab4-a31b-a8a2a2198bc1">

**Comment by yeya24** [comment]
Is it because there is not enough workers due to https://github.com/thanos-io/thanos/pull/7045 and requests keep queueing?

**Comment by jnyi** [comment]
I've used 10 x cpu cores as the # of workers, maybe that's not enought? Also got some tracing results:

Before in v0.34:
<img width="1432" alt="Screenshot 2024-04-08 at 4 27 37 PM" src="https://github.com/thanos-io/thanos/assets/96499497/1ec86b59-37a0-4891-b100-8085ff55a358">

After in v0.35
<img width="1550" alt="Screenshot 2024-04-08 at 4 27 28 PM" src="https://github.com/thanos-io/thanos/assets/96499497/07e036bf-bcb5-4a75-bb04-6fa486504e60">
:

**Comment by jnyi** [comment]
increased the worker count to 3000, the request started to be sequential:

<img width="471" alt="Screenshot 2024-04-08 at 4 57 43 PM" src="https://github.com/thanos-io/thanos/assets/96499497/3f3db151-e55d-49b0-a8a8-d49e7cc176d5">

<img width="1566" alt="Screenshot 2024-04-08 at 4 57 22 PM" src="https://github.com/thanos-io/thanos/assets/96499497/69141f1a-7e0e-4dd8-83d6-d8cee2127de0">

**Comment by jnyi** [comment]
I think I found the bug, this operation isn't parallel:

```
	// Do the writes to remote nodes. Run them all in parallel.
	for writeDestination := range remoteWrites {
		h.sendRemoteWrite(ctx, params.tenant, writeDestination, remoteWrites[writeDestination], params.alreadyReplicated, responses, wg)
	}

func (p *peerWorker) RemoteWriteAsync(ctx context.Context, req *storepb.WriteRequest, er endpointReplica, seriesIDs []int, responseWriter chan writeResponse, cb func(error)) {
	p.initWorkers()

	w := peerWorkItem{
		cc:          p.cc,
		req:         req,
		workResult:  make(chan peerWorkResponse, 1),
		workItemCtx: ctx,
		er:          er,

		sendTime: time.Now(),
	}

	p.work <- w
	res := <-w.workResult

	responseWriter <- newWriteResponse(seriesIDs, res.err, er)
	cb(res.err)
}
```

**Comment by jnyi** [comment]
Hi @yeya24 and @GiedriusS , I've submitted a fix, appreciate your feedback: https://github.com/thanos-io/thanos/pull/7267

**Comment by douglascamata** [comment]
@jnyi there's one more conflict to solve in the PR, FYI. You were also pinged there.
