### ISSUE TITLE
Compact halts when prometheus got restarted

### ISSUE THREAD

**Issue by hsmade** [thanos-io/thanos#726]
**Thanos, Prometheus and Golang version used**
I'm using thanos v0.2.1 and prometheus 2.5.0, both from the docker images.

**What happened**
Prometheus gets restarted (docker killed the process after it went OOM). Prometheus then starts in a fresh container, with no previous data, causing overlap on the blocks that are written to swift.
The compact job now halts with:
 
    {"caller":"compact.go:254","err":"compaction failed: compaction: pre compaction overlap check: overlaps found while gathering blocks. [mint: 1547222400000, maxt: 1547224200000, range: 30m0s, blocks: 6]: \u003culid: 01D0YWTXQ5SW0MFHHD2SZENTN7, mint: 1547222400000, maxt: 1547224200000, range: 30m0s\u003e, \u003culid: 01D0YWW209THR9RY83HX02TG7J, mint: 1547222400000, maxt: 1547224200000, range: 30m0s\u003e, \u003culid: 01D0YWYJ1KPNRZNH11W10SZ0PG, mint: 1547222400000, maxt: 1547224200000, range: 30m0s\u003e, \u003culid: 01D0YWVG5MZH384HAXYSEWZ6PT, mint: 1547222400000, maxt: 1547224200000, range: 30m0s\u003e, \u003culid: 01D0YWXDFT7KHM8NB60J3MPFHT, mint: 1547222400000, maxt: 1547224200000, range: 30m0s\u003e, \u003culid: 01D0YWWNV0PYPPAAJ1MC7YN9D7, mint: 1547222400000, maxt: 1547224200000, range: 30m0s\u003e","level":"error","msg":"critical error detected; halting","ts":"2019-01-11T17:17:47.488410127Z"}

**What you expected to happen**
I would expect compact to complain (+ set metrics), but not to halt.

**Anything else we need to know**

**Comment by bwplotka** [comment]
You can disable halting and it will crashloop but compactor cannot resolve from this.

I can see range is 30m - probably you changed `min-block-size`? If yes, that is wrong and we can't support that. TSDB is designed to work with 2h min block size only.

Anyway I don't think that is the reaons. I think the reason is that you run the Prometheus with non persistent storage.. That might be the case? I think you should run with persistent disk. It's stateful container. That will fix the issue IMO (: 

However to fix this generally, I can see issue that hardware for peristent block dies (but probably it's extremely rare) and restart will do overlap.. Not sure if worth to fix such rare case.

**Comment by pennpeng** [comment]
same problem：
```
level=debug ts=2019-01-31T04:24:54.295337406Z caller=compact.go:174 msg="download meta" block=01D2GPPWQYGP51D4SH3W2A7QHV
level=debug ts=2019-01-31T04:24:54.298905944Z caller=compact.go:174 msg="download meta" block=01D2GPPY3XPPMCAY41H813TRD6
level=debug ts=2019-01-31T04:24:54.303065541Z caller=compact.go:174 msg="download meta" block=01D2GXJKWF14CN5N0Z043TNF1M
level=debug ts=2019-01-31T04:24:54.306842174Z caller=compact.go:174 msg="download meta" block=01D2GXJM0YG9W8T1C8W417KS45
level=info ts=2019-01-31T04:24:54.316329052Z caller=compact.go:822 msg="start of GC"
level=error ts=2019-01-31T04:24:54.316906386Z caller=compact.go:254 msg="critical error detected; halting" err="compaction failed: compaction: pre compaction overlap check: overlaps found while gathering blocks. [mint: 1548838800000, maxt: 1548839100000, range: 5m0s, blocks: 2]: <ulid: 01D2FARVE7G290H5NZ7Y0KRB7M, mint: 1548835200000, maxt: 1548842400000, range: 2h0m0s>, <ulid: 01D2F06TWQE1X7V4K9AM9ZEV1D, mint: 1548838800000, maxt: 1548839100000, range: 5m0s>\n[mint: 1548837900000, maxt: 1548838200000, range: 5m0s, blocks: 2]: <ulid: 01D2FARVE7G290H5NZ7Y0KRB7M, mint: 1548835200000, maxt: 1548842400000, range: 2h0m0s>, <ulid: 01D2EZCW2V89BEEMWY8EVZJPZ8, mint: 1548837900000, maxt: 1548838200000, range: 5m0s>\n[mint: 1548838200000, maxt: 1548838500000, range: 5m0s, blocks: 2]: <ulid: 01D2FARVE7G290H5NZ7Y0KRB7M, mint: 1548835200000, maxt: 1548842400000, range: 2h0m0s>, <ulid: 01D2EZMGYRANBK1WTMWGJ73R90, mint: 1548838200000, maxt: 1548838500000, range: 5m0s>\n[mint: 1548838500000, maxt: 1548838800000, range: 5m0s, blocks: 2]: <ulid: 01D2FARVE7G290H5NZ7Y0KRB7M, mint: 1548835200000, maxt: 1548842400000, range: 2h0m0s>, <ulid: 01D2EZXNXMV6PY10FKJ5Z8ED4S, mint: 1548838500000, maxt: 1548838800000, range: 5m0s>"

```

**Comment by jleloup** [comment]
I also have this issue.

I'm running two Prometheus replicas from a statefulset (deployed from Prometheus Operator Helm chart) with Thanos sidecar v0.5.0 and from time to time I end up with some overlapping blocks & Thanos Compactor in CrashLoopBackoff. So I have persistent storage through PVC.

I'm restarting regularly those pods as I'm in the middle of implementing new scrape configs with trial & error.

**Comment by bwplotka** [comment]
Looks like it's the issue with lack of persistent storage on Prometheus. This is not recommended for Prometheus itself, not mentioning Thanos.

If we *really* want to support this: Vertical compaction / offline deduplication will help once done. However, the use case of lack of persistent storage might be more suitable to solve with Thanos receive and push method and even remote write does not guarantee no data loss. Happy to discuss but closing for now as `won't fix`
