### ISSUE TITLE
Caching Bucket File Unknown Flag

### ISSUE THREAD

**Issue by deprecastor** [thanos-io/thanos#7502]
Hello there,
I just installed Thanos via helm chart from bitnami. In that values file a link to documentation of the Thanos webpage:
https://thanos.io/v0.35/components/store.md/#caching-bucket
or 
https://thanos.io/tip/components/store.md/

But Thanos 35.1 is used by the bitnamit chart.

If I add the arg: "--store.caching-bucket.config-file=/conf/bucket/bucket-cache.yml"

**Object Storage Provider**:
StackIT
**What happened**:
Thanos does not recognize the argument "--store.caching-bucket.config-file"
**What you expected to happen**:
Consume my caching-bucket.conf file.
**How to reproduce it (as minimally and precisely as possible)**:
helm install with the bitnami chart. But I guess you can just run Thanos anywhere and trying to put the option.
**Full logs to relevant components**:

<details>Logs
<p>

```
$:kubectl logs -n thanos thanos-storegateway-0-0
thanos: error: unknown long flag '--store.caching-bucket.config-file'
```

</p>
</details>

I came here first, bc I am pretty sure it has nothing to do with the wrapper around it, Helm, it looks for me like something odd in the documentation. But I am not sure. Sorry if I am totally wrong.

**Environment**:
- Kubernetes / Helm Chart

**Comment by yeya24** [comment]
Are you using the correct version of Thanos? This flag exists for me.
I would double check the chart and the version you are using.

**Comment by deprecastor** [comment]
The error was on my side, had to configure the Helm Chart right, now everything works.
