### ISSUE TITLE
Thanos doesn't show metrics older than ~38 hours after upgrade from 0.15 to 0.35.1 

### ISSUE THREAD

**Issue by kounne** [thanos-io/thanos#7555]
**Thanos, Prometheus and Golang version used**:
thanos, version 0.35.1 (branch: HEAD, revision: 086a698b2195adb6f3463ebbd032e780f39d2050)
  build user:       root@be0f036fd8fa
  build date:       20240528-13:54:20
  go version:       go1.21.10
  platform:         linux/amd64
  tags:             netgo

**Object Storage Provider**:
S3

**What happened**:
After upgrade to 0.35.1 we are losing all metrics after ~38 hours due to 'The specified key does not exist' error. Even though blocks are visible via inspect tool and some can be seen when zoomed in.
<img width="1512" alt="Screenshot 2024-07-17 at 13 04 57" src="https://github.com/user-attachments/assets/fa1f0518-1d27-411a-9147-29d9256cf7df">
<img width="1511" alt="Screenshot 2024-07-17 at 13 28 48" src="https://github.com/user-attachments/assets/d82d6c73-776b-4de7-be40-cbbf74442d5b">
All logs before upgrade are visible only when zoomed in.
<img width="1080" alt="Screenshot 2024-07-17 at 13 31 14" src="https://github.com/user-attachments/assets/0fb8f067-30c3-4725-8eb7-791101e7b496">
<img width="1074" alt="Screenshot 2024-07-17 at 13 30 16" src="https://github.com/user-attachments/assets/28c03dac-817e-4339-9490-8f9aa8a1d791">

Didn't find any error logs on any hosts except the error from above.

**How to reproduce it (as minimally and precisely as possible)**:
Not really sure if it can be reproduced but here are the configs:
Store:
    --http-address          0.0.0.0:9091 \
    --data-dir              /opt/thanos/data \
    --index-cache-size      250MB \
    --chunk-pool-size       2GB \
    --objstore.config-file  /etc/thanos/bucket.yaml \
Sidecard:
    --tsdb.path=\"/prometheus/data\" \
    --prometheus.url=\"http://localhost:9090/prometheus\" \
    --http-address=\"0.0.0.0:19191\" \
    --grpc-address=\"0.0.0.0:19090\" \
    --objstore.config-file=\"/etc/thanos/thanos-sidecar/bucket.yml\" \
Receive:
    --tsdb.path=/prometheus/thanos-receiver \
    --tsdb.retention=36h \
    --receive.hashrings-file=/etc/thanos/thanos-receive/hashrings.json \
    --objstore.config-file=/etc/thanos/thanos-receive/bucket.yml \
    --receive.local-endpoint=198.19.4.201:10901 \
    --label=thanos=\\\"main\\\" \
Rule:
        --data-dir              /opt/thanos/data \
        --eval-interval         30s \
        --rule-file             /etc/thanos/thanos-rule/rules/*.yml \
        --alert.query-url       http://front.vaas.megalabs.ru/thanos \
        --alert.label-drop      replica \
        --alertmanagers.url     http://198.19.4.201:9093 \
        --alertmanagers.url     http://198.19.4.202:9093 \
        --query                 198.19.4.129:19192/thanos \
        --objstore.config-file  /etc/thanos/thanos-rule/bucket.yml \
        --web.external-prefix   thanos-rule \
        --label=thanos=\\\"rule\\\" \
Query:
        --http-address          0.0.0.0:19192 \
        --grpc-address          0.0.0.0:10902 \
        --store                 198.19.4.201:19090 \
        --store                 198.19.4.202:19090 \
        --store                 198.19.4.201:10901 \
        --store                 198.19.4.202:10901 \
        --store                 198.19.4.203:10901 \
        --store                 198.19.4.204:10901 \
        --query.replica-label=\"replica\" \
        --web.external-prefix=thanos  \
        --query.auto-downsampling \
Compactor:
    --data-dir              /opt/thanos/data \
    --delete-delay          48h \
    --wait \
    --compact.concurrency=16 \
    --objstore.config-file /etc/thanos/thanos-compact/bucket.yml \
    --selector.relabel-config-file /etc/thanos/thanos-compact/relabelling.yaml \
    --http-address=0.0.0.0:10902 \
    --web.external-prefix thanos-compact \
Bucket:
type: S3
config:
  bucket: "thanos"
  endpoint: "198.19.28.27:7480"
  region: "us-east-1"
  access_key: "myaccesskey"
  insecure: true
  signature_version2: false
  encrypt_sse: false
  secret_key: "mysecretkey"
  put_user_metadata: {}
  http_config:
    idle_conn_timeout: 0s
    response_header_timeout: 0s
    insecure_skip_verify: false
  trace:
    enable: false

**Full logs to relevant components**:
There are no error logs. At least I didn't find any. The only one I can see is in WebUI.
receive series from Addr: 198.19.4.204:10901 LabelSets: {monitor="dm-prometheus", replica="1"},{monitor="dm-prometheus", replica="2"},{tenant_id="default-tenant", thanos="main"},{thanos="rule"} MinTime: 1689674685500 MaxTime: 1721160000000: rpc error: code = Unknown desc = receive series from (random block ID): load chunks: get range reader: The specified key does not exist.

**Anything else we need to know**:
The only reason to this behaviour I can think of is some kind of error in config on my side on compactor, because before upgrade we've tried to enable it but it didn't work and the stopped service. But after upgrade it successfully started without being notices by us.
Stopping compactor service doesn't affect block deletion process.
I've tried repair tool but it didn't really work. The only messages I found were "found overlapped blocks, but all of the blocks are unique. Seems like unrelated issue. Ignoring overlap" (around 40000 blocks back from 2021)
It may be some kind of error with S3 bucket itself but I can't troubleshoot it by myself.
P.S. I really don't want to rollback to 0.15

**Environment**:
- OS (e.g. from /etc/os-release):
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.5 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"
- Kernel (e.g. `uname -a`):
Linux hostname 3.10.0-862.el7.x86_64 #1 SMP Wed Mar 21 18:14:51 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Evgenx8** [comment]
Same problem...

**Comment by kounne** [comment]
More info if needed:
Compactor was enabled on rules(6th block), now it's running on the 1st block(main).
<img width="1510" alt="Screenshot 2024-07-17 at 14 05 47" src="https://github.com/user-attachments/assets/ae2574cf-b43c-4ca7-8ecf-aa1ff6bd3193">

**Comment by kounne** [comment]
I'm not really sure what was the exact fix, but I switched from compacting rules to the main block, removed retention time from compactor config, added query.auto-downsampling for query and manually deleted all corrupted blocks from S3.
Now it's looking like this and I'm fine with that. 
<img width="717" alt="Screenshot 2024-07-19 at 13 59 22" src="https://github.com/user-attachments/assets/7f38e81f-7327-4b19-9c66-09e89fb3c5ff">
