### ISSUE TITLE
make test fails with GO 1.23

### ISSUE THREAD

**Issue by amaury-d** [thanos-io/thanos#7696]
**Thanos, Prometheus and Golang version used**:
```
thanos, version 0.37.0-dev (branch: main, revision: dfeaf6e258bca159c39fa6f7dadba51c27ff06b0)
  build date:       20240903-12:16:12
  go version:       go1.23.0
  platform:         darwin/arm64
```

**Object Storage Provider**:

**What happened**:
```
❯ make test
(re)installing /Users/adecreme/git/thanos/.bin/alertmanager-v0.24.0
# github.com/prometheus/alertmanager/cmd/alertmanager
link: golang.org/x/net/internal/socket: invalid reference to syscall.recvmsg
make: *** [.bingo/Variables.mk:24: /Users/adecreme/git/thanos/.bin/alertmanager-v0.24.0] Error 1
```

**What you expected to happen**:
`make test` success

**How to reproduce it (as minimally and precisely as possible)**:
- Upgrade to go 1.23
- `make build test`

**Full logs to relevant components**:

<details>Logs
<p>

```
Makefile:358: update target 'check-git' due to: target is .PHONY
test -x /opt/homebrew/bin//git || (echo >&2 "No git executable binary found at /opt/homebrew/bin//git."; exit 1)
.bingo/Variables.mk:22: update target '/Users/adecreme/git/thanos/.bin/alertmanager-v0.24.0' due to: target does not exist
# Install binary/ries using Go 1.14+ build command. This is using bwplotka/bingo-controlled, separate go module with pinned dependencies.
echo "(re)installing /Users/adecreme/git/thanos/.bin/alertmanager-v0.24.0"
(re)installing /Users/adecreme/git/thanos/.bin/alertmanager-v0.24.0
cd .bingo/ && GOWORK=off /opt/homebrew/bin//go build -mod=mod -modfile=alertmanager.mod -o=/Users/adecreme/git/thanos/.bin/alertmanager-v0.24.0 "github.com/prometheus/alertmanager/cmd/alertmanager"
# github.com/prometheus/alertmanager/cmd/alertmanager
link: golang.org/x/net/internal/socket: invalid reference to syscall.recvmsg
make: *** [.bingo/Variables.mk:24: /Users/adecreme/git/thanos/.bin/alertmanager-v0.24.0] Error 1
```

</p>
</details>

**Anything else we need to know**:

- Caused by linker update in golang 1.23: https://go.dev/doc/go1.23#linker
- I was able to launch the tests by bumping to:
    - alertmanager 0.25.1
    - minio v0.0.0-20240903063353-69258d5945c2
    - prometheus v0.37.9
but they ended in errors

**Comment by mehran-prs** [comment]
If the @dosu comment didn't resolve your issue, update the `net` library: `go get -u golang.org/x/net`.

**Comment by lachruzam** [comment]
another workaround to start tests: add `-ldflags="-checklinkname=0"` to alertmanager, minio and prometheus builds in .bingo/Variables.mk

**Comment by fpetkovski** [comment]
This should be fixed on main after bumping go and deps here https://github.com/thanos-io/thanos/pull/7796

**Comment by lachruzam** [comment]
@fpetkovski In my case, I tried to build a version that already had #7796 merged.
The build failed for alertmanager, minio and prometheus. If I'm not missing something then deps weren't bump here.

**Comment by fpetkovski** [comment]
Maybe this should help https://github.com/thanos-io/thanos/pull/7833.

**Comment by GiedriusS** [comment]
We use Go 1.23.3 now so closing this
