### ISSUE TITLE
Thanos Receiver: Error logs "try lock file: open <>.tmp-for-creation/index_tmp_po: no such file or directory" 

### ISSUE THREAD

**Issue by SM-9870** [thanos-io/thanos#7746]
**Thanos, Prometheus and Golang version used**: 
Thanos 0.35.1

**Object Storage Provider**: 
IBM S3

**What happened**:
I am facing errors in the Thanos receiver when I am using S3 Storage for mounting PV/PVC for Thanos Receiver TSDB directory. But I do not see this error If I use the local node storage. In my setup I am using same S3 Storage across all the Pods like Compactor, Receiver, Storagegateway etc. but each service has their own Folder inside the S3 mounted storage. 

In addition to this error, Thanos is not able to upload the metrics to the S3 storage for long term support.

```
ts=2024-09-12T01:43:13.164952074Z caller=db.go:1014 level=error component=receive component=multi-tsdb tenant=default-tenant msg="compaction failed" err="try lock file: open /data/receiver-0/default-tenant/01J7HYBVS79NPA7JJ6292NXCEJ.tmp-for-creation/index_tmp_po: no such file or directory"
ts=2024-09-12T01:44:23.166065172Z caller=db.go:1014 level=error component=receive component=multi-tsdb tenant=default-tenant msg="compaction failed" err="try lock file: open /data/receiver-0/default-tenant/01J7HYE0KDYBKFX92ZACZ2FZ01.tmp-for-creation/index_tmp_po: no such file or directory"
```

Similar error also logged in the Storage gateway:
```
  ts=2024-09-12T01:37:49.186686337Z caller=binary_reader.go:569 level=debug msg="failed to read index-header from disk; recreating" path=/data/storegw/01J7HXTB9PM6MJPYHCJ4AC3DY1/index-header err="try lock file: open /data/storegw/01J7HXTB9PM6MJPYHCJ4AC3DY1/index-header: no such file or directory"
```

**What you expected to happen**:
No errors in receiver and metrics are uploaded to S3

**How to reproduce it (as minimally and precisely as possible)**:
Attach/Mount S3 storage to IKS POD for Thanos Receiver's TSDB 

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by SM-9870** [comment]
It seems like `--sync.delay=10m` is not valid for Thanos Receiver. Its valid for Compactor.

**Comment by GiedriusS** [comment]
Does your filesystem support hardlinks? Or perhaps the filesystem reports success but no hardlinks are actually created?

**Comment by SM-9870** [comment]
Its S3 storage mounted as filesystem. It seems like hard link are not supported:
```
bash-4.4$ ln test1 test2
ln: failed to create hard link 'test2' => 'test1': Operation not supported
```

I am using S3 storage as I am running Thanos in a multi zone Cluster and S3 storage is supported regionally. NFS/Block storage is only supported zone wise. 

Do you have any suggestion in this case?

**Comment by GiedriusS** [comment]
No, all Prometheus TSDB based projects need mmap. Changing that would be a huge endeavor. You probably need to fill this issue in the Prometheus project
