### ISSUE TITLE
Thanos cant query from object store

### ISSUE THREAD

**Issue by TheCodingSheikh** [thanos-io/thanos#7798]
**Thanos, Prometheus and Golang version used**:
Kubernetes, sidecar in kube prom stack chart
And thanos bitnami chart

**Object Storage Provider**:
Ceph
**What happened**:
 
we are facing an issue with Thanos that it can't query after a certain date even though the side car are pushing metrics until current date but in the Thanos front end I can see the object store has a max time of 2024-02-18
I tried thanos tools bucket verify it didnt show any issue
Logs for sidecar, compactor, storegateway didnt include anything that seems an issue
**What you expected to happen**:
I cant query up to date
**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by TheCodingSheikh** [comment]
One thing to mention, the bucket size is now 2T
When i do thanos tools bucket inspect i can only see from 2023-09-12 to 2024-02-08

**Comment by yeya24** [comment]
Is your issue cannot query object store or cannot query object store with latest timestamp?

>  I can see the object store has a max time of 2024-02-18

So your expectation is to see max time of now?

It doesn't sound like an issue of store gateway itself. There is a metric in sidecar for lastest timestamp of uploaded block.

**Comment by mesiu84** [comment]
We have similar issue, we can only see metrics that are only 11 days old. And that time is moving every hour. Sidecar is pushing wal files without issues and I can see the oldest wal file is from 03.2024 but when I'm trying to view any metric from grafana or directly from thanos-query I can see the data not older then 11 days. We have exactly the same setup as described above.

**Comment by yeya24** [comment]
@mesiu84 It might be an issue of your compactor retention. Can you share how you configure your compactor retention time?

**Comment by mesiu84** [comment]
```compactor:
  enabled: true
  retentionResolutionRaw: 1y
  retentionResolution5m: 1y
  retentionResolution1h: 2y```
this is what we have

**Comment by mesiu84** [comment]
I'll just add that when I added --min-time to thanos store command it doesn't fix the issue, that was mentioned somewhere above

**Comment by mesiu84** [comment]
> > We have similar issue, we can only see metrics that are only 11 days old
> 
> It would be good to get more details about what you meant of only 11d old metrics. Were queries timing out or queries returned fine but only 11d metrics showed up.
> 
> Store Gateway has a built-in UI where it shows loaded blocks of the store gateway. Can you share what it looks like? Is store gateway able to load blocks older than 11 days

Found what was the issue, by mistake Thanos Query was reading data from different S3 bucket then the one used by Sidecar to push the data, after updating the settings all data is visable

**Comment by yeya24** [comment]
@TheCodingSheikh I suspect your problem is more an issue of getting data into your S3, rather than querying your metrics from S3. I will close the issue now. Feel free to reopen if you have any question

>  One thing to mention, the bucket size is now 2T
When i do thanos tools bucket inspect i can only see from 2023-09-12 to 2024-02-08
