### ISSUE TITLE
Receive: Lock race condition in multitsdb

### ISSUE THREAD

**Issue by jnyi** [thanos-io/thanos#7856]
We are testing the latest thanos main branch code to adopt cuckoo filters and found receiver sometimes has leak go routines very high numbers, did pprof, and found there are potential lock race conditions between function:

<img width="188" alt="Screenshot 2024-10-23 at 12 50 05 PM" src="https://github.com/user-attachments/assets/6c017a24-0bb5-4eaf-bfc1-1bff43aa4eae">

<img width="131" alt="Screenshot 2024-10-23 at 12 50 12 PM" src="https://github.com/user-attachments/assets/3b81b14f-6e8d-45f4-abff-86a13821be5c">

<img width="1675" alt="Screenshot 2024-10-23 at 11 45 53 AM" src="https://github.com/user-attachments/assets/9d89e5e2-4fe0-4727-bfd1-f57f6dea1f0f">

<img width="336" alt="Screenshot 2024-10-23 at 12 50 18 PM" src="https://github.com/user-attachments/assets/ffb4c7f3-e9d5-4f54-bd18-227fb5d7bc44">

**Thanos, Prometheus and Golang version used**:

thanos: v0.37.0-dev
golang: 1.23.0

**Object Storage Provider**:

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**:

**Anything else we need to know**:

**Comment by jnyi** [comment]
we plan to revert this pr internally which use more memory but less chance to cause pod goroutine leaks and hurts reliability to the system: https://github.com/thanos-io/thanos/pull/7782

**Comment by jnyi** [comment]
np, thanks for helping this out quickly, wonder if we could capture this kind of leaks in unit tests, like `-race` or because we didn't unit test this code branch properly `-race` didn't detect it?

**Comment by GiedriusS** [comment]
We have `-race` enabled but it doesn't catch stuff like this. We need some kind of linter to catch situations where we lock something but don't unlock it in all branches.
