### ISSUE TITLE
Error in Thanos Sidecar: "not uploading as no external labels are configured yet" and Scrape Protocol Unknown (PrometheusText1.0.0)

### ISSUE THREAD

**Issue by Nikhils09** [thanos-io/thanos#7923]
**Thanos and Prometheus version used**:
Prometheus 3.0.0
Thanos 0.36.1

**Object Storage Provider**: S3

**What happened**:
I am seeing the following error in the Thanos Sidecar logs, and the sidecar fails to upload metrics from Prometheus:

``` 
level=error err="not uploading as no external labels are configured yet - is Prometheus healthy/reachable?\nmain.runSidecar.func12.1\n\t/app/cmd/thanos/sidecar.go:397\ngithub.com/thanos-io/thanos/pkg/runutil.RetryWithLog\n\t/app/pkg/runutil/runutil.go:114\ngithub.com/thanos-io/thanos/pkg/runutil.Retry\n\t/app/pkg/runutil/runutil.go:104\nmain.runSidecar.func12\n\t/app/cmd/thanos/sidecar.go:395\ngithub.com/oklog/run.

(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650\naborting as no external labels found after waiting 10m0s\nmain.runSidecar.func12\n\t/app/cmd/thanos/sidecar.go:401\ngithub.com/oklog/run.(*Group).Run.func1\n\t/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650\nsidecar command 
failed\nmain.main\n\t/app/cmd/thanos/main.go:171\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650"

```

Additionally, there seems to be an issue with the scrape protocol, as the following message is being logged:

```
scrape_protocols: unknown scrape protocol PrometheusText1.0.0, 
supported: [OpenMetricsText0.0.1 OpenMetricsText1.0.0 PrometheusProto PrometheusText0.0.4] for global config"
```

**What you expected to happen**:
 Thanos Sidecar should successfully upload metrics from Prometheus and not encounter any errors related to external labels or scrape protocols.

**How to reproduce it (as minimally and precisely as possible)**:
- Deploy Thanos Sidecar version 0.36.1 alongside Prometheus (version 3.0.0).
- Ensure that Prometheus is scraping metrics correctly with the following configuration:
```yaml
global:
  scrape_interval: 2m
  scrape_timeout: 2m
  evaluation_interval: 2m
  external_labels:
    cluster: monitoring-test
```
- Check the Thanos Sidecar logs and wait for the error message

**Comment by GiedriusS** [comment]
Should be fixed by https://github.com/thanos-io/thanos/commit/bfbabbb89a3119e904d48028fb2534446e31a642
