### ISSUE TITLE
When the Prometheus version I deployed is the latest version 3.0.0, the port configured for the --grpc-address of the Thanos sidecar cannot be started

### ISSUE THREAD

**Issue by zhaoting1667** [thanos-io/thanos#7930]
###When the Prometheus version I deployed is the latest version 3.0.0, the port configured for the --grpc-address of the Thanos sidecar cannot be started

**Comment by zhaoting1667** [comment]
@dosu hi! When I set the Prometheus version to the latest version 2.55.1, the -- grpc address configured port of Thanos Sidecar will start normally. I think the current latest version of Thanos has some compatibility issues with Prometheus 3.0.0

**Comment by saswatamcode** [comment]
Hi! To use prometheus v3, you need to upgrade Thanos sidecar to v0.37 (published rc yesterday) 🙂

**Comment by zhaoting1667** [comment]
@saswatamcode Thank you very much. Since v0.37.0 is an RC version, I haven't carefully updated the logs. I'll test it later.😊

**Comment by yasharne** [comment]
@saswatamcode this fixed my issue, thanks

**Comment by MichaHoffmann** [comment]
I close the issue then!
