### ISSUE TITLE
Sidecar issue since v0.37.0

### ISSUE THREAD

**Issue by rgarcia89** [thanos-io/thanos#7947]
**Thanos, Prometheus and Golang version used**:
Thanos: v0.36.1 / v0.37.0
Prometheus: v2.51.2

**What happened**:
After upgrading the Thanos sidecar container from v0.36.1 to v0.37.0, the Thanos Querier (v0.37.0) is no longer able to properly connect to the sidecar. The screenshot below shows two clusters running v0.36.1 and four clusters running v0.37.0.

![image](https://github.com/user-attachments/assets/b1ffdef3-9df1-4c4f-b480-2fc6ab829b34)

As observed, the Min Time data is missing for the sidecars running on the latest version. Interestingly, when using Thanos Query, I can still see data newer than two hours. This suggests that the sidecar is being used since this data has not yet been uploaded to the object storage. Similarly, I can also view data from within the last two hours via Grafana. However, label_values queries no longer work when selecting this time range.

![image](https://github.com/user-attachments/assets/55360389-1704-4747-850a-cf1a8735f6c5)

**Comment by MichaHoffmann** [comment]
Maybe this could be related to https://github.com/thanos-io/thanos/pull/7820 ?

**Comment by MichaHoffmann** [comment]
Do you see anything suspicious in the sidecar logs?

**Comment by rgarcia89** [comment]
Nope nothing suspicious in there.

```
ts=2024-11-29T15:18:09.581373607Z caller=main.go:77 level=debug msg="maxprocs: Leaving GOMAXPROCS=2: CPU quota undefined"
ts=2024-11-29T15:18:09.584061062Z caller=options.go:29 level=info protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
ts=2024-11-29T15:18:09.5846933Z caller=factory.go:54 level=info msg="loading bucket configuration"
ts=2024-11-29T15:18:09.584853638Z caller=azure.go:150 level=debug msg="creating new Azure bucket connection" component=sidecar
ts=2024-11-29T15:18:09.648072464Z caller=sidecar.go:432 level=info msg="starting sidecar"
ts=2024-11-29T15:18:09.648222143Z caller=intrumentation.go:75 level=info msg="changing probe status" status=healthy
ts=2024-11-29T15:18:09.648276193Z caller=http.go:73 level=info service=http/server component=sidecar msg="listening for requests and metrics" address=:10902
ts=2024-11-29T15:18:09.648720274Z caller=reloader.go:274 level=info component=reloader msg="nothing to be watched"
ts=2024-11-29T15:18:09.648857256Z caller=tls_config.go:348 level=info service=http/server component=sidecar msg="Listening on" address=[::]:10902
ts=2024-11-29T15:18:09.648932726Z caller=tls_config.go:351 level=info service=http/server component=sidecar msg="TLS is disabled." http2=false address=[::]:10902
ts=2024-11-29T15:18:09.656684874Z caller=sidecar.go:444 level=warn msg="failed to get Prometheus flags. Is Prometheus running? Retrying" err="got non-200 response code: 503, response: Service Unavailable"
ts=2024-11-29T15:18:11.660515648Z caller=sidecar.go:444 level=warn msg="failed to get Prometheus flags. Is Prometheus running? Retrying" err="got non-200 response code: 503, response: Service Unavailable"
ts=2024-11-29T15:18:13.654530085Z caller=sidecar.go:200 level=info msg="successfully validated prometheus flags"
ts=2024-11-29T15:18:13.655620235Z caller=promclient.go:663 level=debug msg="build version" url=http://localhost:9090/api/v1/status/buildinfo
ts=2024-11-29T15:18:13.658524014Z caller=sidecar.go:223 level=info msg="successfully loaded prometheus version"
ts=2024-11-29T15:18:13.659194342Z caller=promclient.go:699 level=debug msg="lowest timestamp" url=http://localhost:9090/metrics
ts=2024-11-29T15:18:13.7098399Z caller=sidecar.go:254 level=info msg="successfully loaded prometheus external labels" external_labels="{cluster=\"rnd\", prometheus=\"monitoring/rnd\", prometheus_replica=\"prometheus-rnd-0\", stage=\"lab\"}"
ts=2024-11-29T15:18:13.714241929Z caller=intrumentation.go:56 level=info msg="changing probe status" status=ready
ts=2024-11-29T15:18:13.714966097Z caller=promclient.go:699 level=debug msg="lowest timestamp" url=http://localhost:9090/metrics
ts=2024-11-29T15:18:13.715796374Z caller=grpc.go:167 level=info service=gRPC/server component=sidecar msg="listening for serving gRPC" address=:10901
ts=2024-11-29T15:18:43.71504741Z caller=promclient.go:699 level=debug msg="lowest timestamp" url=http://localhost:9090/metrics
ts=2024-11-29T15:19:13.71577582Z caller=promclient.go:699 level=debug msg="lowest timestamp" url=http://localhost:9090/metrics
```

**Comment by MichaHoffmann** [comment]
So it looks like we were able to get lowest timestamp from prometheus. Did prometheus cut a block already?

**Comment by rgarcia89** [comment]
Not since I restarted it. We have configured a block size of 2h

![image](https://github.com/user-attachments/assets/3e2a3466-18b7-4049-9573-74f6d1a742b4)

**Comment by rgarcia89** [comment]
I will let you know. Still, this is not happening with v0.36.1

**Comment by MichaHoffmann** [comment]
> I will let you know. Still, this is not happening with v0.36.1

Yeah; we likely need to fallback to shipper timestamp if we cannot consult the metrics ~ thats a bug; but it would still be cool to know if it recovers after first block is cut!

**Comment by rgarcia89** [comment]
No difference even after prometheus cut a block

**Comment by yeya24** [comment]
@MichaHoffmann Do you plan to work on a fix?

**Comment by rgarcia89** [comment]
Results of the troubleshooting session with @MichaHoffmann 
https://gist.github.com/rgarcia89/2c9a54e8cb7ec9864c05af5037e19cfe

**Comment by yeya24** [comment]
@rgarcia89 Can you give a TLDR of the troubleshooting session? 
Is it related to the `limit` parameter?

**Comment by MichaHoffmann** [comment]
> @rgarcia89 Can you give a TLDR of the troubleshooting session? Is it related to the `limit` parameter?

Limit parameter defaults to 0 for us if not set because we take it from grpc request hints; this works fine with prometheus 2.54+ but not earlier since 0 was illegal parameter there then. Fix is to set it only if its gt 0

**Comment by MichaHoffmann** [comment]
Fixed in 0.37.1

**Comment by ro1611** [comment]
Hi Team, 

We are getting the similar issues as mentioned above where thanos query unable  to pull data from Thanos sidecar. 
Error: No StoreAPI matched for this query.

Version used as below.
Thanos: v0.37.0 & v0.37.1
Prometheus: v3.1.0

It looks like because of this, we are unable to fetch real time data in Grafana. Can someone help here please?
Let me know if need any more information or any logs for debug.

**Comment by rohi1799** [comment]
Hi guys, any updates on the above issue?

**Comment by ro1611** [comment]
Hi Guys, any updates on the above issue?
