### ISSUE TITLE
Receive : Receive 0.36.1 in router / ingestor mode has a memory leak and goes OOM every 2 hrs

### ISSUE THREAD

**Issue by midhun-mohan** [thanos-io/thanos#7963]
**Thanos, Prometheus and Golang version used**:
Thanos : 0.36.1
Prometheus 2.54.1

/ $ thanos --version
thanos, version 0.36.1 (branch: HEAD, revision: 99a5742a15f107d4607d280c825eca5b7f09a253)
  build user:       root@3b4bc83e1037
  build date:       20240813-11:33:32
  go version:       go1.21.13
  platform:         linux/amd64
  tags:             netgo

**Object Storage Provider**:
Azure Blob Storage

**What happened**:
Memory leak for Thanos receive in router ingestor mode

**What you expected to happen**:

No memory leaks happen

**How to reproduce it (as minimally and precisely as possible)**:
Not sure. 

**Full logs to relevant components**:
<img width="1900" alt="image" src="https://github.com/user-attachments/assets/7bc805cf-731f-4332-99d6-5e6f9c335a40">

**Anything else we need to know**:

**Comment by GiedriusS** [comment]
Is it the same with 0.37.1?

**Comment by midhun-mohan** [comment]
Haven't tried 0.37.1. But I am happy to try it. Will report back today

**Comment by midhun-mohan** [comment]
@GiedriusS Its still the same with the new version. 
<img width="1906" alt="image" src="https://github.com/user-attachments/assets/47adcd36-1d16-426b-86bb-450e846b45dc">

**Comment by midhun-mohan** [comment]
Heap memory keeps increasing. 
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/26cee1c3-2b0e-4619-ab25-e01d7a726b2e">

**Comment by GiedriusS** [comment]
I don't think it's a bug - it's how the Prometheus TSDB works. It truncates the WAL and produces a new block every 2h for optimal compression. That's why you see memory usage increase and drop every 2h.

**Comment by midhun-mohan** [comment]
It's not exactly 2hrs. Its around 2 hrs
If you see this instance, it was started at 13:40 and the memory reached all the way to the roof which is at 32 GB and then OOMed at 15:15 which is around 1 hr and 35 minutes. This is not a block size which is 2hrs by default in our environment 
<img width="1909" alt="image" src="https://github.com/user-attachments/assets/cd7c052b-1d71-48ce-901c-3b1252631ddd">

**Comment by midhun-mohan** [comment]
adding a bigger window
<img width="1895" alt="image" src="https://github.com/user-attachments/assets/7346be33-76e4-4f35-bc0b-cc490c958a96">

**Comment by midhun-mohan** [comment]
@MichaHoffmann 
I am now running with more resources for Thanos receive to see how it behaves after 2 hrs. But I have few questions
1) I believe the block is stored in the attached persistent volume and not in memory.  If so what would be causing this increase?
2) Is receive supposed to ingest data to object storage while it receives or is it creating a block and then uploading it?
3) Where is this block stored?

**Comment by midhun-mohan** [comment]
Testing with more resources to pass over 2hours
<img width="1371" alt="image" src="https://github.com/user-attachments/assets/d37932e7-5197-4651-90b2-44c57c6a0c97">

**Comment by MichaHoffmann** [comment]
> @MichaHoffmann 
> I am now running with more resources for Thanos receive to see how it behaves after 2 hrs. But I have few questions
> 1) I believe the block is stored in the attached persistent volume and not in memory.  If so what would be causing this increase?
> 2) Is receive supposed to ingest data to object storage while it receives or is it creating a block and then uploading it?
> 3) Where is this block stored?

Block is stored on disk and mmapped - later it is uploaded to object storage. Head block is stored in memory. You could try decreasing length of blocks to 1h maybe

**Comment by midhun-mohan** [comment]
To me this looks like a memory leak.

Every two hours, the metric `prometheus_tsdb_head_series`  in receive is being flushed as seen in the below screenshot. But the memory is not cleaned up. It eats up whatever available and them went OOM at around 03:00 - 04:00

The current config for reference :  Replication factor is changed to 2, number of pods of ingestor is increased to 6.  The only change I have seen is that it took more time to fall over as compared to the previous settings.

Explanation of Graphs :
First tile shows the `memory` used by each of the ingestor pods. Limit is at 45GB.
Second row shows the `Rate of series / samples` received by receive
Third row shows the metric `prometheus_tsdb_head_series` as seen from receive and our prometheus instance
Fourth row shows the metric `prometheus_tsdb_head_samples_appended_total` as seen from receive and our prometheus instance

<img width="1510" alt="image" src="https://github.com/user-attachments/assets/2e66adc6-c2ed-49df-aee6-28da4e217f0e">

**Comment by MichaHoffmann** [comment]
Can you take a heap profile and upload to pprof.me and share here please? It would be interesting to see what it contains!

**Comment by MichaHoffmann** [comment]
Can you also share configuration of the ingestor component? Do you by chance enabled out of order writes?

**Comment by midhun-mohan** [comment]
Yes. I do have config for out of order writes.

Here is the config for investor. 

```
        - args:
            - receive
            - --log.level=info
            - --log.format=json
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:10902
            - --tsdb.max-exemplars=1000000
            - --tsdb.too-far-in-future.time-window=180s
            - --tsdb.out-of-order.time-window=1800s
            - --remote-write.address=0.0.0.0:19291
            - --tsdb.path=/var/thanos/receive
            - --tsdb.retention=2h
            - --label=replica="$(NAME)"
            - --label=receive="true"
            - --objstore.config=$(OBJSTORE_CONFIG)
            - --receive.local-endpoint=$(NAME).thanos-receive-ingestor-default.$(NAMESPACE).svc.cluster.local:10901
```

**Comment by MichaHoffmann** [comment]
That looks pretty normal except the amount of exemplars, can you try without them just for an experiment?

**Comment by midhun-mohan** [comment]
This is the config for the router.

Yes I can remove exemplars from this one and do a deploy.
```
      - args:
        - receive
        - --log.level=info
        - --log.format=json
        - --tsdb.max-exemplars=1000000
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --remote-write.address=0.0.0.0:19291
        - --receive.replication-factor=2
        - --receive.hashrings-file=/var/lib/thanos-receive/hashrings.json
        - --receive.hashrings-algorithm=ketama
        - --label=replica="$(NAME)"
        - --label=receive="true"
```

**Comment by midhun-mohan** [comment]
@MichaHoffmann 
[Here is a ppof from one of the pod](https://pprof.me/280e23c1b90617cc4a944b2244d083a1/?profileType=profile%253Aalloc_objects%253Acount%253Aspace%253Abytes&color_by=filename)

**Comment by midhun-mohan** [comment]
@MichaHoffmann 
Good news.  After turning exemplar off, the memory is very very stable at 1.6 GB 😱 

Do you have any idea on how often exemplar is flushed from memory?

<img width="1509" alt="image" src="https://github.com/user-attachments/assets/54edc05c-bc33-45b0-99fc-ed42b659bfed">

**Comment by yeya24** [comment]
> Do you have any idea on how often exemplar is flushed from memory?

@midhun-mohan No, exemplars are never flushed from memory to disk so please limit the number of exemplars. That's the same as what Prometheus does today.

**Comment by midhun-mohan** [comment]
@yeya24 Just asking, do you know what is the default in prometheus from the top of your head?

**Comment by MichaHoffmann** [comment]
Can the issue be closed as it's just a misconfiguration essentially?

**Comment by midhun-mohan** [comment]
@MichaHoffmann Yes. It can be closed. 
In anycase, do you know the defaults in prometheus from the top of your head or even an ideal value for it?

**Comment by MichaHoffmann** [comment]
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#exemplars 100k seemingly!

**Comment by midhun-mohan** [comment]
@MichaHoffmann @yeya24 
Thank you for your time. Very much appreciated ❤️

**Comment by midhun-mohan** [comment]
@MichaHoffmann @yeya24 

A followup question, 
Is exemplar stored to object storage at any time?

I am wondering how can we make sure that previous exemplar that was injected is available for future use.
