### ISSUE TITLE
rpc transport closing error while accessing thanos-sidecar through traefik-ingress-proxy

### ISSUE THREAD

**Issue by pruthvirajkanmantha** [thanos-io/thanos#805]
***
I'm trying to debug an issue related to grpc client communication in kubernetes cluster through traefik-ingress-proxy. Although I'm able to communicate with thanos-sidecar using grpcurl, thanos-query component still complains 

```level=warn ts=2019-02-03T13:10:23.590282544Z caller=storeset.go:305 component=storeset msg="update of store node failed" err="initial store client info fetch: rpc error: code = Unavailable desc = transport is closing" address=store-api.apps.local:443```

Thanos query command:

 ```thanos query  --log.level=debug --query.replica-label=replica --store=store-api.apps.local:443  --store.sd-interval=5m``` 

Ingress rule:

 ```---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: kube-system   
  annotations:   
    ingress.kubernetes.io/protocol: h2c
spec:
  rules:
  - host: store-api.apps.local
    http:
      paths:
      - backend:
          serviceName: prometheus-sidecar
          servicePort: 10901 
```
Please let me know if you guys have any inputs on this. Thanks in advance.

**Comment by bwplotka** [comment]
I am really not familiar with `traefik-ingress-proxy`, but if it supports gRPC.. it should work.

There are couple of issues here & there: https://github.com/containous/traefik/issues/3518 worth to check them out.

The important one is that you need to make sure to not load balance between sidecar replicas. Each of replica should be available separatedly (:
