### ISSUE TITLE
[Store] Credentials resolved slowly on anonymous S3 access

### ISSUE THREAD

**Issue by d-ulyanov** [thanos-io/thanos#815]
Thanos Store v0.2.1

**What happened**
Store starts slowly (hours if there is a lot of data).

**What you expected to happen**
Store starts in a minute or few minutes if there you have more than hundred blocks in S3

**How to reproduce it (as minimally and precisely as possible)**:
Omit access key in S3 configuration  

We're using Minio as S3 store and experienced very long start up time for Store component.
The problem was caused by resolving credentials (in chain) on each request. First provider in chain is AWS IAM provider who's IP is not accessible from Internet. 
So each request to IAM failed with timeout. 

If AccessKey and SecretAccessKey could not be resolved - credential will never be cached.
Such situation is possible in EnvAWS provider if Env variables is empty or not exists.

So it seems that the possible solution is to cache credentials in case if there was no errors from provider.  

Let's discuss about solution and I can fix it :)
Thanks!

**Comment by bwplotka** [comment]
hmmmm I don't think we resolve auth on every request. If minio librario does it then it is bad. From Thanos code perspective we create just once bucket client and use this for whole service lifetime.

How fo you know it is because of credential resolution?

**Comment by d-ulyanov** [comment]
Sorry, @bwplotka , I've just updated description. 
Auth will be resolved on each request if last provider (EnvAWS) will return empty values from ENV.

**Comment by d-ulyanov** [comment]
Sorry, it's not in Thanos, its in minio-go dependency :)

https://github.com/minio/minio-go/blob/master/pkg/credentials/chain.go#L68
https://github.com/minio/minio-go/blob/master/pkg/credentials/env_aws.go#L60

**Comment by bwplotka** [comment]
Can we create issue on minio to fix it there? (:

**Comment by d-ulyanov** [comment]
Alright, I'll try to fix it there and upgrade Thanos then. Thank you)

**Comment by d-ulyanov** [comment]
Ok, here's an issue
https://github.com/minio/minio-go/issues/1072

**Comment by bwplotka** [comment]
Any update on this @d-ulyanov ? Looks like we got nice feedback on minio issue (:

**Comment by d-ulyanov** [comment]
Yep, I suppose this issue could be closed
