### ISSUE TITLE
Remove overlap when querying data that both Source and Store have.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#82]
Basically we don't want to ask for the same data twice. Since we know that:
- Source:
  * Produces some data and pushes that to some storage
  * Makes that data accessible for short time (aggressive retention)
  * Faster
- Store:
  * Does not produce any data just enable browsing data from storage
  * Probably slower

As we agreed, it would nice to get as much as possible from Source and rest from store.
As an example:
```
0───2───4───6───8───10
└────Store───┘
         └───Source──┘
    └────Query───┘                               
```
When we query for `2-8` we can make naive algorithm that gets `max(minTime)` from Source (`4` here) and we can query
`2-4` + 1 for safeguard so `2-5` from store
`4-8` + 1 for safeguard so `3-8` from source.
We need safeguards, since the propagation is eventually consistent.

**Problems**:
1. There could be multiple *sources* that can have different `minTime`:
```
0───2───4───6───8───10
└────Store───┘
         └───Source1─┘
           └─Source2─┘
    └────Query───┘                               
```
And even worse in this case for store.. are we sure that `0-6` include actually `4-6` from Source1?
 * Potential solution: We need minTime-maxTime ranges for each store -> PER source.
2. There could be multiple *stores* that can use different backends.. (e.g different buckets -> "global queue" case)
  * Potential solution: minTime->maxTime per store or `storageID`

As we can see, any solution requires to introduce a lot of complexity (passing some IDs to match time ranges), but for what benefit? In reality it in worst case it will be ~12h of unnecessary data for each source in system. That sounds a lot if you want to have rule component and HA (so 3*12h)

**Potential complexity reduction:** 
Since store nodes have peer info about source, they can limit returned data to the data still available from source node. But still we need some ID matching.

**Comment by Bplotka** [comment]
The questions we want to answer:
- Is it worth to dive in into this NOW
- Is there any simpler generic solution that will work for all cases? Cannot see any.
- How we will match stores to sources (just arbitrary ID? external labels?)

**Comment by Bplotka** [comment]
+1 but still: max-synced-time -> needs to be PER Store (:

**Comment by vishnubraj** [comment]
+1

**Comment by bwplotka** [comment]
Thanks for bumping. This issue can be now resolved thanks to [--min-time (time slicing)] flags for both Store Gateway and sidecar.

By default both sidecar and store gateway expose all data they have:
However you can:
* add `--min-time` to sidecar with e.g `4h` value. This will ensure only 4h of of sidecar data is exposed. Useful when you want to use Store Gateway for older queries.
* add `--max-time` for store gateway for something like `retention` minus safety buffer of Prometheus. No min-time for sidecar. This will allow Store GW to not expose anything "younger" than X time. Useful if you want to allow Prometheus to be used rather store Gateway. This however is not ideal as this is a requirement still: [local compaction has to be disabled when uploading blocks](https://github.com/thanos-io/thanos/issues/206)
