### ISSUE TITLE
Thanos can get data from store component but MISSING a part data

### ISSUE THREAD

**Issue by thachnv92** [thanos-io/thanos#845]
Hello,
I have 2 servers setup prometheus A and B. Both A and B upload data to AWS S3 by Sidecar.
I have 1 server setup Thanos Store C get data from AWS S3.
And 1 server setup Thanos Query D.

Data from server A
![nh](https://user-images.githubusercontent.com/38679578/52839952-58d12600-312a-11e9-9833-0b2e8211d77f.png)

Data from server B
![nh](https://user-images.githubusercontent.com/38679578/52839967-62f32480-312a-11e9-9137-296a5fb85e18.png)

When I run Thanos query with 2 source is prometheus server A and B, everything is Ok. Graph show all data from server A and B.
![nh](https://user-images.githubusercontent.com/38679578/52840415-c762b380-312b-11e9-8d85-cd508dd2efa6.png)

But when I run Thanos query with source is Store C, Graph can't show all data. I see many data is missed.
![nh](https://user-images.githubusercontent.com/38679578/52840394-af8b2f80-312b-11e9-80ea-a7d23f154e0f.png)
I checked and see all data from Prometheus server uploaded to AWS S3 successful.

Please explain for me this issue.
And tell me how to fix this issue.
Thank you.

**Comment by bwplotka** [comment]
What do you mean "can't get missing data"? (: 

Can we have the info, what Thanos version you are using? Any logs from thanos store? It looks quite weird. How you configure thanos components? It looks really like thanos store has access only to some blocks.

**Comment by thachnv92** [comment]
@bwplotka Sorry, I changed title but I mistake.
My title is "Thanos can get data from store component but MISSING a part data".

My thanos version:
```
thanos, version 0.2.1 (branch: HEAD, revision: 30e7cbdafd3ef01189f202945c2728fcf37e1cf1)
  build user:       root@79ffcf51ff9b
  build date:       20181227-15:44:56
  go version:       go1.11.4
```
I'm not config for thanos store logs.
All logs store in AWS S3, same folder, So I think thanos store has access to all blocks.

Could you tell me to config log for thanos store?
