### ISSUE TITLE
.*: Recover from panics in goroutines/run.Groups as well in gRPC server request. 

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#890]
We have recovery from panics in gRPC interceptor... but it does not matter as we do all in go routines anywhere. We should safeguard those as well.

This might involve extending `run.Group` / contributing.

**Comment by GiedriusS** [comment]
@bwplotka https://github.com/improbable-eng/thanos/pull/932 WDYT of something like this?

**Comment by bwplotka** [comment]
Yup! Commented <3
