### ISSUE TITLE
grpc: Add logging interceptors.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#891]
Acceptance Criteria: 
* Each request is logged on debug
* Error request produces error log.

**Comment by adrien-f** [comment]
I looked into it and "official" middlewares exists for logrus and zap but not go-kit which is used in Thanos:

* https://github.com/grpc-ecosystem/go-grpc-middleware/tree/master/logging

A little bit of glue is needed ! Might be worth contributing it back ?

**Comment by bwplotka** [comment]
We are maintainers of it (: so we can add that!

**Comment by bwplotka** [comment]
https://github.com/grpc-ecosystem/go-grpc-middleware/issues/64

**Comment by adrien-f** [comment]
Started working on this 😄

**Comment by adrien-f** [comment]
PR made in upstream :) We're getting there !
