### ISSUE TITLE
query: Gaps in Graphed Data

### ISSUE THREAD

**Issue by jjneely** [thanos-io/thanos#896]
**Thanos, Prometheus and Golang version used**

```
$ sudo docker run -it us.gcr.io/fit-prometheus-glob/thanos:0.3.2-r0-8967-gc860b84 --version
thanos, version 0.3.2 (branch: master, revision: 4b7320c0e45e3f48a437bd19294f569785bafb02)
  build user:       root@a29ae292aca7
  build date:       20190304-19:30:39
  go version:       go1.11.5
```

```
$ sudo docker run -it us.gcr.io/fit-prometheus-glob/prometheus:r0-8299-g4c097d2 --version
prometheus, version 2.4.3 (branch: v2.4.3, revision: a605bc881ae3f59e0e001cdd747b6905d5a1b4be)
  build user:       root@fbd6ba49b749
  build date:       20190128-21:36:32
  go version:       go1.11.5
```

**What happened**

Running queries through the Thanos query UI occasionally produces graphs with gaps where valid data is known to exist.  This seems reproducible at graph ranges spanning about 4000h to 1y with many timeseries displayed.

**What you expected to happen**

Graphs should be rendered without data gaps.

**How to reproduce it (as minimally and precisely as possible)**

We used the Thanos benchmark tools and modified them to produce test Prometheus data.  The goal here was to get an idea how Thanos would perform with larger time spans of data, and handle common miss-usages of Prometheus and high cardinality recording rule data.  I built the following code which imports a tsdb package that should be familar to the Thanos authors.

https://github.com/jjneely/stuff/blob/master/cmd/historygen/main.go

We modified the tsdb generator code to create metrics that look like:

```
test{instance="test-metric-XXX", job="testdata"}
```

Where XXX is a zero based index that's incremented to create the number of time series requested on the CLI.  Time series values are nanoseconds since the epoch.  We built a data set of 500 time series going back 1 year.

We copied this data to a GCS bucket and started Store and Compact processes using the same bucket.  Using the Query UI we performed a number of tests and noticed that for 1y graph ranges the data had unexpected gaps.

**Full logs to relevant components**

No logs are emitted from the query interface when this happens.  I may not have them turned up high enough.

**Anything else we need to know**

Pictures are worth a thousand words, right?

Query here is `sum(test{instance=~"test-metric-[012].."})` with auto downsample enabled with the range set to 1y.  This data has been compacted and downsampled by the Compat process.

![thanos-1y-normal-20190306](https://user-images.githubusercontent.com/10540/53910870-f1204380-4022-11e9-9359-d35836164886.png)

Query here is `sum(test{instance=~"test-metric-[0123].."} )` so this selects 400 time series from the test data set.  Gaps begin to appear.

![thanos-1y-gaps-20190306](https://user-images.githubusercontent.com/10540/53911043-61c76000-4023-11e9-8bb5-690995ee5b94.png)

I am jjneely on Slack.

**Comment by bwplotka** [comment]
Hey! Thanks for reporting.

I think this points to some bug in choosing what downsampling levels should be used. Gaps if any suggest either lack of downsampled block (bug in what was compacted). I would be honest: This path is not properly unit/integration tested as it should (:  Help wanted.

I will try to dig and repro it locally, but in mean time:

* Can you try `sum_over_time` instead of `sum`? Only this will have 100% accurate data.
* Can you zoom in, in place of gap? Do you have that data?
* I don't get what is the difference between queries... literally just more time series is summed? That's super weird!

**Comment by jjneely** [comment]
The following images are using the query `sum_over_time(test{instance=~"test-metric-[0123].."}[1h])` with a 1y range.  I've not changed the test data.  What's super fun is that gaps move.  So yes, I'm convinced that I have data throughout the query range.

![thanos-1y-gaps-20190307-01](https://user-images.githubusercontent.com/10540/53978205-a7923000-40d8-11e9-93ec-a931d9fa56cf.png)
![thanos-1y-gaps-20190307-00](https://user-images.githubusercontent.com/10540/53978207-a7923000-40d8-11e9-8580-d303171be10a.png)

**Comment by jjneely** [comment]
I dug through the code enough to realize that whatever is causing the above is going to be in the Store component.  

Separately I decided I'd adjust `--chunk-pool-size` and `--index-cache-size` as the initial values looked on the small side for the size we envision our cluster to be.  I set them to this:

```
store_args    = "--cluster.disable --objstore.config-file=/config/bucket.yaml --data-dir=/data/ --index-cache-size=3GB --chunk-pool-size=8GB"
```

By fluke I decided to attempt to reproduce the above gaps...and to my surprised the issue seemed fixed!  After several attempts and using all 500 metrics (above case appeared at 400 metrics) in my test data I could not reproduce the movable gaps.  I bet this narrows things down quite a bit.

![thanos-1y-gaps-solved-20190308-00](https://user-images.githubusercontent.com/10540/54057106-f797f200-41bf-11e9-9900-861fc4964002.png)

**Comment by bwplotka** [comment]
It seems like yea -> the really low index cache size was the reason.. I think it's still a valid bug, but nice you are unblocked.

**Comment by GiedriusS** [comment]
Is this still reproducible even with small index cache sizes on `0.5.0`? There were some fixes WRT the index cache handling / block selection.

**Comment by GiedriusS** [comment]
@jjneely any updates?

**Comment by jjneely** [comment]
I haven't yet tested, let me see if I can reproduce tomorrow morning.

**Comment by jjneely** [comment]
![thanos-bug-896-20190710](https://user-images.githubusercontent.com/10540/60993094-c5d49a80-a31b-11e9-8bcd-5e463863bb4d.png)

This definitely still exists.  This is with the default settings for `index-cache-size` and `chunk-pool-size`.
