### ISSUE TITLE
store: persistent index cache across restart

### ISSUE THREAD

**Issue by Ehekatl** [thanos-io/thanos#902]
**Thanos, Prometheus and Golang version used**

v1.0

**What happened**

In our production environment, thanos store initializing will last more than 1 hour, with Gigabytes traffic per second. That means every time it restart, the minimum recovery time is one hour.

**What you expected to happen**

There is no need to pull all the data from s3 everytime is start, if thanos store could reuse the cache, it can greatly reduce the pain when there is a pod failure

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

**Anything else we need to know**

**Comment by GiedriusS** [comment]
Seems like a duplicate of one of the ideas listed here: https://github.com/improbable-eng/thanos/issues/814. Could you please check it?

**Comment by Ehekatl** [comment]
@GiedriusS ya it's related with #664 I saw that one
but maybe not necessarily the same

e.g. when the store restart, if it only fetch the incremental cache from s3, the init time would be greatly reduced.

**Comment by godliness** [comment]
@Ehekatl In version 0.3.2, if your local disk already has the index cache file, store will not to download them again, so ti think it hav  solved your problem.
