### ISSUE TITLE
Pin quay.io/prometheus/busybox docker image

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#911]
We cannot do port-forward for Thanos images recently due to:

```
Handling connection for 43709
Handling connection for 43709
E0312 13:56:25.445092   19402 portforward.go:329] an error occurred forwarding 43709 -> 19191: error forwarding port 19191 to pod simstoregw-0_infra, uid : unable to do port forwarding: socat not found.
E0312 13:56:55.018961   19402 portforward.go:269] error creating error stream for port 43709 -> 19191: Timeout occured
```

This is because we pin to latest `FROM quay.io/prometheus/busybox:latest`. We should aim on pinning to something that has `socat` and allows us to do port forwading

AC: 
* Find base image with `sockat` and proper tooling (e.g net tools with `curl` `git` and `dig` is must have)
* Pin to certain version

Non-goals:
* Making sure image is super small, that's not a requirement. But smaller = better.

**Comment by Hashfyre** [comment]
@bwplotka I'm happy to work on this.

**Comment by povilasv** [comment]
maybe this should also be fixed in `quay.io/prometheus/busybox:latest` as it's regression on their part and al lot of ppl run Prometheus in k8s.

**Comment by kadern0** [comment]
Any reason for not using Alpine?

**Comment by aditya-konarde** [comment]
I tried this locally at it seems to work fine: 

```
~ $ oc port-forward thanos-querier-8f98ccf65-7m6tw 9090:9090
Forwarding from 127.0.0.1:9090 -> 9090
Forwarding from [::1]:9090 -> 9090
Handling connection for 9090
```

I am guessing it was a regression in the base image that has now been fixed. Any reason why we don't pin to a specific tag per thanos release regardless of all this?

**Comment by bwplotka** [comment]
No reason; good point - we 100% should. Help wanted. (:

**Comment by Steiniche** [comment]
@bwplotka should this issue be edited or close and another opened for pinning instead?

**Comment by bwplotka** [comment]
AC:
* Pin quay.io/prometheus/busybox version we use in our docker files.

**Comment by Steiniche** [comment]
Thanks for the update @bwplotka.
I could definitely help with pinning the dependency, however prometheus busybox does not have other tags than latest: https://hub.docker.com/r/prom/busybox/tags.
Should I open a issue to discuss it in the prometheus/busybox repo?

**Comment by bwplotka** [comment]
Yes, please - it would be nice to have some solution to this.

Essentially without pinning we are adding another unknown to the system which is `what busybox base we built with`

**Comment by Steiniche** [comment]
Waiting for pr from @daixiang0

**Comment by daixiang0** [comment]
wait for review @bwplotka

**Comment by bwplotka** [comment]
You mean you are "waiting for review"?

**Comment by daixiang0** [comment]
I want some feedback if anything need changes @bwplotka

**Comment by Steiniche** [comment]
Issue is still relevant.

**Comment by brancz** [comment]
This is still a problem.
