### ISSUE TITLE
thanos_sidecar_prometheus_up metric is wrong

### ISSUE THREAD

**Issue by bennydubois** [thanos-io/thanos#944]
**Thanos, Prometheus and Golang version used**
thanos, version 0.3.2 (branch: HEAD, revision: 4b7320c0e45e3f48a437bd19294f569785bafb02)
  build user:       root@e9a9c28f966a
  build date:       20190304-17:11:05
  go version:       go1.11.5

prometheus, version 2.6.0

**What happened**
Sidecar can't connect to Prometheus but alert didn't fire because metric thanos_sidecar_prometheus_up 1

**What you expected to happen**
thanos_sidecar_prometheus_up 0

**Full logs to relevant components**
systemctl status for the sidecar goes:
thanos[104380]: level=warn ts=2019-03-19T18:26:52.84930845Z caller=sidecar.go:132 msg="failed to fetch initial external labels. Is Prometheus running? Retrying" err="is 'web.enable-admin-api' flag enabled? got non-200 response code: 503, response: Service Unavailable"

Prometheus is up and running and restarting the sidecar fixed the issue, but only after quite a bit of sleuthing. Unless I misunderstand this metric, shouldn't it have trapped this 503 code?

**Comment by FUSAKLA** [comment]
Hi, hm looking at the code and it seems be ok. 
Can you show graph of the `thanos_sidecar_prometheus_up` metric and also `thanos_sidecar_last_heartbeat_success_time_seconds` from the given time?

It is set to 0 when calling the prometheus fails and 1 again when it passes.
those checks are every 2s on start till it succeeds and after that every 30s. 

Did you have the admin API enabled?

**Comment by bennydubois** [comment]
Hi

Prometheus's web API is disabled. As for the graphs they looked like while the issue persisted:
![Untitled](https://user-images.githubusercontent.com/48732469/54945918-5cb44d00-4f0d-11e9-83aa-a9a38fc7d1ef.png)
![thanos-2](https://user-images.githubusercontent.com/48732469/54945924-5e7e1080-4f0d-11e9-886a-8cf8f3e988f0.png)
