### ISSUE TITLE
query: Allow for http endpoint to be protected by TLS

### ISSUE THREAD

**Issue by wjam** [thanos-io/thanos#945]
In some environments, it is advantageous to have all traffic encrypted end to end. While this is currently possible to achieve if Thanos is run inside a Kubernetes environment, it is not possible if Thanos is run outside of Kubernetes.

The call to `net.Listen` in the query component needs to be expanded so that the relevant HTTP endpoints can be served over HTTPS, using relevant certificates.

**Comment by GiedriusS** [comment]
I don't feel like this should be a part of this project since you can easily run a proxy in front of Thanos Query, on the same machine, which will do TLS termination. Is there any reason why that doesn't work for you, @wjam?

**Comment by povilasv** [comment]
:+1: to what @GiedriusS said. Prometheus doesn't allow you to do this either.

> Prometheus does not directly support Transport Layer Security (TLS) encryption for connections to Prometheus instances (i.e. to the expression browser or HTTP API). If you would like to enforce TLS for those connections, we recommend using Prometheus in conjunction with a reverse proxy and applying TLS at the proxy layer. You can use any reverse proxy you like with Prometheus, but in this guide we'll provide an nginx example.

https://prometheus.io/docs/guides/tls-encryption/

Maybe we should document this behaviour if we all agree on it?
