### ISSUE TITLE
Fix `goimports`.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#984]
AC:
* `make format` or `gomiports` should fix blank lines.

Eg: 
```
 	"net/http"
 	"path"
 	"regexp"
 	"sort"
 
+	thanosrule "github.com/improbable-eng/thanos/pkg/rule"
+
 	"github.com/improbable-eng/thanos/pkg/store/storepb"
 
 	"github.com/go-kit/kit/log"
 	"github.com/prometheus/client_golang/prometheus"
 	"github.com/prometheus/common/route"
```
`goimports` does NOT fixes those, see why: https://github.com/golang/go/issues/26246

This is quite annoying. I think this was fixed, but then reverted. Anyway we should ensure this is fixed.

**Comment by jojohappy** [comment]
I saw it had been fixed with pinned `goimports`. Any update? @bwplotka

**Comment by bwplotka** [comment]
Still valid.

**Comment by bwplotka** [comment]
Same problem.

**Comment by bwplotka** [comment]
Still broken

**Comment by bwplotka** [comment]
Still goimports is leaving blank lines.

**Comment by bwplotka** [comment]
eh eh (:
