### ISSUE TITLE
query: Ability to turn off grpc server on querier

### ISSUE THREAD

**Issue by kitemongerer** [thanos-io/thanos#993]
**Thanos, Prometheus and Golang version used**
Thanos version 0.3.2 
```
thanos, version 0.3.2 (branch: HEAD, revision: 4b7320c0e45e3f48a437bd19294f569785bafb02)
  build user:       root@e9a9c28f966a
  build date:       20190304-17:11:05
  go version:       go1.11.5
```

**What happened**
When I run the Thanos Query binary and don't provide any grpc server command arguments and I have gossip turned off I see a grpc server spun up on port 10901.  In this situation we are explicitly not setting `--grpc-address` and `--grpc-advertise-address`
**What you expected to happen**
I would expect the grpc server to be disabled.  I'm not sure what it would even do for the Querier at this point.  
**How to reproduce it (as minimally and precisely as possible)**:
Start the Thanos Query binary and run `netstat -l -p` . You'll see Thanos listening on port 10901.  No particular command line arguments are necessary.

**Comment by FUSAKLA** [comment]
Hi, the queries exposes the StoreAPI the same way sidecar, store or rule does. 
This allows you to build hiararchy of thanos clusters having one query querying nodes of two distinct thanos clusters. 

So it's not useless but I understand you don't need it. On the other hand the same way you could require possibility to disable the HTTP servers for every other component if you are not going to scrape it's metrics.

So I'm not sure on this one?

**Comment by povilasv** [comment]
just don't expose the port, in Kubernetes you have a simple option to just remove `containerPort` section

```
     - name: ..
        image: ...
        ports:
        - containerPort: 443
        - containerPort: 80
```

Also its trivial to write iptables rule to block it.

**Comment by robertjsullivan** [comment]
I think it would be good to provide an option to disable it.  Enterprise level customers would greatly prefer to only spin up endpoints that are going to be used as it lowers the risk profile.  Locking it down to localhost is a good interim solution, but why not allow people to disable it like we do with gossip?

**Comment by povilasv** [comment]
Because we would end up with 2-3x additional flags for every component. I.e disable metric address, disable http address, disable grpc adress. If we do this only for Query we make this inconsistent and people will expect us to do the same for other components. 

Same thing in Kubernetes, they don't allow you to disable, but you can listen on localhost if you don't need that.
